### ISSUE TITLE
Error:Could not find glide-parent:library:unspecified. Required by: com.github.bumptech.glide:okhttp3-integration:1.4.0

### ISSUE THREAD

**Issue by Jawnnypoo** [bumptech/glide#1003]
Looks like something may have been wrong with the configuration when the okhttp 1.4.0 was released. Right now, I get this error when building:
```
Error:Could not find glide-parent:library:unspecified.
Required by:
    open-meh:app:unspecified > com.github.bumptech.glide:okhttp3-integration:1.4.0
```
This does not occur if I import the regular okhttp integration, or even the volley integration.

Of course a quick workaround is to just add
```
compile ('com.github.bumptech.glide:okhttp3-integration:1.4.0') {
        exclude group: 'glide-parent'
}
```
but obviously that is not an ideal solution since it requires the user to have knowledge of how to exclude dependencies in gradle. I couldn't see anything obviously wrong with the way the okhttp 3.0 integration was set up that would cause this, as it looks very identical build wise as okhttp 2.0. Maybe it has already been sorted out and the dependency just needs to be redeployed. Nonetheless, I thought I would share the issue.

**Comment by TWiStErRob** [comment]
It's was backport issue, see #941.

There are 3 issues already, so if someone searches for the error message they should find these. But agreed, an 1.4.1 release should be done.

**Comment by jemshit** [comment]
If i do 
```compile ('com.github.bumptech.glide:okhttp3-integration:1.4.0') {
        exclude group: 'glide-parent'
}```
it cannot find `OkHttpUrlLoader` ?

**Comment by TWiStErRob** [comment]
@jemshit did you change the imports? `okhttp3` has a new package. Also you may need to run `gradle assembleDebug` once after adding the compile, so the Android Gradle plugin can extract the AAR so AS/IDEA can find the `classes.jar` inside.

**Comment by jemshit** [comment]
i changed to 1.5-snapshot and it is ok
