### ISSUE TITLE
Glide memory cache

### ISSUE THREAD

**Issue by serhii-tiurenko** [bumptech/glide#1004]
I encountered problem with glide memory cache. For some reason on TV application, it can't use it. (event if used with default configurations) As cache didn't works even with default configuration, can this be some platform issue? (maybe problem with some application configurations etc.). By the way, disk cache works fine.

**Comment by TWiStErRob** [comment]
Can you please debug what values [`MemorySizeCalculator` returns](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L177) and check what decisions Glide makes internally: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling ?

It's also possible that your cache keys don't match up, which should be uncovered by the second one.

**Comment by serhii-tiurenko** [comment]
@TWiStErRob  MemorySizeCalculator gives  around 16Mb(16588800) of memory for memory cache. Most images are around 24000 bytes.

Internally glide shows that resources are loaded, wrote from source to cache, then retrieved from cache. Initially it even don't tries to put thumbnails to memory cache (checked logs from LruResourceCache wrapper), only calls remove and then uses disk cache.

Strange thing is, that when I start scroll it sometimes puts thumbnails to memory cache (thumbnails that were on first rows).

**Comment by TWiStErRob** [comment]
24k seems small for an image, is the thumbnail really that small? 24kB jpeg, doesn't mean it takes 24kB in memory cache, see for example these: http://portersbar.com/images/recent_guests.html most of the image if you decode one of these into a Bitmap you'll get 500x375*2 byte = 375kB (this is the default Glide config using 565, but if you use 8888 format you get double size: 750kB. Still 16+MB should be plenty.

The memory cache is filled when the target is cleared (`Glide.clear` or `into(imageView)` for the same view). Can you share you getView/onBindViewHolder code? Maybe you're not reusing list items, in which case nothing will ever get to be in the memory cache.

**Comment by serhii-tiurenko** [comment]
That's it, @TWiStErRob thank you for help. Clear wasn't called for view that not recycled yet(for example if there is not much items in the list). I wonder why this not mentioned in glide docs.

**Comment by TWiStErRob** [comment]
But if you load the same image (with exact dimensions/transformations/etc...) then it should hit the "active resources" which is checked at the same time as memory cache, see `Engine.load`. Even if there are multiple loads for the same image they complete at the same time.

**Comment by TWiStErRob** [comment]
It's possible that your layout works in a way that Glide only picks up the right matching size if the `ImageView` is empty, so having the previously loaded image there changes the dimensions and it's not hitting those caches.

**Comment by serhii-tiurenko** [comment]
@TWiStErRob If I clean target after loading, memory cache works fine, but then glide starts messed up images on scroll. Problem is, I have no possibility to do layout in another way. And if you are right, then I don't understand why view hits memory cache and don't hits active resources cache, if they use same cache key.

**Comment by TWiStErRob** [comment]
Enable the logging and see what the keys and decision are.

If that doesn't help, can you please extract this list and adapter into a separate app and create a consistent repro? Or alternatively just share some code (Glide related parts of adapter, XML) here, this issue has none so far, that's rare :)

**Comment by TWiStErRob** [comment]
Any news on this?

**Comment by serhii-tiurenko** [comment]
Problem solved, because some specifics of our layout we needed to re-engineer it and all work perfect now. Thank you for help.
