### ISSUE TITLE
decoder->decode returned false

### ISSUE THREAD

**Issue by broakenmedia** [bumptech/glide#1005]
Every image in a gridview simply cannot be loaded. Working 10 minutes ago, closed the activity and re-opened.

SkImageDecoder::Factory returned null
SkImageDecoder::Factory returned null
SkImageDecoder::Factory returned null
SkImageDecoder::Factory returned null
decoder->decode returned false
decoder->decode returned false
decoder->decode returned false

Tried clearing app data, re-installing etc.. no dice

**Comment by xbroak** [comment]
Is also exactly the same for all urls across all domains

**Comment by TWiStErRob** [comment]
Wow, that sounds weird, this should be looked into more.
My guess is that the decoder (`Downsampler`) gets invalid sizes from `ViewTarget.SizeDeterminer`.
Can you please change back to that stretchMode and see what sizes and `inSampleSize` are in play?

**Comment by xbroak** [comment]
Hi, Sorry i'm not sure i'll be much help on this! Is there a logging flag i'll need? It's for a client so i fixed and moved on very quickly!

**Comment by TWiStErRob** [comment]
No, I meant a little debugging, but now that you say logging: if you enable [workflow logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) you should get the sizes in the EngineKey part of the log.

**Comment by ycyangchun** [comment]
@xbroak  Hi,Does that make sense ? I also met.

**Comment by sjudd** [comment]
If anyone runs into this again, please file a new issue and attach the image in question. It would also be great to enable verbose Downsampler logging and include the output of that as well:

```
adb shell setprop log.tag.Downsampler VERBOSE
```
