### ISSUE TITLE
How do I preload only images that are not in the cache ?

### ISSUE THREAD

**Issue by osemen-remit** [bumptech/glide#1006]
I'm trying to pre-fetch some images for better performance on some screens with `preload()` method. But I'm not sure if it invalidates items that are already in the cache. I would like topreload these items only if they are not in the cache as I know that image is not changed as long as url is the same but docs does not say anything about this.

Could you please clarify this ?
Thanks.

**Comment by TWiStErRob** [comment]
Which one do you want to preload the original image or the resized image that will be shown?

For SOURCE cache: use `.downloadOnly()`
For RESULT cache: I suggest [`ListPreloader`](https://github.com/bumptech/glide/issues/978)

**Comment by osemen-remit** [comment]
As images might be used in different places it's better to cache original images. But as they might not be bigger than screen I'm scaling then to screen size in order to save some space on disc. But it seems that it does not read preloaded images if thay are scaled to different size than ImageView requires. For instance most of images are 1440x2560 but a lot of devices have 1080x1920 so there is a big overhead by saving raw image. But if I scale it to 1080x1920 and than load it into view 1000x1000 it seems it does not take image from cache.

**Comment by TWiStErRob** [comment]
These sounds really abstract operations, can you please share your Glide snippets?

Note that SOURCE cache doesn't store raw images, it stores the original, and if it's a compressed JPEG, they it stays that way.

Note hat this kind of speculation and size handling is one of the strength of Glide. You just throw stuff at it and it'll make sure it uses the least amount of processor and memory on account of a little disk space. If you have one size use the default RESULT caching; and if you load a single image multiple times in different views, use ALL caching.

**Comment by TWiStErRob** [comment]
Please reopen if you need more help.
