### ISSUE TITLE
Open up animate API

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#1007]
See comment addressed to @sjudd: https://github.com/bumptech/glide/issues/840#issuecomment-167326465

`GenericRequestBuilder.animate(GlideAnimationFactory)` is package private, increase to public so it's easier to do custom animations.

**Comment by TWiStErRob** [comment]
In [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots) it's possible now to write the following:
```java
Glide
	.with(this)
	.load(url)
	.asBitmap()
	.placeholder(R.drawable.placeholder)
	.crossFade() // new
	.into(imageView);
```

It's also much easier to write custom animation because of the published `animate(factory)` method, for example using palette with cross-fade:
```java
.animate(new BitmapContainerCrossFadeFactory<PaletteBitmap>(FADE_DURATION) {
	@Override protected Bitmap getBitmap(PaletteBitmap resource) {
		return resource.bitmap;
	}
})
```

**Comment by rrahul** [comment]
When will we get to use the  3.8.0 stable version?

**Comment by TWiStErRob** [comment]
As soon as it's released ;) No timeline, really.
You can use the snapshot, it should be just as stable because there should be no big features introduced.
