### ISSUE TITLE
How to use UnlimitedDiskCache for Glide as it is done in UIL?

### ISSUE THREAD

**Issue by IskuhiSargsyan** [bumptech/glide#1009]
I need to store images in internal storage as much as free space available ,and as soon as there is no free space,to stop storing images. How to integrate UnlimitedDiskCache as it is done in Universal Image Loader?

**Comment by TWiStErRob** [comment]
1. You'll need to implement Glide's `DiskCache` interface,  
see [`DiskLruCacheWrapper`](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/cache/DiskLruCacheWrapper.java) for an example implementation that wraps the `DiskLruCache` from Jake.  
Based on that you should be able to wrap UIL's `UnlimitedDiskCache`.
 2. [Register custom cache](https://github.com/bumptech/glide/wiki/Configuration#disk-cache)  
  * I suggest to copy the [`build` method from `DiskLruCacheFactory`](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/cache/DiskLruCacheFactory.java#L55)
  * Use a subdirectory of [`context.getCacheDir()`](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/cache/InternalCacheDiskCacheFactory.java#L25) as the directory.

**Comment by TWiStErRob** [comment]
... or you can be lazy and do:
```java
builder.setDiskCache(new InternalCacheDiskCacheFactory(context, Integer.MAX_VALUE));
``
but it has two limitations: it's limited at 2GB and it'll still try to write the file when there's no space, but as far as I can see UIL's implementation does that too.

**Comment by IskuhiSargsyan** [comment]
You mean I should  implement DiskCache, where UnlimitedDiskCache is from UIL ,which extends BaseDiskCache,which in its turn implements DiscCache from UIL?

`public class UnlimitedDiskCacheWrapper implements DiskCache {
    private UnlimitedDiskCache unlimitedDiskCache;
    private static UnlimitedDiskCacheWrapper wrapper = null;


    private final SafeKeyGenerator safeKeyGenerator;
    private final File directory;

    public static synchronized DiskCache get(File directory) {
        // TODO calling twice with different arguments makes it return the cache for the same directory, it's public!
        if (wrapper == null) {
            wrapper = new UnlimitedDiskCacheWrapper(directory);
        }
        return wrapper;
    }

    protected UnlimitedDiskCacheWrapper(File directory) {
        this.directory = directory;
        this.safeKeyGenerator = new SafeKeyGenerator();
    }

    @Override
    public File get(Key key) {
        String safeKey = safeKeyGenerator.getSafeKey(key);
        return unlimitedDiskCache.get(safeKey);
    }

    @Override
    public void put(Key key, Writer writer) {
        String safeKey = safeKeyGenerator.getSafeKey(key);

    }

    @Override
    public void delete(Key key) {

        String safeKey = safeKeyGenerator.getSafeKey(key);
        try {
            unlimitedDiskCache.remove(safeKey);
        } catch (Exception e) {

        }
    }

    @Override
    public void clear() {
        unlimitedDiskCache.clear();
    }
}
`







If the above class is right , how the put() method should be implemented , how it should wrap save() methods of UnlimitedDiskCache class ?
`

	@Override
	public boolean save(String imageUri, InputStream imageStream, IoUtils.CopyListener listener) throws IOException {
		File imageFile = getFile(imageUri);
		File tmpFile = new File(imageFile.getAbsolutePath() + TEMP_IMAGE_POSTFIX);
		boolean loaded = false;
		try {
			OutputStream os = new BufferedOutputStream(new FileOutputStream(tmpFile), bufferSize);
			try {
				loaded = IoUtils.copyStream(imageStream, os, listener, bufferSize);
			} finally {
				IoUtils.closeSilently(os);
			}
		} finally {
			if (loaded && !tmpFile.renameTo(imageFile)) {
				loaded = false;
			}
			if (!loaded) {
				tmpFile.delete();
			}
		}
		return loaded;
	}

	@Override
	public boolean save(String imageUri, Bitmap bitmap) throws IOException {
		File imageFile = getFile(imageUri);
		File tmpFile = new File(imageFile.getAbsolutePath() + TEMP_IMAGE_POSTFIX);
		OutputStream os = new BufferedOutputStream(new FileOutputStream(tmpFile), bufferSize);
		boolean savedSuccessfully = false;
		try {
			savedSuccessfully = bitmap.compress(compressFormat, compressQuality, os);
		} finally {
			IoUtils.closeSilently(os);
			if (savedSuccessfully && !tmpFile.renameTo(imageFile)) {
				savedSuccessfully = false;
			}
			if (!savedSuccessfully) {
				tmpFile.delete();
			}
		}
		bitmap.recycle();
		return savedSuccessfully;
	}`

**Comment by TWiStErRob** [comment]
> You mean I should implement DiskCache, where UnlimitedDiskCache is from UIL ,which extends BaseDiskCache,which in its turn implements DiscCache from UIL?

Yes, it sounds funny when you say it like that, but you said you wanted to use that class. Note the [alternative](https://github.com/bumptech/glide/issues/1009#issuecomment-189703375) though, or is the 2GB too small?

> how it should wrap save()

You can forget about using `save(String imageUri, Bitmap bitmap)`, because the disk cache in Glide doesn't know about the UI representation (as it supposed to), also Glide can load stuff other than Bitmaps too, so it wouldn't make sense to specialize.

On second look, seeing the incompatibilities of the two interfaces (`UnlimitedDiskCache` cannot fullfill `Writer.write(File)`) it's probably much easier to just copy the code (the relevant part of UDC is less than 100 lines) and modify them so they fit into Glide, something like:
```java
public void put(Key key, Writer writer) {
    String safeKey = safeKeyGenerator.getSafeKey(key);
    File imageFile = getFile(safeKey);
    File tmpFile = new File(imageFile.getAbsolutePath() + TEMP_IMAGE_POSTFIX);
    boolean loaded = writer.write(tmpFile);
    if (loaded && !tmpFile.renameTo(imageFile)) {
        loaded = false;
    }
    if (!loaded) {
        tmpFile.delete();
    }
}
```

`get(String imageUri)` would have been a good candidate, but the `loaded` logic needs to be done by someone too. Another good thing about this is that you don't have to have the UIL dependency just for one class.

**Comment by IskuhiSargsyan** [comment]
Thanks, I will try.
I used Glide in standard way, without extending GlideModule and run the below  code, and I want to find stored file in internal storage, but there is no folder with package name in
 Internal Storage/Android/data/
`  String internetUrl = "http://i.imgur.com/DvpvklR.png";
        Glide
                .with(getApplicationContext()) // could be an issue!
                .load(internetUrl)
                .into(imageView);`

**Comment by TWiStErRob** [comment]
Internal storage in Glide means internal to the system, that is not visible to the user (unless rooted), like where the sqlite DB is stored. Depending on your device/file browser app it is possible that their "internal storage" naming refers to the emulated `/sdcard`, which is internal (as in non-removable) as opposed to the external physical sd card slot. In developer terminology I think everything is external that is not on the system partition.
Also the cache is only written once the image is visible, so if the load failed there'll be no file.

**Comment by IskuhiSargsyan** [comment]
Thanks TWiStErRob .
