### ISSUE TITLE
strange reload into RecyclerView with StaggeredGridLayoutManager

### ISSUE THREAD

**Issue by IamEgor** [bumptech/glide#1010]
Hello.
I'm trying to load images with Glide into RecyclerView with StaggeredGridLayoutManager.
And it loads absolutely fine first time, but when I scroll up and down, it changes image size, cropping them to neighbour size.
Normal :
![device-2016-02-28-210800](https://cloud.githubusercontent.com/assets/7051238/13381034/4b446024-de62-11e5-9a79-ed9cb9fd83c7.png)
Strange :
![device-2016-02-28-212804](https://cloud.githubusercontent.com/assets/7051238/13381033/4b445750-de62-11e5-97d2-a07c56d1da3e.png)

**Comment by wsw87201326** [comment]
yeah,i have the same problem when i use it...
it change the size and not match the view,when i Scroll ,they change

**Comment by TWiStErRob** [comment]
See #864, if that or my linked project doesn't help please include the Glide load line and XML here.
