### ISSUE TITLE
How to extract palette properly?

### ISSUE THREAD

**Issue by FastDr1v3r** [bumptech/glide#1013]
The way I extract the palette color from an image loaded and cached with Glide is this:

```java
Glide.with(yourFragment)
    .load(yourUrl)
    .asBitmap()
    .into(new BitmapImageViewTarget(yourImageView)) {
        @Override
        public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
            super.onResourceReady(bitmap, anim);
            Palette.generateAsync(bitmap, new Palette.PaletteAsyncListener() {  
                @Override
                public void onGenerated(Palette palette) {
                    // Here's your generated palette
                }
            });
        }
    });
```

But on the same page of the example it says:

>Although this is a great simple example, in general I wouldn't recommend generate Palettes this way. Instead checkout Glide's ResourceTranscoder Interface and .transcode () method and consider returning a custom resource containing both your Bitmap and Palette generated on a background thread.

But I don't know how to use ResourceTranscoder Interface or how to implement it in my code to extract the Palette the right way and why using ResourceTranscoder Interface is better than the above code. Can someone explain me why to use this method and also a simple example of extracting Palette this way?
Thanks in advance!

**Comment by TWiStErRob** [comment]
This came up way too many times so I decided to update the wiki page with an example:
https://github.com/bumptech/glide/wiki/Custom-targets#palette-example
Please give it a go and report any issue with it (I didn't test it).

**Comment by FastDr1v3r** [comment]
I will come with a feedback for the code when I get home and test it on my computer. Thank you!

**Comment by i-m-aman** [comment]
And I am loading SVGs which is using PictureDrawable. Wouldn't that be a problem and I am using Glide v4
