### ISSUE TITLE
How to clear cache of a specific url?

### ISSUE THREAD

**Issue by blindfate** [bumptech/glide#1018]
Hi, two question about glide.
1、How to clear cache of a specific url?
clearDiskCache() and clearMemory() will chear all cache, but this is not what I want?
2、How to get bitmap?

**Comment by TWiStErRob** [comment]
1. This has been answered so many times (best duplicate is #624):  
https://www.google.com/search?btnG=1&q=glide+How+to+clear+cache+of+a+specific+url%3F
2. It depends on what do you want to do with the Bitmap, similarly to the above:  
https://www.google.com/search?btnG=1&q=glide+How+to+get+bitmap%3F
 * `.asBitmap().into(imageView)` will force everything to be loaded as a Bitmap (disables GIF)
 * `.asBitmap().into(w,h).get()` will load the Bitmap object synchronously with the specified size
 * `.asBitmap().into(new SimpleTarget<Bitmap>(w,h) {...})` will load async, but won't display it

**Comment by blindfate** [comment]
@TWiStErRob Thanks a lot.
