### ISSUE TITLE
Loading image as Gif into CircularImageView loads still image

### ISSUE THREAD

**Issue by WanClem** [bumptech/glide#1019]
Hey guys,thumbs up for glide,its really awesome.However,I tried loading a gif image into CircularImageView in android via Glide but glide loads a still bitmap into CircularImageView,the gif is not animating...What do I do?.Thanks.

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide#compatibility

Try to use Circle transformation and a normal ImageView.

**Comment by WanClem** [comment]
Ok,thanks.Pls don't be offended,can you provide a snippet on how to perform Circle transformation into  normal imageview,can't get it right over here.Thanks

**Comment by TWiStErRob** [comment]
It should be as simple as:
```java
Glide.with(this).load(gifUrl)
.diskCacheStrategy(SOURCE)
.transform(new CircleCrop(context)) // or bitmapTransform, whichever compiles
.into(imageView)
```
Let me know if it works.

**Comment by WanClem** [comment]
Nah,none worked,coz CropCircleTransformation doesn't implement GifDrawable Transformation but rather Bitmap Transformation....Am stucked right now...

I tried `Glide.with(MainActivity.this).load(userPhoto).asGif().transform(new CropCircleTransformation(MainActivity.this)).crossFade().into(currentlySignedInUserProfileImageView);`

and I keep getting a red error line at  `asGif().transform(new CropCircleTransformation(MainActivity.this)) `

**Comment by TWiStErRob** [comment]
For me these both compile:
```java
load(...).transform(new CenterCrop(context))
load(...).asGif().transformFrame(new CenterCrop(context))
```

**Comment by TWiStErRob** [comment]
Another way would be
```java

```

**Comment by WanClem** [comment]
Both compiles but there is no such object as `new CircleCrop(context)` I want the gif drawable to load inside a CircleTransformation

**Comment by TWiStErRob** [comment]
I assumed you have a transformation at hand already, it doesn't matter what's it called. The GifDrawable loads each frame and applies the transformation. CircleCrop is in Glide v4, but you can just search for a transformation, I think there are two links at the compatibility section in the readme.

**Comment by WanClem** [comment]
v4??,can't get the dependency for v4..to enable CircleCrop,nonetheless I will see if I can get a work around with my current v3.7 and tweak CircleImageView a little to see if it would work.

**Comment by TWiStErRob** [comment]
Let's start again, sorry if it wasn't clear the first itme.

1. `CircleImageView` (or similar other incarnations) cannot display Gifs because they project the Drawable onto a Bitmap as soon as they get ahold of it, and when a Drawable that changes over time will be only projected once. See https://github.com/bumptech/glide#compatibility

2. At Compatibility there's a link to https://github.com/wasabeef/glide-transformations which if you add as dependency gives you a class named `CropCircleTransformation`

3. These are the different ways to use **any transformation** (regardless of name or source, here depicted with our just-imported class as an example) with Gifs:

    ```java
    load(...).transform(new CropCircleTransformation(context))
    load(...).asGif().transformFrame(new CropCircleTransformation(context))
    load(...).asGif().transform(new GifDrawableTransformation(new CropCircleTransformation(context), pool))
    ```

+1: To obtain a pre-release version of v4 that has a built-in version of `CircleCrop` read https://github.com/bumptech/glide/wiki/Snapshots, but the APIs change and it may be harder to use because it's not that widespread yet.

**Comment by WanClem** [comment]
OMG! I got it working now.Thank you very much for being helpful...THUMBS UP GLIDE!!!!!!!!!!

**Comment by GauravSharma531** [comment]
wanClem can you post your code snippet. I am using as below what i am doing wrong?

`Glide.with(baseActivity)
                        .load(imageUrl)
                        .asGif().transformFrame(new CropCircleTransformation(baseActivity))
                        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                        .into(image);`

**Comment by GauravSharma531** [comment]
i tried that also `Glide.with(baseActivity)
                        .load(imageUrl)
                        .asGif().transform(new GifDrawableTransformation(new CenterCrop(baseActivity), Glide.get(baseActivity).getBitmapPool()))
                        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                        .into(image);`

this also don't work for me.

**Comment by WanClem** [comment]
Ok,here is the snippet I had as a work around

CropCircleTransformation cropCircleTransformation = new CropCircleTransformaion();
BitmapPool bitmapPool = new LruCacheBitmapPool(10*1024*1024);

Glide.with(context).load(imageUrl).asGif().transform(new GifDrawableTransformation(cropCircleTransformation ,bitmapPool)).crossFade().into(image);

Try the above snippet.

**Comment by GauravSharma531** [comment]
Thanks for reply but it give error in first two line
```
CropCircleTransformation cropCircleTransformation = new CropCircleTransformaion();
BitmapPool bitmapPool = new LruCacheBitmapPool(10*1024*1024);

```change first line to 
`CropCircleTransformation cropCircleTransformation = new CropCircleTransformation(baseActivity);`

but still not able to resolve LruCacheBitmapPool .

**Comment by WanClem** [comment]
Oh sorry,Typo,,,not LruCacheBitmapPool rather ` LruBitmapPool(int sizeOfChoice);`

**Comment by GauravSharma531** [comment]
```
CropCircleTransformation cropCircleTransformation = new CropCircleTransformation(baseActivity);
                BitmapPool bitmapPool = new LruBitmapPool(10*1024*1024); //new LruCacheBitmapPool(10*1024*1024);

                Glide.with(baseActivity).load(imageUrl).
                        asGif().transform(new GifDrawableTransformation(cropCircleTransformation ,bitmapPool))
                        .crossFade().into(image);
```

still it is not working showing a blank image with circular image view for normal image its working.

**Comment by WanClem** [comment]
Honestly,I noticed the slow image load times in Glide,it sometimes take up to 5mins to get the image rendered on Screen,which I think the Authors of Glide need to look into....Have you tried loading the gif url into a normal imageview without no transformation and confirmed that it loads and animates?

**Comment by GauravSharma531** [comment]
i m using gif image for normal imageview it is loading and animated but here these gif image i want to load in a circular view where it is not loading.

**Comment by WanClem** [comment]
That's unsual...I used exact same code above and gif is loading in cropCircleTransformation..Try and review your code again......

**Comment by TWiStErRob** [comment]
#358 has explanation and links why GIF loading is slow. If it's slow even with SOURCE caching, then it's probably huge files or slow servers which no library can fix.

Usually the first thing you do when "it's not loading" is to go through these and check why: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

Please, please do not use new bitmap pools, if a constructor needs a pool, use `Glide.get(context).getBitmapPool()`, but honestly I don't even know why you opt for the most complicated loads line, the first option (without asGiF) is equivalent, and more flexible (it won't fail if the URL is accidentally a JPEG with GIF extension and circlecrop that too).

**Comment by WanClem** [comment]
Oh,thanks noted

**Comment by GauravSharma531** [comment]
Hi TWiStErRob ,

Thanks for your suggestion it works now but after transformation image is not animating with circular image view.

**Comment by TWiStErRob** [comment]
The whole point of transforming the frames with circular crop is to have an image that is already circular so you can use the stock `ImageView`.

**Comment by cantalou** [comment]
Hi all,
`Glide.with(activity)
    .load(imageUrl)
    .asGif().transformFrame(new CropCircleTransformation(activity))
    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
    .into(image);`
I try this code and it works if it`s a gif .But if i change to png or jpg , it will load fail. How to revise the code?

**Comment by TWiStErRob** [comment]
Remove `asGif` and change `transformFrame` to `transform`. There are several equivalent ways to do this, I showed 3 above, &lt;insert last paragraph from https://github.com/bumptech/glide/issues/1019#issuecomment-191698351 here&gt;

**Comment by cantalou** [comment]
Thanks for reply .
My app info glide v3.7.0 , android 4.4.4
I change my code to
`Glide.with(activity) .load(imageUrl) .transform(new CropCircleTransformation(activity)) .diskCacheStrategy(DiskCacheStrategy.SOURCE) .into(image);`
CropCircleTransformation.java code which copy from [https://github.com/wasabeef/glide-transformations/blob/master/transformations/src/main/java/jp/wasabeef/glide/transformations/CropCircleTransformation.java](url)
` @Override
    public Resource<Bitmap> transform(Resource<Bitmap> resource, int outWidth, int outHeight)
    {
        Bitmap source = resource.get();
        int size = Math.min(source.getWidth(), source.getHeight());

        int width = (source.getWidth() - size) / 2;
        int height = (source.getHeight() - size) / 2;

        Bitmap bitmap = mBitmapPool.get(size, size, source.getConfig());
        if (bitmap == null)
        {
            bitmap = Bitmap.createBitmap(size, size, source.getConfig());
        }

        Canvas canvas = new Canvas(bitmap);

        BitmapShader shader = new BitmapShader(source, BitmapShader.TileMode.CLAMP, BitmapShader.TileMode.CLAMP);
        if (width != 0 || height != 0)
        {
            // source isn't square, move viewport to center
            Matrix matrix = new Matrix();
            matrix.setTranslate(-width, -height);
            shader.setLocalMatrix(matrix);
        }
        paint.setShader(shader);
        paint.setAntiAlias(true);

        float r = size / 2f;

        canvas.drawCircle(r, r, r - borderWidth / 2, paint);

        return BitmapResource.obtain(bitmap, mBitmapPool);
    }`
But I receive the below error ,
`java.lang.ClassCastException: com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapper cannot be cast to android.graphics.Bitmap
`
It looks like I pass the wrong transformation type?

**Comment by TWiStErRob** [comment]
Aaaaaah, @wasabeef used `Transformation<Bitmap>` instead of `BitmapTransformation` for some reason, so it won't work in this context, you'll need `.asBitmap()` to use that class. This is told to you by the unchecked warning you ignored.

Try this one instead http://stackoverflow.com/a/25806229/253468 or modify the one you copied to extend `BitmapTransformation`, it should be a really quick fix.

**Comment by cantalou** [comment]
Thanks @TWiStErRob 
Everything works fine after I use `bitmapTransform` instead of `transform`, Here is all my code, it might help if someone want to supports all types of images to be crop

` Glide.with(context)
                 .load(url)
                 .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                 .bitmapTransform(new CropCircleTransformation(context))
                 .error(error)
                 .placeholder(placeHolder)
                 .into(target);`

**Comment by Pynop** [comment]
Using v4, just wanted to share:
circleCrop() wasn't working for me and I was wondering why. Finally I've found out that apply(RequestOptions.fitCenterTransform()) was the reason. When I deleted the method call my GIFs started cropping in circles.

**Comment by Phinatic** [comment]
@TWiStErRob What is the memory impact of using CircleCrop on a GifDrawable in Glide 4? Memory consumption appears to grow rapidly as the gif animates. Is it eventually released/reused?
