### ISSUE TITLE
How to set decoder only for some images

### ISSUE THREAD

**Issue by ashwanikumar04** [bumptech/glide#1020]
Hello:
This is more of a question than issue.
Glide allows to change the default Decode format to AGRB using following module
```
public class GlideConfiguration implements GlideModule {
 
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // Apply options to the builder here.
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
    }
 
    @Override
    public void registerComponents(Context context, Glide glide) {
        // register ModelLoaders here.
    }
}
```

However this changes the decoding format for all the images.

Is there anyway, I can change decoding format for some images to ARGB and for all others I want the default behaviour.
Thanks

**Comment by TWiStErRob** [comment]
`.asBitmap().format()` lik #865
