### ISSUE TITLE
Not hitting disk cache

### ISSUE THREAD

**Issue by eicm** [bumptech/glide#1022]
This is my load lines:
```java
public void populateViewHolder(RecyclerView.ViewHolder viewHolder, final int position) {
    int[] requestedSize = getMediaLoadSize(data.get(position), 1);
    data.get(position)
            .getMediaRequestBuilder(requestManager, requestedSize)
            .thumbnail(data.get(position).getThumbRequestBuilder(requestManager, requestedSize))
            .crossFade()
            .into(((AlbumGridViewHolder) viewHolder).imageView);
}
```

```java
public DrawableRequestBuilder getMediaRequestBuilder(RequestManager requestManager, final int[] requestedSize) {
    return requestManager.loadFromMediaStore(Uri.parse(mediaPath)).dontTransform().listener(new RequestListener<Uri, GlideDrawable>() {
            @Override
            public boolean onException(Exception e, Uri model, Target<GlideDrawable> target, boolean isFirstResource) {
                return false;
            }

            @Override
            public boolean onResourceReady(GlideDrawable resource, Uri model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                Timber.d(mediaPath + ": isFirstResource: " + isFirstResource + ", isFromCache: " + isFromMemoryCache + ", size: " + requestedSize[0] +" x "+ requestedSize[1] );
                return false;
            }
        }).diskCacheStrategy(DiskCacheStrategy.RESULT).override(requestedSize[0], requestedSize[1]);
}
```

```java
public DrawableRequestBuilder getThumbRequestBuilder(RequestManager requestManager, int[] requestedSize) {
    if(requestedSize[0] < 512 && requestedSize[1] < 384) {
        return null;
    } else {
        return requestManager.loadFromMediaStore(Uri.parse(mediaPath)).skipMemoryCache(false).diskCacheStrategy(DiskCacheStrategy.RESULT).dontTransform().override(512, 384);
    }
}
```

When I scroll over the list enough to remove items from memory cache and come back to the top again, glide doesn't hit the disk cache and starts to load thumbnail and then the image again.

**Comment by TWiStErRob** [comment]
Nothing stands out, except that magic constant (1).
Did you try checking what Glide does behind the scenes?
https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow
Compare the key of a single position on first display and when you scroll back to it the second time and expect to hit the cache.

**Comment by eicm** [comment]
@TWiStErRob That constant number is to force glide to load media store thumbnail if it exist for thumbnail load independent from the size load is requesting.

**Comment by eicm** [comment]
@TWiStErRob here's the log for few scrolls for mediaId 69490, I didn't notice anything wrong:

`03-02 10:29:54.839  1666  2051 V DecodeJob: Decoded transformed from cache in 84.61770899999999, key: EngineKey{content://media/external/images/media/69490+com.bumptech.glide.signature.EmptySignature@11b74c9+[540x540]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
03-02 10:29:54.839  1666  2051 V DecodeJob: Transcoded transformed from cache in 0.035313, key: EngineKey{content://media/external/images/media/69490+com.bumptech.glide.signature.EmptySignature@11b74c9+[540x540]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}




03-02 10:30:47.538  1666  2051 V DecodeJob: Decoded transformed from cache in 85.43229099999999, key: EngineKey{content://media/external/images/media/69490+com.bumptech.glide.signature.EmptySignature@11b74c9+[540x540]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
03-02 10:30:47.538  1666  2051 V DecodeJob: Transcoded transformed from cache in 0.609219, key: EngineKey{content://media/external/images/media/69490+com.bumptech.glide.signature.EmptySignature@11b74c9+[540x540]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}



03-02 10:35:00.394  2975  3096 V DecodeJob: Decoded transformed from cache in 75.81286399999999, key: EngineKey{content://media/external/images/media/69490+com.bumptech.glide.signature.EmptySignature@66bc57b+[540x540]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
03-02 10:35:00.394  2975  3096 V DecodeJob: Transcoded transformed from cache in 0.030052, key: EngineKey{content://media/external/images/media/69490+com.bumptech.glide.signature.EmptySignature@66bc57b+[540x540]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
`

**Comment by TWiStErRob** [comment]
So where is this not hitting the disk cache? All 3 of these are using RESULT cache.

**Comment by eicm** [comment]
@TWiStErRob I thought it's not hitting the cache because I still see the load of the thumbnail first and then the crossfade transition to the image load which I'm not expecting to see when the result is cached. One other question I have is, does the dontTransform() has any effect in using DiskCacheStrategy.RESULT. I'm using the dontTransform() because though the images and thumbnails have the same aspect ration when glide use its transformation (centerCrop) then there's a scaling jump between the transition.

**Comment by TWiStErRob** [comment]
`dontTransform` is just like any other transformation. RESULT cache contains the final transformed Bitmap encoded as a File. The thumbnails you see are because the thumb loads are higher priority and even if they weren't, just think about this: you start the full and thumb load the the same time, the thumb is significantly smaller (at least 4x), so it should load much faster. Glide displays the first resource available.

**Comment by eicm** [comment]
When I use dontTransform but I have centerCrop set in the ImageView, glide caches the image down sampled to the size passed in override(w, h), and let's ImageView handles the scaleType in load right?

**Comment by TWiStErRob** [comment]
Yep, but the downsampling may not be as accurate as you think (compared to fitCenter/centerCrop), because of 2s powers. I think the situation is better on newer phones though. You can hack the Bitmap out from the Drawable and log the size in the listener, that's the best way to see what's cached, or set the disk cache to external and browse the files.

**Comment by eicm** [comment]
I want to put the centerCrop() transform in the glide load to result in caching smaller images but when I add centerCrop to thumbnail load and also to image load, then I see scaling jump between the thumbnail image loaded and actual image loaded; while I dont see that jump if I add the scaleType centerCrop to the ImageView and add dontTransform to both of the glide load lines (thumbnail and image). Any idea on this?

**Comment by TWiStErRob** [comment]
How big is the jump, just a few pixels or significant?

**Comment by TWiStErRob** [comment]
Also what's the layout?

**Comment by eicm** [comment]
It's significant. layout is simple, this is the layout:

`<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/parent_album_view_item"
    android:layout_width="match_parent"
    android:layout_height="@dimen/staggered_grid_items_portrait_height">

    <ImageView
        android:id="@+id/imageview_fragment_gridview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@drawable/bg_dark_grey"
        android:scaleType="centerCrop" />

    <ImageView
        android:id="@+id/imageview_fragment_gridview_video_icon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:layout_margin="10dp"
        android:background="@drawable/ic_video_type"
        android:scaleType="centerCrop" />

    <TextView
        android:id="@+id/textview_fragment_gridview_video_duration"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="10dp"
        android:textColor="@color/white"
        tools:text="00:54" />

    <ImageView
        android:id="@+id/imageview_fragment_gridview_selection_indicator"
        android:layout_width="38dp"
        android:layout_height="38dp"
        android:layout_gravity="center"
        android:visibility="gone" />

    <ImageView
        android:id="@+id/imageview_album_gallery_fav_icon"
        android:layout_width="35dp"
        android:layout_height="35dp"
        android:layout_gravity="end"
        android:layout_margin="10dp"
        android:src="@drawable/ic_like"
        android:visibility="gone" />

</FrameLayout>`

I think the issue happens because the down sampled center cropped image and thumbnail don't keep the same aspect ratio any more when glide uses center crop transformation

**Comment by eicm** [comment]
@TWiStErRob do you want me to write a sample app to demonstrating it?

**Comment by TWiStErRob** [comment]
I played around a little. This is what I managed to put together based on your above comments:
```xml
<ImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerCrop"
    />
```
```java
String url = "http://placehold.it/3000x2000/AAFF00/000000&text=IMAGE";
Glide
        .with(this)
        .load(url)
        .override(540, 540)
        .dontTransform()/.centerCrop()
        .thumbnail(Glide
                .with(this)
                .load(url)
                .override(512, 384)
                .dontTransform()/.centerCrop()
        )
        .into(imageView)
;
```

Here are the loaded images:

|Transformation|Original|Thumb|Full|
|--------------|--------|-----|----|
|dontTransform|3000x2000|750x500|1500x1000|
|centerCrop|3000x2000|512x384|540x540|

Notice that with `.dontTransform` the aspect ratio of each image is the same, the decrease in size is based on `inSampleSize`.
With `.centerCrop` you get exact sizing (the one you requested with `.override`) so the ratios are different. It looks like you're affected by #363.

You have to match up those ratios if you want to use thumbnail, there are two ways to do this:
 1. `int width = 512, height = (int)((float)width / requestedSize[0] * requestedSize[1]);` and use these values in `getThumbRequestBuilder`'s `.override`.
 2. Remove all `.override()`/`.centerCrop()`/`.dontTransform()` and let Glide do it's job of determining the best size:  
  * centerCrop will be picked up from XML
  * the height will be constrained by `staggered_grid_items_portrait_height`
  * the width will be constrained by grid layout item width
  * the thumbnail can be made smaller by `.sizeMultiplier(.3f)` or if you know want an image around ???x384:
    `.sizeMultiplier(Math.min(1, 384f / getResources().getDimensionPixelSize(R.dimen.staggered_grid_items_portrait_height)))`

I highly suggest you go for the 2nd option.

**Comment by eicm** [comment]
@TWiSterRob That was my guess for what is happening, I thought glide implements the same transformation logic that ImageView scaleType does, as the image view keeps the aspect ratio when you set the scaleType to centerCrop. 
There are two reasons I use override:
1- I've notice in a lot of issue tickets here it's been suggested to use override to fix glide loading.
2- I have pinch to zoom on the grid to change number of columns and I don't want to load a new image for each zoom level (I group several zoom level in one category to reuse cached images)

**Comment by TWiStErRob** [comment]
Glide does implement the same logic, the difference is the size: your ImageView has a different size than what you request with override. CenterCrop depends on size a lot, if you change the input you get a different output... also a center crop transformation cannot possibly keep any aspect ratio by definition because it is cropping (removing) the top-bottom or left-right of the image to match the target size.

1- That's only relevant if you have an issue, `.override` is bad in general, because you hard-code sizes that Glide would handle much better. The usage of `override` is really of "it depends" type, mostly when there's an interaction needed between different loads.
2- That's a bigger problem... then you must calculate the size manually (and i'm already suggesting to use override... ;) like I said in the first option to have an aspect ratio match.

**Comment by eicm** [comment]
Thanks for clarifying :)
