### ISSUE TITLE
it feels the thread is blocked when one image can't load successfully

### ISSUE THREAD

**Issue by AnswerZhao** [bumptech/glide#1025]
it's a amazing library. But one trouble is confusing me. In the listview, when one image can't load, the images in the below items also can't load . Only when the blocked image is load successfully , the below items can load. it seems like the thread is blocking. How can i resolve it?  Thanks.

**Comment by TWiStErRob** [comment]
Android, by nature is resource limited and that resource is battery and connectivity. Glide makes an effort to accommodate this by using only a reasonable amount of threads to process loads.

Read #925 up to the point where it's closed.
