### ISSUE TITLE
GIFs keep playing after switching to other Fragment in a ViewPager

### ISSUE THREAD

**Issue by edrobap** [bumptech/glide#1028]
I have a ViewPager with 3 fragments. Fragment1 has a RecyclerView that plays GIFs. The problem is when I switch to Fragment 2, GIFs in Fragment1 keep playing. Is there way to stop these GIFs from playing? I want to stop them because when a GIF plays, it consumes ~40% CPU  [https://github.com/bumptech/glide/issues/1029] which ends up in lots of battery drainage even if user is not viewing Fragment1.

**Comment by TWiStErRob** [comment]
ViewPager keeps off-screen Fragments in memory in case you go back to them, you can `Glide.clear` the ImageView at the appropriate event in the ViewPager or decrease the off-screen limit to 0.

**Comment by edrobap** [comment]
Thanks. `Glide.clear` solves my problem of unnecessary CPU consumption. But it is also clearing the resources. That means I need to do a `Glide.load` to load the resources again. Isn't there a way where I can just start / stop the GIF?

**Comment by TWiStErRob** [comment]
Loading a just-used resource should be immediate (from memory cache), and the clear-load pattern works with any type of image, not just GIFs.

If you really want to start/stop: `imageView.getDrawable() instanceof Animatable`.

**Comment by edrobap** [comment]
I did't get your start/stop suggestion. Could you please elaborate?

**Comment by TWiStErRob** [comment]
```java
Drawable drawable = imageView.getDrawable();
if (drawable instanceof Animatable) {
    Animatable gif = (Animatable)drawable;
    if (gif.isRunning()) gif.stop() else gif.start();
}
```

**Comment by edrobap** [comment]
Got it. Thanks.
