### ISSUE TITLE
High CPU usage when playing GIFs

### ISSUE THREAD

**Issue by edrobap** [bumptech/glide#1029]
I am displaying GIFs in a RecyclerView. Code:

```java
Glide.with(acitivity)
    .load(url)
    .placeholder(R.drawable.image_placeholder)
    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
    .listener(listener)
    .into(viewHolder.imageView);
```

If I keep the Fragment containing this RecyclerView open, very high amount of CPU (~40%) is used by the app. And the phone heats up if I use the Fragment for 1-2 minutes. Is it normal for GIFs? Am I doing anything wrong here?

**Comment by TWiStErRob** [comment]
You're saying you're displaying a list of images that are animated, I think it's normal to use some CPU power this case, especially if you have a GridLayoutManager. Glide decodes frames on the fly and this way it saves a lot of memory and also reuses the frames so no need for constant GC-ing.

If you were to pre-load all Bitmaps of all frames (spike in CPU) and then use those memory-cached frames (low CPU) you would likely run into OOM. Consider displaying static images (`.asBitmap()`) and play the GIF animation on tap (reload same model into same image but without `asBitmap`.

Alternatively stop playing GIFs after 10 seconds of no user interaction by doing setting a flag on the adapter (that the user didn't move) and calling `notifyDataSetChanged` and use `asBitmap` is the flag is on.

**Comment by edrobap** [comment]
I checked with LinearLayoutManager and 2 GIFs visible at a time the CPU usage is 30-40%. With GridLayoutManager and 10 GIFs visible (skips lot of frames but that okay) at a time it is 60-70%.

I like your suggestion of playing GIF on tap and stop playing after some timeout. Should save some battery. Thanks

**Comment by TWiStErRob** [comment]
This is really a game of compromise, CPU/battery or memory... both are scarce resources in Android.

You should be able to call `setLoopCount` on `GlideDrawable/GifDrawable` so it only plays a few times, instead of counting seconds, use `.into(new GlideDrawableImageViewTarget(imageView, 3))` to repeat 3 times, note that as a side effect you'll need to explicitly add `.centerCrop()` or `.fitCenter()`.

**Comment by edrobap** [comment]
Thanks a lot helpful suggestions.
