### ISSUE TITLE
RoundedCorners transformation

### ISSUE THREAD

**Issue by sophiataskova** [bumptech/glide#1030]
It looks like the file RoundedCorners.java is in the com.bumptech.glide.load.resource.bitmap package in the repo, but I don't seem to get it when I import the library with gradle. Should it be available in there, or is it my Android Studio being funny?

Thanks in advance!

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide#status so you either use the snapshot of the unreleased v4 or there's a third party library: https://github.com/wasabeef/glide-transformations or of course you can copy the class until it's not released.
