### ISSUE TITLE
New images are failing to load

### ISSUE THREAD

**Issue by Saketme** [bumptech/glide#1031]
I'm facing a weird issue where Glide is failing to load photos. I have a list of conversations which shows contact photos. Now when a **new** photo is assigned to any contact, Glide often fails to load them when the app starts. It is only able to load them after multiple adapter data-set refreshes.

Adding a listener outputs the following inside the `onException` method:

````
onException(null, content://com.android.contacts/display_photo/10, Target for: com.tattva.app.FABulousSimple{78af96a VFED..CL. ........ 32,32-128,128 #7f0e01b6 app:id/list_item_chat_photo}, true)
````

Any ideas what could be going wrong? This is only happening with list items and not when used elsewhere.

I also tried setting a signature in case this is a cache issue, but it didn't help either.

**Comment by TWiStErRob** [comment]
Try to figure out what leads to that null exception by enabling all internal logging: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#more-logging
`null` exception can mean the model is null (which is not), or there's something funny going on with the decoder (don't remember the exact case).

**Comment by TWiStErRob** [comment]
Found it: the SOURCE cache couldn't write the data: https://github.com/bumptech/glide/issues/986#issuecomment-185929949, but the best is still to se why yours is not loading, it may be different. What's your Glide line?

**Comment by Saketme** [comment]
Hi, here's the full log: 

https://gist.github.com/Saketme/79d8d1213c869e4608f8

The photo Uri that is failing to load:

`content://com.android.contacts/display_photo/10`

Glide lines:

```java
Glide.with(getActivity())
            .load(getPhotoUri(conversation))
            .signature(new StringSignature(signatureKey))
            .centerCrop()
            .crossFade()
            .diskCacheStrategy(DiskCacheStrategy.ALL)
            .into(new ImageViewTarget<GlideDrawable>(holder.chatPhoto) {
                 @Override
                 public void onLoadFailed(Exception e, Drawable errorDrawable) {
                     holder.chatPhoto.setImageDrawable(getThumbnail(conversationName));
                 }

                 @Override
                 protected void setResource(GlideDrawable resource) {
                     holder.chatPhoto.setImageDrawable(resource);
                 }
});
```

Useful enough?

**Comment by TWiStErRob** [comment]
To disable do the same as you did to enable, just use `ERROR`.

The log ordering is really weird, the states don't happen in order, can you include the thread and timestamp columns as well? I can see that it's trying to load two version of that photo 96x96 and 160x160 one with and one without a signature! All the "load failed" log lines should have an exception stack trace...

The only possible way to get a null exception without even seeing a stack trace in the logs is if both `resource` and `exception` is null in `EngineRunnable.run`, which can only happen if `decode()` returns null. You should explore that code and put breakpoints onto return statements and variable assignments to see at which point does it get null. Or you could put a conditional breakpoint on `resource = decode()` with the condition `decodeJob.resultKey.id.equals("your url here")`. Sorry, I can't go deeper without a reproducible sample.

**Comment by Saketme** [comment]
Sorry for the logs, the were probably getting messed up due to multiple dataset update calls while the app is starting. I managed to reproduce the error again with cleaner logs:

https://gist.github.com/Saketme/806817758506b3514105

Do you see anything strange here? Or should I go ahead and debug `EngineRunnable` with breakpoints?

**Comment by TWiStErRob** [comment]
It looks like it's trying to use the cache but getting back null. "DecodeJob: Transformed/Transcoded" log lines don't really mean anything because they're printed even if the resource is null. Try debugging, that's where you can find the root cause.

**Comment by TWiStErRob** [comment]
Did you find the cause?

**Comment by Saketme** [comment]
No I couldn't manage to get time for this. A lot has been going in life. But I do plan to debug this soon. Do you want me to close this issue until then?

**Comment by TWiStErRob** [comment]
It's ok, we can leave it open, I was just cleaning up dead threads.

**Comment by RajeshBatth** [comment]
I'm also getting this error, sometimes the same image gets loaded in one view and doesn't load in another activity. I saw the log, it was showing 
` java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{88fcd8d 20879:com.comp.myapp/u0a198} (pid=20879, uid=10198) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS`

**Comment by TWiStErRob** [comment]
Do you have that permission? Is that other activity maybe in a different app that doesn't have the permission?

**Comment by RajeshBatth** [comment]
the activity is in same app. I did not add the permission

**Comment by RajeshBatth** [comment]
How come it loads the image in one view and not in other?

**Comment by TWiStErRob** [comment]
Maybe it's a temporary permission then. Do you load exactly the same way? If you pick something from another app they may only allow access for a single fetch to their private content provider.

**Comment by RajeshBatth** [comment]
I'm using the same method for loading all images,I've also check the parameters passed to it. Everything is fine

**Comment by RajeshBatth** [comment]
Can permissions be temporary?

**Comment by TWiStErRob** [comment]
See `Intent.FLAG_GRANT_READ_URI_PERMISSION`, `Context.grantUriPermission`. I came across this while developing file sharing within my app, I was using http://developer.android.com/training/secure-file-sharing/setup-sharing.html (notice the `grantUriPermission` in the xml as well). Sadly I don't know more than this.

**Comment by RajeshBatth** [comment]
So maybe the images that are being displayed now are fetched from the cache instead of provider?

**Comment by TWiStErRob** [comment]
Possible, see https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling how to debug that.

**Comment by RajeshBatth** [comment]
Thanks i'll check it and update u
