### ISSUE TITLE
Can not found [asBitmap] method in RequestManager

### ISSUE THREAD

**Issue by gongshoudao** [bumptech/glide#1034]
I use 'com.github.bumptech.glide:glide:3.7.0' in jCenter.
But i can't use these functions [https://github.com/bumptech/glide/wiki/Custom-targets](url) ,because I can't found these method in library.

**Comment by TWiStErRob** [comment]
It's after `load` or `from*`, not after `with`.

**Comment by gongshoudao** [comment]
I got it,thanks!
