### ISSUE TITLE
How can I get the loaded drawable/bitmap from glide

### ISSUE THREAD

**Issue by WanClem** [bumptech/glide#1036]
Hi,I want to get the loaded drawable from glide and set is a background to CollapsingToolbar.How can I achieve this???? Thanks

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Custom-targets#viewtarget

**Comment by WanClem** [comment]
Oh! Thanks...My bad,I forgot to check the Wiki before placing this question....Gonna work with the Wiki henceforth...Thanks again....

**Comment by TWiStErRob** [comment]
Tip: The wiki also ranks third if you enter the title of this issue into Google :)

**Comment by WanClem** [comment]
Cool...
