### ISSUE TITLE
Help needed - Merging two bitmaps together

### ISSUE THREAD

**Issue by Syrou** [bumptech/glide#1037]
I have a question, i would want to merge two bitmaps that has been put on cache together.
I recon the best approach to this would be to use Transform, but how would I do this best?

First I have to load one file, and then load a second file, and then i would want to apply a transformation merging the two bitmaps together into a new bitmap that has the same height, but the double width, where the bitmaps lay next to each other. How would this be done?

**Comment by TWiStErRob** [comment]
If you just want to put the images next to each other wouldn't it be easier to use two `ImageView`s in a horizontal `LinearLayout` with `layout_weight=0.5`?

**Comment by Syrou** [comment]
Hi @TWiStErRob the code would be used in conjunction with a zoomable view, and this is why I would need the merging to be done on a bitmap level

**Comment by TWiStErRob** [comment]
It was worth a mention, how about http://stackoverflow.com/a/35296850/253468?

**Comment by Syrou** [comment]
Ah yes, that would be the way to chain the actual requests together, but the transformation does only accept one "Bitmap toTransform". Does this mean that my custom transform would need to implement something like CustomTransform.setFirstBitmapToUse(Bitmap..) and a CustomTransform.setSecondBitmapToUse(Bitmap..) ?

**Comment by TWiStErRob** [comment]
No, in Solution 1 you load one and in `onResourceReady` you start another load with the just-finished resource passed into the transformation, so one Bitmap comes from constructor and the other comes from Glide.

I think Solution 2 is much cleaner for your case: just fire an AsyncTask that has two sync requests for the two bitmaps, do the merge without any BitmapTransformation and then return it, then set the bitmap in onResourceReady. The problem with this is that it doesn't support caching the resulting image, only the two source images, but I guess this is kind of true for Solution 1 as well if you can combine any two images together.

**Comment by Syrou** [comment]
```
public class SpreadTransformation extends BitmapTransformation {

    private static Paint mPaint = new Paint();
    private Context mContext;
    private BitmapPool mBitmapPool;
    private String mId;
    private Bitmap mLeftPage;


    public SpreadTransformation(Context context, String id) {
        this(context, Glide.get(context).getBitmapPool(), id);
    }

    public SpreadTransformation(Context context, BitmapPool pool, String id) {
        super(pool);
        mBitmapPool = pool;
        mContext = context.getApplicationContext();
        mId = id;
    }


    @Override
    protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
        return transform(mLeftPage, toTransform, outWidth, outHeight);
    }

    public Bitmap transform(Bitmap leftSource, Bitmap rightSource, int outWidth, int outHeight) {

        int width = leftSource.getWidth()*2;
        int height = leftSource.getHeight();

        Bitmap result = mBitmapPool.get(width, height, Bitmap.Config.RGB_565);
        if (result == null) {
            result = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_4444);
        }

        Canvas canvas = new Canvas(result);
        canvas.drawBitmap(leftSource, 0, 0, mPaint);
        canvas.drawBitmap(rightSource, getRightPageOffset(leftSource), 0, mPaint);

        return result;
    }

    private int getRightPageOffset(Bitmap source)
    {
        return source.getWidth();
    }

    @Override public String getId() {
        return "SpreadTransformation(Id=" + mId
                + ")";
    }

    public void setLeftPage(Bitmap leftPage) {
        mLeftPage = leftPage;
    }
}
```

```
  private void loadSpread(final File leftPage, final File rightPage)
    {
        if(leftPage != null && rightPage != null) {
            final ViewTarget<ZoomView, Bitmap> rightViewTarget = new ViewTarget<ZoomView, Bitmap>(mZoomView) {
                @Override
                public void onResourceReady(Bitmap resource, GlideAnimation anim) {
                    ZoomView myView = this.view;
                    // Set your resource on myView and/or start your animation here.
                    myView.setContentThumbnail(resource);

                }
            };

            final ViewTarget<ZoomView, Bitmap> leftViewTarget = new ViewTarget<ZoomView, Bitmap>(mZoomView) {
                @Override
                public void onResourceReady(Bitmap resource, GlideAnimation anim) {
                    SpreadTransformation spreadTransformation = new SpreadTransformation(getActivity(), leftPage.getName()+rightPage.getName());
                    spreadTransformation.setLeftPage(resource);
                    Glide.with(SpreadFragment.this).load(rightPage).asBitmap().transform(spreadTransformation).into(rightViewTarget);

                }
            };


            Glide.with(SpreadFragment.this).load(leftPage).asBitmap().into(leftViewTarget);
        }
    }
```

Became the solution in the end. Let me know if something feels off with it :)

**Comment by TWiStErRob** [comment]
There's an unsafe operation here: when `leftViewTarget` finished you start a new load, but that load goes into the same view so `into(rightViewTarget)` will clear the leftViewTarget's request so the resource you captured *may* become invalid.

Another thing is the `pool.get or create` is using different configs... decide which one you want use only one. The pool may say "i don't have this size for RGB_565", but if you asked for `RGB_4444` you may have received a value back.

**Comment by Syrou** [comment]
Ah thanks for those pointers! Then making leftViewTarget into a SimpleTarget should solve that :)

**Comment by Syrou** [comment]
There seems however to be another problem with this, the bitmap pool never finds a previously created bitmap. Does it have something todo with the cache?

**Comment by TWiStErRob** [comment]
The resources are only returned to the pool (which will result in finding them there later) if you clear the targets: `Glide.clear(leftViewTarget);`

**Comment by TWiStErRob** [comment]
Note that you can re-use targets too, so if you can break the dependency to the final method args, you can move them to being fields. If you load to a target that has an active resource in it Glide will clear it before starting the new load. This is how normal list scrolling works too.

**Comment by Syrou** [comment]
Thanks for the response, I recon that running Glide.clear has to be done when you are destroying the ImageView or View that is using it, if i clear it any earlier I get ```java.lang.IllegalArgumentException: Cannot draw recycled bitmaps```

The problem here is now how slow .transform(spreadTransform) is. If i remove the .transform(...) out of the equation, and do my own bitmap manipulation with my own BitmapPool the merged result is displayed instantly, while if i'm using the BitmapTransformation that i posted an example of above, it takes almost 6 seconds before anything is displayed.

Something seems to be blocking, and i can't for my life figure out why

**Comment by TWiStErRob** [comment]
Yes, the clear needs to be done when you don't need the resources any more. For example in the beginning of method `loadSpread` above. Currently it will just leave the resources hanging until the fragment is destroyed. So if you `loadSpread` a lot of times you should see increasing memory, adding clear will free it immediately.

I can't comment on the slowness really, maybe it's the caching, but multiple seconds sounds a lot especially since you're loading Files. You can try to enable internal logging of Glide to see which part takes long.

From the beginning I was trying to lead you towards Solution 3, it cleaner and there's less weirdness going on there. You can also clear the targets immediately after the merge.

**Comment by TWiStErRob** [comment]
Oh and you should override `Target.onLoadCleared` too.

**Comment by Syrou** [comment]
Yep Solution 3 is probably what will be the new final solution :)
