### ISSUE TITLE
Disable Cross Fade animation

### ISSUE THREAD

**Issue by Jayvd** [bumptech/glide#1039]
hello, Is it possible to disable fade animation when the image has been finally loaded?

I know it is a feature. but I would like to disable it. Is it possible?

        Glide.with(getContext()).load(imageResourceID).placeholder(imageResourceID).into(imageView);

I dont use the `.crossFade()` but the animation is still there.

**Comment by TWiStErRob** [comment]
`.dontAnimate()`?

**Comment by Jayvd** [comment]
Thanksss @TWiStErRob  Did not know it exists
