### ISSUE TITLE
can not stop gif animating right now

### ISSUE THREAD

**Issue by jacklydoudou** [bumptech/glide#1043]
Hi. i keep the target where glide return, i think it's a instance of target<GlideDrawable>, and i invoke onStop method to make it stop, but i found it can not stop animate right now, looks like it will stop at next frame.........but not the frame i want...

**Comment by TWiStErRob** [comment]
`onStop` is a lifecycle method, you shouldn't call it directly. Take a look at this code: https://github.com/bumptech/glide/issues/1028#issuecomment-192481349 you should be calling these methods to interact with the gif animation.

I'm not sure about the next frame thing, it's possible that's a bug, GIF timings are usually too fast to notice anything like that.

**Comment by jacklydoudou** [comment]
I try the code you suggest, but still the same

**Comment by TWiStErRob** [comment]
@sjudd do you think it's possible that the GifDrawable will deliver it's last in-flight load after it has been stopped?

**Comment by jacklydoudou** [comment]
how can i do....may be.. i should download the sourcecode to have a look?

**Comment by sjudd** [comment]
It's possible that the last request will finish. I'd happily accept a pull request if there's an issue.

**Comment by sjudd** [comment]
I believe this was fixed by 90b3b9f054072a7c3625926caa150277352b92dd
