### ISSUE TITLE
Crash on Samsung devices with 5.0.1 and 5.0.1: NoSuchFieldException: allocationSpinLock

### ISSUE THREAD

**Issue by mullender** [bumptech/glide#1047]
Not sure if this is something Glide could fix or not, but it seems that Samsung's version of android 5.0.1 and 5.0.2 cause an exception. 

It seems like the crash is not happening very often because we see the customers use the app successfully later. So the customer impact is low.

Stacktrace:

``` java
0   java.lang.Error: java.lang.NoSuchFieldException: allocationSpinLock
1   at java.util.concurrent.PriorityBlockingQueue.<clinit>(PriorityBlockingQueue.java:919)
2   at com.bumptech.glide.load.engine.executor.GlideExecutor.<init>(GlideExecutor.java:115)
3   at com.bumptech.glide.load.engine.executor.GlideExecutor.newSourceExecutor(GlideExecutor.java:107)
4   at com.bumptech.glide.load.engine.executor.GlideExecutor.newSourceExecutor(GlideExecutor.java:89)
5   at com.bumptech.glide.GlideBuilder.createGlide(GlideBuilder.java:266)
6   at com.bumptech.glide.Glide.get(Glide.java:154)
7   at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.<init>(BitmapTransformation.java:59)
8   at com.bumptech.glide.load.resource.bitmap.CenterCrop.<init>(CenterCrop.java:23)
9   at com.bumptech.glide.request.BaseRequestOptions.centerCrop(BaseRequestOptions.java:501)
...
```

This seems to be the code that is the source of the issue, outside of Glide:

``` java
 static {
        try {
            UNSAFE = sun.misc.Unsafe.getUnsafe();
            Class<?> k = PriorityBlockingQueue.class;
            allocationSpinLockOffset = UNSAFE.objectFieldOffset
                (k.getDeclaredField("allocationSpinLock"));
        } catch (Exception e) {
            throw new Error(e);
        }
    }
```

**Comment by mullender** [comment]
Given the low impact and that the root seems to be outside of glide, we can probably treat this as won't fix. But it is nice to have the information captured, in case the frequency increases.

**Comment by TWiStErRob** [comment]
I guess we could create a different blocking queue for those devices and versions, a copy of PBQ that works. Do you have access to any of these to see what happened to the missing field? (dumping the class via reflection)

How can they use it? Are you sure they don't just uninstall after it's crashing? It looks like this is pretty core and Glide cannot even init.
