### ISSUE TITLE
size of result image after adjusting sample size

### ISSUE THREAD

**Issue by BattleShipPark** [bumptech/glide#1052]
Hi, I am transforming image using Glide.
I wrote test code like below. It decodes image by sample size and prints the size of result image.
```
Glide.with(this).load(pathName)
                .asBitmap()
                .imageDecoder(new StreamBitmapDecoder(new Downsampler() {
                    @Override
                    protected int getSampleSize(int inWidth, int inHeight, int outWidth, int outHeight) {
                        return 16;
                    }
                    @Override
                    public String getId() {
                        return "16";
                    }
                }, Glide.get(this).getBitmapPool(), DecodeFormat.PREFER_ARGB_8888))
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .listener(new RequestListener<String, Bitmap>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                        return false;
                    }
                    @Override
                    public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        Log.w("TEST", String.format("%d x %d", resource.getWidth(), resource.getHeight()));
                        return false;
                    }
                })
                .into(iv);
```

However, even if I change return number in getSampleSize(), size of image in log does not change. Of course, result image on ImageView has changed.
I'd like to know size of result image after adjusting sample size. Can you help me?
Thanks.

**Comment by TWiStErRob** [comment]
See #1051, your problem is the opposite as that, you have `.fitCenter()` automatically applied, to fix that add `.dontTransform()`.

However if you only need the size, decoding the full image (even downsampled) is really wasteful. You should consider the fast solution in #781 (with a little change of dividing the result by 16, or add inSampleSize in the Options, but I don't know if that modifies `outWidth`), your current one is the "slower hacky" one.

**Comment by BattleShipPark** [comment]
Sorry for late. #1051 is very useful to understand to how to work. Thanks!
