### ISSUE TITLE
If the Bitmap has been presented into a imageview, how can i get the Bitmap later from cache directly

### ISSUE THREAD

**Issue by jacklydoudou** [bumptech/glide#1053]

**Comment by TWiStErRob** [comment]
There's no direct cache access, but it's likely possible what you want, but it depends on what you want to do with it.

**Comment by jacklydoudou** [comment]
i just want to get the bitmap.
and in Wiki:
Instead when you later want to retrieve your image, you can do so using a normal call with one exception:
Glide.with(yourFragment)
    .load(yourUrl)
    .diskCacheStrategy(DiskCacheStrategy.ALL)
    .into(yourView);

but i want the bitmap downloaded..not into a imageview

**Comment by jacklydoudou** [comment]
bitmapUpload = Glide.with(frg.getActivity()).load(myUrl).asBitmap().diskCacheStrategy(DiskCacheStrategy.ALL).into(500,500).get();
Will this check the cache?

**Comment by AnimbusDev** [comment]
@jacklydoudou It should...

**Comment by Ajibola** [comment]
Hi @TWiStErRob just want to clarify, downloadOnly does it still go into the cache first before going over the wire? 

I see that i can force it to go to cacheonly, with StreamModelLoader, but still need it to go over the wire or wait if the image is already in the pipeline.

Btw  thanks for all the work you do on glide, it is much appreciated.

**Comment by TWiStErRob** [comment]
> Will this check the cache? --- https://github.com/bumptech/glide/issues/1053#issuecomment-195303961

Yes, that will cache `myUrl`'s raw bytes into the SOURCE cache and cache a 500x500 resized version into RESULT cache, and return the latter 500x500 Bitmap synchronously. You might want to add a `.fitCenter()` or `.centerCrop()` to that as there's not transformation applied after downsampling by default. I hope this is not a line executed on the UI thread... ;)

> downloadOnly does it still go into the cache first before going over the wire? --- https://github.com/bumptech/glide/issues/1053#issuecomment-195514657

Yes, `downloadOnly` won't download a file that was already `downloadOnly`'d, or was displayed with `.diskCacheStrategy(SOURCE or ALL)`; or is in progress of doing any of the above.
