### ISSUE TITLE
ScaleType.MATRIX results in Bitmap too large to be uploaded into a texture warning

### ISSUE THREAD

**Issue by arriolac** [bumptech/glide#1054]
I understand that Glide automatically resizes the drawable to match the size of the containing `ImageView`, this works perfectly fine when I tested it when `ScaleType.FIT_CENTER`. However, when the `ScaleType` is set to `ScaleType.MATRIX`, images retrieved over the network that exceed the maximum allowed size of 4096x4096 I get the warning `Bitmap too large to be uploaded into a texture (4160x2340, max=4096x4096)`. 

Is this a bug or expected for `ScaleType.MATRIX`?

**Comment by TWiStErRob** [comment]
There's no transformation is applied to the input image when you load with `scaleType=matrix`. Check `GenericRequestBuilder#into(ImageView)`. Glide first downsamples the input image to a reasonable size to not consume much memory, and don't lose quality, and then applies a transformation. It looks like your input is so big, that the downsampled version exceeds the texture size.

To fix this you'll either have to provide a smaller target (e.g. `.override()`) and/or add a transformation explicitly (`.fitCenter()` or `.centerCrop()`).

If you need more info please post your Glide line and layout XML so we can see why the target size is that big.
