### ISSUE TITLE
The image is deformed when scrolling the screen in recyclerView with glide 

### ISSUE THREAD

**Issue by lowfiend** [bumptech/glide#1058]
I use compile 'com.github.bumptech.glide:glide:3.7.0' in build.gradle.

I'm scrolling many time,the image is deformed.

What can I do?

```java
@Override
    public void onBindViewHolder(RecyclerViewHolders holder, int position) {

            holder.Name.setText(itemList.get(position).getName());
            holder.PostTime.setText(itemList.get(position).getPostTime());
            holder.PostContent.setText(itemList.get(position).getPostContent());
            Uri uri = Uri.parse(itemList.get(position).getPhoto());
            Glide.with(context).load(uri).crossFade().error(R.mipmap.imge_error).into(holder.PostImg);
            holder.PostImg.setTag(R.id.post_img, position);
            holder.PostImg.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                int position = (int) v.getTag(R.id.post_img);
                Toast.makeText(context,itemList.get(position).getName(),Toast.LENGTH_SHORT).show();
            }
        });
    }
```

![image](https://cloud.githubusercontent.com/assets/9345164/13800683/6a4b1038-eb66-11e5-8084-70bf095512be.png)

![image](https://cloud.githubusercontent.com/assets/9345164/13800691/85d715ae-eb66-11e5-90ee-717721d6f4f4.png)

**Comment by TWiStErRob** [comment]
The height of the item changes, and Glide uses that to load the image. Are you using wrap_content? What's your XML?

**Comment by lowfiend** [comment]
`<android.support.v7.widget.CardView
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/card_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    card_view:cardUseCompatPadding="true"
    card_view:cardCornerRadius="8dp">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.tour.fit_textview.AutoResizeTextView
            android:id="@+id/name"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="8dp"
            android:textStyle="bold"
            android:singleLine="true"
            android:textSize="18sp"
            android:textColor="@color/black"/>
        <com.tour.fit_textview.AutoResizeTextView
            android:id="@+id/post_time"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/name"
            android:singleLine="true"
            android:textSize="18sp"
            android:padding="8dp"/>
        <ImageView
            android:id="@+id/post_img"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/post_time"/>

        <com.tour.fit_textview.AutoResizeTextView
            android:id="@+id/post_content"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/post_img"
            android:singleLine="true"
            android:textStyle="bold"
            android:textSize="18sp"
            android:padding="8dp" />

    </RelativeLayout>

</android.support.v7.widget.CardView>`

**Comment by TWiStErRob** [comment]
I think we can consider this a duplicate of #864, you're essentially trying to make a 1 column staggered grid (even if it's linear layout manager). Here are your options:
* if you know the sizes beforehand (from `itemList.get(position)`), you can try the percent view solution by Bryan
* if you don't, you can try the `layout(0)` workaround
* you can just fix the height of the item to a reasonable size (e.g. aspect 16:9 with percent layout, or a fixed DP height).
* If you want end-to-end display (screen wide) with fixed size you can use centerCrop to make it look nicer

Do you really want to display very tall images as screen-wide too? It could mean that an item occupies more than the screen's height if it's something like a comic strip.

**Comment by lowfiend** [comment]
I use android:scaleType="fitXY" and than look like perfect.

thanks

**Comment by TWiStErRob** [comment]
You should know that distorts the image, try to load a uniform grid pattern or a person's face in the list to see what I mean.

For example: https://rsathya.files.wordpress.com/2011/12/simple-grid-wallpaper.jpg

**Comment by guy-4444** [comment]
Use this solution:
https://stackoverflow.com/a/46147971/7147289
