### ISSUE TITLE
The Gif load problem, can't display well

### ISSUE THREAD

**Issue by JKingdom** [bumptech/glide#1059]
Hi, I load a gif image from local
The gif：
![Image](http://file.baixing.net/201511/40dfc16a7965fff85bc6f6ea2d854f17.gif)
and other gifs:
![Image](http://file.baixing.net/201511/59aa0ca0c1d0c330983a110d605ff940.gif)
![Image](http://file.baixing.net/201511/080408bac9579a07500c212e40bb96ee.gif)

I use 
`      int source = R.drawble.xxx;`
`
Glide.with(this).load(source).asGif().diskCacheStrategy(DiskCacheStrategy.SOURCE).into(imageView);
`
to load those Gifs

But I find the gif1 and gif2 can't display very well, though the gif can display on the phone, but it flick(flash , twinkle, glint  sorry I'm not a English speaker, I don't know how to express it well, all in all the Gif1 and Gif2 in glide are not playing well, It seems that the last frame doesn't  disappear)

However the 3rd Gif is normal.

I'm confused about the question, I try many gifs and find it seems that when the gif's background is transparent it will appear(not for all, just  some of them)

I use Glide 3.6.1
and also find this problem in 3.7.0

But when I choose another gif lib like:
[koral--/android-gif-drawable](https://github.com/koral--/android-gif-drawable)
it display all gifs very well.

So I help to solve this problem.
 Thank you very much!

**Comment by TWiStErRob** [comment]
I think what you see is #836, the fix is done for v4, but needs to be copied into v3, this is tracked in #970. Please confirm that the "screenshot" in #836 is similar to your "flash".

There's also a possibility of using external libraries to display stuff, see #805.

**Tip**: don't use `.diskCacheStrategy(SOURCE)` for local images, that will duplicate the file (in APK, and on SDcard) without any performance benefit. Use NONE for local GIFs.

**Tip**: use `adb screen record /sdcard/demo.mp4`, then `adb pull /sdcard/demo.mp4`, then upload at http://ezgif.com/video-to-gif to make a "moving screenshot" that you can embed on GitHub/StackOverflow.

**Comment by JKingdom** [comment]
Thank you very much for you answer, I will check soon.
But I have another question: 
I use `.diskCacheStrategy(SOURCE)` because I think I load gif is too slow, so I find the issue [#600](https://github.com/bumptech/glide/issues/600)

so I use `.diskCacheStrategy(SOURCE)`  in my code

Depending on what you say, I should use `.diskCacheStrategy(SOURCE)`  only in network gif? But NONE for local gif?   (To be honest, I think if I don't use `.diskCacheStrategy(SOURCE)`  for local     gif,  It loads too slow...)

and think you for you next tip, I will upload soon.

**Comment by TWiStErRob** [comment]
Yes, you see it correctly, it's weird for opening a stream from APK to be slow, I have no idea about that. You can try putting the image in raw or assets, but I don't think it'll make a difference.

Wait... by NONE I mean to explicitly call `.diskCacheStrategy(NONE)`; if you don't call that method at all (omit it from code), it's the same as `.diskCacheStrategy(RESULT)` which is known to be slow for gifs.

**Comment by JKingdom** [comment]
@TWiStErRob 
I try you advice today. For a directly method,  I use 4.0.0-SNAPSHOT to try my gifs.
I follow the guide in [Snapshots](https://github.com/bumptech/glide/wiki/Snapshots)
and use glide:4.0.0-SNAPSHOT in gradle

> dependencies {
>   compile 'com.github.bumptech.glide:glide:4.0.0-SNAPSHOT'
>   compile 'com.github.bumptech.glide:okhttp-integration:2.0.0-SNAPSHOT'
> }

and the Glide code change to
>      int source = R.drawable.xxx
>        Glide.with(this)
>                .load(source)
>                .into(imageView);

I tried the first Gif , it seems become normal
![image](http://i.imgur.com/3gNQOXw.gif)
[gif1](http://i.imgur.com/3gNQOXw.gifv)

(The above image is loaded by android-gif-drawable and the under image is loaded by Glide)

But when I tried second Gif, it look like what I said before “flash or glitter in some frame”
this is link
![image2](http://i.imgur.com/8O4Kn6C.gif)
[gif2](http://i.imgur.com/8O4Kn6C.gifv)

It seems that there are also some bugs in v4 :(

**Comment by TWiStErRob** [comment]
Can you try with `.diskCacheStrategy()`? You may be seeing #1061 which was just reported. I think the v4 format is something like: `.apply(new RequestOptions()....)`

**Comment by JKingdom** [comment]
@TWiStErRob 
I'm so sorry... I used in this way
> Glide.with(this)
>                 .load(source)
>                 .apply(new RequestOptions().diskCacheStrategy(DiskCacheStrategy.NONE))
>                 .into(imageView);

But It's still like this:
![image](http://i.imgur.com/zG1rUIr.gif)

**Comment by TWiStErRob** [comment]
Hmm, it looks like sometimes only half of the frame is decoded, maybe the Bitmap is displayed while it is still decoding, which would be really weird.
Notice there's also a frame where the guy's head is black-ish.

**Comment by TWiStErRob** [comment]
@JKingdom check out #1093.
Thank you for reporting this issue, and sorry for saying it's a dupe.
It turns out this was a well-defined issue, thanks for all the screenshots as well it helped a lot!

**Comment by TWiStErRob** [comment]
Fixed in #1093, should available as [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots).

**Comment by JKingdom** [comment]
Thank you very much for you help! ! !

**Comment by SwayChen** [comment]
@TWiStErRob Hi! I meet this trouble like gif2. 
use `compile 'com.github.bumptech.glide:glide:3.7.0'`

I can't find which version should I use! -_-||
