### ISSUE TITLE
Gif exceptional display

### ISSUE THREAD

**Issue by jacklydoudou** [bumptech/glide#1061]
Glide.with(aty).load(mUrl).transform(getBitmapTransformation()).placeholder(placeHolder).animate(android.R.anim.fade_in).diskCacheStrategy(DiskCacheStrategy.SOURCE)
working fine

Glide.with(aty).load(mUrl).transform(getBitmapTransformation()).placeholder(placeHolder).animate(android.R.anim.fade_in).diskCacheStrategy(DiskCacheStrategy.ALL)
exceptional working

it will play normally util the last frame , suddenly the image on the imageview flash and can 't display well~ 
so i have to make sure i use the DiskCacheStrategy.SOURCE not ALL.

**Comment by TWiStErRob** [comment]
You shouldn't enable RESULT cache for GIF it really slows things down. That said the frames' meta (delay, disposal, etc.) should be kept even when reencoding. So this will need a deeper look. Thanks for the report.

**Comment by TWiStErRob** [comment]
Can you provide an image(attached)/URL you used?

**Comment by jacklydoudou** [comment]
oh.sorry, the url must be used with a token which will be expired,and the app still in the developing state..... i think just find a gif url instead as well.

**Comment by TWiStErRob** [comment]
You can download the gif and attach that too.

**Comment by jacklydoudou** [comment]
i find you all fix this problem in Glide3.8.0,THKSssssss!!!!!!>_<

**Comment by jacklydoudou** [comment]
much of APIs has been changed

**Comment by TWiStErRob** [comment]
What do you mean by "API changed"?

**Comment by jacklydoudou** [comment]
GlideDrawble deleted ?and i must new a BaseRequestOptions if i want to set a transformation, and into() has been depre...........

**Comment by TWiStErRob** [comment]
You're using 4.0.0-SNAPSHOT, not 3.8.0-SNAPSHOT.

**Comment by jacklydoudou** [comment]
should i keep use it or change to 3.8.0

**Comment by TWiStErRob** [comment]
That's up to you:
 * v4 is unreleased and API may still change
 * 3.8.0 is stable, with some bugfixes (mostly GIF) after the released 3.7.1
When you reported this issue you were using 3.x

**Comment by jacklydoudou** [comment]
i can't find 3.7.1 or 3.8.0 in the release page and there is just 3.7.0 in Android studio searching

**Comment by jacklydoudou** [comment]
Can you paste the Url for download?   Thx

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Snapshots
