### ISSUE TITLE
The RequestFutureTarget  violates the Future contract.

### ISSUE THREAD

**Issue by arivald** [bumptech/glide#1063]
For the Android Future, the `isDone()` method contract says: 

> Returns true if this task completed.
> Completion may be due to normal termination, an exception, or cancellation -- in all of these cases, this method will return

But the `RequestFutureTarget.isDone()` implementation ignores the exception case.

Proposed fix:    

``` diff
    public synchronized boolean isDone() {
-        return isCancelled || resultReceived;
+        return isCancelled || resultReceived || exceptionReceived;
    }
```

As a workaround, I call get() with minimum timeout, but this is not the optimal solution.

**Comment by sjudd** [comment]
Thanks for pointing this out. I'd be happy to accept a pull request, your proposed solution looks reasonable.
