### ISSUE TITLE
sslhandshake

### ISSUE THREAD

**Issue by choisungkuen** [bumptech/glide#1066]
https has called upon the problem.

Tell us how to resolve the issue

**Comment by TWiStErRob** [comment]
Please fill in the [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues). Describe the expected/actual behaviour. Give a real example where it failed with [error messages](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling).

**Comment by choisungkuen** [comment]
Certificate issue
I thank processed
