### ISSUE TITLE
Highly customized loads may leak Activity through EngineKey by DiskCache

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#1070]
**Glide Version**: 3.7.0
**Integration libraries**: N/A
**Device/Android Version**: Galaxy S4 / 4.4.2
**Issue details / Repro steps / Use case background**:
I took a heap dump after several GCs and exited the activity:
![image](https://cloud.githubusercontent.com/assets/2906988/13885913/e54adde8-ed34-11e5-925c-03a9ee8128bf.png)

It looks like the DiskCache is keeping things in memory because SafeKeyGenerator keeps a Key map. The key contains all the different pipeline parts, in this case it's the transcoder.

This only happens if the pipeline item actually stores the Context as a field, in case of most Transformations this is ok, because all they need the context for is `Glide.get(context).getBitmapPool()` which uses `getApplicationContext()` internally. The transformation example only included as contrast for Transcoder.

`GlideBitmapDrawableTranscoder` saves `getResources()` into a field, which keeps the reference to the parent Context which is the activity. This is needed because it passes the `Resources` into a `Drawable` which determines the density from it.

I always thought that the pipeline customizations on a Glide load site are only alive for the duration of the Request/until the Target is cleared. So I assumed it was safe to pass the Activity context to it. It turns out that's not always the case.

**Glide load line**:

``` java
RequestManager glide = Glide.with((Fragment)this);
Context context = someView.getContext(); // == activity instance

glide.load(message.getAvatarUrl())
     .bitmapTransform(new FitCenter(context), new CropCircleTransformation(context))
     .listener(new LoggingListener<String, GlideDrawable>())
     .into(avatarView);

glide
    .fromString()
    .asBitmap()
    .transcode(new BitmapToGlideDrawableTranscoder(context), GlideDrawable.class)
    .diskCacheStrategy(DiskCacheStrategy.ALL)
    .centerCrop()
```

**Workaround/Fix**:
A simple workaround is to pass in the app context, the problem is that individual activities may contain customization in theme, that may be accessed, for example a Transformation reads some colors.

``` java
context = context.getApplicationContext();
.transcode(new BitmapToGlideDrawableTranscoder(context), GlideDrawable.class)
```

A proper fix is likely to somehow weaken the reference from the DiskCache to the Key.

**Comment by sjudd** [comment]
This is basically fixed in v4 by preventing users from passing in components directly. Models are still issues if they reference Contexts, but I'm not sure there's a ton we can do about that.
