### ISSUE TITLE
delay when loading images 

### ISSUE THREAD

**Issue by landior1993** [bumptech/glide#1075]
There seems to be a slight delay(the placeholder is shown for 1-2s) when loading images using Glide, especially when scrolling a bunch of images using recyclerview. Is this an intended behavior?. I tried removing placeholder but this does not fix the issue.

```java
Glide.with(((PostsViewHolder)holder)
.imagePost.getContext())
.load(postsData.images.standard_resolution.url)
.priority(Priority.IMMEDIATE)
                    .placeholder(R.drawable.grey_placeholder)
                    .into(((PostsViewHolder) holder).imagePost);
```

**Comment by TWiStErRob** [comment]
* If you're loading a gif, use `.diskCacheStrategy(SOURCE)`
* Using IMMEDIATE in a list is kind of pointless unless you want priority over other parts of the app. Just think about it: if everything is high priority then nothing has lower priority than those items, hence priority doesn't matter (same equivalence class when scheduling, whatever you call it)
* try [enabling logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) to see which part of the load takes time.
* Glide cannot fix your internet speed, if the network is slow it'll take some time to load an images. If you display a list, multiple images' requests are fired at once, sharing bandwidth
* Consider adding a `Glide.with(context).pause|resumeRequests()` when the user is scrolling fast (fling, or [dy > threshold](https://github.com/TWiStErRob/glide-support/blob/a1572179430e837d8410cc9f915d7c4737e584dd/src/glide3/java/com/bumptech/glide/supportapp/github/_864_staggered_grid/PauseOnFling.java))


What is the XML of your layout?
Do you use integration library?
Do you use the exact same code in your app?
Why did you delete the issue template requesting these answers (you can be honest, we are experimenting with it)?

**Comment by landior1993** [comment]
[Here's the xml](https://gist.github.com/landior1993/cd73d25dc314cecb4f08)

I'm using okhttp3 

> compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'
    compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'

and yes i'm using the exact same code. I'm actually loading 2 images from the server like this 
[Viewholder.java](https://gist.github.com/landior1993/c4e5a64b9c7d47716597)

I'm loading images, not GIFS. The size of each image is no more than 200kb each. I don't think this is related to internet speed as I'm testing this using high speed wifi

**Comment by TWiStErRob** [comment]
Ah, I see, so you use priority to queue them better, nice. I see nothing pop out in your view hierarchy.

Remove those `setImageResource(0)` calls, Glide will show the placeholder immediately when you call `.into()` (or clear the view with null drawable if none provided, like in your second load). Calling `setImage*` may confuse Glide, but I don't think that's the issue here. If you want to manually clear views (for example in `onViewRecycled`), you can use `Glide.clear(imageView)`.

In every communication there's more than one party involved, even if you have super high speed network, the server may be busy or have a bad uplink. Please check the logs to see which part is actually slow.

**Comment by landior1993** [comment]
Removing `setImageResource(0)` calls seems to have made loading somewhat faster, though it's still pretty slow compared to other apps (ie Instagram). I'll check out the logs. Thanks!

**Comment by TWiStErRob** [comment]
Ah, if you want to have what big apps do use a preloader. They load thumbnails before their items are even bound, so when you scroll you're see instant displays. It's like having a twice as long list, but you see only the top half at any time, so there's enough buffer to load the other images.

Glide v3 has a built-in ListPreloader for ListView. Glide v4 will have an [integration lib](https://github.com/bumptech/glide/tree/master/integration/recyclerview/src/main/java/com/bumptech/glide/integration/recyclerview) for RecyclerView, but it shouldn't be hard to backport it to Glide v3.

**Comment by landior1993** [comment]
Hmm ok I will look into this feature. Thanks a lot!
