### ISSUE TITLE
java.lang.IllegalStateException: Can't call reconfigure() on a recycled bitmap

### ISSUE THREAD

**Issue by renclav** [bumptech/glide#1079]
**Glide Version**: 3.7.0
**Integration libraries**: `okhttp-integration:1.4.0@aar`
**Device/Android Version**: Fails most times on Nexus 6P and on Genymotion nexus 7 & 10 API 5.1.0

Issue details:
I have a `ListView` (sorry, not recycler on this one just yet) which can load the same image in each cell dependent on API response.
Occasionally, I notice the image fails to load in all cells, until the image has been downloading and cached by glide. This can be reproduced by loading the listview, waiting a few seconds, seeing all images fail to load for a particular URL in each cell, scrolling down and up and seeing all the images appear correctly.

This seems related to #408 

Implementation in `listview getView`:
```java
@Override
public View getView(final int position, View convertView, final ViewGroup parent) {
    final ViewHolder holder;
    if (row == null) {
        if (parent != null) {
            row = inflater.inflate(R.layout.deal_slide, parent, false);
        } else {
            row = inflater.inflate(R.layout.deal_slide, null);
        }
        holder = new ViewHolder(row);
        row.setTag(holder);
    } else {
        holder = (ViewHolder) row.getTag();
    }
    holder.badge_container.removeAllViews();
    inflater.inflate(R.layout.imagebadge, root, true);
    final ImageView imageBadge = (ImageView) root.findViewById(R.id.badge_promotion);
    UIHelper.resizeBadge(imageBadge, big); // defines explicit size
    imageBadge.setId(MiscHelper.generateViewId()); // sets viewId using original android sourcecode for backporting,removing this doesn't help
    Glide.with(imageBadge.getContext())
        .load(urlString)
        .fitCenter()
        .placeholder(UIHelper.getLoadingDrawable(imageBadge.getContext()))
        .dontAnimate()
        .diskCacheStrategy(DiskCacheStrategy.NONE)
        .into(imageBadge);
    return row;
}
```

My `R.layout.imagebadge`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android">

    <ImageView
        android:id="@+id/badge_promotion"
        android:layout_width="@dimen/prodct_badge_dimension"
        android:layout_height="@dimen/prodct_badge_dimension"
        android:adjustViewBounds="true"
        android:contentDescription="Promotion Badge" />

</merge>
```

**Stack trace / LogCat**:
```ruby
java.lang.IllegalStateException: Can't call reconfigure() on a recycled bitmap
```

**Comment by TWiStErRob** [comment]
Edit your comment to see the fixes I made to markdown.
I don't think parent can be null in `getView`, that would mean you're binding an item in a ListView that doesn't exist.
There's some weirdness going on with variable names, `row VS convertView`, `root VS row`, `holder VS findViewById`?.
Anyway the ID doesn't matter for Glide since you pass an exact ImageView reference. Also the xml and I guess `resizeBadge` both define fixed size layouts.
Before you call `removeAllViews` you should iterate through each child and `Glide.clear()` it, otherwise you may run into OOMs as well if you scroll too much back and forth.

Sadly none of this is likely to help with the exception you're getting. This error usually means that the bitmap pool is tainted, so if you're using `Transformation`s anywhere in the app, that could be a culprit. Someone is recycling Bitmaps that are in the pool, outside of Glide's knowledge.
Also worth looking at any uses of `Bitmap.recycle()` (in Android Studio/IDEA press Shift 4 times rapidly, type `recycle`, find `android.graphics.Bitmap` in the list, right click the method name and *Find usages*).

**Comment by renclav** [comment]
Thank you @TWiStErRob  :+1: 
The markdown has been noted (thanks for fixing it up).
So I've added the Glide.clear() as mentioned here and [https://github.com/bumptech/glide/wiki/Resource-re-use-in-Glide](url).

What caught me out reading the similar issues is that the offending bitmap transforms **don't need to be attached to the broken request**. I looked over the codebase and noticed two custom transforms.

`BitmapFixedWidthTransform`
```java
public class BitmapFixedWidthTransform extends BitmapTransformation {

    public BitmapFixedWidthTransform(Context context) {
        super(context);
    }

    @Override
    protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
        int targetWidth = outWidth;

        double aspectRatio = (double) toTransform.getHeight() / (double) toTransform.getWidth();
        int targetHeight = (int) (targetWidth * aspectRatio);
        Bitmap result = Bitmap.createScaledBitmap(toTransform, targetWidth, targetHeight, true);
        if (result != toTransform) {
            // Same bitmap is returned if sizes are the same
            toTransform.recycle(); // removed this
        }
        return result;
    }

    @Override
    public String getId() {
        return "transformation" + " desiredWidth";
    }
}
```

and

`BitmapFixedHeightTransform`
```java
public class BitmapFixedHeightTransform extends BitmapTransformation {

    public BitmapFixedHeightTransform(Context context) {
        super(context);
    }

    @Override
    protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
        int targetHeight = outHeight;

        double aspectRatio = (double) toTransform.getHeight() / (double) toTransform.getWidth();
        int targetWidth = (int)(targetHeight/aspectRatio);

        Bitmap result = Bitmap.createScaledBitmap(toTransform, targetWidth, targetHeight, true);
        if (result != toTransform) {
            // Same bitmap is returned if sizes are the same
            toTransform.recycle(); // removed this
        }

        return result;
    }

    @Override
    public String getId() {
        return "transformation" + " desiredHeight";
    }
}
```

So far removing the `recycle` calls seems to have resolved the issue.
I think this occurred when the move was made from picasso to Glide and the gotcha went uncaught as you pointed out in [http://vardhan-justlikethat.blogspot.co.za/2014/09/android-image-loading-libraries-picasso.html](url)

Not to flog a dead horse here, but I really feel this gotcha needs to be made a bit clearer on the [https://github.com/bumptech/glide/wiki/Resource-re-use-in-Glide](url) page a more fleshed out version of [http://stackoverflow.com/questions/25278821/how-do-rounded-image-with-glide-library/25806229#25806229](url) be provided in sample code (I am happy to test).

Side note:

Reading some backlog of issues, my gut feel is there should be a more efficient means of achieving the above transforms. I saw one guy use a percentage based enclosing framelayout #1011 which may be a solution but I'd prefer to not modify layouts based on library usage.  

Thanks Again :relieved:

**Comment by TWiStErRob** [comment]
Check the javadoc of `Transformation.transform` and `BitmapTransformation.transform`. I'll update the wiki calling out transformations vs recycle.

I'm not exactly sure about your use case but I think:
```java
BitmapFixedWidthTransform == .override(w, Target.SIZE_ORIGINAL)
BitmapFixedHeightTransform == .override(Target.SIZE_ORIGINAL, h)
```
and you can have wrap_content in ImageView layout.

Markdown: when you insert URL, make sure you fill in the url, double check that insert link dialog and the "wiki page" link's markdown above. Also GitHub does autolinking, so just paste URL.

**Comment by renclav** [comment]
Updated Markdown.
I see your thinking there, yet it wont work for my use case as it looks like I require the downloaded bitmaps height and width retrospectively (this is adopted code, hence my tentative response).

I will look into it further, yet you are welcome to close this issue as resolved if desired. 
My final thoughts would be to provide an example like the SO one mentioned previously, just to clearly express how to use the Glide bitmap pool with scaling/cropping etc. In the mean time, I'm going to go learn some bitmap transform math and see if I can make the example myself (hello canvas) :)

**Comment by TWiStErRob** [comment]
Ah, sorry, I just skimmed those transforms. Now I see that they use target size. It feels like they're just specializations of `.fitCenter()`, and the same could be achieved with `match_parent` for the fixed dimension and `wrap_content` for the flexible one.

Updated https://github.com/bumptech/glide/wiki/Resource-re-use-in-Glide, can you please take a look?

**Comment by TWiStErRob** [comment]
Also linked https://github.com/bumptech/glide/wiki/Transformations#bitmap-re-use there, which already documented this too.

**Comment by renclav** [comment]
@TWiStErRob Awesome, the wiki pages updates are gold :)
I'll definitely look into your suggestion, I have the same feeling. Just one of those, "I'm sure they had a good reason for this... right?" feelings :P

Thanks for all the feedback, it's highly appreciated and valued :smiley:

**Comment by TWiStErRob** [comment]
Oh, good old "historical reasons". In my experience most of the time it boils down to simple incompetence, maybe NIH syndrome. If you know the input domain (in this cases possible images) and the expected output (look of the UI), and you can do it in much less code, I would say go for it, just make sure you test in thoroughly.
