### ISSUE TITLE
To what extent does glide optimize images?

### ISSUE THREAD

**Issue by landior1993** [bumptech/glide#1082]
I'm currently reading [the official android guide to optimize images](http://developer.android.com/intl/vi/training/displaying-bitmaps/index.html)

The question is : Is it necessary to implement the techniques mentioned above after using Glide?

**Comment by TWiStErRob** [comment]
No, everything there is covered by Glide, and more; but I recommend reading that documentation. If you want to see where those are implemented feel free to browse the source or ask in this issue.
