### ISSUE TITLE
Image deformation problems and the solutions

### ISSUE THREAD

**Issue by Guolei1130** [bumptech/glide#1084]
When I use it, the image deformation will happen.The reason is scaling calculation error.This is a kind of solution[http://blog.csdn.net/u013177564/article/details/49642173](url) .But I use the way is，In the code really zoom type is used，in xml user error.
在用glide的时候，会发生首次加载变形的情况，我的解决办法是，在xml中用错误的缩放类型，在代码中用正确的，这样就可以解决了。

**Comment by TWiStErRob** [comment]
Glide always keeps the aspect ratio of the image, it cannot distort unless you write a custom transformation.

Take a look at the [documentation of `FIT_XY`](http://developer.android.com/intl/vi/reference/android/widget/ImageView.ScaleType.html#FIT_XY):
> Scale in X and Y independently, so that src matches dst exactly.
> This may change the aspect ratio of the src.

So if you use `fitXY` in XML, the result will be distorted when displayed. The actual Bitmap that was loaded is not distorted, only when it's shown.

**Comment by Guolei1130** [comment]
when i write in xml scaleType is centercrop,and use .centerCrop() to load img,the img will be deformation.(GridView), sorry,my english is very poor.

**Comment by TWiStErRob** [comment]
Can you share the original image you load and a screenshot of how it is loaded?

**Comment by Guolei1130** [comment]
this is,xml is centercrop and code is .centerCrop(),but img...
![啦啦啦啦](https://github.com/Guolei1130/DragGridView/blob/master/Screenshot_2016-03-25-00-32-03_cn.brtn.bbm.png?raw=true "Optional title")
when use adapter.notify..,will be 
![啦啦啦啦](https://github.com/Guolei1130/DragGridView/blob/master/Screenshot_2016-03-25-00-32-12_cn.brtn.bbm.png?raw=true "Optional title")

and this gridview be included in the scrollview

**Comment by TWiStErRob** [comment]
There's no distortion there. It's centercrop with different sizes. Glide read the size of the view to size the bitmap. Can you share your XML and Glide.with line in the adapter (whole getView maybe be even better)? There must be something changing the size of the ImageView between first and second bind. You either need to prevent the layout change from happening, or use `.override` to fix the size of the image to a certain value.

**Comment by Guolei1130** [comment]
thank you,my code is wrong.
