### ISSUE TITLE
Gif + override(int w, int h) => animation stops working

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#1085]
**Glide Version**: 3.7.0
**Integration libraries**: none
**Device/Android Version**: many (emulator with android 6, galaxy alpha with android 5)

**Issue details / Repro steps / Use case background**: 
I'm trying to show gifs/images/videos in a `RecyclerView`. For the sake of speed I always use the exact same preview image size so that I end up with one preview image size cache. As soon as I add `override` to the glide builder, the gif stops animation. The `loadThumb` function is the function I use. I added a simple comment that shows which line "introduces" the problem... Removing this line makes the gif animated, adding it makes the gif static...

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java

private static DrawableRequestBuilder getPreview(DrawableRequestBuilder requestBase)
{
    return requestBase
            .clone()
            .override(GlideHelper.PREVIEW_SIZE, GlideHelper.PREVIEW_SIZE)
            .dontTransform()
            .animate(ANIMATOR)
            .diskCacheStrategy(DiskCacheStrategy.RESULT);
}

public static void loadThumb(@Nullable IMedia photo, @NonNull final ImageView image)
{
    DrawableRequestBuilder requestBase = photo.getRequestBase(image.getContext());

    requestBase
            .dontAnimate()
            .dontTransform()
            // THIS line results in NOT animating gifs
            .override(GlideHelper.SMALLER_SCREEN_WIDTH / 2, GlideHelper.SMALLER_SCREEN_WIDTH / 2) 
            .thumbnail(getPreview(requestBase))
            .into(new GlideDrawableTarget(image));
}
```

**Comment by TWiStErRob** [comment]
What is `requestBase`?

Does the animation happen if you wait a few minutes? Try to add diskCacheStrategy(SOURCE) for **both** loads, just to confirm it's not slow GIF loading.

**Comment by MFlisar** [comment]
When I click on an image in my `RecyclerView` I show it in a big image with following function (I use the image from the `RecyclerView` as preview image):

    public static void loadFull(@NonNull IMedia photo, @NonNull final ImageView image, @Nullable final ImageLoadingListener listener)
    {
        DrawableRequestBuilder requestBase = photo.getRequestBase(image.getContext());

        requestBase
                .dontAnimate()
                .dontTransform()
                .placeholder(image.getDrawable())
                .thumbnail(getPreview(requestBase))
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .listener(new GlideDrawableListener<Uri>() {
                    @Override
                    public void onSuccess(Uri source) {
                        if (listener != null) {
                            listener.onLoaded();
                        }
                    }

                    @Override
                    public void onFail(Uri source) {
                        if (listener != null) {
                            listener.onFailed();
                        }
                    }
                })
                .into(new GlideDrawableTarget(image));
    }

Here it is working again. As said, removing the `override`from the preview function solves the problem as well.

Request base is like following:

    @Override
    public DrawableRequestBuilder getRequestBase(Object linkedObject)
    {
        RequestManager manager = null;
        if (linkedObject instanceof Activity)
            manager = Glide.with((Activity)linkedObject);
        else if (linkedObject instanceof Fragment)
            manager = Glide.with((Fragment)linkedObject);
        else if (linkedObject instanceof Context)
            manager = Glide.with((Context)linkedObject);
        else
            throw new RuntimeException("Can't link image loader to " + linkedObject.getClass());

        DrawableRequestBuilder<Uri> request = manager
                .load(getUri())
                .diskCacheStrategy(DiskCacheStrategy.RESULT);

        if (getSignature() != null)
            request.signature(getSignature());

        return request;
    }

I tried adding DiscCache.ALL to the preview and thumb image loader, but this does not change anything. And I'm using local files only anyway...

This gif (my testing gif) breaks for example:
![gif](https://cloud.githubusercontent.com/assets/2437726/14014172/3372df2c-f1b1-11e5-814a-90650a752a62.gif)

**Comment by TWiStErRob** [comment]
I asked for SOURCE to disable result cache, please try that or NONE should confirm as well. ALL won't change anything.

**Comment by MFlisar** [comment]
Using DiscCache.SOURCE everywhere solves the problem...

**Comment by TWiStErRob** [comment]
So I think what you're seeing is #281. Since you're using local files you can just disable disk cache (NONE) to get the fastest load times.

That GIF is really badly compressible because of dithering. The image contains about 16 different colors if you look at it from afar, I don't know why the encoder choose to dither that much. Also it's not possible to delta-encode because the dither pixels are jumping around. I think if you wait long enough with your original cache setup + override, it should load.

That said, it's still worth looking into why the GifEncoder is so slow for this image. Maybe there's an algorithm whose asymptotic complexity is bad.

**Comment by TWiStErRob** [comment]
What is `ANIMATOR`?

**Comment by MFlisar** [comment]
So you would suggest to use DiscCache.NONE for gifs or for all local files?

DiscCache.RESULT definitely has a big impact on second display for local images, especially if they are really big of course..

ANIMATOR is a simple alpha animator: 

    private static final ViewPropertyAnimation.Animator ANIMATOR =
            new ViewPropertyAnimation.Animator() {
                @Override
                public void animate(View view) {
                    view.setAlpha(0f);
                    view.animate().alpha(1f);
                }
            };

**Comment by TWiStErRob** [comment]
For local files just think about how cache works: you have an image on disk that you load and SOURCE would save the exact same bytes into Glide cache, and you can't use RESULT for GIFs because it's too slow. So SOURCE is pointless for any local file, RESULT would make sense if the original is really big or you use a lot of transformation.

These are the cases for `diskCacheStrategy` I can quickly think of:
* NONE for local GIF
* SOURCE for remote GIF
* RESULT for single-use remote non-GIF (default)
* SOURCE or ALL for multi-use remote non-GIF
* NONE or RESULT for local non-GIF
* RESULT for large or effect-transformed local non-GIF
I think this is improved in v4 already.

Tip for fading: `.animate(R.anim.abc_fade_in)` (or `.animate(android.R.anim.fade_in)` if you're targeting new devices only) should do the same.

**Comment by TWiStErRob** [comment]
Something is weird here, I tried reproducing this, but with no luck.
I found that GifEncoder only takes a long time if there's a transformation which you don't have, because of the `.dontTransform()` calls.

Can you please try to [enable logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) to see if there's something that stands out, when the GIF is not animated?
```shell
adb shell setprop log.tag.GenericRequest VERBOSE
adb shell setprop log.tag.Engine VERBOSE
adb shell setprop log.tag.EngineJob VERBOSE
adb shell setprop log.tag.DecodeJob VERBOSE
adb shell setprop log.tag.GifEncoder VERBOSE
adb shell setprop log.tag.AnimatedGifEncoder VERBOSE
```

**Comment by TWiStErRob** [comment]
It's also worth noting that if you have a debugger attached everything takes significantly longer, but it is still animating for me, just much slower.

**Comment by MFlisar** [comment]
Here's the output when showing a `RecyclerView` with 5 images where the last one is the above posted gif:

	03-24 13:52:08.829 28060-28060/com.mflisar.gallery D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
	03-24 13:52:08.914 28060-28060/com.mflisar.gallery D/com.mflisar.gallery.activities.mvp.MainActivityMVP: [MainActivityMVP-426]	INFO: level=1, selectedImage=null, selectedFolder=/storage/emulated/0/Pictures/A Test FORMATS, movedUp=true
	03-24 13:52:08.919 28060-28306/com.mflisar.gallery D/com.mflisar.gallery.rx.RXManagerCache: [RXManagerCache-55]	CACHED=EXISTS
	03-24 13:52:08.929 28060-28060/com.mflisar.gallery D/com.mflisar.gallery.activities.mvp.MainActivityMVP: [MainActivityMVP-261]	Photos: 5
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.044375 this: 180196834
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.197542 this: 180196834
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 0.40270799999999995 size: 0.39200592041015625 fromCache: true this: 180196834
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 0.24120799999999998ms, key: EngineKey{content://media/external/video/media/24118+com.bumptech.glide.signature.MediaStoreSignature@53a16c70+[72x72]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 0.637 this: 180196834
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 0.6972079999999999 this: 180196834
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.020166999999999997 this: 774651565
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.0885 this: 774651565
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 0.239167 size: 0.98876953125 fromCache: true this: 774651565
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 0.16591699999999998ms, key: EngineKey{content://media/external/video/media/24118+com.bumptech.glide.signature.MediaStoreSignature@53a16c70+[360x360]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 0.399542 this: 774651565
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 0.461458 this: 774651565
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.036791 this: 966995502
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.15525 this: 966995502
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 0.309083 size: 0.061798095703125 fromCache: true this: 966995502
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 0.16674999999999998ms, key: EngineKey{content://media/external/images/media/23759+com.bumptech.glide.signature.MediaStoreSignature@87ddf679+[72x72]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 0.48470799999999997 this: 966995502
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 0.549833 this: 966995502
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.025417 this: 679155881
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.120125 this: 679155881
	03-24 13:52:08.934 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 0.264083 size: 0.6866455078125 fromCache: true this: 679155881
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 0.15562499999999999ms, key: EngineKey{content://media/external/images/media/23759+com.bumptech.glide.signature.MediaStoreSignature@87ddf679+[360x360]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 0.49645799999999995 this: 679155881
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 0.578542 this: 679155881
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.026958 this: 926416698
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.120166 this: 926416698
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 0.24987499999999999 size: 0.0431060791015625 fromCache: true this: 926416698
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 0.14825ms, key: EngineKey{content://media/external/images/media/23758+com.bumptech.glide.signature.MediaStoreSignature@d4586e6d+[72x72]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 0.40570799999999996 this: 926416698
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 0.455916 this: 926416698
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.020333 this: 163812965
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.078958 this: 163812965
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 0.178416 size: 0.6866455078125 fromCache: true this: 163812965
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 0.128625ms, key: EngineKey{content://media/external/images/media/23758+com.bumptech.glide.signature.MediaStoreSignature@d4586e6d+[360x360]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 0.326625 this: 163812965
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 0.371208 this: 163812965
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.026666 this: 232872288
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.130083 this: 232872288
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 0.27275 size: 0.03715705871582031 fromCache: true this: 232872288
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 0.166959ms, key: EngineKey{content://media/external/images/media/23757+com.bumptech.glide.signature.MediaStoreSignature@258f4367+[72x72]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 0.45916599999999996 this: 232872288
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 0.520458 this: 232872288
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.022625 this: 701172067
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.107708 this: 701172067
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 0.21779199999999999 size: 0.5942058563232422 fromCache: true this: 701172067
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 0.119959ms, key: EngineKey{content://media/external/images/media/23757+com.bumptech.glide.signature.MediaStoreSignature@258f4367+[360x360]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 0.365042 this: 701172067
	03-24 13:52:08.939 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 0.414375 this: 701172067
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.024458999999999998 this: 636660620
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.089667 this: 636660620
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.025792 this: 888029659
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.091875 this: 888029659
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/Engine: Started new load in 0.16949999999999998ms, key: EngineKey{0+com.bumptech.glide.load.resource.gif.GifFrameLoader$FrameSignature@d6255886+[72x72]+''+'GifFrameResourceDecoder.com.bumptech.glide.load.resource.gif'+''+''+''+''}
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 0.40825 this: 888029659
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 0.460667 this: 888029659
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 1.4982499999999999 size: 1.5635671615600586 fromCache: true this: 636660620
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 1.455125ms, key: EngineKey{content://media/external/images/media/23922+com.bumptech.glide.signature.MediaStoreSignature@d37c7f48+[72x72]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 1.675959 this: 636660620
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 1.7269169999999998 this: 636660620
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: Got onSizeReady in 0.017166999999999998 this: 416995519
	03-24 13:52:08.944 28060-28060/com.mflisar.gallery V/GenericRequest: finished setup for calling load in 0.079958 this: 416995519
	03-24 13:52:08.949 28060-32203/com.mflisar.gallery V/DecodeJob: Fetched data in 0.062833, key: EngineKey{0+com.bumptech.glide.load.resource.gif.GifFrameLoader$FrameSignature@d6255886+[72x72]+''+'GifFrameResourceDecoder.com.bumptech.glide.load.resource.gif'+''+''+''+''}
	03-24 13:52:08.954 28060-32203/com.mflisar.gallery V/DecodeJob: Decoded from source in 5.484792, key: EngineKey{0+com.bumptech.glide.load.resource.gif.GifFrameLoader$FrameSignature@d6255886+[72x72]+''+'GifFrameResourceDecoder.com.bumptech.glide.load.resource.gif'+''+''+''+''}
	03-24 13:52:08.954 28060-32203/com.mflisar.gallery V/DecodeJob: Transformed resource from source in 0.040417, key: EngineKey{0+com.bumptech.glide.load.resource.gif.GifFrameLoader$FrameSignature@d6255886+[72x72]+''+'GifFrameResourceDecoder.com.bumptech.glide.load.resource.gif'+''+''+''+''}
	03-24 13:52:08.954 28060-32203/com.mflisar.gallery V/DecodeJob: Transcoded transformed from source in 0.034832999999999996, key: EngineKey{0+com.bumptech.glide.load.resource.gif.GifFrameLoader$FrameSignature@d6255886+[72x72]+''+'GifFrameResourceDecoder.com.bumptech.glide.load.resource.gif'+''+''+''+''}
	03-24 13:52:08.959 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 0.187667 size: 0.2716064453125 fromCache: true this: 416995519
	03-24 13:52:08.959 28060-28060/com.mflisar.gallery V/Engine: Loaded resource from active resources in 17.027957999999998ms, key: EngineKey{content://media/external/images/media/23922+com.bumptech.glide.signature.MediaStoreSignature@d37c7f48+[360x360]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
	03-24 13:52:08.959 28060-28060/com.mflisar.gallery V/GenericRequest: finished onSizeReady in 17.340457999999998 this: 416995519
	03-24 13:52:08.959 28060-28060/com.mflisar.gallery V/GenericRequest: finished run method in 17.415167 this: 416995519
	03-24 13:52:08.979 28060-28060/com.mflisar.gallery V/GenericRequest: Resource ready in 34.047582999999996 size: 0.2716064453125 fromCache: false this: 888029659

Gif is static after this and no more debug outputs are comming in 1 minute...

**Comment by TWiStErRob** [comment]
All I can see from this that everything was loaded from active resources, and then a single first (0th) frame was loaded. I'm not sure what is stopping the gif drawable from continuing. Can you check for usages of `Animatable.stop()` in your codebase?

Also can you try to reproduce this in a sample app or a PR against https://github.com/TWiStErRob/glide-support?
