### ISSUE TITLE
Glide does not load fresh image from server

### ISSUE THREAD

**Issue by Sutirth** [bumptech/glide#1095]
Glide version = compile 'com.github.bumptech.glide:glide:3.6.1' 

Scenario : I am allowing user to update his/her profile image which is done perfectly fine. On success I am directing them to profile activity where I use glide to fetch image from server and it still shows me stale Image everywhere in my application.

Glide LoadLine:

   GlideUrl glideUrl = new GlideUrl(URL, new LazyHeaders.Builder()
                .addHeader("access_token", ACCESS_TOKEN)
                .build());

        Glide.with(getApplicationContext()).load(glideUrl).dontAnimate()
                .into(profilePicUser);

       <de.hdodenhof.circleimageview.CircleImageView
           android:id="@+id/profilePicUser"
           android:layout_width="96dp"
           android:layout_height="96dp"
           android:layout_marginTop="20dp"
           android:layout_marginLeft="16dp"
           android:layout_marginBottom="20dp"
           app:civ_border_color="#ffffff"
           app:civ_border_width="2dp"
           />

**Comment by TWiStErRob** [comment]
If Glide were to make a roundtrip and fetch the latest image every time, there would be no point to cache. Even though you can actually achieve that by `.diskCacheStrategy(NONE).skipMemoryCache(true)`, see #624 for more explanation and a better way of doing based on `.signature()`. You'll find many related issues at the bottom too.

**Comment by Sutirth** [comment]
@TWiStErRob  Thanks for clearing doubt so I do hey field response from server as 
"profileImageUpdatedAt": "1970-01-01T05:30:00Z"

So should I use the glide as this

 Glide.with(getApplicationContext()).load(glideUrl).dontAnimate()
                .signature(new StringSignature(1970-01-01T05:30:00Z))
                .into(profilePicUser); 

and Then I would be able to get fresh images or am I missing something again ??

**Comment by TWiStErRob** [comment]
Yes, just use the one you get:
```java
.load(profile.url).signature(new StringSignature(profile.imageUpdatedAt))
```

Note that the date you quoted looks weird (it's essentially 0 in IST timezone), make sure the server returns you a new valid date every time you update the profile picture. That date has to be different from all the previous values, ideally it should be literally the time of upload.

**Comment by Sutirth** [comment]
@TWiStErRob  So based upon your explanation I quickly made dummy json. So rest assure my backend will pick the exact timedate variable it will help me to clear the issue then I hope thnx a ton again. I would get back with the feedback as well.

**Comment by Sutirth** [comment]
@TWiStErRob  I tried adding .load(profile.url).signature(new StringSignature(profileimageUpdatedAt)) But I am still unable to get fresh images from server

**Comment by TWiStErRob** [comment]
Enable logging to see why it hits the cache: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow
