### ISSUE TITLE
How can I get the cache picture‘s path（address） and name？I wanna to Get the Flie that I cached.

### ISSUE THREAD

**Issue by ycpbyht** [bumptech/glide#1100]
When i use the Glide to display picture,I wanna to get the picture file.
For example,i display a gif or JPG in my program,but i can't get the file(XXX.gif or XXX.jpg),how can I
find it ?
 i need get the file that i cached,not the cache DIr
THX

**Comment by TWiStErRob** [comment]
Please detail what are you plans with it, the solution varies widely based on that.

**Comment by ycpbyht** [comment]
i wanna  to find a method that return the file that i cached.
Like this  : String path="https://avatars2.githubusercontent.com/u/11882573?v=3&s=96.jpg";(My head img url),
if i wanna to display it ,I use  Clide.with(mContext).load(path).into(container);
but How can i get the My head Img file (headImg.jpg)?
Because the Glide use the Net url to judge if the image had cached, so i wanna to know if the Glide has a  method that i can eassly to get the file ,like this 

Glide.getFile(path){
//path is my head img url
XXX
return File/Bitmap;
}

THX

**Comment by TWiStErRob** [comment]
I understand what you want to do, my question is why? As in: who would be using that method and what will happen to the return value... as you might have guessed there's no such method as you want it, but there are ways.

**Comment by ycpbyht** [comment]
Because I wanna to get the Pic to do sth.  like to edit it ,or when i find a pic in the APP was very funny that i wanna to shared with my friend by facebook or MSN,but now i can't to find a method to 
achieve this function。

**Comment by TWiStErRob** [comment]
See #459 for sharing and [transformations](https://github.com/bumptech/glide/wiki/Transformations) for manipulation.
