### ISSUE TITLE
has bug in load long Image

### ISSUE THREAD

**Issue by a1018875550** [bumptech/glide#1101]
It's has some bug for load longImage;
```java
Glide.with(activity)
                    .load(image_url)
                    .placeholder(R.drawable.market_icon_app_default_big)
                    .error(R.drawable.market_icon_app_default_big)
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .listener(new RequestListener<String, GlideDrawable>() {
                        @Override
                        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                            holder.image.setImageResource(R.drawable.market_icon_app_default_big);
                            return true;
                        }

                        @Override
                        public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                            holder.image.setImageDrawable(resource);
                            return true;
                        }
                    }).into(holder.image);
```
this is my code
for this imageUrl : http://ww4.sinaimg.cn/large/8a15a1ccgw1f2g5adqsldj20bi9dve81.jpg
When I load long image ;it's can't disply sometimes,It's only show a long white;
But it not display for every longImage;
So I don't why;

**Comment by TWiStErRob** [comment]
Try removing the listener and probably add `.dontAnimate()`. Can you share your xml and a screenshot if it still doesn't work after that?

You might also want to log the exception in `onException`, but make sure you return false in the listener.

**Comment by TWiStErRob** [comment]
You're likely hitting the OpenGL texture limit with that bitmap, especially if you're loading into height=wrap

Also see #700.

**Comment by weidongjian** [comment]
i have the same problem, and  `.dontAnimate()` work for me.
