### ISSUE TITLE
Using Glide to cache images from an Amazon S3 bucket

### ISSUE THREAD

**Issue by wouterdevos** [bumptech/glide#1103]
I want to use Glide to download images from my Amazon S3 bucket, but I would like to use the Amazon Android SDK to achieve this because I do not want to make my bucket public. Is it possible to define a custom model loader that incorporates the networking code from the Amazon SDK? I've seen an example of a custom Glide model loader in this post: https://github.com/bumptech/glide/issues/556, so it looks like it's possible. Unfortunately I don't have a good grasp of how the model loaders work and how I would incorporate the Amazon SDK into this framework.

Any help would be greatly appreciated.

**Comment by TWiStErRob** [comment]
I would assume Amazon's code is similar to Firebase so you could start with that example. Just replace everything with the corresponding Amazon SDK calls. You need a few classes but shouldn't be hard:
You register a ModelLoader.Factory in a GlideModule, the factory creates a ModelLoader (encapsulating your S3 connection) which in turn creates a DataFetcher which retrieves the stream based on a custom model (`FirebaseImage`). Stream to Bitmap will be handled by Glide. This may also help: https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g

**Comment by wouterdevos** [comment]
Thanks for the prompt reply. I'm happy to give it a try, but just so you know, I did try using the code from #556 and I couldn't get it working with Firebase.

**Comment by TWiStErRob** [comment]
That Firebase related code is not tested, I only went as far as calling seemingly correct methods and compiling code, but the Glide flow is correct. Give it a go with S3 (since that's your end goal) and if you're stuck, share your code with stack trace or bad behavior description here; I need more than "it doesn't work" because I've never done it before. Get acquainted to [Wiki}(https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) for getting relevant info in LogCat.

**Comment by wouterdevos** [comment]
I understand you need more info. I'll try with the Amazon SDK and ask for help if I get stuck. Thanks again.

**Comment by FelipeRRM** [comment]
Did you get it working? If you could provide information on how you did it, it would be really useful. I need to implement this on the app I'm working on!

**Comment by avi885** [comment]
I had a similar problem and solved it by making a custom GlideUrl class. Basically you change the url of cached image and use authentication headers only while downloading image from S3. I used this code:

```
public class GlideUrlCustomCacheKey extends GlideUrl {
    @Override
    public String getCacheKey() {
        String url = toStringUrl();
        if (url.contains("?")) {
            return url.substring(0, url.lastIndexOf("?"));
        } else {
            return url;
        }
    }
}
```

**Comment by TWiStErRob** [comment]
@avi885 ah, it's just a simple image Url? Then yes, anything similar to #607 would work.

If you can put the auth info into the request header, you don't even need to create a custom class, just create an instance of `GlideUrl` with the appropriate `LazyHeaders.Builder` passed in.

**Comment by HertelDavid** [comment]
I was looking around for a solution to a similar problem I had with loading images using aws S3. This is my solution using the code @TWiStErRob provided on #556 

`
public class S3ImageModelLoader implements StreamModelLoader<S3Image> {

    private final CottonAmazonS3Accessor accessor;

    public S3ImageModelLoader(CottonAmazonS3Accessor accessor){
        this.accessor = accessor;
    }

    @Override
    public DataFetcher<InputStream> getResourceFetcher(S3Image model, int width, int height) {

        return new DataFetcher<InputStream>(){

            @Override
            public InputStream loadData(Priority priority) throws Exception {

                final CountDownLatch latch = new CountDownLatch(1);
                final AtomicReference<File> fileRef = new AtomicReference<>();

                accessor.downloadFile(model.getKey(), cottonAmazonAccessorType -> {

                    fileRef.set((File) cottonAmazonAccessorType.getPayload());
                    latch.countDown();
                });

                latch.await();

                return new FileInputStream(fileRef.get());
            }

            @Override
            public void cleanup() {
                //To implement 
            }

            @Override
            public String getId() {
                return model.getKey();
            }

            @Override
            public void cancel() {
                //To implement 
            }
        };
    }

    public static class Factory implements ModelLoaderFactory<S3Image, InputStream> {

        private final CottonAmazonS3Accessor accessor;

        public Factory(CottonAmazonS3Accessor accessor){
            this.accessor = accessor;
        }

        @Override
        public ModelLoader<S3Image, InputStream> build(Context context, GenericLoaderFactory factories) {

            return new S3ImageModelLoader(accessor);
        }

        @Override
        public void teardown() {

        }
    }
}

public class S3GlideModule implements GlideModule{

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {

    }

    @Override
    public void registerComponents(Context context, Glide glide) {

        CottonAmazonS3Accessor accessor = new CottonAmazonS3Accessor(context, LoginActivity.credentialsProvider);

        glide.register(S3Image.class, InputStream.class, new S3ImageModelLoader.Factory(accessor));
    }
}

public class S3Image {

    private final String key;

    public S3Image(String key){
        this.key = key;
    }

    public String getKey(){
        return key;
    }
}
`

And the code inside AmazonS3Accessor object I have looks like this

`
public void downloadFile(String key, CottonAmazonS3AccessorListener listener) throws IOException{

        File cache = context.getCacheDir();
        File input = File.createTempFile(key, ".jpg", cache);

        TransferObserver observer = utility.download(AmazonConstants.COTTON_BUCKET_NAME, key, input);

        observer.setTransferListener(new TransferListener() {

            @Override
            public void onStateChanged(int id, TransferState state) {

                Log.d(TAG, state.name());
                if(state == TransferState.COMPLETED){
                    listener.onNotify(new CottonAmazonAccessorType<>(input));
                }
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                Log.d(TAG, "Downloading File!");
            }

            @Override
            public void onError(int id, Exception ex) {
                Log.d(TAG, ex.getMessage());
            }
        });
`

Glide will go to get the InputStream and call the method downloadFile which will notify the listener in the listener in the loadData method which will then countdown on the CountDownLatch. This is just a simple solution that needs more work, but it is working. Most important is the utility.download method in downloadFile.

**Comment by BMarton** [comment]
Did any of you come up with a solution to this? I've seen posts on stackoverlflow suggesting to use a http interceptor either with glide or picasso. Having the proper credentials there and downloading the image with either of these libs should work, but it does not for some reason.
