### ISSUE TITLE
How to load GIF file without auto play?!

### ISSUE THREAD

**Issue by IRMobydick** [bumptech/glide#1107]
Hi there
Is it possible to load gif file without auto playing?
I wanna load first frame of gif file and when user hold `ImageView1 down, trying to play gif

I Try `Animatable` and stop() method but it's not work

			Glide.with(mActivity)
			.load(currentPost.getPostImage().getImageUrl())
			.asGif()
			.diskCacheStrategy(DiskCacheStrategy.ALL)
			.priority(Priority.IMMEDIATE)
			.override(mNewWidth, mNewHeight)
			.listener(new RequestListener<String, GifDrawable>() {

				@Override
				public boolean onException(Exception arg0, String arg1,Target<GifDrawable> arg2, boolean arg3) {
					return false;
				}

				@Override
				public boolean onResourceReady(GifDrawable gif, String arg1, Target<GifDrawable> arg2, boolean arg3, boolean arg4) {
							
					Animatable animate	= (Animatable) gif;
					if(animate.isRunning()){
						animate.stop();
					}
					
					return false;
				}
			})
			.into(holder.POST_IMAGE);

It's not working and still playing GIF , What is wrong?

**Comment by TWiStErRob** [comment]
You return false, which means default behaviour will be executed, which is to start the Drawable, see `GlideDrawableImageViewTarget`.

If you want to go this route write a custom target that extends the above and overrides `onResourceReady` to stop the Drawable right after it was started (super call).

There's an alternative though: to display first frame do:
```java
.load(x).asBitmap().diskCacheStrategy(ALL).into(iv)
```
then when user taps (OnClickListener) load the animation:
```java
.load(x).diskCacheStrategy(SOURCE).into(iv)
```
this has the benefit of not loading the GIF into memory, just a single frame, if you have a grid or large GIF files it may use a lot of memory:

 * `.asBitmap`: single frame as Bitmap, memory: `w*h*bpp`
 * `.asGif` (or omitted): first frame as Bitmap, current frame as Bitmap, next frame as Bitmap, GIF source bytes, memory: `3*w*h*bpp + file size`
