### ISSUE TITLE
MediaStore video Thumbnail load takes very long time

### ISSUE THREAD

**Issue by eicm** [bumptech/glide#1108]
**Glide Version**: 3.7.1

**Integration libraries**: N/A

**Device/Android Version**:  Nexus 5X

**Issue details / Repro steps / Use case background**: I'm trying to load thumbnails for videos registered in MediaStore, it looks like to me that it's not using the thumbnails generated by MediaStore and tries to decode the videos and grabs the frames instead.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with(this).loadFromMediaStore(mediaUri).placeholder(R.drawable.bg_dark).diskCacheStrategy(DiskCacheStrategy.RESULT).dontTransform().override(96, 96).into(imageView);
```

Here's a [sample app](https://github.com/eicm/VideoThumbnailTest)

Here's a link to screen recording of the issue: [Screen recording](https://youtu.be/B1Z0J8PKOxk)

**Comment by TWiStErRob** [comment]
Forked from conversation at https://github.com/bumptech/glide/issues/673#issuecomment-204598553

**Comment by eicm** [comment]
@TWiStErRob did you get a chance to look into it

**Comment by TWiStErRob** [comment]
Re-upload lost repro: [VideoThumbnailTest.zip](https://github.com/bumptech/glide/files/352267/VideoThumbnailTest.zip)

**Comment by gr3ger** [comment]
+1 for this, it's incredibly slow on 4.0 as well.
