### ISSUE TITLE
how to add authorization in header 

### ISSUE THREAD

**Issue by githupfisher** [bumptech/glide#1111]
how to add authorization in header

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/issues?utf8=✓&q=how+to+add+authorization+in+header -> #921

**Comment by TWiStErRob** [comment]
In reply to #1113: how are you using that builder? You need to pass it to `GlideUrl` then `load`.

**Comment by TWiStErRob** [comment]
Please explain how it "doesn't work", you can get the exception in a `.listener()`, see https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener
