### ISSUE TITLE
how to add authorization in header

### ISSUE THREAD

**Issue by githupfisher** [bumptech/glide#1113]
LazyHeaders.Builder builder = new LazyHeaders.Builder()
               .addHeader("Authorization", basicAuth);
it not work .

**Comment by TWiStErRob** [comment]
Please comment on your original issue (#1111). You can cment on closed issues. Don't open a new issue for each comment.

**Comment by githupfisher** [comment]
LazyHeaders.Builder builder = new LazyHeaders.Builder()
.addHeader("Authorization", basicAuth);
 GlideUrl glideUrl = new GlideUrl(urll, builder.build());
 Glide.with(MainActivity.this).load(glideUrl).asBitmap()
