### ISSUE TITLE
won't load static map from google

### ISSUE THREAD

**Issue by 4sskick** [bumptech/glide#1114]
Hi, I used my image view to load from URL that is static map from google. But it won't load. I used with another URL image ended with type like [.png .jpg] Glide loaded it perfectly, but not with this one `https%3A%2F%2Fmaps.googleapis.com%2Fmaps%2Fapi%2Fstaticmap%3Fzoom%3D12%26scale%3D2%26size%3D517x210%26maptype%3Droadmap%20%26markers%3Dcolor%3Ared%7C-7.9524401%2C%20112.6107294`

here I use the config to load
```java
Glide.with(this)                .load(Uri.parse("https%3A%2F%2Fmaps.googleapis.com%2Fmaps%2Fapi%2Fstaticmap%3Fzoom%3D12%26scale%3D2%26size%3D517x210%26maptype%3Droadmap%20%26markers%3Dcolor%3Ared%7C-7.9524401%2C%20112.6107294"))
//                .load("https%3A%2F%2Fmaps.googleapis.com%2Fmaps%2Fapi%2Fstaticmap%3Fzoom%3D12%26scale%3D2%26size%3D517x210%26maptype%3Droadmap%20%26markers%3Dcolor%3Ared%7C-7.9524401%2C%20112.6107294")
                .asBitmap()
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .into(ivMyLocation);
```

**Comment by TWiStErRob** [comment]
Try it with a valid Uri, Chrome can't load that link either.
Notice that your String doesn't have a schema because there's no `:` in it: https://tools.ietf.org/html/rfc3986#section-3

If you get it from somewhere and it's always encoded like this, run it through `Uri.decode` first:
```java
Glide.with(this).load(Uri.parse(Uri.decode("https%3A%2F%2F...")))....;
```

**Comment by PraSoonGosWami** [comment]
http://maps.google.com/maps/api/staticmap?center=22.4585208,88.3854262&zoom=15&size=400x400&sensor=true&key=myapikey

this is getting loaded in chrome but I am not able to load it through glide
@TWiStErRob

**Comment by TWiStErRob** [comment]
@PraSoonGosWami are you running on latest Android? HTTPS restrictions may be kicking in.

**Comment by PraSoonGosWami** [comment]
Yes I have Android 9 on my phone sir

**Comment by sagar091** [comment]
I have http in static map api. I changed to https and miracle happens.
