### ISSUE TITLE
Problem Showing a placeholder of image color 

### ISSUE THREAD

**Issue by soganiabhijeet** [bumptech/glide#1116]
**Glide Version**:3.6.1

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 
I have a doubt on using glide. So I m trying to create a light placeholder before the actual image is loaded. The work of computing the placeholder is done on a different thread and on its success I am calling glide to load the image. 

We guys are using RxJava for background computation. 
loadImageOnBackground() method is called on onBindViewHolder of adapter. 

The problem I am facing is that the final image is shown on a different ImageView due to recycling nature of recyclerView. Any help would be appreciated. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
private void loadImageOnBackground(String imgBase, String imgUrl, ImageView imageView) {
    blurImageDetector = Observable.create(new Observable.OnSubscribe<Drawable>() {
        @Override
        public void call(Subscriber<? super Drawable> subscriber) {
            subscriber.onNext(ImageUtils.getPreviewPlaceholder(context, imgBase));
        }
    });
    blurImageSubscriber = blurImageDetector.subscribeOn(Schedulers.computation())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(returnValue -> addBlurredImage(returnValue, imgUrl, imageView));

}

private void addBlurredImage(Drawable placeholder, String imgUrl, ImageView imageView) {
    Glide.with(context).load(imgUrl).placeholder(placeholder).into(imageView);
}
```

**Comment by TWiStErRob** [comment]
When you start binding some other data you have cancel the async operations in `onBindViewHolder`:
```java
if (holder.subscription != null) holder.subscription.cancel();
Glide.clear(holder.imageView);
holder.subscription = loadImageOnBackground(..., holder.imageView);
```
If the code you posted is in the ViewHolder already, you can just add the above to the beginning of `loadImageOnBackground`.

---

Based on your variable names (=assuming the placeholder is a blurred image of imgBase), a simpler solution would be:
```java
Glide.with(context)
     .load(imgUrl)
     .thumbnail(Glide.with(context)
                     .load(imgBase)
                     .override(SMALL_SIZE, SMALL_SIZE)
                     .transform(new BlurTransformation(context))
     )
     .into(imageView);
```
This also caches the result inside Glide, so the thumbnail will be displayed very fast (from memory cache) the next time it's loaded or the same thumbnail is shown for multiple items.

**Comment by soganiabhijeet** [comment]
Hi 
Sorry for the late reply.
Small doubt: what are SMALL_SIZE in override?
And any source for BlurTransformation ?

**Comment by ndeokar** [comment]
@soganiabhijeet  i am not sure about SMALL_SIZE variable but its just the height and width of the placeholder image which ideally should be of same size of the target imageview.

and here is the reference of the the BlurTransform. 

@TWiStErRob : correct me if i wrong! thank you!

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.renderscript.Allocation;
import android.renderscript.Element;
import android.renderscript.RenderScript;
import android.renderscript.ScriptIntrinsicBlur;

import com.bumptech.glide.Glide;
import com.bumptech.glide.load.Transformation;
import com.bumptech.glide.load.engine.Resource;
import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool;
import com.bumptech.glide.load.resource.bitmap.BitmapResource;

public class BlurTransformation implements Transformation<Bitmap> {

    private static int MAX_RADIUS = 25;
    private static int DEFAULT_DOWN_SAMPLING = 1;

    private Context mContext;
    private BitmapPool mBitmapPool;

    private int mRadius;
    private int mSampling;

    public BlurTransformation(Context context) {
        this(context, Glide.get(context).getBitmapPool(), MAX_RADIUS, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, BitmapPool pool) {
        this(context, pool, MAX_RADIUS, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, BitmapPool pool, int radius) {
        this(context, pool, radius, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, int radius) {
        this(context, Glide.get(context).getBitmapPool(), radius, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, int radius, int sampling) {
        this(context, Glide.get(context).getBitmapPool(), radius, sampling);
    }

    public BlurTransformation(Context context, BitmapPool pool, int radius, int sampling) {
        mContext = context.getApplicationContext();
        mBitmapPool = pool;
        mRadius = radius;
        mSampling = sampling;
    }

    @Override
    public Resource<Bitmap> transform(Resource<Bitmap> resource, int outWidth, int outHeight) {
        Bitmap source = resource.get();

        int width = source.getWidth();
        int height = source.getHeight();
        int scaledWidth = width / mSampling;
        int scaledHeight = height / mSampling;

        Bitmap bitmap = mBitmapPool.get(scaledWidth, scaledHeight, Bitmap.Config.ARGB_8888);
        if (bitmap == null) {
            bitmap = Bitmap.createBitmap(scaledWidth, scaledHeight, Bitmap.Config.ARGB_8888);
        }

        Canvas canvas = new Canvas(bitmap);
        canvas.scale(1 / (float) mSampling, 1 / (float) mSampling);
        Paint paint = new Paint();
        paint.setFlags(Paint.FILTER_BITMAP_FLAG);
        canvas.drawBitmap(source, 0, 0, paint);

        RenderScript rs = RenderScript.create(mContext);
        Allocation input = Allocation.createFromBitmap(rs, bitmap, Allocation.MipmapControl.MIPMAP_NONE,
                Allocation.USAGE_SCRIPT);
        Allocation output = Allocation.createTyped(rs, input.getType());
        ScriptIntrinsicBlur blur = ScriptIntrinsicBlur.create(rs, Element.U8_4(rs));

        blur.setInput(input);
        blur.setRadius(mRadius);
        blur.forEach(output);
        output.copyTo(bitmap);

        rs.destroy();

        return BitmapResource.obtain(bitmap, mBitmapPool);
    }

    @Override public String getId() {
        return "BlurTransformation(radius=" + mRadius + ", sampling=" + mSampling + ")";
    }
}

**Comment by soganiabhijeet** [comment]
Hi all,
The blurTransformation is not working. 
I tried debugging and found that transform() is not called. Any assistance?

/**
 * Created by abhijeetsogani on 4/11/16.
 */

import android.annotation.TargetApi;
import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.os.Build;
import android.renderscript.Allocation;
import android.renderscript.Element;
import android.renderscript.RenderScript;
import android.renderscript.ScriptIntrinsicBlur;

import com.bumptech.glide.Glide;
import com.bumptech.glide.load.Transformation;
import com.bumptech.glide.load.engine.Resource;
import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool;
import com.bumptech.glide.load.resource.bitmap.BitmapResource;




public class BlurTransformation implements Transformation {

    private static int MAX_RADIUS = 25;
    private static int DEFAULT_DOWN_SAMPLING = 1;

    private Context mContext;
    private BitmapPool mBitmapPool;

    private int mRadius;
    private int mSampling;

    public BlurTransformation(Context context) {
        this(context, Glide.get(context).getBitmapPool(), MAX_RADIUS, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, BitmapPool pool) {
        this(context, pool, MAX_RADIUS, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, BitmapPool pool, int radius) {
        this(context, pool, radius, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, int radius) {
        this(context, Glide.get(context).getBitmapPool(), radius, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, int radius, int sampling) {
        this(context, Glide.get(context).getBitmapPool(), radius, sampling);
    }

    public BlurTransformation(Context context, BitmapPool pool, int radius, int sampling) {
        mContext = context.getApplicationContext();
        mBitmapPool = pool;
        mRadius = radius;
        mSampling = sampling;
    }

//my phone has marshamallow
    @TargetApi(Build.VERSION_CODES.M)
    @Override
    public Resource transform(Resource resource, int outWidth, int outHeight) {
        Bitmap source = (Bitmap) resource.get();

        int width = source.getWidth();
        int height = source.getHeight();
        int scaledWidth = width / mSampling;
        int scaledHeight = height / mSampling;

        Bitmap bitmap = mBitmapPool.get(scaledWidth, scaledHeight, Bitmap.Config.ARGB_8888);
        if (bitmap == null) {
            bitmap = Bitmap.createBitmap(scaledWidth, scaledHeight, Bitmap.Config.ARGB_8888);
        }

        Canvas canvas = new Canvas(bitmap);
        canvas.scale(1 / (float) mSampling, 1 / (float) mSampling);
        Paint paint = new Paint();
        paint.setFlags(Paint.FILTER_BITMAP_FLAG);
        canvas.drawBitmap(source, 0, 0, paint);

        RenderScript rs = RenderScript.create(mContext);
        Allocation input = Allocation.createFromBitmap(rs, bitmap, Allocation.MipmapControl.MIPMAP_NONE,
                Allocation.USAGE_SCRIPT);
        Allocation output = Allocation.createTyped(rs, input.getType());
        ScriptIntrinsicBlur blur = ScriptIntrinsicBlur.create(rs, Element.U8_4(rs));

        blur.setInput(input);
        blur.setRadius(mRadius);
        blur.forEach(output);
        output.copyTo(bitmap);

        rs.destroy();

        return BitmapResource.obtain(bitmap, mBitmapPool);
    }

    @Override public String getId() {
        return "BlurTransformation(radius=" + mRadius + ", sampling=" + mSampling + ")";
    }
}

**Comment by ndeokar** [comment]
@soganiabhijeet  : can you just add your code of calling Glide.

**Comment by soganiabhijeet** [comment]
final Target<GlideDrawable> into = Glide.with(context)
                .load(dealListModel.pic)
                .thumbnail(Glide.with(context)
                        .load(dealListModel.imgBase)
                        .transform(new BlurTransformation(context))
                ).override(CommonUtils.getDpInPixels(context,300),CommonUtils.getDpInPixels(context,200))
                .into(holder.imageLayout);

**Comment by TWiStErRob** [comment]
@soganiabhijeet [wasabeef's library](https://github.com/wasabeef/glide-transformations) is the first 3 results for `glide blurtransformation`, `SMALL_SIZE` is just that: a relatively small pixel size, say `300`.
I was assuming that by "light placeholder" and "placeholder of image color" you meant a low quality image that can be loaded fast.
