### ISSUE TITLE
Black background in a transparent GIF

### ISSUE THREAD

**Issue by aleksandrmozgovoi** [bumptech/glide#1118]
Hi, i want to use a transparent GIF and stop it on the event.
So I start animating `Glide.with(getApplicationContext()).load(R.drawable.gif3).asGif().into(gifImageView);`
So I would like to freeze the GIF on the first frame
`Glide.with(getApplicationContext()).load(R.drawable.gif3).asBitmap().into(gifImageView);`
But after stopping the background becomes black.
Here is a video as it happens [http://recordit.co/2Q5Yyqvk6O](http://recordit.co/2Q5Yyqvk6O)

How to fix it?
Thank you.

**Comment by TWiStErRob** [comment]
Which version of Glide are you using?

Looks like the black frame is always the same one, likely the first.
If you just want to start-stop, you can do:
```java
((Animatable)gifImageView.getDrawable()).*();
```
no need to fully reload the file. See #908 and #1107 for related comments.

**Comment by aleksandrmozgovoi** [comment]
I use glide:3.7.0
[link frame](https://drive.google.com/open?id=0B9N8XSJ7TzsFWDlNM1QzZkRnT2s)
It works, but show the first frame?
`Drawable drawable = gifImageView.getDrawable();
    if (drawable instanceof Animatable) {
    Animatable gif = (Animatable)drawable;
    if (gif.isRunning()) gif.stop(); else gif.start();
   }`

**Comment by aleksandrmozgovoi** [comment]
In my case, it is possible to return the first frame?

**Comment by TWiStErRob** [comment]
You can load `asGif()` and cast to `GifDrawable` to manipulate.
You can start/stop it, and there's a `getFirstFrame()` method if you want to replace it, but I'm not sure if it's safe to call `gifIageView.setImageBitmap(gifDrawable.getFirstFrame())`. Your current solution may be best if you need to reset to first frame.

Which emulator are you playing on? I tried Nexus 5X API 23 on the new emulator (SDK Tools 25) and it didn't reproduce. I tried both 3.7.0 and 3.8.0-SNAPSHOT. You might want to try [3.8.0](https://github.com/bumptech/glide/wiki/Snapshots) anyway, it has a few GIF related fixes. Try to clear the cache too (or uninstall your app and install it again)

If your code samples above are not exactly what you run, please update/share them.

Tip regardless everything: for faster load time you should use `.diskCacheStrategy(NONE)` for local GIFs (File/R.drawable/R.raw) and `.diskCacheStrategy(SOURCE)` for HTTP ones.
