### ISSUE TITLE
Exif orientation 6 (90 CCW) not respected

### ISSUE THREAD

**Issue by evelyne24** [bumptech/glide#1120]
**Glide Version**: 4.0.0-SNAPSHOT

**Integration libraries**: okhttp3-integration:2.0.0-SNAPSHOT, recyclerview-integration:2.0.0-SNAPSHOT

**Device/Android Version**: Any Android phone, e.g. Nexus 5X Android 6.0.1, Nexus 6

**Issue details / Repro steps / Use case background**: [This image](https://test-cdn0.deliveroo.co.uk/media/restaurants/12709/720x360.jpg) needs to be rotated 90 CCW but it is not (the orientation is 8 - 90 CCW, also 6 - 90 CW has the same result). Loading it from the network through the provided url or saving the image manually and loading it as a drawable resource has the same effect: the image is NOT correctly rotated. 
By contrast, download the image as drawable and set it as `android:src` directly on an ImageView. It will be correctly rotated. Through Glide, it is not.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```
Glide.with(imageView.getContext())
                    .asDrawable()
                    .load(R.drawable.test).into(imageView);
```

**Layout XML**:
```xml
<ImageView
                    android:id="@+id/restaurant_image"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:scaleType="fitXY"/>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

![with_glide](https://cloud.githubusercontent.com/assets/239384/14387638/3ecfa312-fda2-11e5-8d0e-f490c3f1017b.png)
![without_glide](https://cloud.githubusercontent.com/assets/239384/14387639/3ed28ba4-fda2-11e5-8337-c6c7a224eec3.png)

**Comment by TWiStErRob** [comment]
*I'm assuming the top picture you've taken the screenshot of has `orientation == 8` and the bottom is the drawable one without any rotation.*

I think Glide is doing the right thing, here's what I found:
(I used v3 to test, but it should be the same in v4)
 * 6 means "The 0th row is the visual right-hand side of the image, and the 0th column is the visual top." according to [EXIF](http://www.exif.org/Exif2-2.PDF), which is equivalent to a 90 CW rotation as you said.
 * Android BitmapFactory and hence `Resources.getDrawable()` doesn't handle any EXIF tags
  it loads the raw pixels which are the landscape with blue plate in lower right corner
 * Chrome handles rotation
  displays the image as a portrait image with blue plate in lower left corner
 * The orientation is Rotate 90 CW as reported by [metapicz.com](http://metapicz.com/#landing?imgsrc=https%3A%2F%2Ftest-cdn0.deliveroo.co.uk%2Fmedia%2Frestaurants%2F12709%2F720x360.jpg)  
  it shows the original landscape image as in the raw JPEG file with blue plate in lower right
 * The orientation is "right top" as reported by IrfanView  
  it displays the image portrait with blue plate in lower left corner
 * Glide v3 loads the image via BitmapFactory which is the landscape image with blue plate in lower right corner; then it recognizes that the EXIF rotation is `ExifInterface.ORIENTATION_ROTATE_90 == 6` and creates a matrix accordingly; then it creates a new rotated image with blue plate in the lower left corner

**Comment by evelyne24** [comment]
Thank you, makes a lot more sense now, sorry for rushing in :) 
Indeed that's the case, Glide DOES parse the exif into correctly.
One more question: is there a way to completely ignore the exif?

**Comment by TWiStErRob** [comment]
#665

**Comment by evelyne24** [comment]
Cheers! Really appreciate your help! :+1:
