### ISSUE TITLE
Glide doesn't load image in ListView

### ISSUE THREAD

**Issue by anthony3444** [bumptech/glide#1121]
I have a ViewPager with 3 fragments inside. Each fragment is a list to retrieve some exercises from a remote server. The 3 fragments are in order: "explore", "favorite", "recent".

In "explore" list, all images correctly appear. unfortunately in the "favorite" no image appears (just place holder thumbnail).

This is my common adapter:

```java
@Override public View getView(int position, View convertView, ViewGroup parent) {
    final T item = getItem(position);
    ....
    Glide.with(getContext())
        .load(UIUtils.getThumbnailImageUrl(item.images))
        .placeholder(R.drawable.default_thumbnail_picture)
        .crossFade()
        .listener(new RequestListener<String, GlideDrawable>() {
            @Override
            public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                return false;
            }

            @Override
            public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                return false;
            }
        })
        .into(viewHolder.mExerciseImageView);
	return convertView;
}
```

I put a breakpoint in "onException()" function, and there are several break. Unfortunately, exception is always equal at null...

Could you help me guys?

Thank you very much!

**Comment by TWiStErRob** [comment]
You may be passing a `null` reference to `.load()` or you may have an OOM.
Double check the return value of `UIUtils.getThumbnailImageUrl(item.images)`.
If that's not it, then try enabling internal logging as said on the [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling).

**Comment by anthony3444** [comment]
Thanks for your reply. No, the reference is never null, I checked that before. There is no OOM too. You know in my first list (first tab named "Explore") there is a full exercises list with the thumbnail associated at each exercise. In my second list (named "Favorite") there is just favorite exercises list. So if I can see the thumbnail of exercises in the first list, normally I must see in my favorite too. But it's not the case. 

Before to use Glide, I used Volley (with NetworkImage) and it worked correctly. But the performance was not so good to compare with Glide. So the code is the same, I just change the image loading by Glide. 

I add: these 2 lists start loading data at the same time (ViewPager instanciate 2 first fragments).

Thanks for your help by advance!

**Comment by TWiStErRob** [comment]
Try to find clues in https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
Another way of attacking it is putting a breakpoint in onException and checking where that null is coming from by walking up the stack frames in the Debug view.

**Comment by Tanyangfan** [comment]
@TWiStErRob I have the same trouble. And I find ues "asBitmap" can solve it, but the "asBitmap" can't be used with "crossFade" at the same time. In fact, there are some similary troubles when using "crossFade".

**Comment by TWiStErRob** [comment]
@Tanyangfan yes it can: #1096 (available in [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots))

**Comment by anthony3444** [comment]
Ok guys, I resolve the problem: instead to use `.crossFade()` function I use `.animate(R.anim.anim_glide_fade_in)` with fade_in xml:

```
<alpha xmlns:android="http://schemas.android.com/apk/res/android"
    android:interpolator="@android:anim/linear_interpolator"
    android:fromAlpha="0.0" android:toAlpha="1.0"
    android:duration="300" />
```

There is no problem no to show ImageView, especially RoundedImageView.

Thanks !

**Comment by TWiStErRob** [comment]
Ah, damn, I always forget about the roundy problem when someone says "not loaded": https://github.com/bumptech/glide#compatibility

**Comment by TWiStErRob** [comment]
@anthony3444 note that there's a built-in fade-in: `.animate(R.anim.abc_fade_in)` or `.animate(android.R.anim.fade_in)` if you API level allows.
