### ISSUE TITLE
The Second loading with cache problem

### ISSUE THREAD

**Issue by xubenliang** [bumptech/glide#1122]
1.The first loading is perfect , but the second loading with cache has a problem, I don't konw why?
if use .diskCacheStrategy(DiskCacheStrategy.SOURCE), the problem is resolve。
Glide.with(mContext)
                    .load(url)
                    .placeholder(resId)
                    .fitCenter()
                    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                    .crossFade()
                    .into(mImageView);
The fist: http://imglf1.nosdn0.126.net/img/WHBOUnFJcXNhN2gxai9md3NMNWVsSHdDMWVWY3JObERYaFJMK09vT25RZ0VvbmlzT1JseElBPT0.png?imageView&thumbnail=500x0&quality=96&stripmeta=0&type=jpg
The second:
http://imglf.nosdn0.126.net/img/WHBOUnFJcXNhN2gxai9md3NMNWVsUERlbDhRUUpQUmliTENDbWpuSUZjU0RYQTgvbndMN2d3PT0.png?imageView&thumbnail=500x0&quality=96&stripmeta=0&type=jpg

**Comment by TWiStErRob** [comment]
Good old #305.
