### ISSUE TITLE
can i set colorFilters on Glide targeted imageview having placeholder?

### ISSUE THREAD

**Issue by ndeokar** [bumptech/glide#1124]
i am using Glide 3.6.1

i am showing the images with GridLayoutManager and using Glide to load images.
meanwhile i load the images i am showing the placeholder drawable.

i am providing the user option of selection and for that purpose if item is selected i am adding the color filter to the particular imageview. but that works perfectly fine if the image is loaded into the memory.
but when placeholder is displayed and user clicks on particular image then color filter is not getting applied to imageview. so user has to wait until glide finishes the image loading.

**in the screenshot consider the requirement as i want to show Guitar Tuner selected when user taps on it.** 

```java
 Glide.with(mCOn)
     .load(model.url)
     .placeholder(R.drawable.inventory_placeholder)
     .diskCacheStrategy(DiskCacheStrategy.RESULT)
     .crossFade()
     .into(holder.res_pic);
if (model.status) {
    // selected tint
    holder.res_pic.setColorFilter(ContextCompat.getColor(mCOn, R.color.orange_tint), PorterDuff.Mode.MULTIPLY);
} else {
    holder.res_pic.clearColorFilter();
}
```
![screenshot_2016-04-11-11-50-01](https://cloud.githubusercontent.com/assets/16112654/14418533/eb0e4b9c-ffdc-11e5-99a5-d5c9088f706d.png)

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/issues/1142#issuecomment-213714079 for an extensive custom solution.
