### ISSUE TITLE
Image not display at first load, but ok after a reload.

### ISSUE THREAD

**Issue by tigercbc** [bumptech/glide#1125]
**first load log:**
V/Engine: Started new load in 7.819947999999999ms, key: EngineKey{http://ict.image.alimmdn.com/100000119/1460356240781.jpeg+com.bumptech.glide.signature.EmptySignature@2dfebb16+[192x192]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
V/DecodeJob: Decoded transformed from cache in 56.02401, key: EngineKey{http://ict.image.alimmdn.com/100000119/1460356240781.jpeg+com.bumptech.glide.signature.EmptySignature@2dfebb16+[192x192]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
V/DecodeJob: Transcoded transformed from cache in 3.441041, key: EngineKey{http://ict.image.alimmdn.com/100000119/1460356240781.jpeg+com.bumptech.glide.signature.EmptySignature@2dfebb16+[192x192]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

**second load log:**
V/Engine: Loaded resource from cache in 1.7652079999999999ms, key: EngineKey{http://ict.image.alimmdn.com/100000119/1460356240781.jpeg+com.bumptech.glide.signature.EmptySignature@2dfebb16+[192x192]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

**my codes:**
Glide.with(mActivity).load(XXXXXXX)
                        .diskCacheStrategy(DiskCacheStrategy.ALL)
                        .placeholder(R.drawable.user_center_default_avatar)
                        .centerCrop()
                        .crossFade()
                        .into(logo);

please help! thanks!

**Comment by TWiStErRob** [comment]
Was it a circle ImageView?
