### ISSUE TITLE
the problem about load picture of .png format

### ISSUE THREAD

**Issue by jiajunhui** [bumptech/glide#1127]
**Glide Version**:3.7.0

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby

I load PNG picture (transparent background) with glide. 
The picture local file has a light color background superfluous. 
Can you help me to solve the problem, thank you!

My English is so poor, sorry.

```

**Comment by TWiStErRob** [comment]
Please share original PNG, screenshot and Glide code.

**Comment by jiajunhui** [comment]
I set DiskCacheStrategy value of RESOURCE instead of ALL, the problem is fixed. but I can`t understand clearly.

And I get a mistake, it`s a .jpg picture.
original jpg:
[http://webimg.ikan.cn/test/ximages/eb/product/5ef5aad0-715d-4665-a570-f38cd3c7a942.jpg](url)

local file background color: #F7FCF6

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/issues/515
