### ISSUE TITLE
I am receiving Exception while using glide

### ISSUE THREAD

**Issue by sonaypsi** [bumptech/glide#1134]
eclipse 

 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;    

How can I resolve this.

**Comment by TWiStErRob** [comment]
So it looks like you made it compile by adding the jar and it runs on the device, right?

Try Google "android eclipse java.lang.NoClassDefFoundError" -> http://stackoverflow.com/q/2247998/253468

**Comment by sonaypsi** [comment]
Yes

**Comment by TWiStErRob** [comment]
Try the "Order and Export"-type solutions first.

**Comment by sonaypsi** [comment]
But It is already Checked in Order and Export

**Comment by TWiStErRob** [comment]
Then try clean build, restart, and other solutions on SO.

**Comment by sonaypsi** [comment]
Thankyou so much it worked for me

**Comment by sonaypsi** [comment]
Can I show progessbar until image loads in imageview

**Comment by TWiStErRob** [comment]
Use a `.placeholder()` or if you want animated: #505 #958.
If you want to go crazy: #232.

**Comment by sonaypsi** [comment]
Thank you very much

**Comment by maqli** [comment]
hha,this my problem,
