### ISSUE TITLE
about Glide cache clear

### ISSUE THREAD

**Issue by jiajunhui** [bumptech/glide#1136]
this is my setting for cache

```java
String path = DirectoryManager.getGlideImageCachePath(IkanApplication.getContext());
DiskLruCacheFactory diskLruCacheFactory = new DiskLruCacheFactory(path, cache_name, diskCacheSize);
diskLruCacheFactory.build();
```

when clear cache
```java
Glide.get(context).clearDiskCache();
```

I Specifies a cache directory,When the cache is cleared,All have been cleared away.
but, I hope some pictures will not be cleared away.
What am I to do ? Can I set two cache directories ?

**Comment by TWiStErRob** [comment]
Glide doesn't support that.

There's an API for ignoring files (`.signature`) which will evic them from cache. There's also a hard tricky way to do it, see #1033 for a discussion.

**Comment by LiHanGuang** [comment]
@jiajunhui 
Maybe you can try below, but I am not recommand!

```
// CustomGlideModule.java
builder.setDiskCache(new DiskCache.Factory() {
            @Override
            public DiskCache build() {
                return getDiskCache();
            }
        });

public static synchronized DiskCache getDiskCache(){
        if (sDiskCache == null) {
            sDiskCache = createDiskCache();
        }
        return sDiskCache;
    }
```

How to **clearDiskCache** ?
```
CustomGlideModule.getDiskCache().clear();
``

**Comment by TWiStErRob** [comment]
@LiHanGuang it still clears the whole cache and there's no way to tell which File belongs to what because their names are hexa hashes.

**Comment by LiHanGuang** [comment]
@TWiStErRob 
Sorry , i didnt saw the
>
but, I hope some pictures will not be cleared away.

May be @jiajunhui  want two diskcache:  one not clear,  one clear

**Comment by TWiStErRob** [comment]
Even if you would be able to do this, Glide is not a file/download manager, you'll have to create your own "pinning" logic because there's no guarantee that any file will be in Glide cache.
