### ISSUE TITLE
Load gif throws IllegalArgumentException: Bad position (limit 4234016): 4234042

### ISSUE THREAD

**Issue by dasamanren** [bumptech/glide#1143]
java.lang.IllegalArgumentException: Bad position (limit 4234016): 4234042
![image](https://cloud.githubusercontent.com/assets/6468888/14733325/d8c340d0-0894-11e6-8ce9-3c982cb0369a.png)

**Comment by TWiStErRob** [comment]
#1145

**Comment by dasamanren** [comment]
thanks
