### ISSUE TITLE
Placeholder image is not showing up before image load.

### ISSUE THREAD

**Issue by khandelwaludit** [bumptech/glide#1144]
I am loading an image through glide and setting the placeholder url.

My complete request looks like this. 
```java
requestBuilder = requestManager.using(loader).load(myUrl).
                signature(new Signature(myUrl.getImageQuality()));
requestBuilder.diskCacheStrategy(DiskCacheStrategy.SOURCE);
requestBuilder.override(myUrl.getWidth(), myUrl.getHeight());
requestBuilder.listener(imageLoadListener);
requestBuilder.thumbnail(thumbnailRequest);
requestBuilder.dontAnimate();
requestBuilder.placeholder(myUrl.getDefaultResourceId());
requestBuilder.into(imageview);
```

I have omitted the conditioners for each line but I guess they are irrelevant.

Is there anything that I am doing wrong ? 
Also I do  not need the crossFade animation.

**Comment by TWiStErRob** [comment]
I can think of a few things:

1. The condition actually does matter for placeholder because it's false.
2. The image is loaded quickly from memory cache and then there's no need for placeholder.
3. You may need to set the placeholder on the thumbnail request too.

**Comment by khandelwaludit** [comment]
Thanks for the quick response and actually you were right. One of the condition was not allowing it to set. Now that I have clubbed placeholder and into lines together, I am able to see the place holder. Thanks man.

**Comment by mochadwi** [comment]
> Thanks for the quick response and actually you were right. One of the condition was not allowing it to set. Now that I have clubbed placeholder and into lines together, I am able to see the place holder. Thanks man.

Would you mind explaining to use, what do you mean by **conditioners for each line**?

@khandelwaludit

**Comment by TWiStErRob** [comment]
@mochadwi each `requestBuilder.foo(...)` was wrapped in an an `if (...) { ... }` block. The problem was that the condition in `if` was false, so the `.placeholder(...)` method was not called.
