### ISSUE TITLE
can not show gif image with last frame broken

### ISSUE THREAD

**Issue by LiuChaoCN** [bumptech/glide#1145]
this is image address:http://img1.famulei.com/z/0/p/164/2113351333687.gif.

this image cause this exception.
![8lq le f 07 170miybuh](https://cloud.githubusercontent.com/assets/13093238/14733683/6af02e80-0897-11e6-943f-494df0d81644.png)

the image showed up when we deleted last frame of this gif image.

**Comment by TWiStErRob** [comment]
Even Google Chrome stops rendering, I think this is a case of GIGO.
