### ISSUE TITLE
Gifs are loading really slow with in v3

### ISSUE THREAD

**Issue by paveldudka** [bumptech/glide#1146]
I am facing really strange issue with displaying gifs using Glide. Gifs are loading really slowly - it takes 30-90 seconds to display them. And it doesn't matter if gif is loaded from the network or stored locally (in res/raw folder). I am not doing any transformations/animations/etc. - just pure simple `Glide.with(context).load(R.raw.gif).into(imageView);`

Also I don't have any integrations with other libs (like volley, okhttp, recyclerView).

Interesting thing - updating to Glide v4 snapshot solves the issue. But Im reluctant to use not released version..

Glide version: 3.7.0
Android Gradle plugin: 2.1.0-beta3
AppCompat: 23.3.0

Sample project: https://github.com/paveldudka/Glide3Failure

Tested on following devices (all have the same problem):
- Nexus6 (API 23)
- Nexus5 (API 22)
- Galaxy SIII (API 18)

**Comment by TWiStErRob** [comment]
Do a Google or GitHub issue search and you should find at least 10 issues similar to this with explanations.

> I am not doing any transformations/animations/etc.

An important thing to note here is that the default load you mentioned actually looks like this:
```
.diskCacheStrategy (RESULT) // slow-cause
.crossFade() // animation
.fitCenter() // transformation

**Comment by paveldudka** [comment]
Yesterday I glanced through existing GIF issues and couldn't find anything related... Now indeed I found couple of similar issues.

Changing disk caching type to `SOURCE` solves the problem. 
Thanks for a prompt response!

**Comment by TWiStErRob** [comment]
Hmm, first 5 are about this when I search for "Glide slow GIF", but I guess it's easier to have the right keywords if you know the issue :)
