### ISSUE TITLE
Image is not loading

### ISSUE THREAD

**Issue by madim** [bumptech/glide#1149]
**Glide Version**: 3.7.0

**Device/Android Version**: Nexus 5, Android M

**Issue details / Repro steps / Use case background**: I'm just trying to test glide and load image

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ImageView imageView = (ImageView) findViewById(R.id.imageView);

        Glide.with(this).load("http://goo.gl/gEgYUd")
                .into(imageView);
    }
```

**Layout XML**:
```xml
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="packagename.MainActivity">

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/imageView"
        android:layout_centerVertical="true"
        android:layout_centerHorizontal="true"/>
</RelativeLayout>
```

**Comment by TWiStErRob** [comment]
1. Check the logs for BitmapFactory failures
2. Add a listener https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener
3. If no onException is called then change your layout to match-match. Glide's power lies within loading the right sized image for all views, but for that it needs a size, I think your view's size is 0x0 on first layout, so Glide may wait indefinitely.
4. You can also try wrap-wrap with `.override(Target.SIZE_ORIGINAL)` to load the full image; this works around the no-sized view, but only works if you know your source has a small size (i.e. not a 10MP camera photo).

If it's a layout issue I suggest a much simpler layout: `FrameLayout` and an `ImageView` inside, both match-match sizes, and add `scaleType=centerInside` to the ImageView. You can even skip the `FrameLayout` or change it to `merge`

**Comment by madim** [comment]
Thanks, I forgot to add INTERNET permission
