### ISSUE TITLE
I want to set different cache disk and keep default cache dir

### ISSUE THREAD

**Issue by ouacyou** [bumptech/glide#1150]
I want to set different cache disk and keep default cache dir.

how can i to do?
thanks!

**Comment by TWiStErRob** [comment]
Please explain more, you want to change the directory, but you don't?

**Comment by ouacyou** [comment]
yes,i want to change the directory because some image need clear but the others need not.

**Comment by TWiStErRob** [comment]
So you want 2 cache directories, you don't want to change it. Glide doesn't support that out of the box.

There's an API for ignoring files (`.signature`) which will evict them from cache, see #792. There's also a hard tricky way to do it, see #1033 for a discussion.

**Comment by ouacyou** [comment]
@TWiStErRob Thanks for your answer.
