### ISSUE TITLE
okhttp3-integration is not linked to jcenter

### ISSUE THREAD

**Issue by gfx** [bumptech/glide#1151]
Glide Version: 3.7.0
Glide OkHttp3 Integration Version: 1.4.0

https://bintray.com/bintray/jcenter/com.github.bumptech.glide%3Aokhttp3-integration/view

It seems that Grade OkHttp3 Integration is not linked to jcenter, so it is not easy to use.

Can you please link it to jcenter?

**Comment by TWiStErRob** [comment]
We don't publish to jcenter directly, see #544.
Bintray is "stealing" the jars from maven central when they are requested on-the-fly.

It shows 1.4.0 for me, but the website and other meta are not set. I'm not sure what was the state you saw 4 hours ago.

@sjudd maybe you should claim the ownership of this new lib.

**Comment by ndorigatti** [comment]
this is the dependency to add, you have to put aar suffix
compile "com.github.bumptech.glide:okhttp3-integration:1.4.0@aar"

**Comment by TWiStErRob** [comment]
Also see https://github.com/bumptech/glide/wiki/Integration-Libraries for more info.
Sadly there's an issue whose fix is not released yet, beware of that: #941. It should only matter if you're not using the `@aar`.

**Comment by gfx** [comment]
okhttp3-integration works with `@aar`. Thanks!
