### ISSUE TITLE
ListView items order change when i resumeRequests in ScrollListener

### ISSUE THREAD

**Issue by ouacyou** [bumptech/glide#1152]
I want  to pause/resume  loading picture, but when i pauseRequests , list items order changes, why?

**Comment by TWiStErRob** [comment]
Please share your adapter code.

**Comment by ouacyou** [comment]
`if (convertView == null) {`
`viewHolder = new TrackHolder();`

			convertView = LayoutInflater.from(context).inflate(
					R.layout.item_live_track_view, null);

			viewHolder.trackView = (LiveTrackView) convertView
					.findViewById(R.id.live_track_view);

			convertView.setTag(viewHolder);
		} else {
			viewHolder = (TrackHolder) convertView.getTag();
		}
		final LiveTrackView trackView = viewHolder.trackView;
		Glide.with(context).load(picurll)
				.asBitmap().into(new SimpleTarget<Bitmap>() {

					@Override
					public void onResourceReady(Bitmap bitmap,
							GlideAnimation<? super Bitmap> arg1) {
}

**Comment by TWiStErRob** [comment]
That's looks ok, but the important part is missing: when you use a `SimpleTarget` (or any custom target) you take on many responsibilities you may not be aware of don't really want to handle.

**Comment by ouacyou** [comment]
i found the position is wrong in onResourceReady, may be asynchronous cause?

**Comment by TWiStErRob** [comment]
Glide is async, it needs to be cancelled properly when an item is reused, by using SimpleTarget you're responsible for that, but without showing me what you actually do I can't help more than this.

**Comment by ouacyou** [comment]
` 

	public View getView(int position, View convertView, ViewGroup parent){

		TrackHolder viewHolder = null;
		final LiveScore score = scoreList.get(position);
		if (convertView == null) {
			viewHolder = new TrackHolder();
			convertView = LayoutInflater.from(context).inflate(
					R.layout.item_live_track_view, null);

			viewHolder.trackView = (LiveTrackView) convertView
					.findViewById(R.id.live_track_view);

			convertView.setTag(viewHolder);
		} else {
			viewHolder = (TrackHolder) convertView.getTag();
		}
		final LiveTrackView trackView = viewHolder.trackView;
		Glide.with(context).load(fairwayList.get(score.Serial - 1).PicUrl)
				.asBitmap().into(new SimpleTarget<Bitmap>() {

					@Override
					public void onResourceReady(Bitmap bitmap,
							GlideAnimation<? super Bitmap> arg1) {
						matrix = getMatrix(bitmap);
						Bitmap newFairway = Bitmap.createBitmap(bitmap, 0, 0,
								bitmapW, bitmapH, matrix, true);
						trackView.setLayoutParams(getLayoutParams(newFairway));
						trackView.setImageBitmap(newFairway);
						trackView.setData(score, scale);
					}

					@Override
					public void onLoadFailed(Exception e, Drawable errorDrawable) {
						super.onLoadFailed(e, errorDrawable);
						AbsListView.LayoutParams layoutParams = new AbsListView.LayoutParams(
								android.widget.AbsListView.LayoutParams.MATCH_PARENT,
								failPicH);
						trackView.setLayoutParams(layoutParams);
						trackView
								.setBackgroundResource(R.drawable.news_fail_bg);

					}

				});

		return convertView;
	}

	Matrix matrix;

	private Matrix getMatrix(Bitmap bitmap) {
		if (matrix == null) {
			matrix = new Matrix();
			bitmapW = bitmap.getWidth();
			bitmapH = bitmap.getHeight();
			scale = (float) width / bitmapW;
		} else {
			matrix.reset();
		}
		System.out.println("wang>>>scale>>" + scale);
		matrix.postScale(scale, scale);
		return matrix;
	}

	AbsListView.LayoutParams layoutParams;

	private AbsListView.LayoutParams getLayoutParams(Bitmap newFairway) {
		if (layoutParams == null) {
			layoutParams = new AbsListView.LayoutParams(newFairway.getWidth(),
					newFairway.getHeight());
		}
		return layoutParams;
	}

	private int bitmapW;
	private int bitmapH;
	float scale;

	public void resetList(List<LiveScore> scoreList) {
		this.scoreList = scoreList;
		notifyDataSetChanged();
	}

	private static final class TrackHolder {
		LiveTrackView trackView;
	}`

**Comment by TWiStErRob** [comment]
I think you're just missing the `onLoadCleared` override, which should clear the `trackView`'s image.
When an item in list is reused `Glide....into` clears the existing request/target associated with that view, and then starts the new load. Without an `onLoadCleared` implementation your previously shown image will be kept in view. Normally you would get an exception/weird rendering problems, but you don't here because you made a copy of the bitmap you received from Glide.
I suggest extending `BitmapImageViewTarget` instead of `SimpleTarget` which has all the logic you would need.

Also note that your `scale` field will only be valid if all your loaded `PicUrl`s are the same size and `width` doesn't change ever.

Tip: That Bitmap-matrix logic can be replaced with `.override(bitmapW, bitmapH).fitCenter()` after `.asBitmap()`, it'll be more performant (both processor and memory usage) and simpler that way.

In case your `LiveTrackView` is an `ImageView` you can do something like this:
```java
private final int failPicH;
private final int bitmapW;
private final int bitmapH;
private final AbsListView.LayoutParams successLayoutParams;
private final AbsListView.LayoutParams failureLayoutParams;
YourAdapter(int width, int height, int failHeight) {
	bitmapW = width;
	bitmapH = height;
	failPicH = failHeight;
	successLayoutParams = new AbsListView.LayoutParams(bitmapW, bitmapH);
	failureLayoutParams = new AbsListView.LayoutParams(AbsListView.LayoutParams.MATCH_PARENT, failPicH);
}
public View getView(int position, View convertView, ViewGroup parent) {
	...
	Glide.with(context)
	     .load(fairwayList.get(score.Serial - 1).PicUrl) 
	     .asBitmap()
	     .error(R.drawable.news_fail_bg)
	     .override(bitmapW, bitmapH)
	     .fitCenter()
	     .listener(new RequestListener<String, Bitmap>() {
		     @Override public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
			     trackView.setLayoutParams(failureLayoutParams);
			     return false;
		     }
		     @Override public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
			     trackView.setLayoutParams(successLayoutParams);
			     trackView.setData(score, (float) width / bitmapW);
			     return false;
		     }
	     })
	     .into(trackView); // this means that Glide's internal targets will be used handling all lifecycle for you
```
even if it's not you can apply some parts of the above, for example the precomputed layout params and you get an `errorDrawable` in your target, with which you can call `trackView.setBackground`.

**Comment by ouacyou** [comment]
@TWiStErRob Thank your very much!
