### ISSUE TITLE
How to know if image came from disk cache or network and if other resolution available in cache

### ISSUE THREAD

**Issue by gitanshu** [bumptech/glide#1153]
**Glide Version**: 3.7.0

**Integration libraries**: None

I want to use [facebook's network connection class library](https://github.com/facebook/network-connection-class) to find out the user's current connection bandwidth class and fetch corresponding quality image from cloudinary. A typical cloudinary url used in my app goes like 

    https://res.cloudinary.com/demo/image/upload/w_300,q_40/bike.jpg 

where w_300 tells cloudinary that the image should be 300 pixels wide and q_40 tells it to generate image at 40% quality. Now I have 2 problems:

1. I want to do network sampling only when an image is being downloaded over the network, which means I need a way to determine if an image would be downloaded or would come from disk cache so that I can call the connection class' startSampling() method when I issue the request for image. 

2. Since the quality factor changes with when the network quality changes, it means the image url also changes. I need a way to know if I already have the image in some other quality in disk cache so that I can ask for the same quality instead of the one corresponding to current network state, else I'll have the same image in cache in different qualities.

I am heavily reliant on Glide for image fetching across the app. I typical Glide call in my app looks like this:

    String imgUrl = Utils.getImageUrl(productData.getImgUrl(), mImageWidth);  //generates Url by replacing width and quality factor in original Url
    
    Glide.with(mContext).load(imgUrl).placeholder(Utils.getRandomColor()).dontTransform()
            .crossFade(450).into(holder.productImageView);

**Comment by TWiStErRob** [comment]
To do sampling only on requests, you can replace the network integration library, the default is `HttpUrlFetcher` created by `HttpUrlGlideUrlLoader`, see https://github.com/bumptech/glide/wiki/Integration-Libraries for more. Start sampling before opening the connection and stop in `cleanup`.

There's no standard/sync way to query the cache, I think in your case you may be able to get away with the trick in #639. `.thumbnail()`s can also be nested so you can build requests for each of your qualities which have the network disabled and nest them with the best quality being the main request and the lowest being the innermost. I think it should load the best possible version this way, but if the main request's `onException` is called that means none of them were in cache and you can fire another load that will make a request with your current quality.
