### ISSUE TITLE
Animation on multiple images

### ISSUE THREAD

**Issue by abhinav272** [bumptech/glide#1154]
**Glide Version**: 3.6.1

**Integration libraries**: Retrofit

**Device/Android Version**: All

**Issue details / Repro steps / Use case background**:  I have 10 image urls and one ImageView, I want to load these images one by one (which is happening) but with animation so that the already loaded image should fade out and new image should fade in simultaneously.
Using the below code I m only able to get fade_in for new image that is loading but already loaded image disappears instantly.
Have already spend few days on it.. Any help ??

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(mContext).load(productList.get(j).getImgUrl()).fitCenter().diskCacheStrategy(DiskCacheStrategy.SOURCE).crossFade(1500).into(imageView);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Yes, it's an interesting issue, take a look at my solution: https://github.com/bumptech/glide/issues/861#issuecomment-169490382

**Comment by abhinav272** [comment]
@TWiStErRob : Awesome... 👍 
Exactly what I was looking for.. Thanks....

**Comment by abhinav272** [comment]
Is there a way to stop this cycler..??
I am having seven image views and want to randomly play cycler on few views..

**Comment by TWiStErRob** [comment]
It only loads the next one if you call `cycler.startNext();` I think you need to modify code around `autoAdvance()` in the Fragment.

**Comment by TWiStErRob** [comment]
Also each ImageView will need it's own cycler.

**Comment by abhinav272** [comment]
@TWiStErRob : Thanks again.. Worked fine
