### ISSUE TITLE
Inconsistent outheights from bitmaptransformation causing cache leak

### ISSUE THREAD

**Issue by SeanOxford** [bumptech/glide#1156]
I'm currently using Glide in an adapter, pulling three bitmaps per cell in a vertical recyclerview. Depending on the orientation of the image, I have to rotate it in the instances it's portrait. When doing this transformation, the outheight of the same URL will every once in a while be off by a bit causing it to be recached. Each time I go forward to the next fragment, then go back and rescroll through, it "permanently" adds more memory on my monitor, causing the user to be susceptible OOM crashes.

Logging myself scrolling up and down, you can see 5e9d2281993d9945 outheight goes from 573 to 547 and back.

Any ideas on how I might solve this? These images are pretty big, and I'd hate for our users to have to keep downloading just to avoid a crash.

```
photo/a389605113218bce.1500.0.0.jpg, width: 573, height: 573
photo/558208dc22fcdb95.1500.0.0.jpg, width: 573, height: 573
photo/34527c1901bb04d6.1500.0.0.jpg, width: 573, height: 573
photo/22f0e9518368b3f2.1500.0.0.jpg, width: 573, height: 573
photo/c44278e16f5de67e.1500.0.0.jpg, width: 573, height: 573
photo/a291555b2c90c34d.1500.0.0.jpg, width: 573, height: 573
photo/e61d1ad902deec0f.1500.0.0.jpg, width: 573, height: 573
photo/aa050a4fe929d51b.1500.0.0.jpg, width: 573, height: 573
photo/8b15a0101bbfb24d.1500.0.0.jpg, width: 573, height: 573
photo/d7faadcab4ed7529.1500.0.0.jpg, width: 573, height: 573
photo/8d7d1b3f454784f8.1500.0.0.jpg, width: 573, height: 573
photo/5e9d2281993d9945.1500.0.0.jpg, width: 573, height: 573
photo/5c3a4adc06b648bf.1500.0.0.jpg, width: 573, height: 573
photo/341fe28b480c2efc.1500.0.0.jpg, width: 573, height: 547
photo/50fbd5461d576e0a.1500.0.0.jpg, width: 573, height: 547
photo/eeb0fdaa1879f007.1500.0.0.jpg, width: 573, height: 547
photo/1ba1059800d9713f.1500.0.0.jpg, width: 573, height: 547
photo/1ac2d03ca980da3d.1500.0.0.jpg, width: 573, height: 547
photo/184375f432cb67d9.1500.0.0.jpg, width: 573, height: 547
photo/7642e12bf72cd015.1500.0.0.jpg, width: 573, height: 547
photo/c99d9c1b714eb507.1500.0.0.jpg, width: 573, height: 547
photo/4c604ed8bccce1d0.1500.0.0.jpg, width: 573, height: 547
photo/278a75b2b42fa0e5.1500.0.0.jpg, width: 573, height: 547
photo/96b9ece169224646.1500.0.0.jpg, width: 573, height: 547
photo/278a75b2b42fa0e5.1500.0.0.jpg, width: 573, height: 547
photo/184375f432cb67d9.1500.0.0.jpg, width: 573, height: 547
photo/1ac2d03ca980da3d.1500.0.0.jpg, width: 573, height: 547
photo/eeb0fdaa1879f007.1500.0.0.jpg, width: 573, height: 547
photo/1ba1059800d9713f.1500.0.0.jpg, width: 573, height: 547
photo/341fe28b480c2efc.1500.0.0.jpg, width: 573, height: 547
photo/50fbd5461d576e0a.1500.0.0.jpg, width: 573, height: 547
photo/8d7d1b3f454784f8.1500.0.0.jpg, width: 573, height: 547
photo/5e9d2281993d9945.1500.0.0.jpg, width: 573, height: 547
photo/d7faadcab4ed7529.1500.0.0.jpg, width: 573, height: 547
photo/5c3a4adc06b648bf.1500.0.0.jpg, width: 573, height: 547
photo/aa050a4fe929d51b.1500.0.0.jpg, width: 573, height: 547
photo/c44278e16f5de67e.1500.0.0.jpg, width: 573, height: 547
photo/558208dc22fcdb95.1500.0.0.jpg, width: 573, height: 547
photo/a389605113218bce.1500.0.0.jpg, width: 573, height: 547
photo/22f0e9518368b3f2.1500.0.0.jpg, width: 573, height: 547
photo/34527c1901bb04d6.1500.0.0.jpg, width: 573, height: 547
photo/a291555b2c90c34d.1500.0.0.jpg, width: 573, height: 547
photo/aa050a4fe929d51b.1500.0.0.jpg, width: 573, height: 547
photo/d7faadcab4ed7529.1500.0.0.jpg, width: 573, height: 547
photo/e61d1ad902deec0f.1500.0.0.jpg, width: 573, height: 547
photo/8d7d1b3f454784f8.1500.0.0.jpg, width: 573, height: 547
photo/5c3a4adc06b648bf.1500.0.0.jpg, width: 573, height: 547
photo/50fbd5461d576e0a.1500.0.0.jpg, width: 573, height: 547
photo/5e9d2281993d9945.1500.0.0.jpg, width: 573, height: 573
photo/341fe28b480c2efc.1500.0.0.jpg, width: 573, height: 547
photo/8b15a0101bbfb24d.1500.0.0.jpg, width: 573, height: 547
photo/eeb0fdaa1879f007.1500.0.0.jpg, width: 573, height: 547
photo/1ba1059800d9713f.1500.0.0.jpg, width: 573, height: 547
photo/1ac2d03ca980da3d.1500.0.0.jpg, width: 573, height: 547
photo/278a75b2b42fa0e5.1500.0.0.jpg, width: 573, height: 547
photo/7642e12bf72cd015.1500.0.0.jpg, width: 573, height: 547
photo/184375f432cb67d9.1500.0.0.jpg, width: 573, height: 547
photo/c99d9c1b714eb507.1500.0.0.jpg, width: 573, height: 547
photo/4c604ed8bccce1d0.1500.0.0.jpg, width: 573, height: 547
photo/96b9ece169224646.1500.0.0.jpg, width: 573, height: 547
```

**Comment by TWiStErRob** [comment]
Did you actually crash with OOM? As far as I know the "permament' memory usage you see is because the Bitmap is placed into the BitmapPool/MemoryCache. These storages should be freed under memory pressure (`onLowMemory`). You can also call `Glide.get(context).clearMemory()` if you get an OOM and try again.

The changing heights probably have to do with your layout / item reuse, if you share your item XML and adapter code I may be able to help. This would be the root-cause treatment.

As a workaround if we can't figure it out, or you don't bother you can also use `.diskCacheStrategy(SOURCE)` to save the original JPG file into cache. Using `SOURCE` cache means that the user will only download it once, and then whatever size is needed that will be decoded from that original image.

**Comment by SeanOxford** [comment]
Thanks for the quick reply!

Yes, the eventual crash in the app is an OOM, I've considered manually clearing it, but I don't want the user to have to redownload these large images. 

The XML I'm using is the following:

`        <ImageView android:layout_width="150dp" android:layout_height="150dp"
                   android:id="@+id/ImageView_bottom_card"
                   android:background="@android:drawable/dialog_holo_light_frame"
                   android:scaleType="matrix"/>

        <ImageView android:layout_width="150dp" android:layout_height="150dp"
                   android:id="@+id/ImageView_middle_card"
                   android:background="@android:drawable/dialog_holo_light_frame"
                   android:scaleType="matrix"/>

        <ImageView android:layout_width="150dp" android:layout_height="150dp"
                   android:id="@+id/ImageView_top_card"
                   android:background="@android:drawable/dialog_holo_light_frame"
                   android:scaleType="matrix"/>`

The layout bounds do not get changed in the code, though we are doing matrix work.

using source for DiskCacheStrategy sounded like it would have worked but I'm still getting the same issue. 

Current Debug implementation (Context being used is application, however this fragment persists at the bottom of the navigation flow):
`            if (shouldRotate) {
                mGlider.load(imageUrl)
                       .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                       .transform(bitmapTransformation)
                       .into(cardImageView);
            } else {
                mGlider.load(imageUrl)
                       .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                       .into(cardImageView);
            }
`

The transformation (debug implementation, mind the redundancy):

`                      BitmapTransformation bitmapTransformation = new BitmapTransformation(mContext) {
                @Override
                protected Bitmap transform(BitmapPool pool,
                                           Bitmap toTransform,
                                           int outWidth,
                                           int outHeight) {

                    if (shouldRotate) {
                        Matrix matrix = new Matrix();

                        matrix.postRotate(-90f);

                        Bitmap rotatedBitmap = Bitmap.createBitmap(toTransform,
                                                                   0,
                                                                   0,
                                                                   toTransform.getWidth(),
                                                                   toTransform.getHeight(),
                                                                   matrix,
                                                                   true);

                        return rotatedBitmap;
                    }

                    return toTransform;
                }

                @Override public String getId() {
                    return imageUrl;
                }
            };
`

**Comment by SeanOxford** [comment]
I'd like to add that I just found that the MemoryCategory is being set to high on the fragment where most of the crashes occur. I think removing that will smooth things out, but I'd still like to solve the core issue.

**Comment by TWiStErRob** [comment]
> using source for DiskCacheStrategy sounded like it would have worked but I'm still getting the same issue.

The sizes will still be loaded differently, but the image won't be re-downloaded! Also the memory cache will still contain multiple Bitmaps.

> `String getId() { return imageUrl;`

Here you should return `"RotateTransformation:" + shouldRotate`. The cache key already contains the Url, because the model (Uri/String) is part of it (added by the fetcher).

> though we are doing matrix work.

Where is this? If you mean the Matrix used in the transformation, then your code is equivalent to a cleaner version: `android:scaleType="fitCenter"` (or remove attr from XML) and `.dontTransform()` on Glide load (only needed where `.transform()` is not called

Explanation: There can be only one transformation chain (varargs). Each call to transform (~ fitCenter / centerCrop / dontTransform / transform) will override any transformation set before. If none were explicitly set then Glide will use the transformation from ImageView's scaleType (code: `GenericRequestBuilder.into(ImageView)`.

> outheight goes from 573 to 547 and back.

Based on the knowledge you shared so far this is indeed weird. You're requesting 150dp sizes on both sides, but sometimes the height doesn't match. Can you please change your load and transformation to:
```java
// adapter
if (shouldRotate) {
    mGlider.load(imageUrl)
           .diskCacheStrategy(DiskCacheStrategy.SOURCE)
           .transform(bitmapTransformation)
           .listener(new LoggingListener("rotated"))
           .into(cardImageView);
} else {
    mGlider.load(imageUrl)
           .diskCacheStrategy(DiskCacheStrategy.SOURCE)
           .listener(new LoggingListener("original"))
           .into(cardImageView);
}

// transformation
Log.wtf("TRANSFORM", String.format(Locale.ROOT, "input: %dx%d, return: %dx%d, target: %dx%d",
toTransform.getWidth(), toTransform.getHeight(), rotatedBitmap.getWidth(), rotatedBitmap.getHeight(), outWidth, outHeight);
return rotatedBitmap;
```

LoggingListener can be found here: https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/utils/LoggingListener.java

**Comment by SeanOxford** [comment]
>Where is this? If you mean the Matrix used in the transformation, then your code is equivalent to a cleaner version: android:scaleType="fitCenter" (or remove attr from XML) and .dontTransform() on Glide load (only needed where .transform() is not called

Called right after the method in which all the Glide calls, I have a method call that does

    Matrix matrix = new Matrix();
    matrix.preScale(.48f, .48f);
    imageView.setImageMatrix(matrix);

>Based on the knowledge you shared so far this is indeed weird. You're requesting 150dp sizes on both sides, but sometimes the height doesn't match. 

I was actually mistaken, I am actually resetting the layoutparams for those imageviews to have width and height set to the same value which is only initialized in the constructor. (573 in my Galaxy S5's case)


Here are the logs within the transformation, I'm having a bit of trouble working with the glide-support. This is scrolling to the bottom then up. Gonna keep trying things.

A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x573
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x573
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x573
A/TRANSFORM: input: 1500x1079, return: 1079x1500, target: 573x573
A/TRANSFORM: input: 1500x1079, return: 1079x1500, target: 573x573
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x573
A/TRANSFORM: input: 1500x1079, return: 1079x1500, target: 573x573
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x573
A/TRANSFORM: input: 1500x1079, return: 1079x1500, target: 573x573
A/TRANSFORM: input: 1500x1078, return: 1078x1500, target: 573x573
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x573
A/TRANSFORM: input: 1500x1078, return: 1078x1500, target: 573x573
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x573
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x573
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1500x1079, return: 1079x1500, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1500x1078, return: 1078x1500, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1500x1079, return: 1079x1500, target: 573x547
A/TRANSFORM: input: 1500x1078, return: 1078x1500, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1500x1079, return: 1079x1500, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1500x1079, return: 1079x1500, target: 573x547
A/TRANSFORM: input: 1500x1079, return: 1079x1500, target: 573x547
A/TRANSFORM: input: 1079x1500, return: 1500x1079, target: 573x547
A/TRANSFORM: input: 1078x1500, return: 1500x1078, target: 573x547

**Comment by TWiStErRob** [comment]
You don't need to compile `glide-support`, just copy that class to your project.

**Comment by TWiStErRob** [comment]
It's strange that some inputs are 1079 and others are 1078, but there's no correlation between that and the target size. The target size is the actual view size. Something is changing the layout size that Glide sees (it's reading via `getHeight()` in `ViewTarget.SizeDeterminer`). The 573 VS 547 is clear though and is shows that once an item is reused the size never resets to the origiinal 150dp. Do you by any chance have `adjustViewBounds`?

I'm not sure what that matrix transformation is there for, but I think you're wasting memory: you have a view that's ~500px in size, you load a Bitmap into memory that's ~1500/1000px and render it as ~750px/500px? You may want to try `.transform(bitmapTransformation, new FitCenter())` or `.sizeMultiplier(0.5f)` depending on your goals. Note that this is unrelated to the layout issue.

**Comment by SeanOxford** [comment]
>You don't need to compile glide-support, just copy that class to your project.
Right, it was complaining about not having another class and I was afraid that was gonna cascade into pasting in half the library, but it worked. However, not sure what data you want from this, here's the kind of output I'm getting.

V/GLIDE: original.onResourceReady(GlideBitmapDrawable@e166490(1500x1078@RGB_565), https://d3pjs3gkyiam7n.cloudfront.net/asset/photo/2a8ec3cf81b99b1a.1500.0.0.jpg, Target for: ImageView{298ce189 V.ED.... ........ 463,0-1036,547 #7f0d01be app:id/ImageView_top_card}(params=573x573->size=573x547), async, first)

>Do you by any chance have adjustViewBounds?

It is not being set in XML or programmatically. Is there any way that Glide can change bounds? I've even gone as far as setting the layout params for the image view to a 573 square right before the Glide call but in the transformation, it still tells me the bounds are 547. I think this is probably a recyclerview issue since height switches to 547 once views start recycling, but if you can see any glaring insights, I appreciate all the help!

**Comment by TWiStErRob** [comment]
Ah, OK. It has a lot of info that is available in the listener:
For example `params=573x573->size=573x547` is confirming that your layout and Glide-size don't match. Try calling `imageView.layout(0,0,0,0)` before Glide loads. This may help, but it may also hurt scroll performance so not suggested as a production fix. How do you set the params? What is the container in XML for those 3 views?

**Comment by SeanOxford** [comment]
>How do you set the params? What is the container in XML for those 3 views?

They are set programmatically in the constructor of my viewholder.

                 RelativeLayout.LayoutParams imageLayoutParams =
                new RelativeLayout.LayoutParams(mRowViewHeight, mRowViewHeight);

            imageLayoutParams.addRule(RelativeLayout.ALIGN_PARENT_RIGHT, RelativeLayout.TRUE);
            mImageViewBottomImage.setLayoutParams(imageLayoutParams);
            mImageViewMiddleImage.setLayoutParams(imageLayoutParams);
            mImageViewTopImage.setLayoutParams(imageLayoutParams);


Layout(0, 0, 0, 0) is causing the out dimensions to stay consistent, however, the memory is still piling up. 
The only time I can avoid the memory build-up is when the rotated images are set to DiskCacheStrategy.NONE and/or skipMemoryCache(true). :( Maybe it could not be related to caching images by dimension, because I feel like in that case it would have at most 2 cached versions, 573x573 and 573x547. Any other ideas on what may be causing this if that is ruled out?

**Comment by TWiStErRob** [comment]
Sharing the same layoutparams object for multiple views looks weird to me, are you sure that's supported? Try to set 3 separate ones. Which one of the 3 views `cardImageView` represent? What I'm trying to gauge is: Is it always the top/bottom/middle one?

Are you correctly reusing the items? (ViewHolder pattern).
Can you share the whole adapter with me? (email if you don't want to publish).

**Comment by SeanOxford** [comment]
>Sharing the same layoutparams object for multiple views looks weird to me, are you sure that's supported? Try to set 3 separate ones. Which one of the 3 views cardImageView represent? What I'm trying to gauge is: Is it always the top/bottom/middle one?

In each cell, I have three image views stacked on top of each other (hence the same params) that I rotate and position respectively to look like three cards fanned out as a preview for selectable cards in a category for the next fragment (i.e. christmas, birthday, etc.). 

>Are you correctly reusing the items? (ViewHolder pattern).

Yep, onCreateViewHolder gets called a couple times in the beginning then nothing but onBindViewHolder from then on. The 574x547 issue actually arose after the number of viewholders created had matched onBindViewHolder, so it was the recycling that was triggering that issue.

>Can you share the whole adapter with me?

Emailed!

**Comment by SeanOxford** [comment]
By the way, I just tried individual layoutparams for each card and the problem is persisting.
