### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/OkHttpClient;

### ISSUE THREAD

**Issue by yubaokang** [bumptech/glide#1158]
<meta-data
            android:name="com.bumptech.glide.integration.okhttp.OkHttpGlideModule"
            android:value="GlideModule" />
         compile 'com.github.bumptech.glide:glide:3.7.0'
         compile 'com.github.bumptech.glide:okhttp-integration:1.4.0@aar'
         compile 'com.squareup.okhttp3:okhttp:3.2.0'

        Glide.with(context).load(uri).into(imageView);

error:  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/OkHttpClient;

**Comment by TWiStErRob** [comment]
Decide if you're using okhttp (v2) or okhttp3 and update your code:
```gradle
compile 'com.github.bumptech.glide:okhttp-integration:1.4.0@aar'
compile 'com.squareup.okhttp:okhttp:2.7.5'
```
or
```gradle
compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'
compile 'com.squareup.okhttp3:okhttp:3.2.0'
```

Also either
```
<meta-data
        android:name="com.bumptech.glide.integration.okhttp3.OkHttpGlideModule"
        android:value="GlideModule" />
compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0'
```
or just
```
compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'
```

Read https://github.com/bumptech/glide/wiki/Integration-Libraries for more details. I'll update that page with the new OkHttp3 lib as well.

**Comment by yubaokang** [comment]
Problem solved, thank you

**Comment by TWiStErRob** [comment]
Updated https://github.com/bumptech/glide/wiki/Integration-Libraries/_compare/c2e59fb58597d179b0280770bcdc6577a1094ab8...1fe0495caa9acac6ef4ac1a5d33d31aaf848d428
