### ISSUE TITLE
Load AppIcons to ListView

### ISSUE THREAD

**Issue by ironbob** [bumptech/glide#1159]
How can I load app icons to listView or RecyclerView. A app icon is a drawable. If i set the drawable to listview directly,the listview often caton that get a bad experience.

**Comment by TWiStErRob** [comment]
Duplicate of https://groups.google.com/forum/m/#!topic/glidelibrary/MAqPfuHpjr4

Full code available at https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/groups/_MAqPfuHpjr4_app_icons
