### ISSUE TITLE
moderate laggy list view scrolling while load image from URL

### ISSUE THREAD

**Issue by yfsx** [bumptech/glide#1163]
Hi, i tried to use glide to load image in each child of my list view from URL. For small amount of data, it works perfectly with no lag. And then when i tried to handle more than thousand datas, i found that the list view will work really slow while glide still load the image from url, but the list view works perfectly when image is completely loaded to list view.

any suggestion how to handle this ''laggy event" for list view or recycler view? 

thanks!

**Comment by TWiStErRob** [comment]
Do some profiling, it may not be Glide. Usually the layout is working too much. The ImageView lays out every time you change the image inside. If you don't have a placeholder it means on every item scrolled into view. But when you have less items those images may fit in memory and not having a layout because the image sizes match. See also https://github.com/bumptech/glide/issues/1038#issuecomment-193403959

If this doesn't help, please include XML and adapter code.

**Comment by yfsx** [comment]
My layout only do displaying data into list view, and i do some proofing before i post this. i remove glide load image code and there isn't any lag when list view scrolled.

Here's the adapter code

`public class DealBrandListViewAdapter extends BaseAdapter {
    RealmList<Brand> brandRealmList = new RealmList<>();
    HashMap<Integer,Brand> brandHashMap = new HashMap<>();
    HashMap<Integer,String> headerHashMap = new HashMap<>();
    int totalCount=0;
    Realm realm;
    Context ctx;
    public final int TYPE_ITEM = 0;
    public final int TYPE_SEPARATOR = 1;

    public DealBrandListViewAdapter(Context ctx){
        this.ctx = ctx;
    }

    public void updateAdapter(RealmList<Brand> brandRealmList){
        brandHashMap.clear();
        headerHashMap.clear();
        this.brandRealmList = brandRealmList;
        totalCount = 0;
        String latestFirstChar = "";
        for(Brand brand : brandRealmList){
            String currentFirstChar = brand.getBrandName().charAt(0)+"";
            if(!currentFirstChar.equalsIgnoreCase(latestFirstChar)) {
                addSectionHeaderItem(totalCount, currentFirstChar);
                latestFirstChar = currentFirstChar;
            }
            addItem(totalCount,brand);
        }
        notifyDataSetChanged();
    }

    public void addItem(Integer index,Brand brand) {
        brandHashMap.put(index,brand);
        totalCount++;
    }

    public void addSectionHeaderItem(Integer index,String firstChar) {
        headerHashMap.put(index,firstChar);
        totalCount++;
    }

    @Override
    public int getItemViewType(int position) {
        return headerHashMap.containsKey(position) ? TYPE_SEPARATOR : TYPE_ITEM;
    }

    @Override
    public int getCount() {
        return totalCount;
    }

    @Override
    public Object getItem(int position) {
        return brandHashMap.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View view = convertView;
        Holder holder = new Holder();
        SectionHolder sectionHolder = new SectionHolder();
        LayoutInflater inflater = (LayoutInflater) ctx.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        int rowType = getItemViewType(position);
        if(convertView == null){
            switch (rowType){
                case TYPE_SEPARATOR:
                    view = inflater.inflate(R.layout.itemlistview_dealfragmentheader,null);
                    sectionHolder.sectionTitle = (OpenSansSemiBoldTextView)view.findViewById(R.id.itemDeal_headerTextView);
                    view.setTag(sectionHolder);
                    break;
                case TYPE_ITEM:
                    view = inflater.inflate(R.layout.itemlistview_dealfragment,null);
                    holder.itemImageView = (ImageView)view.findViewById(R.id.itemDeal_imageView);
                    holder.tagTitle = (OpenSansRegularTextView)view.findViewById(R.id.itemDeal_titleTextView);
                    view.setTag(holder);
                    break;
            }

        }else{
            switch (rowType){
                case TYPE_SEPARATOR:
                    if (view.getTag() instanceof SectionHolder){
                        sectionHolder = (SectionHolder)view.getTag();
                    }else{
                        view = inflater.inflate(R.layout.itemlistview_dealfragmentheader,null);
                        sectionHolder.sectionTitle = (OpenSansSemiBoldTextView)view.findViewById(R.id.itemDeal_headerTextView);
                        view.setTag(sectionHolder);
                    }
                    break;
                case TYPE_ITEM:
                    if (view.getTag() instanceof Holder){
                        holder = (Holder)view.getTag();
                    }else{
                        view = inflater.inflate(R.layout.itemlistview_dealfragment,null);
                        holder.itemImageView = (ImageView)view.findViewById(R.id.itemDeal_imageView);
                        holder.tagTitle = (OpenSansRegularTextView)view.findViewById(R.id.itemDeal_titleTextView);
                        view.setTag(holder);
                    }
                    break;
            }
        }
        if(rowType == TYPE_SEPARATOR){
            String titleString = headerHashMap.get(position);
            sectionHolder.sectionTitle.setText(titleString);
        }else {
            Brand theBrand = brandHashMap.get(position);
            if (theBrand.getBrandImageURL() != null) {
                Glide.with(ctx).load(theBrand.getBrandImageURL()).into(holder.itemImageView);
            }
            holder.tagTitle.setText(theBrand.getBrandName());
        }
        return view;
    }

    public class Holder{
        ImageView itemImageView;
        OpenSansRegularTextView tagTitle;
    }
    public class SectionHolder{
        OpenSansSemiBoldTextView sectionTitle;
    }
}
`

what i wanna ask is, is there any trick to reduce this lag?

thanks :)

**Comment by TWiStErRob** [comment]
> i remove glide load image code and there isn't any lag when list view scrolled.

That doesn't prove Glide is the culprit. It could be the layout as well when different images get set into the ImageView in the list item the layout changes.

Please include your XML as well.
