### ISSUE TITLE
Can Glide play local mp4? 

### ISSUE THREAD

**Issue by namchuai** [bumptech/glide#1165]
**Glide Version**: 3.7.0

I'm working on a project which require to play GIF, MP4 (like snapchat's vertical video section). 

GIF is greatly supported by Glide (thanks to  Glide creator).
But for MP4, I can only display a still image. 

Glide.with(context)
                .load(Uri.fromFile(file))
                .into(mCoverImage);

My question is does Glide support playing MP4 as well as GIF?

Thanks!

**Comment by TWiStErRob** [comment]
No, it can only play GIFs, and show video thumbs. This is working as intended, see #831.
