### ISSUE TITLE
Maybe is a bug which load images from local albums with custom animation 

### ISSUE THREAD

**Issue by SupLuo** [bumptech/glide#1166]
Glide version：glide-3.7.0

I get all image file path from media provider，then use glide to show them in gridview with custom load animation 。
I got an strange phenomenon that if fast scroll the gridview ，some item of the gridview wil not show the image data but a white background， and i see that，this item have load the GlideBitmapDrawable，and this kind of situation is random，So it should not be a problem of the image data，So I guess it's a question of animation，then I do not use the load animation，everything is OK，I just want to know whether it is a bug。

Here is the code I use：
with problem：
```java
                 Glide.with(imageView.getContext())
                .load(url)
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .placeholder(placeHolder).error(errorPlaceHolder)
                .animate(R.anim.fade_in)
                .into(imageView);
```
no problem:
```java
                 Glide.with(imageView.getContext())
                .load(url)
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .placeholder(placeHolder).error(errorPlaceHolder)
                .into(imageView);
```

**Comment by TWiStErRob** [comment]
What is your layout XML for list item?
Do you mess around with the imageview outside this line?
Is this line surrounded by a condition (`if`) in adapter's bind?

Also please double-check the image is loaded via https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener and also check the system gallery app to see if the thumbnail is not white. Please also double-check that your placeholder/error Drawable is not white.

**Comment by TWiStErRob** [comment]
BTW, when you don't specify anim you're using `.crossFade()`.
