### ISSUE TITLE
Glide can't load Image with "https" urls

### ISSUE THREAD

**Issue by mohopa** [bumptech/glide#1167]
hi.

I am using glide version 3.7.0. it can load all image perfectly also with urls, exact like your sample code I could load images with url.

```
ImageView imageView = (ImageView) findViewById(R.id.my_image_view);

  Glide.with(this).load("http://goo.gl/gEgYUd").into(imageView); 
```

but when same image address change to **https** ,can't load that :(

what I can to do?

thank you.

**Comment by TWiStErRob** [comment]
Check the reason why: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener
