### ISSUE TITLE
Failed to resolve okhttp3-integration:1.4.0@jar and okhttp3-integration:1.4.0

### ISSUE THREAD

**Issue by start141** [bumptech/glide#1168]
Failed to resolve: glide-parent:library:unspecified

using
compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@jar' and
compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0'

**Comment by TWiStErRob** [comment]
Duplicate of #941.

Tip: if you copy your title or even whole description into Google Search you'll be directed to #957 / #941.

**Comment by start141** [comment]
thanks!
