### ISSUE TITLE
Reducing number of refresh token call requests when loading images in RecyclerView

### ISSUE THREAD

**Issue by rshah** [bumptech/glide#1169]
I'm using Glide 3.7.0 with OkHttp3 integration library to display images in RecyclerView. 
Authentication is needed to access the images which is done inside OkHttpClient authenticator. 
But sometime i need to refresh the token first when the token expired . In this case there are many refresh token request from glide to server. What i'm using now by comparing lastRefreshTime against current time refreshToken function.
Something like below:
```Kotlin
fun refreshToken(): AccessToken? {
        synchronized(lockObject) {
            if (System.currentTimeMillis() - lastSyncTime > SYNC_INTERVAL) {
                val oldToken = activeToken.get()
                accountManager.invalidateAuthToken(MyAccountAuthenticator.ACCOUNT_TYPE, oldToken)
            }
            return getToken() //blocking method
        }
    }
```
Do you have some kind of best practices to avoid multiple refresh token calling?
```Kotlin
class MyGlideSetup : GlideModule { 
    override fun applyOptions(context: Context?, builder: GlideBuilder?) {  }  
    override fun registerComponents(context: Context?, glide: Glide?) { 
        if (context == null) { 
            return 
        }  
        val httpClientBuilder = OkHttpClient.Builder()  
        httpClientBuilder.authenticator {
             route, response ->
             val originalRequest = response.request()
             val newRequest = originalRequest.newBuilder()
              val credentialManager = MyApplication.getCredentialManager(context)
             val accessToken: AccessToken?
             if (originalRequest.header("Authorization") == null) {
                 accessToken = credentialManager.getToken() 
                accessToken?.let { 
                    newRequest.header("Authorization", "${it.token_type} ${it.access_token}") 
                } 
            } else { 
                accessToken = credentialManager.refreshToken() 
            }  
            accessToken?.let { 
                newRequest.header("Authorization", "${it.token_type} ${it.access_token}") 
            }   
           newRequest.build() 
        }  
        glide?.register(GlideUrl::class.java, InputStream::class.java,   
                      OkHttpUrlLoader.Factory(httpClientBuilder.build())) 
    }
 }

```

**Comment by TWiStErRob** [comment]
I don't see where your problem lies. It looks ok to me to refresh periodically. These two things are strange to me, they may worth pursuing:
 * Do you update `lastSyncTime` anywhere?
 * `accessToken?.let` seems to be duplicated and executed twice if there's no header present.

---

There's also a Glide API for producing headers in Glide which don't require OkHttpClient customization, nor OkHttp itself. Take a look at https://github.com/bumptech/glide/issues/921#issuecomment-174185985.

**Comment by rshah** [comment]
Yes, `lastSyncTime`, updated somewhere.
My initial version of `refreshToken()` did not have `lastSyncTime`. In this case, the url for refreshing token will be called several times. For example if i have 20 item in RecyclerView, then there will be 20 refresh token  request to server. That's why i added `lastSyncTime` to limit the refresh token request to server. Which works somehow, i just wondering if there is another better way.

 As for the `accessToken` if no header present i will use existing token, but when the header present means the token need to be refreshed first before using it in header.

Thank you for the idea,  i will have a look your reference.

**Comment by TWiStErRob** [comment]
> Which works somehow, i just wondering if there is another better way.

I see, so when you open a list because many requests are fired at once to show the initial N items you get all of them calling refresh. I think what you're describing is normal, and it should be the credentialManager's responsibility to do a no-op refresh when the token is still valid, like you did.
I don't if you're using a library or it's all your own code, maybe you should try StackOverflow/programmers/codereview on stackexchange to see if the larger community has better insights.
It's definitely not Glide's responsibility because it is just requesting the image through the network and it needs to. Caching (SOURCE/RESULT) can help a little, to not request the same image again, but the first load of any list will have this effect anyway.

> As for the accessToken if no header present i will use existing token, but when the header present means the token need to be refreshed first before using it in header.

Yes, I see that, but the code doesn't fully reflect that, here is the structure of the code:
```kotlin
val accessToken: AccessToken?
if (originalRequest.header == null) {
    accessToken = getToken() 
    newRequest.header = accessToken // (1)
} else { 
    accessToken = refreshToken() 
}
newRequest.header = accessToken // (2)
```
(2) is redundant: either (2) needs to be inside the `else` or better yet (1) removed so (2) sets the "getOrRefresh"-d token.

**Comment by rshah** [comment]
I see,
Thank you very much for your help.

**Comment by rshah** [comment]
I'm trying to implement your suggestion as in [https://github.com/bumptech/glide/issues/921#issuecomment-174185985](https://github.com/bumptech/glide/issues/921#issuecomment-174185985).
But i'm wondering how to refresh the token using your suggestion.
What will Glide tell us when something the supplied token not valid anymore?

In my solution, i can try to refresh the token when OkHttp return the "Authorization" header.

**Comment by TWiStErRob** [comment]
Hmm, that's a good point; Glide won't return anything. I'm not that familiar with OkHttp. Based on your usage it looks like OkHttp will try the request and if it fails with a specific HTTP code it'll call this method where you can retry.

You need the header to decide if you failed or not. I thought the time limit should be enough: when Glide makes the first refresh your "last refresh" is infinitely in the past so you do a refreshToken, then for subsequent requests you add that token to the header until some time elapses when you need to refresh again. If you hide refresh inside getToken and let the manager worry about timings you can just created a header factory (not a static string header) which returns getToken() which can be blocking.

This works if you need auth for every request and override GlideUrl handling. If you need auth only for some requests, but not others, and I think this is the case and this is why you needed to check for presence of the header, then you should go with the custom model route and leaving the default registration intact. So for that custom model you always attach an auth header lazily within the extended modelloader and use `.load(CustomModel)`; and for normal requests you can use all the other non auth loads you can use `.load(String|Uri|...)` as if your custom model didn't even exists.

I think the difference between my suggestion and your current version is that you only do token logic when the server tells you to, but as a dev you should have prior knowledge which endpoint/server/path needs auth and always auth for those. This should save a lot of sever roundtrips. I assume the current worst case flow is: load something - HTTP request for image - server responds - authenticator called - HTTP request for refreshToken - HTTP request for image - image returned. You can save the first one if you do the time based expiration and/or separation of normal and authenticated requests.

I hope this makes sense; if not, please correct me where my assumptions lack.
