### ISSUE TITLE
Exif Orientation

### ISSUE THREAD

**Issue by CorentinPacaud** [bumptech/glide#1173]
**pb**
I use Glide to display multiple photo. Apparently, Glide automatically rotate images following the Exif orientation, but it's not. 
It doesn't work on all Sony Xperia we try. It works on the Nexus 5X because size is 2000x3000 or 3000x2000 (no exif)

**Glide Version**: 
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.android.support:support-v4:23.3.0'

**Integration libraries**:

**Device/Android Version**:
 Android 5.1.1 (Sony Xperia Z)
Android 6.0 (Sony Xperia Z3)
Android 5.1.1 (Sony Xperia M2)

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(mContext).load("file:" + file.getLocalUri()).diskCacheStrategy(DiskCacheStrategy.SOURCE).listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        holder.progressBar.setVisibility(View.GONE);
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        holder.progressBar.setVisibility(View.GONE);
                        return false;
                    }
                }).into(holder.image);
```

**Layout XML**:
```
Just a basic imageView.
```

**Stack trace / LogCat**:
```
No error
```

I verified Exif of images from Sony Xperia. They contain "orientation : CW 90"

**Comment by TWiStErRob** [comment]
Take a look at #1120 to see if anything there helps. If not please share an image that doesn't work.

**Comment by TWiStErRob** [comment]
CW 90 by itself doesn't mean anything, it's also important how the raw pixels are stored. Maybe the raw pixels are correctly oriented, but the EXIF says that it needs rotation.

**Comment by TWiStErRob** [comment]
Tip: don't SOURCE cache local files, it'll copy the original file into Glide's cache, but won't speed up anything, because they're both on the Phone/SD Card.

**Comment by CorentinPacaud** [comment]
Ok, I just the pb. A library I use to take picture resized image but doesn't copy exif in the resized Image.
Not a Glide issue sry.
