### ISSUE TITLE
GIF start playing only after all GIFs shows in gridview or listview

### ISSUE THREAD

**Issue by shewenbiao** [bumptech/glide#1176]
**Glide Version**: [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots)

**Issue details / Repro steps / Use case background**: 
Use glide to load GIFs  in grid view or list view adapter, and I notice that GIF start playing only after all GIFs displayed. But I hope the GIF start playing if it shows instead of starting to play together after all GIFs shows. Is there anyway to achieve it?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(getContext())
        .load(gifUri)
        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
        .into(holder.gifImage);
```

**Comment by TWiStErRob** [comment]
How did you solve this?

As far as I know the GIF frame loads have higher priority than normal images, but they're using the same queue/thread pool.

**Comment by shewenbiao** [comment]
I hadn't solve this problem, now I have to reopen this issue because of  it is not good for user experience.
Do you have a good suggestion to solve this problem?

**Comment by TWiStErRob** [comment]
Sadly I have no idea with this one other trying to move the grid's image load priority down.

**Comment by shewenbiao** [comment]
Thank you anyway, but how to move the grid's image load priority down, can you give me some details.

**Comment by TWiStErRob** [comment]
http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/GenericRequestBuilder.html#priority(com.bumptech.glide.Priority)

**Comment by seshuvinay** [comment]
glide:4.1.1
Same issue with com.felipecsl.gifimageview.library.GifImageView in GridView. Any fix?

**Comment by sjudd** [comment]
@seshuvinay Try 4.3.1 or newer version of Glide.
