### ISSUE TITLE
Caching Issue on Redirected Urls

### ISSUE THREAD

**Issue by stripathi669** [bumptech/glide#1177]
My code looks like this:

     Glide.with(this)
                .load(randomImageUrl)
                .asBitmap().signature(new StringSignature(String.valueOf(System.currentTimeMillis() / 1000)))
                .placeholder(R.drawable.loading_image_placeholder_old).centerCrop()
                .skipMemoryCache(true).diskCacheStrategy(DiskCacheStrategy.NONE)
                .into(image);

`randomImageUrl` is static url which redirects to a random url each time. (I have tested and verified this). Now the problem is, Glide is loading same image everytime, meaning it is has somehow cached the static url's first redirect. It susbsequently loads first redirect's image, even though I have skipped all cache.

I am unable to understand how/why is this happening. How can I prevent it?

Glide v3.6 with Volley

**Comment by TWiStErRob** [comment]
Hmm, that should load a new image every second.
I would look around Volley, maybe they cache too, so even though Glide goes to the network to fetch, Volley serves from cache.

Try Stetho to see your requests: http://stackoverflow.com/q/36642052/253468 (you'll have to adapt this to use Volley thought)

**Comment by stripathi669** [comment]
I have no caching for normal volley requests.

Does Glide's Volley integration enable it by default?

**Comment by TWiStErRob** [comment]
I couldn't find evidence: https://github.com/bumptech/glide/tree/3.0/integration/volley/src/main/java/com/bumptech/glide/integration/volley

Please try using the default or the OkHttp integration to see if it's a problem with Volley.

Please double-check that your server receives the request, and that the image is actually different, for example through Wireshark or Stetho.

**Comment by TWiStErRob** [comment]
You could also try proving/disproving that Glide's engine is the problem (e.g. signature handling):
https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by stripathi669** [comment]
I tried removing integration and it works. 
So, the problem is somewhere when I add volley integration. I will try to further track source of the issue and post here.

**Comment by TWiStErRob** [comment]
`Volley.newRequestQueue`, the default queue created by Glide, uses disk cache. See Volley source code. Give it [a custom queue](https://github.com/bumptech/glide/wiki/Integration-Libraries#overriding-default-behaviour) that uses `NoCache`.
