### ISSUE TITLE
Android studio2.0 import glide project gradle error

### ISSUE THREAD

**Issue by workjm** [bumptech/glide#1180]
hi，I use Android studio 2.0 version import glide project, modify some places:

-ANDROID_GRADLE_VERSION=1.2.3
+ANDROID_GRADLE_VERSION=2.0.0

-    gradleVersion = '2.9'
+    gradleVersion = '2.10'

-distributionUrl=https\://services.gradle.org/distributions/gradle-2.9-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip

But happen an error:
Error:Cannot invoke method systemProperty() on null object

Can you help me?Thanks very much.

**Comment by TWiStErRob** [comment]
`gradlew jar --stacktrace` will tell you where the error is.

1.x -> 2.x won't be that easy as you depicted. Also of this is the 3.0 branch, it's even worse. Use an IDEA 14+ to import it, or a pre-2.x AS which doesn't require you to use the 2.x gradle plugin.
