### ISSUE TITLE
placeholder has problem.

### ISSUE THREAD

**Issue by TianLiJun** [bumptech/glide#1183]
```java
Glide.with(context)
.load(imageUrl)
.diskCacheStrategy(DiskCacheStrategy.ALL)
.centerCrop()
.placeholder(R.drawable.aaa)
.crossFade()
.into(imageView);
```

first time to use this method ,image can`t show,ImageView always show the placeholde image.
Image show until next time to use this method.

**Comment by TWiStErRob** [comment]
Take a look at https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling, it should help you figure out what's actually wrong.

**Comment by TWiStErRob** [comment]
Also be aware of https://github.com/bumptech/glide#compatibility

**Comment by lmmmowi** [comment]
I meet the same problem, have you fixed it?

**Comment by TWiStErRob** [comment]
Likely using CircleImageView, so closing it.
Please reopen if that's not the case.
