### ISSUE TITLE
Can I judge whether there is a certain URL in memory Bitmap caching

### ISSUE THREAD

**Issue by decide15** [bumptech/glide#1184]
**Glide Version**:3.7.0

**Integration libraries**:okhttp:2.7.0

I want my listview lazyload image : when listview is scrolling ,Glide only load momery cache bitmap.

**Comment by decide15** [comment]
than you very much!

**Comment by decide15** [comment]
thank you very much~

**Comment by TWiStErRob** [comment]
You can prevent Glide from going to the network by using a special loader that just throws an exception:
```java
Glide.with(context).using(new NetworkDisablingLoader<String>()).load(url).....into(imageView);
```
See https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/utils or #828

**Comment by TWiStErRob** [comment]
@decide15 Actually, this will load disk cache as well, so if you really just want memory cache, then you should add `.diskCacheStrategy(NONE)` as well.
