### ISSUE TITLE
Glide does not load gif for an ActivityTransition

### ISSUE THREAD

**Issue by mformetal** [bumptech/glide#1186]
**Glide Version**: 3.7.0

**Integration libraries**: 

**Device/Android Version**: Only tested on Nexus 5

**Issue details / Repro steps / Use case background**: 

Loading file Uri's from an Android cursor for display in a RecyclerView. When loaded the first time from the cursor in the respective adapter, Gif plays fine. When I click on the image to start an ActivityTransition (uri in recyclerview is same as uri in the started activity), gif does not play at all. I'm trying to keep the Transition, as it works for images that are displayed in the RecyclerView, and I'd like to keep that same feel. 

In my adapter...

``` java
public void onBindViewHolder(ViewHolder holder, int position) {
 if (cursor.moveToPosition(position)) {
   final int index = cursor.getColumnIndex(MediaStore.Images.Media.DATA);
                final String path = cursor.getString(index);

                File file = new File(path);
                if (file.length() != 0) {
                    final Uri uri = Uri.fromFile(file);

                    Glide.with(host) // host is an Activity context
                            .load(uri)
                            .into(imageView);

                    imageView.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            String name = host.getString(R.string.transition_gallery_to_uri);
                            imageView.setTransitionName(name);

                            Intent intent = new Intent(host, UriActivity.class);
                            ActivityOptions options =
                                    ActivityOptions.makeSceneTransitionAnimation(host,
                                            imageView,
                                            host.getString(R.string.transition_gallery_to_uri));
                            intent.setData(uri);
                            host.startActivityForResult(intent, GalleryActivity.RESULT_SELECT,
                                    options.toBundle());
                        }
                    });
                }
 }
}
```

In started activity. "this" is an Activity, "uri" is passed to the activity in an intent

``` java
Glide.with(this).load(uri).into(imageView)
```

**Layout XML**:

``` xml
<FrameLayout xmlns:android="...
```

Activity:

``` xml
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <ImageView
        android:id="@+id/activity_uri_image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:scaleType="centerCrop"
        android:transitionName="@string/transition_gallery_to_uri" />

    <Toolbar
        android:id="@+id/activity_uri_toolbar"
        android:layout_width="match_parent"
        android:layout_height="?android:attr/actionBarSize"
        style="@style/AppTheme.EntryActivity.Toolbar" />

</FrameLayout>
```

Adapter:

``` xml
<miles.diary.ui.widget.SquareImageView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/adapter_gallery_image"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerCrop"
    android:elevation="@dimen/fab_elevation" >
</miles.diary.ui.widget.SquareImageView>
```

**Stack trace / LogCat**:

``` ruby
paste stack trace and/or log here
```

No error log is printed. I tried attaching a listener to Glide, but nothing is printed there either.

**Comment by TWiStErRob** [comment]
Listener not being called could be because a view is not visible, or it does not have a size; sadly both your layouts are matching parent size and there's no visibility manipulation (is there any maybe in code?).

Notice that you're not actually making the transition possible the first time, because Glide cannot load the second image synchronously, which is I think required for an activity transition. You can match the size with `.override(w, h)` (everything else seems to be matched, because your load line is so simple).

In any case when I tried transitions they are really finicky about sizing and redraws, so I would suggest loading the GIF with `.asBitmap()` in the activity first, and when the transition finished reload it without to let the animation happen.

**Comment by mformetal** [comment]
The view is definitely visible and has a width/ height defined. There's no visibility manipulation that I'm doing. 

So, you recommend loading the Bitmap first, then when the Transition is finished, load the Gif. Seems ugly, but I understand why that should work. I'll try implementing that now.

**Comment by TWiStErRob** [comment]
Yep, w/h is defined, but to hit cache it has to match other other load's size, otherwise you get an async completion which is too late for the transition to capture the drawn state (it'll capture the empty view).

**Comment by mformetal** [comment]
As you expected, that worked. However, it does not load the correct size into the view for some odd reason. Code:

`Transition transition = getWindow().getSharedElementEnterTransition();
        transition.addListener(new SimpleTransitionListener() {
            @Override
            public void onTransitionEnd(Transition transition) {
                Logg.log(imageView.getWidth(), imageView.getHeight());
                if (imageView.getWidth() == 0 || imageView.getHeight() == 0) {
                    PreDrawer.addPreDrawer(imageView, new PreDrawer.OnPreDrawListener<ImageView>() {
                        @Override
                        public boolean onPreDraw(ImageView view) {
                            Glide.with(UriActivity.this)
                                    .load(uri)
                                    .into(imageView);
                            return false;
                        }
                    });
                } else {
                    Glide.with(UriActivity.this)
                            .load(uri)
                            .asGif()
                            .override(imageView.getWidth(), imageView.getHeight())
                            .into(imageView);
                }
            }
        });`

Because the Transition ended, the true-condition of the if-loop should (and never is) executed, but I added it just to be sure. The `Glide.with(UriActivity.this)
                            .load(uri)
                            .asGif()
                            .override(imageView.getWidth(), imageView.getHeight())
                            .into(imageView);` line loads the gif, but for a size inconsistent with the size of the image view

**Comment by TWiStErRob** [comment]
`imageView.getWidth()` will give you the current size which may be weird because of the animation. If that's true, you can try forcing Glide to wait for another layout like this:
```java
imageView.layout(0, 0, 0, 0);
Glide.... // without override
```

---

Originally I meant something like this (untested):
```java
// adapter
final Target<?> target = Glide.with(host)
                              .load(uri)
                              .into((ImageView)null);

imageView.setOnClickListener(new View.OnClickListener() {
    @Override public void onClick(View v) {
        ... prepare transition
        // steal size of thumbnail: usually an async callback,
        // but since the user just tapped on it, it must be visible and laid out
        target.getSize(new SizeReadyCallback() {
            @Override public void onSizeReady(int width, int height) {
                intent.putExtra("transition:width", width);
                intent.putExtra("transition:height", height);
            }
        });
        ... startActivity
    }
});

// activity
int width = getIntent().getIntExtra("transition:width", Target.SIZE_ORIGINAL);
int height = getIntent().getIntExtra("transition:height", Target.SIZE_ORIGINAL);
final BitmapRequestBuilder<Uri, GlideDrawable> firstImage = Glide
        .with(this)
        .load(uri)
        .asBitmap()
        // force loading as bitmap, but still end up with a GlideDrawable for compatibility
        .transcode(new BitmapToGlideDrawableTranscoder(getApplicationContext()), GlideDrawable.class)
        .override(width, height);
firstImage.into(imageView);

@Override public void onTransitionEnd(Transition transition) {
    Glide // replace bitmap used for transition with actual image (possibly animated)
            .with(MainActivity.this)
            .load(uri)
            .thumbnail(firstImage) // use the exact same params so it's sync, see #527 and related
            .into(imageView);
}
```

Hmm, actually after writing this I realized that this won't match the animated thumbnails from your list... (because one is loaded with default decoders and the other `asBitmap` which probably won't match the cache key.

**Comment by mformetal** [comment]
Yeah, this is an interesting situation. Even after copying and muddling with your code a bit, I can't get the gif to play. I'm not sure if it's a memory thing or what.

**Comment by TWiStErRob** [comment]
Did you manage to resolve this somehow?
