### ISSUE TITLE
I meet a problem

### ISSUE THREAD

**Issue by Tryking** [bumptech/glide#1193]
Hello,When I compile the program,I meet a trouble.

The compiler remind me of:

Error:Execution failed for task ':app:transformClassesWithJarMergingFor_DebugDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider.class

**Glide Version**: 3.7.0

I hope you can reply me ,Thank you very much.

**Comment by spermicide** [comment]
Maybe your other module has glide dependency, that collide with this glide dependency?

**Comment by TWiStErRob** [comment]
Hmm, first would be `gradle clean` and then delete all `build` folders (from project root, app folder and all other subprojects you may have). If that doesn't help check out `gradle dependencies`, that `_DebugDebug` looks weird to me it was always `debugCompile` (not sure if 2.0 changed it though). 

Please list your build.gradle dependencies and project structure if none of the above helps.

**Comment by Tryking** [comment]
The trouble had resolved.Thank you everyone.The reason is gradle dependencies are repeated.
