### ISSUE TITLE
recyleview Fast scrolling image dislocation

### ISSUE THREAD

**Issue by chendiyou** [bumptech/glide#1200]
glide version :glide-3.7.0

demo
```java
Glide.with(mContext)
    .load(url)
    .placeholder(failedResourceId)
    .centerCrop()
    .into(new SimpleTarget<GlideDrawable>() {
        @Override
        public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
            if (view == null) {
                throw new IllegalArgumentException("You must pass in a non null View");
            }

            if (view instanceof ImageView) {
                ((ImageView) view).setImageDrawable(resource);
            } else {
                view.setBackground(resource);
            }
        }

        @Override
        public void onLoadFailed(Exception e, Drawable errorDrawable) {
            if (view == null) {
                throw new IllegalArgumentException("You must pass in a non null View");
            }

            if (view instanceof ImageView) {
                ((ImageView) view).setImageResource(failedResourceId);
            } else {
                view.setBackgroundResource(failedResourceId);
            }
        }
    });
```

question
recyleview Fast scrolling image dislocation

Please forgive me English is really poor.

**Comment by TWiStErRob** [comment]
`SimpleTarget` simply too simple to support scrolling at all, let alone fast scrolling. To handle scrolling Glide requires the getRequest to return the previously started request (the one that was binded before). Try this:
```java
void loadImage(Context mContext, final View view, String url, @DrawableRes int failedResourceId) {
	if (view == null) {
		// fail fast, the exception thrown in Target is async
		// at that point it's too late, and it'll be harder to find where the null View came from
		throw new IllegalArgumentException("You must pass in a non null View");
	}
	// prepare Glide load
	DrawableRequestBuilder<String> load = Glide
			.with(mContext)
			.load(url)
			.error(failedResourceId)
			.centerCrop();
	// execute Glide load to relevant target
	if (view instanceof ImageView) {
		load.into(new GlideDrawableImageViewTarget((ImageView)view));
	} else {
		load.into(new GlideDrawableViewBackgroundTarget(view));
	}
}
```
You can find `GlideDrawableViewBackgroundTarget` in https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_938_background and more information in #938.

**Comment by TWiStErRob** [comment]
I would also suggest passing around `Glide.with(this)` (= a `RequestManager`) from where you initiate the load (as a method argument) instead of doing `Glide.with(mContext)` hidden inside, see http://stackoverflow.com/a/32887693/253468 for more.

**Comment by chenchongyu** [comment]
I have the same question.But ur solution not work.My problem is I have a file list.Every file has its own icon like zip,png...When I scroll and load the picture failed,some icon such as zip turn to picturs's icon.It confuse me for a long time.

**Comment by chenchongyu** [comment]
By the way,I use ViewHolder in my listview adapter.

**Comment by TWiStErRob** [comment]
Using Glide's builtin targets for ImageView sould've fixed the problem. How is the file type icon shown? Is it loaded into the background? Because those background targets are untested by me. Do you have your adapter code published somewhere?

**Comment by chenchongyu** [comment]
Thanks for ur reply.
public static BitmapRequestBuilder<GlideUrl, Bitmap> loadImg(Context mContext, String url){
        GlideUrl glideUrl = new GlideUrl(url, builder.build());
        return Glide.with(mContext).load(glideUrl)
                .asBitmap()
                .placeholder(R.drawable.icon_file_picture)
                .error(R.drawable.icon_file_picture);
    }
This is my code to load picture.
Below is  my adapter code.
final ListItemViewHolder itemView ;
		if(convertView == null){
			itemView = new ListItemViewHolder();
			convertView = View.inflate(mContext, R.layout.file_browser_list_item, null);
			itemView.mFileIcon = (PhotoView) convertView
	                .findViewById(R.id.file_icon);
}else{
			itemView = (ListItemViewHolder) convertView.getTag(R.id.glide_tag_id);
		}

final int iconResID = FileIconHelper.getFileIcon(fileExt);
itemView.mFileIcon.setImageResource(iconResID);
 if(xfile.type == 0){//the file is picture				KuaipanApplication.loadImg(itemView.mFileIcon,URLConstant.getThubmUrl(mContext, xid,xfile.file_version));
}

if u want all the adapter code,I can send it to ur email.

**Comment by chenchongyu** [comment]
And what is the "Glide's builtin targets" ?

**Comment by TWiStErRob** [comment]
> what is the "Glide's builtin targets" ?

The classes implementing the `Target` interface that are bundled in the Glide library JAR. Most importantly the ones used in `ImageViewTargetFactory`. This factory is used when you call `into(imageView)` to create the target for that view.

> `if(convertView == null)`

Are you sure you're using the ViewHolder pattern correctly? I don't see a `setTag` call.

> `if(xfile.type == 0){`

Ah, this is another case where location may be wrong. Conditional loading and item reuse don't go well together. You always have to update all views in the item when reusing. Try something like:
```java
if (xfile.type == 0) { //the file is picture
    loadImg(itemView.mFileIcon, pictureIcon);
} else if (xfile.type == 1) { // file is a zip
    loadImg(itemView.mFileIcon, zipIcon);
} else { // something else (this probably needs to be added to your code)
    loadImage(itemView.mFileIcon, fileIcon);
    // or Glide.clear(itemView.mFileIcon); to make sure no image is shown!
}
```

**Comment by chenchongyu** [comment]
Yeah,3Q so much! Glide.clear(itemView.mFileIcon); is work perfect!
