### ISSUE TITLE
Glide resize the place holder with loading the image

### ISSUE THREAD

**Issue by hrsalehi** [bumptech/glide#1201]
**Glide Version**: 3.7.0
**Device/Android Version**:Nexus 7 2012
**Issue details / Repro steps / Use case background**: I have a two pictures that by clicking on them Glide must replace the image into the image view but the the result is resizing the placeholder to aspect ratio of the main image and because of that the image doesn't place in the center of the  screen. I set a background color for the ```ImageView``` (```"@+id/image_view_right"```) so it the area of that became visible.
The problem is by changing the image the new image stick to the top and not remain in center.

```java
Glide.with(context).load(destination)
                            .crossFade()
                            .diskCacheStrategy(DiskCacheStrategy.NONE)
                            .skipMemoryCache(true)
                            .into(image);
```

**Layout XML**:
```xml

            <ImageView
                android:id="@+id/image_view_right"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:scaleType="fitCenter"
                android:background="@color/blueLight"
                android:src="@drawable/background_colorful" />
```

![screenshot_2016-05-14-13-56-30](https://cloud.githubusercontent.com/assets/6253428/15267630/166d3a64-19dc-11e6-8c73-32a86f2a2436.png)
![screenshot_2016-05-14-13-56-15](https://cloud.githubusercontent.com/assets/6253428/15267632/181c7a50-19dc-11e6-885f-a7963f67879f.png)

**Comment by TWiStErRob** [comment]
Try `android:scaleType="centerInside"` and add `.fitCenter()` to your Glide line.

**Comment by TWiStErRob** [comment]
Oh, and also change the height to `match_parent`.

**Comment by TWiStErRob** [comment]
Actually, setting the height alone may solve your problem.

**Comment by hrsalehi** [comment]
Thank you for quick response! that was a silly mistake thank you.
