### ISSUE TITLE
WRAP_CONTENT on ImageView's both dimension and display in RecyclerView

### ISSUE THREAD

**Issue by hubcin** [bumptech/glide#1203]
I had set ImageView's width and height to WRAP_CONTENT and set maxWidth and maxHeight to a certain value ( with adjustViewBounds = true). 
Because I want to display images in it's original aspect ratio.

It works perfect if the image is loaded. But before image is loaded into ImageView, the placeholder is empty and shows nothing, and RecyclerView just jumps when the image is completely loaded.

If there's anyway I could know the exact size( width and height) of the image (via remote URL or local image path) and resize the placeholder before loading the image? 

any approach will be appreciated, thanks !

**Comment by hubcin** [comment]
I know we should have an API to provide the image dimension with the URL request, but for the time being our server side is not likely to provide this functionality, so I'm seeking a way to do it on client side. 
I don't care how much time spent when getting the image size, because I won't add it to the list view until the bitmap is cached. So all I need to do is to write the width and height of the image into a variable and save it when I cache the image with glide. And when I have to display the image, all thing's is ready, and everything will work fine.

**Comment by TWiStErRob** [comment]
Try #781 and #1024.
