### ISSUE TITLE
Is it possible to have 2 instances of Glide?

### ISSUE THREAD

**Issue by IskuhiSargsyan** [bumptech/glide#1208]
I want to have 2 different instances of Glide, to download and show images separately in 2 different instances,while the first one I could cancel ,and let the other one to continue the job.
Is it possible, if not how it could be implemented using the open sources of  glide library?

**Comment by TWiStErRob** [comment]
No. Why would you need to do those things separately?

To build on: you have `.priority()` and context/fragment-associated RequestManager (`.with(*)` which you can pause/resume/destroy separately. Also `.signature()` can be used to "clear" a particular image from cache, which can be extended to a group of images by using the same signature within each group.

**Comment by TWiStErRob** [comment]
Feel free to reopen or just continue the conversation if you want.

**Comment by zzmingo** [comment]
When use signature, how to delete a group of images from disk cache with the specified signature?
