### ISSUE TITLE
D/skia: --- SkImageDecoder::Factory returned null

### ISSUE THREAD

**Issue by weitaoyang** [bumptech/glide#1210]
```java
Glide
.with(this)
.load("http://www.pyfda.gov.cn/Circulation/Manufacturer/Attachment/Upload/Files/20151202151005/img20151202151005.jpg")
.into(iv_pic1);
```

**Comment by TWiStErRob** [comment]
I'm getting an image for
http://www.pyfda.gov.cn/Circulation/Manufacturer/Attachment/Upload/Files/20151202151005/img20151202151005.jpg
but I get a HTML forbidden for this:
http://www.pyfda.gov.cn/Circulation/Manufacturer/Attachment/Upload/Files/20151202151005/img20151202151005.jpg?%22

It would be revealing to check what the response is from the webpage, the skia errors are usually a result of a non-image stream.

Can you please do the following temporarily to diagnose the issue:
* [Create a GlideModule and relocate the disk cache to external storage](https://github.com/bumptech/glide/wiki/Configuration#location)
* Clear your app's cache: in Settings or simply reinstall
* Load the same url with `.diskCacheStrategy(SOURCE)`
* go to `/sdcard/Android/data/your.package/ and download those files to your computer
* with a hex/text editor validate that they're indeed images
