### ISSUE TITLE
PlaceHolder problem

### ISSUE THREAD

**Issue by lmmmowi** [bumptech/glide#1211]
I use Glide.with(context).load(src).listener(l).placeholder(loading).into(imageView)

the listener invoke onResourceReady, but the imageView just show the loading image, the real src image doesn't show~

ps: src is image url, imageView is a circle ImageView( https://github.com/hdodenhof/CircleImageView )

**Comment by lmmmowi** [comment]
ps: src is image url

**Comment by lmmmowi** [comment]
It works when I use 
Glide.with(context).load(src).asBitmap().listener(l).placeholder(loading).into(imageView) !!!!!!

**Comment by TWiStErRob** [comment]
Did you read https://github.com/bumptech/glide#compatibility?

CircleImageView rasterizes the drawable as soon as it's received which means it can't handle animated/changing ones. Loading as Bitmap disables crossFade, you'll have the same effect if you add `.dontAnimate()` to any load.
