### ISSUE TITLE
glide can't load the image of HD video

### ISSUE THREAD

**Issue by peterforme** [bumptech/glide#1213]
**Glide Version**:3.7.0

**Integration libraries**:volley

**Device/Android Version**:HUAWEI MT7-CL00

**Issue details / Repro steps / Use case background**: 
i use glide to load the image of videos, howerver i find that normal videos' thumb can be shown in a imageview but HD video can't 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
//folderPath is the path of a video,variable uri is just to get this video's Uri 
 Uri uri = UriUtil.generatorUri(folderPath,UriUtil.LOCAL_FILE_SCHEME);
   Glide.with(getContext()).load(uri).error(R.drawable.video_thumb).thumbnail(0.3f).into(photo_thumbview);

```

**Comment by TWiStErRob** [comment]
Isn't it just really slow? Even VLC takes a few seconds to load a thumb for big files.

You can play around with loadFromMediaStore or as Bitmap to see if it makes a difference.

Also double check if you don't have any errors: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by peterforme** [comment]
I don't think it's too slow , because I can see the error picture(  **.error(R.drawable.video_thumb)**  )

**Comment by TWiStErRob** [comment]
Then there must be something in the logs if you do any of what's on the wiki.

**Comment by peterforme** [comment]
I turn on the log and can see logs as follows:

05-19 16:05:58.595 31906-32022/com.dlodlo.store E/MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
05-19 16:05:58.595 31906-32022/com.dlodlo.store V/DecodeJob: Decoded from source in 173.17416699999998, key: EngineKey{file:/storage/emulated/0/DCIM/Camera/%E8%88%9E%E6%A2%A6%E5%A4%A9%E4%BD%BF3D.mp4+com.bumptech.glide.signature.EmptySignature@434abb88+[520x360]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
05-19 16:05:58.595 31906-32022/com.dlodlo.store V/DecodeJob: Transformed resource from source in 0.047917, key: EngineKey{file:/storage/emulated/0/DCIM/Camera/%E8%88%9E%E6%A2%A6%E5%A4%A9%E4%BD%BF3D.mp4+com.bumptech.glide.signature.EmptySignature@434abb88+[520x360]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
05-19 16:05:58.595 31906-32022/com.dlodlo.store V/DecodeJob: Transcoded transformed from source in 0.042291999999999996, key: EngineKey{file:/storage/emulated/0/DCIM/Camera/%E8%88%9E%E6%A2%A6%E5%A4%A9%E4%BD%BF3D.mp4+com.bumptech.glide.signature.EmptySignature@434abb88+[520x360]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
05-19 16:05:58.610 31906-31906/com.dlodlo.store D/GenericRequest: load failed

as u can see , it shows load failed

**Comment by TWiStErRob** [comment]
That's a problem in the underlying Android implementation of getting the thumbnail, we can't do much about it sadly. However it may be possible that we're missing a parameter, like it's mentioned in SO answers if you search for "getFrameAtTime: videoFrame is a NULL pointer". Please let us know if you find a way make it work, especially if it's without an extra library.

I suggest you write your own loader/fetcher or decoder for videos to handle all cases.

**Comment by masterwok** [comment]
I know this is an old issue, but I ran into this the other day. I wrote a resource decoder that uses FFmpegMediaMetadataRetriever to avoid the "videoFrame is a NULL pointer" error. It works, however it uses another library. Maybe it can help someone else out in the future: [https://github.com/masterwok/ffmpeg-glide-video-decoder](https://github.com/masterwok/ffmpeg-glide-video-decoder)
