### ISSUE TITLE
Glide fail to load image whose name contains '%'

### ISSUE THREAD

**Issue by AllenVork** [bumptech/glide#1217]
I find glide can't show the image which contains '%' in the path.
such as file:///storage/emulated/0/Pictures/Screenshots/S605**%**14-145315.jpg
and so does other image framework such as fresco.

**Comment by TWiStErRob** [comment]
`%14` is a "device control 4" character, I don't think that's valid in any file name.

In case you want to load the file name with a literal `%` in it do either:
```java
load(new File("/storage/emulated/0/Pictures/Screenshots/S605%14-145315.jpg"))
load(Uri.fromFile(new File(...))
```
You can find much more details about percent-encoding in #1041 and linked issues.

**Comment by AllenVork** [comment]
@TWiStErRob thx,it works for me.
