### ISSUE TITLE
Preload is not working properly

### ISSUE THREAD

**Issue by KashanDanish** [bumptech/glide#1218]
**Glide Version**: 3.6.1

**Device/Android Version**: Nexus 6/6.0.1

**Issue details**: I have an activity which contains an `ImageView`. If I let that activity fetch the image, user have to look at white space until the image is downloaded. To improve that experience, I want to download the image first and when it is downloaded then open the activity. So I went and used `preload` but I am still seeing the white space for the first time. After the first time the image appears instantly.

**Glide pre-load line**:
```java
Glide.with(context)
                .load(url)
                .listener(new RequestListener<String, GlideDrawable>() {

                    @Override
                    public boolean onException(Exception e, String model,
                                               Target<GlideDrawable> target,
                                               boolean isFirstResource) {
                        callbacks.onFailure();
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource,
                                                   String model, Target<GlideDrawable> target,
                                                   boolean isFromMemoryCache, boolean isFirstResource) {
                        callbacks.onSuccess();
                        return false;
                    }
                })
                .preload(500, 500);
```

**Glide load line**:
```java
Glide.with(this) //'this' is an Activity
                .load(url)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .override(500, 500)
                .into(imageView);
```

**Layout XML**:
```xml
<ImageView
        android:id="@+id/promotion_pic"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop"/>
```

**Comment by TWiStErRob** [comment]
Add `.centerCrop()` to your preload to match the transformation, see code of `GenericRequestBuilder.into(ImageView)` for more details.

You'll likely want to add `.diskCacheStrategy(ALL)` to the preload as well: setting the strategy controls **both** reading **and** writing the cache, so it's unreasonable to wait for a cache hit when no-one saved the file into the cache. But I'm 99% sure that you're just missing the transformation like I said above.
