### ISSUE TITLE
How to pass custom viewgroup as param Glide.into()?

### ISSUE THREAD

**Issue by IskuhiSargsyan** [bumptech/glide#1219]
I have recyclerView ,where item .xml like this
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/view_image"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_gravity="center_horizontal">

    <ImageView
        android:id="@+id/iv_background"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:background="@drawable/placeholder_large" />

    <ImageView
        android:id="@+id/iv_cover"
        style="@style/SmallCoverTab" />
</RelativeLayout>
```
where bitmap is loaded I set to iv_cover and the iv_background visibility should gone ,
it should act as placeholder, but I don't need to set placeholder for the same view ,I use two different ImageView, where 1st should visibility gone the 2nd set bitmap
I try to pass custom viewGroup to Glide() but as I understand it accepts only viewTarget.

**Comment by TWiStErRob** [comment]
You can try to write a [custom target](https://github.com/bumptech/glide/wiki/Custom-targets) to wrap these two views together, but it's non-trivial. You can find some examples of Targets in https://github.com/TWiStErRob/glide-support > Find file > enter "Target.java".

To simplify things you can try using a listener to hide the "placeholder".

**Comment by IskuhiSargsyan** [comment]
"To simplify things you can try using a .listener() to hide the "placeholder"."
.But in .listener(requestListener) I don't have access to view (even it is simple ImageView)


"You can try to write a custom target to wrap these two views together, but it's non-trivial. You can find some examples of Targets in https://github.com/TWiStErRob/glide-support > Find file > enter "Target.java"."
`.into(new ViewTarget<GlideImageView, GlideDrawable>(glideImageView) {
                    @Override
                    public void onResourceReady(GlideDrawable resource, GlideAnimation anim) {
//                        GlideImageView mView = this.view;

                    }
                });`
where 
`public class GlideImageView extends RelativeLayout {
    private View viewBackground;
    private ImageView ivCover;`
........
}
ok ?

**Comment by TWiStErRob** [comment]
That'll  measure your layout view group and then in onResourceReady you have to set the drawable to ivCover.

In listener you have access to anything, usual Java rules apply. Just create a class that implements the listener and pass in anything to the constructor, or use the anonymous inner class closure (final local variables) to access your views.

Also you have the target so if you really want: `((ViewTarget)target).getView()`.

**Comment by IskuhiSargsyan** [comment]
`package com.joomag.glide.utils.customview;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.RelativeLayout;

import com.bumptech.glide.load.resource.drawable.GlideDrawable;
import com.joomag.R;

/**
 * Created by Iskuhi on 5/20/2016.
 */
public class GlideImageView extends RelativeLayout {
    private View viewBackground;
    private ImageView ivCover;

    public GlideImageView(Context context) {
        super(context);
        loadView();
    }

    public GlideImageView(Context context, AttributeSet attrs) {
        super(context, attrs);
        loadView();
    }

    public GlideImageView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        loadView();
    }

    public GlideImageView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
        loadView();
    }

    private void loadView() {
        inflate(getContext(), R.layout.thumbnail_layout, this);
        this.viewBackground = findViewById(R.id.iv_background);
        this.ivCover = (ImageView) findViewById(R.id.iv_cover);
    }
//
//    public void setBackgroundVisibility(boolean isVisible) {
//        viewBackground.setVisibility(isVisible ? View.VISIBLE : View.GONE);
//    }
//
    public void setTestTest(GlideDrawable resource) {
//        ivCover.setImageDrawable(resource);
    }
}

    private void gDisplayImage(GlideImage glideImage, GlideView glideImageView) {


        ViewTarget<GlideView, GlideDrawable> customView = new ViewTarget<GlideView, GlideDrawable>(glideImageView) {
            @Override
            public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                GlideImageView view  = ((GlideImageView ) getView());
                ImageView ivCover = (ImageView)view.findViewById(R.id.iv_cover);
                ivCover.setImageDrawable(resource);
//or commenting the above 2 lines and calling GlideImageView setTestTest() casuses project build //fail
//view.setTestTest(resource);

            }

        };

        Glide.with(getContext())
                .load(glideImage)
//                .listener(requestListener)
                .skipMemoryCache(false)
                .into(customView);

    }


`
casuses app:package"packageName" FAILED
Execution failed for task"app:package"packageNAme"< value(110277)>0x000fff

**Comment by TWiStErRob** [comment]
That doesn't make any sense, maybe you have some rror in the xml, check your logs and stack trace.
