### ISSUE TITLE
if I set the imageview   android:layout_width="match_parent", android:layout_height="match_parent"

### ISSUE THREAD

**Issue by gushoubang** [bumptech/glide#1220]
<ImageView
                    android:id="@+id/img_loc"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content" />
but  the imageView show is not original picture,

**Comment by TWiStErRob** [comment]
Please describe your issue more and fill in more of the issue template: https://raw.githubusercontent.com/bumptech/glide/master/ISSUE_TEMPLATE.md

**Comment by TWiStErRob** [comment]
#1221
