### ISSUE TITLE
if I set the imageview   android:layout_width="match_parent", android:layout_height="match_parent"

### ISSUE THREAD

**Issue by gushoubang** [bumptech/glide#1221]
<ImageView
                    android:id="@+id/img_loc"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content" />
but  the imageView show is not original picture,
and I dont't know how to use like this
https://github.com/bumptech/glide/issues/781

**Comment by TWiStErRob** [comment]
#781 is about getting the size of the original image, not loading the original image.
You may just want `.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)` to load an 1:1 sized Bitmap.

*Note that you can edit your issues and comments with the little pencil in the upper right or just add more comments to an existing issue. (Edit button is only visible in Desktop mode on mobile or on your computer)*

**Comment by gushoubang** [comment]
yes I just want how to load an 1:1 sized Bitmap.
