### ISSUE TITLE
A problem about load a image from a invalid url.

### ISSUE THREAD

**Issue by Mybrc91** [bumptech/glide#1226]
When i load a invalid url into ImageView, then i setImageBitmap for imageview.The drawable can't visiable and stil show the placeholder.Why ?
```
Glide.with(context)
		.from(String.class)
		.placeholder(R.drawable.icon_default_round_thumb)
		.load(uri).into(imageView);

....

mIvThumb.setImageBitmap(bitmap);
```
The bitmap is from camera. When load a valid url,it is right.

**Comment by TWiStErRob** [comment]
Is `imageView` and `mIvThumb` the same?

Before you start using an ImageView normally you have to let Glide know to stop using it by: `Glide.clear(iv)`, if you always have that Bitmap available when you start the load you can also just add: `.error(new BitmapDrawable(bitmap))` so it'll be displayed automatically when the url is invalid.

**Comment by Mybrc91** [comment]
@TWiStErRob It's same. It's ok when use ```  Glide.clear(iv) ``` then setImageBitmap.Thank you very much.I don't know the api ```  Glide.clear(iv) ```.
