### ISSUE TITLE
Glide loads with lower image quality when height is set to wrap_content

### ISSUE THREAD

**Issue by AllanWang** [bumptech/glide#1227]
I'm a bit new to coding, and I decided to use Glide to load some images, and I get the following result:

Using a width of match_parent and a predefined height will load the image with good quality, but using the following ImageView layout

```xml
 <ImageView
            android:id="@+id/item_post_picture"
            android:layout_below="@id/item_post_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingBottom="@dimen/padding_medium"
            android:scaleType="fitCenter"
            android:adjustViewBounds="true"
            android:visibility="gone"
            tools:ignore="ContentDescription" />
```

Produces a much worse image. The proportions are correct though.

![screenshot_20160520-170213](https://cloud.githubusercontent.com/assets/6251823/15442130/12ca0574-1ead-11e6-89e1-34dccea84ce6.png)

This is how I'm using Glide now:

```java
 ImageView photo = (ImageView) itemView.findViewById(R.id.item_post_picture);
                photo.setVisibility(View.VISIBLE);
                Glide.with(mContext)
                        .load(sPost.getFullPicture())
//                        .fitCenter()
//                        .centerCrop()
//                        .bitmapTransform()
//                        .asBitmap()
//                        .atMost()
                        .into(photo);
```

I was looking around some other questions from others and tried a combination of the commented lines above, but it didn't change anything.

Should I be setting the height to a defined value and then change it with onMeasure as mentioned in some other posts?

**Comment by AllanWang** [comment]
Spoke too soon. 
Using [.dontTransform()](https://github.com/bumptech/glide/issues/531) did the trick.

**Comment by TWiStErRob** [comment]
That's not a fix; it's a bad workaround. It'll force Glide to load a bigger image than required. Remove the padding from the ImageView and all will be fine, see #939.

Nice report though, thanks for creating this.

**Comment by AllanWang** [comment]
It worked. Thanks for the quick response

**Comment by uzair19** [comment]
I am running Glide version 4.9.0. And I am still getting blurry gif.
My XML:
<ImageView
        android:id="@+id/launch_screen_9890_animation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/_15sdp"
        android:adjustViewBounds="true"
        android:contentDescription="@string/launch_screen_animation"
        android:focusable="false"
        android:focusableInTouchMode="false"
        android:scaleType="fitXY"
        app:layout_constraintBottom_toTopOf="@id/launch_screen_9890_route_number_txt"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/launch_screen_9890_version_txt"
        tools:src="@drawable/anim_truck_loading" />

And My Java Code:
Glide.with(LaunchActivity9890.this)
                .load(R.drawable.anim_truck_loading)
                .apply(new RequestOptions()
                        .override(Target.SIZE_ORIGINAL)
                        .format(DecodeFormat.PREFER_ARGB_8888))
                .into(imageView);

And I downloaded the Gif from here:
https://dribbble.com/shots/1651085-Load-up-Move-out

**Comment by bctpl** [comment]
> 
> 
> It's a bad workaround for this issue, it'll force Glide to load a bigger image than required. Remove the padding from the ImageView and all will be fine, see #939. You can use margin instead.
> 
> Nice report though, thanks for creating this.

I'm not giving any padding still image shows low quality

**Comment by volic** [comment]
The issue still occurred if I use different ratio proportions without any padding.
For instance for image view with 16 : 9 ratio for placeholder I will insert rotated image with 9 : 16 ratio. 
I suppose the cached image size calculated by inserted  9 : 16 image into 16 : 9 ImageView and then due to `android:adjustViewBounds="true"` stretched to 9 : 16 with low quality.
```
<ImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        android:src="@drawable/16_9_placeholder" />
```
P.S. **.dontTransform()** is worked for me also but I would prefer to have smaller correct cached image.

**Comment by CoolMind** [comment]
> It's a bad workaround for this issue, it'll force Glide to load a bigger image than required. Remove the padding from the ImageView and all will be fine, see #939. You can use margin instead.
> 
> Nice report though, thanks for creating this.

In case no padding is set, `.dontTransform()` also works well. Even if you have source and thumbnail images in a good quality and size. Even if thumbnail image equals to source.

Look at the picture: 1) common loading, 2) loading with `.dontTransform()`.
![image](https://user-images.githubusercontent.com/10630436/93596715-7fb8a380-f9c2-11ea-885e-f6329cfe6e30.png)

I suppose, Glide doesn't know the size of a resulting `ImageView` and then Android resizes a Glide image (`android:adjustViewBounds="true"` and `android:scaleType="fitCenter"`).

Maybe transformation should be applied, I can search for it.

**Comment by CoolMind** [comment]
Also upscaling works not so well as Android can. In the picture below an original or thumbnail image is shown in `ImageView` with `Glide`. No matter, `.dontTransform()` or not, it will result in aliazed image, though first two have more smooth borders.

![image](https://user-images.githubusercontent.com/10630436/93601411-d70e4200-f9c9-11ea-8536-ef29fda432e0.png)
