### ISSUE TITLE
cant load original bitmap

### ISSUE THREAD

**Issue by aprilhyuna** [bumptech/glide#1230]
use glide 3.7.0

want get original image 
but cant
other color image & other size

this is original image
![cat](https://cloud.githubusercontent.com/assets/1997167/15461280/9b02457a-20f4-11e6-84a8-be50b47b74ae.jpg)
![screenshot_2016-05-23-13-07-07](https://cloud.githubusercontent.com/assets/1997167/15461282/9fb41198-20f4-11e6-91d0-76c0f4befbda.png)

```
 Bitmap bitmap = Glide.with(mContext)
                    .load(mImageInfo.getFilePath())
                    .asBitmap()                    
                    .diskCacheStrategy(DiskCacheStrategy.NONE)
                    .format(DecodeFormat.PREFER_ARGB_8888)
                    .into(-1, -1)
                    .get()
                    .copy(Bitmap.Config.ARGB_8888, true);
```
this is use glide image

![selka_20160523_142757](https://cloud.githubusercontent.com/assets/1997167/15461298/cec77e02-20f4-11e6-95d8-62e6f5bd131a.jpg)
![screenshot_2016-05-23-14-28-25](https://cloud.githubusercontent.com/assets/1997167/15461301/d2154698-20f4-11e6-8873-5d3fd8cecc88.png)

**Comment by TWiStErRob** [comment]
Try `Target.SIZE_ORIGINAL` instead of `-1`. I think -1 is `ViewGroup.LayputParams.WRAP_CONTENT` which falls back to screen size and because of downsamplong the colors get merged.

<strike>You can use SOURCE caching to prevent downloading the image again and again, except for local files which you seem to have.</strike>

Make sure you don't `Bitmap.compress(JPEG)` as it changes the colors: http://stackoverflow.com/q/36487971

**Comment by TWiStErRob** [comment]
Let me know if you need more help, I assume the above worked for you.

**Comment by zhangchaojiong** [comment]
```
Glide.with(this).load(info.mCoverUrl).asBitmap()
				.centerCrop()
						.into(new SimpleTarget<Bitmap>(-1,-1) {
							@Override
							public void onResourceReady(Bitmap resource,
									GlideAnimation<? super Bitmap> arg1) {
								// TODO Auto-generated method stub
								if (resource == null) {
									mAlbumImageView.setImageResource(R.drawable.bg_album_default);
								} else {
									mAlbumImageView.setImageBitmap(resource);
								}
							}
					    });
```
