### ISSUE TITLE
Cancel all loading requests

### ISSUE THREAD

**Issue by amanjain08** [bumptech/glide#1231]
**Glide Version**:3.7.0

**Integration libraries**: N/A

**Device/Android Version**:6.0.1

**Issue details / Repro steps / Use case background**: 
How do I cancel all image loading request as soon as the activity goes to background. I heard of a method Glide.clear() to serve the purpose. But I am not sure that, will it cancel all the previous request or just the last one ?

**Comment by TWiStErRob** [comment]
If you look at the signature of that method it should be clear that it's for a single request/view/target. I would recommend `Glide.with(this).pauseRequestsRecursive()` in `Activity.onStop`.

Tip: http://meta.stackexchange.com/q/10647/247470
