### ISSUE TITLE
The image seems to load and reload constantly

### ISSUE THREAD

**Issue by lolobosse** [bumptech/glide#1232]
**Glide Version**: 3.7.0

**Integration libraries**: none

**Device/Android Version**: Wileyfox Swift 6.0.1

**Issue details / Repro steps / Use case background**: 
Hello there, I'm using the [material intro lib](https://github.com/spongebobrf/MaterialIntroTutorial) but I really deep dive into it and modified it; the underlaying image loading lib is Glide.

I want to have GIFs in these tutorials and I'm very close to success but I'm running into an issue and none of the issues I've found solved my problem (I even tried SNAPSHOT versions).

Let's see the code: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with(this).load(tutorialItem.getForegroundImageRes())
    .asGif()
    .dontAnimate()
    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
    .into(imageViewFront);
```

(the `dontAnimate` doesn't seem to matter)

And I got that [video](https://youtu.be/DXn_WCceibE) (it is a Youtube Link do not worry ^^)

Does it ring a bell to someone? Can someone help?

Btw, thanks Bump for the lib, I worked for one (small) competitor from yours few years ago and the technical side was, already at that time, very sharp 👍  😄

**Comment by TWiStErRob** [comment]
Not sure about this.
Did you try to load the same image but with into just a normal imageview in a normal activity?
Also try to [check logging of those loads](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) to see which one is being called and when, maybe it's reloaded for some reason and that causes flashing. If you tried 3.8.0-SNAPSHOT that should have the best GIF loader so far.

*Also see my comments on spongebobrf/MaterialIntroTutorial#11.*
*(Did you know http://blog.bu.mp/ ?)*

**Comment by lolobosse** [comment]
@TWiStErRob I got it! It is not your fault, it works on every device except mine hahahaha!!

I use a Wileyfox Swift With Cyanogen OS 13. And that seems to be the problem.

No problem with S5 Mini API 19 or Z3 Compact API 21. 

I do not know if you want to fix such things honestly and I cannot find anything in the logs

**Comment by TWiStErRob** [comment]
Since we don't really know what the problem is it's hard to fix it. If it's only your device I guess we would need physical access to one to debug; is it possible it's a Cyanogen-wide problem?

**Comment by lolobosse** [comment]
@TWiStErRob It seems that Oxygen OS is fine, but I do not have any access to another Cyanogen...

Firebase Cloud Test Lab?

**Comment by TWiStErRob** [comment]
Based on this screenshot: https://developers.google.com/cloud-test-lab/web-ui#getting_ready_to_start_a_new_test
 it looks like they only have stock versions.

**Comment by lolobosse** [comment]
Hmmm, I would need to investigate this weekend on that (we need to focus on release yet) but it would be a problem that the problem is not only happening on the gifs but also on plain pictures...

**Comment by TWiStErRob** [comment]
Did you see it in other apps? (Ones that may not be using Glide?)
Btw, we already have a device-specific fix: #758

**Comment by lolobosse** [comment]
The best will be if you can give me a list of apps that are using glide for gifs... 

9gag is working but I doubt they do not have their own stuff 😆 

But, yes I'd glad to experiment 🚀

**Comment by TWiStErRob** [comment]
I don't have a list, though some library websites may have decompiled some apps to figure out the libs they use for statistics. For fun here's a list of [GitHub projects that load GIFs](https://github.com/search?q=Glide+asgif&type=Code&utf8=✓).

I'm not even really sure where to begin investigating. Probably create a really simple app that loads a single image and is wrong on your phone. You can use `.diskCacheStrategy(NONE).skipMemoryCache(true)` to force reload all the time.

**Comment by TWiStErRob** [comment]
Any news on this?
