### ISSUE TITLE
Image Loader in different phone

### ISSUE THREAD

**Issue by itdais** [bumptech/glide#1236]
I hava google 5X   / mi 4  / mi note 2 / Samsung 6   , total four mobile
but user glide loader image ,  mi 4 and Samsung 6 can loader,
google 5X and mi note 2 loader error
code is
```java
Glide.with(context).load(url)
                .placeholder(R.drawable.def_img)
                .dontAnimate()
                .crossFade()
                .into(view);
```

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
