### ISSUE TITLE
Placeholder still shown after load completed

### ISSUE THREAD

**Issue by aLoyalStudent** [bumptech/glide#1240]
I show an ImageView in a GridView,the GridView is in ViewPager container.And I laod image from server using Glide.But Glide load image completely,the imageView still show the placeHolder image.But I refresh The View,the load image will show .Who can help me?Thanks.

**Comment by TWiStErRob** [comment]
How do you know the image has been fully loaded?
Check out https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling 
Please add your XML layout, Java code where you call Glide.... and any exceptions you may encounter related to this.
