### ISSUE TITLE
Images not loading with android support libraries 23.2.0 and above

### ISSUE THREAD

**Issue by Rakatan** [bumptech/glide#1241]
**Glide Version**: 3.7.0

**Integration libraries**: None

**Device/Android Version**: Nexus 5X, Nexus 6P, both on Android 6.0.1

**Issue details / Repro steps / Use case background**: 
I am using Glide in order to load images in a custom image gallery. When using android support libraries with versions 23.2.0 and above, no images are displayed. Using for example the 23.1.1 set, images are loaded as expected. I have enabled logging and no errors are thrown.
I will update this question with any details that are requested.

Support libraries used:
```
    com.android.support:appcompat-v7:23.4.0
    com.android.support:design:23.4.
    com.android.support:percent:23.4.0
    com.android.support:support-v4:23.4.0
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).
    load(item.getThumbUri()). // The image URI
    listener(requestListener).
    error(R.drawable.ic_error_outline_white_48dp).
    dontAnimate().
    into(holder.image);
```

**Layout XML**:
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:layout_weight="1"
    android:layout_margin="2dp">

<ImageView
        android:id="@+id/gallery_image"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="centerCrop"/>

</RelativeLayout>
```
 
The root layout's width is 0dp due to the fact that it is calculated at runtime based on screen size.

**Stack trace / LogCat**: No error messages in either the verbose logs or request listeners, Glide is completely silent.

**Comment by TWiStErRob** [comment]
I'm using 23.4.0 (updated from 23.2.x) in https://github.com/TWiStErRob/glide-support and another app of mine for about 2 weeks now and I didn't see any problems. Here are some questions/ideas to try.

Is this the only place in the app where it doesn't work?
Did you try a clean build after changing the support version?
Did you try to get rid of the sizing trickery (just for temporarily) and use some hardcoded `dp` value?
You can also confirm the view has size by setting a background color on the view.

There's some mocking around with vectors in 23.2.0 which may have broken other stuff, see [blog post](http://android-developers.blogspot.hu/2016/02/android-support-library-232.html), I would suggest trying 23.4.0.
Is it possible the AppCompat theme changed and that has an effect on your layout?

Complete silence probably means that Glide is waiting for a size to become available.
Try to launch the app in debug mode with breakpoints present on the first lines of `GenericRequestBuilder.into(Y)`, `Engine.load`, `EngineRunnable.run`, `ViewTarget.SizeDeterminer.getSize` and `checkCurrentDimens` and try to figure out where it's waiting.

Alternatively do you use `pauseRequests` somewhere? Maybe some lifecycle thing changed and your loads are paused (you should be able to confirm this while debugging `into` which calls `runRequest`).

**Comment by Rakatan** [comment]
Hello @TWiStErRob  and thank you for your comment.
I have tried your suggestions and the issue also happens with 23.4.0

**However**, i've tried to get rid of the "sizing trickery" as you suggested and used hardcoded dp values in the XML. Images are now displayed. 

Any idea why this may happen and how I could fix it?

**Comment by TWiStErRob** [comment]
Not sure how a support lib change can affect a RelativeLayout and ImageView pair. Maybe the answer lies in the parent(s) of these. There are some weird attributes in your sample. For example I'm not aware of orientation of RelativeLayout. weight + width=0 suggest a LinearLayout(horizontal) as parent, but this is the whole layout file.

I think you just need to make sure the view has a size before trying to load anything into it. Glide will wait for a valid size before continuing, so your "sizing trickery" needs to make sure to set a valid width and that the ImageView is laid out again and gets that width too. The height wrap_content will fall back to screen height so Glide will receive a target size of <calculated width> x <screen height> and load the image with that size. You could try reverting back to the state when you reported this and adding a simple `.override(w,h)` to see if that makes the image load. That's a workaround; I think a real fix would be to make sure the ImageView is sized correctly before loading by setting a background and checking that it's visible without load with Glide.

Use the points of debugging I mentioned to find out what Glide sees and figure out why it sees those values.

**Comment by Rakatan** [comment]
I managed to fix it specifying the width and height of the root relative layout to wrap_content. This way the resized imageview dictates it's size and it seems to work just fine for now :)

Thank you so very much for your help, if anything else turns up i'll reopen this issue.
