### ISSUE TITLE
In recyclerview when i  use  notifyItemChanged(position)

### ISSUE THREAD

**Issue by itxuye** [bumptech/glide#1242]
In recyclerview when i  use  notifyItemChanged(position) ,i found that the imageview refresh , but i don't want to refresh it .How can i fix it ?

**Comment by TWiStErRob** [comment]
You tell your adapter that your item changed, but you don't want the adapter to react to changes?

Glide loads should be idempotent which means that loading an already loaded image should make no difference, it will be loaded from active resources or memory cache synchronously. Why is it a problem that it goes through a cycle? It should be unnoticeable to the user.

If you want to be clever about it you can save which item is bound to a particular ViewHolder by adding an extra field for your model object. You can then check if the ViewHolder's model and the model you're about to bind are the same to figure out if RecyclerView is rebinding/refreshing the same position.

**Comment by itxuye** [comment]
@TWiStErRob  Thanks for your answer ! The problem is that  I  want only refresh other views such as textview but not the imageview .

**Comment by TWiStErRob** [comment]
Yes, I understand that, but why? Using Glide makes it effective to always just load things, it'll serve you the fastest possible way.

**Comment by itxuye** [comment]
@TWiStErRob Thanks you.Now I delete the recyclerview default animation codeq to avoid it。Because my boss don't want to refresh the imageview.

**Comment by TWiStErRob** [comment]
Glad you found a way that satisfies your case.

We still don't know why ... I'm getting really curious ;)
You can tell your boss that loading the same image into the same ImageView is an idempotent operation and is done from a memory based cache synchronously really fast.
