### ISSUE TITLE
If the url  constantly changing，how can I set the Config???

### ISSUE THREAD

**Issue by zhouhytx2010** [bumptech/glide#1243]
Hi, I have a question when I use Glide, can you help me deal the problem ,thank you! 
In our project, our service return url like this:

http://function-private-hls.oss-cn-hangzhou.aliyuncs.com/x/10776/timeline/1462008313s0s4_thumb.jpg?Expires=1464784197&OSSAccessKeyId=RCHafDRGNN6zBdFe&Signature=TAp2IbcSbjNbYLesfEFXuOgKlkY%3D

Before  "?Expires=" ,the content does not change, but after "?Expires=" the content changes constantly.But the picture will not change.  How can I set the Config, avoid picture repeat Download?

Thank you very much!

**Comment by TWiStErRob** [comment]
See #501 and #607 for two different approaches. He custom model is less hacky and more flexible I think.

**Comment by zhouhytx2010** [comment]
Thank you very much. This help me!
