### ISSUE TITLE
Resize asbitmap multiple images

### ISSUE THREAD

**Issue by FunnyDevs** [bumptech/glide#1245]
I have tried this code to resize multiple images with different sizes (i must create marker on maps):

> ```java
Glide.with(getContext())
.load(message.getUserImage())
.asBitmap()
.centerCrop()
.transform(new CropCircleTransformation(getContext()))
.into(new SimpleTarget<Bitmap>(50,50)
    {
       @Override
        public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation)
        {
           int b = resource.getWidth();
           int c = resource.getHeight();
        }
    });
```

The problem: measuring bitmap width and height (with b and c variables ),  the values are different from what i have written in "SimpleTarget", and for different size images the output are different circle images (and so not uniform markers).

**Comment by TWiStErRob** [comment]
`asBitmap` will try to approximate the size, but the exact size is done by `centerCrop` which you overrode with crop circle.

Try `.transform(new CenterCrop(), new CropCircle())` and follow the code in `centerCrop` to see why you need this. (Same works with `fitCenter`.)

See also #290 which you may run into later.

**Comment by FunnyDevs** [comment]
Thanks a lot, now it works!
