### ISSUE TITLE
Can't load image from web using Glide with Kotlin

### ISSUE THREAD

**Issue by aleien** [bumptech/glide#1246]
Hi! I am experiencing troubles using Glide to load images from web with Kotlin. 
glide:3.7.0
No extra libraries
Sony Xpreia Z2, Android 6.0

I use Glide as it shown in most basic guides, except that I use Kotlin, not Java:
```java
Glide
                .with(holder?.image?.context)
                .load("https://s-media-cache-ak0.pinimg.com/736x/f0/ef/36/f0ef36a66dfc6f193f4939b6c57d2500.jpg")
                .fitCenter()
                .into(holder?.image)
```

I tried loading image from resource, which works fine, and web - fails. Picasso didn't help too. AndroidManifest countains `<uses-permission android:name="android.permission.INTERNET" />`
Tried loading into plain imageview, not one used in recyclerview - didn't help.

I'd apprecciate any help. Thank you. 
My brain is exploding.

**Comment by TWiStErRob** [comment]
Try https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener

Tip: don't overuse the elvis operator: there's no point in null-safe access when you know it won't ever be null. It's useful when you would otherwise have to do a lot of null checks, which is not the case with ViewHolders.

**Comment by aleien** [comment]
Thank you very much, Twister! After enabling logging I found problem immediately. Seems instant run (that same old lazy guy, ehhhhh) was ignoring my changes to AndroidManifest, effectively removing internet permission for app. Yikes. 
At least I know about Glide debugging from now on. Thank you very much for fast response! 

Also thanks for the tip! Although compiler doesn't give me an option to not use these two.
