### ISSUE TITLE
glide load img ,but background is green?

### ISSUE THREAD

**Issue by cococa** [bumptech/glide#1250]
Glide
        .with( context )
        .load( "http://image.kuaiqiangche.com/data/attachment/2016-04-26/o_1ah8asnbk9uc17931tajgek5fb7.jpg" )
        .into( imageView);

when load the this img url , the bg is green ;

**Comment by cococa** [comment]
and I changed decodeFormat to  DecodeFormat.PREFER_ARGB_8888,  ,still not work

**Comment by TWiStErRob** [comment]
You need to clear the caches after change. DecodeFormat is not part of the cache key.

**Comment by cococa** [comment]
thanks
it's ok now
