### ISSUE TITLE
How to show only custom area selected by crop?

### ISSUE THREAD

**Issue by t7ank** [bumptech/glide#1251]
Hello!

I want to show only specific area of image, but i can not find any examples how to do it with Glide.
When picture is taken and crop area selected, i save values CropX, CropY (coordinates in original image) and CropWidth, CropHeight (lenght of croped image).

But i can not get it working with Glide to show only specific area, it always load whole image.
Example what i want to show/achieve:
![glidecrop](https://cloud.githubusercontent.com/assets/19713784/15792394/4a421f06-29dd-11e6-950f-8ce1a9dd3a6d.jpg)
(but whole picture is loaded).

Is this possible to do it with Glide? If similar topic already exists please feel free to link me there.
Even some keyword would help what to search.
Thanks, T.

**Comment by TWiStErRob** [comment]
Glide only supports the most basic transformations ImageView does, if you want something more specific you have to write it yourself (or use a lib).

Check out wasabeef's library maybe there's a special crop that already does this. If not take a look at CenterCrop's code and modify it so it can handle any xywh tuple. You could also look for top crop or face crop transformations that were written for Glide on the interwebs.

Mind you that you may be better of performance-wise if you write a decoder that is not using the Downsample, but instead uses a BitmapRegionDecoder and loads/returns only the part of the image that's relevant. If you go down his route you can also add more transformations. I made a complex example in #700 that could be reused here.

**Comment by t7ank** [comment]
I have managed to solve this problem. To show only part of image to show from original image.
I hope it helps someone. If anyone have any better solution please share.
`public class CropGlideTransformation extends BitmapTransformation {

    private MyImage myImage;

    public CropGlideTransformation(Context context, ImageGON imageGON) {
        super(context);
        this.imageGON = imageGON;
    }

    @Override
    protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
        
        Bitmap bmOverlay = Bitmap.createBitmap(
                    toTransform,
                    myImage.getCropX(),
                    myImage.getCropY(),
                    myImage.getCropWidth(),
                    myImage.getCropHeight());
        
        return bmOverlay;
    }

    @Override
    public String getId() {
        return String.valueOf(myImage.getId());
    }
}`

MyImage.class
`public class MyImage{
    private int id;
    private String name;
    private int cropWidth;
    private int cropHeight;
    private int cropX;
    private int cropY;

    //getters & setters`
