### ISSUE TITLE
Can I set two GlideModules in one project?

### ISSUE THREAD

**Issue by zhouhytx2010** [bumptech/glide#1252]
Can I set two GlideModules ，then I can show different Picture resolution in my project ? 
Like this:
public class GlideConfiguration1 implements GlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // Apply options to the builder here.
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_565);
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        // register ModelLoaders here.
    }
}

public class GlideConfiguration2 implements GlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // Apply options to the builder here.
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        // register ModelLoaders here.
    }
}

I want to use GlideConfiguration1 show the pic in Listview or GridView  and use GlideConfiguration2 show the big pic ， use two GlideModules  in my Project. How do I set the Config? Thank you very much.

**Comment by TWiStErRob** [comment]
`.asBitmap().format(...)` on the load builders. You can't register different configuration, Glide is a singleton.
