### ISSUE TITLE
XiaoMi4 Glide first open app load ImageView show white border

### ISSUE THREAD

**Issue by WuZhenXing** [bumptech/glide#1254]
**Glide Version**: 3.7.0

**Integration libraries**:

**Device/Android Version**: android6.0 XiaoMi4

**Issue details / Repro steps / Use case background**:XiaoMi4 use Glide first open app load ImageView picture, have white border, no kill app process, just normal. if kill process restart app also show ImageView white border, no kill process reopen app no show white border

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java

		Glide.with(imageView.getContext()).load("http://baidu.com/xxxxxxx")
				.centerCrop()
				.placeholder(R.drawable.miss_image)
				.diskCacheStrategy(DiskCacheStrategy.SOURCE)
				.crossFade()
				.into(imageView);

```

**Layout XML**:
```xml
 <ImageView
            android:id="@+id/headerBgImageView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop"
            android:src="@drawable/bg4"/>
>

```

![image](https://cloud.githubusercontent.com/assets/6036393/15811001/c7de605a-2bd6-11e6-8bb5-5f18f96a743a.png)

![image](https://cloud.githubusercontent.com/assets/6036393/15811011/d467f26e-2bd6-11e6-80bc-5bc7c38d6195.png)

![image](https://cloud.githubusercontent.com/assets/6036393/15811020/de3f845a-2bd6-11e6-8ba7-33781de3cd9d.png)

**Comment by TWiStErRob** [comment]
If you remove change crossFade to dontAnimate does that make his problem go away?

**Comment by WuZhenXing** [comment]
@TWiStErRob remove crossFade , can't solve this problem

**Comment by TWiStErRob** [comment]
Remove `crossFade()` is the same as having `crossFade()`, that's the default. Did you also add `.dontAnimate()`?

**Comment by cantalou** [comment]
@TWiStErRob 
![qq 20160624163632](https://cloud.githubusercontent.com/assets/10027821/16332723/135074b8-3a2a-11e6-8c00-1d68588b7d7d.png)
I have the similar problem. It happened when I every time launch activity and first time loading image. If I refresh data from server and use glide to load the image again, then it works fine. 

`        <ImageView
            android:id="@+id/activity_theme_list_adapter_item_logo_iv"
            android:layout_width="105dp"
            android:layout_height="70dp"
            android:scaleType="centerCrop"/>`

**Comment by TWiStErRob** [comment]
@cantalou yours always has a border, the weird thing is that the first time it is squashed a little.

**Comment by WuZhenXing** [comment]
@TWiStErRob thank you

**Comment by TWiStErRob** [comment]
@WuZhenXing so did you solve it?

**Comment by WuZhenXing** [comment]
@TWiStErRob YEAH!!!!  thank u
