### ISSUE TITLE
Troubles Updating Custom ImageView

### ISSUE THREAD

**Issue by mcoded** [bumptech/glide#1258]
**Glide Version**: 3.70 (with the OkHttp3 integration)

**Device/Android Version**: Nexus 5X API 23 Emulator

**Details**: 
I'm currently transitioning an app to Glide and am running into some trouble when using a [custom view used to create rounded images](https://gist.github.com/mcoded/7052cc778700d186a0fbcab8982b44e9). When using this view in conjunction with a placeholder, it seems that Glide is unable to update the image after it has been loaded. This leads to two possible outcomes:
* If the image was quickly loaded via the cache, it will be set properly.
* If the image needs to be downloaded, the placeholder will be set but will never be updated once the image download is complete. This View will always show the placeholder until Glide is called again.

**Glide load line**:
```java
Glide
  .with(view.getContext())
  .load(url)
  .diskCacheStrategy(DiskCacheStrategy.SOURCE)
  .placeholder(R.drawable.placeholder)
  .into(view);
```

My guess is that this is likely due to some error in the custom view (though it does update correctly outside of Glide) but I've been unable to find it so far. Any pointers would be appreciated.

**Comment by TWiStErRob** [comment]
Same as any other circle view, see the compatibilty section in the readme. `drawableToBitmap` is just not workable for any animated stuff and crossFading is the default. Try dontAnimate.

**Comment by mcoded** [comment]
That fixes it, thanks!
