### ISSUE TITLE
Is there anyway to query image from cache synchronously?

### ISSUE THREAD

**Issue by Muyangmin** [bumptech/glide#1263]
**Glide Version**:3.7.1

**Integration libraries**:OkHttp3

**Use case background**: Now I have to implement a feature to save users' data traffic on non-WiFi network, called **"Save Network Mode"**.   
Once user enter this mode, then for any image:
* if available from memory/disk cache, then display it;
* if not, just display a placeholder image, and **do not request network**.  
Some code I imagined like this:
```Java
List<Drawable> list =  PerfectGlide.query(uri)
        .inMemoryCache(true).inFileCache(true)
        .minWidth(48).minHeight(48)
        .execute();//Query From disk/memory
if (list!=null && list.size()>0){
    //Display as normal
}
else{
    //do NOT request
    imageView.setBackgroundResource(R.drawable.placeholder);
}
```
I know UIL can query image by uri, but I can't find a way to achieve this by using Glide. Really need help, thanks for all.

**Comment by TWiStErRob** [comment]
#639 has a similar use case, though yours is much simpler so far. There's no way to find out which Uri has different sizes cached, so for that you need to use SOURCE/ALL cache... this will mean that you can load each Uri into any sized target without network roundtrip.

Here's a take on how I would implement your use case:
```java
DrawableRequestBuilder<String> glide;
if (saveNetworkMode) {
	glide = Glide
			.with(this)
			.using(new NetworkDisablingLoader<String>())
			.from(String.class)
	;
} else {
	glide = Glide
			.with(this)
			.fromString()
	;
}

glide
		.load(url)
		//.diskCacheStrategy(DiskCacheStrategy.ALL)
		.error(R.drawable.glide_placeholder)
		.into(imageView)
;
```
You can find the latest `NetworkDisablingLoader` in [my support project](https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/utils). Using disabling loader will fail the load with error, so you have to put the placeholder there. Using ALL is optional, you have to decide whether you want to store/load the original or the transformed image in cache (or both).

**Comment by Muyangmin** [comment]
Thanks a lot, I'll try it.
