### ISSUE TITLE
The method diskCacheStrategy(DiskCacheStrategy) is undefined for the type  RequestBuilder<Bitmap>

### ISSUE THREAD

**Issue by lcn1988** [bumptech/glide#1265]
I use master version, use 

```
Glide.with (mContext).AsBitmap ().DiskCacheStrategy (DiskCacheStrategy.NONE).SkipMemoryCache ().Load (URL).Into (ImageView) () ;
```

but compile error
Method diskCacheStrategy is (DiskCacheStrategy) undefined for the type The
RequestBuilder<Bitmap>

How to do？

**Comment by TWiStErRob** [comment]
The master branch is an unreleased version, so there's no documentation for it; the APIs changed a lot compared to 3.x. See #340 and the linked design document.

For examples of API usage you can look around:
 * https://github.com/bumptech/glide/tree/master/samples
 * https://github.com/TWiStErRob/glide-support/tree/master/src/glide4
