### ISSUE TITLE
Using placeholder ruins aspect ratio of loaded image

### ISSUE THREAD

**Issue by matejhacin** [bumptech/glide#1266]
Just came across a weird issue.

    Glide.with(appContext)
            .load(glideUrl)
            //.placeholder(R.drawable.loading_files)
            .error(R.drawable.unsupported_files)
            .thumbnail(0.1f)
            .centerCrop()
            .listener(this)
            .into(imageView);

My placeholder is has very different aspect ratio than the image I load. So it seems like when I use placeholder before loading ImageView, it will mess up the final image aspect ratio.

Let me know if my explanation doesn't make sense and I will provide an example.

**Comment by TWiStErRob** [comment]
How about #363? (see last comment for the best solution if you don't want to `dontAnimate`)
