### ISSUE TITLE
LruCache NamingPolicy?

### ISSUE THREAD

**Issue by adauvalter** [bumptech/glide#1276]
**Glide Version**: 3.7.0

**Integration libraries**: glideOkHttpVersion = '1.4.0'

**Device/Android Version**: Nexus 5x Android 6.0.1

I'm trying to save cached images like:
````
builder.setDiskCache(() -> {
            final File cacheLocation = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), ALBUM);
            if (!cacheLocation.mkdirs()) {
                Timber.d("Directory not created");
            }
            return DiskLruCacheWrapper.get(cacheLocation, CACHE_SIZE);
        });
`````
and the question is, if I could set the name policy for cached images, because now they are saved as `xxxxxxx.o` and I would like to see all those cached images in Gallery App, so that means that they should have an `jpg` of `png` extension

**Comment by TWiStErRob** [comment]
A cache is not an album. A cache is a fast way to retrieve images that would take a long time over network. If you want to create named images publicly available in an album I suggest you grab a networking library like OkHttp, download the albums/images to a public directory yourself and use `load(File).diskCacheStrategy(NONE)` to load them and prevent duplication on the phone's storage. If the images are big and you're loading a small thumbnail consider `.diskCacheStrategy(RESULT)`.

**Comment by adauvalter** [comment]
Thank you, I made it with okHttpImageFetcher. This Issue could be closed.
