### ISSUE TITLE
FileNotFoundException when loading from path

### ISSUE THREAD

**Issue by TigranSarkisian** [bumptech/glide#1280]
Here https://github.com/bumptech/glide/issues/867  TWiStErRob writes

>  Note that you don't have to worry about all this if you pass the original absolute path String directly to load, Glide will load it correctly. The first three loads I quoted above are equivalent.

but i am trying to load file:///storage/emulated/0/Android/data/com.gz.template/Util/20160606_154656.jpeg

and it says FileNotFoundException

code

```java
Glide.with(this)
    .load(url)
    .asBitmap()
    .placeholder(R.color.custom_orange)
    .error(R.color.custom_orange)
    .diskCacheStrategy(DiskCacheStrategy.ALL)
    .listener(new RequestListener<String, Bitmap>() {
        @Override
        public boolean onException(Exception e, String model, Target<Bitmap> target, boolean    isFirstResource) {
            e.printStackTrace();
            return false;
        }
        @Override
        public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
            return false;
        }
    })
    .into(mIvGlide);
```

i tried also 
create URI and File from this path - FileNotFoundException also

**Comment by TWiStErRob** [comment]
Unix and hence android is case sensitive, is your folder called `Util` or `util`?

I would suggest to run this code to check what's missing:
```java
String fileName = "/storage/emulated/0/Android/data/com.gz.template/Util/20160606_154656.jpeg";
File file = new File(fileName);
while (file != null) {
	Log.d("FILE", file + " exists=" + file.exists());
	file = file.getParentFile();
}
```

**Comment by TigranSarkisian** [comment]
Problem was in "case sensitive", thanks,  i missed such obvious thing as  case sensitive.

**Comment by KitTak** [comment]
java.io.FileNotFoundException: No such file or directory: '/storage/emulated/0/Android/data/com.harmonywisdom.mobile.soldier/image/th1418382339181.JPEG'

code 

 Glide.with(getContext()).load(new File(remoteUrl)).asBitmap()
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .thumbnail(0.1f)
                    .listener(new RequestListener<File, Bitmap>() {
                        @Override
                        public boolean onException(Exception e, File file, Target<Bitmap> target, boolean b) {
                            e.printStackTrace();
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(Bitmap bitmap, File file, Target<Bitmap> target, boolean b, boolean b1) {
                            return false;
                        }
                    })........

**Comment by TWiStErRob** [comment]
Check if each path elememt exists, my suspicion is JPEG should be jpeg at the end. There's code exactly for this above. Or you can `adb shell` and then use `cd folder` and `ls` to see what's really there.

For local files you should be using `diskCacheStrategy(NONE)`, because otherwise the whole file is duplicated in Glide cache. At worst RESULT if your thumbnails are small or the originals are huge.

**Comment by KitTak** [comment]
@TWiStErRob thks~ Problem has been resolved

**Comment by varun7952** [comment]
Hey i have this problem from past 1 year and its still not resolved by posting on stackoverflow now i am going to trying my luck here. Please help me.

`Glide.with(getActivity()).load(file).into(uploadImage);`
I m trying to load an image from my camera folder by custom gallery which return image path like that.
/storage/emulated/0/DCIM/Camera/IMG_20190430_221429.jpg

Then i tried your code to check if its valid path or not 
here is the result

> D/FILE: /storage/emulated/0/DCIM/Camera/IMG_20190430_221429.jpg exists=true
D/FILE: /storage/emulated/0/DCIM/Camera exists=true
D/FILE: /storage/emulated/0/DCIM exists=true
D/FILE: /storage/emulated/0 exists=true
D/FILE: /storage/emulated exists=true
D/FILE: /storage exists=true
D/FILE: / exists=true

My image still not loading into ImageView
