### ISSUE TITLE
Where can I get the class and architecture diagram of the glide library

### ISSUE THREAD

**Issue by khandelwaludit** [bumptech/glide#1286]
Hi,
I wish to understand the architecture of glide. Can you please point me out to the right place.

Regards
Udit

**Comment by TWiStErRob** [comment]
Check out the wiki for description: https://github.com/bumptech/glide/wiki
This is the only diagram I'm aware of: https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit?usp=sharing

Feel free to share any diagrams you may create from source code.

**Comment by khandelwaludit** [comment]
Sure. Thanks :)
