### ISSUE TITLE
Local GIF is incorrectly decoded for playback

### ISSUE THREAD

**Issue by osama** [bumptech/glide#1289]
**Glide Version**: 3.7.0
**Integration libraries**: OkHttp3
**Device/Android Version**: Nexus 5X Emulator, Galaxy S6 (Both Marshmallow)

**Issue details**: 
I'm trying to load a local GIF into an `ImageView` via Glide and am noticing some errors in the way it is played. The GIF consists of a speaker animation that is surrounded by a rectangular border. However, when loading via Glide, the border only shows up for the last frame of the GIF (instead of consistently being there throughout the animation). The bugged out animation looks as follows:
![Bug](https://thumbs.gfycat.com/CostlyQuarrelsomeKitten-size_restricted.gif)
[I've included both the original GIF and a recording of how it is rendered in this ZIP file.](https://github.com/bumptech/glide/files/335226/original_and_error.zip) Since this is a local resource, there are several versions of the GIF included with the app (for `mdpi`, `hdpi`, and `xhdpi`). In the attached examples, I've used the resource for `xhdpi`. The GIF itself looks correct to me upon investigation, leading me to believe that this bug might be due to an error in Glide's playback.

**Glide load line**:

``` java
Glide
  .with(getContext())
  .load(R.drawable.watch_video_speaker)
  .diskCacheStrategy(DiskCacheStrategy.NONE)
  .into(speakerIcon);
```

**Layout XML**:

``` xml
<ImageView
  android:id="@+id/speaker_animation"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  android:layout_marginBottom="@dimen/watch_video_animation_bottom_padding"
  android:visibility="@integer/watch_video_animation_visibility"
  tools:src="@drawable/watch_video_speaker" />
```

I realized when looking at this `ImageView` that `wrap_content` is generally not recommended for use with Glide. However, setting a concrete width and height (using `dp`) did not resolve the issue.

**Comment by TWiStErRob** [comment]
Try 3.8.0-SNAPSHOT: https://github.com/bumptech/glide/wiki/Snapshots
I fixed a lot of GIF issues already.

**Comment by mcoded** [comment]
Thanks. Any ETA on a stable release of `3.8.0`? I'm hesitant to ship a snapshot to production.

**Comment by TWiStErRob** [comment]
No eta, maintenance dev is slow on 3.x branch. You can see how seldom there's a commit:
https://github.com/bumptech/glide/commits/3.0

**Comment by sbaar** [comment]
@TWiStErRob After comparing multiple implementations of android gif decoders and amassing a collection of gifs that are broken in novel ways, I can confirm that your 3.8 snapshot seems to be the most stable and consistent at playing them all. However, in [this file](https://dl.dropboxusercontent.com/u/5742211/1001249.gif) it appears that it is corrupted on its first play through then fine on subsequent ones.

**Comment by TWiStErRob** [comment]
@sbaar can you please open a new issue describing the problem in detail? (Hopefully with screen recoding)

**Comment by sbaar** [comment]
@TWiStErRob Fyi it works fine in glide itself, it's only when I extract the gifdecoder into my own app that I see the problem of the first run being corrupted on a few of the gifs, so your implementation is probably fine.

**Comment by sjudd** [comment]
3.8.0 was (finally) released.
