### ISSUE TITLE
load image have green background

### ISSUE THREAD

**Issue by machao669** [bumptech/glide#1292]
### first load (this image style  is jpg)
![first](https://cloud.githubusercontent.com/assets/14209984/16402952/3b7117ee-3d23-11e6-99e9-779908f7dc6f.png)

### next load, have green background,why ? and how to fix
![two](https://cloud.githubusercontent.com/assets/14209984/16402968/588830a6-3d23-11e6-8727-ce69987dd172.png)

#  #Thanks

**Comment by TWiStErRob** [comment]
[Googling "Glide green background"](http://www.google.com/search?q=glide+green+background) gives me 7 relevant results on the first page.

See #305 and related issues.
