### ISSUE TITLE
Is there any way to load images from server if cached image is updated in server

### ISSUE THREAD

**Issue by Nickx27** [bumptech/glide#1293]
Hi,
Actually its not an issue, its a question :).
I'm using glide to cache images from network, so that I can able to render the same images easily later. My question is that suppose I'm using a listview to render 1000 user avatars and a few of them are changed to new ones say about 100, so how can i handle that. I used signatures with time when first loaded, but found not helpful. As simply, if the I'm scrolling a listview, how can I effectively use the changes in avatars. 

Thanks in advance.

**Comment by TWiStErRob** [comment]
`.signature()` is the way to go. You just have to find the right value. You're getting the user avatar list from the server. When you get that, the server should send the last modified date of the avatar images and you use that as signature. This means that as soon as the server sends a new date Glide will have a cache miss and redownload the avatar.

You can find more discussion in #624 and related issues. Feel free to ask follow-up questions here, even though I'll close this.

**Comment by Nickx27** [comment]
Thanks for the feedback @TWiStErRob , the point is clear now, but unfortunately, there is no such service implemented in backend. One more question, I'll force glide to fetch images each time from server, is there any functionality to use the previously cached image as placeholder and upon successful fetching, the image can be replaced.

**Comment by TWiStErRob** [comment]
Depends on how you force fetch. If you use a changing signature to force fetch (e.g.a daily changing number) then you have to use the previous valid signature for each image. You'll need to store which image was last seen by the user and when. Remeber that the user may not have opened the avatar list yesterday. Try something like a `glide.load(avatar).signature(fresh).thumbnail(glide.load(avatar). signature(lastDisplay)). listener(lastDisplayUpdater).into(...)`. Be sure to constrain the Glide cache size so the LRU can evict the unused avatars faster to prevent piling up 100s of the same image in cache.

**Comment by Nickx27** [comment]
Wow, thanks gonna try this, I'll get back to you for help, if anything more needed :)

**Comment by elhelow** [comment]
This worked with me , 
.diskCacheStrategy(DiskCacheStrategy.NONE)
                .skipMemoryCache(true)

**Comment by TWiStErRob** [comment]
@elhelow That disables most of the handy features of Glide, it'll not invalidate the cache, but **always** make a network request.
