### ISSUE TITLE
SimpleTarget in thumbnail

### ISSUE THREAD

**Issue by TigranSarkisian** [bumptech/glide#1294]
I am loading image from url and trying to load thumbnail from another url! When thumbnail is loaded I receive bitmap in onResourceReady - great, but question is  can i  somehow  receive  separate callback when thumbnail is be loaded?

something like this 
```java
 Glide.with(this)
                .load(mImageUrl)
                .asBitmap()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                  // set seperate SimpleTarget to receive callback from thumb exactly here
                .thumbnail(Glide.with(this).load(mThumbUrl).asBitmap().into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                        displayThumb(bitmap);
                    }
                }))
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                        displayImage(bitmap);
                    }
                });
```

**Comment by TWiStErRob** [comment]
Why don't you just start two loads separately into two targets?
You could also use two separate listeners.
Just curious: Why are you using SimpleTarget? There may be a better solution.

**Comment by TigranSarkisian** [comment]
>Why don't you just start two loads separately into two targets?
Because it is not so beautiful as if in one load ! Moreover Glide has .thumbnail() for this purposes but it's not very convenient for me while it sends all callbacks in one onResourceReady, onResourceReady waits callbacks from main url but also receives from thumbUrl, even if i use RequestListener for thumbnail.

>Just curious: Why are you using SimpleTarget? There may be a better solution.
Why SimpleTarget is not the best way here?

**Comment by TWiStErRob** [comment]
> it sends all callbacks in one onResourceReady, onResourceReady waits callbacks from main url but also receives from thumbUrl

A Target is seen as a single place on a display. It shouldn't matter what you display there, because whatever you receive is the valid resource at that time and anything you received previously is not valid any more (after onLoadCleared). If you're trying to animate between thumb and full you're  working around Glide's animation framework.

> i am caching data

This also means you're working around Glide, it has multiple levels of caching, really powerful, but you're trying to ignore it and do it yourself.

> Why SimpleTarget is not the best way here?

Not sure, no idea really what you're doing. All I see is that the Bitmaps escape somewhere via `display*()`.

---

Anyway, since you want to distinguish between thumb and full load and don't want a listener I figured you could (ab)use the animation for that:
```java
Glide
.with(...)
.load(...)
.asBitmap()
.thumbnail(Glide
    .with(...)
    .load(...)
    .asBitmap()
    .crossFade()
)
.dontAnimate()
.into(SimpleTarget)
;

onResourceReady(Bitmap bitmap, GlideAnimation anim) {
    if (anim == NoAnimation.get()) {
        displayImage(bitmap);
    } else {
        displayThumb(bitmap);
    }
}
```

**Comment by TigranSarkisian** [comment]
> Anyway, since you want to distinguish between thumb and full load and don't want a listener I figured you could (ab)use the animation for that:

thanks!

> This also means you're working around Glide, it has multiple levels of caching, really powerful, but you're trying to ignore it and do it yourself.

No, a mean i use Glide cache  diskCacheStrategy(DiskCacheStrategy.ALL)

so this two questions remains:

Another point with two loads instead one - i am caching data, i suppose when using one load Glide ignore thumb loading when it has cached image?

One more problem of 2 loads - first time i ask glide to load thumb and main url separately - great, second time when they both cached glide can load in wrong order - first main url then thumb:)

**Comment by TWiStErRob** [comment]
> No, I mean i use Glide cache diskCacheStrategy(DiskCacheStrategy.ALL)

Yep sorry, I realised  after pressing comment and edited it, I just wasn't fast enough ;)
(edit also answers Q1)

> By the way - Glide not allow use crossFade with asBitmap..

Yes it does, I implemented it in 3.8.0 (it's just not released yet). You get the idea through. You can create two different dummy animations, using one of the `animate()`s, which you can somehow distinguish and you'll know which one is the thumb.

> both cached glide can load in wrong order

Yep you need to do some ordering yourself, but it shouldn't be hard: once you received a full image just ignore any thumbnails.

---

I'm really curious now: where do those Bitmaps go? Where are you displaying them?

**Comment by TigranSarkisian** [comment]
>You get the idea through. You can create two different dummy animations,

got it 

>I'm really curious now: where do those Bitmaps go? Where are you displaying them?

here it is:

1. First I load bitmap  from url with Glide
2. then I have to scale it depending on bitmap actual size and devices screen size (project requires) 
3. after some calculations I set it to view - mIvPhoto.setImageBitmap(Bitmap.createScaledBitmap(loadedBitmap, imageW, imageH, false))

**Comment by TWiStErRob** [comment]
> here it is:

Thanks!
That sounds like you don't need a SimpleTarget for that. You need an `into(mIvPhoto)` and a `.transform(new BitmapTransformation(){...})` that does the scaling. That way you probably don't even need `.asBitmap()` and can `crossFade` to your heart's content ;)

**Comment by TigranSarkisian** [comment]
>That sounds like you don't need a SimpleTarget for that. You need an into(mIvPhoto) and a

ok, but i need to know initial bitmap size (loaded from url) to calculate scale ratio, in suggested above case  how is it possible?

**Comment by TWiStErRob** [comment]
You get the same Bitmap, just in an earlier phase of Glide's pipeline. Based on this you should have the same amount of info ready for you (plus the target size you get as `int`s so no need to reference the ImageView). The display and resource management is handled better because you can use `ImageViewTarget`. You may need to use `SOURCE` though because `RESULT` is saved from the Bitmap you return and not sure how scaledBitmap works when saved and loaded. I think you should give transform a try and see if it's feasible in your case. It has much more benefits for a potentially very fast implementation time. Read the JavaDoc of `BitmapTransformation.transform`.

**Comment by TigranSarkisian** [comment]
> I think you should give transform a try and see if it's feasible in your case. It has much more benefits for a potentially very fast implementation time. Read the JavaDoc of BitmapTransformation.transform.
thanks, i will
thanks for help, suppose issue closed.

**Comment by TWiStErRob** [comment]
Yep, it's resolved, we have quite a few alternatives.
Please let us know how it goes if you try the transformation.
