### ISSUE TITLE
problem is in the same url with diffrent content(image) 

### ISSUE THREAD

**Issue by ghasem6264** [bumptech/glide#1297]
hi dear !!

i use glide for showing profile in image view but every time i use that , its show first pic
my url is [http://machinejo.ir/images/profile_image/1/1.jpg] and when i change it , still show thats

im waiting .......

**Comment by TWiStErRob** [comment]
Most images don't change so the default behavior is to cache rigorously. See #624 and related issues for possible ways to handle changing profile pictures with static URLs.

**Comment by ghasem6264** [comment]
i read all of them !! but i have problem still

can glide refresh pic of one url ??

**Comment by TWiStErRob** [comment]
If you read all of them you must've read about `.signature()`. If you change the signature on a load it'll miss the cache and reload it from the original source.
This will leave the old image in cache as well, but the disk cache is size-bound so eventually it'll be evicted. If you care about your users calculate a reasonable cache size and use that. See wiki for more info.

**Comment by ghasem6264** [comment]
i use this , but dont reload image
```

Glide.with(fragment)
    .load(url)
    .signature(new StringSignature(UUID.randomUUID().toString()))
    .into(imgView);
```

**Comment by TWiStErRob** [comment]
Does it change if you open it in the browser on the phone? Do you use integration library? (OkHttp/Volley) Do your cache headers sent by the server correspond to the behaviour your trying to achieve?

**Comment by shanmukhkask** [comment]
Please don't give lot of lines of answers just give the code. I am irritating to see that lines you wrote.
