### ISSUE TITLE
Cannot specify okhttp client

### ISSUE THREAD

**Issue by paul321** [bumptech/glide#1298]
I need to load an image that is only loading if the user is logged, so i use a okhttp client that logs the users into the website, i setup Glide using glide module and override the registerComponents method and i try to pass the App global okhttp client like this

    public void registerComponents(Context context, Glide glide) {
        glide.register(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(MyApp.client));
    }

The problem is Glide isn't using this client is using a new instance and the image is not loaded because the internal client doesn't have the session cookie like the MyApp.client

**Comment by TWiStErRob** [comment]
How are you referencing the OkHttp integration library?
Read https://github.com/bumptech/glide/wiki/Integration-Libraries#overriding-default-behaviour

**Comment by paul321** [comment]
Yes i have it in gradle and it's working fine until i try to specify the
custom client

**Comment by TWiStErRob** [comment]
What is the exact gradle line?

**Comment by paul321** [comment]
compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@a

**Comment by TWiStErRob** [comment]
It's truncated but I assume the end is `@aar'`. That means that the Gradle Android plugin will extract the .aar file and merge the manifests. This means that even though you have your own `GlideModule` (I assume you registered it in your own manifest), the default OkHttp integration will be in effect as well. There's no defined order in which the modules are set up in Glide so the last one to register for `GlideUrl` wins. Remove the `@aar` from the dependency and try running your app.

**Comment by paul321** [comment]
If i remove @aar Gradle throws the following error
Error:Failed to resolve: glide-parent:library:unspecified

**Comment by TWiStErRob** [comment]
That's a bug in the latest release, see #941. If you don't want to use the snapshot, you can add this to your manifest (from [the integration lib](https://github.com/bumptech/glide/blob/3.0/integration/okhttp3/src/main/AndroidManifest.xml)) and keep the `aar` qualifier:
```xml
<meta-data
            tools:node="remove"
            android:name="com.bumptech.glide.integration.okhttp3.OkHttpGlideModule"
            android:value="GlideModule"
/>
```

**Comment by paul321** [comment]
It doesn't work same problem with http client, which snapshot shall i use?

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/issues/941#issuecomment-182663850

**Comment by paul321** [comment]
It's working.
Thank you
