### ISSUE TITLE
Thumbnail

### ISSUE THREAD

**Issue by dinesh1235** [bumptech/glide#1299]
How can I disable thumbnail in glide ??

**Comment by TWiStErRob** [comment]
Don't call `.thumbnail()` on the load.

**Comment by dinesh1235** [comment]
Not calling .thumbnail() still showing thumbnail



Here is my code where I am loading thumbnail()
package com.extra.adapter;

import android.app.Activity;
import android.content.Context;
import android.graphics.Bitmap;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.bumptech.glide.load.resource.drawable.GlideDrawable;
import com.bumptech.glide.request.RequestListener;
import com.bumptech.glide.Glide;
import com.bumptech.glide.load.engine.DiskCacheStrategy;

import com.bumptech.glide.request.target.Target;
import com.daimajia.androidanimations.library.Techniques;
import com.daimajia.androidanimations.library.YoYo;
import com.extra.item.ItemWallCat;
import com.extra.util.Constant;
import com.ksmobile.launcher.theme.neonlife.R;
import com.nostra13.universalimageloader.core.DisplayImageOptions;

import java.util.List;

public class Wallpaper_Category_Grid_Adapter extends ArrayAdapter<ItemWallCat> {

	//private Activity activity;
	private List<ItemWallCat> itemsLatest;
	private ItemWallCat objLatestBean;
	private int row;
	private int lastPosition = -1;
	private DisplayImageOptions options;
	private Context mContext;
	private LayoutInflater inflater ;
    private View view;
	public Wallpaper_Category_Grid_Adapter(Context mContext, int resource, List<ItemWallCat> arrayList) {
		super(mContext, resource, arrayList);
		this.mContext =mContext ;
		this.row = resource;
		this.itemsLatest = arrayList;
		inflater = LayoutInflater.from(mContext);

	}

	@Override
	public View getView(final int position, View convertView, ViewGroup parent) {


		view = convertView;
		ViewHolder holder=null;
		if (view == null) {
			view=inflater.inflate(row,parent,false);

			/*LayoutInflater inflater = (LayoutInflater) activity.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
			view = inflater.inflate(row, null);*/

			holder = new ViewHolder();
			holder.imgv_latetst=(ImageView)view.findViewById(R.id.category_grid);
			holder.text_wallcat=(TextView) view.findViewById(R.id.text_wallcatname);
			view.setTag(holder);
		} else {
			holder = (ViewHolder) view.getTag();
		}

		if ((itemsLatest == null) || ((position + 1) > itemsLatest.size()))
		return view;
		objLatestBean = itemsLatest.get(position);
       //holder.imgv_latetst.setScaleType(ImageView.ScaleType.CENTER_CROP);
		holder.imgv_latetst.setLayoutParams(new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 300));
		String url=Constant.SERVER_IMAGE_UPFOLDER_THUMB+objLatestBean.getCategoryImage().replace(" ", "%20");
		Glide.with(mContext)
				.load(url)
				.listener( requestListener )
				.placeholder(R.drawable.ic_stub)
				.centerCrop()
				.diskCacheStrategy( DiskCacheStrategy.ALL )
				.into(holder.imgv_latetst);
		holder.text_wallcat.setText(objLatestBean.getCategoryName().toString());

		return view;

	}

	private RequestListener<String, GlideDrawable> requestListener = new RequestListener<String, GlideDrawable>() {
		@Override
		public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
			// todo log exception

			// important to return false so the error placeholder can be placed
			return false;
		}

		@Override
		public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {

			YoYo.with(Techniques.Pulse)
					.duration(700)
					.playOn(view.findViewById(R.id.category_grid));
			return false;
		}
	};

	public class ViewHolder {

		public ImageView imgv_latetst;
		public TextView text_wallcat;
	}

}

**Comment by dinesh1235** [comment]
I am using Glide 3.7.0

**Comment by TWiStErRob** [comment]
Remove `.placeholder`? or don't use `SERVER_IMAGE_UPFOLDER_THUMB` to build the url?
I'm still not sure what your question is.
