### ISSUE TITLE
Image space occupied but not Image is shown

### ISSUE THREAD

**Issue by harshavardhands** [bumptech/glide#130]
In wiki (wiki/Transformations) given as "You can also apply either of the default transformations if you're loading Bitmaps or GIFs"
// For gifs:

``` java
Glide.with(yourFragment)
    .load(yourUrl)
    .asGif()
    .fitCenter()
    .into(yourView);
```

Space is occupied, but image is not shown...

My Code:

``` java
String url = "http://upload.wikimedia.org/wikipedia/commons/2/2b/Seven_segment_display-animated.gif";
imageView2 = (ImageView) findViewById(R.id.imageView2);
Glide.with(this).load(url).asGif().into(imageView2);
```

By using listener it worked out.

``` java
Glide.with(this).load(url).asGif().listener(new MyRequestListener()).into(imageView2);
```

**Comment by Tirthtrivedi** [comment]
In my samsung 4.4.2  with lowe memory configuration  i am also facing the same issue...my image view height width is match parent and  i am using  "  menuImage.setBackgroundDrawable(resource);" for setting glide resources....it loads the image but not showing in imageview.

why it happens in specific old devices.?

Any other workaround?

**Comment by TWiStErRob** [comment]
@Tirthtrivedi it sounds like you're using a custom target. Can you please create a new issue based on [this template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues)?

**Comment by Tirthtrivedi** [comment]
com.github.bumptech.glide:glide:3.6.1

Android versio 4.4.2
/////////////////////////////////////

 Glide.with(MenuImageFragment.this).load(imageUrl).listener(LocalDataProvider.getListener()).
                placeholder(R.drawable.ic_transparent_logo).
                error(R.mipmap.ic_launcher).signature(new StringSignature(imageUrl)).dontAnimate().
                diskCacheStrategy(DiskCacheStrategy.ALL)
                into(new SimpleTarget<GlideDrawable>() {
                    @Override
                    public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {

                      //  menuImage.setImageDrawable(resource);
                        menuImage.setScaleType(ImageView.ScaleType.FIT_XY);
                        menuImage.setBackgroundDrawable(resource);

                        dragParent.setViewToCapture(menuImage);

                    }


///////////////////////////////////
    <ImageView
        android:id="@+id/menuImage"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:adjustViewBounds="true"
        app:layout_direction="vertical"
        app:layout_draggable="true"
        tools:background="?colorPrimaryDark"
        tools:src="@mipmap/ic_launcher" />

ABOVE CODE IS WORKING FINE IN VERSION >5.0 AND HIGHER MEMORY RAM DEVICES.

**Comment by TWiStErRob** [comment]
@Tirthtrivedi new issue please because it seems unrelated to this one and https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues.

**Comment by Tirthtrivedi** [comment]
ok thanks
