### ISSUE TITLE
Gifs take a very long time to load

### ISSUE THREAD

**Issue by sbaar** [bumptech/glide#1302]
**Glide Version**:
Same behavior on 'com.github.bumptech.glide:glide:3.7.0' and 'com.github.bumptech.glide:glide:3.8.0-SNAPSHOT'

**Device/Android Version**: Nexus 6

**Issue details / Repro steps / Use case background**: 
[Sample repo](https://github.com/sbaar/LongGifLoad) Open app. Wait about a minute. Gif will finally load and play correctly. Exiting/force closing after this and re opening the gif will play instantly, probably because it's cached? Is the gif being re encoded? Maybe, because when I use the gif decoder alone in my own project the first playback of the gif is corrupted, but here it's fine.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
Glide.with(this).load("https://dl.dropboxusercontent.com/u/5742211/1001249.gif").into(iv);

**Comment by TWiStErRob** [comment]
> Is the gif being re encoded?

Yes

To fix: `.diskCacheStrategy(SOURCE)`, see https://www.google.com/search?q=glide+slow+gif and #281 for details.
