### ISSUE TITLE
Limit Number of Concurrent Executor Threads

### ISSUE THREAD

**Issue by r4m1n** [bumptech/glide#1304]
Does Any Config exist to limit number of concurrent executor threads?
I implement custom DataFetcher to connect our server and load images over socket.
The glide run multiple instance of my custom data fetcher and execute them concurrent. but i want to be only one thread and all request be in queue to process one by one. because we don't want to have multiple connection to our server per user.

Please help me.Thank you!

**Comment by TWiStErRob** [comment]
Create a [`GlideModule`](https://github.com/bumptech/glide/wiki/Configuration) and register an executor service. See `GlideBuilder` class for defaults. Also see #799 and #925.
Please note that decreasing thread count will greatly reduce your apps perceived performance by the user, please re-consider implementing the ability to handle multiple requests per user.

**Comment by sivabudh** [comment]
@TWiStErRob Thanks for the instructions. Would it be possible to have detailed instruction somewhere? We tried to do this but had no luck getting it to work.

**Comment by sssurvey** [comment]
Here is code sample for limiting the Glide source loading thread via GlideModule:

`kotlin
@GlideModule
class ReaderGlideModule : AppGlideModule() {
    override fun applyOptions(context: Context, builder: GlideBuilder) {
        builder
            .setLogLevel(Log.ERROR)
            .setSourceExecutor(                // source executor specify the thread it uses to load the image from remote
                GlideExecutor
                    .newSourceBuilder()
                    .setThreadCount(1)          // use the builder to set a desired thread amount
                    .build()
            )
    }
}
`
