### ISSUE TITLE
which api to use

### ISSUE THREAD

**Issue by prabinshrestha** [bumptech/glide#1306]
Prabin Shrestha | Thursday, June 30th | View on Future Studio Blog
Hello I am new to Glide, what should we use Glide.get(this).with(this).load(url) or Glide.with(this).load(url)
, I want to know what is the difference between them and which one is best preferable on which condition??

**Comment by TWiStErRob** [comment]
`Glide.with(this).load(url)`. any other combination shouldn't even compile.
Read this to learn what the `with` part does: http://stackoverflow.com/questions/31964737/glide-image-loading-with-application-context

`Glide.get` is used to mess with the global object, shouldn't be used in normal image displaying code.

**Comment by prabinshrestha** [comment]
Thanks for the reply and stackoverflow answer but i am only talking about the method here
* so that means we shouldnot use Glide.get(this or some context).with(this).load(url) instead we should use Glide.with(this).load(url) ??
* also if we do integration between volley and glide, when i call Glide.with(this).load(url) i don't see any method calling to my module but when i use Glide.get(this or some context).with(this).load(url), i see this method calling and setting up my module configuration like this 

A piece of code from Glide ...
    public static Glide get(Context context) {
        if (glide == null) {
            synchronized (Glide.class) {
                if (glide == null) {
                    Context applicationContext = context.getApplicationContext();
                    List<GlideModule> modules = new ManifestParser(applicationContext).parse();

                    GlideBuilder builder = new GlideBuilder(applicationContext);
                    for (GlideModule module : modules) {
                        module.applyOptions(applicationContext, builder);
                    }
                    glide = builder.createGlide();
                    for (GlideModule module : modules) {
                        module.registerComponents(applicationContext, glide);
                    }
                }
            }
        }

        return glide;
    }

Therefore what would be the best scenario to use it.

Thanks

**Comment by TWiStErRob** [comment]
If you use `get` like this, it's more verbose, there's no advantage of doing so. I think as a beginner you should forget about `get` exists. The registered `GlideModule`s are initialised lazily when needed. They will be only called once. If you tested this in one run, the first `Glide.get` had a side effect of initialising Glide and the second `Glide.with` (which internally calls `Glide.get`) doesn't need to initialise again.

**Comment by prabinshrestha** [comment]
*now i get the good answer and thanks for explanation.
*that means in conclusion we should use Glide.with(this).load(url) only no matter it is volley or glide integration caz it  internally calls Glide.get

Thanks in advance
GlideLover

**Comment by TWiStErRob** [comment]
Yep, just remove `get(activity)` and `skipMemoryCache`. The latter just slows Glide down. You're caching the file anyway, but forcing Glide to reload from disk all the time.
