### ISSUE TITLE
is there any way to retry image loading if glide fails,can somebody give example with circular progress and retry image request

### ISSUE THREAD

**Issue by prabinshrestha** [bumptech/glide#1307]
i put my Glide request on the adapter like this inside
```java
@Override
public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
    for(int p=0;p<photoLists.size;p++) {
        Glide.with(activity)
            .load(photoLists.get(p))
            .thumbnail(0.1f)
            .centerCrop()
            .diskCacheStrategy(DiskCacheStrategy.ALL).skipMemoryCache(true)
            .placeholder(R.color.photo_placeholder)
            .error(R.color.photo_placeholder_error)
            .listener(new RequestListener<String, GlideDrawable>() {
                @Override
                public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                    progressWheel.setVisibility(View.INVISIBLE);
                    return false;
                }
                @Override
                public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                    progressWheel.setVisibility(View.INVISIBLE);
                    return false;
                }
            })
            .into(imageview);
    }
}
```

* if you look at the code glide will download image with for loop as photoLists.get(p)
* so my question is: should we need to make separate static method where glide will be called or this is ok, does we get memory issue if we use like this.
* my last question is what to do when glide failed to load images or download images in a simple case like this or with the volley-glide integration. Can somebody give me best example

Thanks

**Comment by TWiStErRob** [comment]
If Glide fails, just leave the error placeholder. There's not much point in trying again: if the issue is permanent it will fail again; if it's intermittent, like bad network, it'll likely fail again, or load very slowly. You can give the user an option to force reload though, if it's important.

That for loop looks really weird especially since you're not even loading into `viewHolder.imageView`. This current code with the loop is equivalent to `Glide.with(activity).load(photoList.get(photlists.size-1).into(imageview)` (boilerplate omitted). If you start a load into an imageview, and then start a new one right away, the first one will be cancelled.

Take a look at [an example of an adapter usage](https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/github/_1189_recycler_preload/TestFragment.java) (ignore `stolenSize`, preloading and inflate your views from XML!)

**Comment by prabinshrestha** [comment]
oh sorry here is the good snippet
`@Override
public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
for(int p=0;p<photoLists.size;p++) {
Glide.with(this)
.load(photoLists.get(p))
.thumbnail(0.1f)
.centerCrop()
.diskCacheStrategy(DiskCacheStrategy.ALL)
.placeholder(R.color.photo_placeholder)
.error(R.color.photo_placeholder_error)
.listener(new RequestListener() {
@Override
public boolean onException(Exception e, String model, Target target, boolean isFirstResource) {
progressWheel.setVisibility(View.INVISIBLE);
return false;
}
@Override
public boolean onResourceReady(GlideDrawable resource, String model, Target target, boolean isFromMemoryCache, boolean isFirstResource) {
progressWheel.setVisibility(View.INVISIBLE);
return false;
}
})
.into(someviewholder.imageview);
}
}`

*oops, i am not loading on same imageview and i am using viewholder , now i think the code is understandable
*so now there is any memory issue??
*and also how can i give a user option to reload if it fails to load, can you give another simple example

**Comment by TWiStErRob** [comment]
> i am not loading on same imageview

The loop doesn't change the value of `someviewholder`, so you're loading into the same view. The cancellation from my above comment still applies. I don't think you need the for loop, you need `load(photoLIsts.get(position))`.

> now i think the code is understandable

Take a look at your comment, and think again ;)

> so now there is any memory issue??

If you use Glide properly within bind, and you always bind a new image to the holder's imageView the previous load's resources will be freed. If you have image only sometimes look at http://stackoverflow.com/a/32766674/253468.

> how can i give a user option to reload

Add a click listener on the image, or show a "Try again" button above the imageView. In the listener you can try to load the image again with the same code.

**Comment by prabinshrestha** [comment]
Oh sorry again,
MyModel{
private String name;
private List<String> images;
}

SomeAdapter(List<MyModel> models)

actually that loop is like this inside onBindVIewHolder method...
MyModel model=models.get(position)
for(int i=0;i<model.getImages().size;i++){
String imageUrl=model.getImages().get(i);
Glide.with(this).load(imageUrl).into(myviewholder.imageview);
}

Thanks for the reply,I appreciate very much

**Comment by TWiStErRob** [comment]
Ah, I see, so a single row contains multiple images. In that case you'll want to override `onViewRecycled` and `for(each model image) Glide.clear(corresponding imageView);`.
Otherwise you'll keep more than one image in memory.

**Comment by prabinshrestha** [comment]
Sorry again 
My code is like this
class MyModel{
String name;
List<String> images;
}

class MyAdapter{

MyAdapter(List<MyModel> models){

inside onBindViewHolder(postion){
MyModel model=models.get(position);
for(int i=0;i<model.getImages().size();i++){
String imageUrl=model.getImages().get(i);
Glide.with(this).into(myviewholder.imageview);

}

}

* ok now can you give me some tips and nice example

for(each model image) Glide.clear(corresponding imageView);.
i dont clearly understand it, please clarify

Thanks for your reply , i really really appreciate it

**Comment by TWiStErRob** [comment]
Do the same thing that you do in `onBindViewHolder`, but instead of `Glide.with.into(XXX)` call `Glide.clear(XXX)`.

**Comment by prabinshrestha** [comment]
Sorry again 
My code is like this
class MyModel{
String name;
List<String> images;
}

class MyAdapter{

MyAdapter(List<MyModel> models){

inside onBindViewHolder(postion){
MyModel model=models.get(position);
for(int i=0;i<model.getImages().size();i++){
String imageUrl=model.getImages().get(i);
Glide.with(this).into(myviewholder.imageview);

}

}

* ok now can you give me some tips and nice example

for(each model image) Glide.clear(corresponding imageView);.
i dont clearly understand it, please clarify

Thanks for your reply , i really really appreciate it

**Comment by danielgomezrico** [comment]
@TWiStErRob it makes sense to do a retry if you get a timeout, maybe not on some kind of errors, but there will be usefull some kind of `tryWhen` that RxJava provides just to point an example, more docs here: https://blog.danlew.net/2016/01/25/rxjavas-repeatwhen-and-retrywhen-explained/.

**Comment by Andrew0000** [comment]
The retry function would be still helpful.
Please note, there are places in the world where connection is intermittent.
Also there is always Not 100% availability for CDN services which provide images.
