### ISSUE TITLE
how to increase glide timeout

### ISSUE THREAD

**Issue by prabinshrestha** [bumptech/glide#1310]
what to do if it is integrated with volley

**Comment by TWiStErRob** [comment]
Glide doesn't have customizable timeouts, the networking library takes care of that.
Once you integrated with a library, read the [overriding defaults section](https://github.com/bumptech/glide/wiki/Integration-Libraries#overriding-default-behaviour) (which you already have) and then look in your selected integration library how to enable the features you want. So if you want "timeout in Glide using Volley", just search for "timeout in Volley".

**Comment by prabinshrestha** [comment]
public class CustomGlideModule extends VolleyGlideModule {

    public static String TAG = CustomGlideModule.class.getSimpleName();

    @Override
    public void applyOptions(final Context context, GlideBuilder builder) {
        LoggerUtils.log(TAG, "apply options");

        builder.setDiskCache(
                new
DiskLruCacheFactory(FileUtils.getDiskCacheDirPath(context,
FileUtils.ImageCacheDirectory), FileUtils.DISK_MAX_SIZE));

    }


    @Override
    public void registerComponents(Context context, Glide glide) {
        LoggerUtils.log(TAG, "register component");

RequestQueue queue = new RequestQueue( // params hardcoded from
Volley.newRequestQueue()

        new DiskBasedCache(FileUtils.getDiskCacheDir(context,
FileUtils.ImageCacheDirectory), FileUtils.DEFAULT_DISK_USAGE_BYTES),
        new BasicNetwork(new HurlStack())) {
    @Override
    public <T> Request<T> add(Request<T> request) {
        request.setRetryPolicy(new DefaultRetryPolicy(40000, 2, 2));
        return super.add(request);
    }
};
queue.start();
glide.register(GlideUrl.class, InputStream.class, new
VolleyUrlLoader.Factory(queue));

    }
}

In order to do to retry something in volley we have to do like this in
module look at 40000, its 40 sec for time out so i am bit confused what to
do... because this method force to include diskbasedcache too.
And you said if i do this i will be caching two: one is from glide and
another is from volley.

I am out of idea so please help me.


Thanks

**Comment by TWiStErRob** [comment]
How about using `NoCache` instead of `DiskBasedCache`?

Please make sure that your directories are distinct, putting multiple caches in the same directory can cause unforeseen problems. You can easily create subdirectories with `new File(cacheDir, "name of subfolder")`.

**Comment by TWiStErRob** [comment]
You should be using `new DiskLruCacheFactory(new CacheDirectoryGetter() {` from [the wiki](https://github.com/bumptech/glide/wiki/Configuration#location) to call `getDiskCacheDir` because it looks like it's doing I/O on UI.
