### ISSUE TITLE
Black areas of GIFs can be encoded as transparent

### ISSUE THREAD

**Issue by ravitapu** [bumptech/glide#1318]
Black areas of GIFs can be encoded as transparent.

![before](https://cloud.githubusercontent.com/assets/9557893/16687239/3d62b262-450f-11e6-8c19-b3afcffd4494.png)
![after](https://cloud.githubusercontent.com/assets/9557893/16687238/3d623288-450f-11e6-8c61-badeeef3ed06.png)

**Comment by TWiStErRob** [comment]
Ok, so let me re-ask all the questions in the issue template:
 * What version of Glide you're running?
 * What devices you managed to get the issue to come up on?
 * How do you use Glide? What is your Glide load line?
 * Do you have any configuration in a GlideModule?
 * Which one is your app's picture? (guessing second)

Can you please attach/link the original GIF file?

**Comment by ravitapu** [comment]
What version of Glide you're running?
Ans : glide:3.6.1

What devices you managed to get the issue to come up on?
Ans: All android devices checked (e.g. MOTOROLA G, SAMSUNG GALAXY etc.)

How do you use Glide? What is your Glide load line?
Ans: For Gif Loading in chat module, From local gif file and from url

Do you have any configuration in a GlideModule?
Ans : Not Changed in Library just using library feature.

Which one is your app's picture? (guessing second)
Ans: first is the png, second is a screenshot of the gif

What's up with "encoding"? (Glide is decoding images)
Ans: Glide internally doing encoding for gif creation , So we are using this feature for gif creation.

**Comment by TWiStErRob** [comment]
> glide:3.6.1

Give [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots) a shot, it has a lot of GIF related fixes.

> From local gif file and from url

They key would be the code here, because each method call after `with` means a lot of things may change in Glide behavior.

> png, gif, encoding

I'm still confused. Please elaborate more.

**Comment by ravitapu** [comment]
We are using glide to convert X number of pngs into a gif. Any black areas in the original pngs are appearing transparent in the final gif output. (hope this helps!)

**Comment by TWiStErRob** [comment]
Still no, sorry. I can see how you can load PNG files with Glide, but what I don't see is how you save GIFs. Please include some code.

**Comment by ravitapu** [comment]
we are using the animations gif encoder in the glide library by adding frames one by one with the duration time

**Comment by TWiStErRob** [comment]
Ah, so you're using `AnimatedGifEncoder` programmatically to build a GIF file from Bitmap objects.

I think you just need to set the transparent color, see `AnimatedGifEncoder.analyzePixels`:
```java
        // get closest match to transparent color if specified
        if (transparent != null) {
            transIndex = findClosest(transparent);
        } else if (hasTransparentPixels) {
            transIndex = findClosest(Color.TRANSPARENT);
        }
```
I've never used this API myself. You may need to preprocess your Bitmaps replacing `Color.TRANSPARENT` with some distinct color (usually `0xFF00FF00`).

**Comment by TWiStErRob** [comment]
Curious: Why do you re-encode a PNG as GIF? Both are good compressors and shouldn't be much difference between size.

**Comment by ravitapu** [comment]
we are re-encoding multiple pngs to create a gif as the final output. is there a better method?

**Comment by TWiStErRob** [comment]
Ah, yes, if it's animated then you need GIF (or webp).

Did you try upgrading to 3.8.0? Maybe your GIF is correct, but the decoding fails to distinguish black and transparent.

**Comment by ravitapu** [comment]
We have upgraded to version 3.8.0 but we are getting the same issue. How can we resolve the decoding issue where it is not able to distinguish between black and transparent?

**Comment by TWiStErRob** [comment]
Did you check that the encoded GIF is correct when viewed elsewhere?
The "distinguish" problem is just an idea, I cannot confirm, because I don't have the images.
If I were you I would first look around for a solution near https://github.com/bumptech/glide/issues/1318#issuecomment-231373674

**Comment by ravitapu** [comment]
we have tried that solution but are still getting the same problem. any idea what could be the issue?

**Comment by TWiStErRob** [comment]
My guess without any debugging is either `analyzePixels` or something in the decoder. You should debug those two to figure it out.
