### ISSUE TITLE
Additional info required with Reference to #1301

### ISSUE THREAD

**Issue by venkymsnv** [bumptech/glide#1319]
Hi Rob,

Your suggestions were very helpful for us and we appreciate your support.

Please let us know if we are doing this efficiently or can we enhance the loading of images and create a seamless experience.

We want to develop an application to display Backgrounds & wallpapers for Android mobiles. We wish to display images in 3 screens.

Screen 1:
We are displaying images in a gridview as mentioned below:

In the MainActivity class
` fullRequest = Glide.with(this)
                .from(Webphotos.class)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .crossFade(R.anim.fade_in, 150);

        thumbnailRequest = Glide.with(this)
                .from(Webphotos.class)
                .centerCrop()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .crossFade(R.anim.fade_in, 150)
        ;

        preloadRequest = true ? thumbnailRequest.clone().priority(Priority.HIGH) : fullRequest;`

Adapter class thumbnail loading:
` final Photos nature = photos.get(i);
           NewPhotoActivity.thumbnailRequest
                   .load(nature)
                   .dontAnimate()
                   .dontTransform()
                   .placeholder(null)
                   .thumbnail(1f)
                   .into(((NormalViewHolder)viewHolder).imgThumbnail);`
Preloading
`@Override
    public GenericRequestBuilder getPreloadRequestBuilder(Webphotos item) {
        return NewPhotoActivity.preloadRequest.load(item);
    }`
Screen 2:

Upon clicking an image in gridview I want to display the image in another activity (image size about 20-25% of screen height)
` Glide.with(this)
                .load(photo)
                .placeholder(null)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(fullscreenView);`

But it is taking more time to display the image.

Screen 3:
Upon clicking the fullscreen button in screen 2 we want to open a new activity with full screen image with out of bounds (height = screen size) and auto scroll the image from right to left and back until the user touches the screen.

Below are our current challenges:

1. Displaying the images is consuming more time, can we make it faster?
2. How to achieve full screen auto scroll image with out of bounds when clicking on fullscreen button.
3. How can we make the App experience seamless, are there any tips on how to fetch the images faster?
4. Is there any to use pre-loader efficiently with lower priority such that the immediate resources are not blocked.
5. Our images are typically about 4-5 MB, how can we download them faster to phone storage upon clicking save?

Please have a glance at our demo, if time permits. [link:](https://goo.gl/xnMt9V)

Thanks in advance for your help.

**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
We have everything in #1301.
The original question was so vague that these questions still fit the scope.
