### ISSUE TITLE
Animate even when image was loaded from memory cache

### ISSUE THREAD

**Issue by gonemad** [bumptech/glide#132]
I'm using glide to load an image into the background of one of my activities.  This background image changes very often and I use the crossfade() to animate between the image changes.  This works all fine and dandy when the image is not in the cache.. the crossfade works as expected.  However, it seems that if the image was already in the memory cache, the animation does not happen and the image just instantly loads.  

Is it currently possible to always animate regardless if its in the cache or not?  If not, can this be added?  The instant loading really messes with the fluidity of my app

**Comment by neoteknic** [comment]
Hello, I'm looking for the same thing, just to force the crossfade when image are already cached (Usefull to loop between few images). Any news about this ? Thank you !

**Comment by neoteknic** [comment]
The crossfade works perfect when It's loaded from the server, can you just make an async request from cache ? This is my code :

    private Runnable mRunnable = new Runnable() {
        @Override
        public void run() {
            if(timer_run) {
                timer_run=false;
                if(isVisible())
                    Glide.with(frag).load(getString(R.string.url_res) + getString(R.string.path_img_home_mz) + i_img + getString(R.string.file_ext_jpg)).placeholder(image.getDrawable()).listener(new RequestListener<String, GlideDrawable>() {
                        @Override
                        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                            timer_run = false;
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                            timer_run = true;
                            i_img++;
                            if (i_img > max_img) {
                                i_img = 1;
                            }
                            hTimer.postDelayed(mRunnable, RestoVal.HOMES_TRANSITION_TIMER_MS);
                            return false;
                        }
                    }).crossFade(RestoVal.IMAGE_FADE_DURATION).into(image);
            }
        }
    };

**Comment by headsvk** [comment]
Yeah I'd also like to know if someone has a solution for this as of now.

**Comment by neoteknic** [comment]
any news about this ?

**Comment by TWiStErRob** [comment]
@neoteknic for your use case:

> just to force the crossfade when image are already cached (Usefull to loop between few images).

take a look at https://github.com/bumptech/glide/issues/527#issuecomment-148840717.

**Comment by eicm** [comment]
@sjudd @TWiStErRob 
I load thumbnails() using .thumbnail(pathToThumbFile) along with my load line.
I'm facing this issue that the cross fade always happen no matter whether the image is cached or not. When I scroll to already cached images I see the cached image first then I see the thumbnail cross fading to the image again.

requestManager.load(mediaPath).clone().centerCrop().override(requestedSize[0], requestedSize[1])
.thumbnail(requestManager.load(thumbPath).clone().fitCenter().override(requestedSize[0], requestedSize[1]))
                .crossFade()
                .into(((AlbumGridViewHolder) viewHolder).imageView)

**Comment by PrathameshKesarkar** [comment]
@TWiStErRob   
The answer you have posted doesn't have an new DrawableCrossFadeFactory
Also I have a ScaleIn Animation that I want to show no matter it in cache or the Image is loaded for first time.
can you tell me any work around

**Comment by TWiStErRob** [comment]
@PrathameshKesarkar it does have a `new DrawableCrossFadeFactory` that's the core of the linked solution. Can you please open a **new issue** and describe what you want in more detail, also share what you already have.

**Comment by zeroarst** [comment]
Hi I just migrated from v3 to v4. And wondering if any solution for this now?

**Comment by zeroarst** [comment]
OK. I made a small library ViewTransitioner can be used along with Glide for transition purpose. This project is just for me to use in my the other project. But if someone wants to use transition for all resources all the time can check it out. 
https://github.com/zeroarst/ViewTransitioner

**Comment by aldochristiaan** [comment]
I hope this feature will come soon 👍

**Comment by luchfilip** [comment]
Any updates on this?

**Comment by sjudd** [comment]
This is possible in v4, though you have to implement your own ``TransitionFactory``: http://bumptech.github.io/glide/doc/transitions.html#custom-transitions.

**Comment by JavierSegoviaCordoba** [comment]
I am having a problem with this.

I go to Activity B from Activity A. It crossfade from a ColorDrawable to a Image from an URL. I go back to Activity A, then I go to Activity B, the crossfade is not working.

I tried to use  DrawableCrossFadeFactory but I am getting the same issue.

@sjudd is there a way to fix this problem?

I think should be great a method to force crossfade always.

**Comment by sjudd** [comment]
@JavierSegoviaCordoba see http://bumptech.github.io/glide/doc/transitions.html#custom-transitions. You can choose to cross fade always, even when the request was loaded from memory.
