### ISSUE TITLE
save selected image only 

### ISSUE THREAD

**Issue by sagar15795** [bumptech/glide#1320]
**Glide Version**: 3.6.0

**Integration libraries**: okhttp3:3.2.0

**Issue details**: Is it possible to save the only selected image on the phone? I am loading an image from the internet and want to download if I want to save .

**Comment by TWiStErRob** [comment]
`downloadOnly`? or use OkHttp to download a file from the internet.
Glide provides more than simple downloading, so `downloadOnly` is just a convenience.

**Comment by sagar15795** [comment]
Thank You for helping
