### ISSUE TITLE
Having Problem Loading Image as a Square

### ISSUE THREAD

**Issue by taimur97** [bumptech/glide#1325]
I am trying to load the image in my imageview which is resized like a square in xml. When I load image in it Glide automatically resizes the imageview according to the resolution of the image that's loaded.
I am using the following code
```java
Glide.with(getApplicationContext()).load(uri).asBitmap().fitCenter().into(floatImage);
```
I don't want to crop the image 

I want the image exactly fill the imageview without resizing it's original dimensions without croppping

**Comment by TWiStErRob** [comment]
Glide doesn't resize the ImageView at all, Android ImageView resizes itself according to contents and constraints. There shouldn't be any cropping either on the actual Bitmap object because you explicitly asked fit. If you have scaleType set in XML to crop, then that may be it.

Can you please share your XML and the dimensions of source, and expected sizes? Also please elaborate on what you mean by "resized like a square in xml"?

By the way, if you have a non-square image and you want to display it in a square view something will have to give: either crop; or fit, but have bands on either side or above/below. Look at https://github.com/bumptech/glide/issues/1099#issuecomment-203868327 for more.

**Comment by taimur97** [comment]
this is the imageview

 <ImageView
            android:layout_width="250dp"
            android:layout_height="300dp"
            android:layout_centerInParent="true"
            android:id="@+id/floatImage"
            android:scaleType="centerInside"
            android:adjustViewBounds="true"
            />

Look How it resizes the front imageview when I use images of different resolutions 

![screenshot_2016-07-11-01-13-08](https://cloud.githubusercontent.com/assets/2510169/16715846/44d2643c-4705-11e6-8877-9bba88dc9d1c.png)
![screenshot_2016-07-11-01-13-30](https://cloud.githubusercontent.com/assets/2510169/16715848/4f77bdc4-4705-11e6-8950-e016e50e8189.png)

**Comment by TWiStErRob** [comment]
Disregarding the blurry backgrounds, via simple measurements in MSPaint, the first image is `750x500 px`, the second image is `600x900 px`. Assuming a 3x (xxhdpi) screen you've declared `250x300 dp` = `750x900 px` in XML. Glide reads the size put in xml, or laid out size (in this case they're equal) and uses that as the target size, that is the decoding and transformations are aimed at reaching that size.

Looking at Glide JavaDocs for `.fitCenter() -> FitCenter.class`:
> Scales the image uniformly (maintaining the image's aspect ratio) so that one of the dimensions of the image will be equal to the given dimension and the other will be less than the given dimension.

We can clearly see that the input images are not distorted, but resized via `fitCenter()`. We can also see that one of the dimensions (width in first image, height in second image) is matched to the target size. This is the `Bitmap` in memory. Now let's see how it is rendered:

Looking at `ImageView.ScaleType.CENTER_INSIDE`:
> Scale the image uniformly (maintain the image's aspect ratio) so that both dimensions (width and height) of the image will be equal to or less than the corresponding dimension of the view (minus padding).

Again, no distortion; and the size of the Bitmap is equal to or less than the view dimensions. `750x500 px <= 750x900 px` and `600x900 px <= 750x900 px`.

How do you want it to look? Based on the above it looks like it's doing what you asked it to do.

**Comment by TWiStErRob** [comment]
Btw, do you know the name of the "blur in background" technique? (I've been keeping an eye out for it since it came up in https://github.com/bumptech/glide/issues/1099#issuecomment-203868327)

**Comment by taimur97** [comment]
sorry for my late reply 
If I use the centercrop as scaleType then it works

BTW here is a library to get the blur effect https://github.com/faradaj/BlurBehind
There are also many other libs on github just search blur and select java as language and you will find them. There's also one called quickblur

**Comment by TWiStErRob** [comment]
> If I use the centercrop as scaleType then it works

It worked before as well: if you want to display an image as cropped, then don't say "`.fitCenter()` and `="centerInside"` in code". Try removing any explicit transformation on the Glide line and putting `="centerCrop"` into XML, that should result in the behavior you achieved through `.fitCenter()` + `="centerCrop"`, but with better performance.
