### ISSUE TITLE
Volley 2.0 snapshot not compile

### ISSUE THREAD

**Issue by pedrowav** [bumptech/glide#1328]
Error:Module 'com.github.bumptech.glide:volley-integration:2.0.0-SNAPSHOT' depends on one or more Android Libraries but is a jar

**Comment by TWiStErRob** [comment]
I think this is a missing feature in Volley. They don't publish .jar any more, only .aar.
Does anyone know where their most up to date code and issue tracker is?

Workaround:
```gradle
compile('com.github.bumptech.glide:volley-integration:2.0.0-SNAPSHOT') {
    // exclude to prevent "depends on one or more Android Libraries but is a jar", but still depend on it below
    exclude group: 'com.android.volley', module: 'volley'
}
compile 'com.android.volley:volley:1.0.0'
```
Details: https://github.com/bumptech/glide/pull/1303#issuecomment-231558845

*If anyone knows how we could fix this so it "just works" with both `compile ...glide:volley-integration:2.0.0` and `compile ...glide:volley-integration:2.0.0@aar`, I'm all ears.*
