### ISSUE TITLE
Using Glide with DexGuard

### ISSUE THREAD

**Issue by barend** [bumptech/glide#1331]
The ProGuard configuration in the README is insufficient when using DexGuard, the commercial version of ProGuard. It requires one more directive for an app to work correctly:

``` proguard
-keepresourcexmlelements manifest/application/meta-data@value=GlideModule
```

I figure you might want to add this to the wiki and/or the primary documentation.

**Glide Version**: 3.7.0

**Comment by TWiStErRob** [comment]
Noted. Do you think it's sufficient to do this on `master` (v4), or you're reading the `3.0` branch's readme?

**Comment by barend** [comment]
It's not tied to any particular version of Glide. DexGuard obfuscates the contents of the `meta-data` element in the Android Manifest, and this causes the "Unknown Type Class" IllegalArg to be thrown. 

To be honest it's pretty niche. I suppose anywhere Google can find it is good enough.

**Comment by TWiStErRob** [comment]
I added it to the wiki: https://github.com/bumptech/glide/wiki/Configuration#keeping-a-glidemodule
and noted down to update the README as well.

> I suppose anywhere Google can find it is good enough.

That's already done... this issue ;)

**Comment by TWiStErRob** [comment]
Just curious: what is the rationale behind DexGuard removing metadata from the manifest? Is skimming off those 100 bytes from the compiled XML worth it?

**Comment by barend** [comment]
It's not about size, it's about obfuscation. Removing/scrambling as much information as possible to make the app harder (or at least more irritating) to reverse engineer. This includes assets and resources.

**Comment by ernestp** [comment]
I'm getting Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: proguard.ParseException: Unknown option '-**keepresourcexmlelements**' in line 317 of file '...../app/proguard-rules.pro'

Android Studio 2.2 Beta 3
Build #AI-145.3225885, built on August 26, 2016
JRE: 1.8.0_76-release-b03 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Gradle Plugin 2.1.3
Gradle 2.14.1

**Comment by TWiStErRob** [comment]
@ernestp It says "for DexGuard only", just remove the line if you use ProGuard.

**Comment by black-snow** [comment]
@TWiStErRob main page says *ProGuard* but ProGuard throws with `-keepresourcexmlelements` - should be mentioned imho

**Comment by TWiStErRob** [comment]
@black-snow  #1666 fixes this

**Comment by black-snow** [comment]
@TWiStErRob great!

**Comment by TWiStErRob** [comment]
I'm going to close this, if there's more changes needed feel free to make PR against master/README.md or comment to request Wiki updates.

**Comment by oatpano** [comment]
In my case, I found this error when create release apk.
- App module have lib module.
- Lib module have Glide and use Dexguard -keepresourcexmlelements manifest/application/meta-data@value=GlideModule.
- App module use Proguard.

How can i fixed it?

**Comment by w-k-s** [comment]
In case this helps: I faced a similar issue when using Glide v3. I was able to resolve it by adding the following line to `proguard-base-rules`:

`-keep class okhttp3.internal.publicsuffix.PublicSuffixDatabase`

**Comment by KishanViramgama** [comment]
Unknown option '-keepresourcexmlelements'

**Comment by TWiStErRob** [comment]
@KishanViramgama https://github.com/bumptech/glide/issues/1331#issuecomment-243657947?

**Comment by squm** [comment]
Why this issue is closed?

**Comment by TWiStErRob** [comment]
@squm why do you think it shouldn't be closed?
