### ISSUE TITLE
how can i update diskLruCache 

### ISSUE THREAD

**Issue by LinJZong** [bumptech/glide#1334]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Real issue is in #1335.

Tip: You can edit your comments in the top right corner, you don't need to open new issues. You could also have just ignored the above and commented below.
