### ISSUE TITLE
how can i update diskLruCache 

### ISSUE THREAD

**Issue by LinJZong** [bumptech/glide#1335]
I use Glide to load images .In my situation,I have two process,both of them can download images.but now i find that when i download an image in process A ,then I want to use the same url of image in process B,B will download from Intenet again.
So i read the source code, I find that the diskLruCache will only load once the first time i use it,so,if i start two process at the same time, they will have the same disk cache index.when i download image in process A, A's cache index changed,but B doesn't know,so B will still download from intenet.
May i change diskcache or reload diskcache in the runtime?

**Comment by TWiStErRob** [comment]
Are you looking to share a cache between distinct apps? I don't see what you mean about processes.

**Comment by LinJZong** [comment]
no ,i start a new process with "android:process=":processB"",they are in the same app. i want to draw a big Bitmap so i start a new one

**Comment by TWiStErRob** [comment]
Huh, that means that you have two Glide singletons unaware of each other. I don't think the disk cache can handle this as you've seen. You may look at DiskLruCache API if there's a way to force a reload from disk. If you implement a custom cache based on the built-in one that always reloads before operationsyou,  may get a behaviour you want.

I would think about another approach: download the file yourself and then load it with Glide from a File. Here, it looks like, that an image is not just an image, but your main data, so you need more control over it. Look around `downloadOnly` to get a File out of SOURCE cache in Process A and hand the File Uri over to B.

**Comment by LinJZong** [comment]
thanks a lot.
I solved this problem by create a new class implement DiskCache to manage disckcache

**Comment by LinJZong** [comment]
share a cache between distinct apps?
i think i can share cache between distinct app by using the same directory path。 but it may oc

**Comment by TWiStErRob** [comment]
> i think i can share cache between distinct app by using the same directory path。 but it may oc

It's the same problem as above. Both apps read the journal once and then work in memory. Concurrent accesses can mess everything up. If the two apps are not running at the same time, then it may work, but I don't think it's a good idea to do so. If two apps work on the same set of images, they should be the same app :)
