### ISSUE TITLE
Profiling Glide shows that when network speed is slow, the decoding time increases. 

### ISSUE THREAD

**Issue by samjain1994** [bumptech/glide#1336]
Hi, 
I am trying to see what time it takes for an images to load from network and then decode. I am using OkHttp. For network time I attach the time with each URL and measure the time using OkHttpInterceptor. For decoding I add my custom  decoder which extends Glide decoder and attach the timer with each URL in the decode function. Now what I see is that when I throttle the network speed to slow the network, then decoding time goes as much as 10 times higher. I am using RecyclerView to show my images and 4 images are shown in a single page. Can you please explain what maybe the reason ?

**Comment by TWiStErRob** [comment]
The default diskCacheStrategy is RESULT. It reads directly from the network stream.
If you add `.diskCacheStrategy(SOURCE)` (or `ALL`) to your load the network stream will first be streamed into a disk file and decoded from there.

**Comment by samjain1994** [comment]
I am using requestBuilder.diskCacheStrategy(DiskCacheStrategy.NONE).skipMemoryCache(true);

**Comment by TWiStErRob** [comment]
Ah, it's still true. The difference between NONE and RESULT is that RESULT compresses the Bitmap into cache once it's decoded and transformed from the source (network) stream.

**Comment by samjain1994** [comment]
I know that inputstream will be directly decoded and won't be cached. But I don't understand why decoding time should hike up when network speed is slow.

**Comment by samjain1994** [comment]
```
public class MySourceDecoder extends GifBitmapWrapperResourceDecoder {
    MyUrl myUrl;
    public MySourceDecoder(ResourceDecoder<ImageVideoWrapper, Bitmap> bitmapDecoder,
                              ResourceDecoder<InputStream, GifDrawable> gifDecoder, BitmapPool bitmapPool, MyUrl myUrl) {
        super(bitmapDecoder, gifDecoder, bitmapPool);
        this.myUrl = myUrl;
    }
    @Override
    public Resource<GifBitmapWrapper> decode(ImageVideoWrapper source, int width, int height) throws IOException {
        myUrl.start_decode_time = System.currentTimeMillis();
        Resource<GifBitmapWrapper> gifBitmapWrapperResource =  super.decode(source, width, height);
        myUrl.end_decode_time = System.currentTimeMillis();
        return gifBitmapWrapperResource;
    }

    @Override
    public String getId() {
        return " ";
    }
}

```

**Comment by TWiStErRob** [comment]
Reading the network stream directly means that decoding the pixels from the compressed version is not possible until they arrive. Take a simple image format (RAW) for example: you're decoding a 10x10 image which is 100*3 bytes (RGB) long. You already received 10*3 bytes and you know that those build up the first row of the resulting Bitmap. You receive 2 more bytes (R, G), but then the network waits 2 seconds before sending you the next 1 byte (B). You have to wait to decode the 1st color in the second row, because you only have R and G, and waiting for B.

**Comment by samjain1994** [comment]
Okay got it, thank you. I thought decoding starts only when the image is completely loaded from network.

**Comment by TWiStErRob** [comment]
That's only true when you're using SOURCE or ALL.

**Comment by TWiStErRob** [comment]
Tip: don't override `getId`, because you didn't change what the decoder does (unless it was on purpose, and you know what you're doing). It may cause you headaches/false results if you start playing around with caches.
