### ISSUE TITLE
Glide calls

### ISSUE THREAD

**Issue by maddenbrain** [bumptech/glide#1342]
Hi! I'm trying to implement glide, but i have an issue. Here is gradle config:
```gradle
repositories {
    mavenCentral()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:support-v4:24.0.0'
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.android.support:design:24.0.0'
    compile 'com.android.support:recyclerview-v7:24.0.0'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.github.bumptech.glide:glide:3.7.0'
}
```

But in code, i can't call Glide.load() or some other methods, because glide has no it! 

UPD: Sorry, stupid question. Command order matters.

**Comment by TWiStErRob** [comment]
```java
Glide.with(this).load("url").into(imageView);
```
Yes, the order matters. The API is a fluid builder, after each call you may get a different object back which allows you to continue down the path you want.
