### ISSUE TITLE
Whether can display webP animations？

### ISSUE THREAD

**Issue by Yongzili** [bumptech/glide#1343]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
No animations yet, but still images are supported whenever the framework supports it: https://developer.android.com/guide/appendix/media-formats.html#core

Follow #571 to get notified on updates. (Subscribe button in right column.)

**Comment by renyanxu2000** [comment]
We all hope to have this feature！

**Comment by Srain-z** [comment]
i hope to have this feature too . like Fresco.

**Comment by HeSuxiang** [comment]
i hope to have this feature too . like Fresco. can display webP animations in API 4.0.
