### ISSUE TITLE
Is it possible to call Glide from separate thread?

### ISSUE THREAD

**Issue by BanksA761** [bumptech/glide#1344]
I have separate thread and need to call Glide only for downloading and caching not displaying images on UI, is it possible to call Glide from not UI main thread?

**Comment by TWiStErRob** [comment]
```java
Glide.with(context).load(model).downloadOnly();
```
would work in the background.

You could also get a Bitmap if you end with `into(w, h).get()`.

See the documentation for the methods mentioned.
