### ISSUE TITLE
Is it possible to call Glide from separate thread?

### ISSUE THREAD

**Issue by BanksA761** [bumptech/glide#1349]
I have IntentService and need to call Glide from another Service , where I use Glide only for downloading/caching ,,Is it possible to call Glide from not UI Thread?

**Comment by TWiStErRob** [comment]
Yes, it is possible, read:
https://github.com/bumptech/glide/wiki/Loading-and-Caching-on-Background-Threads
https://github.com/bumptech/glide/issues/1344
https://github.com/bumptech/glide/issues/1348

(Please stop asking the same question.)
