### ISSUE TITLE
DrawableRequestBuilder - show gif as bitmap, without using another builder

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#1350]
Is it possible to somehow convert a `DrawableRequestBuilder` to show a gif as bitmap? But still return a drawable! Without loading gif frames and only stop playing in a listener?

I want to avoid to adjust the code to handle bitmap requests and drawable requests independently everywhere and to distinguish between `BitmapTargets` and `DrawableTargets`.

using `asBitmap` requires to use this call after the `load` call and then I don't have a `DrawableRequestBuilder` anymore... I want to show gifs without animation as drawables instead of bitmaps...

**Comment by TWiStErRob** [comment]
How about?
```java
.asBitmap()
.transcode(new GlideBitmapDrawableTranscoder(context), GlideBitmapDrawable.class)
```

**Comment by MFlisar** [comment]
I can't call `asBitmap` on the `DrawableRequestBuilder` but only on the `DrawableTypeRequest`... I have a lot of base classes that return a `DrawableRequestBuilder`... I would have to distinguish in my base classes so i'm looking for a solution on the `DrawableRequestBuilder` level... 

I only see following solution:
* change the base classes to return a `DrawableRequestBuilder` or a `BitmapRequestBuilder` as a `GenericRequestBuilder` and then I can use that builder with `transcode` to always get a `GlideDrawable`...

**Comment by MFlisar** [comment]
I can't call `asBitmap` on the `DrawableRequestBuilder` but only on the `DrawableTypeRequest`... I have a lot of base classes that return a `DrawableRequestBuilder`... I would have to distinguish in my base classes so i'm looking for a solution on the `DrawableRequestBuilder` level... I already use `override` and `signature` in this base classes on the builder... I can adjust my base classes of course and tried that, but then your suggestion does not return a `DrawableRequestBuilder` anymore...

I only see following solution:
* change the base classes to return a `DrawableRequestBuilder` or a `BitmapRequestBuilder` as a `GenericRequestBuilder` and then I can use that builder and cast it again and then decide to use `BitmapTarget` or a `DrawableTarget`

Here's an example of a base class:

    @Override
    public DrawableRequestBuilder getRequestBase(Object linkedObject, boolean fullSize)
    {
        RequestManager manager = ImageHelper.getGlide(linkedObject);

        DrawableRequestBuilder request = null;

        // 1) Entscheiden was geladen wird
        // 1.1) FullSize => Datei wird direkt geladen
        if (fullSize)
        {
            request = manager.load(getUri());
        }
        else
        // 1.2) kleines Bild => Einstellungen prüfen
        {
            DrawableTypeRequest drawableTypeRequest = null;
            SmallImageLoadingType loadingType = SmallImageLoadingType.getById(MainApp.getPrefs().smallImageLoadingType());
            switch (loadingType)
            {
                case ExifBeforeMediaStore:
                    if (getMediaType() != MediaType.Video)
                    {
                        drawableTypeRequest = manager.using(new StreamModelLoader<IMedia>()
                        {
                            @Override
                            public DataFetcher<InputStream> getResourceFetcher(IMedia media, int width, int height)
                            {
                                return new GlideLocalPreviewFetcher(media);
                            }
                        }).load(this);
                        break;
                    }
                    else
                    {
                        // fall through to media store only!
                    }
                case MediaStoreOnly:
                    drawableTypeRequest = manager.loadFromMediaStore(getUri());
                    break;
                case CustomResolution:
                    drawableTypeRequest = manager.load(getUri());
                    break;
                default:
                    throw new TypeNotHandledException();
            }

            // does not work!!! return type does not fit
            // if (!MainApp.getPrefs().animateGifsInLists())
            // {
            //    drawableTypeRequest = drawableTypeRequest
            //            .asBitmap()
            //            .transcode(new GlideBitmapDrawableTranscoder(ImageHelper.getGlideContext(linkedObject)), GlideBitmapDrawable.class);
            // }


            switch (loadingType)
            {
                case ExifBeforeMediaStore:
                case MediaStoreOnly:
                    request = drawableTypeRequest.override(ImageHelper.MEDIA_STORE_SQUARE, ImageHelper.MEDIA_STORE_SQUARE);
                    break;
                case CustomResolution:
                    int size = MainApp.getPrefs().customSmallImageLoadingSize();
                    request = drawableTypeRequest.override(size, size);
                    break;
                default:
                    throw new TypeNotHandledException();
            }
        }

        if (getSignature() != null)
            request.signature(getSignature());

        return request;
    }

**Comment by TWiStErRob** [comment]
Copy this code and then in AS/IDEA right click on the file with the original method and "Compare with Clipboard".
```java
    @Override
    public GenericRequestBuilder<?, ?, ?, GlideDrawable> getRequestBase(Object linkedObject, boolean fullSize)
    {
        RequestManager manager = ImageHelper.getGlide(linkedObject);

        GenericRequestBuilder<?, ?, ?, GlideDrawable> request;

        // 1) Entscheiden was geladen wird
        // 1.1) FullSize => Datei wird direkt geladen
        if (fullSize)
        {
            request = manager.load(getUri());
        }
        else
        // 1.2) kleines Bild => Einstellungen prüfen
        {
            DrawableTypeRequest<?> drawableTypeRequest;
            SmallImageLoadingType loadingType = SmallImageLoadingType.getById(MainApp.getPrefs().smallImageLoadingType());
            switch (loadingType)
            {
                case ExifBeforeMediaStore:
                    if (getMediaType() != MediaType.Video)
                    {
                        drawableTypeRequest = manager.using(new StreamModelLoader<IMedia>()
                        {
                            @Override
                            public DataFetcher<InputStream> getResourceFetcher(IMedia media, int width, int height)
                            {
                                return new GlideLocalPreviewFetcher(media);
                            }
                        }).load(this);
                        break;
                    }
                    else
                    {
                        // fall through to media store only!
                    }
                case MediaStoreOnly:
                    drawableTypeRequest = manager.loadFromMediaStore(getUri());
                    break;
                case CustomResolution:
                    drawableTypeRequest = manager.load(getUri());
                    break;
                default:
                    throw new TypeNotHandledException();
            }

            if (!MainApp.getPrefs().animateGifsInLists())
            {
                request = drawableTypeRequest
                        .asBitmap()
                        .transcode(new BitmapToGlideDrawableTranscoder(ImageHelper.getGlideContext(linkedObject)), GlideDrawable.class);
            }
            else
            {
                request = drawableTypeRequest;
            }

            int size;
            switch (loadingType)
            {
                case ExifBeforeMediaStore:
                case MediaStoreOnly:
                    size = ImageHelper.MEDIA_STORE_SQUARE;
                    break;
                case CustomResolution:
                    size = MainApp.getPrefs().customSmallImageLoadingSize();
                    break;
                default:
                    throw new TypeNotHandledException();
            }
            request.override(size, size);
        }

        if (getSignature() != null)
            request.signature(getSignature());

        return request;
    }
```
You can still `crossFade`: `.animate(new DrawableCrossFadeFactory<GlideDrawable>())`. The only thing you lose is the transformations, because you don't know the `ResourceType` (3rd in `GenericRB`), which may be a problem. You can work around it in 3 ways:
 * Use `into(imageView)`, because it knows how to call the transformation based on `scaleType`.
 * Cast back with `instanceof`
 * Create an accessor to call `GRB.applyFitCenter()`.

**Comment by MFlisar** [comment]
That's more or less the solution i though of... Thanks for the help
