### ISSUE TITLE
When first load Image in RecycleAdapter ,it seems slowly

### ISSUE THREAD

**Issue by Aeiric** [bumptech/glide#1351]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Glide is not a magic teleportation device, your network is probably downloading the image.

Please fill in the above template (edit comment with pencil in upper right corner) and then reopen this issue, if you want help.
