### ISSUE TITLE
Fit Width Wrap Height Using Glide

### ISSUE THREAD

**Issue by stripathi669** [bumptech/glide#1353]
My desired behaviour is for the image to fill the screen width, and wrap around the height, keeping the aspect ratio.
I tried following:
1. In XML:
   
   ```
   <ImageView
       android:layout_width="fill_parent"
       android:layout_height="wrap_content"
       android:id="@+id/imgView"
       android:maxHeight="400dp"
       android:visibility="visible"
       android:adjustViewBounds="true"
       />
   ```
2.  In Java:
   
   ```
   Glide.with(mcontext)
                           .load(image_url).placeholder(R.color.light_grey)
                           .fitCenter()
                           .diskCacheStrategy(DiskCacheStrategy.RESULT)
                           .bitmapTransform(new RoundedCornersTransformation(mcontext,4,0))
                           .crossFade()
                           .into(imgView);
   ```

Result: 
![screenshot_2016-07-18-17-14-03](https://cloud.githubusercontent.com/assets/7647281/16913992/58b24e74-4d0c-11e6-9267-3eaa95647cee.png)

What am I doing wrong?

Glide 3.7.1 with Volley, tested in 5.0.1 L

**Comment by TWiStErRob** [comment]
Is it possible that your source image is smaller than the view (in pixels)?
Also `.fitCenter()` has no effect on your Glide load because `bitmapTransform` overwrites it, see https://github.com/wasabeef/glide-transformations/issues/32#issuecomment-193889035

**Comment by stripathi669** [comment]
Ah! My bad, Fit center wasn't being applied.

Any way to scale it to fit width irrespective of resolution?

Thanks for help.

**Comment by TWiStErRob** [comment]
There's no point in upscaling the Bitmap if the source was low-res, but I think you can make sure that the ImageView renders the Bitmapt full-width if you size it properly. Try different `scaleType`s and make sure `maxHeight` is not too restrictive.
