### ISSUE TITLE
Error drawables

### ISSUE THREAD

**Issue by raviteja83** [bumptech/glide#1354]
**Glide Version**: 3.7.0

**Integration libraries**:integration not added but using okhttp 

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).load(url).error(res).placeholder(res).into(imageview);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

Can you support url's in error instead of drawable or local resources? The error url is definitely known to have a valid image.Is there a way to use url instead of drawable or resource?

**Comment by TWiStErRob** [comment]
You can do that through
 * a listener: start another load and `return true`,
 * a thumbnail:

    ```java
    Glide.with(context).load(url).thumbnail(Glide.with(context).load(fallbackUrl)).into(imageview);
    ```
    here the fallback will be very likely loaded first (acts a placeholder) from cache and will remain visible if there's an error (unless you call `.error()` on the load).
 * a [custom fetcher](https://github.com/bumptech/glide/issues/606#issuecomment-145015261)
