### ISSUE TITLE
permission for cache??

### ISSUE THREAD

**Issue by prabinshrestha** [bumptech/glide#1356]
suppose we want to have our custom directory for cache, according to the new api standard for marshmallow i think there we might need ask user for permission for storage.

* So do we need to ask permission in order to run on marshmallow device when we setup on Glide Module or leave as it is ??

**Comment by TWiStErRob** [comment]
We talked about permissions in #1333.

I think as long as you're not polluting the user's sdcard(s), you don't need a permission:
> This enables apps to manage their package-specific directories on external storage without requiring they hold the broad WRITE_EXTERNAL_STORAGE permission. - [article](http://www.androidpolice.com/2014/02/17/external-blues-google-has-brought-big-changes-to-sd-cards-in-kitkat-and-even-samsung-may-be-implementing-them/)

Not polluting means that you use the context object to retrieve the location of the cache dir and not Environment. The Android/data/package folders are writable without and there's no reason to put your files (especially cache files) outside that.
