### ISSUE TITLE
Upgrade to support-v23+ and use `Fragment.onAttach(Context)`

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#1358]
Based on https://github.com/bumptech/glide/commit/8eaa0217ad955db159b4fdca05287ad2ccd85aca#commitcomment-18294851:

> This method is deprecated. Any reason why you're not using the new method? 
> From source code:
> 
> ``` java
> /**
>  * Called when a fragment is first attached to its context.
>  * {@link #onCreate(Bundle)} will be called after this.
>  */
> public void onAttach(Context context) {
>     mCalled = true;
>     final Activity hostActivity = mHost == null ? null : mHost.getActivity();
>     if (hostActivity != null) {
>         mCalled = false;
>         onAttach(hostActivity);
>     }
> }
> /**
>  * @deprecated Use {@link #onAttach(Context)} instead.
>  */
> @Deprecated
> public void onAttach(Activity activity) {
>     mCalled = true;
> }
> ```

**Comment by TWiStErRob** [comment]
@frel the problem here is that `Fragment.onAttach(Context)` is a new method introduced in API 23. If we simply override the new method Glide won't work on older versions of Android, so we'll have to either override both methods, or just ignore the deprecation.

Though it's possible to use the new method in `SupportRequestManagerFragment`, but even there we have to wait to remove the current overriding method in case someone is still using `< support-v23`.

**Comment by frel** [comment]
Ok, thank you for clarifying.

**Comment by TWiStErRob** [comment]
@sjudd do you think there's a way to use only that method?

@frel We're also still using 22.2 of the support lib, but the users can depend on newer versions, Gradle will figure out which one to use. Do you have any argument against what I said above?

**Comment by frel** [comment]
Not really. The reason I noticed it is because I was getting "Activity already destroyed" when resuming a fragment. I've upgraded to 3.8-SNAPSHOT and it works there. It seems onAttach is called after the activity has been destroyed.

**Comment by sjudd** [comment]
This is fixed in v4 for support Fragments, for backwards compatibility we will continue to use the old method until that's the minimum API level or it's removed.
