### ISSUE TITLE
ImageView disappears for only a moment

### ISSUE THREAD

**Issue by egugue** [bumptech/glide#1361]
**Glide Version**:
3.7.0

**Integration libraries**:
I don't integrate any libraries.

**Device/Android Version**:
Any devices

**Issue details / Repro steps / Use case background**: 
I use Glide in list-item of RecyclerView.

But `Glide.with().isPaused` method returns `true` just when `into` method be invoked.
And an `ImageView` used in the list-item sets relative height and width. (Relative means `match_parent` value.)

As a result,
The `ImageView` disappears just like setting `GONE` visibility for only a moment just when `into` be invoked.
And after the moment, the one appears just like setting `VISIBLE` visibility.

So I checked the code of `Glide` to explore the cause.
And I noticed that `Glide` doesn't set placeholder to `ImageView` until [`RequestTracker` is not paused](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/manager/RequestTracker.java#L42).
I guess it causes the disappearing event above.

So What I would like to know are:
__Why the `Glide` is paused?__
and
__Why `Glide` not set placeholder to `ImageView` immediately?__ (I guess it is better that Glide sets placeholder immediately.)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
target = Glide.with(getContext())
        .load(image.getUrl())
        .animate(R.anim.thumbnail_fade_in)
        .placeholder(thumbnailPlaceHolder)
        .error(thumbnailPlaceHolder)
        .into(thumbnail);

Log.d("Glide", "isResourceSet = " + target.getRequest().isResourceSet());
Log.d("Glide", "isFailed = " + target.getRequest().isFailed());
Log.d("Glide", "isPaused = " + target.getRequest().isPaused());
Log.d("Glide", "isRunning = " + target.getRequest().isRunning());
Log.d("Glide", "isCancelled = " + target.getRequest().isCancelled());
Log.d("Glide", "isComplete = " + target.getRequest().isComplete());
Log.d("Glide", "Glide is paused = " + Glide.with(getContext()).isPaused());
```

**Layout XML**:
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@android:color/black">

    <ImageView
        android:id="@+id/thumbnail"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerInParent="true"
        android:adjustViewBounds="true"
        android:focusableInTouchMode="false"/>

</RelativeLayout>
```

**Stack trace / LogCat**:
Here is LogCat sent from the code above.
```
...D/Glide: isResourceSet = false
...D/Glide: isFailed = false
...D/Glide: isPaused = false
...D/Glide: isRunning = false
...D/Glide: isCancelled = false
...D/Glide: isComplete = false
...D/Glide: Glide is paused = true
```

**Screenshot**:
I'm afraid that I cannot provide something like a screenshot because of private project.
But If you cannot understand what I write above because of my poor english,
I will be willing to create a sample project and to provide the one.

**Comment by TWiStErRob** [comment]
Did you ever call `Glide.get(context).pauseRequests` on this activity? (e.g. Flinging listener or similar).
If not, try putting a breakpoint where `isPaused = true` is and see the stack frames to figure out why it gets called.

**Comment by TWiStErRob** [comment]
Btw, the whole point of match parent is that it doesn't require content to be laid out. It'll be visible and empty even with null drawable.

**Comment by TWiStErRob** [comment]
You might be also interested in #952, which is similar, but possibly unrelated.

**Comment by egugue** [comment]
Thank you for your reply and sharing relavant infomation!

> Did you ever call Glide.get(context).pauseRequests on this activity?

I have never call `Glide.get(context).pauseRequests`.

So I've checked that why `Glide` is paused by the following steps.

**1. I want to know the reason why `RequestTracker#isPaused` is true.**
So I put breakpoints anywheret the `isPaused` value is assigned and ran debugger.
The image below is the result.
According to it, it seems that `RequestTracker.pauseRequest()` is invoked.

![2016-07-22 19 58 05](https://cloud.githubusercontent.com/assets/9448567/17057004/5cf0b572-5052-11e6-88e5-9ca6e5d46418.png)

**2. I want to know the reason why `RequestTracker.pauseRequest()` is invoked.**
So I put breakpoints anywhere there is a suspicion that `Glide` changes pause.  
The image below is the result.  

According to it, it seems that `ActivityFragmentLifecycle.addListener()` is invoked,
But before the method is invoked, `ActivityFragmentLifecycle.onStart()`, `onStop()`, or `onDestroy()` methods are never invoked.  
In this condition, `ActivityFragmentLifecycle#isStarted` and `#isDestroyed` is false.  

![image](https://cloud.githubusercontent.com/assets/9448567/17057026/761ab96c-5052-11e6-95a6-42a535dd9fd8.png)


**Conclusion**
According to it above,
`RequestTracker.pauseRequest()` is invoked because of `ActivityFragmentLifecycle`'s condition.
That's why `Glide.with().isPaused` returns `true`.

So in the condition,
How does I work around the issue?
I have verified it solves the issue that `Glide.with().onStart()` is invoked when `Activity.onStart()` is invoked.
So is this action no problem?

**Comment by TWiStErRob** [comment]
Where is your `Glide.with` located? Maybe the activity is really in that limbo state. I can see that it's in a lambda from the stack, what triggers that lambda callback?

**Comment by egugue** [comment]
First of all, I appreciate you reading my long sentence.

> I can see that it's in a lambda from the stack, what triggers that lambda callback?

I use lambda expression to implementing a callback, which is invoked when `ImageView` completes `onMeasure()`. (Look at the code below, plase)
Using `measuredWidth`, `measuredHeight`, real image width and height, I calculate suitable size for `ImageView`.
That is the lambda callback.

Do the action above makes the issue?

I know the action is not better (or rather bad).
And I would like to fix it, but cannot fix the action immediately.

```java
public class ThumbnailView extends ImageView {
    public interface Callback {
        void onMeasureCompleted();
    }
    public Callback callback;

    @Override protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        callback.onMeasureCompleted();
    }
```
```java
public class JumbotronView extends RelativeLayout {
    public void bind(List<Image> imageList) {
        thumbnail.callback = () -> {
            Image image = null; //In fact, calculating the suitable image size.
            int thumbnailPlaceHolder = image.isWide() ? R.drawable.thumbnail_bg_wide : R.drawable.thumbnail_bg;

            target = Glide.with(getContext())
                    .load(image.getUrl())
                    .animate(R.anim.thumbnail_fade_in)
                    .placeholder(thumbnailPlaceHolder)
                    .error(thumbnailPlaceHolder)
                    .into(thumbnail);
            
        }

    }
```

**Comment by TWiStErRob** [comment]
I did a quick test and my `onMeasure` is called after everything is `onResume`d (activity, fragments).
I'm not sure if that call is safe there. The view hierarchy is in the middle of the layout pass and you try to attach a new fragment and possibly request a layout for the ImageView in the middle of it. See how `ImageView.setDrawable` calls `requestLayout()` which has this JavaDoc:
> This should not be called while the view hierarchy is currently in a layout (`isInLayout()`}.

I have a hacky solution in one of my apps which emits this line, which like is because of the above restriction, maybe you have this too:
> W/View: requestLayout() improperly called by android.widget.FrameLayout{...} during layout: running second layout pass

Here are some possible workarounds (each is a different idea/hack):
 * I would try to externalize these calls to normal lifecycle methods.
 * If you want to stick to this you can try calling `Glide.with(getContext())` in `JumbotronView`'s constructor and store the result in a field. This may affect how the `paused` flag is set.
 * You can also try moving `onMeasureCompleted` call after to `super.layout()`
 * Calling `post(() -> callback())` to delay execution may also help
 * Ignore all this and just call `thumbnail.setImageResource` yourself, which will be displayed until Glide is resumed and then replaced by the same drawable.

I'm also beginning to think that calling `onStop` is a valid thing in Glide, because the fragment is possibly not yet attached. So the `FragmentManager` cannot do any real work. It likely collects all `.into` calls and queues them up in a pending queue waiting for an `onStart` callback from the fragment lifecycle.

**Comment by egugue** [comment]
I appreciate you giving me many useful advices.

Based on the given advices, I tried to investigate the issue again.
And I noticed that `SupportRequestManagerFragment` to be attached is also postponed until a `ImageView` is visible.

Then, I tried to move `Glide.with()` where
* `Activity` `Fragment`'s Lifecycle methods
* `RecyclerView.Adapter`'s constructor and override methods such as `getItemViewType`
* CustomView's constructor.

I also noticed that it works well where `Activity` and `Fragment`'s `onCreate()`, `onStart()` and `onResume()`  and `RecyclerView.Adapter`'s constructor,
but it doesn't where `RecyclerView.Adapter`'s override methods and CustomView's constructor.

Eventually, I have no idea that what makes the issue while I keep on investigating.
And to work around the issue temporarily,
I try to choice the action calling `Glide.with` in `Activity.onCreate()` and store the result in a field.
(Because the given workarounds don't work well except for last one.)

Anyway I really appreciate you.

**Comment by TWiStErRob** [comment]
The adapter's methods are also called during a layout pass, that may be the reason. Most of those calls are required so the RecyclerView knows its size or creates its children.

I'll close this for now, but if you find any bugs that need to be fixed feel free to reopen or create a new issue.
