### ISSUE TITLE
How can I get the local Uri for the online image url 

### ISSUE THREAD

**Issue by AssassinWayne** [bumptech/glide#1365]
**Glide Version**: 3.7.0

**Integration libraries**: OkHttp3-1.4.0

**Device/Android Version**: Android 4.0+

**Issue details / Repro steps / Use case background**: 
Hey, hello everyone, I'm new in Glide. And there is some problem which I cannot fix it, I want to get the local image Uri to compose a Tweet through the "Twitter Kit App Card Composer", it requests the specific local media file to finish the composition. 
[https://docs.fabric.io/android/twitter/compose-tweets.html#twitter-kit-app-card-composer](url)

![39b85969-d80c-4453-9f7e-5c211a570e64](https://cloud.githubusercontent.com/assets/16981284/17105468/f175b51c-52b9-11e6-8af8-15d9e8b4211d.png)

So is there any way to get the local file of the online url which I can load successfully?

Thanks for your help!

**Comment by TWiStErRob** [comment]
#459 should help.

**Comment by AssassinWayne** [comment]
@TWiStErRob Do appreciate your help.

**Comment by TWiStErRob** [comment]
Please let me know if that worked.

**Comment by AssassinWayne** [comment]
@TWiStErRob Sorry for delay reply. 
The method downloadOnly is OK, besides I test the code as below to add a watermark with the bitmap, and it works well.
`Glide.with(activity.getApplicationContext())
                .load(photoUrl)
                .asBitmap()
                .into(new SimpleTarget<Bitmap>(width, height) {
                    @Override
                    public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                        // Do something with bitmap here.
                    }
                });`

Thanks for your help.

**Comment by TWiStErRob** [comment]
If you do it like that make sure you know that the Bitmap is delivered on the UI thread, so you should watermark/save the file in the background. You should also probably clear the target once you're done with the Bitmap. `Glide.clear(target)`: you can acquire the target as `this` in `onResourceReady`, the return value of `into`, or save it as a variable right at `new`ing time. You may also want to define a transformation: fitCenter or centerCrop.

**Comment by AssassinWayne** [comment]
@TWiStErRob 
Yes, I'm sure the Bitmap is delivered on the UI thread and the IO executed in the background. Thanks for your tips that I almost forget to clear the target.

Thank you very much!
