### ISSUE TITLE
Image flicker issue

### ISSUE THREAD

**Issue by DeepsUttekar** [bumptech/glide#1369]
This is the code....

```java
  /*
     * get image from server
     */
    private void getThumbnailFromServer(final Contents contents, final ViewHolder holder, final String thumbnailUrl) {
        //Glide image downloader is used to get image from server
        Glide.with(mFragment).load(thumbnailUrl).asBitmap().override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).centerCrop().diskCacheStrategy(DiskCacheStrategy.SOURCE).listener(new RequestListener<String, Bitmap>() {
            @Override
            public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                return false;
            }

            @Override
            public boolean onResourceReady(final Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
                String imageName = thumbnailUrl.substring(thumbnailUrl.lastIndexOf("/") + 1);
                String imagePath = Environment.getExternalStorageDirectory() + File.separator + mFragment.getActivity().getString(R.string.app_name) + THUMBNAILS_FOLDER_NAME + imageName;
               // holder.mIvContentImage.setImageBitmap(resource);

                saveImage(resource, contents, imagePath);
                return false;
            }
        }).into(holder.mIvContentImage);
    }
```

so when we try to run this for first time.... we see all data with no thumbnail/image... complete recycler view gets inflated...

but once the images starts downloading.. recycler view starts flickering/repainting and its bad user experience and once all images gets downloaded completely.. repainting stops

please let me know how can I fix this

**Comment by TWiStErRob** [comment]
I don't see anything wrong here. Can you please share your XML and capture a video (`adb screenrecord` or describe the flicker in a lot of details)?

Do you call this method from `onBind`?
Try to not call `saveImage` (I hope that's just a debugging thing), I'm guessing it's I/O on the UI thread, which may mess things up.

**Comment by DeepsUttekar** [comment]
this is xml

<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:id="@+id/card_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:animateLayoutChanges="true"
    android:clickable="true"
    android:foreground="?attr/selectableItemBackground"
    card_view:cardCornerRadius="@dimen/card_view_radius"
    card_view:cardElevation="@dimen/card_view_elevation">

    <RelativeLayout
        android:id="@+id/rl_content_grid_item_parent"
        android:layout_width="match_parent"
        android:layout_height="@dimen/card_view_height"
        android:background="@color/content_grid_background_color"
        android:orientation="vertical">
        
        <RelativeLayout
            android:id="@+id/rl_content_image"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_above="@+id/rl_bottom_layout"
            android:scaleType="fitXY">

            <ImageView
                android:id="@+id/iv_content_image"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_gravity="center" />

            
            <FrameLayout
                android:id="@+id/rl_download_content"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_above="@+id/ll_desc">

                <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:alpha="0.3"
                    android:background="@color/black" />

            </FrameLayout>
            
            <FrameLayout
                android:id="@+id/ll_desc"
                android:layout_width="match_parent"
                android:layout_height="@dimen/card_view_desc_layout_height"
                android:layout_alignParentBottom="true">

                <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:alpha="0.4"
                    android:background="@color/black" />

                <com.springct.customfontviews.RobotoRegularTextView
                    android:id="@+id/tv_content_name"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:layout_marginLeft="@dimen/card_view_desc_left_margin"
                    android:layout_marginRight="@dimen/card_view_desc_right_margin"
                    android:ellipsize="end"
                    android:maxLines="2"
                    android:singleLine="false"
                    android:textColor="@color/white"
                    android:textSize="@dimen/grid_view_item_title" />

            </FrameLayout>
        </RelativeLayout>
        
        <RelativeLayout
            android:id="@+id/rl_bottom_layout"
            android:layout_width="match_parent"
            android:layout_height="@dimen/card_view_bottom_layout_height"
            android:layout_alignParentBottom="true"
            android:background="@color/cardview_bottom_layout_color"
            android:visibility="visible">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/card_view_bottom_layout_margin_bottom"
                android:layout_marginTop="@dimen/card_view_bottom_layout_margin_top"
                android:orientation="horizontal"
                android:visibility="visible">

                <ImageView
                    android:id="@+id/iv_assessment_button"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentBottom="true"
                    android:layout_toLeftOf="@+id/iv_add_to_download_button"
                    android:scaleType="center"
                    android:src="@drawable/ic_doc_normal"
                    android:visibility="gone" />

                <ImageView
                    android:id="@+id/iv_add_to_download_button"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentBottom="true"
                    android:layout_alignParentRight="true"
                    android:layout_marginLeft="@dimen/card_view_margin"
                    android:layout_marginRight="@dimen/card_view_margin"
                    android:clickable="true"
                    android:scaleType="center"
                    android:src="@drawable/ic_list_download"
                    android:visibility="visible" />
            </RelativeLayout>
        </RelativeLayout>


        <com.springct.customfontviews.RobotoRegularTextView
            android:id="@+id/tv_thumbnail_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:layout_marginLeft="@dimen/card_view_desc_left_margin"
            android:layout_marginRight="@dimen/card_view_desc_right_margin"
            android:ellipsize="end"
            android:maxLines="4"
            android:singleLine="false"
            android:textAlignment="center"
            android:textColor="@color/content_grid_text_color"
            android:textSize="@dimen/grid_view_item_title_no_thumbnail" />

        <ImageView
            android:id="@+id/img_content_type"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentTop="true"
            android:layout_alignParentRight="true"
            android:layout_marginLeft="@dimen/card_view_desc_left_margin" />

    </RelativeLayout>


</android.support.v7.widget.CardView>

**Comment by TWiStErRob** [comment]
Hmm, try `.dontAnimate()`, `animateLayoutChanges` and `TransitionDrawable` may be in conflict.

**Comment by DeepsUttekar** [comment]
Will upload video after

**Comment by DeepsUttekar** [comment]
No its not working with above options

**Comment by TWiStErRob** [comment]
Did you try removing `animateLayoutChanges` to rule that out?

**Comment by DeepsUttekar** [comment]
Yes I tried that... its not working. And im not able to upload video file here

**Comment by TWiStErRob** [comment]
You can put it on YouTube as an unlisted video or in your Google Drive and share it.

**Comment by DeepsUttekar** [comment]
drop box link
https://www.dropbox.com/s/3vi4go72ucqwro2/GlideRecyclerViewRepaintIssue.mp4?dl=0

**Comment by TWiStErRob** [comment]
Wow, that's a kind of flickering I've never seen. It looks like something is triggering a full rebind.
Notice that it's not the ImageView flickering, but the whole CardView is faded in again (along with the download button). Are you sure it's caused by Glide? I mean, what happens if you change the end of `getThumbnailFromServer` to below (or don't call the method at all)?
```
}); //.into(holder.mIvContentImage);
```

**Comment by DeepsUttekar** [comment]
If I do that and comment last line, it dnt get repainted again but image view is in blue(my default colour)

I tried to add debug point in onBindView but its not getting called during this flicker/repaint issue. 

And for 2nd run I use images from SD card instead of server, even that time also I dnt this repaint /flicker issue... So im thinkng its glide issue

**Comment by TWiStErRob** [comment]
So you're saying it only happens if you load images from network?
What triggers that card fade-in animation?

**Comment by DeepsUttekar** [comment]
no idea.... I have commented all the animations.. still this recreation issue happens

**Comment by TWiStErRob** [comment]
What I mean is something like: is it triggered when list-item's layout changes? Because that would explain Glide's hand in this. Each time an image is set into an ImageView a layout is triggered, see the code of `ImageView.setDrawable`.

**Comment by DeepsUttekar** [comment]
no... When I launch the screen. This is my applications home screen. I get data from database and I check if local copy of thumbnail is present, if yes,
I use following statment
 Glide.with(mFragment).load(Uri.fromFile(imageFile)).into(holder.mIvContentImage);

but if image is not local then I call function in 1st comment.

So

**Comment by TWiStErRob** [comment]
You didn't respond to my comment about animation, you explained where you load the file from. The problem is very likely how that fade-in is being triggered, it's probably too sensitive to layout changes.

**Comment by DeepsUttekar** [comment]
I have commented layout animation and still that issue persist. So its not animation issue.

**Comment by TWiStErRob** [comment]
No, I'm not talking about `animateLayoutChanges`, but the fade-in animation.

**Comment by DeepsUttekar** [comment]
Yeah.. we have explicitely handled onLayout and have implemeted delayed/animated loading of grid items. I have commented that code but issue is still there.

 @Override
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        super.onLayout(changed, l, t, r, b);
       /* for (int i = 0; i < getChildCount(); i++) {
            animate(getChildAt(i), i);

            if (i == getChildCount() - 1) {
                getHandler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        mScrollable = true;
                    }
                },  0);
            }
        }*/
        //mScrollable = true;
    }

**Comment by TWiStErRob** [comment]
So you commented out the fading code, but it's still fading? Something is not right about that statement.

**Comment by DeepsUttekar** [comment]
:-) after  creating videos.. i continued to do my trials... so my one of the trial was to commnet out onlayout code. I have not captured that video. So animation/fade-in n out is stopped but recreation is still der. Hence I told you that this is not a solution as I can nt create and upload video for everything

**Comment by TWiStErRob** [comment]
I'm just trying to help. There must be something fishy somewhere in your codebase that triggers the recreation. What I don't understand is how the issue (disappearing and appearing items) is still visible if nothing sets the item's alpha to 0.

**Comment by DeepsUttekar** [comment]
hmm.. As of now I have commented all the fancy stuffs but still same issue. Please let me know if you want me to try out anything else

**Comment by TWiStErRob** [comment]
Look, I don't understand what you mean when you say you still have the "same issue", because if all the fancy stuff is out of the picture, then there's nothing that would animate, or change the visibility of anything.

**Comment by DeepsUttekar** [comment]
i have explained u in my previous comment...  video sent to u was older
one... that video is created when i have not comentwd animation code...
after discusiions with u..  i have commented animation code also...

bt then also output is same... just animation effect ia removwd

**Comment by TWiStErRob** [comment]
So the full recycler items flash all at once, each time an image is loaded? Or just the ImageViews are flashing? Are the name TextViews still visilble when the flash happens? Did you try `.dontAnimate()` now, after removing all the fancy stuff?
