### ISSUE TITLE
How to load pictures with different size ratio and scale it to match fix width?

### ISSUE THREAD

**Issue by ZekunWang** [bumptech/glide#1370]
Hi, I am new to glide and I wish to get the basic idea or some sample codes, if possible, to load pictures and scale to fix width while keeping their original ratio.

Let's say I want the ImageViews to maintain a fix 100dp width and I need to load a 200dp x 100dp picture and another 50dp x50dp one.. They show be shown eventually as 100dp x 50dp and 100dp x 100dp. How can I implement this?

**Comment by TWiStErRob** [comment]
The image sizes are conventionally `wxh`, so you may have a typo in your description.
Anyway, you can very easily code what you described. In xml set the width to 100dp, and the other to whatever fits your layout structure. Then just call `Glide.with(this).load(blah).into(iv)`. Glide always keeps ratios. So unless you set `fitXY` you're all set.

**Comment by ZekunWang** [comment]
It works. Thank you very much!
