### ISSUE TITLE
How to remove a green background

### ISSUE THREAD

**Issue by chendiyou** [bumptech/glide#1371]
besides setDiskCache and implements GlideModule。
There are other ways you?

**Comment by chendiyou** [comment]
fix.
 // prepare Glide load
            BitmapRequestBuilder load = Glide.with(context)
                    .load(url)
                    .asBitmap()
                    .encoder(new BitmapEncoder(Bitmap.CompressFormat.PNG,100));

            // execute Glide load to relevant target
            if (view instanceof ImageView) {
                load.into((ImageView) view);
            } else {
                load.into(new GlideBitmapViewBackgroundTarget(view));
            }

**Comment by TWiStErRob** [comment]
#305, the green is caused by 565 bitmap format
There's workaround: https://github.com/bumptech/glide/wiki/Configuration#bitmap-format
This makes cached images smaller and faster than your current. PNG workaround.
