### ISSUE TITLE
Does glide downsample the image by itsself

### ISSUE THREAD

**Issue by prabinshrestha** [bumptech/glide#1372]
Hello Sir,
Does glide downsample the image by itself or do we have to downsample before we load it.And how do we do it as glide has method like Glide.load(url) since i am fetching my image from url

**Comment by TWiStErRob** [comment]
Just `load(url).into(imageView)` and Glide will downsample and transform it automatically based on view size and scaleType. If you want more detail check out the downsample class and the into method source code. You can also see in debug what sizes Glide is working with if you use something like https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/utils/LoggingListener.java. (see also [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener).
