### ISSUE TITLE
cancel a gilde request in recyclerview custom module

### ISSUE THREAD

**Issue by TheGreat0004** [bumptech/glide#1373]
https://gist.github.com/TWiStErRob/08d5807e396740e52c90

This is the gist, which explains in an excellent manner how to update view on progress,
but i don't know how to cancel a single request in this scenario.

any help would be great.

**Comment by TWiStErRob** [comment]
Normally it would be `Glide.clear(imageView)`, but since there's a custom target it's different here:
```java
class ProgressViewHolder {
...
    public void clear() {
        Glide.clear(target);
    }
}
```

**Comment by TheGreat0004** [comment]
It will delete the current request but 
like i have 5 image loading in recycler view, then how can i delete a single request like no. 5. from that 5 loading image.

**Comment by TWiStErRob** [comment]
The same way you would do it if there was no Glide or fanciness involved. You get ahold of the model/ViewHolder for that position and do something with it. e.g. `((MyVH)RecyclerView.findViewHolderForAdapterPosition(2)).clear()`.
