### ISSUE TITLE
When loading GIF into imageview it occurs FileNotFoundException: No such file or directory

### ISSUE THREAD

**Issue by 80998062** [bumptech/glide#1374]
Everything works fine yesterday,but after some tiny modify of my code , it throws a exception when loading gifs into imageView,(sometimes it can show only one gif successful).

> the code I load gif is

    this.drawableRequestBuilder = mGlide
                .fromString()
                .priority(Priority.IMMEDIATE)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .dontAnimate()
                .centerCrop();

                ......
                
    DribbbleTarget target = drawableRequestBuilder
                .load(shotUrl)
                .into(new DribbbleTarget(holder.mShot, data.isAnimated(), mAutoPlayGif));
        if (stolenSize == null) {
            // assuming uniform sizing among items (fixed size or match works, wrap doesn't)
            target.getSize((width, height) -> {
                if (0 < width && 0 < height) {
                    stolenSize = new int[]{width, height};
                }
            });
        } 

as you can see,I use a listPreloader here ,but I think it has nothing to do with this issue so I skip the code about that.               

> the logcat are as follow 

    07-29 15:14:52.880 8516-8516/com.sinyuk.yuk W/System.err: java.io.FileNotFoundException: No such file or directory
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at android.os.Parcel.openFileDescriptor(Native Method)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:270)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:937)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:865)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:21)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:14)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:83)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    07-29 15:14:52.881 8516-8516/com.sinyuk.yuk W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    07-29 15:14:52.882 8516-8516/com.sinyuk.yuk W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    07-29 15:14:52.882 8516-8516/com.sinyuk.yuk W/System.err:     at java.lang.Thread.run(Thread.java:818)
    07-29 15:14:52.882 8516-8516/com.sinyuk.yuk W/System.err:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

I also use glide-okhttp3-integration,its logcat is:

    07-29 15:33:05.317 26525-27101/com.sinyuk.yuk D/OkHttp: User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 6P Build/MTC19X)
    07-29 15:33:05.317 26525-27101/com.sinyuk.yuk D/OkHttp: Accept-Encoding: identity
    07-29 15:33:05.317 26525-27101/com.sinyuk.yuk D/OkHttp: --> END GET
    07-29 15:33:05.320 26525-27276/com.sinyuk.yuk D/OkHttp: <-- HTTP FAILED: java.io.IOException: Canceled

Ehhh, I think maybe one reason for this is the disk cache.
Should I use the DiskCacheStrategy.SOURCE ? It looks like the exception occurs when Glide trying to hit the cache.

Or am I wrong about my GlideModule?

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // Prefer higher quality images unless we're on a low RAM device
        ActivityManager activityManager =
                (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        builder.setDecodeFormat(activityManager.isLowRamDevice() ?
                DecodeFormat.PREFER_RGB_565 : DecodeFormat.PREFER_ARGB_8888);
        
        builder.setResizeService(new FifoPriorityThreadPoolExecutor(4));
        builder.setDiskCache(new InternalCacheDiskCacheFactory(context, sizeInBytes));
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        DaggerApiComponent.builder().appModule(new AppModule((Application) context.getApplicationContext()))
                .build().inject(this);
        glide.register(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(okHttpClient));
    }

I set the disk cache by myself because I think a lot gifs is big , so I should control cache size more strictly ( I guess... )
And I setResizeService() here cause the Gif plays slower than it on the computer...(through it's still slow now)
OMG,I found that things become so complicated for me When I want to use Glide in advanced....

Ok back to my problem , kindly review my code and give me some advice. Thx in advance!

**Comment by TWiStErRob** [comment]
If you have more than 4 GIFs displayed at the same time, you may need more threads than 4. I imagine when you say it's slower than the desktop you opened only 1 GIF there, but checked the list on the phone. It's also possible that the frame timings are too right, so Glide uses a bigger delay.

Immediate won't really help here, unless you have other loads in the list. Priorities are relative to each other, increasing one group if you have only one group won't make a difference. Also I think that priority only affects the initial loading of the GIF bytes, not individual frame decodes.

SOURCE is the rightcache for GIFs.

Constraint is a good idea for large files, however it may result in more downloads if the user scrolls a lot and fills the cache quickly.

Advanced Glide is complex, yes, but imagine how much complexity is still hidden from you below the surface.

Now, onto the error. The file descriptor thing suggest that it's trying to load a local file. Double check `shotUrl`, if it's correct and exists. I can imagine that the size is so low that by the time on image is downloaded the other thread makes the just-downloaded cache file evicted. It would help a lot if you knew what that "small code change" was, though if it's unrelated then it's weird.

The fact that OkHttp says cancelled sounds like a load was started and then you scrolled and the item was recycled and a new load started into the same view. What's your custom target btw? That may be hiding clues as well.

Try `asGif()`, though it may not make any difference. Put a breakpoint in `ImageVideoModelLoader` and check what it's referring to and how it behaves.

Just curious: why do you inject the GlideModule into Dagger?

**Comment by 80998062** [comment]
Thank you for reply....actually I am playing with my Dribbble client ,but I found one interesting difficulty that is to load the animated images😂(cause the GIF plays really slower than usual).

I have figured out that a high quality gif is about 1 MB😢, while a JPG is only about 200 KB...so an alternative for me is Not to play the GIF;But if so,I wonder whether  I can 

- only load the first frame of the GIF use `asBitmap()` in request,in this way will Glide load only first frame of GIF...so it can be faster
- then when I want to play the GIF , I make a new request (use `.asGIF()` instead,although it seems to make no difference )

Sorry for my easy explanation😂,it's just a rough idea.Plz consider if this is feasible...And all my usage of Glide is put here:
[https://github.com/80998062/Yuk/blob/master/app/src/main/java/com/sinyuk/yuk/ui/feeds/FeedsAdapter.java](url)
And thank you for taking time to read this... 😊

**Comment by TWiStErRob** [comment]
Those numbers don't matter `.asBitmap()` still downloads the full GIF image, and if you don't use `.asBitmap().diskCacheStrategy(ALL)`, the later `.asGif().diskCacheStrategy(SOURCE)` will download the file again. Also a 200kB JPEG in memory can still be 24MB, Bitmap objects are uncompressed. The idea is good though, but don't make the user long-press and hold, it's really weird, just start/stop on tap.

I've lost track a little of what your issue is, because you were saying FNFException, but now it's slow GIF playback? I built and installed that app on my phone and GIF is very smooth when I hold my finger.
