### ISSUE TITLE
Glide loading image problem

### ISSUE THREAD

**Issue by a6289413** [bumptech/glide#1376]
I used glide to meet the following problems, these problems have been repeated before, but I have not found a good solution, do not know now have a good solution to it?
1, I use glide combined with `de.hdodenhof.circleimageview.CircleImageView` to use, load the circular picture, the code is as follows:
```java
 Glide.with(mFragment).load(url).placeholder(R.drawable.ic_company_default).into(imagView);
```
This will have a problem, the first load out of the placeholder picture, rather than I want to load the picture, but my URL is valid. obviously this issue has been addressed already and the other program is given.
The code:

```java
Glide.with(this).load(URL).transform(new CircleTransform(context)).into(imageView);

public static class CircleTransform extends BitmapTransformation {
    public CircleTransform(Context context) {
        super(context);
    }

    @Override protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
        return circleCrop(pool, toTransform);
    }

    private static Bitmap circleCrop(BitmapPool pool, Bitmap source) {
        if (source == null) return null;

        int size = Math.min(source.getWidth(), source.getHeight());
        int x = (source.getWidth() - size) / 2;
        int y = (source.getHeight() - size) / 2;

        // TODO this could be acquired from the pool too
        Bitmap squared = Bitmap.createBitmap(source, x, y, size, size);

        Bitmap result = pool.get(size, size, Bitmap.Config.ARGB_8888);
        if (result == null) {
            result = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        }

        Canvas canvas = new Canvas(result);
        Paint paint = new Paint();
        paint.setShader(new BitmapShader(squared, BitmapShader.TileMode.CLAMP, BitmapShader.TileMode.CLAMP));
        paint.setAntiAlias(true);
        float r = size / 2f;
        canvas.drawCircle(r, r, r, paint);
        return result;
    }

    @Override public String getId() {
        return getClass().getName();
    }
}
```
But this program has a problem, that is, can not be set placeholder. Do you have any suggest ( s) ?

2, I put some fragment into a ViewPager, When I switched the fragment, the loaded image cannot display,  the code:
```java
Glide.with(mFragment).load(url).placeholder(R.drawable.ic_company_default).into(imagView);
```
So I select another method load image, the code:
```java
 Glide.with(fragment).load(url).placeholder(R.drawable.head_img_default)..into(newSimpleTarget<GlideDrawable>() {
            @Override
            public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                imageView.setImageDrawable(resource);
            }
        });
```
This can solve the problem that I said before.But it will have a new problem. for example , I have a RecyclerView, and the RecyclerView has 3 items, every item's width and height is match_parent , I will load  a.jpg , b.jpg , c.jpg,  but only the a.jpg  url is valid, others is invalid.  when the program is running, the first item will load a.jpg sucess, then  I scroll the RecyclerView, the second item load b.jpg and the third item load c.jpg will failed, and the second item and the third item will display the placeholder. But in the process has a problem, the second item and the third item first display a.jpg, and then display the placeholder

**Comment by TWiStErRob** [comment]
> the second item and the third item first display a.jpg, and then display the placeholder

That's only possible if you run your `Glide....into` async. If the code is straight in the onBind method this shouldn't happen. Though `SimpleTarget` is not a good solution there. I think what you're looking for is:
```
Glide.with(mFragment).load(url).placeholder(R.drawable.ic_company_default).dontAnimate().into(imagView);
```
this will solve all your problems at once: you can use a circular image view and it will circle-crop the placeholder, and the viewpager issue is probably similarly related to TransitionDrawable.

Or you could alternatively use CircleTransform + a placeholder, but make the placeholder round in res/drawable. Or if you don't like hard-coding you can apply the transformation before handing it to Glide: https://github.com/bumptech/glide/issues/1077#issuecomment-199292758

**Comment by a6289413** [comment]
tks
