### ISSUE TITLE
How to set loading with load?

### ISSUE THREAD

**Issue by xanaduo** [bumptech/glide#1377]
如果在加载的过程中设置加载进度？

**Comment by TWiStErRob** [comment]
#232 or #505?

**Comment by LiHanGuang** [comment]
@TWiStErRob 

@xanaduo ask you: how to show the progress of loading image by Glide.

**Comment by TWiStErRob** [comment]
@LiHanGuang Thanks, I gathered that much, but that question - even in your translation - simply can target the simple use of a `placeholder`, animated or not, or a full progress bar, or something totally different. Hence my two links, which should cover most of the cases.
