### ISSUE TITLE
integration okhttp3 error

### ISSUE THREAD

**Issue by wwflier** [bumptech/glide#1380]
Gradle config:
compile 'com.squareup.okhttp3:okhttp:3.4.1'
compile 'com.github.bumptech.glide:glide:3.7.0'
compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'

manifests config:
<meta-data
            android:name="com.bumptech.glide.integration.okhttp3.OkHttpGlideModule"
            android:value="GlideModule" />

code:
 @Override
    protected void onCreate(Bundle savedInstanceState) {
               .......
              Glide.with(this).load(imageUrl).into(imageView);
              .......
}
error:
You must provide a Model of a type for which there is a registered ModelLoader, if you are using a custom model, you must first call Glide#register with a ModelLoaderFactory for your custom model class

**Comment by TWiStErRob** [comment]
You don't need the Glide module, the manifest merger will pick it up from the AAR file.

What's the type of `imageUrl`?

**Comment by wwflier** [comment]
@TWiStErRob thanks! It's done.
