### ISSUE TITLE
Glide loading image slowly when adding header request and response as byte 

### ISSUE THREAD

**Issue by santhanam1991** [bumptech/glide#1384]
glide_version=3.7.0

no integration library used.

Genymotion Nexus 5 5.0.1 / Other devices

-----------------------------------------------
```java
LazyHeaders.Builder builder = new LazyHeaders.Builder();
 for (Map.Entry<String, String> keySet : headerData.entrySet())
   { 
   builder.addHeader(keySet.getKey(), keySet.getValue()); 
  } 
GlideUrl glideUrl = new GlideUrl(baseURl, builder.build());

myReq = Glide.with(fragment);
myReq.load(glideUrl) 
  .signature(new StringSignature(thumbPath)) 
  .placeholder(R.drawable.loading) 
  .listener(new RequestListener<GlideUrl, GlideDrawable>() {...}
```
Image loading based on viewport size.

--------------------------------------------------------------------

I have followed the above steps to load image with header data (Note : Image response in content data as encoded), but Glide takes more time for loading. It seems it's loading one by one. then I used Picasso loader(which is suggested https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/FilesAdapter.java)

it's really faster.

But my glide object was loading efficiently for other type of images like device source,url direct image.

Also I have checked image caching logic is working fine. for loading alone takes around 2.5sec and after that not rendering immediately.

I don't understand the reason, whether I have done any configuration mistake or due to passing header request for near thousands of images.

**Comment by TWiStErRob** [comment]
*Thanks for opening a new issue, we can have a long conversation here if needed.*

> "Image response in content data as encoded"

If that's true, then Skia would fail loading it. Who is decoding the stream? Do you have a GlideModule you're not disclosing?

> .noFade()

Tip: the corresponding call is `.dontAnimate()` in Glide.

> it's really faster [...]  loading alone takes around 2.5sec

Which part of the load is faster? Download, decode, transformation, animation, ...? Enable [logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) to see what Glide is doing internally. Also: How did you check previously? How did you check the cache is working fine? What type of image are you loading?

**Comment by santhanam1991** [comment]
@TWiStErRob 

Sry for the late reply.

yes i'm using GlideModule to set cache path.

target is into(aImageView);

given dontanimate(), I don't know where to give nofade().

I have enabled all the Glide log. please update we where the delay is happening.

but other than Picasso loader. I have tried Other ImageLoader Library still it's slow. for my url. [link ](https://www.dropbox.com/developers/documentation/http/documentation#files-get_thumbnail)

I don't think Glide is doing something wrong. but I'm not sure how Picasso loading very quickly [example](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/build.gradle). 

When Cache False:
--------------------
08-11 08:50:23.900	3313	3313	V	GenericRequest	Resource ready in 7915.120470999999 size: 0.10986328125 fromCache: false this: 1392621244
08-11 08:50:24.504	3313	4975	V	DecodeJob	Fetched data in 602.2350369999999, key: EngineKey{https://content.dropboxapi.com/2/files/get_thumbnail+StringSignature{signature='/50Mb50Photo/IMG_20141205_112706.jpg'}+[240x240]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
08-11 08:50:24.504	3313	4975	V	LruBitmapPool	Get bitmap=[96x128], RGB_565
08-11 08:50:24.504	3313	4975	V	LruBitmapPool	Hits=81, misses=110, puts=97, evictions=0, currentSize=2390544, maxSize=13639680
08-11 08:50:24.504	3313	4975	V	LruBitmapPool	Strategy=AttributeStrategy:
08-11 08:50:24.504	3313	4975	V	LruBitmapPool	  GroupedLinkedMap( {[96x128], RGB_565:0}, {[240x240], RGB_565:0}, {[128x96], RGB_565:1}, {[80x80], RGB_565:0}, {[128x128], RGB_565:1}, {[122x122], RGB_565:1}, {[128x64], RGB_565:1}, {[128x80], RGB_565:1}, {[93x128], RGB_565:1}, {[128x72], RGB_565:1}, {[230x230], RGB_565:0}, {[720x720], RGB_565:0}, {[480x480], RGB_565:1}, {[72x128], RGB_565:1}, {[60x60], RGB_565:0}, {[313x316], RGB_565:2}, {[717x402], RGB_565:1}, {[447x450], RGB_565:1}, {[296x296], RGB_565:1}, {[306x306], RGB_565:1}, {[64x64], RGB_565:1} )
08-11 08:50:24.504	3313	4975	V	DecodeJob	Decoded from source in 1.015526, key: EngineKey{https://content.dropboxapi.com/2/files/get_thumbnail+StringSignature{signature='/50Mb50Photo/IMG_20141205_112706.jpg'}+[240x240]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
08-11 08:50:24.504	3313	4975	D	LruBitmapPool	Missing bitmap=[240x240], RGB_565
08-11 08:50:24.504	3313	4975	V	LruBitmapPool	Get bitmap=[240x240], RGB_565
08-11 08:50:24.504	3313	4975	V	LruBitmapPool	Hits=81, misses=111, puts=97, evictions=0, currentSize=2390544, maxSize=13639680
08-11 08:50:24.504	3313	4975	V	LruBitmapPool	Strategy=AttributeStrategy:
08-11 08:50:24.504	3313	4975	V	LruBitmapPool	  GroupedLinkedMap( {[240x240], RGB_565:0}, {[96x128], RGB_565:0}, {[128x96], RGB_565:1}, {[80x80], RGB_565:0}, {[128x128], RGB_565:1}, {[122x122], RGB_565:1}, {[128x64], RGB_565:1}, {[128x80], RGB_565:1}, {[93x128], RGB_565:1}, {[128x72], RGB_565:1}, {[230x230], RGB_565:0}, {[720x720], RGB_565:0}, {[480x480], RGB_565:1}, {[72x128], RGB_565:1}, {[60x60], RGB_565:0}, {[313x316], RGB_565:2}, {[717x402], RGB_565:1}, {[447x450], RGB_565:1}, {[296x296], RGB_565:1}, {[306x306], RGB_565:1}, {[64x64], RGB_565:1} )
08-11 08:50:24.504	3313	4975	V	LruBitmapPool	Put bitmap in pool=[96x128], RGB_565
08-11 08:50:24.508	3313	4975	V	LruBitmapPool	Hits=81, misses=111, puts=98, evictions=0, currentSize=2415120, maxSize=13639680
08-11 08:50:24.508	3313	4975	V	LruBitmapPool	Strategy=AttributeStrategy:
08-11 08:50:24.508	3313	4975	V	LruBitmapPool	  GroupedLinkedMap( {[240x240], RGB_565:0}, {[96x128], RGB_565:1}, {[128x96], RGB_565:1}, {[80x80], RGB_565:0}, {[128x128], RGB_565:1}, {[122x122], RGB_565:1}, {[128x64], RGB_565:1}, {[128x80], RGB_565:1}, {[93x128], RGB_565:1}, {[128x72], RGB_565:1}, {[230x230], RGB_565:0}, {[720x720], RGB_565:0}, {[480x480], RGB_565:1}, {[72x128], RGB_565:1}, {[60x60], RGB_565:0}, {[313x316], RGB_565:2}, {[717x402], RGB_565:1}, {[447x450], RGB_565:1}, {[296x296], RGB_565:1}, {[306x306], RGB_565:1}, {[64x64], RGB_565:1} )


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
When Cache true :
----------
08-11 08:50:15.780	3313	3313	V	GenericRequest	Got onSizeReady in 0.009611999999999999 this: 1392726168
08-11 08:50:15.780	3313	3313	V	GenericRequest	finished setup for calling load in 0.048577999999999996 this: 1392726168
08-11 08:50:15.780	3313	3313	V	GenericRequest	Resource ready in 0.09000999999999999 size: 0.01220703125 fromCache: true this: 1392726168
08-11 08:50:15.780	3313	3313	V	Engine	Loaded resource from cache in 0.048257ms, key: EngineKey{https://content.dropboxapi.com/2/files/get_thumbnail+StringSignature{signature='/4 x 4/HD1405927662536.jpg'}+[80x80]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
08-11 08:50:15.780	3313	3313	V	GenericRequest	finished onSizeReady in 0.135626 this: 1392726168
08-11 08:50:15.780	3313	3313	V	GenericRequest	finished run method in 0.14654 this: 1392726168

**Comment by TWiStErRob** [comment]
Turn off `LruBitmapPool`, that's just spamming here.
I can see that the first log line says 8 second load time, but the rest of the logging is missing.
`dontAnimate()` in Glide == `noFade()` in Picasso
Please answer the rest of the questions above, and include some code; that's the easiest to overcome the language barrier.

**Comment by santhanam1991** [comment]
Sorry It's my fault understanding in glide,

Glide setting threadPoolExecutor size based on Runtime.getRuntime().availableProcessors() 

 int availableProcessors = **Math.max(1, Runtime.getRuntime().availableProcessors())**; but my case I'm getting only one available processor. [link](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java).

So that image is loading one by one in glide.

**But, Picasso default threadPoolCount is 3**,  private static final int DEFAULT_THREAD_COUNT = 3;
[link](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/PicassoExecutorService.java)

Of-course dropbox taking around 3sec for loading each image for both in glide and picasso.

Also I know we can override default glide ExecutorService, .setResizeService(ExecutorService service) in my glidemodule.
