### ISSUE TITLE
onLoadFailed, Exception is null

### ISSUE THREAD

**Issue by MKevin3** [bumptech/glide#1385]
Glide 3.7.0
Android Studio Emulator
Loading image the onLoadFailed(Exception e, Drawable errorDrawable)

e is null

The iOS side is getting this error

The certificate for this server is invalid. You might be connecting to a server that is pretending to be "{server info in here}" which could put your confidential information at risk

Know issue with URL but I was expecting to get a similar error from Glide on the Android side of things.

```java
        Glide.with(getContext())
                .load(avatarUrl)
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .placeholder(R.drawable.missing_tutor)
                .into(new ViewTarget<ImageView, GlideDrawable>(avatarImage) {
                    @Override
                    public void onResourceReady(GlideDrawable resource, GlideAnimation anim) {
                        Timber.d("Glide image load success");
                        avatarImage.setImageDrawable(resource.getCurrent());
                        hideProgressDialog();
                    }

                    @Override
                    public void onLoadFailed(Exception e, Drawable errorDrawable) {
                        hideProgressDialog();
                        Timber.d("Glide image load failed for %s -> %s", profileUrl, e == null ? "<unknown>" : e.getLocalizedMessage());
                        profileUrl = null;
                        avatarImage.setVisibility(View.INVISIBLE);
                        avatarText.setVisibility(View.VISIBLE);
                    }
                });
```

**Comment by TWiStErRob** [comment]
Hmm, I think it could only be null if the model (url) is null or there's a cache problem (which doesn't seem to apply here, because you disabled both).

Try other techniques: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
Or debug https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/EngineRunnable.java#L50-L83

It might be that the fetcher returns a null stream or the decoder a null object (watch out for skia logs).

**Comment by yashasvigirdhar** [comment]
@TWiStErRob 
facing similar issue. Is it intended behaviour from Glide to return a null exception even in the cases that you mentioned. Normally, we don't add null checks for exceptions, so wanted to clear this.

**Comment by TWiStErRob** [comment]
@yashasvigirdhar Yes, I agree, this is likely one of those "historical reasons". In Glide 3.x you need a null check as of now.

Let's track this in #1675; if you feel up to it, you can have a stab at a PR against 3.0 branch, it would be most welcome!
