### ISSUE TITLE
How to get "content-type" header if loaded image from URL

### ISSUE THREAD

**Issue by zeroarst** [bumptech/glide#1387]
Glide Version: 3.7.0

Integration libraries: no

Device/Android Version:
Android Virtual Device and Samsung S7 edge 6.0

**Issue details / Repro steps / Use case background**: 
Basically what I would like to achieve is to know what is the image type from given URL which has not extension at the end. ex. Http://www.myweb.com/img=LilsjIsoJLOLSlsoAqJoOEuFHVVNbz
I found that I can get this info with urlConnection.getHeaderField("Content-Type"), then I dug into the source code, found out that in HttpUrlFetcher there is a URLConnection instance. However, they cannot be accessed. 

Do I have to create a HttpUrlGlideUrlLoader by myself..? Or there are other better solutions..?

Thanks!!

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/issues/1378#issuecomment-236879983, the same applies.

To prevent this situation you're in, I would suggest sending down meta-data for the image at the time you're receiving the url itself. See for example the [Twitter API](https://dev.twitter.com/overview/api/entities-in-twitter-objects#media).

**Comment by zeroarst** [comment]
Thanks @TWiStErRob 
I wrote a ModelLoader and i wonder can I still use `DiskCacheStrategy`?

I found then I call `.using(new ImageTypeOKHttpUrlGlideUrlLoader(), InputStream.class)` it returns me a GenericModelRequest instance which unlike normal  `Glide.(Myfragmentthis).load(mImgUrl)` which returns `DrawableTypeRequest` that has `DiskCacheStrategy` method.

Sorry been asking questions as I am still new to Glide and not understand how to customize it.

```java
class ImageTypeOKHttpUrlGlideUrlLoader implements ModelLoader<String, InputStream> {
        
        @Override
        public DataFetcher<InputStream> getResourceFetcher(final String model, int width, int height) {
            return new DataFetcher<InputStream>() {
                @Override
                public InputStream loadData(Priority priority) throws Exception {
                    final OkHttpClient client = new OkHttpClient.Builder().build();

                    Request req = new Request.Builder().url(model).build();

                    Response response = client.newCall(req).execute();

                    mImageType = response.header("content-type");
                    return response.body().byteStream();
                }

                @Override
                public void cleanup() {

                }

                @Override
                public String getId() {
                    return model;
                }

                @Override
                public void cancel() {

                }
            };
        }
    }
````

**Comment by TWiStErRob** [comment]
I think if you continue as usual with `.load(model)` or `from(Model.class)` and you'll get more options. You may need to use `StreamModelLoader` though, or add cacheEncoder/decoder yourself.
