### ISSUE TITLE
如何监听图片加载结束

### ISSUE THREAD

**Issue by wincentytg** [bumptech/glide#1388]
大神 如何监听图片加载结束？我要在图片加载结束后做相关操作

**Comment by Ztiany** [comment]
@wincentytg http://mrfu.me/2016/02/27/Glide_Getting_Started/

**Comment by xesam** [comment]
你得先知道大神懂不懂中文。。

**Comment by wincentytg** [comment]
@xesam 哈 ok i get thanks！

**Comment by wincentytg** [comment]
@Ztiany thanks

**Comment by xanaduo** [comment]
呵呵，看了几个问题，发现这个框架监测图片进度很难的样子。

**Comment by TWiStErRob** [comment]
Thanks guys for helping out.
As far as I understand you're looking for `.listener()`, that's called at the end of load. If you want beginning and end then you need to extend  `*ImageViewTarget` and override some methods.
