### ISSUE TITLE
Instead of Placeholder, How to hide the Imageview?, is it possible to do with glide return values? Please response for this issue.

### ISSUE THREAD

**Issue by mohanrajsambath** [bumptech/glide#1390]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with...
```

**Layout XML**:

``` xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:

``` ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Can you please elaborate more on what are you trying to achieve and why?
What do you mean by "Glide return values"?
