### ISSUE TITLE
Unable to get images displayed in fragments with viewpager?

### ISSUE THREAD

**Issue by venkymsnv** [bumptech/glide#1398]
I have displayed the thumbnails of images with recyclerview in Screen 1.
Upon clicking an image in Screen 1, I want to display a larger image in another activity with view pager fragment in Screen 2. When swiping the images, it is displaying only 1 to 2 images, left or right side of current image, and the remaining images are not displaying.
Below is the code I used in fragment:

``` java
MainActivty.fullRequest
    .load(photo)
    .dontAnimate()
    .dontTransform()
    .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
    .listener(new RequestListener<Webphotosone, GlideDrawable>() {
        @Override
        public boolean onException(Exception e, Webphotosone model, Target<GlideDrawable> target, boolean isFirstResource) {
            return false;
        }

        @Override
        public boolean onResourceReady(GlideDrawable resource, Webphotosone model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
            return false;
        }
    })
    .into(fullscreenView);
```

**Comment by TWiStErRob** [comment]
You have `.error(null)`, so very likely that's what you're (not) seeing. Check https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling on how to diagnose errors.

Based on your load, you're very likely out of memory. ViewPager doesn't work like RecyclerView, it keeps more pages in memory. You're loading original sized images, they're likely big (Bitmap is uncompressed, so a 200kB PNG file can be 50MB in memory).

Tip: If you're loading the same images in multiple places enable `SOURCE` cache. For the thumbnail: `.diskCacheStrategy(ALL)` and for the big image: `.diskCacheStrategy(SOURCE)`.

**Comment by venkymsnv** [comment]
Thanks for the quick response.
I used fullrequest and thumbnail request for recyclerviews grid.
and 
I used below code for large images
` Glide.with(FullscreenActivity.this).load(phot.getUrlc())
                  .crossFade()
                  .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                  .into(fullscreenView);`
By using above way cache size is very large about 20MB for 40 images.
Is there any efficient way to perform the task?

**Comment by TWiStErRob** [comment]
The default cache is RESULT, so in your thumb and full load will download the image and save a resized version of it, then comes the large image which downloads it again. It's wasting cache space. Never load full resolution images in the grid, let Glide figure out the optimal size, that's the most efficient.

In the grid: `.diskCacheStrategy(ALL).override(don't call)`, if you want thumbnail for the grid, use `.sizeMultiplier()` or `.thumbnail(float)`. In the full-sized image: `.diskCacheStrategy(SOURCE).override(don't call)`. Clear your cache / reinstall the app to see how it affects the size.

**Comment by venkymsnv** [comment]
with .sizeMultiplier() or .thumbnail(0.5f) thumbnails are flickering.
when I use override for thumbnail its not flickering.
also there is very little difference in cache.

**Comment by TWiStErRob** [comment]
There shouldn't be any flickering normally, but anyway, `.dontAnimate()` should take care of that.
