### ISSUE TITLE
GifDecoder class not found?

### ISSUE THREAD

**Issue by kuang438951276** [bumptech/glide#1402]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with...
```

**Layout XML**:

``` xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:

``` ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
A little more info please... what are you doing when not found? What is the error message? What is your environment? ...
