### ISSUE TITLE
Glide how to obtain the size of the cache

### ISSUE THREAD

**Issue by hekaidaqaz** [bumptech/glide#1403]
If you have to provide access to the size of the cache, can you tell the method, if not, can also provide the train of thought

**Comment by TWiStErRob** [comment]
There's no way to read the cache sizes (current/max), only to set the maximum.

If you need it for debugging you can get `Glide.memoryCache` with reflection and call `MemoryCache` methods on it. If you want the disk cache size you need to know where it is on the device and sum the file sizes, see `InternalCacheDiskCacheFactory`; both of these are set up in `GlideBuilder.createGlide` or overridden via a `GlideModule`: https://github.com/bumptech/glide/wiki/Configuration#global-configuration
