### ISSUE TITLE
Firebase problem with glide.

### ISSUE THREAD

**Issue by nmlemus** [bumptech/glide#1407]
I am  using firebase 9.0.2 and when I include compile 'com.github.bumptech.glide:glide:3.7.0' in my project I have the following error in Android 4.4:
java.lang.NoClassDefFoundError: com.google.firebase.FirebaseOptions
If I exlcude the glide library everything is working again.
Do you know if you have some kind of incompatibility with Firebase?
Regards,
Noel

**Comment by TWiStErRob** [comment]
We don't know any, I think it would've come up already.

Afelter a fully clean build with Glide on the dependencies I would look around multidex. Likely Glide is pushing firebase out of the base dex.

**Comment by nmlemus** [comment]
I think this is the problem, do you know how can I solve it?

**Comment by TWiStErRob** [comment]
Use multidex, I'm sure there are hundreds of tutorials out there.
