### ISSUE TITLE
placeholder  Set up has been displayed

### ISSUE THREAD

**Issue by hekaidaqaz** [bumptech/glide#1409]
Added to figure, load for the first time has been showed to figure, loaded not refresh, the second time to refresh

**Comment by TWiStErRob** [comment]
Please try to diagnose with https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling 

If it doesn't help, please try to write a better description, I don't get it.

**Comment by hekaidaqaz** [comment]
Glide.with(fragment).load(((HospitalEntity) alObjects.get(position)).getImg()).centerCrop().placeholder(R.drawable.default_cover).error(R.drawable.default_cover).crossFade().into(holder.imgCover);


Above this kind of writing will appear constantly "default_cover"

**Comment by hekaidaqaz** [comment]
Remove ". CrossFade () "is ok, but there is no animation effects

**Comment by TWiStErRob** [comment]
You're likely seeing the error drawable, not the placeholder. Check the link above and add a listener to log. `crossFade` is enabled by default, so that shouldn't change anything.

**Comment by hekaidaqaz** [comment]
所有问题都是我自定义view的情况下发生的，好像我自定义Imagvew后，glide就不怎么适用了
All problem is my custom view of the case, it seems I custom Imagvew, glide don't apply

**Comment by TWiStErRob** [comment]
Hmm, is it circle view?
https://github.com/bumptech/glide#compatibility

**Comment by hekaidaqaz** [comment]
Use. DontAnimate () solved
