### ISSUE TITLE
How to disable gif feature? 

### ISSUE THREAD

**Issue by cantalou** [bumptech/glide#1411]
**Glide Version**: 3.8.0

**Integration libraries**: no

**Device/Android Version**: Android 2.3

**Issue details / Repro steps / Use case background**:
My app often encounters oom on version 2.3. I had add the plugin leakcanary and no activty was leaked. After dumping the heap , I found some big object about gif. so I want to  disable gif feature and make more test? 
![image](https://cloud.githubusercontent.com/assets/10027821/17641934/65f0f392-6166-11e6-825a-1fd88d6d4b87.png)

**Comment by TWiStErRob** [comment]
`load(...).asBitmap()`

You're probably either loading too big GIFs, or not clearing them often enough (see `RecyclerView.Adapter.onViewRecycled` and `Glide.clear`)

**Comment by hamberluo** [comment]
load as bitmap does not have a transition animation between placeholder and bitmap

**Comment by TWiStErRob** [comment]
It has been added in #1096, but not released yet; you can use the [snapshot](https://github.com/bumptech/glide/wiki/Snapshots) or one of the [verbose workarounds](https://github.com/bumptech/glide/issues/840#issuecomment-167326465).
