### ISSUE TITLE
Avoid download again when going to other activity

### ISSUE THREAD

**Issue by blitzk01** [bumptech/glide#1412]
Like any other gallery, my app have a preview activity (grid) of all images. Glide works nice and download all images nicelly. But, if I click the Image I want to see in fullscreen, Glide DOWNLOAD AGAIN that image when the next activity pop-up (on oncreate method, for example). 
How do I use the already downloaded images in the preview activity, but now in the fullscreen activity to avoid re-download?
Thanks.

**Comment by TWiStErRob** [comment]
`.diskCacheStrategy(SOURCE or ALL)` in the grid load and `.diskCacheStrategy(SOURCE)` in the full screen load.
