### ISSUE TITLE
load from ftp

### ISSUE THREAD

**Issue by abbasalim** [bumptech/glide#1413]
hello, i want to load from a ftp , what must i do it?

**Comment by TWiStErRob** [comment]
I think you need to create a custom model class that holds the host, port, credentials, path. Register a model loader factory for it, and then return a stream fetcher which will open an InputStream from the FTP. How you connect to FTP is up to you.

**Comment by abbasalim** [comment]
try {

                final FTPClient ftp = new FTPClient();
                ftp.connect(Config.server);

                ftp.enterLocalPassiveMode();
                if (!ftp.login(Config.user, Config.pass)) {
                    ftp.logout();
                    Log.d("@@@@", "Couldn't log in");

                } else {
                    Log.d("@@@@", "OK - reply code: " + ftp.getReplyCode());
                    FTPFile[] files = ftp.listFiles(Config.getImagesPath(thisSHahid.id));
                    Log.d("@@@@", "File count on server: " + files.length);
                    if (files != null && files.length > 0) {
                        data = new ArrayList<>();
                        for (FTPFile aFile : files) {
                            System.out.println(aFile.getName() + "::" + aFile.getLink());
                            ImageModel imageModel = new ImageModel();
                            imageModel.setName("تصویر " );
                            imageModel.setUrl(aFile.getName());
                            data.add(imageModel);
                        }
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            }

**Comment by TWiStErRob** [comment]
That's how you get the list I guess, so your model to register with Glide here is either FTPFile or ImageModel, so you can do `Glide.with(this).load(data.get(position))...`.

**Comment by abbasalim** [comment]
no, i dont know, thiw dont work , only show my code
