### ISSUE TITLE
Elevation flickering with animation

### ISSUE THREAD

**Issue by Pereck** [bumptech/glide#1415]
I use Glide 3.7.0 to load little images in ImageViews inside a recyclerview with a gridlayoutmanager. In any of imageviews i set an elevation of 3dp. with the Glide standard animation for image loading this shadow flicks and it disappears from some images. instead, if i call `.dontAnimate()` Glide loads well everything.

My imageview XML is this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="85dp"
    android:scaleType="fitCenter"
    android:background="#fff"
    android:padding="8dp"
    android:elevation="2dp">

</ImageView>
```

and i use glide in this way:
```java
public void onBindViewHolder(ViewHolder holder, int position) {
        int res = mThumbIds[position];
        ImageView i = (ImageView) holder.imageView;
        Glide.with(mContext).load(res).dontAnimate().fitCenter().into(i);
    }
```

If i remove `.dontAnimate()` the problem persists.

**Comment by TWiStErRob** [comment]
Huh... what are you loading?

Glide uses TransitionDrawable, which is disabled here, because you don't have placeholder nor thumbnail. Instead, an AlphaAnimation is used, see `DrawableCrossFadeFactory`.

**Comment by Pereck** [comment]
I'm loading png images in my imageviews. In these i must to set the background to white to enable the elevation attribute.

**Comment by TWiStErRob** [comment]
Is it transparent? Which: drawable/raw?

**Comment by Pereck** [comment]
Yes, they are transparent and are located in drawable directory

**Comment by Pereck** [comment]
I've checked the documentation, but i can't figure out how to use DrawableCrossFadeFactory. Sorry but i use Glide from 24 hours. Could you help me?

**Comment by TWiStErRob** [comment]
`.crossFade()` enables that factory. It's on by default. I just told you where to look in case you wanted to debug. I'll try it in a few days, I'm busy now.

**Comment by Pereck** [comment]
Thank you. For now i've made some test and in my opinion i got some useful information:
the problem depends by two factor:

1. The speed of scroolling: with the animation enabled if i scroll slowly the porblem doesn't show up;
2. The duration of animation as `crossFade(int duration)` parameter: more fast is the animation and more fast can be the scrolling;

i hope they can be helpful

**Comment by Pereck** [comment]
I got a solution! And it has been simple.

I have override the method `onViewDetachedFromWindow(ViewHolder holder)` in my Adapter class.

```java
@Override
    public void onViewDetachedFromWindow(ViewHolder holder) {
        holder.imageView.clearAnimation();
    }

```

**Comment by johninvictus** [comment]
I solve this issue by setting a defined dimensions on the ImageView

**Comment by tnaffh** [comment]
setting `iv.layout(0,0,0,0);` before Glide fixed it for me
