### ISSUE TITLE
in a certain period of time, all the pictures used to show the glide are white.

### ISSUE THREAD

**Issue by jjdxmashl** [bumptech/glide#1420]
**Glide Version**:3.71

**Integration libraries**:OkHttp3

**Device/Android Version**:   4.4.4

**Issue details / Repro steps / Use case background**: 
The use of the 3.7.1 version, found a problem, the emergence of sporadic problems, in a certain period of time, all the pictures used to show the glide are white. When this problem occurs, the use of multiple devices to test is the case. Did not capture the log, and then after a few minutes to go back to the test, the return to normal, is not a package in the use of network authentication?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with...
```

**Layout XML**:

``` xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:

``` ruby
paste stack trace and/or log here
```

**Comment by Teovald** [comment]
AFAIK there is no 3.7.1, do you mean 3.7.0 ?

It is hard to help you without more information, it sounds like you are maybe mishandling glide calls in a viewHolder.

Can you provide more information on how you use the lib ?

**Comment by TWiStErRob** [comment]
Yes, @jjdxmashl  please fill in the template fully.
