### ISSUE TITLE
Loading Gif figure, cause unlimited cache, lead to other image cannot be loaded,

### ISSUE THREAD

**Issue by hekaidaqaz** [bumptech/glide#1421]
Glide.with(getActivity()).load(activeEntity.getImgUrl()).placeholder(R.drawable.ads_place).error(R.drawable.ads_place).thumbnail( 0.1f ).crossFade().into(activeMap);

The above is my way of loading Gif images, to come in after launch, calculation of cache suddenly becomes other images can be loaded

**Comment by TWiStErRob** [comment]
Not sure what your problem is, I feel like you missed a "not" from your problem description.
Add `.diskCacheStrategy(SOURCE)` when loading GIFs, so they load much faster and don't waste space/resources. Search "Glide slow gif" for more.

**Comment by hekaidaqaz** [comment]
`Glide.with(this).load(activeEntity.getImgUrl()).placeholder(R.drawable.ads_place).error(R.drawable.ads_place).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(activeMap);`

Before "this" for "context" not set "DiskCacheStrategy. SOURCE". With the default Settings, cause I have been changes in the calculation of cache.
The end of the day, other than Gif images cannot be loaded.


And my GIF images are not necessarily GIF figure, so useless "asGif"

**Comment by TWiStErRob** [comment]
I agree, asGif doesn't help here, but SOURCE is independent of that and works with any image type. I was hoping GIFs were just slow.

Please try https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling. After that, please explain what's your problem, "cannot be loaded" is not a problem, but a generic statement.

If you have customized with GlideModule, please share that too.
