### ISSUE TITLE
Glide library issue of caching in android

### ISSUE THREAD

**Issue by shrawanshinde** [bumptech/glide#1422]
**Glide Version**: **glide-3.6.1.jar**

**Integration libraries**: **Volley**

**Device/Android Version**:  fails on HTC 4.1, moto E 5.1, oneplus 6.0, works fine on Sony Xperia

**Issue details / Repro steps / Use case background**:
Glide library load all the images from server, but I have an issue of the image caching. If I update new images on server, glide shows old images. Once clear cache or reinstall it again changes not reflected on app.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with(context).load(dataProducts.get("images")).into(holder.product_image);
```

**Layout XML**:

``` xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:

``` ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Normally, and image doesn't change at an url. If it does you need to change something about it to force a re-download. You can use `.signature()` to mix in some data (e.g. last modification date), Also take a look at `.diskCacheStrategy`, specifically `NONE` and it's companion `.skipMemoryCache`.

This really shouldn't behave different on different OSs, unless there's some SDK_INT or simlar check.

**Comment by shrawanshinde** [comment]
Thank you Róbert  but i used all possible ways like clear cache, reinstall app, and also used your way **"Glide.with(ProductDetails.this).load(images).signature(new StringSignature(String.valueOf(System.currentTimeMillis()))).into(ProImgView);"** but still issue in app

**Comment by TWiStErRob** [comment]
> i used all possible ways like clear cache, reinstall app [...] but still issue in app

Then the problem is not in Glide, but on your server; or you have Volley caching enabled.

Check out [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) to see which cache its hitting.

**Comment by shrawanshinde** [comment]
Yes volley caching is enabled

**Comment by TWiStErRob** [comment]
So I guess this is resolved then?
I don't think you need Volley caching AND Glide caching. One of them should be turned off fully, otherwise I image is taking up 2x space from the user. I personally wouldn't use Volley cache.
