### ISSUE TITLE
Glide 4.0 SNAPSHOT Image Caching

### ISSUE THREAD

**Issue by chipiimen** [bumptech/glide#1426]
How can I properly add signature for image caching in loading images from URL?

**Comment by TWiStErRob** [comment]
I think it's `.apply(RequestOptions.signatureOf(...))` or `.apply(new RequestOptions().signature(...)....)`.

**Comment by chipiimen** [comment]
Thanks

**Comment by chipiimen** [comment]
Hi Rob, Can you also give advise on this.

Issue: Avatar Image Caching, Server is giving the same avatar image url for every time user changed their avatar. Glide will still load the cache version.

What do you think is the best solution on how can I invalidate the cache?

Thanks

**Comment by TWiStErRob** [comment]
Add an avatarLastUpdated field to the user object on the server and send it down to clients. Use that with signature.

**Comment by chipiimen** [comment]
Thanks Rob. We had decided to change the URL instead.
