### ISSUE TITLE
first time load actual image from glide next time they load cache image with diffrent resoluation 

### ISSUE THREAD

**Issue by pawarlalit29** [bumptech/glide#1427]
first time load actual image from glide next time they load cache image with diffrent resoluation 

here is a cache image with different resolution size load at next time
![device-2016-08-24-145721](https://cloud.githubusercontent.com/assets/10419245/17925809/092141c2-6a0c-11e6-8bd7-09c7e0095aed.png)

here is a actual size image load at first time
![device-2016-08-24-145701](https://cloud.githubusercontent.com/assets/10419245/17925810/0924f4f2-6a0c-11e6-98e9-a445794bb1dd.png)

how can show same size of image at everytime

**Comment by TWiStErRob** [comment]
I think this may be #363, try `.dontAnimate()`. If it doesn't help please share your Glide line.

**Comment by pawarlalit29** [comment]
TWiStErRob (Róbert Papp) thanks for the help ,may be its working when i used the .dontAnimate()
