### ISSUE TITLE
Could not load local video thumbnails :  Mark has been invalidated

### ISSUE THREAD

**Issue by anilshar** [bumptech/glide#1428]
Please have a look. 

**Glide Version**: 3.7.0

**Device/Android Version**: Nexus 6p , Moto g

**Issue details / Repro steps / Use case background**: 

Could not load video thumbnail form local video, captured  from phone. 
I was getting the below exception every time I tried to display video thumbnail in my app. 
com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException: Mark has been invalidated 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java

 mRequestBuilder.load(imgPath).diskCacheStrategy(DiskCacheStrategy.RESULT).placeholder(R.color.lightest_grey) .crossFade(180).into(mImageView);

where mRequestBuilder = Glide.with(context)


```

**Comment by TWiStErRob** [comment]
Sounds like something read too much data before Glide was trying to rewind.
Can please you share a video file that does this? Hopefully a small/short one.
Also stack trace would also be part of a report about an exception... ;)
