### ISSUE TITLE
how to get ExifOrientation from URL image. 

### ISSUE THREAD

**Issue by chipiimen** [bumptech/glide#1429]
Problem: 
Server is sending the image urls (avatar image) in different orientation. Some are in correct orientation and sometimes is not.

Question:
In Glide 4.0, how can I check the orientation of the image coming from url?

Thanks

**Comment by TWiStErRob** [comment]
Glide handles EXIF orientations correctly by default. It may be worth fixing the server side in this case. How would you know programmatically whether the input JPEG is correctly oriented or not?

If you want to ignore you have to write your own data fetcher, see #665

**Comment by chipiimen** [comment]
Hi Rob, Thank you for your very fast response. I'm using my own data fetcher but I'm not sure why glide cannot parse the orientation of the image from the server. (always returns as -1)

 stream = new BufferedInputStream(httpEntity.getContent(), 8192);
 int orientation = new ImageHeaderParser(stream, Glide.get(context).getArrayPool()).getOrientation();

**Comment by TWiStErRob** [comment]
Can you give an example Url or a raw file?
(if you attach one, zip it first, because GitHub may re-encode it)

**Comment by chipiimen** [comment]
Now i was able to get the orientation value. Last time was -1 because image is not existing on the server.

Now i'm getting orientation value of 6 and 1, but I want to rotate all images with 6 orientation. How can you advise on this?

On my data fetcher, I will try to rotate the image before returning the inputstream. Do you think it is advisable?

 try {
                        stream = new BufferedInputStream(httpEntity.getContent(), 8192);
                        int orientation = new ImageHeaderParser(stream, Glide.get(context).getArrayPool()).getOrientation();

                        switch (orientation){
                            case ExifInterface.ORIENTATION_ROTATE_90:
                                Bitmap bm = BitmapFactory.decodeStream(stream);

                                Bitmap temp = TransformationUtils.rotateImage(bm, -90);
                                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                                temp.compress(Bitmap.CompressFormat.PNG, 0, bos);
                                byte[] bitmapdata = bos.toByteArray();
                                ByteArrayInputStream bs = new ByteArrayInputStream(bitmapdata);
                                stream = bs;
                                break;
                        }

                        dataCallback.onDataReady(stream);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

**Comment by TWiStErRob** [comment]
That's wasteful and slow. Just wrap your returned stream in ExifOrientationStream as described in #665, then Glide will do the rotating efficiently.

**Comment by chipiimen** [comment]
Thanks, I updated the code above. The sad thing is I have to check the orientation of the avatar once I am loading it.

Another thing is I am calling this fetcher asynchronously.

**Comment by TWiStErRob** [comment]
Wouldn't this yield the same result (without fully reading it into memory)?
```java
dataCallback.onDataReady(new ExifOrientationStream(httpEntity.getContent(), ExifInterface.ORIENTATION_NORMAL));
```
Do you want to leave other orientations (180, 270, flips) as is?

**Comment by chipiimen** [comment]
Yes I can leave other orientation as is. 

`dataCallback.onDataReady(new ExifOrientationStream(httpEntity.getContent(), ExifInterface.ORIENTATION_NORMAL));`

Yeah this would have different result as I need to consume the httpEntity twice which is not allowed right?
1. Get image orientation
 `int orientation = new ImageHeaderParser(httpEntity.getContent(), Glide.get(context).getArrayPool()).getOrientation();`
2. Wrap to ExifOrientation
 `dataCallback.onDataReady(new ExifOrientationStream(httpEntity.getContent(), ExifInterface.ORIENTATION_NORMAL));`

**Comment by TWiStErRob** [comment]
What I meant is to replace all your above code (the whole try-catch) with that single line. In the end you're mapping 90 rotation to 0 rotation. My proposal is to map everything to 0 rotation, that is to ignore any rotation given in the JPEG file. In this case you don't need to know the orientation, just blindly override it. The question is if this blindness is acceptable?

**Comment by chipiimen** [comment]
Thanks, I got what you mean but some images are in PNG format, so this wont work.

**Comment by TWiStErRob** [comment]
Ah, I see. You can use Java's `mark` to double-read the stream.
```java
InputStream stream = httpEntity.getContent();
if (response.isAvatar()) {
	stream = new BufferedInputStream(stream, 32 * 1024);
	stream.mark(1024); // ExifOrientationStream.ORIENTATION_POSITION would be enough, but be generous
	int orientation = new ImageHeaderParser(stream, Glide.get(context()).getArrayPool()).getOrientation();
	stream.reset();
	if (orientation == ExifInterface.ORIENTATION_ROTATE_90) {
		stream = new ExifOrientationStream(stream, ExifInterface.ORIENTATION_NORMAL);
	}
}
dataCallback.onDataReady(stream);
```

**Comment by chipiimen** [comment]
Thanks Rob :) This is way better.
