### ISSUE TITLE
Canceling requests lead to Okhttp DiskLruCache stops working

### ISSUE THREAD

**Issue by ralphhm** [bumptech/glide#1434]
**Glide Version**: 3.7.0
**OkHttp3 Version**: 3.0.1 (same for 3.4.1)

**Integration libraries**: okhttp3-1.4.0

**Device/Android Version**: Genymotion Google Nexus 6 5.0.0

**Issue details / Repro steps / Use case background**:
If Glide is used together with OkHttp disk cache instead of the Glide disk cache the cancelation mechanism (while scrolling through a list of images) of Glide leads to an Thread.interrupt(). If the thread is interrupted while OkHttp DiskLruCache is writing an entry to the disk it leads to a corruption of the file journal. OkHttp doesn't recover from this state until the app is restarted with the effect that caching stops working.
I don't know whether this problem should be solved on the Glide or OkHttp side. This is why I create issue tickets in both projects: You can find the related OkHttp issue ticket [here](https://github.com/square/okhttp/issues/2822)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

disable Glide disk cache in every request
```java
new GlideRequestBuilder(requestManager.load(url).diskCacheStrategy(DiskCacheStrategy.NONE));
```
enabling OkHttp disk cache in the GlideModule
```java
OkHttpClient.Builder builder = new OkHttpClient.Builder();
builder.cache(new Cache(new File(context.getCacheDir(), "okhttp_image_disk_cache"), DiskCache.Factory.DEFAULT_DISK_CACHE_SIZE));
glide.register(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(builder.build()));
```
The cancelation calling stack is as follows:
GenericRequest.cancel()
Engine$LoadStatus.cancel()
EngineJob.removeCallback()
EngineJob.cancel()
FutureTask.cancel()
Thread.interrupt()

**Comment by TWiStErRob** [comment]
At first glance OkHttp3 Cache handles failures correctly. InterruptedException is a checked exception, and there's no mention of it in Cache, so it must propagate up as an IOException which is handled by aborting the edit.

What is it that you see, what is "stops working"? I think if there's a problem its `DiskLruCache#completeEdit` not leaving in a consistent state whenever an `IOException` is thrown at any line. One thing to note is that `DiskLruCache` is used by Glide as well and that works? There is a difference between the two implementations.

**Comment by ralphhm** [comment]
@TWiStErRob thanks for the fast reply
You are right, DiskLruCache#completeEdit is executed. This executes BufferedSink#flush() which writes the buffer to the sink via Sink#write(). This write is interrupted with an InterruptedIOException. As I had a deeper look into the StackTrace of the exception it seems that there is a okio.Timeout causing the exception while writing. So I assume that this problem is not related to Glide and this issue ticket can be closed.

**Comment by TWiStErRob** [comment]
Just curious: What is the reason you're not using Glide's cache?

**Comment by ralphhm** [comment]
The new requirement is that an image that is changed in the filesystem on the image server (nginx that supports http caching and conditional requests out of the box) should be updated in a timely manner. As OkHttp supports http 1.1 caching we thought it's a good idea to use it's cache.
Jesse Wilson just [replied](https://github.com/square/okhttp/issues/2822#issuecomment-243408772) to my issue that OkHttp doesn't expect to be interrupted and thus break.
