### ISSUE TITLE
Glide not clearing cached images when leaving fragment, causing memory leak and eventual OOM

### ISSUE THREAD

**Issue by SeanOxford** [bumptech/glide#1436]
Glide Version:
`3.7.0`

Integration Library Implementation:
`compile ('com.github.bumptech.glide:okhttp3-integration:1.4.0'){
        exclude group: 'glide-parent'
    }}`

I am running into some serious memory leak issues with Glide. Whenever I go into a specific fragment (B) which contains a custom View (Card), which contains 3 other custom views(Front, Back, Back premium), of which I am using Glide to load images, I find that my memory keeps piling up as go back (A) and forth (B) through the two fragments, even if it's the same detail/URL loading. (However, it seems the memory stacks faster if I use different details, but same fragment class (B)).

This effect persists even if I use DiskCacheStrategy.NONE and skipDiskCache(true) on all cases in which I use Glide. I am currently using an injected Glide Module into my BaseFragment which uses the application's context. I have played around with using static Glide.with(fragment) implementations, but it did not seem to help, I'm willing to try again, though. I have also tried using clearMemory() (Threading with RxJava) and clearDiskCache() in my fragment's onStop() (just for debug purposes because I didn't fully trust onDestroy()), which seems to have no effect on my memory monitor clearing up space.

When I look through the java heap after building up the memory a bit using the method noted, it seems to be a pile-up of an object known as com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable$BitmapState. The bitmaps that are being loaded each time I enter Fragment B consist of between 1 - 5 "style" imagesets of 3 bitmaps per, which include a front card template, a back message template and a premium back template.

Please help, I'm running out of ideas :(

Heap analysis and Fragment images
http://imgur.com/a/WZABd

**Comment by TWiStErRob** [comment]
`Glide.with(fragment)` only works if the fragment is destroyed, maybe you're reusing the same Fragment B and it just keeps accumulating requests. You can always manually clear any `Target` or `ImageView` at a point where you see fit. Try to put `Glide.clear(...)` wherever you go back to Fragment A (onBackPressed, onStop, onDestroyView or even `OnBackStackChangedListener` for debugging's sake).

**Comment by SeanOxford** [comment]
I'm currently not using the fragment, but rather the ApplicationContext, but onDestroy() was being called within the fragment when I was and it was still leaking. I tried calling .clear(...) on all ImageViews being used with Glide in onStop(), but it did not do much. I added mImageView.setImageDrawable(null) in the same call and it seems to be piling up memory much slower. As I've commented out the image loading of an offscreen adapter I forgot about, the count of bitmapstates (107 in Leak Suspect part 2) has dropped even further than when I was just clearing the drawables in the other Glided ImageViews. I'm not sure what's happening exactly, but it appears Glide is still holding onto my ImageViews' bitmaps unless I free them up. Not sure if that's normal behavior, but no ImageViews are being leaked in my reports, only GlideBitmapDrawable$BitmapStates.

**Comment by TWiStErRob** [comment]
I know you're not using with fragment, I was just trying to point it why it may have not helped when you tried.

Maybe those are held in the memory cache which may be too big for your app. Try to disable it in your Glide module: there's an adapter implementation that does nothing to test or set a lower size.

Most of the time I use [LoggingTarget](https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/utils/LoggingTarget.java) to see what is/not being cleared.

Are you using `.placeholder(iv.getDrawable())` by any chance?

**Comment by sjudd** [comment]
All of the references in your heap are weak. When you're looking for reference chains, use the exclude weak references part. If manually setting the image drawable to null helps, it sounds a lot like you are in fact leaking views.

**Comment by SeanOxford** [comment]
> it sounds a lot like you are in fact leaking views.

I, in fact, was. Sorry everyone!

**Comment by YaphetZhao** [comment]
Other version has this problem?

**Comment by TWiStErRob** [comment]
@YaphetZhao no version has this problem, it was a user error.
