### ISSUE TITLE
Non-2xx responses leak connections with OkHttp integrations

### ISSUE THREAD

**Issue by JakeWharton** [bumptech/glide#1441]
In both the OkHttp 2 and OkHttp 3 integrations on `master`, the `ResponseBody` is not closed when `isSuccessful()` is `false` (aka non-2xx response). The `else` branch should immediately call `response.body().close()` or at the very least set the `responseBody` field for later closing (the former seems more logical).

**Comment by TWiStErRob** [comment]
Good catch, in v3 the sync version assigned `responseBody` every time.
