### ISSUE TITLE
Blurry image with match_parent for width.

### ISSUE THREAD

**Issue by vxhviet** [bumptech/glide#1448]
**Glide Version**: 3.7.0

**Integration libraries**: None

**Device/Android Version**: Issue appears on Nexus 5 (6.0.1), Galaxy S6 (6.0.1), Oppo F1w (5.1.1).

**Issue details / Repro steps / Use case background**: 

- When I'm trying to load my pre-blurred image into an `ImageView` with `match_parent ` for width, the image shows up with a blurry, smearing pattern (this pre-blurred image's dimension is 600*200 pixels):

![glide_match_parent_no_override](http://i.imgur.com/MAIX87H.png "glide_match_parent_no_override") 

The loading code: 

```java
Glide.with(child.getImgPhoto().getContext())
                 .load(item.getHeaderUrl())
                 .placeholder(new ColorDrawable(ContextCompat.getColor(child.getImgPhoto().getContext(), R.color.dark_gray)))
                 .into(child.getImgHeader());
```

- However this works fine with Picasso:

![picasso_match_parent](http://i.imgur.com/nrHLYa3.png "picasso_match_parent")

```java
Picasso.with(child.getImgPhoto().getContext())
                    .load(item.getHeaderUrl())
                    .placeholder(new ColorDrawable(ContextCompat.getColor(child.getImgPhoto().getContext(), R.color.dark_gray)))
                    .into(child.getImgHeader());
```

This is one item of our vertical `RecyclerView`, the layout is as the following:

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_vertical">

        <ImageView
            android:id="@+id/img_header"
            android:layout_width="match_parent"
            android:layout_height="72dp"
            android:adjustViewBounds="true"
            android:scaleType="centerCrop" />
      ...
</RelativeLayout>
```

- I've try the solutions suggested in issue #1227 and issue #531 but it doesn't seem to take any effect:

```java
Glide.with(child.getImgPhoto().getContext())
                 .load(item.getHeaderUrl())
                 .override(600, 200)  //original image's size
                 .dontTransform()
                 .placeholder(new ColorDrawable(ContextCompat.getColor(child.getImgPhoto().getContext(), R.color.dark_gray)))
                 .into(child.getImgHeader());
```

and

```java
Glide.with(child.getImgPhoto().getContext())
                 .load(item.getHeaderUrl())
                 .override(512, 128)  //resizing to 2's powers
                 .dontTransform()
                 .placeholder(new ColorDrawable(ContextCompat.getColor(child.getImgPhoto().getContext(), R.color.dark_gray)))
                 .into(child.getImgHeader());
```

with a fixed layout width's:

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_vertical">

        <ImageView
            android:id="@+id/img_header"
            android:layout_width="300dp"
            android:layout_height="72dp"
            android:adjustViewBounds="true"
            android:scaleType="centerCrop" />
      ...
</RelativeLayout>
```

still give me this:

![glide_300dp_512_128](http://i.imgur.com/DGVDWa0.png)

- I have been using the Picasso work around up until now, but Picasso takes way too much memory that cause serious problem for lower end devices so I would love to completely switch to Glide.

Any input if highly appreciated, thank you for your time.

**Comment by vxhviet** [comment]
Sorry, problem solved. I didn't think the lower quality (RGB_565) could cause this kind of smearing so I haven't tested this before. 

In short, we just need to use the higher quality and the image displays perfectly. I put down the code for anyone need it:

```java
Glide.with(child.getImgPhoto().getContext())
                 .load(item.getHeaderUrl())
                 .asBitmap()
                 .format(DecodeFormat.PREFER_ARGB_8888)
                 .placeholder(new ColorDrawable(ContextCompat.getColor(child.getImgPhoto().getContext(), R.color.dark_gray)))
                 .into(child.getImgHeader());
```

Still need to do a bit of memory testing though.

**Comment by TWiStErRob** [comment]
Yep, that's the usual banding of low bit width. Just remember how 24bit images looked on a 256-color screen (if you're old enough). 565 is just 16 bits.
