### ISSUE TITLE
Qustion) Android Add glideLibrary to my project. Why should I get an error?

### ISSUE THREAD

**Issue by man2845** [bumptech/glide#1450]
I want Add glide Library to my project so I added the code. The first project succeeded in applying. but, next project Android has displayed an error text. and not create the support-v4 file. Even though the same version! I tried changing the version to continue. But it was unsuccessful. Why this message is being output? How can I use the glide library?

ps. code apply plugin: 'org.robolectric' is in gif_decoder\bulid.gradle.

**Code**

```gradle
apply plugin: 'com.android.application'
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        applicationId "com.abcd.abcd.abcd"
        minSdkVersion 10
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions.encoding = 'UTF-8'

    repositories {  //this
        mavenCentral() // jcenter() works as well because it pulls from Maven Central
    }

    dependencies {  
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.12'
        compile 'com.github.bumptech.glide:glide:3.7.0'  //this
        compile 'com.android.support:support-v4:24.2.0'  //this
    }
}
```

**Error text**
```
Error:(2, 0) Plugin with id 'org.robolectric' not found.

Error:(2, 1) A problem occurred evaluating project ':third_party:gif_decoder'.
> Plugin with id 'org.robolectric' not found.
```
and
```
Error:(5, 0) Could not get unknown property 'SUPPORT_V4_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by TWiStErRob** [comment]
What's in your `libs` folder? You don't need the sources/custom compiled version to use Glide, just that single `compile ...` line. Even if you're using one of the samples in this repository, copy them to a separate independent folder and remove dependencies on Glide source code.

Tip: Runnig gradle from command line: `gradlew --stacktrace` outputs the exact file location of the error.

**Comment by man2845** [comment]
thank you! I solved the problem with the help.  Big Thanks
