### ISSUE TITLE
I delete Glide cache on the phone file ,then Glide cann't load picture to ImageView;

### ISSUE THREAD

**Issue by yudehai0204** [bumptech/glide#1451]
this is my code;
```java
getCache.DeleteFile(new File(ConstantsYiBaiSong.IMAGE_CACHE_PATH));
			SharedPreferences loginShare = getSharedPreferences("loginName",
					Context.MODE_PRIVATE);
			new Thread(new Runnable() {
				@Override
				public void run() {
					Glide.get(MeSettingActivity.this).clearDiskCache();
				}
			}).start();
			Glide.get(this).clearMemory();
			Editor editor = loginShare.edit();
			editor.putString("nameString", "");
			editor.putString("pswString", "");
			editor.commit();
```

then  the Activity load image still use disk cache, but the file is delete  so load fail; 
I want know  , has methed let glide back to the initial state ?
My English is so poor; Please Forgive me. Thanks.

**Comment by TWiStErRob** [comment]
Yes, `clearDiskCache` is the way. It looks like `DeleteFile` also deletes the cache directory, that's not good. DiskLruCache doesn't like if external parties mess with their files.

**Comment by yudehai0204** [comment]
so I need single create a File Folder  let Glide DiskCache use ?

**Comment by TWiStErRob** [comment]
Just don't delete files manually from Glide's cache directory. Use the `clearDiskCache` method to clear the cache.

**Comment by yudehai0204** [comment]
yeah ! I know . Thank you.

**Comment by TWiStErRob** [comment]
Did it fix your problem?

**Comment by yudehai0204** [comment]
Yeah   , perfect solution .
