### ISSUE TITLE
Glide doesn't load image from local storage

### ISSUE THREAD

**Issue by MostafaNasiri** [bumptech/glide#1452]
I want to load an image file which is stored in app's directory with the path below:
`/data/data/ir.sohreco.ghesseyema/files/contents/photo_2016-04-19_22-47-08.jpg`
And i load image like this:

```
Glide.with(getApplicationContext())
                    .load(photoFile)
                    .into(ivStoryPhoto);
```

But it doesn't show anything in the imageview!
Any idea?

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
