### ISSUE TITLE
import this project android stuido  Error:Configuration with name 'default' not found.  this is why?

### ISSUE THREAD

**Issue by maolvxiansheng** [bumptech/glide#1453]

**Comment by TWiStErRob** [comment]
It really depends on what you did to achieve that error message. It usually means there's a module in `settings.gradle` whose directory doesn't contain a `build.gradle` file. 
Did you follow the steps at https://github.com/bumptech/glide#build?

**Comment by maolvxiansheng** [comment]
thanks ,but i not doing Anything ,only downed the version 3.7.0 source code ziphttps://github.com/bumptech/glide/releases  ,after import the project  ,i need other anything? thanks

**Comment by maolvxiansheng** [comment]
I want to get a picture of the URL, the url.host will be modified into my own IP DNS, set the request of the Host header field for url.host, my approach is to add
Glide.register (GlideUrl.class, InputStream.class, OkHttpUrlLoader.Factory new ());
In their own OkHttpUrlLoader to get to the Request.Builder, and then add Host for the Header field, but the result is wrong, I add the Host field does not exist, the request is wrong, how do I do it?

**Comment by TWiStErRob** [comment]
> only downed the version 3.7.0 source code zip

That's exactly what I was looking for. If you don't say what you did, it's hard to help. There are multiple branches, and tags. It all depends on which one you're dealing with.
 
You need the submodules as shown at https://github.com/bumptech/glide/tree/3.0#build; if you don't want to use `git`, then read the `.gitmodules` file and download those repositories too into their folders given by `path = `.

I suggest making it compile from command line first with `gradlew build`, and only after that worked, import it in Android Studio.

**Comment by TWiStErRob** [comment]
Oh man, [beautiful example of the XY problem](http://meta.stackexchange.com/q/66377/247470)...
Try one of these: https://www.google.com/search?q=glide%20add%20headers.

http://stackoverflow.com/a/30327461/253468 is the best IMO, because it doesn't require any integration libraries.

Your problem with OkHttp is probably that you [didn't reference the `@jar` version (or excluded the meta)](https://github.com/bumptech/glide/wiki/Integration-Libraries#overriding-default-behaviour), so there are two `GlideModule`s registering for `GlideUrl.class`: yours and the one automatically merged by the manifest merger from the `okhttp-integration.aar`; the latter won in your case. Check your `build\intermediates\manifests\full\debug\AndroidManifest.xml` for `GlideModule` metas.

**Comment by maolvxiansheng** [comment]
Hi, I do it in your way, but my headers is not the field I add, Host this field is still his default instead of I add, this is why, my URL is https,These methods are not valid .http://stackoverflow.com/a/30327461/253468

**Comment by TWiStErRob** [comment]
You know what, let's start with a clean slate. Imagine we never spoke, please describe your Glide related logic (with relevant code samples: GlideModule, Glide load line, any customizations to Glide). [This](https://raw.githubusercontent.com/bumptech/glide/master/ISSUE_TEMPLATE.md) can guide you with questions to answer.

**Comment by maolvxiansheng** [comment]
OK, my new approach is: to glide a URL, and then to set up a new field for the Host Header, but glide seems to be the default one such field, I add in Header Host and no effect, I saw the pictures or the original request Header has not changed. I was using this method
GlideUrl GlideUrl = GlideUrl new ("myURL", LazyHeaders.Builder new ()
.addHeader ("Host", "new host  is not   myURL.host")
.build ());
Glide....load (glideUrl)..;

But Header did not change

**Comment by TWiStErRob** [comment]
Look, I really can't help you if you don't give me anything to work with.

Here's what I did: I have a local XAMPP server with Apache inside. It's available at `localhost`, and I can access it from within the local network at `1.1.1.15`. This server has an invalid SSL certificate. For this reason I copied http://stackoverflow.com/a/26456106/253468 just before the following code and put it in an app:
```java
GlideUrl glideUrl = new GlideUrl("https://1.1.1.15/glide", new LazyHeaders.Builder()
				.addHeader("Host", "something.else")
				.build());

Glide.with(this).load(glideUrl).listener(...).into(imageView);
```

The result:
on the server side on my laptop:
```
access.log:
1.1.1.19 - - [06/Sep/2016:15:56:33 +0200] "GET /glide HTTP/1.1" 400 980
forensic.log:
+16056:57cecb11:0|GET /glide HTTP/1.1|User-Agent:Dalvik/2.1.0 (Linux; U; Android 5.0; SM-G900FD Build/LRX21T)|Host:something.else|Accept-Encoding:identity|Connection:Keep-Alive
-16056:57cecb11:0 
```
in the android app:
```
listener.onException(java.io.IOException: Request failed 400: Bad Request, https://1.1.1.15/glide
   LazyHeaders{headers={Host=[StringHeaderFactory{value='something.else'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 5.0; SM-G900FD Build/LRX21T)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, LoggingTarget@44fdf58, first)
   java.io.IOException: Request failed 400: Bad Request
       at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:90)
       at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:44)
       at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:20)
...
```
as you can see the server received the `Host` header correctly, and responded with a HTTP 400 which is propagated nicely to the Glide listener.
