### ISSUE TITLE
Glide doesn't load images in slow connections

### ISSUE THREAD

**Issue by Beni84** [bumptech/glide#1454]
We are using Glide library to download server images. We've always tested our app with wifi and work well.  But, we have a report which say images don't load in slow connection. I have tried to reply this bug and I have changed my mobile network connection to 2G to limit the bandwidth. The app doesn't load the images (200 x 200 px). 

We've tried this behavior in other project which is using Glide with OkHttp and works. But, if we remove the OkHttp instance for Glide has the same problem.

We have tried other two libraries (Picasso and Aquery). Those libraries have the same behavior and load the images at the same time as expected.

**Glide Version**:

Glide version we are using is glide:3.7.0 and glide:3.6.1

**Integration libraries**:
For default, we aren't using any integration libraries. But if we use OkHttp library, Glide can load images.

**Device/Android Version**:

My device is a Nexus 5 (6.0.1) 

I attach an Android demo project with a basic Glide configuration to load a 58x58px image 
[GlideTest.zip](https://github.com/bumptech/glide/files/457162/GlideTest.zip)

**Comment by TWiStErRob** [comment]
The default timeout in Glide is [2500ms](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java#L66), if the server doesn't respond it that time, or doesn't send data for longer than that, Glide cancels and errors. [OkHttp probably has different defaults.](http://stackoverflow.com/a/34088015/253468).
