### ISSUE TITLE
have Conflict with netty

### ISSUE THREAD

**Issue by 751811032** [bumptech/glide#1455]
I use glide 3.7.0 and 3.6.0, it have Conflict with netty (compile 'io.netty:netty-all:5.0.0.Alpha2').
It will error when Compile if haven't set "multiDexEnabled true".
If set "multiDexEnabled true". It wiil error when Runtime with netty can't found.

**Comment by TWiStErRob** [comment]
What's the error? Are you over 65k dex limit?

**Comment by 751811032** [comment]
java.lang.NoClassDefFoundError: io.netty.util.internal.TypeParameterMatcher.  not over 65k dex limit

**Comment by TWiStErRob** [comment]
And the compile error?

**Comment by 751811032** [comment]
no, Runtime error

**Comment by 751811032** [comment]
if not add glide,it run well, if add glide, it will have Runtime error

**Comment by TWiStErRob** [comment]
> It will error when Compile

You said, what's that?

**Comment by 751811032** [comment]
add glide it will show this error when Compile:
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\java\jdk\bin\java.exe'' finished with non-zero exit value 2

so I write build.gradle like this:
defaultConfig {
        multiDexEnabled true
}
it will compile succeed. but will have Runtime error
