### ISSUE TITLE
CenterCrop Scaling issue with placeholder

### ISSUE THREAD

**Issue by camillebeaumont** [bumptech/glide#1456]
**Glide Version**: 3.7.0

**Device/Android Version**: Nexus 6 6.0.1, Emulator Nexus 5X 6.0, Samsung SM-T230 4.4.2 (I suppose any devices)

**Issue details / Repro steps / Use case background**: 

I see many issues with centerCrop problems. None of them seem to correspond with this. I've a recyclerView with Cardview. Each card contains text + image. Image is matching parent width and fix height. ScaleType (centerCrop) is define in XML.

The problem is that there is distortion for all images on first load. Then on refresh (for example, scrolling down to recycle views or quit and relaunch activity, image are correctly scaled. I found that the distortion come from adding a placeholder. If I remove the placeholder line, there is no problem. 

```java
			Glide.with(context)
					.load(item.getPhoto())
					.placeholder(R.drawable.same_size_placeholder) 
					.diskCacheStrategy(DiskCacheStrategy.SOURCE)
					.into(holder.getPicture());
```

To investigate further, I make a sample with images all the same size, and make a placeholder with the exact same size but the distortion is still present. (I use a grid-pattern image to see correctly the issue). (See attached and github)

Please correctly kill app and clear cache to test it.

When commenting placeholder line, Glide work perfectly. (For simplification, I use images in drawable but it the same with url)
https://github.com/camillebeaumont/GlidePlaceholderTest

**First loading**: 
![screenshot_20160907-152229](https://cloud.githubusercontent.com/assets/7327604/18313631/e78de376-750f-11e6-992f-c7f4accd2c98.png)

**After Refresh**: 
![screenshot_20160907-152232](https://cloud.githubusercontent.com/assets/7327604/18313647/f3d668ec-750f-11e6-90ee-0d7f61db7d54.png)

**Comment by camillebeaumont** [comment]
My bad! I commit the wrong file... 
![giphy 45](https://cloud.githubusercontent.com/assets/7327604/18344669/856ff130-75b8-11e6-9246-c99b246dff95.gif)


Thanks for the tip, didn't think I could be a Android issue. Thanks for the ```.dontAnimate()``` fix, it work as a charm :)

**Comment by TWiStErRob** [comment]
Give a spin for the `thumbnail` version as well, because in that case the animation should work correctly. It's nicer on the eye.

**Comment by dishantkawatra** [comment]
Glide.with(mActivity)
                    .load(imageUrl)
                    .apply(new RequestOptions().dontTransform().placeholder(placeholder))
                    .into(imageView);

Glide version 4.8.0 after this code i solved my issue

**Comment by MahdiAbbasian** [comment]
> Naming it `same_size_placeholder` won't make it the same size, you actually have to resize it ;)
> The problem is that the input images (even after cropping) have a different aspect ratio than the placeholder drawable. Glide doesn't apply centerCrop to the placeholder and the enabled-by-default crossFade animation using Android's `TransitionDrawable` doesn't support different aspects: #363.
> 
> You can either use `.dontAnimate()` or change `.placeholder(X)` to `.thumbnail(Glide.with(context).load(X).centerCrop())` to force a transformation. This may leave a little delay during the list first showing, but after that it should be the same as `.placeholder()` until the memory cache keeps that image.

Thank you so much my issue with this solution solved.
