### ISSUE TITLE
placeholder and error method are not found

### ISSUE THREAD

**Issue by chihau** [bumptech/glide#1462]
I would try the placeholder and error methods but this methods are not found when I am trying to use them in my Android Studio project. 

The error message is "Cannot resolve method error(int)" and "Cannot resolve method placeholder(int)"

I am using glide 3.7.0

**Comment by TWiStErRob** [comment]
A little more code would probably help here.
Did you start with `Glide.with(this).load(blah)` or `Glide.with(this).fromString()`?
