### ISSUE TITLE
Error:Failed to resolve: glide-parent.third_party:gif decoder:unspecified

### ISSUE THREAD

**Issue by jakingting** [bumptech/glide#1464]
**Glide Version**: 4.0.0-SNAPSHOT

**Integration libraries**: doesn't matter

**Device/Android Version**: doesn't matter, build error

**Issue details / Repro steps / Use case background**: 
Since today our gradle build started giving errors.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```gradle
compile 'com.github.bumptech.glide:glide:4.0.0-SNAPSHOT'
```

**Stack trace / LogCat**:
```
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_P003DebugCompile'.
   > Could not find glide-parent.third_party:gif_decoder:unspecified.
     Searched in the following locations:
         file:/D:/jakingting/android/Android Studio/gradle/m2repository/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.pom
         file:/D:/jakingting/android/Android Studio/gradle/m2repository/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.jar
         https://jcenter.bintray.com/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.pom
         https://jcenter.bintray.com/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.jar
         https://jitpack.io/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.pom
         https://jitpack.io/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.jar
         http://oss.sonatype.org/content/repositories/snapshots/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.pom
         http://oss.sonatype.org/content/repositories/snapshots/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.jar
         file:/D:/jakingting/android/sdk/extras/android/m2repository/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.pom
         file:/D:/jakingting/android/sdk/extras/android/m2repository/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.jar
         file:/D:/jakingting/android/sdk/extras/google/m2repository/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.pom
         file:/D:/jakingting/android/sdk/extras/google/m2repository/glide-parent/third_party/gif_decoder/unspecified/gif_decoder-unspecified.jar
     Required by:
         code:app:unspecified > com.github.bumptech.glide:glide:4.0.0-SNAPSHOT
```

**Comment by jacklydoudou** [comment]
me too, make me crazy~~~~~~~~

**Comment by jacklydoudou** [comment]
need help~
This is the Msg:

Error:Could not find glide-parent.third_party:gif_decoder:unspecified.
Required by:
    GGF:app:unspecified > com.github.bumptech.glide:glide:4.0.0-SNAPSHOT
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by jacklydoudou** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/github/bumptech/glide/glide/4.0.0-SNAPSHOT/glide-4.0.0-20160912.001439-203.pom

is there sth wrong in the "<dependencies>....</dependencies>"?

**Comment by jakingting** [comment]
how to resolve?thx!

**Comment by jacklydoudou** [comment]
@jakingting 不知道啊,看似是他们的Pom文件写错了, 比较了上几个版本,就这个版本的 dependencies节点关于GifCoder的修改了,在12号的凌晨,目测得等他们起床,毕竟有时差~~~~5555555555555555555

**Comment by jakingting** [comment]
666666

**Comment by Ashok-Varma** [comment]
same issue here

**Comment by jacklydoudou** [comment]
@TWiStErRob

**Comment by alinturcu** [comment]
Is there any workaround for this? Excluding the dependency doesn't solve the issue

**Comment by jipeprojects** [comment]
Same issue here.

**Comment by nifhel** [comment]
Maybe using the @aar from here? https://oss.sonatype.org/content/repositories/snapshots/com/github/bumptech/glide/glide/4.0.0-SNAPSHOT/

**Comment by TWiStErRob** [comment]
*Morning everyone... don't be so impatient, you know there're time zones...
Even if the problem is so apparent, I would suggest to fill in the issue details, which I updated now it helps others to find the issue and to faster diagnose it as well.*

Yes, it seems it was broken a few hours ago. There are two workarounds, both work with integration libraries as well.

@alinturcu, yes it does, you can use a similar technique as described in #941 for this as well:
```gradle
dependencies {
    compile ('com.github.bumptech.glide:glide:4.0.0-SNAPSHOT') {
        // for some reason this is not enough
        //exclude group: 'glide-parent.third_party', module: 'gif_decoder'
    }
    // if you need GIF support, you need re-include that module too:
    compile 'com.github.bumptech.glide:gifdecoder:1.0.0-SNAPSHOT'
}
// but you need adding
configurations {
	compile.exclude group: 'glide-parent.third_party', module: 'gif_decoder'
}
```

--- 
**A simpler workaround**: since [Gradle 2.4](https://docs.gradle.org/2.4/release-notes#depending-on-a-particular-maven-snapshot-version) you can just revert to the previous version until there's a fix:
```gradle
// the broken build is 4.0.0-20160912.001439-203 and probably 4.0.0-...-204 will be fixed again
compile 'com.github.bumptech.glide:glide:4.0.0-20160905.222409-202'
```

**Comment by jacklydoudou** [comment]
compile 'com.github.bumptech.glide:glide:4.0.0-20160905.222409-202' 

useful and simple~ thx~

**Comment by jakingting** [comment]
resolve and thx

**Comment by alinturcu** [comment]
Tnx @TWiStErRob ! Works!
