### ISSUE TITLE
I give the imageview setTag and getTag,When I click the iamge have a bug

### ISSUE THREAD

**Issue by LcTerry** [bumptech/glide#1466]
In my project ,the listview item which includ a gridView，in the gridview item I use http://stackoverflow.com/a/35096552/253468  this to deal with the tag  !  the imageview show good,but When i give the gridview a OnItemClick to brower the pictures,but the datas it confusion！looks like: when i click the third item，show good, but when then to click the first! It's also show the third item datas!     please give me help!

**Comment by TWiStErRob** [comment]
You're probably sending the wrong position somewhere. Without code I can't help you much.

**Comment by LcTerry** [comment]
@TWiStErRob here is the Gridview code! `private LayoutInflater mLayoutInflater;
    List<WorkShowImgs>  files;
    long nodeId;
    StudentWorkShowActivity context;
    public WorkShowAdapter(StudentWorkShowActivity context, List<WorkShowImgs> files, long nodeId) {
        this.files = files;
        this.nodeId=nodeId;
        this.context=context;
        mLayoutInflater = LayoutInflater.from(CustomApplication.getContext());
    }

    @Override
    public int getCount() {
        return files == null ? 0 : files.size();
    }

    @Override
    public WorkShowImgs getItem(int position) {
        return files.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        ViewHolder holder;
        if (convertView == null) {
            holder = new ViewHolder();
            convertView = mLayoutInflater.inflate(R.layout.item_gridview_circle, parent, false);
            holder.imageView = (ImageView) convertView.findViewById(R.id.album_image);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }
        // 根据屏幕宽度动态设置图片宽高
        int width = DisplayUtils.getWidth(CustomApplication.getContext());
        int imageWidth = (width / 4 - 60);
        LayoutParams lp = holder.imageView.getLayoutParams();
        lp.width = imageWidth;
        lp.height = imageWidth;
        holder.imageView.setLayoutParams(lp);
        WorkShowImgs infosBean=getItem(position);
        String localPath = CourseUtils.getCourseImgePath(nodeId+"", infosBean.getAttachmentId());
        if(localPath==null) {
            //get the net
            ImageLoaderUtils.showImage(context,NetworkUrlConstants.getDownloadUrl(infosBean.getAttachmentId()),holder.imageView,infosBean.getAttachmentId(),nodeId+"",false);
        }else {
            //get local
            holder.imageView.setBackgroundResource(R.drawable.time_back);
            CourseUtils.displayImagePath(context,nodeId+"", infosBean.getAttachmentId(),  holder.imageView);
        }
        return convertView;
    }

    private static class ViewHolder {
        ImageView imageView;
    }`  
and Iset the Gridview click event in the listviewAdapter ` holder.gridView.setAdapter(new WorkShowAdapter(mContext,workShowImgs, nodeId));
            holder.gridView.setOnItemClickListener(((parent1, view, position1, id) -> {
                ImageUtils.imageBrower(mContext, imageUrls, position1);
            }));`

**Comment by LcTerry** [comment]
@TWiStErRob Here is the GridView code  

`private LayoutInflater mLayoutInflater;
    List<WorkShowImgs>  files;
    long nodeId;
    StudentWorkShowActivity context;
    public WorkShowAdapter(StudentWorkShowActivity context, List<WorkShowImgs> files, long nodeId) {
        this.files = files;
        this.nodeId=nodeId;
        this.context=context;
        mLayoutInflater = LayoutInflater.from(CustomApplication.getContext());
    }

    @Override
    public int getCount() {
        return files == null ? 0 : files.size();
    }

    @Override
    public WorkShowImgs getItem(int position) {
        return files.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        ViewHolder holder;
        if (convertView == null) {
            holder = new ViewHolder();
            convertView = mLayoutInflater.inflate(R.layout.item_gridview_circle, parent, false);
            holder.imageView = (ImageView) convertView.findViewById(R.id.album_image);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }
        // 根据屏幕宽度动态设置图片宽高
        int width = DisplayUtils.getWidth(CustomApplication.getContext());
        int imageWidth = (width / 4 - 60);
        LayoutParams lp = holder.imageView.getLayoutParams();
        lp.width = imageWidth;
        lp.height = imageWidth;
        holder.imageView.setLayoutParams(lp);
        WorkShowImgs infosBean=getItem(position);
        String localPath = CourseUtils.getCourseImgePath(nodeId+"", infosBean.getAttachmentId());
        if(localPath==null) {
            //get the net
            ImageLoaderUtils.showImage(context,NetworkUrlConstants.getDownloadUrl(infosBean.getAttachmentId()),holder.imageView,infosBean.getAttachmentId(),nodeId+"",false);
        }else {
            //get local
            holder.imageView.setBackgroundResource(R.drawable.time_back);
            CourseUtils.displayImagePath(context,nodeId+"", infosBean.getAttachmentId(),  holder.imageView);
        }
        return convertView;
    }

    private static class ViewHolder {
        ImageView imageView;
    }`

and I set the gridview clickevent in the listViewAdapter  

` holder.gridView.setAdapter(new WorkShowAdapter(mContext,workShowImgs, nodeId));
            holder.gridView.setOnItemClickListener(((parent1, view, position1, id) -> {
                ImageUtils.imageBrower(mContext, imageUrls, position1);
            }));`

**Comment by TWiStErRob** [comment]
Are the two lists `workShowImgs` and `imageUrls` correspond to each other 1:1?

Some tips: I suggest you change the variable type of `context` to `Context`, because you don't seem to use the fact that it's an activity. Similarly, since you already have a `context`, why are you using `CustomApplication.getContext()` twice over?

**Comment by LcTerry** [comment]
the iamgeUrls is only the url, which from the bean workShowImgs ` imageUrls.clear();
            for (WorkShowImgs data : workShowImgs) {
                imageUrls.add(NetworkUrlConstants.getDownloadUrl(data.getAttachmentId()));
            }`
no this correspond !    thank you for u tips!

**Comment by LcTerry** [comment]
i give the logger in listview  ` holder.gridView.setOnItemClickListener(((parent1, view, position1, id) -> {
                Logger.d(imageUrls.size() + "########imageUrls.size()##########");
                for (String str : imageUrls) {
                    Logger.d(str + "######str######");
                }
                ImageUtils.imageBrower(mContext, imageUrls, position1);
            }));`
then  I click the second item,and then to click first item!
here is the Logger  

 `09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ║ StudentWorkShowAdapter.access$lambda$0  (StudentWorkShowAdapter.java:-1)
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ║    StudentWorkShowAdapter.lambda$getView$91  (StudentWorkShowAdapter.java:123)
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ╟────────────────────────────────────────────────────────────────────────────────────────
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ║ 1########imageUrls.size()##########
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ╚════════════════════════════════════════════════════════════════════════════════════════
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ╔════════════════════════════════════════════════════════════════════════════════════════
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ║ Thread: main
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ╟────────────────────────────────────────────────────────────────────────────────────────
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ║ StudentWorkShowAdapter.access$lambda$0  (StudentWorkShowAdapter.java:-1)
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ║    StudentWorkShowAdapter.lambda$getView$91  (StudentWorkShowAdapter.java:125)
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ╟────────────────────────────────────────────────────────────────────────────────────────
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ║ http://192.168.0.128:6001/p/main/download_file/KdjyFileSystem1_b9eb7a35-8c13-4648-8ee1-de45cf6dd7ad.jpg######str######
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ╚════════════════════════════════════════════════════════════════════════════════════════
09-13 20:02:50.338 4312-4312/io.itit.ititeducation D/ITIT: ╔════════════════════════════════════════════════════════════════════════════════════════
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ║ Thread: main
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ╟────────────────────────────────────────────────────────────────────────────────────────
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ║ StudentWorkShowAdapter.access$lambda$0  (StudentWorkShowAdapter.java:-1)
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ║    StudentWorkShowAdapter.lambda$getView$91  (StudentWorkShowAdapter.java:123)
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ╟────────────────────────────────────────────────────────────────────────────────────────
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ║ 1########imageUrls.size()##########
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ╚════════════════════════════════════════════════════════════════════════════════════════
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ╔════════════════════════════════════════════════════════════════════════════════════════
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ║ Thread: main
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ╟────────────────────────────────────────────────────────────────────────────────────────
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ║ StudentWorkShowAdapter.access$lambda$0  (StudentWorkShowAdapter.java:-1)
09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ║    StudentWorkShowAdapter.lambda$getView$91  (StudentWorkShowAdapter.java:125)
09-13 20:02:50.358 4312-4312/io.itit.ititeducation D/ITIT: ╟────────────────────────────────────────────────────────────────────────────────────────
09-13 20:02:50.358 4312-4312/io.itit.ititeducation D/ITIT: ║ http://192.168.0.128:6001/p/main/download_file/KdjyFileSystem1_b9eb7a35-8c13-4648-8ee1-de45cf6dd7ad.jpg######str######`
I guess u method which give the tag have a effect on the listview????? 

my listview code 
` List<StudentWorkShowInfo.DataBean.InfosListBean> data;
    private StudentWorkShowActivity mContext;
    ArrayList<String> imageUrls = new ArrayList<>();
    long nodeId;
    int status;

    public StudentWorkShowAdapter(List<StudentWorkShowInfo.DataBean.InfosListBean> data, Context context, long nodeId, int status) {
        this.data = data;
        this.mContext = (StudentWorkShowActivity) context;
        this.nodeId = nodeId;
        this.status = status;

    }

    @Override
    public int getCount() {
        if (data != null && data.size() > 0) {
            return data.size();
        } else {
            return 0;
        }
    }

    @Override
    public Object getItem(int position) {
        return data.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(final int position, View convertView, ViewGroup parent) {
        ViewHolder holder;
        if (convertView == null) {
            convertView = View.inflate(mContext, R.layout.item_student_work_show, null);
            holder = new ViewHolder();
            holder.tv_commentCount = (TextView) convertView.findViewById(R.id.tv_commentCount);
            holder.tv_releaseTime = (TextView) convertView.findViewById(R.id.tv_releaseTime);
            holder.tv_goodCount = (TextView) convertView.findViewById(R.id.tv_goodCount);
            holder.img_delete_click = (RippleView) convertView.findViewById(R.id.img_delete_click);
            holder.tv_commentCount_click = (RippleView) convertView.findViewById(R.id.tv_commentCount_click);
            holder.tv_goodCount_click = (RippleView) convertView.findViewById(R.id.tv_goodCount_click);
            holder.gridView = (NoScrollGridView) convertView.findViewById(R.id.gridView);
            holder.tv_nickname = (TextView) convertView.findViewById(R.id.tv_nickname);
            holder.iv_icon = (ImageView) convertView.findViewById(R.id.iv_icon);
            holder.img_delete = (ImageView) convertView.findViewById(R.id.img_delete);
            holder.ll_add_comment = (LinearLayout) convertView.findViewById(R.id.ll_add_comment);
            holder.ll_student = (LinearLayout) convertView.findViewById(R.id.ll_student);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }
        StudentWorkShowInfo.DataBean.InfosListBean infosListBean = data.get(position);
        List<WorkShowReply> replyDatas = infosListBean.getListReply();
        WorkShowStudent workShowStudent = infosListBean.getNodeShowWorksStudent();
        List<WorkShowImgs> workShowImgs = infosListBean.getAttachmentInfos();
        //评论
        holder.ll_add_comment.removeAllViews();
        if (replyDatas != null && replyDatas.size() > 0) {
            for (WorkShowReply datas : data.get(position).getListReply()) {
                TextView textView = new TextView(mContext);
                textView.setTextColor(Color.argb(255, 0, 0, 0));
                textView.setPadding(8, 4, 0, 0);
                textView.setTextSize(16);
                textView.setText(datas.getReplyStudentName() + "的评论:" + datas.getReplyContent());
                holder.ll_add_comment.addView(textView);
            }
        }
        if (workShowImgs != null && workShowImgs.size() > 0) {
            imageUrls.clear();
            for (WorkShowImgs data : workShowImgs) {
                imageUrls.add(NetworkUrlConstants.getDownloadUrl(data.getAttachmentId()));
            }
            holder.gridView.setVisibility(View.VISIBLE);
            holder.gridView.setAdapter(new WorkShowAdapter(mContext, workShowImgs, nodeId));
            holder.gridView.setOnItemClickListener(((parent1, view, position1, id) -> {
                Logger.d(imageUrls.size() + "########imageUrls.size()##########");
                for (String str : imageUrls) {
                    Logger.d(str + "######str######");
                }
                ImageUtils.imageBrower(mContext, imageUrls, position1);
            }));
            if (null != workShowStudent) {
                holder.ll_student.setVisibility(View.VISIBLE);
                if (DBHelper.getStudent().getId() == (Long.valueOf(workShowStudent.getStudentId()))) {
                    holder.img_delete.setVisibility(View.VISIBLE);
                    holder.img_delete_click.setVisibility(View.VISIBLE);

                    holder.img_delete_click.setOnClickListener((v -> {
                        if (status != 2) {
                            deleteDialog(workShowStudent.getId() + "");
                        } else {
                            ToastUtils.show(mContext, R.string.title_the_show_passed);
                        }
                    }));
                } else {
                    holder.img_delete.setVisibility(View.GONE);
                    holder.img_delete_click.setVisibility(View.GONE);
                }
                String localPath = CourseUtils.getCourseImgePath(nodeId + "", workShowStudent.getStudentLogoAttachmentId());
                if (localPath == null) {
                    ImageLoaderUtils.showImage(mContext, NetworkUrlConstants.getStudentHeadPicUrl(workShowStudent.getStudentLogoAttachmentId()), holder.iv_icon, workShowStudent.getStudentLogoAttachmentId(), nodeId + "", true);
                } else {
                    holder.iv_icon.setBackgroundResource(R.drawable.login_user);
                    CourseUtils.displayImagePath(mContext, nodeId + "", workShowStudent.getStudentLogoAttachmentId(), holder.iv_icon);
                }
                holder.tv_nickname.setText(workShowStudent.getStudentName());
                holder.tv_goodCount.setText("点赞" + workShowStudent.getUpCount());
                holder.tv_goodCount_click.setOnClickListener((v1 -> {
                    if (status != 2) {
                        DataUtils.updateStudentWorkShowLike(mContext, workShowStudent.getId() + "");
                    } else {
                        ToastUtils.show(mContext, R.string.title_the_show_passed);
                    }
                }));
                holder.tv_commentCount_click.setOnClickListener((v -> {
                    if (status != 2) {
                        showLikeDialog(workShowStudent.getId() + "");
                    } else {
                        ToastUtils.show(mContext, R.string.title_the_show_passed);
                    }
                }));
            } else {
                holder.tv_releaseTime.setText(CalendarUtil.Long2String(workShowStudent.getCreateTime(), CalendarUtil.DATE_LONG));
            }
        } else {
            holder.ll_student.setVisibility(View.GONE);
            holder.gridView.setVisibility(View.GONE);
        }
        return convertView;
    }

    private void deleteDialog(String s) {
        new MaterialDialog.Builder(mContext)
                .theme(Theme.LIGHT)
                .title(R.string.title_sure_delete_show)
                .positiveText(R.string.title_confirm)
                .negativeText(R.string.title_cancel)
                .onPositive((dialog, which) -> {
                    DataUtils.deleteStudentWorkShow(mContext, s);
                    dialog.dismiss();
                })
                .onNegative((dialog, which) -> dialog.dismiss())
                .show();
    }

    private void showLikeDialog(String s) {
        new MaterialDialog.Builder(mContext)
                .title(R.string.title_comment)
                .inputType(InputType.TYPE_CLASS_TEXT |
                        InputType.TYPE_TEXT_VARIATION_PERSON_NAME |
                        InputType.TYPE_TEXT_FLAG_CAP_WORDS)
                .inputRange(2, 100)
                .positiveText(R.string.title_submit)
                .negativeText(R.string.title_cancel)
                .onPositive((dialog, which) -> {
                    dialog.dismiss();
                })
                .onNegative((dialog, which) -> dialog.dismiss())
                .input("", "", false, new MaterialDialog.InputCallback() {
                    @Override
                    public void onInput(@NonNull MaterialDialog dialog, CharSequence input) {
                        DataUtils.updateStudentWorkShowComment(mContext, s, input.toString());
                    }
                }).show();

    }

    private static class ViewHolder {
        ImageView iv_icon;
        TextView tv_nickname;
        TextView tv_releaseTime;
        TextView tv_goodCount;
        TextView tv_commentCount;
        NoScrollGridView gridView;
        LinearLayout ll_add_comment;
        LinearLayout ll_student;
        ImageView img_delete;
        RippleView img_delete_click;
        RippleView tv_goodCount_click;
        RippleView tv_commentCount_click;
    }`

**Comment by LcTerry** [comment]
**i give the logger in listview**  `holder.gridView.setOnItemClickListener(((parent1, view, position1, id) -> {
                Logger.d(imageUrls.size() + "########imageUrls.size()##########");
                for (String str : imageUrls) {
                    Logger.d(str + "######str######");
                }
                ImageUtils.imageBrower(mContext, imageUrls, position1);
            }));`
**I click the second item,and then to click first item!
the logger**
`09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ║ 1########imageUrls.size()##########
09-13 20:02:45.768 4312-4312/io.itit.ititeducation D/ITIT: ║ http://192.168.0.128:6001/p/main/download_file/KdjyFileSystem1_b9eb7a35-8c13-4648-8ee1-de45cf6dd7ad.jpg######str######

09-13 20:02:50.348 4312-4312/io.itit.ititeducation D/ITIT: ║ 1########imageUrls.size()##########
09-13 20:02:50.358 4312-4312/io.itit.ititeducation D/ITIT: ║ http://192.168.0.128:6001/p/main/download_file/KdjyFileSystem1_b9eb7a35-8c13-4648-8ee1-de45cf6dd7ad.jpg######str######
`
**I guess u method which give the tag have a effect on the listview?????**

this my listview code 

` List<StudentWorkShowInfo.DataBean.InfosListBean> data;
    private StudentWorkShowActivity mContext;
    ArrayList<String> imageUrls = new ArrayList<>();
    long nodeId;
    int status;

    public StudentWorkShowAdapter(List<StudentWorkShowInfo.DataBean.InfosListBean> data, Context context, long nodeId, int status) {
        this.data = data;
        this.mContext = (StudentWorkShowActivity) context;
        this.nodeId = nodeId;
        this.status = status;

    }

    @Override
    public int getCount() {
        if (data != null && data.size() > 0) {
            return data.size();
        } else {
            return 0;
        }
    }

    @Override
    public Object getItem(int position) {
        return data.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(final int position, View convertView, ViewGroup parent) {
        ViewHolder holder;
        if (convertView == null) {
            convertView = View.inflate(mContext, R.layout.item_student_work_show, null);
            holder = new ViewHolder();
            holder.tv_commentCount = (TextView) convertView.findViewById(R.id.tv_commentCount);
            holder.tv_releaseTime = (TextView) convertView.findViewById(R.id.tv_releaseTime);
            holder.tv_goodCount = (TextView) convertView.findViewById(R.id.tv_goodCount);
            holder.img_delete_click = (RippleView) convertView.findViewById(R.id.img_delete_click);
            holder.tv_commentCount_click = (RippleView) convertView.findViewById(R.id.tv_commentCount_click);
            holder.tv_goodCount_click = (RippleView) convertView.findViewById(R.id.tv_goodCount_click);
            holder.gridView = (NoScrollGridView) convertView.findViewById(R.id.gridView);
            holder.tv_nickname = (TextView) convertView.findViewById(R.id.tv_nickname);
            holder.iv_icon = (ImageView) convertView.findViewById(R.id.iv_icon);
            holder.img_delete = (ImageView) convertView.findViewById(R.id.img_delete);
            holder.ll_add_comment = (LinearLayout) convertView.findViewById(R.id.ll_add_comment);
            holder.ll_student = (LinearLayout) convertView.findViewById(R.id.ll_student);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }
        StudentWorkShowInfo.DataBean.InfosListBean infosListBean = data.get(position);
        List<WorkShowReply> replyDatas = infosListBean.getListReply();
        WorkShowStudent workShowStudent = infosListBean.getNodeShowWorksStudent();
        List<WorkShowImgs> workShowImgs = infosListBean.getAttachmentInfos();
        //评论
        holder.ll_add_comment.removeAllViews();
        if (replyDatas != null && replyDatas.size() > 0) {
            for (WorkShowReply datas : data.get(position).getListReply()) {
                TextView textView = new TextView(mContext);
                textView.setTextColor(Color.argb(255, 0, 0, 0));
                textView.setPadding(8, 4, 0, 0);
                textView.setTextSize(16);
                textView.setText(datas.getReplyStudentName() + "的评论:" + datas.getReplyContent());
                holder.ll_add_comment.addView(textView);
            }
        }
        if (workShowImgs != null && workShowImgs.size() > 0) {
            imageUrls.clear();
            for (WorkShowImgs data : workShowImgs) {
                imageUrls.add(NetworkUrlConstants.getDownloadUrl(data.getAttachmentId()));
            }
            holder.gridView.setVisibility(View.VISIBLE);
            holder.gridView.setAdapter(new WorkShowAdapter(mContext, workShowImgs, nodeId));
            holder.gridView.setOnItemClickListener(((parent1, view, position1, id) -> {
                Logger.d(imageUrls.size() + "########imageUrls.size()##########");
                for (String str : imageUrls) {
                    Logger.d(str + "######str######");
                }
                ImageUtils.imageBrower(mContext, imageUrls, position1);
            }));
            if (null != workShowStudent) {
                holder.ll_student.setVisibility(View.VISIBLE);
                if (DBHelper.getStudent().getId() == (Long.valueOf(workShowStudent.getStudentId()))) {
                    holder.img_delete.setVisibility(View.VISIBLE);
                    holder.img_delete_click.setVisibility(View.VISIBLE);

                    holder.img_delete_click.setOnClickListener((v -> {
                        if (status != 2) {
                            deleteDialog(workShowStudent.getId() + "");
                        } else {
                            ToastUtils.show(mContext, R.string.title_the_show_passed);
                        }
                    }));
                } else {
                    holder.img_delete.setVisibility(View.GONE);
                    holder.img_delete_click.setVisibility(View.GONE);
                }
                String localPath = CourseUtils.getCourseImgePath(nodeId + "", workShowStudent.getStudentLogoAttachmentId());
                if (localPath == null) {
                    ImageLoaderUtils.showImage(mContext, NetworkUrlConstants.getStudentHeadPicUrl(workShowStudent.getStudentLogoAttachmentId()), holder.iv_icon, workShowStudent.getStudentLogoAttachmentId(), nodeId + "", true);
                } else {
                    holder.iv_icon.setBackgroundResource(R.drawable.login_user);
                    CourseUtils.displayImagePath(mContext, nodeId + "", workShowStudent.getStudentLogoAttachmentId(), holder.iv_icon);
                }
                holder.tv_nickname.setText(workShowStudent.getStudentName());
                holder.tv_goodCount.setText("点赞" + workShowStudent.getUpCount());
                holder.tv_goodCount_click.setOnClickListener((v1 -> {
                    if (status != 2) {
                        DataUtils.updateStudentWorkShowLike(mContext, workShowStudent.getId() + "");
                    } else {
                        ToastUtils.show(mContext, R.string.title_the_show_passed);
                    }
                }));
                holder.tv_commentCount_click.setOnClickListener((v -> {
                    if (status != 2) {
                        showLikeDialog(workShowStudent.getId() + "");
                    } else {
                        ToastUtils.show(mContext, R.string.title_the_show_passed);
                    }
                }));
            } else {
                holder.tv_releaseTime.setText(CalendarUtil.Long2String(workShowStudent.getCreateTime(), CalendarUtil.DATE_LONG));
            }
        } else {
            holder.ll_student.setVisibility(View.GONE);
            holder.gridView.setVisibility(View.GONE);
        }
        return convertView;
    }

    private void deleteDialog(String s) {
        new MaterialDialog.Builder(mContext)
                .theme(Theme.LIGHT)
                .title(R.string.title_sure_delete_show)
                .positiveText(R.string.title_confirm)
                .negativeText(R.string.title_cancel)
                .onPositive((dialog, which) -> {
                    DataUtils.deleteStudentWorkShow(mContext, s);
                    dialog.dismiss();
                })
                .onNegative((dialog, which) -> dialog.dismiss())
                .show();
    }

    private void showLikeDialog(String s) {
        new MaterialDialog.Builder(mContext)
                .title(R.string.title_comment)
                .inputType(InputType.TYPE_CLASS_TEXT |
                        InputType.TYPE_TEXT_VARIATION_PERSON_NAME |
                        InputType.TYPE_TEXT_FLAG_CAP_WORDS)
                .inputRange(2, 100)
                .positiveText(R.string.title_submit)
                .negativeText(R.string.title_cancel)
                .onPositive((dialog, which) -> {
                    dialog.dismiss();
                })
                .onNegative((dialog, which) -> dialog.dismiss())
                .input("", "", false, new MaterialDialog.InputCallback() {
                    @Override
                    public void onInput(@NonNull MaterialDialog dialog, CharSequence input) {
                        DataUtils.updateStudentWorkShowComment(mContext, s, input.toString());
                    }
                }).show();

    }

    private static class ViewHolder {
        ImageView iv_icon;
        TextView tv_nickname;
        TextView tv_releaseTime;
        TextView tv_goodCount;
        TextView tv_commentCount;
        NoScrollGridView gridView;
        LinearLayout ll_add_comment;
        LinearLayout ll_student;
        ImageView img_delete;
        RippleView img_delete_click;
        RippleView tv_goodCount_click;
        RippleView tv_commentCount_click;
    }`

**Comment by TWiStErRob** [comment]
Ooh, nested list, I was wondering what `holder.gridView` was... Move the `imageUrls` to `ViewHolder`. Currently it's shared by all items and each bind overrides the previous one. After moving each list item will have it's own list, so you'll have a 1:1 correspondence between `imageUrls` adn `gridView`.

You could also simply get rid of that extra list and store `workShowImgs` in `holder`. You can delay generation of `getDownloadUrl` until the click: `getDownloadUrl(workShowImgs.get(position1).getAttachmentId())`. There's no need to gererate all urls, when they likely won't be used.

More tips: `ViewHolder` is a class, so it can have a constructor and methods that operate on the fields. For example you can move that bunch of `findViewById`s into the constructor. Most of the adapters out there have [feature envy](http://programmers.stackexchange.com/q/212128/160848) for their `ViewHolder`s, so another example is that you can move all the event listener setters into that same constructor (there's no need to set those listeners again and again as the views don't change in the holder). You might be wondering how it'll access `workShowStudent`, but that's really simple, you start binding with `holder.workShowStudent = ...` (a new field on holder). So each item (=ViewHolder) knows about the current data that's bound to it and the async clicks can read that.

**Comment by LcTerry** [comment]
Thank you so much!!!!!
i will try u tips and improve my skill   !!!!
