### ISSUE TITLE
Add support for SVG animated stickers

### ISSUE THREAD

**Issue by Emasoft** [bumptech/glide#1469]
Please add support for SVG to Glide.

Glide was the first to add animated GIF support. And that was great.
Now GIF is being replaced by animated SVGs in many apps. SVG have a much smaller size than GIFS (few Kbs Vs one or more MBs), and yet offer better quality than GIFs for some kind of animated images (social stickers/animated emoticons, etc).
For example the Android App "Viber" uses them (you can see an example at this link: http://www.tbyrne.org/viber-animated-svgs ). 
Notice that I'm referring to simple SVG files that do not use javascript, but only the standard SVG 1.1 markup to define animations, like those used by Viber.

**Comment by TWiStErRob** [comment]
There is an SVG example in the repo, granted that's not animated. For it to be animated you need a library that supports loading animated SVGs into a drawable. Once you have that, it is really simple to integrate it with Glide.
