### ISSUE TITLE
glide volley integeration not allowing my api url to load

### ISSUE THREAD

**Issue by sant527** [bumptech/glide#1471]
compile 'com.github.bumptech.glide:glide:3.6.1'
    compile 'jp.wasabeef:glide-transformations:2.0.0'
    compile 'com.mcxiaoke.volley:library:1.0.19'

    compile 'com.github.bumptech.glide:volley-integration:1.3.1@aar'

In an activity: I have a tabviewer 
On first tab loads image gallery using glide
On second tab i have a list of items. when i click on a item, using volley it get the JSON data from an api and shows   the data in a new Activity

Because of image gallery being loaded, is it going to hamper the network for api being loaded.

**Comment by TWiStErRob** [comment]
Configure Volley to handle your requests with higher priority, or Glide's with lower priority.

**Comment by TWiStErRob** [comment]
Also if the first tab is not visible it shouldn't be binding that UI. In one of my uses I clear the adapter of the recyclerview and handle `onViewRecycled` in the adapter by `Glide.clear(holder.image)`, this frees up any resources and cancels the load.

**Comment by sant527** [comment]
Where to put the Glide.clear(holder.image). Is it ok that i dont use the volley integration.

**Comment by TWiStErRob** [comment]
I don't think we can fix this. It looks like Glide users need to configure Volley to handle more parallel requests in some cases. If anyone thinks this could be fixed though let us know.
