### ISSUE TITLE
staggeredgrid layout not showing properly

### ISSUE THREAD

**Issue by sant527** [bumptech/glide#1472]
compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'jp.wasabeef:glide-transformations:2.0.0'

I am using staggered list and glide in the recyclerview adapter. the layout is not showing properly when i move up.  

Please refer to this link http://stackoverflow.com/questions/39503823/androidstaggergridlayout-while-moving-up-shuffles/39504460#39504460  to see the images of staggeredlist layout problem.

the glide code i am using is as below.

```
        Glide.with(personViewHolder.itemView.getContext())
                .load(placeListGalleries.get(i).placegallery_urlsize_thumb)
                .placeholder(R.drawable.logo_02_1).animate(android.R.anim.fade_in)
                .priority(Priority.LOW)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .error(R.drawable.exception)
                .into(personViewHolder.place_image);
```

Why the layout is not showing properly i dont understand

**Comment by TWiStErRob** [comment]
Here's a working staggered example: https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_864_staggered_grid
You need to know the sizes beforehand, otherwise it becomes jumpy, because while the image is loading the layout manager doesn't know what size the item will be, but it needs that info to layout.

**Comment by sant527** [comment]
If i know the size of the image, thats ok. or i have to define the imageview size

**Comment by TWiStErRob** [comment]
Those two are the same thing, really. Note that you don't need to know the size, only the aspect ratio. I couldn't find a better way than this yet.

If you define the image size in XML, it's not really staggered any more, only if you're doing it dynamically based on position.

**Comment by sant527** [comment]
Where in that example link the code which i have to implement is there. I cant understand that code.

is `listView.addOnScrollListener(new PauseOnFling(glide));`  this what i have to implement

**Comment by TWiStErRob** [comment]
No, that's an extra which helps to stop loading images when they won't be seen (fast scrolling).
For you, you need to take a look at the ImageView in the item's XML and `holder.bindImage` method.

**Comment by sant527** [comment]
I have lot of images with different aspect ratio.` tools:layout_aspectRatio="178%"` is not possible. Any other way then

**Comment by TWiStErRob** [comment]
It's `tools`, not `android`, it's just for the preview in the IDE to show something meaningful. Read up on the tools namespace. The real aspect will be set in code per item per image.

**Comment by sant527** [comment]
can you show me sample code of setting real aspect per item per image.

**Comment by TWiStErRob** [comment]
https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/github/_864_staggered_grid/FeedEntryViewHolder.java#L77

**Comment by sant527** [comment]
Ok. tried:

```
<android.support.percent.PercentRelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent">
    
<ImageView
    android:id="@+id/placegalleryrvadapter_image"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:layout_widthPercent="100%"
    tools:layout_aspectRatio="178%"
    android:layout_margin="2dp"
    android:adjustViewBounds="true"
    android:src="@drawable/bubble_mask"/>

</android.support.percent.PercentRelativeLayout>
```

then 

```
Glide.with(personViewHolder.itemView.getContext())
                .load(placeListGalleries.get(i).placegallery_urlsize_thumb)
                .placeholder(R.drawable.logo_02_1).animate(android.R.anim.fade_in)
                .priority(Priority.LOW)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .error(R.drawable.exception)
                .into(personViewHolder.place_image);
```

But the image size does not change as per the aspect ratio. presently i am testing the same aspect ratio for all the images. all the images maintain their origianl aspect ratio rather than 178%

**Comment by TWiStErRob** [comment]
Did you use the fixLayout method as shown in the example?

**Comment by sant527** [comment]
```
PercentRelativeLayout.LayoutParams layoutParams = (PercentRelativeLayout.LayoutParams)personViewHolder.place_image.getLayoutParams();

        PercentLayoutHelper.PercentLayoutInfo info = layoutParams.getPercentLayoutInfo();

        float oldAspect = info.aspectRatio;
        layoutParams.height = 0;
        personViewHolder.place_image.setLayoutParams(layoutParams);
```

i tired the above code.everything is blank. is this because of height

**Comment by TWiStErRob** [comment]
I'm not sure, use normal debugging ways to figure it out:
 * turn on show layout borders in Developer Options
 * modify your layout to have different colors for each item to see if they're laid out
 * add a click listener and put a breakpoint inside it on a dummy line (e.g. a `Log.d`) and investigate the variables in debugger
 * https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
