### ISSUE TITLE
Status of Glide 4

### ISSUE THREAD

**Issue by Teovald** [bumptech/glide#1473]
Right now Glide is in a bit of an awkward state with 3.x being updated from times to times while the focus seems to be on version 4.  

3.x is a bit of a pain to compile with JVM 7 and old support libraries while improvements made on the 4.x branch can only be used if we compile it ourselves.

Is there any plan to officially publish Glide 4.0 soon ?  From what I can gather it is already used internally at Google on some products so it sounds stable enough.  

IMO it would benefit the library to focus on this branch and only maintain 3.x .

**Comment by TWiStErRob** [comment]
I think the state is like this because the API may be changing still. @sjudd will know better.

> can only be used if we compile it ourselves
That's news for me, did you read https://github.com/bumptech/glide/wiki/Snapshots

**Comment by Teovald** [comment]
my bad, I forgot about the snapshots.
Still, the awkwardness of this prolonged state with the 2 branches remains.

**Comment by sjudd** [comment]
Yup I agree, I'm working on it. Probably the end result will be 4.0 released with dot releases that break some APIs. It still feels like there's room for improvement in the API, but we're clearly not making a lot of significant changes so I agree it's silly to keep holding it up.

**Comment by Teovald** [comment]
Awesome !  
There is clearly no perfect solution, but most API changes can probably be handled with AS structural replace feature.

**Comment by sjudd** [comment]
Sorry for the delay here. Looking to get this out in the next month or two. Mostly focusing on documentation and Glide's generated API. 

If anyone is interested in contributing to documentation, it's available here: http://sjudd.github.io/glide/ (see the contributing section). Updates to javadocs are also helpful. The 4.0.0 snapshot is also available with changes if people want to try it out. The 4.0 snapshot version is used internally at Google by a number of apps.
