### ISSUE TITLE
How to simplify loading an image to relativelayouts background?

### ISSUE THREAD

**Issue by Muuddz** [bumptech/glide#1475]
I have just moved from Picasso to Glide where in Picasso it was easy to load a image into any Views background, it's not the case with Glide.

I found a guide on the web and I had to create 2 classes just so I could load a image into a Relativelayout's background. **There must be a more cleaner and better way?**

I have initiated a custom ViewTarget in my mainActivity and loaded into the relativelayout's background like this:

```
ViewTarget viewTarget = new ViewTarget(relativeLayout);
Glide.with(App.getAppContext()).load(data.getData()).fitCenter().centerCrop().into(viewTarget);
```

And the  two classes below are the ones that are needed to load a image into Relativelayout.
Can it be improved or simplified in anyway?

**The ViewTarget class:**

```
public class ViewTarget extends ViewTarget2<GlideDrawable> {
 
    public ViewTarget(ViewGroup view) {
        super(view);
    }
 
    @Override
    protected void setResource(GlideDrawable resource) {
        view.setBackground(resource);
 
    }
}
```

**The abstract class ViewTarget2<Z>**

    public abstract class ViewTarget2<Z> extends com.bumptech.glide.request.target.ViewTarget<ViewGroup,Z> implements GlideAnimation.ViewAdapter {

    public ViewTarget2(ViewGroup view) {
        super(view);
    }

    @Override
    public Drawable getCurrentDrawable() {
        return view.getBackground();
    }

    /**
     * Sets the given {@link android.graphics.drawable.Drawable} on the view using
     * {@link android.widget.ImageView#setImageDrawable(android.graphics.drawable.Drawable)}.
     *
     * @param drawable {@inheritDoc}
     */
    @Override
    public void setDrawable(Drawable drawable) {
        view.setBackground(drawable);
    }

    /**
     * Sets the given {@link android.graphics.drawable.Drawable} on the view using
     * {@link android.widget.ImageView#setImageDrawable(android.graphics.drawable.Drawable)}.
     *
     * @param placeholder {@inheritDoc}
     */
    @Override
    public void onLoadStarted(Drawable placeholder) {
        view.setBackground(placeholder);
    }

    /**
     * Sets the given {@link android.graphics.drawable.Drawable} on the view using
     * {@link android.widget.ImageView#setImageDrawable(android.graphics.drawable.Drawable)}.
     *
     * @param errorDrawable {@inheritDoc}
     */
    @Override
    public void onLoadFailed(Exception e, Drawable errorDrawable) {
        view.setBackground(errorDrawable);
    }

    /**
     * Sets the given {@link android.graphics.drawable.Drawable} on the view using
     * {@link android.widget.ImageView#setImageDrawable(android.graphics.drawable.Drawable)}.
     *
     * @param placeholder {@inheritDoc}
     */
    @Override
    public void onLoadCleared(Drawable placeholder) {
        view.setBackground(placeholder);
    }

    @Override
    public void onResourceReady(Z resource, GlideAnimation<? super Z> glideAnimation) {

        this.setResource(resource);
    }

    protected abstract void setResource(Z resource);

}

**Comment by TWiStErRob** [comment]
See #938 and [glide-support code](https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_938_background).
There's no simpler way if you want to handle the lifecycle correctly. You don't need to create 2 classes though, you can do it with one, but for sake of clarity and reusability it's worth doing it in two.

Tip 1: I don't know why you're constraining yourself to `ViewGroup` all the methods you use are on `View`.
Tip 2: `.fitCenter().centerCrop()` is a contradiction, choose one of them

I'm not sure what you migrated from, it looks like you needed to create classes in Picasso too:
 * http://stackoverflow.com/q/31464867/253468
 * http://stackoverflow.com/a/29777471/253468

**Comment by logicgupta** [comment]
This will solve the issue in setting image to relative layout

Glide.with(this).load(imageViewPath).asBitmap().into(new SimpleTarget<Bitmap>(relLayoutWidth, relLayoutHeight) {
    @Override
    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
        Drawable drawable = new BitmapDrawable(context.getResources(), resource);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            yourRelativeLayout.setBackground(drawable);
        }
    }
});
