### ISSUE TITLE
why load asGif can not this method to listen

### ISSUE THREAD

**Issue by mm46468648** [bumptech/glide#1476]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

 Glide
                        .with(NewsDetailActivity.this) // 指定Context
                        .load(imgSrc)// 指定图片的URL
                        .asGif()
                        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                        .into(new GlideDrawableImageViewTarget(imageView));

**Comment by TWiStErRob** [comment]
I don't understand, can you please rephrase your problem? What do you expect? And what is happening actually?

**Comment by mm46468648** [comment]
sorry,my english is not very well,i can't descript my problem actually,but the problem is solved,is due to my personal reasons, very thanks for your repley.

At 2016-09-21 15:28:53, "Róbert Papp" <notifications@github.com> wrote:


I don't understand, can you please rephrase your problem? What do you expect? And what is happening actually?
