### ISSUE TITLE
White flicker when loaded into ImageView

### ISSUE THREAD

**Issue by chitgoks** [bumptech/glide#1477]
I've searched through previous issues regarding white flicker background and even in stackoverflow and the posts there did not work. maybe it could be my situation may be different. please advise.

This is my xml

 <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:id="@+id/image"
        android:contentDescription="@string/video"/>

and code in my Fragment

Glide.with(getActivity())
            .load(URL)
            .into((ImageView) fragmentView.findViewById(R.id.image));

Now, i tried adding scaleType fitCenter in the XML, even setting background to black but it did not work. There was also a post some sort of a hack using listeners in Glide but still no effect.

I am using Glide 3.7.0

**Comment by TWiStErRob** [comment]
Not sure what your flicker was, most of them are related to cross fade, but you're simply fading in.

Tip: you should consider changing your layer to not have wrap-wrap ImageView, because it triggers Glide to load an unnecessarily large Bitmap.

**Comment by chitgoks** [comment]
hi twisterRob. apologies. there does not seem to be a delete option here so i opted to close it. it seems i got hit by an old VideoView bug on pre-marshmallow os that was the cause of the flicker.

**Comment by TWiStErRob** [comment]
Ah, thanks for sharing.

> does not seem to be a delete option

That's the reason I asked, if anyone finds it in the future they have at least some pointer as to what to issue was.
