### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by zhulujiang** [bumptech/glide#1480]
when I import files  into the studio, the Message Gradle Sync control-panel  show the follow errors:

Error:CreateProcess error=2, 系统找不到指定的文件。
Gradle 'glide-master' project refresh failed

 what's wrong with this?   can you help me?

**Comment by TWiStErRob** [comment]
Make sure you can build from command line first: https://github.com/bumptech/glide/blob/master/README.md#build

Why do you need to build the code yourself?

**Comment by rbiggers** [comment]
I am actually having the same issue. I am able to build successfully from the command line but when I try to build through Android Studio I get this error.

**Comment by TWiStErRob** [comment]
error 2 means file not found, maybe there's a PATH issue. The `master` branch calls `git` from `settings.gradle`.

**Comment by rbiggers** [comment]
I think I figured out what it was. I found some information on another issue that lead me to the solution. I had cloned the master branch but was calling v3.7.0 from maven. So once I checked out the 3.0 branch everything worked as expected.

**Comment by TWiStErRob** [comment]
@rbiggers the `3.0` doesn't have that `commandLine` call as far as I know.

**Comment by rbiggers** [comment]
@TWiStErRob Once I switched to the 3.0 branch Android Studio took over and synced gradle and the command line was no longer needed.

**Comment by CoKoOne** [comment]
@zhulujiang 请问一下 你导入成功了吗，我用Android studio 导入时也出现Error:CreateProcess error=2, 系统找不到指定的文件。
