### ISSUE TITLE
Auto select diskCacheStrategy form image format

### ISSUE THREAD

**Issue by Heycz** [bumptech/glide#1481]
I want to use SOURCE when load gif,use RESULT when load other image,but sometimes i can not determine the image is a gif ,is there any soluttion ?

**Comment by TWiStErRob** [comment]
Glide v4 will do the automatic selection:
https://github.com/bumptech/glide/commits/master/library/src/main/java/com/bumptech/glide/load/engine/DiskCacheStrategy.java

In the meantime: https://github.com/bumptech/glide/wiki/Snapshots
Or make your image provider either use extensions or give metadata about the images.
