### ISSUE TITLE
Can't load the picture

### ISSUE THREAD

**Issue by laymanZ** [bumptech/glide#1487]
Hello, first time using your framework, there has been a problem that plagued for a long time。
Here is my code：

about  java
```java
imageView = (ImageView)findViewById(R.id.image_glidetest);
        Glide.with(getApplicationContext())
                .load("http://d.lanrentuku.com/down/png/1607/10material-avatars-new/avatar-07.png")
                .asBitmap()
                .into(new SimpleTarget<Bitmap>()
                {
                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation)
                    {
                            imageView.setImageBitmap(resource);
                    }

                    @Override
                    public void onLoadFailed(Exception e, Drawable errorDrawable)
                    {
                        super.onLoadFailed(e, errorDrawable);
                                                Log.e("LLpp:加载失败 loadOnFalied：","http://d.lanrentuku.com/down/png/1607/10material-avatars-new/avatar-07.png");

                        imageView.setVisibility(View.GONE);
                    }
                });
```
about  xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">
    <ImageView
        android:id="@+id/image_glidetest"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</RelativeLayout>
```

But has been unable to load pictures, no matter what format。And I changed the version, did not achieve the desired results

The output log is always this：
`09-27 03:02:28.057 10595-10595/? E/LLpp:加载失败 onFalied：: http://d.lanrentuku.com/down/png/1607/10material-avatars-new/avatar-07.png`

**Comment by TWiStErRob** [comment]
You're almost there, but you're logging the wrong thing: try `Log.e("LLpp", "onLoadFailed", e);`. That exception argument is there for a reason.

By the way, custom targets are advanced stuff, you shouldn't use it until you understand Glide better. Try adding a `.listener` instead to see when the load succeeded/failed. It has even more information available than a target. `into(imageView)` should be sufficient 99% of the time.

**Comment by TWiStErRob** [comment]
Also check out https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by laymanZ** [comment]
Thank you for your detailed answer, the proposed issue, I found the "Exception e" this parameter, how careless, I continue to try, more familiar with the use of glide
