### ISSUE TITLE
How do you know whether the picture is loaded or not?

### ISSUE THREAD

**Issue by StrangerMosr** [bumptech/glide#1493]
I want do something when  the picture is loaded ,but i don't find any Listener.Can you help me?

**Comment by Ccixyj** [comment]
override methods in RequestListener 
```java
  Glide.with(context) .load(uri) .listener(new RequestListener<Uri, GlideDrawable>(){}).into(imageView);
```

**Comment by StrangerMosr** [comment]
Thank you,

**Comment by StrangerMosr** [comment]
Glide.with(this).load(advertisementBean.getImageUrl()).diskCacheStrategy(DiskCacheStrategy.ALL).listener(new RequestListener<String, GlideDrawable>() {
                @Override
                public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                    return false;
                }

                @Override
                public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {

                    rel_advertisement.setVisibility(View.VISIBLE);

                    Times(TIME_OUT);
                    return false;
                }
            }).into(iv_advert_img);


` rel_advertisement.setVisibility(View.VISIBLE);   `
This code is not executed, even if I use Hadler to update it.

**Comment by Ccixyj** [comment]
@StrangerMosr  check onException  is executed,then check onResourceReady's params  is null or some else

**Comment by TWiStErRob** [comment]
Tip: it's good to start with https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener to see if your load is correct, and then replace that with your listener once you're certain everything works. Both these callbacks are called on the UI thread, you don't need handlers.

**Comment by StrangerMosr** [comment]
@TWiStErRob Thank you,I have solved it.I find if the imageview isn't VISIBLE ,the listenter will not be executed.

**Comment by TWiStErRob** [comment]
Ah, that's correct. Glide needs to know the view size to start loading the image (otherwise transformations wouldn't know the target size), and that sizing is only available after layout/draw which won't happen for non-visibles.

**Comment by StrangerMosr** [comment]
@TWiStErRob Thank you very much for your guidance.
