### ISSUE TITLE
java.net.UnknownHostException: Unable to resolve host "1.bp.blogspot.com": No address associated with hostname

### ISSUE THREAD

**Issue by mdtuyen** [bumptech/glide#1496]
I try load [this picture](https://1.bp.blogspot.com/-PAZ9N3fTH8s/V_FAwLne0OI/AAAAAAAHE18/gx-UudDQzjY/c-w180-h255/TT8-2.jpg) 

But now thing to show, i put listenner to debug and see in the log:

> java.net.UnknownHostException: Unable to resolve host "1.bp.blogspot.com": No address associated with hostname

Why ?

**Comment by TWiStErRob** [comment]
Did you search for the problem?
e.g. http://stackoverflow.com/q/3314137/253468

**Comment by mdtuyen** [comment]
Hi @TWiStErRob I have full permission and put correct position:

>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
>     <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

**Comment by TWiStErRob** [comment]
Have you tried turning it off and on again?

**Comment by mdtuyen** [comment]
Yes, I tried on/off internet. 
But when I change url to "http://cdn3.nflximg.net/images/3093/2043093.jpg" it work fine

**Comment by TWiStErRob** [comment]
The device, restart the device. DNS lookups are cached, regardless of network state; if it failed once it won't resolve for a while and then potentially fix itself. For this reason loading from a different host obviously works.

**Comment by mdtuyen** [comment]
Hi @TWiStErRob I work with two device and two network. I have just restart device but it still not show

**Comment by TWiStErRob** [comment]
Did you manage to make it work? Does it work now without change maybe? What's the difference between the two hosts you mentioned above?

**Comment by mdtuyen** [comment]
I don't know why the link of image can open on PC but can't open on Mobile.

**Comment by TWiStErRob** [comment]
I don't know either, but it works on my phone. I'm pretty sure it's a network/host/device specific problem and Glide can't do much about it. Please reopen if you can create a consistent repro.

**Comment by mabuthraa** [comment]
I suspect it's due to self-signed certificate with SSL .. 
you have two options : 

1. Trust that certificate on emulator
2. Ignore these self-signed certificate  . see : https://stackoverflow.com/a/34137694/2267723

**Comment by escm1990** [comment]
> I suspect it's due to self-signed certificate with SSL .. you have two options :
> 
> 1. Trust that certificate on emulator
> 2. Ignore these self-signed certificate  . see : https://stackoverflow.com/a/34137694/2267723

How can you perform step 1?

**Comment by Shubham-Kumar01** [comment]
If you tried everything, at last, flush your DNS server by using (ipconfig /flushdns) command. After that, it will work just fine.
