### ISSUE TITLE
Release previous resources after next load?

### ISSUE THREAD

**Issue by yihuanzhou** [bumptech/glide#1501]
I have a fairly specific use case question on Glide.

There are instances in my application where I load a new image into a previously used ImageView without a placeholder drawable. This would trigger a clear of the previous request that would release the resources as well as nulling the drawable in the ImageView since there was no placeholder set. I want to avoid this brief period where the ImageView is blank before the new load is complete.

I have tried overriding the onLoadStarted behavior to not set null placeholder drawable but I believe this may lead to the common `java.lang.RuntimeException: Canvas: trying to use a recycled bitmap` crash since the bitmap referenced by the current ImageView was cleared and may have been recycled by the BitmapPool.

Is there a recommended workaround for this type of issue where we release the previous load's resources until after the next load is complete?

**Comment by TWiStErRob** [comment]
#527? Let me know if you need more help.
