### ISSUE TITLE
Images loaded with glide get green tint on android N

### ISSUE THREAD

**Issue by nglro** [bumptech/glide#1502]
Using glide to load images in android N causes them to get a green tint. Works as expected on any other android version. 

**Glide Version**: 3.7.0
**Integration libraries**: volley-integration:1.4.0
**Device/Android Version**: Android Emulator, Genymotion Emulator, both api 24

Glide.with( image.getContext() ).load( path )
                    .diskCacheStrategy( DiskCacheStrategy.SOURCE )
                    .override( width, height ).into( image );

Android M:
![android_m](https://cloud.githubusercontent.com/assets/12345015/19155975/fc1b007c-8be8-11e6-8712-afe50008855e.png)
Android N:
![android_n](https://cloud.githubusercontent.com/assets/12345015/19155974/fc133c2a-8be8-11e6-8c6e-fc98201aec65.png)

**Comment by TWiStErRob** [comment]
Is it this one? #515. More explanation: https://github.com/bumptech/glide/issues/305#issuecomment-112937571

**Comment by nglro** [comment]
No, it's not the same thing. Only manifests on android Nougat. Besides, i`m already using DiskCacheStrategy.SOURCE.

**Comment by TWiStErRob** [comment]
What about `decodeFormat`? Does it still repro with 8888? (Remember to clear the cache!)

**Comment by nglro** [comment]
setting `builder.setDecodeFormat( DecodeFormat.PREFER_ARGB_8888 );` fixed the problem.

Since this increases memory usage, should i only do it for api version > M ?

**Comment by nglro** [comment]
I went with 
```
if( Build.VERSION.SDK_INT >= Build.VERSION_CODES.N ) {
	builder.setDecodeFormat( DecodeFormat.PREFER_ARGB_8888 );
}
```

and now all works good. Thanks for the help.

**Comment by TWiStErRob** [comment]
It's weird that it doesn't happen for below, but good to know. @sjudd maybe default to this behavior in v4? Not sure what you have now.

**Comment by sjudd** [comment]
Sorry I missed this. Can you attach a sample image that reproduces the issue? If so, I can look into it internally.

**Comment by aadbz14** [comment]
I am also using the DiskCacheStrategy.SOURCE. and in my android device which has Android 7.0 this issue persists but no below Android 7.0

**Comment by sjudd** [comment]
The default is now ARGB_8888: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/DecodeFormat.java#L37
