### ISSUE TITLE
images in recyclerview become smaller and smaller as i pull up the list

### ISSUE THREAD

**Issue by venjee** [bumptech/glide#1506]
**Glide Version**:   glide:3.7.0

**Integration libraries**: volley-integration:1.4.0@aar

**Device/Android Version**: all android devices

**Issue details / Repro steps / Use case background**: 
I just load images from network,and show them in 
recyclerview,and when i pull up the list,the images will become smaller and smaller, i am not sure if this behavior is glide's normal behavior or i  did some wrong action. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
 Glide.with(fragmentWeakReference.get())
                   .load(data.get(position).getPicUrl())
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .crossFade()
                    .placeholder(R.drawable.placeholder)
                    .into(holder.image);
```

**Layout XML**:

``` xml
recyclerview item layout
            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignTop="@id/joke_text"
                android:layout_centerHorizontal="true"
                android:id="@+id/joke_img"/>
```

**Stack trace / LogCat**:

``` ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Don't use wrap/wrap on the ImageView. Try to refactor your UI to have at least one match or fixed size on the ImageView, the other can be wrap.

**Comment by venjee** [comment]
hi @TWiStErRob 

thanks for your reply,i change the image view's width to match_parent,however,it seems not work, please check the image 

![screenshot_20161009-161037 1](https://cloud.githubusercontent.com/assets/7614399/19219025/23ab09bc-8e3b-11e6-82fc-14a12fcc0751.jpg)

**Comment by TWiStErRob** [comment]
No good idea fore this. Did you try clearing the cache? Do you have anything in code that messes with the layout params?

**Comment by yuansip** [comment]
@venjee , I suggest you call `holder.image.layout(0, 0, 0, 0)` in `your_recyclerview_adapter.onBindViewHolder`. This help me resolve the issue #1591, which is similar with your issue #1506.
