### ISSUE TITLE
{java.lang.IllegalStateException}Received a resource without any callbacks to notify

### ISSUE THREAD

**Issue by Chunyulo** [bumptech/glide#1512]
**Glide Version**:glide:3.7.0

**Integration libraries**:

**Device/Android Version**:GT-I9500/SM-G900H 5.0/5.0.1(just this two device found)

**Issue details / Repro steps / Use case background**: 

**Stack trace / LogCat**:

``` ruby
Exception: java.lang.IllegalStateException
Cause: null
Message: Received a resource without any callbacks to notify
at com.bumptech.glide.load.engine.d.c(EngineJob.java:145)
at com.bumptech.glide.load.engine.d.a(EngineJob.java:22)
at com.bumptech.glide.load.engine.d$b.handleMessage(EngineJob.java:202)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5951)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

In EngineJob.java, the code is : 

``` java
  private void handleResultOnMainThread() {
    stateVerifier.throwIfRecycled();
    if (isCancelled) {
      resource.recycle();
      release(false /*isRemovedFromQueue*/);
      return;
    } else if (cbs.isEmpty()) {
      throw new IllegalStateException("Received a resource without any callbacks to notify");
    } else if (hasResource) {
      throw new IllegalStateException("Already have resource");
    }
    engineResource = engineResourceFactory.build(resource, isCacheable);
    hasResource = true;

    // Hold on to resource for duration of request so we don't recycle it in the middle of
    // notifying if it synchronously released by one of the callbacks.
    engineResource.acquire();
    listener.onEngineJobComplete(key, engineResource);

    for (ResourceCallback cb : cbs) {
      if (!isInIgnoredCallbacks(cb)) {
        engineResource.acquire();
        cb.onResourceReady(engineResource, dataSource);
      }
    }
    // Our request is complete, so we can release the resource.
    engineResource.release();

    release(false /*isRemovedFromQueue*/);
  }
```

when cbs is empty throw this exception, but cannot find any call this function in glide handle this exception, is there any reason to handle this exception is this way, and how to handle this? Thanks.

**Comment by TWiStErRob** [comment]
I think that code you found is v4, the 3.7.0 code is at https://github.com/bumptech/glide/blob/v3.7.0/library/src/main/java/com/bumptech/glide/load/engine/EngineJob.java#L140-L163

Anyway, the exception is still the same and it sounds like an internal issue with Glide. It may be a nasty sync issue, though I'm not entirely sure. Can you list all your interactions with Glide? (adapter bind, glide module, onLowMemory, custom targets, listeners)
Can you reproduce this? If not can you give some stats on how often it happens live?

**Comment by Chunyulo** [comment]
Yeah, The code is from V4, but the exception is same in the 3.7.0 
This issue is from crash collect report, and i tried this for several hours but cannot reproduce it.
It happens on GT-I9500(5.0.1) 76 times & SM-G900H(5.0) 18 times.
And the glide use in MVP pattern, then there's no idea why this can happen and cannot catch in our code.

**Comment by TWiStErRob** [comment]
I can't prove that this can ever happen statically. If you look at `EngineJob` you'll see that all methods touching `cbs` are called on the UI thread, which means that internally the job should be in cancelled state by `removeCallback` when the callbacks are empty.

Based on this only some really weird usage can break it. And I still suspect ProGuard or your custom code you didn't share yet. ProGuard's keep is not enough. It also optimizes code which can break things. Based on some assumption it can optimize statements into a non-compatible order. @Chunyulo can you please share your compiled APK that did this? (send a private mail if you don't want to publish the name). I'm actually only looking to dedex and decompile `com/bumptech/glide/load/engine/d*.class` to check.

@sjudd shouldn't `if (hasResource) { cb.onResourceReady(engineResource);` also acquire the resource?

**Comment by Chunyulo** [comment]
@TWiStErRob  mail is sent, thanks.

**Comment by TWiStErRob** [comment]
Didn't see anything weird in the decompiled EngineJob, only the names are obfuscated, no optimizations are done. I haven't further ideas.
