### ISSUE TITLE
EGL errors on rapid scrolling

### ISSUE THREAD

**Issue by rcketscientist** [bumptech/glide#1515]
**Glide Version**: 3.7.0

**Integration libraries**:

**Device/Android Version**: Tab S Android 6.0

**Issue details / Repro steps / Use case background**: I have a gallery with a few hundred images, Images load fine slowly.  If I scroll very rapidly it will crash.  Often I'll need to scroll both up and down, occasionally multiple times before it crashes, but it's very repeatable.

Once thumbnails are created for all images I can't seem to recreate the error any longer. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
        Glide.with(mContext)
                .using(new RawModelLoader(mContext))
                .load(values)
                .centerCrop()
                .into(vh.mImageView);
```

**Stack trace / LogCat**:

```
A/OpenGLRenderer: Encountered EGL error 12291 EGL_BAD_ALLOC during rendering

or

E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -2147483646
A/OpenGLRenderer: Encountered EGL error 12299 EGL_BAD_NATIVE_WINDOW during rendering
```

There's never more information than that unfortunately.

I'm doubtful this is even a bug in Glide, mainly I'm hoping someone has seen this error before to point me in a direction.  The only references I can find are actually related to building the OS source.

**Comment by TWiStErRob** [comment]
You have an unfinished thought in the details: "I'm not [...]"

I didn't see this, but it would be worth trying without your custom loader. You say you can repro it pretty consistently, so I suggest your convert all your images to JPEG or PNG and try like that. If you can repro it with that version too, there's likely a problem with Bitmap rendering in general on that device.

Similarly, do you do any recycling or similar in `RawModelLoader`?

**Comment by rcketscientist** [comment]
Thanks, that's a really good idea.  I was actually in the process of setting up another device with a large image set to segregate hardware/OS, but it's a nexus, so space is limited.  I'll give the jpeg set a try first.

There's no recycling in the loader, just a conversion of raw image formats.  There's plenty of error logging in that so there *should* be a message if it's leading to the crash, but just the hundreds of:

```W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!```

and the actual error.  I'll follow up with a jpeg test.

**Comment by rcketscientist** [comment]
Good call, same batch of images converted to jpeg loads.  I'm willing to bet this is a memory issue that's falling through the cracks for some reason.  Never seen so little data on a crash before.

**Comment by TWiStErRob** [comment]
Did you try unfiltered LogCat?

Did you try to log all the loaded values in the loader/fetcher? It may help: maybe it's always crashing on the same image.

Can you share your raw loader? Just to double check it's not doing anything strange.

**Comment by rcketscientist** [comment]
Yah I've tried mutliple combinations of filtering and scanning full verbose.  It's not the same image as I can't get it to crash in the same location.  It's just a matter of lots of scrolling which implies volume and memory.  I'll run some memory tests later.  Thanks for the help, I'll follow up with anything relevant.

Can't share the loader.  It involves TONS of native.

**Comment by TWiStErRob** [comment]
That pretty much explains the native crash... what you allocate has to be valid until the Bitmap is recycled. Maybe there's a flag that you need to change in the native decoder, or the decoder is not thread safe (multiple fetchers can run at the same time on different threads).

**Comment by rcketscientist** [comment]
What is the threading policy of glide.  Is that:

```com.bumptech.glide.load.engine.executor```

If so, there should be no more than `core count` instances of a ModelLoader at any time?

**Comment by TWiStErRob** [comment]
Most of the bookkeeping stuff happens on the UI thread, so that's safe. The parallelized part on that executor is the actual fetching and transformations. So as far as I know there's 1 instance of the loader factory (you register), which creates 1 cached loader (in `GenericLoaderFactory`), which will create multiple fetchers for each load. I don't think there's an upper limit on fetchers alive at any single point in time, because the fetchers get created pretty early. If you fire up 100 loads with all different models, it'll create 100 fetchers which will queue up for the "core count" threads available. It's possible that a created fetcher won't be used at all, if their `getId` based on their models match (see `Engine.load`).
