### ISSUE TITLE
Check an Array of images downloaded or not

### ISSUE THREAD

**Issue by renjithkrish89** [bumptech/glide#1524]
How can I check whether an Array of image already cached or not.
In my application there is a offline reading option . So user can able to download the image for the offline.  So I implemented the downloaded option with user can able to cancel the download at any time. Currently I downloading using the Glide download only feature.I need to show it in the application that the pages are offline(I mean cached or downloaded), So I need to check all the files to be downloaded or not or offline reading. How can I check an array of images that is cached or downloaded in the Application.

**Comment by TWiStErRob** [comment]
First, this is not what Glide cache is designed to do. Its purpose is to make Glide able to quickly show images. Cache is volatile by definition, so LRU may simply evict some of your pages without your knowledge. Your downloadOnly should be replaced with a networking library where you save all the images into a folder within your app's data folder. Then you can check if all the files exist really easily and also give the user the ability to remove a "pinned book" fully without clearing the whole cache. In this case (when using local File objects) you can simply skip Glide duping your file in cache and wasting precious space by using `DiskCacheStrategy.NONE` for full loads and `RESULT` for thumbs.

If you really want to hack around, you can use a `NetworkDisablingLoader` to start the load. This will prevent Glide from loading from network and only decode from cache. Adding a listener or special target can be used to capture if the load from cache finished or failed. The drawback is that you have to load the actual full image to check for existence. There may be a better way, but it'll be always a hack when compared to the above solution where you can just list the files in a folder to check for existence.

See #509 and related for more info.
