### ISSUE TITLE
Add Builder Option for Ripples

### ISSUE THREAD

**Issue by eygraber** [bumptech/glide#1525]
It would be nice if there was a way to wrap the final `Drawable` in a `RippleDrawable`. What I've been doing now is a little hacky:

```
Glide.with(context)
        .load(photos[position])
        .centerCrop()
        .crossFade()
        .listener(new RequestListener<String, GlideDrawable>() {
          @Override
          public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
            imageView.setImageDrawable(new RippleDrawable(colorStateList, resource, null));
            return true;
          }

          @Override public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) { return false; }
        })
        .into(imageView);
```

**Comment by TWiStErRob** [comment]
Yes, that is the hackiest of the solutions. You could make a custom target (extending `ImageViewTarget`) that handles this, so it's easy to reuse and handles animations (which you disabled with listener)

The best way is to write a transcoder (your builder option) that wraps the default transcoder and actually returns the ripple, but this way GIFs may not work if Glide chooses the wrong target. It should be possible to do it with a little extra code here and there, but the custom target solution makes Glide unaware of the ripple and hence everything should work as usual.

Let me know if you need more info.

**Comment by eygraber** [comment]
@TWiStErRob Is this how you would do it with the `ImageViewTarget`?

```
.into(new ImageViewTarget<GlideDrawable>(imageView) {
          @Override 
          public void setDrawable(Drawable drawable) {
              view.setImageDrawable(new RippleDrawable(colorStateList, resource, null));
          }

          @Override 
          public void setResource(GlidDrawable resource) {
              setDrawable(resource);
          }
        });
```

**Comment by TWiStErRob** [comment]
Yep, that looks ok. To clear up a confusion that you may have:
 * `setDrawable` is called by animation, you will get a `TransitionDrawable` there usually.
 * `setResource` is called when there was no animation, then the raw transcoded resource is passed to you.

If you want to replace the stuff inside `TransitionDrawable` you'll have to override `onResourceReady` and call super with a wrapped drawable, but be careful because in that case `setResource` doesn't need to re-wrap it. Also if you want it to work for placeholder/error too, you need to override `onLoadStarted`/`onLoadFailed`.

**Comment by eygraber** [comment]
So if I override `onResourceReady` and return the wrapped `Drawable` there it'll cover all the cases? I don't need it for the error or placeholder.

**Comment by TWiStErRob** [comment]
Yes, quite possibly `onResourceReady` alone with `super(new Ripple(resource), anim)` is enough; it simulates Glide's transcoder behavior.

**Comment by nibuen** [comment]
Was trying to convert to this as well but can't figure out how to convert RippleDrawable to GlideBitmapDrawable to return on the super call, or should I have used a different transcoder before this?

**Comment by TWiStErRob** [comment]
@nibuen you can try .asBitmap with a custom transcoder.
