### ISSUE TITLE
Lots of large size image decoding requests in Recyclerview may cause process killed on Galaxy S3

### ISSUE THREAD

**Issue by shchao** [bumptech/glide#1527]
**Glide Version**: 3.7.0

**Integration libraries**: none

**Device/Android Version**: Galaxy S3/GT-I9300 4.3

**Issue details / Repro steps / Use case background**: 

I'm implementing a media picker by recyclerview with 3 columns GridLayoutManager.
While browsing some album contains 100+ large size images (above 4000 x 4000),
current process may be killed by system on Galaxy S3 (4.3 Jelly Bean). There is no OOM message in logcat.

Currently, it only happened in the first time on Galaxy S3. After disk cache has been created, it didn't happen again. I have tested the implementation on Nexus 6 (6.0.1), Nexus 4 (5.0), HTC Butterfly (4.4.2) with the same testing image set, all works fine.

It should be related to memory usage.  In somehow, system killed current process due to lack of memory.

Does anyone has the same problem ? is there any suggestion or solution to the issue ? 
Thanks

**More observation** : 

1. RAM size : Galaxy S3 (1G). Nexus 6 (3G), Nexus 4 (2G), Butterfly (2G)

2. MemorySizeCalculator: Calculated memory cache size: 7.03 MB pool size: 14.06 MB memory class limited? false max size: 25.60 MB memoryClass: 64 isLowMemoryDevice: false

3. Each imageview size is 240x240, and DecodeJob logs EngineKey:{url+[240x240]+...}. It seems decoding may respect the imageview size.

4. If java heap size growing to ~50 mb, process will be killed.

5. While scrolling, ashmem (pss) may boost to 2~300 mb peak and then went down to 4~50 mb suddenly (dumpsys meminfo) 

6. We also observed [Google Photos](https://goo.gl/MpBfK6) has the same issue. Process was killed while browsing the same testing image set.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

Adapter load request
```java
Glide.with(Fragment.this).load(url).into(imageview)
```
Adapter clear request
```java
public void onViewRecycled(RecyclerView.ViewHolder holder) {
     Glide.clear(holder.imageview);
}
```

**Layout XML**: (Adapter item layout)

```xml
<FrameLayout 
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent">
       <my.custom.SquareImageView
            android:id="@+id/image"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

         <!-- other views won't affect imageview layout--> 
</FrameLayout>
```

**Stack trace / LogCat**:
```ruby
none
```

**Comment by TWiStErRob** [comment]
There's no process crash without a trace. Please take a look at LogCat, turn off all filtering if you need to (the crash may be logged under system processes, not your package name). Also take a look at #466 (my take: https://github.com/bumptech/glide/issues/466#issuecomment-169364336), it feels similar to your issue.

**Comment by shchao** [comment]
@TWiStErRob Thanks for quick response.

**LogCat**
Following are excerpt but suspicious log
```ruby
10-17 17:45:03.830 24654-25152/com.swiitt.pixgram D/skia: --- SkImageDecoder::Factory returned null
10-17 17:45:03.845 24654-25154/com.swiitt.pixgram D/skia: --- SkImageDecoder::Factory returned null
10-17 17:45:03.845 24654-25154/com.swiitt.pixgram D/skia: --- SkImageDecoder::Factory returned null
...
10-17 17:45:04.050 24654-25152/com.swiitt.pixgram D/dalvikvm: GC_FOR_ALLOC freed 1K, 16% free 27783K/33044K, paused 22ms, total 22ms
10-17 17:45:04.050 24654-25152/com.swiitt.pixgram I/dalvikvm-heap: Grow heap (frag case) to 31.361MB for 1843216-byte allocation
10-17 17:45:04.075 24654-25152/com.swiitt.pixgram D/dalvikvm: GC_FOR_ALLOC freed 0K, 16% free 29583K/34848K, paused 21ms, total 26ms
...
10-17 17:45:04.850 2357-2368/? I/ActivityManager: Process com.android.contacts (pid 24261) (adj 15) has died.
10-17 17:45:04.850 2357-3242/? I/ActivityManager: Process com.sec.android.app.music:service (pid 24386) (adj 15) has died.
10-17 17:45:04.865 2357-8808/? I/ActivityManager: Process com.sec.android.app.clockpackage (pid 24495) (adj 11) has died.
10-17 17:45:04.870 2357-3248/? I/ActivityManager: Process com.android.vending (pid 25044) (adj 9) has died.
10-17 17:45:04.880 2357-3246/? I/ActivityManager: Process com.facebook.katana (pid 24693) (adj 13) has died.
...
10-17 17:45:08.765 24654-25154/com.swiitt.pixgram D/dalvikvm: GC_FOR_ALLOC freed 5708K, 24% free 27281K/35800K, paused 262ms, total 264ms
...
10-17 17:45:10.990 2357-8808/? I/ActivityManager: Process com.google.process.gapps (pid 25383) (adj 0) has died.
10-17 17:45:11.035 2357-2745/? I/ActivityManager: Process com.android.nfc:handover (pid 25401) (adj 0) has died.
10-17 17:45:11.270 2357-2745/? I/ActivityManager: Process com.swiitt.pixgram (pid 24654) (adj 0) has died.
```
Complete logcat is placed on [google drive](https://goo.gl/1lNjp6)

**Observation**

1. It seems more like the process was killed by low memory killer, but not process crash.
    There is no OOM exception and ActivityManager killed background processes from adj 15, adj 13, to adj 0.

2. By the suggestions of #466, I tried with ```asBitmap()``` and fixed size ```override(100,100)``` or  ```.loadFromMediaStore()```, the issue still happens.

```java
Glide.with(Fragment.this).asBitmap().override(100,100).into(imageview)
Glide.with(Fragment.this).loadFromMediaStore(uri).into(imageview)
```

**Comment by shchao** [comment]
@TWiStErRob

I also tried the [APK](https://github.com/ruanml/SampleMisplaced/blob/master/bin/SampleMisplaced.apk) mentioned in #466 with my [testing image set](https://drive.google.com/drive/folders/0B1q2gZvs0gHeMFJCMzdtcGhrSTQ?usp=sharing) on Galaxy S3.
The process `com.sample.samplemisplaced` was also killed if I scrolled the image set multiple times fast enough.

**Comment by TWiStErRob** [comment]
I don't think it's low memory. Android wouldn't kill a resumed activity, that would be really weird.

> W/ActivityManager: Force removing ActivityRecord{430ff8e0 u0 com.swiitt.pixgram/com.swiitt.mediapicker.activity.MediaPickerActivityV3}: app died, no saved state

for me suggests that that the app disappeared ("has died"). I didn't see any SIGKILL or similar.

The last log before "has died" looks like an ad trying to initialize a WebView. Any idea about that?

> There's no process crash without a trace.

I may revoke this, as a native OOM crash may not have enough memory to execute logging and stuff.

> V/MediaPlayerService: Create new media retriever from pid 24654

Do you think it's possible that these retrievers are not freed or they don't free their buffer after failing to decode your images?

**Comment by shchao** [comment]
@TWiStErRob Thanks a lot for your quick response.

> The last log before "has died" looks like an ad trying to initialize a WebView

WebView initialization is because of integrating Admob NativeExpressAdView in the fragment.
I tried to remove NativeExpressAdView from the fragment and WebView initialization log didn't show. However, the issue still happened.

> V/MediaPlayerService: Create new media retriever from pid 24654

The media picker lists also video items and uses Glide to load video thumbnail. 
I'm sure Glide handles the resource release very well.  And I tried to remove listing of video items, no more "Create new media retriever from pid 24654" dump. But, the issue still happened.

**Comment by TWiStErRob** [comment]
@shchao are the images progressive?
@sjudd any other ideas?

**Comment by shchao** [comment]
@TWiStErRob
Yes!! several images are progressive. Once I filtered out those progressive jpegs, the issue did not happen again. Thanks for your quick and helpful advices.

I'm going to try your advice from [#466 comment](https://github.com/bumptech/glide/issues/466#issuecomment-198584324) 

> fall back to a single decoder thread in a GlideModule setup

Please help me to close the issue, thank you :)

**Comment by TWiStErRob** [comment]
*You just needed to press "Close and comment" instead of "Comment" ;)*... or do you want more help?

**Comment by shchao** [comment]
No, I just misunderstand that only project manager can close an issue. Thanks you :)

**Comment by TWiStErRob** [comment]
Yes, that's correct, init is once and final. However you can inject any tread pool you want (see `GlideBuilder.createGlide` for defaults). The custom thread pool can be dynamic and accessible throughout your app and you can change the thread count on the fly as you wish.

---

Another option is to have a the default thread pool, but write a custom decoder that wraps the default one and the logic goes like:
```java
decode(stream) {
    if (peek(stream) is progressive) {
        synchronised { return default.decode(stream); }
    } else {
        return default.decode(stream);
    }
}
```
Check out [`PaletteCacheDecoder`](https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/github/_1272_palette_cache/PaletteCacheDecoder.java) from #1272 for example delegation like this.

**Comment by shchao** [comment]
The second solution looks neat and elegant, I will try this one.
Thanks Robert :)
