### ISSUE TITLE
RecyclerView & StaggeredGridLayoutManager

### ISSUE THREAD

**Issue by rfazi** [bumptech/glide#1530]
**Glide Version**: 3.7.0

**Integration libraries**: NO

**Device/Android Version**: LG G3 D855 / 6.0

**Issue details / Repro steps / Use case background**: I use an ImageView in a StaggeredGridLayoutManager. If scroll fast up and down the ImageView overlaps. If i don't use Glide and use src="@drawable/example" in xml there's no bug.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).load(mStringArrayList.get(position)).centerCrop().into(Holder.mImageView);
// OR - WITH SAME RESULT
GlideDrawableImageViewTarget imageViewTarget = new GlideDrawableImageViewTarget(Holder.mImageView);
Glide.with(context).load(mStringArrayList.get(position)).centerCrop().into(imageViewTarget);

// context = Fragment from Activity;
// mStringArrayList = ArrayList<String>;
// Holder.mImageView = ImageView;
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
           android:id="@+id/row_profilo_pager_flare_image"
           android:layout_height="125dp"
           android:layout_width="125dp" />
```

**Video of the bug**:
https://youtu.be/RfSbClLzEVs

**Comment by TWiStErRob** [comment]
Wow, never seen that before, maybe you found a bug in `StaggeredGridLayoutManager`. It looks like some views are being removed from the flow and just hanging around.

Try to replace your Glide line with these, to see if it reproduces:

 * `holder.mImageView.setImageDrawable(R.drawable.example)`
 * `holder.mImageView.post(new Runnable() { /* same as above */ })` 
 * `Glide.with(context).load(R.drawable.example).into(holder.mImageView)`

This helps isolate the actual culprit.

Do you do anything weird with the views? For example, change their parent, set layout params, use some kind of sticky thing on the RV.

**Comment by rfazi** [comment]
With these three methods, there are no problems.
```java
holder.mImageView.setImageDrawable(R.drawable.example)
holder.mImageView.post(new Runnable() { /* same as above */ })
Glide.with(context).load(R.drawable.example).into(holder.mImageView)
```

The view isn't modified, it's original.
With the ImageHolder i have and AdsHolder for advertising that have full span.
I tried to remove the full span and reduce the imageview width and height with no result:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
           android:id="@+id/row_profilo_pager_flare_image"
           android:layout_height="55dp"
           android:layout_width="55dp" />
```
[![Screenshot_2016-10-18-20-20-54.png](https://s17.postimg.org/irn1ph973/Screenshot_2016_10_18_20_20_54.png)](https://postimg.org/image/6d09p5hor/)
The bug persist.

**Comment by rfazi** [comment]
@TWiStErRob 
UPDATE: I used Volley and there are no bugs. The problem is Glide.

**Comment by TWiStErRob** [comment]
Volley is a networking library, Glide is an image loader. If you used Volley to load an image is probably means that the image was loaded at full resolution, wasting a lot of memory. You can get the same behavior with `.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)`.

Would it be possible to create a repro app for this?

**Comment by rfazi** [comment]
@TWiStErRob 
https://github.com/rfazi/GlideReproApp

I found the bug: check TODO in MappaturaDetailsFragment.java

**Comment by TWiStErRob** [comment]
Wow, you really stumbled into something, I tried the following:
 * remove coordinator layout and behavior
 * change RecyclerView to match-match (was match-wrap); in v24 I think they changed something incompatible regarding wrapping, see [23.2.0 recyclerview changes](https://developer.android.com/topic/libraries/support-library/revisions.html) and it's hard to imagine that your app wants to display a wrapped list anywhere).
 * static fragment
 * inline fragment
 * `setHasFixedSize` has no effect (true should be valid if you use match-match)
 * fix `getItemViewType` to properly recycle views (all numbers have the same type, you should only use a different type when you have stuff like in your video above, but even then only 2-3 different ones)
 * change to `GridLayoutManager` (no staggered)

None of them helped, but then I had a revelation: `.dontAnimate()`. It fixes the issue. Here's a full repro *without Glide* and above steps applied:

```java
public class MainActivity extends AppCompatActivity {
	@Override protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		RecyclerView list = new RecyclerView(this);
		list.setLayoutParams(new LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT));
		setContentView(list);

		list.setLayoutManager(new GridLayoutManager(null, 3));
		list.setAdapter(new Adapter(this));
	}

	static class Adapter extends RecyclerView.Adapter<Adapter.ImageHolder> {
		private final Context context;
		private final List<Integer> colors = new ArrayList<>();
		private final Random rnd = new Random();

		Adapter(Context context) {
			this.context = context;
			for (int i = 0; i < 150; i++) {
				colors.add(Color.argb(255, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256)));
			}
		}

		@Override public int getItemViewType(int position) { return 1; }
		@Override public int getItemCount() { return colors.size(); }

		@Override public ImageHolder onCreateViewHolder(ViewGroup parent, int viewType) {
			ImageView image = new ImageView(context);
			int fixed = (int)TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 120,
					context.getResources().getDisplayMetrics());
			image.setLayoutParams(new GridLayoutManager.LayoutParams(LayoutParams.MATCH_PARENT, fixed));
			return new ImageHolder(image);
		}

		@Override public void onBindViewHolder(final ImageHolder holder, int position) {
			int color = colors.get(position);
			// for easier identification in debug (breakpoint)
			holder.image.setContentDescription(position + ": " + color);
			holder.image.setImageDrawable(new ColorDrawable(color));
			holder.image.clearAnimation();
			AlphaAnimation animation = new AlphaAnimation(0f, 1f);
			animation.setDuration(300);
			holder.image.startAnimation(animation);
		}

		static class ImageHolder extends RecyclerView.ViewHolder {
			final ImageView image;
			ImageHolder(View v) {
				super(v);
				image = (ImageView)v;
			}
		}
	}
}
```
However you don't want to not use Glide I guess, so here's that:
```java
String url = "https://dummyimage.com/250x250/" + String.valueOf(color) + "/fff.png&text=" + (position + 1);
Glide
		.with(context)
		.load(url)
		//.skipMemoryCache(true) // makes the bug happen more often
		//.dontAnimate() // fixes the bug, but disables fade in
		.into(holder.image);
```
I don't know about you, but I like the fade in animation more and more, so to keep it you need to apply this fix instead (snippet from https://github.com/bumptech/glide/issues/1415#issuecomment-239784760):
```java
// in adapter
@Override public void onViewDetachedFromWindow(ImageHolder holder) {
	holder.image.clearAnimation();
}
```
this will allow the ImageView to disappear properly (Views are forcefully displayed while animation is running), for more details see https://github.com/bumptech/glide/issues/952#issuecomment-231062728
