### ISSUE TITLE
Glide Can't load local Vector drawable?

### ISSUE THREAD

**Issue by kooeasy** [bumptech/glide#1532]
Glide Can't load local Vector drawable?

` Glide.with(this)
                .load(R.drawable.ic_1f3ad)
                .into(image);`

this ic_1f3ad is a Vector drawable!

I use 3.7.0  or 4.0.0-SNAPSHOT can't load ! 

I want know this is glide can't support or my fault？

**Comment by TWiStErRob** [comment]
The result would be no different than `image.setImageResource(R.drawable.ic_1f3ad)`.
This is a duplicate of #794, tracking issue is #350.
Try `load(null).fallback(R.drawable.ic_1f3ad)` or `load("").error(R.drawable.ic_1f3ad)` if you really want to use Glide.
Note: I've been able to use animated vectors as placeholders: #1261
Let me know if you need help.

**Comment by kooeasy** [comment]
Thanks !

**Comment by AndroidDeveloperLB** [comment]
Is it possible to load VectorDrawable from byte array or file outside of current app, though?
The only thing I've found is [this](https://stackoverflow.com/a/62114760/878126), but it uses reflections on private API...
