### ISSUE TITLE
Can i download mp3 files using glide

### ISSUE THREAD

**Issue by sant527** [bumptech/glide#1534]
Does glide have facility to load mp3 files from server. I want the file to be downloaded in cache and then played in mediaplayer. And later whenever i want i can play.

**Comment by TWiStErRob** [comment]
You can with custom loader/fetcher/decoder/encoders, but I'm not sure it's worth it. For one, the downloaded mp3 would be in Glide cache, which means it's volatile and it is not guaranteed that it'll stay there (LRU may evict it). Also there's not really an intermediate representation for mp3 audio. MediaPlayer supports `http` streams as I saw from the code. If you go with Glide you would have to copy the stream you get from cache to a File and then use that in a MediaPlayer. Take a look at `downloadOnly` if you want to use Glide as a networking library (which it isn't, same caching issue applies).

**Comment by sant527** [comment]
do you have any example of downloadonly

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Loading-and-Caching-on-Background-Threads#downloadonly
https://www.google.com/search?q=glide%20downloadonly
