### ISSUE TITLE
Download and resize GIF to a file

### ISSUE THREAD

**Issue by tomislavturcic** [bumptech/glide#1535]
I'm trying to download a .gif file to external storage. I want them to be 250 x 250 pixels.
I've tried this and a few variations with downloadOnly(int w, int h).

``` java
byte[] bytes = Glide.with(context)
                    .load(url)
                    .asGif()
                    .toBytes()
                    .into(250, 250)
                    .get();
file = new File(fileName);

FileOutputStream fileWriter = new FileOutputStream(file);
fileWriter.write(bytes);
fileWriter.flush();
fileWriter.close();
```

Downloaded .gif file keeps the original size though.

**Comment by TWiStErRob** [comment]
With `downloadOnly` it doesn't matter what size you pass in, that size is used for bucketing only (see `BaseGlideUrlLoader.getUrl`); `downloadOnly` doesn't decode and encode the image, it just fills the SOURCE cache (which is the original remote stream).

I think that `toBytes` is a good way of doing it, but this version will only work if the input image is larger than 500px. You need to add a transformation to tell Glide how you want the frames to transform into the target size (250x250). Simply pop a `.fitCenter()` or `.centerCrop()` on it. When you're using normal `into(imageView)` this is hidden from you (see `GenericRequestBuilder#into(ImageView)`).

**Comment by tomislavturcic** [comment]
Ok, but how can I use .fitCenter() in conjunction with toBytes() ?

**Comment by TWiStErRob** [comment]
Good point, try adding this after `.toBytes()`:
```java
.transform(new GifDrawableTransformation(new CenterCrop(context), Glide.get(context).getBitmapPool()))
```

**Comment by tomislavturcic** [comment]
That actually works. Thanks for quick replies :)

**Comment by TWiStErRob** [comment]
Let's leave it open as a reminder that the API is not complete for `asGif.toBytes`

**Comment by tomislavturcic** [comment]
Hm, after a few tests, something still doesn't work right. Files sometimes still get downloaded in original size. I'll try playing around with different DiskCacheStrategies.

**Comment by TWiStErRob** [comment]
Are those who don't work smaller or larger than 250?

**Comment by tomislavturcic** [comment]
Larger. They're mostly around 300 x 294 pixels. I've also tried to resize to much smaller sizes (50 x 50). Setting DiskCacheStrategies doesn't have much effect. I'll try to test with regular images to see what kind of results that yields.

**Comment by tomislavturcic** [comment]
I've managed to test this with regular .png files and it works flawlessly. 
Here's the code that I've tried for png files:

`private byte[] downloadPng(String url) throws ExecutionException, InterruptedException {
        return Glide.with(context)
                .load(url)
                .asBitmap()
                .toBytes()
                //.centerCrop()
                .into(150, 150)
                .get();
    }`
Works with and without transformation. 
Maybe a bug with resizing .gif files ?

**Comment by TWiStErRob** [comment]
So you're saying that GIF files don't apply the transformation with toBytes at all or that sometimes they work and sometimes they don't?

*(Press the pencil in the top right of your previous comment, I fixed the formatting (see also [the template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and the "Styling with Markdown is supported" next to the "Comment" button for more)*

**Comment by tomislavturcic** [comment]
Resizing of the .gif file sometimes works and sometimes doesn't. 
I've been unable to figure out how or why it happens. At first I thought it might have something to do with caching, but after playing around with different DiskCacheStrategies, I've been unable to come to a conclusion.

**Comment by tomislavturcic** [comment]
It's been a while since this issue has been posted. I've come back to it because it popped up again in my app. This time I have more conclusive results. 
Gifs on my server are 300 x 294 pixels. I needed them smaller.
Using a DiskCacheStrategy.ALL or DiskCacheStrategy.RESULT (default), first download results in an image that isn't resized. Subsequent downloads produce expected results. Not sure what could be causing this.

**Comment by carlosheiras17** [comment]
this works for glide 4.0 ? i can't reach it.

**Comment by sjudd** [comment]
Glide v4 has removed GIF re-encoding. There is still an integration library which includes the original GIF encoder which could be used directly or registered as an Encoder in Glide. I'm going to close this for now since I don't think we're going to make any improvements for this particular use case in v4.
