### ISSUE TITLE
Glide load long image error。

### ISSUE THREAD

**Issue by shizhongyu** [bumptech/glide#1537]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
*User give short description error.*

Please fill in the issue template, you essentially gave as much info as "there was an error".

Check out https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling to see how to gather more info about an error, then do some research on the error message before continuing here.
