### ISSUE TITLE
How to design Glide

### ISSUE THREAD

**Issue by krait8064** [bumptech/glide#1539]
Great honor to every seniors for developing glide.I am just a junior android developer and I'm quite interested in how to design a image-loading-frame.There are many docs for how to use glide but few about how to design it.Plz try to tell me briefly the design-progress just like thinking about cache first or network first and what interface shall we design.Thank u ,everyone,it's late but early for ur perfect sulotion for my question,again!

**Comment by colinrtwhite** [comment]
It's probably tough for the developers to neatly and quickly sum up the design process of Glide. Instead I'd recommend looking at the [design doc for the upcoming Glide 4.0](https://docs.google.com/document/d/13jhhlAqcKU2kweY2PlKW8HMPgTxXvu3Qv8A8dPBJP0Q/edit#heading=h.z0ow8za7i4ej) to get a sense of how they design the API structure.

**Comment by TWiStErRob** [comment]
Also check out https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit

However, I don't think you should roll your own. There are great libs out there, which do the job: Glide, Picasso, UIL, Fresco; and you'll just have many problems that are already solved in those. Just pick one and start using it. After a year of daily usage of one or more of these, solving a different problem every day, you can think about designing your own.

If you really want to get involved in writing code for image loading frameworks you should consider contributing to one of these, for example for Glide there are limited human resources, but a lot of enhancement requests (see issue tracker labels: enhancement, feature, bug); feel free to pick one and implement/fix it. You'll get great insight into the inner workings if you force yourself to work on something, that's how I got involved as well.

**Comment by krait8064** [comment]
Thanks very much!It's quite an useful answer to my question,thanks for ur patience again,buddy!
