### ISSUE TITLE
Glide does not open images stored on FTP

### ISSUE THREAD

**Issue by waideman** [bumptech/glide#1540]
Glide is not loading images when it is stored on a FTP server.

```
    Glide.with(mContext).load("ftp://qtt:qtt@//192.168.43.1:2221/images/DJI_0052.JPG")
            .thumbnail(0.5f)
            .crossFade()
            .diskCacheStrategy(DiskCacheStrategy.ALL)
            .into(holder.thumbnail);
```

**Glide Version**: 3.7.0

Works when I store the images on Apache, but fails for FTP, with or without authentication.

**Comment by TWiStErRob** [comment]
The url is not valid: `schema://user:pass@host:port/path` `//` is not valid in host name.

**Comment by TWiStErRob** [comment]
I can't help you with "fails"/"not working", what is the exception? (add a [listener](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling))
