### ISSUE TITLE
Glide doesn't support to play APNG?

### ISSUE THREAD

**Issue by axkza** [bumptech/glide#1542]

**Comment by TWiStErRob** [comment]
Glide is just a fancy wrapper around BitmapFactory + a software level GIF decoder written in Java.
So whatever Android supports, Glide supports: https://developer.android.com/guide/appendix/media-formats.html I think Fresco have support for more formats based in its monstrous size.

If you want to add this support, you could do it based in GIF, and create a PR. Maybe it is possible to utilise BitmapFactory to decode individual frames if the format is structured that way.
