### ISSUE TITLE
Why doesn't Glide clear targetView field in the request after calling clear()

### ISSUE THREAD

**Issue by electrolobzik** [bumptech/glide#1543]
**Glide Version**: 3.7.0

**Issue details / Repro steps / Use case background**: 

I am trying to cancel `Glide` request when my fragment is replaced. I am calling `Glide.clear(imageView)` in `onDestroyView`.
But than I get a report from `LeakCanary` about leak in `GlideDrawableImageViewTarget.view`.
How should I cancel the request and clear the reference from `RequestManager` to my view?

There are screenshots from LeakCanary and AS. (`AvatarView extends ImageView`)

![LeakCanary report](http://i.imgur.com/B9Q0fyK.png)
![Screenshot from AS debug](http://i.imgur.com/y6fkRzE.png)

**Comment by TWiStErRob** [comment]
If you want to kill all requests in `onDestroyView` you need to call `Glide.with(this).onDestroy()`. Normally that is called on `onDestroy`.

**Comment by electrolobzik** [comment]
- What is `Glide.clear()` for and what is the difference between it and `onDestroy()` except the second is called only for the concrete `RequestManager`?

- Why `Glide` is clearing target views only in `onDestroy()` of a fragment but not in 'onDestroyView()'? Keeping the reference to the target view is useless after 'onDestroyView()' and I suppose it should be cleared automatically.

**Comment by electrolobzik** [comment]
- How can I do the same thing that `onDestroy()` does but only for concrete view?

**Comment by TWiStErRob** [comment]
`Glide.clear` clears the target which means the corresponding method in the target implementation is called, this usually sets the placeholder. See #1337 for more in destroy. Glide doesn't know whether the target holds a view or not, a `Target` is more abstract than that. This means that Glide may clear stuff that is still required in case the fragment is reattached.

You may have found a bug, but I'm not sure yet. In `into` there's a call that removes the request from the tracker. It feels like clear should do the same. Check the sources of `RequestManager`, `RequestTracker` and `Glide.clear` for more on how you can destroy parts. I have a feeling that it's all or nothing. Again, Glide doesn't know which request is for a particular view, but if `clear` were to totally remove it from the tracker there would be no problem.

**Comment by electrolobzik** [comment]
Thank you for reply. But I still don't get idea about destroying views. Even if fragment is reattached it will not be able to use old views after `onDestroyView` isn't it? If so why not add another lifecycle callback for `onDestroyView` and make this clear job there?

**Comment by TWiStErRob** [comment]
I agree that the view refs are unusable in the future. But Glide doesn't know about views. Consider: `Glide.with(this).load(stuff).into(new MyCustomTargetThatHasNothingToDoWithViews())`. Any result loaded into this may ve valid until the fragment is destroyed.

>  why not add another lifecycle callback for onDestroyView and make this clear job there?

Did you read #1337? 

---

You might be interested in #616, though it may not apply here.

**Comment by electrolobzik** [comment]
But we can just add condition for ViewTarget which also stores a strong view reference. It should be enough for the most cases. What do you think?

**Comment by electrolobzik** [comment]
After digging into the code found that code from the `master` has method `RequestManager::clear(target)` and doesn't have `Glide.clear(target)`. This should has been added after `3.7.0`. Seems that latest code from the `master` does what I expected `Glide.clear(target)` should do. What are plans about releasing it?

I am going to continue discussion of `onDestroyView` in #1337 because it is about absolutely the same problem. 

Thank you.

**Comment by TWiStErRob** [comment]
For using the new code see #1473
