### ISSUE TITLE
How can I use listener with downloadOnly method? 

### ISSUE THREAD

**Issue by nancyyihao** [bumptech/glide#1546]
**Glide Version**: 3.7.0

**Integration libraries**: okhttp:3.2.0

**Device/Android Version**: Android-5.1

**Issue details / Repro steps / Use case background**: 
I want to use a listener with downloadOnly method，but the listener's callback is never called.

**Here is my code**:
```java
DrawableTypeRequest builder = (DrawableTypeRequest) getRequestManager(BaseApplication.getInstance()).load(url);
            builder.listener(new RequestListener() {
                @Override
                public boolean onException(Exception e, Object o, Target target, boolean b) {
                   // never call
                    Log.e("pic", String.valueOf(e));
                    return false;
                }

                @Override
                public boolean onResourceReady(Object o, Object o2, Target target, boolean b, boolean b1) {
                    //never call
                    return false;
                }
            });
            builder.downloadOnly(new SimpleTarget<File>() {
			@Override
			public void onLoadFailed(Exception e, Drawable errorDrawable) {
				// work fine
			}

			@Override
            public void onResourceReady(File resource, GlideAnimation glideAnimation) {
				// work fine
            }
        }); 
```

**Comment by TWiStErRob** [comment]
If you can't chain all the lines one after the other without a local variable, then that request is not valid. See https://github.com/bumptech/glide/issues/406#issuecomment-95617989

Using a SimpleTarget is almost the same. If your method receives a RequestListener you can always call the appropriate methods from the target callbacks. The boolean values are irrelevant for downloadOnly (always false).
