### ISSUE TITLE
 Could not get unknown property 'assembleDebug' for project ':library' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by x-dragonet** [bumptech/glide#1547]
Error:(68, 1) A problem occurred configuring project ':samples:gallery'.
> A problem occurred configuring project ':library'.
> Could not get unknown property 'assembleDebug' for project ':library' of type org.gradle.api.Project.

who can tell me reason?

**Comment by TWiStErRob** [comment]
Not much idea. Which branch is this? Did you write the code that fails? If so try `proj.tasks.assembleDebug`.

**Comment by x-dragonet** [comment]
My colleagues had solved this problem for me. Thank you anyway

**Comment by David-Kuper** [comment]
Error (69,46),a problem occurred when i run the sample module . how to solve the problem?
`* Where:
Build file '/Users/malingyi/AndroidStudioProjects/glide/library/build.gradle' line: 69

* What went wrong:
A problem occurred configuring project ':samples:giphy'.
> Could not resolve all dependencies for configuration ':samples:giphy:_debugApk'.
   > A problem occurred configuring project ':library'.
      > Could not get unknown property 'assembleDebug' for project ':library' of type org.gradle.api.Project.
`

**Comment by TWiStErRob** [comment]
Same question: which branch? Did you modify anything? What version of Gradle are you using? Did you try a clean build in the command line?

**Comment by liwujun11111** [comment]
@TWiStErRob  I used the master branch.and The result was builded fail that the same as what David-Kuper has said.

**Comment by junaidTbox** [comment]
i have cloned with master branch and using latest android SUPPORT_V4_VERSION=25.3.1,
SUPPORT_V7_VERSION=25.3.1, ANDROID_GRADLE_VERSION=2.3.0 .
https://cloudup.com/c38CBvTf5ga

**Comment by TWiStErRob** [comment]
@junaidTbox Did you try a clean build in the command line? **Before** changing anything in the code! If that works, then you can try changing variables and stuff.

**Comment by junaidTbox** [comment]
i just download the code , didn't change a bit , clean build -> sync gradle and then make build.
i switch to old commits as well but same error.

**Comment by TWiStErRob** [comment]
Do a `gradlew clean buildArchives`, and once that's successful import it in IDEA/AS.
