### ISSUE TITLE
when scan the bluetooth devices  of ibeacon, Glide+okhttp3 load image very slow from server.

### ISSUE THREAD

**Issue by Owen-Hw** [bumptech/glide#1549]
When the application starts, I first start the intentservice to download the audio, then opened the service to scan the Bluetooth equipment ibeacon. At this point, I found the picture from the server to download very slowly, in the local load is not affected. when i stop scan,the image will show quick .

I think the child thread may be blocked, how to solve it.

android os: huawei 6.0 and xiaomi 5.0

**Comment by TWiStErRob** [comment]
Glide has it's own threads, so the only thing I can think of is that your scanning uses too much network bandwith or CPU hence slowing down everything else on those channels. Try to run a trace and/or check the monitors in AS to see what's going on,

**Comment by li96968510** [comment]
@TWiStErRob Thank you for your answer, my app, memory is used about 50M, CPU user:1%~10%, kenel: 0.2%~2%. I was integrated by glide+okhttp3,when download file, always paused in :   byte[] buff = response.body().bytes(); debug was found it show : paused in another  thread, I don't know what happened.
