### ISSUE TITLE
Loading images from assets

### ISSUE THREAD

**Issue by vpratfr** [bumptech/glide#155]
Hi,

I have switched my current project from Picasso to Glide. However, I cannot manage to load an image from the application assets. Is that even possible?

Sample code: 

```
String assetPath = "file:///android_asset/flags/FR.jpg";
Glide.with(getContext())
                .load(Uri.parse(assetPath))
                .placeholder(missingFlagDrawable)
                .centerCrop()
                .crossFade()
                .into(flag);
```

I have also tried the load(String) method without success and I don't see a load method taking for instance an InputStream or a FileDescriptor I could have obtained with the AssetManager class.

That exact same code was working in Picasso.

Glide is working properly in the rest of the app and loading nicely remote images.

**Comment by androiddeveloperPooja30** [comment]
Hi,
We are updating image but does not change file path. In this case, glide does not refresh image.
Please tell me how to resolve this issue.

Thanks in advance.

**Comment by sjudd** [comment]
@androiddeveloperPooja30 Check out the wiki on cache invalidation: https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#custom-cache-invalidation. You will want to pass in a new signature each time you update the file.
