### ISSUE TITLE
com.bumptech.glide.RequestBuilder can't  import

### ISSUE THREAD

**Issue by x-dragonet** [bumptech/glide#1550]
glide master sample can use RequestBuilder, but My project compile 'com.github.bumptech.glide:glide:3.7.0', and I import com.bumptech.glide.RequestBuilder doesn't succeed. Could you tell me why?

**Comment by TWiStErRob** [comment]
Because master is v4, try to look at the samples on the `3.0` branch. In v3 there are several request builders rooting from ` GenericRequestBuilder`.
