### ISSUE TITLE
I/O exception - redirects fb graph image

### ISSUE THREAD

**Issue by mdudzak** [bumptech/glide#1551]
**Glide Version**: 3.7.0

**Integration libraries**: okhttp3-1.40

**Device/Android Version**: Nexus 5X API 24 (7.0)

**Issue details / Repro steps / Use case background**: Glide obviously can't handle facebook open graph redirects, i'm using this URL : graph.facebook.com/100005008535151/picture?type=large

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide
                .with(this)
                .load(url)
                .asBitmap()
                .centerCrop()
                .into(avatar);
```

**Layout XML**:
```xml
<ImageView
            android:id="@+id/avatar"
            android:layout_width="50dp"
            android:layout_height="50dp" />
```

**Stack trace / LogCat**:
```java
EXCEPTION: No such file or directory
           
           [ 10-25 13:28:00.559  6159: 6257 D/         ]
           HostConnection::get() New Host Connection established 0x7ffedc465b60, tid 6257
```

same bug as described here: https://github.com/bumptech/glide/issues/119

**Comment by mdudzak** [comment]
Problem solved, i had to add **https://** before url, so i changed it like this : 
```java
Glide
                .with(this)
                .load("https://"+url)
                .asBitmap()
                .centerCrop()
                .into(avatar);
```

**Comment by TWiStErRob** [comment]
Yep, every url hast to start with a scheme, scheme-less ones are assumed to be File paths.
