### ISSUE TITLE
Please remove synthetic methods

### ISSUE THREAD

**Issue by RiteshChandnani** [bumptech/glide#1555]
**Glide Version**: 3.7.0

**Issue details**: 
There’s no true nesting in Java. Hence, any access to private members of outer class from nested class will have to go via a package scoped method generated by Java to facilitate the call.

To reduce method, make methods of outer class package scoped.

More information:
https://realm.io/news/360andev-jake-wharton-java-hidden-costs-android/

**Comment by TWiStErRob** [comment]
Yep, I watched that too, agree, it's a good one.

Feel free to implement a PR that increases some scopes where the IDEA inspection flags there's a synthetic accessor, I think @sjudd will be happy to accept it.
