### ISSUE TITLE
Why would like to load the picture flash?

### ISSUE THREAD

**Issue by h1091129209** [bumptech/glide#1557]
I was just on the same ImageView every 500 ms to load another network picture, why would flash it? I hope it doesn't flash.
With the.DontAnimate () or so.

![gif5](https://cloud.githubusercontent.com/assets/9931634/19842623/a31d595e-9f55-11e6-8a54-a3d2c8b596c6.gif)

**Comment by TWiStErRob** [comment]
Please fill in the issue template? That looks like dontAnimate works as expected.

**Comment by h1091129209** [comment]
@TWiStErRob I was just on the same ImageView every 500 ms to load another network picture, why would flash it? I hope it doesn't flash.

**Comment by TWiStErRob** [comment]
You didn't show any code yet, but I guess you're using
```java
Glide...load(url).dontAnimate().into(imageView);
```
which is equivalent to
```java
Glide...load(url).dontAnimate().placeholder(null).into(imageView);
```
When Glide starts a load it immediately (sync) sets the placeholder and then fires up the load on a background thread to deliver it later and set the image (async on UI). The time between this sync and async operation is what you see as fashing.

Read #527 and related issues for more info.

**Comment by h1091129209** [comment]
@TWiStErRob Glide...load(url).dontAnimate().placeholder(null).into(imageView); This is not used

**Comment by h1091129209** [comment]
@TWiStErRob  Glide.with(MainActivity.this).load(str[msg.what-1]).dontAnimate().placeholder(iv.getDrawable())  This can be solved

**Comment by TWiStErRob** [comment]
That won't work, because what is returned from `iv.getDrawable()` becomes invalid after into is called. So right when the statement finishes executing. Your app will very likely crash if you do that. See comments below where you got that (I also edited that comment to call this out).

**Comment by h1091129209** [comment]
@TWiStErRob Do you have a better way?

**Comment by TWiStErRob** [comment]
Yes, https://github.com/bumptech/glide/issues/527#issuecomment-148840717
