### ISSUE TITLE
cannot resolve SimpleTarget, ViewTarget

### ISSUE THREAD

**Issue by ys144756** [bumptech/glide#1558]
cannot resolve SimpleTarget, ViewTarget class...
try invalidate caches and redownload glide, but it still remain unresolved.

i investigate glide-3.7.0.jar file, in 'com.bumptecth.glide.request' package, i can't found 'target' package..

thanks..

**Comment by TWiStErRob** [comment]
Just downloaded https://github.com/bumptech/glide/releases/tag/v3.7.0 and it's there:
`glide-3.7.0.jar\com\bumptech\glide\request\target\ViewTarget.class`

Maybe try re-downloading again, I had similar experiences when old versions of Maven/Gradle didn't download the file fully, but Eclipse/IDEA was already using them.

**Comment by ys144756** [comment]
thank you for detailed answer.
you are right.
i updated my gradle version and redownload '3.7.0' version.
i finally found ViewTraget.class.

but, IDE (android studio) still not shown 'target' package.. (i tried restart, synchronize)
this section is already closed, but if you have any idea based on your experience or advise, please tell me.  ; )

thank you.

**Comment by TWiStErRob** [comment]
Try it reimport your project in AS, or change Gradle settings (you can select which gradle to use for example). When something like this happens I usually just check the full jar dependency pah that AS finds, and delete it. Also an AS restart with "clear indexes" may help.
