### ISSUE TITLE
asBitmap().format(DecodeFormat.PREFER_ARGB_8888) not working

### ISSUE THREAD

**Issue by gnuhel** [bumptech/glide#1559]
**Glide Version**: 3.7.0
**Integration libraries**: okhttp3-integration-1.4.0
**Device/Android Version**: Nexus 5X

I want to set PREFER_ARGB_8888 for some specific cases but it does not work somehow.

```kotlin
    fun loadCrossfadeCropCenter(view: ImageView,
                                url: String?,
                                rounded: Boolean = false,
                                placeholder: Int? = null,
                                betterQuality: Boolean = true) {

        if (url == null) return

        Glide.clear(view)

        val requestBuilder = Glide.with(view.context).load(url)

        if (betterQuality) {
            requestBuilder.asBitmap().format(DecodeFormat.PREFER_ARGB_8888)
        }

        requestBuilder
                .animate(R.anim.abc_fade_in)    // replace .crossFade()
                .centerCrop()

        if (placeholder != null) {
            requestBuilder
                    .placeholder(placeholder)
                    .error(placeholder)
                    .into(ViewTarget(view, rounded) as Target<GlideDrawable>)
        } else {
            requestBuilder
                    .into(ViewTarget(view, rounded) as Target<GlideDrawable>)
        }
    }
```

When I use the global configuration then it works
```kotlin
    override fun applyOptions(context: Context, builder: GlideBuilder) {
        // Apply options to the builder here.
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888)
    }
```

Do you have any idea?

**Comment by TWiStErRob** [comment]
`requestBuilder.asBitmap()` returns a new requestBuilder with different type arguments, you have to continue calling other builder methods on that object.

Btw, Glide 3.8.0 will have `.asBitmap().crossFade()`, you can try the [snapshot](https://github.com/bumptech/glide/wiki/Snapshots).

**Comment by idish** [comment]
@TWiStErRob Is it okay to use a snapshot version of Glide in a production app?

**Comment by TWiStErRob** [comment]
@idish that really depends on your team/company. I use 3.8.0-SNAPSHOT in a personal published app, there are very rare commits to that one, pretty much waiting to be released. 3.7.0->3.8.0 increase guarantees backwards compatibility; however 3.7.0->4.0 doesn't and even the 4.0.0-SNAPSHOTs may contain breaking changes, because it's unreleased yet.
