### ISSUE TITLE
Load Strings into TextView

### ISSUE THREAD

**Issue by svenoaks** [bumptech/glide#1562]
Is it possible to use Glide to load String's into TextView's? Specifically I am using your AudioCover implementation in previous Issue's to load audio cover art into an ImageView. I would also like to use the MediaMetadataRetriever to retrieve the artist and song titles and insert them into TextView's along with the cover art. Is this a possibility with Glide? Please suggest how to get started, thanks.

**Comment by TWiStErRob** [comment]
You can do it, but I'm not sure it's worth it. If you want to play around and see how it feels, here it is:

Check out https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit?usp=sharing

You'll need a `GenericRequestBuilder<Song, File, SongInfo, SongInfo>`, meaning you'll need:
 * `class Song { /* whatever you use to identify the file or source */ }`
 * `class SongInfo { String title; String artist }`
 * model loader that passes a `Song` to a new fetcher
 * fetcher that figures out what you need to use with `MediaMetadataRetriever`  
(i.e. something that you can use for`setDataSource`)
 * decoder that uses `MediaMetadataRetriever` to create a `SongInfo` object
 * `UnitTranscoder` to pass `SongInfo` along
 * custom target that wraps the lifecycle of the `TextView`, override started/failed/cleared/ready methods

Fetcher and decoder are on background thread so you can do I/O to your heart's content. Don't forget to close/release everything you opened/created.

See the [SVG sample](https://github.com/bumptech/glide/tree/3.0/samples/svg/src/main/java/com/bumptech/glide/samples/svg) for more details.

**Comment by svenoaks** [comment]
Thanks for the response. I need to do something, because on main thread is way too slow. Since you say you're not sure if it's worth it, would you have any other simpler suggestions for how to do this?

**Comment by TWiStErRob** [comment]
What I mean is that I'm not sure if it's worth to do it with Glide processes. You get caching and other stuff, but it may be easier to load the metadata when you query the list of songs before binding to a list. You definitely need to take I/O off the UI thread, but there are many ways to do it. I suggest you give a try to the Glide API, I can help if you get stuck somewhere; but I also suggest thinking about alternate solutions.

**Comment by svenoaks** [comment]
Thank you for continued support. I think I will try Glide API, it seems more ideal since then they won't staring at loading screen while it loads them all upfront (measuring many seconds for a few dozen songs). Do you think it is possible to combine the cover art image loading and the artist, title strings in a single call to setDataSource()?

**Comment by TWiStErRob** [comment]
It may be possible if you use the same `Song` objects for both loads. Cache the retriever or the retrieved artist/title and synchronize calculation of those fields. That way only once the data will be read and any further access will get the cached value.
