### ISSUE TITLE
Duplicate entry during build

### ISSUE THREAD

**Issue by ai930** [bumptech/glide#1564]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider.class

**Comment by TWiStErRob** [comment]
`build.grade > dependencies`?

**Comment by ai930** [comment]
The final discovery is that I heaven blocked the download channel, the file has a problem. Download over the wall to solve it.
