### ISSUE TITLE
How to delete all the files related to specific URL

### ISSUE THREAD

**Issue by alexzaitsev** [bumptech/glide#1566]
Hello, I know that this question was asked many times but I haven't managed to find an answer to my question. The ordinal case is when the image was updated but URL didn't change. 
My case is another. I implement gifs in my application.
The use case is the next:
1. User loads gif with 3G (low quality, assume that it is loaded from URL1).
2. User swiches to Wifi and loads gif with WiFi (high qulity, assume that it is loaded from URL2).
URL1 != URL2

So technically we have 2 different gifs. 

I want to delete all related to the URL1 when URL2 is loaded as it will be never used in future.
I read about signatures but I'm not sure that I can use it. Please point me some direction for my investigation. 
Thank you.

**Comment by alexzaitsev** [comment]
I've read [https://github.com/bumptech/glide/issues/657](#657) issue. Is it still not possible? It very confusing that such poverful instrument doens't have such paramount possibility.

**Comment by TWiStErRob** [comment]
It's not possible the way you want it, but It has the possibility: just ignore the old urls (i.e. don't do anything about it) and they'll be deleted when the cache fills up, until then there's no point in micromanaging stuff. If you slap a `.signature` onto the load that'll invalidate the old file (i.e. it very likely won't be used any more) and hence will be evicted sooner or later. However if your urls are different, then you don't need signatures; signature is useful when the same source has different versions.

If you want to limit the space used by your app, limit the [Glide disk cache size](https://github.com/bumptech/glide/wiki/Configuration#size).

If you want to have control higher control over what files exist on the devices (remember: Glide is an image loader, not a generic caching solution), then store your files in your app's directory and load with `.diskCacheStrategy(NONE)` to prevent duplicating the files in Glide cache. This way you can remove them all you want.

Let me know if you need more pointers.

**Comment by alexzaitsev** [comment]
Thank you. It's pretty clear.

**Comment by alexzaitsev** [comment]
Thank you. It's pretty clear.
