### ISSUE TITLE
Animated Gif Pause/Resume

### ISSUE THREAD

**Issue by Wilson13** [bumptech/glide#1567]
Just wanted to be sure, is this function not supported or I overlooked it?

Thank you.

**Comment by TWiStErRob** [comment]
See #908, I'm not exactly sure if it's pause/resume or stop/restart operation though, but that's the only API currently.

**Comment by Wilson13** [comment]
My mistake on the title.  It's supposed to be "pause/unpause". So it only supports stop/restart through the Animatable class right?

Thank you.

**Comment by Wilson13** [comment]
My mistake on the title. It's supposed to be "pause/resume". So it only supports stop/restart through the Animatable class right?

Thank you.

**Comment by TWiStErRob** [comment]
To be correct, it looks like it's pause/restart, because `GifDrawable.start` has a `resetLoopCount()` call.

**Comment by TWiStErRob** [comment]
To be correct, it looks like it's pause/restart, because `GifDrawable.start` has a `resetLoopCount()` call.

**Comment by TWiStErRob** [comment]
To be correct, it looks like it's pause/restart, because `GifDrawable.start` has a `resetLoopCount()` call.

**Comment by TWiStErRob** [comment]
Oh, wait loop count is not the same as current frame :) So it looks more like pause/resume from code. If that's true that's what you need, and additionally you can emulate restart by loading the same resource again into the same view.

Give it a try, that's the best course of action here.

**Comment by suhadzain** [comment]
GlideDrawableImageViewTarget imageViewTarget = new GlideDrawableImageViewTarget(imageView, 1);
//after image view , u can set loop count via constructor
 Glide.with(this).load(sss_gif).into(imageViewTarget);

**Comment by markcadag** [comment]
I've created a gist https://gist.github.com/markcadag/a88a11bb297537491f9b92a46be719d4
