### ISSUE TITLE
GIF compression?

### ISSUE THREAD

**Issue by rbiggers** [bumptech/glide#1570]
Is there a way that Glide can reduce the byte size of a GIF? Many of the GIF's exceed the byte size limit for sending via MMS.

**Comment by TWiStErRob** [comment]
This should help:
```java
Glide.with(context)
     .load(url)
     .asGif()
     .toBytes()
     .override(w, h) // resize to this size
     // transformation to use for resize
     .transform(new GifDrawableTransformation(new FitCenter(context), Glide.get(context).getBitmapPool()))
     .into(new SimpleTarget<byte[]>() {
         @Override public void onResourceReady(byte[] resource, GlideAnimation<? super byte[]> glideAnimation) {
	         // send resource as MMS
         }
     })
```

**Comment by rbiggers** [comment]
Thank you for your quick response! I will give this a try. Below is what I was using but it did not seem to work.

                            bytesToReturn = Glide.with(context)
                                    .load(mUri)
                                    .asGif()
                                    .toBytes()
                                    .transform(new GifDrawableTransformation(new FitCenter(context), Glide.get(context).getBitmapPool()))
                                    .into(330, 330)
                                    .get();

**Comment by TWiStErRob** [comment]
What does "did not work" mean?

**Comment by rbiggers** [comment]
I'm sorry I should have been more specific. It returned the same byte size as as the original GIF, so no compression seemed to take place.

**Comment by TWiStErRob** [comment]
Not sure. `.override(w,h)` and `.into(w,h)` and `SimpleTarget(w,h)` should have the same effect.
Hmm, `GifDrawableBytesTranscoder` doesn't seem to apply the transformation, it possibly just reads the original bytes out.

**Comment by TWiStErRob** [comment]
Don't have time to look deeper, but you can try loading simply an `asGif` and then encode the drawable manually:
```java
GifDrawable resource = Glide
		.with(context)
		.load(url)
		.asGif()
		.into(100, 100)
		.get();
ByteArrayOutputStream out = new ByteArrayOutputStream();
new GifResourceEncoder(Glide.get(context).getBitmapPool())
		.encode(new GifDrawableResource(resource), out);
byte[] bytes = out.toByteArray();
```
it's a little hacky, but if `toBytes()` doesn't transform you don't have much choice.

**Comment by rbiggers** [comment]
Ok sounds good. I will give both of the options a try and let you know the outcome. Thank you again for your help!

**Comment by rbiggers** [comment]
Ok I was able to get it working with this code below:

                GifDrawable resource = Glide
                        .with(context)
                        .load(mUri)
                        .asGif()
                        .transform(new GifDrawableTransformation(new FitCenter(context), Glide.get(context).getBitmapPool()))
                        .into(110, 110)
                        .get();

                ByteArrayOutputStream out = new ByteArrayOutputStream();
                new GifResourceEncoder(Glide.get(context).getBitmapPool())
                        .encode(new GifDrawableResource(resource), out);
                byte[] bytes = out.toByteArray();

Now I have a follow up question to ask that goes with this, maybe you would have an idea about how I could go about it.

Is there a way that I could guesstimate the the byte array size after encoding before I encode it? The reason I ask is because I want to get the encoded GIF as close as I can to 1047552 Bytes. So this would mean adjusting the width and height dynamically for each GIF in order to get an "optimized" GIF after encoding. I was thinking that there may be a way by knowing the the original byte array size and the number of frames? But I figured I would ask and get your thoughts.

**Comment by TWiStErRob** [comment]
I don't think you can predict based on simple factors, because the size highly depends on the Huffman tree, which in turn depends on the pixel colors. If you know that anims are opaque and each frame looks roughly the same, you could try  getting the first one with asBitmap and encoding that to see his big a frame is with GIF. 

However, if you have time (runtime) or really want to get close, you could do a binary search for the size that gets you closest to the wanted size. A few tries should get you pretty close.

Tip: you only need that monster transform with toBytes, in this case you could simply use `fitCenter()`.

Also don't forget to `Glide.clear` whatever is returned from `into` after you're done with the drawable to prevent leaks. See doc of FutureTarget.

**Comment by CrackerKSR** [comment]
> ```java
> GifResourceEncoder
> ```

How to do this with Glide v4.. Encode class is missing in glide v4

**Comment by CrackerKSR** [comment]
> Ok I was able to get it working with this code below:
> 
> ```java
> GifDrawable resource = Glide
>         .with(context)
>         .load(mUri)
>         .asGif()
>         .transform(new GifDrawableTransformation(new FitCenter(context), Glide.get(context).getBitmapPool()))
>         .into(110, 110)
>         .get();
> 
> ByteArrayOutputStream out = new ByteArrayOutputStream();
> new GifResourceEncoder(Glide.get(context).getBitmapPool())
>         .encode(new GifDrawableResource(resource), out);
> byte[] bytes = out.toByteArray();
> ```
> 
> Now I have a follow up question to ask that goes with this, maybe you would have an idea about how I could go about it.
> 
> Is there a way that I could guesstimate the the byte array size after encoding before I encode it? The reason I ask is because I want to get the encoded GIF as close as I can to 1047552 Bytes. So this would mean adjusting the width and height dynamically for each GIF in order to get an "optimized" GIF after encoding. I was thinking that there may be a way by knowing the the original byte array size and the number of frames? But I figured I would ask and get your thoughts.

How to do that with glide v4

**Comment by TWiStErRob** [comment]
Have a look at https://bumptech.github.io/glide/doc/migrating.html maybe it has the answer, I haven't used it enough to answer.

**Comment by CrackerKSR** [comment]
GifResourceEncoder is not there in glide v4 everything else is fine.
