### ISSUE TITLE
Images never get loaded when following the Palette example

### ISSUE THREAD

**Issue by wasdennnoch** [bumptech/glide#1571]
**Glide Version**: 3.7.0

**Integration libraries**: --

**Device/Android Version**: Galaxy S3 with ResurrectionRemoc 5.7.4 (API 23)

**Issue details / Repro steps / Use case background**: I'm following the Palette example of the Custom targets wiki to load images into a RecyclerView and got the issue that the images never load / the callback never gets called.

**Relevant code parts** (everything in the RecyclerView adapter):
Constructor:
```java
mRequestManager = Glide.with(context)
        .fromString()
        .asBitmap()
        .transcode(new PaletteBitmapTranscoder(context), PaletteBitmap.class)
        .error(R.drawable.ic_error)
        .fitCenter()
        .diskCacheStrategy(DiskCacheStrategy.SOURCE);
```

onBindViewHolder:
```java
Glide.clear(thumbnail);
holder.indicateLoading(true);
Log.d("puush", "Loading Init " + item.thumbUrl);
mRequestManager
        .load(item.thumbUrl)
        .into(new ImageViewTarget<PaletteBitmap>(thumbnail) {
                @Override
                protected void setResource(PaletteBitmap resource) {
                    Log.d("puush", "setResource");
                    holder.finishLoading(resource.bitmap, ViewUtils.getRippleColor(resource.palette, mDefaultRippleColor));
                }

                @Override
                public void onResourceReady(PaletteBitmap resource, GlideAnimation<? super PaletteBitmap> glideAnimation) {
                    Log.d("puush", "onResourceReady");
                    super.onResourceReady(resource, glideAnimation);
                }

                @Override
                public void onLoadStarted(Drawable placeholder) {
                    Log.d("puush", "onLoadStarted");
                    super.onLoadStarted(placeholder);
                }

                @Override
                public void onLoadFailed(Exception e, Drawable errorDrawable) {
                    Log.d("puush", "onLoadFailed");
                    super.onLoadFailed(e, errorDrawable);
                }
            });
```

The `PaletteBitmap*` classes are identical to the example project. As you see I added some logging to the callbacks. In the logcat I see that `onLoadStarted` gets called for every image (just as it should), but then nothing happens, no other callback gets called.

**Comment by TWiStErRob** [comment]
My first hunch: make your view visible.
Glide needs to know the size of the view to actually start the decoding process. I'm guessing that `indicateLoading` hides the view and puts up a progress or something similar.

**Comment by wasdennnoch** [comment]
Huh, that was indeed the reason. Didn't think of this. Thanks for your time!
