### ISSUE TITLE
Can't decode GIF from server I have to use but decodes fine everywhere else

### ISSUE THREAD

**Issue by rayanmestiri** [bumptech/glide#1572]
**Glide Version**: 3.7.0

**Integration libraries**: none

**Device/Android Version**: Nexus 5/6.0.1

**Issue details / Repro steps / Use case background**: 
I have to load this gif: http://s3-eu-west-1.amazonaws.com/qanda-answers/answ_2141/2141.gif

The gif loads in a web browser but Glide gives a decoding error when loading from this server.

The same gif reuploaded to another image hosting website: http://i.imgur.com/2vYf5gr.gif or loaded from the device directly will display fine.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
ImageView gifView = (ImageView)this.findViewById(R.id.gifView);
GlideDrawableImageViewTarget gifTarget = new GlideDrawableImageViewTarget(gifView);

Glide
   .with(this)
   // .load(R.raw.testgif) // loads properly from device
   //.load("http://i.imgur.com/2vYf5gr.gif") // this is the same gif but reuploaded to imgur (and therefore reencoded). This one works.
   .load("http://s3-eu-west-1.amazonaws.com/qanda-answers/answ_2141/2141.gif") // this fails
   .into(gifTarget);
```

**Layout XML**:
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.glidetesting.rayan.testglidegiferror.MainActivity">

    <ImageView
        android:id="@+id/gifView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentTop="true"
        android:adjustViewBounds="true"
        android:scaleType="fitCenter"
        android:background="@android:color/darker_gray"/>

</RelativeLayout>
```

**Stack trace / LogCat**:
```ruby
D/skia: --- SkImageDecoder::Factory returned null
```
[TestGlideGifError.zip](https://github.com/bumptech/glide/files/576636/TestGlideGifError.zip)

**Comment by TWiStErRob** [comment]
The server is messing with you. It doesn't respond with a GIF when used from other than a browser.
```
curl -r 0-100 -i -v http://s3-eu-west-1.amazonaws.com/qanda-answers/answ_2141/2141.gif`
```
compare the output to the same command with imgur url.
GIF format has magic three bytes: `GIF` and then a year as a version.

I tried mimicking a browser request by adding some switches to curl:
```
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36'
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
-H 'Accept-Encoding: gzip, deflate, sdch'
-H 'Accept-Language: en-GB,en;q=0.8,en-US;q=0.6,hu;q=0.4'
```
but it didn't change.

Then I checked what format the server is responding with and according to https://hexed.it/ > Tools > File Format Identification the returned stream is a GZIP stream. Now, this is ok if the requests says it's ok, like the browser does, but Glide explicitly asks for no compression similar to this:
```
curl -r 0-100 -i -v http://s3-eu-west-1.amazonaws.com/qanda-answers/answ_2141/2141.gif -H 'Accept-Encoding: identity'
```
if you run this you can see that the server does not adhere to the request header to send the raw data.

**Comment by rayanmestiri** [comment]
Thank you, I was going nuts because I tried using a Glide module to request with 'Accept Encoding: Identity' but it wasn't working either.
