### ISSUE TITLE
Hello ，I have a problem to use glide with recyclerview

### ISSUE THREAD

**Issue by RealFeeling** [bumptech/glide#1574]
my layoutmanager of recyclerview is dynamic changing. item xml just a imageview. it width is match_parent.
but when the layoutmanager changed. the imageview's width display still pre width. it doesn't  refresh.

please help me

**Comment by TWiStErRob** [comment]
You should probably destroy the csched viewholders/re-set the adapter when you change LM.
Or as a simple hack you can call `iv.layout(0,0,0,0)`, before each load but that may degrade performance during normal use.
