### ISSUE TITLE
Glide can prioity to load the items that i can see in RecyclerView？

### ISSUE THREAD

**Issue by AndroidMsky** [bumptech/glide#1575]
Should I write code to control priority or Glide do it automatically？

Thank you！

**Comment by TWiStErRob** [comment]
All loads have the same priority by default. There's a `.priority()` method on the request builder, but you only need to use that if you have very special requirements: for example each row of the list contains 3 images, but they overlap; in this case it's worth to lower the prio of image 2&3 so the list "looks" populated faster. Another example might be a chat where the people's avatars are usually more important, than any shared image in the conversation history.

**Comment by AndroidMsky** [comment]
I get it! 

i like Glide and thank you very much!
