### ISSUE TITLE
RequestListener in Release Mode

### ISSUE THREAD

**Issue by storix** [bumptech/glide#1576]
Hi! I need some clarification regarding [RequestListener](https://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/request/RequestListener.html). 

According to [this](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) official wiki guide we can use `RequestListener` to get notified about the image loading process: whether there was an exception or an image has been loading successfully. I need this functionality to make it possible to display some error message to the users.

But at the end I found the following statement: 

> Make sure to remove any usages of this class before releasing your application!

What does it mean? Do I need to remove all listeners when I'm ready to release my app to Google Play? How should I then catch Glide errors in release mode? Thanks.

**Comment by TWiStErRob** [comment]
I wrote that comment. It's referring to `LoggingListener`, not any custom `RequestListener`. The point is that `LoggingListener` is just a debugging tool and should not be in the released app.

**Comment by storix** [comment]
Ok, thank you for the quick reply. Just wanted to make sure that I can freely use my listener in a released app.
