### ISSUE TITLE
3.7.0 version of the library is not available in http://jcenter.bintray.com/com/github/bumptech/glide/glide/

### ISSUE THREAD

**Issue by jkicha** [bumptech/glide#1584]
Trying to build from Android Studio. The 3.7.0 version is not available in http://jcenter.bintray.com/com/github/bumptech/glide/glide/

I am using the below in dependencies
    compile 'com.github.bumptech.glide:glide:3.7.0'
with Repositories as jcenter()

**Comment by TWiStErRob** [comment]
That's because Glide is published to Maven Central, not JCenter, see #544 for more details.

However, it's tricky, because even thought it's not listed, it's available, see https://jcenter.bintray.com/com/github/bumptech/glide/glide/3.7.0/glide-3.7.0.jar

**Comment by TWiStErRob** [comment]
I verified it works by deleting `p:\caches\gradle\caches\modules-2\files-2.1\com.github.bumptech.glide` folder and using
```gradle
repositories {
	jcenter()
}
dependencies {
	compile 'com.github.bumptech.glide:glide:3.7.0'
}
```
then
```
gradle build
```
which is ok:
```
Download https://jcenter.bintray.com/com/github/bumptech/glide/glide/3.7.0/glide-3.7.0.jar
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
...
:assembleDebug
...
:assembleRelease
...
:check
:build

BUILD SUCCESSFUL

**Comment by Ralphilius** [comment]
@TWiStErRob solution works for me! I was struggling with that for ages. Thanks a ton.
