### ISSUE TITLE
Load more than one image in RecyclerView ViewHolder make recyclerview laggy

### ISSUE THREAD

**Issue by IRMobydick** [bumptech/glide#1585]
Version : 3.7.0
Integration: okhttp3-1.4.0

Hi there,
I'm using glide in my project with okhttp integration to show progress ( as like as sample provided by @TWiStErRob | [link](https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_232_progress) )

I passed Glide RequestManager from Fragment to my adapter

```java
@Override
public void onAttach(Context context) {
    super.onAttach(context);
    mRes        = context.getResources();
    mGlide      = Glide.with(context);
}
```

  In `OnViewCreated` method of `Fragment`

```java
mRecyclerView.setAdapter(mAdapter = new PostAdapter(mContext, mActivity, mGlide));
```

In adapter `OnCreateViewHolder`

```java
return new PostViewHolder(parent, glide);
```

and finally in adapter `ViewHolder`, I'm going to load images, main image is post image and second image is user avatar. for loading main image, I'v follow the sample code of @TWiStErRob and this is code:

```java
private void bindImage(Post post){

    final ImageObject image;

    if (UserConfig.imageQuality == UserConfig.imageQualityPoor) {
        image = post.Image.ImageThumbnail;
    }else{
        image = post.Image.ImageLow;
    }

    int width = image.Width;
    int height = image.Height;

    if (height > 500){

        height  = 500;
        post.Image.ImageLow.setHeight(height);
        post.Image.ImageLow.setRatio(height / width);
        post.setTall(true);

    }

    if (post.isTall){
        expandable.setVisibility(View.VISIBLE);
    } else {
        expandable.setVisibility(View.GONE);
    }

    imageView.setRatio(post.Image.ImageLow.getRatio());

    target.setModel(image.Url);

    mGlide.load(image.Url)
            .asBitmap()
            .priority(Priority.IMMEDIATE)
            .diskCacheStrategy(DiskCacheStrategy.RESULT)
            .transform(new CropTransformation(itemView.getContext(), width, height, CropTransformation.CropType.TOP))
            .override(width, height)
            .listener(new LoggingListener<String, Bitmap>())
            .into(target);

}
```

and for loading user avatar image:

```java
private void bindUser(final Post post){

    textUser.setText(post.Owner.Username);

    mGlide.load(post.Owner.UserAvatar)
            .asBitmap()
            .priority(Priority.HIGH)
            .diskCacheStrategy(DiskCacheStrategy.RESULT)
            .transform(new CropCircleTransformation(itemView.getContext()))
            .placeholder(R.mipmap.dr_user_avatar)
            .listener(new LoggingListener<String, Bitmap>())
            .into(imageAvatar);

}
```

P.s: ImageView using as main image is a custom view

```java
public class DynamicHeightImageView extends ImageView{

    private float whRatio = 0;

    public DynamicHeightImageView(Context context) {
        super(context);
    }

    public DynamicHeightImageView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }


    public void setRatio(float ratio) {
        if (ratio != whRatio) {
            whRatio = ratio;
            requestLayout();
        }
    }

    public double getHeightRatio() {
        return whRatio;
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {

        if (whRatio != 0.0) {
            int width = MeasureSpec.getSize(widthMeasureSpec); //getMeasuredWidth();
            int height = (int)(whRatio * width);
            setMeasuredDimension(width, height);
        } else {
            super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        }

    }

}
```

*Question*

Is it right way to load more than one image with glide?
`Recyclerview` using `StaggeredGridLayoutManager` to produce view like Pinterest, before adding `bindUser` recyclerview working smoother, but after adding that, recyclerview scroll laggy!

Where am i wrong??

**Comment by TWiStErRob** [comment]
It likely depends on your layout. It's possible that setting an image causes re-layout and that causes a lot of work on the UI thread. I've had lagging spinners/lists the simplest of layouts: fixed imageview and a textview in a horizontal linear layout. See https://github.com/bumptech/glide/issues/1038#issuecomment-193403959.

Other than that I can also imagine that not transforming your Bitmaps can be a culprit. `.transform(new CropCircleTransformation(itemView.getContext()))` clears the fitCenter/centerCrop so the resulting Bitmap is bigger than necessary (CircleCrop doesn't resize, just make parts transparent). You may need `.transform(new FitCenter(), new CircleCrop())` to resize to a smaller size. `LoggingListener` should tell you if the size is much bigger than the view.

The only other thing I can think of is the priorities you set, but that shouldn't affect lagginess, only the order and delay of showing images.

Tip: if you're passing in `mGlide` why not initialize it to `Glide.with((Fragment)this)`? (for more info see http://stackoverflow.com/a/32887693/253468).

**Comment by IRMobydick** [comment]
My xml layout is like this:

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
     android:layout_width="match_parent"
     android:layout_height="wrap_content"
     android:background="@drawable/background_post_list"
     android:orientation="vertical">

    
    <FrameLayout
        android:id="@+id/image_holder"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:gravity="center">

        <com.wisgoon.android.ui.components.ColorfulRingProgressView
            android:id="@+id/progressbar"
            android:layout_width="46dip"
            android:layout_height="46dip"
            android:layout_gravity="center"
            app:bgColor="#e1e1e1"
            app:fgColorEnd="@color/endColor"
            app:fgColorStart="@color/startColor"
            app:percent="0"
            app:startAngle="0"
            app:strokeWidth="2dp" />

        <com.wisgoon.android.ui.components.DynamicHeightImageView
            android:id="@+id/image_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:adjustViewBounds="true"
            android:scaleType="centerCrop" />

        <LinearLayout
            android:id="@+id/expandable"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom"
            android:background="@color/toast_back"
            android:gravity="center"
            android:orientation="vertical"
            android:visibility="gone">

            <TextView
                android:id="@+id/text_tall"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:paddingBottom="@dimen/four"
                android:paddingTop="@dimen/four"
                android:text="@string/tall_image"
                android:textColor="@color/white" />

        </LinearLayout>


    </FrameLayout>

    
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:background="@drawable/background_border_bottom">

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:layout_marginRight="@dimen/eight"
            android:orientation="horizontal">

            <TextView
                android:id="@+id/comment_txt"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical"
                android:gravity="center"
                android:textColor="@color/textColorBold"
                android:textSize="@dimen/h3" />

            <Button
                android:id="@+id/comment_icon"
                android:layout_width="30dp"
                android:layout_height="30dp"/>

        </LinearLayout>

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentLeft="true"
            android:layout_centerVertical="true"
            android:layout_marginLeft="@dimen/eight"
            android:orientation="horizontal">

            <Button
                android:id="@+id/like_icon"
                android:layout_width="30dp"
                android:layout_height="30dp"/>

            <TextView
                android:id="@+id/like_txt"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical"
                android:gravity="center"
                android:textColor="@color/textColorBold"
                android:textSize="@dimen/h3" />

        </LinearLayout>

    </RelativeLayout>

    
    <TextView
        android:id="@+id/description"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@drawable/background_border_bottom"
        android:ellipsize="end"
        android:lines="2"
        android:maxLines="2"
        android:paddingLeft="@dimen/eight"
        android:paddingRight="@dimen/eight"
        android:paddingTop="@dimen/four"
        android:textColor="@color/textColorLight"
        android:textSize="@dimen/h3" />

    
    <RelativeLayout
        android:layout_width="wrap_content"
        android:layout_height="?attr/actionBarSize">

        <ImageButton
            android:id="@+id/context_menu"
            android:layout_width="@dimen/thirty_two"
            android:layout_height="@dimen/thirty_two"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_centerVertical="true"
            android:layout_marginLeft="@dimen/eight"
            android:layout_marginStart="@dimen/eight"
            android:background="@android:color/transparent"
            android:src="@mipmap/ic_dots_vertical" />

        <ImageView
            android:id="@+id/owner_avatar"
            android:layout_width="@dimen/thirty_two"
            android:layout_height="@dimen/thirty_two"
            android:layout_alignParentEnd="true"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:layout_marginEnd="@dimen/eight"
            android:layout_marginRight="@dimen/eight"
            android:src="@mipmap/dr_user_avatar" />

        <TextView
            android:id="@+id/owner_name"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:layout_marginEnd="@dimen/four"
            android:layout_marginLeft="@dimen/four"
            android:layout_marginRight="@dimen/four"
            android:layout_marginStart="@dimen/four"
            android:layout_toEndOf="@+id/context_menu"
            android:layout_toLeftOf="@+id/owner_avatar"
            android:layout_toRightOf="@+id/context_menu"
            android:layout_toStartOf="@+id/owner_avatar"
            android:ellipsize="end"
            android:gravity="right"
            android:textColor="@color/textColorBold"
            android:textSize="@dimen/h3" />

    </RelativeLayout>


</LinearLayout>

**Comment by IRMobydick** [comment]
I've change `Glide.with(context)` to `Glide.with(this)` by moving mGlide from fragment `OnAttach(Context context)` to `OnViewCreate(...)`

And change transformation in both `bindImage` and `bindUser` to what you said:

    //bindUser
    .transform(new FitCenter(itemView.getContext()), new CropCircleTransformation(itemView.getContext()))


    //bindImage
    .transform(new FitCenter(itemView.getContext()), new CropTransformation(itemView.getContext(), width, height, CropTransformation.CropType.TOP))

But nothing changed :(

**Comment by TWiStErRob** [comment]
No further ideas. Maybe try profiling your app or check Hierarchy Viewer for red dots.

**Comment by IRMobydick** [comment]
Thanks for your patience
Every time I've open an issue here, I learned something new
Thanks Bro! 👍

**Comment by TWiStErRob** [comment]
Does that mean you solved it?

**Comment by IRMobydick** [comment]
No, I'm going to dive in profiling! and up to now, there is no red dot at all!!
I've seen an article that Staggered Grid Layout Manager act lagy on Samsung devices, maybe the problem be there!!

I'll share Hierarchy Viewer of my app with you here

**Comment by IRMobydick** [comment]
As you said I've profiling Hierarchy Viewer and there was not any red dot.
