### ISSUE TITLE
Why does a image loaded by glide has bad quality compared with setImagexxx() by imageView?

### ISSUE THREAD

**Issue by octopuslaowang** [bumptech/glide#1589]
**Glide Version**:
3.7.0

**Device/Android Version**:
all the devices

**Issue details / Repro steps / Use case background**: 
Why does a image loaded by glide has bad quality compared with setImage() by imageView?
I has tried various file types(e.g. jpg, png, webp)  and the effects look so bad always. Once i used setImagexxx() for the imageView, the effect is lossless. 
Does i have any ways to load lossless image by glide?
Thanks！

**Comment by TWiStErRob** [comment]
Can you please show with a screenshot what you mean by "bad"?

**Comment by octopuslaowang** [comment]
image loaded by glide:
![device-2016-11-17-135349](https://cloud.githubusercontent.com/assets/6631824/20378795/4b15a910-acd3-11e6-8ba1-3557c52e7421.png)

image loaded by setImageURI():
![device-2016-11-17-142707](https://cloud.githubusercontent.com/assets/6631824/20378796/4b1a308e-acd3-11e6-889b-04bb6fb0988d.png)

**Comment by TWiStErRob** [comment]
Ah, the gradients :)
Read this: https://github.com/bumptech/glide/wiki/Configuration#bitmap-format
Along global config you can also set format per request via `load().asBitmap().format()`

**Comment by octopuslaowang** [comment]
solved!
thx!
Ｏ(≧∇≦)Ｏ

**Comment by jahirfiquitiva** [comment]
@TWiStErRob 
I have created a custom GlideModule
I have also added it in AndroidManifest.xml ... do I have to do something else for it to be used for Glide?
Thanks in advance
