### ISSUE TITLE
Relationship between BitMapPool, MemoryCache and DiskCache?

### ISSUE THREAD

**Issue by MNDaveC** [bumptech/glide#1590]
What is the relation between BitMapPool, MemoryCache and DiskCache? is one a subset of the other? how should their sizes be comparatively? The default suggestions I got from the calculator produced 29mb for cache and 58mb for bitmap pool.

When profiling my app, I see memory usage jump by 100MB when loading a RecyclerView that has up to 30 images of approx 350-400 kb each at the source. Can I restrict cache sizes to contain the 100MB spike in memory? Any other suggestions to contain the memory usage?

**Glide Version**: 3.7.0

**Integration libraries**: okhttp3-integration:1.4.0

**Device/Android Version**: Galaxy S7

**Issue details / Repro steps / Use case background**: Occasional OOM

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

        Glide.with(imageView.getContext())
                .load(imageItem.imageUrl())
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .placeholder(placeholder)
                .crossFade()
                .dontAnimate()           //Avoids flicker
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e,
                                               String model,
                                               Target<GlideDrawable> target,
                                               boolean isFirstResource) {
                        // Don't set the tag here in case we want to retry on the next call to notify
                        // the adapter.

                        // Always clear the placeholder
                        mHeroImagePlaceholderDrawable = null;
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource,
                                                   String model,
                                                   Target<GlideDrawable> target,
                                                   boolean isFromMemoryCache,
                                                   boolean isFirstResource) {
                        // Set the image URL as a tag so we know that the image with this URL has
                        // successfully loaded
                        imageView.setTag(imageItem);

                        // Always clear the placeholder
                        mHeroImagePlaceholderDrawable = null;
                        return false;
                    }
                })
                .into(imageView);

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
Occasional OOM

**Comment by ronpeer7** [comment]
I have the same problem and I open a new issue as well. Glide load with recyclerview results in memory leak.
