### ISSUE TITLE
Image size changed after being reloaded

### ISSUE THREAD

**Issue by yuansip** [bumptech/glide#1591]
**3.7.0**:

**failed on com.android.support:recyclerview-v7:25.0.1**:

**failed on all devices I have, such as Nexus 5 6.0.1**

**expected result**
![snap_20161117_085203](https://cloud.githubusercontent.com/assets/5660702/20372068/ad939fbe-aca3-11e6-899a-5502fdabfb32.jpg)
**unexpected result**
![snap_20161117_085222](https://cloud.githubusercontent.com/assets/5660702/20372067/ad23bce4-aca3-11e6-8e1e-847017bf671d.jpg)

**:

**use Glide to load gif into items of recyclerview, then scroll the recyclerview up and down, the image size is changed after scrolling out of screen then into screen**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
        final Uri uri = Uri.parse(urls[i]);
        Glide.with(getContext())
                .load(uri)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(viewHolder.imageView);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
    <ImageView
        android:id="@+id/image"
        android:scaleType="fitCenter"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
</FrameLayout>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by yuansip** [comment]
I added some log in `onResourceReady` and found the size of the GlideDrawable reloaded from cache was changed.

**Comment by yuansip** [comment]
Similar issue:
#1506

**Comment by yuansip** [comment]
I found a workaround:
```java
        Glide.with(getContext())
                .load(urls[i])
                .listener(new RequestListener<Uri, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, Uri model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, Uri model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        GlideDrawableImageViewTarget glideTarget = (GlideDrawableImageViewTarget) target;
                        ImageView iv = glideTarget.getView();
                        int width = iv.getMeasuredWidth();
                        int targetHeight = width * resource.getIntrinsicHeight() / resource.getIntrinsicWidth();
                        if(iv.getLayoutParams().height != targetHeight) {
                            iv.getLayoutParams().height = targetHeight;
                            iv.requestLayout();
                        }
                        return false;
                    }
                })
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(viewHolder.imageView);
```

**Comment by TWiStErRob** [comment]
The list items are being reused, and when you scroll down you bind a larger image which makes the ImageView layout taller (wrap_content). When you scroll back up Glide sees that taller size and tries to load an image that has that size. `wrap_content` only works if the didn't have a layout before, otherwise Glide reads the laid-out width/height and uses that as the target size. I usually recommend a `holder.iv.layout(0,0,0,0)` to reset the size of the view/target and behave as if the list item was just inflated.

**Comment by yuansip** [comment]
@TWiStErRob, Thanks for your reply. I tried to call `viewHolder.imageView.layout(0, 0, 0, 0)` in `onBindViewHolder(...)` as your suggestion, it resolved this issue.

**Comment by Ennosukeblade** [comment]
I tried this but in the last line it tell me **Cannot resolve method 'into(void)'**
``        Glide.with(c)
                .load(i.getUri())
                .apply(new RequestOptions().fitCenter())
                .apply(new RequestOptions().placeholder(R.drawable.placeholder))
                .into(holder.imgView.layout(0,0,0,0));

**Comment by ezhd** [comment]
@Ennosukeblade I assume you have to call `holder.imgView.layout(0,0,0,0);` before calling Glide.. because as you said, it returns nothing but null

**Comment by jkailin** [comment]
Adding `.override(view.width)` worked best for me. Ex:

```
Glide.with(view.context)
.load(imageUrl)
.override(view.width)
.transition(DrawableTransitionOptions.withCrossFade())
.into(view)
```

**Comment by TWiStErRob** [comment]
@jkailin that only works if you have a fixed width layout, and it'll also shrink taller than wide (portrait shape) images as a side effect. It also should not work on the first bind, interesting if it does for you.

**Comment by jkailin** [comment]
@TWiStErRob Ah that's right. Portrait images have issues. When I use `holder.iv.layout(0,0,0,0)` some views still don't resize correctly. Is this fix still usable?

**Comment by TWiStErRob** [comment]
@jkailin Based on the many upvotes to my original comment, yes :)
However I don't know if the changes that happened since 3.7 could affect this.
Originally the 0s are meant to trigger this check:
`com.bumptech.glide.request.target.ViewTarget.SizeDeterminer#isSizeValid`
I'm not sure if it still exists in a fairly similar for in v4.

**Comment by squm** [comment]
centering image on the left, as you would with TextView `gravity="center_vertical|start"` using `scaleType="fitStart"` and `layout_height="wrap_content"`. And there the images have incorrect smaller size, probably they keep the preloaded resolution?

**Comment by franciscobarrios** [comment]
Still happening, in my case I'm using different dimensionRatio (from ConstraintLayout) go show image, files and videos, and to fix the problem the solution was:
```
fun ImageView.resizeImage(imagePath: String?, placeholder: Int) {
       this.layout(0,0,0,0)  // <------- 
            GlideApp.with(context.applicationContext)
                   .load(imagePath)
                   .apply(options)
                   .fitCenter()
                   .centerCrop()
                   .into(this)
           }
```

**Comment by bobguy1234** [comment]
When I use ```holder.iv.layout(0,0,0,0)``` and scrolling fast on the recyclerview, it instantly scrolls all the way to the first image.

**Comment by bobguy1234** [comment]
```holder.imgView.layout(0,0,0,0);``` causes a snapping effect that instantly scrolls all the way to the first item

**Comment by james04gr** [comment]
> `holder.imgView.layout(0,0,0,0);` causes a snapping effect that instantly scrolls all the way to the first item

This is because when the view is created it has a height of 0, and when Glide loads the image suddenly the height of an item changes, so it pushes other items down/up (according to orientation scroll)

Any idea how to fix this?

**Comment by GerardoRobledo** [comment]
@james04gr if you have a predefined height for the items, you can use that value for the bottom param.
`holder.imgView.layout(0,0,0,itemHeight);`
