### ISSUE TITLE
is there a friendly way to switch glide's cache path in app runingtime?

### ISSUE THREAD

**Issue by julist213** [bumptech/glide#1595]
im my app ,i need to switch user cache file in an independent dir .i try to refelct glide==null ,and it's not help .

**Comment by julist213** [comment]
my code:
                   //glide
                    Class<?> glideClz = Class.forName(Glide.class.getName());
                    Field glideField = glideClz.getDeclaredField("glide");
                    glideField.setAccessible(true);
                    glideField.set(null, null);
                    //DiskLruCacheWrapper
                    Class<?> diskLruClz = Class.forName(DiskLruCacheWrapper.class.getName());
                    Field diskLruField = diskLruClz.getDeclaredField("wrapper");
                    diskLruField.setAccessible(true);
                    diskLruField.set(null, null);

**Comment by TWiStErRob** [comment]
That may remove the instances, but did you take any measures to change the path when the new instances are created? https://github.com/bumptech/glide/wiki/Configuration#location
