### ISSUE TITLE
How to cancel loading Glide "processes", so a new thread won't be run until the previous one is finished?

### ISSUE THREAD

**Issue by jahirfiquitiva** [bumptech/glide#1598]
**Glide Version**: 3.7.0

**Integration libraries**: none

**Device/Android Version**: Moto G 2014 - Android 7.1

**Issue details / Repro steps / Use case background**: 
In my app, I have multiple sections that use Glide to load different kind of images. What I have noticed is that, when I enter each section, the Glide "process" to load the images in it, starts. But if I enter another section, the new "process" won't start until previous one is finished, which makes it really slow to load the pictures and (for me) results in a bad UX (already had some complaints about it).

What I expect to be able to do, is cancel all Glide previous "processes" after entering to each section, so only the "process" for current section is being run.

As I just said, my app has multiple sections, so for explanation I will say I have one section that shows apps icons that are in drawable folder of the app. And another section that shows wallpapers, downloaded from web.

I tried using the `Priority.HIGH` and `Priority.IMMEDIATE` line, but it does not really help.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
**_For Apps Icons_**
```java
Glide.with(context)
		.load(iconResource)
		.asBitmap()
		.diskCacheStrategy(DiskCacheStrategy.SOURCE)
		.priority(Priority.IMMEDIATE)
		.into(new BitmapImageViewTarget(holder.icon) {
			@Override
			protected void setResource(Bitmap resource) {
				if ((!inChangelog && mPrefs.getAnimationsEnabled()) &&
						(holder.getAdapterPosition() > lastPosition)) {
					holder.icon.setAlpha(0f);
					holder.icon.setImageBitmap(resource);
					holder.icon.animate().setDuration(250).alpha(1f).start();
					lastPosition = holder.getAdapterPosition();
				} else {
					holder.icon.setImageBitmap(resource);
				}
			}
		});
```

**_For wallpapers_**
```java
BitmapImageViewTarget target = new BitmapImageViewTarget(holder.wall) {
	@Override
	protected void setResource(Bitmap bitmap) {
		Palette.Swatch wallSwatch = ColorUtils.getPaletteSwatch(bitmap);
		if (animationEnabled && (holder.getAdapterPosition() > lastPosition)) {
			holder.wall.setAlpha(0f);
			holder.titleBg.setAlpha(0f);
			holder.wall.setImageBitmap(bitmap);
			if (wallSwatch != null) setColors(wallSwatch.getRgb(), holder);
			holder.wall.animate().setDuration(250).alpha(1f).start();
			holder.titleBg.animate().setDuration(250).alpha(1f).start();
			lastPosition = holder.getAdapterPosition();
		} else {
			holder.wall.setImageBitmap(bitmap);
			if (wallSwatch != null) setColors(wallSwatch.getRgb(), holder);
		}
	}
};

Glide.with(activity)
		.load(wallURL)
		.asBitmap()
		.diskCacheStrategy(DiskCacheStrategy.SOURCE)
		.priority(Priority.HIGH)
		.thumbnail(0.5f)
		.into(target);
```

**Layout XML**:
**_For apps icons_**
```xml
<jahirfiquitiva.iconshowcase.views.SquaredImageView
        android:id="@+id/icon_img"
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:foreground="?attr/selectableItemBackground"
        android:padding="@dimen/cards_margin"
        tools:ignore="ContentDescription"/>
```

**_For wallpapers_**
```xml
<RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:foreground="?attr/selectableItemBackground">

    <FrameLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:tools="http://schemas.android.com/tools"
            android:id="@+id/wall_frame_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

        <ProgressBar
                android:id="@+id/progress"
                style="?progressBarStyle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:clickable="false"
                android:focusable="false"
                android:gravity="center"/>

        <jahirfiquitiva.iconshowcase.views.SquaredImageView
                android:id="@+id/wall"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scaleType="centerCrop"
                tools:ignore="ContentDescription, UnusedAttribute"/>

    </FrameLayout>

    <LinearLayout
            android:id="@+id/titleBg"
            style="@style/ListsContent"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/wall_frame_layout"
            android:layout_gravity="bottom"
            android:background="@color/semitransparent_black"
            android:orientation="vertical"
            tools:ignore="UnusedAttribute">

        <TextView
                android:id="@+id/name"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom"
                android:gravity="center"
                android:singleLine="true"
                android:textAppearance="@style/TextAppearance.AppCompat.Medium"
                android:textColor="@android:color/white"
                tools:text="Title"/>

        <TextView
                android:id="@+id/author"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom"
                android:gravity="center"
                android:singleLine="true"
                android:textAppearance="@style/TextAppearance.AppCompat.Small"
                android:textColor="@android:color/white"
                tools:text="Author"/>

    </LinearLayout>
</RelativeLayout>
````

A demo of my project can be downloaded from [here](https://drive.google.com/file/d/0Bw52d3_ZiSb9d2NJNW5kZ0JucFk/view?usp=sharing)... It has a navigation drawer with the sections, if you quickly switch between sections (icons, wallpapers, apply, zooper, kustom) ... you may be able to see the issue.

Any help in terms of code or info about some kind of feature for a future Glide update will be really appreciated.
Thanks in advance.

Also, thanks for such an awesome library. Keep up the good work.

**Comment by jackcsk** [comment]
I'm having the same problem, with a recyclerview loading lots of large .gif files.

My current workaround is to call `Glide.clear(imageView)` on imageviews hidden from the screen.
It helps, but doesn't totally resolve the issue, so I am interested to hear in as well.

**Comment by Emeritus-DarranKelinske** [comment]
Did anyone find a solution for this?

**Comment by jahirfiquitiva** [comment]
@Emeritus-DarranKelinske No, and devs do not help

**Comment by Emeritus-DarranKelinske** [comment]
I was able to fix this in a recyclerview by doing the following:

    @Override
    public void onViewRecycled(ViewHolder holder) {
        super.onViewRecycled(holder);
        Glide.clear(holder.mAvatar);
        holder.mAvatar.setImageResource(R.drawable.ic_avatar);
    }

basically cancelling the image loading and setting the imageview to a default state with then the view is recycled

**Comment by jahirfiquitiva** [comment]
@Emeritus-DarranKelinske 

I don't think that's a good solution, especially in terms of efficiency.

Anyways, what I meant with this issue/question is something completely different.

In my app, I have different fragments, some of those fragments use Glide to load certain pictures, either from web or from resources. The thing is switching fragments won't cancel the Glide task from previous fragment, and in the new fragment, it will wait until the previous Glide tasks are completed to start the current fragment task, which results in a long delay and an empty section for some time.

That's what I want to avoid.

**Comment by Emeritus-DarranKelinske** [comment]
Okay. Thank you! Good luck!

**Comment by jackcsk** [comment]
So, we don't expect any update on the 3.x branch. Right?

**Comment by sjudd** [comment]
``clear()`` will cancel any particular pending request, ``RequestManager`` has other methods for clearing all requests started in a particular ``Fragment`` or ``Activity``.

If you're using a ``RecyclerView`` clearing requests in on ViewRecycled as @Emeritus-DarranKelinske suggested is perfectly reasonable and efficient, though won't solve issues related to changing screens.

However you're correct that we're not planning on making any further changes to the v3 branch.
