### ISSUE TITLE
[Question] How to find out activity's lifecycle in glide

### ISSUE THREAD

**Issue by HyowonHwang** [bumptech/glide#1600]
Hi, I found Glide will automatically stop the request when the requesting activity is stopped is from the blogs. 
If it is possible, you would mind to know how it works, please.

https://futurestud.io/tutorials/glide-callbacks-simpletarget-and-viewtarget-for-custom-view-classes

**Comment by TWiStErRob** [comment]
To see what applies: http://stackoverflow.com/a/32887693/253468
To see how it happens, see `(Support)RequestManagerFragment` which is a view-less fragment added when you call `with(...)` by `RequestManagerRetriever`. The fragment calls `((RequestManager)lifecycle).onStop` which pauses the requests.
