### ISSUE TITLE
Preloading images into cache is not working

### ISSUE THREAD

**Issue by AndroiZdevel** [bumptech/glide#1602]
Hi,
I am new to Glide. I am developing a fitness app and my goal is to show a sequence of images (let's say 4) to show how to execute an exercise. My idea is to first cache all the images and then show them as an animation one after the other. 
I am using Glide 3.7.0
The problem is that when I try to retrieve the images from the LruCache I get a null bitmap or a 
"Unknown type class android.graphics.Bitmap. You must provide a Model of a type for which ...." error.
Here is my code:

This is where I cache the images
```java
Glide.with(getActivity().getApplicationContext())
                                .load(uri)
                                .asBitmap()
                                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                                .into(new SimpleTarget<Bitmap>( width, height ) {
                                    @Override
                                    public void onResourceReady(Bitmap resource, GlideAnimation glideAnimation) {
                                            mMemoryCache.put("image_"+counter, resource);
                                        }
                                    });
```
This is where I load the images (I also tried without asBitmap() but the result is the same)
```java
Glide.with(getActivity().getApplicationContext())
                                            .load(image)
                                            .asBitmap()
                                            .into(target);
```

And here is my target:
```java
private SimpleTarget target = new SimpleTarget<Bitmap>() {
        @Override
        public void onResourceReady(Bitmap resource, GlideAnimation glideAnimation) {
            exercisePhoto.setImageBitmap(resource);
        }
    };
```

Any idea?
Really thanks a lot

**Comment by TWiStErRob** [comment]
See #122, but why not just use `exercisePhoto.setImageBitmap(image);`? there's no point in squeezing it through Glide twice if you already have a Bitmap.

If I were use I would use Glide's caches for all this. You can pre-cache onto disk with `.downloadOnly()` if you're worried internet will disappear during animation. From there you can load it easily with `.load(url).diskCacheStrategy(SOURCE).into(exercisePhoto);`. Most of the time loading from disk cache will be consistently fast, so there's no need to store all "frames" in memory; few milliseconds won't make a difference regarding animation.

You might also be interested in https://github.com/bumptech/glide/issues/861#issuecomment-169490382.
