### ISSUE TITLE
Volley TimeoutError

### ISSUE THREAD

**Issue by alexzaitsev** [bumptech/glide#1605]
Hello, 
I have a screen with a grid of the gifs. I open this screen using 2G connection. About 16 gifs are started downloading with LOW priority. I click on the random (not yet downloaded) item and the screen with preview is opened. The gif is loading with IMMEDIATE priority. 
However it gives me TimeoutError. 
I think that it's because I lot of another gifs are downloading at the same moment. 

While searching a solution I added an integration with Volley 
```gradle
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.github.bumptech.glide:volley-integration:1.3.1@aar'
```
custom module
```java
@Override
    public void registerComponents(Context context, Glide glide) {
        File cacheDir = new File(context.getCacheDir(), DEFAULT_CACHE_DIR);
        Network network = new CustomBasicNetwork(new HurlStack());
        RequestQueue queue = new RequestQueue(new DiskBasedCache(cacheDir), network){

            @Override
            public <T> Request<T> add(Request<T> request) {
                request.setRetryPolicy(new DefaultRetryPolicy(TIMEOUT_MS, 1, 1));
                return super.add(request);
            }
        };
        queue.start();
        glide.register(GlideUrl.class, InputStream.class, new VolleyUrlLoader.Factory(queue));
    }
```

I tried to set TIMEOUT_MS to 30000 and even 100000 but it doesn't work. In any case I get the next error
```ruby
11-23 12:49:52.343 4803-4803/com.talk W/System.err: java.util.concurrent.ExecutionException: com.android.volley.TimeoutError
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.integration.volley.VolleyRequestFuture.doGet(VolleyRequestFuture.java:125)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.integration.volley.VolleyRequestFuture.get(VolleyRequestFuture.java:92)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.integration.volley.VolleyStreamFetcher.loadData(VolleyStreamFetcher.java:68)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.integration.volley.VolleyStreamFetcher.loadData(VolleyStreamFetcher.java:21)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
11-23 12:49:52.350 4803-4803/com.talk W/System.err: Caused by: com.android.volley.TimeoutError
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:140)
11-23 12:49:52.350 4803-4803/com.talk W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
```

If I open the grid with gifs, wait until they will be downloaded and open preview of some downloaded gif  - everything works ok. 
Why priority doesn't work?
Perhaps I misunderstand the concept of priorities. I thought that IMMEDIATE must perform current request in front of the queue.

**Comment by TWiStErRob** [comment]
Yes, IMMEDIATE has that effect, however if all the pool threads are clogged with megabytes of download left, the request cannot start. Even if one finishes and your important request is started, the others are still loading and hogging bandwidth. If you use `SOURCE` cache, it's also possible that the second IMMEDIATE request for the same HTTP source will just attach to the previous one without lifting the priority. This is an edge case that I don't know how it behaves (see `Engine.load`).

Tip: you shouldn't cache Volley requests, because they'll duplicate data on the device (GIF file will be saved in Volley cache and then in Glide SOURCE cache).

**Comment by alexzaitsev** [comment]
I dismissed Volley cache:

```
@Override
    public void registerComponents(Context context, Glide glide) {
        Network network = new CustomBasicNetwork(new HurlStack());
        RequestQueue queue = new RequestQueue(new NoCache(), network){

            @Override
            public <T> Request<T> add(Request<T> request) {
                request.setRetryPolicy(new DefaultRetryPolicy(TIMEOUT_MS, 1, 1));
                return super.add(request);
            }
        };
        queue.start();
        glide.register(GlideUrl.class, InputStream.class, new VolleyUrlLoader.Factory(queue));
    }
```
Thanks for the tip.

I'm wondering is there any way to improve my situation? 
(Actually I know one workaround: cancel all running requests. Is it possible to do with a single Glide command? However it sounds as not a good solution..)

**Comment by TWiStErRob** [comment]
`Glide.with(x).onDestroy()` should cancel, but I don't recommend calling it directly. The side effect is that even if 3.9 out of 4 megabytes were downloaded all 3.9 are discarded.

I think what you should consider is showing thumbnails for GIFs from a separate url. A small JPEG file which loads quickly, and then when the user wants to see the anim start loading the full megabytes large GIF files. Alternatively `load(gif).asBitmap().diskCacheStrategy(RESULT)` may work if your image provider doesn't have thumbs, because it should only transfer the header and the first frame over the wire; but this needs confirmation.

**Comment by TWiStErRob** [comment]
You should also try to debug it out, why the timeouts happen. The Volley timer only starts once Glide actually request (calling `.into()` just queues it). So the only way I see your timeout happening is that the parallel downloads make the network so slow that you don't get a response.

**Comment by alexzaitsev** [comment]
I use thumbnail with different URL. However there are about 16 pending gifs. They are loading very slow with 2G connection. So it's natural to get TimeoutError with the current approach. Unfortunately.
It's pity that IMMEDIATE can't push my new thread in front of the another running ones. It would solve my problem.

**Comment by TWiStErRob** [comment]
You can try implementing your own behavior for priorities to kick out lower ones:
```java
class ... implements GlideModule {
	@Override public void applyOptions(Context context, GlideBuilder builder) {
		builder.setResizeService(new ...);
	}
```
You can try for example interrupting a random thread in the pool which will stop the running I/O operations and error the load that had lower priority. You should be able to observe the `InterruptedException` in `onException`.

**Comment by alexzaitsev** [comment]
I'll discuss the situation with a business in order to find the best solution. I'll close this issue however if you don't mind I'll reopen it in future if I have additional questions. 
Many thanks for the help! I don't know what I would do without you.
If you have some minute please take a look on my another issue: https://github.com/bumptech/glide/issues/1604
