### ISSUE TITLE
Artifacts when loading .png with gradient

### ISSUE THREAD

**Issue by Inquallity** [bumptech/glide#1608]
**Glide Version**: 3.7.0
**Integration libraries**: none
**Device/Android Version**: any
**Issue details / Repro steps / Use case background**: 
Loading \*.jpg/\*.png image from resources or network.
For additional code please check sample repo https://github.com/Inquallity/glidegradient

Hello, guys!
Can anyone take me advice with Glide config? I'm trying to load image with gradient from resources/network and set it up into simple _ImageView_. But result image contains weird artifacts looks like vertical lines [screenshot on imgur](http://imgur.com/a/TRWtg).
Loading via _BitmapFactory_ and _Fresco_ library works as expected, but not with Glide and Picasso.
I guess the reason is the transformation when caching images (?). But I was unable to determine the exact cause :(

Many thanks for help

**Comment by TWiStErRob** [comment]
See #1589 #1448 and probably [many more](https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=is%3Aissue%20banding).
