### ISSUE TITLE
Signature issue with the placeholder

### ISSUE THREAD

**Issue by RobertoMorelos** [bumptech/glide#1609]
**Glide Version**:  'com.github.bumptech.glide:glide:3.7.0'

**Integration libraries**: N/A

**Device/Android Version**: 6.0.1

**Issue details / Repro steps / Use case background**: This issue happens when I try to put the signature and a placeholder. The first time I launch my app the ImageView shows the placeholder image but when I launch another one and then relaunch the previous one my image is there. The funny thing is if I remove the placeholder the behavior is the expected.  I really need to put the holder because sometimes the image takes a while to be displayed. Any one with the same issue?
Bellow is the code I'm using:

**Glide load line**:
```java
Glide.with(this)
                .load(loggedUser.getProfileImageURL())
                .fitCenter()
                .signature(new StringSignature(loggedUser.getSignature()))
                .placeholder(R.drawable.placeholder_user)
                .error(R.drawable.error_user)
                .centerCrop()
                .into(imageViewUserProfile);
```

**Comment by TWiStErRob** [comment]
Goodbye.

(*Feel free to reopen if you filled in the details in the opening comment by editing via the pencil in top right.*)

**Comment by RobertoMorelos** [comment]
Sorry, my first post

**Comment by TWiStErRob** [comment]
Can you please elaborate on this part:

> The first time I launch my app the ImageView shows the placeholder image but when I launch another one and then relaunch the previous one my image is there.

**Comment by RobertoMorelos** [comment]
I have two Activities, the main one and profile activity. When I launch my app it starts with the main activity so I have a navigation drawer which takes me to profile activity. When I do this instead of showing me the picture in the ImageView it shows the placeHolder. Then I go back and return to profile activity and now I have the image from the URL. The thing is if I remove the placeholder this never happens and since the first attempt the ImageView displays the image from the URL.

**Comment by TWiStErRob** [comment]
Any chance `imageViewUserProfile` is a CircleImageView? See https://github.com/bumptech/glide#compatibility

**Comment by RobertoMorelos** [comment]
Yes, I forgot to say that!

**Comment by TWiStErRob** [comment]
Check those linked issues for explanation, feel free to ask here (even after closed) if you need more info.

**Comment by RobertoMorelos** [comment]
Thank you man! Really helpful!
