### ISSUE TITLE
Signature issue with the placeholder

### ISSUE THREAD

**Issue by RobertoMorelos** [bumptech/glide#1610]
**Glide Version**:  'com.github.bumptech.glide:glide:3.7.0'

**Integration libraries**: N/A

**Device/Android Version**: 6.0.1

**Issue details / Repro steps / Use case background**: This issue happens when I try to put the signature and a placeholder. The first time I launch my app the ImageView shows the placeholder image but when I launch another one and then relaunch the previous one my image is there. The funny thing is if I remove the placeholder the behavior is the expected.  I really need to put the holder because sometimes the image takes a while to be displayed. Any one with the same issue?
Bellow is the code I'm using:

**Glide load line **:
```java
Glide.with(this)
                .load(loggedUser.getProfileImageURL())
                .fitCenter()
                .signature(new StringSignature(loggedUser.getSignature()))
                .placeholder(R.drawable.placeholder_user)
                .error(R.drawable.error_user)
                .centerCrop()
                .into(imageViewUserProfile);
```

**Comment by TWiStErRob** [comment]
#1609
You can simply rename an issue; there's an Edit button on top.
