### ISSUE TITLE
Gif only show partly.

### ISSUE THREAD

**Issue by mcxtzhang** [bumptech/glide#1612]
Gif only show partly.
When I use glide to load gif, most of gif image is normal.
But  a few of gifs is show partly.
Such as  "http://pic.anlaiye.com.cn/f905e87b5fb04d1dab80084dcc78151e_240x240.gif"

![](http://ac-mhke0kuv.clouddn.com/ad81682ec9aa7e9265a9.gif)

This is my codes:
```xml
    <ImageView
        android:id="@+id/aaa"
        android:layout_width="100dp"
        android:layout_height="100dp"/>
```

```java
        Glide.with(this)
                .load("http://pic.anlaiye.com.cn/f905e87b5fb04d1dab80084dcc78151e_240x240.gif")
                .asGif()
                .into((ImageView) findViewById(R.id.aaa));
```

**Comment by TWiStErRob** [comment]
Try to use [3.8.0](https://github.com/bumptech/glide/wiki/Snapshots), there are numerous GIF issues fixed there. Please let me know if that fixes your issue, it may be new one we're not aware of.

Note: I cannot access the GIF url you posted.

**Comment by mcxtzhang** [comment]
Thank you！I dowload jar ( glide-3.8.0-20160712.015114-14 ).
It works.
