### ISSUE TITLE
Request Failed 404 : Not Found

### ISSUE THREAD

**Issue by meet2011** [bumptech/glide#1614]
I'm facing some weird issues while loading images into list-view. Initially it loads when its scrolled some images disappears and throws request failed 404 not found. We're looking for a library that can help us to load 50-100 images in a list-view without any hassle of 100-200 kb per image. is that possible with Glide?

```java
Glide.with(context)
                .load(url)
                .placeholder(R.color.Black)
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .dontAnimate()
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {

                        Log.d(TAG,e.getLocalizedMessage(),e);
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        return false;
                    }
                })
                .into(imageView);
```

**Comment by TWiStErRob** [comment]
That looks correct, I don't see anything strange.

Tip: One thing you might want to change: `e.getLocalizedMessage()` to `String.valueOf(e)`, because `e` can be `null`.

Further investigation:
 * Do you want to load those 50-100 at once, or in a normal list of 4-8 items per screen? Either way, Glide shouldn't be causing problems like random 404s.
 * I would look into your server side for reasons of rejection, for example rate limiting.
 * Try to log those `url`s/`model`s and see if there are anything common between those which fail. One suspicion is having special chars in them and/or wrong percent escapes.
 * Try to swap out the default networking layer with OkHttp-integration to see if anything changes.

**Comment by meet2011** [comment]
@TWiStErRob Yes we're going to load about 10-15 images per loading. I don't think there is any kind of special chars because if it loads for the first time then there won't be any such chars. 

Our image format is **JPEG**. is that causing the problem?

> aa912db6c5.jpeg

**Comment by meet2011** [comment]
@TWiStErRob Once the image is loaded, doesn't it load from cache? Why it goes for the URL to load?

**Comment by TWiStErRob** [comment]
It doesn't matter what the url/file name is, the important part is the first few bytes. But if Glide gets to that point it's already processing an HTTP 200.

Don't rule out anything, but I suggest to verify my ideas one by one. For example you said the first page loads, ok, that rules out the first 10 images, what about images 15-25?

**Comment by TWiStErRob** [comment]
Hmm, do you mean that if you scroll down and back, then sometimes the first ~10 get 404?

**Comment by meet2011** [comment]
Yes sometimes it gives 404 for the already loaded image during scroll. I will try your idea to investigate further.

**Comment by TWiStErRob** [comment]
RESULT should keep reloading from disk cache. It's quite possible that your item view size changes, and that forces a cache miss.

Take a look around https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling and https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/utils/LoggingListener.java for debugging tips. Look for non-matching sizes. What's your XML btw?

**Comment by meet2011** [comment]
**XML file**
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/Black">

    <LinearLayout
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <ImageView
            android:id="@+id/ivBannerShop"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:minWidth="0dp" />


        <RelativeLayout
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:gravity="center_vertical">


            <TextView
                android:id="@+id/tvShopWallpaperTitle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentLeft="true"
                android:layout_centerVertical="true"
                android:layout_marginLeft="15dp"
                android:text="Wallpaper 1"
                android:textColor="@color/White"
                android:textSize="16sp" />

            <Button
                android:id="@+id/btnWallpaperStatus"
                android:layout_width="150dp"
                android:layout_height="40dp"
                android:layout_alignParentRight="true"
                android:layout_centerVertical="true"
                android:layout_margin="10dp"
                android:background="@color/Red"
                android:text="Free"
                android:textColor="@color/White" />

        </RelativeLayout>

    </LinearLayout>


</RelativeLayout>
```

**Comment by TWiStErRob** [comment]
The outer layout is unnecessary, but other than that I don't see anything obvious right now.

What does `minWidth=0` do? Maybe try without.

**Comment by meet2011** [comment]
minWidth=0 is used to stretch the image on tablet devices. I'm not sure if its working without using the attribute.
