### ISSUE TITLE
The cache file extension

### ISSUE THREAD

**Issue by CiccioJoe** [bumptech/glide#1620]
**Glide Version**: 3.7.1  

 
 
**Device/Android Version**: Xiaomi Redmi Note 3 Pro / 6.0

 

The cache file has an extension ".0" . Can i modify it? i want a .gif extension

**Comment by TWiStErRob** [comment]
No, you can't unless you write your own cache implementation for Glide. (See `DiskCache` interface.)

As a workaround you can copy the file out of cache and give it the name you want, or in case you're sharing the file with some third party, use the correct mime type, so they don't have to fall back to deducing the file type from extension.

If you specify why you want to do this, it's possible we can suggest a better solution.

**Comment by CiccioJoe** [comment]
when I try to share (ex. with whatsapp) the cache file with .0 extension, this fails with error code (of course) not supported file.

 @Override protected File doInBackground(String... params) {
            String url = params[0]; 
            try {
                 
                return Glide
                        .with(context)
                        .load(url)
                        .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                        .get()
                        ;

            } catch (Exception ex) {
                Log.w("SHARE", "Sharing " + uri + " failed", ex);
                return null;
            }
        }
        @Override protected void onPostExecute(File result) {
            if (result == null) {Log.w("NULL", "NULL "); return; }

            Uri uri = FileProvider.getUriForFile(context, "kefaapplication.specialgif.fileprovider" , result);
            Log.w("URI", uri.getPath() + " "+uri.getAuthority()+ "file Name"+result.getName());
            share(uri); 
        }

        private void share(Uri result) {
            Intent intent = new Intent(Intent.ACTION_SEND);
            intent.setType("image/*");
            intent.putExtra(Intent.EXTRA_SUBJECT, "SUBJECT);
            intent.putExtra(Intent.EXTRA_TEXT, "MyText");
            intent.putExtra(Intent.EXTRA_STREAM, result);
            context.startActivity(Intent.createChooser(intent, "Share image"));
        }

**Comment by broapplication** [comment]
Any suggestions?

**Comment by TWiStErRob** [comment]
The way I see it is `image/*` is not a valid mime type, it's a valid mime type matcher when using intent filters. Try to set it to `image/gif` and also check out the conversation #459 particularly the ones related to `String getType(Uri uri)`. If setting both of those types to `image/gif` doesn't help, my only suggestion is to send feedback to WhatsApp to handle the Android intents and content providers correctly.

**Comment by TWiStErRob** [comment]
As an alternative workaround you can always copy the File out of Glide cache and name it however you want, just don't forget to delete the File after it has been used.
