### ISSUE TITLE
setting Background of a layout as a gif

### ISSUE THREAD

**Issue by ajithkpistar** [bumptech/glide#1623]
How to load a Gif image into a background of a layout.I want to load the gif image into bacgound of a layout.is it possible ??? then how????

**Comment by TWiStErRob** [comment]
See #938.

GIF or not shouldn't matter, because GlideDrawable is expected in both cases.
Please let me know if the solution provided there doesn't work for animated GIFs.

**Comment by ajithkpistar** [comment]
I am Not getting clearly pls give the sample code that will be helpfull

**Comment by TWiStErRob** [comment]
I can't explain more than https://github.com/bumptech/glide/issues/938#issuecomment-176150770
