### ISSUE TITLE
Gif play slow on certain gif picture

### ISSUE THREAD

**Issue by nuaawango** [bumptech/glide#1625]
Hi,
    i meet a problem:when i load certain gif, it play very slow,when i use fresco or android-gif-drawable,it play well.
    please tell me what's wrong, thanks a lot !

**Glide Version**:3.7.0

**Integration libraries**:okhttp:3.4.1

**Device/Android Version**:android 6.0.1

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(mContext).load(gifUrl).into(mImageView);
```

**Layout XML**:
```xml
        <ImageView
            android:id="@+id/img_gift_right"
            android:layout_width="80dp"
            android:layout_height="90dp"
            android:layout_gravity="center" />
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by nuaawango** [comment]
![gift](https://cloud.githubusercontent.com/assets/17288330/20711599/8c2d608a-b67b-11e6-96b5-48be1e2285dd.gif)

**Comment by TWiStErRob** [comment]
Do you mean it starts to play slow or the frames come slow one after the other?

I assume it starts slow, so add `.diskCacheStrategy(SOURCE)` to your load, and Google "glide slow gif" or #281 for more info. If the frames are slow, please reopen.

**Comment by m4xp1** [comment]
The frames are slow, what is the problem?

**Comment by TWiStErRob** [comment]
@m4xp1 can you please post a GIF url? There's a minimum frame display time limit. So even if the GIF file says play this frame for 1ms, it'll be displayed for a longer time. Don't remember exactly off the top of my head how much.

**Comment by karthickperumal** [comment]
@TWiStErRob Hi please tell me where to use this .diskCacheStrategy(SOURCE).
