### ISSUE TITLE
Unable to Load Images or Gifs from URL

### ISSUE THREAD

**Issue by Kazi101** [bumptech/glide#1626]
**Glide Version**:

I'm using Glide version 3.7.0.

**Integration libraries**:

**Device/Android Version**:

I am using a Samsung Galaxy S7 and had the same issue when running a Nexus 5 emulator.

**Issue details / Repro steps / Use case background**: 

I am looking to use Glide to load gifs from online in order to cut down on memory used by my app. Right now I am able to load gifs from my Assets folder and display them using a web view. When using Glide the only thing that will show is when I include .onError(R.drawable."some image") in which case it shows that image.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
I'm not doing anything too crazy with Glide.
```java
ImageView imageViewGif = (ImageView) findViewById(R.id.gif);

        String gifUrl = "http://imgur.com/gallery/4tm6M";

        Glide
                .with(this)                 // <--this being the current activity I'm trying to show the gif in.
                .load(gifUrl)
                .fitCenter()
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(imageViewGif);
```

**Layout XML**:
My xml consists of an ImageView wrapped in a Relative layout put below a TextView.
```xml
<ImageView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:id="@+id/gif"
        android:layout_below="@id/description"/>

```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
I think your problem is really simple:
http://imgur.com/gallery/4tm6M is not a GIF, try http://i.imgur.com/lyBgod3.gif

If you [add a listener or log the exception](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) it should say so. There's also a log from the system usually:
> skia: decoder->decode returned false

**Comment by Kazi101** [comment]
The gif you provided did work, which confuses me. Shouldn't it not matter if it is a gif or an image for it to load? Either way this is the actual URL I am trying to load and it is not loading. (http://imgur.com/a/tbGrk)

Upon looking at the logs it comes up as nullISkImageDecoder:: Factory returned null) despite being a valid URL. I have run into this issue whenever I try other image and gif URLs that aren't the one you provided. Am I misunderstanding the URL format? Also I noticed you have .gif at the end of your URL and it loads just the gif in browser. I tried this with other gifs and I was told the URL didn't exist. Why is that? Sorry if this is the wrong place to ask these questions. If you have a better place to redirect me I would appreciate that as well.

**Comment by TWiStErRob** [comment]
The link you're providing is a website:
![image](https://cloud.githubusercontent.com/assets/2906988/20801434/2f5b9e3e-b7e9-11e6-9b01-e61a7c1cd3fc.png)
Glide/Android won't parse the HTML for you looking for potential images.

You're trying to load gallery/albums, you need to load images directly, for example the one you provided is http://i.imgur.com/Wjr6scd.gif
I right clicked the video and pressed Inspect to get the direct Url (replace mp4 with gif):
![image](https://cloud.githubusercontent.com/assets/2906988/20801582/bdffcf2a-b7e9-11e6-8db5-23ed7424fd9a.png)

**Comment by Kazi101** [comment]
That'd be the issue. Makes sense to me now. Thanks for the help. Works exactly as I need it to.
