### ISSUE TITLE
Display gif problem

### ISSUE THREAD

**Issue by Drizzlezhang** [bumptech/glide#1627]
When I use DiskCacheStrategy except DiskCacheStrategy.SOURCE to display remote gif , it seems won't work(the target ImageView display nothing)

**Glide Version**:3.7.0

**Integration libraries**:okhttp3-integration:1.4.0

**Device/Android Version**:all

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context)
                    .load(url)
                    .priority(Priority.NORMAL)
                    .diskCacheStrategy(DiskCacheStrategy.SOURCE) // DiskCacheStrategy.SOURCE is ok , but others won't display gif successfully
                    .crossFade(500)
                    .into(imageview);
```

Now I use this method in a RecyclerView which play many gifs , and I think DiskCacheStrategy.RESULT maybe lead to OOM .

**Comment by TWiStErRob** [comment]
Use https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling to figure out what's the actual behavior, it's easier than guessing :)

**Comment by Drizzlezhang** [comment]
@TWiStErRob Thanks for your answer.
Our project has a RecyclerView with many pictures(or gif), before use DiskCacheStrategy.SOURCE , in Android Monitor it need about 100M memory , now it need about 150M  We all know some Android devices have limited memory , and online OutOfMemoryError has no stack available usually , so I have to worry about OOM.

**Comment by TWiStErRob** [comment]
To reduce the possibility of OOM on low-end devices you may want to consider showing `.asBitmap()` of the GIF first in the RV on those devices and play them only on user interaction.

**Comment by Drizzlezhang** [comment]
@TWiStErRob An useful solution!

**Comment by TWiStErRob** [comment]
So, what's the deal with the original issue? `RESULT` loads slowly, or you have some exception?

**Comment by Drizzlezhang** [comment]
@TWiStErRob Yes , `RESULT` loads slowly , so I have to use `SOURCE` to display gif . Now I use `asBitmap` to reduce OOM on low memory devices .

**Comment by jpage4500** [comment]
I updated glide to the latest version and DiskCacheStrategy values have changed.. is a special .gif solution still required?
