### ISSUE TITLE
Saving gif image using listener

### ISSUE THREAD

**Issue by prabinshrestha** [bumptech/glide#1628]
Hello,
I am trying to save the gif image but it is only saving the first frame of gif so i would like to save the gif image that saves all the frame.

Please help me, I am new to this.

Please provide me an example.

**Comment by TWiStErRob** [comment]
Please provide more info. Based on what you said so far, I think you're looking for `.downloadOnly`. Also you're potentially using `.asBitmap()`, and a Bitmap can only store a single frame.

**Comment by prabinshrestha** [comment]
Hey,there you go- this is my sample code.I have finally success to create gif with frame but i want a better solution if you can give me any suggestion or example.

 Glide.with(itemView.getContext())
                    .load(url).asGif().listener(giflistener)
                    .into(imageView);

//giflistener
 @Override
            public boolean onResourceReady(final GifDrawable resource, final String model, final Target<GifDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
  
                btnFullImageDownload.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        if (fullScreenImageListener != null) {
                            LoggerUtils.log(TAG, "framecount" + resource.getFrameCount() + " " + model);

                            ByteArrayOutputStream bos = new ByteArrayOutputStream();
                            AnimatedGifEncoder encoder = new AnimatedGifEncoder();
                            encoder.start(bos);

                            final GifDecoder gifDecoder = resource.getDecoder();
                            final int frameCount = resource.getFrameCount();
                            for (int i = 0; i < frameCount; i++) {
                                gifDecoder.advance();
                                Bitmap bitmap = Bitmap.createBitmap(gifDecoder.getNextFrame());
                                int delay = gifDecoder.getDelay(i);
                                encoder.addFrame(bitmap);
                                encoder.setDelay(delay);
                            }

                            encoder.finish();
                  //lastly convert to byte array to create gif
                     createGifFileWithByteArray(bos.toByteArray());
                return false;
            }

**Comment by TWiStErRob** [comment]
Hmm, the use of encoder reminded me of #1570, does that help? `.downloadOnly` saves the original image, but it looks like you want to save the resized image. If you can make do with the original, consider #459.

Note: you're doing a lot of work on the UI thread, you should consider moving that. #1570 provides methods that are useful on a worker thread (and only there). If you use `.diskCacheStrategy(SOURCE)` it'll prevent downloading the url twice, and you can make your saving logic independent of `onResourceReady` by using the `url` only.

**Comment by prabinshrestha** [comment]
Hey friend I put my code on the background thread to download the full gif and save it to  the customized location of my file with "blablabla.gif" extension when i open on the explorer app on my xiomi redmi note 3 device gif plays and also gallery app plays gif too but photoviewer app and other app didn't play it,do we have to do something that  system will recognize it as gif.

Please provide me some idea.

class GifAsyncTask extends AsyncTask<Void, Void, File> {
                
                @Override
                protected File doInBackground(Void... params) {
                    LoggerUtils.log(TAG, "download " + url);
                    try {
                        return Glide
                                .with(context)
                                .load(url)
                                .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                                .get(); // needs to be called on background thread

                    } catch (Exception ex) {
                      LoggerUtils.log(TAG,ex.getMessage());
                        return null;
                    }
                }

                @Override
                protected void onPostExecute(File file) {
                    super.onPostExecute(file);
                    if (file == null) {
                        return;
                    }
                     //save our gif
                      saveGifImage(context,getBytesFromFile(file),"blablabla.gif");
                }

                public byte[] getBytesFromFile(File file) throws IOException {
                    // Get the size of the file
                    long length = file.length();

                    // You cannot create an array using a long type.
                    // It needs to be an int type.
                    // Before converting to an int type, check
                    // to ensure that file is not larger than Integer.MAX_VALUE.
                    if (length > Integer.MAX_VALUE) {
                        // File is too large
                        throw new IOException("File is too large!");
                    }

                    // Create the byte array to hold the data
                    byte[] bytes = new byte[(int) length];

                    // Read in the bytes
                    int offset = 0;
                    int numRead = 0;

                    InputStream is = new FileInputStream(file);
                    try {
                        while (offset < bytes.length
                                && (numRead = is.read(bytes, offset, bytes.length - offset)) >= 0) {
                            offset += numRead;
                        }
                    } finally {
                        is.close();
                    }

                    // Ensure all the bytes have been read in
                    if (offset < bytes.length) {
                        throw new IOException("Could not completely read file " + file.getName());
                    }
                    return bytes;
                }


    public  ImagePath saveGifImage(Context context, byte[] bytes, String imgName) {
        ImagePath imagePath = new ImagePath();
        FileOutputStream fos = null;
        try {
            File externalStoragePublicDirectory =     Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES);
            File customDownloadDirectory = new File(externalStoragePublicDirectory, "Custom_Downloads");
            if (!customDownloadDirectory.exists()) {
                boolean isFileMade = customtDownloadDirectory.mkdirs();
                if (isFileMade) {
                } else {
                    LoggerUtils.log(TAG, "couldn't create custom download directory!");
                    imagePath.setImageSaved(false);
                    return imagePath;
                }
            }
            if (customDownloadDirectory.exists()) {
                File file = new File(customDownloadDirectory, imgName);
                fos = new FileOutputStream(file);
                fos.write(bytes);
                fos.flush();
                fos.close();
                /**Update image to gallery**/
                if (file != null) {
                    MediaStore.Images.Media.insertImage(context.getContentResolver(),
                            file.getAbsolutePath(), file.getName(), file.getName());
                    LoggerUtils.log(TAG, "Image saved!" + file.getAbsolutePath());
                    imagePath.setImageSaved(true);
                    imagePath.setPath(file.getAbsolutePath());
                }
                return imagePath;
            }
        } catch (Exception e) {
            e.printStackTrace();
            LoggerUtils.log(TAG, e.getMessage());
            return imagePath;
        }
        return imagePath;
    }

**Comment by prabinshrestha** [comment]
oh i made some mistakes not a glide problem sorry.Lastly thank you very much for your quick reply.Hurray Glide!

         if (file != null) {
                    ContentValues values = new ContentValues();
                    values.put(MediaStore.Images.Media.TITLE,  file.getName());
                    values.put(MediaStore.Images.Media.DISPLAY_NAME,  file.getName());
                    values.put(MediaStore.Images.Media.DESCRIPTION, "");
                    values.put(MediaStore.Images.Media.MIME_TYPE, "image/gif");
                    values.put(MediaStore.Images.Media.DATE_ADDED, System.currentTimeMillis());
                    values.put(MediaStore.Images.Media.DATE_TAKEN, System.currentTimeMillis());
                    values.put(MediaStore.Images.Media.DATA, file.getAbsolutePath());

                    ContentResolver contentResolver=context.getContentResolver();
                    contentResolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);

                   // MediaStore.Images.Media.insertImage(context.getContentResolver(),
                   // file.getAbsolutePath(), file.getName(), file.getName());
                    LoggerUtils.log(TAG, "Image saved!" + file.getAbsolutePath());
                    imagePath.setImageSaved(true);
                    imagePath.setPath(file.getAbsolutePath());
                }

**Comment by TWiStErRob** [comment]
Glad to see you made it work. My guess would've been that the Gallery app handles the files differently than Photoviewer.

Note: `onPostExecute` is still UI thread.
