### ISSUE TITLE
Glide RuntimeException

### ISSUE THREAD

**Issue by x2hokim** [bumptech/glide#163]
I'm using glide 3.3.1 latest version.

``` java
ImageView iv = (ImageView) findViewById(R.id.iv_profile);
Glide.with(this).load("http://goo.gl/h8qOq7").into(iv);
```

this simple code occurs follows Exceptions..

> 10-01 20:24:19.961: E/ACRA(10652): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=15, result=-1, data=Intent { (has extras) }} to activity {com.eztogether.nearbig/com.eztogether.nearbig.setting.SettingProfileActivity}: java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting

**Comment by deviant-studio** [comment]
Not a solution. What if my code already use tags heavily?

**Comment by TWiStErRob** [comment]
@deviant-studio you can keep looking and find #370 ;)
