### ISSUE TITLE
It is written in glide documentation that one may not need to worry about clearing memory when using glide. It will automatically release it when app is low in memory and reaches oom. My question is exactly which functions are called internally to do so? Class MemorySizeCalculator is used to initially allocate memory, but does this allocation change while app runs? Does it increase or decrease depending on memory requirements?

### ISSUE THREAD

**Issue by mgarg** [bumptech/glide#1634]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Glide handles events from [ComponentCallbacks][1] and [ComponentCallbacks2][2] to partially or completely clear the memory cache and bitmap pool. MemorySizeCalculator just sets the initial size of the memory cache and bitmap pool based on some heuristics (screen width, height, memory class, low ram etc).

[1]: https://developer.android.com/reference/android/content/ComponentCallbacks.html
[2]: https://developer.android.com/reference/android/content/ComponentCallbacks2.html

**Comment by mgarg** [comment]
can you please answer issue #1639
