### ISSUE TITLE
You cannot start load before it is attached

### ISSUE THREAD

**Issue by zihadrizkyef** [bumptech/glide#1635]
Before, glide works fine, but unfortunately i got internet problem which makes my internet so slow. Also it make me got many error which is said "You cannot start a load on a fragment before it is attached". Now, my internet connection is back to normal and i don't get that error anymore.

What i do :
-Open fragment 1 (contain recycler view with glide to load image)
-Open fragment 2
-Immediatelly back again to fragment 1

What i got :
-Error "You cannot start a load on a fragment before it is attached"

**Comment by sjudd** [comment]
You will need to make sure you're not starting loads before the fragment is attached or after the fragment is detached. It's hard to be more specific without parsing a lot of your code. 

There are a few cases it's quite difficult to do this, and nested fragments may be one of those cases.

**Comment by zihadrizkyef** [comment]
**FragmentList**
`    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        listMode = false;
        rvProductAdapter.setListMode(listMode);
        rvProductList.setLayoutManager(gridLayoutManager);
        rvProductList.setAdapter(rvProductAdapter);
        rvProductList.setHasFixedSize(true);

        downloadSignature = new StringSignature(String.valueOf(System.currentTimeMillis()));
        rvProductAdapter.setDownloadSignature(downloadSignature);

        if (isInternetAvailable()) {
            showListProduct(null, 0);
        } else {
            MainActivity.showToast("No internet connection", Toast.LENGTH_LONG);
            TextView tvEmpty = (TextView) mainView.findViewById(R.id.tvEmptyRecyclerView);
            tvEmpty.setHint("No internet connection");
            tvEmpty.setVisibility(View.VISIBLE);
        }
    }

    private void showListProduct(@Nullable final String name, final int category) {
        StringRequest showListProductSR = new StringRequest(Request.Method.POST, MainActivity.SERVER_URL + "/product/listproduct.php",
                new Response.Listener<String>() {
                    @Override
                    public void onResponse(String response) {
                        TextView tvEmpty = (TextView) mainView.findViewById(R.id.tvEmptyRecyclerView);
                        try {
                            JSONObject responseJSON = new JSONObject(response);
                            if (responseJSON.getBoolean("success")) {
                                tvEmpty.setVisibility(View.GONE);
                                rvProductAdapter.setProductData(responseJSON.getJSONArray("product"));
                            } else {
                                tvEmpty.setHint("No product");
                                tvEmpty.setVisibility(View.VISIBLE);
                                MainActivity.showToast(responseJSON.getString("message"));
                            }
                        } catch (JSONException e) {
                            e.printStackTrace();
                        }

                    }
                },
                new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        MainActivity.showToast(error, Toast.LENGTH_LONG);
                        TextView tvEmpty = (TextView) mainView.findViewById(R.id.tvEmptyRecyclerView);
                        tvEmpty.setHint("No product");
                        tvEmpty.setVisibility(View.VISIBLE);
                    }
                }) {
            @Override
            protected Map<String, String> getParams() throws AuthFailureError {
                if (name != null || category != 0) {
                    Map<String, String> param = new HashMap<>();
                    if (name != null) {param.put("name", name);}
                    if (category != 0) {param.put("category", String.valueOf(category));}
                    return param;
                }
                return super.getParams();
            }
        };
        volleyRequestQueue.add(showListProductSR);
    }`

in onActivityCreated() i call showListProduct() to get list of data of product from server, then i put the result to RecyclerView which is contain Glide. When i click an item of RecyclerView, it goes to FragmentViewProduct.java. Here's the code : 

`    @Override
    public void onResume() {
        super.onResume();

        downloadSignature = new StringSignature(String.valueOf(System.currentTimeMillis()));
        loadProductData();
    }

    private void loadProductData() {
        StringRequest srLoadData = new StringRequest(Request.Method.POST, MainActivity.SERVER_URL + "/product/readproduct.php",
                new Response.Listener<String>() {
                    @Override
                    public void onResponse(String response) {
                        try {
                            JSONObject responseJSON = new JSONObject(response);
                            if (responseJSON.getBoolean("success")) {
                                tvId.setText("Product code: "+String.valueOf(idToRead));
                                tvName.setText(responseJSON.getString("name"));
                                String priceText = "Rp " + NumberFormat.getNumberInstance(Locale.US).format(Integer.parseInt(responseJSON.getString("price")));
                                tvPrice.setText(priceText.replaceAll(",", "."));
                                CharSequence[] categoryName = new CharSequence[]{"Batik", "Lukis", "Lukis Bunga"};
                                tvCategory.setText("Category: "+categoryName[responseJSON.getInt("category")-1]);
                                tvStock.setText("Stock: "+responseJSON.getString("stock"));
                                tvDescription.setText(responseJSON.getString("description"));
                                rbStar.setRating(Float.parseFloat(responseJSON.getString("rating")));

                                JSONArray listImageUrl = new JSONArray(responseJSON.getString("imageurl"));
                                for(int i=0; i<listImageUrl.length(); i++) {
                                    final String imageUrl = MainActivity.SERVER_URL+"/product/asset/"+listImageUrl.getString(i);
                                    if (i==0) {
                                        lyImageList.removeView(mainView.findViewById(R.id.ivImageChild));
                                        Glide.with(fragmentActivity)
                                                .load(imageUrl)
                                                .crossFade()
                                                .placeholder(R.drawable.loading)
                                                .error(R.drawable.noimage)
                                                .signature(downloadSignature)
                                                .into(ivImageMain);
                                    }

                                    final ImageView ivImageChild = new ImageView(fragmentActivity);
                                    LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
                                    if (i < listImageUrl.length()-1) {
                                        layoutParams.rightMargin = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 3, getResources().getDisplayMetrics());
                                    }
                                    ivImageChild.setLayoutParams(layoutParams);
                                    ivImageChild.setScaleType(ImageView.ScaleType.FIT_XY);
                                    ivImageChild.setAdjustViewBounds(true);
                                    ivImageChild.setTag(R.string.tagId, i);
                                    ivImageChild.setOnClickListener(new View.OnClickListener() {
                                        @Override
                                        public void onClick(View view) {
                                            Glide.with(FragmentViewProduct.this)
                                                    .load(imageUrl)
                                                    .crossFade()
                                                    .placeholder(R.drawable.loading)
                                                    .error(R.drawable.noimage)
                                                    .signature(downloadSignature)
                                                    .into(ivImageMain);
                                        }
                                    });
                                    Glide.with(FragmentViewProduct.this)
                                            .load(MainActivity.SERVER_URL+"/product/asset/"+listImageUrl.getString(i))
                                            .placeholder(R.drawable.loading)
                                            .error(R.drawable.noimage)
                                            .signature(downloadSignature)
                                            .into(ivImageChild);
                                    lyImageList.addView(ivImageChild);
                                }
                            } else {
                                MainActivity.showToast(responseJSON.getString("message"));
                            }
                        } catch (JSONException e) {
                            e.printStackTrace();
                        }
                    }
                },
                new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        MainActivity.showToast(error, Toast.LENGTH_LONG);
                    }
                }) {
            @Override
            protected Map<String, String> getParams() throws AuthFailureError {
                Map<String, String> params = new HashMap<>();
                params.put("id", String.valueOf(idToRead));
                return params;
            }
        };
        volleyRequestQueue.add(srLoadData);
    }`

in onResume() i put loadProductData() to load the selected item from FragmentListProduct, then proccess it which is contain Glide.

From above code, can you estimate what is wrong with my code?
