### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by luck-fc** [bumptech/glide#1636]
# main
java.lang.NoSuchMethodError
android.os.SystemClock.elapsedRealtimeNanos
1 com.bumptech.glide.g.e.a(LogTime.java:25)
2 com.bumptech.glide.request.GenericRequest.b(GenericRequest.java:262)
3 com.bumptech.glide.manager.l.a(RequestTracker.java:37)
4 com.bumptech.glide.h.b(GenericRequestBuilder.java:661)
5 com.bumptech.glide.h.a(GenericRequestBuilder.java:697)
6 com.bumptech.glide.f.a(DrawableRequestBuilder.java:448)

Android 4.2.2,level 17
ROM
HuaWei/EMOTION
armeabi-v7a

**Comment by rupinderjeet** [comment]
Its not an issue with Glide, [android.os.SystemClock.elapsedRealtimeNanos](https://developer.android.com/reference/android/os/SystemClock.html#elapsedRealtimeNanos()) is causing this. Is your API 17 SDK up to date?

**Comment by luck-fc** [comment]
Android SDK: Glide requires a minimum API level of 10.
this Is device does not support ?
