### ISSUE TITLE
How glide working ?is threre a sequence diagram ?

### ISSUE THREAD

**Issue by edconan93** [bumptech/glide#1638]
Hello, now Im trying to reseach deeply about glide library work, I ve traced code by debug when program running but the library is so big, someone can help me please? I need know the core of glide library , important functions and class, how the cache save and load , if there is a sequence diagram ,please send me, thank you so much

**Comment by TWiStErRob** [comment]
I've made this while learning Glide:
https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g
hope it helps.

The entry points you're probably interested in are `Engine.load` (called from `.into()`) and `EngineRunnable.run` (background internals of Glide).

If you think any more docs (you may write) would be helpful, feel free to reach out, we can it on the wiki.

**Comment by edconan93** [comment]
Thank you for your help, I will try more to learn about the library
