### ISSUE TITLE
Downloading Large Images in getCacheDir()

### ISSUE THREAD

**Issue by rupinderjeet** [bumptech/glide#1640]
I am using `downloadOnly()` only from Glide. If an image size is 100MB, does Glide still load it in `getCacheDir() + /image_manager_disk_cache/`. In this case, what happens if user is low on cache memory?

Version: 3.7.0
Integration libraries: No
Devices: Galaxy S2

I just want to know how can i dodge the exceptions and still download a big file of 100MB max. Can i just blindly load it in cache dir. Is there some way to use `getExternalCacheDir()`. I delete all cache while exiting my app. I also have a button for user to clear cache. So, Max cache i might have is 100MB, which is valid only for the time user is using the app.

```java
    File file = Glide.with(context)
                    .load(Uri.parse(fileUrl))
                    .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                    .get();
```

How does your app look like : not related
Logcat: 5-10 of GC/VFY freed/grow heap messages for downloading: 
Screenshots: not applicable

Do i still get bonus points?

**Comment by TWiStErRob** [comment]
Clearing on exit may not be reliable and also remember that LRU evicts items when the next one is loaded. So if you load a `99MB` image into a `100MB` cache, it may never be freed up unless you load something that's `>1MB`; only at the time of this second load the first file is deleted.

To relocate your cache: https://github.com/bumptech/glide/wiki/Configuration#location

*Please keep in mind that Glide is not a networking library, you may have more luck using a proper library that's meant for downloading (big) files; it may even support resuming the downloads!* You can still use Glide to decode that humongous image using the `.load(File)` overload.
