### ISSUE TITLE
Gif not loading when used as placeholder. 

### ISSUE THREAD

**Issue by larrytech7** [bumptech/glide#1642]
when i use a Gif as a drawable for my placeholder, the gif shows but doesn;t animate as expected or as it should. It's actually a gif to show 'loading' operation. If there's another way to make this happen i will be very grateful to learn, else if this is an issue, i need to know how to go about resolving it. 

**Glide Version**:
3.7.0

**Integration libraries**:
None, just firebase

**Device/Android Version**:
Samsung Note 3, android 5.0 API Level 21

**Issue details / Repro steps / Use case background**: 
Use a local gif as your placeholder resource

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context)
                    .load(imageUrl)
                    .crossFade()
                    .placeholder(R.drawable.loading)
                    .into(holder.mediaImage);
```

**Comment by TWiStErRob** [comment]
Sorry for the delayed reply, my life have been busy.

Sorry but using GIF as placeholder is not possible, see #659 for more info.
