### ISSUE TITLE
Where the priority use for arrange the request queue ?

### ISSUE THREAD

**Issue by edconan93** [bumptech/glide#1643]
Hello  , Im trace code glide but I dont know Where the priority use for arrange the request queue ? Can someone tell me the function use it ? And where the request add to the thread ??? Thank you

**Comment by TWiStErRob** [comment]
Look at `Engine.load` and `EngineRunnable`, also [here is](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/executor/FifoPriorityThreadPoolExecutor.java#L137) where the priority is read internally.

High priority loads will start before load priority ones, but they won't interrupt already running requests.
