### ISSUE TITLE
About glide parsing base64 format data

### ISSUE THREAD

**Issue by myhcqgithub** [bumptech/glide#1644]
Hello, the item needs to be done in my recycleview pictures show, but the server url interface returns the base64 format of the data, should excuse me I how to custom processing, urgent need, thank you very much!!!!!

**Comment by TWiStErRob** [comment]
#556 and the related https://github.com/TWiStErRob/glide-support/commit/e10619ef737d3adc60e19bf5fb224dc4c0d54055 commit has the 3 most common use cases, you should be able to easily build on these.

**Comment by myhcqgithub** [comment]
thanks!!!
