### ISSUE TITLE
Wiki says to remove usage of RequestListener in production

### ISSUE THREAD

**Issue by eygraber** [bumptech/glide#1645]
[The wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) has a strong note at the bottom of the section dealing with `RequestListener` that says:

>**Make sure to remove any usages of this class before releasing your application!**

What's the reasoning behind this? Are there performance issues, or is it because logging in production can disclose sensitive info?

**Comment by TWiStErRob** [comment]
> Here's an example implementation for quick debugging purposes

I wrote it so the production app is not polluted with temporary debugging tools. Leaving a `RequestListener` implementation that actually does something you want is obviously OK, but I would say just dumping every load's result is not wanted behavior in general. Sensitive info is also a good point.

See also #1576.
