### ISSUE TITLE
OOM exception when load a lot image in gridview

### ISSUE THREAD

**Issue by edconan93** [bumptech/glide#1646]
When I try to load ~2400 image from local storage   by a simple adapter and it catch OOM exception when scroll fast and stop sometime. I found that the cache of app have large size and not clear after out app, do we avoid the exception and manage cache saved duration by hand? Thank you

**Comment by edconan93** [comment]
And when i try with picasso it not happend

**Comment by TWiStErRob** [comment]
Can you please provide more info? An awful lot depends on how your adapter and loading code works. It may be as simple as a wrong approach to view holder recycling when you're using `ListView` (if you're using that). Feel free to reopen once you've shown some code.
