### ISSUE TITLE
How to use glide 4.0 to load app icon

### ISSUE THREAD

**Issue by csshuai** [bumptech/glide#1647]
```
    String apkFilePath;
    PackageManager packageManager = getActivity().getPackageManager();
    PackageInfo info = packageManager.getPackageArchiveInfo(apkFilePath, PackageManager.GET_ACTIVITIES);
    ApplicationInfo appInfo = info.applicationInfo;
    Drawable drawable = appInfo.loadIcon(packageManager);
```

can i change above code into glide 4.0?

https://groups.google.com/forum/#!topic/glidelibrary/MAqPfuHpjr4

**Comment by csshuai** [comment]
I solve it.
[https://gist.github.com/csshuai/9ccab646e35194eddafca9929cd9ad01](url)

**Comment by TWiStErRob** [comment]
Sorry for not answering in time, nice job.

See also https://groups.google.com/forum/#!topic/glidelibrary/LRMHdhLNRfc for more info on app icon loading.
