### ISSUE TITLE
show gif problem 

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [bumptech/glide#1649]
```gradle
   //glide
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'
```

Device/Android Version:
Samsung Galaxy7 edge, android 6.0 
meizu mx5, android 5.0 

```java
     Glide.with(context)
                .load(url)
                .asGif()
                .dontAnimate()      
                .placeholder(R.drawable.ic_stub)
                .error(R.drawable.ic_error)
                .into(imageView);
```

GIF will show some GIF frame is incomplete, but these GIF in the computer and other applications show no problem, so the GIF itself should be no problem.
ps:I try to use fresco no problem

**Comment by sjudd** [comment]
Can you attach the GIF in question?

**Comment by AndroidJohnsonWang** [comment]
![a003](https://cloud.githubusercontent.com/assets/15881869/21283042/df70d704-c436-11e6-9307-127ad2688f71.gif)
![a001](https://cloud.githubusercontent.com/assets/15881869/21283043/dfa06ed8-c436-11e6-9991-9455bc41f8fb.gif)
![a006](https://cloud.githubusercontent.com/assets/15881869/21283045/e0d23e26-c436-11e6-9c1f-0e16ae00c50c.gif)
![a020](https://cloud.githubusercontent.com/assets/15881869/21283044/dfda1c96-c436-11e6-86ee-81ed97b0992f.gif)
@sjudd

**Comment by SimplySu** [comment]
@AndroidJohnsonWang you can try glide:3.8.0-SNAPSHOT for a test trying which fix some bugs about gif showing.
I try these pictures in the 3.8.0-SNAPSHOT, they show ok and correct.

**Comment by AndroidJohnsonWang** [comment]
@SimplySu Thanks,When will the official release（3.8.0）?

**Comment by SimplySu** [comment]
I was also very expected to know, you can ask @TWiStErRob @sjudd

**Comment by TWiStErRob** [comment]
Closing as duplicate for one of #1323's fixes.
Good question about release, SNAPSHOT is pretty stable, as in: it wasn't modified much in the past and I wouldn't include breaking changes in the future because we know many people are using it.
