### ISSUE TITLE
Feature: efficient rounding

### ISSUE THREAD

**Issue by AlexBlokh** [bumptech/glide#165]
Transformation is always a creation and allocation of at least one more bitmap in memory. There is a way to make it way more efficient. RoundedImageView with RoundedDrawable. You just path a bitmap to roundedImageView, then it is passed to a roundedDrawable, transform matrices are calculated, bitmapShader swaps the bitmap and it just draws a circle or a rounded rectangle, or a shape with bitmapShader and it's way more efficient than making a transformation. But when I using this way of drawing rounded image, I'm not able to use a great feature of your library - crossfade. 
So if it's possible to make a workaround of it?

**Comment by AlexBlokh** [comment]
the only one thing, that prevents me to do all the stuff, is that 
```java
public class GlideBitmapDrawable extends Drawable
```

how can I get the bitmap from the GlideBitmapDrawable in library, where there is no dependency on Glide? Reflection or something else? Can you please help?

**Comment by sjudd** [comment]
You should be able to just pass in a [``BitmapTransformation``][1] to [``transform()``][2]? In theory you shouldn't need to mutate the drawable at all?

Keep in mind that you can also just request a Bitmap by using [``asBitmap()``][5]:

```java
    Glide.with(fragment)
        .load("imageUrl")
        .asBitmap()
        .into(new SimpleTarget<Bitmap>(width, height) {
             ...
        });
```

If you really need to mutate the Drawable, the only real solution is to use instanceof and cast the ``GlideDrawable`` to [``GlideBitmapDrawable``][3], keeping in mind that it may also be a [``GifDrawable``][4]. 

[1]: http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/load/resource/bitmap/BitmapTransformation.html
[2]: http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/DrawableRequestBuilder.html#transform(com.bumptech.glide.load.resource.bitmap.BitmapTransformation...)
[3]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/load/resource/bitmap/GlideBitmapDrawable.html
[4]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/load/resource/gif/GifDrawable.html
[5]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/DrawableTypeRequest.html#asBitmap()

**Comment by AlexBlokh** [comment]
Hi, guys! It's been a while

so basically I'll just copy my issue from here https://github.com/vinc3m1/RoundedImageView/issues/196

Hi!
I'm not really sure it has to be here, but there're an issue with Glide library producing Transition Drawable and this library not being able to round it.

There're mainly two pitfalls:
1 - Transition drawable leaves a hidden layer visible after crossfading(fading) drawable in (if you're familiar with overdrawing - you know what I mean)

2 - Transition drawable extends from LayerDrawable(which has horrible api as for me) and LayerDrawable doesn't set drawable ids by default and you can only set drawables by there indexes and index is only obtained by their ids

so, here are some screencasts. My implementation is on the left:

overdrawing
![overdraw](https://user-images.githubusercontent.com/4045375/30382169-1c0287c2-98a7-11e7-8480-529bcacafc70.gif)

rounding
![rounded_rorners](https://user-images.githubusercontent.com/4045375/30382137-00c9ac1a-98a7-11e7-9763-d212ea24d105.gif)

There's basically an issue with TransitionDrawable, background layer remains visible after transition, causing overdrawing. 
And another issue with transition drawable is that by default transition drawable does not set drawable ids. So it has to be done manually, or RoundedImageView(anybody else) won't be able to change those drawables

Here's my implementation, you can examine it. Maybe we'll leave it as a gist, but I'd still recommend to put that stuff into doc. Would save a lot of times for devs. And might have a performance boost also

https://gist.github.com/AlexBlokh/c4294d355048c50cba137895be7a6a8d
