### ISSUE TITLE
There is an additional yellow point when load a GIF

### ISSUE THREAD

**Issue by SwayChen** [bumptech/glide#1652]
use `compile 'com.github.bumptech.glide:glide:3.8.0-SNAPSHOT'`

My codes:
```java
Glide.with(this).load(R.mipmap.christmas_tree).asGif().diskCacheStrategy(DiskCacheStrategy.SOURCE).into(imageView);
```
There has a yellow point like the picture below:
![1](https://cloud.githubusercontent.com/assets/6345749/21304789/8312899e-c602-11e6-94f9-ffea5eacadae.png)

What's more, I found it plays a little slow, compared with `pl.droidsonroids.gif:android-gif-drawable:1.2.3`

**Comment by SwayChen** [comment]
Here is the GIF file. Maybe you can have a try.
![christmas_tree](https://cloud.githubusercontent.com/assets/6345749/21304827/bde1f438-c602-11e6-904a-97f60e79b118.gif)

**Comment by TWiStErRob** [comment]
Re slowness: https://github.com/bumptech/glide/blob/6d44b1834e07ae3a81162eb9a165d4c3364b6723/third_party/gif_decoder/src/main/java/com/bumptech/glide/gifdecoder/GifHeaderParser.java#L162-L164
The frames are coming too fast, it may be only possible to decode that fast if you pre-process the whole file (like the lib you said). Glide does on-the-fly frames and uses the delays used by browsers, see #205 for more info. The GIF you've shared seems to go with 40ms, so it's likely the device that cannot deal with that fast decodes.

I'll check the dot when I have time, that's an interesting issue which shouldn't be there.

**Comment by SwayChen** [comment]
@TWiStErRob Thanks for looking the additional dot. And about the slowness, it runs on Nexus 5 (I think it should be with a nice hardware performance), but I accept your point of pre-precess 0_0

**Comment by TWiStErRob** [comment]
I'll also look at speed when I get here. I agree, the the GIF is small, so it shouldn't be a big deal for any high-end phone.
