### ISSUE TITLE
Incorrect Integration libraries wiki instruction

### ISSUE THREAD

**Issue by s3r6** [bumptech/glide#1653]
https://github.com/bumptech/glide/wiki/Integration-Libraries#okhttp-with-gradle

> When you use the `@aar` qualifier the integration library's GlideModule will be merged into your application's manifest automatically. When using `@jar` or omitting the qualifier you need include the library module yourself or use the classes in your own GlideModule.

Should be 

When you use **no qualifier** the integration library's GlideModule will be merged into your application's manifest automatically. When using `@jar` **or `@aar`** qualifier you need include the library module yourself or use the classes in your own GlideModule.

No qualifier
```
+--- com.github.bumptech.glide:okhttp-integration:1.4.0
|    +--- com.github.bumptech.glide:glide:3.7.0
|    \--- com.squareup.okhttp:okhttp:2.2.0
|         \--- com.squareup.okio:okio:1.2.0 -> 1.9.0
```

aar qualifier
```
+--- com.github.bumptech.glide:okhttp-integration:1.4.0
```

**Comment by TWiStErRob** [comment]
I think you may be confusing two things: manifest merging and transitive Gradle dependencies.

Check the `<meta-data` tags after an `assembleDebug` in `build\intermediates\manifests\full\debug\AndroidManifest.xml` to see what those sentences are referring to.

Let me know if you still think it's wrong.
