### ISSUE TITLE
Load video frames with different time , it always show the first frame.

### ISSUE THREAD

**Issue by AnswerZhao** [bumptech/glide#1656]
Glide 3.7.0
Load video frames with different time ,but  it always show the first frame,
```java
final BitmapPool bitmapPool = Glide.get(getContext()).getBitmapPool();
VideoBitmapDecoder videoBitmapDecoder = new VideoBitmapDecoder(microSecond);
FileDescriptorBitmapDecoder fileDescriptorBitmapDecoder = new  FileDescriptorBitmapDecoder(videoBitmapDecoder, bitmapPool,    DecodeFormat.PREFER_ARGB_8888);
Glide.with(getContext())
                        .load(mSrc)
                        .asBitmap()
                        .override(thumbSize,thumbSize)
                        .placeholder(R.mipmap.ic_album_no_photos)
                        .diskCacheStrategy(DiskCacheStrategy.RESULT)
                        .centerCrop()
                        .videoDecoder(fileDescriptorBitmapDecoder)
                        .into(((ViewHolder)holder).mImageView);
```
Please help me.

**Comment by TWiStErRob** [comment]
Did you clear the cache? If not try that, and if that helped you'll need to add a `signature()` that incorporates the `microSecond` into the cache key.

`VideoBitmapDecoder#getId` should have included it; as a workaround you can extend that class and override `getId`, this is an alternative to using a signature.

@sjudd v4 should make sure to use all the possible params in all `getId`s. Does the `Option` system make this obsolete?

**Comment by sjudd** [comment]
@TWiStErRob Yes, Options should make all of the things we'd been passing to constructors of decoders to customize their behavior obsolete. Changing the specific frame of the video the user wants to decode is a perfect example of where Options should be used.

**Comment by AnswerZhao** [comment]
@TWiStErRob Thank you very much.

**Comment by sjudd** [comment]
This is implemented, see https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/VideoBitmapDecoder.java#L41
