### ISSUE TITLE
Reconfigure warning on gif

### ISSUE THREAD

**Issue by Vaycent** [bumptech/glide#1663]
**Glide Version**:
```gradle
compile 'com.github.bumptech.glide:glide:3.7.0'
```

**Device/Android Version**:
Samsung C7 / Android 6.0.1

**Issue details / Repro steps / Use case background**: 
I'm using glide to load a gif in my imageview, and the "codebrain.gif" is a resource file in res/drawable , this gif can be shown normally.
But I found that there're some warning log ceaselessly in my logcat as below:
```java
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this).load(R.drawable.codebrain)
.asGif()
.diskCacheStrategy(DiskCacheStrategy.SOURCE)
.into(bigImg);

```

![image](https://cloud.githubusercontent.com/assets/15797973/21478020/6db157f8-cb82-11e6-914c-ed8885774afc.png)

**Comment by TWiStErRob** [comment]
See #743 It's a check that was added in the Android core, but Glide's usage is currently known as safe. It's a non-issue until there's proof of actual problems. Add a logcat filter mentioned in the other issue if you're bothered by it.
