### ISSUE TITLE
Images are not fit ImageView with wrap_content height

### ISSUE THREAD

**Issue by erikha1501** [bumptech/glide#1664]
**Glide Version**:
Glide.Xamarin 3.7.0

**Integration libraries**:
None

**Issue details / Repro steps / Use case background**: 
I'm transitioning from downloading and applying images by hand to use Glide which supports caching and efficient loading.
However, on the first try the loaded image was very small, i mean tiny.

I've read the documentations about resizing and Glide provides me with 2 options:
.FitCenter() or .CenterCrop()

FitCenter did nothing but CenterCrop shows some progress, which makes the image fit ImageView horizontally but it crops nearly 3/4 of that image's height.

What I want to accomplish is making the image fit ImageView's width and keeping the aspect ratio.

*Update*
Okay I had some further experiment with Glide and found that .DontTransform() did what I want. Is this the expected and justifiable behavior or there is something I should use instead of .DontTransform()? 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
Glide implementation is placed in RecyclerView's Adapter 
Here is my related code:
```
string imageUrl = currentPost.Embedded.WpFeaturedMedia.FirstOrDefault().SourceUrl;
Glide.With(context).Load(imageUrl).Into(currentViewHolder.ThumbnailImage);
```
imageUrl only contains a link to a single image.

**Layout XML**:
```xml
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:auto="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:layout_margin="5dp"
    android:elevation="3dp"
    auto:cardCornerRadius="3dp"
    android:id="@+id/postcardviewitem_cardview_root"
    auto:cardBackgroundColor="@color/cardview_post_background">
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <ImageView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/postcardviewitem_imageview_thumbnailimage"
            android:src="@android:drawable/ic_menu_gallery"
            android:adjustViewBounds="true"
            android:paddingLeft="20dp"
            android:paddingRight="20dp"
            android:paddingBottom="5dp"
            android:layout_alignParentTop="true"
            android:paddingTop="5dp" />

```

This is a screen shot of my app
![example](https://cloud.githubusercontent.com/assets/24774495/21480532/63fdf712-cb90-11e6-9c52-3e308170c72a.png)

Black rectangles are just for censoring purposes

**Comment by fayou147** [comment]
https://github.com/bumptech/glide/issues/1410

**Comment by TWiStErRob** [comment]
don't agree with @fayou147 . Glide doesn't support padding on views, but can't find the issue where this came up. When the item is first laid out wrap_content measures the padding, which is 5dp+5dp, and when Glide queries `iv.getHeight()` it returns this value. This tells Glide that this is the size to use for height and combined with match_parent and a transformation it results in a big resize. Refactor your layout to use margins instead of paddings.

Tip: change `android:src` to `tools:src` it's more efficient for the end user and you still get Android Studio preview.

**Comment by TWiStErRob** [comment]
Found it: #939

**Comment by erikha1501** [comment]
It works after refactoring to use margins. Thank you Sir.
