### ISSUE TITLE
Memory leak with glide and recycler view

### ISSUE THREAD

**Issue by ronpeer7** [bumptech/glide#1668]
**Glide Version**: 3.7.0

**Integration libraries**: No

**Device/Android Version**:  Samsung Galaxy S5, Android 6.0.1

**Issue details / Repro steps / Use case background**:
I'm using Glide with recyclerview in order to present list of images (from my Firebase Storage).
the images are read as png files of about 200-500KB each. and the grid is 3 items in width.
I seems that Glide doesn't release bitmap from heap memory and my app is crashing after awhile.
I'm aware of the bitmap pool concept but I whould expect that Glide will prevent my app reach the heap limit (128MB in my device).
 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

package com.peer.ron.mysprays;
/**
 * Created by User on 11/6/2016.
 */
import android.content.Context;
import android.graphics.Typeface;
import android.os.Bundle;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.view.ViewTreeObserver.OnGlobalLayoutListener;
import android.widget.ImageView;
import android.widget.TextView;
import com.bumptech.glide.RequestManager;
import com.bumptech.glide.load.engine.DiskCacheStrategy;
import com.firebase.ui.storage.images.FirebaseImageLoader;
import com.google.firebase.storage.StorageReference;
import java.util.ArrayList;

public class SprayAdapter extends RecyclerView.Adapter<SprayAdapter.SprayViewHolder> {

    private int[] animationArray = new int[2];
    private ArrayList<Spray> sprayList;
    Context context;
    private String fragmentTag = "";
    private boolean skipMemCache = false;
    private final RequestManager glide;
    private long timeStamp = 0;

    public SprayAdapter(Context context , RequestManager glide) {
        this.sprayList = new ArrayList<>() ;
        this.context = context;
        this.glide = glide;
    }

    public class SprayViewHolder extends RecyclerView.ViewHolder {

        public ImageView imageView;
        public TextView likeTextview;
        public TextView timeTextview;
        public View itemView;

        public SprayViewHolder(View itemView) {
            super(itemView);
            this.imageView = (ImageView)itemView.findViewById(R.id.card_imageview);
            likeTextview = (TextView) itemView.findViewById(R.id.likes_textview);
            likeTextview.setTypeface(Typeface.createFromAsset(context.getAssets(),"fonts/Roboto-Medium.ttf"));
            timeTextview = (TextView) itemView.findViewById(R.id.card_time_textview);
            timeTextview.setTypeface(Typeface.createFromAsset(context.getAssets(),"fonts/Roboto-Medium.ttf"));
            this.itemView =  itemView;
        }
    }

    @Override
    public SprayViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View cardView  = LayoutInflater.from(parent.getContext()).inflate(R.layout.card_layout,parent,false);
        SprayViewHolder sprayViewHolder = new SprayViewHolder(cardView);
        return sprayViewHolder;
    }

    @Override
    public void onBindViewHolder(SprayViewHolder holder, final int position) {
        bind(holder);
    }

    private void bind (final SprayViewHolder holder){
        if(sprayList.size()>0) {

            holder.itemView.getViewTreeObserver().addOnGlobalLayoutListener(new OnGlobalLayoutListener() {
                @Override
                public void onGlobalLayout() {
                    ViewGroup.LayoutParams lparams = holder.itemView.getLayoutParams();
                    int width = holder.itemView.getWidth();
                    lparams.height = width;
                    holder.itemView.setLayoutParams(lparams);
                }
            });

            final int invertPos = sprayList.size() - holder.getAdapterPosition() - 1;
            //revertPosition = sprayList.size() - position - 1;
            StorageReference sprayImagesRef = ((MainActivity) context).getSprayImagesRef();
            StorageReference sprayImageRef = sprayImagesRef.child(sprayList.get(invertPos).getImageUrl() + ".png");
            glide
                    .using(new FirebaseImageLoader())
                    .load(sprayImageRef)
                    //.diskCacheStrategy(DiskCacheStrategy.ALL) // Cache the original size to disk so that open will be fast
                    .skipMemoryCache(skipMemCache)  // Cache everything
                    .crossFade()
                    .into(holder.imageView);

            int likes = sprayList.get(invertPos).getLikes();
            String likesStr;
            if (likes < 1000) {
                likesStr = Integer.toString(likes);
            }else {
                likes /= 1000;
                likesStr = Integer.toString(likes) + "K" ;
            }
            holder.likeTextview.setText(likesStr);
            if(timeStamp > 0) {
                Spray.SprayTimeResult timeResult = sprayList.get(invertPos).getStringTime(timeStamp);
                holder.timeTextview.setText(timeResult.getResultTime() + timeResult.getResultShortUnit());
            }
            animationArray[0] = R.anim.fragment_open;
            animationArray[1] = R.anim.fragment_close;
            holder.itemView.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View v) {

                    if (context == null) {
                        return;
                    }
                    if (context instanceof MainActivity) {
                        MainActivity mainActivity = (MainActivity) context;
                        MySprayDetailsFragment mySprayDetailsFragment = MySprayDetailsFragment.newInstance("");
                        Bundle bundle = new Bundle();
                        Log.i("RonP","Position = " + holder.getAdapterPosition());
                        bundle.putSerializable("key",sprayList.get( invertPos)); //revert position
                        mySprayDetailsFragment.setArguments(bundle);
                        mainActivity.startDetailsFragment(R.id.container_layout, mySprayDetailsFragment, fragmentTag, true, animationArray);
                    }
                }
            });
        }
    }

    @Override
    public int getItemCount() {
        return sprayList.size();
    }

    public void addItemToList (Spray spray) {
        sprayList.add(spray);
    }

    public void updateItemToList (Spray spray) {
        for(int i=0; i< sprayList.size();i++){
            if(sprayList.get(i).getSprayId() != null && sprayList.get(i).getSprayId().equals(spray.getSprayId())) {
                sprayList.set(i,spray);
            }

        }
    }

    public void removeItemFromList(Spray spray){
        for(int i=0; i< sprayList.size();i++){
            if(sprayList.get(i).getSprayId() != null && sprayList.get(i).getSprayId().equals(spray.getSprayId())) {
                sprayList.remove(i);
            }

        }
    }

    public void clearList(){
        sprayList.clear();
    }

    public void setTimestamp(long timeStamp){
        this.timeStamp = timeStamp;
    }

    public boolean isSkipMemCache() {
        return skipMemCache;
    }

    public void setSkipMemCache(boolean skipMemCache) {
        this.skipMemCache = skipMemCache;
    }

    public String getFragmentTag() {
        return fragmentTag;
    }

    public void setFragmentTag(String fragmentTag) {
        this.fragmentTag = fragmentTag;
    }

    @Override
    public void onViewRecycled(SprayViewHolder holder) {
        super.onViewRecycled(holder);
        holder.imageView .setImageBitmap(null);
        Log.i("RonP","holder i " + holder.getAdapterPosition() + " recycled" );
    }
}

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by ronpeer7** [comment]
Ok, I moved the onClickListener from the bind function to the viewHolder and it resolved the leak!

**Comment by howyongjun** [comment]
My app crashed after it reached certain heap. The app able to create Fragment which contain RecyclerView that lazy load images as user scroll. After creating few Fragments, the app crashed. The expected behaviour is that the system should be able to destroy Fragment to free up memory. Any idea? @TWiStErRob
