### ISSUE TITLE
Error:CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by Syedwaheed** [bumptech/glide#1671]
Is there anyone who have fixed this issue..
I have done the both import the project as well as open it in android studio 2.2.3.
But still i m getting this error. Any help please ? thanks in advance

**Comment by lu769257351** [comment]
同求，是我導入方法錯誤碼？

**Comment by TWiStErRob** [comment]
Do you mean you imported Glide's code in AS?
That's not guaranteed to work, use IDEA: https://github.com/bumptech/glide#development
