### ISSUE TITLE
GlideDrawableImageViewTarget changes size of loaded image

### ISSUE THREAD

**Issue by ItaiLeigh** [bumptech/glide#1673]
**Glide Version**: 3.7.0

**Device/Android Version**: 
Xiami - REDMI NOTE 3 / Android 5.1.1 LMY47V
Nexus 5 / Android 6.0.1

**Issue details / Repro steps / Use case background**: 
Using `Glide.with(Context).load(File).into(target)` loads the image properly when using the ImageView as the target, and loads it smaller if the target is a GlideDrawableImageViewTarget (calling the `super`'s implementation in the `onResourceReady` of the anonymous class extending it).

Looking at the [documentation](https://github.com/bumptech/glide/wiki/Custom-targets) I understand the two are supposed to be interchangable (which is what I need them to be). 

I want to use the image's size to set another view's size, and to use the image itself later on so I wanted to get the image once it was set. But without doing anything with it - just using GlideDrawableImageViewTarget makes the set image smaller than it is when using the ImageView directly.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
        Glide.with(getActivity()).load(takenPicFile).into(takenPicPreview); //loading the image using the full height available

        Glide.with(getActivity()).load(takenPicFile).into(new GlideDrawableImageViewTarget(takenPicPreview){
            @Override
            public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> animation) {
                super.onResourceReady(resource, animation);
                //resource set
            }
        }); //loading the image as a smaller one not using the whole area available
```

**Layout XML**:
In RelativeLayout:
```xml
<ImageView
        android:id="@+id/taken_pic_preview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
```

**Photos:**
Here's the difference demonstrated using cropped screenshots in the Xiami phone (I cropped the same area in both photos):
(Note that the taken image is shown completely in both cases - they are just 2 different photos. The difference is just the size - they are not cropped)

![screenshot_2017-01-02-18-22-15_com maatayim stringbean](https://cloud.githubusercontent.com/assets/15845720/21593605/ab6b8826-d121-11e6-99d8-8bd0714e502b.png)
![screenshot_2017-01-02-18-25-23_com maatayim stringbean](https://cloud.githubusercontent.com/assets/15845720/21593606/b01d19c0-d121-11e6-8249-1e47c7dc8272.png)

**Comment by TWiStErRob** [comment]
My first hunch is that you're calling two different methods `.into(ImageView)` and `.into(Target)`. Check out the source code of both (`GenericRequestBuilder`)! The `ImageView` version has an extra step for convenience and common usage. In your case `.load().into(iv)` is equivalent to `.load().fitCenter().into(new GlideDrawableImageViewTarget(iv))` (`ImageView.scaleType`'s default is `ScaleType.FIT_CENTER`). What you're doing (`.load().into(new GlideDrawableImageViewTarget(iv))`) is actually: `.load().dontTransform().into(iv)`.

**Comment by ItaiLeigh** [comment]
Thank you very much. That's exactly it. 
I wrote that that's what I'm doing in the details - I think it's worth it to add this distinction in the [documentation](https://github.com/bumptech/glide/wiki/Custom-targets). Currently it says:

> If all you want to do is observe Glide's default behavior without changing it, you can subclass one of Glide's two default concrete ImageViewTargets:

> GlideDrawableImageViewTarget - The default Target for normal loads and loads that use asGif().

 From reading that I was convinced the two methods are supposed to be equivalent as long as I'm calling the `supe.onResourceReady(resource, animation)` and doing nothing else in the `GlideDrawableImageViewTarget`.

**Comment by ItaiLeigh** [comment]
The reason I am using the `GradleDrawableImageViewTarget` is that I need,  once the size is resolved, to use it to resize another view. But once I add the `.fitCenter()` it reports `resource.getIntrinsicWidth()` as the width of the whole window (although I can see the image does not cover the whole window in the width dimension. You can refer to the first photo I attached at the first post here).

When I don't add `fitCenter()` the `resource.getIntrinsicWidth()` reports the actual size of the presented image (although it's way too small, of course, as the desired behavoiur is using `fitCenter()`).

Is that the way it should behave? If so - how can I get the presented width of the image in the `onResourceAvailable(resource, animation)` when I use `fitCenter()`?
