### ISSUE TITLE
loading local file oom in some device

### ISSUE THREAD

**Issue by chenshuhong** [bumptech/glide#1676]
**Glide Version 3.7.0**:

**Device/Android Version Redmi Note 2**:

**Issue details / Repro steps / Use case background**: 
I use glide to load all pic in my phone,it do well in my demo.But it always oom when I use the same code 
in my company app.I watch the memory monitors it never clear the memory.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide
.with(fragment)
.load(photo.getPath())
.diskCacheStrategy(DiskCacheStrategy.NONE)
.dontAnimate()
.override(imageSize, imageSize)
.placeholder(R.drawable.ic_placeholder)
.into(holder.ivPhoto);
```
imageSize is one-third of the screen

**Comment by chenshuhong** [comment]
![qq 20170106212251](https://cloud.githubusercontent.com/assets/11794327/21718882/50228cc6-d455-11e6-8a4b-11b36e0f895b.png)
above is the memory monitor

**Comment by wanghaihui** [comment]
I also met this issue in XIAOMI 4

**Comment by TWiStErRob** [comment]
If the fragment is really a fragment, you need to make sure that it's destroyed. Either by double-checking the transaction or by killing the whole activity. `setRetainInstance` may trip you up, though I think activity destroy should get rid of it. The main point is **check for memory leaks**: as long as the fragment/activity is active, Glide won't clear up.

In my app I use a trick to force-clear the list's images when I want to: implement `onViewRecycled` to `Glide.clear` all image views and do a `.setAdapter(null)` to force RV to call that for each displayed item.
