### ISSUE TITLE
 Loading  Uninstall Application Image icon 

### ISSUE THREAD

**Issue by lougw** [bumptech/glide#1680]
Hi !
how can i   Loading  Uninstall Application Image icon Using Glide ,thank you!

**Comment by TWiStErRob** [comment]
Can you please share how do you load it without Glide?

**Comment by lougw** [comment]
@TWiStErRob  Here is the code ,thank you !
  
        PackageInfo packageInfo = mContext.getPackageManager().getPackageArchiveInfo(path,   PackageManager.GET_ACTIVITIES);
        ApplicationInfo appInfo = packageInfo.applicationInfo;
        if (Build.VERSION.SDK_INT >= 8) {
            appInfo.sourceDir = path;
            appInfo.publicSourceDir = path;
        }
       Drawable icon=appInfo.loadIcon(mContext.getPackageManager());

**Comment by TWiStErRob** [comment]
https://groups.google.com/forum/#!topic/glidelibrary/MAqPfuHpjr4

**Comment by TWiStErRob** [comment]
You may need to alter it a little to do `getPackageArchiveInfo` inside the loader: `ModelLoader<PackagePath, ApplicationInfo>`, where `class PackagePath { String path; }` to distinguish it from normal `load(String)` calls.

**Comment by lougw** [comment]
I will test this, thank you!
