### ISSUE TITLE
Question: A proper way to preload images and cache to the disk

### ISSUE THREAD

**Issue by burakkilic** [bumptech/glide#1681]
Hello;

I have an application that works offline. I'm preloading images with that code as I understand from the tutorial:

```java
FutureTarget<File> future = Glide.with(context.getApplicationContext())
        .load(list.get(i))
        .downloadOnly(1536,1024);
future.get();
publishProgress(((int) ((i / (float) count) * 100)));
```

First of all, I should download 3 sizes of an image, small, large and medium. I'm using imgix.net for that. And my url is like:

    http://myimgix.imgix.net/VJzYDYJag/EktgSYvtJpx.jpg?cropType=entropy&dpi=72&fit=crop&fm=jpg&h=512&ixlib=java-1.0.0&q=60&w=768

And while showing, I'm using:

```java
Glide.with(context)
    .load(item.getLargeImageUrl())
    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
    .listener(new RequestListener<String, GlideDrawable>() {
        @Override
        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
            Log.i("GLIDE", "onException for :" + item.getLargeImageUrl(), e);
            Log.e("GLIDE", e.getLocalizedMessage());
            return false;
        }

        @Override
        public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
            Log.i("GLIDE", "onResourceReady for " + item.name);
            return false;
        }
    })
    .into(holder.itemImageView);
```

and I saw that some of the images are not cached, and cannot be seen offline. 

What is the proper way to use disk caching with preloading?

Thank you

**Comment by TWiStErRob** [comment]
SOURCE cache contains the original image, `downloadOnly`'s argument only helps selecting the bucket, it's not the image size that will be cached. Call `Glide.clear(future)` to make sure stuff is freed (see Javadoc of FutureTarget class). Make sure the URLs are exactly the same: if the query param order is different, then it's a different image! Use the stuff on the [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) to help diagnose cache misses (look at `CacheKey`s).

**Comment by ndeokar** [comment]
Hey @TWiStErRob  i am working on similar case. I have list of images and want to download them when app starts. So i have created IntentService for same. 

I am using this inside onHandleIntent:

      
      for (String url:imagesArray) {
                Log.i(TAG, "URL : "+url);
              
                FutureTarget futureTarget = glide
                        .load(url)
                        .downloadOnly(1536,1024);
                futureTarget.get();
            }

But i am getting `java.util.concurrent.ExecutionException: java.io.IOException: Request failed 403: Forbidden`
after 3rd iteration. from [this](http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/request/RequestFutureTarget.html) i have to call `Glide.clear(future)` but before calling this what i need is trigger which would inform me that image has downloaded successfully. 

Please suggest any other proper way to preload list of images in background.

Thank You!

**Comment by TWiStErRob** [comment]
@ndeokar `.get()` blocks, the `for` loop won't progress until the `File` is returned from `.get()`, just add `Glide.clear(futureTarget);` before the closing bracket of `for`.

Regarding `HTTP 403` that's probably a header or rate limiting?!

@burakkilic let me know if you need further help.
