### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by lzhhh** [bumptech/glide#1689]
After checking out Glide's source code , every time when I try to open it by Android studio , It gives me this error:  
Gradle 'glide' project refresh failed
error:CreateProcess error=2, The system cannot find the file specified

**Comment by TWiStErRob** [comment]
That's not guaranteed to work, use IDEA: https://github.com/bumptech/glide#development
I used 2016.x and it worked nicely.
See also [related issues](https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=Error%3ACreateProcess%20error%3D2), e.g. #756.
