### ISSUE TITLE
placeholder photo and result photo scale different  problem

### ISSUE THREAD

**Issue by mxylayout** [bumptech/glide#1694]
Excuse me i had a problem:

first time load list :
![qq 20170120114609](https://cloud.githubusercontent.com/assets/10346229/22135110/150b70a0-df07-11e6-8521-67b89a28e84e.png)

then i refresh the list after first time load completed :
That's the right effect.

![qq 20170120114642](https://cloud.githubusercontent.com/assets/10346229/22135197/999b0380-df07-11e6-88f5-764bfc503bfe.png)

here is the code：
![qq 20170120114809](https://cloud.githubusercontent.com/assets/10346229/22135222/cb839c86-df07-11e6-9162-dc3a54eeb330.png)
![qq 20170120114832](https://cloud.githubusercontent.com/assets/10346229/22135227/d111e40a-df07-11e6-9f47-8e075e268c9e.png)

I had changed CenterInside to FitCenter  and call  ( .fitCenter()),but it is also like this.
so,what should i do?
Thanks in advance.

**Comment by mxylayout** [comment]
here is the problem photo url:
http://miclouds.hebg3.com//userfiles/manufacturer/images/goods/1/02020102010112.jpg

and i try to use centerCrop ,there still problem.

**Comment by mxylayout** [comment]
change the code like this:
![qq 20170123103230](https://cloud.githubusercontent.com/assets/10346229/22189421/78ad7462-e157-11e6-9281-b203dfb4b480.png)

it works!!!   
wonderful~

**Comment by TWiStErRob** [comment]
Sorry for slow response. Your fix is accidental. The side effect of what you did is to disable animations which caused this in the first place. In the first load the load is async and the placeholder has time to load while the image is being downloaded. The cross-fade from the placeholder is what distorts the image: #363. The second load is sync and there's no cross-fade so no distortion can happen. See linked issue for more. The easiest workaround is `.dontAnimate()`.

Note 1: PNG doesn't have quality, so that 50 doesn't affect the encoding.
Note 2: Glide is not an official Google product.

**Comment by mxylayout** [comment]
Thank you for your letter, I will rewrite the code as you say after Chinese New Year, and thank you for being so strict with any question.


Note 1:i will change 50 to 100.
Note 2:i will change the method name to “displayImageByWonderfulGlide()”.


-----------------------------------------------------------------------------------------------

At 2017-01-26 07:45:56, "Róbert Papp" <notifications@github.com> wrote:


Sorry for slow response. Your fix is accidental. The side effect of what you did is to disable animations which caused this in the first place. In the first load the load is async and the placeholder has time to load while the image is being downloaded. The cross-fade from the placeholder is what distorts the image: #363. The second load is sync and there's no cross-fade so no distortion can happen. See linked issue for more. The easiest workaround is .dontAnimate().

Note 1: PNG doesn't have quality, so that 50 doesn't affect the encoding.
Note 2: Glide is not an official Google product.

**Comment by gikarasojo** [comment]
@TWiStErRob This is what I did to avoid image distortion when moving from placeholder to downloaded photo. hope it's not bad 

```
Glide.with(context)
            .load(size)
            .centerCrop()
            .crossFade()
            .placeholder(R.drawable.house)
            .priority(Priority.IMMEDIATE)
            .diskCacheStrategy(DiskCacheStrategy.RESULT)
            .listener(new RequestListener<CustomImageSize, GlideDrawable>() {
              @Override
              public boolean onException(Exception e, CustomImageSize model, Target<GlideDrawable> target, boolean isFirstResource) {
                return false;
              }

              @Override
              public boolean onResourceReady(GlideDrawable resource, CustomImageSize model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                imageView.setImageResource(0);
                return false;
              }
            })
            .into(imageView);
```

**Comment by gikarasojo** [comment]
@mxylayout 

> Note 2:i will change the method name to “displayImageByWonderfulGlide()”.

hahaaa you sound like a comedian

**Comment by TWiStErRob** [comment]
@gikarasojo my response is almost the same as before: https://github.com/bumptech/glide/issues/1694#issuecomment-275268807

In your case you're disabling cross-fade by removing the image to fade from. You could achieve the same effect without the `listener()` hack, by using `.animate(android. R.anim.fade_in)`.

If you stick with your solution, you should do `imageView.setImageDrawable(null)`, the intent is more clear.

**Comment by gikarasojo** [comment]
@TWiStErRob got it sir. thank you very very much
