### ISSUE TITLE
Loading does not come out with specific pictures

### ISSUE THREAD

**Issue by Bakumon** [bumptech/glide#1695]
Use Glide to load it out of this picture, however, using any browser can load successfully.

**Image link:**
Http://oi66gxcxy.bkt.clouddn.com/2017-01-20-030332.jpg

**Glide Version:**
```
compile 'com.github.bumptech.glide:glide:3.7.0'
```

**java code:**
```java
Glide.with(this)
     .load("http://oi66gxcxy.bkt.clouddn.com/2017-01-20-030332.jpg")
     .into(mImageView);
```

**Comment by TWiStErRob** [comment]
Check why it is not loading: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by Bakumon** [comment]
@TWiStErRob 

Sorry, such a long time to care about their own issues, because we Chinese New Year, all holidays, of course, including me.

Hello, in accordance with the tips to you, I tried to debug this error, but still can not get the specific reasons for the error, I hope you help me find.

I did this:

1. in the command line
`adb shell setprop log.tag.GenericRequest DEBUG`

2. Creates a listener
```java
// example usage: .listener(new LoggingListener<String, GlideDrawable>())
public class LoggingListener<T, R> implements RequestListener<T, R> {
    @Override public boolean onException(Exception e, Object model, Target target, boolean isFirstResource) {
        android.util.Log.d("GLIDE", String.format(Locale.ROOT,
                "onException(%s, %s, %s, %s)", e, model, target, isFirstResource), e);
        return false;
    }
    @Override public boolean onResourceReady(Object resource, Object model, Target target, boolean isFromMemoryCache, boolean isFirstResource) {
        android.util.Log.d("GLIDE", String.format(Locale.ROOT,
                "onResourceReady(%s, %s, %s, %s, %s)", resource, model, target, isFromMemoryCache, isFirstResource));
        return false;
    }
}
```

3. The listener used in the code, and the loading is the special picture url

```java
mImageView = (ImageView) findViewById(R.id.image);
        Glide.with(this)
                .load("http://oi66gxcxy.bkt.clouddn.com/2017-01-20-030332.jpg")
                .listener(new LoggingListener<String, GlideDrawable>())
                .into(mImageView);
```

4. Then, I figure in the first sign on the location of a breakpoint.

![debugforglide](https://cloud.githubusercontent.com/assets/12182189/22675230/7145135a-ed1f-11e6-9ef9-53d3cdd212a0.png)

### However, the frustration is that I get the exception is null, did not get any useful information, how can I do to get exciting information?

**Comment by sjudd** [comment]
It looks like BitmapFactory returns null when attempting to decode this image. It also looks like the image itself has errors (there's a pixelated block of pixels when you view the image in a browser) which might explain why BitmapFactory fails to decode it.

Since BitmapFactory doesn't give us any more information than a null result, we don't have much else to go on.
