### ISSUE TITLE
Image does not load in recyclerview initially

### ISSUE THREAD

**Issue by joeytsai** [bumptech/glide#1697]
**Glide Version**: 3.7.0

**Integration libraries**: okhttp3-integration:1.4.0

**Device/Android Version**: Nexus 6 7.1.1

**Issue details / Repro steps / Use case background**: Using Glide with a RecylerView; the image in question starts off screen at the bottom of the list.  For debugging I added an RequestListener.  
1) Fling to the bottom of the list. onResourceReady has: isFromMemoryCache = [false], isFirstResource = [true] and the image does NOT appear.
2) Fling to the top, then fling back to the bottom list. onResourceReady has isFromMemoryCache = [true], isFirstResource = [true], and the resource DOES appear
3) Fling to the top, then fling back to the bottom of the list. onResourceReady has isFromMemoryCache = [false], isFirstResource = [true], and the resource does NOT appear.
4) Once more fling to top, then fling to the bottom, and the resource will now ALWAYS appear (can continue to fling to top and bottom).   isFromMemoryCache = [true]

Another hint that may be useful is the image will NEVER load if I add:
                        .diskCacheStrategy(DiskCacheStrategy.NONE)
                        .skipMemoryCache(true)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context)
                        .load(GlideUtil.authUrl(context, optimizedUrl))
                        .into(chatImageIv);
```

The GlideUtil.authUrl() calls returns a new GlideUrl() that has some authentication headers for the request; I've used it in other places without incident.

**Layout XML**:
```xml
            <ImageView
                android:id="@+id/chat_imageview"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:adjustViewBounds="true"
                android:contentDescription="@string/chat_image"/>
```

**Stack trace / LogCat**:
```ruby
n/a
```

**Comment by TWiStErRob** [comment]
Don't see anything obvious, though your statement of `NONE` breaking it makes me suspicious of your auth. Can you enable all logging and add [this listener](https://github.com/TWiStErRob/glide-support/blob/20483729ba6c17b3b2194197014714c126904890/src/glide3/java/com/bumptech/glide/supportapp/utils/LoggingListener.java) to gather more data? (Feel free to redact, but try to keep as much info as you can.)

**Comment by joeytsai** [comment]
Sure, here's the four onResourceReady calls again, with the first and third failing:

V/GLIDE: .onResourceReady(GlideBitmapDrawable@becb5cb(1188x891@RGB_565), https://REDACTED.sharepoint.com/sites/OTSG/StarWars/Pictures/_w/e07c3779-a87e-4d5e-9dd7-2c95e56ee0e8_jpg.jpg
         LazyHeaders{headers={Cookie=[StringHeaderFactory{value='rtFa=4cVvWRx9nNTzZPOA3mcevH8N1BK4p37Quyws5f5v+XJkwqwL1clDbjHAbrKn+sa1s3z3faRq/sfoo5s6tfj/5eLr3NZxdS36Gdb6663IrKOE1+swSmIu95EvHLUeXhyHHZ5j+5FRdtkPPKSIepkkWcUsywai6iqAfsGzyqXj9fUuawMITgbaw0GtILvBSCTdppSizXZLAjtFEAaIUGd4igRR2cDXVCA1tib6HOodCWR0gZin2NGKblKxwWVaWr/qz+EtSCfE+Md04ZLE28bAiY+n4acGObbb5DBmOYMhzLEsaVThMZEe7Vrr8l7G/Q2mIFSHZD6TjCGJnsyqGazxUz/T8l8umHKCPO42ZVphQZAQbnXz2IQBjfxyEg5TVaSgIAAAAA==; domain=sharepoint.com; path=/; secure; HttpOnly;FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjIsMGguZnxtZW1iZXJzaGlwfDEwMDM3ZmZlOTkyODU3YTJAbGl2ZS5jb20sMCMuZnxtZW1iZXJzaGlwfHJpY2thcmRAc2xhbG9tY29uc3VsdGluZy5vbm1pY3Jvc29mdC5jb20sMTMxMjkyMzk3NzMwMDAwMDAwLDEzMTIzNjQ1ODg1MDAwMDAwMCwxMzEyOTY3MTc3ODAwMzg0MTksMC4wLjAuMCwyLGYyMmNlMTI1LTA0MjEtNDE5NS1hYjhkLTk2YWUxYTU4NjdkYywsVjIhMTAwMzdGRkU5OTI4NTdBMiExMzEyOTIzOTc3MywyYzUyY2M5ZC1iMDE4LTIwMDAtMzZiYy05ZWIwZDUzNmNjOGIsMmM1MmNjOWQtYjAxOC0yMDAwLTM2YmMtOWViMGQ1MzZjYzhiLEdDU3N4QlpSQm54WHFrbUhJdGovN1ZXcXM3c05CUEdBdDVoV1F4M2R3S3hxbGZBdm9zZVl1bUg0SFlPY01iZTRHalA5ZE9BemtvMGNWdFJsVWc0czhNK2V0VUxUWk9nSGhOZmlZRm5YbHh1TTFidDAxbERCdHJYS1ppK2FYS3oyVW9QTU9Oa1A2VHpUcVplV0VrYjBwN2ZTTDkyMVpCaXV5NXJnSU9UL045blRsZzVlZVhibnhBQUh6a0EyclB1Q0xLQ2VmbDVzMDlBYXZva3NPQlBlQk9Ma1BrUVJOU2RycnlrUEJlTWdEdzN0Y2FjQVlHRFBNNUR1UUVJcHJtWGlRN0VLeUdjUE5PQnJhM0FVdGtBdFlQN09ESXlqMWZreEZmZUtNQnAxN2h4RFhXanc5WGs5cXlXWjU0Uy9JVVNheU9WVm1ReHZBcE1IakhFcThwdjJsUT09PC9TUD4=; path=/; secure; HttpOnly'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 7.1.1; Nexus 6 Build/N6F26Q)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: v7.widget.AppCompatImageView{92f71a8 V.ED..... ........ 0,168-1188,168 #7f0f013b app:id/chat_imageview}(params=-1x-2->size=1188x0), async, first)
V/GLIDE: .onResourceReady(GlideBitmapDrawable@a2c7eac(1188x891@RGB_565), https://REDACTED.sharepoint.com/sites/OTSG/StarWars/Pictures/_w/e07c3779-a87e-4d5e-9dd7-2c95e56ee0e8_jpg.jpg
         LazyHeaders{headers={Cookie=[StringHeaderFactory{value='rtFa=4cVvWRx9nNTzZPOA3mcevH8N1BK4p37Quyws5f5v+XJkwqwL1clDbjHAbrKn+sa1s3z3faRq/sfoo5s6tfj/5eLr3NZxdS36Gdb6663IrKOE1+swSmIu95EvHLUeXhyHHZ5j+5FRdtkPPKSIepkkWcUsywai6iqAfsGzyqXj9fUuawMITgbaw0GtILvBSCTdppSizXZLAjtFEAaIUGd4igRR2cDXVCA1tib6HOodCWR0gZin2NGKblKxwWVaWr/qz+EtSCfE+Md04ZLE28bAiY+n4acGObbb5DBmOYMhzLEsaVThMZEe7Vrr8l7G/Q2mIFSHZD6TjCGJnsyqGazxUz/T8l8umHKCPO42ZVphQZAQbnXz2IQBjfxyEg5TVaSgIAAAAA==; domain=sharepoint.com; path=/; secure; HttpOnly;FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjIsMGguZnxtZW1iZXJzaGlwfDEwMDM3ZmZlOTkyODU3YTJAbGl2ZS5jb20sMCMuZnxtZW1iZXJzaGlwfHJpY2thcmRAc2xhbG9tY29uc3VsdGluZy5vbm1pY3Jvc29mdC5jb20sMTMxMjkyMzk3NzMwMDAwMDAwLDEzMTIzNjQ1ODg1MDAwMDAwMCwxMzEyOTY3MTc3ODAwMzg0MTksMC4wLjAuMCwyLGYyMmNlMTI1LTA0MjEtNDE5NS1hYjhkLTk2YWUxYTU4NjdkYywsVjIhMTAwMzdGRkU5OTI4NTdBMiExMzEyOTIzOTc3MywyYzUyY2M5ZC1iMDE4LTIwMDAtMzZiYy05ZWIwZDUzNmNjOGIsMmM1MmNjOWQtYjAxOC0yMDAwLTM2YmMtOWViMGQ1MzZjYzhiLEdDU3N4QlpSQm54WHFrbUhJdGovN1ZXcXM3c05CUEdBdDVoV1F4M2R3S3hxbGZBdm9zZVl1bUg0SFlPY01iZTRHalA5ZE9BemtvMGNWdFJsVWc0czhNK2V0VUxUWk9nSGhOZmlZRm5YbHh1TTFidDAxbERCdHJYS1ppK2FYS3oyVW9QTU9Oa1A2VHpUcVplV0VrYjBwN2ZTTDkyMVpCaXV5NXJnSU9UL045blRsZzVlZVhibnhBQUh6a0EyclB1Q0xLQ2VmbDVzMDlBYXZva3NPQlBlQk9Ma1BrUVJOU2RycnlrUEJlTWdEdzN0Y2FjQVlHRFBNNUR1UUVJcHJtWGlRN0VLeUdjUE5PQnJhM0FVdGtBdFlQN09ESXlqMWZreEZmZUtNQnAxN2h4RFhXanc5WGs5cXlXWjU0Uy9JVVNheU9WVm1ReHZBcE1IakhFcThwdjJsUT09PC9TUD4=; path=/; secure; HttpOnly'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 7.1.1; Nexus 6 Build/N6F26Q)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: v7.widget.AppCompatImageView{92f71a8 V.ED..... ......ID 0,168-1188,168 #7f0f013b app:id/chat_imageview}(params=-1x-2->size=1188x0), sync, first)
V/GLIDE: .onResourceReady(GlideBitmapDrawable@638d998(1188x891@RGB_565), https://REDACTED.sharepoint.com/sites/OTSG/StarWars/Pictures/_w/e07c3779-a87e-4d5e-9dd7-2c95e56ee0e8_jpg.jpg
         LazyHeaders{headers={Cookie=[StringHeaderFactory{value='rtFa=4cVvWRx9nNTzZPOA3mcevH8N1BK4p37Quyws5f5v+XJkwqwL1clDbjHAbrKn+sa1s3z3faRq/sfoo5s6tfj/5eLr3NZxdS36Gdb6663IrKOE1+swSmIu95EvHLUeXhyHHZ5j+5FRdtkPPKSIepkkWcUsywai6iqAfsGzyqXj9fUuawMITgbaw0GtILvBSCTdppSizXZLAjtFEAaIUGd4igRR2cDXVCA1tib6HOodCWR0gZin2NGKblKxwWVaWr/qz+EtSCfE+Md04ZLE28bAiY+n4acGObbb5DBmOYMhzLEsaVThMZEe7Vrr8l7G/Q2mIFSHZD6TjCGJnsyqGazxUz/T8l8umHKCPO42ZVphQZAQbnXz2IQBjfxyEg5TVaSgIAAAAA==; domain=sharepoint.com; path=/; secure; HttpOnly;FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjIsMGguZnxtZW1iZXJzaGlwfDEwMDM3ZmZlOTkyODU3YTJAbGl2ZS5jb20sMCMuZnxtZW1iZXJzaGlwfHJpY2thcmRAc2xhbG9tY29uc3VsdGluZy5vbm1pY3Jvc29mdC5jb20sMTMxMjkyMzk3NzMwMDAwMDAwLDEzMTIzNjQ1ODg1MDAwMDAwMCwxMzEyOTY3MTc3ODAwMzg0MTksMC4wLjAuMCwyLGYyMmNlMTI1LTA0MjEtNDE5NS1hYjhkLTk2YWUxYTU4NjdkYywsVjIhMTAwMzdGRkU5OTI4NTdBMiExMzEyOTIzOTc3MywyYzUyY2M5ZC1iMDE4LTIwMDAtMzZiYy05ZWIwZDUzNmNjOGIsMmM1MmNjOWQtYjAxOC0yMDAwLTM2YmMtOWViMGQ1MzZjYzhiLEdDU3N4QlpSQm54WHFrbUhJdGovN1ZXcXM3c05CUEdBdDVoV1F4M2R3S3hxbGZBdm9zZVl1bUg0SFlPY01iZTRHalA5ZE9BemtvMGNWdFJsVWc0czhNK2V0VUxUWk9nSGhOZmlZRm5YbHh1TTFidDAxbERCdHJYS1ppK2FYS3oyVW9QTU9Oa1A2VHpUcVplV0VrYjBwN2ZTTDkyMVpCaXV5NXJnSU9UL045blRsZzVlZVhibnhBQUh6a0EyclB1Q0xLQ2VmbDVzMDlBYXZva3NPQlBlQk9Ma1BrUVJOU2RycnlrUEJlTWdEdzN0Y2FjQVlHRFBNNUR1UUVJcHJtWGlRN0VLeUdjUE5PQnJhM0FVdGtBdFlQN09ESXlqMWZreEZmZUtNQnAxN2h4RFhXanc5WGs5cXlXWjU0Uy9JVVNheU9WVm1ReHZBcE1IakhFcThwdjJsUT09PC9TUD4=; path=/; secure; HttpOnly'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 7.1.1; Nexus 6 Build/N6F26Q)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: v7.widget.AppCompatImageView{92f71a8 V.ED..... ........ 0,168-1188,168 #7f0f013b app:id/chat_imageview}(params=-1x-2->size=1188x0), async, first)
V/GLIDE: .onResourceReady(GlideBitmapDrawable@dadf744(1188x891@RGB_565), https://REDACTED.sharepoint.com/sites/OTSG/StarWars/Pictures/_w/e07c3779-a87e-4d5e-9dd7-2c95e56ee0e8_jpg.jpg
         LazyHeaders{headers={Cookie=[StringHeaderFactory{value='rtFa=4cVvWRx9nNTzZPOA3mcevH8N1BK4p37Quyws5f5v+XJkwqwL1clDbjHAbrKn+sa1s3z3faRq/sfoo5s6tfj/5eLr3NZxdS36Gdb6663IrKOE1+swSmIu95EvHLUeXhyHHZ5j+5FRdtkPPKSIepkkWcUsywai6iqAfsGzyqXj9fUuawMITgbaw0GtILvBSCTdppSizXZLAjtFEAaIUGd4igRR2cDXVCA1tib6HOodCWR0gZin2NGKblKxwWVaWr/qz+EtSCfE+Md04ZLE28bAiY+n4acGObbb5DBmOYMhzLEsaVThMZEe7Vrr8l7G/Q2mIFSHZD6TjCGJnsyqGazxUz/T8l8umHKCPO42ZVphQZAQbnXz2IQBjfxyEg5TVaSgIAAAAA==; domain=sharepoint.com; path=/; secure; HttpOnly;FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjIsMGguZnxtZW1iZXJzaGlwfDEwMDM3ZmZlOTkyODU3YTJAbGl2ZS5jb20sMCMuZnxtZW1iZXJzaGlwfHJpY2thcmRAc2xhbG9tY29uc3VsdGluZy5vbm1pY3Jvc29mdC5jb20sMTMxMjkyMzk3NzMwMDAwMDAwLDEzMTIzNjQ1ODg1MDAwMDAwMCwxMzEyOTY3MTc3ODAwMzg0MTksMC4wLjAuMCwyLGYyMmNlMTI1LTA0MjEtNDE5NS1hYjhkLTk2YWUxYTU4NjdkYywsVjIhMTAwMzdGRkU5OTI4NTdBMiExMzEyOTIzOTc3MywyYzUyY2M5ZC1iMDE4LTIwMDAtMzZiYy05ZWIwZDUzNmNjOGIsMmM1MmNjOWQtYjAxOC0yMDAwLTM2YmMtOWViMGQ1MzZjYzhiLEdDU3N4QlpSQm54WHFrbUhJdGovN1ZXcXM3c05CUEdBdDVoV1F4M2R3S3hxbGZBdm9zZVl1bUg0SFlPY01iZTRHalA5ZE9BemtvMGNWdFJsVWc0czhNK2V0VUxUWk9nSGhOZmlZRm5YbHh1TTFidDAxbERCdHJYS1ppK2FYS3oyVW9QTU9Oa1A2VHpUcVplV0VrYjBwN2ZTTDkyMVpCaXV5NXJnSU9UL045blRsZzVlZVhibnhBQUh6a0EyclB1Q0xLQ2VmbDVzMDlBYXZva3NPQlBlQk9Ma1BrUVJOU2RycnlrUEJlTWdEdzN0Y2FjQVlHRFBNNUR1UUVJcHJtWGlRN0VLeUdjUE5PQnJhM0FVdGtBdFlQN09ESXlqMWZreEZmZUtNQnAxN2h4RFhXanc5WGs5cXlXWjU0Uy9JVVNheU9WVm1ReHZBcE1IakhFcThwdjJsUT09PC9TUD4=; path=/; secure; HttpOnly'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 7.1.1; Nexus 6 Build/N6F26Q)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: v7.widget.AppCompatImageView{92f71a8 V.ED..... ......ID 0,168-1188,168 #7f0f013b app:id/chat_imageview}(params=-1x-2->size=1188x0), sync, first)

**Comment by joeytsai** [comment]
For readability, replacing the headers with IDENTICAL_HEADERS (and I checked, they are):

V/GLIDE: .onResourceReady(GlideBitmapDrawable@becb5cb(1188x891@RGB_565), https://REDACTED.sharepoint.com/sites/OTSG/StarWars/Pictures/_w/e07c3779-a87e-4d5e-9dd7-2c95e56ee0e8_jpg.jpg
         LazyHeaders{headers={Cookie=[StringHeaderFactory{value='IDENTIAL_HEADERS'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 7.1.1; Nexus 6 Build/N6F26Q)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: v7.widget.AppCompatImageView{92f71a8 V.ED..... ........ 0,168-1188,168 #7f0f013b app:id/chat_imageview}(params=-1x-2->size=1188x0), async, first)
V/GLIDE: .onResourceReady(GlideBitmapDrawable@a2c7eac(1188x891@RGB_565), https://REDACTED.sharepoint.com/sites/OTSG/StarWars/Pictures/_w/e07c3779-a87e-4d5e-9dd7-2c95e56ee0e8_jpg.jpg
         LazyHeaders{headers={Cookie=[StringHeaderFactory{value='IDENTIAL_HEADERS'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 7.1.1; Nexus 6 Build/N6F26Q)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: v7.widget.AppCompatImageView{92f71a8 V.ED..... ......ID 0,168-1188,168 #7f0f013b app:id/chat_imageview}(params=-1x-2->size=1188x0), sync, first)
V/GLIDE: .onResourceReady(GlideBitmapDrawable@638d998(1188x891@RGB_565), https://REDACTED.sharepoint.com/sites/OTSG/StarWars/Pictures/_w/e07c3779-a87e-4d5e-9dd7-2c95e56ee0e8_jpg.jpg
         LazyHeaders{headers={Cookie=[StringHeaderFactory{value='IDENTIAL_HEADERS'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 7.1.1; Nexus 6 Build/N6F26Q)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: v7.widget.AppCompatImageView{92f71a8 V.ED..... ........ 0,168-1188,168 #7f0f013b app:id/chat_imageview}(params=-1x-2->size=1188x0), async, first)
V/GLIDE: .onResourceReady(GlideBitmapDrawable@dadf744(1188x891@RGB_565), https://REDACTED.sharepoint.com/sites/OTSG/StarWars/Pictures/_w/e07c3779-a87e-4d5e-9dd7-2c95e56ee0e8_jpg.jpg
         LazyHeaders{headers={Cookie=[StringHeaderFactory{value='IDENTIAL_HEADERS'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 7.1.1; Nexus 6 Build/N6F26Q)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: v7.widget.AppCompatImageView{92f71a8 V.ED..... ......ID 0,168-1188,168 #7f0f013b app:id/chat_imageview}(params=-1x-2->size=1188x0), sync, first)

**Comment by TWiStErRob** [comment]
Still nothing :(

It looks like you're getting the correct sized bitmaps, but maybe their content is transparent or something like that?

Do you have any other interaction with these ImageViews? Layout/draw listeners, animations and the like? Any method calls on `chatImageIv` that may affect this?

**Comment by joeytsai** [comment]
Before the Glide call I do                
chatImageIv.setVisibility(View.VISIBLE);
but I've done this many other times without incident.  (There are other times when the imageView is GONE.)

Before the Glide call I also set a clickListener on the enclosing LinearLayout.  

The only other non-Glide interaction I'm investigating is my RecyclerView.Adapter is setting ViewHolder.itemView.setLayoutParams() to do sticky-header layout, but this is feeling less likely esp. considering the image properly loads after the third fling up and down.

The best clues I've seen are the isFromMemoryCache = [false] or ..async, first) vs sync, first) from the onResourceReady() calls, which directly correspond to whether the image appears or not.  Was hoping that would jog an idea =l

**Comment by TWiStErRob** [comment]
Yeah, it did jog, that there's a problem outside Glide :) Sadly, from there, it's just shooting in the dark without a repro repo. Visibility affects Glide loads, but since you set it beforehand there's no problem there. Hidden views don't draw, so Glide can't get the size to even start the load, but yours actually finish loading.

Async failure suggests that you may do something that affects the display after the Glide load started (`into` returns), but before it finished (`onResourceReady`).

**Comment by joeytsai** [comment]
Thanks Rob, I'll keep investigating outside Glide - appreciate the hints!  In case it helps, looking at the layouts from the Layout Inspector shows these differences in the AppCompatImageView (displayed image first, hidden image second):

- mPrivateFlags: 0x1018830, 0x81201830
- mPrivateFlags_FORCE_LAYOUT: n/a, 0x1000
- mPrivateFlags_DRAWING_CACHE_INVALID: n/a, 0x0
- mPrivateFlags_DIRTY: n/a, 0x200000
- getPivotY(): 445.5, 0.0
- getY(): 0.0, 168.0
- isOpaque(): true, false
- mBottom: 891, 168
- mTop: 0, 168
- getHeight(): 891, 0
- getLocationOnScreen_y(): 845, 1994
- mMeasuredHeight: 891, 0
- getMeasuredHeightAndState(): 891, 0

Seems when the image doesn't appear the height = 0 and has more view private flags set?

**Comment by joeytsai** [comment]
An update!  By adding a .placeholder() to the Glide line:
```java
                Glide.with(context)
                        .load(GlideUtil.authUrl(context, optimizedUrl))
                        .listener(new LoggingListener<>(requestListener))
                        .placeholder(R.drawable.ic_wallpaper_black_24dp)
                        .into(chatImageIv);
```

The image loads the 3rd time! (So the image only doesn't show the first time.)  The 3rd load still shows async onResourceReady().  Additionally, if I leave the Activity and return so the image stays in memory cache, the first load still fails (though onResourceReady() has sync).

**Comment by TWiStErRob** [comment]
Updated your diff to a table. The flag diff: `PFLAG_INVALIDATED | PFLAG_DIRTY | PFLAG_FORCE_LAYOUT` is in hidden image (sounds like `setImageDrawable` was just called and the drawable was differently sized than the preivous one) and `PFLAG_DRAWING_CACHE_VALID | PFLAG_ANIMATION_STARTED` (this is probably `.crossFade()` doing the fallback alpha fade-in animation) for displayed image. You can try turning off animation with `.dontAnimate()` to see if it makes a difference.

When did you make this observation of the layout? Asking because of the 0 height, that feels like the image is not yet set. What does your `requestListener` do? Try without `adjustViewBounds`, maybe.

1st failing, 3rd not: is it possible you have some code that only happens on recycle? It sounds like a freshly inflated item state is different from one that's rebound.

**Comment by joeytsai** [comment]
I tried many of DrawableRequestBuilders options, but the only one that changed behavior was the aforementioned .placeholder().  That in mind, I changed the item layout to include a drawable:

```xml
 <ImageView
                android:id="@+id/chat_imageview"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:adjustViewBounds="true"
                android:src="@drawable/ic_wallpaper_black_24dp"
                android:contentDescription="@string/chat_image"/>
```

and adding the "android:src" worked, the image reliably loads 100% of the time!  Perhaps I didn't set up things correctly or there is a weird interaction going on - there still noticable remains visual artifacts as the layout appears to change from layout_width x layout_width to layout_width x scaled_image_height - but my main issue of the image not loading has been resolved.

Thanks a lot for helping me debug Rob, I'll also close this issue

**Comment by TWiStErRob** [comment]
Did you try without `adjustViewBounds`? Can you please share the code that's changing the layout?

**Comment by joeytsai** [comment]
Without src or adjustViewBounds: first load: no image; second load: images load taking up the width of the layout; third load: images load, but are not correctly sized (they are tiny, although it looks like their aspect ratio has been retained).

With src but without adjustViewBounds: images load every time, but every load they are the tiny sized.  I think this tiny size is the size of @drawable/ic_wallpaper_black_24dp unscaled.

There is no code changing the layout, I'm saying I see some resizing layout issues.  When I first load the list the layout of the containing item wraps the image (this is what I want).  When I fling away and back, the image is the same size, but the enclosing layout is now much taller (this looks bad since there's too much whitespace above and below the image).  Sometimes I witness this layout resizing and the size of the layout jumps.

**Comment by TWiStErRob** [comment]
I was referring to "my RecyclerView.Adapter is setting ViewHolder.itemView.setLayoutParams()".

Hmm, the sizing seems to be actually correct. If the placeholder is set in XML or via `.placeholder()` then Glide will likely observe its size. When you fling there will be many placeholder setting binds, and then the last re-bind will observe those previous placeholders, or even its own placeholder. That's just how Glide works.

You could try the `chatImageIv.layout(0,0,0,0)` hack (just before `into()`) to reset the observed size to invalid so Glide waits for a layout. The weird thing is that you always seemed get the right sized bitmap in the original versions.
