### ISSUE TITLE
Images don't load in fragment or nested fragment if placeholder function is used.

### ISSUE THREAD

**Issue by sandeeprana011** [bumptech/glide#1702]
**Glide Version**: compile 'com.github.bumptech.glide:glide:3.7.0'

**Integration libraries**: No i didn't tried.

**Device/Android Version**: Moto G4/7.0 Nougat

**Issue details / Repro steps / Use case background**: Issue is coming out when i proceed with the placeholder(int) function. But without placeholder it works fine.
To reproduce the error  
1. Take A Activity
2. Inside that create A fragment
3. Inside that take a Recycler View 
4. Apply adapter in overriden function onBindView put this code

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(fragment.getActivity())// I tried all contexts
                .load(<Some Url>)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .override(128, 128)
                .error(R.drawable.icon_person)
                .placeholder(R.mipmap.ic_launcher)
                .into(viewHolder.imageView);
```

**Layout XML**:
```xml
 <LinearLayout
        android:id="@+id/layout_normal"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal|top"
        android:gravity="center_horizontal"
        android:orientation="vertical"
        android:padding="@dimen/_6sdp">


        <de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/activity_select_category_imageview_item"
            android:layout_width="@dimen/_50sdp"
            android:layout_height="@dimen/_50sdp" />
<...>
```

**Comment by TWiStErRob** [comment]
The issue has nothing to do with context, or nesting, see [Compatibility about `CircleImageView`](https://github.com/bumptech/glide#compatibility).
