### ISSUE TITLE
Glide doesn't rotate image on Samsung devices

### ISSUE THREAD

**Issue by pawlo2102** [bumptech/glide#1704]
Glide doesn't rotate image based on exif tag on my samsung A3. On other devices it works perfect. Does anyone have a workaround to fix this issue? Here is how i load image from server:

`Glide.with(getContext()) .load(Uri.parse(uri)) .fitCenter()
                .crossFade()
                .error(R.drawable.icn_photo_negative)
                .into(getProfileImageView());`

**Comment by TWiStErRob** [comment]
Run the above line on A3 with debugger attached and put a breakpoint in `com.bumptech.glide.load.resource.bitmap.Downsampler#decode` on the line `new ImageHeaderParser(exceptionStream).getOrientation()` and step into it to see what happens.
