### ISSUE TITLE
Get image dimensions prior to full load

### ISSUE THREAD

**Issue by Phinatic** [bumptech/glide#1709]
Is it possible to get the image dimensions from Glide prior to the image being fully downloaded? I would like to setup the layout prior to the download to reduce screen movement.

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/issues/781, but it's better if you can make your server/service return `{width: x, height: y, url: "blah"}` objects. I don't think you would gain much from getting the size, because the timescale would be like:
```
| into | ----------------------------------------------------------------- | size | -- | image |
```

**Comment by TWiStErRob** [comment]
Actually from #781 &rarr; [GNiGFBMwyfE](https://groups.google.com/forum/m/#!msg/glidelibrary/GNiGFBMwyfE/ae9PXuYXAgAJ) 2) may work for you, but it would need to be a double request.
