### ISSUE TITLE
Please add animate(boolean) method to Glide builder

### ISSUE THREAD

**Issue by jahirfiquitiva** [bumptech/glide#1714]
**Glide Version**: 3.7.0

**Integration libraries**: none

**Device/Android Version**: Moto G 2nd Gen - Android 7.1.1

**Issue details / Repro steps / Use case background**: 

Hi, I wanted to ask you to please add a method like this one to Glide builder:
```java
animate(boolean doAnimation)
```

It will be really useful for me, and I think for many other people too, because I have a preference in my app that enables/disables animation.
Right now, my code is:
```java
if (mPrefs != null && mPrefs.getAnimationsEnabled()) {
	Glide.with(context)
			.load(res)
			.priority(Priority.IMMEDIATE)
			.into(holder.icon);
} else {
	Glide.with(context)
			.load(res)
			.priority(Priority.IMMEDIATE)
			.dontAnimate()
			.into(holder.icon);
}
```

With the implementation of a method like the one I'm requesting, the code would be as simple as:
```java
Glide.with(context)
		.load(res)
		.priority(Priority.IMMEDIATE)
		.animate(mPrefs != null && mPrefs.getAnimationsEnabled())
		.into(holder.icon);
```

As you can see, it results in less written code.

Thanks in advance.

**Comment by TWiStErRob** [comment]
`boolean` arg would restrict you to built-in animation. I suggest you to do this (available in 3.8.0):
```java
.animate(wantAnimation()
        ? new DrawableCrossFadeFactory<GlideDrawable>()
        : new NoAnimationFactory<GlideDrawable>()
)
```
You can even write your own factory that's a wrapper around preferences.
