### ISSUE TITLE
Using Glide with Amazon s3 presigned url 

### ISSUE THREAD

**Issue by Sutirth** [bumptech/glide#1717]
Using Glide version: 3.7.0

Well, I have been using a basic URL to load images into glide which works perfectly. However, due to recent server load, I am required to load images directly from amazon s3 server. The code for which is as follows.

    AmazonS3 s3 = AmazonUtil.getS3Client(this);
    URI uri = s3.generatePresignedUrl("bucket-name", "myUserId", new DateTime().plusDays(90).toDate()).toURI();
    Log.i(TAG, "Amazon url: " + uri);
           

I tried loading this URI directly into Glide method load. It seems s3.generatedPresignedUrl is downloading the image on the main thread and hence I am not able to download the image. I have many recycler views which have images one after another. Is there builder or custom method where I can integrate amazon s3 with glide seamlessly.

**Comment by TWiStErRob** [comment]
What is returned by `generatePresignedUrl`? `URL` is known to make network calls willy-nilly; though Android may have fixed that.

Assuming that `generatePresignedUrl` is blocking, you can create a custom Model class that encapsulates bucket and user id, then write a custom fetcher that generates the URI in the background and makes the request. See [this](https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/github/_670_delegate/FlickrModelLoader.java) on how to fall back a built-in fetcher. `getResourceFetcher` is called on the UI thread AFAIR, so make sure you do the url generation in `loadData` and delegate to the default loader with `URI`.

**Comment by Sutirth** [comment]
@TWiStErRob  generatePreignedUrl actually generates target Url if I click on it from android studio console it will start downloading the image from amazon s3 server. Is my issue similar to one #634.

**Comment by TWiStErRob** [comment]
If it's non-blocking you can just create a custom model class, model loader and fetcher. #634 is a good example, but you can find a lot more in this project: https://github.com/TWiStErRob/glide-support/search?utf8=%E2%9C%93&q=%22implements+DataFetcher%22&type=Code

**Comment by jontyankit** [comment]
I was also looking for loading images via Amazon S3.
So I created repo.
https://github.com/jontyankit/Glide-Amazon-Image-Load
