### ISSUE TITLE
use okhttp3-integration with custom GlideModule

### ISSUE THREAD

**Issue by byedo** [bumptech/glide#1718]
i wanno use compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar' and then custom a GlideModule  to use PREFER_ARGB_8888, i think there will have two GlideModule in androidmanifest.xml,can both of them work?

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/wiki/Configuration#conflicting-glidemodules

**Comment by TWiStErRob** [comment]
Oh, but you can leave OkHttp3 as is and just create your own module. If no setup is done that conflicts between the two modules you're ok. For example OkHttp replaces networking and your module would just change decode format.
