### ISSUE TITLE
Does not load by url starts from //

### ISSUE THREAD

**Issue by dimmduh** [bumptech/glide#1719]
Does not load image from url like:
//lh3.googleusercontent.com/bSR-e2pEgMrWEanWiy8y-Mwgl2PSwKFg67jMbV1rufRRkIUJYK0670-K_YDQab56jA=w300

**Comment by TWiStErRob** [comment]
`//` is a notation for the web, how should Glide know if it's `http`/`https` or anything else? In a browser you have the context of the current page you're on, whose protocol is used in front of `//`. Just prepend whichever you want to use, or write a custom model loader to overwrite the default and handle it automatically. For this latter let me know if you need help.

**Comment by dimmduh** [comment]
Glide can start to load via http and follow redirect to https if it's required.
But I agree, that better if developer resolves it by yourself.

**Comment by TWiStErRob** [comment]
I've seen sites that simply don't respond to `http` calls, only `https`, With `http` it looks like the site doesn't exist, in that case there won't be a redirect. Though this should be the exception to the rule. Anyway, `//` is not a common notation as far as I know, it's for websites running in web browsers.
