### ISSUE TITLE
Are you using the Libpng library?

### ISSUE THREAD

**Issue by SheldenJeong** [bumptech/glide#1720]
I am tring to register my app to Google play store.
But I got reject with below comment.
Are you using the Libpng library?

"Libpng library 
The vulnerabilities were fixed in libpng v1.0.66, v.1.2.56, v.1.4.19, v1.5.26 or higher. You can find more information about how resolve the issue in this Google Help Center article."

I used the version 3.7.0 of Glide.

**Comment by TWiStErRob** [comment]
Short: no.

Longer: run `gradlew :app:dependencies` on your project to see what you pulled in. It may be listed. I think Fresco may have native libs, we don't have any.

You can take a look into your dependencies if you go to your gradle cache and open the AAR files as ZIP files.
