### ISSUE TITLE
glide load gif never loop with  LOOP_INTRINSIC mode

### ISSUE THREAD

**Issue by Letty-Liang** [bumptech/glide#1724]
here i find a bug, when glide load git with LOOP_INTRINSIC mode, a forever loop gif will never loop at all

=====code====
in third party parse  
https://gist.githubusercontent.com/devunwired/4479231/raw/df2725be4ae0f12f5265deaf0a769936ea94950b/GifDecoder.java
**protected int loopCount = 1; // iterations; 0 = repeat forever**

    /**
     * Reads Netscape extension to obtain iteration count.
     */
    private void readNetscapeExt() {
        do {
            readBlock();
            if (block[0] == 1) {
                // Loop count sub-block.
                int b1 = ((int) block[1]) & 0xff;
                int b2 = ((int) block[2]) & 0xff;
                header.loopCount = (b2 << 8) | b1;
            }
        } while ((blockSize > 0) && !err());
    }

**while in glide loopCount = 0 means never loop** 

    @Override
    public void setLoopCount(int loopCount) {
        if (loopCount <= 0 && loopCount != LOOP_FOREVER && loopCount != LOOP_INTRINSIC) {
            throw new IllegalArgumentException("Loop count must be greater than 0, or equal to "
                    + "GlideDrawable.LOOP_FOREVER, or equal to GlideDrawable.LOOP_INTRINSIC");
        }

        if (loopCount == LOOP_INTRINSIC) {
            maxLoopCount = decoder.getLoopCount();
        } else {
            maxLoopCount = loopCount;
        }
    }
hope u will fix it soon or maybe i could create a pr

**Comment by TWiStErRob** [comment]
Fixed for 3.8.0 in #1813, you can consume it via https://github.com/bumptech/glide/wiki/Snapshots, thanks @toyama-sumio!
