### ISSUE TITLE
Image Center Crop not working properly

### ISSUE THREAD

**Issue by himmatpratapsinghgill** [bumptech/glide#1725]
Hi,

I have been using Glide for a while loading image URLS into my customised image views. HOwever, I came across an issue today where if I pick an Image from my gallery and set that uri, the image gets loaded properly with the center crop scale type. However next time, the image is loaded when I come on that screen, I have that uri locally saved and when I set the image the scale type automatically become something similar to fit center instead of center crop. I am stuck and not able to debug what to do here.

```java
if (mLicenseImageUri != null) {
                               mLicenseImage.setImageUri(mLicenseImageUri,        R.drawable.ic_register_image_default, false);
                mLicenseFrame.setBackgroundResource(R.drawable.shape_dotted_rectangle);
            }
```

where 

```java
    /**
     * This method is used to setImage on ImageView.
     *
     * @param uri          set url to get image
     * @param defaultImage set default image if url fails
     * @param isRounded    {@link ScaleType} if not any pass null
     **/


    public void setImageUri(Uri uri, int defaultImage, boolean isRounded) {

        mAsyncImageView.isImageRound(isRounded);
        mRequestManager.load(uri).asBitmap().centerCrop().error(defaultImage)
                .placeholder(defaultImage).listener(new CustomRequestListener(getContext(), mProgressBar)).into(mAsyncImageView);


    }
```

**Comment by thuan-savvycom** [comment]
I have the same issue. Please help.

**Comment by himmatpratapsinghgill** [comment]
The mAsyncImageView is nothing but a custom Image view that I use for my projects. The class itself extends ImageView as the base class. IsImageRound is a variable that I use to check if the image is to be drawn as a circular image or just the regular one. Not sure what the issue is here but something is definitely off place. 

@https://github.com/thuan-savvycom- could you share your methods as well so that we are able to see the code. Not sure what is wrong in my code.

The image is present inside a Linear Layout and am using the latest version of Glide

**Comment by TWiStErRob** [comment]
Can you try without your custom component?
(there are a lot of unknowns here, reducing them could help find the culprit).

> The image is present inside a Linear Layout

I'm looking for match and wrap on the imageview itself and any parents.

> am using the latest version of Glide

So that could be 3.7.0, 3.8.0-SNAPSHOT, 4.0-SNAPSHOT

**Comment by dishantkawatra** [comment]
Glide.with(mActivity)
                    .load(imageUrl)
                    .apply(new RequestOptions().dontTransform().placeholder(placeholder))
                    .into(imageView);

Please use this and and glide version is 4.8.0
