### ISSUE TITLE
GlideModule integration with custom OkHttp not working with HTTPS images

### ISSUE THREAD

**Issue by Nickx27** [bumptech/glide#1726]
Hi,
When I try to load images from "https" the image is not loading throwing the exception in Log "javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.".

I tried the solution provided in the following link, but no improvements
https://futurestud.io/tutorials/glide-module-example-accepting-self-signed-https-certificates

I can use the custom Okhttp which I used with glide for Retrofit, which works fine.
Looking forward for your reply,
Thanks.

**Comment by TWiStErRob** [comment]
If it works for Retrofit with your custom OkHttpClient, then make Glide use that client.
See for example [glide-support#1133_stetho](https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/github/_1133_stetho_integration/GlideModule.java) + [wiki on how to register the GlideModule](https://github.com/bumptech/glide/wiki/Configuration#registering-a-glidemodule)

**Comment by Nickx27** [comment]
Thanks Rob, It works with <meta-data android:name="com.bumptech.glide.integration.okhttp.OkHttpGlideModule" tools:node="remove" /> code in manifest :) :+1:

**Comment by muthuraj57** [comment]
@Nickx27 `<meta-data
            android:name="com.bumptech.glide.integration.okhttp3.OkHttpGlideModule"
            tools:node="remove" />` if using okhttp3

**Comment by Allan-Nava** [comment]
I have errors when I try to Override the registerComponents

```
 @Override
    public void registerComponents(Context context, Glide glide) {
        OkHttpClient client = UnsafeOkHttpClient.getUnsafeOkHttpClient();
        glide.register(GlideUrl.class, InputStream.class,
                new OkHttpUrlLoader.Factory(client));
    }
```

![screen shot 2017-10-18 at 10 22 00](https://user-images.githubusercontent.com/22498435/31708030-35195d3c-b3ee-11e7-810a-690aa8cccbb8.png)

**Comment by TWiStErRob** [comment]
@Allan-Nava looks like you're missing an import.
You need to reference these: https://github.com/bumptech/glide/tree/master/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3

**Comment by Allan-Nava** [comment]
@TWiStErRob Yes, i solve with add missing import.
