### ISSUE TITLE
Glide gif and Bitmap access.

### ISSUE THREAD

**Issue by benevolent13** [bumptech/glide#1727]
I have a issue as Glide support for gif I am using gif as thumnail and loading url to imageview.Issue is I want the Bitmap from imageview in new SimpleTarget.

here is my code.

```
Glide.with(getApplicationContext()).load(url)
                .thumbnail(Glide.with(getApplicationContext()).load(R.drawable.preloader))
                .fitCenter()
                .crossFade()
                **.into(Want bitmap here is it possible);**
```

**Comment by TWiStErRob** [comment]
`asBitmap`?
Can you please clarify if that's not what you're looking for?

**Comment by benevolent13** [comment]
I have tried it but when i use .asBitmap my thumbnail shows an error(Cannot resolve the method thumbnail).The other option I used is that I called Glide.... again  and I kept that asBitmap and got bitmap.But what I want is when i load for first time i want the bitmap.Don't want to call the Glide... again for just bitmap.
Thank you

**Comment by TWiStErRob** [comment]
The types must match `.asBitmap` loads a `Bitmap`, but that `thumbnail` loads a `GlideDrawable`. There are ways around that, but you should just use `.placeholder(R.drawable.preloader)` and not `.thumbnail` API in this case.

**Comment by KhalidElSayed** [comment]
@TWiStErRob 
the `.asBitmap()` itself shows this error "Can't resolve method '.asBitmap()'"
below is my code:
`Glide.with(mContext)
                .load(book.getImageUrl())
                .asBitmap()
                .placeholder(R.drawable.img_book_placeholder)
                .error(R.drawable.img_book_placeholder)
                .into(holder.imgBook);`
and if I remove it the `.placeholder()` shows the error instead!
btw: I use the latest version 4.0.0
