### ISSUE TITLE
How to scale tall image and keep the ratio?

### ISSUE THREAD

**Issue by namchuai** [bumptech/glide#1728]
**Glide Version**: 3.7.0

**Integration libraries**: com.github.bumptech.glide:okhttp3-integration:1.4.0@aar

**Device/Android Version**: Xiaomi Mi5 / 6.0.1

**Issue details / Repro steps / Use case background**: I'm trying to display tall image by scale the width to fit the width of the screen, and keep the width/height ratio.

I want to make this image scale match_parent width

![screenshot_2017-02-13-08-57-50-662_com vnindie nobrain](https://cloud.githubusercontent.com/assets/10397206/22876998/eabbdd5a-f205-11e6-8356-326e24b62fce.png)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(target.getContext())
        .load(url)
        .asBitmap()
        .diskCacheStrategy(DiskCacheStrategy.RESULT)
        .into(target);
```

**Layout XML**:
```xml
<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/white">

    ....

    <ImageView
      android:id="@+id/post_image"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_below="@id/post_title"
      android:contentDescription="@string/post_content"/>

    ....

  </RelativeLayout>
```

**Comment by TWiStErRob** [comment]
Currently `wrap_content` is not supported as is. It's implemented as an alias to screen width/height in hopes that the other dimension is not `wrap_content` and the aspect ratio will help to get a nice and efficient image. This works most of the cases.
In your case match-wrap results in constraints that match the screen size, and then `fitCenter` just does its job and fits the whole image inside that area.

A quick and dirty fix would be `.override(screenWidth, Target.SIZE_ORIGINAL)`, but it'll quickly result in an OOM or an OpenGL texture issue.

There's no simple fix for this, sorry; take a look at #700.
