### ISSUE TITLE
Glide not updating image on same  url ,using signature api also

### ISSUE THREAD

**Issue by DemindoO** [bumptech/glide#1729]
I have the same url for an image. When I update this image more than one time it shows the previous image. The image and picture version on the server is updated but Glide is not showing the new image.I want to get new changed image  and cache it.

```java
Glide.with(context)
        .load(Constants.COPY_LINK_BASE_URL + info.getDisplayPicture())
        .placeholder(R.drawable.ic_profile).dontAnimate()
        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
        .signature(new (LocalPreferebManager.getUserPictureVersion(context)))
        .into(ivUserProfilePhoto);
```

I can reproduce this bug by changing internet ,on one internet its change image as expected on other internet it remain same after 2 or 3 tries to changing image

**Comment by TWiStErRob** [comment]
Your setup looks correct.

> I can reproduce this bug by changing internet

I'm assuming you mean a different WiFi/wired network. Based on this, it sounds like you have a proxy between you and your image server that caches the image by url and doesn't have a concept of `userPictureVersion`.

> I want to get new image every time and cache it.

That's a contradiction, what's the point of caching if you want to get it every time?

---

As a workaround you can try
```
url = Constants.COPY_LINK_BASE_URL + info.getDisplayPicture() + "?ver=" + SettingManager.getUserPictureVersion(context)
```
but if the signature version works on most internet connections, I wouldn't do this concatenation. There must be a reason why its cached.

**Comment by DemindoO** [comment]
Image is changed by user and have to update

**Comment by TWiStErRob** [comment]
Because it's a hack.
To invalidate Glide cache the API is `.signature`.
To invalidate a proxy on a certain network: it's out of scope for Glide.

Did you actually test whether there's a proxy in play? I think if you open the profile in the browser and then you change it, and reload the image in browser, it should behave the same as the app.

I'm not saying you can't use it, because it'll work; just trying to make you aware of the choice you're making.

**Comment by DemindoO** [comment]
if  i copy open URL in Chrome browser before and after changing it display right image. in Firefox it behave like app . i do not know how to check that proxy in play ! :(
