### ISSUE TITLE
Glide memory cache interop w/ other libs?

### ISSUE THREAD

**Issue by jbarr21** [bumptech/glide#1734]
I'm interested in moving to Glide, but don't want to have 2 memory caches. I'm planning on providing a memory cache wrapper to Glide that delegates to my current image loading library's memory cache. I was not able to find anything while looking through the source or with my test app. Does Glide do anything to images, especially around bitmap pooling or recycling, that would cause any issues with this approach?

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/wiki/Configuration#memory-cache how to replace memory cache and bitmap pool. It's also a good pointer for default implementations (just look at who implements the interfaces).

I think there's some `reconfigure` going on either in the pool or in `Downsampler`. `Downsampler` definitely does `Options.inBitmap`
