### ISSUE TITLE
GLIDE: onException(java.io.IOException: Request failed 404: Not Found

### ISSUE THREAD

**Issue by kashif06** [bumptech/glide#1738]
I am getting GLIDE: onException(java.io.IOException: Request failed 404: Not Found ERROR and it further says that  http://10.0.2.2/images/f.png not found.......

**Comment by idanakav** [comment]
Please provide more info, you are trying to access a local address, are you sure that address is reachable on your device?

**Comment by kashif440** [comment]
I found the problem. Actually, the IP address was a local one, not 10.0.2.2. Now it's working because I was testing on my real phone.
