### ISSUE TITLE
Disk cache RESULT cacheDecoder never called in Glide

### ISSUE THREAD

**Issue by idish** [bumptech/glide#1740]
I'm using Glide to load encrypted images from local files and also would like to use Glide's disk cache to save only the RESULT encrypted image files (I would like them to be encrypted in cache and not plain image)

The reason I would like to use the disk cache to save the result image (default behavior) is because the decryption process from the disk cache would be much more efficient than encrypting it from the original big image file, as the disk cache has a "thumbnail" encrypted version (smaller in size).

The problem is that Glide still manages to load the images even though I still didn't even implement a matching cache decoder that suppose to decrypt the images from the cache..
How could that happen? Does the images don't really get encrypted?

Also, in here: https://github.com/bumptech/glide/issues/735#issuecomment-156370953
The OP also mentioned that Glide's cache decoder wasn't even implemented. 

Relevant code:

```java
        Glide.with(mActivity)
                .load(container)
                .asBitmap()
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .encoder(new DiskCachingEncryptor())
                .centerCrop()
                .into(holder.image);
```

**Comment by idish** [comment]
Any help please?

**Comment by TWiStErRob** [comment]
I answered the magic decrypt below that comment, additionally it could be coming from memory cache. While testing, add `.skipMemoryCache(true)`. See https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling to figure out what's going on inside Glide.

**Comment by TWiStErRob** [comment]
To further debug you can also peek into the Glide cache with a hex editor to see if you can see the JPEG header or just some mumbled stuff (encrypted). For this, **temporarily** move the disk cache to an accessible place (unless you're rooted): https://github.com/bumptech/glide/wiki/Configuration#location

**Comment by idish** [comment]
Sorry, I didn't really understand your comment in the other issue.

I added `.skipMemoryCache(true).` but still the cacheDecoder is never called as I expect it to be.
There must be something I'm missing in understanding Glide's caching mechanism.

According to Glide's flow: 
https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit

It looks like Glide has to first call `loadData` (e.g loading from the internet) and only then it should use the cache. Is it correct? (Although this flow doesn't really make sense at all for me)

What is the usage of `RESULT `caching? 'cacheDecoder' never gets called when I set 'RESULT' but only when I set `SOURCE` or `ALL` caching.

**Comment by TWiStErRob** [comment]
`SOURCE` means that the left gray/red arrows will be active, `RESULT` means that the right gray/red arrows will be active, `ALL` means all red/gray arrows will be active. `SOURCE` and `RESULT` caches are decoded by the same object (red arrows).

Try putting breakpoints around [`EngineRunnable`](https://github.com/bumptech/glide/blob/6d44b1834e07ae3a81162eb9a165d4c3364b6723/library/src/main/java/com/bumptech/glide/load/engine/EngineRunnable.java#L51-L82) to see which path is taken and why your encoder/decoder is not called (step into `decode()`). Also look around [`Engine.load`](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/Engine.java#L145-L191) for memory cache behavior. *I created that diagram by reading these sources.*

My suspicion is that encoding fails, so there's no file in cache to cacheDecode from.

**Comment by idish** [comment]
You are right! when I don't put a custom encoder, the `cacheDecoder` is being successfully called!
Which means the my encoder is not encoding the image well.
BTW, what is the usage of `getId()` in the encoding process? Does it have to be unique for each?

**Comment by TWiStErRob** [comment]
`getId()` becomes part of the cache key, see `EngineKey` class. The id of decoder/encoder/transcoder should be static (i.e. same for all load, as long as they're not parametrizable). Fetcher's id should be the resource it's fetching, i.e. the model's toString, which is usually Uri or file path.
