### ISSUE TITLE
how to use FrameSequenceDrawable in listview

### ISSUE THREAD

**Issue by lhjandroid** [bumptech/glide#1743]
i have know how let the cup low form #1604 .but i can't find a way to control the FrameSequenceDrawable in listview
`public static void display(Context context, final String tag, String url, final ImageView targeView, final CheckingProvider mProvider) {
        Glide.with(context).load(url).asGif().toBytes().into(new SimpleTarget<byte[]>() {
            @Override
            public void onResourceReady(final byte[] resource, GlideAnimation<? super byte[]> glideAnimation) {
                Observable.create(new Observable.OnSubscribe<FrameSequenceDrawable>() {
                    @Override
                    public void call(Subscriber<? super FrameSequenceDrawable> subscriber) {
                        ByteArrayInputStream bis = new ByteArrayInputStream(resource);
                        FrameSequence fs = FrameSequence.decodeStream(bis);
                        FrameSequenceDrawable drawable = new FrameSequenceDrawable(fs, mProvider);
//                        ArrayList<FrameSequenceDrawable> drawables = getDrawableList(tag);
//                        drawables.add(drawable);
//                        gifDrawable.put(tag,drawables);
                        subscriber.onNext(drawable);
                    }
                }).subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread()).subscribe(new Action1<FrameSequenceDrawable>() {
                    @Override
                    public void call(FrameSequenceDrawable frameSequenceDrawable) {
                        targeView.setImageDrawable(frameSequenceDrawable);
                        targeView.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener() {
                            @Override
                            public void onViewAttachedToWindow(View v) {
                                Log.e(tag,"view  onViewAttachedToWindow");
                            }

                            @Override
                            public void onViewDetachedFromWindow(View v) {
                                Log.e(tag,"view  onViewDetachedFromWindow");
                            }
                        });
                    }
                });
            }
        });
    }`

when i leave the activity how can i release the drawables. i have record the drawables like this 
`private static ArrayMap<String,ArrayList<FrameSequenceDrawable>> gifDrawable = new ArrayMap<>();`
and when leave the activity to call `public static void releaseAdpter(String tag,CheckingProvider mProvider) {
        SparseArray<FrameSequenceDrawable> drawables = getAdapterDrawableList(tag);
        Log.e(tag,"release count:" + drawables.size());
        int size = drawables.size();
        for (int i = 0 ; i < size; i ++) {
            FrameSequenceDrawable drawable = drawables.valueAt(i);
            drawable.destroy();
            drawable = null;
        }
        gifAdapterDrawable.remove(tag);
        if (!mProvider.isEmpty()) throw new IllegalStateException("All bitmaps not recycled");
        System.gc();
    }`
but it not work. it can't release the drawas. how can i do it? thanks

**Comment by TWiStErRob** [comment]
I'm not saying I understood your above post, you may want to clean it up a little.

`FrameSequenceDrawable` is not part of Glide, so if you have problems with that SO is the place to ask. In Glide the callback for freeing resources is `Target.onLoadCleared`.

Notes:
1) you're still using software decode AND encode built into Glide! (`.asGif()` decodes, `.toBytes()` encodes), you need to create a custom decoder/transcoder to tap into Glide's pipeline.
2) The double-dispatch (rx) in onResourceReady is not a good idea, fast scrolling will mess things up, again, use the pipeline, Glide already does the thread-hopping for you

See the SVG example on the 3.0 branch to see how to write custom stuff
