### ISSUE TITLE
Gif plays very slowly

### ISSUE THREAD

**Issue by Drizzlezhang** [bumptech/glide#1744]
**Glide Version**:3.8.0-SNAPSHOT

**Integration libraries**:1.5.0-SNAPSHOT

**Device/Android Version**:HUAWEI mate7  / Android 6.0

**Issue details / Repro steps / Use case background**: In this device, the gif's animation is very slow.(In other devices the animation speed is correct)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
               Glide.with(context)
                        .load(gifUri)
                        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                        .crossFade(500)
                        .into(imageView);
```

**Comment by TWiStErRob** [comment]
Any chance of sharing the GIF?

**Comment by Drizzlezhang** [comment]
@TWiStErRob Not the gif file's problem. Only in the device(HUAWEI mate7 / Android 6.0). And the problem has been solved  when I rollback to *Glide 3.7.0*.

**Comment by TWiStErRob** [comment]
Ouch, there have been some changes in GIF decoding to support more types of GIFs correctly:
https://github.com/bumptech/glide/compare/0f93217f2dca8133be6ef6654abb0905712ec3b6...3.0#diff-e8fb31a29df05c2aa5edb53954828247

I was asking for the GIF so I can see how the frames are being built. Can you try to profile the app to see what's going wrong? (traces on that device and one that's working as a baseline)

**Comment by Drizzlezhang** [comment]
@TWiStErRob Here is the [gif](http://s2.cdn.xiachufang.com/9748367af81b11e6bc9d0242ac110002_350w_262h.gif?imageView2/2/w/200/interlace/1/q/90/format/gif/.gif). In our Android APP the gif plays very slowly on the device(HUAWEI mate7 / Android 6.0). And not only this gif, every gif has the same problem on the device . I guess the CPU of the device lead to the problem,  you know HUAWEI has self-made CPU.

**Comment by Jeyhey** [comment]
I have the same problem with `com.github.bumptech.glide:glide:4.1.1` on an LG: the gif plays like in very slow motion. The gif in question can be found here: https://giphy.com/gifs/laughing-despicable-me-minions-ZqlvCTNHpqrio
When I play the gif in the phone's gallery app it plays correctly.

**Comment by ajaystha005** [comment]
I also have the same problem on some Samsung and Lg phones :(
