### ISSUE TITLE
How to set it from memory to load？

### ISSUE THREAD

**Issue by ytrjp** [bumptech/glide#1746]
fitst activity is feed, click item got to detail. 
The picture has been loaded in feed, but in the details page also need to be loaded from the disk cache, how can we load from the memory cache ?

**Comment by TWiStErRob** [comment]
The memory cache hit can only happen if the load has the exact same size and transformation, as well as format (asBitmap/asGif/or nothing=drawable).
Try the `.override()` API (you'll need to grab the view size (say in `RequestListener.onResourceReady`) and pass the size along to the detail view).

**Comment by ytrjp** [comment]
ths
