### ISSUE TITLE
Measuring the real size of imageView after loaded

### ISSUE THREAD

**Issue by KamilPieta** [bumptech/glide#1747]
Im loading diffrent images from url into ImageView with parameters layout_width="match_parent" /  layout_height="250dp" sometimes it is horizontal photo of smth, sometimes its vertical. I use fitCenter() parameters in Glide to keep the proportion of the result picture. However I need to place a button in the corner of the loaded picture. How can I measure the real size of the picture after loaded, and set the button in correct place? I tried getSize parameter but the results are incorrect.
example
https://i.stack.imgur.com/D3Cmd.jpg

**Comment by TWiStErRob** [comment]
Wrap the ImageView and the Button in a `FrameLayout` and add `android:layout_gravity="top|end"` to the button.

**Comment by TWiStErRob** [comment]
Aaah, I see :) `match_parent` widens the view, so it would be outside the picture. Try `adjustViewBounds` and wrap the FrameLayout width.
