### ISSUE TITLE
can show .jpg but cant show .JPG

### ISSUE THREAD

**Issue by eccentricyan** [bumptech/glide#1748]
**Glide Version**:
3.7.0

**Integration libraries**:
okhttp3-1.3.1

**Device/Android Version**:
Nexus 5 5.0.1

**Issue details / Repro steps / Use case background**: 
can show .jpg but cant show .JPG

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
  Log.d("url", url); // the picture didnt show if use url with .JPG 
        Glide.with(getContext())
                .load(url)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(this);
```

**Layout XML**:
```xml
<com.example.android.widget.RatioImageView
                    android:id="@+id/image"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:originalWidth="@{viewModel.width}"
                    app:originalHeight="@{viewModel.height}"
                    app:url="@{viewModel.originalUrl}"/>
```

**Stack trace / LogCat**:
```
no error got
```

**Comment by TWiStErRob** [comment]
By default there's no logging, please turn it on: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

I have a suspicion that your server is case sensitive and it just gives a 404 for `.JPG`.
