### ISSUE TITLE
Glide pre loaded image

### ISSUE THREAD

**Issue by arpitjoshi08** [bumptech/glide#1752]
On first activity i loaded five large size images and same images loaded again on second activity but issue is that i already downloaded images on first activity and is available in cache but taking time on second activity when load. my first activity code.

```java
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.third);

    ArrayList<Integer> list = new ArrayList<Integer>();
    list.add(R.drawable.iamge_1);
    list.add(R.drawable.iamge_2);
    list.add(R.drawable.iamge_3);
    list.add(R.drawable.image_5);
    list.add(R.drawable.iamge_4);
    list.add(R.drawable.image_6);
    loadImages(list);

    findViewById(R.id.button3).setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            Intent i = new Intent(First.this, Second.class);
            startActivity(i);
        }
    });
}


public void loadImages(ArrayList<Integer> list) {

    for ( int i = 0; i < list.size(); i++) {
        Glide
                .with(getApplicationContext())
                .load(list.get(i))
                .asBitmap()
                .thumbnail(0.1f)
                 .diskCacheStrategy(DiskCacheStrategy.ALL)
                .priority(Priority.HIGH)
                .override(133, 133);

    }
}
```
and second activity
```java
private void initViews() {
    RecyclerView recyclerView = (RecyclerView) findViewById(R.id.card_recycler_view);
    recyclerView.setHasFixedSize(true);
    RecyclerView.LayoutManager layoutManager = new GridLayoutManager(getApplicationContext(), 2);
    recyclerView.setLayoutManager(layoutManager);

    ArrayList<Integer> androidVersions = prepareData();
    DataAdapter adapter = new DataAdapter(getApplicationContext(), androidVersions);
    recyclerView.setAdapter(adapter);

}

public ArrayList<Integer> prepareData() {
    ArrayList<Integer> list = new ArrayList<Integer>();
    list.add(R.drawable.iamge_1);
    list.add(R.drawable.iamge_2);
    list.add(R.drawable.iamge_3);
    list.add(R.drawable.image_5);
    list.add(R.drawable.iamge_4);
    list.add(R.drawable.image_6);
    return list;
}
```

and adapter:

```java
@Override
public DataAdapter.ViewHolder onCreateViewHolder(ViewGroup viewGroup, int i) {
    View view = LayoutInflater.from(viewGroup.getContext())
      .inflate(R.layout.recycler_item, viewGroup, false);
    return new ViewHolder(view);
}

@Override
public void onBindViewHolder(DataAdapter.ViewHolder viewHolder, int i) {

    Glide
            .with(context)
            .load(android.get(i))
            .asBitmap()
            .thumbnail(0.1f)
            .diskCacheStrategy(DiskCacheStrategy.ALL)
            .priority(Priority.HIGH)
            .override(133, 133).into(viewHolder.img_android);
}

@Override
public int getItemCount() {
    return android.size();
}

public class ViewHolder extends RecyclerView.ViewHolder {
    private TextView tv_android;
    private ImageView img_android;

    public ViewHolder(View view) {
        super(view);

        img_android = (ImageView) view.findViewById(R.id.img_android);
    }
}
```
note that all images size greater than 5 mb. when i open second activity first time, image take time to load then when again open its loaded so fast. so i want to preload all images on first activity. how is it possible

**Comment by TWiStErRob** [comment]
You didn't do anything in the first activity, you created the request builder, but you didn't actually fire it. You need to call a terminal method: `into`, `downloadOnly`, `preload`! This will solve your SOURCE cache miss.

However, to match images from RESULT cache, you need to match the transformations on the two loads. Assuming you'll use `.downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)` (you still keep `.override()` this size is only used for bucketing), there's no transform applied, while the second load applies a `.fitCenter()` or `.centerCrop()`. This is because `.into()` has some magic code in it, read the method body you're calling.

**Comment by arpitjoshi08** [comment]
i used t his method now in first activity is this fine or not
` Glide
                    .with(context)
                    .load(list.get(i))
                    .asBitmap().skipMemoryCache(false)
                    .cacheDecoder(new FileToStreamDecoder(new StreamBitmapDecoder(context)))
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .override(133, 133)
                    .encoder(new BitmapEncoder(null, 50)).preload();`

**Comment by arpitjoshi08** [comment]
yupp working fine now thanks @TWiStErRob  for help
