### ISSUE TITLE
Whice decoder are you using ?

### ISSUE THREAD

**Issue by partho-maple** [bumptech/glide#1755]
I am trying to write a library like Glide, but using C++ for making it cross-platform. I was wondering which image decoder library/process(Like libjpeg-turbo) did Glide used to decode it's encoded image to create bitmap image ?  Or is it using hardware decoder ? If possible then please describe in details.

Thanks in advance.

**Comment by TWiStErRob** [comment]
See the `Downsampler` class, there's no magic, it's just using the framework's `BitmapFactory`.
