### ISSUE TITLE
Get Bitmap from cache

### ISSUE THREAD

**Issue by yangjieK** [bumptech/glide#1756]
Is there a way to check if a bitmap is already cached? And How to get some cached bitmaps by key

**Comment by TWiStErRob** [comment]
Not possible directly, but if you describe your use case (what **and why**) I can suggest a way to approach it without querying the cache.

**Comment by yangjieK** [comment]
When I did Glide.with(getActivity()).pauseRequests(), I need cached bitmap to bind imageView fristly, but  placeholderDrawable has been bind to imageView before cached bitmap bind to it.
