### ISSUE TITLE
Glide unable to load or took over 60 seconds to load, when YouTube cover image／inaccessible image blocking up coming images 

### ISSUE THREAD

**Issue by susyimes** [bumptech/glide#1759]
**Glide Version**:
  compile 'com.github.bumptech.glide:glide:3.7.0'

**Integration libraries**:
none

**Device/Android Version**:
SONY E6883
SVMSUNG NOTE3 ON5 
XIAOMI  5S
MEIZU NOTE5 MX4 PRO
ALL SAME PROBLEM

**Issue details / Repro steps / Use case background**: 
Location： China Beijing
Problem ：Glide unable to load or took over 60 seconds to load, when YouTube cover image／inaccessible image blocking up coming images. 
 
I’ve uploaded an example, and this test is take place in China, without VPN. While loading oversea src image, 5 YouTube image blocking the next 4 images. And this situation did not occur when I reduce the YouTube image for 5 to 3 (4 up coming image load less than 1 second).
 
This problem often occurred in our application, where it took it long time for image to load. We have 2 types of image in our application (our cdn and image from YouTube)
 
Is there any possibilities for you to tell us how to solve this problem? Many thanks.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
MainActivity:
```java
        img1= (ImageView) findViewById(R.id.img1);
        img2= (ImageView) findViewById(R.id.img2);
        img3= (ImageView) findViewById(R.id.img3);
        img4= (ImageView) findViewById(R.id.img4);
        img5= (ImageView) findViewById(R.id.img5);
        img6= (ImageView) findViewById(R.id.img6);
        img7= (ImageView) findViewById(R.id.img7);
        img8= (ImageView) findViewById(R.id.img8);
        img9= (ImageView) findViewById(R.id.img9);
        Glide.with(getBaseContext()).load("https://i.ytimg.com/vi/n8iBl4soB9c/sddefault.jpg").into(img1);
        Glide.with(getBaseContext()).load("https://i.ytimg.com/vi/YE0pZHXvDpw/mqdefault.jpg").into(img2);
        

Glide.with(getBaseContext()).load("https://i.ytimg.com/vi/YE0pZHXvDpw/maxresdefault.jpg").into(img3);
        Glide.with(getBaseContext()).load("https://i.ytimg.com/vi/Hkclun8J6m8/mqdefault.jpg").into(img5);
        Glide.with(getBaseContext()).load("https://i.ytimg.com/vi/iWEXMkc3QMU/default.jpg").into(img8);
        Glide.with(getBaseContext()).load("http://img.masala-sg.goldenmob.com/img/69c9d815a02d66fd8d4952210268cccd/i_4_article20151236111330041580000-216.webp").into(img4);
        Glide.with(getBaseContext()).load("https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/img/logo_top_ca79a146.png").into(img6);
        Glide.with(getBaseContext()).load("http://img.masala-sg.goldenmob.com/img/10bae98b67a3b1540444092f02e59f0d/i_0_ileana50-216.webp").into(img7);
        Glide.with(getBaseContext()).load("http://img.masala-sg.goldenmob.com/img/69c9d815a02d66fd8d4952210268cccd/i_2_article20151236111112240282000-216.webp").into(img9);
```

**Layout XML**:
```xml
activity_main.xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.susyimes.imageglide.MainActivity"
    >
<ScrollView
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <ImageView
            android:id="@+id/img1"
         android:layout_width="200dp"
         android:layout_height="100dp" />
        <ImageView
            android:id="@+id/img2"
            android:layout_width="200dp"
            android:layout_height="100dp" />
        <ImageView
            android:id="@+id/img3"
            android:layout_width="200dp"
            android:layout_height="100dp" />
        <ImageView
            android:id="@+id/img4"
            android:layout_width="200dp"
            android:layout_height="100dp" />
        <ImageView
            android:id="@+id/img5"
            android:layout_width="200dp"
            android:layout_height="100dp" />
        <ImageView
            android:id="@+id/img6"
            android:layout_width="200dp"
            android:layout_height="100dp" />
        <ImageView
            android:id="@+id/img7"
            android:layout_width="200dp"
            android:layout_height="100dp" />
        <ImageView
            android:id="@+id/img8"
            android:layout_width="200dp"
            android:layout_height="100dp" />
        <ImageView
            android:id="@+id/img9"
            android:layout_width="200dp"
            android:layout_height="100dp" />


    </LinearLayout>
</ScrollView>
</RelativeLayout>
```

What is the error message that you got in the log?
no error just stop load, block glide's nomarl work

**Comment by TWiStErRob** [comment]
60 seconds is a lot, do you have timeouts configured? The default is [2.5 seconds](https://github.com/bumptech/glide/blob/e0e00745549443a1a6e6392bb501b99223f9b4dd/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java#L66-L67), so it should fail really quickly. Is it possible that the image blocker may be dripping you some bytes from time to time (within read timeout)? Consider configuring an OkHttp to see if the behavior changes... with that you can also configure timeouts more easily.

The blocking: your device probably allows Glide to set up 4 threads in the pool which means 4 parallel in-flight requests. If the 4 requests don't fail or time out, then they'll stay there long, blocking the next ones. This is expected behavior and the only way around it is to make sure the requests fail fast. I don't have enough tech details about the image blocking to help you out more.

**Comment by susyimes** [comment]
hanks a lot, I had try to use GlideModule, to set connnectiontimeout to less than 2500 milliseconds, block never happen. but i worry about connectiontimeout duration is too short , when user have bad networkstate , then will loadfaild many image. 
maybe...to avoid that, should i use an Intercepter to redifine retry count ?

```java
public class SusGlideModule implements GlideModule {
    @Override public void applyOptions(Context context, GlideBuilder builder) {

    }



    @Override public void registerComponents(Context context, Glide glide) {


        OkHttpClient.Builder client = new OkHttpClient.Builder()
                .retryOnConnectionFailure(true)
                .connectTimeout(500, TimeUnit.MILLISECONDS)
                .readTimeout(10000, TimeUnit.MILLISECONDS)
                .writeTimeout(10000, TimeUnit.MILLISECONDS);


        OkHttpUrlLoader.Factory factory=new OkHttpUrlLoader.Factory(client.build());

        glide.register(GlideUrl.class, InputStream.class, factory);
    }
}

```

**Comment by TWiStErRob** [comment]
It really depends on your users, use case, images and server. `500` seems too small: if you're on 3G, a simple roundtrip may take longer.
Tip: you only need `writeTimeout` if you do POST
