### ISSUE TITLE
Loading images from cache (I think)

### ISSUE THREAD

**Issue by MostafaEbrahimi** [bumptech/glide#1760]
Hi.
When I use Glide with recyclerview .When I run my app on my device for first time (Using android studio) images loaded correctly but after press back and finish app then open app again images not load and I must click on cards(Click on card opens new activity) to load display images (it seems images cached but not load)
I enable all type of debug logging but don't get any of exception or error

`Glide version 'com.github.bumptech.glide:glide:3.7.0'`

`Glide.with(mContext)
                    .load(Uri.parse(image.getImage_url()))
                    .diskCacheStrategy(DiskCacheStrategy.RESULT)
                    .into(holder.image);`
This code in recyclerview adapter

I Think The Problem is by size of image and glide cache :(

You can see my code in [stackoverflow](http://stackoverflow.com/questions/42509670/loading-images-from-cache-glide/42509990?noredirect=1)

**Comment by MostafaEbrahimi** [comment]
any idea how to solve this problem?!?

**Comment by TWiStErRob** [comment]
Didn't see anything obvious, I would need to fully repro it.
You can try adding this advanced listeners to see what's going on with the load:
https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/utils/LoggingListener.java
https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/utils/LoggingTarget.java

So your load changes to:
```java
...
.listener(new LoggingListener<Uri, GlideDrawable>())
.into(new LoggingTarget<GlideDrawable>(new GlideDrawableImageViewTarget(holder.image)))
;
```

One thing might worth checking: is the view visible when you call Glide on it?

**Comment by MostafaEbrahimi** [comment]
No visible.After a lot of test i found that changing form `glide.with(MainActivity.this)` to `glide.with(getApplicationContext())` solve the problem.[ I create 3 new project :((((  ]

**Comment by TWiStErRob** [comment]
Hmm... that gives a clue.
I think you may be binding the images in the wrong lifew cycle. If the activity is destroyed all glide loads are cleared. So check what life cycle callbacks are called on first load and what happens when it doesn't work. It's possible you Glide lines are not executed.

**Comment by MostafaEbrahimi** [comment]
I logged and check all type of loggings.I found that in second lunch of app (Lunch with android studio then close and open again) images not appear and in debugging mode can not reach to lines in glide listener on method `onReadyresource()` but when clicked on a single card of images placeholder suddenly all of images  appear . A difficult problem :)))

**Comment by TWiStErRob** [comment]
What did you mean when you said "No visible."? "Not visible", or "No, visible"?

**Comment by Comori** [comment]
@TWiStErRob see #1767 ，Can I do that?

**Comment by MostafaEbrahimi** [comment]
@TWiStErRob The view is visible.
