### ISSUE TITLE
Compiled 9-patch images not loading correctly the first time

### ISSUE THREAD

**Issue by zlippard** [bumptech/glide#1766]
**Glide Version**: 3.7.0

**Integration libraries**: okhttp-1.4

**Device/Android Version**: Nexus 5X, Nexus 6, Pixel

**Issue details / Repro steps / Use case background**: 

I am attempting to download an image, which may or may not be a compiled 9-patch, over the network into a bitmap target.  `Once onResourceReady()` is called on the target, I inspect the bitmap's 9-patch chunk data to determine if the image is indeed a compiled 9-patch.  If the image is a compiled 9-patch, the first time the image is downloaded, the chunk data is null, however consecutive requests for the image (once it's cached) returns the chunk data.  It almost seems like there's extra processing on the bitmap after it's cached but before it's returned in `onResourceReady()`.

One thing to note is I have to use the SOURCE disk cache strategy in order to ever get the chunk data.  It appears that the default strategy, due to resizing the image, loses the chunk data.

```
SimpleTarget<Bitmap> target = new SimpleTarget<Bitmap>(){
    @Override
    public void onResourceReady(Bitmap bitmap, GlideAnimation< ? super Bitmap > glideAnimation){
        byte[] chunk = bitmap.getNinePatchChunk();

        // Detect 9-patch chunk
        if( chunk == null ){
            // Not a 9-patch image, load as regular bitmap
        } else { // 9-patch compiled image found
            // Do 9-patchy things here
        }
    }
};

Glide.with( imageLoaderBitmapTarget.getTargetContext() )
    .load( imageUrl )
    .asBitmap()
    .diskCacheStrategy( DiskCacheStrategy.SOURCE )
    .into( target );
```

**Comment by zlippard** [comment]
I was able to work around this issue by supplying my own cache decoder for Glide.  It seems the problem resides in the downsampler when it attempts to decode the bitmap from a stream (`BitmapFactory.decodeStream(is, null, options)`).  It appears that when a recyclable bitmap is placed in the inBitmap property of the `options` object, the nine patch chunk comes back is returned with a null value.  This may actually be an issue with BitmapFactory's decodeStream method, but I was unable to reproduce it when attempting to supply an Options object with a recycled bitmap myself.

Here's the code that works for me, albeit it bypasses the bitmap pool for recycling bitmaps:

```
private static ResourceDecoder<File, Bitmap> bitmapCacheDecoder = new ResourceDecoder<File, Bitmap>() {
    @Override
    public Resource<Bitmap> decode(File source, int width, int height) throws IOException {
        final Bitmap bitmap = BitmapFactory.decodeFile(source);
        return new Resource<Bitmap>() {
            @Override
            public Bitmap get() {
                return bitmap;
            }

            @Override
            public int getSize() {
                return bitmap.getByteCount();
            }

            @Override
            public void recycle() {
                bitmap.recycle();
            }
        };
    }

    @Override
    public String getId() {
        return "ImageLoaderHelper.bitmapCacheDecoder";
    }
};

SimpleTarget<Bitmap> target = new SimpleTarget<Bitmap>(){
    @Override
    public void onResourceReady(Bitmap bitmap, GlideAnimation< ? super Bitmap > glideAnimation){
        byte[] chunk = bitmap.getNinePatchChunk();

        // Detect 9-patch chunk
        if( chunk == null ){
            // Not a 9-patch image, load as regular bitmap
        } else { // 9-patch compiled image found
            // Do 9-patchy things here
        }
    }
};

Glide.with( imageLoaderBitmapTarget.getTargetContext() )
    .load( imageUrl )
    .asBitmap()
    .cacheDecoder( bitmapCacheDecoder )
    .diskCacheStrategy( DiskCacheStrategy.SOURCE )
    .into( target );
```

**Comment by weizaishouex2010** [comment]
do you know how to resolve this in Glide 4.x
