### ISSUE TITLE
Cache problem: does HTTP cache-control header work in Glide?

### ISSUE THREAD

**Issue by enginebai** [bumptech/glide#1768]
Hi, my app provides user to upload avatar, and server side use `cache-control: max-age=600, public` to control cache. 

<img width="347" alt="2017-03-03 3 23 58" src="https://cloud.githubusercontent.com/assets/3387462/23541960/7ea8f58e-0025-11e7-87a1-290e50424b03.png">

My problem is that after uploading the image, the glide still load the cached image, and I use browser to open the image, it's updated. Does glide support `cache-control` header? Or how can I control cache in this way?

Here is my code to load image, I use `signature()` api but doesn't work.

```java
Glide.with(getActivity())
		.load(mUser.getCoverPhoto())
		.error(R.drawable.bg_1)
		.signature(new StringSignature(String.valueOf(System.currentTimeMillis())))
		.listener(new RequestListener<String, GlideDrawable>() {
			@Override
			public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
				mTextBioOther.setVisibility(!isMe ? View.VISIBLE : View.GONE);
				return false;
			}

			@Override
			public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
				mTextBioOther.setVisibility(!isMe ? View.VISIBLE : View.GONE);
				return false;
			}
		})
		.into(mImageCover);
```

**Comment by enginebai** [comment]
I fixed the problem by providing `signature(new StringSignature(String.valueOf(System.currentTimeMillis() / (1000 * 60 * 10))))`.

**Comment by TWiStErRob** [comment]
Sorry for the silence, yes, Glide doesn't support it out of the box.
You can get OkHttp to do the caching and invalidation based on headers for you, but then you have to disable Glide cache (`.diskCacheStrategy(NONE)`).

**Comment by enginebai** [comment]
OK, thanks for your kindly help.

**Comment by platinum7919** [comment]
Will volley work also? I am currently using volley and I don't want to add okhttp.

**Comment by TWiStErRob** [comment]
@platinum7919 sure, if you know how to configure it to handle these headers. It doesn't matter what you use as long as you can configure it correctly.

**Comment by kavinmk6** [comment]
> I fixed the problem by providing `signature(new StringSignature(String.valueOf(System.currentTimeMillis() / (1000 * 60 * 10))))`.

Hi, Thanks for the solution. In My case I need to set the cache for 3,628,800 seconds. May I know how can I set the calculation for this? Thanks

**Comment by TWiStErRob** [comment]
@kavinmk6 The example is 10 minutes (600 seconds).
