### ISSUE TITLE
Question: Is this hack for loading progress good?

### ISSUE THREAD

**Issue by yudhir** [bumptech/glide#1769]
http://stackoverflow.com/a/42116017/4645947

 ```
   Glide.with(ctx)
            .load(url)
            .thumbnail(Glide.with(ctx).load(R.drawable.progressbargif))
            .diskCacheStrategy(DiskCacheStrategy.SOURCE)
            .error(R.drawable.image_unavailable)
            .crossFade(200)
            .into(iv);
```

**Comment by TWiStErRob** [comment]
I would suggest using the 90 times up-voted answer instead of a down-voted one. See my new comment on the down-voted answer.

**Comment by yudhir** [comment]
Thanks for the answer .
that Looked elegant LoL . its Using Glide call inside Glide builder  too.

**Comment by TWiStErRob** [comment]
Yeah it looks elegant, but it's a hack with too many drawbacks to use a thumbnail when you want to show a synchronous placeholder.
