### ISSUE TITLE
duplicate entry: com/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider.class

### ISSUE THREAD

**Issue by kyungkeun** [bumptech/glide#1772]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by kyungkeun** [comment]
maybe another module also ues this class but, I can't it.

**Comment by TWiStErRob** [comment]
Please provide more info about what you're doing, why and how.
