### ISSUE TITLE
Glide.clear() is bad for unit testing

### ISSUE THREAD

**Issue by danielesegato** [bumptech/glide#1774]
A typical code for rendering an item would look something like this:

```java
@Override
public void bind(MyViewHolder holder, MyModel model) {
    String imageUrl = model.image();
    if (imageUrl != null) {
        DrawableTypeRequest<String> load = glide.load(imageUrl)
            .into(holder.image());
    } else {
        Glide.clear(holder.image());
    }
}
```

the `glide` in he code here is actually a `RequestManager` and I can easily inject it in my adapter and mock it. But How am I supposed to test my bind method is calling `Glide.clear()`? It is static and I cannot inject it because of that.

I know I can write a wrapper but this shouldn't be needed.

Wouldn't be better if clear could be part of `RequestManager` and `Glide.clear` just a shortcut to it?

**Comment by TWiStErRob** [comment]
Do you mean you want it to be like [this](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/RequestManager.java#L382-L419)? I guess you can backport https://github.com/bumptech/glide/commit/7858f3ce3bdb368fa836c4c98e26da5f71585979 if you don't want to upgrade to v4.

**Comment by danielesegato** [comment]
I'm confused, I'm running `'com.github.bumptech.glide:glide:3.7.0'` isn't this the last version?

I can't see any tag after that in this repository.
And that version doesn't have the method clear in the `RequestManager`.

**Comment by TWiStErRob** [comment]
3.7.0 latest released, 3.8.0 is latest from that code (`3.0` branch), but there's also a v4 in the works (`master` branch): https://github.com/bumptech/glide/wiki/Snapshots

**Comment by danielesegato** [comment]
I've seen the branch but I think I'll wait for the actual release before adopting it :) thank you!

**Comment by danielesegato** [comment]
Oh let me clarify: I'm ok backporting that commit, it's just a cherry-pick probably... It's just I do not want to depend on a fork :-) but if you are going to include the backport in v3 and release a new version I'll happily work on it

**Comment by TWiStErRob** [comment]
"just a cherry-pick" is usually more, let's see what @sjudd says about your query.

**Comment by sjudd** [comment]
This is fixed in v4, but we're not planning on backporting anything to v3.
