### ISSUE TITLE
DiskLruCache memory consumption

### ISSUE THREAD

**Issue by korniltsev** [bumptech/glide#1776]
**Glide Version**:3.7.0

**Integration libraries**:no

**Device/Android Version**: Samsung SM-T116, but does not matter

**Issue details / Repro steps / Use case background**: 
We found DiskLruCache#lruEntries can take quite a lot of memory. 
For example we got OOM with 40k entries in it, and it takes ~39Mb (See screenshot below). 
DiskLruCache.Entry is 742 bytes (average. see screenshot number 2) and 360 of them are "memoized" DiskLruCache.Entry#cleanFiles,dirtyFiles.
In order to lower memory footprint and decrease amount of OOM, we decreased the disk cache size.
However I would like to be able to disable memoization in DiskLruCache.Entry#cleanFiles,dirtyFiles, or make memoization lazy. i.e. make the optimization optional, and configurable at runtime. 
Note: original https://github.com/JakeWharton/DiskLruCache has no memoization and keeps much fewer memory.  
What do you think about that change? If you think this is a good idea I can work on PR.

I've attached the heapdump and a screenshot of it to demonstrate the problem
The heapdump https://monosnap.com/file/rMBGyNAWjFQQ7Q9oDZuqnuU6B25sD1

DiskLruCache
![java visualvm 2017-03-09 13-37-13](https://cloud.githubusercontent.com/assets/331773/23748174/8471333e-04d3-11e7-97ec-22d3ca84742c.png)
DiskLruCache$Entry
![2017-03-09 15 29 43](https://cloud.githubusercontent.com/assets/331773/23750389/c9351c9c-04dd-11e7-9eab-369da24aac56.png)

**Comment by TWiStErRob** [comment]
Interesting, do you have 40k items in the cache? Is that normal?

I ran this OQL query on your dump:
```java
SELECT s.toString(), s.@retainedHeapSize FROM java.lang.String s WHERE s.toString().startsWith("/data/data/ru.ok.live/cache/image_manager_disk_cache/")
```
and it shows that there are 80k ~284 long strings: adding up to 22MBs.

**Comment by korniltsev** [comment]
I don't know if the crashed app has 40k files in the cache. The dumps are all I have (there are many of them).
I've just checked the average size of cached file on mdpi device and it is 15kb. It is about 17k entries in 250Mb cache. It is not 40k, but it is still huge.

**Comment by NiaNingXue** [comment]
I find the same issue, the LruDiskCache keep big memory

**Comment by korniltsev** [comment]
I will close because we fixed it internally long time ago
