### ISSUE TITLE
Wrong image shown in list first time. Scrolling shows right image

### ISSUE THREAD

**Issue by raghunandankavi2010** [bumptech/glide#1782]
I use a listview. In getview
```java
      if(feedItems.get(position).getUser_details()!=null) {
            Glide.with(activity).load(feedItems.get(position).getUser_details().getUser_profile_image())
                    .asBitmap().centerCrop()
                    .placeholder(R.drawable.pod_h)
                    .into(new BitmapImageViewTarget(viewHolder.profilePic) {
                        @Override
                        protected void setResource(Bitmap resource) {
                            RoundedBitmapDrawable circularBitmapDrawable =
                                    RoundedBitmapDrawableFactory.create(activity.getResources(), resource);
                            circularBitmapDrawable.setCircular(true);
                            viewHolder.profilePic.setImageDrawable(circularBitmapDrawable);
                        }
                    });
        }else
        {
            // make sure Glide doesn't load anything into this view until told otherwise
            Glide.clear(viewHolder.profilePic);
            // remove the placeholder (optional); read comments below
            viewHolder.profilePic.setImageDrawable(null);
           }
```

I see that at the start the wrong image is displayed in the wrong position. May be the cached one. On scrolling the right image is displayed. I m not sure what is happening. 

But i did try searching similar issues on stackoverflow http://stackoverflow.com/questions/32706246/recyclerview-adapter-and-glide-same-image-every-4-5-rows and followed the suggestion there.

![screenshot_20170311-132205](https://cloud.githubusercontent.com/assets/4216745/23821896/f4c28230-0665-11e7-9bec-b44120723509.png)

Wrong image shown

![screenshot_20170311-132107](https://cloud.githubusercontent.com/assets/4216745/23821916/49c7ef40-0666-11e7-8eb1-7bb1adbc431b.png)

I can reproduce this whenever i close the app clear from recents and open the above screen again. So i suspect this could be wrong image cached and displayed at the start.

**Comment by raghunandankavi2010** [comment]
After going through other issues i removed this new BitmapImageViewTarget(viewHolder.profilePic) { looking at https://github.com/bumptech/glide/issues/1376 comment from TWiStErRob.

**Comment by raghunandankavi2010** [comment]
Ok. using transformations instead of the above code seems to solve the problem.  I will wait till author confirms and author can close this issue.

**Comment by TWiStErRob** [comment]
I see a few possibilities why this was wrong, but didn't share enough code to confirm:
* the viewHolder might be a field instead of a final local car,  which means because of Glide's async behavior the field changes while Glide decodes. After scrolling image is from memory cache and at that point you get the ready callback by the time into() returns.
* combined with above, I'm  assuming that the robot icon is your placeholder, so you can only observe one load completion: last async load completed into the last item bound, everything else stays placeholder.

Tip: you can close your own issues.

**Comment by raghunandankavi2010** [comment]
yup. ViewHolder code

        if (convertView == null) {
            viewHolder = new ViewHolder();


Sorry i should have gone through the documentation first. Seems i also used CircularImageView.
