### ISSUE TITLE
is there any flag or function for on loading image and failed loading image

### ISSUE THREAD

**Issue by AAHB** [bumptech/glide#1783]
hi there
I want to load some images
but I want to show an gif when the image is not loaded...
or when the image has some issue in loading (e.g. not connecting to the internet or full memory) show another gif image from my project files
so here is the question
Is there any function or flag that specify the states  like "loading started" or "loading failed" ?
thanks and good luck!

**Comment by TWiStErRob** [comment]
`.listener()` is for listening for completion, so:
```java
String model = "<url>";
Log.i("Loading started: " + model);
Glide
	.with(this)
	.load(model)
	.listener(new RequestListener<String, GlideDrawable>() {
		public boolean onResourceReady(R resource, T model, Target<R> target, boolean isFromMemCache, boolean isFirst) {
			Log.i("Loading finished: " + model);
			return false;
		}
		public boolean onException(Exception e, T model, Target<R> target, boolean isFirstResource) {
			Log.i("Loading failed: " + model, e); // e may be null
			return false;
		}
	})
	.into(imageView);
```

If you want more fine-grained notifications, look into custom targets; however they're more advanced and less documented. It's easy to leak stuff if you're not careful.
