### ISSUE TITLE
when I using this methodw: ViewTarget.setTagId(R.id.glide_tag_id);，it caused some problem ...

### ISSUE THREAD

**Issue by my-sunshine** [bumptech/glide#1784]
when I using this method as bellow：

ViewTarget.setTagId(R.id.glide_tag_id);

it caused some problem ：

java.lang.NoSuchMethodError
No static method setTagId(I)V in class Lcom/bumptech/glide/request/target/ViewTarget; or its super classes (declaration of 'com.bumptech.glide.request.target.ViewTarget' appears in /data/data/XXX/tinker/patch-6a269f69/dex/classes.dex.jar)

how to solved this problem？

thank you

**Comment by TWiStErRob** [comment]
multidex? did you try a clean build?

**Comment by my-sunshine** [comment]
maybe not...
I immediate run 'assembleRelease',and then publish it to app store...

this problem occurred only once:when the user first into the app.the user`s rom is Oppo/COLOROS,version is Android 5.1.In my app,I added  'tinker'(third party) to monitor crash.why 'No static method setTagId...'happened?

**Comment by my-sunshine** [comment]
I had not clean build,will it matter?
