### ISSUE TITLE
get cache file or bitmap on UI thread

### ISSUE THREAD

**Issue by bylijian** [bumptech/glide#1785]
Hi, I must get  cache file or bitmap on Ui thread which has been cached,but ,when I use
```java
File file = Glide.with(context.getApplicationContext())
                        .load(url)
                        .downloadOnly(width, height)
                        .get();
```
It will throw error ,because the source code will use this:
```java
    /**
     * Throws an {@link java.lang.IllegalArgumentException} if called on the main thread.
     */
    public static void assertBackgroundThread() {
        if (!isOnBackgroundThread()) {
            throw new IllegalArgumentException("YOu must call this method on a background thread");
        }
    }
```
I want to know how can I avoid this ? Or ,if I have an url of  a image, how can I get it's cache in DiskCache on UI thread.
Thanks .

**Comment by TWiStErRob** [comment]
The point of that check is to prevent bad practices. The one you're trying to do is so bad, they created a named exception for it: https://developer.android.com/reference/android/os/NetworkOnMainThreadException.html

> I must get cache file or bitmap on Ui thread which has been cached

Can you please explain the "must", and why? I think we're looking at an [X-Y problem](http://xyproblem.info/).

**Comment by bylijian** [comment]
I need to use Bitmap of an Image from Server to do some animation .Because the image is an item of a ListView ,I don't want to save and recycle bitmap by myself or create my Bitmap Pool to save all bitmaps. I think the best way is get it from Glide cache but not network with it's url .if it's null,I will use a default image to do animation. I know that we should not do something heavy on UI thread. Do you have some other ideas ?

**Comment by bylijian** [comment]
I try this way to solve my problem ,just get the bitmap form that ImageView using View.getDrawingCache(),
but I really want to know that Is there any method to get bitmap if the image has been cached by Glide.
