### ISSUE TITLE
How to load gif with DiskCacheStrategy.SOURCE and load jpg(or png) with DiskCacheStrategy.RESULT

### ISSUE THREAD

**Issue by Drizzlezhang** [bumptech/glide#1787]
Hi, Glide is an useful tool to load gif in android, but if I can't get the type of file(gif or others) from url , how can I load gif with DiskCacheStrategy.SOURCE and load jpg(or png) with DiskCacheStrategy.RESULT? If I use other DiskCacheStrategy , Glide can't load gif normally, and if I use DiskCacheStrategy.SOURCE to load jpg, maybe will waste cache space and load image slowly.

**Comment by TWiStErRob** [comment]
You need to store the builder in a variable and add the strategy conditionally. (e.g. based on url file name ending)
