### ISSUE TITLE
Error:(1, 0) Gradle sync failed: Process 'command 'git'' finished with non-zero exit value 128

### ISSUE THREAD

**Issue by roy46320856** [bumptech/glide#1788]
new-- import project
Gradle sync failed: Process 'command 'git'' finished with non-zero exit value 128
Error:(1, 0) Process 'command 'git'' finished with non-zero exit value 128 <a href="openFile:F:\WorkspaceForAndroidStudio\glide-master\settings.gradle">Open File</a>
what‘s wrong ？who can help me？ Thanks  a  lot .

**Comment by TWiStErRob** [comment]
First get a successful build from the command line, if that happened, only then start importing into IDEA, see https://github.com/bumptech/glide#development:

> Follow the steps in the Build section to setup the project *and then*

**Comment by roy46320856** [comment]
Thanks，but the problem was not solved。

**Comment by TWiStErRob** [comment]
Did you get a successful command line build? Do you have `git` on your path?

See also #1283, http://stackoverflow.com/a/35941193/253468, and http://stackoverflow.com/a/36333284/253468

**Comment by roy46320856** [comment]
Thank you very much,the problem has been solved,the reason is that the version is inconsistent,Can not be updated to the latest version.
but, after rebuilding,show a lot of information about"Error:(200, 14) 警告: [deprecation] Options中的inDither已过时""Error:(402, 38) 警告: [deprecation] RequestBuilder中的load(URL)已过时
其中, TranscodeType是类型变量:
TranscodeType扩展已在类 RequestBuilder中声明的Object",“”Error:(164, 15) 警告: [deprecation] Fragment中的onAttach(Activity)已过时“”The source code is not really using outdated code？
Thanks a lot.

**Comment by roy46320856** [comment]
Thank you very much,the problem has been solved,the reason is that the version is inconsistent,Can not be updated to the latest version.
but, after rebuilding,show a lot of informations about"Error:(200, 14) 警告: [deprecation] Options中的inDither已过时""Error:(402, 38) 警告: [deprecation] RequestBuilder中的load(URL)已过时
其中, TranscodeType是类型变量:
TranscodeType扩展已在类 RequestBuilder中声明的Object",“”Error:(164, 15) 警告: [deprecation] Fragment中的onAttach(Activity)已过时“”Isn't the source code really using outdated code？ Is this normal ？
Thanks a lot.

**Comment by TWiStErRob** [comment]
There are some deprecated API usage, because Glide also works on old API versions. I use it in my app with minSdk=10 to load SVGs.

**Comment by roy46320856** [comment]
Thank you for patient guidance !

**Comment by hoooou** [comment]
I also encountered this problem,This problem can be solved
VCS->Enable Control Integration->Select "Git"

**Comment by kangdawei** [comment]
thanks @hoooou

**Comment by kangdawei** [comment]
new problem


Could not get unknown property 'sourceSets' for project ':third_party:disklrucache' of type org.gradle.api.Project. Open File

**Comment by TWiStErRob** [comment]
@kangdawei which branch? Did you follow the setup instructions from the branch's Readme?
