### ISSUE TITLE
Problem with SimpleTarget and GlideAnimation

### ISSUE THREAD

**Issue by BottleChain** [bumptech/glide#1789]
hi , I'm using Glide 3.8.0-SNAPSHOT，my question is simple, I'm using a SimpleTarget like this:

```bash
target = new SimpleTarget<Drawable>() {
                @Override
                public void onResourceReady(Drawable drawable, GlideAnimation<? super Drawable> glideAnimation) {
                    if (imageView != null && drawable != null) {
                        Bitmap bitmap = getBitmap(drawable);
                        if (bitmap != null)
                            imageView.setImageBitmap(bitmap);
                    }
                }
            }

// and use like this:
Glide.with(context)...  .into(target)

```

and i set an animateFactory like this before:

```bash
drawableRequestBuilder.animate(new PaddingAnimationFactory<>(new DrawableCrossFadeFactory<GlideDrawable>(500)));
```

but when comes to the onResourceReady method, i found that the animation is lost, so how can i use the GlideAnimation<? super Drawable> glideAnimation to let the animation run normally? 

Thanks a lot !

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/blob/e0e00745549443a1a6e6392bb501b99223f9b4dd/library/src/main/java/com/bumptech/glide/request/target/ImageViewTarget.java#L75-L77

but I think you're taking the wrong approach (based on what I see from your code).
I think you're looking for this:
```
Glide.with(context)
.load(blah)
.asBitmap()
.transform(new CenterCrop(context), new PaddingTransformation())
.into(imageView);
```
You need to write `PaddingTransformation` yourself: extend `BitmapTransformation`, see for example: https://github.com/wasabeef/glide-transformations/blob/master/transformations/src/main/java/jp/wasabeef/glide/transformations/CropSquareTransformation.java#L46-L54 (not the lines not highlighted are not needed, `BitmapTransformation` takes that burden off you)

**Comment by BottleChain** [comment]
Perfectly solved my problem, lots of thks!
