### ISSUE TITLE
Is it possible to load bitmap from byteArray and cache it?

### ISSUE THREAD

**Issue by ashwinkhadgi** [bumptech/glide#1791]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
No, it's pointless. Have thought about this a lot trying to find workarounds and stuff.

For example: How are you proposing to access it again? The cache key is the model that you use to `load()` it. Now, to access the cache you need the `byte[]`, but if you have the full `byte[]` in memory already what's the point of caching?

That being said if you feel like hacking, see https://github.com/bumptech/glide/issues/906
