### ISSUE TITLE
加载图片闪烁，有遇到的么

### ISSUE THREAD

**Issue by liupeng110** [bumptech/glide#1792]
rt

**Comment by liupeng110** [comment]
如何让他不闪烁 ：
 Glide.with(this).load("file:///android_asset/d_3_z.jpg").dontAnimate().into(layout_background);

**Comment by bylijian** [comment]
Glide.with(this).load("file:///android_asset/d_3_z.jpg").into(layout_background);

**Comment by liupeng110** [comment]
@bylijian 
没用，一开始就是用的你这种默认的加载方式  会闪烁

**Comment by TWiStErRob** [comment]
What kind of flicker do you get? Can you do an `adb screenrecord`?

**Comment by airtayork** [comment]
I has the flicker too when GC occurs.

**Comment by liupeng110** [comment]
Find the reason,I rewrote these functions in BaseActivity :
 
@Override
    protected void onCreate(Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
        L.i("base-onCreate");
       Glide.get(this).clearMemoryCache();  
  }

or

  @Override
    protected void onDestroy() {
   super.onDestroy(); 
}

**Comment by CyoClound** [comment]
@TWiStErRob 我的ListView中图片滑动时也是显示错乱
![screenshot_2017-04-10-11-16-12-814_com mdsd telec](https://cloud.githubusercontent.com/assets/11866354/24844718/4035025c-1ddf-11e7-83ba-8da91b949d90.png)
![screenshot_2017-04-10-11-16-25-366_com mdsd telec](https://cloud.githubusercontent.com/assets/11866354/24844740/6820574e-1ddf-11e7-859f-0ca8dc860dfa.png)


public View getView(int position, View convertView, ViewGroup parent) {
        View view;
        if(convertView==null){
            LayoutInflater inflater=LayoutInflater.from(context);
            view=inflater.inflate(R.layout.listview_experts,parent,false);
        }else{
            view=convertView;
        }
        TextView textView1=(TextView) view.findViewById(R.id.textView1);
        TextView textView2=(TextView) view.findViewById(R.id.textView2);

        imageView=(ImageView) view.findViewById(R.id.imageView1);
        if(listExpertsBean.getData().getList().get(position).getIMAGE_PATH()!=null){
            imagePath=listExpertsBean.getData().getList().get(position).getIMAGE_PATH().toString();
            Glide.with(context).load(Constants.BASE_URL + imagePath).centerCrop().placeholder(R.mipmap.ic_launcher).into(imageView);
        }

        String username=listExpertsBean.getData().getList().get(position).getUSER_NAME();
        String sex=listExpertsBean.getData().getList().get(position).getUSER_SEX_STR();
        textView1.setText(username+"|"+ sex);
        //TODO:
        return view;
    }

**Comment by liupeng110** [comment]
我是用viewpager时候闪烁，错乱应该不会吧  
我又换回了imageloader  现在没问题了

**Comment by CyoClound** [comment]
@liupeng110 我是用的listView,你可以看到两个图片中第一条数据图片是错乱的，有时显示正常，有时显示就错误了

**Comment by liupeng110** [comment]
@CyoClound  你代码有问题 

 if (convertView == null) {
                convertView = View.inflate(context, R.layout.item_foot, null);
                convertView.setLayoutParams(new GridView.LayoutParams(w, h));
                mHolder = new ViewHolder();
                mHolder.mIvAdd = (ImageView) convertView.findViewById(R.id.video_iv_add);
                mHolder.mRlAdd = (RelativeLayout) convertView.findViewById(R.id.rl_add_foot);
                mHolder.mMPbAdd = (ProgressBar) convertView.findViewById(R.id.loadmore_myfilm_footer_pb);
                convertView.setTag(mHolder);  
            } else {
                mHolder = (ViewHolder) convertView.getTag();
            }

**Comment by CyoClound** [comment]
@liupeng110 看不出重点和区别在哪里

**Comment by TWiStErRob** [comment]
@CyoClound don't speak Chinese, but I think your problem will be solved with this code:
```java
// don't use Object fields to store temporary data, use local variables!
SomeExpertObject expert = listExpertsBean.getData().getList().get(position); // extracted this variable, notice how much cleaner the code becomes
ImageView imageView = (ImageView) view.findViewById(R.id.imageView1); // make this local, not a field!
if (expert.getIMAGE_PATH() != null) {
	Glide
		.with(context)
		.load(Constants.BASE_URL + expert.getIMAGE_PATH())
		.centerCrop()
		.placeholder(R.mipmap.ic_launcher)
		.into(imageView);
} else {
	// need to remove the old binding because you're reusing the view of the list item
	// if you don't clear, the previously displayed image in this item will be visible (as per screenshot)
	Glide.clear(imageView);
}
String username = expert.getUSER_NAME();
String sex = expert.getUSER_SEX_STR();
```

Also @liupeng110 is telling you to use the ViewHolder pattern instead of using `.findViewById()` every single time, look up some tutorials on it for more info and why it's used. It's a really useful and kind of mandatory pattern if you develop Android ListView/RecyclerViews.

**Comment by CyoClound** [comment]
The problem has been solved, thank you very much for your detailed explanation @TWiStErRob ，同时也非常感谢 @liupeng110 ，么么哒😊
