### ISSUE TITLE
Android 7.0 image loading issue?!

### ISSUE THREAD

**Issue by vulko** [bumptech/glide#1793]
Hello, I'm trying to use Glide for loading images in background and storing them in LruCache, but I keep failing to load all the time with the following exception:

**Exception is java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA of type java.util.concurrent.ExecutionException**

Also, I think it's somehow connected with the fact that I'm using Android N (api 25), which seems to be failing to load images with BitmapFactory as well, with the same exception. On stackoverflow some ppl say that it's some C++ code changes in native layer, that produced this issue.

Here's the code:

```
        @Override
        protected Void doInBackground(Void... params) {
            final int imageSize = CachingController.getInstance().getPrefferedCachingSize();
            try {
                FutureTarget<GlideDrawable> futureDrawable = Glide.with(mContext)
                        .load(mPath)
                        .diskCacheStrategy(DiskCacheStrategy.RESULT)
                        .into(imageSize, imageSize);
                GlideDrawable drawable = futureDrawable.get(30, TimeUnit.SECONDS);
                mLoadedDrawable = new WeakReference<Drawable>(drawable);
            } catch (InterruptedException e) {
                Log.e(getClass().getName(), "Failed to wait for image to get loaded! Path = " + mPath);
            } catch (ExecutionException e) {
                Log.e(getClass().getName(), "Failed to wait for image to get loaded! Path = " + mPath);
            } catch (TimeoutException e) {
                Log.e(getClass().getName(), "Failed to wait for image to get loaded! Path = " + mPath);
            }

            return null;
        }

```

**Comment by sjudd** [comment]
Can you attach a sample image that fails?

**Comment by vulko** [comment]
Basically most images fail. I don't know why, but it works rarely for instagram folder, but otherwise the images can't be loaded. I've tried running max 2 simultaneous AsyncTasks at the same time, that call load, but the same result as with more.

Could it be a Nougat issue?

**Comment by TWiStErRob** [comment]
Can you share a bit more of stack trace? Is it the file descriptor fetcher that fails?

**Comment by vulko** [comment]
Well, I get this:
java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA

And the very same thing I get if I try to use BitmapFactory for loading bitmaps.
It used to work, but after some update it stopped. I've bumped on the same issue of loading bitmaps from local storage on stackoverflow.

**Comment by BongJaeChoi** [comment]
Ref. Nougat. Can't use file:/// Uri
https://developer.android.com/about/versions/nougat/android-7.0-changes.html?#sharing-files

**Comment by vulko** [comment]
I'm using File.getPath, which doesn't contain "file://" prefix.

**Comment by vulko** [comment]
And also if it helps, my device is Sony Xperia X Compact with 7.0.

**Comment by vulko** [comment]
I'm just really curious, is it just me having this issue, or is just everybody not yet caring about Android N? :)

**Comment by TWiStErRob** [comment]
> I'm using File.getPath, which doesn't contain "file://" prefix.

Yes it does. `.load((File)file)` and `.load((String)path)` both lead to `Uri.fromFile()`, check `StringLoader` and `FileLoader`.

So I think the question is: what's wrong with your file. I tried `adb push local.jpg /sdcard/Download/` on a Nougat emulator and Glide had no problem loading it as `.load("/sdcard/Download/local.jpg")`.

Please share your `mPath` variable contents and possible the image you're trying to load and please share your full stack trace, not just the `ex.toString()`.
