### ISSUE TITLE
Use Glide to load installed apps icon?

### ISSUE THREAD

**Issue by xiongke15117937934** [bumptech/glide#1799]

**Comment by xiongke15117937934** [comment]
Picasso was can be loaded

**Comment by TWiStErRob** [comment]
http://lmgtfy.com/?q=Use+Glide+to+load+apps+icon%3F -> https://groups.google.com/d/topic/glidelibrary/MAqPfuHpjr4

Related: #1647

**Comment by xiongke15117937934** [comment]
4.0.0 How to use？
