### ISSUE TITLE
Glide 3.7.0 Memory Issues

### ISSUE THREAD

**Issue by 2trogers** [bumptech/glide#1802]
Hello, I am working on an app that displays a lot of images in RecyclerViews. One of my fragments  has a RecyclerView with dynamic views laid out on each cell that when tapped replace the current fragment. The new fragment tries to load a byte[] or url via Glide or defaults to a resource placeholder if those are invalid. The Glide load has a listener that then calls an async image blur via RenderScript on the finished image and sets the blurred bitmap to another ImageView. If it fails (onException) then I blur the resource drawable default and set it on the other ImageView.

I used DDMS to get the allocations on the RecyclerView layout before and after going into the new fragment and all my top allocation sizes associated with glide jumped by at least 5x, with one being over 100x. I use a clear memory on glide when detaching the new fragment.

I am using Xamarin.Android but I would like you to ignore that for now as being the cause.

Testing on OnePlus 3 but these memory issues are more prevalent on a lower memory device, like a Galaxy S4.

```java
Glide.With(this)
     .Load(<image-uri>)
	 .DontAnimate()
	 .Listener(this)
	 .Placeholder(<drawable resource>)
	 .Into(View.FindViewById<ImageView>(Resource.Id.collectionCover));
```
`this` is a non-support Fragment.

Below is the `onResourceReady`. `BlurHandler.Transform` uses RenderScript to blur it.

```java
BlurHandler
    .Transform(((GlideBitmapDrawable)p0).Bitmap, Activity)
    .ContinueWith(result => {
        if (result.Exception == null && result.Result != null && this.IsAdded) {
            Activity.RunOnUiThread(() => {
                if (View != null) {
                    View
                        .FindViewById<ImageView>(Resource.Id.collectionCoverBlur)
                        .SetImageBitmap(result.Result);
                }
            });
        }
    });
return false;
```

The layout is long, here is the part with the `ImageView`s:
```xml
<RelativeLayout
    android:id="@+id/headerContainer"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:fitsSystemWindows="true"
    app:layout_collapseMode="pin">
        <ImageView
            android:id="@+id/collectionCoverBlur"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop" />
        <LinearLayout
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#990a142f">
            <ImageView
                android:id="@+id/collectionCover"
                android:layout_width="187dp"
                android:layout_height="187dp"
                android:layout_gravity="center_horizontal"
                android:layout_marginTop="?attr/actionBarSize"
                android:scaleType="centerCrop"
                android:elevation="5dp" />
```

This is contained within a `CollapsingToolbarLayout`. As the IDs suggest, the `collectionCover` is the non-blurred image, `collectionCoverBlur` is the blurred image. 

Sorry about the bad formatting.

**Comment by TWiStErRob** [comment]
Can you please re-state what your actual problem is? I don't understand the paragraph with 5x and 100x. Why would you have allocations in the RecyclerView if the fragment is detached? What are you measuring?

Is your "current" fragment being replaced the one that contains the `RecyclerView` or they're side by side?

Also: fixed your formatting, you can check the markdown by pressing the pencil in top right of your opening post.

**Comment by 2trogers** [comment]
The problem is that when looking at the allocations on let's call it Page 1, then going into the new fragment, then back to Page 1, the number of objects allocated goes up by 1000.

The top ~10 are all glide .decode or something similar.
On Page 1 Before: Top ~10 allocations are all around 50KB according to DDMS
On Page 1 After: Top allocation is about 5MB, the rest are all about 250KB. 
That is the 100x and 5x I mentioned.

I cannot determine if the allocation is directly related to my RecyclerView, I stated it wrong when I said "get the allocations on the RecyclerView layout before and after". It is just the same fragment before and after visiting the new fragment.

The new fragment does a replace then pops off the backstack when going back.
