### ISSUE TITLE
setDecodeFormat(DecodeFormat.PREFER_ARGB_8888) is not working

### ISSUE THREAD

**Issue by oscargrgm** [bumptech/glide#1806]
**Glide Version**: 3.7.0
**Integration libraries**: None
**Device/Android Version**: Moto G (2nd gen) - Android 6.0 // Nexus 4 - Android 5.0.1
**Issue details / Repro steps / Use case background**: 
I'm using Glide to download images and loading them into different `ImageView` on a `RecyclerView`.

The code is inside my adapter class:
```java
Glide.with(context)
    .load(image)
    .diskCacheStrategy(DiskCacheStrategy.ALL)
    .placeholder(R.drawable.news_list_img_default)
    .error(R.drawable.news_list_img_default)
    .into(holder.image);
```

The resolution of the cached images is very poor, so I've added my own `GlideConfiguration.java` as you describe in your Wiki:
```java
public class GlideConfiguration implements GlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
    }
}
```
Also added in the `AndroidManifest.xml`:
```xml
<meta-data
    android:name="com.mypackage.folder.utils.GlideConfiguration"
    android:value="GlideModule" />
```

but the resolution is exactly the same. I've the same app for iOS and in an iPhone 4S I'm getting a very high resolution.

Am I doing anything wrong declaring Glide or implementing the GlideModule?

**Comment by TWiStErRob** [comment]
`8888` won't change the resolution, but may decrease the banding; see #820 for a good example. If you want resolution increase you probably need to use a higher DPI device.

In your case you may need to clear the Glide cache / reinstall the app. If you need to upgrade your users, you can call `Glide.get(context).clearDiskCache()`.

**Comment by oscargrgm** [comment]
Ok, I've seen this wasn't the problem. But now is even stranger.

I'm parsing an XML where I fetch the image urls and after that I use Glide to load them it into my different ImageViews.

If I parse the remote XML I get a very bad quality, but if I copy the same XML in my own computer, I get a perfect one. So the only difference between those XML is the place where they are located (one in remote, the other one in local).

The urls are the same for both.

Remote xml:
![screenshot_2017-03-22-15-51-57](https://cloud.githubusercontent.com/assets/9430919/24204245/2804636a-0f18-11e7-99d3-416ac4911cf2.png)

Local xml:
![screenshot_2017-03-22-15-52-03](https://cloud.githubusercontent.com/assets/9430919/24204266/37f4c2e2-0f18-11e7-9d4c-1cb3334d0956.png)

Maybe the problem is on the connection with the remote server?

**Comment by TWiStErRob** [comment]
It may be the speed at which the XML is parsed, the timings are different. It looks like you're using `padding` on the view, Glide doesn't support that. Refactor your layout XML to use margins.

**Comment by TWiStErRob** [comment]
Try to enable all logs: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling to see what's going on; maybe even apply https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/utils/LoggingListener.java to get more info.

**Comment by oscargrgm** [comment]
Thanks to your LoggingListener I've checked that the problem was in how I got the urls from the XML, not in the Glide method itself. So I guess this issue can be closed.

Thank you very much for your help and congrats for your amazing library!

**Comment by TWiStErRob** [comment]
Kudos goes to @sjudd I'm just contributing small things.
