### ISSUE TITLE
How to have different GlideModule for App and AndroidTest

### ISSUE THREAD

**Issue by poldz123** [bumptech/glide#1807]
Currently right now we can specify GlideModule in the manifest which is used by the Glide, but how do you specify different GlideModule for `app` and `androidTest` with the same name.

I know that we can currently do it through `Glide.setup` but this will be deprecated in the future release of Glide. Would there be a way in the future to specify it programmatically or specify different module in the manifest?

**Comment by TWiStErRob** [comment]
I think the easiest way is to just not depend on Glide to do that. For example, you could use a different Dagger component for prod and test, and inject some set-up code using that. This way you have the same module, doing different setup.

Another thing worth trying is to set up a GlideModule for test APK, but you'd probably need reflection to swap it out in `Glide` class. If you're using reflection, you might as well just `null` out the singleton. See https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/GlideReset.java for example. This app tears down the previous Glide every time, so I can set up different modules for each example (list item) without re-compile.

**Comment by TWiStErRob** [comment]
How did you go about it?

**Comment by poldz123** [comment]
I just used the setup method during test and the module for the app itself
