### ISSUE TITLE
Images loading twice with two different fetchers?

### ISSUE THREAD

**Issue by rcketscientist** [bumptech/glide#1811]
**Glide Version**: glide:3.7.0

**Integration libraries**: none

**Device/Android Version**: Samsung Tab S 6.0 stock

**Issue details / Repro steps / Use case background**: 
I'm trying to implement a `ContentProvider` that can supply thumbs on demand.  I noticed the `openFile` is being called twice for every file.

These are the two stacks:
```
openInputStream:711, ContentResolver (android.content)
loadResource:21, StreamLocalUriFetcher (com.bumptech.glide.load.data)
loadResource:14, StreamLocalUriFetcher (com.bumptech.glide.load.data)
loadData:44, LocalUriFetcher (com.bumptech.glide.load.data)
loadData:70, ImageVideoModelLoader$ImageVideoFetcher (com.bumptech.glide.load.model)
loadData:53, ImageVideoModelLoader$ImageVideoFetcher (com.bumptech.glide.load.model)
decodeSource:170, DecodeJob (com.bumptech.glide.load.engine)
decodeFromSource:128, DecodeJob (com.bumptech.glide.load.engine)
decodeFromSource:122, EngineRunnable (com.bumptech.glide.load.engine)
decode:101, EngineRunnable (com.bumptech.glide.load.engine)
run:58, EngineRunnable (com.bumptech.glide.load.engine)
```
```
openAssetFileDescriptor:914, ContentResolver (android.content)
loadResource:21, FileDescriptorLocalUriFetcher (com.bumptech.glide.load.data)
loadResource:14, FileDescriptorLocalUriFetcher (com.bumptech.glide.load.data)
loadData:44, LocalUriFetcher (com.bumptech.glide.load.data)
loadData:83, ImageVideoModelLoader$ImageVideoFetcher (com.bumptech.glide.load.model)
loadData:53, ImageVideoModelLoader$ImageVideoFetcher (com.bumptech.glide.load.model)
<same stack>
```
It seems to be calling on both `StreamLocalUriFetcher ` and `FileDescriptorLocalUriFetcher`.  Any idea why it would be doing this?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
		Glide.with(mContext)
				.load(MetaProvider.getThumbUri(galleryItem.uri))
				.centerCrop()
				.into(vh.mImageView);
```

**Comment by TWiStErRob** [comment]
It's just how it is implemented. `ImageVideoModelLoader` has two approaches: streams and descriptors, it calls both fetchers to see which one responds, so you get these two calls:
```java
contentResolver.openInputStream(uri); // StreamLocalUriFetcher#loadResourceFromUri
contentResolver.openAssetFileDescriptor(uri, "r").getParcelFileDescriptor(); // FileDescriptorLocalUriFetcher#loadResource
```

Not sure about the original reason, I always thought it has to do with video thumbnails. @sjudd why is `ImageVideoWrapper` and friends needed?

**Comment by TWiStErRob** [comment]
I'm using `ContentProvider` `Uri`s as well in my app, I disabled the above behavior by using this load:
```java
Glide
	.with(context)
	.using((StreamModelLoader<Uri>)Glide.buildModelLoader(Uri.class, InputStream.class, context))
	.from(Uri.class)
	// ... other stuff is the same as if it was just `Glide.with(context)`
```

**Comment by rcketscientist** [comment]
Thanks for lightning fast support as usual Rob.  Is that generating a custom loader on the fly?  Trying to follow that code, but that's some ninja jedi magic.  Above my pay grade ;-).

Why use `.from(Uri.class)` instead of `fromUri()`.  Is that necessary due to the builder?

On a whole isn't this extremely undesirable behavior?  In my case since the images being loaded are in memory I'm using pipes and the double calls create a world of hurt.  Even if they didn't, it's a possibly expensive process that need not happen and may not even be noticed.

**Comment by TWiStErRob** [comment]
Look into `fromUri` which points to `loadGeneric`, there you should immediately see that it creates two loaders. Also note that `.fromUri()` is not available after `using()`.

If you don't like `buildModelLoader` you can directly instantiate `new StreamUriLoader(context)`.

My usage, where I constructed the above example from, is generic,
so those `Uri`s in the above code are actually `<T>`s:
```java
<T> DrawableRequestBuilder<T> baseRequest(RequestManager glide, Class<T> clazz, Context context) {
	ModelLoader<T, InputStream> loader = Glide.buildModelLoader(clazz, InputStream.class, context);
	DrawableRequestBuilder<T> builder = glide
		.using((StreamModelLoader<T>)loader)
		.from(clazz)
		.animate(android.R.anim.fade_in)
		.error(R.drawable.image_error);
	if (/*magic condition to debug*/) {
		builder = builder
			.diskCacheStrategy(DiskCacheStrategy.NONE)
			.skipMemoryCache(true)
		;
	}
	return builder;
}
```
Have fun understanding the wizardry of Glide ;)

**Comment by rcketscientist** [comment]
Ok, glad I asked about the fromUri.  Now the whole thing is coming together.  I'll move ahead with the workaround.  

I would still make the argument that this is not an ideal setup.  Granted almost no one uses providers properly, but it is still "officially" the proper way to do tasks such as these.  With the changes to the filesystem in 5.0 and 6.0 I would expect that `Uri` loading will become far more common.  The `Document` api is pretty awful, you really don't want to be calling that twice for every image in a gallery.

**Comment by sjudd** [comment]
Yup I agree, this behavior is (mostly) fixed in Glide v4. We try each complete path one at a time. We will open a file more than once, but only if the type we opened (InputStream, FileDescriptor etc) couldn't be decoded.

**Comment by rcketscientist** [comment]
Ok, sounds great!  I know I can grab the snapshots, but how stable is 4.0/ how far out till release?

On an aside, since I don't want to open a question for this.  `RecyclerViewPreloader` looks interesting, but I can't find any info on it.  Would it be considered stable?  If so just pull the snapshot with gradle?

**Comment by TWiStErRob** [comment]
Not sure about close-ness, but you can use/copy/write `RecyclerViewPreloader` in v3 as well. Look around https://github.com/bumptech/glide/issues/1189
