### ISSUE TITLE
How to crossfade between old and new image

### ISSUE THREAD

**Issue by ControlAdad** [bumptech/glide#1815]
**Glide Version**:3.7.0
**Integration libraries**:NO

**Device/Android Version**:Nexus 5x, 7.1

I am using Glide for loading images in an adapter, the problem is when I modify and image in a new activity and return to thumbnail list and refresh screen, Glide cross fades between placeholder and new image. I want it to cross fade between old image and new image.

Thanks for great Glide.

**Comment by TWiStErRob** [comment]
See #861 for lengthy discussion on this. Code is at https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_861_preload_loop

You may not need `LoadCycler`, but instead just load the previous image as thumbnail, which hits the memory cache, and then the new image will fade from that. Though you may not have the previous data in your case.
