### ISSUE TITLE
There is a brief white screen when loading local images

### ISSUE THREAD

**Issue by MissMyDearBear** [bumptech/glide#1817]
Use glide to load a local image with a brief white screen。

**Comment by MissMyDearBear** [comment]
sory，
Glide.with(context).load(file).diskCacheStrategy(DiskCacheStrategy.NONE).dontAnimate().into(imageView);
 is solve  this issue

**Comment by TWiStErRob** [comment]
Likely duplicate of #527 though you didn't say you're loading an image on top of an already loaded image.

Well done for using `.diskCacheStrategy(NONE)` for local files!
