### ISSUE TITLE
Glide in 4.2 the webp images on your mobile phone?

### ISSUE THREAD

**Issue by xiongke15117937934** [bumptech/glide#1819]

**Comment by xiongke15117937934** [comment]
Tested detection is convert the rounded out the exception Delete will be gone

`public class GlideRoundTransform extends BitmapTransformation {

  private static float radius = 0f;

    public GlideRoundTransform(Context context) {//default 5dp
        this(context, 5);
    }

    public GlideRoundTransform(Context context, int dp) {
        super(context);
        radius = ViewUtils.dp2px(context, dp);
    }

    @Override
    protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
        return roundCrop(pool, toTransform);
    }

    private static Bitmap roundCrop(BitmapPool pool, Bitmap source) {
        if (source == null) return null;

        Bitmap result = pool.get(source.getWidth(), source.getHeight(), Bitmap.Config.ARGB_8888);
        if (result == null) {
            result = Bitmap.createBitmap(source.getWidth(), source.getHeight(), Bitmap.Config.ARGB_8888);
        }

        Canvas canvas = new Canvas(result);
        Paint paint = new Paint();
        paint.setShader(new BitmapShader(source, BitmapShader.TileMode.CLAMP, BitmapShader.TileMode.CLAMP));
        paint.setAntiAlias(true);
        RectF rectF = new RectF(0f, 0f, source.getWidth(), source.getHeight());
        canvas.drawRoundRect(rectF, radius, radius, paint);
        return result;
    }

    @Override
    public String getId() {
        return getClass().getName() + Math.round(radius);
    }`

**Comment by TWiStErRob** [comment]
http://lmgtfy.com/?q=glide+webp, explanation in second result: https://github.com/bumptech/glide/issues/571#issuecomment-131404236
