### ISSUE TITLE
Is Glide alive?

### ISSUE THREAD

**Issue by sergeyfitis** [bumptech/glide#1820]
How soon we can see new stable version?

**Comment by TWiStErRob** [comment]
@sjudd is the best to answer this; 3.8.0 has been getting PRs slowly, mostly around GIF, v4 has been dormant, but it's been woken up lately; peek at the closed PRs.

**Comment by b95505017** [comment]
@TWiStErRob 
I think that glide team should release current okhttp-integration snapshot to stable ASAP.
Because of this: https://github.com/bumptech/glide/issues/941#issuecomment-182663850

**Comment by sjudd** [comment]
Ah the joys of doing work in your spare time :). I appreciate your patience! If you'd like to help out, let me know or take a look at the open issues.
