### ISSUE TITLE
How to load into a preference?

### ISSUE THREAD

**Issue by DanteAndroid** [bumptech/glide#1821]
I have a preference for setting avatar, how do I load image into the icon of preference? Thx.
Preference has a method `setIcon(Drawable)`

**Comment by TWiStErRob** [comment]
Write a custom target based on `GlideDrawableImageViewTarget` and its super-classes, and use it with `.into(new PreferenceIconTarget(pref))`. If you manage to do it, consider a PR so other's don't have to.

**Comment by DanteAndroid** [comment]
Well, a little complex for a noob like me. Any example or elaborate explanation? Thx
