### ISSUE TITLE
Weird image partly displayed in nexus 5 / android 6.0.1

### ISSUE THREAD

**Issue by BottleChain** [bumptech/glide#1828]
Hi guys, I took about two weeks to change our app's imageLoader from fresco to glide. i feel that glide is a very powerful image loader. however ,there is a problem that i don't know how to solve. it happens some time. please take a look at the picture below:

![-1](https://cloud.githubusercontent.com/assets/8213373/24544253/24ea42fc-1635-11e7-9ecd-9779398f08d4.jpg)

as you can see, there is a banner on top of the screen , it should be as wide as the screen , seems the imageView's width is correct, but in the picture somehow is cut, only the middle part is shown on the screen. 

the interesting part is that , in the beginning , i mean when the app is first started, the banner is ok, but sometimes when i click and enter an other activity and then backup to the mainActivity or i scroll down a lot and go back to the top, one of the banner's imageView's picture has the problem of being cut~ i guess it is because the bitmap has been reused and the size is not correct? i just don't know how to solve this problem...because this banner is not the only imageView that has this problem, sometimes some other imageViews also have. so how can i fix this? 

another information is that there are lots of pictures in my app~

**and the gray rectangle in the middle of the picture is for secrecy，hope you don't mind~**

**Glide Version**: 3.8.0 snap-shot

**Integration libraries**:com.squareup.okhttp3:okhttp:3.2.0

**Device/Android Version**:Nexus 5/ 6.0.1

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
//code like below
Glide.with(context).load(url).listener(listener).into(imageview)
```

**# any help would be appreciated! thks!**

**Comment by boyw165** [comment]
I think it is the same problem as mine

https://youtu.be/Nzs2-1I3dvo

It is easy to reproduce this bug by simply scrolling down and up fast for several times. If you set the `placeholder` before loading the image, the problem would be solved.

**Comment by TWiStErRob** [comment]
I think this may be #363, but can't say for sure. When you say "middle part" do you mean vertical/horizontal/total middle? What about the height constraint, if the height doesn't allow the image to fit the width, that's normal, because you're likely using `.fitCenter()` implicitly (the default ImageView.scaleType).

**Comment by BottleChain** [comment]
hi TWiStErRob,

"middle part" means the left and right part of the banner is cut... like the picture above, the left and right side of the picture is lost, and the gray backgournd is showing~~

by boyw165's advice~, i did find out that the banner's imageviews do not have a placehoder setting, after i set a placehoder(.9.png) with a fitxy scaletype, it works fine so far~
