### ISSUE TITLE
Scaling Image in ImageView

### ISSUE THREAD

**Issue by wahyuprihantoro** [bumptech/glide#1831]
I have an ImageView with match_parent width and wrap_content height like this: 

```xml
<ImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
```

How to load an image (http://lorempixel.com/400/600/) using Glide that fit with ImageView and keeps the aspect ratio of the image?

**Comment by TWiStErRob** [comment]
Have you tried:
```java
ImageView imageView = (ImageView)findViewById(R.id.image);
Glide.with(this).load("http://lorempixel.com/400/600/").into(imageView);
```

The default `ImageView.scaleType` is `FIT_CENTER`, which Glide recognizes and uses `.fitCenter()` implicitly. See source code of `GenericRequestBuilder.into(ImageView)` method.

**Comment by wahyuprihantoro** [comment]
I've tried your solution but the image doesn't fit with the width of the layout. The layout_width of my ImageView is match_parent, so the image's width should follow the layout width which is match_parent. I've tried using fitXY, but it doesn't keep the aspect ratio of the image. Look at the result below:

**Load image from http://lorempixel.com/400/400/ (this is what I want in 400x600 and other ratios, the width is match_parent):**
![image](https://cloud.githubusercontent.com/assets/17500336/24579834/7267bc38-1727-11e7-9cb2-cf1a5062a017.png)

**Load from http://lorempixel.com/400/600/ using fitXY:** 
![image](https://cloud.githubusercontent.com/assets/17500336/24579861/02cfedb8-1728-11e7-9199-f21e007de79b.png)

**Load from http://lorempixel.com/400/600/ using default configuration:**
![image](https://cloud.githubusercontent.com/assets/17500336/24579862/1bfe6134-1728-11e7-9d38-e3ec779cc4c7.png)

and why GenericRequestBuilder.into(ImageView) doesn't handle all scaleType? 
thank you :)

**Comment by TWiStErRob** [comment]
`wrap_content` defaults to screen height so if your ratio would overshoot that you get a fitted image.  What you probably want is `.override(screenWidth, Target.SIZE_ORIGINAL).fitCenter()`, to display images taller than the screen, but consider that it's probably bad UX (IMO).

**Comment by TWiStErRob** [comment]
It does support all the scale types, the default applies to the non-mentioned ones.

**Comment by Visualrainy** [comment]
that's true to use Target.SIZE_ORIGINAL

**Comment by AndroidDeveloperLB** [comment]
Is there something similar to center-crop, yet I have the choice where to focus? 
I want to make sure a specific point/rectangle is shown while fitting&cropping.
How can I do it?
Currently the only similar thing that exists officially for ImageView is center-crop, but it's only to the center. What if the most important part in the image is at the bottom, instead? Or 10% (or 10px) from the bottom, etc... ? Or if there is a specific region in the bitmap that's most important?

**Comment by TWiStErRob** [comment]
@AndroidDeveloperLB You're describing custom transformations, have a look at https://github.com/wasabeef/glide-transformations, `CropTransformation` does some of what you listed, and others can be done based on that code.

**Comment by AndroidDeveloperLB** [comment]
@TWiStErRob Sure it's the same? I can't find explanation about CropTransformation. I can see it has width&height, but not sure if that's what I requested about:

https://github.com/wasabeef/glide-transformations/blob/main/transformations/src/main/java/jp/wasabeef/glide/transformations/CropTransformation.java

My question was about fit-cropping a region of the image that will include the given point/region, so that instead of center-crop that starts from the center so that the center will definitely be shown out of the image, it's the point/region of my choice.

**Comment by TWiStErRob** [comment]
I said "some" not "same" ;) It supports top/bottom crop. Your use case is quite special, you'll need to code that part.

**Comment by AndroidDeveloperLB** [comment]
@TWiStErRob Edges/corners are already available on various repositories. I asked about point/region. When I ask if it's possible, I meant to ask if there is an API for it. Not to ask if I can implement it. I can also avoid using Glide completely, and crop from Bitmap or use Matrix for the ImageView to choose which part to draw out of a given Bitmap.
