### ISSUE TITLE
Integration libraries don't use StreamModelLoader interface

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#1832]
**Glide Version**: 3.8.0

**Integration libraries**: all networking

**Device/Android Version**: N/A

**Issue details / Repro steps / Use case background**:
I was trying to work out #1829, by reusing code from OkHttp3, but when I tried to use the loader via `.using` I had to specify all decoders and everything, which is uncalled for.

https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/model/stream/HttpUrlGlideUrlLoader.java#L19
https://github.com/bumptech/glide/blob/3.0/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpUrlLoader.java#L18
https://github.com/bumptech/glide/blob/3.0/integration/okhttp/src/main/java/com/bumptech/glide/integration/okhttp/OkHttpUrlLoader.java#L17
https://github.com/bumptech/glide/blob/3.0/integration/volley/src/main/java/com/bumptech/glide/integration/volley/VolleyUrlLoader.java#L18

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide
	.with(this)
	.using(new OkHttpUrlLoader(myOkHttpClient)) // compile error
	.load(new GlideUrl("http://..."))
	.into(imageView);
```

**Stack trace / LogCat**:
```
error: no suitable method found for using(OkHttpUrlLoader)
method RequestManager.<A,T#1>using(ModelLoader<A,T#1>,Class<T#1>) is not applicable
(cannot infer type-variable(s) A,T#1
(actual and formal argument lists differ in length))
method RequestManager.<T#2>using(StreamModelLoader<T#2>) is not applicable
(cannot infer type-variable(s) T#2
(argument mismatch; OkHttpUrlLoader cannot be converted to StreamModelLoader<T#2>))
method RequestManager.using(StreamByteArrayLoader) is not applicable
(argument mismatch; OkHttpUrlLoader cannot be converted to StreamByteArrayLoader)
method RequestManager.<T#3>using(FileDescriptorModelLoader<T#3>) is not applicable
(cannot infer type-variable(s) T#3
(argument mismatch; OkHttpUrlLoader cannot be converted to FileDescriptorModelLoader<T#3>))
where A,T#1,T#2,T#3 are type-variables:
A extends Object declared in method <A,T#1>using(ModelLoader<A,T#1>,Class<T#1>)
T#1 extends Object declared in method <A,T#1>using(ModelLoader<A,T#1>,Class<T#1>)
T#2 extends Object declared in method <T#2>using(StreamModelLoader<T#2>)
T#3 extends Object declared in method <T#3>using(FileDescriptorModelLoader<T#3>)
```

#### Workaround

```java
Glide
	.with(this)
	.using(new StreamModelLoaderWrapper<>(new OkHttpUrlLoader(myOkHttpClient))
	.load(new GlideUrl("http://..."))
	.into(imageView);
```

```java
class StreamModelLoaderWrapper<T> implements StreamModelLoader<T> {
	private final ModelLoader<T, InputStream> wrapped;

	StreamModelLoaderWrapper(ModelLoader<T, InputStream> wrapped) {
		this.wrapped = wrapped;
	}

	@Override
	public DataFetcher<InputStream> getResourceFetcher(T model, int width, int height) {
		return wrapped.getResourceFetcher(model, width, height);
	}
}
```

**Comment by TWiStErRob** [comment]
@sjudd would it be a compatible change for 3.8.0 to change those four linked places to say `implements StreamModelLoader<GlideUrl>`?

**Comment by sjudd** [comment]
It's slightly unsafe because you're making the type more specific, but I doubt that it will negatively affect anyone. I'd say go for it.
