### ISSUE TITLE
Question about caching

### ISSUE THREAD

**Issue by lazercorn** [bumptech/glide#1833]
Just a quick question. Let's say we're using a cache mode. We go to the image link first time and it's new so Glide caches it. Then second time we come upon the same image link, we notice it's already in the cache so Glide grabs it from the cache. Now let's say Glide keeps getting new image links and caching them. Eventually the cache space will run out. How does Glide deal with this? Will it start removing already cached images to make room for caching new image links? or will it throw an error or something?

Thanks for reading.

**Comment by TWiStErRob** [comment]
Glide uses DiskLruCache, so it'll evict the oldest image that was used to make room. See DiskLruCacheWrapper.

**Comment by lazercorn** [comment]
Thanks!
