### ISSUE TITLE
Glide with Instant Run Enabled

### ISSUE THREAD

**Issue by ghiyats-olx** [bumptech/glide#1834]
I am getting an unusual NoClassDefFound Exception when running my app with InstantRun enabled on Android Studio 2.3 which resulting the images not appeared on the screen, but somehow when I disable the instantRun everything works just fine.

`java.util.concurrent.ExecutionException:` java.lang.NoClassDefFoundError: Failed resolution of: Lcom/newrelic/agent/android/instrumentation/BitmapFactoryInstrumentation;`

**Comment by TWiStErRob** [comment]
Why is that a Glide issue? You should get the same exception if you used `BitmapFactory` yourself. Try http://stackoverflow.com/a/24316729/253468 or similar based on your exception.
