### ISSUE TITLE
load image with https

### ISSUE THREAD

**Issue by vlad-shtark** [bumptech/glide#1839]
Please,can you show an example of uploading an image through the https protocol?

**Comment by neelanshsahai** [comment]
I had the same Issue
But this can be resolved if we remove the **s** from the _https://_
Try using the http links instead of https ones

**Comment by sjudd** [comment]
Glide doesn't generally deal with uploading images. Http/https should work fine, unless you're trying to trust a self signed cert, in which case something like this might be helpful: https://futurestud.io/tutorials/glide-module-example-accepting-self-signed-https-certificates.
