### ISSUE TITLE
Images can not be displayed, but the browser can be used

### ISSUE THREAD

**Issue by tudousiji** [bumptech/glide#1840]
Images can not be displayed, but the browser can be used

http://img1.qcdqcdn.com/group1/M00/01/96/oYYBAFij5YqAKhccABNcDv0Afxo466_300x200.jpg

**Comment by TWiStErRob** [comment]
It looks like the server responds with a forced GZIP encoding, but doesn't send the corresponding `Content-Encoding` header, so Glide decodes the gz stream as JPEG which obviously fails in `BitmapFactory`. Glide [explicitly asks for `identity`](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/LazyHeaders.java#L103-L104), which is uncompressed.

**Comment by lizheng98** [comment]
@TWiStErRob 
I used OkHttpGlideModule, but I still can not show it
