### ISSUE TITLE
Gif converted to webp can not be displayed

### ISSUE THREAD

**Issue by zhangqb** [bumptech/glide#1844]
**Glide Version 3.7**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Why is it so hard to Google "Glide webp" before opening an issue? It feels like every week someone opens a new issue for webp.
