### ISSUE TITLE
Fetching photos from database via content provider

### ISSUE THREAD

**Issue by shomybg88** [bumptech/glide#1845]
Hello
I was using URI to fetch photos from android contacts db so far, and that worked perfect!
I was wondering can I just modify URI and fetch photos from my database via content provider?
(I have a database with photos, saved as blob)

I saw the explanation here, but it doesn't work. When I use URI in load() method, my content provider isn't called at all. 
https://groups.google.com/d/msg/glidelibrary/mnaZ7E7gwX8/Co8_Qc-GnNIJ

Any idea how to make a URI to trigger my content provider?
Thanks

**Comment by TWiStErRob** [comment]
So many things can go wrong here, so without an exception we can't help.
Please try to get a stack trace: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
... and share your Glide code.
