### ISSUE TITLE
Gif Image Load Error

### ISSUE THREAD

**Issue by Caij** [bumptech/glide#1849]
image url:   http://wx1.sinaimg.cn/large/006Hm8pLgy1fei13a3386g30dc07i1l5.gif

Glide load the image error, but browser can be loaded successfully.  
then I debug the load process， when GifResourceDecoder.inputStreamToBytes thow  java.net.ProtocolException: unexpected end of stream.

**Comment by TWiStErRob** [comment]
The file is invalid, it doesn't have an ending. The last 3k is zeroed out.

According to the specification the GIF Data Stream must end in a Trailer which is a 0x3B character. See https://www.w3.org/Graphics/GIF/spec-gif89a.txt section 27 and Appendix B.
