### ISSUE TITLE
How to load https url

### ISSUE THREAD

**Issue by wanyt** [bumptech/glide#1850]
When I show https url, there is exception:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.  
                                                          
How to fix it.

**Comment by xesam** [comment]
you can customize OkHttpClient to support https。[https://github.com/bumptech/glide/wiki/Integration-Libraries](https://github.com/bumptech/glide/wiki/Integration-Libraries)

**Comment by TWiStErRob** [comment]
HTTPS shoyld be supported by default, but I think only with valid certificates. @xesam is right, you need to configure an integration library (or custom loader/fetcher) to ignore some validations.

**Comment by sorya-dev** [comment]
You try this
https://medium.com/@starryzoo/glide-https-ssl-handshake-exception-e0f22b8457f1
