### ISSUE TITLE
Glide how to load a image with session cookie?

### ISSUE THREAD

**Issue by ggtf** [bumptech/glide#1851]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Which Glide version and what integration libraries do you use? (aka: please fill in the above template)

**Comment by TWiStErRob** [comment]
Please reopen once you provided the info.
