### ISSUE TITLE
is it possible to create 2 folders for caching images ?

### ISSUE THREAD

**Issue by alonaviram** [bumptech/glide#1852]
im using glide:3.7.0.
i want to create one folder of cache up to 150mb for specific purpose,and other folder will be for general purposes. ( prefer not to download files to storage on my own unless i have to)
what i actually want to achieve is that specific images must be available offline and their size should not be more than 150 mb.
thanks.

**Comment by TWiStErRob** [comment]
> must be available offline

That's where caching falls sort, there's no guarantee that the files will be there. Even the user can clear the cache from standard Android UI. If you want offline pinning, you have to implement it yourself.

The next problem that will come up (as it did about 50 times before), is that you cannot delete files from cache explicitly. To which the solution is again: use a proper networking library to manage files.

To load files from these custom pinned offline storages you can use `Glide.with(...).load(file).diskCacheStrategy(NONE).into(imageView)`; NONE is needed to not duplicate files in Glide caches.

See https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=%22Glide%20is%20not%20a%20networking%20library%22 for more info.
