### ISSUE TITLE
Remove cache key to invaldite to get image from update image.

### ISSUE THREAD

**Issue by rameshkec85** [bumptech/glide#1854]
I have one url where image loads dynamically by redirecting url to new url. 

http://www.sampleimages.com?id=1

**Redirected to**:

http://www.sampleimages.com/1/abc.jpg&modifieddate=12345

When url of redirect url has changed, i want to invalidate cache.
(OR)
Will get push notification with id if image has changed. So that I have to invalidate cache of the url.

Please help me to remove cache key from the glide. (Scenario: image will changed at any point of time at the server and I don't have meta information related to image)
 
**Glide Version**:  3.7.0

**Comment by TWiStErRob** [comment]
See also related #1847
