### ISSUE TITLE
Question regarding OkHttp integration on master branch (v4)

### ISSUE THREAD

**Issue by gajicm93** [bumptech/glide#1855]
Why does OkHttp integration for v4 on master branch use async call (enqueue()) in the loadData() method, if the loadData method itself is called on the background thread? Doesn't it just unnecessarily spawn new thread inside OkHttp itself, and also causing your thread to finish before the image itself is loaded?

**Comment by TWiStErRob** [comment]
I think it is to support cancellation.
In v3 most of the fetchers completed even if the Glide load target was cleared.
@sjudd knows more about this.

**Comment by sjudd** [comment]
The main reason is to avoid blocking Glide's threads with long running network operations. Doing so can negatively affect local image loading, especially on poor networks where both local and remote content is loaded concurrently.

Glide isn't a networking library, so whenever possible we try to offload work to networking libraries. OkHttp has it's own internal executor service which seems appropriate here.
