### ISSUE TITLE
How to draw Glide GifDrawable on canvas?

### ISSUE THREAD

**Issue by rahul-padmakumar** [bumptech/glide#1856]
I want to draw GIF drawable on a rotated canvas. When I use GifDrawable's draw() method, only the first frame gets drawn and animation is also not working. Can anyone please help me with this?

**Comment by TWiStErRob** [comment]
You need to `start`/`stop` the drawable, you can check current state via `isRunning`, all this is on the `Animatable` interface from Android. You can subscribe to frame changes via `Drawable.setCallback`, in `invalidateDrawable` you can draw the current frame. This will advance the GIF animation as per its intrinsic timings, if you want more control you have to use `GifFrameLoader` or `GifDecoder` directly.

For education: May I ask what you're doing? Where's that Canvas targeted at?

**Comment by rahul-padmakumar** [comment]
Thanks, TWiStErRob for your help. I will try it.
Basically i am trying to scale, rotate and translate a GIF. I was able to achieve it by loading GIF in an image view and rotating it using matrix transformation. But now I want to load GIF in a custom view that only extends a view and then rotate, scale and translate the GIF.

**Comment by TWiStErRob** [comment]
Consider writing a custom bitmap transformation for it, each frame will go through that if you apply it. Though if you want to do it dynamically, per user input, or anim, then it's not viable.
