### ISSUE TITLE
Can v4 support GifDrawable seek(int frameIndex) method ?

### ISSUE THREAD

**Issue by SwordBearer** [bumptech/glide#1857]
Thanks for this excellent .
I think is that GifDrawable  may need a seek(int frameIndex) method ,thus we can easily show any frame in gif file .now.i.found that v3 has a inner class GifFrameLoader ,can you guys support this seek() method in v4  :)

**Comment by TWiStErRob** [comment]
Pull request is welcome to do that.

**Comment by sjudd** [comment]
I'm going to close this. There's no reasonable way to seek in GIFs. You have to decode every intermediate frame. Probably if you need seeking you'd be better off using a different format (though I suppose that's true in general for GIF...).

**Comment by stevenwsg** [comment]
O No, I have this need
