### ISSUE TITLE
can not load local video thumbnail successfully

### ISSUE THREAD

**Issue by Drizzlezhang** [bumptech/glide#1861]
**Glide Version**:3.7.1

**Integration libraries**:okhttp3-1.4.0

**Issue details / Repro steps / Use case background**: Hi, recently I want to use Glide to replace UIL. Because my app have my own photo picker, and when I use UIL I use the video path to display video thumbnail.UIL displayed the thumbnail successfully, but Glide only can display image thumbnail. I read the Glide and UIL's source code, I think the code is right, but I don't know why it can's display successfully.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context)
                      .loadFromMediaStore(Uri.parse("file:///storage/emulated/0/DCIM/Camera/VID_20151225_214839.mp4"))
                        .priority(Priority.NORMAL)
                        .diskCacheStrategy(DiskCacheStrategy.ALL)
                        .animate(android.R.anim.fade_in)
                        .into(imageview);
```

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by Drizzlezhang** [comment]
I have written a custom ModelLoader, and use the ThumbnailUtils to solve the problem.Thx for your answer.

**Comment by AshishPsaini** [comment]
Hi Drizzlezhang,
I am getting the same issue. May you provide any link where I can get the code of ThumbnailUtils and ModelLoader classes.
