### ISSUE TITLE
 Caused by java.lang.IllegalStateException: Activity has been destroyed

### ISSUE THREAD

**Issue by xiongke15117937934** [bumptech/glide#1863]
`
Caused by java.lang.IllegalStateException: Activity has been destroyed
android.support.v4.b.w.a (FragmentManager.java:1864)
android.support.v4.b.h.a (BackStackRecord.java:649)
android.support.v4.b.h.c (BackStackRecord.java:614)
com.bumptech.glide.d.k.a (RequestManagerRetriever.java:187)
com.bumptech.glide.d.n.onAttach (SupportRequestManagerFragment.java:116)
android.support.v4.b.q.onAttach (Fragment.java:1222)
android.support.v4.b.w.a (FragmentManager.java:1231)
android.support.v4.b.w.d (FragmentManager.java:1528)
android.support.v4.b.w.a (FragmentManager.java:1595)
android.support.v4.b.h.e (BackStackRecord.java:757)
android.support.v4.b.w.b (FragmentManager.java:2355)
android.support.v4.b.w.a (FragmentManager.java:2146)
android.support.v4.b.w.b (FragmentManager.java:2098)
android.support.v4.b.w.d (FragmentManager.java:2008)
android.support.v4.b.w.r (FragmentManager.java:2924)
android.support.v4.b.q.performDestroy (Fragment.java:2427)
android.support.v4.b.w.a (FragmentManager.java:1442)
android.support.v4.b.w.d (FragmentManager.java:1528)
android.support.v4.b.w.a (FragmentManager.java:1595)
android.support.v4.b.w.r (FragmentManager.java:2925)
android.support.v4.b.q.performDestroy (Fragment.java:2427)
android.support.v4.b.w.a (FragmentManager.java:1442)
android.support.v4.b.w.d (FragmentManager.java:1528)
android.support.v4.b.w.a (FragmentManager.java:1595)
android.support.v4.b.w.r (FragmentManager.java:2925)
android.support.v4.b.t.m (FragmentController.java:271)
android.support.v4.b.r.onDestroy (FragmentActivity.java:390)
android.support.v7.app.d.onDestroy (AppCompatActivity.java:209)`

glide version：3.7.0

**Comment by sjudd** [comment]
This is fixed in 4.0 at least.

**Comment by sjudd** [comment]
https://github.com/Teovald/glide/commit/ac3b33aadd4961eeee00ff985205d3a6434789c8
