### ISSUE TITLE
skia: --- decoder->decode returned false

### ISSUE THREAD

**Issue by xpzzgh** [bumptech/glide#1864]
platform：Android5.0     
CPU：ATM7059 Cortex-A9 Quad-core 1.6GHz
**Glide Version**: 3.7.0

"skia: --- decoder->decode returned false" will display when size of png is bigger than 300K and image is not show. but I can load it successfully after I download it.
picasso can load successfully.

```java
Glide.with(this)
                .load(url)
                .asBitmap()
                .into(imageview);
```

**Comment by TWiStErRob** [comment]
What's the URL?

**Comment by xpzzgh** [comment]
@TWiStErRob    like this:    https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1492505075134&di=129585e00fd38c6f25c2cd1cc66863c6&imgtype=jpg&src=http%3A%2F%2Fimg2.imgtn.bdimg.com%2Fit%2Fu%3D781340808%2C1125214629%26fm%3D214%26gp%3D0.jpg

every image will not show as long as the image's size is larger than 300K in my case.

**Comment by xpzzgh** [comment]
I debug it, and it will go in onLoadFailed,but Exception is null. 
It will only load failed on this platform, and it can load successfully on other platform like Sumsung S7.  
So I don't know whether it's related to the OS.

**Comment by TWiStErRob** [comment]
The exception is null, because there's no exception. `BItmapFactory` simply cannot decode it and that returns a null.

Check the logs around, maybe there's a clue why, even on newer versions, see #1843 to see what I mean by that.

**Comment by xpzzgh** [comment]
@TWiStErRob   It can load successfully with Picasso.
                   `Picasso.with(this).load(url).into(view);`

**Comment by xpzzgh** [comment]
And Glide can load it after I download the image with a AsyncTask.

**Comment by TWiStErRob** [comment]
It's possible that the `Content-Length` header is wrong for the generated image, can you try to add OkHttp3 integration and load with that?

**Comment by xpzzgh** [comment]
@TWiStErRob   It's not work, the image isn't show.  it can show when I compress this image's size to 292K.
      So I don't know why.

**Comment by xpzzgh** [comment]
I can't resolve it, any help？

**Comment by ycyangchun** [comment]
I also encountered this problem and finally found the reason why the color mode of the image was cmyk
