### ISSUE TITLE
Glide: Can't copy a recycled bitmap

### ISSUE THREAD

**Issue by bartwell** [bumptech/glide#1869]
I am using SubsamplingScaleImageView with Glide to load, cache and show images:

```
SubsamplingScaleImageView mImageView;

Glide.with(this)
.load(url)
.asBitmap()
.into(new SimpleTarget<Bitmap>() {
        @Override
        public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                mImageView.setImage(ImageSource.bitmap(
                    Bitmap.createBitmap(resource, x1, y1, x2 - x1, y2 - y1)));
        }
    });

```

It works but crashes sometimes with error `IllegalStateException: Can't copy a recycled bitmap` in `Bitmap.createBitmap`. How to fix it?

**Comment by michaelDnguyen** [comment]
This case also happens with me, Please help this issue ?

**Comment by sjudd** [comment]
What version of Glide are you using? What is you load line? 

Some tips here (written for v3, but applies to v4 as well): https://github.com/bumptech/glide/wiki/Resource-re-use-in-Glide

**Comment by michaelDnguyen** [comment]
Here my code:
`FutureTarget<Bitmap> futureTarget = Glide.with(getActivity()).asBitmap().load(selectedimg).submit();
Bitmap realImage = null;
try {
	realImage = futureTarget.get();
} catch (InterruptedException e) {
	e.printStackTrace();
} catch (ExecutionException e) {
	e.printStackTrace();
}
Bitmap myBitmap = realImage.copy(Bitmap.Config.ARGB_8888, true);
`

App crash ai here, log : IllegalStateException: Can't copy a recycled bitmap

**Comment by sjudd** [comment]
@michaelDnguyen take a look at http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors.

I don't see anything obviously wrong with the code you've provided here, If you're calling bitmap.recycle() or passing Bitmaps around that you've extracted from Views or Targets in other parts of your code, they could be triggering an exception here.
