### ISSUE TITLE
关于Ubuntu环境下编译glide错误

### ISSUE THREAD

**Issue by a354425558** [bumptech/glide#1871]
packages/apps/BoatApp/BoatExpression/src/main/java/com/boat/boatexpression/InteractiveActivity.java:369: error: cannot find symbol
                                    .load(R.mipmap.gocharging).diskCacheStrategy(DiskCacheStrategy.SOURCE)
                                                                                 ^
  symbol: variable DiskCacheStrategy
Note: packages/apps/BoatApp/BoatExpression/src/main/java/com/boat/boatexpression/InteractiveActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

**Comment by TWiStErRob** [comment]
Check your imports. If `Glide` class is visible, then `DiskCacheStrategy` must be visible as well.
