### ISSUE TITLE
ETA on Glide 3.8

### ISSUE THREAD

**Issue by jaredsburrows** [bumptech/glide#1876]
Hey, we really appreciate the hard work on Glide, @TWiStErRob! Can you please give me an ETA when you plan on releasing on Glide 3.8? Could we also start releasing more often?

**Comment by jaredsburrows** [comment]
Any update on this, @TWiStErRob?

**Comment by TWiStErRob** [comment]
You're asking the wrong person, I mostly only answer to technical questions and some code contribution.
If you'd like to help out with releasing I'm sure @sjudd will be happy to guide you!

**Comment by jaredsburrows** [comment]
@TWiStErRob Thanks!

@sjudd If you do not mind, when is the ETA for the 3.8 release?

**Comment by jaredsburrows** [comment]
Any news @sjudd?

**Comment by Teovald** [comment]
Glide 3.8 is out so we can close this ticket

**Comment by jaredsburrows** [comment]
Thank you!
