### ISSUE TITLE
Custom pause and resume for resource loading

### ISSUE THREAD

**Issue by neevek** [bumptech/glide#1877]
I am not using either Fragments or multiple Activities to build the app stack, I wrap views, put them in a stack, and manage the lifecycle of the views myself. 

My question is: is it possible to integrate Glide with my view wrappers to support auto pause/resume? (My view wrappers have lifecycle methods like `onStart()`, `onStop`, etc. It is like Fragment, but it is not.)

**Comment by TWiStErRob** [comment]
Yes, it should be. Take a look at `RequestManager` constructor usage, `RequestManagerRetriever`.
You'll need to write your own `GlideX.with(MyViewThingy)` to return a `RequestManager` associated with your view hierarchy/stack element and from there Glide usage should be the same.

For more info see #1148 and make contact with @thedumbtechguy how far he got.

Mind you also that @sjudd just implemented `Glide.with(View)` for v4 in #1800. That's using the closes standard android component though, I take you need finer control than that (i.e. you have a single activity, but need multiple managers).
