### ISSUE TITLE
How to detect broken image links in Glide

### ISSUE THREAD

**Issue by WanClem** [bumptech/glide#1879]
Hello guys, so I was thinking...Is there any way for Glide to detect if an image url doesn't resolve to a resource. I mean, how can one detect broken image links so I can show a lettered image replacement for that broken link. Thanks

**Comment by TWiStErRob** [comment]
`.listener()` is your friend if you need access to the view or model (url); otherwise `.error()`, if a generic solution is enough. You can combine both: if you return false in listener, `.error()` will be shown.
