### ISSUE TITLE
Failed to find GeneratedAppGlideModule

### ISSUE THREAD

**Issue by rahulpandey** [bumptech/glide#1880]
i'm keep getting  warning **Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignore**
i'm using   glideVersion="4.0.0-SNAPSHOT" ,glideOkHttpModule="2.0.0-SNAPSHOT"
it is require any extra dependency  ?

**Comment by sjudd** [comment]
See: http://sjudd.github.io/glide/doc/download-setup.html#gradle
And: http://sjudd.github.io/glide/doc/generatedapi.html

**Comment by rahulpandey** [comment]
Look like it's not uploaded on MavenCentral
 **Error:(54, 11) Failed to resolve: com.github.bumptech.glide.annotation:compiler:4.0.0-SNAPSHOT
<a href="openFile:D:/Discount-workspace/DiscountHub/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>**

**Comment by TWiStErRob** [comment]
of course not, it's not released: https://github.com/bumptech/glide/wiki/Snapshots

**Comment by rahulpandey** [comment]
i'm following this http://sjudd.github.io/glide/doc/download-setup.html#gradle to add com.github.bumptech.glide.annotation:compiler:4.0.0-SNAPSHOT this dependency it's giving me that error

**Comment by rahulpandey** [comment]
@TWiStErRob  i already added 
repositories {
    jcenter()
    mavenCentral()
    maven {
      name 'glide-snapshot'
      url 'http://oss.sonatype.org/content/repositories/snapshots'
    }
  } in gradle file

**Comment by TWiStErRob** [comment]
Ah, ok, looking at https://oss.sonatype.org/content/repositories/snapshots/com/github/bumptech/glide/ abd #1906 you need 
```gradle
compile 'com.github.bumptech.glide:compiler:4.0.0-SNAPSHOT'
compile 'com.github.bumptech.glide:annotations:4.0.0-SNAPSHOT'
```

**Comment by sjudd** [comment]
Wups, yup my documentation wasn't quite right, fixed here: e99dcf6a13d6ac888f4e00fc6b5165c119e94e5c

**Comment by zeroarst** [comment]
I think this page should be updated?
http://bumptech.github.io/glide/doc/configuration.html

**Comment by TWiStErRob** [comment]
@zeroarst Likely, feel free to open a PR for docs: http://bumptech.github.io/glide/dev/contributing.html#documentation

**Comment by StainlessStlRat** [comment]
Is it ok to ignore this warning?  I'm on 4.7.1, have the requested annotationProcessor directive, and my images seem to be loading fine.  What will happen if I ignore this warning?

**Comment by elronsmith** [comment]
Have this problem with 4.8.0 and without proguard. I dont use glide modules. targetSdkVersion 27

**Comment by sjudd** [comment]
It's ok to ignore this warning as long as:

1. You don't want to use [the generated API][1]
2. You're not depending on any libraries that add functionality to Glide via LibraryGlideModules

[1]: http://bumptech.github.io/glide/doc/generatedapi.html
[2]: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/module/LibraryGlideModule.html

**Comment by DysaniazzZ** [comment]
So the AppGlideModule is not necessary if I don't want to use, am I right? BTW, is there any side effect when not use the generated API? @sjudd

**Comment by TWiStErRob** [comment]
@DysaniazzZ you can use Glide without any annotation processing. The only drawback I'm aware of is a non-fluid API. The limitations are as @sjudd stated above. If you use just Glide you should be ok, but adding OkHttp for example might trigger you to do annotation processing, or some manual setup.
