### ISSUE TITLE
How to get images using glide with http server api Url and append headers with tokens?

### ISSUE THREAD

**Issue by karthikkavin** [bumptech/glide#1881]
hi!
How to get a image using Glide?
How to get token based authentication server api Url used to get images using Glide?

Please help?

**Comment by TWiStErRob** [comment]
First question should be obvious: https://github.com/bumptech/glide#how-do-i-use-glide

Second is not obvious, but is already answered in the issues: https://github.com/bumptech/glide/issues/921#issuecomment-174185985
