### ISSUE TITLE
Preload images in a RecyclerView

### ISSUE THREAD

**Issue by ImageViewGlide** [bumptech/glide#1886]
**3.7.0**:

When I scroll through my RecyclerView the first time, my images load slowly. After that they are there instantly without any waiting time until I close my app. I want to preload like 5-10 images so scrolling is smoother, so here is what I have tried:

    
                            Glide
                                    .with(getContext())
                                    .load(getResources().getIdentifier("item"+(listIndex+7, "drawable", getContext().getPackageName()))
                                    .diskCacheStrategy(ALL)
                                    .preload(120,60);
                        }

That was supposed to preload the 7th image that comes next into cache. Then my normal image loads:

    Glide
                                        .with(getContext())
                                        .load(getResources().getIdentifier("item"+(listIndex), "drawable", getContext().getPackageName()))
                                        .diskCacheStrategy(ALL)
                                        .into((ImageView)itemView.findViewById(R.id.imageH));
                            }

But even now the images still take time to load while scrolling.

**Comment by TWiStErRob** [comment]
You're missing the transformation, add `.fitCenter()` or `.centerCrop()` depending on what your ImageView scaleType is. (See `GenericRequestBuilder​.into(ImageView)` for more.

Also make sure that the ImageView actually measures to 120x60px

**Comment by TWiStErRob** [comment]
If still doesn't work, check https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling for how to debug cache hits.

**Comment by ImageViewGlide** [comment]
That didn't work, but I found another way. I preloaded the images into an invisible ImaeView and that worked very well. Any downsides of using this?
