### ISSUE TITLE
problem load image

### ISSUE THREAD

**Issue by mreram** [bumptech/glide#1888]
i use this url http://app.akharinkhabar.ir/AndroidOnlineNewsImage.aspx?id={id}
to load images.
example url: http://app.akharinkhabar.ir/AndroidOnlineNewsImage.aspx?id=12617879

                Glide.with(GlideActivity.this).load(etxt.getText().toString()).listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        Toast.makeText(GlideActivity.this,e==null?" null exception":e.getMessage(),Toast.LENGTH_LONG).show();
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        return false;
                    }
                }).into(img);

other libraries works fine but your's doesn't load images correctly.
i've set RequestListener to get exception but returns null.. and show  "D/skia: —- SkImageDecoder::Factory returned null" in log.

**Comment by TWiStErRob** [comment]
We're going to need more info, because it "just loads" (tried emu 19 and 25):
![image](https://cloud.githubusercontent.com/assets/2906988/25585347/fccb5480-2e91-11e7-8fbf-c1ae198bea40.png)

**Comment by TWiStErRob** [comment]
Maybe your id is wrong, because if I do http://app.akharinkhabar.ir/AndroidOnlineNewsImage.aspx?id=123456789 it is a 0-byte stream, and not a 404, which obviously cannot be decoded to an image by BitmapFactory:
```
D/skia: --- SkImageDecoder::Factory returned null
V/GLIDE: .onException(null, http://app.akharinkhabar.ir/AndroidOnlineNewsImage.aspx?id=123456789, LoggingTarget@ad1475f8, first)
```

**Comment by mreram** [comment]
i test by following link application ... works with some network connections and doesn't work with others
[test glide.zip](https://github.com/bumptech/glide/files/969516/test.glide.zip)
