### ISSUE TITLE
java.lang.IllegalArgumentException: Bad position (limit 2905387): 2905459

### ISSUE THREAD

**Issue by ZhenMrLee** [bumptech/glide#1891]
url:http://fashion2017.niwodu.com/515617-e0144647ae9ee6a53dfe32a6458be834?imageslim
` Glide.with(NewsApplication.getInstance())
                .load(url)
                .asGif()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .error(R.drawable.ic_fail)
                .listener(requestGIFListener)
                .placeholder(R.drawable.ic_loading).into(imageView);`
`java.lang.IllegalArgumentException: Bad position (limit 2905387): 2905459`

I am a newcomer，so i saw a few of issues,i can't deal with it

**Comment by sjudd** [comment]
You'd need to include more the stack trace for this to be actionable. Please also fill out the issue template next time.

**Comment by TWiStErRob** [comment]
Also see #1849, you file ends mid-frame: open it in browser and notice the half-frame flash at the end of each loop.
