### ISSUE TITLE
Unable to load images whose URL contains special characters ø, å, æ 

### ISSUE THREAD

**Issue by GSala** [bumptech/glide#1896]
**Glide Version**:
3.7.0

**Integration libraries**:
Retrofit 2.2.0 which contains a dependency to OkHttp

**Device/Android Version**:
Nexus 5

**Issue details / Repro steps / Use case background**: 
Trying to load a URL like this one: http://www.dlg.dk/-/media/DLG/Corporate/Landmand/Økologi/DLG-Okologi_haand.ashx fails with 404 - Not Found. Pasting the same URL in the browser resolves just fine.
Relevant: #133

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(imageView.getContext())
                .load(imageUrl)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(imageView);
```

**Layout XML**:
Not relevant

**Stack trace / LogCat**:
```ruby
Request failed 404: Not Found
```

**Comment by sjudd** [comment]
Feel free to take a look at the logic and send a PR with changes. Thanks!

https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/GlideUrl.java#L86

**Comment by TWiStErRob** [comment]
I actually had no problem loading it:
```java
String url = "http://www.dlg.dk/-/media/DLG/Corporate/Landmand/Økologi/DLG-Okologi_haand.ashx";
Glide
		.with(this)
		.load(url)
		.into(imageView)
;
```
![image](https://cloud.githubusercontent.com/assets/2906988/25826781/0ac267e6-3440-11e7-9186-79e8df460d7a.png)

Make sure that the special characters are not escaped in any way when they're in the String that you pass in to Glide. That means that for this specific url `url.charAt(49) == 216`, i.e. this character: http://www.fileformat.info/info/unicode/char/d8/index.htm

```java
Log.wtf("TEST", String.valueOf(url.charAt(49) == 216));
```

If you're hardcoding this url, like I did, make sure your file encoding is UTF-8, similarly if you're getting it from a server make sure the transfer has the correct encoding, and that the JSON/XML/whatever is also decoded correctly.

**Comment by TWiStErRob** [comment]
I also tried OkHttp 2, and it works too. Note that just having OkHttp on the classpath via an unrelated (Retrofit) transitive dependency won't make Glide use it. You have to add the integration library as well:
https://github.com/bumptech/glide/wiki/Integration-Libraries
