### ISSUE TITLE
DiskCache file invaliad.

### ISSUE THREAD

**Issue by 835127729** [bumptech/glide#1899]
I use Glide v4 in my chat app and the users may send pictures frequrently.
In some cases,one user send a pic to the other,the image may load fail.
then I check the url and I'm sure that url is valid.

so I read the source code of Glide and make some breakpoints.
I found there is diskcache of image,but the diskcache is invaliad or impaired.

I pull the dir named "image_manager_disk_cache" from my device.And I append ",jpg" to all the cache file so I can see whether the cache is valiad.

the invaliad file is actually the diskcache for my url. 

my result is as below:
![wangwang20170504171257](https://cloud.githubusercontent.com/assets/5118609/25697380/555649ae-30ed-11e7-81de-a0602cc1544e.png)

My English is poor and I try to describe my  situation carefully.
I have no idea how to reappear this bug and I just send image frequrently and then it happens.

more details:
1、I use DiskCacheStrategy.ALL to load the image.
2、I clear the cache of my app,and then reload the image.This time,the image load successful.

**Comment by 835127729** [comment]
this is the invaliad cache file.
![80fe25f6e4aa0b12fb1e8b4690239abdf4aaa80bd3d6cf4e5477f579e5b94aa1 0](https://cloud.githubusercontent.com/assets/5118609/25697520/dae88b86-30ed-11e7-9363-236517b4b70f.jpg)

**Comment by sjudd** [comment]
How do you retrieve these images? Are they downloaded from the internet? If so, what library do you use to download them?

In our default http library, we try to avoid this with an InputStream subclass that verifies that the number of bytes read matches the content length header (see [``ContentLengthInputStream``][1]).

[1]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/util/ContentLengthInputStream.java

**Comment by 835127729** [comment]
Sorry foring replying you so late.
Indeed,I use default http library.
In this time, some of my users feedback that they cannot load image anymore.
I have not idea what happened and just suggest them to clear the cache.
After doing this,our app can load image normally.

I cant see any log from glide to judge what's wrong.And the gilde just tell me load image fail.
my questions is as followed:
1、how can i track the exeception of glide when i can never use my users's phone.
2、If i discard the default http library and use volley or others, may i avoid this problem?

**Comment by sjudd** [comment]
If anyone can still reproduce this, I'd be curious. We have a lot of checks that try to ensure that we write all data to the disk cache that the server tells us we need to. If any of those checks fail, we don't write the data to cache and will retry on the next request.

We've had a few cases where either servers occasionally returned invalid data or invalid content lengths that break these checks. We've also had a few cases where client implementations of ModelLoaders or DataFetchers were broken and could return partial or invalid data which would cause the same issue. See #2213 for an example
