### ISSUE TITLE
How to get Bitmap from Glide when loading is complete

### ISSUE THREAD

**Issue by Sourav-21** [bumptech/glide#1903]
I just want to have Bitmap variable for further use. Because first I want to check with one URL. If it returns null, then I want to load the image with another URL.

**Comment by TWiStErRob** [comment]
`.listener()` and maybe combine with `.asBitmap()`, but shouldn't be necessary for your described use case.

**Comment by Sourav-21** [comment]
In my case, the url of images changes with time. So I cached image with custom key. That's why I want to first check that the images is cached or not. If not then I want to load image with new url.
