### ISSUE TITLE
Call to override () method, if the incoming width is equal to the height, method of failure

### ISSUE THREAD

**Issue by KevinWard0910** [bumptech/glide#1904]
Set an ImageView width and height to wrap_content, Glide invokes the override (width, height) method, if the incoming of the width and height difference, within 50 images of wide high displays are very small, and show for the first time will not according to override the value is set inside, according to the size but after that would be great.What's the problem

**Comment by TWiStErRob** [comment]
Can you please rewrite your description, I couldn't understand what's your case. Try to make a list of things that happen instead of prose.
