### ISSUE TITLE
Glide loading cropped image at first in viewpager

### ISSUE THREAD

**Issue by Nitish-3379** [bumptech/glide#1908]
**Glide Version**: 3.7.0

**Integration libraries**: No

**Device/Android Version**: Happening on all devices. Tested on Android v5.0+

**Issue details / Repro steps / Use case background**: I am using glide inside Viewpager. The imageview is wrapped inside cardview. When image is loaded at first, the image is appeared cropped. See attached 
 screenshot 
![device-2017-05-05-214901](https://cloud.githubusercontent.com/assets/10203956/25754454/dd122bf2-31dc-11e7-9228-465f81413956.png)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(mContext).load(Util.getAbsoluteImageUrl(banner.getImgScrollBanner())).asBitmap().centerCrop()
                    .placeholder(R.drawable.loading_spinner).error(R.drawable.def_bg).into(bannerView);
```
I tried by replacing `centerCrop()` with `fitCenter()`. The image acquired width leaving a little white space from left and right side. Then, I removed cardview, and now image appeared perfect. It is happening only when I wrap image inside cardview. 

**Layout XML**:
```xml
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:cardCornerRadius="@dimen/margin_three"
    app:cardElevation="@dimen/margin_three">

    <ImageView
        android:id="@+id/main_banner"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        tools:ignore="ContentDescription" />
</android.support.v7.widget.CardView>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by gastsail** [comment]
have you solved it? I'm having the same issue, I know it has past so many time but I think the problem relies on the placeHolder
