### ISSUE TITLE
How to log the time (in ms) it takes to load each image

### ISSUE THREAD

**Issue by fermatijoe** [bumptech/glide#1909]
**Glide Version**: 3.7.0

Hi, I'm using Glide to populate a recycelrview of imageviews with pictures from the internet. I am encountering issues with images loading very slowly (to be fair the pictures have a with of 1000) and so I'm trying to see how long it takes to load each image so that I know if I'm actually fixing the issue or not. is there a log option that resturns the time in ms it takes to download the picture and display it? Thanks

**Comment by TWiStErRob** [comment]
You can get some timings when you enable logging via tags: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

If you want end-to-end/observed time, store the current time in a variable just before `.into()` and inspect the difference in `.listener()` callbacks.

If you share some code we may be able to help you out with common culprits (e.g. GIF should use SOURCE cache only).

**Comment by fermatijoe** [comment]
Hi, thanks for the quick reply, this is my code:

`Glide.with(getActivity())
                    .load(resizedUrl)
                    .crossFade(500)
                    .diskCacheStrategy(DiskCacheStrategy.RESULT)
                    .into(holder.mImageView);`

Where and how can I save the time? I thought about putting this before the glide code:

`Log.v(LOG_TAG, "GLIDE start time: " + System.currentTimeMillis());
Glide.with(getActivity())
                    .load(resizedUrl)
                    .crossFade(500)
                    .diskCacheStrategy(DiskCacheStrategy.RESULT)
                    .into(holder.mImageView);`

But I don't know how to get notified when the image has loaded.

Ragarding my problem i wrote a [quesion here](http://stackoverflow.com/questions/16516888/how-to-get-current-date-time-in-milliseconds-in-android).
