### ISSUE TITLE
imageview can't set image from bitmpat or url by can set by default or from res 

### ISSUE THREAD

**Issue by Adnan9011** [bumptech/glide#1910]
hi all
i have problem with imageview .
i dont khow how to fix it .
i have imageview from adapter . when i set pic from res , imageview work .
when set pic from xml file . it's work .

but .
when set pic from base64 or when set url to it , imageview shows nothing . also my base64 bitmap not large , just 210*150

i think it's depending on  my performance .

i use 

private Bitmap textToBitmap(String input) {
        try {
            byte[] decodedByte = Base64.decode(input, 0);
            return BitmapFactory.decodeByteArray(decodedByte, 0, decodedByte.length);
        } catch (OutOfMemoryError e) {
            Log.e(TAG, e.getMessage() + "");
        } catch (Exception e) {
            Log.e(TAG, e.getMessage() + "");
        }
        return null;
    }

or other code , picasso and glide . but nothing .

**Comment by TWiStErRob** [comment]
Base64 or URL &rare; use `.thumbnail()`, it's preferred to take load off the UI thread.

Bitmap already in memory: `.placeholder(new BitmapDrawable(bm))`.

**Comment by Adnan9011** [comment]
@TWiStErRob thanks for reply , but how can i to fix it ?
i know this issue depending on ui thread or threading , how can i fix this issue ?

thanks in advance

**Comment by TWiStErRob** [comment]
If you use `Glide....load()` you're in the background.

Use the API I mentioned, Google for "Glide custom fetcher", "Glide thumbnail", "Glide base64" for more info.

**Comment by Adnan9011** [comment]
for clide base64 , i use this code , but , this code can't help me :

Glide.with(context)
                .load(parametersCoreGetIPGListResponses.getParameters().get(position).getIPGThumbnail())
                .asBitmap()
                .placeholder(R.drawable.default)
                .into(holder.imageView);

nothing show ...

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by TWiStErRob** [comment]
https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_556_data_uri_from_string

**Comment by Adnan9011** [comment]
@TWiStErRob  my adapter is freeze , and i can't change picture in adapter view .
