### ISSUE TITLE
No option for gif pause 

### ISSUE THREAD

**Issue by FahidMirza** [bumptech/glide#1916]
Is there any way that we can pause gif? and then resume it again.

**Glide Version**: 3.7.1

**Integration libraries**: No

**Device/Android Version**: Galaxy s6

**Comment by TWiStErRob** [comment]
Yes.

**Comment by FahidMirza** [comment]
Kindly can you let me know what it is exactly? @TWiStErRob

**Comment by TWiStErRob** [comment]
Jk, in seriousness: you can get the drawable from ImageView and use `Animatable` or `GifDrawable` directly to control it.

**Comment by FahidMirza** [comment]
Thank you. Will try it.

**Comment by shashank090789** [comment]
@FahidMirza did you find the solution

**Comment by androsathish** [comment]
@TWiStErRob can you explain with bit of code?

**Comment by sjudd** [comment]
```java
Drawable drawable = imageView.getDrawable();
if (drawable instanceof Animatable) {
  ((Animatable) drawable).stop();
}
```

**Comment by androsathish** [comment]
Your code works well for stop(). Is there any chance to pause()

**Comment by sjudd** [comment]
stop is equivalent to pause (at least in v4). If you want to restart the loop when resuming you need to use ``startFromFirstFrame()`` instead of ``start()``.

**Comment by Hitexroid** [comment]
@sjudd imageView.getDrawable() always is null :/

**Comment by sjudd** [comment]
@Hitexroid it will be null until the asynchronous load finishes.

**Comment by Hitexroid** [comment]
Right but i forgot `AsGif`

**Comment by emretekin** [comment]
> ```java
> Drawable drawable = imageView.getDrawable();
> if (drawable instanceof Animatable) {
>   ((Animatable) drawable).stop();
> }
> ```

This is absolutely best answer for that problem. It works for me thanks.

**Comment by yogeshkalwar** [comment]
start will make animation to start from first frame.. is there anyway to resume from last drawn frame?

**Comment by TWiStErRob** [comment]
@yogeshkalwar sounds like that should be the behaviour: https://github.com/bumptech/glide/issues/1916#issuecomment-361016890

**Comment by Mouadabdelghafouraitali** [comment]
Is there any possibility to change the GIF speed ?
