### ISSUE TITLE
希望提供支持同步加载，或者异步加载一组图片的方法

### ISSUE THREAD

**Issue by smallgirl** [bumptech/glide#1918]
在某些特定场景下，比如加载多张本地图片，获取bitmap 然后转换成base64String,传给服务器。使用ImageLoader就可以
/**

     * 将图片转化成base64编码

     */
    public static String imgToBase64Str(String path) {
        long start =System.currentTimeMillis();
        Bitmap bmp = ImageLoader.getInstance().loadImageSync(ImageUtils.IMAGE_FILE+path, new       ImageSize(480, 800), ImageUtils.getDefautDio());
        AppLog.e(System.currentTimeMillis()-start);
        Bitmap bmpt= BitmapUtis.decodeBitmap(path,480,800);
        String s;
        if (bmpt==null){
            s= bitmapToBase64Str(bmp);
        }else {
            s= bitmapToBase64Str(bmpt);
        }
        AppLog.e(System.currentTimeMillis()-start);
        return s;
    }

    public static void imgToBase64Str(String[] urls, final Base64Listener base64Listener) {

        class MyTask extends AsyncTask<String, Integer, String> {
            @Override
            protected void onPreExecute() {

            }
            @Override
            protected String doInBackground(String... params) {
                    List<String> list=new ArrayList<>();
                    for (String str:params){
                        list.add(imgToBase64Str(str));
                    }
                    return JSON.toJSONString(list);
            }

            //onProgressUpdate方法用于更新进度信息
            @Override
            protected void onProgressUpdate(Integer... progresses) {
            }

            //onPostExecute方法用于在执行完后台任务后更新UI,显示结果
            @Override
            protected void onPostExecute(String result) {
                if (base64Listener!=null){
                    base64Listener.onBase64Listener(result);
                }

            }

            //onCancelled方法用于在取消执行中的任务时更改UI
            @Override
            protected void onCancelled() {
            }
        }
        MyTask mTask = new MyTask();
        mTask.execute(urls);
    }

    public interface Base64Listener{
       void onBase64Listener(String string);
    }
如果使用glide 没有同步方法，就不好控制，只能如下：
public static void imgToBase64Str(String[] urls, final Base64Listener base64Listener) {
List<String> list=new ArrayList<>();

        num = urls.length;
        for (String str:urls){

                Glide.with(this).load(str).asBitmap().into(new Target<Bitmap>() {
                    @Override
                    public void onStart() {

                    }

                    @Override
                    public void onStop() {

                    }

                    @Override
                    public void onDestroy() {

                    }

                    @Override
                    public void onLoadStarted(Drawable placeholder) {

                    }

                    @Override
                    public void onLoadFailed(Exception e, Drawable errorDrawable) {

                    }

                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                         num--;
                        // bitmap to base64 code
                        if (0==num){
                            // 全部转换完毕
                        }

                    }

                    @Override
                    public void onLoadCleared(Drawable placeholder) {

                    }

                    @Override
                    public void getSize(SizeReadyCallback cb) {

                    }

                    @Override
                    public void setRequest(Request request) {

                    }

                    @Override
                    public Request getRequest() {
                        return null;
                    }
                });
        }

}

**Comment by mariotaku** [comment]
@smallgirl Glide 支持同步加载，尝试如下代码：
````
load(url).into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).get()
````

To maintainer: This issue is about synchronized loading feature, which is solved by this answer I think.

**Comment by TWiStErRob** [comment]
@mariotaku Yes, that looks good.
@smallgirl Please make sure you clear the `FutureTarget`, see the [class' JavaDoc](http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/request/FutureTarget.html)!

**Comment by wangsuicheng** [comment]
@mariotaku into(500,500) does't work, the height of the bitmap decoded that isn't 500...did you test?

**Comment by mariotaku** [comment]
@wangsuicheng You can combine `load()` with `centerCrop()` or `fitCenter()` to ensure you get the bitmap with size you want.

**Comment by XuQK** [comment]
第一张图是Pixel3 Android10
第二张图是一加6 Android10
都是用的直接下载下来的demo打开的，看宽高，都是0

![WechatIMG217](https://user-images.githubusercontent.com/2867860/72241107-ea8a3180-3620-11ea-9eec-d4d1c18c7ffd.jpeg)
![Screenshot_20200113-161234](https://user-images.githubusercontent.com/2867860/72241203-2d4c0980-3621-11ea-8aff-7db518777589.jpg)

**Comment by oscaryue** [comment]
> @smallgirl Glide 支持同步加载，尝试如下代码：
> 
> ```
> load(url).into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).get()
> ```
> 
> To maintainer: This issue is about synchronized loading feature, which is solved by this answer I think.

Yes, it works. But it is only working on background thread.

**Comment by mariotaku** [comment]
@oscaryue I haven't been developing Android apps for quite a while, but I think such things should be performed in background threads, or it will freeze the UI.
