### ISSUE TITLE
AnimatedGifEncoder -- Encoding is very slow

### ISSUE THREAD

**Issue by j3elam** [bumptech/glide#1923]
**Glide Version**: 3.7.0

**Device/Android Version**: OnePlus 3T / Android 7.1.1

**Issue details / Repro steps / Use case background**: 
The issue is that encoding the first frame takes 2900 ms of the 3100ms used by decoding and encoding all 7 frames(Code in next snippet, not directly below). I traced the problem back and found that the "AddFrame" function has some code that runs only for the FirstFrame, however, it seems like the problem comes from the call to getImagePixels() and analyzePixels() on the first frame. 

How can I make this process faster? 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
TimingLogger time = new TimingLogger("J","Decode/Encode");
                    for (int i = 0; i < resource.getDecoder().getFrameCount()/4 +1; i++) {
                        resource.getDecoder().advance();
                        Decoded_Gif[i] = resource.getDecoder().getNextFrame();
                        Decoded_Gif[i] = transform(Decoded_Gif[i], 320, 320, TransformType);
                        Decoded_Gif[i] = RoundImageTransform.circleCrop(pool,Decoded_Gif[i], true);
                    }
                    time.addSplit("Decode Complete");  <== THIS ENTIRE FOR LOOP TAKES ROUGHLY 40 ms
                    ByteArrayOutputStream bos = new ByteArrayOutputStream();
                    AnimatedGifEncoder a = new AnimatedGifEncoder();
                    a.start(bos);
                    a.setQuality(20); //FIXME Default quality is 10, minimum 1 , max 256,lower is better
                    int delay = resource.getDecoder().getDelay(0);//his is an arbitrary frame (1) since delays are the same
                    a.setDelay(delay);
                    for (int j = 0; j < resource.getDecoder().getFrameCount() /4 +1; j++) {                     
                        time.addSplit("add 1 frame start");
                        a.addFrame(Decoded_Gif[j]);
                        time.addSplit("Add 1 frame FINISH");
                    }
                    a.finish();
                    time.addSplit("Encode Finish"); <== THIS ENTIRE FOR LOOP TAKE 3100 ms, but encoding the first frame uses 2900 ms 
                    time.dumpToLog();
                    try{
                        //only save if  it has been closed
                        bos.close();
                        editedImage = bos.toByteArray();
                        //FIXME Debugging
                    }catch(IOException io){
                        Log.e(TAG,"Error trying to close Cropped Gif/Image Byte Output Stream");
                    }
```
![image](https://cloud.githubusercontent.com/assets/14875933/25993488/6c861528-370a-11e7-8aae-7482fd7675ed.png)

**Comment by sjudd** [comment]
You're welcome to look through the code and see if you can do anything that would speed it up. In general we're moving away from that library, mostly because of the speed issues.

**Comment by j3elam** [comment]
@sjudd Does "moving away" mean deprecating and not re-implementing in future versions, or moving to a more efficient solution?

**Comment by sjudd** [comment]
Sorry I missed your response, but in Glide v4 we avoid this by not writing transformed GifDrawables to the disk cache unless you specifically include an integration library. By default we only write the original bytes to disk, which doesn't require us to perform this super expensive encoding process that wastes CPU and disk space.
