### ISSUE TITLE
svg

### ISSUE THREAD

**Issue by kyaw-san-oo** [bumptech/glide#1925]
**Glide Version/Integration library (if any)**:
**Device/Android Version**:
**Issue details/Repro steps**:

**Glide load line**:
```
Glide.with(context)...;
```

**Stack trace**:
```
paste stack trace here
```

**Comment by TWiStErRob** [comment]
v3: https://github.com/bumptech/glide/tree/3.0/samples/svg
v4: https://github.com/bumptech/glide/tree/master/samples/svg
