### ISSUE TITLE
Load image from cache while and load new image from url on top of it

### ISSUE THREAD

**Issue by gwidaz** [bumptech/glide#1926]
**This is not an issue, but the question**

I have been banging my head over this and I have been trying to work around the solution, but I have no idea if using Glide is possible in first place, if so, can someone point me to the direction for the information?

The Glide is perfect for my app, but there is 1 disadvantage when user changes an image, the app will still show images from the cahce and never sync with the new image from the url unless user deletes cache manually.

How do I (using Glide) can load image from the cache by default if the image exist in the cache (to avoid empty ImageViews and loading time) and then fetch in the bg the image from the url and replace it with the one in cache?

**Comment by sjudd** [comment]
Use [thumbnail()][1] API. Make the request you pass into the ``thumbnail()`` method match the old url that might be in the disk cache and the main request match the new url. Glide will load the old url from cache if it's available, but will always eventually replace it with the main request. 

[1]: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/RequestBuilder.html#thumbnail-com.bumptech.glide.RequestBuilder-.

**Comment by sough** [comment]
Hi, how to do the same but when url is constant and images are changing

**Comment by sjudd** [comment]
You can still use thumbnail, but you'll need to add a signature each time the image changes if the url is constant, see http://bumptech.github.io/glide/doc/caching.html#custom-cache-invalidation
