### ISSUE TITLE
the picture which in the RecycleView will change its own size

### ISSUE THREAD

**Issue by wu-liao-de-ren-sheng** [bumptech/glide#1928]
![image](https://cloud.githubusercontent.com/assets/11866678/26045461/f7459610-397c-11e7-9a21-b716d304f299.png)
![image](https://cloud.githubusercontent.com/assets/11866678/26045470/029e1a14-397d-11e7-8e32-bcf5e785a126.png)

init ImageView
`ImageView imageView = new ImageView(context);
 imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
`

load ImageView
`Glide.with(context)
                .load(path)
                .asBitmap()
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .placeholder(placeholder)
                .into(imageView);`

ImageView size 16:9

**Comment by wu-liao-de-ren-sheng** [comment]
在RecycleView滑动的时候图片会变大变小。ImageView大小不会变，会变的是ImageView的内容

**Comment by sjudd** [comment]
What version? 3.8.0? 4.0.0?

**Comment by wu-liao-de-ren-sheng** [comment]
3.7.0  The reason is my custom layout。Layout after load

**Comment by Likeyong** [comment]
> 在RecycleView滑动的时候图片会变大变小。ImageView大小不会变，会变的是ImageView的内容

我也遇到了这个问题,在使用recyclerview setSpanSizeLookup 这个功能后就出现了这个问题.想问一下您是怎么解决这个问题
