### ISSUE TITLE
picture's color is #f7fbf7 or #ffffff

### ISSUE THREAD

**Issue by MarsToken** [bumptech/glide#1929]
![picture](https://cloud.githubusercontent.com/assets/16185910/26060356/610004fc-39b7-11e7-96d6-7290319c189e.png)
I use the glide to load my picture according to url,but I find a issue.
I use default DecodeFormat.PREFER_RGB_565.When I load picture,the imageview show the picture as #f7fbf7 or #ffffff ,but the explorer show as #fdfdfd
This is url:https://test.dfs.fe520.com/group1/M00/E1/3C/ChpRNFkZGECAPZbHAAAfWvKd658791.jpg
I don't know how to change it to the picture as explorer.
Thanks for your answer.

**Comment by TWiStErRob** [comment]
You need to use 8888. Remember that not all colors are representable in 565. It's half the bit size: 4294967296 VS 65536 colors.

**Comment by MarsToken** [comment]
I know the RGB doesn't contain alpha,but when I use the 8888,the src (I mean that is show as #fdfdfd in the explorer,it's like backgroud,but real not)of the imageview that show the picture is #fdfdfd(it is right as the same with the explorer) or #fcfcfc(it is not  that I want to show).Two colors maybe random .

**Comment by TWiStErRob** [comment]
Sorry, that's a mistake on my part about the alpha, but you still need to take into account 24 bit VS 16 bit of color range. It's just physically not possible to represent all colors in 565.

**Comment by MarsToken** [comment]
perfect ! thank you.
