### ISSUE TITLE
where is the default path of distcache?

### ISSUE THREAD

**Issue by MarsToken** [bumptech/glide#1935]
I use diskCacheStrategy(DiskCacheStrategy.ALL);
but I can't find the SDCard/Android/data/app's package/cache/image_manager_disk_cache;
I only find the cache in the data/data/app's package/cache/image_manager_disk_cache;
You know the internal storage is too little,Why not  put them on SDCard as the default?

**Comment by sjudd** [comment]
See https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/cache/ExternalCacheDiskCacheFactory.java

https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/cache/InternalCacheDiskCacheFactory.java

**Comment by TWiStErRob** [comment]
See also https://github.com/bumptech/glide/wiki/Configuration#disk-cache

And note that not all devices have "SD cards", but all of them have internal storage.
