### ISSUE TITLE
4.0.0-RC0 Failed to resolve gifdecoder

### ISSUE THREAD

**Issue by FioneraGH** [bumptech/glide#1938]
Error:Failed to resolve: com.github.bumptech.glide:gifdecoder:4.0.0-RC0
<a href="openFile:/home/fionera/Git/EsonShop/base/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Glide Version**:4.0.0-RC0

**Integration libraries**:No

**Device/Android Version**:gradle sync failed

pom issue? thx

**Comment by yubaokang** [comment]
the  same!

**Comment by sonzerolee** [comment]
the same to me

**Comment by sjudd** [comment]
Sorry I think the maven push got messed up, you can use the jar for now. I've uploaded a new version, so hopefully this will be resolved in a few hours. Thanks for letting me know.
