### ISSUE TITLE
Cannot resolve symbol 'GlideApp' 

### ISSUE THREAD

**Issue by sonzerolee** [bumptech/glide#1939]
I'm trying to use glide 4.0.0-RC0 by Gradle:
> dependencies {
>     compile 'com.android.support:appcompat-v7:25.1.0'
>     compile 'com.caverock:androidsvg:1.2.2-beta-1'
>     compile 'com.github.bumptech.glide:glide:4.0.0-RC0'
>     compile 'com.android.support:support-v4:25.3.1'
> }

I followed the example here: [https://github.com/bumptech/glide/tree/master/samples/svg/src/main/java/com/bumptech/glide/samples/svg](https://github.com/bumptech/glide/tree/master/samples/svg/src/main/java/com/bumptech/glide/samples/svg)
but after add glide by Gradle, I got error: **Cannot resolve symbol 'GlideApp'**
My source:

> package com.example.quangson.glidesvg;
> 
> import android.support.v7.app.AppCompatActivity;
> import android.os.Bundle;
> import static com.bumptech.glide.load.resource.drawable.DrawableTransitionOptions.withCrossFade;
> 
> import android.content.ContentResolver;
> import android.graphics.drawable.PictureDrawable;
> import android.net.Uri;
> import android.widget.ImageView;
> import android.widget.LinearLayout;
> 
> import com.bumptech.glide.RequestBuilder;
> import com.example.quangson.glidesvg.glide.SvgSoftwareLayerSetter;
> 
> public class MainActivity extends AppCompatActivity {
> 
>     private static final String TAG = "SVGActivity";
> 
>     private ImageView imageViewRes;
>     private ImageView imageViewNet;
>     private RequestBuilder<PictureDrawable> requestBuilder;
>     LinearLayout ll;
> 
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         setContentView(R.layout.activity_main);
> 
>         imageViewNet = (ImageView) findViewById(R.id.svg_image_view2);
> 
>         requestBuilder = GlideApp.with(this)
>                 .as(PictureDrawable.class)
>                 .placeholder(R.drawable.image_loading)
>                 .error(R.drawable.image_error)
>                 .transition(withCrossFade())
>                 .listener(new SvgSoftwareLayerSetter());
> 
>         Uri uri = Uri.parse("http://www.clker.com/cliparts/u/Z/2/b/a/6/android-toy-h.svg");
>         requestBuilder.load(uri).into(imageViewNet);
>     }
> }

Please help

**Comment by sjudd** [comment]
You need to add the annotationProcessor dependency:

```groovy
annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC0'
```

You also need to add an [AppGlideModule][1]. See the [generated API][2] documentation for details. 

[1]: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/module/AppGlideModule.html
[2]: http://bumptech.github.io/glide/doc/generatedapi.html

**Comment by bajicdusko** [comment]
@sjudd I've stumbled on this one as well, somehow with readme reading, @GlideModule part is skipped. Maybe it'd be useful to add it as part of the readme for v4. Just a suggestion :).

**Comment by rigo-ptz** [comment]
I have the same problem, but my code contains all necessary dependencies
`compile "com.github.bumptech.glide:glide:4.0.0-RC1"`
`annotationProcessor "com.github.bumptech.glide:compiler:4.0.0-RC1"`
`   compile "com.github.bumptech.glide:okhttp3-integration:4.0.0-RC1"`
`compile 'com.android.support:support-v4:25.3.1'`
and
```
@GlideModule
public class MyGlideModule  extends AppGlideModule
```
Android Studio 2.3.3, Gradle 3.5.5, Android Gradle 2.3.3.

I've read other issues but didn't find anything helpful there.

**Comment by MichaelHader** [comment]
Hi,
i have the same problem and found out, that the plugin 'com.neenbedankt.android-apt' causes the problem.
When i removed this plugin and uses annotationprocessor for all apt dependencies it works and GlideApp was generated.
Maybe it helps someone else too.

**Comment by xuehuashi** [comment]
@MichaelHader  i also do it,but it's still not generate glideapp

**Comment by zeroarst** [comment]
In my case I am using Android Studio 3.0 beta2 in app build.gradle I have 
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
```

I have to use `kapt 'com.github.bumptech.glide:compiler:4.0.0'` instead of `annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'`

**Comment by artemtkachenko** [comment]
same issue: Cannot resolve symbol 'GlideApp'

Added all dependencies and annotationProcessor and @GlideModule and it still does not work.

Seems this lib is not awesome anymore.

**Comment by kenk11** [comment]
Same issue here
I'm using Kotlin and update with `kapt 'com.github.bumptech.glide:compiler:4.0.0'`
and already add annotation `@GlideModule` but `GlideApp` was not generated

**Comment by kenk11** [comment]
Hi all,
I found solution for this case, 
I'm using Android Studio 3.0 Canary version so I need to include `apply plugin: 'kotlin-kapt'` in app gradle
You can see more detail at here:
https://kotlinlang.org/docs/reference/kapt.html

**Comment by ljaniszewski** [comment]
@kenk11 The only solution that worked! Thanks mate. 
And this -> http://bumptech.github.io/glide/doc/getting-started.html 

is a joke. 
You are making big change in a library that is used by half of android world and you can't even do a proper explaination. 

Yeah, do a module class, and you're done. Bs. Where do I put this class? Can it be in some kotlin file alongside other classes? Does it need any contents or must be empty? What are the benefits of new system? What particular errors mean and how to solve them?

**Comment by TWiStErRob** [comment]
@ljaniszewski 
> ... is a joke. You are making big change in a library that is used by half of android world and you can't even do a proper explaination.

don't need that tone... it is open source and most of the maintenance and support is done in free time. Feel free to contribute a better documentation: http://bumptech.github.io/glide/dev/contributing.html#documentation

> Where do I put this class? Does it need any contents or must be empty?

Have you opened "*See Glide’s [generated API page](http://bumptech.github.io/glide/doc/generatedapi.html) for more information.*"? http://bumptech.github.io/glide/doc/generatedapi.html#kotlin

> What are the benefits of new system?

http://bumptech.github.io/glide/doc/generatedapi.html#about
http://bumptech.github.io/glide/doc/migrating.html#generated-api

> What particular errors mean and how to solve them?

I think GitHub issues already cover most of them. As far as I remember the resolution was always a missing step from these linked pages.

> The only solution that worked!

I think your case is also similar, you missed a step at http://bumptech.github.io/glide/doc/generatedapi.html#kotlin where it links to https://kotlinlang.org/docs/reference/kapt.html

**Comment by kenk11** [comment]
@ljaniszewski 
> You are making big change in a library that is used by half of android world and you can't even do a proper explaination.

Lol I just share my solution and take a brief 
Why you are too serious ?

**Comment by DCRichards** [comment]
@kenk11 Thank you for pointing this out. I've now [submitted with a PR](https://github.com/bumptech/glide/pull/2435) to include this in the docs, looks like it'll be in v4.2.

**Comment by kenk11** [comment]
@DCRichards your welcome :)

**Comment by Redman1037** [comment]
Same issue with me , it worked fine with me in previous project , but in this project i am facing this issue

  i am using all dependencies
 
    compile 'com.github.bumptech.glide:glide:4.3.1'
    compile 'com.github.bumptech.glide:annotations:4.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'

also included glide module

   import com.bumptech.glide.annotation.GlideModule;
   import com.bumptech.glide.module.AppGlideModule;

    @GlideModule
    public final class MyAppGlideModule extends AppGlideModule {

    }

Tried clean,rebuild,make ,project,   also did invalidate cache and restart but the issue still exists,
is there any thing else i can do ?

I like the old glide where we added only 1 dependency and worked perfectly fine.

**Comment by Redman1037** [comment]
Ok found out the cause   after an hour of struggle . There was another issue in my project so my project was unable to build successfully , so GlideApp was not built  hence showing this error . All the errors at the starting were of GlideApp and main error was hiding somewhere in the middle . 

So guys if you did every thing i mentioned above and still getting this error the please check if there is some other issue in the project which is stopping build.

**Comment by DCRichards** [comment]
@Redman1037 I've noticed that Android Studio 3.x is quite selective with its error output, I'd recommend using the command line and inspecting the more verbose output. it's saved me on numerous occasions.

**Comment by xuie0000** [comment]
我遇到一类这问题，其实是后面出现的错误引起的这个提示，仅仅是显示在前面，以为是GlideApp的错误，其实是后面的错误

**Comment by LloydBlv** [comment]
for anyone who is still facing this issue:
in my case I had the 

>   implementation 'com.github.bumptech.glide:glide:4.4.0'
in my library module's build.gradle and the 

> kapt 'com.github.bumptech.glide:compiler:4.4.0'

inside my application module's build.gradle and the GlideApp class was not generated.

I ended up with having both dependencies inside my application module's build.gradle file!

**Comment by wilburt** [comment]
For those experiencing this issue, also make sure `annotationProcessor 'com.github.bumptech.glide:compiler:4.X.X` is added to module level build.gradle

**Comment by xiaoc024** [comment]
Other dependencies use annotationProcessor like butterknife may casue this problem. So check out other annotations' correctness first may be help. 
e.g. I used butterknife and used @BindView(R.id.xx)  but haven't the View to be bind under this code. delete this annotation then clean and make project will be useful.

**Comment by iamutkarshtiwari** [comment]
This is the only answer the solved my this issue for me - https://stackoverflow.com/a/46638213

This configuration worked for me - 
- In app module gradle -
```
    implementation "com.github.bumptech.glide:glide:${glide_version}"
    implementation "com.github.bumptech.glide:okhttp3-integration:${glide_version}"
    kapt "com.github.bumptech.glide:compiler:${glide_version}"
```
- In app proguard -
```
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep class com.bumptech.glide.GeneratedAppGlideModuleImpl
```
- My Custom Glide module class -
```
package com.github.iamutkarshtiwari.glidedemoapp;

import android.content.Context;

import com.bumptech.glide.Glide;
import com.bumptech.glide.GlideBuilder;
import com.bumptech.glide.Registry;
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.integration.okhttp3.OkHttpUrlLoader;
import com.bumptech.glide.load.model.GlideUrl;
import com.bumptech.glide.module.AppGlideModule;

import java.io.InputStream;

import okhttp3.OkHttpClient;

@GlideModule
public final class OkHttp3GlideModule extends AppGlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        super.applyOptions(context, builder);
    }

    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        OkHttpClient client = new OkHttpClient.Builder()
                .build();

        OkHttpUrlLoader.Factory factory = new OkHttpUrlLoader.Factory(client);

        glide.getRegistry().replace(GlideUrl.class, InputStream.class, factory);
    }
}

```

### Note-
- Glide 4.0 need not have "GlideModule" declaration in AndroidMinifest.xml
- You need to `Make project` in order to generate `GlideApp` class

**Comment by mkmckenna** [comment]
Tried just about everything on multiple different SO questions to solve this issue. GlideApp is still not generating. This entire approach just seems like bad design to me and the fact so many people are having a problem is worrying.

**Comment by almalikiy** [comment]
I tried to use Glide 4.80 and stuck for a few days, even after following download & setup page.
Clean project, make project didn't work.

finally, works after deleted build directory and rebuild.

**Comment by sadaharusong** [comment]
> Hello everyone,
> 
> Seems like great discussion going on. Don't worry. I have solution.
> 
> **Follow the steps:**
> 
> * Add dependency as follow (I used latest version)
> 
> ```
> implementation 'com.github.bumptech.glide:glide:4.8.0'
> annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
> ```
> * Create package (as I always used structured code) `myglide` and **copy/paste** following class:
> 
> ```
> @GlideModule
> public class SampleGlideModule extends AppGlideModule {
>     @Override
>     public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
>         super.applyOptions(context, builder);
>     }
> }
> ```
> * Now you can press **CTRL+F9** OR you can click on `Make Project` option in **Build** menu. It will **_generate one file automatically_** (You can see by pressing **CTRL** and hover on **ClassName** in File.
> 
> ```
> final class GeneratedAppGlideModuleImpl extends GeneratedAppGlideModule {
>   private final SampleGlideModule appGlideModule;
>   ....
> }
> ```
> Now you can use **GlideApp** very easily. 
> 
> Hope it will helps you.
> 
> I love Glide as always. <3

Gradle sync failed: Could not resolve all dependencies for configuration ':MyProject:x86DebugRuntimeClasspath'.
				Could not determine artifacts for com.github.bumptech.glide:glide:4.8.0
				Could not get resource 'https://jcenter.bintray.com/com/github/bumptech/glide/glide/4.8.0/glide-4.8.0.aar'.
				Could not HEAD 'https://jcenter.bintray.com/com/github/bumptech/glide/glide/4.8.0/glide-4.8.0.aar'.
				Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/143.204.194.185, d29vzk4ow07wi7.cloudfront.net/143.204.194.28, d29vzk4ow07wi7.cloudfront.net/143.204.194.133, d29vzk4ow07wi7.cloudfront.net/143.204.194.97] failed: Read timed out
				Read timed out
				Consult IDE log for more details (Help | Show Log) (2 m 12 s 770 ms)


When I use your solution, andorid studio get this error log... have you even been have this error before?

**Comment by pratikbutani** [comment]
> @pratikbutani
> 
> > Hello everyone,
> > Seems like great discussion going on. Don't worry. I have solution.
> > **Follow the steps:**
> > 
> > * Add dependency as follow (I used latest version)
> > 
> > ```
> > implementation 'com.github.bumptech.glide:glide:4.8.0'
> > annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
> > ```
> > 
> > * Create package (as I always used structured code) `myglide` and **copy/paste** following class:
> > 
> > ```
> > @GlideModule
> > public class SampleGlideModule extends AppGlideModule {
> >     @Override
> >     public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
> >         super.applyOptions(context, builder);
> >     }
> > }
> > ```
> > 
> > * Now you can press **CTRL+F9** OR you can click on `Make Project` option in **Build** menu. It will **_generate one file automatically_** (You can see by pressing **CTRL** and hover on **ClassName** in File.
> > 
> > ```
> > final class GeneratedAppGlideModuleImpl extends GeneratedAppGlideModule {
> >   private final SampleGlideModule appGlideModule;
> >   ....
> > }
> > ```
> > Now you can use **GlideApp** very easily.
> > Hope it will helps you.
> > I love Glide as always. <3
> 
> Gradle sync failed: Could not resolve all dependencies for configuration ':MyProject:x86DebugRuntimeClasspath'.
> Could not determine artifacts for com.github.bumptech.glide:glide:4.8.0
> Could not get resource 'https://jcenter.bintray.com/com/github/bumptech/glide/glide/4.8.0/glide-4.8.0.aar'.
> Could not HEAD 'https://jcenter.bintray.com/com/github/bumptech/glide/glide/4.8.0/glide-4.8.0.aar'.
> Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/143.204.194.185, d29vzk4ow07wi7.cloudfront.net/143.204.194.28, d29vzk4ow07wi7.cloudfront.net/143.204.194.133, d29vzk4ow07wi7.cloudfront.net/143.204.194.97] failed: Read timed out
> Read timed out
> Consult IDE log for more details (Help | Show Log) (2 m 12 s 770 ms)
> 
> When I use your solution, andorid studio get this error log... have you even been have this error before?

No, I never ever got this type of error. I am using latest version of Android Studio.

**Comment by Suaix** [comment]
Same question happened when i update android studio to v3.2.1, but GlideApp works fine in android studio v2.3.0 with same build config and same version of glide(glide v4.0.0). 
Here is my build config and glideModule class:
`dependencies {
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'
    compile 'com.github.bumptech.glide:glide:4.0.0'
}`
`@GlideModule
public class UxinGlideModule extends AppGlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        super.applyOptions(context, builder);
        //将缓存设置为外部缓存
        builder.setDiskCache(new ExternalCacheDiskCacheFactory(context, 1024 * 1024 * 100))
                .setMemoryCache(new LruResourceCache(1024 * 1024 * 20))
                .setLogLevel(Log.ERROR);
    }

    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }

}`
Has anyone experience this question? How to fix it?

**Comment by pratikbutani** [comment]
Have you tried this: press **CTRL+F9** OR you can click on **Make Project** option in Build menu. It will generate one file automatically (You can see by pressing CTRL and hover on ClassName in File.

**Comment by Suaix** [comment]
I have tried Make Project and rebuild, it generate GlideApp in build/generated, but just can not found the symbol, have no idea why cannot resolve the symbol.

**Comment by XF-zhjnc** [comment]
Maybe you should use the **latest version** of `com.github.bumptech.glide:compiler`.
e.g.
```gradle
dependencies { 
    implementation('com.github.bumptech.glide:glide:4.7.1') {
        exclude group: 'com.android.support'
    }
    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'   // use latest version
}
```

**Comment by denis-simplex** [comment]
For me solving this was run in terminal: 

gradle assemble --stacktrace

and solve issues not related with Glide

**Comment by tilalapradip** [comment]
See here Kotlin guideline to Add Glide to Your App:
http://bumptech.github.io/glide/doc/generatedapi.html#kotlin
If you’re using Kotlin you can:
**1.** Implement all of Glide’s annotated classes (AppGlideModule, LibraryGlideModule, and GlideExtension) in Java as shown above.
**2.** Implement the annotated classes in Kotlin, but add a kapt dependency instead of an annotationProcessor dependency on Glide’s annotation processor:

**Comment by varunam** [comment]
> Ok found out the cause after an hour of struggle . There was another issue in my project so my project was unable to build successfully , so GlideApp was not built hence showing this error . All the errors at the starting were of GlideApp and main error was hiding somewhere in the middle .
> 
> So guys if you did every thing i mentioned above and still getting this error the please check if there is some other issue in the project which is stopping build.

True. I observed the same.

**Comment by ssjsaha** [comment]
Well In my case apply plugin: 'kotlin-kapt' caused the ERROR . . 
So ,If you are usningit with only java, Removing kotlin-kapt plugin could solve your case . Thanks :)

**Comment by Mihir3646** [comment]
There could be your project level error and just **### check at the bottom of the GlideApp error** you will find the issue causing this. In my case, it was `Parcelable` POJO class which also extends `RealmObject` there was no public construction with no argument.

**Comment by jeffreyliu8** [comment]
my solution is simply using replace "implementation" with "kapt" in gradle on glideCompiler.

**Comment by pratikbutani** [comment]
Have you checked it?  https://stackoverflow.com/a/58267685/1318946
