### ISSUE TITLE
what would happen if cancel() is not implemented when use OkHttpStreamFetcher.java in 3.8.0?

### ISSUE THREAD

**Issue by BottleChain** [bumptech/glide#1940]
hi guys, i use glide 3.8.0 snap-short, and my app had been online for a while. recently, some users told me that their app can't show images....i tried some, and finally found that where the problem might be:

you see i use okhttp3 like this: https://github.com/bumptech/glide/blob/3.0/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpStreamFetcher.java

but i forgot to implement the cancel() method in OkHttpStreamFetcher...

the origin is  :
` 
@Override
    public void cancel() {
        Call local = call;
        if (local != null) {
            local.cancel();
        }
    }
`

but mine is: 
`
@Override
    public void cancel() {
      // nothing
    }
`

so I want to know that, whether this code would lead to used for app to stopp showing images? 

any help would be appreciated! 
Thanks a lot!

**Comment by BottleChain** [comment]
any help may save my life....

**Comment by sjudd** [comment]
It could lead to delays if you queue up a bunch of requests by scrolling through a large number of photos. I'm not sure whether or not it would stop images from loading altogether (I wouldn't expect it to). It might be slow enough though that it would be hard to tell the difference.
