### ISSUE TITLE
How to use 4.0.0

### ISSUE THREAD

**Issue by luhuanxml** [bumptech/glide#1941]
Why not update README  file.

**Comment by TWiStErRob** [comment]
Because it's not final. See http://sjudd.github.io/glide/ for current state.

**Comment by luhuanxml** [comment]
thanks





在 Róbert Papp <notifications@github.com>，2017年5月18日 17:40写道：

Because it's not final. See http://sjudd.github.io/glide/ for current state.

**Comment by sjudd** [comment]
readme is also now updated, though basically the usage is the same if you use the generated api.
