### ISSUE TITLE
Glide.with(context).using(*) in Glide 4

### ISSUE THREAD

**Issue by FrancoisBlavoet** [bumptech/glide#1942]
Hi,

I am trying to build a flexible ModelLoader for Glide.

Use case : we have tons of different objects loaded with Glide, backed by the same API's ImageUrlGenerator.  
We have many variations : the spec of the image (png, jpeg, squarred, cropped, fixed height + ratio, etc) as well as the loading strategy (just load from network, query the synchro module, etc).  

In order to simplify this, I am in the process of writing a single ModelLoader + ModelFetcher which can be configured.  

The idea is to create the model loader and configure it, then use it for the corresponding loads : 

```
RequestManager.ImageModelRequest<IImage> request =  Glide.with(context).using(new ImageLoader(context, imageSpec, loadingStrategy));

//also configure the load itself : 
this.loader = Glide.with(context).using(request).from(IImage.class).placeholder(R.drawable.placeholder);

```

then I can inject this loader object in my viewholder and keep it as a field in order to use itfor different loads, it will honor this spec & strategy.
It will also applies all the options chosen after the `from` call  (placeholder, transformation, etc

```
loader.load(image).into(view);
```

1 - is that a correct approach ? the 'from' does not feel really idiomatic. However I have tested it and it works !

2- I have looked at Glide 4, it looks like the using() API has been removed (fair enough, it was marked as experimental).  Is there a replacement for this in Glide 4 ? or another way to attain the same result ? or should I create a ticket to port this API to Glide 4 ?

**Comment by sjudd** [comment]
In Glide 4 you can just register your ModelLoader once and it will automatically be used whenever you pass in your model. See the [Flickr sample app][1] for an example.

If you want to specify a particular set of options along with your, you can add a [GlideExtension][2] with a method that applies the set of options you want. Your usage would then look something like:

```java
GlideApp.with(fragment)
  .load(image)
  .yourOptionSetMethodName()
  .into(view)
```

[1]: https://github.com/bumptech/glide/blob/master/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrGlideModule.java
[2]: http://bumptech.github.io/glide/doc/generatedapi.html#glideextension

**Comment by Teovald** [comment]
Maybe I have not been clear enough ^^ 

I want to have only one kind of model (an IImage interface)  
and be able to configure my modelLoader.  

I can post a sample if it is not clear.

All my models implement IImage.
IImage allows me to build an url (with something like getModelId() & getModelImageType()).  


In addition to that,  

I want to be able to pass a configuration to the ModelLoader (and Fetcher, but the loader can pass it to the fetcher).  
This configuration can be different from one ModelLoader to another, so I don't want a GlideModule.  

Also, I don't think a GlideExtension will work here, this is not just an Options, this is the ModelLoader itself I need to access.

**Comment by sjudd** [comment]
Sorry I wasn't especially clear either. There is no way to pass in a ModelLoader. There are alternatives that allow similar functionality.

You can:

1. Use a different model (including different implementations of IImage)
2. Add parameters to your model that lets the appropriate ModelLoader decide whether or not it should handle it (you can register multiple ModelLoaders for a given type)
3. Add options that configure how your ModelLoader behaves (including delegating if you want) and pass them in explicitly.

The third option would work well with GlideExtension.

**Comment by Teovald** [comment]
Thanks for the quick answer !

1. & 2 I guess it is always an option. The data layer only provides the image's url, but the viewModel could indeed add this information.

3. sounds like what I want to do ! 

So for 3, I would do something like : 

```    request = Glide.with(this)
        .asDrawable()
        .transition(...)
        .apply(new RequestOptions()
                .centerCrop()
                .placeholder(R.drawable.ic_android_24dp)
                .set(new Option<Integer>("my.app.package.", OPTION_VALUE, new Option.CacheKeyUpdater<Object>() {
                  @Override
                  public void update(byte[] keyBytes, Object value, MessageDigest messageDigest) {
                    messageDigest.update(keyBytes); // NOT SURE ABOUT THIS YET
                  }
                })
                .autoClone());
```

?  
And then I would get the options map in my ModelLoader ?
That sounds like what I want to do 👍 

If this is correct, should I write some documentation for this ?

**Comment by sjudd** [comment]
Yeah that's pretty much it. You can use a GlideExtension to replace the ``set()`` call with a new method that's somewhat more fluent. I also typically define options where they're used. You can also use an in memory option if you don't expect your option to change how data is cached on disk. If you do, then you want to add the key bytes and some other set of bytes that represents the particular value you're using. Ie you want your cache key to include both that your option was set and what it was set to.

If you'd like, I'd be happy to accept a PR for the gh-pages branch with some documentation on this. You could add to the migration page, or create your own. See [contributing][1] for more info.

[1]: http://bumptech.github.io/glide/dev/contributing.html#documentation

**Comment by Teovald** [comment]
I finally had some time to spend on Glide.   

So I spent a while on migrating everything to Glide 4.  

It works like a charm !  
Very happy with the migration overall  

Some feedback :  

- the `lock()` / `autoclone()` mechanism is a bit hidden. It would help to document this so you don't shoot yourself in the foot while reusing `RequestOptions`

- It is very unclear why Glide applies a transition or not on a load. I still need to look into it but the behavior looks very different from Glide's 3 one for some reason, with many images skipping the crossfade while they come from `LOCAL` or `REMOTE` datasources.

- I was going to suggest changing the namespace in order to facilitate the transition. So when you are rewriting a large codebase, you can have both implementations at the same time (without actually shipping in that state). But in practice the transition was smooth enough that I don't think it is necessary.

**Comment by sjudd** [comment]
Thanks for he feedback. Yeah lock/autoclone is hidden. Frankly we probably should have used a Builder pattern for those and made them immutable. It was probably an over optimization to save the single object allocation. 

In theory Glide should apply a transition by default unless the image is loaded from the memory cache. 

Glad to hear the migration is relatively simple.

**Comment by Teovald** [comment]
> Thanks for he feedback. Yeah lock/autoclone is hidden. Frankly we probably should have used a Builder pattern for those and made them immutable. It was probably an over optimization to save the single object allocation.

Well, less allocations are always better when it comes to lists, so even though it is a bit extreme, I think it is ok. IMO it should just be added to the options documentation.   

> In theory Glide should apply a transition by default unless the image is loaded from the memory cache.

I can't reproduce this behavior :/ 
Even when I try with the flicker (and removing the `dontAnimate()` call) or gallery samples, I don't get any animation when the images are loaded.  
Unless I use `withCrossfade()` of course.

**Comment by sjudd** [comment]
Ah so yes, we removed the cross fade transition. It can cause a lot of issues, especially when placeholders are used. You can still apply a transition yourself and any of the built in transitions should by default run when anything is loaded from anywhere but the memory cache.

**Comment by Teovald** [comment]
hmm

I guess I should open another ticket to discuss crossfade and these issues.  

I can understand that for something like let's say a messaging app, no animation is a good default.  

For more content centric apps, I know that I need crossfade in most cases when the image does not come from cache.
