### ISSUE TITLE
How to force a refetch? (Skip cache?)

### ISSUE THREAD

**Issue by liuzhen2008** [bumptech/glide#1943]
I have a image that updates itself constantly.

I wonder if there is a way to set the cache to a specific time? Say, 30 seconds? 

So the next time it loads the image, it should attempt to reload if it has been more than some set timer.

Is this something already supported?

Thanks

**Comment by sjudd** [comment]
It's not possible to expire cache entries at the moment. That said, you can manually change the cache key you use, see https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#custom-cache-invalidation.

**Comment by TWiStErRob** [comment]
You'll likely want a signature that changes every 30 seconds, see #996.

**Comment by liuzhen2008** [comment]
@TWiStErRob I think the signature is exactly what I need. I will just use the updateAt timestamp as the signature.
