### ISSUE TITLE
Does RecyclerViewPreloader still make sense ?

### ISSUE THREAD

**Issue by FrancoisBlavoet** [bumptech/glide#1951]
**Glide Version**: 4.0

**Integration libraries**: RecyclerView

Since RecyclerView now prebinds views (see [link](https://medium.com/google-developers/recyclerview-prefetch-c2f269075710) for reference), does it still make sense to have an extension to preload bitmaps in Glide ?

**Comment by sjudd** [comment]
I'd imagine it depends. Not all layout managers use pre-binding (custom ones have to explicitly support it). RecyclerView's pre-binding is based on the amount of time it takes to bind each view not the amount of time it takes to start each image load. You can probably preload images further ahead than you can prebind the view.

You'd have to play with it and see, and it will probably vary by the app. Variables like image size, scrolling speed and layout manager may make the answer different for different apps.
