### ISSUE TITLE
Glide 4.x and info.guardianproject.iocipher

### ISSUE THREAD

**Issue by zoff99** [bumptech/glide#1952]
**Glide Version**: 4.0.0-RC0

**Issue details / Repro steps / Use case background**: 
can you add the possibility to load images from vfs (info.guardianproject.iocipher) instead of normal java.io.File ? 
iocipher has its own implementations of info.guardianproject.iocipher.File

or can i override the loading with my own class to do that?

```
            GlideApp.with(context).
                    load(new info.guardianproject.iocipher.File(vfs_filename_with_path)).
                    placeholder(something).
                    into(icon_view);

```

**Comment by zoff99** [comment]
can anybody point my to a good example on loading data from a custom type?

**Comment by zoff99** [comment]
any hints?

**Comment by zoff99** [comment]
i tried a few ways and faild.
any help on this?

**Comment by sjudd** [comment]
You can implement a ModelLoader and a DataFetcher if you can extract an InputStream from these objects eventually.

**Comment by zoff99** [comment]
is there a working example for glide 4.0
i tried to implement a ModelLoader but it still tried to load from java.io.File
i can't find in what method the actual loading of the bytes happens

**Comment by sjudd** [comment]
Sure, see [HttpUrlLoader](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/stream/HttpGlideUrlLoader.java) for a sample ModelLoader in Glide v4.
