### ISSUE TITLE
Glide 4.0.0-RC0: how to set tint color for ImageView after successfully loading SVG

### ISSUE THREAD

**Issue by sonzerolee** [bumptech/glide#1953]
I followed this sample: [https://github.com/bumptech/glide/tree/master/samples/svg/src/main/java/com/bumptech/glide/samples/svg](https://github.com/bumptech/glide/tree/master/samples/svg/src/main/java/com/bumptech/glide/samples/svg)

After successfully loading SVG file with Glide 4.0.0-RC0, i want to set tint color for ImageView, but setColorFilter NOT WORKING

My source:
```java
package com.example.quangson.glidesvg;

import static com.bumptech.glide.load.resource.drawable.DrawableTransitionOptions.withCrossFade;

import android.content.ContentResolver;
import android.graphics.PorterDuff;
import android.graphics.drawable.PictureDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ImageView;
import com.bumptech.glide.RequestBuilder;
import com.example.quangson.glidesvg.glide.GlideApp;
import com.example.quangson.glidesvg.glide.SvgSoftwareLayerSetter;

public class MainActivity extends AppCompatActivity {

    private static final String TAG = "SVGActivity";
    private ImageView imageViewSVG;
    private ImageView imageViewPNG;
    private RequestBuilder<PictureDrawable> requestBuilder;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        imageViewSVG = (ImageView) findViewById(R.id.svg_image_view1);
        imageViewPNG = (ImageView) findViewById(R.id.svg_image_view2);

        imageViewPNG.setImageResource(R.drawable.image_mylogo);

        requestBuilder = GlideApp.with(this)
                .as(PictureDrawable.class)
                .error(R.drawable.image_error)
                .transition(withCrossFade())
                .listener(new SvgSoftwareLayerSetter());
        Uri uri = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://" + getPackageName() + "/"  + R.raw.android_toy_h);
        requestBuilder.load(uri).into(imageViewSVG);

        imageViewSVG.setColorFilter(getResources().getColor(R.color.colorAccent), PorterDuff.Mode.SRC_IN);
        imageViewPNG.setColorFilter(getResources().getColor(R.color.colorAccent), PorterDuff.Mode.SRC_IN);
    }
}
```
In my source: 
I loaded PNG image (from res/drawable) into imageViewPNG and setColorFilter for imageViewPNG ⇒ WORKING
I loaded SVG image (from res/raw) into imageViewSVG and setColorFilter for imageViewSVG ⇒ NOT WORKING (Loaded SVG file successfully but can't setColorFilter)

I want to change SVG image color when i clicked button.

Please help me set tint color for imageViewSVG.
Thanks

**Comment by judemanutd** [comment]
@sonzerolee i was trying to load svg myself, could you share parts of your code that are required to load an svg into an image view using glide v4,it would be really helpful.

**Comment by TWiStErRob** [comment]
@judemanutd it's all in the Glide repo linked at the top of OP.

@sonzerolee 
a) try to set the color filter before you start the Glide load, asynchronicity may be tricking you.
b) maybe move the color filter onto a listener and set it right before the drawable is propagated to the imageview
c) try to get Glide out of the picture, by loading the SVG synchronously; I have a hunch that maybe `PictureDrawable` doesn't support color filter? in onCreate do something like:
```java
InputStream source = getContentResolver().openInputStream(uri);
SVG svg = SVG.getFromInputStream(source);
Picture picture = svg.renderToPicture();
PictureDrawable drawable = new PictureDrawable(picture);
imageViewSVG.setImageDrawable(drawable);
```
d) give a try to tinting via compat: https://medium.com/@hanru.yeh/tips-for-drawablecompat-settint-under-api-21-1e62a32fc033

**Comment by judemanutd** [comment]
@TWiStErRob I tried the above code mentioned but i get the following error

`Load failed for http://politico.octave.tech/images/channels/bullhorn.svg with size [-2147483648x-2147483648]
                                                               class com.bumptech.glide.load.engine.GlideException: Failed to load resource`

`E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource`

[http://politico.octave.tech/images/channels/bullhorn.svg](SVG URL)

Why does it fail to load resource in spite of the link being active?I have replicated the exact code from the above github pages.

**Comment by TWiStErRob** [comment]
@judemanutd Can you please open a new issue for your problem, let's not hijack this issue about tinting. Please fill in the issue template fully, especially the exception stack trace, see https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by ScottPierce** [comment]
I'm encountering this issue as well.

**Comment by sonzerolee** [comment]
I have been researching for a long time but still can't change color ImageView after successfully loading SVG
Can you help me a solution?
---
PictureDrawable support setColorFilter: https://developer.android.com/reference/android/graphics/drawable/PictureDrawable.html

Looking forward for your help.
Thanks

**Comment by MaheshKumarPrajapati** [comment]
Please try this solution its working in my code

https://stackoverflow.com/a/66171056/8794123

**Comment by UlugbekDevAll** [comment]
Hi this is error
