### ISSUE TITLE
Is there some doc about how Glide works ?

### ISSUE THREAD

**Issue by jacklydoudou** [bumptech/glide#1955]
hi, Is there some docs about how Glide works ?  or UML ? or sth to learn about Glide src?
ths~~~~~

**Comment by jacklydoudou** [comment]
I'm using Glide 4.0.0-RC0 now~

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide#how-do-i-use-glide has a doc link.

Also for v3: https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit

**Comment by jacklydoudou** [comment]
@TWiStErRob thanks for your help
