### ISSUE TITLE
Is it possible to increase some methods，Like get local path by the url and get bitmap from bitmap-pool by url?

### ISSUE THREAD

**Issue by peerless2012** [bumptech/glide#1958]
**Glide Version**:3.7.0

**Integration libraries**:okhttp3-integration:1.4.0@aar

**Device/Android Version**:HTC-D816W

**Issue details / Repro steps / Use case background**: 

Sometimes, I need to use the bitmap what glide load into imageview to other places, but there is not a method that i can get the absolute path on Disk just by the url（Don't download） or get the bitmap from the bitmap-pool by the url(Don't download)。

Is there any ideas？

**Comment by peerless2012** [comment]
Here are some cases!

Sometimes , I want to share something to other apps, but the share need a bitmap to use。
etc...

**Comment by TWiStErRob** [comment]
#459?

What if the url is not downloaded yet?

**Comment by peerless2012** [comment]
Just return null !

**Comment by TWiStErRob** [comment]
I meant from the user's perspecitve.

**Comment by peerless2012** [comment]
I mean,when the user want to share A web url，the url is the main share data，but the thumb bitmap is just an arg I have to add。and some share support offline 。In this case，I think if I have the cached bitmap I will use the cached,otherwise use the default(like ic_launcher)。And if the share is in recycleview, It's not a good idea to add a callback to eache item。

**Comment by musicode** [comment]
+1.

I want to know whether an image is cached or not.

**Comment by TWiStErRob** [comment]
@musicode would `.onlyRetrieveFromCache(true)` help?

**Comment by musicode** [comment]
maybe like below?

```java
Glide.with(this)
                .load(url)
                .onlyRetrieveFromCache(true)
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onLoadFailed(GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                        // image is not cached
                        return false;
                    }
                    @Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                        // image is cached
                        return false;
                    }
                })
                .into(mPhotoView);
```

**Comment by TWiStErRob** [comment]
Yep. I just noticed that the OP is 3.7.0. This method is available in v4.

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/27829802-fb8bd16c-60f5-11e7-8e12-3c914e58dc36.png)

maybe `4.0.0-RC1` has no `onlyRetrieveFromCache ` method, right?

**Comment by peerless2012** [comment]
Yes ，the above is useful！

ps: there is another issue when i just load the local bitmap resource,#2110

**Comment by sjudd** [comment]
@musicode onlyRetrieveFromCache is a RequestOptions method unless you're using the generated API, see http://bumptech.github.io/glide/doc/options.html#requestoptions, http://bumptech.github.io/glide/doc/generatedapi.html
