### ISSUE TITLE
Glide doesnt support multiple disk caches

### ISSUE THREAD

**Issue by barnhill** [bumptech/glide#1959]
**Glide Version**: 4.0-RC0

**Integration libraries**: None

**Device/Android Version**: Google Pixel XL 7.1.2

**Issue details / Repro steps / Use case background**: 
I have tried to use multiple instances of Glide to separate the caches of large amounts of images that our app consumes.  We need the ability to clear one cache and not the others due to the very large user base we have.  It would generate too much traffic to clear all images.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

Ive tried using @GlideModule with an AppGlideModule but the auto generated GlideApp doesnt seem to work in 4.0.  Any insight on how to separate caches would be very helpful.

**Comment by TWiStErRob** [comment]
Do you really need to clear the cache explicitly?, or invalidation is enough?

I don't think Glide is a Multiton yet, last time I checked it was a Singleton.

**Comment by barnhill** [comment]
It is a singleton.  Invalidation of a cache would be fine but I dont need to invalidate all images just ones of a particular type.  (Logos vs all others)

**Comment by barnhill** [comment]
Any idea how to facilitate this using Glide?  Im open to suggestions.

**Comment by sjudd** [comment]
You're correct that Glide does not support multiple disk cache implementations directly. You can always try to write your own DiskCache implementation, or you can use a ModelLoader to write data you retrieve to your own cache independent of Glide.

Most of the information we have available is here: http://bumptech.github.io/glide/doc/caching.html.

We don't have plans to support multiple disk caches directly within Glide. I am open to accepting pull requests that would make it easier to customize disk caches though. For example you could pass more information into the disk cache interface to allow implementations to distinguish between images (right now they just get a string sha).

**Comment by TWiStErRob** [comment]
@barnhill To invalidate, you can use a signature that you change at times, which will force a re-download; or use anything from http://bumptech.github.io/glide/doc/caching.html#skipping-the-cache for your logos.

**Comment by tarun-swiggy** [comment]
Did someone find solution for multiple cache support ?
