### ISSUE TITLE
Android Glide Preload large number of Images

### ISSUE THREAD

**Issue by deepSymmetry** [bumptech/glide#1962]
**Glide Version**: 3.7.0

**Integration libraries**:

**Device/Android Version**: Android TV - 7.0 API 24

**Issue details / Repro steps / Use case background**: 
I am trying to preload a couple thousand images (2K-3K), each 10KB or less. Firing `glide.load()` leads to certain unsettling log messages like

`Long monitor contention with owner fifo-pool-thread-2 (15957) at void com.bumptech.glide.disklrucache.DiskLruCache.completeEdit(com.bumptech.glide.disklrucache.DiskLruCache$Editor, boolean)(DiskLruCache.java:502) waiters=0 in void com.bumptech.glide.disklrucache.DiskLruCache.completeEdit(com.bumptech.glide.disklrucache.DiskLruCache$Editor, boolean) for 565ms`

`Long monitor contention with owner pool-11-thread-1 (25980) at java.lang.Void com.bumptech.glide.disklrucache.DiskLruCache$1.call()(DiskLruCache.java:162) waiters=1 in com.bumptech.glide.disklrucache.DiskLruCache$Editor com.bumptech.glide.disklrucache.DiskLruCache.edit(java.lang.String, long) for 890ms`

This makes me think Glide is Struggling with I/O. Requests are queuing and locks are not being released.

Would you suggest any other approach for fast download and cache/preload of such large number of images. On demand (network) is too slow for my application.

The load is as simple as `glide.load(URL).dontTransform().preload(someWidth, someHeight)`

Moreover, it takes Glide several minutes to download these images. The bandwidth is good enough to stream an HDR 4K content. Please advise.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
CustomGlideModule {
        builder.setMemoryCache(new LruResourceCache(99999999));
}

glide = Glide.with(fragment.this)

for i-> 1-N
glide.load(URL[i]).dontTransform().preload(W, H);
```

**Comment by deepSymmetry** [comment]
e.g Just to preload 20 images, 10KB each, it took glide 11 seconds which is eternity.

Is there any harm in sequential firing of 20 image URLs.

**Comment by franciscofranco** [comment]
As a simple test, have you tried to query/download these images through simple HTTP requests to see how long it will take? If that's quick (it should) then it'll highlight some issue with Glide.
Without looking at any code and reading the messages above, following a FIFO mechanism it takes a single request to time out (or a slow server reply) to block any subsequent requests. Why are you doing this sequentially anyway (or maybe I'm misunderstanding).
