### ISSUE TITLE
StreamModelLoader in glide 4.0?

### ISSUE THREAD

**Issue by mianharisali** [bumptech/glide#1965]
Hi
we are using StreamModelLoader class  in our App , but in 4.0 we cannot figuerout how to get it done , as it is no more available.

We have images in InputStream format this is our code that we are using in glide 3.8.0.

how can we achieve this in glide 4.0?
```
class MyModule implements GlideModule {
   @Override public void applyOptions(Context context, GlideBuilder builder) {

   }
   @Override public void registerComponents(Context context, Glide glide) {
      glide.register(InputStream.class, InputStream.class, new PassthroughStreamLoader.Factory());
   }
}

class PassthroughStreamLoader implements StreamModelLoader<InputStream> {
   @Override public DataFetcher<InputStream> getResourceFetcher(final InputStream model, int width, int height) {
      return new DataFetcher<InputStream>() {
         @Override public InputStream loadData(Priority priority) throws Exception {
            return model;
         }
         @Override public void cleanup() {
            try {
               model.close();
            } catch (IOException e) {
               Log.w("PassthroughDataFetcher", "Cannot clean up after stream", e);
            }
         }
         @Override public String getId() {
            return String.valueOf(System.currentTimeMillis()); // There's no way to have a meaningful value here,
            // which means that caching of straight-loaded InputStreams is not possible.
         }
         @Override public void cancel() {
            // do nothing
         }
      };
   }

   public static class Factory implements ModelLoaderFactory<InputStream, InputStream> {
      @Override public ModelLoader<InputStream, InputStream> build(Context context, GenericLoaderFactory factories) {
         return new PassthroughStreamLoader();
      }
      @Override public void teardown() {
         // nothing to do
      }
   }
}
```

**Comment by sjudd** [comment]
[``StreamModelLoader<T>``][1] is just ``ModelLoader<T, InputStream>``, so you'd need to implement a ``ModelLoader<InputStream, InputStream>`` in your case.

As an aside, it's a little unusual to pass in an InputStream like this, usually you expect your ``ModelLoader`` to do the work of opening the stream. 

[1]: https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/model/stream/StreamModelLoader.java#L12

**Comment by sjudd** [comment]
I added a section to the migrating page for model loaders, let me know if you have feedback: http://bumptech.github.io/glide/doc/migrating.html#using-modelloader-streammodelloader

**Comment by mianharisali** [comment]
@sjudd thanks for your info , i just implemented it and it is working.
we are passing streams because we are decrypting images at run time.
to do that we need android context and i am not sure how can i pass context to loadData() method of DataFetcher class.

**Comment by jesphinpt** [comment]
Any solution for this?
