### ISSUE TITLE
Can not find GlideApp Class in glide 4.0?

### ISSUE THREAD

**Issue by developerHaoz** [bumptech/glide#1966]
Can not find GlideApp Class in glide 4.0?

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/getting-started.html.

You need an ``AppGlideModule`` annotated with ``@GlideModule`` and a dependency on Glide's annotation processor in your build.gradle file. 

Alternatively you can continue to use Glide as a substitute if you don't want to use the generated API.

This is a duplicate of #1939

**Comment by sjudd** [comment]
Duplicate of #1939

**Comment by developerHaoz** [comment]
thanks.

**Comment by checkming** [comment]
You could make project in "android studio -> build -> rclean project - > ebuild project - > make project", Repeat the above operation！
it will generate the GlideApp class.
