### ISSUE TITLE
How to resize image and set scale type to FitXY?

### ISSUE THREAD

**Issue by pinvisible** [bumptech/glide#1969]
**Glide Version**:4.0.0-RC0

**Integration libraries**: NO

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

 Need to load all gallery photos to my app, so i am using Glide.
**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java

RequestOptions requestOptions = new RequestOptions();
            requestOptions.placeholder(R.drawable.logo2);
            requestOptions.fitCenter();

Glide.with(PhotosScreen.this)
                    .applyDefaultRequestOptions(requestOptions)
                    .load(new File(photosList.get(position)))
                    .into(holder.my_image_view);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

I need to fetch all photos from gallery and display it to app.  Need to display photos in grid of 3 columns.
Also need to resize image and scale with fitxy.

**Comment by barnhill** [comment]
have you tried the override option to scale your image to an XY value?

**Comment by pinvisible** [comment]
How to do this? Can you please share code or link?

**Comment by TWiStErRob** [comment]
@pinvisible it should be as simple as:
```java
Glide.with(PhotosScreen.this)
        .load(new File(photosList.get(position)))
        .apply(new RequestOptions()
                .placeholder(R.drawable.logo2)
                //.fitCenter() // no need for this
        )
        .into(holder.my_image_view) // set ImageView.scaleType to `fitXY` before the Glide load
;
```
or what @barnhill was referring to:
```java
Glide.with(PhotosScreen.this)
        .load(new File(photosList.get(position)))
        .apply(new RequestOptions()
                .placeholder(R.drawable.logo2)
                .override(w, h) // set exact size
                .fitCenter() // keep memory usage low by fitting into (w x h) [optional]
        )
        .into(holder.my_image_view) // probably set ImageView.scaleType to `fitXY` so it stretches
;
```

Also, please reconsider that requirement, I can't imagine a use case where the user might want to see a distorted image coming from their own device. It'll just make them think that there's something wrong with the original image... even though it's just the display in your app; there are so many better ways to display images.

**Comment by baona95** [comment]
@TWiStErRob Surprisingly I can't resize the image with particular size. 
All things are setup as mentioned: scaleType, wrap_content, adjust view bounds but the height of images are variable.

**Comment by vincent-paing** [comment]
Anyone figure out how to do this?

**Comment by HombreTech** [comment]
> Anyone figure out how to do this?
```
override(w, h)
fitCenter()
```
and

`android:scaleType="fitXY"`
