### ISSUE TITLE
Load only from Cache

### ISSUE THREAD

**Issue by ManuelGA** [bumptech/glide#1970]
Hello,

I have been looking at some documentation and before we would use "using()" to force images to be loaded strictly from cache, but now that it has been removed on v4, what is the best approach to only load images if they are alreayd cached? And also, how could I check if the image was found on cache or not.

Thank you very much in advance.

**Comment by sjudd** [comment]
Added some documentation:

http://bumptech.github.io/glide/doc/caching.html#skipping-the-cache

There is no synchronous way to check if an image is in cache, you can only attempt to load from the cache and handle the failure.
