### ISSUE TITLE
Glide 4 - extension annotation procesor, error, fallback

### ISSUE THREAD

**Issue by mare011** [bumptech/glide#1971]
**Glide Version**: 4.0.0-RC0

**Integration libraries**: okhttp-integration:4.0.0-RC0

**Device/Android Version**: Galaxy S6 SDK version 25

**Issue details / Repro steps / Use case background**: 
When using an annotation processor, generated class GlideRequests contains duplicate field:

```java
@Override
  public <ResourceType> GlideRequest<ResourceType> as(Class<ResourceType> resourceClass) {
    return new GlideRequest<>(glide, this, resourceClass);
  }
  @Override
  public <ResourceType> GlideRequest<ResourceType> as(Class<ResourceType> resourceClass) {
    return (GlideRequest<ResourceType>) super.as(resourceClass);
  }
```

My module:
```java
@GlideModule
public class GlideAppModule extends AppGlideModule {
	@Override
	public void applyOptions(Context context, GlideBuilder builder) {
		builder.setDiskCache(new InternalCacheDiskCacheFactory(context, 20 * 1024 * 1024));
	}

	@Override
	public boolean isManifestParsingEnabled() {
		return false;
	}
}
```

Extension:
```java
@GlideExtension
public final class GlideAppExtension {
	private GlideAppExtension() {}

	@GlideOption
	private static void cropCircle(RequestOptions options) {
		// TODO
	}
}
```

Should i use in build.gradle:
`annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC0'`
or
`compile 'com.github.bumptech.glide:compiler:4.0.0-RC0`

I've tried both, and tried SNAPSHOT version
Also in the documentation example the first argument is RequestOptions<?>, but the class from the sources is not generic?

Also in the code bellow, error drawable is not used when the url is null, and docs state: "null models will cause the error drawable to be displayed", this is working in the latest 3.x version.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(this).load(contractImage) // contractImage is null
			        .transform(new CropCircleTransformation())
			        .error(errorDrawable)
			        .into(imageView);
```

**Comment by sjudd** [comment]
I can reproduce this.

Your dependency looks correct to me:
```groovy
annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC0'
```

**Comment by sethchhim** [comment]
compile "com.github.bumptech.glide:glide:4.0.0-RC0"
compile "com.github.bumptech.glide:okhttp3-integration:4.0.0-RC0"

Great to hear this bug is acknowledged. In the meantime, the library still parses the manifest for a legacy (deprecated) `GlideModule`, so you can use that for testing purposes. Just make sure to remove the annotationProcessor dependency and `@GlideModule` annotations.

 `<meta-data`
        `android:name="com.example.test.GlideModule"`
        `android:value="GlideModule" />`

**Comment by sjudd** [comment]
Splitting out a separate issue for the error fallback since it's unrelated.
