### ISSUE TITLE
documentation of fluent api - wrong order of calls

### ISSUE THREAD

**Issue by imbryk** [bumptech/glide#1975]
Order in witch the methods are called in documentation is wrong - eg. it is not possible to call `placeholder()` nor `fitCenter` on `GlideRequests`, so you have to call  `load()` or one of `as...()` methods first to obtain instace of `GlideRequest<>`:

wrong order ([as provided in documentation](http://bumptech.github.io/glide/doc/getting-started.html#applications))
```
GlideApp.with(fragment)
   .placeholder(placeholder)
   .fitCenter()
   .load(myUrl)
   .into(imageView);
```

correct order:
```
GlideApp.with(fragment)
   .load(myUrl)
   .placeholder(placeholder)
   .fitCenter()
   .into(imageView);
```

**Comment by sjudd** [comment]
Thanks for pointing this out, any interest in contributing a fix? See http://bumptech.github.io/glide/dev/contributing.html#documentation

**Comment by imbryk** [comment]
Happy to have a look at it this later this week
