### ISSUE TITLE
about memory

### ISSUE THREAD

**Issue by 1479HuangDa** [bumptech/glide#1978]
Glide 4 is used in ListView. when slide the ListView，the memory growing up to 50MB and unstable. Can you decrease the memory usage .

**Comment by TWiStErRob** [comment]
We can't change your app... but you can improve/configure for better usage. Do you have a baseline you're comparing against? Can you please share how you're using Glide? (All those questions that were in the template play here)

**Comment by 1479HuangDa** [comment]
No baseline to compare.
I use Glide 4 in the Adapter of ListView as follow:
 
mAdapter = new SimpleAdapter(GlidListTestActivity.this,data,R.layout.glidlisttest_item,new String[]{"list_item"},new int[]{R.id.iv_iamge}){
            @Override
            public void setViewImage(ImageView v, String value) {
                GlideApp.with(GlidListTestActivity.this).load(Uri.parse(value)).diskCacheStrategy(DiskCacheStrategy.ALL)
                        .into(v);
            }
        };

and in ViewPage`s adapter:

public class PagersAdapter extends PagerAdapter {

        private GlideRequests with;

        public PagersAdapter() {
            with = GlideApp.with(getContext());
        }

        @Override
        public View instantiateItem(ViewGroup container, int position) {
            Log.d("instantia", "instantiateItem .position: " + position);
            final String iamgeUrl = showPicturelist.get(position);
            int i = position % 4;
            FrameLayout layout = list.get(i);

            ImageView image = (ImageView) layout.findViewById(R.id.mIimage);
            image.setTag(iamgeUrl);
            layout.setTag(image);

            container.addView(layout);


            with.load(iamgeUrl)
                    .thumbnail(0.1f)
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .into(new DrawableImageViewTarget(image) {
                        @Override
                        public void onResourceReady(Drawable resource, @Nullable Transition<? super Drawable> transition) {
                            super.onResourceReady(resource, transition);
                            ImageView view = getView();

                            PhotoViewAttacher attacher = new PhotoViewAttacher(view);
//                            attacher.setOnLongClickListener(new ImageOnclickListener(iamgeUrl));
                            attacher.update();
                        }
                    });

//
            return layout;
        }


        @Override
        public void destroyItem(ViewGroup container, int position, Object object) {
            FrameLayout layout = (FrameLayout) object;
            Log.d("instantia", "destroyItem .position: " + position);
            if (layout.getTag() != null) {
                if (layout.getTag() instanceof ImageView) {
                    ImageView image = (ImageView) layout.getTag();
                    image.setOnLongClickListener(null);
                    with.clear(image);
                }
            }

            GlideApp.get(getContext()).clearMemory();
            container.removeView(layout);
            System.gc();

        }

        @Override
        public int getCount() {

            return showPicturelist.size();
        }

        @Override
        public boolean isViewFromObject(View arg0, Object arg1) {
            return arg0 == arg1;
        }


    }

int the short the Glide4 is use in ListView .the memory usage growing up to 50MB sliding fastly .particularly in Viewpage ,it is in bad condition which continue jumping up and down .
