### ISSUE TITLE
it

### ISSUE THREAD

**Issue by Wenqin-231** [bumptech/glide#1979]
![image](https://cloud.githubusercontent.com/assets/17612221/26613233/5addf1b0-45ec-11e7-8e77-4580c1df3176.png)
 I have tried to use GlideApp， but the with is return GlideRequests without error() and anyother method.
And I have to use GlideApp.wth(context).load(url) that return GlideRequest with the method like error.
So is it wrong or my user is wrong?

**Comment by sjudd** [comment]
For the order of requests, see #1975, if GlideApp errors, see #1939. If neither of those explain the errors you're seeing, please re-open and include the error message.
