### ISSUE TITLE
Glide 4.0.0-RC0: Images are not loaded when fast scrolling through RecyclerView (worked on 3.7)

### ISSUE THREAD

**Issue by rafakob** [bumptech/glide#1981]
**Glide Version**:
Glide 4.0.0-RC0

**Integration libraries**:
tested with okhttp3-integration:4.0.0-RC0 and without it - same behavior

**Issue details**: 
When fast scrolling through a RecyclerView, images are not loaded. Take a look at this short video. The same list works without any issues on Glide 3.7. How to fix this?

I've attached listener - no errors returned.

https://www.dropbox.com/s/rpfpltgyi32ntmr/2017_05_31_11_28_30.mp4?dl=0

**Usage in onBindViewHolder**:
```java
GlideApp.with(vh.photo.context)
        .load(model.photoUrl)
        .into(vh.photo)
```

**Comment by christopherperry** [comment]
I had the same issue when I upgraded. Check logcat, there's probably errors. I had to change the way things were configured to get it to work.

**Comment by TWiStErRob** [comment]
@christopherperry can you be more specific, there shouldn't be a difference except the default pixel format being changed as far as I know.

**Comment by christopherperry** [comment]
@TWiStErRob For sure. I had to comment out this bit of code in our AppGlideModule, which worked for the previous version.

```java
@Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // disabling Glide internal cache since we'll be using OkHttp's cache
        // TODO: If you uncomment this images no longer load, are we sure we really want to do this anyways?
//        builder.setDiskCache(new DiskCache.Factory() {
//            @Override
//            public DiskCache build() {
//                // this is a no-op cache: https://github.com/bumptech/glide/wiki/Configuration#disk-cache
//                return new DiskCacheAdapter();
//            }
//        });
    }
```

**Comment by DummyCo** [comment]
I'm having the same issue, log is not reporting any errors.
For instance first image in recycler can be loaded as
`Finished loading BitmapDrawable from REMOTE`
But if we're going quickly to the end of huge list and returning back - it's not even trying to get the image from MEMORY_CACHE/DATA_DISK_CACHE, it stays blank.

**Comment by AlexTip** [comment]
+1

**Comment by TWiStErRob** [comment]
@DummyCo @AlexTip please share Glide load lines and GlideModule configurations.

**Comment by yangshiliang** [comment]
+1
exactly the same issue with @rafakob, also used in onBindViewHolder, with no customised configurations, and with the same Glide version and integration library:
```
Glide.with(context)
         .load(mData.get(position))
         .into(viewHolder.mImageView);
```

**Comment by praveenmoto** [comment]
+1

**Comment by DummyCo** [comment]
@TWiStErRob can you please investigate that? Should we create a sample?

**Comment by TWiStErRob** [comment]
That would probably help... it seems to affect a lot of people. Maybe something is clogging up the threads.

**Comment by ozv101** [comment]
Same issue. Seeing it on `RC1`. Listener callback methods are never fired.
```
Glide.with(context)
                .asBitmap()
                .transition(withCrossFade())
                .load(new MyUrlLoader(url))
                .apply(new RequestOptions()
                        .diskCacheStrategy(DiskCacheStrategy.RESOURCE))
                .listener(new RequestListener<Bitmap>() {
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object o, Target<Bitmap> target, boolean b) {
                        Log.e("loadIMG", e.getMessage());
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Bitmap bitmap, Object o, Target<Bitmap> target, DataSource dataSource, boolean b) {
                        return false;
                    }
                })
                .into(new BitmapImageViewTarget(view) {
                    @Override
                    protected void setResource(Bitmap resource) {
                        super.setResource(resource);
                    }
                });
```

**Comment by VladislavNikolaev** [comment]
+1

**Comment by praveenmoto** [comment]
Issue is happening because glide is unable to calculate height and width of
view.if you pass height and width then issue doesn't happen

**Comment by sjudd** [comment]
If someone who can reproduce this can attach a sample app the issue is probably fixable.

Unfortunately +1s and load lines aren't especially helpful at this point.

**Comment by rafakob** [comment]
@sjudd Here's the example project. Please don't judge me for the images links, I haven't found any open API which offers high res pictures ;)

https://github.com/rafakob/GlideRecyclerSample

**Comment by sjudd** [comment]
Thanks for the sample project! I was able to reproduce and I think my change will fix the issue, or at least the one demonstrated in the sample app.
