### ISSUE TITLE
Glide taking too much time to load and sometime not loading images

### ISSUE THREAD

**Issue by pnjolapara** [bumptech/glide#1983]
**Glide Version**:3.8.0

**Integration libraries**:

**Device/Android Version**: OS6.0.1

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(holder.mIvMenu.getContext())
.load(mList.get(position).getImgUrl())
.diskCacheStrategy(DiskCacheStrategy.SOURCE)
.thumbnail(0.1f)
.crossFade()
.dontAnimate()
.skipMemoryCache(true)
.into(holder.mIvMenu)
```

**Layout XML**:
```xml
<android.support.v7.widget.AppCompatImageView
        android:id="@+id/IvMenu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="8dp"
        android:layout_centerVertical="true"
        android:layout_centerHorizontal="true"
        />

```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/art: Suspending all threads took: 5.637ms
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
```

**Comment by pnjolapara** [comment]
I am using 3.8.0 glide version
I have aprox. 65 to 75 images with each image aprox size is 1.3MB
below is my code:
Glide.with(holder.mIvMenu.getContext())
                .load(mList.get(position).getImgUrl())
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .thumbnail(0.1f)
                .crossFade()
                .dontAnimate()
                .skipMemoryCache(true)
                .into(holder.mIvMenu)

when its loading image its priting log like: 
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/art: Suspending all threads took: 5.637ms
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!

**Comment by seemranxec** [comment]
I have been facing similar issues.The images wont load sometimes.Tried to turn off caching but still the images wont load.

**Comment by sjudd** [comment]
@seemranxec file a new issue and fill out the issue template please.
