### ISSUE TITLE
Update Placeholder Documentation for v4.0

### ISSUE THREAD

**Issue by christopherperry** [bumptech/glide#1988]
Placeholder is now a part of `RequestOptions` and not the `RequestBuilder`. The [documentation](http://bumptech.github.io/glide/doc/placeholders.html#placeholder) needs to be updated.

**Comment by TWiStErRob** [comment]
It explicitly says before each example: "With the generated API:"

**Comment by christopherperry** [comment]
My bad. I totally glossed right over that.

**Comment by sjudd** [comment]
No worries, better to have the report and verify it's WAI than not have the report and have something stay broken, thanks!
