### ISSUE TITLE
NullPointerException in RequestManagerRetriever.findAllSupportFragmentsWithViews

### ISSUE THREAD

**Issue by YutaTetsuka** [bumptech/glide#1991]
sorry, I am not good at English.

**Glide Version**: 4.0.0 RC0

**Integration libraries**: okhttp3-integration 4.0.0 RC0 

**Device/Android Version**: Android 5.1

**Issue details / Repro steps / Use case background**: 
NullPointerException in `RequestManagerRetriever.findAllSupportFragmentsWithViews()` after `Glide.with(Context)`

in `findAllSupportFragmentsWithViews()` , `topLevelFragments` Collection is not null and not empty too.
but, `topLevelFragments` have `null`, so NullPointerException in for-each.

I received crash reporting, but I could not reproduction.
I think that will occur when called `Glide.with` after view is destroyed. 
But, I tried block after onDetachedFromWindow, It did not improve.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public void setImageUrl(@NonNull String url) {
  Glide.with(this).load(url).into(this); // "this" is ImageView instance
}
```

```java
public void setImageUrl(@NonNull String url) {
  if (!isViewDestroyed) { // "true" after called onDetachedFromWindow
    Glide.with(this).load(url).into(this); // "this" is ImageView instance
  }
}
```

NPE too.

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.support.v4.app.Fragment.getView()' on a null object reference
       at com.bumptech.glide.manager.RequestManagerRetriever.findAllSupportFragmentsWithViews(RequestManagerRetriever.java:189)
       at com.bumptech.glide.manager.RequestManagerRetriever.findSupportFragment(RequestManagerRetriever.java:200)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:167)
       at com.bumptech.glide.Glide.with(Glide.java:609)
       at com.example.views.ExImageView.setImageUrl(ExImageView.java:55)
       at ...
```

[RequestManagerRetriever.java#189](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/manager/RequestManagerRetriever.java#L189) fragment is null

Is it bug of glide? or Is my usage wrong?

**Comment by sjudd** [comment]
Looks like a bug in Glide. Great report, thanks!
