### ISSUE TITLE
Seeking help in using Facebook Conceal to encrypt and decrypt the image across the whole app in Glide 4.0.0-RC0

### ISSUE THREAD

**Issue by TonyTangAndroid** [bumptech/glide#1995]
I am trying to integrate Facebook Conceal with Glide 4.0 to encrypt the cache of image globally across the whole app and decrypt the file before decoding the file into bitmap again.

In according to the discussion [here](https://github.com/bumptech/glide/issues/735), it is possible by defining a new ResourceDecoder and ResourceEncoder, which is exactly what I had tried to do in the code base based on the sample app of Flickr. But it did not success.

Any help or suggestion will be highly appreciated.

PS : If anyone who is interested in seeing the details of what I am doing, I have forked the repository and committed the related code that was intended to do the encryption and decryption into a [new branch](https://github.com/TonyTangAndroid/glide/tree/master_flickr_encryption).

**Comment by TonyTangAndroid** [comment]
Here is the pull request difference https://github.com/bumptech/glide/pull/1994

**Comment by TonyTangAndroid** [comment]
This issue has been resolved.For anyone who comes here for a solution, please refer to [this example](https://github.com/TonyTangAndroid/GlideEncyptionDemo).

**Comment by Guang1234567** [comment]
@TonyTangAndroid   good !!!
