### ISSUE TITLE
Load A Thumbnail Of firstframe of an online video

### ISSUE THREAD

**Issue by Amin1012** [bumptech/glide#1997]
**Glide Version**:4.0.0-SNAPSHOT
Hi, How can i load a thumbnail of an online video (ex: .mp4) using glide?

**Comment by sjudd** [comment]
Glide doesn't handle load parts of videos, we can load thumbnails for videos, but only by downloading the entire video. You're better off using a backend service that can generate the thumbnail for you and downloading the thumbnail instead.
