### ISSUE TITLE
The rounded corners are not centered glide:4.0.0-RC0

### ISSUE THREAD

**Issue by yefawei** [bumptech/glide#1998]
`RequestOptions option = new RequestOptions().centerCrop().optionalTransform(new RoundedCorners(10));
Glide.with(holder.itemView.getContext()).load(bean.image_url).apply(option).into(holder.imageIv);`
[http://1.file.leanote.top/593132a0ab64415f5500154b/2017-06-02-172945.png?e=1496400158&token=ym9ZIrtxjozPN4G9he3-FHPOPxAe-OQmxzol5EOk:8JL6OaSojUO4jLjm7rlVpWuTFjU](url)

**Comment by cschua** [comment]
First you will need to add AppGlideModule class, as explained here:
http://bumptech.github.io/glide/doc/getting-started.html

Then update your code to something like this:
GlideApp.with(context)
   .load(item.getImage())
   .centerCrop()
   .apply(RequestOptions.bitmapTransform(new RoundedCorners(8)));

**Comment by TheLester** [comment]
Use multiTransformation 

`Glide.with(fragment)
  .load(url)
  .transform(new MultiTransformation(new FitCenter(), new YourCustomTransformation())
  .into(imageView);`
