### ISSUE TITLE
Hi, I am using Glide for sometime now, its really amazing. Although, I am facing one issue with image quality.

### ISSUE THREAD

**Issue by shahidbits** [bumptech/glide#2009]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Dupe of #2010 I think.
