### ISSUE TITLE
Bad image quality on using override() method

### ISSUE THREAD

**Issue by shahidbits** [bumptech/glide#2010]
Hi, I am using Glide for sometime now, its really amazing. Although, I am facing one issue with image quality.

I am picking an image from Camera using the following code -

```
Intent cameraIntent = new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE);

String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
String imageFileName = "JPEG_" + timeStamp + "_";
File storageDir = getActivity().getExternalFilesDir(Environment.DIRECTORY_PICTURES);
try {
	mSelectedImageFile = File.createTempFile(
	imageFileName,  /* prefix */
	".jpg",         /* suffix */
	storageDir      /* directory */
	);

	if (mSelectedImageFile != null) {
		selectedImageUri = Uri.fromFile(mSelectedImageFile);
	}
} catch (IOException e) {
	e.printStackTrace();
}

if (selectedImageUri != null) {
	cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT, selectedImageUri);
}

startActivityForResult(cameraIntent, 100);
```

Upon receiving the uri in onActivityResult(), I am using Glide to display the image -

```
Glide.with(getApplicationContext()).load(imageUri)
//.thumbnail(0.9f)
.crossFade()
//.sizeMultiplier(0.4f)
.override(2000, 1600)
.fitCenter()
.placeholder(R.drawable.ic_placeholder_feed_600)
.diskCacheStrategy(DiskCacheStrategy.ALL)
.into(new SimpleTarget<GlideDrawable>() {

	@Override
	public void onResourceReady(GlideDrawable glideDrawable, GlideAnimation<? super GlideDrawable> glideAnimation) {
		Bitmap bitmap = ((GlideBitmapDrawable) glideDrawable).getBitmap();
		mNewImageDp.setImageBitmap(bitmap);
	}
});
```

The image quality is not good.
If I remove override() from the above code, it loads the full size image which consumes lot of memory.
Is there a way in Glide to scale down an image without affecting the quality.
In WhatsApp, if we send a large image of 4MB, it is scaled down to ~200KB without compromising the quality. How can the same quality be achieved using Glide.

compile 'com.github.bumptech.glide:glide:3.7.0'

Thanks
Shahid

**Comment by EsteveAguilera** [comment]
By default, Glide uses RGB_555 configuration while Picasso loads images in ARGB_8888. 

You can tell Glide to use ARGB_8888 with

```builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);```

We've added this in our own GlideModule to use this on all Glide usages.
