### ISSUE TITLE
 Use 4.0.0 glide compile,  method " .placeholder" don't use

### ISSUE THREAD

**Issue by Heipi** [bumptech/glide#2013]
Glide.with(RankMainFragment.this).load(“https://lh3.googleusercontent.com//RcuHO_RC49xMWnxWFftJI312tJLFjO5STSDZwbUUHy7VG1qmT1-fgOpymQcy8O38ziI9”) .into(mHeadImageView); Don't use method “.placeholder” ?

**Comment by liyuhaolol** [comment]
thats old way ,new way is 
RequestOptions options = new RequestOptions().placeholder(res);
Glide.with(context).asDrawable().apply(options).load(res) .into(target);

**Comment by TWiStErRob** [comment]
you can use the old way in v4 as well: http://bumptech.github.io/glide/doc/generatedapi.html
