### ISSUE TITLE
gif asBitmap() background color change

### ISSUE THREAD

**Issue by ZzjBeatYou** [bumptech/glide#2015]
```
 Glide.with(context)
                        .load(url)
                        .asBitmap()
                        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                        .centerCrop()
                        .into(view);
```
Test  phone  `Redmi Note 4`
android version `6.0`
glide version ` 3.7.0`
test gif link `http://i1.mopimg.cn/public/images/face/iframe/10.gif`

error display in RedmiNote4
![_20170607183603](https://user-images.githubusercontent.com/7357841/26874456-3e15cf3e-4bb0-11e7-84bf-0e63b8fda39a.png)

normal display in other phone
![_20170607184108](https://user-images.githubusercontent.com/7357841/26874699-25ee0aa6-4bb1-11e7-88d5-b726d7213604.png)

but some gif will not this problem 
`http://i3.mopimg.cn/public/images/face/1007.gif`

**Comment by LeonScroggins** [comment]
This is likely due to a bug in Android's BitmapFactory. This should work properly on O.

(I thought it was due to the fact that in N and before, Android respected the background index, unlike most other viewers, but the background index in that image matches the transparent index.)
