### ISSUE TITLE
Fetched data long time

### ISSUE THREAD

**Issue by dingshaoran** [bumptech/glide#2018]
V/DecodeJob: Fetched data in 27490.785666, key: EngineKey{http://c6.xinstatic.com/che/20161207/1506/5847b4fd49fde950162_25.jpg+com.bumptech.glide.h.b@94203eb+[315x210]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}
when fast scroll recyclerview，load image so slow。

**Comment by toutoumu** [comment]
我也遇到了同样的情况, 在自定义的 MyGlideModule extends AppGlideModule 写自己的加载本地文件的方法, 结果比Glide3.x慢了许多, 3.x RecyclerView滚动的时候很快就可以加载出缩略图, 而4.x的速度明显慢了很多,而且有点卡住UI .

这是4.x的代码
`/**
   * 如何加载数据
   */
  public static class MyDataFetcher implements DataFetcher<InputStream> {

    private Picture file;
    private boolean isCanceled;
    InputStream mInputStream = null;

    public MyDataFetcher(Picture file) {
      this.file = file;
    }

    @Override public void loadData(Priority priority, DataCallback<? super InputStream> callback) {
      // 可以在这里进行一些文件处理,比如根据文件路径处理,文件解密等
      try {
        Timber.e(file.getFilePath());
        if (!isCanceled) {
          mInputStream = new FileInputStream(new File(file.getFilePath()));
        }
      } catch (FileNotFoundException e) {
        callback.onLoadFailed(e);
        Timber.e(e);
      }
      callback.onDataReady(mInputStream);
    }

    @Override public void cleanup() {
      if (mInputStream != null) {
        try {
          mInputStream.close();
        } catch (IOException e) {
          Timber.e(e);
        }
      }
    }

    @Override public void cancel() {
      isCanceled = true;
    }

    @Override public Class<InputStream> getDataClass() {
      return InputStream.class;
    }

    @Override public DataSource getDataSource() {
      //return LOCAL;
      return REMOTE;
      //return DATA_DISK_CACHE;
      //return RESOURCE_DISK_CACHE;
      //return MEMORY_CACHE;
    }
  }`

这是3.x的代码
`public static class ImageDataFetcher implements DataFetcher<InputStream> {

    // 检查是否取消任务的标识
    private volatile boolean mIsCanceled;

    private final String mFilePath;
    private InputStream mInputStream;

    public ImageDataFetcher(String filePath) {
      mFilePath = filePath;
    }

    /**
     * 在后台线程中调用，用于获取图片的数据流，给Glide处理
     *
     * @param priority
     * @throws Exception
     */
    @Override public InputStream loadData(Priority priority) throws Exception {
      if (mIsCanceled) {
        return null;
      }
      mInputStream = new FileInputStream(mFilePath);
      return mInputStream;
    }


    /**
     * 在后台线程中调用，在Glide处理完{@link #loadData(Priority)}返回的数据后，进行清理和回收资源
     */
    @Override public void cleanup() {
      if (mInputStream != null) {
        try {
          mInputStream.close();
        } catch (IOException e) {
          Log.e("Glide", "Glide", e);
        } finally {
          mInputStream = null;
        }
      }
    }

    /**
     * 在UI线程中调用，返回用于区别数据的唯一id
     */
    @Override public String getId() {
      return mFilePath;
    }

    /**
     * 在UI线程中调用，取消加载任务
     */
    @Override public void cancel() {
      mIsCanceled = true;
    }
  }`
