### ISSUE TITLE
What is the maximum cache size that I can set?? Can I set more than INTEGER_MAX value?

### ISSUE THREAD

**Issue by bhargavms** [bumptech/glide#2022]
HI,
I would like to know if it would be possible to set a cache size more than the that allowed by the `int` data type? since `builder.setDiskCache(new InternalCacheDiskCacheFactory(context, diskCacheSizeBytes));` takes `int` as the discCacheSizeBytes.

**Comment by sjudd** [comment]
Not currently, you're welcome to send a pull request to change these to longs.

2GB is a lot of cache space...

**Comment by bhargavms** [comment]
Alright Ill be sure to get on it first thing once I finish the project at hand :)

**Comment by sjudd** [comment]
Thanks! I'll look forward to it.

**Comment by sjudd** [comment]
Fixed in #2558
