### ISSUE TITLE
Log.isLoggable Performance Issue

### ISSUE THREAD

**Issue by christopherperry** [bumptech/glide#2023]
I'm doing some profiling of my app, and came across this:

<img width="1262" alt="screen shot 2017-06-11 at 4 36 35 pm" src="https://user-images.githubusercontent.com/1331096/27015498-a4a3ffbc-4ec3-11e7-881d-eaf45168d730.png">

Can you guys please strip logging from the release version? I'm using v3.8 currently.

**Comment by TWiStErRob** [comment]
I don't see the performance issue, 0.1% is well within an acceptable range. If we strip logging then there's no way to see what's going on inside other than debugging, which is not always desirable.

You can assume no side effects with ProGuard to remove the logging. I've successfully done that in my apps' release builds.

**Comment by sjudd** [comment]
traceview isn't a particularly accurate way of measuring how long methods take and ProGuard is the standard way of stripping logs (the isLoggable/Log pattern is used to make this 0 overhead).

**Comment by christopherperry** [comment]
I'm more concerned about the CPU Time per call and Real Time per call given we only get 16.7 ms to draw a frame. 5ms / 10ms doesn't seem like zero overhead. Am I totally lost here? Please correct me if I'm misunderstanding something.

**Comment by sjudd** [comment]
traceview doesn't produce accurate cpu times, small method calls in particular are massively inflated.

If you strip log lines with proguard they won't show up in your apk, so they will take 0ms.
