### ISSUE TITLE
How to apply glide to aidl?

### ISSUE THREAD

**Issue by komamj** [bumptech/glide#2025]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
I'm not really sure what you're asking. Can you re-open after providing more detail?
