### ISSUE TITLE
signature,skipMemoryCache Method not found

### ISSUE THREAD

**Issue by younas-bangash** [bumptech/glide#2026]
**Glide Version**:
com.github.bumptech.glide:glide:4.0.0-RC0

**Integration libraries**:

**Device/Android Version**:
6.0

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(holder.albumimage.getContext())
                                    .load(decodedString)
                                    .skipMemoryCache(true)
                                    .into(holder.albumimage);
```

**Layout XML**:
```xml
<ImageView
            android:id="@+id/albumimage"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_centerHorizontal="true"
            android:layout_centerVertical="true"
            android:visibility="gone" />
```

**Stack trace / LogCat**:
```ruby
Cannot resolve method 'skipMemoryCache(boolean)
```

**Comment by younas-bangash** [comment]
I solved the issue by changing the version of glide to `compile 'com.github.bumptech.glide:glide:3.8.0'`

**Comment by bbfxier** [comment]
this method seem come back

**Comment by Quazar1** [comment]
Thank you i solved this problem by change the version of glide to 3:8:0

**Comment by sjudd** [comment]
The method is available in Glide v4 via [the generated API][1] or [the default API][2]. The docs page has a ton of information and examples on options as well. 

[1]: http://bumptech.github.io/glide/doc/generatedapi.html
[2]: http://bumptech.github.io/glide/doc/migrating.html#requestoptions
