### ISSUE TITLE
trying to use a recycled bitmap

### ISSUE THREAD

**Issue by BlackBirds** [bumptech/glide#2027]
**Glide Version**:3.7.1

**Issue details / Repro steps / Use case background**: 
1.if onLowMemory callback when my Activity onStop. the bitmap will be Recycled. 
2. When onResume excute
`Glide.with(SecondActivity.this).load(url).asBitmap().into(target);`
3.in the GenericRequestBuilder class
```java
public <Y extends Target<TranscodeType>> Y into(Y target) {
        ....
        Request previous = target.getRequest();

        if (previous != null) {
            previous.clear();
            requestTracker.removeRequest(previous);
            previous.recycle();
        }
}
```
4.The code will put the bitmap has recycled in MemoryCache，and when onResourceReady the crash will happen.

5.please tell me,the above conjecture is likely to happen?

**Comment by sjudd** [comment]
Are you using a custom Target? Make sure that when ``onLoadCleared`` is called you remove the Bitmap from any Views and ensure it's completely dereferenced.

If for whatever reason you need to reference the Bitmap after onStop/onDestroy, use the Application Context when loading the image:

```java
Glide.with(SecondActivity.this.getApplicationContext()).load(url).asBitmap().into(target);
```

**Comment by BlackBirds** [comment]
Why use ApplicatiionContext？

**Comment by sjudd** [comment]
Glide uses the lifecycle of the object you pass in to automatically clear and restart requests. If you pass in an Activity, Glide uses the Activity's lifecycle. If you pass in a Fragment, Glide uses the Fragment's lifecycle etc.

If you pass in the Application Context, Glide has no lifecycle to listen to. As a result, Glide doesn't try to automatically manage requests that are started with the Application Context, so your requests won't be cleared unless you explicitly clear them yourself. Worse for performance if you make a habit of it, but completely fine for individual requests, especially if they're made outside of ListView, RecyclerView or GridView.

**Comment by TWiStErRob** [comment]
See also https://stackoverflow.com/a/32887693/253468
