### ISSUE TITLE
Image Background color vary in versions of android

### ISSUE THREAD

**Issue by aayushthakur** [bumptech/glide#2030]
**Glide Version**: 3.8.0

**Integration libraries**: Volley

**Device/Android Version**: Motorola G4 Plus/ 7.0 , Asus P024 Tablet/ 6.0.1, Oneplus One/5.0.2, 

**Issue details / Repro steps / Use case background**:  I am loading an image with a background #f9f9f9 [this image](https://teafloor.com/media/catalog/product/t/h/the-tea-explorer-1.jpg). So I have made a layout with a background color #f9f9f9. Inside which I have an image view. The problem is the image background color is different in each of the mentioned devices.

Moto G4 Plus Android 7.0
![moto g4 plus 7 0](https://user-images.githubusercontent.com/16386061/27080508-cdc44a72-5059-11e7-85b7-cd6f80af93be.png)

Asus P024 Tablet Android 6.0.1
![asus tablet 6 0 1](https://user-images.githubusercontent.com/16386061/27080512-d1779106-5059-11e7-8a44-ba91a56d2407.jpg)

OnePlus One Android 5.0.2
![oneplus 5 0 2](https://user-images.githubusercontent.com/16386061/27080513-d30dc080-5059-11e7-8930-7e6e2278409b.png)

The nougat device loads the image with some transparent color.
The Marshmallow device loads the image with #f7f7f7 color
The Lollipop device loads the image with #b9b9b9 color.

I have used Picasso for the same image and it loads the image perfectly.

Why is this happening?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public static void glideImageLoader(Context mContext, String imgUrl, ImageView imageView) {
        Glide.with(mContext).load(imgUrl)
                .thumbnail(0.5f)
                .crossFade()
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(imageView);
    }
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginBottom="@dimen/dp_15"
    android:layout_marginTop="@dimen/dp_5"
    android:orientation="vertical"
    app:cardBackgroundColor="@color/colorPrimary"
    app:cardCornerRadius="@dimen/dp_5">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/f9f9f9"
            android:gravity="center">

            <ImageView
                android:id="@id/thumbnail"
                android:layout_width="@dimen/dp_160"
                android:layout_height="@dimen/dp_160"
                android:layout_marginLeft="@dimen/dp_50"
                android:layout_marginRight="@dimen/dp_50"
                tools:ignore="ContentDescription" />

        </LinearLayout>

        <com.teafloor.utils.TextViewSemiBold
            android:id="@id/title"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:ellipsize="end"
            android:gravity="center|start"
            android:maxLines="1"
            android:minLines="1"
            android:paddingLeft="@dimen/dp_15"
            android:paddingRight="@dimen/dp_15"
            android:textColor="@color/blackShade"
            android:textSize="@dimen/sp_15" />

        <com.teafloor.utils.TextViewRegular
            android:id="@id/description"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:ellipsize="end"
            android:gravity="center|start"
            android:lineSpacingMultiplier="1.1"
            android:maxLines="2"
            android:minLines="2"
            android:paddingBottom="@dimen/dp_15"
            android:paddingLeft="@dimen/dp_15"
            android:paddingRight="@dimen/dp_15"
            android:textColor="@color/blackShade"
            android:textSize="@dimen/sp_13" />

    </LinearLayout>


</android.support.v7.widget.CardView>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by aayushthakur** [comment]
@sjudd Can you please have a look at this?

**Comment by TWiStErRob** [comment]
Looks like #515. Since you're on Glide v3, the default decode format is 565, which may not be able to represent some colors (rounding). Picasso uses 8888 by default. You can change Glide to do the same as well: https://github.com/bumptech/glide/wiki/Configuration#bitmap-format

**Comment by sjudd** [comment]
Duplicate of #515
