### ISSUE TITLE
[Question] Regarding `RequestOptions.onlyRetrieveFromCache(bool)`

### ISSUE THREAD

**Issue by bhargavms** [bumptech/glide#2031]
The docs say

> If the image is found in the memory cache or in the disk cache, it will be loaded. Otherwise, if this option is set to true, the load will fail.

What I want to understand is if I were to set a `RequestListener<File>` using the `.listener()` method, would and also set `onlyRetieveFromCache(true)`, would the api throw Load failed exception and call the  `onLoadFailed` method of the `RequestListener<File>` interface implementation?

**Comment by bhargavms** [comment]
Nevermind I wrote a test, it indeed does call onLoadFailed, awesome! Would be nice if you added it to the docs too

**Comment by sjudd** [comment]
Speaking of pull requests... :)
