### ISSUE TITLE
4.0.0-RC0 NO placeholder() or error() method

### ISSUE THREAD

**Issue by BugMen** [bumptech/glide#2033]
When I was in the use of 4.0.0-RC0, I found placeholder() or error() method not.How to solve it.please

**Comment by nucleartip** [comment]
you can supply this through new class `RequestOptions` and then pass it on to glide using `apply()` api.

**Comment by sjudd** [comment]
For the generated API: http://bumptech.github.io/glide/doc/placeholders.html.

If you want to pass in RequestOptions as @nucleartip suggests: http://bumptech.github.io/glide/doc/options.html#requestoptions
