### ISSUE TITLE
How to show the loading progress with Glide 4.0.0-SNAPSHOT? Thanks!

### ISSUE THREAD

**Issue by sfsheng0322** [bumptech/glide#2034]

**Comment by nucleartip** [comment]
you can use `listener()` api by passing `RequestListener` instance, it has api for notifying request failed and processed, you can choose to display and hide progress base on that.

**Comment by sfsheng0322** [comment]
我封装了一下，可以监听加载图片时的进度
https://github.com/sfsheng0322/GlideImageView

**Comment by Anayuta** [comment]
@sfsheng0322 3.7的版本如果监听？

**Comment by geekmario** [comment]
@Anayuta https://blog.csdn.net/guolin_blog/article/details/78357251
