### ISSUE TITLE
Image flicker using glide 4.0RC 

### ISSUE THREAD

**Issue by nucleartip** [bumptech/glide#2035]
**Glide Version**: 4.0RC

**Integration libraries**: None

**Device/Android Version**: All devices running Android L and above

**Issue details / Repro steps / Use case background**: Image are flickering when used in recycling component, such as List/Recycler view of perhaps any custom adapter view.

this behaviour is only happening when Adapter view is supplied with `ArrayAdapter` and has custom transformations, issue is not happening when only one of build in transformations is used such as `CenterCrop`

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
            Glide.with(getContext())
                    .asBitmap()
                    .load(uri)
                    .apply(options)
                    .listener(new RequestListener<Bitmap>() {

                        @Override
                        public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Bitmap> target,
                                                    boolean isFirstResource) {

                            if (listener != null) {
                                listener.onLoadFailed(uri.toString());
                            }
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(Bitmap resource, Object model, Target<Bitmap> target,
                                                       DataSource dataSource, boolean isFirstResource) {
                            if (listener != null) {
                                listener.onResourceReady(uri.toString(), resource);
                            }
                            return false;
                        }
                    })
                    .into(this);
```

and this is how `RequestOptions` is being built upon

```java
        // either it can be circle or rounded rectangle not both
        if (this.roundedEdgesRadius > 0 && !this.roundAsCircle) {
            options.transform(new RoundedCornersTransformation(getContext(),
                    roundedEdgesRadius,0));
        }


        if (this.roundAsCircle && this.blurr) {
            options.transform(new CropCircleWithBlurTransformation());
        } else if (this.roundAsCircle && this.isGreyScale) {
            options.transform(new CropCircleWithGrayscaleTransformation());
        } else if (this.roundAsCircle) {
            options.transform(new CropCircleTransformation(getContext()));
        } else if (this.blurr) {
            options.transform(new BlurTransformation(getContext()));
        } else if (this.isGreyScale) {
            options.transform(new GrayscaleTransformation(getContext()));
        }


        if (placeHolderImage > 0) {
            options.placeholder(placeHolderImage);
        }

        if (errorImage > 0) {
            options.error(errorImage);
        }

```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by favn1585** [comment]
I see there is an ability to use own transition policy. We can check if this is isFirstResource and image were loaded from memory, but I have no idea how to set it up. Maybe someone can help..

```
DrawableTransitionOptions transitionOptions = DrawableTransitionOptions.with(new TransitionFactory<Drawable>() {
            @Override
            public Transition<Drawable> build(DataSource dataSource, boolean isFirstResource) {
                return null;
            }
        })
```

**Comment by TWiStErRob** [comment]
@favn1585 Look at the existing implementations for TransitionFactory/Transition interfaces for ideas.

**Comment by TWiStErRob** [comment]
@nucleartip can you please expand on the conditions in which you observe the flickering? e.g. scrolling/flinging/forward/backward, first/all the time/when not from cache, ...

**Comment by nucleartip** [comment]
@TWiStErRob its during scrolling or perhaps swiping of views, for instance Image is loaded into view with all transformation applied, when same image is again applied to view a flicker between placeholder and actual view is visible. This behaviour does not show up when only inbuilt transformation is used e.g when same processed image is applied to view it does not flicker when only inbuilt transformation is used e.g `CenterCrop`.

**Comment by favn1585** [comment]
@TWiStErRob I found that issue with flickering appears when I register model. Flickering appears when I call `notifyDataSetChanged()` in `RecyclerView`.

![ezgif-3-e0f9d2a215](https://user-images.githubusercontent.com/3111598/27181294-4b5f8d92-51d7-11e7-8573-75c4f3477b61.gif)

I register model loader in GlideModule

`registry.append(AvatarUrl.class, InputStream.class, new AvatarUrlLoader.Factory());`

My loader:

```
public class AvatarUrlLoader extends AuthUrlLoader<AvatarUrl> {

    private AvatarUrlLoader(ModelLoader<GlideUrl, InputStream> concreteLoader) {
        super(concreteLoader);
    }

    @Override
    protected String getUrl(AvatarUrl avatarUrl, int width, int height, Options options) {
        return avatarUrl.getAvatarUrl();
    }

    public static class Factory implements ModelLoaderFactory<AvatarUrl, InputStream> {

        @Override
        public ModelLoader<AvatarUrl, InputStream> build(MultiModelLoaderFactory multiFactory) {
            return new AvatarUrlLoader(multiFactory.build(GlideUrl.class, InputStream.class));
        }

        @Override
        public void teardown() {
        }
    }
}
```
I have also `AuthLoader`

```
class AuthUrlLoader<T> extends BaseGlideUrlLoader<T> {

    private LazyHeaders.Builder headers;

    AuthUrlLoader(ModelLoader<GlideUrl, InputStream> concreteLoader) {
        super(concreteLoader);
        headers = createHeaders();
    }

    @Override
    protected String getUrl(T t, int width, int height, Options options) {
        return null;
    }

    @Override
    public boolean handles(T t) {
        return true;
    }

    @Nullable
    @Override
    protected Headers getHeaders(T authUrl, int width, int height, Options options) {
        return headers.build();
    }

    private static LazyHeaders.Builder createHeaders() {
        return new LazyHeaders.Builder().addHeader(RequestConstants.AUTHORIZATION_KEY,
                () -> String.format(RequestConstants.AUTHORIZATION_PATTERN, TokenManager.Manager.getToken()));
    }
}
```

If I load simple url  

```
GlideApp.with(context).load(**url**)
                .placeholder(placeholder).error(placeholder).fallback(placeholder)
                .transition(transitionOptions).circleCrop().into(source);
```

But if I load model url, I have this weird flickering

```
GlideApp.with(context).load(**new AvatarUrl(url)**)
                .placeholder(placeholder).error(placeholder).fallback(placeholder)
                .transition(transitionOptions).circleCrop().into(source);
```

I was thinking that problem that I use wrong constructor and cache not stored, but using does not help `ModelCache<AvatarUrl, GlideUrl> modelCache`

**Comment by nucleartip** [comment]
@TWiStErRob can you suggest something for this? our app release is hanging on bridge due to this.

**Comment by sjudd** [comment]
What is AvatarUrl? That flickering you're seeing is Glide re-loading your image. That may be happening because equals() and hashcode() are either not implement or have a bug. Transformations and models (like ``AvatarUrl``) are expected to implement equals() and hashcode().

**Comment by sjudd** [comment]
For an example Transformation, see [CenterCrop][1]. For an example model, see [GlideUrl][2].

[1]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/CenterCrop.java#L16
[2]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/GlideUrl.java#L133

**Comment by girubhai** [comment]
@sjudd Same flicker issue.
Note : using lib version 3.8.0
Can you please give an example of this **because equals() and hashcode() are either not implement or have a bug**

**Comment by TWiStErRob** [comment]
@girubhai just above your comment?

**Comment by girubhai** [comment]
@TWiStErRob yes.

**Comment by girubhai** [comment]
@TWiStErRob Any help/suggestion?

**Comment by nucleartip** [comment]
@sjudd its an string, and i believe it has default impl for hashcode and equals method already.

**Comment by favn1585** [comment]
Overriding `equals` and `hashCode` fix my problem. Thank you so much!

**Comment by girubhai** [comment]
@favn1585 Didn't fix here, can you please share sample code.

**Comment by favn1585** [comment]
@girubhai I don't have such issues on v3.8.0. I am using v4.0. and sample code will not work for 3.8 same as for 4.0

**Comment by TWiStErRob** [comment]
@nucleartip `class AvatarUrl { String url; }` doesn't "inherit" equals/hashCode from String. You need to write delegate methods for it.

@girubhai try writing a proper custom target for your load, you're leaking resource, because the Target lifecycle methods are not handled (e.g. clear).

Also equals/hashCode won't help you because `byte[]` turns off caches. You can try to wrap it in a `class MemoryImage { String cacheKey; byte[] data; hashCode() { return cacheKey.hashCode(); } equals() {...}}` along with a custom loader.

**Comment by nucleartip** [comment]
@TWiStErRob i meant in my case avatarUrl is string literal itself `String avatarUrl`

**Comment by yanxinmiao** [comment]
@favn1585 do you solve your problem that image flicker when recyclerview refreshing ?

**Comment by favn1585** [comment]
@yanxinmiao yes. Read upper:

> Overriding equals and hashCode fix my problem. Thank you so much!

**Comment by yanxinmiao** [comment]
@favn1585 i load image by url ,and print log kown that dataSource is DATA_DISK_CACHE ,but refresh recyvlerview imge also filicker .

**Comment by favn1585** [comment]
Maybe you should set ImageView size manually? I had a problem with flickering when image view size was set after (post) Glide starts loading image

**Comment by yanxinmiao** [comment]
@favn1585  thank you ,my problem is sloved .
the solution is override the Transformation‘s hashcode and equals method .
