### ISSUE TITLE
How to load a bitmap when current process is running Binder process?

### ISSUE THREAD

**Issue by komamj** [bumptech/glide#2038]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
`.into(w, h).get()`, for more info see `FutureTarget`.
