### ISSUE TITLE
when i only use "com.github.bumptech.glide:glide:3.7.0" is ok ,but when i user release and add the " jp.wasabeef:glide-transformations:2.0.0"     com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider.class

### ISSUE THREAD

**Issue by liangjiaxuan** [bumptech/glide#2040]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by nucleartip** [comment]
wasabeef lib is not compatible with glide RC4.0, in new glide version transformation API's has been changed, that guy need to update is library to be compatible, otherwise you can extract the required transformation classes and probably port by yourself.

**Comment by sjudd** [comment]
@nucleartip is correct. You may want to open an issue in that repo to add a branch that works with v4. Porting yourself should be straight forward, there aren't radical changes in the transformation APIs.

**Comment by jamshidch** [comment]
compile'com.github.bumptech.glide:glide"3.7.0'
