### ISSUE TITLE
Question: How to properly use resource type options?

### ISSUE THREAD

**Issue by gajicm93** [bumptech/glide#2041]
Hi, can you explain what exactly resource type options like "asBitmap" and "asDrawable" do, and which should be used for loading JPG images from local files or network? Thanks.

**Comment by TWiStErRob** [comment]
It depends on what you want to do with it. If you just `.into(imageView)`, then don't specify anything. If you need to hack around with the Bitmap or Drawable in the listener/target, then choose accordingly.

**Comment by gajicm93** [comment]
Thanks!
