### ISSUE TITLE
too many load url failed in recycleView 

### ISSUE THREAD

**Issue by s949492225** [bumptech/glide#2045]
Glide: Load failed for http://p.lrlz.com/data/upload/mobile/special/s282/s282_05436927947534653.png with size [1080x60]
                                                          class com.bumptech.glide.load.engine.GlideException: Failed to load resource
Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource

**Comment by sjudd** [comment]
Please fill out the issue template and re-open.
