### ISSUE TITLE
Multiple cache directory in external storage

### ISSUE THREAD

**Issue by vaibhavvishal** [bumptech/glide#2046]
**Glide Version**: 4.0.0-RC0

**Integration libraries**: OkHttp3 : 4.0.0-RC0

**Device/Android Version**: Android N, API 24

**Issue details / Repro steps / Use case background**: 
I have multiple types of images and videos which need to be cached in external storage.
But I want to cache them at different locations depending upon the image and video type.
Is this possible?
E.g.
Types of images available : A and B
I need to cache images of type A at <some location>/cache_root/A/
and of type B at <some location>/cache_root/B/

**Comment by TWiStErRob** [comment]
#1959
