### ISSUE TITLE
Unable to Load SVG image from Web URL

### ISSUE THREAD

**Issue by judemanutd** [bumptech/glide#2050]
I need to load the folowing url http://politico.octave.tech/images/channels/bullhorn.svg from the web.
I have incorporated the following https://github.com/bumptech/glide/tree/master/samples/svg/src/main/java/com/bumptech/glide/samples/svg into my project but the file refuses to load.

I tried the following debugging techniques https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling but the only crash log that i get is the following

` W/Glide: Load failed for http://politico.octave.tech/images/channels/bullhorn.svg with size [-2147483648x-2147483648]
                                                               class com.bumptech.glide.load.engine.GlideException: Failed to load resource
 E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource`

**Comment by TWiStErRob** [comment]
I checked out the glide repo. Edited `p:\projects\contrib\github-glide-v4\samples\svg\src\main\java\com\bumptech\glide\samples\svg\MainActivity.java` to include your URL and then ran `p:\projects\contrib\github-glide-v4> gradlew :samples:svg:run`. The image showed up.

Try to debug `SingleRequest.onLoadFailed` to see the root cause in the exception, the default logLevel should be INFO, so I'm not sure why you're not getting a trace.

**Comment by TWiStErRob** [comment]
Do you have internet permission?

**Comment by judemanutd** [comment]
@TWiStErRob i do but as it turns out i had missed out `@GlideModule` annotation for the SvgModule class.It works now but i have another issue.
I had already created a GlideModule class like so.

   public final class MyAppGlideModule extends AppGlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        super.applyOptions(context, builder);

        RequestOptions requestOptions = new RequestOptions();
        requestOptions.format(DecodeFormat.PREFER_ARGB_8888)
                .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                .centerCrop();
        builder.setDefaultRequestOptions(requestOptions);
    }

    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }
}

But when i try using the same apply options for the SvgModule class it fails to decode the svg but other images like jpg and png load fine.
Is there a way i can apply the above options for files other than svg?

**Comment by TWiStErRob** [comment]
You can't have two App modules, and this one is missing the annotation as well.
Either move the lines from one module to another (merge), or turn the svg module into a library module.

**Comment by judemanutd** [comment]
Using the above code unable to load svg on android version 4.4.
I am not getting any error log for this.

**Comment by edcastrohit** [comment]
is any way to load the svg web url using glide. showing properly in web browser but want to load inside the imageview but glide fails to load svg image url class com.bumptech.glide.load.engine.GlideException: Failed to load resource
