### ISSUE TITLE
How Stop GifDrawable and reset show firstFrame?

### ISSUE THREAD

**Issue by Caij** [bumptech/glide#2052]

**Comment by TWiStErRob** [comment]
How about https://github.com/bumptech/glide/blob/8f22bd9b82349bf748e335b4a31e70c9383fb15a/library/src/main/java/com/bumptech/glide/load/resource/gif/GifDrawable.java#L160?

**Comment by Elliptica1** [comment]
I have the same issue, even though I call that, it still shows the last frame before restarting at the first one

**Comment by BrainCrumbz** [comment]
@Elliptica1 did you open a different issue about that? Or did you manage to solve it? Thanks
