### ISSUE TITLE
Hard to wrap into RxJava Observable with new Listener/Target separation

### ISSUE THREAD

**Issue by onomated** [bumptech/glide#2054]
Glide version: **4.0.0-RC0**

**Issue details / Repro steps / Use case background**: 
With Glide 3.0, wrapping a glide request to an RxJava observable was as simple as:
```java
Observable.create(emitter -> {
            final Target<Bitmap> target = new SimpleTarget<Bitmap>() {
                @Override
                public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                    // Do something with bitmap here, then notify
                    emitter.onNext(resource);
                    emitter.onComplete();
                }

                @Override
                public void onLoadFailed(Exception e, Drawable errorDrawable) {
                    // Perform error side effect here, then notify
                    if (!emitter.isDisposed())
                        emitter.onError(e);  // <-- Targets had access to exception
                }
            };
});

Glide.with(url).asBitmap().into(target);
```

With Glide 4 docs, this can be accomplished with `RequestListener`.  However, it is not as straightforward.  Since the listener is invoked before the target, we now have to invoke the target manually in the listener implementation before notifying Rx subscribers.  Not an problem if we could apply animations the same way you do in `SingleRequest`:
```java
    if (requestListener == null
        || !requestListener.onResourceReady(result, model, target, dataSource, isFirstResource)) {
      Transition<? super R> animation =
          animationFactory.build(dataSource, isFirstResource); // <-- How do we do in client code?
      target.onResourceReady(result, animation);
    }
```

If the exception is added back to the `Target#onLoadFailed` interface, then this is simply solved by applying Rx wrapper functionality to a custom target only, removing the need for the listener in this scenario.  Otherwise, it would help to have guidance on how to apply animations using the glide animation factory.

There is also a javadoc bug in the RequestListener interface definition.  It states that the listener is called after Target#onResourceReady which isn't the case:
```
/**
   * Called when a load completes successfully, immediately after {@link
   * Target#onResourceReady(Object, com.bumptech.glide.request.transition.Transition)}.
```

**Comment by sjudd** [comment]
Is there a reason why you're trying to use RequestListener in Glide v4 instead of Target like you did with v3?

**Comment by sjudd** [comment]
Oh in the code you commented that the Target in v3 got access to the actual exception, which isn't the case in v4, is that it?

You could also just have your Target implement both interfaces, save any exception you receive in onLoadFailed in the RequestListener impl and handle it when the Target's method is called.

**Comment by onomated** [comment]
Yes, I need access to the exception for the Rx Observable wrapper.
I also work around the issue similar to what you describe.  I define a static listener that captures exceptions and maps them to my different target definitions, which I consume in the Target#onLoadFailed.  
Ultimately though, I think this bids the question of the value of a separate listener and/or the reason for omitting exceptions from the Target interface.

**Comment by sjudd** [comment]
One other thought, Glide has an API that returns a Future. That might be a better way to interface with RxJava. See http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/RequestBuilder.html#submit-int-int-
