### ISSUE TITLE
"You must not call setTag() on a view Glide is targeting" exception erroneously thrown

### ISSUE THREAD

**Issue by capezzbr** [bumptech/glide#2055]
**Glide Version**: 4.0.0-RC0

**Integration libraries**: None

**Device/Android Version**: Nexus 4 with Android 6.0.1

**Issue details / Repro steps / Use case background**: 

Had an exception thrown when invoking

```java
Glide.clear(myImageView)
```

I've navigated into the code during runtime, and below you can see what's going on

![image](https://user-images.githubusercontent.com/3534630/27355846-40b30caa-55c1-11e7-81d5-f8ae5ed76a85.png)

which is resulting in the below exception being thrown

```
throw new IllegalArgumentException("You must not call setTag() on a view Glide is targeting")
```

I've tried myself and both `instanceof` and `Request.class.isAssignableFrom(myImageView.getTag().getClass())` are returning `false`

Also in my case `SingleRequest` is `com.bumptech.glide.request.SingleRequest`

let me know if there is any other information needed

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(MyApplication.getInstance())
```

**Layout XML**:
I'm using a custom library to create UI element, but I'm respecting the rule to not assign any tag to my view.

**Comment by TWiStErRob** [comment]
Crazy, can this be multidex?

**Comment by capezzbr** [comment]
Interesting, so I've checked the `build.gradle` and looks like multidex is not enabled

**Comment by TWiStErRob** [comment]
Silly query, but can you check `tag.getClass()` in intermediate debug? Just a hunch it may be a string or some other type whose toString looks ok.

Another thing to check: Request's and SingleRequest's classloader.

**Comment by capezzbr** [comment]
> Silly query, but can you check tag.getClass() in intermediate debug?

![image](https://user-images.githubusercontent.com/3534630/27400749-f691230e-5675-11e7-8ee3-2bc73e8fc696.png)

---

> Another thing to check: Request's and SingleRequest's classloader.

```java
ClassLoader requestClassLoader = Request.class.getClassLoader();
```

```
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-2/lib/arm, /data/app/com.myapp-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]]
```

and

```java
ClassLoader singleRequestClassLoader = SingleRequest.class.getClassLoader();
```

```
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-2/lib/arm, /data/app/com.myapp-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]]
```

---

I've also discovered that `tag instanceof com.bumptech.glide.request.Request` returns `true`

![image](https://user-images.githubusercontent.com/3534630/27401363-daaeac2c-5677-11e7-9758-e45cd0dd4e94.png)

let me know if there is anything else you'd like me to test 🙌

**Comment by TWiStErRob** [comment]
Must be trippin', this looks the weirdest thing.

I have a few more ideas:
 * Try to navigate to `Request` to see what it refers to.
 * print out `Request.class` and `com.bumptech.glide.request.Request.class`
 * also compare those above two with `==` and `equals`

Can you please try to repro this in a small project?
How about AGP 3.0-alpha, may be a desugar or similar bug?
Would you drop me a mail with your APK? (I would read the smali code)

**Comment by capezzbr** [comment]
Opss, I've just discovered the issue, and it's totally my fault.

```
import io.intercom.com.bumptech.glide.Glide;
```

I think I might have imported this by mistake. 🏃

**Comment by TWiStErRob** [comment]
Ah, so the request was of correct type, but the clear was using the repackaged version? Which step helped?

**Comment by capezzbr** [comment]
> Ah, so the request was of correct type, but the clear was using the repackaged version?

Correct

> Which step helped?

>>Try to navigate to Request to see what it refers to

thanks a lot for your help and support 👍
