### ISSUE TITLE
Glide v4.0.0-RC1 diskcachestrategy error.

### ISSUE THREAD

**Issue by Starscream9559** [bumptech/glide#2062]
**4.0.0-RC1**:

**ButterKnife 8.4.0**:

**LG Nexus 5X / Android 8.0.0 Beta 3**:

**I try to upgrde drom ver 3.7.0 to 4.0.0-RC1 but got errors which Glide can't understand DiskCacheStrategy.SOURCE. I got and errors say Error:(62, 180) error: cannot find symbol method diskCacheStrategy(DiskCacheStrategy).**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this).load("https://firebasestorage.googleapis.com/v0/b/travel-and-go-93552.appspot.com/o/My_Victoria_beach1_620.jpg?alt=media&token=1e9cd6db-9d36-4fda-b0d4-283eaa1f3aff").diskCacheStrategy(DiskCacheStrategy.SOURCE).into(img1);
```

**Layout XML**:
```xml
<ImageView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:id="@+id/vict"
                android:scaleType="fitXY"
                android:alpha="0.65"
            />
```

**Stack trace / LogCat**:
```ruby
Error:(62, 180) error: cannot find symbol method diskCacheStrategy(DiskCacheStrategy)
```

![s](https://user-images.githubusercontent.com/12114864/27415016-45720940-5737-11e7-9e77-3c4461a2a2a0.PNG)

**Comment by pallavgrover** [comment]
You have to use 
```
RequestOptions requestOptions = new RequestOptions();
requestOptions.diskCacheStrategy(DiskCacheStrategy.SOURCE)
```
then 

`Glide.with(this).load("https://firebasestorage.googleapis.com/v0/b/travel-and-go-93552.appspot.com/o/My_Victoria_beach1_620.jpg?alt=media&token=1e9cd6db-9d36-4fda-b0d4-283eaa1f3aff").apply(requestOptions).into(img1);
`
From v4 we have to add option

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/migrating.html#requestoptions.

To inline those options methods, see also: http://bumptech.github.io/glide/doc/generatedapi.html

**Comment by Starscream9559** [comment]
Oh, you mean in v4 diskCacheStrategy need to be separated from Glide call? declare diskCacheStrategy and call the method back in Glide call...? It kinda looks the same as before.

**Comment by TWiStErRob** [comment]
@Starscream9559 Use generated api to call it without request options.

Strategies got smarter: https://github.com/bumptech/glide/compare/v3.8.0...v4.0.0-RC1#diff-dfd10e58078a83f42eee8f6aeb17d5c1

**Comment by Starscream9559** [comment]
Ok, now Ive applied all activities that use Glide with that RequestOptions. and .apply(requestOptions) after .load(url)...
My Java file got no errors, but the app force close without even open first activity (ANR).. what's wrong..?
Logcat says that I got error on this line;

**Glide.with(this).load("https://firebasestorage.googleapis.com/v0/b/travel-and-go-93552.appspot.com/o/buku.png?alt=media&token=bad59236-e4ff-44e0-81ac-32adf9c1aea4").apply(req).into(buku);**

But the IDE shows no error.

**Comment by TWiStErRob** [comment]
Well without an error it's pretty hard to tell. I usually diagnose infinite loops by attaching the debugger, letting it hang for a few seconds and then pausing the app (in Debugger hit the `||` button). After this you can check each Thread's state/stack. Find out the one that's busy. Also check CPU/Memory monitors near LogCat in AS.

**Comment by Starscream9559** [comment]
Well @TWiStErRob of course debugging has been done and as I stop at the Glide line, the screen is displayed but no content. so that make me thing the root of error (which is regarding to the new version).
Letme try revoke to 3.7.0 and make that activity as usual.

**Comment by TWiStErRob** [comment]
> as I stop at the Glide line

which one?

> displayed but no content

Have you just tried https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling to see the logs / add a listener?

**Comment by Starscream9559** [comment]
Yep at that line `Glide.with().....` 
i mean it likes a TextView with no text.
not try that yet cuz didnt know how to use it.
