### ISSUE TITLE
java.net.ProtocolException: Unexpected status line

### ISSUE THREAD

**Issue by DizzyYang** [bumptech/glide#2063]
Glide Version: 3.8.0

Integration libraries: OkHttp3

This question does not specify which picture, again reloaded several times to show normal

java.net.ProtocolException: Unexpected status line: `������JFIF������������������ZExif����MM��*�����������������������i��������������&���������������������������������������������������������������������,Photoshop 3.0��8BIM%������������ُ����	���B~����C��`

EngineJob.class ->

```java
private void handleExceptionOnMainThread() {
        if(!this.isCancelled) {
            if(this.cbs.isEmpty()) {
                throw new IllegalStateException("Received an exception without any callbacks to notify");
            } else {
                this.hasException = true;
                this.listener.onEngineJobComplete(this.key, (EngineResource)null);
                Iterator i$ = this.cbs.iterator();

                while(i$.hasNext()) {
                    ResourceCallback cb = (ResourceCallback)i$.next();
                    if(!this.isInIgnoredCallbacks(cb)) {
                        cb.onException(this.exception);      exception:"java.net.ProtocolException: Unexpected status line: ������JFIF������������������ZExif����MM��*�����������������������i��������������&���������������������������������������������������������������������,Photoshop 3.0��8BIM%������������ُ����	���B~����C��"
                    }
                }

            }
        }
    }
```

**Comment by DizzyYang** [comment]
Glide.with(getApplicationContext()).load(imageUrl).asBitmap().centerCrop().listener(new RequestListener<String, Bitmap>() {
                @Override
                public boolean onException(Exception e, String s, Target<Bitmap> target, boolean b) {
                    L.e("Glide", "Exception: " + e.toString() + " String: " + s);
                    return false;
                }

                @Override
                public boolean onResourceReady(Bitmap bitmap, String s, Target<Bitmap> target, boolean b, boolean b1) {
                    L.e("Glide", "String: " + s);
                    return false;
                }
            }).into(new SimpleTarget<Bitmap>(200, 200) {

                @Override
                public void onResourceReady(Bitmap logo, GlideAnimation<? super Bitmap> glideAnimation) {

                }

                @Override
                public void onLoadFailed(Exception e, Drawable errorDrawable) {

                }
            });

**Comment by TWiStErRob** [comment]
At first glance that looks like your web server returns the content in HTTP response message?

**Comment by DizzyYang** [comment]
My suspicions are the same, but when I use the debug time to finally locate here.

EngineRunnable.class->

public void run() {
        if(!this.isCancelled) {
            Object exception = null;
            Resource resource = null;

            try {
                resource = this.decode();
            } catch (OutOfMemoryError var4) {
                if(Log.isLoggable("EngineRunnable", 2)) {
                    Log.v("EngineRunnable", "Out Of Memory Error decoding", var4);
                }

                exception = new ErrorWrappingGlideException(var4);
            } catch (Exception var5) {
                if(Log.isLoggable("EngineRunnable", 2)) {
                    Log.v("EngineRunnable", "Exception decoding", var5);
                }

                exception = var5;  exception:"java.net.ProtocolException: Unexpected status line: �������JFIF���������������������ZExif����MM��*������������������������������i����������������&����������������������������������������������������������������������������������,Photoshop 3.0��8BIM�%��������������ُ�����	���B~����C��������"
            }

            if(this.isCancelled) {
                if(resource != null) {
                    resource.recycle();
                }

            } else {
                if(resource == null) {
                    this.onLoadFailed((Exception)exception);
                } else {
                    this.onLoadComplete(resource);
                }

            }
        }
    }

**Comment by DizzyYang** [comment]
I seem to have found a specific problem, but I still do not know how this is generated

HttpUrlFetcher.class->

int statusCode1 = this.urlConnection.getResponseCode(); // Wait for later

Jumped up ImageVideoModelLoader.class->

public ImageVideoWrapper loadData(Priority priority) throws Exception {
            InputStream is = null;
            if(this.streamFetcher != null) {
                try {
                    is = (InputStream)this.streamFetcher.loadData(priority);
                } catch (Exception var6) {
                    if(Log.isLoggable("IVML", 2)) {
                        Log.v("IVML", "Exception fetching input stream, trying ParcelFileDescriptor", var6);
                    }

                    if(this.fileDescriptorFetcher == null) {
                        throw var6;   exception:"java.net.ProtocolException: Unexpected status line: �������JFIF���������������������ZExif����MM��*������������������������������i����������������&����������������������������������������������������������������������������������,Photoshop 3.0��8BIM�%��������������ُ�����	���B~����C��������"
                    }
                }
            }

            ParcelFileDescriptor fileDescriptor = null;
            if(this.fileDescriptorFetcher != null) {
                try {
                    fileDescriptor = (ParcelFileDescriptor)this.fileDescriptorFetcher.loadData(priority);
                } catch (Exception var5) {
                    if(Log.isLoggable("IVML", 2)) {
                        Log.v("IVML", "Exception fetching ParcelFileDescriptor", var5);
                    }

                    if(is == null) {
                        throw var5;
                    }
                }
            }

            return new ImageVideoWrapper(is, fileDescriptor);
        }

Jumped up EngineRunnable.class->

public void run() {
        if(!this.isCancelled) {
            Object exception = null;
            Resource resource = null;

            try {
                resource = this.decode();
            } catch (OutOfMemoryError var4) {
                if(Log.isLoggable("EngineRunnable", 2)) {
                    Log.v("EngineRunnable", "Out Of Memory Error decoding", var4);
                }

                exception = new ErrorWrappingGlideException(var4);
            } catch (Exception var5) {
                if(Log.isLoggable("EngineRunnable", 2)) {
                    Log.v("EngineRunnable", "Exception decoding", var5);
                }

                exception = var5;   exception:"java.net.ProtocolException: Unexpected status line: �������JFIF���������������������ZExif����MM��*������������������������������i����������������&����������������������������������������������������������������������������������,Photoshop 3.0��8BIM�%��������������ُ�����	���B~����C��������"
            }

            if(this.isCancelled) {
                if(resource != null) {
                    resource.recycle();
                }

            } else {
                if(resource == null) {
                    this.onLoadFailed((Exception)exception);
                } else {
                    this.onLoadComplete(resource);
                }

            }
        }
    }

**Comment by DizzyYang** [comment]
@TWiStErRob Thank you, the problem I should know, I wrote a simple access to the picture stream procedures, but in my getInputStream () when the throw this exception.
