### ISSUE TITLE
Glide and Activity onDestroy

### ISSUE THREAD

**Issue by jehoon77** [bumptech/glide#2065]
**Glide Version**: 4.0 rc0

**Integration libraries**: none

**Device/Android Version**: independant

**Issue details / Repro steps / Use case background**: 

I have some problems in my app.
Crashlytics reports some crashes but i cannot handle it.

My application loads local image files and show them in recycler view.

issues are two.

first. 

Fatal Exception: java.lang.IllegalStateException
Cannot pool recycled bitmap

com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.put (SourceFile:86)
com.bumptech.glide.load.resource.bitmap.LazyBitmapDrawableResource.recycle (SourceFile:57)
com.bumptech.glide.load.engine.LockedResource.recycle (SourceFile:83)
com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread (SourceFile:1170)
android.os.Handler.dispatchMessage (Handler.java:98)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

There is no "Bitmap.recycle()" codes written by me.
I guess that the activity was destroyed before glide handles the result. is it possible?

maybe 5% of users a day encounter this crash.

Second.

Fatal Exception: java.lang.IllegalStateException
Cannot recycle a resource that has already been recycled

com.bumptech.glide.load.engine.EngineResource.recycle (SourceFile:60)
com.bumptech.glide.load.engine.ResourceRecycler$ResourceRecyclerCallback.handleMessage (SourceFile:43)
android.os.Handler.dispatchMessage (Handler.java:98)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(context)
                                    .load(model)
                                    .apply(options)
                                    .listener(requestListener)
                                    .transition(DrawableTransitionOptions.withCrossFade())
                                    .into(imageView)
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
What are the options and what does listener do?
Also: any tiger usages of Glide?

**Comment by jehoon77** [comment]
option is very simple

RequestOptions options = RequestOptions.placeholderOf(placeHolder);

just setting a placeholder drawable which is color drawable.

thanks.

**Comment by TWiStErRob** [comment]
can you please answer the other two questions?

**Comment by jehoon77** [comment]
okay. i forgot to mention about listener.

in listener 
I check exception and drawable and call my own callback and return true.

thanks for advance

**Comment by jehoon77** [comment]
issue also exists in rc1
