### ISSUE TITLE
How do you make the picture rounded and rounded?

### ISSUE THREAD

**Issue by to686312** [bumptech/glide#2068]
Using the older version is okay, and 4.0.0 can't succeed in asking for it

**Comment by TWiStErRob** [comment]
There should be a built-in circle crop transformation in v4.

**Comment by to686312** [comment]
Can you make it more detailed?

**Comment by TWiStErRob** [comment]
Sorry, was walking to work, couldn't research.

`GlideApp.with(this).load(url).centerCrop().into(imageView);` or if you don't have the [generated API](http://bumptech.github.io/glide/doc/generatedapi.html): `Glide.with(this).load(url).apply(new RequestOptions().centerCrop()).into(imageView);`

For more see http://bumptech.github.io/glide/doc/options.html
