### ISSUE TITLE
Get cache file in Glide 4.0.0-RC1

### ISSUE THREAD

**Issue by icoolguy1995** [bumptech/glide#2069]
Using Glide 4.0.0-RC1

Hi! I am trying to migrate from Glide 3.7.0 to Glide 4.0.0RC1. Now I am trying to get cache image from glide to use it later. In Glide 3.7.0 I get file like this:
```

 private class ShareTask extends AsyncTask<String, Void, File> {
        private final Context context;
        ShareTask(Context context) {
            this.context = context;
        }
        @Override
        protected File doInBackground(String... params) {
            String url = params[0];
            try {
                
                return Glide
                        .with(context)
                        .load(url)
                        .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                        .get();

            } catch (Exception ex) {
                return null;
            }
        }
        @Override
        protected void onPostExecute(File result) {
            if (result == null) {
                return;
            }
            Uri uri = FileProvider.getUriForFile(context, context.getPackageName(), result);
        }
    }
```
But in Glide 4.0.0-RC1 `Downloadonly` is deprecated and `.get()` is also unresolved when using `RequestManager` Could someone point me in the right direction?

Thanks!

**Comment by icoolguy1995** [comment]
So now I am using
```
RequestManager rc = Glide.with(this);
rc.downloadOnly();
```
Now the problem is that `rc.downloadOnly();` does not return `file` it returns `RequestBuilder<File>`. Now how can I use `RequestBuilder<File>`. to get `Uri`?

**Comment by TWiStErRob** [comment]
Try this:
```java
RequestManager rc = Glide.with(this);
File file = rc.downloadOnly().|;
```
put your cursor at `|` and press CTRL+SHIFT+Space (Smart Type) twice in IDEA. It should figure it out for you:
![2017-06-23_20-58-24](https://user-images.githubusercontent.com/2906988/27498414-c0f87b2e-5856-11e7-9ec4-57cba521ca3c.gif)

Also (note the deprecation messages):
![image](https://user-images.githubusercontent.com/2906988/27498475-18c323e0-5857-11e7-9591-eceed331542f.png)
![image](https://user-images.githubusercontent.com/2906988/27498504-386d84f6-5857-11e7-893b-8ae8e0d0eef9.png)

**Comment by TWiStErRob** [comment]
(Updated `ShareTask` in the original issue;
Thank you for opening a new issue and not appending to that monster conversation!)
