### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;

### ISSUE THREAD

**Issue by bshikhar13** [bumptech/glide#2071]
simple `Glide.with(context).load(url).into(image)` not working after syncing the project with 
  ```
compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
  compile 'com.android.support:support-v4:25.3.1'
  annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'
```

**Comment by bshikhar13** [comment]
Even after shifting to Glide 3.8.0 the error is persisting.

**Comment by sjudd** [comment]
Is this in Android Studio? Gradle? If it's one or the other, have you tried the one you're not using? 

This doesn't look like an issue with the library, but with your build setup. Someone might be able to help better if you provide more detail, like your complete build.gradle file or the complete error you're seeing.
