### ISSUE TITLE
Download .ashximage from server

### ISSUE THREAD

**Issue by Anmolk22** [bumptech/glide#2072]
Can we use Glide to download an image from a url ending with .ashx ? If not then what alternate do we have

**Comment by TWiStErRob** [comment]
You can download anything as long as it's standard HTTP/HTTPS, or even Android Content Uri. Content type doesn't matter either.

The file type is deduced from image header (first few bytes), not from the url.

**Comment by Anmolk22** [comment]
Actually server is .net server.
And when I give path to the image which ends with .ashx it doesn't return anything

**Comment by TWiStErRob** [comment]
Glide can't load empty response... ;)

But in seriousness, what's the error? https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
