### ISSUE TITLE
RequestOptionsExtensions must be public, with private constructors and only static methods. Found a non-private constructor

### ISSUE THREAD

**Issue by msquare097** [bumptech/glide#2073]
**Glide Version**:com.github.bumptech.glide:glide:4.0.0-RC1

**Integration libraries**:"com.github.bumptech.glide:okhttp3-integration:4.0.0-RC1"

**Device/Android Version**:N/A

**Stack trace / LogCat**:
```ruby
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: RequestOptionsExtensions must be public, with private constructors and only static methods. Found a non-private constructor
```

Everything working perfectly. But got this error only when i add extension using below code.

```
@GlideExtension
public class MyAppExtension {

    @GlideOption
    public static void applyOptions(RequestOptions options) {
        options
                .placeholder(R.drawable.tmp_placeholder)
                .error(R.drawable.tmp_placeholder_error)
                .fitCenter();
    }
}

```

The above class i just copied from Glide v4 wiki. and just added "placeholder" and "error".

**Comment by TWiStErRob** [comment]
`Found a non-private constructor`, because Java auto-generates `public MyAppExtension() { super(); }`. Add `private MyAppExtension() {}` to your class.

**Comment by TWiStErRob** [comment]
The doc at http://bumptech.github.io/glide/doc/generatedapi.html says
> They should have a private and empty constructor.

updated the doc with #2076, please let us know if that fixes your problem.
