### ISSUE TITLE
encodeQuality not work !

### ISSUE THREAD

**Issue by Hitexroid** [bumptech/glide#2075]
`requestOptions.encodeQuality(50);
requestBuilder.apply(requestOptions);`

but not decrease quality.

**Comment by TWiStErRob** [comment]
This is just a guess, but try `requestOptions = requestOptions.encodeQuality(50);` or better yet
```java
requestBuilder
    .apply(new RequestOptions()
        ...
        .encodeQuality(50)
    )
    .into(blah);
```
The options may create a copy of itself in some cases so the returned object is not the same as the object you called the method on.

Or as an other possiblity: the `encodeQuality` only affects what's on disk, but the resource is loaded from the original stream (not sure). So you'll only see quality degradation if the image is coming from disk cache (force kill and restart the app).

Yet another idea, the format you're using doesn't support quality, that is PNG; or the quality is so good you can't see the difference, maybe WEBP?
