### ISSUE TITLE
Is '|' char allowed in GlideUrl?

### ISSUE THREAD

**Issue by belinwu** [bumptech/glide#2080]
The char '|' isn't in ALLOWED_URI_CHARS = "@#&=*+-_.,:!?()/~\'%", Why?

**Comment by TWiStErRob** [comment]
It is allowed, it's just not as a literal; it'll be percent-encoded iirc.

**Comment by belinwu** [comment]
The problem is that it is percent-encoded, and I wanna it as a literal.

**Comment by TWiStErRob** [comment]
Where does this make a difference?

**Comment by belinwu** [comment]
Because it is used as a delimiter. 
I'll fix that by myself. 
Thank you!

**Comment by TWiStErRob** [comment]
You should probably parse the delimited text after Uri decoding.

**Comment by belinwu** [comment]
@TWiStErRob OK! Thank you!
