### ISSUE TITLE
ClassCastException com.bumptech.glide.request.target.SquaringDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

### ISSUE THREAD

**Issue by developer--** [bumptech/glide#2083]
Glide version is   `compile 'com.github.bumptech.glide:glide:3.7.0'`

I'm trying to get bitmap from imageView
this is code snippent which causes the error
`        Bitmap bitmap = ((BitmapDrawable)profileImageView.getDrawable()).getBitmap();
`

**Comment by TWiStErRob** [comment]
Well, the message is clear, it is not of that type. You can't expect it to be exactly that unless you set it so. Are you using `.asBitmap()` on the builder?

**Comment by developer--** [comment]
@TWiStErRob now I'm using .asBitmap() and it works.

**Comment by TWiStErRob** [comment]
Note: 3.8.0 is out, consider upgrading
