### ISSUE TITLE
4.0.0-RC1 - Combined transformations

### ISSUE THREAD

**Issue by realdeadfish** [bumptech/glide#2086]
I wrote a custom transformation that uses a `BitmapShader` to "center-crop" an image (an animated GIF) to the outside's width / height of the container, while applying rounded corners to it. This works all nicely now, except that I need another transformation on the same thing, namely a blur transformation.

The issue here is now that I cannot apply the blur transformation before I center-crop the image in the other transformation, because the center-cropping might upscale the image resulting in blur / scaling artifacts.

Due to my transformation's corner rounding however I also cannot apply the blur transformation after the center-crop transformation, because this would naturally blur my just cut-out edges. So I thought, well, maybe I need another pass, even if it's ugly, to again cut-out my image after blurring, so I basically did this:

    CenterCropRoundedCornersTransformation roundCornerTransformation =
              new CenterCropRoundedCornersTransformation(...);
    RequestOptions options = new RequestOptions();
    options.transform(roundCornerTransformation);
    options.transform(new BlurTransformation(...));
    options.transform(roundCornerTransformation);
    Glide.with(context)
              .load(file)
              .apply(options)
              .into(imageView);

Now what struck me was that the `BlurTransformation` code does not seem to get executed at all, i.e. during debugging I never actually got into this transformation's `transform(...)` method. So I dug deeper into the code and figured that for some (to me unknown) reason transformations are registed in a map by their drawable type, where they overwrite each other without further notice. This however is contrary to the fact again that _two_ transformations (one corner and one blur) seem to somehow work flawlessly, but when adding the third the thing falls apart.

I guess you're saying now "it's inefficient to apply more than one transformation" and I guess you're right and if the solution is really to combine cropping, rounding and blurring into one transformation, I'll certainly try to accomplish that, but for now I thought of code re-use, i.e. being able to mix and match single transformations easily together, but that seems to have unexpected boundaries.

**Comment by realdeadfish** [comment]
OK, my fault, it really does not work with two transformations, I just see that my blur transformation actually replaces the original transformation - the (test) images just happen to be scaled properly so not much center-cropping took actually place. So, is there a way to chain transformations then at all?

**Comment by realdeadfish** [comment]
I came up with a `CombinedTransformation` class that I paste here for reference. This just executes any number of transformations one after another:

```
class CombinedTransformation(vararg val transformations: Transformation<Bitmap>) 
        : Transformation<Bitmap> {
    override fun transform(context: Context, resource: Resource<Bitmap>, 
                           outWidth: Int, outHeight: Int): Resource<Bitmap> {
        var out = resource
        for (transformation in transformations) {
            out = transformation.transform(context, out, outWidth, outHeight)
        }
        return out
    }
    override fun updateDiskCacheKey(messageDigest: MessageDigest) {
        transformations.forEach { it.updateDiskCacheKey(messageDigest) }
    }
}
```

**Comment by sjudd** [comment]
You can use http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/load/MultiTransformation.html.

I switched to making transform override rather than append transformations so that it was possible to replace a previously set transformation. We could add a helper method like ``multiTransform(Transformation...)`` that would let you pass in multiple transformations at the same time and make the API a bit more discoverable.

I'd welcome a pull request to add the helper method if you're interested.

**Comment by realdeadfish** [comment]
`MultiTransformation` - nice, this is what I need indeed. The doc improvements help as well. Let me have a look into this helper method next week - I have then some time for it during my vacation.

**Comment by sjudd** [comment]
I believe this is fixed.
