### ISSUE TITLE
cannot resolve symbol 'GlideApp'(After the Make Project)

### ISSUE THREAD

**Issue by SuperXpher** [bumptech/glide#2087]
After the Make Project, it still prompts "can not resolve symbol 'GlideApp',Ask for help~

`compile 'com.github.bumptech.glide:glide:4.0.0-RC1'

  annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'`

`@GlideModule
public final class MyAppGlideModule extends AppGlideModule {}`

Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

**Comment by ragasjohn** [comment]
Same here.
Help please

**Comment by sjudd** [comment]
Make sure you're following all the steps here: http://bumptech.github.io/glide/doc/generatedapi.html#getting-started. Check to see if it works if you just run your build with gradle directly.

If gradle fails as well and you can reproduce this in a sample app, please attach one here and re-open the issue.

**Comment by AudienL** [comment]
mush add :
```
annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'
```

**Comment by sjudd** [comment]
Duplicate of #1939

**Comment by pattagobi** [comment]
Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored


how to fix this.. i did everything as per the docs .. please help
