### ISSUE TITLE
 java.lang.AssertionError: No yet implemented

### ISSUE THREAD

**Issue by JackHang** [bumptech/glide#2088]
**Glide Version**:
    compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'

**Issue details / Repro steps / Use case background**: 
![setting](http://i4.piimg.com/1949/5897d712210a5fd5.png)

Error:Execution failed for task ':app:transformJackWithJackForDebug'.
> com.android.jack.ir.JNodeInternalError: java.lang.Exception: java.lang.AssertionError: No yet implemented

**Comment by sjudd** [comment]
Yeah I ran into this trying to use Java 8 too. SInce jack is deprecated, I doubt this will be fixed. 

There does appear to be an alpha version of the Android gradle plugin you can use instead: https://developer.android.com/studio/write/java8-support.html
