### ISSUE TITLE
V4 Generated API support Kotlin

### ISSUE THREAD

**Issue by jumperson** [bumptech/glide#2089]
I use Glide 4.0.0:RC1 with Kotlin 1.1.2-5 (kapt3).
I want to use Generated API.
I implemented AppGlideModule class by Kotlin.

```
import com.bumptech.glide.annotation.GlideModule
import com.bumptech.glide.module.AppGlideModule

@GlideModule
class MyAppGlideModule : AppGlideModule()
```

`buid.gradle` is

```
    compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'
```
But GlideApp class was not generated.
Maybe Annotation Processing is not working.

I changed `build.gradle` .
```
    compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
    kapt 'com.github.bumptech.glide:compiler:4.0.0-RC1'
```
And I retried.
As result, GlideApp clas was generated!!!

Is this result expected or not?
Or was it a success by change?

**Comment by sjudd** [comment]
I'm not particularly familiar with Kotlin, but it looks like kapt might be Kotlin's equivalent of annotationProccessor: https://kotlinlang.org/docs/reference/kapt.html.

Thanks for pointing out that this works for you.

**Comment by gildor** [comment]
@jumperson You must use `kapt` instead `annotationProcessor` if you want to generate any code from annotated Kotlin code (annotationProcessor knows nothing about Kotlin).
So there are only two options:
1. Convert MyAppGlideModule to Java and use annotationProcessor
2. Use kapt

**Comment by sjudd** [comment]
Thanks @gildor and @jumperson. I've added a couple of brief sections to our documentation on kapt and getting the generated API working with Kotlin. Please let me know (or send a PR) if I've missed anything.

**Comment by jumperson** [comment]
Thanks @gildor for comment!! Thanks @sjudd for adding to the documentation!!
LGTM

**Comment by DCRichards** [comment]
I've added further clarification to the docs, as the `kotlin-kapt` plugin is also required in `build.gradle` for it to work, which wasn't clear for some people. There's a nice [PR here](https://github.com/bumptech/glide/pull/2435).
