### ISSUE TITLE
ImageView Height Wrap_Content Loads Image Incorrectly

### ISSUE THREAD

**Issue by christianrei** [bumptech/glide#2091]
**Glide Version**: 3.7.0

**Integration libraries**: None

**Device/Android Version**: Genymotion Nexus 5 API Level 21

**Issue details / Repro steps / Use case background**: The code is currently in a List View. Images need to be loaded into an ImageView. Sometimes the image will load properly and look good but if I scroll away and scroll back up to see the Image again it will load differently the next time. The width is always the same because I have that set to match_parent. It seems wrap content for the height is the big issue. How can I fix this so that the height being loaded for the same image isn't constantly changing each time?
```xml
<ImageView
        android:id="@+id/LinkPreviewImage"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical"
        android:adjustViewBounds="true"
        android:maxHeight="200dp"
        android:scaleType="fitCenter" />
```
I also tried multiple different scale types so that is not the problem.

Here is the Glide call:
```java
public static void LoadPreview(ImageView view, string location)
{
	try
	{
		if (string.IsNullOrWhiteSpace(location))
			return;

		var locationTuple = GetLocation(location);
		Glide
			.With(view.Context)
			.Load(locationTuple.Item2)
                        .Error(Resource.Drawable.LinkPreviewDefaultImage)
                        .DontAnimate()
			.DiskCacheStrategy(locationTuple.Item1 ? DiskCacheStrategy.None : DiskCacheStrategy.All)
			.Into(view);
	}
	catch
	{
		// fall-through
	}
}
```

**Layout XML**: The ImageView is inside a LinearLayout. This LinearLayout is inside another LinearLayout, inside a RelativeLayout, inside 3 more LinearLayouts.

**Comment by liufsd** [comment]
"wrap_content" problem +1
