### ISSUE TITLE
can't access to trasform() and bitmapTransform(). Kotlin

### ISSUE THREAD

**Issue by Savrov** [bumptech/glide#2094]
I can't access to trasform() and bitmapTransform() methods using **Kotlin**. 
![todayfragment_kt_-_gym_-____documents_workspaceandroid_gym__-_android_studio_3_0_canary_4](https://user-images.githubusercontent.com/5410076/27761142-c744f7c2-5e56-11e7-89f0-088f2c641585.png)

my dependecies:
```
    compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'
    compile 'jp.wasabeef:glide-transformations:2.0.2'
```
Can you navigate me how to solve it? Thank you.

**Comment by TWiStErRob** [comment]
I guess you found GlideApp or apply?

**Comment by Savrov** [comment]
@TWiStErRob yeah, apply() method with "options" list

**Comment by TWiStErRob** [comment]
Ah, didn't notice Kotlin, sorry.
You can use kapt to get a full builder with GlideApp, see http://bumptech.github.io/glide/doc/generatedapi.html
