### ISSUE TITLE
GlideApp cannot resolve symbol, or Glide cannot support error() current verrsion 4.0.0-RC1

### ISSUE THREAD

**Issue by nguyentthai96** [bumptech/glide#2095]
I include 
compile 'com.github.bumptech.glide:glide:4.0.0-RC1' 
and annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'
but GlideApp cannot resolve symbol. I only can resolve found Glide and it cannot support placeholder and cannot resolve when load image from server error I cannot set image default orther.
Please, help I, Thank for every help.

**Comment by TWiStErRob** [comment]
Normal Glide supports all those as well, just not on the main builder. You can use `.apply(new RequestOptions()....)`.

To get GlideApp you need an app module and you need to compile once to get it generated (hammer icon, not the play button in AS). See http://bumptech.github.io/glide/doc/generatedapi.html, you may have missed step 2)

**Comment by nguyentthai96** [comment]
Thank you, it work nice.

2017-07-01 18:34 GMT+07:00 Róbert Papp <notifications@github.com>:
