### ISSUE TITLE
When we set the width and height of the ImageView to wrap_content and its parent layout is wrap_content, how Glide calculates the image size.

### ISSUE THREAD

**Issue by wcglws** [bumptech/glide#2098]
When we set the width and height of the ImageView to wrap_content and its parent layout is wrap_content, how Glide calculates the image size.

**Comment by sjudd** [comment]
Wrap content is usually treated as Target.SIZE_ORIGINAL. See https://github.com/bumptech/glide/blob/8f22bd9b82349bf748e335b4a31e70c9383fb15a/library/src/main/java/com/bumptech/glide/request/target/ViewTarget.java#L202
