### ISSUE TITLE
can we load .svg imageview by glide 

### ISSUE THREAD

**Issue by sunfangcheng** [bumptech/glide#2099]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
See the SVG sample: https://github.com/bumptech/glide/tree/8f22bd9b82349bf748e335b4a31e70c9383fb15a/samples/svg.

If you're asking about placeholders, then yes if you're using the v7 support library.
