### ISSUE TITLE
Recycler view placeholder issue

### ISSUE THREAD

**Issue by pallavgrover** [bumptech/glide#2102]
**Glide Version**:4.0.0-RC1

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: So what i want is to have a placeholder before loading images which is working fine the first time in recycler view but once some images are loaded and i scroll down new images are loaded and then when i scroll back up come the new images are replaced with the old ones what i want is to see placeholder rather than the image getting replaced. Please help with this .

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
You shouldn't see the old image when scrolling at all. Can you please share your code?

And maybe a `screenrecord` demonstrating the behaviour you don't want.

**Comment by pallavgrover** [comment]
Please find the video record in this
[2017_07_03_20_01_38.zip](https://github.com/bumptech/glide/files/1119908/2017_07_03_20_01_38.zip)

**Comment by pallavgrover** [comment]
```
RequestOptions cropOptions = new RequestOptions();
        cropOptions.placeholder(this.getDrawable());
GlideApp.with(mContext).load(url).transition(withCrossFade()).apply(cropOptions).into(this);
```

**Comment by pallavgrover** [comment]
Did you @TWiStErRob look at it ?
