### ISSUE TITLE
"Cannot resolve method using[...]"

### ISSUE THREAD

**Issue by PLPellegrini** [bumptech/glide#2103]
https://stackoverflow.com/questions/44832599/cannot-resolve-method-usingcom-firebase-ui-storage-images-firebaseimageloader

I'm having the same problem on my end. It tells me nothing more than 
"Cannot resolve method using(com.ui.firebase.storage.images.FirebaseImageLoader)". 
Everything else seems to be working fine.

  * FirebaseUI version: 1.2.0
  * Glide version: 4.0.0-RC1

**Comment by TWiStErRob** [comment]
FirebaseUI will have to update to Glide 4 as well. I'll post an answer to SO for a workaround if it's possible.

**Comment by sjudd** [comment]
Firebase was updated here: https://github.com/firebase/FirebaseUI-Android/issues/731

**Comment by PeterHdd** [comment]
According to this http://bumptech.github.io/glide/doc/migrating.html#using, using() was removed from Glide 4, so it cannot be used in firebase, is that right?

**Comment by TWiStErRob** [comment]
@PeterHdd Even if `using` was available, the interface would've changed. You can still achieve the same functionality with Glide modules. Note that even in 3.x the preferred way would've been to use a pre-registered loader to handle Firebase types.
Note: a loader is a simple glue between the two libraries (Glide and external), they're usually very simple so you can always write your own.

**Comment by PeterHdd** [comment]
Thank you so much for answering, this is the first time I post on github. Yes, I was answering this question on stackoverflow https://stackoverflow.com/questions/48762263/using-firebase-storage-image-with-glide. It is why I asked. Thank you!
