### ISSUE TITLE
Not able to import GlideDrawable (Glide.4.0.0)

### ISSUE THREAD

**Issue by theashwin007** [bumptech/glide#2104]
Following imports are failing when I upgraded Glide from 'com.github.bumptech.glide:glide:3.7.0' to 'com.github.bumptech.glide:glide:4.0.0-RC1'.
```java
import com.bumptech.glide.load.resource.drawable.GlideDrawable;
import com.bumptech.glide.request.RequestListener;
import com.bumptech.glide.request.target.Target;



   Glide.with(context)
                .load(itemImageView.getImageurl())
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model,
                                                   Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        animatePhoto(holder);
                        return false;
                    }
                })
                .into(holder.ivPhoto);

```

**Comment by TWiStErRob** [comment]
There's no `GlideDrawable` any more, just change the types to `Drawable`.

**Comment by theashwin007** [comment]
Thanks. I replaced with Drawable. It worked. But I am getting bitmapTransform not found in below code

 Glide.with(context).load(R.drawable.meera)
                    .bitmapTransform(new CropCircleTransformation(context))
                    .into(holder.ivUserAvatar);

**Comment by sjudd** [comment]
For applying transformations, see: http://bumptech.github.io/glide/doc/transformations.html#applying-transformations

**Comment by Newtoxton** [comment]
I Am faced with this major issues after migrating my project to androidx.

error: cannot find symbol
import com.bumptech.glide.load.resource.drawable.Drawable;
                                                ^
  symbol:   class Drawable

I have taken all the possible first steps to fix the issue like downgrading my google services from 4.3.3 to 4.1.0 and still that won't resolve my issue. have already Interchanged GlideDrawable to Drawable as seen in the error, but still have issues. What could be the possible fix to this?

Facts:
1. API:  implementation 'com.github.bumptech.glide:glide:4.11.0'
2. buildscript {
    
    repositories {
        mavenCentral()
        jcenter()
        google()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath 'com.google.gms:google-services:4.1.0'
    }
}

**Comment by nihp** [comment]
@Newtoxton  Any updates. I am facing the same.

**Comment by hengbenkeji** [comment]
Surprise. The authors of this library just pretended they had answered the question

**Comment by TWiStErRob** [comment]
The original issue was answered and accepted in 2017: https://github.com/bumptech/glide/issues/2104#issuecomment-312695526

---

Any other issues should be new issues.

Re
> error: cannot find symbol
import com.bumptech.glide.load.resource.drawable.Drawable;

The above doesn't exist, never has, the standard Android class is `android.graphics.drawable.Drawable`, I think  they figured it out by now, because if you remove the import, AS will automatically suggest what to do.
