### ISSUE TITLE
Glide taking images from cache and not updating it from json i have to reinstall app to update gallery 

### ISSUE THREAD

**Issue by sagunesh** [bumptech/glide#2105]
**Glide Version**: compile 'com.github.bumptech.glide:glide:3.7.0'

**Integration libraries**: Volley

**Device/Android Version**: Redmi Note 4 Xiaomi Android 6.0 Marshmallow.

**Issue details / Repro steps / Use case background**:
``  .diskCacheStrategy(DiskCacheStrategy.NONE)
                .skipMemoryCache(true) 
                 .signature(new StringSignature(System.currentTimeMillis()))``

**StackOverflow link of mine** : https://stackoverflow.com/questions/44887919/glide-how-to-stop-glide-from-loading-images-from-cache-instead-load-from-server
These methods not working still glide is using cache It is not updating from server each time i update json

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Are you sure Volley is not caching anything?

**Comment by sagunesh** [comment]
Thanks buddy you made my day Volley was caching :+1:
