### ISSUE TITLE
Images stop loading after fereshing adapter [v4]

### ISSUE THREAD

**Issue by favn1585** [bumptech/glide#2114]
**v4**, **No integration libraries**, **Native android studio emulator (Nexus 5 Api 25), Nexus 6p, Nexus 7(2013)**:

There is an issue that `notifyDataSetChanged()` cause image loading stop/freeze. We have ViewPager where we can switch between tabs. When we first-time open tab where we have some images and they did not exist in the cache, they did not load well. When we open fragment, we first load some data from the cache and then update data from the server. When glide start loading image URLs from cached data (images not cached) and at the same time we receive a response from the server(set data and call `notifyDataSetChanged()`), it loads images (listener invoke `onResourceReady`) but they did not render into image view.

```java
with(context).load(new GroupUrl(url).asThumbnail()) .transform(roundedCornersTransformation).transition(crossFadeTransitionOptions).into(source);
```

I was trying to load images with/without placeholder, using `Glide.clear()`, not using `transformation()` and `transaction()` but all this did not help. 

Image view looks like this:

```
<ImageView
android:layout_width="114dp"
android:layout_height="match_parent"/>
```

`GroupUrl` overrides `hashCode` and `equals` but I was even trying with a simple String URL and it does not help.

`GlideModule options`:

```
@Override
    public void applyOptions(Context context, GlideBuilder builder) {
        RequestOptions requestOptions = new RequestOptions();
        requestOptions.placeholder(R.color.feedBackground);
        requestOptions.fallback(R.color.feedBackground);
        requestOptions.error(R.color.feedBackground);
        requestOptions.centerCrop();
        requestOptions.format(DecodeFormat.PREFER_RGB_565);
        builder.setDefaultRequestOptions(requestOptions);

        super.applyOptions(context, builder);
    }

```

There is no any ERROR, WARN, INFO about it in logs. 

Here is how it looks like:

![ezgif-3-cc1dc31f2d](https://user-images.githubusercontent.com/3111598/27860440-f0d3d13e-617c-11e7-9bbb-088cf8a80abb.gif)

**Comment by favn1585** [comment]
@sjudd can you help me with it? Any suggestions? I can't find anything in specifications about it. Thank you in advance.

**Comment by favn1585** [comment]
@TWiStErRob maybe you can help me? Sorry for pinging you guys but I am fighting with this issue for 2 weeks already.

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/debugging.html#debugging

If there are no errors logged, I'd suspect an issue with the View state. You can debug [ViewTarget](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/request/target/ViewTarget.java#L202) by adding a few break points to confirm. If you can point out where in ``ViewTarget``'s logic the request gets stuck, we can probably provide better advice.

**Comment by favn1585** [comment]
I figure out the problem. I had 2 issues in 2 places:

1. 
```
android:layout_width="114dp"
android:layout_height="match_parent"
```

In `xml.` height was set as "match_parent", after changing it to some strict value, it works fine.

2. The second problem (another place in the app)

We use custom proportional image view.

```
@Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

        int measuredWidth = getMeasuredWidth();
        setMeasuredDimension(measuredWidth, (int) (measuredWidth * 0.5));
    }
```

I fixed issues with setting image view sizes manually, but still, have no idea why `Glide` not load an image into the container that has no sizes. Previous (3.8.0) version was working good. @sjudd Can you point me to the documentation?

**Comment by DavidMatos91** [comment]
@favn1585 Thanks a lot for sharing the solution! I was also struggling with this for the past two days and setting the ImageView's width and height to fixed sizes fixed the problem. Still, I believe Glide should be able to load the image regardless.
