### ISSUE TITLE
is there a way to get pictures serially?

### ISSUE THREAD

**Issue by skywang12345** [bumptech/glide#2115]
i want to get pictures from DashCam thru http request, and the DashCam can execute only one command at one time. which means that the request send to DashCam has to be one after another.

Is there a way to do this by using Glide?

**Comment by sjudd** [comment]
You can use [``submit()``][1] to get a Future on a background thread and then wait to submit each Future until the previous one has finished. 

If the DashCam breaks if you make more than one request, it might be safer to write a custom ModelLoader that handles your custom http request and uses a lock to make sure it never makes more than one request at a time 

[1]: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/RequestBuilder.html#submit-int-int-

**Comment by skywang12345** [comment]
thansk for the advice.
