### ISSUE TITLE
Custom view - load and draw multiple drawables

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#2118]
**Glide Version**: 3.8.0

What I want to do is using Glide in a custom view. My attempt looks like following:

```
public class CustomView extends View {

	@Override
	protected void onDraw(Canvas canvas) {
		super.onDraw(canvas);
		// this does of course not work on the foreground thread!
		Drawable icon = Glide.with(context).load(icon).into(size, size).get();
		if (icon != null) {
			icon.draw(canvas);
			canvas.restore();
		}
	}
}
```

This does not work of course, how would I correctly do this? My problem is, I'm not only loading one single drawable but a few and draw them afterwards in my custom view.

Any ideas on how to load a few drawables with glide for my custom view?

**Comment by rahulpandey** [comment]
why are you not creating method inside CustomeView view like
public void loadIcon() {\\glide load here   }
and not invalidating view

**Comment by sjudd** [comment]
In your View subclass you can create multiple custom ``Target`` instances, usually anonymous inner classes that implement the ``Target`` interface. You can load each ``Drawable`` into a different ``Target`` instance, save the ``Drawable`` in an instance variable when the load completes (don't forget to null out the Drawable if the ``Target``'s ``onLoadCleared()`` method is called), and then draw using the ``Drawable`` instance variables in ``onDraw`` in your ``View``.

**Comment by MFlisar** [comment]
Ok, so I need to clear the drawable reference whenever my target's `onLoadCleared` method is called. I have functions for loading and for cancelling in my view (I use them in an `RecyclerView` adapter `onBind` and `onUnbind` method).

Do I have to clear the drawable reference when I call `Glide.cancel(target)`? Or is it save to wait for the `onLoadCleared` method and only then clear the drawable reference?

**Comment by MFlisar** [comment]
I have a weird issue here with a custom view displaying one single image. What I have is following:

**Custom View**

	public class AppItemView extends View implements IconDrawer {

		private Drawable icon = null;
		private BaseIconProvider iconProvider;

		public void load() {
			if (iconProvider != null) {
				iconProvider.loadIcon(this, (int)iconSize, 0);
			}
		}

		public void reset() {
			if (iconProvider != null) {
				iconProvider.cancelLoad(this);
			}
			label = "";
			icon = null;
			invalidate();
		}

		@Override
		protected void onDraw(Canvas canvas) {
			super.onDraw(canvas);

			// preperations and calculations

			// center the icon
			if (icon != null) {
				canvas.save();
				canvas.translate((getWidth() - iconSize) / 2, heightPadding);
				icon.setBounds(0, 0, (int) iconSize, (int) iconSize);
				icon.draw(canvas);
				canvas.restore();
			}
		}

		@Override
		public void onIconAvailable(Drawable drawable, int index) {
			icon = drawable;
			super.invalidate();
		}

		@Override
		public void onIconCleared(Drawable placeholder, int index) {
			icon = placeholder;
			super.invalidate();
		}
	}

	
**`RecyclerView` adapter item**

	 @Override
    public void bindView(DrawerAppItem.ViewHolder holder, List payloads) {
		// update appItemView and bind the current app it should display => then load it's icon
        holder.appItemView.load();
        super.bindView(holder, payloads);
    }

    @Override
    public void unbindView(DrawerAppItem.ViewHolder holder) {
        super.unbindView(holder);
        holder.appItemView.reset();
    }
	
**Glide loading which is called by my `IconProvider.load` implementation**

    // cancel any previous load
	if (glideTarget != null)
		Glide.clear(glideTarget);
    int size = ...;
	glideTarget = new SimpleTarget<Drawable>(size, size) {
		@Override
		public void onResourceReady(Drawable resource, GlideAnimation glideAnimation) {
			iconDrawer.onIconAvailable(resource, index);
		}


		@Override
		public void onLoadCleared(Drawable placeholder) {
			iconDrawer.onIconCleared(placeholder, index);
		}
	};
    mGlide
        .using(new StreamModelLoader<PhoneAppItem>() {
			@Override
			public DataFetcher<InputStream> getResourceFetcher(PhoneAppItem model, int width, int height) {
				return new AppItemLoader(model, width, height, iconPackName);
			}
		})
		.load(item)
		.fitCenter()
		.into(target);
	
**Problem**

All images that are not already displayed somewhere else are loaded slowly when scrolling. Whenever I scroll up and down it seems like all images are reloaded and not cached (only images that are displayed somewhere else are shown instantly) I made sure via logging that images are loaded with the same size always and I know my `AppItemLoader` works fine because I use it in a few other places as well without problems. This only happens when using the custom view in an adapter, using a normal `ImageView` and loading icons into this `ImageView` works perfectly fine with the same loading setup...

Any ideas what could be the cause for this?
