### ISSUE TITLE
glide load video thumbnail in RecyclerView

### ISSUE THREAD

**Issue by dmcBig** [bumptech/glide#2123]
in  RecyclerView.Adapter work is ok, but Low performance！ help me

`    @Override
    public void onBindViewHolder(MyViewHolder holder, int position) {

        Bitmap bm = ThumbnailUtils.createVideoThumbnail(videoPath, MediaStore.Images.Thumbnails.MICRO_KIND);

        ByteArrayOutputStream stream = new ByteArrayOutputStream();

        bm.compress(Bitmap.CompressFormat.PNG, 70, stream);

        Glide.with(context)
                .asBitmap()
                .load(stream.toByteArray())
                .into(holder.media_image);

    }`

**Comment by sjudd** [comment]
createVideoThumbnail is expensive and shouldn't be called on the main thread.
Bitmap.compress (especially as a PNG!) is hugely expensive and shouldn't be called on a main thread.

If you want to load the thumbnail for a video, just pass the video file path into Glide's ``load()`` method.

**Comment by AllanWang** [comment]
@sjudd I tried passing the uri to glide, but the loading seems to be quite slow (about 1s per video).

```kotlin
Glide.with(holder.itemView)
		.load(data.data)
		.listener(object : RequestListener<Drawable> {
			override fun onLoadFailed(e: GlideException?, model: Any, target: Target<Drawable>, isFirstResource: Boolean): Boolean {
				holder.image.setImageDrawable(MediaPickerCore.getErrorDrawable(holder.itemView.context))
				return true;
			}

			override fun onResourceReady(resource: Drawable, model: Any, target: Target<Drawable>, dataSource: DataSource, isFirstResource: Boolean): Boolean {
				return false
			}
		})
		.into(holder.image)
```

I've done nothing more than retrieve the uri's using a cursor loader. Is there anything else that should be added? I also tried setting the diskcachestrategy to RESOURCE
