### ISSUE TITLE
What happens with thumbnail() and OOM?

### ISSUE THREAD

**Issue by Mithrandir21** [bumptech/glide#2124]
I have attempting to find out what happens in the following situation:

```java
Glide.with(getContext()) // With View context
   .load(imageResource)
   .thumbnail(0.2f) // Load a smaller version of the original image first
   .into(emptyStateImage);
```

**The question**:
What if the image resource is large enough to cause an OOM crashes on some lower-end devices?
Will the thumbnail (1/5th the size of the original) still be loaded or will the OOM happen before the thumbnail is actually created and displayed?

**Scenarios**:
Glide will have to create the thumbnail from something. If the source image has to be fully loaded before the thumbnail is created, than the OOM will happen before the thumbnail is created and displayed.
OR
If the source image does not have to be fully loaded for the thumbnail to be created and displayed, is it likely (and/or probable) that the thumbnail is created and displayed before the loading of the full source image causes an OOM?

**Comment by Mithrandir21** [comment]
Also, are there any significant performance gains by using a thumbnail for a bundled image resource?

**Comment by sjudd** [comment]
Re: OOM, there are no guarantees one way or another. Thumbnails are queued first, but they can be decoded in parallel with the main load, so it's totally possible for the thumbnail to OOM before the main image. OOMs should be avoidable, usually they mean either a memory leak or that the images you're loading are larger than they should be.

Unless decoding a resource is especially expensive or the resource is particularly large, there probably isn't much of a performance gain in using thumbnail(). Measure and verify though.
