### ISSUE TITLE
GlideApp loading a png without background issues

### ISSUE THREAD

**Issue by xuuhaoo** [bumptech/glide#2127]
GlideApp loading a png without background overlap with the placeholder.
like this
![image](https://user-images.githubusercontent.com/10423664/28073641-f50542cc-6688-11e7-91a3-c08d605a051e.png)

my code is:
GlideApp.with(this)
                .load("imge_url")
                .transition(new DrawableTransitionOptions().crossFade(500))
                .placeholder(R.drawable.driver_default)
                .into(mIcon);

**Comment by christopherperry** [comment]
This is by design. See the documentation here:

http://bumptech.github.io/glide/doc/transitions.html#cross-fading-with-placeholders-and-transparent-images

Unfortunately, there is no code example to show you how to enable cross fades using `DrawableCrossFadeFactory`.
