### ISSUE TITLE
How can I use ResourceTranscoder in v4

### ISSUE THREAD

**Issue by Cfanyang** [bumptech/glide#2130]
I haven't found the method transcode, How can I use a customized ResourceTranscoder

**Comment by sjudd** [comment]
You can register one in a [``GlideModule``][1]. If you request the type the Transcoder uses, Glide will run the request through your Transcoder (as long as the Resource intermediate decoded matches your Transcoder).

See http://bumptech.github.io/glide/doc/configuration.html#registering-components

[1]: http://bumptech.github.io/glide/doc/configuration.html#applications
