### ISSUE TITLE
如何根据图片原始地址获取图片是否存在磁盘缓存中？

### ISSUE THREAD

**Issue by smallgirl** [bumptech/glide#2131]
FutureTarget<File> future = Glide.with(MainApplication.getInstance())
                            .load(ads.getAdvertImage())
                            .downloadOnly(500, 500).onResourceReady(File file,);
                             File cacheFile = future.get();

future.get(); 只能在异步方法中调用 现在希望在 同步方法中知道 图片是否存在磁盘缓存中？

**Comment by Heleninsa** [comment]
HHH他不懂中文的。同步方法看不了，你可以参考[issues639](https://github.com/bumptech/glide/issues/639)
