### ISSUE TITLE
Glide 4.0.0-RC1 doesn't work on Gingerbread: NoClassDefFoundError

### ISSUE THREAD

**Issue by dsmudhar** [bumptech/glide#2134]
It's work fine on Android N but when I tested my app on Gingerbread it's giving me error.

`E/AndroidRuntime(10149): FATAL EXCEPTION: main
E/AndroidRuntime(10149): java.lang.NoClassDefFoundError: com.bumptech.glide.Glide
E/AndroidRuntime(10149):        at ...
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime(10149):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
E/AndroidRuntime(10149):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
E/AndroidRuntime(10149):        at android.app.ActivityThread.access$1500(ActivityThread.java:123)
E/AndroidRuntime(10149):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
E/AndroidRuntime(10149):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10149):        at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime(10149):        at android.app.ActivityThread.main(ActivityThread.java:3835)
E/AndroidRuntime(10149):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10149):        at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(10149):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/AndroidRuntime(10149):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
E/AndroidRuntime(10149):        at dalvik.system.NativeStart.main(Native Method)
`

I've tried to Clean Build multiple times but didn't help.
Also added the following (it worked on Android N without the following though):
`annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'
compile 'com.android.support:support-v4:25.3.1'
`
along with:
`compile 'com.github.bumptech.glide:glide:4.0.0-RC1'`
but still crashing.

I tried Glide 3.8.0, it's working fine.

**Comment by sjudd** [comment]
ICS is the minimum Android version for Glide v4.

**Comment by dsmudhar** [comment]
Do you plan to support Gingerbread again?

**Comment by TWiStErRob** [comment]
Most libs are dropping old support (see Google's compat for example). You can keep using the Glide v3, that's not going to be upped on min API as far as I know.

**Comment by daniele-athome** [comment]
[You should upgrade your README then :-)](https://github.com/bumptech/glide/tree/master#compatibility)

**Comment by TWiStErRob** [comment]
@daniele-athome good point: #2323
