### ISSUE TITLE
bitmap memory management

### ISSUE THREAD

**Issue by MrDreamCacher** [bumptech/glide#2135]
If a bitmap is shown an ImageView it's an active resource, which means it's not in any cache or pool.
And glide use Reference counting to manage bitmap memory, but how do glide know the bitmap is in inactive state, is glide listening the view's lifecycle?

**Comment by sjudd** [comment]
The reference count is decreased when the corresponding Target displaying the Bitmap is cleared. That happens manually when RequestManager#clear is called and automatically when Fragments and Activitys are destroyed (depending on the object passed to Glide#with()).
