### ISSUE TITLE
Pre-store image to catch memory after getting it uploaded from device and display efficiently

### ISSUE THREAD

**Issue by ShreyashPromact** [bumptech/glide#2140]
Hi,

I am displaying the image after uploading it to my server.
However the image size is 1024x1024, It takes approx 10-15 seconds to visible in image view after getting it uploaded. I am using below code for same.

```
`Glide.with(context)
                .load(url)
                .asBitmap()
                .thumbnail(0.4f)
                .override(200,200)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .centerCrop()
                .listener(new RequestListener<String, Bitmap>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                        holder.progressBar.setVisibility(View.GONE);
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        holder.progressBar.setVisibility(View.GONE);
                        holder.taskImage.invalidate();
                        return false;
                    }
                })
                .into(holder.taskImage);`
```

I would like to know. if is there any way to store the image in glide cache, while it gets uploaded to server and getting displayed to the user? So, that way, I can directly store the image in catch and that will be really fast visible to the user.

Right now, I am facing an issue to show uploaded an image to view very fast.

Please guide me in this scenario or if there is any mechanism available to pre-store the image in the catch.

Thanks.
Sincerely,
Shreyash

**Comment by ShreyashPromact** [comment]
Please also let me know if I am doing anything wrong here to display image efficiently.

**Comment by lewinskimaciej** [comment]
Kinda refreshing thread but as far as I understand, I want to achieve exactly the same thing. I'd like to use local file(by either Uri or File) to cache Image under the Key that will be used will image from API, short version:
Cache File with a Key that would be reused when we load the same image from Url later on, but with the same Key. How would one approach this?
