### ISSUE TITLE
GlideApp is not generated ？

### ISSUE THREAD

**Issue by GTooo** [bumptech/glide#2142]
I  include a AppGlideModule implementation in My application also setting annotationProcessor and compile package,But GlideApp is not generated, I try to Make Project or Make Module,But still not
:
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.load.engine.cache.LruResourceCache;
import com.bumptech.glide.module.AppGlideModule;

import java.io.InputStream;

/**
 * Created by --ln on 2017/7/15.
 */
@GlideModule
public class CustomAppGlideModule extends AppGlideModule {}

**Comment by Teovald** [comment]
It would be easier to help you if you provided a sample project

**Comment by Caij** [comment]
Did you use dagger2? Update dagger2 version

**Comment by GTooo** [comment]
@trinhvanminh2009 Thank you, I have solved it

**Comment by GTooo** [comment]
@Teovald Thank you, I have solved it

**Comment by GTooo** [comment]
@Caij Thank you, I have solved it

**Comment by sjudd** [comment]
Duplicate of #1939

**Comment by mochadwi** [comment]
> @Caij Thank you, I have solved it

What solution did you use to solve this issue? @GTooo
