### ISSUE TITLE
Glide 4.0.0-RC1 load local gif file issue

### ISSUE THREAD

**Issue by asker517** [bumptech/glide#2146]
Hi,Dear
  when I load local gif file with codes below : 
``
Glide.with(imageView.getContext()).load(file))..
``

result show a static image; however use codes like this:
``
Glide.with(imageView.getContext()).load(Uri.fromFile(file))
``
result is goes so nice....gif image auto play good.

what's  difference between both?

**Comment by TWiStErRob** [comment]
There shouldn't be any difference.

@sjudd
