### ISSUE TITLE
GlideApp not found

### ISSUE THREAD

**Issue by BahaaIddinSharqawi** [bumptech/glide#2147]
I read this issue #1939 which reflects my problem and I have implemented all the steps mentioned in it to solve the problem but that did not solve it.

My app build.gradle dependencies look like 

       dependencies {
		     compile 'com.android.support:appcompat-v7:25.3.1'
		     compile 'com.android.support:design:25.3.1'
		     compile 'com.android.support:palette-v7:25.3.1'
		     compile 'com.android.support:cardview-v7:25.3.1'
		     compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
		     compile 'com.android.support:support-v4:25.3.1'
		     annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'
	}
and I added mavenCentral() repository to project gradle file

          repositories {
               jcenter()
               mavenCentral()
        }

also I added MyAppGlideModule into my app with @GlideModule.

			import com.bumptech.glide.annotation.GlideModule;
			import com.bumptech.glide.module.AppGlideModule;

			@GlideModule
			public class MyAppGlideModule  extends AppGlideModule {}

**Comment by sinhpn92** [comment]
Did u rebuild or remake app?

**Comment by TWiStErRob** [comment]
Also use the released version: https://github.com/bumptech/glide/releases, not sure if it fixes this though.

**Comment by sjudd** [comment]
What is the actual error? If you build with gradle and look through the build logs, are there other errors?

**Comment by BahaaIddinSharqawi** [comment]
@sjudd The problem is that GlideApp is not genereted and the lint notifies "can not resolve GlideApp"

          dependencies {
                compile 'com.android.support:appcompat-v7:25.3.1'
                compile 'com.android.support:design:25.3.1'
                compile 'com.nhaarman.listviewanimations:lib-manipulation:3.1.0@aar'
                compile 'com.nhaarman.listviewanimations:lib-core:3.1.0@aar'
                compile 'com.nhaarman.listviewanimations:lib-core-slh:3.1.0@aar'
                compile files('src/main/java/lib/nineoldandroids-2.4.0.jar')
                compile 'com.jakewharton:butterknife:8.7.0'
                annotationProcessor 'com.jakewharton:butterknife-compiler:8.7.0'
                compile 'com.google.code.gson:gson:2.7'
                compile 'com.github.bumptech.glide:glide:4.0.0'
                compile 'com.android.support:support-v4:25.3.1'
                annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'
            }

**Comment by BahaaIddinSharqawi** [comment]
@sinhpn92 yes I rebuild and clean my project more than once but that did not solve the issue

**Comment by TWiStErRob** [comment]
Can you paste an actual error, including gradle task name and full relevant output (we still don't know who prints the error)

**Comment by cears-bhumika** [comment]
+1 same error

**Comment by sjudd** [comment]
Please re-open if you get the chance to paste the output @TWiStErRob asked for above.

**Comment by micheilsgrey** [comment]
I had same issue `error: cannot find symbol class GlideApp`. After i added Butterknife to my project and tryed to bind views in the Fragment  - `error: @BindView fields must not be private or static`, somehow this triggered issue with not generating GlideApp, in new to android and java so im not sure why its even happening but changing private to protected @BindView fix issue with butterknife and with GlideApp.

**Comment by xinxin1314** [comment]
weather your custom application is called BaseApplication?? if that, it is conflict with com.bug.glidetestdemo.BaseApplication

**Comment by TWiStErRob** [comment]
@micheilsgrey annotation processing is done in rounds, if any processor in a round fails the whole round fails, and javac still tries to compile the code, even though a round failed. The compilation has to be error free and we always have to find the error that's fixable. We have Dagger and use it extensively, a single compilation error will yield many-many pages of "cannot find symbol", if you don't see all, it's worth adding `-Xmaxerrs 10000` (default is 100) to javac.
