### ISSUE TITLE
Glide doesn't work...

### ISSUE THREAD

**Issue by light12** [bumptech/glide#2155]
Glide : 
compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
compile 'com.android.support:support-v4:25.3.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'

Nexus 5
Android 6.0.1 API 23

I have a problem with Glide. It doesn't work.
I would like to display the photos from my local storage.
But i have a fatal exception : 
"FATAL EXCEPTION: main
java.lang.NullPointerException: Argument must not be null"

and just before the android monitor tells me that : 
"Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored"

This is my code of my imageAdapter : 
public class ImageAdapter extends RecyclerView.Adapter<ImageAdapter.MyViewHolder> {

    private Context mContext;
    private ArrayList<String> mItemList = new ArrayList<>();

    public ImageAdapter(Context context, ArrayList<String> itemList) {
        mContext = context;
        mItemList = itemList;
    }

    @Override
    public MyViewHolder onCreateViewHolder(ViewGroup viewGroup, int itemType) {
        View view = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.recyclerviewphotos, viewGroup, false);
        return new MyViewHolder(view);
    }

    @Override
    public void onBindViewHolder(MyViewHolder holder, int position) {

        String img = mItemList.get(position);
        Uri uri = Uri.parse(img);
        Log.i("ListePhotos", mItemList.get(position));

        Glide
                .with(mContext)
                .load(uri)
                .into(holder.imageView);

    }

    @Override
    public int getItemCount() {
        return mItemList.size();
    }

    public class MyViewHolder extends RecyclerView.ViewHolder {

        private ImageView imageView;

        public MyViewHolder(View itemView){
            super(itemView);
            imageView = (ImageView) itemView.findViewById(R.id.onePhoto);

        }
    }
My photosFragment : 

  public class PhotosFragment extends Fragment {
    private RecyclerView mListPhotos;
    private ImageAdapter myImageAdapter;
    private Cursor mCursor;
    private ArrayList<String> itemList;

    public static PhotosFragment newInstance() {
        PhotosFragment fragment = new PhotosFragment();
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.recyclerviewphotos, container, false);

        itemList = new ArrayList<>();
        mCursor = getActivity().getContentResolver().query(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, null, null, null, null);
        mCursor.moveToFirst();
        while (!mCursor.isAfterLast()) {
            itemList.add(mCursor.getString(mCursor.getColumnIndex(MediaStore.Images.Media.DATA)));
            mCursor.moveToNext();
        }
        mCursor.close();

        mListPhotos = (RecyclerView) view.findViewById(R.id.listPhotos);
        mListPhotos.setLayoutManager(new GridLayoutManager(getContext(), 3));
        myImageAdapter = new ImageAdapter(getContext(), itemList);
        mListPhotos.setAdapter(myImageAdapter);

        return view;

    }
}

And my build.gradle : 

    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha4'
    compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
    compile 'com.android.support:support-v4:25.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'
    testCompile 'junit:junit:4.12'

**Comment by sjudd** [comment]
For the generated API message, see http://bumptech.github.io/glide/doc/generatedapi.html.

For the crash, you'd need to include a full stack trace.
