### ISSUE TITLE
Anyone using Glide with Conductor?

### ISSUE THREAD

**Issue by sevar83** [bumptech/glide#2156]
I try to use both Glide and https://github.com/bluelinelabs/Conductor. I'm interested how to properly clear all the ImageViews when there are no fragments and thus no fragment lifecycles which Glide attaches to in order to cancel pending requests. I'm pretty sure using Glide.with(appContext) will lead to OOM when enough ImageViews gather. From what I've understood inside Glide's code I will need to implement the Lifecycle interface and the RequestManagerTreeNode interface to enable RequestManager to "attach" to the Conductor's Controllers lifecycle. Any guidance or advice please?

Using:
Glide 4.0.0-RC1
OkHttp3

**Comment by sevar83** [comment]
There's some example from the Conductor's author but currently it doesn't work for more than one controller.
https://github.com/EricKuck/ConductorGlideDemo

**Comment by sevar83** [comment]
Try with this:
https://gist.github.com/sevar83/7b5e151233481b629e3d1fb1be7327dc

**Comment by MkhytarMkhoian** [comment]
Hi! I have implemented Glide support for Controller. So, if you need Glide support, you can try this one. This code works well in my production.

https://github.com/MkhytarMkhoian/ConductorGlide
