### ISSUE TITLE
Glide.bitmapTransform method not resolved?

### ISSUE THREAD

**Issue by HasnainAD** [bumptech/glide#2161]
I am new to glide and I was trying to perform transformations on it.

I followed Glide's official guides to include required libraries.
Then I used this code in my project:

![untitled](https://user-images.githubusercontent.com/10392852/28489397-c8651844-6edc-11e7-9e3c-04a3993dffaf.jpg)

Why am i getting this error?
Is there something I am doing wrong or the Glide tuts are at fault here?

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/getting-started.html
http://bumptech.github.io/glide/doc/options.html

I'm guessing that you're using Glide v4, if that's not the case please open a new issue with the issue template filled out.
