### ISSUE TITLE
load byte[]

### ISSUE THREAD

**Issue by Cornflower1991** [bumptech/glide#2172]
**Glide Version**: glide:4.0.0-RC1

**Issue details / Repro steps / Use case background**: 
when i repeatedly use  different byte[] load，but imageView not change

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
byte[] image
GlideApp.with(getActivity()).load(image).into(imageView)
```

**Comment by sjudd** [comment]
What do you mean by the ImageView doesn't change? It doesn't update to the new image?

**Comment by Cornflower1991** [comment]
yes  I refresh verification code  but ImageView  not't update  to the new image.  the verification code is
different

**Comment by Aslanisl** [comment]
I did
```
byte[] image
GlideApp.with(mContext).asBitmap().load(image) .into(imageView);
```
works for me.
