### ISSUE TITLE
Load Mutiple Image from path 

### ISSUE THREAD

**Issue by faketon** [bumptech/glide#2173]
I have 3 menu 
First menu have 15 images
Second menu have 5 images
Third menu have 2 images

I use glide 4.0.0 in recyclerview  when i choose Second menu and Third menu images will show but when i choose First menu and Second menu or First menu and Third menu images will not show.

i try to use diskCacheStrategy(DiskCacheStrategy.NONE).skipMemoryCache(true) but not help

what can i do ?

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/debugging.html
