### ISSUE TITLE
Glide NPE when trimming

### ISSUE THREAD

**Issue by guness** [bumptech/glide#2174]
**Glide Version**: 3.7.0

**Device/Android Version**: Does not matter

**Issue details / Repro steps / Use case background**: 
I am seeing this stack trace a lot on Crashlytics:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.decrementBitmapOfSize(SizeConfigStrategy.java:108)
       at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.removeLast(SizeConfigStrategy.java:100)
       at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimToSize(LruBitmapPool.java:175)
       at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.clearMemory(LruBitmapPool.java:157)
       at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimMemory(LruBitmapPool.java:167)
       at com.bumptech.glide.Glide.trimMemory(Glide.java:386)
       at com.bumptech.glide.RequestManager.onTrimMemory(RequestManager.java:88)
       at com.bumptech.glide.manager.RequestManagerFragment.onTrimMemory(RequestManagerFragment.java:156)
       at android.app.Fragment.performTrimMemory(Fragment.java:2298)
       at android.app.FragmentManagerImpl.dispatchTrimMemory(FragmentManager.java:2014)
       at android.app.FragmentController.dispatchTrimMemory(FragmentController.java:253)
       at android.app.Activity.onTrimMemory(Activity.java:1914)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4469)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5525)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

I am using only one custom transformation, here is the code:
```
private static class SquaringTransformation extends BitmapTransformation {

        public SquaringTransformation(Context context) {
            super(context);
        }

        public SquaringTransformation(BitmapPool bitmapPool) {
            super(bitmapPool);
        }

        @Override
        protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
            int dim = Math.max(outWidth, outHeight);
            final Bitmap toReuse = pool.get(dim, dim, getSafeConfig(toTransform));
            Bitmap transformed = square(toReuse, toTransform, dim);
            if (toReuse != null && toReuse != transformed && toReuse != toTransform && !pool.put(toReuse)) {
                toReuse.recycle();
            }
            return transformed;
        }

        @Override
        public String getId() {
            return SquaringTransformation.class.getName();
        }

        private Bitmap square(Bitmap recycled, Bitmap toSquare, int dim) {
            if (toSquare == null) {
                return null;
            } else if (toSquare.getWidth() == dim && toSquare.getHeight() == dim) {
                return toSquare;
            }

            final Bitmap result;
            if (recycled != null) {
                result = recycled;
            } else {
                result = Bitmap.createBitmap(dim, dim, getSafeConfig(toSquare));
            }

            final float widthPercentage = dim / (float) toSquare.getWidth();
            final float heightPercentage = dim / (float) toSquare.getHeight();
            final float minPercentage = Math.min(widthPercentage, heightPercentage) * 4.5f / 5f;

            final int targetWidth = (int) (minPercentage * toSquare.getWidth());
            final int targetHeight = (int) (minPercentage * toSquare.getHeight());

            final float left = (dim - targetWidth) / 2f;
            final float top = (dim - targetHeight) / 2f;

            Canvas canvas = new Canvas(result);
            canvas.drawColor(Color.WHITE);
            Paint paint = new Paint(PAINT_FLAGS);

            Matrix matrix = new Matrix();
            matrix.setScale(minPercentage, minPercentage);
            matrix.postTranslate(left, top);
            canvas.drawBitmap(toSquare, matrix, paint);

            return result;
        }

        private Bitmap.Config getSafeConfig(Bitmap bitmap) {
            return bitmap.getConfig() != null ? bitmap.getConfig() : Bitmap.Config.ARGB_8888;
        }
    }
```

I am also using `'jp.wasabeef:glide-transformations:2.0.2'`

**Comment by sjudd** [comment]
Are you able to reproduce with 3.8.0? Or the latest 3.x snapshot?

**Comment by guness** [comment]
I haven't push the update with 3.8.x yet.

here is another log,

`

com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.decrementBitmapOfSize (SizeConfigStrategy.java:108)
--
  | com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.removeLast (SizeConfigStrategy.java:100)
  | com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimToSize (LruBitmapPool.java:175)
  | com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.evict (LruBitmapPool.java:109)
  | com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.put (LruBitmapPool.java:104)
  | com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawableResource.recycle (GlideBitmapDrawableResource.java:25)
  | com.bumptech.glide.load.engine.EngineResource.recycle (EngineResource.java:61)
  | com.bumptech.glide.load.engine.ResourceRecycler.recycle (ResourceRecycler.java:25)
  | com.bumptech.glide.load.engine.Engine.onResourceRemoved (Engine.java:283)
  | com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted (LruResourceCache.java:32)
  | com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted (LruResourceCache.java:12)
  | com.bumptech.glide.util.LruCache.trimToSize (LruCache.java:162)
  | com.bumptech.glide.util.LruCache.evict (LruCache.java:167)
  | com.bumptech.glide.util.LruCache.put (LruCache.java:124)
  | com.bumptech.glide.load.engine.cache.LruResourceCache.put (LruResourceCache.java:12)
  | com.bumptech.glide.load.engine.Engine.onResourceReleased (Engine.java:291)
  | com.bumptech.glide.load.engine.EngineResource.release (EngineResource.java:100)
  | com.bumptech.glide.load.engine.Engine.release (Engine.java:249)
  | com.bumptech.glide.request.GenericRequest.releaseResource (GenericRequest.java:341)
  | com.bumptech.glide.request.GenericRequest.clear (GenericRequest.java:320)
  | com.bumptech.glide.manager.RequestTracker.clearRequests (RequestTracker.java:94)
  | com.bumptech.glide.RequestManager.onDestroy (RequestManager.java:221)
  | com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy (ActivityFragmentLifecycle.java:64)
  | com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy (SupportRequestManagerFragment.java:147)
  | android.support.v4.app.Fragment.performDestroy (Fragment.java:2434)
  | android.support.v7.app.AppCompatActivity.onDestroy (AppCompatActivity.java:209)
  | com.argeusteknoloji.sikayetvar.core.SVActivity.onDestroy (SVActivity.java:96)
  | com.argeusteknoloji.sikayetvar.ui.pages.DetailActivity.onDestroy (DetailActivity.java:167)
  | android.app.Activity.performDestroy (Activity.java:5713)
  | dalvik.system.NativeStart.main (NativeStart.java)

`
