### ISSUE TITLE
Gif animation frame rate issue

### ISSUE THREAD

**Issue by vishal-i4gs** [bumptech/glide#2175]
I have been using compile 'com.github.bumptech.glide:glide:4.0.0-RC1'. I am consistently seeing a frame rate difference on phones compared to the original. I also note that the gifs are playing well on the simulator and also on the browser/others apps on the phone.

I am using this :
        GlideApp.with(this)
                .asGif()
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .load(R.drawable.giphy)
                .fitCenter()
                .into(image);

**Comment by didixyy** [comment]
I also have this problem

**Comment by 459905207** [comment]
I also have this problem

**Comment by TWiStErRob** [comment]
An example please..., this is highly dependent on the actual frame delays encoded in the GIF header.

**Comment by TWiStErRob** [comment]
Also which devices have this issue, which browsers/apps don't.

**Comment by 459905207** [comment]
Yes, I think so, but I use compile 'pl.droidsonroids.gif: android-gif-drawable: 1.2.8' can be the correct frame rate on the same phone to play gif.
