### ISSUE TITLE
Pre warm cache Using image received out of band.

### ISSUE THREAD

**Issue by labeneator** [bumptech/glide#2181]
I am using Glide 3.8.0 and can extract images from the disk cache. These images are then sent to a peer over wifi who can use them to pre warm their cache; the typical user of this app doesn't have good Internet connectivity and is minimising cost by not using 3G.

Once a peer receives an image (and the source URL), the optimal route would be to inject the image into glide?

Is it possible to inject an image back into the cache using the original fetched image and a copy sitting on the SDCard (Much like a pre warm)?

Cheers

**Comment by sjudd** [comment]
You can use a custom ModelLoader and a cache you maintain outside of Glide. The custom ModelLoader can check your prewarm cache and if it finds an image in cache for a given request, it can delegate to the file ModelLoader to load the cached image. If the custom ModelLoader doesn't find the image in the prewarm cache, it can delegate to the url ModelLoader to download the image remotely.

It's difficult to inject content directly in to Glide's cache, so using your own cache and a custom ModelLoader is usually a better route.
