### ISSUE TITLE
Transition customization via GlideModule

### ISSUE THREAD

**Issue by Teovald** [bumptech/glide#2182]
**Glide Version**:  4.0 RC1
**Device/Android Version**: Any

**Issue details / Repro steps / Use case background**:  for rich content apps, crossfade is the default and I would like to be able to configure Glide through @GlideModule in order to provide a default transition used when the image does not come from the memory cache.

@sjudd in #1942 you mentioned issues tied to crossfade. Could you expand on this please ? 

How would you feel about such a default option, just like we can have default RequestOptions ?

**Comment by sjudd** [comment]
I tried to find the issues (there have been a number) related to crossfade but GitHub's search isn't the greatest.

My recollection is:
1. The cross fade shows the placeholder under the full image if the full image is transparent
2. The cross fade doesn't handle significant differences in sizes between the placeholder and full image, sometimes resulting in the full image being sized incorrectly.

I have no problems with adding a default set of options for transitions just like we have with RequestOptions, it's a great idea.
