### ISSUE TITLE
Glide doesnot load some images url

### ISSUE THREAD

**Issue by MohamedHamada12** [bumptech/glide#2183]
**3.7.0**:

**no**:

**7 **:

some images urls that doesn't work
http://www.alchourouk.com/images/images_articles_2015/668_334_1501161207.jpg
http://www.alchourouk.com/images/images_articles_2015/668_334_150117318134_1462527730.jpg
http://www.alchourouk.com/images/images_articles_2015/668_334_1501160598_0.jpg

Some images url doesn't work , I dont Know what is reasons 
        
Glide.with(this).load("http://www.alchourouk.com/images/images_articles_2015/668_334_150117121234_1499893833anasraoui.jpg").into(iv);

and I tried to use listener but I can't get any response onException or onResourceReady
   Glide.with(this).load(http://www.alchourouk.com/images/images_articles_2015/668_334_150117121234_1499893833anasraoui.jpg).listener(new RequestListener<String, GlideDrawable>() {
            @Override
            public boolean onException(Exception e, String model, com.bumptech.glide.request.target.Target<GlideDrawable> target, boolean isFirstResource) {
                Log.d("error_dd",e.toString());
                return false;
            }

            @Override
            public boolean onResourceReady(GlideDrawable resource, String model, com.bumptech.glide.request.target.Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                Log.d("error_dd","gfdgfdg");

                return false;
            }
        });

**Comment by Wenqin-231** [comment]
I test it and it tell me the error is 
`java.io.IOException: Request failed 403: Forbidden`

**Comment by MohamedHamada12** [comment]
@Wenqin-231 
Yes I got this error in android devices , however in IOS devices those images work fine.
do you have any idea

**Comment by manishjss** [comment]
I also have same issue after updating to 4.0.0-RC1 ...  before this working fine..

**Comment by sjudd** [comment]
403 Forbidden is a server error that we can't really do anything about. If you think otherwise, please re-open with a full stack trace and more detail.
