### ISSUE TITLE
Not loading bitmap in Viewpager

### ISSUE THREAD

**Issue by lzn202** [bumptech/glide#2184]
**Glide Version**: 3.7.0

**Integration libraries**:

**Device/Android Version**: 4.1 (Jelly bean) /4.4.2 ()

**Issue details / Repro steps / Use case background**: 

Hello everyone, I have previously used Glide to load images to a Bitmap and display them in a Pageadapter, this way you can choose between different images. This project worked correctly on a tablet with Android 4.1. (Jelly bean), but when installed the same code on another device with Android 4.4.2 (kitkat) the images are not loaded correctly. When loading multiple images I have found that the first image is not shown but after using the page adapter to navigate between several images, the first image if it is loaded.
I hope you understand my problem, thank you all

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
            Glide.with(mContext)
                    .load(mImages.get(position))
                    .asBitmap()
                    .diskCacheStrategy(DiskCacheStrategy.NONE)
                    .skipMemoryCache(true)
                    .dontAnimate()
                    .override(675, 972)
                    .into(new SimpleTarget<Bitmap>() {

                        @Override
                        public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                            if(bitmap!=null)
                            {
                                imageView.setImageBitmap(bitmap);
                            }

                        }
                    });

//Page adapter, (Allows you to switch between the different available images)
mPager.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            }

            @Override
            public void onPageSelected(int position) {
                TouchImageView imageView = (TouchImageView)  mPager.findViewWithTag(position);
                Glide.get(Context).clearMemory();
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });
```

**Comment by Wenqin-231** [comment]
The ViewPager will load first and second view frist time, and maybe you can set a lazy load for it.

**Comment by lzn202** [comment]
Sorry but I do not understand the answer, the images are loaded from the internal memory of the device and the variable mImages is used to save a list with the path of the files. The examples I have searched about Lazy loading work the same as the project code, so it is not clear to me which is the recommended change

**Comment by nexodev** [comment]
@lzn202  Hello
I had the same problem, solved when upgrading to glide 4.0

**Comment by lzn202** [comment]
Hi, thanks for the reply, I changed the project to glide v4 but the problem continues. For several days I have been trying to solve this error but the images are still not loading.  I attach the code of the change made in case I have made a mistake in the implementation of Glide V4.
          

            options.dontAnimate().diskCacheStrategy(DiskCacheStrategy.NONE)
                    .skipMemoryCache(true)
                    .override(675, 972).autoClone();


            Glide.with(mContextl)
                    .asBitmap().load(mImages.get(position))
                    .apply(options)
                    .into(new Target<Bitmap>() {
                        @Override
                        public void onLoadStarted(@Nullable Drawable placeholder) {

                        }

                        @Override
                        public void onLoadFailed(@Nullable Drawable errorDrawable) {

                        }

                        @Override
                        public void onResourceReady(Bitmap resource, Transition<? super Bitmap> transition) {
                            imageView.setImageBitmap(resource);
                        }

                        @Override
                        public void onLoadCleared(@Nullable Drawable placeholder) {

                        }

                        @Override
                        public void getSize(SizeReadyCallback cb) {

                        }

                        @Override
                        public void removeCallback(SizeReadyCallback cb) {

                        }

                        @Override
                        public void setRequest(@Nullable Request request) {

                        }

                        @Nullable
                        @Override
                        public Request getRequest() {
                            return null;
                        }

                        @Override
                        public void onStart() {

                        }

                        @Override
                        public void onStop() {

                        }

                        @Override
                        public void onDestroy() {

                        }
                    });`

**Comment by sjudd** [comment]
You need to implement the required methods in the Target interface. Why aren't you loading into a View or using one of Glide's built in Targets?

**Comment by lzn202** [comment]
The code works with another device with Jelly Bean, the problem occurs on the device with Android KitKat, because I used the setTag method inside the class,and I can´t use the method because it shows an error. I have also tried to comment the setTag line and send the values manually to the view but the problem continues, and the image is not displayed. I added the changed code used in the ImageViewTarget, in which the image is not displayed.


```
            RequestOptions options = new RequestOptions();

            options.dontAnimate().diskCacheStrategy(DiskCacheStrategy.NONE)
                    .skipMemoryCache(true)
                    .override(675, 972).autoClone();


            Glide.with(ManejadorRecursos.actividadActual)
                    .asBitmap().load(mImagenes.get(position))
                    .apply(options)
                    .into(new ImageViewTarget<Bitmap>(imageView) {
                        @Override
                        protected void setResource(@Nullable Bitmap resource) {
                            imageView.setImageBitmap(resource);
                        }
                    });
```

**Comment by lzn202** [comment]
I found the solution by adding the line .placeholder (new ColorDrawable (Color.WHITE)) in the RequestOptions. Thanks

```java
            options.dontAnimate().diskCacheStrategy(DiskCacheStrategy.NONE)
                    .skipMemoryCache(true)
                    .placeholder(new ColorDrawable(Color.WHITE))
                    .override(675, 972);
```
