### ISSUE TITLE
 You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by zbldgit** [bumptech/glide#2185]
new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        Glide.with(this).load("").into(image);
                    }
                }, 30000);

**Comment by Wenqin-231** [comment]
Firstly  your issues is irregular so that I can not know your version of Glide. 
Secondly, what is meaning of  'this'? Maybe it should be xxActivity.this or xxFragment.this in run method.

In my case, beacase Glide can not know the Fragment or Activity destory when it start in sub-thread, I use it like this :
`if (!isFinishing()) {
                    Glide.with(MainActivity.this).load("").into(imageView);
                }`
in Fragment you can use isDeatch.

**Comment by sjudd** [comment]
By posting like that you're making it very likely that you start the request after whatever "this" is is destroyed, which won't work. Don't start your requests before your Fragment/Activity is created or after it's destroyed.

**Comment by scsfwgy** [comment]
@wenqin-231  hi 

`if (!isFinishing()) ` still cause “You cannot start a load for a destroyed activity”

**Comment by dahuoji1024** [comment]
I solved the problem like this.

if (context instanceof AppCompatActivity && Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 && ((AppCompatActivity) context).isDestroyed()) {
                Log.e("CurrencyIconUtil", "picture load failed, because of activity destroyed");
            } else {
                Glide.with(context).load(imageUrl).into(imageView);
            }

Because the Glide source code says this:

    @TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
    private static void assertNotDestroyed(Activity activity) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 && activity.isDestroyed()) {
            throw new IllegalArgumentException("You cannot start a load for a destroyed activity"); 
        }
    }
