### ISSUE TITLE
Glide ViewTarget doesn't suport ViewGroup.

### ISSUE THREAD

**Issue by Gkundu1** [bumptech/glide#2186]
**Glide Version**:3.7.0

**Integration libraries**:retrofit:2.2.0

**Device/Android Version**:ASUS Zenfone Max

**Issue details / Repro steps / Use case background**: No issue but enhancement if possible can the class of Glide (ViewTarget) extends ViewGroup so that it will easy to load the image in all available ViewGroup of android.As now glide class ViewTarget<T extends View, Z> only support view but as requirement change need support for ViewGroup also.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
That doesn't make sense, how do you pair up a Bitmap/Drawable with any ViewGroup? e.g. a ConstraintLayout?

You should be able to do either `((ViewGroup)target.getView()).foo` or create your own target extending ViewTarget

**Comment by TWiStErRob** [comment]
Check out https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_938_background

**Comment by Gkundu1** [comment]
Is there any way to set my image on linear layout background instead of ImageView using Glide?

**Comment by TWiStErRob** [comment]
Uhm, exact comment just above yours?
