### ISSUE TITLE
Glide cant display images

### ISSUE THREAD

**Issue by bxjxxyy** [bumptech/glide#2189]
**Glide Version**:  glide:4.0.0-RC0

**Integration libraries**:OkHttp3.6.0, alicloud-httpdns

**Device/Android Version**:Redmi note3  ,  oppo a31/Android 4.4 ,ZTE-BA601
  just know these  for now
Got three feed back last weekend , glide can't display any image on their phone.
The first time users feed back question like this.
But I tried on my own Redmi note3 and oppo a31, glide works fine ,all image can be displayed.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
I use Glide in a Activity.

if(!isFinishing){
 Glide.with(getApplicationContext()).load(imgurl).into(imgview);
}

**Stack trace / LogCat**:
onException: com.bumptech.glide.load.engine.GlideException: Failed to load resource  model:http://cdn.jianzhiku.com/c/zatanimg/2017075/thumb_15009154636480thisqrcode.jpg isFirstResource: true

I got that error log from RequestListener.

**Comment by sjudd** [comment]
Can you show the full stack trace? There's not enough there to tell why.  Also look for error logs in logcat from BitmapFactory.

**Comment by bxjxxyy** [comment]
I found this problem from my app's user. I just gathered the error log in RequestListener, and that's all I got. And I can't reproduce this problem on my own phone, even the same phone model.

**Comment by yanxinmiao** [comment]
me too

`
  GlideApp.with(imageView.getContext())
                .load(url)
                .placeholder(R.drawable.default_news_cat_pic)
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                        return false;
                    }
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                        Logger.d("e：" + e.getMessage());
                        return false;
                    }
                })
                .into(imageView);
`

log
`

Load failed for http://pic26.photophoto.cn/20130226/0017029302915045_b.jpg with size [1080x675]
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
08-02 14:53:25.076 1571-1571/cn.mypep.weike E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
08-02 14:53:25.076 1571-1571/cn.mypep.weike D/PRETTY_LOGGER: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
08-02 14:53:25.076 1571-1571/cn.mypep.weike D/PRETTY_LOGGER: │ Thread: main
08-02 14:53:25.076 1571-1571/cn.mypep.weike D/PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
08-02 14:53:25.076 1571-1571/cn.mypep.weike D/PRETTY_LOGGER: │ SingleRequest.onLoadFailed  (SingleRequest.java:516)
08-02 14:53:25.076 1571-1571/cn.mypep.weike D/PRETTY_LOGGER: │    ImageUtils$1.onLoadFailed  (ImageUtils.java:37)
08-02 14:53:25.077 1571-1571/cn.mypep.weike D/PRETTY_LOGGER: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
08-02 14:53:25.077 1571-1571/cn.mypep.weike D/PRETTY_LOGGER: │ eFailed to load resource
`

**Comment by yanxinmiao** [comment]
my problem has solved ， this method applyOptions's code may mistake ，i comments this method's code , the image can display .

**Comment by sjudd** [comment]
Any number of reasons could cause an HTTP request to fail, the most likely is just a connectivity issue. Please re-open if you come up with repro steps or find a more specific error message. Unfortunately I don't think we can do anything with the information we have available.

For other ideas, you can also try looking at: http://bumptech.github.io/glide/doc/debugging.html
