### ISSUE TITLE
[Question] How to improve initial video thumbnail loading

### ISSUE THREAD

**Issue by AllanWang** [bumptech/glide#2192]
This is an extension of #2123 

As per the conversation there, I tried loading the thumbnails by directly passing the video path data without any changes like so:

```kotlin
Glide.with(holder.itemView)
	.load(data.data)
	.listener(object : RequestListener<Drawable> {
		override fun onLoadFailed(e: GlideException?, model: Any, target: Target<Drawable>, isFirstResource: Boolean): Boolean {
			holder.image.setImageDrawable(MediaPickerCore.getErrorDrawable(holder.itemView.context))
			return true;
		}

		override fun onResourceReady(resource: Drawable, model: Any, target: Target<Drawable>, dataSource: DataSource, isFirstResource: Boolean): Boolean {
			return false
		}
	})
	.into(holder.image)
```

But the first load takes on average 1 second per video. In the end, the panels take around 10 seconds to fully load.

I am using Glide v4 without the generated api, and the path data comes from a cursor loader.

The source code snapshot can be found [here](https://github.com/AllanWang/KAU/blob/0a3f9dc10b50bb842888ddd523cd7e17b179c8f9/mediapicker/src/main/kotlin/ca/allanwang/kau/imagepicker/MediaItemBasic.kt#L46)

With an example apk [here](https://play.google.com/store/apps/details?id=ca.allanwang.kau.sample)
(the apk is subject to change once this issue is resolved)

**Comment by sjudd** [comment]
Videos can take a while to load. We use [MediaMetadataRetriever](https://developer.android.com/reference/android/media/MediaMetadataRetriever.html) to extract the frame.

One option might be to try to load the thumbnail from media store. Glide will do this for you automatically if the width and height you request are less than those used for [MINI_KIND](https://developer.android.com/reference/android/provider/MediaStore.Images.Thumbnails.html#MINI_KIND). If that's too small for your View, you can make the request using the ``thumbnail()`` API and continue to load the slower full resolution images as well. 

Note that media store thumbnails may not have been generated previously and if so, loading them will be no faster than loading from the video directly.

**Comment by sjudd** [comment]
Media store thumbnails are global for all apps. My suggestion was that you might be able to take advantage of any pre-generated media store thumbnails for the videos which would be much faster to decode than using ``MediaMetadataRetriever``. Unfortunately Glide itself doesn't cause media store to generate thumbnails when they're missing, so I wouldn't expect an improvement in first load time if you uninstall and re-install the app. You'd only see an improvement if the media store thumbs are eagerly generated or requested by another app.

As far as ``DiskCacheStrategy``, all you really want to do is make sure you're using [``AUTOMATIC``](http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/load/engine/DiskCacheStrategy.html#AUTOMATIC) or [``RESOURCE``](http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/load/engine/DiskCacheStrategy.html#RESOURCE). Using ``DATA`` will cause Glide to copy the entire video into the cache, which will also be quite slow.

If all else fails you could try to pre-generate some of these thumbnails on a background thread before your app is opened or before the screen where you display the video thumbnails is opened. See [``preload()``](http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/RequestBuilder.html#preload-int-int-), or for a more complicated example that avoids starving out foreground requests,  see the [flickr sample](https://github.com/bumptech/glide/blob/eb2d54ba034721717075e02677524a1f20ed1adf/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrSearchActivity.java#L330)

**Comment by AllanWang** [comment]
I tried with preload by doing the following:

```kotlin
if (!hasPreloaded && preload) {
    hasPreloaded = true
    val preloadSize = 120.dpToPx
    val manager = Glide.with(this)
    models.subList(0, Math.min(models.size, 50)).forEach { manager.load(it.data).preload(preloadSize, preloadSize) }
}
```

The images are normally loaded with a thumbnail that is guaranteed to be smaller than 120dp, but this preload doesn't seem to make any difference still. Scrolling down still takes the same time to load, and I think waiting for the full preview to load after the thumbnail actually takes longer because of the preload above.

I'll try the flickr example and see if that helps

**Comment by sjudd** [comment]
Make sure that the options and size you use for your preloads match the size of the options and size of the requests you eventually make exactly. You can see the cache keys per request by looking at the Engine log tag: https://github.com/bumptech/glide/blob/eb2d54ba034721717075e02677524a1f20ed1adf/library/src/main/java/com/bumptech/glide/load/engine/Engine.java#L169

**Comment by AllanWang** [comment]
@sjudd I've set an override to ensure that the size is always the same:

`apply(RequestOptions().override(MediaPickerCore.viewSize(this@MediaPickerCore)))`

viewSize is a lazy value so it will be a constant.

And here is the output (I waited for prefetch then I scrolled down):

```
08-02 14:33:11.708 ca.allanwang.kau.sample V/Engine: Started new load in 0.362708ms, 
	key: EngineKey{model=/storage/emulated/0/DCIM/Camera/VID_20160904_150646.mp4, width=360, height=360, 
	resourceClass=class java.lang.Object, transcodeClass=class java.io.File, signature=EmptySignature, 
	hashCode=1241398304, transformations={}, options=Options{values={}}}
08-02 14:33:13.171 ca.allanwang.kau.sample I/TimberLogger: KAU: MediaPickerCore prefetched /storage/emulated/0/DCIM/Camera/VID_20160904_150646.mp4
08-02 14:33:25.585 ca.allanwang.kau.sample V/Engine: Started new load in 0.47515599999999997ms, 
	key: EngineKey{model=/storage/emulated/0/DCIM/Camera/VID_20160904_150646.mp4, 
	width=360, height=360, resourceClass=class java.lang.Object, 
	transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=294428989, 
	transformations={class android.graphics.Bitmap=com.bumptech.glide.load.resource.bitmap.CenterCrop@dc40790e, class com.bumptech.glide.load.resource.gif.GifDrawable=com.bumptech.glide.load.resource.gif.GifDrawableTransformation@dc40790e, 
	class android.graphics.drawable.BitmapDrawable=com.bumptech.glide.load.resource.bitmap.BitmapDrawableTransformation@dc40790e}, options=Options{values={Option{key='com.bumptech.glide.load.resource.bitmap.Downsampler.DownsampleStrategy'}=com.bumptech.glide.load.resource.bitmap.DownsampleStrategy$CenterOutside@b282696}}}
```

When loading in the recycler, my target is an imageview, whereas prefetching is with `submit` like in the flickr sample. It seems like that is why the prefetch image doesn't help.

Another thing I noticed is that if I kill my app and reopen it (without uninstalling), it loads as if nothing has been cached as well.

This is the response after I restart:

```
08-02 14:37:51.160 ca.allanwang.kau.sample V/Engine: Started new load in 0.29104199999999997ms, 
	key: EngineKey{model=/storage/emulated/0/DCIM/Camera/VID_20160904_150646.mp4, 
	width=360, height=360, resourceClass=class java.lang.Object, 
	transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=-1333166253, 
	transformations={class android.graphics.drawable.BitmapDrawable=com.bumptech.glide.load.resource.bitmap.BitmapDrawableTransformation@dc40790e, 
	class com.bumptech.glide.load.resource.gif.GifDrawable=com.bumptech.glide.load.resource.gif.GifDrawableTransformation@dc40790e, 
	class android.graphics.Bitmap=com.bumptech.glide.load.resource.bitmap.CenterCrop@dc40790e}, options=Options{values={Option{key='com.bumptech.glide.load.resource.bitmap.Downsampler.DownsampleStrategy'}=com.bumptech.glide.load.resource.bitmap.DownsampleStrategy$CenterOutside@65f8e2c}}}
```

The hash isn't the same and centercrop is not present in both keys.

If it helps, [this](https://github.com/AllanWang/KAU/blob/1b83a71a59505dfe11e60e6dd123302251de4b38/mediapicker/src/main/kotlin/ca/allanwang/kau/mediapicker/MediaPickerCore.kt#L168) is my preloading call, and [this](https://github.com/AllanWang/KAU/blob/1b83a71a59505dfe11e60e6dd123302251de4b38/mediapicker/src/main/kotlin/ca/allanwang/kau/mediapicker/MediaItemBasic.kt#L51) is how I load it for imageviews.

I've removed the thumbnail call for now in case that made a difference.

**Comment by sjudd** [comment]
Add a ``centerCrop()`` call to the ``RequestOptions`` you pass in to your preload so that the keys match. Everything has to be the same, including transformations, for there to be a cache hit in memory and on disk.

**Comment by AllanWang** [comment]
Thanks! It works now. And another thing I changed was to remove `downloadOnly` for the preloader, as that returns a file type builder rather than a drawable one
