### ISSUE TITLE
BaseGlideUrlLoader changed url not applied in 4.0

### ISSUE THREAD

**Issue by PaulWoitaschek** [bumptech/glide#2193]
After upgrading to Glide 4.0, requesting modified urls does no longer work.

I have a single `AppGlideModule`, where I register a `BaseGlideUrlLoader<String>` and append the the width of the image to the url so the server can directly return the appropriate size.

This method does get called. However it is not being used in 4.0 (but it was in 3.x). The full image is always downloaded.
`D/Glide: Finished loading BitmapDrawable from REMOTE for https://my.server.com/image.jpg with size [80x80] in 1318.053778 ms
`

This is how my url loader looks like:

```kotlin
/**
 * Glide url loader that appends width and height to fetch images faster from the server
 */
class ImageSizeUrlLoader(
    concreteLoader: ModelLoader<GlideUrl, InputStream>
) : BaseGlideUrlLoader<String>(concreteLoader) {

  private val raster = listOf(64, 128, 192, 256, 448, 512, 768, 1080, 1280, 1440, 1640, 2048)

  private fun adjustSize(desired: Int): Int = raster.firstOrNull { it >= desired }
      ?: raster.last()

  override fun getUrl(source: String, width: Int, height: Int, options: Options): String {
    val adjustedWidth = adjustSize(width)
    val adjustedHeight = adjustSize(height)
    val adjusted = "$source&w=$adjustedWidth&h=$adjustedHeight&no-upscale&q=65"
    Timber.i("adjusted to $adjusted")
    return adjusted
  }

  override fun handles(source: String) = source.contains(ImageLoading.IMAGE_SERVER)

  class Factory : ModelLoaderFactory<String, InputStream> {

    override fun build(multiFactory: MultiModelLoaderFactory): ImageSizeUrlLoader {
      val concreteLoader = multiFactory.build(GlideUrl::class.java, InputStream::class.java)
      return ImageSizeUrlLoader(concreteLoader)
    }

    override fun teardown() {}
  }
}
```

And it logs that it was called 

`I/ImageSizeUrlLoader: adjusted to https://my.server.com/image.jpg&w=128&h=128&no-upscale&q=65
`

**Comment by sjudd** [comment]
Can you clarify which method isn't being called? The [flickr sample](https://github.com/bumptech/glide/blob/eb2d54ba034721717075e02677524a1f20ed1adf/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrModelLoader.java#L51) does rely on a ModelLoader that extends BaseGlideUrlLoader to modify the requested size in the URL, which I think is what you're trying to do. As far as I can tell, that works fine in the flickr sample.

**Comment by PaulWoitaschek** [comment]
I did not say that any method is not get called. I said that getUrl gets called, but the whole image gets downloaded anyways, so it seems that the modified url does not get used.

**Comment by sjudd** [comment]
Ah got it, thanks for clarifying. In the flickr sample I see the url I expect being created in the BaseGlideUrlLoader and I see that url being requested in HttpUrlFetcher. 

What networking library are you using? Can you verify that the url you expect is or isn't being loaded by the networking library?

**Comment by PaulWoitaschek** [comment]
I am not using any integration library. I use OkHttp in the rest of my project for networking.

**Comment by PaulWoitaschek** [comment]
I tried the sample. It works well with the photo class. However I am using `String` directly because I want to apply it to server urls.

You can try it with the sample app and not let the flickr sample load the photos but directly the resolved string urls.

A url loader like this will replace every image to load with an image of jimi hendrix. (and it does in 3.x)
If you set the breakpoint to getUrl, you can see that it gets called for each image. However it does not get applied. It always loads the url you supplied initially.

```java
public class SameImageLoader extends BaseGlideUrlLoader<String> {

  public static class Factory implements ModelLoaderFactory<String, InputStream> {

    @Override
    public ModelLoader<String, InputStream> build(MultiModelLoaderFactory multiFactory) {
      return new SameImageLoader(multiFactory.build(GlideUrl.class, InputStream.class));
    }

    @Override
    public void teardown() {
    }
  }

  public SameImageLoader(ModelLoader<GlideUrl, InputStream> urlLoader) {
    super(urlLoader);
  }

  @Override
  public boolean handles(String model) {
    return true;
  }

  @Override
  protected String getUrl(String model, int width, int height, Options options) {
    return "https://img.discogs.com/SLLPFJ_vMX9ZrhktQjO_nS_-iqg=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/A-110593-1449578430-6807.jpeg.jpg";
  }
}
```

So when you're in `FlickrPhotosGrid` and pass the url directly:

```java
  @Override
    public void onBindViewHolder(PhotoViewHolder holder, int position) {
      final Photo current = photos.get(position);
      String url = Api.getPhotoURL(current, 2000, 2000);

      fullRequest.load(url)
          .into(holder.imageView);
```

Instead of a grid of jimi hendrixes you see just the regular images at the size of 2000x2000x.

**Comment by sjudd** [comment]
Can you show your AppGlideModule code? What method do you use to register your ModelLoader? ``append`` or ``prepend``?

**Comment by PaulWoitaschek** [comment]
I'm using append. What is the difference? I can't find any documentation on that.

**Comment by sjudd** [comment]
Yeah this isn't well documented, I need to get to that, sorry!

prepend/append determine the order in which ModelLoaders are called. At the beginning of a request, Glide looks at the given model and requested resource and finds all possible paths using registered components to load the requested resource from the model. Each of those paths is then tried in order until one succeeds or all fail.

By using append, you're adding your ModelLoader after any existing ModelLoaders for the model type (in this case String). That means your ModelLoader will only be tried if the others for the model type fail. 

Use prepend instead to indicate that you want your ModelLoader to be tried first.

I know that the calls the getUrl make this more confusing. For simplicities sake we construct all DataFetchers in the order we will try to call them when a request is made rather than trying to only call each ModelLoader when we're definitely going to also call its DataFetcher.

**Comment by PaulWoitaschek** [comment]
Prepend fixes it, thanks! Shall I leave this open as a reminder to add some javadoc?

**Comment by sjudd** [comment]
Sure thanks!
