### ISSUE TITLE
BitmapImageViewTarget return null

### ISSUE THREAD

**Issue by nuli1228588792** [bumptech/glide#2199]
**Glide Version**:
Glide 4.0.0

**Integration libraries**:
okhttp3:okhttp:3.8.1

**Device/Android Version**:
huawei MHA-AL100 android 7.0

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
I use Glide 4.0.0 load image in listViewAdapter : the code like this 

       @Override
	public View getItemView(int position, View convertView, ViewGroup parent) {
               .....
               Glide.with(context).asBitmap().load(avatorUrl).apply(options)
						.into(new BitmapImageViewTarget(vh.avator){
					@Override
					protected void setResource(android.graphics.Bitmap resource) {
						Log.i("TAGF","resource=="+resource);
						super.setResource(resource);
					}
                });
              return convertView;
        }

I want to use loaded bitmap for transition, but  the method setResource return twice in every request,
 the log is that:

08-02 23:34:20.664 4276-4276/com.let I/TAGF: resource==null
08-02 23:34:20.664 4276-4276/com.let I/TAGF: resource==android.graphics.Bitmap@e54b272
08-02 23:34:20.664 4276-4276/com.let I/TAGF: resource==null
08-02 23:34:20.664 4276-4276/com.let I/TAGF: resource==android.graphics.Bitmap@412b37d
08-02 23:34:20.664 4276-4276/com.let I/TAGF: resource==null
08-02 23:34:20.665 4276-4276/com.let I/TAGF: resource==android.graphics.Bitmap@d9c0a79
08-02 23:34:20.665 4276-4276/com.let I/TAGF: resource==null
08-02 23:34:20.665 4276-4276/com.let I/TAGF: resource==android.graphics.Bitmap@e9ae6c3
08-02 23:34:20.665 4276-4276/com.let I/TAGF: resource==null
08-02 23:34:20.665 4276-4276/com.let I/TAGF: resource==android.graphics.Bitmap@815db40
08-02 23:34:20.666 4276-4276/com.let I/TAGF: resource==null
08-02 23:34:20.666 4276-4276/com.let I/TAGF: resource==android.graphics.Bitmap@93783be
08-02 23:34:20.666 4276-4276/com.let I/TAGF: resource==null
08-02 23:34:20.666 4276-4276/com.let I/TAGF: resource==android.graphics.Bitmap@9bb2c1f
08-02 23:34:20.667 4276-4276/com.let I/TAGF: resource==null
08-02 23:34:20.667 4276-4276/com.let I/TAGF: resource==android.graphics.Bitmap@9bb2c1f

can you help me ?

**Comment by sjudd** [comment]
``setResource`` is used to set both placeholder ``Drawables`` and ``Bitmaps``/``Drawables`` that Glide eventually loads. If you're not using a placeholder, ``setResource`` will be called once with ``null`` each time a new load starts. If you were using a placeholder, you'd see ``setResource`` being called with your placeholder. 

If you want a callback for when the load completes, use [RequestListener](http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/RequestListener.html) or if you have to get the callback in a ``Target``, use [``onResourceReady``](http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/target/Target.html#onResourceReady-R-com.bumptech.glide.request.transition.Transition-)
