### ISSUE TITLE
Removed the method signature() in v4.0.0 ?

### ISSUE THREAD

**Issue by Joky-SSS** [bumptech/glide#2201]
can not find method signature()  and class StringSignature.
    What's different between v3.8.0 and v4.0.0?

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/migrating.html#requestoptions

http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/RequestOptions.html#signature-com.bumptech.glide.load.Key-
