### ISSUE TITLE
how to use okhttp3-integration:4.0.0@aar listening glide4.0.0 download progress???

### ISSUE THREAD

**Issue by yaochangliang159** [bumptech/glide#2202]
`
 compile 'com.github.bumptech.glide:glide:4.0.0'
  compile 'com.squareup.okhttp3:okhttp:3.8.0'
  compile 'com.github.bumptech.glide:okhttp3-integration:4.0.0@aar'
`
how to listen in glide load image progress with percent???
here is a library to listen progress for glide 3.7.0
[https://github.com/JessYanCoding/ProgressManager](url)
but it not works on glide 4.0.0
please help me....

**Comment by sjudd** [comment]
Unfortunately that link doesn't seem to work. The basic principle in v3 and v4 should be the same. You may want to ask the author of that library to update it so it works with v4.
