### ISSUE TITLE
Recommended way of saving a GIF fetched from cache to a file?

### ISSUE THREAD

**Issue by Saketme** [bumptech/glide#2205]
**Glide Version**: 3.7
**Integration libraries**: Okhttp3
**Use case background**: Saving images as files

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
private Single<GlideDrawable> findHighestResImageFromCache(MediaAlbumItem albumItem) {
  return Single.fromCallable(() -> {
    RequestManager.ImageModelRequest<String> glideRequestManager = Glide.with(this).using(new GlideNetworkDisablingLoader<String>());
    DrawableTypeRequest<String> fullResolutionRequest = glideRequestManager.load(albumItem.mediaLink().originalUrl());
    DrawableTypeRequest<String> optimizedImageRequest = glideRequestManager.load(albumItem.mediaLink().optimizedImageUrl(getDeviceDisplayWidth()));

    FutureTarget<GlideDrawable> imageFutureTarget = fullResolutionRequest
        .thumbnail(optimizedImageRequest)
        .diskCacheStrategy(DiskCacheStrategy.ALL)
        .into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
    return imageFutureTarget.get();
  });
}
```

Hey folks, I am exploring if it's possible to save an image downloaded by Glide to a file and eventually share it with another app. I think I cannot use `downloadOnly()` because I'd like to hit cache first.

So far I've been able to figure out that there's `GifResourceEncoder` which I can use by supplying a File output stream. Could you please review this code and see if it's the correct usage?

```java
Resource<GifDrawable> gifDrawable = new GifDrawableResource((GifDrawable) glideDrawable);
GifResourceEncoder gifResourceEncoder = new GifResourceEncoder(Glide.get(this).getBitmapPool());

File temporaryImageFile = new File(getExternalCacheDir() + "/" + filename);
FileOutputStream fileOutputStream = new FileOutputStream(temporaryImageFile);
gifResourceEncoder.encode(gifDrawable, fileOutputStream);
```

**Comment by sjudd** [comment]
Have you tried downloadOnly? It should hit the disk cache if the item is already cached.

**Comment by Saketme** [comment]
But can I force `downloadOnly()` to only hit the cache? 

To explain more about my usecase, I am creating a photo viewer activity which contains the image a download button and an option for fetching high-res version of the image. The download button is only enabled when the image gets fetched by Glide so I'm certain that there is atleast one image in cache, either the standard version or the high-res version.

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/RequestOptions.html#onlyRetrieveFromCache-boolean-

**Comment by Saketme** [comment]
Oh no, I'm not on v4 yet :( Is there any similar option for v3 or do I have to make the change?

**Comment by sjudd** [comment]
Yeah I don't think that option is implemented in v3. That said there are various issues here showing you how to do it on v3 with a custom ModelLoader, see NetworkDisablingLoader here: https://github.com/bumptech/glide/issues/639

**Comment by Saketme** [comment]
This worked, thanks!
