### ISSUE TITLE
Glide 4 Cache corruption

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#2213]
**Glide Version**:
4.0.0

**Issue details / Repro steps / Use case background**: 

Since glide 4 is much more efficient I had a race condition in my custom DataFetcher that can be called multiple times at the same time for the same model.
This race condition could lead to return a dataCallback.onDataReady(imageStream); when something was actually also writing in that file. (Writing the same data, but I guess Android did not like that).

This case leads to Glide cache corruption that it can't recover until we clear the disk and memory cache.

See stack trace below. If it's not already the case I'd propose that when glide can't decode an entry for it's disk cache or it's memory cache it clears it if it's not the case.
Currently most of the time, it will set the imageview to black and still call onResourceReady if we use a listener and not the onLoadFailed. Leaving no clue to the app that this corruption has happened and can't react accordingly.

And unlike what the stack trace seems to say, the DataFetcher is not called again.

**Stack trace / LogCat**:
```ruby
08-06 14:26:58.910 1141-1141/xxxxx W/Glide: Load failed for ImageRequest{url='http://192.168.1.80:8080/image/image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F', onlyCached=false, keepTransparency=true, cacheKey=image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F} with size [256x256]
                                                                           class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                             Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Bitmap->Bitmap}, DATA_DISK_CACHE, ImageRequest{url='http://192.168.1.80:8080/image/image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F', onlyCached=false, keepTransparency=true, cacheKey=image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F}
                                                                               Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Bitmap}
                                                                             Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Bitmap->Bitmap}, DATA_DISK_CACHE, ImageRequest{url='http://192.168.1.80:8080/image/image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F', onlyCached=false, keepTransparency=true, cacheKey=image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F}
                                                                               Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Bitmap}
                                                                             Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Bitmap->Bitmap}, DATA_DISK_CACHE, ImageRequest{url='http://192.168.1.80:8080/image/image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F', onlyCached=false, keepTransparency=true, cacheKey=image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F}
                                                                               Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Bitmap}
                                                                             Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Bitmap->Bitmap}, REMOTE, ImageRequest{url='http://192.168.1.80:8080/image/image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F', onlyCached=false, keepTransparency=true, cacheKey=image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F}
                                                                               Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Bitmap}
                                                                             Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Bitmap->Bitmap}, REMOTE, ImageRequest{url='http://192.168.1.80:8080/image/image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F', onlyCached=false, keepTransparency=true, cacheKey=image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F}
                                                                               Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Bitmap}
                                                                             Cause (6 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Bitmap->Bitmap}, REMOTE, ImageRequest{url='http://192.168.1.80:8080/image/image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F', onlyCached=false, keepTransparency=true, cacheKey=image%3A%2F%2Fmusic%40F%253a%255cFakeLibrary%255cMusic%255cMisc%255cClassic%2520turtle%2520-%252001%2520-%2520Robert%2520Knappa%2520-%2520Bones%2520and%2520fingers.mp3%2F}
                                                                               Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Bitmap}
```

**Comment by sjudd** [comment]
There's some logic in the disk cache that prevents simultaneous writes to the same key. How confident are you that the complete data was written each time? 

We could delete disk cache entries after loads fail, but that's not a solution for this particular problem. It would be a solution if a server transiently returned invalid data. For this case, it's much better to not write the corrupt data to begin with.

**Comment by Tolriq** [comment]
Corrupted data is written to the cache.

Not sure if there's double write at the same time (on your side)

My fetcher does download images and resize them to a max size then just return a fileinputstream to glide.

The problem was that since there was sometimes a read from glide and a write from my fetcher at the same time the cache get bad data.

From what you say bad data should not be written so not sure what is going on here.

All I'm sure is that each time there was the issue my side of the cache was always valid images.

And that glide after cache corruption would set black images for that image even after process kill so not a memory cache issue. 

I've added security in my fetcher to prevent double write. But if cache corruption can happens understanding the issue could help solving future issues for many.

**Comment by TWiStErRob** [comment]
@Tolriq if I understand correctly you have your own mini "image loader library" within a Glide fetcher and the cache of that component is not thread safe. You can see that your cache is not corrupted, and Glide's is, but is it possible that at the time Glide observed your cached File, another thread was re-opening and writing to that file? And only after Glide copied it over to its cache, your write completed and you saw that uncorrupted state yourself?

> Any third party libraries called must be thread safe (or move the work to another thread) since this method will be called from a thread in a ExecutorService that may have more than one background thread. -- http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/load/data/DataFetcher.html#loadData-com.bumptech.glide.Priority-com.bumptech.glide.load.data.DataFetcher.DataCallback-

**Comment by Tolriq** [comment]
Well if you had read you have the answer ;) I guess things does not change :p

And in the end I just explained a way to reproduce the issue. But the issue is there's corrupted data in Glide cache. This can happens with that method and so can also occurs with other cases. So well probably needs some more investigation and possible solution for apps to recover.

For my fetcher with cache, a corrupted block on sdcard could produce the same effect without any threading things ;)
