### ISSUE TITLE
how to free Glide's memory when app is closed?

### ISSUE THREAD

**Issue by showedboy** [bumptech/glide#2214]
**Glide Version**:3.7.0

**Integration libraries**:okhttp3-3.6.0

**Device/Android Version**:4.4.2

**Issue details / Repro steps / Use case background**: how to free Glide's memory when app is closed?
My APK uses a lot of pictures. And when app is closed,before closed use Glide.get(this).clearMemory();,then run full GC,has 0 Activitys,and many views,then dump the memory heap to check app’s memeory,I find a lot of picture's byte array,and owns by 
com.bumptech.glide.load.engine.bitmap_recycle.GroupedLinkedMap$LinkedEntry. Take up 23MB.
how to clear them.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(getApplicationContext())
                .load(url)
                .crossFade()
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .placeholder(placeholderId)
                .error(errorId)
                .skipMemoryCache(skip)
                .into(imageView);
```

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/caching.html#resource-management.

The documentation there is for v4, but most of the same options are available in v3.
