### ISSUE TITLE
glide doesn't load image :(

### ISSUE THREAD

**Issue by urrabit** [bumptech/glide#2215]
i want to load drawable image but glide doesn't work  without error log  X(
could i forget something? plz help me

**Device/Android Version**: Galaxy Note3

**Glide Version**:
```
    compile 'com.github.bumptech.glide:glide:3.5.2'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'
```

**Code here**:
```
public class ActivityName extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.layout_name);

        ImageView noticePart2;
   
        noticePart2 = (ImageView) findViewById(R.id.tr_notice_part2);

        Glide.with(this)
                .load(R.drawable.shape_00_00)
                .into(noticePart2);
    }
}
```

(i've already changed with's this to getApplicationContext() and ActivityName.this )

**Comment by sjudd** [comment]
Glide doesn't decode a lot of types of Drawables. Typically those can be set easily by just using ``imageView.setImageDrawable(getResources().getDrawable(R.drawable.shape_00_00);``
