### ISSUE TITLE
Glide 4.0 play gif

### ISSUE THREAD

**Issue by Shyky** [bumptech/glide#2217]
Glide 4.0 play gif so slow?

**Comment by sjudd** [comment]
You can take a look at [``GifDecoder``](https://github.com/bumptech/glide/blob/6b137c2b1d4b2ab187ea2aa56834dea039daa090/third_party/gif_decoder/src/main/java/com/bumptech/glide/gifdecoder/GifDecoder.java) and see if you can find a way to speed it up. Pull requests, especially for performance improvements, are always welcome!

**Comment by Shyky** [comment]
ok,I will try.

**Comment by Shyky** [comment]
Glide play gif very slow in RecyclerView.

**Comment by caineyang** [comment]
i find it too,i have several gifs in a recycleView,and it go like one gif plays a frame,and then a randomly another gif play a frame ,it was ok on my last app version written in java,i am writing the new version with kotlin,this happens,i am confused,i know its not the language,but do not know what went wrong

**Comment by caineyang** [comment]
even in a recycleView with only one gif, it does not animates smoothly
