### ISSUE TITLE
Can not find the right cache file  when loading a gif image using DiskLruCache?

### ISSUE THREAD

**Issue by miguoer** [bumptech/glide#2218]
Hello. I am using Glide to load some gif images. I use the DiskLruCache for caching. But each time when I finish the activity, and then re-start it, the diskcache for gif images doesn't work. 

I have checked the cache files at data/data/package_name/cache/image_manager_disk_cache. The gif images are in the folder. Then I checked the put and get method at class DiskLruCacheWrapper. I found that the safeKey from safeKeyGenerator.getSafeKey(key) is different from the safeKey  put into the cache. It really doubts me. Can you help me to figure out this problem?

By the way, each time when I create the acitivity, I preload the gif image. 

- my Glide config:
```
        RequestOptions mNormalOptions = new RequestOptions()
                .fitCenter()
                .priority(Priority.HIGH)
                .diskCacheStrategy(DiskCacheStrategy.RESOURCE);
```

- my code:
```
        public void displayGifWithPlaceHolder(final Context mContext, final ImageView mImageView, final AnimateImageInfo mInfo) {
        LogUtil.d(TAG, "displayGifWithPlaceHolder: animateUrl=" + mInfo.getAnimateImageUrl() + ", firstFrameUrl" + mInfo.getFirstFrameImageUrl() + ", staticImageUrl" + mInfo.getStaticImageUrl());
        Glide.with(mContext)
                .load(mInfo.getAnimateImageUrl())
                .apply(mNormalOptions)
                .into(new ImageViewTarget<Drawable>(mImageView) {
                    @Override
                    protected void setResource(@Nullable Drawable resource) {
                    }

                    @Override
                    public void onLoadFailed(@Nullable Drawable errorDrawable) {
                        LogUtil.d(TAG, "Load animate image failed. Url is " + mInfo.getAnimateImageUrl());
                        Glide.with(mContext)
                                .load(mInfo.getFirstFrameImageUrl())
                                .apply(mNormalOptions)
                                .into(new SimpleTarget<Drawable>() {
                                    @Override
                                    public void onResourceReady(Drawable resource, Transition<? super Drawable> transition) {
                                        LogUtil.d(TAG, "First frame image resource ready. Url is " + mInfo.getFirstFrameImageUrl());
                                        mImageView.setImageDrawable(resource);
                                    }

                                    @Override
                                    public void onLoadFailed(@Nullable Drawable errorDrawable) {
                                        LogUtil.d(TAG, "Load first frame image failed. Url is " + mInfo.getFirstFrameImageUrl());
                                        Glide.with(mContext)
                                                .load(mInfo.getStaticImageUrl())
                                                .apply(mNormalOptions)
                                                .into(new SimpleTarget<Drawable>() {
                                                    @Override
                                                    public void onResourceReady(Drawable resource, Transition<? super Drawable> transition) {
                                                        mImageView.setImageDrawable(resource);
                                                    }
                                                });
                                    }
                                });
                    }

                    @Override
                    public void onLoadStarted(@Nullable final Drawable placeholder) {
                        LogUtil.d(TAG, "start to load animate image " + mInfo.getAnimateImageUrl());
                        Glide.with(mContext)
                                .load(mInfo.getFirstFrameImageUrl())
                                .apply(mNormalOptions)
                                .into(new SimpleTarget<Drawable>() {
                                    @Override
                                    public void onLoadStarted(@Nullable Drawable placeholder) {
                                        LogUtil.d(TAG, "Load static image as place holder when loading first frame image.");
                                        Glide.with(mContext)
                                                .load(mInfo.getStaticImageUrl())
                                                .apply(mNormalOptions)
                                                .into(new SimpleTarget<Drawable>() {
                                                    @Override
                                                    public void onResourceReady(Drawable resource, Transition<? super Drawable> transition) {
                                                        LogUtil.d(TAG, "Static image resource ready. Url is " + mInfo.getStaticImageUrl());
                                                        if (!mInfo.isFirstFrameResourceReady()) {
                                                            mImageView.setImageDrawable(resource);
                                                        }
                                                    }
                                                });
                                    }

                                    @Override
                                    public void onResourceReady(Drawable resource, Transition<? super Drawable> transition) {
                                        LogUtil.d(TAG, "First frame image resource ready. Url is " + mInfo.getFirstFrameImageUrl());
                                        mInfo.setFirstFrameResourceReady(true);
                                        if ((mImageView.getDrawable() instanceof GifDrawable && ((GifDrawable) mImageView.getDrawable()).isRunning())) {
                                            LogUtil.d(TAG, "Gif is running. Don't load first frame image.");
                                            return;
                                        }
                                        if (mInfo.isAnimate() && !mInfo.isAutoPlay() && !mImageView.isSelected()) {
                                            return;
                                        }
                                        mImageView.setImageDrawable(resource);
                                    }

                                    @Override
                                    public void onLoadFailed(@Nullable Drawable errorDrawable) {
                                        LogUtil.d(TAG, "Load first frame image failed. Url is " + mInfo.getFirstFrameImageUrl());
                                        Glide.with(mContext)
                                                .load(mInfo.getStaticImageUrl())
                                                .apply(mNormalOptions)
                                                .into(new SimpleTarget<Drawable>() {
                                                    @Override
                                                    public void onResourceReady(Drawable resource, Transition<? super Drawable> transition) {
                                                        LogUtil.d(TAG, "Static image resource ready. Url is " + mInfo.getStaticImageUrl());
                                                        mImageView.setImageDrawable(resource);
                                                    }

                                                    @Override
                                                    public void onLoadFailed(@Nullable Drawable errorDrawable) {
                                                        LogUtil.d(TAG, "Load static image failed. Url is " + mInfo.getStaticImageUrl());
                                                    }
                                                });
                                    }

                                });


                    }

                    @Override
                    public void onResourceReady(Drawable resource, @Nullable Transition<? super Drawable> transition) {
                        LogUtil.d(TAG, "Animate image resource ready. Url is " + mInfo.getAnimateImageUrl());
                        if (resource instanceof GifDrawable) {
                            mImageView.setImageDrawable(resource);
                            ((GifDrawable) resource).start();
                        }
                    }
                });
    }
```

**Comment by sjudd** [comment]
Enable the ``Engine`` log tag and check to see why the requests you're making have different cache keys: http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses

**Comment by miguoer** [comment]
I check the Key put into DiskLruCache and find that it seems to be a DataCacheKey which has no height and width. But when the get method in DiskLruCacheWrapper called, the key is a ResourceCacheKey  which has height and width. 

I change the DiskCacheStrategy from DiskCacheStrategy.RESOURCE to DiskCacheStrategy.ALL which can sovle the problem.

I remember that  using DiskCacheStrategy.RESOURCE is the recommended way to load a gif image. But why the key put into the DiskLruCache  is a DataCacheKey?

**Comment by sjudd** [comment]
ResourceCacheKey is used to read/write the decoded/transformed resource, DataCacheKey is used to read/write the original unmodified data. 

It sounds like the disk cache strategies you're using in your two requests differ. It's no longer harmful to use DiskCacheStrategy.RESOURCE for gifs with Glide v4 though it used to be for Glide v3.

**Comment by miguoer** [comment]
My disk cache strategies are the same. I have enabled Engine log tag and got this:

`0-12 18:14:54.526 V/Engine  (11553): Started new load in 0.06999999999999999ms, key: EngineKey{model=http://cdn.video.51togic.com/metro/background/1505822448585.gif, width=324, height=324, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=735758180, transformations={}, options=Options{values={}}}
10-12 18:14:54.526 D/GlideStrategy(11553): http://cdn.video.51togic.com/metro/background/1505822448585.gif onLoadStarted
10-12 18:14:54.536 W/Glide   (11553): Load failed for http://cdn.video.51togic.com/metro/background/1505822448585.gif with size [324x324]
10-12 18:14:54.536 W/Glide   (11553): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
10-12 18:14:54.536 W/Glide   (11553):   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
10-12 18:14:54.536 W/Glide   (11553):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
10-12 18:14:54.536 W/Glide   (11553):       Cause (1 of 1): class java.net.UnknownHostException: Unable to resolve host "cdn.video.51togic.com": No address associated with hostname
10-12 18:14:54.536 E/Glide   (11553): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
10-12 18:14:54.536 I/Glide   (11553): Root cause (1 of 1)
10-12 18:14:54.536 D/GlideStrategy(11553): http://cdn.video.51togic.com/metro/background/1505822448585.gif onLoadFailed
`

If I change the disk cache strategies to DiskCacheStrategy.DATA, the problem can be solved. And the log is:
`10-12 18:09:53.135 V/Engine  ( 1863): Started new load in 0.119ms, key: EngineKey{model=http://cdn.video.51togic.com/metro/background/1505822448585.gif, width=324, height=324, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=1415888044, transformations={}, options=Options{values={}}}
10-12 18:09:53.165 D/GlideStrategy( 1863): http://cdn.video.51togic.com/metro/background/1505822448585.gif onResourceReady
10-12 18:09:53.165 D/GlideStrategy( 1863): http://cdn.video.51togic.com/metro/background/1505822448585.gif plays animate
10-12 18:09:53.165 V/Engine  ( 1863): Started new load in 0.108ms, key: EngineKey{model=com.bumptech.glide.gifdecoder.StandardGifDecoder@432a2688, width=324, height=324, resourceClass=class android.graphics.Bitmap, transcodeClass=class android.graphics.Bitmap, signature=com.bumptech.glide.load.resource.gif.GifFrameLoader$FrameSignature@66379709, hashCode=-883569687, transformations={class android.graphics.drawable.BitmapDrawable=com.bumptech.glide.load.resource.bitmap.BitmapDrawableTransformation@4213b5b8, class android.graphics.Bitmap=com.bumptech.glide.load.resource.UnitTransformation@4213b5b8, class com.bumptech.glide.load.resource.gif.GifDrawable=com.bumptech.glide.load.resource.gif.GifDrawableTransformation@4213b5b8}, options=Options{values={}}}
`
 As you can see, when using DiskCacheStrategy.RESOURCE, the EngineKey will also have width and height. So I think whether this is a bug when loading a gif image.
