### ISSUE TITLE
How to fix ExifOrientation from url image with 3.7.0

### ISSUE THREAD

**Issue by fg2q1q3q** [bumptech/glide#2219]
Hello,I use glide 3.7.0,There are avarts in my app, but some of them are rotated。so I need to get the degree of the image, and then rotate the exception automatically，I see the issuse #1429 ，But I don't understand, probably because it's 4.0，please help me,thanks

**Comment by TWiStErRob** [comment]
See #665 as well. The only difference between v3 and v4 in this issue is that v4: `dataCallback.onDataReady(stream);` becomes `return stream;` in v3.
