### ISSUE TITLE
Timeout changes with glide 4.0.0 

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [bumptech/glide#2220]
I searched a long time for the solution how to easily change the Timeout from only 2.5s to something higher to 10s or 20s. 
I did not find any real documentation about it, but I think it may be correct to use the Option class and it's memory function. 

Using this code before the first Glide call is made will change the default timeout 
``` 
Option.memory("com.bumptech.glide.load.model.stream.HttpGlideUrlLoader.Timeout", 2500).update(20_000, MessageDigest.getInstance("SHA-512"))
``` 

**Glide Version**: 4.0.0

**Integration libraries**: default 

**Device/Android Version**: Android 6.0, Samsung Galaxy S5 and Android 7.0 on Emulator 

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
Glide.with(view)
```

**Comment by sjudd** [comment]
Close, this isn't well documented.

I've added a section on the ``Option`` class to the documentation here: http://bumptech.github.io/glide/doc/options.html#component-options.

I'm also going to submit a change that will expose ``timeout()`` as a method on ``RequestOptions`` though with a note that it will only work if you're using Glide's default networking library.

I need to find a way to expose some of these individual options better in our documentation site, but I can't think of a great way at the moment other than just adding a hodgepodge of frequently mentioned options.

**Comment by sjudd** [comment]
If this comes up again I'll reconsider, hopefully the option added to RequestOptions is sufficient.
