### ISSUE TITLE
Glide 4.0.0 doesn't have placeholder

### ISSUE THREAD

**Issue by MohammadRezaei92** [bumptech/glide#2222]
**4.0.0**:

**com.squareup.okhttp3:logging-interceptor:3.4.2**:

**7.0.1**:

**I used glide ver3.7.0 before and now upgrade it to ver4.0.0 but it seems like ver4.0.0 doesn't have placeholder method.
![untitled](https://user-images.githubusercontent.com/14319444/29108218-3bc19a0a-7cf3-11e7-9b9e-959226a854d7.png)
**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
You must have found http://bumptech.github.io/glide/doc/migrating.html#generated-api
