### ISSUE TITLE
Load SVG file by Glide 4.0.0 - Can't clear memory cache

### ISSUE THREAD

**Issue by sonzerolee** [bumptech/glide#2223]
I followed the sample here: [https://github.com/bumptech/glide/tree/master/samples/svg](https://github.com/bumptech/glide/tree/master/samples/svg)

**I have 2 Activity: MainActivity and SecondActivity**
**At MainActivity: i have a button, when clicked on this button will move to SecondActivity**

```
btnGotoSecond= (Button) findViewById(R.id.btn_goto_second);
btnGotoSecond.setOnClickListener(new View.OnClickListener() {
	@Override
	public void onClick(View v) {
		Intent intent = new Intent(context, SecondActivity.class);
		startActivity(intent);
	}
});
```

**At SecondActivity: I have 20 ImageView (Each ImageView will be displayed 1 SVG image), and 1 button (when clicked on this button will back to MainActivity)**

```
protected void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);
	setContentView(R.layout.activity_second);
	
	imageView1 = (ImageView) findViewById(R.id.svg_image_view1);
	imageView2 = (ImageView) findViewById(R.id.svg_image_view2);
	imageView3 = (ImageView) findViewById(R.id.svg_image_view3);
	...

	requestBuilder = GlideApp.with(this)
			.as(PictureDrawable.class)
			.transition(withCrossFade())
			.listener(new SvgSoftwareLayerSetter());
			
	loadSvgToImageView(imageView1,"svgFile1");
	loadSvgToImageView(imageView2,"svgFile2");
	loadSvgToImageView(imageView3,"svgFile3");
	...

	btnBackToMain= (Button) findViewById(R.id.btn_back_to_main);
	btnBackToMain.setOnClickListener(new View.OnClickListener() {
		@Override
		public void onClick(View v) {
			clearAllCache();
			Intent intent = new Intent(context, MainActivity.class);
			startActivity(intent);
		}
	});
}
```

```
private void loadSvgToImageView(ImageView iv, String svgName) {
	int idR = this.getResources().getIdentifier(svgName, "raw", this.getPackageName());
	Uri uri = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://" + getPackageName() + "/" + idR);
	requestBuilder
		.load(uri)
		.into(iv);
}

public void clearAllCache() {
	GlideRequests glideRequests = GlideApp.with(this);
	glideRequests.clear(imageView1);
	glideRequests.clear(imageView2);
	glideRequests.clear(imageView3);
	...
	GlideApp.get(this).clearMemory();
	File cacheDir = Glide.getPhotoCacheDir(this);
	if (cacheDir.isDirectory()) {
		for (File child : cacheDir.listFiles()) {
			if (!child.delete()) {
				//Log.w(TAG, "cannot delete: " + child);
			}
		}
	}
}
```

**Follow the steps below:**
    1. Start project: At MainActivity, my allowcated is 29.26MB.
    2. At MainActivity, click btnGotoSecond, go to SecondActivity (after successful loading 20 SVG image into 20 ImageView), my allowcated is 52.28MB.
    3. At SecondActivity, click btnBackToMain, back to MainActivity,  my allowcated ~ 50.33MB.

I repeat second and third step. Each time repeating my allocated increased more than. When my allocated increases to 255~256MB, my app crashed (error message: Unfortunately, MyAppName has stopped).
I tested on LG G4, Samsung S5 and Genymotion emulator.

Please help.

**Comment by sjudd** [comment]
Sounds like you have a memory leak in one or both activities. See https://developer.android.com/studio/profile/investigate-ram.html.

If it turns out to be a leak in Glide, please re-open the issue.
