### ISSUE TITLE
Low-resolution display with placeholder with glide4.0

### ISSUE THREAD

**Issue by DCTANT** [bumptech/glide#2225]
Hello everyone, that's my first time to submit issue in github, if question doesn't satisfy requirement, please point out the error. I will correct it, Thanks.

In my new project, I use glide 4.0 first time. I finish configuration and use GlideApp to display pictures in project.

This is my configuration:
```
@GlideModule
public class MyGlideModule extends AppGlideModule {
	@Override
	public void applyOptions(Context context, GlideBuilder builder) {
		int memoryCacheSizeBytes = 1024 * 1024 * 20; // 20mb
		builder.setMemoryCache(new LruResourceCache(memoryCacheSizeBytes));
		int diskCacheSizeBytes = 1024 * 1024 * 100; // 100 MB
		builder.setDiskCache(new InternalCacheDiskCacheFactory(context, diskCacheSizeBytes));
	}
}
```

And this is my Util with GlideApp:
```
public static boolean display(Context context, ImageView imageView, String imageUrl, int errRes) {
		String url = imageUrl;
		if (imageUrl == null || imageUrl.length() == 0) {
			imageView.setImageResource(errRes);
			return false;
		}
		if (!imageUrl.contains("http://") && !imageUrl.contains("https://")) {
			url = S_WebInfo.WebRootUrl + imageUrl;
		}
		if (context instanceof Activity) {

			GlideApp.with((Activity) context)
					.load(url)
//					.placeholder(R.mipmap.unload_default_pic_small)
					.diskCacheStrategy(DiskCacheStrategy.ALL)
					.skipMemoryCache(false)
//					.placeholder(R.mipmap.unload_default_pic)
					.into(imageView);
		} else {
			GlideApp.with((Activity) context)
					.load(url)
//					.placeholder(R.mipmap.unload_default_pic_small)
					.diskCacheStrategy(DiskCacheStrategy.ALL)
					.skipMemoryCache(false)
//					.placeholder(R.mipmap.unload_default_pic)
					.into(imageView);
		}
		return true;
	}
```

Everything is OK, when I don't use placeholder in GlideApp, only show nothing when pictures haven't loaded. But when I use placeholder, everything become error(My placeholder pictures' resolution is 600*600.). My pictures show in very low resolution and dim. They also become very small. I think pictures are compressed and I don't know how to fix them. Please help me!

**Comment by sjudd** [comment]
It's unusual to use mipmaps for placeholders, though I'm not sure that it would break anything.

Can you share the xml for the imageView in question? 

Are you re-using Views? Is the ``display()`` method called in a ``RecyclerView``, ``ListView``, or ``GridView``?

**Comment by DCTANT** [comment]
This is my xml file: 
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
			  android:layout_width="match_parent"
			  android:layout_height="match_parent"
			  android:gravity="center_horizontal"
			  android:orientation="vertical">

	<include layout="@layout/title_detail"></include>

	<TextView
		android:id="@+id/hint"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_marginTop="68dp"
		android:text="Product Introduce"
		android:textColor="@color/white"
		android:textSize="25dp"/>

	<LinearLayout
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:layout_marginTop="45dp"
		android:orientation="horizontal"
		android:paddingBottom="65dp"
		android:paddingLeft="136dp"
		android:paddingRight="136dp">

		<ImageView
			android:id="@+id/productImage"
			android:layout_width="0dp"
			android:layout_height="wrap_content"
			android:layout_marginRight="65dp"
			android:layout_weight="1"
			android:maxHeight="551dp"
			android:maxWidth="764dp"/>

		<WebView
			android:id="@+id/showDetailWeb"
			android:layout_width="0dp"
			android:layout_height="wrap_content"
			android:layout_weight="1">
		</WebView>

	</LinearLayout>

</LinearLayout>`

This is my usage in Activity:
`ImageUtil.display(context, getViewObject().getImageView_productImage(), w_product.getCoverImagePath(), 0);`

I put my placeholder picture into drawable dictionary just now, but it didn't work still in low-resolution.
