### ISSUE TITLE
Black boxes when showing pictures right after downloading them

### ISSUE THREAD

**Issue by GauthierChan** [bumptech/glide#2226]
**Glide Version**: 3.8.0

**Integration libraries**: We only load local pictures we previously downloaded 

**Device/Android Version**: Happens on a Nexus 6P with 7.1.2 (couldn't reproduce it on a OnePlus 2 with 6.0.1, Samsung Galaxy S5 on 6.0.1 and a OnePlus 1 with 5.1.1)

**Issue details / Repro steps / Use case background**:  When loading a picture into an ImageView it 
 can happen that black blobs appear. It usually happens on a consecutive batch of pictures, then works again. Once we have a black blob on a picture, it stays until we clear the Glide cache.

We use Glide only to load local files into ImageViews. Every images are downloaded and saved on the user's storage.
If an image appears with a black box on the app with Glide and we try to do a simple call _imageView.setImageBitmap(BitmapFactory.decodeFile(filepath));_ with the same picture it will then show without a black box. 
In the same fashion, if we try to open the same file on another app it also shows without a black box.

It also usually happens after loading a lot of Bitmap (80+) into Glide for the first time.

![black stripes](https://user-images.githubusercontent.com/14746791/29134918-a0fa7b5e-7d38-11e7-9023-d896cae34638.png)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(activity)
.load(uri)
.listener(new RequestListener<String, GlideDrawable>() {
    @Override
    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
        return false;
    }

    @Override
    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
        classicViewHolder.uploading.setVisibility(View.GONE);
        return false;
    }
})
.override(maxWidth, maxHeight) // Both cannot be higher than 300
.centerCrop()
.into(img);
```

**Layout XML**:

Just an ImageView within a RelativeLayout

```xml
    <ImageView
        android:id="@+id/timeline_picture"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:adjustViewBounds="true"
        android:scaleType="centerCrop"/>
```

**Stack trace / LogCat**:

When it happens we get this like 80% of the time for each picture with a black box on the first loading with Glide:

```ruby
08-09 19:59:27.202 14186-30457/com.XXX.XXX D/skia: ------ png error Read Error!
08-09 19:59:27.202 14186-30457com.XXX.XXX D/skia: setjmp long jump!
```

**Comment by andrewmunn** [comment]
Occasionally seeing this issue on Pixel XL 8.0 beta with Glide 4.0
