### ISSUE TITLE
GifBitmapWrapperTransformation and GifBitmapWrapper missing from v4.0.0

### ISSUE THREAD

**Issue by rodly** [bumptech/glide#2227]
I'm migrating my application to v4 and have run into a snag. I'm curious why `GifBitmapWrapper` and `GifBitmapWrapperTransformation` was removed? They are fairly simple classes that allow the client to pass in either a `Bitmap` or `GifDrawable` and the transformation class also handles this for you. Was it outside the scope of the library? Did this pairing of resources become generalized somewhere in the library? I don't see it in the migration document.

**Comment by sjudd** [comment]
Glide v3 required you to specify every type used by every component in your request chain. If you wanted to load either a Bitmap or a GIF, you needed have components that accepted a single type that wrapped both a Bitmap and a GIF.

In Glide v4 you just specify the type you want to receive and the object you want to load the type from. Glide v4 will then dynamically find all available components that can be used to form a path from the object you want to load to the type you want to receive and then try each path in order until something works.

As a result in Glide v4 these wrapping types are no longer necessary and were removed. 

Out of curiosity what were you using these types for? If you had a custom transformation, you can instead just write and apply a ``BitmapTransformation`` directly: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/RequestOptions.html#transform-com.bumptech.glide.load.Transformation-

**Comment by rodly** [comment]
@sjudd thanks for the explanation, that makes sense. I was using them to to show both images and gifs in a list.
