### ISSUE TITLE
No default transition with Glide 4.0

### ISSUE THREAD

**Issue by andrewmunn** [bumptech/glide#2228]
I just upgraded to Glide 4.0 from 3.8 and I'm not seeing the default transition animation anymore. The documentation says there should be a default transition. I also tried the Flickr demo app and it also doesn't have transition animations, although that might be intentional.

**Glide Version**: 4.0

**Integration libraries**: Okhttp 3.0

**Device/Android Version**: Pixel XL 8.0 and Nexus 5x emulator running 8.0

**Issue details / Repro steps / Use case background**: None of my network images have a transition. They just pop-in after loading. Maybe it's an Android 8.0 bug?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(activity).load(myUrl).into(myImageView);
```

**Comment by sjudd** [comment]
Can you link me to the documentation that references a default transition in v4? We removed the default cross fade because it can cause a bunch of issues when used with placeholders and it can also cause performance issues if not used carefully. 

#2182 is a request to allow people to add their own default transition.

**Comment by andrewmunn** [comment]
Hi @sjudd thank you for responding so quickly.

The [Default Behavior](http://bumptech.github.io/glide/doc/transitions.html) section of The transitions documentation seems to suggest there is a default transition animation when loading from disk or network:

> Glide’s default transitions do not run if data is loaded from Glide’s in memory cache. However, Glide’s default transitions do run if data is loaded from Glide’s disk cache, a local source File or Uri or a remote source Url or Uri.

**Comment by sjudd** [comment]
Great thanks I'll try and clarify.
