### ISSUE TITLE
Images stop loading if app is idle for more than twenty seconds

### ISSUE THREAD

**Issue by clfristoe** [bumptech/glide#2234]
**Glide Version**: 3.8.0

**Integration libraries**: Unirest

**Device/Android Version**: Samsung S5 6.0.1

**Issue details / Repro steps / Use case background**: I am loading images from a web API (Droplr.com) and have options to share and view the corresponding link to them. If I load the app and don't scroll for about twenty seconds, only the placeholder images appear and the actual image from the url never loads. I'm also experiencing quite a bit of a lag depending on the size of the image.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```
`class CustomRecyclerAdapter extends RecyclerView.Adapter<CustomRecyclerAdapter.MyViewHolder> {

    private List<Row> rows = new ArrayList<>();
    public Context context;
    public LinearLayout layout;

    CustomRecyclerAdapter(List<Row> rowList) {
        this.rows.addAll(rowList);
    }

    @Override
    public MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        context = parent.getContext();
        final LayoutInflater inflater = LayoutInflater.from(parent.getContext());
        final View view = inflater.inflate(simplerow, parent, false);
        return new MyViewHolder(view);
    }

    @Override
    public void onBindViewHolder(final MyViewHolder holder, final int position) {
        final Row row = rows.get(position);
        Typeface typeface = Typeface.createFromAsset(context.getAssets(),"SourceSansPro-Regular.ttf");
        Typeface boldTypeface = Typeface.createFromAsset(context.getAssets(), "SourceSansPro-SemiBold.ttf");
        holder.dateTitle.setTypeface(typeface);
        holder.txtTitle.setTypeface(boldTypeface);

        holder.txtTitle.setText(row.getItemName());
        holder.dateTitle.setText(row.getItemDate());
        int placeholder = R.mipmap.ic_placeholder;
        if(row.getImgType()!=null) {
            switch (row.getImgType()) {
                case "IMAGE":
                    placeholder = R.mipmap.ic_image;
                    break;
                case "VIDEO":
                    placeholder = R.mipmap.ic_video;
                    break;
                case "LINK":
                    placeholder = R.mipmap.ic_link;
                    break;
                case "AUDIO":
                    placeholder = R.mipmap.ic_audio;
                    break;
                case "NOTE":
                    placeholder = R.mipmap.ic_note;
                    break;
                case "FILE":
                    placeholder = R.mipmap.ic_file;
                    break;
            }
   ```
Glide.with(context).load(row.getImgId()).centerCrop().placeholder(placeholder).into(holder.imageView);
        }
        holder.copyButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                PopupMenu popup = new PopupMenu(context, holder.copyButton);
                //Inflating the Popup using xml file
                popup.getMenuInflater().inflate(R.menu.popup_menu, popup.getMenu());
                //registering popup with OnMenuItemClickListener
                popup.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener() {
                    public boolean onMenuItemClick(MenuItem item) {
                        if (item.getTitle().toString().equals("Copy Link")) {
                            String url = row.getItemLink();
                            int sdk = android.os.Build.VERSION.SDK_INT;
                            if (sdk < android.os.Build.VERSION_CODES.HONEYCOMB) {
                                android.content.ClipboardManager clipboard = (android.content.ClipboardManager) context.getSystemService(Context.CLIPBOARD_SERVICE);
                                android.content.ClipData clip = android.content.ClipData.newPlainText("Drop", url);
                                clipboard.setPrimaryClip(clip);
                            } else {
                                android.content.ClipboardManager clipboard = (android.content.ClipboardManager) context.getSystemService(Context.CLIPBOARD_SERVICE);
                                android.content.ClipData clip = android.content.ClipData.newPlainText("Drop", url);
                                clipboard.setPrimaryClip(clip);
                                System.out.println("Link copied to clipboard!");
                                final Handler handler = new Handler();
                                final AlertDialog.Builder builder = new AlertDialog.Builder(context);
                                builder.setMessage("Link copied to clipboard!");
                                final AlertDialog dialog = builder.create();
                                dialog.show();
                                handler.postDelayed(new Runnable() {
                                    public void run() {
                                        dialog.dismiss();
                                    }
                                }, 3000); // Dismiss in 3 Seconds
                            }
                        } else if (item.getTitle().toString().equals("Share Via")) {
                            String url = row.getItemLink();
                            Intent sharingIntent = new Intent(android.content.Intent.ACTION_SEND);
                            sharingIntent.setType("text/plain");
                            sharingIntent.putExtra(android.content.Intent.EXTRA_SUBJECT, "Shared from Droplr for Android");
                            sharingIntent.putExtra(android.content.Intent.EXTRA_TEXT, url);
                            context.startActivity(Intent.createChooser(sharingIntent, "Share via"));
                        }
                        return true;
                    }
                });
                popup.show();//showing popup menu
            }
        });
        holder.layout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(context, FullScreenActivity.class);
                intent.putExtra("Image", row.getImgId());
                intent.putExtra("Title", row.getItemName());
                intent.putExtra("Url", row.getItemLink());
                intent.putExtra("Type", row.getImgType());
                context.startActivity(intent);
            }
        });
    }

@Override
    public int getItemCount() {
        return rows.size();
    }

    class MyViewHolder extends RecyclerView.ViewHolder {
        @BindView(R.id.titleView)TextView txtTitle;
        @BindView(R.id.icon)ImageView imageView;
        @BindView(R.id.dateView)TextView dateTitle;
        @BindView(R.id.copy)ImageButton copyButton;
        @BindView(R.id.linearLayout)LinearLayout layout;

        MyViewHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(this,itemView);
        }
    }
}
```
`

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal"
    android:weightSum="1"
    android:baselineAligned="false"
    android:id="@+id/linearLayout">

 <ImageView
     android:id="@+id/icon"
     android:layout_width="90dp"
     android:layout_height="90dp"
     android:padding="5dp"
     android:contentDescription="@string/imageview" />

 <LinearLayout
     android:layout_width="200dp"
     android:layout_height="90dp"
     android:layout_weight="0.77"
     android:orientation="vertical"
     android:weightSum="1">

  <TextView
      android:id="@+id/titleView"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_marginStart="10dp"
      android:layout_marginTop="15dp"
      android:text="@string/titleView" />

  <TextView
      android:id="@+id/dateView"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_marginStart="10dp"
      android:layout_marginTop="5dp"
      android:text="@string/dateView" />
 </LinearLayout>

 <LinearLayout
     android:layout_width="wrap_content"
     android:layout_height="wrap_content"
     android:layout_marginEnd="10dp"
     android:layout_marginTop="20dp"
     android:orientation="vertical">

  <ImageButton
      android:id="@+id/copy"
      style="@style/Widget.AppCompat.Button.Borderless"
      android:layout_width="18dp"
      android:layout_height="42dp"
      android:contentDescription=""
      android:scaleType="centerCrop"
      app:srcCompat="@drawable/more" />
 </LinearLayout>
</LinearLayout>`

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

Screen recording: http://d.pr/v/ozeFqO

**Comment by sjudd** [comment]
I don't have any great ideas. Is the latency network latency, or do you not see any network traffic running when this issue occurs? What networking library are you using and have you tried using a different one?

Support for Glide 3.x is winding down, though I doubt that updating to Glide v4 will help you much here.

**Comment by clfristoe** [comment]
It turns out it was an issue with the API I was using, not Glide. The link was expiring, so no image was appearing. Thanks for getting back to me!
