### ISSUE TITLE
How to add authentication headers to a request?

### ISSUE THREAD

**Issue by ScottPierce** [bumptech/glide#2238]
**Glide Version**: 4.0.0
**Integration libraries**: okhttp3-4.0.0

The annotation processor is confusing me with Glide 4. I'm not understanding based on the documentation how I should handle providing authentication request headers for the images I'm trying to download. Right now, as far as I can reason, I should include the OkHttp3 integration library, and then manually apply the `registry.replace(GlideUrl.class`, while disabling manifest parsing and excluding the `OkHttpLibraryGlideModule`. This way I can provide my own `OkHttpClient`, and provide an interceptor to that. Can you confirm this is the best approach?

```Java
@GlideModule
@Excludes(OkHttpLibraryGlideModule.class)
public class MyAppGlideModule extends AppGlideModule {
  @Override public boolean isManifestParsingEnabled() {
    return false;
  }

  @Override public void registerComponents(Context context, Glide glide, Registry registry) {
    registry.register(SVG.class, PictureDrawable.class, new SvgDrawableTranscoder())
        .append(InputStream.class, SVG.class, new SvgDecoder());

    OkHttpClient client = new OkHttpClient.Builder()
        .addInterceptor(/* TODO */)
        .build();
    registry.replace(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(client));
  }
}
```

**Comment by sjudd** [comment]
Yeah that looks reasonable.

**Comment by ScottPierce** [comment]
Thanks for confirming!
