### ISSUE TITLE
How to use glide for big video file?

### ISSUE THREAD

**Issue by mengtrue** [bumptech/glide#2240]
**Glide Version**: glide:4.0.0-RC0
**Integration libraries**: None
**Device/Android Version**: Android 7.1
**Issue details / Repro steps / Use case background**: 
There is big video (mp4) file, over 2.2G, I use glide to get thumbnail, it cause exception.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
compile 'com.github.bumptech.glide:glide:4.0.0-RC0'
I do not use GlideModule
Bitmap thumbnail = null;
      thumbnail =
          Glide.with(context)
              .asBitmap()
              .apply(
                  new RequestOptions()
                      .override(request.getWidth(), request.getHeight())
                      .centerCrop())
              .load(filePath)
              .submit(request.getWidth(), request.getHeight())
              .get();

**Stack trace / LogCat**:

08-12 18:53:27.629  2438  4317 E GlideExecutor: java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:850)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at com.bumptech.glide.util.ByteBufferUtil.fromFile(ByteBufferUtil.java:31)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:59)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:245)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at java.lang.Thread.run(Thread.java:761)
08-12 18:53:27.629  2438  4317 E GlideExecutor: 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)

**Comment by sjudd** [comment]
Can you reproduce this on multiple devices or versions of Android? Or only one particular device/version of Android?

The code in our control uses longs for file size, it looks there's some internal cast from long to int in the framework code.

**Comment by sjudd** [comment]
And I'm wrong: https://developer.android.com/reference/java/nio/channels/FileChannel.html#map(java.nio.channels.FileChannel.MapMode, long, long).
