### ISSUE TITLE
Question: Does promoting existing LOW priority requests to HIGH by making a new request works the way I think it does?

### ISSUE THREAD

**Issue by PSP-MarkoG** [bumptech/glide#2241]
So here's a thing, I have a RecyclerView with grid of images, I'm using a preloader from the RV integration lib, and the way I've configured it at the moment is to set LOW priority for "preload requests", but when that same image is requested in "onBind" method, I create a request for it with for example NORMAL priority.

My question is does Glide properly "promote" the priority for the potentially existing unfinished request for the same given resource, or I might potentially be doing a bad thing by creating 2 requests for the same resource with different priorities?

For all the requests mentioned I also have thumbnail requests with their own differentiating priorities.

Thank you!

**Comment by sjudd** [comment]
We don't currently promote priorities, which means that all identical requests inherit the priority of whatever the original request was. In your case, probably most of your requests are ending up with the LOW priority.

In Photos we use the same priority when preloading as we do in onBindView.
