### ISSUE TITLE
Glide 4.1 side effect of ignore identical request.

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#2245]
**Glide Version**:
4.1

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

@sjudd 
It seems https://github.com/bumptech/glide/commit/9d10097e7bd298cc5b393364663fa0cf08711e8e does not take in account the fact that a request is completed. So restarting a request that is completed will actually do nothing.

Maybe this is on purpose but this implies a side effect of preventing a force reload when needed and does not trigger any listener.

For example in my case when doing transition my fetcher only load the image from cache to avoid slowing down the transition. Then after the transition start a full download by restarting the glide query. (I'm pretty sure it would be the same for any app that would for example restart the requests after network is connected when first one occurred without network).

With 3 and 4.0 it works correctly, but with 4.1 the subsequent query is not restarted preventing the actual load to happens and do not trigger any listener to warn the application.

Cheating with different models could work, but then when the image is actually already cached it would trigger a real reload and not a memory hit cache as Glide think it's different items.

I understand the purpose of the optimization but impact are not neutral if the completed state is not taken in account.

Maybe by default if state is completed then the request should restart, and an option to always prevent restart provided. Or add an option to force the reload. Or a new Listener event so app can cheat (But for this one impact may be huge on API clients).

Can PR something but need your choice and target. (And maybe an hint for the detection of completed state)

Default should maybe work like actual, or maybe add something in the documentation, as the total ignore of the request may trouble clients to actually understand what is happening.

**Comment by Tolriq** [comment]
Actually the side effect is even bigger.

In a recyclerview adapter I do rely on a error listener to change the view (Typically set a label to be visible in case the image fails to load).

With this change since the request is no more restarted, the listener is not called when rebinding the view holder, leading to no callback called, and wrong display.

**Comment by sjudd** [comment]
I think I understand the use case in your first comment (you expect the Target or RequestListener to be called whenever you start a new request). That can be solved by just calling ``Glide.with(context).clear(Target)`` before you start your new request to mimic the old behavior.

I'm not sure I understand the error listener bit. Can you maybe provide some psuedo code that explains what you're doing there?

I'm considering my options here. On the one hand restarting a completed request is generally wasteful, especially for rebinds in scrolling views when users are just loading images into ImageViews. On the other, it's definitely weird that your request is silently ignored.

**Comment by Tolriq** [comment]
Calling a clear each time even when not needed does not sound perfect :( More line of code to maintain and easy to forget.  

Specially for the basic use case: RecyclerView with no Internet, all is called and error images are displayed. Internet is back, dev call notifyDataSetChanged() and nothing happens images are still not loaded despite they now could and should.
Reading the code, it seems you now offer an automatic handling of not trying to download when not connected, and it does not seems to be taken in account even if integrated so worse for any custom solutions by devs. This means that calling clear would now nearly be mandatory, and makes the possible gain of your PR useless :(

Since thanks to new very cool Glide 4 API I can now build a proper wrapper without all previous complexity to handle, it's less of an issue for me but may not be an easy solution for all users.

For the error listener, often I need to alter the display when image does not load, for example displaying a title over the error image to help user understand what they see as in a grid view that should only display posters, a full grid of error images when no Internet is not really useful.

For example with WIP code in onBindViewHolder
```java
        holder.title.setVisibility(View.GONE);
        DisplayHelper.setNullBackground(holder.thumbnail);
        ImageRequestBuilder.newBuilder(fragment)
                .dontTransform(true)
                .animate(new FadeSaturateAnimation())
                .load(holder.thumbnailBuffer)
                .build()
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object o, Target<Drawable> target, boolean b) {
                        DisplayHelper.setImageViewEmptyBackground(holder.thumbnail);
                        holder.title.setVisibility(View.VISIBLE);
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Drawable drawable, Object o, Target<Drawable> target, DataSource dataSource, boolean b) {
                        return false;
                    }
                }).into(holder.thumbnail);
```

This works on first call, the onLoadFailed is properly called, but when you scroll and return to previous position, it's no more called so wrong content is displayed.

This makes quite a few use case, where restart is actually needed, because there's many external factor to handle. IMO it's not as simple as request is the same, it should more be result will be the same taking in account external factors like internet connection and many other things.
Sounds quite hard to properly implements without missing use cases, that why allowing restart when completed seems easier to keep compatibility while still allowing gain in some cases. (Typically a restart with memory cache is not really impacting, as the image should still be in cache as still used).

**Comment by Tolriq** [comment]
As supposed, calling Clear, triggers back the flickering of https://github.com/bumptech/glide/issues/2194

See attached video as it's quite strange in my case that always the images that are not 100% displayed are reloaded.
[glide.zip](https://github.com/bumptech/glide/files/1222969/glide.zip)
(Posting here but maybe could / should be posted on the other issue too)

Fixing this issue would get back the other issue, but not sure what is worse.

**Comment by sjudd** [comment]
Calling clear() each time is exactly what the old logic did for you, so it's not inefficient. It's definitely a bit less convenient, but it may be reasonable if it's only a minority of the time that you add listeners like this. 

The automatic retry logic is not affected by my change. My change only ignores duplicate requests that are started with ``into()`` or any of the other methods on ``RequestBuilder``. Retries for connectivity or lifecycle reasons are managed with the ``Request`` directly using ``RequestTracker`` and are unaffected. 

We should definitely allow restarts with failed requests, that's a great point. It's a little tricky to keep track of the thumbnail though and figure out what to do with requests that have completed.

**Comment by sjudd** [comment]
Yeah it's not super surprising that clear() triggers the flickering. Part of the point here was to avoid the confusion of how you handle a View in an invalid state (ie pending layout). We can wait for the layout to complete and make sure we load an image with the right size. Or we can just load the image with the current view size which may be incorrect now that the view is re-used for a new position. It's hard to find an intermediate solution.

**Comment by Tolriq** [comment]
For my use case 90% of the calls have listeners as I do use complex views and configurable views by the user, or use listeners to start transitions 

I can, as temporary solution, call clear each time in my wrapper so less an issue but definitively a major change from 4.0 and 3.X that will impact peoples relying on listeners, use datafetchers that handle internet state outside of your code, and many other cases. Definitively needs proper documentation and bold in changelog :) ( And if left like that, maybe think about adding an onIgnored in interface RequestListener)

Furthermore I'm currently not fully confident of possible side effect of calling clear on something that is actually still used, as the doc http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/RequestManager.html clearly says it will free the resources, maybe clearing memory cache or disk cache when it will be needed 10 ms later.

For the flickering issue, it's impacting and not cool but way less this one without calling clear. But we can discuss the flickering on the other issue if you need more details / logs or anything.

**Comment by sjudd** [comment]
> And last use case, is transitions, request have a special flag in the model to prevent returning image if not in cache to not slow down the transition, and then restart the request when transition is ended to ensure image loading after. This is also broken. (I could unbroke it by taking in account that flag in the model hashCode / equals but then Glide thinks it's different images and does not use memory cache for the second query .....).

Can you clarify what you mean here? What flag are you referring to? 

>Furthermore I'm currently not fully confident of possible side effect of calling clear on something that is actually still used, as the doc http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/RequestManager.html clearly says it will free the resources, maybe clearing memory cache or disk cache when it will be needed 10 ms later.

If you call ``into()`` on a Target, the previous request is cleared. It's exactly equivalent to calling ``clear()`` and then ``into()``: https://github.com/bumptech/glide/blob/8fac1236423cec5f46bff2d904a0803070a14c4b/library/src/main/java/com/bumptech/glide/RequestBuilder.java#L367. Prior to my change we would always have called ``clear()`` when you called ``into()`` even if the requests were identical.

**Comment by Tolriq** [comment]
Here's an extract of my model.

The model pass specific data to the fetcher to ensure proper handling. Typically a cache key, as multiple different images sources can point to the same image, the onlyCached flag to prevent the fetcher to download the image if the host is down (or not connected to correct network or SSID) and keepTransparency to have it's cache in png and not jpg.

Those are the more relevant part for this case.

The problem is with the onlyCachedKey. Previously in glide 3 only the Id generated from the model was used and everything was simple. Now you also equals the model, this require proper implementation of hashCode/Equals in model.

1) This means that my current default implementation does not work efficiently as different urls but same cachekey should return identical objects. (Simple solution is to equals/hashCode on the diskCacheKey but this have the side effect of next point).
2) This means that to have 2 request identical that use Glide memory/diskCache I must not take in account the hashCode/Equals fields that do no impact the final result.
This allows the exact same request with the same model but different onlyCached values to use the same memoryCache/diskCache from Glide (mandatory for transitions, as if not using memory cache Glide transition is applied and this triggers flickering and looks horrible).
Typically needed for smooth transitions. First call with onlyCached set to true to avoid download before the transition start. Then a new call with onlyCached to false, to either refresh with same image from memory cache, or do the actual download. It's not UI job to actually do different things depending on states it does not manage.
The problem with that is that with your PR, the request are actually seen as the same (wanted for memory cache reuse) and as such is not called again and do not download the image.

So will need me to call clear() as for all requests :( (Thanks for details about it)

I guess this kind of thing will be used by a few devs that push optimization a little to handle network states or things like that.
The listener case for success / error handling also :( (But for this one I guess maybe the recycle just have to call the listeners or something like that).


```java
public class ImageRequest implements Key {

    public String url;
    public String cacheKey;
    public boolean onlyCached = false;
    public boolean keepTransparency = false;

    @Override
    public void updateDiskCacheKey(MessageDigest messageDigest) {
        messageDigest.update(getCacheKeyBytes());
    }

    private byte[] getCacheKeyBytes() {
        return GlideUtils.getImageRequestId(this).getBytes(CHARSET);
    }

    @Override
    public String toString() {
        return "ImageRequest{" +
                "url='" + url + '\'' +
                ", onlyCached=" + onlyCached +
                ", keepTransparency=" + keepTransparency +
                ", cacheKey=" + cacheKey +
                '}';
    }

    @SuppressWarnings("SimplifiableIfStatement")
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ImageRequest that = (ImageRequest) o;

        if (keepTransparency != that.keepTransparency) return false;
        if (url != null ? !url.equals(that.url) : that.url != null) return false;
        return cacheKey != null ? cacheKey.equals(that.cacheKey) : that.cacheKey == null;
    }

    @Override
    public int hashCode() {
        int result = url != null ? url.hashCode() : 0;
        result = 31 * result + (cacheKey != null ? cacheKey.hashCode() : 0);
        result = 31 * result + (keepTransparency ? 1 : 0);
        return result;
    }
}
```

**Comment by sjudd** [comment]
Thanks for the details. I'm still considering making some changes here, I just want to make sure I understand the use case first.

**Comment by Tolriq** [comment]
Thanks for considering, I've finished my internal migration to Glide 4 and everything works with a way better code on my side :) Thanks again for all the work on that version.
I've tested to always call Clear and have not found side effect except the flickering getting back.
The flickering is currently a quite important issue for me to migrate in production, do you have time / insight on what can be done as a workaround before finding a global solution? (Maybe continue discussion on the other thread?)

**Comment by sjudd** [comment]
https://github.com/bumptech/glide/pull/2261 Might be a solution to allow you to avoid clear.

**Comment by Tolriq** [comment]
@sjudd yes just saw that and wanted to make a quick test, but Jitpack bugs on it :(

https://jitpack.io/com/github/sjudd/glide/restart_failed_and_call_listeners-v4.0.0-g7def8af-22/build.log

And until gif support is moved to sub library it's quite painful to switch from maven to local distribution to add all necessary aars / jars.

Do you have any idea about the issue? I hope it's trivial, or I'll do proper tests with local builds probably only on Monday now :(

**Comment by Tolriq** [comment]
@sjudd Ho and to avoid opening an other issue it seems it's not possible to setLog to higher than Error.

So no way to disable some logs in release mode, like 
```
E/Glide: class com.bumptech.glide.load.engine.GlideException: Received null model
E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

That in some cases are perfectly normal (user supplied ressources, no need to do a precheck for existence as Glide does it already, simplifies code).
Did I miss something ?

Strange related thing searching again before pressing comment:
```Java
      // Only log at more verbose log levels if the user has set a fallback drawable, because
      // fallback Drawables indicate the user expects null models occasionally.
      int logLevel = getFallbackDrawable() == null ? Log.WARN : Log.DEBUG;
      onLoadFailed(new GlideException("Received null model"), logLevel);
```
Yet the errors are at Error level in logcat. (And I use listeners to handle errors not fallback drawable but not important).

**Comment by sjudd** [comment]
Opening new issues is better for things that are unrelated: #2266.

For the pull request I'll just go ahead and submit for now. I think it's a reasonable solution. If there are bugs we can submit more fixes.

**Comment by Tolriq** [comment]
Okay thanks, and no problem to open new, just that with Glide 4 I see you are overwhelmed by issues so tried to be gentle :)

**Comment by Tolriq** [comment]
@sjudd Actually it's does some really weird things now :( (No clear calling)

See attached video, it seems to be random on what it does. But at least when it fails the error callback is called.

[glide-2.zip](https://github.com/bumptech/glide/files/1234946/glide-2.zip)
