### ISSUE TITLE
Glide 3.7.0 cannot load local image for i18n

### ISSUE THREAD

**Issue by rexih** [bumptech/glide#2246]
when i load an image in drawable folder ,I use:

Glide
                .with(this)
                .load(R.drawable.text_new_version)
                .into(iv_test);

text_new_version has two image for different region, the default one in drawable-xxhdpi and an English version in drawable-en-xxhdpi

when my context is in English, Glide still load the default one ,not the English version.at the same place i change the code to use imageView.setImageResource(resId); it show the English version

**Comment by sjudd** [comment]
The logic to convert a resource id into a Uri happens here: https://github.com/bumptech/glide/blob/7e1548bb2d6473790b09d72756de12c64841ef50/library/src/main/java/com/bumptech/glide/load/model/ResourceLoader.java#L38. 

If you can find a way to change that so it accounts for languages, let me know or send a pull request and we can fix this.

**Comment by sjudd** [comment]
I haven't figured out a way to do this, it might require hidden APIs?

If anyone knows how Glide could do this programmatically, let me know.
