### ISSUE TITLE
Seeking advice on preserving aspect ratio when caching center-cropped thumbnail

### ISSUE THREAD

**Issue by sheamartinson** [bumptech/glide#2248]
**Glide Version**: 4.0.0

**Integration libraries**: OkHttp

**Issue details / Repro steps / Use case background**: 
I am using shared element transitions on a thumbnail which, when clicked, brings the user to a fullscreen view of that image. The local image files are often very large and take a long time to load, so I have used a resource caching strategy in order to recycle the thumbnail image when fullscreen is entered.

The problem is that the gallery view (containing potentially thousands of thumbnails) contains images which are center cropped into a perfect square. In order to recycle the resource cache of the image, I have to override the thumbnail size with the size of the square in the gallery view. This means that when I use shared element transitions the thumbnail and the fullsize image in most cases have different aspect ratios, which leads to an awkward jittery resize when the full size element is loaded after the "override" thumbnail into a fitCenter view.

I suspect that the most ideal thing for this use case would be to cache a smaller version of the fullsized image with the aspect ratio preserved instead of just caching the visible area of the square in the gallery layout. Since we don't actually have full control over Glide's caching mechanism, I wonder then what I can do to achieve a smooth transition between two aspect ratios.

**Comment by Tolriq** [comment]
Usually you just need to use dontTransform() + proper transition set

```xml

<?xml version="1.0" encoding="utf-8"?>
<transitionSet xmlns:android="http://schemas.android.com/apk/res/android"
               android:duration="300"
               android:interpolator="@android:interpolator/linear_out_slow_in">
    <changeBounds>
        <arcMotion/>
    </changeBounds>
    <changeTransform/>
    <changeClipBounds/>
</transitionSet>

```
