### ISSUE TITLE
Need help in adjusting the caching behavior to always try to get and use an updated image before using the cache

### ISSUE THREAD

**Issue by dcominottim** [bumptech/glide#2249]
**Glide Version:** 4.0

**Integration libraries:** OkHttp3

**Issue details / Repro steps / Use case background:** I am trying to implement the following load/cache behavior:

1. Always try to GET an image from an URL (which never changes, although the image changes), performing an actual HTTP request;
2. If the call succeeds, load the returned image and cache it; otherwise, load the cached version if there is any.

**Comment by sjudd** [comment]
You can write your own [DiskCacheStrategy](https://github.com/bumptech/glide/blob/49142cf1d9cd81bf2347e8dc9c7350a43447b114/library/src/main/java/com/bumptech/glide/load/engine/DiskCacheStrategy.java#L9) and have it return false from ``decodeCachedData`` and ``decodeCachedResource``. That will always do an HTTP request and cache the result, but will ignore cached data. That takes care of 1.

2 I think you will need to do a second request. You can add a RequestListener that listens to ``onLoadFailed`` and starts a new request for the same url using [``onlyRetrieveFromCache``](http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/RequestOptions.html#onlyRetrieveFromCache-boolean-). That will load any previously cached image without making a new request.

I can't think of a way to do it all at once in a single request, but doing a second request if the first fails should be fairly reasonable.

As an alternative consider using HTTP caching and a networking library that supports it (OkHttp or Volley), along with either ``DiskCacheStrategy.NONE`` or disabling Glide's disk cache completely.
