### ISSUE TITLE
Placeholder not removed when crossfade transition is used

### ISSUE THREAD

**Issue by svenjacobs** [bumptech/glide#2251]
**Glide Version**: 4.0

**Device/Android Version**: Google Nexus 5X / Android 8.0

**Issue details / Repro steps / Use case background**: 

The following code

```kotlin
Glide.with(this)
        .load("http://www.fnordware.com/superpng/pngtest8rgba.png")
        .apply(RequestOptions.placeholderOf(R.drawable.placeholder))
        .transition(DrawableTransitionOptions.withCrossFade())
        .into(imageView)
```

will draw the loaded image **over** the placeholder image on first load (empty cache). The placeholder image can still be seen below. This only happens when the crossfade transition is used.

See the [demo application](https://github.com/svenjacobs/glide_4_0_placeholder_error) showcasing this issue. When pressing the "Load image" button for a second time the placeholder image is gone.

**Comment by svenjacobs** [comment]
This happens whether or not the `ImageView` has the placeholder image defined in the layout via `android:src`.

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/transitions.html#cross-fading-with-placeholders-and-transparent-images

**Comment by svenjacobs** [comment]
Thanks for pointing me to the appropriate documentation. This behavior is different than in Glide 3.x so maybe it should be mentioned in the migration guide? 😉

**Comment by keien411** [comment]
thanks

**Comment by saikat-bbil** [comment]
I used glide 4.8.0
& this issue happens to me.
any solution?

**Comment by CaptMustache** [comment]
Still open. Same here with glide 4.10.0

**Comment by rafael-labela** [comment]
And in 4.11.0, how comes this was even closed?

**Comment by YvgenTroshchiy** [comment]
glide  `4.15.1`  still exist

**Comment by Zhuxszzz** [comment]
It worked for me, thanks a lot!
