### ISSUE TITLE
How to get Thumbnail for over 2GB file

### ISSUE THREAD

**Issue by mengtrue** [bumptech/glide#2252]
Branching from #2240

**Glide Version**: Glide 4.0

Sometimes, I will use glide to get thumbnail for over 2GB file.
in Android source code, FileChannelImpl.java 
public MappedByteBuffer map(MapMode mode, long position, long size)
if (size > Integer.MAX_VALUE)
           throw new IllegalArgumentException("Size exceeds Integer.MAX_VALUE");

So once the file is over 2GB, it will throw exception, it will fail to get thumbnail.
Could you help me to check?

**Comment by sjudd** [comment]
You don't need to. ByteBuffers aren't necessary for decoding the video.
