### ISSUE TITLE
 java.lang.IllegalStateException: Had two simultaneous puts for:***

### ISSUE THREAD

**Issue by miguoer** [bumptech/glide#2258]
Hello, I use Glidev4 to load gif images. I have configed the MemoryCache and DiskLruCache. My DiskLruCache strategy is DiskCacheStrategy.ALL. 

Just now I got a uncaught throwable problem when I performed the following steps:
(1)Enter a activity and load gif images successfully.
(2)Put a lot of files into sdcard to make it full.
(3)Finish the activity and clear the memory cache.
(4)Re-enter into the activity to reload gif images.

After step-4, I got the exception:

```
08-17 18:11:15.520 E/GlideExecutor( 9964): Request threw uncaught throwable
08-17 18:11:15.520 E/GlideExecutor( 9964): java.lang.IllegalStateException: Had two simultaneous puts for: a6dfb76d2bbb45a76afdb365325b0d7cdf6d4376fa86c97035e3dc831ae4687b
08-17 18:11:15.520 E/GlideExecutor( 9964):     at com.bumptech.glide.c.b.b.e.a(DiskLruCacheWrapper.java:110)
08-17 18:11:15.520 E/GlideExecutor( 9964):     at com.bumptech.glide.c.b.w.a(SourceGenerator.java:1080)
08-17 18:11:15.520 E/GlideExecutor( 9964):     at com.bumptech.glide.c.b.f.i(DecodeJob.java:284)
08-17 18:11:15.520 E/GlideExecutor( 9964):     at com.bumptech.glide.c.b.f.run(DecodeJob.java:1254)
08-17 18:11:15.520 E/GlideExecutor( 9964):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-17 18:11:15.520 E/GlideExecutor( 9964):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-17 18:11:15.520 E/GlideExecutor( 9964):     at java.lang.Thread.run(Thread.java:841)
08-17 18:11:15.520 E/GlideExecutor( 9964):     at com.bumptech.glide.c.b.c.a$a$1.run(GlideExecutor.java:349)
```

Wish you could help me figure out this problem. Thank you.

**Comment by sjudd** [comment]
That implies there's a bug somewhere in the cache wrapper: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/cache/DiskLruCacheWrapper.java#L91.

We should be acquiring a single write lock before writing any data. If you can figure out what is going wrong there, let me know. I'd be happy to accept a pull request.

**Comment by sjudd** [comment]
Actually this came up randomly in an internal issue. 

This can happen when equals()/hashcode() in your model are based on different data than your disk cache key and you end up with two different models with different results from equals()/hashcode(), but exactly the same disk cache key.

Our locking needs to be based on disk cache key, not equals/hashcode. Or we need to handle simultaneous puts.

**Comment by sjudd** [comment]
Also it's weird to have your Model object have an equals()/hashcode() implementation that doesn't include the same data that you use for updateDiskCachekey. You can also probably fix this issue for your application by making sure that your Model's equals/hashcode and updateDiskCacheKey methods use the same set of data. You may need to split out a new class that contains only the data you need to pass in to Glide to make this work.

**Comment by sjudd** [comment]
That said, we've made this case safer in Glide here: 01f5a3d3dc0e78cc83b9e390b331a65dd5c1a9f3
