### ISSUE TITLE
Is it possible to use downloadOnly() asynchronously with a Target?

### ISSUE THREAD

**Issue by Saketme** [bumptech/glide#2259]
**Glide Version**: 4

**Integration libraries**: okhttp3

**Issue details / Repro steps / Use case background**: 
I'm trying to use Glide for downloading an image and getting a reference to the File directly, using:

```java
Glide.with(this).download(imageUrl).into(progressTarget);
```

I was wondering if it's possible to get run this code synchronously without losing the [progress target](https://gist.github.com/TWiStErRob/08d5807e396740e52c90)? I know that there's `into(int, int)` that returns a `FutureTarget`, but I am unable to figure out how to use it with my progress target.

Update: I just realized that this _may_ not be possible, but I'd like to hear more about this.

**Comment by sjudd** [comment]
You can either load into a target or into a FutureTarget (via submit). There's no way to combine them without writing your own target if that's what you're asking?
