### ISSUE TITLE
divide by zero

### ISSUE THREAD

**Issue by hdfywxn** [bumptech/glide#2260]
**Glide Version**: 3.3

**Integration libraries**:

**Device/Android Version**: Android 7.0

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
com.bumptech.glide.gifdecoder.GifDecoder.advance(GifDecoder.java:187)
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
                                    java.lang.ArithmeticException: divide by zero
                                   at com.bumptech.glide.gifdecoder.GifDecoder.advance(GifDecoder.java:187)```

**Comment by sjudd** [comment]
3.3 is quite old, can you reproduce on Glide 4? or at least Glide 3.8?

**Comment by hdfywxn** [comment]
what is the version of the master branch

**Comment by sjudd** [comment]
4.1 snapshot.
