### ISSUE TITLE
Why the avart will automatically rotate

### ISSUE THREAD

**Issue by fg2q1q3q** [bumptech/glide#2263]
hello，My picture address is  "http://211.138.31.211:8088/webOffice/?furl=http://portalui.ha.cmcc:9080/AddressBook/uploadedImg/zhuke.jpg".
It's normal in the browser (vertical), but after the use of Glide will become a rotating (horizontal), how to deal with it

**Comment by sjudd** [comment]
It looks like the image is rotated incorrectly in chrome, so I assume it will be rotated incorrectly in Glide. You can use exiftool to check the orientation.

If that doesn't work please re-open and make sure to fill out the issue template.
