### ISSUE TITLE
Null model ignores Log level

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#2266]
From @Tolriq: It's not possible to setLog to higher than Error.

So no way to disable some logs in release mode, like 
```
E/Glide: class com.bumptech.glide.load.engine.GlideException: Received null model
E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

That in some cases are perfectly normal (user supplied ressources, no need to do a precheck for existence as Glide does it already, simplifies code).
Did I miss something ?

Strange related thing searching again before pressing comment:
```Java
      // Only log at more verbose log levels if the user has set a fallback drawable, because
      // fallback Drawables indicate the user expects null models occasionally.
      int logLevel = getFallbackDrawable() == null ? Log.WARN : Log.DEBUG;
      onLoadFailed(new GlideException("Received null model"), logLevel);
```
Yet the errors are at Error level in logcat. (And I use listeners to handle errors not fallback drawable but not important).

**Comment by sjudd** [comment]
There's a duplicate error logged, which I'll fix. However if I set the log level to ERROR in a GlideModule, I don't see any error logged for null models (or other kinds of request failures). 

Let me know if I'm missing something.

**Comment by Tolriq** [comment]
Hum your right, I forget that switched back to debug mode when testing the clear and was perturbed to see the errors in red :(

Sorry for the noise but since it triggered a little fix it was not for nothing :)
