### ISSUE TITLE
dontTransform() follow up #2194

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#2267]
This is a follow up to https://github.com/bumptech/glide/issues/2194#issuecomment-323384083 where you say dontTransform is no more needed in glide 4.

Please see attached videos showing the differences with dontTransform (3) and without (4)
Look at the jump in the big fanart it's the easiest part to see it.

The calls are basic GlideApp withFragment a transition a listener into an ImageView.

This was the same impacts on Glide 3. No real idea about why it does that.

**Comment by Tolriq** [comment]
Actually adding the videos :)
[Temp.zip](https://github.com/bumptech/glide/files/1235273/Temp.zip)

**Comment by sjudd** [comment]
misspoke, dontTransition is no longer required, dontTransform is if you want to eliminate transformations based on the View's scale type.
