### ISSUE TITLE
How to detect when a picture is finished loading (onLoad or onComplete)

### ISSUE THREAD

**Issue by ryandailey100** [bumptech/glide#2268]
Is there a way to run code when the picture is finished loading? Please help. Thanks

**Comment by sjudd** [comment]
For Glide v4:
http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/target/Target.html#onResourceReady-R-com.bumptech.glide.request.transition.Transition-
or
http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/RequestListener.html#onResourceReady-R-java.lang.Object-com.bumptech.glide.request.target.Target-com.bumptech.glide.load.DataSource-boolean-

In the future please fill out the issue template when you file an issue so we can link you to the appropriate information!

**Comment by ryandailey100** [comment]
Can you please provide an example? I can not get it to work. Thanks

**Comment by sjudd** [comment]
Looks like a duplicate of #2278.
