### ISSUE TITLE
Play multiple Gifs in single imageview container as a video

### ISSUE THREAD

**Issue by csmuthukuda** [bumptech/glide#2273]
I need to do the task mentioned in the tile by using glide.can some one suggest an efficient way of achieving this..

**Comment by sjudd** [comment]
You can load multiple gifs into multiple ``ImageView``s and you can stack multiple ``ImageView``s inside another container (FrameLayout, LinearLayout etc), but you can't load multiple Gifs into a single ``ImageView``.

If that doesn't answer your question, please re-open and fill out the issue template.
