### ISSUE TITLE
Cant get onResourceReady to work

### ISSUE THREAD

**Issue by ryandailey100** [bumptech/glide#2274]
I am not sure what parameters to pass into onResourceReady in order to get a block of code to run. Can someone please send me an example code for this? Kotlin would be preferred. Thanks.

**Comment by Nenco1993** [comment]
check out this tutorial:
https://futurestud.io/tutorials/glide-callbacks-simpletarget-and-viewtarget-for-custom-view-classes

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/getting-started.html as well.

**Comment by ryandailey100** [comment]
I cannot get this to work. I can't find .asBitmap(), which is needed to get it working.
