### ISSUE TITLE
OutOfMemoryError in new version (4.0.0)

### ISSUE THREAD

**Issue by SIARAY** [bumptech/glide#2275]
My app encountered OutOfMemoryError  , When I updated the library to 4.0.0 version.
It seems that in this version the library will occupy more memory.

My app crashed after scroll recyclerview for several minutes and show this error.
> java.lang.OutOfMemoryError: Failed to allocate a 36876 byte allocation with 35152 free bytes and 34KB until OOM
> 

My code:
        
    RequestOptions options = new RequestOptions();
    options.diskCacheStrategy(GLIDE_DISK_CACHE_STRATEGY);      
    options.dontAnimate();   
    RequestBuilder glide = Glide.with(context)
                        .load(imageLink)
                        .apply(options);
    glide.into(imageView);

I compared the previous version (3.8.0) with the current version (4.0.0), there is a big difference in the occupied memory.

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors.

If you think something is broken in v4, please re-open with more detail about what specifically you thin has changed.

**Comment by SIARAY** [comment]
Please compare the below screenshots.
Images are taken in almost identical conditions.

[Glide V4.0.0](http://i.imgur.com/5SixfBT.jpg)

[Glide V3.8.0](http://i.imgur.com/MNbHTH2.jpg)

[Picasso](http://i.imgur.com/AsqoYg1.jpg)

The code for loading the image in different versions has not changed.
I think that the memory occupied by the library is much larger than before.
