### ISSUE TITLE
Gif not loading  - skia: --- codec->getAndroidPixels() failed

### ISSUE THREAD

**Issue by rishabh876** [bumptech/glide#2282]
**Glide Version: 3.7.0**
**Integration libraries:** N/A
**Device/Android Version:** Nexus 6 (happening on all devices though)
**Issue details / Repro steps / Use case background:**

I am trying load images/GIF from url. All images are showing up fine. Even GIFs were showing up just fine but suddenly they stopped working. I am unable to understand what has changed in our code as I realised it few days after this started happening. 
Note: We have also recently increased our target API to 25.

**Glide load line:**
```
Glide.with(context)
                     .load(CloudinaryApi.getInstance().getUrl(mediaScaledWidth, 0, photo.getCloudinaryMedia()))
                     .placeholder(gradientDrawable)
                     .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                     .error(gradientDrawable)
                     .override(mediaScaledWidth, mediaScaledHeight)
                     .into(mediaView);
```

**Layout XML:**
```
<com.justunfollow.android.widget.RoundedImageView
                android:id="@+id/media_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:adjustViewBounds="true"
                android:scaleType="centerCrop"/>
```

**LogCat:**

> V/GenericRequest: Got onSizeReady in 0.08520799999999999 this: 225983059
> V/GenericRequest: finished setup for calling load in 3.6223959999999997 this: 225983059
> V/Engine: Started new load in 0.388073ms, key: EngineKey{http://res.cloudinary.com/crowdfire-test/image/fetch/f_webp,q_auto:good,w_500/https://firebot-media.crowdfireapp.com/images/admin_1487847173908.gif+com.bumptech.glide.signature.EmptySignature@9cbfc52+[964x535]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
> V/GenericRequest: finished onSizeReady in 5.831198 this: 225983059
> V/GenericRequest: finished run method in 6.0133339999999995 this: 225983059
> V/DecodeJob: Decoded source from cache in 1.163854, key: EngineKey{http://res.cloudinary.com/crowdfire-test/image/fetch/f_webp,q_auto:good,w_500/https://firebot-media.crowdfireapp.com/images/admin_1487847173908.gif+com.bumptech.glide.signature.EmptySignature@9cbfc52+[964x535]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
> V/DecodeJob: Transformed resource from source in 0.053958, key: EngineKey{http://res.cloudinary.com/crowdfire-test/image/fetch/f_webp,q_auto:good,w_500/https://firebot-media.crowdfireapp.com/images/admin_1487847173908.gif+com.bumptech.glide.signature.EmptySignature@9cbfc52+[964x535]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
> V/DecodeJob: Transcoded transformed from source in 0.040312, key: EngineKey{http://res.cloudinary.com/crowdfire-test/image/fetch/f_webp,q_auto:good,w_500/https://firebot-media.crowdfireapp.com/images/admin_1487847173908.gif+com.bumptech.glide.signature.EmptySignature@9cbfc52+[964x535]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
> V/DecodeJob: Fetched data in 186.799914, key: EngineKey{http://res.cloudinary.com/crowdfire-test/image/fetch/f_webp,q_auto:good,w_500/https://firebot-media.crowdfireapp.com/images/admin_1487847173908.gif+com.bumptech.glide.signature.EmptySignature@9cbfc52+[964x535]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
> V/DecodeJob: Wrote source to cache in 175.136111, key: EngineKey{http://res.cloudinary.com/crowdfire-test/image/fetch/f_webp,q_auto:good,w_500/https://firebot-media.crowdfireapp.com/images/admin_1487847173908.gif+com.bumptech.glide.signature.EmptySignature@9cbfc52+[964x535]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
> D/skia: --- codec->getAndroidPixels() failed.
> V/DecodeJob: Transformed resource from source in 0.045676999999999995, key: EngineKey{http://res.cloudinary.com/crowdfire-test/image/fetch/f_webp,q_auto:good,w_500/https://firebot-media.crowdfireapp.com/images/admin_1487847173908.gif+com.bumptech.glide.signature.EmptySignature@9cbfc52+[964x535]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
> V/DecodeJob: Transcoded transformed from source in 0.032084, key: EngineKey{http://res.cloudinary.com/crowdfire-test/image/fetch/f_webp,q_auto:good,w_500/https://firebot-media.crowdfireapp.com/images/admin_1487847173908.gif+com.bumptech.glide.signature.EmptySignature@9cbfc52+[964x535]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
> D/GenericRequest: load failed

If you look closely in the logs. You will see skia: --- codec->getAndroidPixels() failed.
This is the closest thing I could find that might has caused this.

**Comment by sjudd** [comment]
The skia decode failure is weird, it means that Android's decoder is failing to decode a single frame version of the GIF. It also means that Glide's GifDecoder is failing to decode the animated version of the Gif since Glide's GifDecoder is attempted before Android's BitmpaFactory.

Are you sure the images you're downloading are valid? Did a change on your backend maybe change the image format you receive to something like animated webp?

Glide 3.7 hasn't changed in a long time. If your code hasn't changed, I'd suspect maybe a change in your backend or the request parameters it uses or requires.

**Comment by rishabh876** [comment]
Ok found the issue. Cloudinary was giving a webp format image. Which was failing to decode. Although I don't understand why this started failing now. May be Android decoder was working earlier but in API 25 it started giving errors.

**Comment by LeonScroggins** [comment]
Can you attach the image that fails? Or is it all images? Is it possible that Cloudinary changed to give webp instead of gif? Android's decoder has a bug decoding certain webp files. (See https://bugs.chromium.org/p/webp/issues/detail?id=332)

**Comment by rishabh876** [comment]
Cloudinary was always giving me webp. It only started failing in API 25. Also it fails for all GIFs, images are fine. One of the image url is 
http://res.cloudinary.com/crowdfire-test/image/fetch/f_webp,q_auto:good,w_500/https://firebot-media.crowdfireapp.com/images/admin_1487847173908.gif

**Comment by LeonScroggins** [comment]
In Android N, BitmapFactory fails to decode WEBP images that have animation. (I haven't checked earlier versions, but I would guess that they would be the same.)

The gif you just linked to has a ".gif" extension, but the file itself is an animated WEBP, so I would expect it to fail.
