### ISSUE TITLE
Where did using() go in 4.0?

### ISSUE THREAD

**Issue by leftcoding** [bumptech/glide#2283]
int 3+,i can use  using 
Glide.with(context).using(....)
int 4.0 ,i use now ,but i don't know how to get cache. I just want to know if there is caching, i just want to use caching

thanks.for help!

**Comment by TWiStErRob** [comment]
http://bumptech.github.io/glide/doc/migrating.html#using-modelloader-streammodelloader

**Comment by leftcoding** [comment]
thanks
