### ISSUE TITLE
Placeholder,error is missing in 4.0.0

### ISSUE THREAD

**Issue by rohithjayan** [bumptech/glide#2284]
#When i upgraded to new 4.0.0 version i can't apply functions like placeholder,error etc .
How can i solve it?. Please help.

**Comment by Tolriq** [comment]
http://bumptech.github.io/glide/doc/migrating.html :)

**Comment by jaredsburrows** [comment]
You have to use `RequestOptions `, see this example: https://github.com/jaredsburrows/android-gif-example/blob/master/src/main/kotlin/burrows/apps/example/gif/data/rest/repository/ImageApiRepository.kt#L27.

**Comment by rohithjayan** [comment]
thanks

**Comment by jaredsburrows** [comment]
Can you close this issue now?
