### ISSUE TITLE
GlideApp not accessible outside module (cannot access RequestManager)

### ISSUE THREAD

**Issue by shaishavgandhi05** [bumptech/glide#2285]
**Glide Version**: 4.0

**Issue details / Repro steps / Use case background**:  I have a base module (com.android.library) which is then imported by the app. I import Glide in this base module and GlideApp is generated as expected. GlideApp is also available to the modules importing the base module. However, GlideApp.with(fragment) and any subsequent chaining gives the error : cannot access com.bumptech.glide.RequestManager.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(this)
                    .load(url)
                    .placeholder(R.drawable.placeholder)
                    .dontAnimate()
                    .into(image);
```

**Comment by sjudd** [comment]
Can you paste the full error?

**Comment by shaishavgandhi05** [comment]
Seems like it was an Android Studio intellisense error. It was showing as not available but it builds successfully.
