### ISSUE TITLE
It seems Glide does not save a Image in own Cache if byte array is used as a resource.

### ISSUE THREAD

**Issue by sinkiru** [bumptech/glide#2290]
I have used compile 'com.github.bumptech.glide:glide:3.7.0' for my android project.

Under is my Codes.

I used byte[] data to draw image on Screen as a image resource.
however I have a question. If byte array is used as image resource and signature method as the key String in Glide,

**Was a decoded resource image saved automatically in Glide Cache (Memory and Disk)?**
if not! why? 

I am not sure Glide does not save a image data [using byte array] in own Cache.

```java
synchronized public void loadAlbumArtAndUpdateBg(final byte[] img_buffer, final int
            placeholder, final ImageView originView, final String key) {

        Glide.with(mContext).load(img_buffer).asBitmap().error(Utils.getDefaultImageResId
                (ConstVariables.IMG_SIZE_LARGE)).dontAnimate().override(mDisplayWidth,
                mDisplayWidth).signature(new StringSignature(key)).skipMemoryCache(false).diskCacheStrategy(DiskCacheStrategy.ALL)//.into(originView);
            .into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<?
                    super Bitmap> glideAnimation) {

                originView.setImageBitmap(resource);

                // background
                requestBackgroundProcess(mLastRequestBuffer.array());
            }
```

**Comment by sjudd** [comment]
There's no efficient way to compute a cache key for a byte array, so by default caching is disabled. You can manually override these options and supply your own ``Key`` using ``signature()``.

**Comment by Rotemy** [comment]
@sjudd Can I supply a key using `signature` when using `byte[]` that mimics the cache key that is being generated for remote URL?
