### ISSUE TITLE
Conflict with dagger2 depencies. 

### ISSUE THREAD

**Issue by ruodezizaiyi** [bumptech/glide#2292]
when i use glide and dagger2 together, perhaps use @GlideModule, then occurs 
"Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.squareup.javapoet.MethodSpec$Builder.addJavadoc(Lcom/squareup/javapoet/CodeBlock;)Lcom/squareup/javapoet/MethodSpec$Builder". 

if i delete dagger2, there will be ok~

**Comment by Tolriq** [comment]
See https://github.com/JakeWharton/butterknife/issues/1063#issuecomment-324706716 :) It's a gradle problem with selecting the correct javaPoet version.
