### ISSUE TITLE
add header to glide 4.x

### ISSUE THREAD

**Issue by mohamadk** [bumptech/glide#2294]
in Glide 3.x we could add register a String model loader like following:

```java
public class GlideService /* implements GlideModule*/ {


    @Override
    public void registerComponents(Context context, Glide glide) {
        glide.register(String.class, InputStream.class, new HeaderedLoader.Factory());
    }

    private static class HeaderedLoader extends BaseGlideUrlLoader<String> {

        public HeaderedLoader(Context context) {
            super(context);
        }

        @Override
        protected String getUrl(String model, int width, int height) {
            return model;
        }


        @Override
        protected Headers getHeaders(String model, int width, int height) {

            LazyHeaders.Builder headersBuilder = new LazyHeaders.Builder();
            if (BuildConfig.FLAVOR.equals("staging")) {
                String auth = "username:password";
                String base64 = Base64.encodeToString(auth.getBytes(), Base64.NO_WRAP);
                headersBuilder.addHeader("Authorization", "Basic " + base64);
            }

            return headersBuilder.build();
        }

        public static class Factory implements ModelLoaderFactory<String, InputStream> {
            @Override
            public StreamModelLoader<String> build(Context context, GenericLoaderFactory factories) {
                return new HeaderedLoader(context);
            }

            @Override
            public void teardown() { }
        }
    }
}
```
But it's not clear from the docs how we can accomplish this for the lastest version
https://stackoverflow.com/questions/45782670/how-to-add-authorization-header-to-all-glide-4-x-request

**Comment by sjudd** [comment]
The same steps apply in Glide v4, but the interfaces have changed slightly.

See http://bumptech.github.io/glide/doc/configuration.html#adding-a-modelloader. When you register your ModelLoader, use ``replace()``, not ``prepend()`` or ``append()``

**Comment by mohamadk** [comment]
we don't have OkHttpUrlLoader class in glide 4.x so how can we handle that?

**Comment by sjudd** [comment]
OkHttpUrlLoader does in fact exist in Glide v4, in the same place it did in v3: https://github.com/bumptech/glide/blob/b667cab8d3e384ab6f127aef83eafe631d210fd0/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpUrlLoader.java#L15. 

Ii'm also not sure how it's relevant? In your code sample you're using ``BaseGlideUrlLoader``?

**Comment by mohamadk** [comment]
oops sorry your right I forget to add compile 'com.github.bumptech.glide:okhttp3-integration:1.5.0@aar' in my gradle but now my compiler say "Error:(46, 103) error: cannot find symbol class GenericLoaderFactory" 
public static class FactoryX extends OkHttpUrlLoader.Factory{
        @Override
        public ModelLoader<GlideUrl, InputStream> build(Context context, com.bumptech.glide.load.model.GenericLoaderFactory factories) {

            return super.build(context, factories);
        }
    }
am I mising somthing ? 
thanks for your help

**Comment by sjudd** [comment]
See https://github.com/bumptech/glide/blob/b1b024ebced1e6aef74062cfd04f67d1ca4aa8f5/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpUrlLoader.java#L37. You will need to make changes to handle the difference in API.

**Comment by mohamadk** [comment]
thanks, your aowsome
