### ISSUE TITLE
placeholder effect  fragment recycle

### ISSUE THREAD

**Issue by cosplay-wang** [bumptech/glide#2295]
i  use   viewpager  +  fragment + recyclerview   ，everyfragment has a recycerview。
i use  glide to load  picture  。
 Glide.with(myFragment).load(bookTypeDetails.get(position).getCover()).placeholder(R.drawable.booklib_type_detail).error(R.drawable.booklib_type_detail).crossFade().into(holder.imageView);

when i  remove placeholder ，myfragment can  recycle 。but when i add  that，the memory increase fastly。

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

To investigate memory usage, see http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors2. Is your placeholder especially large? Cross fade uses ``TransitionDrawable`` which will keep both the placeholder and your image in memory at the same time.
