### ISSUE TITLE
How to load http post url in glide?

### ISSUE THREAD

**Issue by LavanyaChokkalingam** [bumptech/glide#2297]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
You should actually fill out the template when filing new issues.

I'm not totally sure what you're asking. Usually Glide is only used to retrieve data, not POST. Maybe re-open after you fill out the template and with a clarification of what you're trying to do and what doesn't work?
