### ISSUE TITLE
GIF do not play when use makeSceneTransitionAnimation

### ISSUE THREAD

**Issue by SailFlorve** [bumptech/glide#2301]
I have a custom view contains a imageView, and it was set a transitionName, so did another imageview on another activity, but when activity switched, the imageview on new activity will not play gif.

**Comment by sjudd** [comment]
Please fill out the issue template when filing issues.

You're going to need to provide more detail. What do you mean by "the imageview on the new activity will not play gif"? Does the gif fail to load? does it load but fail to animate?

**Comment by sharafatshaikh7** [comment]
Hi @SailFlorve did you get the solution?
