### ISSUE TITLE
glide4.0.0的圆角要怎么弄？下面链接里的如果glide是4.0.0的话，会报错的

### ISSUE THREAD

**Issue by cancanw** [bumptech/glide#2303]

**Comment by cancanw** [comment]
http://blog.csdn.net/xiaoteshort/article/details/74939942  百度了个解决了。。。

**Comment by kenneth2008** [comment]
jp.wasabeef.glide.transformations
你在GIT搜這個, 有些人把做好的Transformation 打包了
