### ISSUE TITLE
Dependencies can NOT be found in Jcenter

### ISSUE THREAD

**Issue by googolmo** [bumptech/glide#2304]
I can't download glide from jcenter, and there is no glide version 4 in jcenter.
Follow this link https://jcenter.bintray.com/com/github/bumptech/glide/glide/

**Comment by sjudd** [comment]
I've never actually uploaded anything to jcenter. I've only ever uploaded to maven central. I was assuming jcenter was copying new versions over from maven central, but either that's stopped or I was incorrect.

It's kind of a pain to change the way uploads work. Is there some reason why you don't want to download from maven central?

**Comment by googolmo** [comment]
@sjudd Sometimes maven central's server is very slow for my network.
In my option you can upload it to bintray and it can be sync to maven central.

**Comment by sjudd** [comment]
Duplicate of #544
