### ISSUE TITLE
listview slip very slow if url is " " by glide 4.0 

### ISSUE THREAD

**Issue by cwi888** [bumptech/glide#2305]
listview slip very slow if url is " " by glide 4.0

**Comment by sjudd** [comment]
Are you able to reproduce this in a sample app? 

I tried replacing all loads with load("") in one of Glide's sample apps a few days ago and I didn't see anything slow (though of course images don't load).

Are you using a placeholder, error, or fallback drawable? Maybe retrieving that drawable is expensive? Or do you maybe have a ``RequestListener`` that's doing something expensive when a load fails?

**Comment by TWiStErRob** [comment]
Is the space within quotes important? Is it actually space (ASCII 0x20=32) or a special Unicode whitespace that looks like a space?
