### ISSUE TITLE
Image flickering on request restart.

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#2306]
**Glide Version**:
4.x

See attached video : [glide.zip](https://github.com/bumptech/glide/files/1263623/glide.zip)

Half visible views will display the transition animation so do not use memory cache.
Can happens in other cases too but this is the more obvious to reproduce.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.clear()
Glide.with...

After a notifydatasetchanged()
```

**Layout XML**:
```xml
<FixedRatioFrameLayout
    android:id="@+id/media_item_frame_container"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:foreground="@drawable/recycler_view_selector_holo_dark"
    app:frameAspectRatio="0.5625">

    <ImageView
        android:id="@+id/media_item_fanart"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentTop="true"
        android:layout_centerHorizontal="true"
        android:adjustViewBounds="true"
        android:contentDescription="@string/ctd_logo"
        android:scaleType="centerCrop"/>
</FixedRatioFrameLayout>
```

Dimensions are not fixed, the fixedratio layout is a simple layout that force a ratio.

**Comment by Tolriq** [comment]
@sjudd Anything I can do / provide so we can advance on this one?

This is way too deep in the library so hard for me to help / debug. But once this is fixed I can PR the Model interface equity part.

**Comment by sjudd** [comment]
Sorry I haven't had time to try it yet. I'd probably create a sample app with similar dimensions.

You can debug [``ViewTarget``](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/request/target/ViewTarget.java#L208) to verify that the flash occurs because we're failing to determine the ImageView's size, probably because the view has a pending layout.

Beyond that I'm not sure.
