### ISSUE TITLE
Glide versioning

### ISSUE THREAD

**Issue by Ajit121** [bumptech/glide#2310]
want to you version 3.7.0
i'm including as compile 'com.github.bumptech.glide:glide:3.7.0'. but i'm checking the external libraries. its showing version 4.0.0
![screen shot 2017-08-30 at 11 42 01 pm](https://user-images.githubusercontent.com/8845059/29887983-e11f9124-8ddc-11e7-99f0-14a7d76891be.png)
![screen shot 2017-08-30 at 11 41 53 pm](https://user-images.githubusercontent.com/8845059/29887985-e16e3130-8ddc-11e7-8acd-024a4078f96b.png)

**Comment by TWiStErRob** [comment]
First, you should use `3.8.0`, 3.7 is really old.

Second, to check why, run `gradlew :app:dependencies` and find lines like `glide 3.7.0 -> 4.0.0`. The tree will shed some light who updates it, my guess is `sendotp` may use a new version. If you find one and want to override, you can use `compile('...') { exclude group: 'com.bumptech.glide' }` syntax.

**Comment by Ajit121** [comment]
Just found some other libraries using Glide and found the line glide 3.7.0 -> 4.0.0. 
 also  excluded but the problem still exists

**Comment by Ajit121** [comment]
if i'm externally downloading and including the .jar file to libs folder and adding them as library. its showing multiple dex file defined in some of the files. 
    
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by TWiStErRob** [comment]
Verify that you excluded all by rerunning dependencies task.

**Comment by Ajit121** [comment]
it worked.. thank you so much for your help.

**Comment by TWiStErRob** [comment]
Mind you that just excluding won't solve the problems, if you have a lib that uses 3.x and one that uses 4.x, one of them will always fail at runtime (#2311), unless you're only using the parts that don't depend on Glide.

**Comment by Ajit121** [comment]
ok.. i'll keep in mind. Thank you
