### ISSUE TITLE
How to handle max texture problem in 4.0 without download the full size Bitmap?

### ISSUE THREAD

**Issue by kenneth2008** [bumptech/glide#2313]
[https://github.com/bumptech/glide/issues/547](https://github.com/bumptech/glide/issues/547)
Here has some code seems to be solution, but I don't know how to:
1. Do it on the Glide 4.0 version
2. Do it without download the full size Bitmap

I think in the target or listener to handle this will make memory leak. Can give some help??? Or glide?

**Comment by sjudd** [comment]
You can set a ``DownsampleStrategy`` with [``.downsample()``](http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/RequestOptions.html#downsample-com.bumptech.glide.load.resource.bitmap.DownsampleStrategy-):

```java
Glide.with(fragment)
  .apply(new RequestOptions.downsample(DownsampleStrategy.AT_MOST))
  .load(url)
  .into(view);
```

You can't do it without downloading the full size Bitmap unless you have access to a server API that lets you request images at specific sizes. Glide can't parse partial images.

**Comment by kenneth2008** [comment]
@sjudd It seems that, downsample() is not the door to exit this trap.
I found that there is a method to do this:
1. [http://extremej.itscoder.com/android_long_picture_process/#](get max texture integer)
2. Use it to check if the width or height is bigger then the max texture
3. SimpleTarget<Bitmap>, matrix.postScale(), Bitmap.createBitmap(bitmap, 0, 0, width, height, matrix, true), AdjustImageView, adjustViewBounds = true
4. If the size is:
max ture = 2048
original bitmap = 1024 x 3086
view = match_parent, wrap_content
I will have a Bitmap which will be 680x 2048, adjustViewBounds = true will make it fit the view width.

**Comment by sjudd** [comment]
``.fitCenter()`` or ``.centerInside()`` will accomplish basically the same thing if you pass in your maximum width and height into ``.override()``. A more canonical way to do what you're doing exactly would be to move the logic into a [``Transformation``](http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/load/resource/bitmap/BitmapTransformation.html)
