### ISSUE TITLE
fitcenter() and transform(..)    ,it's only one has work

### ISSUE THREAD

**Issue by mynamenoway** [bumptech/glide#2314]
RequestOptions options = new RequestOptions().fitCenter().transform(new RoundedCorners(14));

it's only transform work; 

RequestOptions options = new RequestOptions().transform(new RoundedCorners(14)).fitCenter();

it's only fitcenter work;

why?    if use:
new RequestOptions().centerCrop().transform(new RoundedCorners(14));
it's OK.

**Comment by Tolriq** [comment]
See documentation http://bumptech.github.io/glide/doc/transformations.html#multiple-transformations you need to use MultiTransformation

**Comment by mynamenoway** [comment]
I use 
private RequestOptions options = new RequestOptions().transform(new MultiTransformation<Bitmap>( new FitCenter(), new RoundedCorners(10)));
but it's also not work
at glide:4.0.0  API 21

**Comment by mynamenoway** [comment]
@Tolriq I use 
private RequestOptions options = new RequestOptions().transform(new MultiTransformation<Bitmap>( new FitCenter(), new RoundedCorners(10)));
but it's also not work
at glide:4.0.0  API 21
