### ISSUE TITLE
Get bitmap synchronously with Glide 4.0

### ISSUE THREAD

**Issue by tibbi** [bumptech/glide#2316]
Hey,

I'm using Glide in combination with [SubsamplingScaleImageView](https://github.com/davemorrissey/subsampling-scale-image-view) , which sadly decodes the images in RGB_565 format, which creates ugly artifacts on some images. To use ARGB_8888 I have to implement a custom decoder, as in [this sample](https://gist.github.com/davemorrissey/e2781ba5b966c9e95539#file-picassodecoder-java-L15) . The problem is that I need to get the image synchronously there. Glide used to have the `.get()` function, but since 4.0.0 it's not there anymore.

Is there any way to load the bitmap synchronously with the latest Glide 4.x? The images I'm loading are all on the device locally, I guess using Glide is still the proper solution, right?

Thanks

**Comment by sjudd** [comment]
There is still a ``get()`` method:

```java
// On a background thread:
Glide.with(applicationContext)
  .load(url)
  .submit(width, height)
  .get();
```

**Comment by tibbi** [comment]
works great, thanks!
