### ISSUE TITLE
Error in images displayed in Gallery [Cache]

### ISSUE THREAD

**Issue by lzn202** [bumptech/glide#2317]
**Glide Version**: 3.7 / 4.0

**Integration libraries**:

**Device/Android Version**:
4.0 / 4.4

**Issue details / Repro steps / Use case background**: 
I made the migration from Glide 3.7.0 to Glide 4.0.0, but after that I have been experiencing problems displaying the images in my RecyclerView.
The images shown in the RecyclerView are incorrect, showing repeated images.
I guess the configurations made for both versions of Glide are the same, so I can not find where the problem is

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
Glide 3.7.0

``java
        Glide.with(mActivity)
                .load(getUriFromMediaStore(position))
                .centerCrop()
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .skipMemoryCache(true)
                .override(160, 160)
                .into(holder.getImageView());``

Glide 4.0.0
```
        RequestOptions options =new RequestOptions();

        options.centerCrop()
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .skipMemoryCache(true)
                .override(160, 160)
                .dontAnimate();

        Glide.with(mActivity)
                .load(getUriFromMediaStore(position))
                .into(holder.getImageView());
```

**Comment by sjudd** [comment]
You probably want ``.transition(new DrawableTransitionOptions().dontTransition())`` instead of ``dontAnimate()``. 

Make sure you're calling ``Glide.with(activity).clear(holder.getImageView())`` if you have any cases in ``onBindViewHolder`` where you don't start a new load using ``into()``.

**Comment by lzn202** [comment]
I add the line you suggested with the clear onBindViewHolder method before the load, but the problem still occurs. I tried with Glide version 3.7 and it works correctly. There should be some change between versions that prevents the images being cleaned

` Glide.with(mActivity).clear(holder.getImageView());`

**Comment by lzn202** [comment]
I found the error, the problem occurred because I was using incorrectly the following line 
`.apply (options)`
