### ISSUE TITLE
GIF image is static when use TransitionAnimation

### ISSUE THREAD

**Issue by SailFlorve** [bumptech/glide#2320]
I have two activity, and each of them contains an imageview to play gif resources. I want an activity transition animation, so I use
`startActivity(intent, ActivityOptionsCompat.makeSceneTransitionAnimation(FirstActivity.this, imageview, "image").toBundle());`
but on second activity the gif do not animate just like a jpg, when I returned to firstActivity, gif do not animate too.

**Comment by sjudd** [comment]
I don't have any great ideas, i'm not sure whether or not transition animations support animated drawables?

What version of Glide are you using? Please fill out the issue template when filing new issues.
