### ISSUE TITLE
com.android.dex.DexException with Glide 4.1.0 and Android Studio Beta 4

### ISSUE THREAD

**Issue by colinrtwhite** [bumptech/glide#2322]
**Glide Version**:
4.1.0

**Integration libraries**:
OKHttp3

**Device/Android Version**:
Any

**Issue details / Repro steps / Use case background**:
Upgrading to Glide 4.1.0 causes the following compile exception on Android Studio 3.0 Beta 4:

    Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
    > com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Landroid/support/compat/R$drawable;

Downgrading to 4.0.0 fixes the issue. [Here's a demo project.](https://github.com/bumptech/glide/files/1272688/MyApplication.zip)

**Comment by TWiStErRob** [comment]
Hmm, looks like ee8a8eda15cf4961cda152817dfce5350ce59620 fixing a similar exception in #1972 is not complete. @sjudd `**/R$*.class`?

**Comment by jaredsburrows** [comment]
A Reddit user also posted something similar: https://www.reddit.com/r/androiddev/comments/6xji9f/android_studio_30_beta_4_is_available_now/dmglz2k/.

**Comment by sjudd** [comment]
Thanks for the sample app, very helpful. After 1325d87, I'm able to build the project. You can test this yourself by using the [4.2.0-SNAPSHOT](http://bumptech.github.io/glide/dev/snapshots.html) version of Glide.
