### ISSUE TITLE
Glide4.0 cannot dynamic set ModelLoader?

### ISSUE THREAD

**Issue by zaozaoge** [bumptech/glide#2325]
Glide3.7 can use like this "Glide.with(context).using(new MyModelLoader())" ,
but the method is gone when I update to 4.0.
so can I use my custom ModelLoader in Glide4.0 dynamically?

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/migrating.html#using

**Comment by sjudd** [comment]
Assuming this is answered, let me know if not.
