### ISSUE TITLE
Get File Size

### ISSUE THREAD

**Issue by liufsd** [bumptech/glide#2327]
**Glide Version**: 4.0

**get file**:
```java
FutureTarget<File> future = Glide.with(applicationContext)
    .load(yourUrl)
    .downloadOnly(500, 500);
File cacheFile = future.get();
```

i know, this will be get file ,but this only work on background thread. but i need on main ui thread sync when user click the imageview (the image load finish at this time), i will tell user ,the image file size .
so i need get cache file on main thread, and show user file size by show toast.

as i known, the glide not support to do this by library design.

**Comment by sjudd** [comment]
There's no way to get the file size on the main thread. The deprecated method you're using suggests using a ``RequestManager`` equivalent: http://bumptech.github.io/glide/javadocs/410/com/bumptech/glide/RequestBuilder.html#downloadOnly-int-int-. 

The ``RequestManager`` equivalent will return a ``RequestBuilder``: http://bumptech.github.io/glide/javadocs/410/com/bumptech/glide/RequestManager.html#downloadOnly--. You can use that ``RequestBuilder`` to load the ``File`` into a ``Target`` asynchronously and show the ``Toast`` when the load completes.

**Comment by liufsd** [comment]
i know this. but i find that more than one this issue. why glide still not support this ?

**Comment by sjudd** [comment]
There's no efficient way to do what you want to do on the main thread. Obtaining a file size on the main thread does I/O, which adds jank and is a strict mode violation.
