### ISSUE TITLE
Glide 4.0 how to implements https  certs

### ISSUE THREAD

**Issue by aiven163** [bumptech/glide#2330]
Glide 4.0 how to implements https  certs?

**Comment by sjudd** [comment]
Can you be more specific?

**Comment by Nicozb** [comment]
Hi, same problem here. Doesn't work with https self signed certificate.

I was using this method with Glide 3.8.0: 
https://futurestud.io/tutorials/glide-module-example-accepting-self-signed-https-certificates

But now it's outdated with Glide 4.1.0.. Any idea to update it ?
Thanks

**Comment by sjudd** [comment]
That tutorial link is not not really outdated. Interfaces have changed, but it shouldn't be too much work to adjust their code sample in your app. The only real significant change is that ``DataFetchers`` take a callback instead of returning a value.
