### ISSUE TITLE
BITMAP_POOL_TARGET_SCREENS should be >= O not > O

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#2332]
https://github.com/bumptech/glide/commit/bb5c391a8b418f8ac2296d4d2c2ca24110e83984

Thanks @SUPERCILEX

**Comment by Tolriq** [comment]
Actually it's <

**Comment by SUPERCILEX** [comment]
@Tolriq OMG, lol, you're right! 😆 I didn't read the documentation, but it states that the pool is less important on O+ devices so `<` makes sense.

**Comment by Tolriq** [comment]
NP can PR that tommorow @sjudd

**Comment by SUPERCILEX** [comment]
@Tolriq I've [got it](https://github.com/bumptech/glide/pull/2334).
