### ISSUE TITLE
Glide 4.1 issue while building the project

### ISSUE THREAD

**Issue by mhdtouban** [bumptech/glide#2333]
Whenever I upgraded from 3.8 to 4.1 I get the following issue, even I have a multidex enabled. The app builds normally changing version back to 3.x
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.tools.r8.errors.CompilationError: Program type already present: android.support.coreui.R$string

**Integration libraries**:
The issue still occurs even if I disabled okhttp3-1.5.0

**Device/Android Version**: doesn't even build
Android studio 3.0 beta-4
gradle 3.0.0-beta4

**Issue details / Repro steps / Use case background**: 
Trying to upgrade to latest glide version

**Stack trace / LogCat**:
```Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.tools.r8.errors.CompilationError: Program type already present: android.support.coreui.R$string
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.tools.r8.errors.CompilationError: Program type already present: android.support.coreui.R$string
```

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/releases/tag/v4.1.1
