### ISSUE TITLE
Glide4.1.1 still not available ! But Glide4.0.0 is ok

### ISSUE THREAD

**Issue by galfordliu** [bumptech/glide#2335]
report error:

Error:Failed to resolve: annotationProcessor
Error:Failed to resolve: com.android.support:support-annotations:26.0.2

on
compileSdkVersion 25
buildToolsVersion '25.0.3'

compile 'com.github.bumptech.glide:glide:4.1.1'
compile 'com.github.bumptech.glide:okhttp3-integration:4.1.1@aar'
annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'

**Comment by sjudd** [comment]
At least this morning I'm able to build a sample app against Glide 4.1.1 retrieved from maven central. It's also able to find support-annotations 26.0.02 (as is travis). 

If you're still seeing this error, please add the full stack trace.

**Comment by jishuo1213** [comment]
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.android.support:support-annotations:26.0.2.
     Required by:
         project :app
         project :app > com.android.support:appcompat-v7:25.3.1
         project :app > com.android.support:recyclerview-v7:25.3.1
         project :app > com.android.support:appcompat-v7:25.3.1 > com.android.support:support-vector-drawable:25.3.1
         project :app > com.android.support:design:25.3.1 > com.android.support:transition:25.3.1
         project :app > com.android.support:support-v4:25.3.1 > com.android.support:support-compat:25.3.1
         project :app > com.android.support:support-v4:25.3.1 > com.android.support:support-media-compat:25.3.1
         project :app > com.android.support:support-v4:25.3.1 > com.android.support:support-core-utils:25.3.1
         project :app > com.android.support:support-v4:25.3.1 > com.android.support:support-core-ui:25.3.1
   > Could not find com.android.support:support-annotations:26.0.2.
     Required by:
         project :app > com.github.bumptech.glide:glide:4.1.1 > com.github.bumptech.glide:gifdecoder:4.1.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jishuo1213** [comment]
@sjudd

**Comment by galfordliu** [comment]
I also use 25.3.1, and Glide4.1.1 must use 26.0.2?

**Comment by galfordliu** [comment]
@sjudd 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_qqDebugApkCopy'.
   > Could not find com.android.support:support-annotations:26.0.2.
     Required by:
         project :app > com.android.support:appcompat-v7:25.3.1
         project :app > com.android.support:recyclerview-v7:25.3.1
         project :app > com.android.support:cardview-v7:25.3.1
         project :app > com.android.support:appcompat-v7:25.3.1 > com.android.support:support-vector-drawable:25.3.1
         project :app > com.android.support:recyclerview-v7:25.3.1 > com.android.support:support-compat:25.3.1
         project :app > com.android.support:recyclerview-v7:25.3.1 > com.android.support:support-core-ui:25.3.1
         project :app > com.android.support:design:25.3.1 > com.android.support:transition:25.3.1
         project :app > com.android.support:support-v4:25.3.1 > com.android.support:support-media-compat:25.3.1
         project :app > com.android.support:support-v4:25.3.1 > com.android.support:support-core-utils:25.3.1
   > Could not find com.android.support:support-annotations:26.0.2.
     Required by:
         project :app > com.jakewharton:butterknife:8.8.1
         project :app > com.jakewharton:butterknife:8.8.1 > com.jakewharton:butterknife-annotations:8.8.1
   > Could not find com.android.support:support-annotations:26.0.2.
     Required by:
         project :app > com.github.bumptech.glide:glide:4.1.1 > com.github.bumptech.glide:gifdecoder:4.1.1

**Comment by sjudd** [comment]
Thanks, this looks like a duplicate of #2347. I just added a couple of ideas there, can you try those and let me know how it goes in that issue?

**Comment by DRPrincess** [comment]
I also meet this question , and I add  `maven { url 'https://maven.google.com' }`, but doesn't work, I don't know how to resolve it .
this is error msg when clean 
`
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve com.android.support:support-annotations:26.0.2.
     Required by:
         ReallyCarFinance:app:unspecified > com.android.support:appcompat-v7:25.3.1
         ReallyCarFinance:app:unspecified > com.android.support:appcompat-v7:25.3.1 > com.android.support:support-vector-drawable:25.3.1
         ReallyCarFinance:app:unspecified > com.android.support:appcompat-v7:25.3.1 > com.android.support:support-v4:25.3.1 > com.android.support:support-media-compat:25.3.1
         ReallyCarFinance:app:unspecified > com.android.support:appcompat-v7:25.3.1 > com.android.support:support-v4:25.3.1 > com.android.support:support-core-utils:25.3.1
         ReallyCarFinance:app:unspecified > com.jakewharton:butterknife:8.8.1 > com.android.support:support-compat:25.3.1
         ReallyCarFinance:app:unspecified > com.android.support:recyclerview-v7:25.1.0 > com.android.support:support-core-ui:25.3.1
      > Could not resolve com.android.support:support-annotations:26.0.2.
         > Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
               > Remote host closed connection during handshake
      > Could not resolve com.android.support:support-annotations:26.0.2.
         > Could not get resource 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
            > Could not GET 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'. Received status code 409 from server: Conflict
   > Could not resolve com.android.support:support-annotations:26.0.2.
     Required by:
         ReallyCarFinance:app:unspecified > com.jakewharton:butterknife:8.8.1
         ReallyCarFinance:app:unspecified > com.jakewharton:butterknife:8.8.1 > com.jakewharton:butterknife-annotations:8.8.1
      > Could not resolve com.android.support:support-annotations:26.0.2.
         > Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
               > Remote host closed connection during handshake
      > Could not resolve com.android.support:support-annotations:26.0.2.
         > Could not get resource 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
            > Could not GET 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'. Received status code 409 from server: Conflict
   > Could not resolve com.android.support:support-annotations:26.0.2.
     Required by:
         ReallyCarFinance:app:unspecified > com.android.support:cardview-v7:25.1.0
         ReallyCarFinance:app:unspecified > com.android.support:recyclerview-v7:25.1.0
      > Could not resolve com.android.support:support-annotations:26.0.2.
         > Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
               > Remote host closed connection during handshake
      > Could not resolve com.android.support:support-annotations:26.0.2.
         > Could not get resource 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
            > Could not GET 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'. Received status code 409 from server: Conflict
   > Could not resolve com.android.support:support-annotations:26.0.2.
     Required by:
         ReallyCarFinance:app:unspecified > com.github.bumptech.glide:glide:4.1.1 > com.github.bumptech.glide:gifdecoder:4.1.1
      > Could not resolve com.android.support:support-annotations:26.0.2.
         > Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
               > Remote host closed connection during handshake
      > Could not resolve com.android.support:support-annotations:26.0.2.
         > Could not get resource 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.
            > Could not GET 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'. Received status code 409 from server: Conflict
`

**Comment by DRPrincess** [comment]
when I upgrade glide from 4.1.1 to 4.0.0 ,solve this problem ,but I think it not true answer。

**Comment by TWiStErRob** [comment]
> Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.0.2/support-annotations-26.0.2.pom'.

This file exists when I try it, are you behind some strict proxy maybe?

**Comment by sjudd** [comment]
See also https://developer.android.com/topic/libraries/support-library/setup.html
