### ISSUE TITLE
Usage in android library module (generated API)

### ISSUE THREAD

**Issue by DDeg** [bumptech/glide#2343]
In library module I need to use glide loading with generated API customization.

Using AppGlideModule class runs to Duplicate entry ZipException in main app, LIbraryGlideModule not generate any class to use Glide loading in library module.

How can I use Glide customized loading in my android library module?

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

What version of Glide are you using? Maybe 4.0.0? If so, try 4.1.1. If not, please provide the full exception you're seeing.

**Comment by Fisherman91** [comment]
the same question

**Comment by Fisherman91** [comment]
4.1.1
