### ISSUE TITLE
ip6 address can`t load

### ISSUE THREAD

**Issue by Lyoona** [bumptech/glide#2348]
Version: Glide.4.0.0
Description: hello, when i use the ipv6 ip address , i can`t load the image, it seems the ip address like that '[2222.2222.2222]' which '[]' resolve has something wrong. i can`t use the domain because my application can`t translate the ipv4 to ipv6 perfect on every phone. so ,can you take some suggestion

**Comment by sjudd** [comment]
What error do you see? What is your load line? Can you provide a sample url?

**Comment by Lyoona** [comment]
thanks your reply,and i`m sorry i forget it, because it`s a long time when i first do it, now i try use the fresco instead it,it works, maybe this wrong in the glide

**Comment by maxwell-nc** [comment]
load "https://[xxxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:1234/1.png" throw exception:

java.net.MalformedURLException: java.lang.NumberFormatException: Invalid int:  "xxxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx%5D:1234"

**Comment by ContentCoderJian** [comment]
http://[fe80::d40b:fb37:5fba:4e8e]:8080/html/image.jpg
can not show,.
java.net.MalformedURLException(invalid port: :d40b:fb37:5fba:4e8e%5D:8080)
