### ISSUE TITLE
load local image circleCrop not working

### ISSUE THREAD

**Issue by Wingge** [bumptech/glide#2350]
version: 
4.1.1
code:
RequestOptions options = new RequestOptions()
                .format(DecodeFormat.PREFER_RGB_565)
                .circleCrop()
                .placeholder(R.mipmap.ic_launcher)
                .error(R.mipmap.ic_launcher)
                .priority(Priority.NORMAL) 
                .diskCacheStrategy(DiskCacheStrategy.NONE) 
                ;
Glide.with(getActivity()).load(url).apply(options ).into(header);

result:
the final image after loading get completed did not cropped completely inside circle

**Comment by Wingge** [comment]
the remote url is working,but the local is not.

**Comment by sjudd** [comment]
Does it work if you remove DecodeFormat.PREFER_RGB_565?

**Comment by Wingge** [comment]
@sjudd no, still not working. and i found the log :
09-08 10:38:11.728 32704-32704/com.qhfm.golfseeking W/Glide: Load failed for null with size [0x0]
                                                             class com.bumptech.glide.load.engine.GlideException: Received null model

**Comment by sjudd** [comment]
Is url ``null``?

**Comment by Wingge** [comment]
No, the url is local image is R.drawable.XX. and the image can display but not "circleCrop“

**Comment by Wingge** [comment]
@sjudd I have to say, the circleCrop work when the url is remote.

**Comment by Wingge** [comment]
Yes!!!  the url is null , so the circleCrop work.
