### ISSUE TITLE
Exception in OkHttp3 library on O

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#2355]
09-07 10:10:54.540 E/AndroidRuntime( 8724): FATAL EXCEPTION: OkHttp Dispatcher
09-07 10:10:54.540 E/AndroidRuntime( 8724): Process: com.bumptech.glide.samples.flickr, PID: 8724
09-07 10:10:54.540 E/AndroidRuntime( 8724): java.lang.ClassCastException: android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at libcore.io.IoBridge.getLocalInetSocketAddress(IoBridge.java:700)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at libcore.io.IoBridge.connectDetail(IoBridge.java:197)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at libcore.io.IoBridge.connect(IoBridge.java:138)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at java.net.Socket.connect(Socket.java:616)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.internal.Platform$Android.connectSocket(Platform.java:200)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:137)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:108)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.RealCall.getResponse(RealCall.java:240)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.RealCall.access$100(RealCall.java:30)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-07 10:10:54.540 E/AndroidRuntime( 8724): 	at java.lang.Thread.run(Thread.java:764)
09-07 10:10:54.543 W/ActivityManager( 1539):   Force finishing activity com.bumptech.glide.samples.flickr/.FlickrSearchActivity

See https://github.com/square/okhttp/issues/3438 and https://issuetracker.google.com/issues/63649622.

**Comment by yschimke** [comment]
Is it worth upgrading to OkHttp 3.9.1 and reverting this fix https://github.com/bumptech/glide/blame/e35a73b4e78f2f05dc5c1163b8083ac1b662b02f/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpStreamFetcher.java#L56

**Comment by sjudd** [comment]
@yschimke probably yes, although anyone deliberately using an older version of OkHttp may break. 

Probably ok to wait and see if that happens though, there's not much reason to force your build to be on an older version and I think Gradle will prefer the newest of an specified versions.
