### ISSUE TITLE
In order to save memory, how can I use RGB888?

### ISSUE THREAD

**Issue by frel** [bumptech/glide#2360]
In order to save memory, how can I use RGB888? It's not defined in DecodeFormat. For our needs ARGB8888 is required some places, but RGB888 would be sufficient all over. RGB565 looks too bad (color banding is really noticeable).

Thank you

**Comment by sjudd** [comment]
Android doesn't support RGB_8888, only ARGB_8888: https://developer.android.com/reference/android/graphics/Bitmap.Config.html

**Comment by frel** [comment]
Ah thank you for clarifying.

**Comment by sjudd** [comment]
Sure no problem.
