### ISSUE TITLE
Glide v4 occupy more memory

### ISSUE THREAD

**Issue by SIARAY** [bumptech/glide#2365]
Please compare the below screenshots.
Screenshots are taken in almost identical conditions.
The app was launched on Samsung galaxy s7.

Glide v3.8.0
![glide-v3 8 0](https://user-images.githubusercontent.com/22600090/29754037-f9ef0492-8b92-11e7-9fa0-fada92f004ca.jpg)

Glide v4.0.0 - v4.1.1
![glide-v4 0 0](https://user-images.githubusercontent.com/22600090/29754038-f9f1468a-8b92-11e7-874f-c8d1b9e3e9e1.jpg)

Picasso
![picasso](https://user-images.githubusercontent.com/22600090/29754039-f9f44074-8b92-11e7-9e15-bcb1056439e6.jpg)

I think that the memory occupied by the library is much larger than before.

**Comment by TWiStErRob** [comment]
Memory usage has to be looked at over a long period of time. Glide keeps some Bitmaps in memory anticipating further usage of those, which means that *a* future load will have no allocation.

What's your code and use case that produced these graphs?

**Comment by TWiStErRob** [comment]
For testing mem I suggest to set the memory cache to `MemoryCacheAdapter` to disable it and see what the actual resources are using.

**Comment by SIARAY** [comment]
I load image in RecyclerView

        rv = (RecyclerView) view.findViewById(R.id.recyclerView);
        adapter = new MyAdapter(getActivity(), getList());
        rv.setAdapter(adapter);
        final GridLayoutManager gridLayoutManager = new GridLayoutManager(this.getActivity(), 2);
        rv.setLayoutManager(gridLayoutManager);

My loading image code.

        RequestOptions options = new RequestOptions();
        options.diskCacheStrategy(GLIDE_DISK_CACHE_STRATEGY);
        if (!hasAnim) {
            options.dontAnimate();
        }
        RequestBuilder glide = Glide.with(context)
                .load(imageLink)
                .apply(options);
        glide.into(imageView);

How to set memory cache to MemoryCacheAdapter and test it?
Also, I have OOM error in my app.

**Comment by sjudd** [comment]
One significant change is that Glide v4 uses ARGB_8888 by default instead of RGB_565 (used in v3) .
v3: https://github.com/bumptech/glide/blob/211c4dbd79d92dcc56f186d0dd8b50849f9236ff/library/src/main/java/com/bumptech/glide/load/DecodeFormat.java#L48
v4: https://github.com/bumptech/glide/blob/a4af922db56c928a56bcb8bfc7651e32fe10fd10/library/src/main/java/com/bumptech/glide/load/DecodeFormat.java#L54.

It's also probable that the default memory cache and bitmap pool sizes have changed. You can customize those if you'd like: http://bumptech.github.io/glide/doc/configuration.html#application-options

If you're seeing OOMs though, that implies either your Target/View sizes are too large, or that you have a memory leak in your application: http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors.

You could try comparing heap dumps if you want to more definitively determine where the memory usage comes from in the various cases.

**Comment by SIARAY** [comment]
I did more testing.
The problem seems to be the size of the photos and their centercrop mode. Although they used less memory in the previous version.
How to fix this problem?
The size of the images is not the same. Also, I do not want the quality of photos to be reduced.

**Comment by sjudd** [comment]
Are you saying that the View size is the same, but the width and height of the Bitmaps Glide loads is different in v3 vs v4?

Or are you saying that View size and the Bitmap size is the same, but the memory size of the Bitmaps Glide loads is different in v3 vs v4?

**Comment by SIARAY** [comment]
Noو
I mean, loading similar images in version 4 occupies more memory than version 3.
But I think my problem at the moment is a lot of memory occupation. This may cause the application to oom error.
If the problem is due to the size of the images and the centercrop mode, what is your suggestion for solving the problem?
Does Glide have the ability to minimize images by keeping it ratio?

**Comment by sjudd** [comment]
If the Bitmap and View dimensions are the same in v3 and v4, you can just use ``DecodeFormat.RGB_565`` to get the same memory usage in v4. See http://bumptech.github.io/glide/javadocs/410/com/bumptech/glide/request/RequestOptions.html#format-com.bumptech.glide.load.DecodeFormat-.

If you're not happy with the quality or you want to reduce memory usage further, then you can:
1. Reduce the size of your Views
2. Use [``override(int, int)``][1] to force Glide to load an image that's smaller than your view using the given dimensions.
3. Use [``sizeMultiplier(float)``][2] to scale down the image based on your ``View`` size. 

[1]: http://bumptech.github.io/glide/javadocs/410/com/bumptech/glide/request/RequestOptions.html#override-int-int-
[2]: http://bumptech.github.io/glide/javadocs/410/com/bumptech/glide/request/RequestOptions.html#sizeMultiplier-float-

**Comment by SIARAY** [comment]
Thank you, @sjudd, I will try.

**Comment by svshishkina** [comment]
I faced with the same problem. We migrated from version 3.8.0 to 4.6.1 and memory consumption extremely increased. This causes OOM exception. 
Screenshots below show memory usage, the same app screen was opened. I tried change DecodeFormat to RGB_565, but it didn't improve a lot. May be something else changed in configuration?

Glide 3.8.0
<img width="1560" alt="2018-04-09 22 00 14" src="https://user-images.githubusercontent.com/16253423/38517215-df58c9fa-3c41-11e8-99ae-9b9645daf697.png">

Glide 4.6.1
<img width="1556" alt="glide v4" src="https://user-images.githubusercontent.com/16253423/38516788-b8312ce2-3c40-11e8-9dc8-1ba8b7319808.png">

**Comment by SIARAY** [comment]
Use following code for change DecodeFormat:

`        RequestOptions options = new RequestOptions();
        options.format(DecodeFormat.PREFER_RGB_565);`

**Comment by svshishkina** [comment]
@SIARAY I've already done this. Screenshot for Glide 4.6.1 was done with decode format RGB_565

**Comment by sjudd** [comment]
For memory issues, you'll need to look at a heap dump, see http://bumptech.github.io/glide/doc/debugging.html#memory-leaks which has a few pointers.

**Comment by easternHong** [comment]
```
        Glide.with(this)
                .load("")
                .into(new SimpleTarget<GlideDrawable>(120, 120) {
                    @Override
                    public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                        int h = resource.getIntrinsicHeight();
                        int w = resource.getIntrinsicHeight();
                        //4.x  h =120 && w = 120  ,so memory usage may be increased
                        //3.x  h <=120 && w<= 120
                    }
                });
```

**Comment by HerminioDeveloper** [comment]
Glide I am developing a gallery app and loading thumbnail with this Glide library... the question is from how can I do to optimize the load ... thanks
