### ISSUE TITLE
Report a bug when using Glide.with(view)

### ISSUE THREAD

**Issue by liubaoyua** [bumptech/glide#2370]
**Glide Version**: 4.1.1

**Issue details / Repro steps / Use case background**: 

I found that glide 4.x have add a new api 
```
  public static RequestManager with(View view) {
    return getRetriever(view.getContext()).get(view);
  }
```

and I look into the source code 
```
  public RequestManager get(View view) {
    if (Util.isOnBackgroundThread()) {
      return get(view.getContext().getApplicationContext());
    }

    Preconditions.checkNotNull(view);
    Preconditions.checkNotNull(view.getContext(),
        "Unable to obtain a request manager for a view without a Context");
    Activity activity = findActivity(view.getContext());
    // The view might be somewhere else, like a service.
    if (activity == null) {
      return get(view.getContext().getApplicationContext());
    }

    // Support Fragments.
    if (activity instanceof FragmentActivity) {
      Fragment fragment = findSupportFragment(view, (FragmentActivity) activity);
      if (fragment == null) {
        return get(activity);
      }
      return get(fragment);
    }

    // Standard Fragments.
    android.app.Fragment fragment = findFragment(view, activity);
    if (fragment == null) {
      return get(activity);
    }
    return get(fragment);
  }
```

and I find a bug that if someone use AppCompatActivity  (which extends FragmentActivity).
And in that activity, use the android.app.Fragment, inside the fragment, use the code below to load image. 
```
    RequestManager manager = Glide.with(viewHolder.imageView);
    manager.load(current.uri).into(viewHolder.imageView);
```
The ```manager``` we get is from ```public RequestManager get(Activity activity)```, 
instead of  ```public RequestManager get(android.app.Fragment fragment)```

**Comment by sjudd** [comment]
Can you clarify:

> The manager we get is from public RequestManager get(Activity activity),
> instead of public RequestManager get(android.app.Fragment fragment)

How are you determining this? Can you attach a sample app that reproduces the issue, or a failing test case?

**Comment by liubaoyua** [comment]
Here is the Sample https://github.com/liubaoyua/Example.

The debugger show that in MainActivity.java line 91,  
```
RequestManager manager = Glide.with(imageView);
manager.load("https://assets-cdn.github.com/images/modules/site/universe-logo.png")
                    .into(imageView);
```
The manager come from  RequestManagerRetriever.get(android.app.Activity), but the imageView is a fragment view.

**Comment by sjudd** [comment]
Thanks for the sample app, that's hugely helpful! Unfortunately that case can't be fixed: https://github.com/bumptech/glide/blob/b1b024ebced1e6aef74062cfd04f67d1ca4aa8f5/library/src/main/java/com/bumptech/glide/Glide.java#L614.

Basically there's nothing that connects the View to the Fragment at that point in time. After onCreateView, when ``getView()`` returns the View or its parent, the method will work. Before or during onCreateView, it won't.

In general if you have access to a Fragment or Activity, you should use the Fragment or Activity for with(). The View method should only be used if you don't have access to a Fragment or Activity.

**Comment by liubaoyua** [comment]
Thank you for you reply. And you are right, the View method should only be used if you don't have access to a Fragment or Activity. I just find the problem when reading the source code, if you think this is meaningless, it is ok  to ignore me.

Actually in my sample app, even when ```getView()``` returns the View or its parent, the method still can't work if you are using the ```android.app.Fragment```.

I think there are some wrong in method ```public RequestManager get(View view)```.

And it should be changed to 
```
public RequestManager get(View view) {
    if (Util.isOnBackgroundThread()) {
      return get(view.getContext().getApplicationContext());
    }

    Preconditions.checkNotNull(view);
    Preconditions.checkNotNull(view.getContext(),
        "Unable to obtain a request manager for a view without a Context");
    Activity activity = findActivity(view.getContext());
    // The view might be somewhere else, like a service.
    if (activity == null) {
      return get(view.getContext().getApplicationContext());
    }

    // Support Fragments.
    if (activity instanceof FragmentActivity) {
      Fragment fragment = findSupportFragment(view, (FragmentActivity) activity);
     // here is the different, if we can't find the view in the support fragments,  we still need to find it in standard fragments.
      if (fragment != null) {
        return get(fragment);
      }
    }

    // Standard Fragments.
    android.app.Fragment fragment = findFragment(view, activity);
    if (fragment == null) {
      return get(activity);
    }
    return get(fragment);
  }
```

However , after  I modify the source code, it still can't work. The method ```private void findAllFragmentsWithViews(
      android.app.FragmentManager fragmentManager, ArrayMap<View, android.app.Fragment> result)``` can't not find the attached fragment, the ArrayMap always empty. I'm trying to figure out why.

**Comment by liubaoyua** [comment]
Surprise! I find out why the method```private void findAllFragmentsWithViews(
      android.app.FragmentManager fragmentManager, ArrayMap<View, android.app.Fragment> result)```  doesn't work because of the wrong key in ```Fragment getFragment(Bundle bundle, String key)```
Here is the modified method. 
```
  private void findAllFragmentsWithViews(
      android.app.FragmentManager fragmentManager, ArrayMap<View, android.app.Fragment> result) {
    int index = 0;
    while (true) {
      tempBundle.putInt(FRAGMENT_INDEX_KEY, index++);
      android.app.Fragment fragment = null;
      try {
        fragment = fragmentManager.getFragment(tempBundle, FRAGMENT_INDEX_KEY);
      } catch (Exception e) {
        // This generates log spam from FragmentManager anyway.
      }
      if (fragment == null) {
        break;
      }
      if (fragment.getView() != null) {
        result.put(fragment.getView(), fragment);
        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN_MR1) {
          findAllFragmentsWithViews(fragment.getChildFragmentManager(), result);
        }
      }
    }
  }
```

**Comment by sjudd** [comment]
Thanks for letting me know, what version of Android are you testing this on?

**Comment by sjudd** [comment]
Actually don't worry about it, I can reproduce this all the way back to ICS. Thanks for finding this and point it out! I'll fix it shortly.

**Comment by liubaoyua** [comment]
Android 7.1.1

I find out the solution from the the support-fragment library 25.3.1 

and it's source code
```
@Override
    public Fragment getFragment(Bundle bundle, String key) {
        int index = bundle.getInt(key, -1);
        if (index == -1) {
            return null;
        }
        if (index >= mActive.size()) {
            throwException(new IllegalStateException("Fragment no longer exists for key "
                    + key + ": index " + index));
        }
        Fragment f = mActive.get(index);
        if (f == null) {
            throwException(new IllegalStateException("Fragment no longer exists for key "
                    + key + ": index " + index));
        }
        return f;
    }
```

**Comment by Naderkunbhar** [comment]
Android 9 Pie Google Pixel
Image Drawable Icon loading with Glide for Multilangual are reset to English from Arabic ,after launch webview,please give me some hint
