### ISSUE TITLE
RecyclerView ImageView wrap_content

### ISSUE THREAD

**Issue by liufsd** [bumptech/glide#2373]
Glide Version: 4.1.1 

Integration libraries:  RecyclerView

Issue details / Repro steps :

Code:

```
                  Glide.with(context)
                        .load(imageUri)
                        .apply(RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.RESOURCE))
                        .apply(RequestOptions().placeholder(imageView.context.resources.getDrawable(holderConfig?.loading ?: R.drawable.emoticon_image_show_loading)))
                        .apply(RequestOptions().error(imageView.context.resources.getDrawable(holderConfig?.error ?: R.drawable.emoticon_image_show_retry)))
                        .listener(object : RequestListener<Drawable> {
                            override fun onLoadFailed(e: GlideException?, model: Any?, target: Target<Drawable>?, isFirstResource: Boolean): Boolean {
                                loadImageCompleteListener?.onLoadImageComplete(false)
                                return false
                            }

                            override fun onResourceReady(resource: Drawable?, model: Any?, target: Target<Drawable>?, dataSource: DataSource?, isFirstResource: Boolean): Boolean {
                                loadImageCompleteListener?.onLoadImageComplete(true)
                                return false
                            }
                        })
                        .into(imageView)
``` 

xml: 

```
 <LinearLayout
                android:id="@+id/rl_chatcontent"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:gravity="center">

                <ImageView
                    android:id="@+id/tv_chatcontent"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:adjustViewBounds="true"
                    android:maxWidth="150dp"
                    android:maxHeight="150dp"
                    android:minHeight="40dp"
                    android:minWidth="40dp"
                    android:scaleType="centerInside"
                    android:layout_gravity="center" />

            </LinearLayout>
``` 

The problem:

When i scroll the my recyclerView, the recyclerView will 'shake', because my image src are not same size, so item will resize height when image load complete. 

how to fix this ?

I saw many issue about "wrap_content" .

**Comment by sjudd** [comment]
Don't use wrap_content.

Even if you don't use Glide, wrap_content necessarily means that the size of your views in RecyclerView are going to change from item to item. That's going to cause all sorts of UI weirdness.

One option is to try to obtain the image dimensions in whatever metadata you're using to populate the RecyclerView. Then you can set a fixed View size in onBindViewHolder so the view size at least doesn't change when the image is loaded. You're still likely to see weird scroll bar behavior though.

If nothing else, you can always pick a uniform size that's large enough for all items and use the same consistent size for every item.

**Comment by liufsd** [comment]
The other problem by i have set placeholder. if i have not set placeholder. it will scroll ok. but the imageview show only small size , maybe glide load 'minWidth' size, not image src origin size.

**Comment by sjudd** [comment]
For the image file size, you can downscale or upscale by setting the ImageView size manually to 150dp x 150dp. Ultimately either you need uniform view sizes or predetermined view sizes. There's nothing else that will prevent content from expanding or shrinking in your RecyclerView.

For the placeholder bit, I think that will be fixed by 648c58e4214d9c2e2605e9b6203159a0655ad067, you can check by trying the 4.2.0-SNAPSHOT version: http://bumptech.github.io/glide/dev/snapshots.html.

**Comment by liufsd** [comment]
ok, i will test the SANPSHOT.

**Comment by mehmetgr06** [comment]
I have same problem. When I use wrap_content, performance is decreasing. Using a fixed size so absurd. This is certainly not a solution. Did you find a real solution ? @liufsd
