### ISSUE TITLE
Glide and recycler view, documentation is not clear

### ISSUE THREAD

**Issue by stephanenicolas** [bumptech/glide#2374]
Inside a recycler view: should we or should we not call 
```
requestManager.clear(imageView);
```
when a view holder is unbound (when `onViewRecycled` is called). The documentation is not clear, there are many issues related to this, but no clear and definitive answer, especially for glide 4. 

According to our tests, if you don't call this method, viewholder still keep a reference to their bitmap because of the their tag. And this takes a lot of RAM, especially when there are multiple view types involved in a recycler view.
But is calling `clear` breaking some intended mechanism internal to glide ? The code mentions that the tag is used internally when recycling view but it's not clear.

A fast answer would be appreciated.

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/getting-started.html#listview-and-recyclerview

You can clear() in onViewRecycled, you don't have to.

**Comment by stephanenicolas** [comment]
@sjudd thx for the fast answer, it's really appreciated. 

But, it's very pre-occupating that we could find a Lazy bitmap waiting 2.5Mb in the tag of a view that was in the scrap view set of the recycler view. This should not happen and is a bug in glide if calling clear is not mandatory.

**Comment by sjudd** [comment]
You can definitely set your own ``RecyclerListener`` and clear out the views using ``clear()`` to save memory.

Using setImageDrawable isn't a reliable way of clearing out View's resources (at least not those loaded by Glide) in either v3 or v4, there's no behavior change there. See the second half of http://bumptech.github.io/glide/doc/getting-started.html#listview-and-recyclerview.

**Comment by stephanenicolas** [comment]
@sjudd I guess we can close the issue now. It will probably serve as a hub for everyone wondering the same question as we did. 

Thanks for yor answers and the links to the docs.
