### ISSUE TITLE
Link to Simplified Chinese documentation

### ISSUE THREAD

**Issue by Muyangmin** [bumptech/glide#2377]
I've translated the documentation of Glide v4.x into **Simplified Chinese**, as mentioned before in #2336 . Now it's deployed on GitHub：[glide-docs-cn](https://muyangmin.github.io/glide-docs-cn/index.html). 

Though there are still some dead link issue(and I'm working on fixing them), can we add a link to it in somewhere of Glide main repo?  I want more people to see this doc as early as possible. If a Pull Request is required, I can do it.

**Comment by sjudd** [comment]
Looks good!

The one issue I saw was I think what you're referring to as the dead links, the bottom of most of the pages have the reference urls visible. That's not blocking though.

We can: 
1. Put a link to this version in the existing docs page (maybe in a header?)
2. Add the link to the readme at the top of the page next to the existing docs page
3. 1 and 2?

**Comment by sjudd** [comment]
Also I should ask - are you interested in maintaining this moving forward? I try to add documentation when I see a question a few times and it ends up changing pretty frequently.

**Comment by Muyangmin** [comment]
I've done some research for it today, there are 3 type links in pages: 
1. absolute link, like `https://developers.android.com/XXX` - this type now woking as expected.
2. relative link, like `doc/download-setup.html` - this should work, but now get 404 due to the different path, and it can be fixed by change the path.
3. link starts with {{ site.url }} - this type is the most difficult.  These links cannot be recognized as valid URL so the Markdown renderer just render the raw text -- that's what we saw now at the bottom of pages.

Although Hexo support [tag plugins](https://hexo.io/docs/tag-plugins.html) to provide similar grammar to generate links, unfortunately  **my doc site address is not same as glide site**.  So I think maybe the best solution is to change those {{site.url}} into an absolute site address, IE:
```Markdown
//Before
[1]: {{ site.url }}/glide/javadocs/400/com/bumptech/glide/load/Option.html
//After
[2]: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/load/Option.html
```

If there is a way to define a global variable `site.url` in hexo's `_config.yml` and refer it in pages, that would be the best solution. But I didn't found that yet. 

Do you have any better ideas?

**Comment by Muyangmin** [comment]
Of course I'm very pleased to continuously maintain this in the future.  I'll also try to contribute codes if I can :stuck_out_tongue_closed_eyes:

**Comment by sjudd** [comment]
Yeah you can probably run sed s/{{ site.url }}/http:\/\/bumptech.github.io/glide/g, that's reasonable enough if you want to link directly to Glide's documentation.

We only use {{ site.url }} because the site is actually visible at sjudd.github.io in addition to bumptech.github.io.

**Comment by Muyangmin** [comment]
I have changed the Chinese documentation engine to `jekyll`, to keep better consistency of this official repo(Thanks for help by @vincgao  ). Now the [Chinese documentation](https://muyangmin.github.io/glide-docs-cn/) is totally available and looks very closed to bumptech.io!

**Comment by Muyangmin** [comment]
### Conclusion before closing this issue

Now Chinese documentation is available and is already linked in both [glide repo's README](https://github.com/bumptech/glide) and [glide documentation](http://bumptech.github.io/glide).

 **For Chinese user who see this issue later**(e.g. see this by searching `Chinese`, `中文`, `文档`, etc)**, you can directly visit [here](https://muyangmin.github.io/glide-docs-cn), and [contribute to it](https://github.com/Muyangmin/glide-docs-cn) if you'd like to.**

**For how to link to other language translation version, please see PR #2409 .**

Thanks for @vincgao and @sjudd again for their suggestion and works.
