### ISSUE TITLE
Images Loaded from storage are not fully clear

### ISSUE THREAD

**Issue by mufad** [bumptech/glide#2380]
**Glide Version**: 3.7.0

**Integration libraries**: PhotoView

**Device/Android Version**: One Plus X, 5.0.1

**Issue details / Repro steps / Use case background**:  I'm trying to load an image from internal storage to PhotoView, but it gets all blurry

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(Gallery.this).load(currentFile).override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).into(singleImageView);
```

**Comment by sjudd** [comment]
Maybe attach a screen shot? What is the width/height, layout params, padding, and scale type of ``singleImageView``?
