### ISSUE TITLE
is safe use Glide in Async to load a bitmap ? 

### ISSUE THREAD

**Issue by ncaferra** [bumptech/glide#2381]
**Glide Version**: 3.8.0

Hi,
i currently use Glide with no issues, but i have a complex use case and i would like to discuss with you before I implement it in my application.
I have a background thread (asynctask) instanced by a JobService (new Android API for scheduled task). This service/background thread is completely separate from activity and is scheduled each 24h~. In this background thread i need to load a bitmap using a specific height/width. I'm currently using android guidelines to load bitmap (https://developer.android.com/topic/performance/graphics/load-bitmap.html), but i don't like using inSampleSize method (a lot of OOR still occurring). 
My question is : is safe (and correct) to use Glide to load bitmap from an asynctask ? Is this piece of code correct ? 

```java
Bitmap bitmap = Glide
                    .with(context)
                    .load(.....)
                    .asBitmap()
                    .centerCrop()
                    .into(WIDTH, HEIGHT)
                    .get() 
```

Thanks a lot for your help :-)

**Comment by sjudd** [comment]
Sure that's perfectly safe if you need to obtain and use a Bitmap on a background thread. Just make sure you pass in the application context to ``Glide.with()`` to avoid memory leaks.

**Comment by ncaferra** [comment]
ok, thanks a lot. 
I'm trying to download a 6000x4000 bitmap from an url. I've used

Bitmap bitmap = Glide
.with(context)
.load(.....)
.asBitmap()
.centerCrop()
.into(2000, 1000)
.get()

but bitmap.getWitdh is different from desidered value (2000), am i missing something ? I would like to download and resize to a specific height/width

**Comment by sjudd** [comment]
What width and height do you actually get? into(2000, 1000) and centerCrop() should generate an output Bitmap that's 2000x1000

**Comment by ncaferra** [comment]
my mistake (i was missing center crop). it works perfectly
