### ISSUE TITLE
how to get loaded image width and height in Glide v4

### ISSUE THREAD

**Issue by SIARAY** [bumptech/glide#2386]
hi,
how i can get loaded image width and height (orginal size) in Glide v4?

**Comment by TWiStErRob** [comment]
#781 + http://bumptech.github.io/glide/doc/migrating.html#using-modelloader-streammodelloader should help.

**Comment by SIARAY** [comment]
Unfortunately, I did not know exactly how to do it.
May you explain more? Because some of the codes written #781 are not working in Glide v4.
