### ISSUE TITLE
circleCrop() with margin

### ISSUE THREAD

**Issue by Dahnark** [bumptech/glide#2390]
Hello, I would like to circleCrop() my image with a determined margin instead of circleCrop() at border

Circle image without margin:
![image](https://user-images.githubusercontent.com/7463564/30409034-cd8cbff2-9902-11e7-97c3-866a4192b9b0.png)

Circle image with margin
![image](https://user-images.githubusercontent.com/7463564/30409051-e6377286-9902-11e7-8930-d2fec73a8196.png)

How can I do this?

**Comment by sjudd** [comment]
You can write your own transformation. CircleCrop is here as an example: https://github.com/bumptech/glide/blob/b2fb2297dcd64398a9415677b6d566648d52a7a1/library/src/main/java/com/bumptech/glide/load/resource/bitmap/CircleCrop.java
