### ISSUE TITLE
Downsampler#decodeStream return null on some phone for some image

### ISSUE THREAD

**Issue by NamekMaster** [bumptech/glide#2392]
**Glide Version**: 3.8.0

**Integration libraries**: okhttp or not

**Device/Android Version**: fails on Galaxy Note4 SM-N9108V 6.0.1, works fine on HTC U-1w 7.0

**Issue details / Repro steps / Use case background**: 
I try to load an image use Glide from a url, or just put it into assets folder, or use a single ImageView with src="@drawable/xxxx", the image doesn't shown on Galaxy Note 4, but it works fine on my HTC u1w.
I debug into the source code and found the reason is in class Downsampler#decodeStream, ` BitmapFactory.decodeStream(is, null, options);` returns null.  I don't know why, I found a [post](http://www.gitshah.com/2011/05/fixing-skia-decoder-decode-returned.html) about this, and I copy OkHttp integration into my project and modify the class `OkHttpStreamFetcher`, change the end of the method `loadData`  to return a wrapped inputStream, but it's also not working.
The image is attached below. I also copy this image file to Galaxy Note4, open it in file manager, it only show a black window, but this image can open in the browser of my computer, and charles can also show it ,so I supposed it is a well formatted image.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this).load("url is here")
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        return false;
                    }
                })
                .into((ImageView) findViewById(R.id.image));
```

**Layout XML**:
```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:visibility="invisible"
    tools:visibility="visible">

    <ImageView
        android:id="@+id/thumb"
        android:layout_width="160dp"
        android:layout_height="90dp"
        android:layout_marginBottom="@dimen/activity_vertical_margin"
        android:layout_marginLeft="@dimen/activity_horizontal_margin"
        android:layout_marginRight="@dimen/activity_horizontal_margin"
        android:layout_marginTop="@dimen/activity_vertical_margin"
        android:background="@android:color/black"
        android:scaleType="matrix" />
</LinearLayout>
```

**Stack trace / LogCat**:
This is the only different log I compared between the other image which can load normally and this.
```ruby
skia: --- decoder->decode returned false
```

**Comment by NamekMaster** [comment]
It looks like github change the image format of my uploaded, so I upload it again.
[vmflat.jpeg.zip](https://github.com/bumptech/glide/files/1301831/vmflat.jpeg.zip)

**Comment by sjudd** [comment]
Simplest test is to add the file to assets or the raw folder and try to decode it with BitmapFactory directly. If BitmapFactory.decode returns null or an invalid Bitmap, that's why Glide can't load it.

**Comment by NamekMaster** [comment]
> Simplest test is to add the file to assets or the raw folder and try to decode it with BitmapFactory directly. If BitmapFactory.decode returns null or an invalid Bitmap, that's why Glide can't load it.

It's only return null on some phone , on my test, it's not work on Galaxy Note4 6.0 and works fine on HTC U1w 7.0, so it should be a valid bitmap I think.

**Comment by sjudd** [comment]
I'm not sure there's much we can do if just passing an InputStream or file path into BitmapFactory fails on a particular device. Glide doesn't include its own decoders, other than for GIFs, so we're dependent on the framework. 

We've been able to work around a few bugs in certain decoders in the framework that might cause failures, like webp images, but all of those were edge cases that didn't happen if you just passed in the complete image to BitmapFactory directly.

**Comment by MarsDemon** [comment]
Excuse me, did you solve your problem? I also met

**Comment by GYingchao** [comment]
also met in Moto G3

**Comment by NamekMaster** [comment]
I noticed people still ask for solution even almost a year past, so I think I should describe how I solved this problem. This is definitely not a Glide error, you can check whether the image witch you try to show is in a correct format by using some command line tools, unfortunately I forgot the tool's name. The picture which I uploaded above is not in a correct form after I checked it. I guess some version of the decode method doesn't tolerant invalid images. So I just ask the server side to check whether their function is work fine because the image was generated by themselves and the problem is solved. If you are using a image file that embed inside your app, you should change a correct one instead of finding another decoder. I hope this will help someone.

**Comment by GYingchao** [comment]
Thanks @NamekMaster. To share my searching effort, I found someone said if the color code of the decoding image is CMYK, which android does not support, decodeStream would return null directly. While I checked the target image format using [ImageMagick](https://www.imagemagick.org/script/index.php), there was no abnormal params found til now
