### ISSUE TITLE
findBugs report "defines clone() but doesn't implement Cloneable"

### ISSUE THREAD

**Issue by bingoogolapple** [bumptech/glide#2394]
**Glide Version**: 4.1.1

**Stack trace / LogCat**: ![image](https://user-images.githubusercontent.com/8949716/30429967-12a9fd64-998c-11e7-91d5-510d58151d98.png)

**Comment by sjudd** [comment]
Interesting, both of these classes do actually implement Cloneable because they extend RequestOptions and RequestBuilder, both of which implement Cloneable.
