### ISSUE TITLE
RGB_565 is used in GIFs by default

### ISSUE THREAD

**Issue by HeSuxiang** [bumptech/glide#2396]
**Glide Version 4.1.1**:

**not use integration library **:

**Coolpad/7320 4.2.2**:

** the default DecodeFormat is still DecodeFormat.PREFER_RGB_565, the gif turn to green, but in glide 3.7,  when you config it to ARGB_8888 , the gif isn't trun to green**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```@GlideModule
public class MyAppGlideModule extends AppGlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // nothing here
    }
}
```

**Layout XML**:
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:background="@color/list_background"
    >
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:background="@drawable/list_item_shape"
        android:layout_margin="5dp"
        >

 <ImageView
        android:id="@+id/imageView1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:paddingLeft="16dp"
        android:paddingRight="16dp"
        android:layout_gravity="center"
        android:scaleType="fitXY"
        android:adjustViewBounds="true"/>
    </LinearLayout>
</LinearLayout>
```

<!--
What is the error message that you got in the log?
You can find some help on diagnosing issues here: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
-->
**LogCat**:
``` E/Parcel: Reading a NULL string not supported here.
this LogCat was show in glide 3.7.0 too, but everything is ok.
```

**Comment by sjudd** [comment]
Gifs always prefer RGB_565 unless the frames are actually transparent: http://google3/third_party/java_src/android_libs/glide/third_party/gif_decoder/src/main/java/com/bumptech/glide/gifdecoder/StandardGifDecoder.java?l=780&rcl=155115287
