### ISSUE TITLE
how to get GifDecoder from GifDrawable?

### ISSUE THREAD

**Issue by berrytao7** [bumptech/glide#2397]
hello ,
my glide version now is 4.1.1,
before ,it is 3.8.0.
I want to know how to get GifDecoder for GifDdrawable in 4.1.1?
in 3.8.0 it is like this:
GifDecoder decoder = gifDrawable.getDecoder();
 but now cannot find getDecoder method.

**Comment by sjudd** [comment]
In short, you can't.

Out of curiosity, what are you using the GifDecoder for?

**Comment by berrytao7** [comment]
I want to get the end of playing gif,
and then ,do something。
Is it has any method for this in Glide 4.1.1?

**Comment by sjudd** [comment]
What do you mean by gt the end of playing gif? 

GifDrawable does have an API, but beyond that nothing is exposed by default. If you have a use case that is generally useful, please feel free to create a pull request to expand GifDrawable. If not, you could write your own ResourceDecoder that returns an extension of GifDrawable that exposes whatever you need.

**Comment by berrytao7** [comment]
got it! Thanks

**Comment by ScreamingHawk** [comment]
I realise this issue is closed, but I too have this use case. 

I want to set the number of loops of a GIF depending on the length of time the GIF runs for. 

e.g. If it's a long GIF play once. If it's short play twice.

**Comment by niuyunedu** [comment]
I want to do something like @ScreamingHawk does,  and I  had the same problem. 
Maybe I can write a class that extends GifDrawable to solve my problem, but I don't know how to do it.

`public class MyGifDrawable extends GifDrawable {

	private final GifDecoder gifDecoder;

	public MyGifDrawable(Context context,
	                     GifDecoder gifDecoder,
	                     Transformation<Bitmap> frameTransformation,
	                     int targetFrameWidth,
	                     int targetFrameHeight,
	                     Bitmap firstFrame) {
		super(context, gifDecoder, frameTransformation, targetFrameWidth, targetFrameHeight, firstFrame);
		this.gifDecoder = gifDecoder;
	}

	public GifDecoder getGifDecoder() {
		return gifDecoder;
	}
}
`

Is any way to load a gif file as MyGifDrawable ?

**Comment by sjudd** [comment]
@niuyunedu You'd also need to write a `ResourceDecoder` and register it. http://bumptech.github.io/glide/doc/configuration.html#registering-components might be helpful.

**Comment by niuyunedu** [comment]
@sjudd Thank you!
