### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by renkchina** [bumptech/glide#2398]
Log:
```
 Rejecting class com.bumptech.glide.load.resource.gif.GifResourceDecoder$GifDecoderPool because it failed compile-time verification (declaration of 'com.bumptech.glide.load.resource.gif.GifResourceDecoder$GifDecoderPool' appears in /data/app/love.edriving-1/base.apk)
at com.bumptech.glide.load.resource.gif.GifResourceDecoder.<clinit>(GifResourceDecoder.java:29)
                                                               at com.bumptech.glide.load.resource.gif.GifDrawableLoadProvider.<init>(GifDrawableLoadProvider.java:27)
                                                               at com.bumptech.glide.Glide.<init>(Glide.java:226)
```
Code:
```java
 private static final String imagePath ="http://www.renk.top/";
    public static void loadImages(Context context, ImageView imageView, String url) {
        if (context != null) {
            if (TextUtils.isEmpty(url)) {
                url = "http://www.bz55.com/uploads/allimg/150701/140-150F1142638.jpg";
            }
            if (url.startsWith("http")) {
                Glide.with(context).load(url).into(imageView);//error position
            } else {
                Glide.with(context).load(imagePath + url).into(imageView);
            }
        }
    }
```
gradle:
```gradle
    compile 'com.github.bumptech.glide:glide:4.1.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'
```

**Comment by sjudd** [comment]
That's a reference to the v3: https://github.com/bumptech/glide/blob/211c4dbd79d92dcc56f186d0dd8b50849f9236ff/library/src/main/java/com/bumptech/glide/load/resource/gif/GifResourceDecoder.java#L29. There is no GifDecoderPool in v4.

Are you using both dependencies at the same time? Or do you have a transitive dependency on v3? If so, that explains the error.

**Comment by renkchina** [comment]
I didn't use two dependencies, I had V3 upgraded to V4, and I reported this error. I tried to load the image network using okhttp, but I didn't succeed,

**Comment by sjudd** [comment]
If you look through your dependencies, you'll probably find one that depends on Glide v3. 

I believe you can list them with ./gradlew :app:configurations (depending on your project structure).

**Comment by TWiStErRob** [comment]
@sjudd It's `gradlew :app:dependencies --configuration compile` (or `implementation` depending on your Android plugin version)

**Comment by sjudd** [comment]
Thanks @TWiStErRob

**Comment by renkchina** [comment]
I added V4 dependency once all the glide dependencies in the project were deleted. I also made the same mistake. I searched the whole world and found no other references.what's the solution。

**Comment by renkchina** [comment]
I found the problem, but I couldn't solve it. This is the case because when I first referenced V3, it was normal. Then you change version V4. Once again, this error occurs. It doesn't work whether or not you switch back to the original version.
