### ISSUE TITLE
LruCache Syncronized Question

### ISSUE THREAD

**Issue by skauss** [bumptech/glide#2399]
Hi,
we use Glide 4.0.0 and have some times the feeling we have the wrong picture on screen.
Also I have seen some concurrency exception using the LruCache

We use the Glide LruCache were the cache is
  `  private final LinkedHashMap<T, Y> cache = new LinkedHashMap<>(100, 0.75f, true);`

Would it be better to use 
`private final LinkedHashMap<T, Y> cache = Collections.synchronizedMap(new LinkedHashMap<>(100, 0.75f, true));
`

Regards
Stephan

**Comment by sjudd** [comment]
The LRU cache is only accessed on the main thread, so it doesn't need to be synchronized: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/Engine.java#L160.

If you're seeing exceptions, please provide the stack trace.
