### ISSUE TITLE
Add a preloader for RecyclerView

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#240]

**Comment by Charrondev** [comment]
Is it possible to hack around and preload images in a recycler view with this right now?

**Comment by vipinhelloindia** [comment]
+1

**Comment by sjudd** [comment]
Absolutely, you just need to call the existing preloader's [``onScroll``][1] method will all of the required values other than the ``AbsListView``. If you're using LinearLayoutManager or GridLayoutManager, you can use this gist: https://gist.github.com/sjudd/0776594543c4b6c30d38

[1]: http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/ListPreloader.html#onScroll(android.widget.AbsListView,%20int,%20int,%20int)

**Comment by Saketme** [comment]
This would be wonderful. I'm currently manually calling Glide on each item inside the adapter, but this looks cleaner.

**Comment by sjudd** [comment]
@Saketme You'd still need to call Glide on each item in the adapter. The preloader only loads items into memory, not into views. The preloader is a performance improvement that prevents users from seeing images loading while they scroll (assuming the images can be loaded at least as fast as the user is scrolling). 

Without the preloader, since you only request images when the view is rendered, the image doesn't start loading until the user can see the view, and so the user will always see a loading indicator.

**Comment by Saketme** [comment]
@sjudd That's exactly what I'm doing. Sorry if I wasn't clear enough, but I'm currently calling Glide only to preload them into memory using downloadOnly() :D

**Comment by TWiStErRob** [comment]
This should be fixed in https://github.com/bumptech/glide/tree/master/integration/recyclerview
