### ISSUE TITLE
Can i cache multiple scaleType of thumbnail in advance?

### ISSUE THREAD

**Issue by zhangchaojiong** [bumptech/glide#2402]
>  I have a question . can i set `centerCrop ` and ` override(80, 80) ` as thumbnail setting. and then ,when i load full image, i want to display `fitCenter ` and  `override(80, 80)` of thumbnails as transition.
> Is it possible to do it?

example:
```
load thumbnail  code:
 Glide.with(context)
                    .load(uri)
                    .override(80, 80)
                    .centerCrop()
                    .crossFade()
                    .into(iconview);
load full image code:
  Glide.with(ImagePagerDialogFragment.this)
                    .load(path)
                    .thumbnail(Glide.with(ImagePagerDialogFragment.this)
                            .load(path) 
                            .override(80, 80) // size has to match
                            .fitCenter()// model has to match
                    ) .into(iconview);
```

> If can not do it, can i be cache `fitCenter `thumbnail in advance？

**Comment by TWiStErRob** [comment]
You can cache anything with [`.preload(...)`](http://sjudd.github.io/glide/javadocs/380/com/bumptech/glide/GenericRequestBuilder.html#preload(int,%20int))

**Comment by TWiStErRob** [comment]
Btw, I'm not sure where you copied the code, but the comments should be:
```
.load(path) // model has to match
.override(80, 80) // size has to match
.fitCenter() // transformation has to match
```

**Comment by zhangchaojiong** [comment]
Thank you  very much ！i got it.
