### ISSUE TITLE
UncaughtThrowableStrategy API / extension 

### ISSUE THREAD

**Issue by stephanenicolas** [bumptech/glide#2403]
In our crash reporting tool, we can see this:

![image](https://user-images.githubusercontent.com/1832925/30516489-adaee8dc-9af5-11e7-85ed-8d481e56c4a9.png)

The threads created by GlideExecutor thread factory crash, mostly because of OOMs, but they actually crash the app and are caught by the crash reporting general uncaught exception handler.

It would be valuable for us to be able to pass a custom UncaughtExceptionStrategy to the glide executor, that would simply log the crash, without crashing the app. Our app can live with an image that could not be loaded.

Is it possible to create an API so that we can use a custom error handler here:
https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java#L349

If you agree with this feature, we will gladly contribute a PR for it.

**Comment by sjudd** [comment]
Yeah I think that's totally reasonable.

You could probably work around it with sufficient hackery in a default uncaught exception handler, but you'd probably have to do ugly things like assume the names of the threads Glide creates.

Go for it, thanks for offering.
