### ISSUE TITLE
isFromMemoryCache analog in v4

### ISSUE THREAD

**Issue by vasskob** [bumptech/glide#2408]
Halo guys. Sorry about this issue, but I'm currently looking for an analog of isFromMemoryCache boolean field in RequestListener onResourceReady callback in Glide v4. Can you help me with it? I`m trying to migrate from v3 to v4. My v3  source code looks like this 
```
@Override
public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
                            if (!isFromMemoryCache || !isFirstResource) marker.showInfoWindow();
                            return false;
                        }
```
Thanks for your advice!

**Comment by TWiStErRob** [comment]
`DataSource.MEMORY_CACHE`?

**Comment by vasskob** [comment]
This is what I'm looking for. Thanks a lot!
