### ISSUE TITLE
Glide v4 conflict with 'com.neenbedankt.android-apt'

### ISSUE THREAD

**Issue by franticn** [bumptech/glide#2410]
when i annotate everything about 'com.neenbedankt.android-apt',GlideApp can be generated normally.But if i cancel annotate about 'com.neenbedankt.android-apt' GlideApp can not find ;

**Comment by TWiStErRob** [comment]
Is there any reason to not use the Android Gradlew plugin's `annotationProcessor` instead of a third party plugin?
