### ISSUE TITLE
Load local video memory overflow

### ISSUE THREAD

**Issue by wang869755676** [bumptech/glide#2414]
SIGSEGV(SEGV_MAPERR)
                                                             0x24
                                                             #00  pc 0004c18e  /system/lib/libdvm.so [armeabi-v7a::8be7596e35ee9b6689d339f53181f94e]
                                                             #01  pc 000125ed  /system/lib/libmedia_jni.so [armeabi-v7a::db6df068e4ded2d9a457e860da15df98]
                                                             #02  pc 0001ab65  /system/lib/libmedia_jni.so [armeabi-v7a::db6df068e4ded2d9a457e860da15df98]
                                                             #03  pc 0001e44c  /system/lib/libdvm.so (dvmPlatformInvoke+112) [armeabi-v7a::8be7596e35ee9b6689d339f53181f94e]
                                                             #04  pc 0004e913  /system/lib/libdvm.so (_Z16dvmCallJNIMethodPKjP6JValuePK6MethodP6Thread+398) [armeabi-v7a::8be7596e35ee9b6689d339f53181f94e]
                                                             #05  pc 00027860  /system/lib/libdvm.so [armeabi-v7a::8be7596e35ee9b6689d339f53181f94e]
                                                             #06  pc 0002bdf8  /system/lib/libdvm.so (_Z12dvmInterpretP6ThreadPK6MethodP6JValue+184) [armeabi-v7a::8be7596e35ee9b6689d339f53181f94e]
                                                             #07  pc 00060a89  /system/lib/libdvm.so (_Z14dvmCallMethodVP6ThreadPK6MethodP6ObjectbP6JValueSt9__va_list+292) [armeabi-v7a::8be7596e35ee9b6689d339f53181f94e]
                                                             #08  pc 00060ab3  /system/lib/libdvm.so (_Z13dvmCallMethodP6ThreadPK6MethodP6ObjectP6JValuez+20) [armeabi-v7a::8be7596e35ee9b6689d339f53181f94e]
                                                             #09  pc 00055823  /system/lib/libdvm.so [armeabi-v7a::8be7596e35ee9b6689d339f53181f94e]
                                                             #10  pc 0000cb58  /system/lib/libc.so (__thread_entry+72) [armeabi-v7a::a151b2cd01b3e8338e59026c77004104]
                                                             #11  pc 0000ccd4  /system/lib/libc.so (pthread_create+208) [armeabi-v7a::a151b2cd01b3e8338e59026c77004104]
                                                             java:
                                                             java.lang.Thread.parkFor(Thread.java:1205)
                                                             sun.misc.Unsafe.park(Unsafe.java:325)
                                                             java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
                                                             java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
                                                             java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:505)
                                                             java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
                                                             java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
                                                             java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                             java.lang.Thread.run(Thread.java:841)
                                                             com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
                                                             java pending exception:
                                                             [Native crash above happened with a java pending exception as following]
                                                             java.lang.OutOfMemoryError
                                                             android.graphics.Bitmap.createBitmap(Bitmap.java:726)
                                                             android.graphics.Bitmap.createBitmap(Bitmap.java:703)
                                                             android.graphics.Bitmap.createBitmap(Bitmap.java:670)
                                                             android.media.MediaMetadataRetriever._getFrameAtTime(Native Method)
                                                             android.media.MediaMetadataRetriever.getFrameAtTime(MediaMetadataRetriever.java:243)
                                                             android.media.MediaMetadataRetriever.getFrameAtTime(MediaMetadataRetriever.java:296)
                                                             com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:131)
                                                             com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:24)
                                                             com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
                                                             com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
                                                             com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
                                                             com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                             com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                             com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:457)
                                                             com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:450)
                                                             com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:436)
                                                             com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:390)
                                                             com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:359)
                                                             com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
                                                             com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:48)
                                                             com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                             com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
                                                             com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:398)
                                                             com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(De

**Comment by Muyangmin** [comment]
Cause stack of OutOfMemoryError are often not accurate, is there any potential memory leak in your app? Or have you reproduce this error with same video in a small sample project? 

In addition, please provide details **as issue template comments described** (glide version, integration, device, etc).

**Comment by sjudd** [comment]
See also: http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors

**Comment by wang869755676** [comment]
I just close the cache,it works
