### ISSUE TITLE
Glide uses custom SimpleTarget to load network pictures and sets fillet not in effect

### ISSUE THREAD

**Issue by zrg1215** [bumptech/glide#2415]
I used the glide to load the image, respectively, set the centerCrop and fillet. I use Glide.into (ImageView) image to show rounded corners, but use Glide.into (SimpleTarget) picture shows no fillet, how do I fix?
The Glide version is 3.7

**Comment by zrg1215** [comment]
Glide使用自定义的SimpleTarget加载网络图片，设置圆角不生效？
我在使用glide加载图片时，分别设置了centerCrop和圆角。我使用Glide.into(ImageView) 图片显示有圆角，但是使用Glide.into(SimpleTarget) 图片显示没有圆角，请问怎么解决？
Glide版本是3.7

**Comment by a1018875550** [comment]
try the v4.1
