### ISSUE TITLE
Apply custom options to transcoder

### ISSUE THREAD

**Issue by thibseisel** [bumptech/glide#2417]
**Glide Version**: 4.1.1

Hello, I'm using Glide to load a set of pictures from the Android Mediastore in a RecyclerView, along with colors that are extracted from each picture with the Android Palette API.
For that purpose, I defined the following classes : 
* PaletteBitmap to hold data
* PaletteBitmapResource the equivalent Glide Resource,
* PaletteBitmapTranscoder, that takes the loaded ResourceBitmap and generate its corresponding color palette.

Here is the code :
```java
// PaletteBitmap.java
public class PaletteBitmap {
    public final Bitmap bitmap;
    public final Palette palette;

    // Constructor omitted for brevity
}

// PaletteBitmapResource.java
public class PaletteBitmapResource implements Resource<PaletteBitmap> {
    private final PaletteBitmap paletteBitmap;
    private final BitmapPool bitmapPool;

   // This class is the Glide v4 equivalent of the one presented on the Wiki
}

// PaletteBitmapTranscoder.java
public class PaletteBitmaptranscoder implements Transcoder<Bitmap, PaletteBitmap> {
    private final BitmapPool bitmapPool;

    @Override public Resource<PaletteBitmap> transcode(Resource<Bitmap> toTranscode) {
        Bitmap bitmap = toTranscode.get();
        Palette palette = Palette.from(bitmap).generate();
        PaletteBitmap result = new PaletteBitmap(bitmap, palette);
        return new PaletteBitmapResource(result, bitmapPool);
    }
}

// MyGlideModule.java
@GlideModule
public class MyAppGlideModule extends GlideAppModule {
    @Override
    public void registerComponents(@Nullable Context context, @Nullable Glide glide, @Nullable Registry registry) {
        if (glide != null && registry != null) {
            registry.register(Bitmap.class, PaletteBitmap.class, new PaletteBitmapTranscoder(glide.getBitmapPool());
        }
    }
}

// Then in my Adapter
GlideApp.with(fragment).as(PaletteBitmap.class).load(mediastoreUri).into(new ImageViewTarget<PaletteBitmap>(holder.imageView) {
    @Override protected void setResource(PaletteBitmap resource) {
        // Set the bitmap and use the palette
    }
}); 
```

**This works fine.**
What I'd like to achieve is to specify custom options for the `Palette.Builder` defined in `PaletteBitmapTranscoder` *on a request basis*. I mean, something like that :

```java
GlideApp.with(fragment).as(PaletteBitmap.class).load(mediastoreUri)
        .apply(paletteConfig()
            .maximumColorCount(24)
            .withRegion(...))
        .into(...);
```

In Glide v3, I created a new `PaletteBitmapTranscoder` with my custom options and passed it to the `transcode` method of RequestBuilder. But in Glide v4, transcoders are registered one for all and shared for all requests.

My question is : Is it possible to do this with the Generated API ?
If yes, can you give me some hints on how to do it ?
If not, is there any other way to handle Palette with Glide that allow this behaviour ?

Thanks in advance, Glide is a great library.

**Comment by sjudd** [comment]
Not currently, I need to change the API of ResourceTranscoder to pass in Options like the other classes. I think that's straight forward, so I'll take a look.

**Comment by sjudd** [comment]
This will go out in 4.2, by the end of the month.

You can pass in a palette config as an option. For an example, you can take a look at the options in [``Downsampler``][2]. Basically ``Options`` is a map of Option keys to Object values. In your case you'll want a memory option since the results of ResourceTranscoders aren't written to disk.

Check out [``GlideExtension``][1] as well. It would allow you to inline your palette options into Glide's generated API, so you'd probably even be able to avoid the ``apply`` call.

[1]: http://bumptech.github.io/glide/doc/generatedapi.html#glideextension
[2]: https://github.com/bumptech/glide/blob/1b4a99a7e442cfb88f5b902d87cc4c988a310c42/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L54
