### ISSUE TITLE
Problem loading images on Marshmallow Devices

### ISSUE THREAD

**Issue by edurocks** [bumptech/glide#2418]
Good Afternoon,
I use Glide 4.1.1 on my project and I can show the image on every android verison and devices less on marshmallow devices especifically samsung s5 neo. Glide gives me this exception 

```
Load failed for http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/10.png with size [-2147483648x-2147483648]
  class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, DATA_DISK_CACHE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/10.png
      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
    Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, DATA_DISK_CACHE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/10.png
      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
    Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, DATA_DISK_CACHE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/10.png
      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
    Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/10.png
      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
    Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/10.png
      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
    Cause (6 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/10.png
      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
```
Why is this happening? I can´t figure it out why. Thanks.

**Comment by sjudd** [comment]
Do you see anything else in your logs? If you download the image in question and then just pass it to BitmapFactory directly without using Glide, does BitmapFactory decode a Bitmap successfully?

**Comment by edurocks** [comment]
No @sjudd if i try to load the image without Glide I can´t do it either at least on the marshmallow. Just this apears on my log. This is all the info glide gives to me. I will repost it.

W/Glide: Load failed for http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/11.png with size [906x360]
                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                      Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, DATA_DISK_CACHE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/11.png
                                                                        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                                        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                                        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                                      Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, DATA_DISK_CACHE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/11.png
                                                                        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                                        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                                        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                                      Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, DATA_DISK_CACHE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/11.png
                                                                        Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                                        Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
                                                                      Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/11.png
                                                                        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                                        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                                        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                                      Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/11.png
                                                                        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                                        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                                        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                                      Cause (6 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/11.png
                                                                        Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                                        Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}

This is all.

**Comment by sjudd** [comment]
You probably will see some BitmapFactory error logs (not in the GlideException). You should definitely see them if you just pass the image into BitmapFactory.

**Comment by edurocks** [comment]
When i try to decode the inputstream the bitmap always returning null.

**Comment by TWiStErRob** [comment]
Try to open the actual image, it's broken: http://appgalpqldweb01.cloudapp.net/MobileApi/api/images/11.png
missing the bottom half, probably a truncated file.

**Comment by edurocks** [comment]
Yes i know that @TWiStErRob but do you think it is related to that? That´s because the same image opens on another versions of Android. Strange. I really don´t know why.

**Comment by TWiStErRob** [comment]
Probably image decoding got stricter, bad images are not nice to be passed around anyway.

**Comment by edurocks** [comment]
Ok I will test it with a normal image. Hope this will not happen but in case it occurs do you have an ideia why?

**Comment by TWiStErRob** [comment]
I'm pretty sure it won't fail if you give it a well-formed PNG stream.

**Comment by edurocks** [comment]
I tworks @TWiStErRob . Thanks!!!!!"

**Comment by TWiStErRob** [comment]
So the takeaway here is that Android may or may not be able to process malformed images. Failure callback from Glide in this case is a reasonable response. If you want to magically handle partial/bad images you need to provide a decoder that can do that.

**Comment by edurocks** [comment]
Yes I provide a fallback image in case Android can´t load the image. Thanks.
