### ISSUE TITLE
Glide 4.0.0 加载圆角图片失败

### ISSUE THREAD

**Issue by wdza** [bumptech/glide#2421]
RequestOptions options = new RequestOptions();
        options.centerCrop()
                .placeholder(R.mipmap.ic_circle_default)
                .error(R.mipmap.ic_circle_default)
                .priority(Priority.HIGH)
                .transform(new GlideRoundTransform());

        Glide.with(context)//
                .load(url)//
                .apply(options)//
                .into(iv);

**Comment by DCRichards** [comment]
@wdza you'll need to provide more information on this or this will most likely be closed. If my translation is correct, the issue is 'Failed to load rounded picture'?

**Comment by didixyy** [comment]
i also have this problem，when i add placeholder  rounder pictuer is not work,
this, is my code 

  public static void loadRoundImage(final Context context, final ImageView target, final String url,
      final @DrawableRes int loadingRes, final @DrawableRes int errorRes, final int radius) {
    createRequestBuilder(context, url, loadingRes, errorRes).into(
        new BitmapImageViewTarget(target) {

          @Override protected void setResource(Bitmap resource) {
            RoundedBitmapDrawable circularBitmapDrawable =
                RoundedBitmapDrawableFactory.create(target.getContext().getResources(), resource);

            float radiusPix = Resources.getSystem().getDisplayMetrics().density * radius;

            circularBitmapDrawable.setCornerRadius(radiusPix);
            circularBitmapDrawable.setAntiAlias(true);
            target.setImageDrawable(circularBitmapDrawable);
          }
        });
  }


  private static RequestBuilder<Bitmap> createRequestBuilder(final Context context,
      final String url, final @DrawableRes int loadingRes, final @DrawableRes int errorRes) {
    RequestOptions options =
        RequestOptions.centerCropTransform().diskCacheStrategy(DiskCacheStrategy.RESOURCE);
    if (loadingRes != -1) options.placeholder(loadingRes);
    if (errorRes != -1) options.error(errorRes);
    return getRequestManager(context).asBitmap()
        .load(url)
        .transition(new BitmapTransitionOptions().crossFade())
        .apply(options);
  }

**Comment by didixyy** [comment]
i also have this problem ,when i need placeholder,roubder picture is not work
this is my code 


 public static void loadRoundImage(final Context context, final ImageView target, final String url,final @DrawableRes int loadingRes, final @DrawableRes int errorRes, final int radius) {
    createRequestBuilder(context, url, loadingRes, errorRes).into(
        new BitmapImageViewTarget(target) {

          @Override protected void setResource(Bitmap resource) {
            RoundedBitmapDrawable circularBitmapDrawable =
                RoundedBitmapDrawableFactory.create(target.getContext().getResources(), resource);

            float radiusPix = Resources.getSystem().getDisplayMetrics().density * radius;

            circularBitmapDrawable.setCornerRadius(radiusPix); 
            circularBitmapDrawable.setAntiAlias(true);
            target.setImageDrawable(circularBitmapDrawable);
          }
        });
  }

private static RequestBuilder<Bitmap> createRequestBuilder(final Context context,
      final String url, final @DrawableRes int loadingRes, final @DrawableRes int errorRes) {
    RequestOptions options =
        RequestOptions.centerCropTransform().diskCacheStrategy(DiskCacheStrategy.RESOURCE);
    if (loadingRes != -1) options.placeholder(loadingRes);
    if (errorRes != -1) options.error(errorRes);
    return getRequestManager(context).asBitmap()
        .load(url)
        .transition(new BitmapTransitionOptions().crossFade())
        .apply(options);
  }

**Comment by a1018875550** [comment]
you can see [this link]( http://blog.csdn.net/a1018875550/article/details/78133228 ) to solve your problem
and the [#1077](https://github.com/bumptech/glide/issues/1077)  explained the reason

**Comment by androidlli** [comment]
,,ԾㅂԾ,, Do not solve

**Comment by leon2017** [comment]
Hi,u can this setiing round ImageView:

`GlideApp.with(context)
                .asBitmap()
                .load(path)
                .dontAnimate()
                .placeholder(R.drawable.icon_place_holder_circle)
                .centerCrop()
                .error(R.drawable.icon_place_holder_circle)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(new BitmapImageViewTarget(imageView) {
                    @Override
                    protected void setResource(Bitmap resource) {
                        RoundedBitmapDrawable circularBitmapDrawable =
                                RoundedBitmapDrawableFactory.create(context.getResources(), resource);
                        float radiusPix = Resources.getSystem().getDisplayMetrics().density * radius;
                        circularBitmapDrawable.setCornerRadius(radiusPix);
                        circularBitmapDrawable.setAntiAlias(true);
                        imageView.setImageDrawable(circularBitmapDrawable);
                    }
                });`

and u can setting circler ImageView:

`      RequestOptions circleOptions = RequestOptions.circleCropTransform();
        RequestOptions options = new RequestOptions();
        options.dontAnimate()
                .placeholder(R.drawable.icon_user_avatar)
                .centerCrop()
                .error(R.drawable.icon_user_avatar)
                .diskCacheStrategy(DiskCacheStrategy.ALL);
        Glide.with(context)
                .load(path)
                .apply(options)
                .apply(circleOptions)
                .into(imageView);`

I hope I can help you，good luck!!!
