### ISSUE TITLE
Fix migration guide please

### ISSUE THREAD

**Issue by j-garin** [bumptech/glide#2422]
Hello. I am using the following version of Glide:
```
    compile 'com.github.bumptech.glide:glide:4.1.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'

```
I took the code from your 3->4 migration guide. It looks like this:
```
import com.bumptech.glide.load.resource.bitmap.CenterCrop;
import com.bumptech.glide.load.resource.bitmap.RoundedCorners;
[skipped]
			GlideApp.with(context).load(url)
					.placeholder(drawable)
					.error(drawable)
					.transforms(new CenterCrop(), new RoundedCorners(20))
					.into(ivProfilePhoto);

```
It doesn't compile as it expects me to pass an Array of Transformation<Bitmap> objects. Please fix the migration guide [here](http://bumptech.github.io/glide/doc/migrating.html).

**Comment by TWiStErRob** [comment]
Huh, I guess both of those `extends BitmapTransformation` which `implements Transformation<Bitmap>`, so the Java type inference gives you a `BitmapTransformation[]`.

@sjudd maybe there's a need for a specialized overload to cover this case? (it would also hide the generic array creation warning if it shows, because it's not a generic type)

**Comment by j-garin** [comment]
@TWiStErRob yes, both of those extend `BitmapTransformation`

**Comment by j-garin** [comment]
@TWiStErRob I have checked the generated API file and this method looks like this:
`  public GlideRequest<TranscodeType> transforms(Transformation<Bitmap>[] arg0) {`
I think it can be changed to 
`  public GlideRequest<TranscodeType> transforms(Transformation<Bitmap>... arg0) {`
Then the code from migration guide will compile. What do you think?

**Comment by sjudd** [comment]
This was fixed here I think: 56368d03f3c1688ca853794cbc26dc413f80d4e2

**Comment by j-garin** [comment]
@sjudd looks like it. do you have any estimates on when this fix will be released?

**Comment by sjudd** [comment]
You can follow: https://github.com/bumptech/glide/milestone/15
