### ISSUE TITLE
download + onlyRetrieveFromCache block

### ISSUE THREAD

**Issue by hackerwgf** [bumptech/glide#2428]
download image like this:
```java
GlideApp.with(context)
.download(imageUrl)
.submit();
```
and load it onlyRetrieveFromCache at the same time:
```java
new Thread(new Runnable() {
    @Override
    public void run() {
        try{
            GlideApp.with(context)
            .download(imageUrl)
            .onlyRetrieveFromCache(true)
            .submit()
            .get();
         }catch (Exception e){
             e.printStackTrace();
         }
    }
}).start();
```
then *.get()* will block

**Comment by sjudd** [comment]
.get() will block, yes. Is that what you were asking?

**Comment by hackerwgf** [comment]
So...why? I think *.onlyRetrieveFromCache(true)*, it means that if no cache file here, then throw exception or just return null something else.
I apologize for my bad English

**Comment by sjudd** [comment]
You still need to do I/O to check the disk cache and decode the image if it's present.

**Comment by hackerwgf** [comment]
I know it need time to do I/O stuff, maybe I did not express my meaning clearly.
In my situation, *.get()* will block by downloading the same *imageUrl*, not decoding or checking file.

A=*.download(imageUrl).submit()*
B=*.download(imageUrl).onlyRetrieveFromCache(true).submit().get()* in new thread
current situation:
start A >>>>>>downloading>>>>>>downloaded
start B >>>>>>blocking>>>>>>>>>got file

my expectation:
start A >>>>>>downloading>>>>>>downloaded
start B >>>>>>return error

**Comment by sjudd** [comment]
Ah, then start with: http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses. The Engine logs will tell you why there is/isn't a cache miss.

**Comment by hackerwgf** [comment]
The log is "Added to existing load ...", that's why *.get()* blocked.
Maybe I should take the time to read source code for In-depth understanding. 
*.onlyRetrieveFromCache(true)* makes me completely confused, especially the word **ONLY**. 
So now look, is there a way to check cache file without blocking caused by existing load, or check a  request status with url ?

**Comment by Caij** [comment]
load image from server, when the task is not completed,  load same url request image only from cache, why second request need block wait first request complete(file down)? i think second request need return null.

the source code from:

EngineKey key = keyFactory.buildKey(model, signature, width, height, transformations,
        resourceClass, transcodeClass, options);
EngineJob<?> current = jobs.get(key);
    if (current != null) {
      current.addCallback(cb);
      if (Log.isLoggable(TAG, Log.VERBOSE)) {
        logWithTimeAndKey("Added to existing load", startTime, key);
      }
      return new LoadStatus(cb, current);
    }

Can you add onlyRetrieveFromCache param to EngineKey？
