### ISSUE TITLE
Migrate to Android Plugin for Gradle 3.0.0

### ISSUE THREAD

**Issue by paour** [bumptech/glide#2429]
**Glide Version**: 4.1.1

**Integration libraries**: okhttp3, own implementation

**Device/Android Version**: 7

**Issue details / Repro steps / Use case background**: I'm building a library that uses Glide 4.
I've updated my build to use the [new style of dependency declarations](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations), declaring Glide as an `api` so as not to pollute my client apps' with Glide's classes and methods. However, this also means that the app does not automatically package Glide's dependency on `appcompat-v7`, because Glide declares that `com.android.support:appcompat-v7` is *provided*.

I'm not sure this declaration is valid anymore, since Glide explicitly uses support classes such as `import android.support.v4.util.ArrayMap`.

**Stack trace / LogCat**:
```
ClassNotFoundException android.support.v4.util.ArrayMap in com.bumptech.glide.GlideBuilder
```

**Comment by sjudd** [comment]
Fixed here: 963191a6554449531fd96feba6f85902b53af20a
