### ISSUE TITLE
he following dependencies on the compile classpath are found to contain annotation processor.

### ISSUE THREAD

**Issue by Nsikaktopdown** [bumptech/glide#2430]
Error:Execution failed for task ':app:javaPreCompileDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - auto-service-1.0-rc2.jar (com.google.auto.service:auto-service:1.0-rc2)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues. 

What version of Glide are you using? What version of gradle? Can you show your build.gradle file?
