### ISSUE TITLE
Placeholder is always visible when there is a transition

### ISSUE THREAD

**Issue by FabioGiulietti** [bumptech/glide#2433]
With Glide 4.1.1, In a recyclerview, when i load an image with a placeholder and a transition, the placeholder remain visible and stay below the image that has been downloaded.
If i remove the transition there aren't issues.

An example:

```java
@Override
    public void onBindViewHolder(ImageTextCellHolder holder, int i) {
        super.onBindViewHolder(holder, i);

        RequestOptions options = new RequestOptions();
        options.placeholder(R.drawable.photo_placeholder);

        Glide.with(getGridFragment())
                .load("http://dc942d419843af05523b-ff74ae13537a01be6cfec5927837dcfe.r14.cf1.rackcdn.com/wp-content/uploads/Android-logo.png")
                .transition(DrawableTransitionOptions.withCrossFade())
                .apply(options)
                .into(holder.getImageView());
    }
```

![untitled](https://user-images.githubusercontent.com/28961465/30852266-8196c180-a2ab-11e7-96d3-7a20c9af8e37.png)

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/transitions.html#common-errors
