### ISSUE TITLE
useing thumbnail（0.6f）and override（width，height）Load failed 

### ISSUE THREAD

**Issue by wei120698598** [bumptech/glide#2440]
useing thumbnail（0.6f）and override（width，height）Load failed 

 Load failed for /storage/emulated/0/微信图片_20170929160552.jpg with size [214x214]
                                                      class com.bumptech.glide.load.engine.GlideException: Expected to receive a Resource<R> with an object of class android.graphics.drawable.Drawable inside, but instead got null.

**Comment by Muyangmin** [comment]
@wei120698598 seems there are some wrong calls in your code, have your resolved it? If yes you can close this issue. Otherwise please show more details as issue template described.

**Comment by StephenMilone** [comment]
Not the op, but this happens to me where I do a refresh on a recyclerview, whose items contain imageviews loaded by Glide.  Haven't been able to make it occur in any other situation. 

The images load fine w/o error on activity creation, then after a refresh, the images still are fine, but the logs have this message.  Hope that helps.  Here's the glide code I use:

`RequestOptions options = new RequestOptions().centerCrop().diskCacheStrategy(DiskCacheStrategy.ALL);
GlideApp.with(context).load(imageUrl).apply(options).thumbnail(0.1f).into(imageView);`

**Comment by sjudd** [comment]
@StephenMilone What version of Glide are you using? Can you provide a full stack trace? Or a sample app that reproduces the problem?

**Comment by StephenMilone** [comment]
4.2.0 w/ okhttp3 integration.  There is no trace, just that one message comes in the logcat

`W/Glide: Load failed for https://{url}.png with size [25x25]
                                                          class com.bumptech.glide.load.engine.GlideException: Expected to receive a Resource<R> with an object of class android.graphics.drawable.Drawable inside, but instead got null.`

**Comment by sjudd** [comment]
I'm not able to reproduce this in the flickr sample app with that set of options and a Runnable that's posted once a second that calls notifyDataSetChanged.

If you find a way to reliably reproduce this, or can do so in a sample app please let me know.

**Comment by wei120698598** [comment]
sorry，I can't resolve it.
