### ISSUE TITLE
Glide 加载Uri资源问题

### ISSUE THREAD

**Issue by lyh857718490** [bumptech/glide#2442]
**Glide Version**:4.1.1

**Integration libraries**:okhttp3-integration

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 
content://media/external/images/media/51 是一张Gif图片，用下边的代码加载图片时，会加载成BitmapDrawable 。但是，在PageAdapter中,却又加载成了 GifDrawable。ps：RecyclerView中，也加载成了 BitmapDrawable

怎么会出现两种结果？？

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 GlideApp.with(context)
                .load(uri)
                .transition(DrawableTransitionOptions.withCrossFade()) //过渡动画
                .into(imageView)；
```

**Layout XML**:
```xml
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <ImageView
        android:id="@+id/image_iv"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:contentDescription="@null"
        android:scaleType="centerCrop"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</android.support.constraint.ConstraintLayout>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Muyangmin** [comment]
不清楚你是在何种情形下遇到了这种问题，或许你可以尝试使用 [asGif()](http://bumptech.github.io/glide/javadocs/410/com/bumptech/glide/RequestManager.html#asGif--) 或 [asBitmap()](http://bumptech.github.io/glide/javadocs/410/com/bumptech/glide/RequestManager.html#asBitmap--) 以确保最终结果是你想要的类型。 参见 [选择资源类型](https://muyangmin.github.io/glide-docs-cn/doc/options.html#选择资源类型) 。

Another tip: from your issue content I feel you can do normal read/write of English, so please try to use English in the next time. You can get more help from collaborators who don't speak Chinese. FYI: #2384

**Comment by lyh857718490** [comment]
Thanks.
This problem is caused by the device. On other devices, there is no problem.
