### ISSUE TITLE
Ignore Exif orientation

### ISSUE THREAD

**Issue by SeoJinHyuk** [bumptech/glide#2443]
how to ignore exif orientation?
help me.

no working #665

**Comment by TWiStErRob** [comment]
Need a bit more than "not working". What did you try, why is it not working? (crash, code not running, etc.) What's the stacktrace, if any? Also which version? Please use the [issue template](https://raw.githubusercontent.com/bumptech/glide/master/ISSUE_TEMPLATE.md); edit your OP and fill in the details.
