### ISSUE TITLE
Version 4.2.0 无法访问RequestOptionsGenerator$1

### ISSUE THREAD

**Issue by shfouc** [bumptech/glide#2451]
错误: 无法访问RequestOptionsGenerator$1
  错误的类文件: ...\libs\compiler-4.2.0.jar(com/bumptech/glide/annotation/compiler/RequestOptionsGenerator$1.class)
    类 RequestOptionsGenerator$1 的封闭方法属性错误
    请删除该文件或确保该文件位于正确的类路径子目录中。
错误: 无法访问RequestOptionsGenerator$1
  错误的类文件: ...\libs\compiler-4.2.0.jar(com/bumptech/glide/annotation/compiler/RequestOptionsGenerator$1.class)
    类 RequestOptionsGenerator$1 的封闭方法属性错误
    请删除该文件或确保该文件位于正确的类路径子目录中。
1 个错误

**Comment by TWiStErRob** [comment]
Please fill in the issue template, (and in English if possible).
