### ISSUE TITLE
Result of clearDiskCache?

### ISSUE THREAD

**Issue by hzsweers** [bumptech/glide#2454]
Currently, clearDiskCache is a bit of a black box. I understand the design of the cache is to be open ended, but it would be great to be able to know how much memory was reclaimed. Any thoughts around supporting this?

**Comment by TWiStErRob** [comment]
Do you mean how much disk space was reclaimed?

```java
File cacheDir = ...
long before = cacheDir.getFreeSpace();
Glide.get(this).clearDiskCache();
long after = cacheDir.getFreeSpace();
long freed = after - before;
```

`cacheDir` either set in GlideModule in your app, or simply `context.getCacheDir()` or `context.getExternalCacheDir()` depending on which factory you use, default is:
https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L328

**Comment by hzsweers** [comment]
fair point
