### ISSUE TITLE
PlaceHolder Issue:

### ISSUE THREAD

**Issue by arunramya** [bumptech/glide#2455]
Version 4.2.0 :

Glide.with(c)
                    .load(f.getPath())
                    .placeholder(new ColorDrawable(Color.BLACK))
                    .into(holder.imgv1);

placeholder cannot resolved ? please help me.

**Comment by biswajitpanday** [comment]
Before Last update it was working fine. But not on v 4.2.0.. Please help asap.

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

What error do you see? Or is the placeholder simply not visible?

**Comment by piratejason** [comment]
it looks like there is not any more placeholder

**Comment by sjudd** [comment]
Oh you mean the method is missing? If so that's a change in v4, not specifically in 4.2.0, see http://bumptech.github.io/glide/doc/migrating.html#requestoptions. If you want have the methods inlined, see the generated API: http://bumptech.github.io/glide/doc/generatedapi.html

**Comment by gongzelong0718** [comment]
http://bumptech.github.io/glide/doc/migrating.html#requestoptions

It is said that we use RequestOption to replace what we use placeholder in previous way.
