### ISSUE TITLE
How set the logLevel in case of using GeneratedApi GlideApp

### ISSUE THREAD

**Issue by afaucogney** [bumptech/glide#2457]
I need to setup Glide log level with code, but as the doc enforce, I'm using the GlideApp genetated api. How to define the loglevel with those constraint.

I just was able to setup loglevel with:
- adb
- GlideBuild that make no sense with GlideApp.

Thanks for helping

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/configuration.html#log-level
