### ISSUE TITLE
getData() is not showing in Android Studio

### ISSUE THREAD

**Issue by abhiccc5** [bumptech/glide#2460]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Please fill in more info! e.g. What are you doing? What is your setup? Which class? When is it not showing? Is it a compile error? Is it missing from autocomplete? Are you using annotation processing? Did you clean/build/gradle sync?
