### ISSUE TITLE
Skip caching into disk

### ISSUE THREAD

**Issue by dovahkiin98** [bumptech/glide#2463]
I want to load an image but not save it in the disk as cache, only in memory.

I used diskCacheStrategy(DiskCacheStrategy.NONE) but that made the image to always get downloaded while I want it to be saved in only memory, not skip saving.

**Comment by TWiStErRob** [comment]
What was the problem? Did you solve it?

Maybe helps: http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses
