### ISSUE TITLE
bug : Glide load failed when clear app cache and clearDiskCache

### ISSUE THREAD

**Issue by yxcSini** [bumptech/glide#2465]
**Glide Version**:4.2.0 and before

**Integration libraries**:OkHttp3 

**Device/Android Version**:All

**Issue details / Repro steps / Use case background**: 
1.Clear App Cache from system setting
2.Then call GlideApp.get(context).clearDiskCache() , that will cause a exception
log:
`W/DiskLruCacheWrapper: Unable to clear disk cache java.io.IOException: not a readable directory: /data/data/com.paisheng.example.pslib/cache/image_manager_disk_cache at com.bumptech.glide.disklrucache.Util.deleteContents(Util.java:55) at com.bumptech.glide.disklrucache.DiskLruCache.delete(DiskLruCache.java:660) at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.clear(DiskLruCacheWrapper.java:143) at com.bumptech.glide.load.engine.Engine.clearDiskCache(Engine.java:326) at com.bumptech.glide.Glide.clearDiskCache(Glide.java:498)`
3.Then call GlideApp.with(context).load(url).into(iv) , that will cause a exception
log:
`E/GlideExecutor: Request threw uncaught throwable java.lang.IllegalStateException: cache is closed at com.bumptech.glide.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:620) at com.bumptech.glide.disklrucache.DiskLruCache.get(DiskLruCache.java:409) at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.get(DiskLruCacheWrapper.java:75) at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:62) at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293) at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:260) at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at java.lang.Thread.run(Thread.java:841) at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)`

**Comment by dyfan** [comment]
我出现这个bug的原因是,前面我删除缓存的时候默认把应用的cache都删除了,接着又去删除Glide的磁盘缓存,抛出了这个异常,希望可以帮到你.

**Comment by sjudd** [comment]
Are you able to attach a sample app that can reproduce this? I'm not able to reproduce either the error attempting to clear the disk cache or a subsequent error using the disk cache.

It looks like you might have deleted the directory manually before calling ``clearDiskCache()``? Or cleared the cache directory for the application in settings?

**Comment by yxcSini** [comment]
That's right. I have cleared the cache directory for the application in settings before calling `clearDiskCache()`.  @sjudd
