### ISSUE TITLE
image not Load using Glide in topuchImageview from internal storage

### ISSUE THREAD

**Issue by DPatel02** [bumptech/glide#2466]
Hello,
i work with one image making application, in which i use glide for loading image, Recently change gradlebuild
compile 'com.github.bumptech.glide:glide:**3.7.0**' to  'com.github.bumptech.glide:glide:**4.1.1**'
my issue is i can not load image from phone memory or sdcards in to TouchImageview using glide.

Glide.with(getActivity()).
                 load(Uri.fromFile(new File(sdcard, "Download/xyz.jpg"))).
                 into(tiv_image_1);

please comment if any other solutions,
Please Help me out.
thank you.

**Comment by Debdeep009** [comment]
For the new api, use `RequestOptions` and set `DiskCacheStrategy`. You may apply those settings to a `RequestBuilder` or directly to your code and then use.

**Comment by sjudd** [comment]
What isn't working? See http://bumptech.github.io/glide/doc/migrating.html#requestoptions for the new API and http://bumptech.github.io/glide/doc/debugging.html for debugging.
