### ISSUE TITLE
Gif image frames spill into each other.

### ISSUE THREAD

**Issue by EGecius** [bumptech/glide#247]
I am creating an application that uses a lot of gifs in ListViews. What happens is that parts of gifs spill from one gif to another.

**Comment by paru0000** [comment]
hey EGecius, i am facing the same problem u faced ,ca u please share the sample code with me

**Comment by TWiStErRob** [comment]
@paru0000 make sure you try the latest [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots) version; it has a lot of GIF fixes.

**Comment by kmfish** [comment]
hi, I am facing the same problem too.
Glide version: 3.7.0 (3.8.0-SNAPSHOT same)
Android: 5.1 Meizu MX5

I use glide to load images of a album in a gridview, When first show the gridview, one of gridview items will did not display the content. Then, I scroll the gridview, the problem will be occur. Reproducible almost every time i try.

when gridview first show, one of items no conent show:
![device-2017-03-22-150812](https://cloud.githubusercontent.com/assets/518858/24186084/8b8be00e-0f11-11e7-8a6d-61f2e27b6760.png)

please notice the third rows first column in gridview:
![ezgif-1-177bf2137f](https://cloud.githubusercontent.com/assets/518858/24185782/f1f96c3c-0f0f-11e7-87a8-e6743a7e0771.gif)

**Comment by TWiStErRob** [comment]
@kmfish Do any of these grid items have the same url? Is it always the same image? Maybe the same position? (What happens if you reverse the bound list for example?)

**Comment by kmfish** [comment]
@TWiStErRob No same url in these items, But have same image in these.(some image be copied to different folder)
what do you mean "reverse the bound list"?
Some else, I found gridview adapter will call getView(0) many times(Thus load image 0 many times). So i want to try replace gridview to RecyclerView

**Comment by kmfish** [comment]
@TWiStErRob After I replace Gridview to RecyclerView, everything is ok. Don't have any problem for gif image.  But I don't understand why it like this.

**Comment by f0restgump92** [comment]
I can confirm this. 

I have couple of people with 5.0 devices reporting this, but i'm unable to reproduce it on 7.0.
I'm using Glide 3.7 as

`Glide.with(holder.itemView.getContext())
                .load(mItem)
.diskCacheStrategy(SOURCE)
                .into(holder.mAvatar);`

and also In Grid recycler view.
