### ISSUE TITLE
Question to BitmapTransformation

### ISSUE THREAD

**Issue by camino2007** [bumptech/glide#2480]
**Glide Version 4.1.1**:

Hey guys, 

I have a question about the Glide BitmapTransformation class. I've extended the BitmapTransformation to do some customization in the method
```java
protected Bitmap transform(@NonNull final BitmapPool pool, @NonNull final Bitmap toTransform, final int outWidth, final int outHeight){...}
```
Is it possible that the outWidth and/or the outHeight can be 0? Maybe when the visibility of ImageView is set to View.GONE? I did some researching but I'm still not sure about it. I appreciate any hint, thank you!

**Comment by sjudd** [comment]
outWidth and outHeight shouldn't be 0 if you're using just Glide's normal ViewTargets. If you use SimpleTarget and pass in a 0 width and height, then the size will be 0. If you're using some other custom target and call the callback from ``getSize`` with a 0 width and height, then the size will be 0 as well.

If you're only ever using Glide's standard Targets and you're not passing in 0 ever (including passing in ``view.getWidth()`` or ``view.getHeight()`` yourself), let me know and please provide your load lines/Targets.
