### ISSUE TITLE
4.2.0 - handle 2 bitmap in a target

### ISSUE THREAD

**Issue by ncaferra** [bumptech/glide#2481]
**Glide Version**: 4.2.0

Hello,
i'm migrating from 3.8 version to 4.2. 

I need to handle 2 bitmap in the same target. This is the use case : after the first bitmap is loaded i need to create a copy and apply a blur transformation to it, then i set (at the same time) the first bitmap (to a generic imageview) and use the second bitmap as background (in a different imageview).  

In version 3.8 i used the "transcoder" feature to handle 2 different Bitmap (in ResourceTranscoder.transcode() i loaded a new bitmap), in version 4.2 "transcoder" is gone. Can you suggest me how can i implement this feature using glide 4.2 ? (maybe "transcoder" method wasn't the best way to do it)

thanks,
nicola

**Comment by sjudd** [comment]
[``ResourceTranscoders``][2] were not removed. You just have to register them in a ``GlideModule``.

Assuming your ``ResourceTranscoder`` produces a distinct object, let's say ``TwoBitmaps.java``, you'd [register your ``ResourceTranscoder``][1] and then your load line would look like:

```java
Glide.with(fragment)
  .as(TwoBitmaps.class)
  .load(url)
  .into(new TwoBitmapImageViewTarget(imageView));
```

Where ``TwoBitmapImageVIewTarget`` is a custom ``Target`` implementation you define that  handles the two bitmaps. You could also use ``SimpleTarget`` if you're not loading into a ``View`` or ``ImageViewTarget`` if you are.

[1]: http://bumptech.github.io/glide/doc/configuration.html#registering-components
[2]: http://bumptech.github.io/glide/javadocs/420/com/bumptech/glide/load/resource/transcode/ResourceTranscoder.html

**Comment by ncaferra** [comment]
Ok, i have created a ResourceTranscoder and a Model class : 

`public class TwoBitmaps {

    private final Bitmap bitmap;
    private final Bitmap blurredBitmap;
}`

`public class TwoBitmapsModuleTranscoder implements ResourceTranscoder<Bitmap, TwoBitmaps> {

    private Context context;

    public TwoBitmapsModuleTranscoder(Context context) {
        this.context = context;
    }

    @Override
    public Resource<TwoBitmaps> transcode(Resource<Bitmap> toTranscode, Options options) {
        Bitmap bitmap = toTranscode.get();

        Resource<Bitmap> blurredBitmapResource = PixelUtils.blurBitmap(context, toTranscode.get(), 100, 1);
        TwoBitmaps twoBitmaps = new TwoBitmaps(bitmap, blurredBitmapResource.get());

        return new SimpleResource<>(twoBitmaps);
    }
}`

but i receive a null instance in my target. I'm loading the TwoBitmaps instance with : 
`GlideApp.with(this)
                        .as(TwoBitmaps.class)
                        .apply(options)
                        .load("URL")
                        .into(target);
`

target is a custom Target, extends ImageViewTarget<TwoBitmaps>


Am i missing somethng ?

**Comment by sjudd** [comment]
Are you registering your Transcoder? Do you see error logs? What do you mean by receive a null instance?

**Comment by ncaferra** [comment]
I'm registering transcoder with 

`
@GlideModule
public class TwoBitmapsModule extends AppGlideModule {
    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        registry.register(Bitmap.class, TwoBitmaps.class, new TwoBitmapsModuleTranscoder(context));
    }

    // Disable manifest parsing to avoid adding similar modules twice.
    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }
}`

is it correct ?? 

In my Target instance, in method setResource i receive a null isntance of TwoBitmaps class

**Comment by ncaferra** [comment]
it works now ! 

I was using 

```
 GlideApp.with(this)
      .as(TwoBitmaps.class) .apply(options) .load("URL") .into(target);
```

fixed with:
```
 Glide.with(this)
     .as(TwoBitmaps.class) .apply(options) .load("URL") .into(target);
```

i need to read carefully the doc the understand the differences between Glide and GlideApp. 

One more question. In my Transcoder i'm returning an instance of 
`new SimpleResource<>(twoBitmaps);`
Is it safe ? Do i need to implement a custom Resource and override the "recycle" method ? 
I'm currently looking at this piece of code in v3 glide doc (https://github.com/bumptech/glide/wiki/Custom-targets#palette-example ): 
```
public class PaletteBitmapResource implements Resource<PaletteBitmap> {
    private final PaletteBitmap paletteBitmap;
    private final BitmapPool bitmapPool;

    public PaletteBitmapResource(@NonNull PaletteBitmap paletteBitmap, @NonNull BitmapPool bitmapPool) {
        this.paletteBitmap = paletteBitmap;
        this.bitmapPool = bitmapPool;
    }

    @Override public PaletteBitmap get() {
        return paletteBitmap;
    }

    @Override public int getSize() {
        return Util.getBitmapByteSize(paletteBitmap.bitmap);
    }

    @Override public void recycle() {
        if (!bitmapPool.put(paletteBitmap.bitmap)) {
            paletteBitmap.bitmap.recycle();
        }
    }
}
```

**Comment by sjudd** [comment]
I'm surprised that there's a difference between GlideApp and Glide, I wouldn't expect one.

You should implement something more than SimpleResource so that your ``getSize()`` method returns the combined size of both your Bitmaps to avoid OOMs. You should also implement ``recycle()`` and so that you let Glide re-use your Bitmaps.

**Comment by ncaferra** [comment]
ok thanks.

in 3.x samples, recycle() method is implement in this way : 

```
@Override public void recycle() {
        if (!bitmapPool.put(paletteBitmap.bitmap)) {
            paletteBitmap.bitmap.recycle();
        }
    }
```

in 4.2, the method put() in bitmapPool is changed. I'm looking in BitmapResource.recycle() code, i'm currently using : 
```
    @Override
    public void recycle() {
        bitmapPool.put(twoBitmaps.getBitmap());
        bitmapPool.put(twoBitmaps.getBlurredBitmap());
    }
```

Is it correct ?
thanks for your help

**Comment by sjudd** [comment]
Yup that looks right.

 Basically the ``BitmapPool`` now does the recycle thing for you so we don't need those two lines copied everywhere.

**Comment by ncaferra** [comment]
Ok, thanks. Last question :D 

I'm trying to retrieve an instance of BitmapPool in Transcoder constructor using : 
```
 public TwoBitmapsModuleTranscoder(Context context) {
        this.context = context;
        this.bitmapPool = Glide.get(context).getBitmapPool();
    }
```

i receive this error at startup : 

> IllegalStateException: You cannot call Glide.get() in registerComponents(), use the provided Glide instance instead

I'm not able to find an example for v4 Glide (i'm currently using sample from v3 doc)

**Comment by sjudd** [comment]
Add the ``BitmapPool`` as a parameter in the constructor of your ``ResourceTranscoder``, then:

```java
@GlideModule
public class TwoBitmapsModule extends AppGlideModule {
    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        registry.register(Bitmap.class, TwoBitmaps.class, 
            new TwoBitmapsModuleTranscoder(context, glide.getBitmapPool()));
    }

    // Disable manifest parsing to avoid adding similar modules twice.
    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }
}
```
