### ISSUE TITLE
Get to Cache on SyncAdapter

### ISSUE THREAD

**Issue by jagiellonczyk14** [bumptech/glide#2484]
I am wondering is it possible o use gLide on SyncAdapter in Adnroid in order to get images ino Cache and than when user will be Intrested And get to the same File (I use Firebase Storage) The image or gif animation would be taken from cache. 

To be more precise I want to get the image to cache without Loading it to ImageView on SyncAdapter thread.

**Comment by TWiStErRob** [comment]
`downloadOnly()`?

**Comment by jagiellonczyk14** [comment]
Thank You very much One more question I have Introduced download only On SyncAdapter -  On OnPerformSync method code below

  Glide.with(ctx1)
                    .using(new FirebaseImageLoader())
                    .load(islandRef)
                    .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                    .get();


I am getting error 
 java.lang.IllegalArgumentException: YOu must call this method on a background thread

As far As I know OnPerformSync in Sync Adapter Is on Background Thread

**Comment by sjudd** [comment]
It looks like the sync adapter (or wherever you're calling this method) is not actually running in a background thread. You might want to start a new background thread to run during the sync that loads Glide's images.
