### ISSUE TITLE
Need update on repo's main page, about gradle file

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bumptech/glide#2490]
This isn't needed anymore:

```
repositories {
  mavenCentral()
  maven { url 'https://maven.google.com' }
}
```

Instead, you just need to make sure this exists:

```
    repositories {
        google()
        ...
    }
```

**Comment by TWiStErRob** [comment]
not really, see https://developer.android.com/studio/build/dependencies.html#google-maven

**Comment by AndroidDeveloperLB** [comment]
What do you mean "not really"? 
You can remove the 2 lines, and use a single word instead. I've tested it. It works fine.
Also, that's added by default to new projects anyway.

**Comment by TWiStErRob** [comment]
I meant it's still needed; lot of people are still on Gradle 2.14+ and 3.x, let's wait at least until Gradle Plugin 3 comes out as stable. I know it works with `google()` as well, the link I quoted shows you why it works.

We still need `mavenCentral()` though, I don't think Glide is published in the Google repo. Your `...` may contain that or a `jcenter()`.

@sjudd thoughts?

**Comment by AndroidDeveloperLB** [comment]
I have "jcenter()" .
Is it the same as "mavenCentral" ?

**Comment by sjudd** [comment]
Glide isn't published on jcenter right now and they appear to have stopped automatically syncing new versions, so mavenCentral is still needed. 

We can use google() directly when the new plugin is stable.

**Comment by AndroidDeveloperLB** [comment]
Well the weird thing is that "jcenter()" together with "google()" are enough for me to use Glide (can't remove any of them though) , so I think you got something wrong here.

**Comment by TWiStErRob** [comment]
`maven { url 'https://maven.google.com' }` == `google()` from Gradle 4.1, we'll change this once it's wide-spread.

`jcenter()` is a superset of `mavenCentral()`, Sam only uploads to Maven, and some artifacts don't appear to appear on jcenter, but actually accessible, see https://github.com/bumptech/glide/issues/544#issuecomment-122855054.
> so I think you got something wrong here.

It is possible that it was working before, and now it isn't ("appear to have stopped"), Glide may be just in your local cache.

---

So yes, looks outdated, but is accurately depicting the dependencies Glide needs
```
mavenCentral()
maven { url 'https://maven.google.com' }
```
and I would recommend everyone using (along with latest stable Gradle and Android Gradle Plugin):
```
jcenter()
google()
```
but I don't think it's in the scope of the README of Glide to educate people about this.

**Comment by AndroidDeveloperLB** [comment]
But I already use those two:

jcenter()
google()

I don't understand...

**Comment by TWiStErRob** [comment]
I'm agreeing with you, that everyone should be using that, but not because Glide requires it.

**Comment by sjudd** [comment]
This has been done, though we still list mavenCentral() explicitly.
