### ISSUE TITLE
Using GlideApp.as(NinePatchDrawable.class) error

### ISSUE THREAD

**Issue by mhy8958** [bumptech/glide#2491]
**Glide Version**:V4

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 
I wanna use glide to load ninePatch drawable as textview background. I write the following code. Can I use 'as()' like this?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(context).as(NinePatchDrawable.class).load(url).into(new SimpleTarget<NinePatchDrawable>() {
            @Override
            public void onResourceReady(NinePatchDrawable resource, Transition<? super NinePatchDrawable> transition) {
                textView.setBackgroundDrawable(resource);
            }
        });
```

**Stack trace / LogCat**:
```ruby
W/Glide: Load failed for http://xxx.png with size [-2147483648x-2147483648]
                                                                      class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

**Comment by Leolkalnus** [comment]
@mhy8958 I have the same problem. Did you find answer?
