### ISSUE TITLE
Error:Execution failed for task ':app:transformJackWithJackForDebug'. > com.android.jack.ir.JNodeInternalError: java.lang.Exception: java.lang.AssertionError: No yet implemented

### ISSUE THREAD

**Issue by edifangyi** [bumptech/glide#2493]
compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "com.mana.distribution"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        // 开启 multidex
        multiDexEnabled true

        jackOptions {
            enabled true
        }
    }

 //  编译选项
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

 androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //noinspection GradleCompatible
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:recyclerview-v7:26.1.0'
    compile 'com.android.support:cardview-v7:26.1.0'
    compile 'com.android.support:design:26.1.0'
    compile 'com.android.support:support-v4:26.1.0'

    compile 'com.github.bumptech.glide:glide:4.2.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.2.0'
    //  svg
    compile 'com.caverock:androidsvg:1.2.1'

==============================================================
I'm using SVG demo, and the new demo can be used, but that's the error in the project. 
No matter where it is, it's the same

Error:Execution failed for task ':app:transformJackWithJackForDebug'.
> com.android.jack.ir.JNodeInternalError: java.lang.Exception: java.lang.AssertionError: No yet implemented

![image](https://user-images.githubusercontent.com/12421552/31660401-ded0d1c8-b369-11e7-8abb-36f69c88cc66.png)

**Comment by edifangyi** [comment]
I've removed Java 8, and I can use it


![image](https://user-images.githubusercontent.com/12421552/31660777-19bbc882-b36b-11e7-8952-769db4f295c9.png)

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/download-setup.html#jack
