### ISSUE TITLE
Could I use glide to load many images with the same session ?  

### ISSUE THREAD

**Issue by onlyloveyd** [bumptech/glide#2495]
**Glide 3.8.0**:

**Integration libraries**: No

**Device/Android Version**: Huawei P10 / Android7.0

**Issue details / Repro steps / Use case background**: 
Using Glide to load image to ImageView one by one  in a RecyclerView, the session numbers in Server will increase one by one. 
How can I using the same session when i load image with Glide in my Android App.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).load(url).into(imageView);
```

**Layout XML**:
No XML. I add the ImageView dynamically.

**Stack trace / LogCat**:
No

Thanks

**Comment by sjudd** [comment]
I'm not really sure what you're asking or what you mean by session numbers.

**Comment by onlyloveyd** [comment]
Sorry for my poor English. I solved the problem by using GlideUrl with Cookie.

Thanks.  : )

**Comment by TWiStErRob** [comment]
Thanks for sharing your solution.
