### ISSUE TITLE
How to load thumb image from header(Exif) of JPG?

### ISSUE THREAD

**Issue by zhangchaojiong** [bumptech/glide#2501]
> How to load thumb image from header(Exif) of JPG ？

```
I checked the source code:

 final Bitmap result = BitmapFactory.decodeStream(is, null, options);

```

> Glide alway load source image ,and then converted into thumbnails.
> Is there a way to extract thumbnails from the JPG header?

**Comment by TWiStErRob** [comment]
You need to write your own decoder and register in a glide module.

Had you filled in the issue template I could direct you more...

**Comment by zhangchaojiong** [comment]
thanks you ，I got it.

**Comment by sjudd** [comment]
Glad you got it solved. If you want to share your solution here, someone else might find it useful.
