### ISSUE TITLE
java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.checkSelfPermission

### ISSUE THREAD

**Issue by wei120698598** [bumptech/glide#2502]
if my application compile v4 22.2.1，throw this exception，glide compile v4 is
26.0.1 ，too height

**Comment by TWiStErRob** [comment]
The version you're trying to use is 2.5 years and 3 major Android releases old... so if you want to stick with I you can choose a Glide that's 2.5 years old.

I think you can get away not updating to 26, but something in between that has that method. For example the method you're missing is 23.0: https://developer.android.com/reference/android/support/v4/content/ContextCompat.html#checkSelfPermission(android.content.Context,%20java.lang.String).

However please note http://bumptech.github.io/glide/doc/download-setup.html#android-sdk-requirements and remember that SDK compile should match appcompat version.

**Comment by sjudd** [comment]
Also worth noting that you don't need to target the same version of Android that you compile against. It ought to be easier to update your compileSdk than your targetSdk
