### ISSUE TITLE
glide4.2.0版本加载gif动态图 背景显示绿色

### ISSUE THREAD

**Issue by guoqj** [bumptech/glide#2503]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by guoqj** [comment]
谁知道怎么解决呢？

**Comment by sjudd** [comment]
Sorry if you can repeat your question in English I can try to help.
