### ISSUE TITLE
[Glide v4] How to clear memory cache in runtime

### ISSUE THREAD

**Issue by oneroman** [bumptech/glide#2504]
Hi there,

I would like to clear memory cache in runtime. My scenario is that for some period of time Glide shall do cache in memory only and then based on some event I want to do clear that memory cache. I am not able to find any API for that. Is that possible to do? 

Thanks for any help!

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/caching.html#clearing-memory

**Comment by TWiStErRob** [comment]
Mind you that images that are actively loaded (displaying) in current Views (targets) won't be freed. If you want to get rid of those too, you may need to manually clear some of those targets, e.g. via `Glide.clear(ImageView)`.

**Comment by oneroman** [comment]
@sjudd @TWiStErRob Thanks a lot, guys!
