### ISSUE TITLE
Need to use both versions of glide 3 and 4

### ISSUE THREAD

**Issue by denisshikunets** [bumptech/glide#2506]
Because of the others libraries, I need to use glide4 and glide3 at the same time. Is it possible to change package for glide 4, like it is done in rxjava and rxjava2 or in retrofit and retrofit2 etc.?

**Glide Version**:
4.2.0 and 3.8.0

**Device/Android Version**:
All versions

**Comment by sjudd** [comment]
Glide is somewhat more heavy weight than most of those libraries. Using two disk caches, two memory caches, two bitmap pools, double the expected number of threads etc could easily lead to substantial bugs and OOMs. As a result Glide uses the same package name.

You can encourage your dependencies to update and use Glide 3 until they do. If you want to take the risk, you could also repackage Glide 4 yourself and use that with some strict controls over the various sizes I mentioned above.

**Comment by TWiStErRob** [comment]
Just out of curiosity: what are these libraries that embed Glide into your app?
