### ISSUE TITLE
Trying to migrate Glide v3 to v4 but lose my way when migrate custom model loader

### ISSUE THREAD

**Issue by iam1492** [bumptech/glide#2513]
This is not Glide issue but needs help to migrate v3 to v4.
I use stream model loader in Glide v3. As our server resizes uploaded image async way, android should request for original Url if resize Url is missing. So below code shows that DataFetcher request for original Url when Exception happens with resized Url(this mean the resized image is not ready).

Currently, I have no idea migrate this code to v4. Glide v4 does not have getResourceFetcher. Do I have to implement this fetcher for my own?

I already read the article about Model Loader migration document from Glide. But still, don't know how to handle this problem. Any hint for me would be a great help!

```java
class HoianModelLoader implements StreamModelLoader<HoianImage> {
    private final ModelLoader<String, InputStream> loader;

    private HoianModelLoader(ModelLoader<String, InputStream> loader) {
        this.loader = loader;
    }

    @Override
    public DataFetcher<InputStream> getResourceFetcher(final HoianImage model, final int width,
                                                       final int height) {
        return new DataFetcher<InputStream>() {
            private DataFetcher<InputStream> fetcher;

            @Override
            public String getId() {
                return model.url;
            }

            @Override
            public InputStream loadData(Priority priority) throws Exception {
                try {
                    fetcher = loader.getResourceFetcher(model.getResizeUrl(), width, height);
                    return fetcher.loadData(priority);
                } catch (Exception ex) {
                    if (fetcher != null) {
                        fetcher.cleanup();
                    }
                    fetcher = loader.getResourceFetcher(model.getOriginUrl(), width, height);
                    return fetcher.loadData(priority);
                }
            }

            @Override
            public void cleanup() {
                if (fetcher != null) {
                    fetcher.cleanup();
                }
            }

            @Override
            public void cancel() {
                if (fetcher != null) {
                    fetcher.cancel();
                }
            }
        };
    }

    static class Factory implements ModelLoaderFactory<HoianImage, InputStream> {
        @Override
        public com.bumptech.glide.load.model.ModelLoader<HoianImage, InputStream> build(Context context,
                                                                                        GenericLoaderFactory factories) {
            return new HoianModelLoader(factories.buildModelLoader(String.class, InputStream.class));
        }

        @Override
        public void teardown() {
        }
    }
}
```

**Comment by sjudd** [comment]
One thought is to compare one of Glide's v3 ModelLoaders to its v4 equivalent, for example here's the v3 FlickrModelLoader: 
https://github.com/bumptech/glide/blob/211c4dbd79d92dcc56f186d0dd8b50849f9236ff/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrModelLoader.java#L21

And the v4 version:
https://github.com/bumptech/glide/blob/d447e582397cc7cf3f95a9871eb18d81a917544f/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrModelLoader.java#L20.

Or here's the OkHttp v3 version:
https://github.com/bumptech/glide/blob/211c4dbd79d92dcc56f186d0dd8b50849f9236ff/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpUrlLoader.java#L19

And v4:
https://github.com/bumptech/glide/blob/d447e582397cc7cf3f95a9871eb18d81a917544f/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpUrlLoader.java#L15
