### ISSUE TITLE
App extends AppGlideModule then can't extends MultiDexApplication(Glide.4.2.0)

### ISSUE THREAD

**Issue by kolacbb** [bumptech/glide#2517]
My App.java used to extends MultiDexApplication, in glide 4.2.0, app should extends AppGlideModule I can't extends both.

**Comment by TWiStErRob** [comment]
Nowhere it says your app has to extend it. Just create a separate class for the module with the right annotation.

Also you don't have to extend Multidex, it's a really simple method override you can copy: https://developer.android.com/studio/build/multidex.html#mdex-gradle (see also code of `MultiDexApplication`)

**Comment by kolacbb** [comment]
@TWiStErRob thanks for you solve my question, when I read the implement of MultiDexApplication I realized How stupid am I
