### ISSUE TITLE
Load More RecyclerView Bug

### ISSUE THREAD

**Issue by AhmadullahSaikat** [bumptech/glide#2518]
I am using glide 4.2.0

after integrate this lines this following crash occures:

.apply(new RequestOptions()
                                    .centerCrop()
                            )

when after adding a or more item/'s to server. If i go back to Recyclerview. Then swipe to refresh. After loading more items then the following crash occures. 

Crash Report:

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{432383a position=31 id=-1, oldPos=30, pLpos:30 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{2f88c50 VFED..... .F....ID 0,0-480,800 #7f0f00f5 app:id/recycleView}, adapter:com.neuronplayer.aroundme.screens.company.list.CompaniesFragment$CompanyListAdapter@e29d93, layout:android.support.v7.widget.LinearLayoutManager@f3211d0, context:com.neuronplayer.aroundme.screens.company.list.CompaniesActivity@d0f7f54

Please fix this as soon as possible..

**Comment by sjudd** [comment]
That's a crash in RecyclerView. Usually those exceptions occur when you update your data without notifying the corresponding adapter.

Can you clarify how this is related to Glide?
