### ISSUE TITLE
Migrate from 3 to 4 version and RecyclerView 

### ISSUE THREAD

**Issue by Anton111111** [bumptech/glide#2519]
I have a small question. 
On 3 version i used Glide.clear(image); in RecyclerView on recycle(). (image is ImageView object )
But now clear is missed.
What must i use to clear in recycle() for 4 version?

**Comment by TWiStErRob** [comment]
I think it's `Glide.with(this).clear(image);` and `this` is the same thing that you use to load the image into the view.
