### ISSUE TITLE
Add support annotations to public interfaces

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#252]
By upgrading to API level 21 (#200) Glide will get `support-annotations` as a transitive dependency via `support-v4`.

The philosophy so far was:

> No support annotations (I don't want to force an additional dependency on users of the library, otherwise I'd be happy to use them).

But since Google did this for us, we might as well take advantage of it.

**Comment by sjudd** [comment]
Work is in progress on this, thanks to Nick:

https://github.com/bumptech/glide/commit/86a3afa40b56bad2f0d1d51a2a148d897a912b89

**Comment by sjudd** [comment]
I'm going to close this for now. This is an on-going project, but we've hit most of the major APIs or will soon. Additional pull requests would definitely be welcome if someone finds an area we've missed (we're mostly focussing on ``@Nullable``, although ``@NonNull`` is ok too in some more limited circumstances)

**Comment by TWiStErRob** [comment]
@sjudd what's your standing on the below variants?
(I prefer second as I see nullity as part of the type, see [`Nullable<T>` in C#](https://msdn.microsoft.com/en-us/library/1t3y8s4s.aspx))
```java
@Nullable private final String field;

@Nullable
public static Bitmap method() {
```
versus
```java
private final @Nullable String field;

public static @Nullable Bitmap method() {
```
