### ISSUE TITLE
Gifs appear in multiple views when start/stopped

### ISSUE THREAD

**Issue by charlesdurham** [bumptech/glide#2526]
Noticed an issue where gifs seem to duplicate when going from stopped to started state across multiple gifs see [Video](https://camo.githubusercontent.com/bb8cc835a6b0cedeea714efb74001bc55381a725/68747470733a2f2f7468756d62732e6766796361742e636f6d2f44656172657374466978656447726f736265616b2d73697a655f726573747269637465642e676966).

- glide 4.2
- Android 7.1 and 8.0 

Issue seems to go away with ` Glide.get(context).bitmapPool.setSizeMultiplier(0f)`.

I **think** I've identified the issue; `GifDrawable` is stopped and removes its frame loader callback during a frame load (after `GifFrameLoader.loadNextFrame()`). Eventually, the `GifFrameLoader` is going to get one last `onFrameReady` callback and it will attempt to notify its listeners but since the `GifDrawable` is already removed nothing happens, however the previous `Bitmap`, which in this case is still being used by the `GifDrawable` is cleared and put into the cache.

I've got some sample code that I was able to reproduce with by quickly stopping the gifs and starting the others:
```
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)

    val iv1 = findViewById<ImageView>(R.id.imageView1)
    val iv2 = findViewById<ImageView>(R.id.imageView2)

    val glide = Glide.with(this)

    glide
        .load("https://media.giphy.com/media/l2YWEhwRvpY4Q6UJG/giphy.gif")
        .into(iv1)

    glide
        .load("https://media.giphy.com/media/muVfdK4fmamek/giphy.gif")
        .into(iv2)

    iv1.setOnClickListener {
      val drawable = iv1.drawable as GifDrawable
      if (iv1Playing) {
        drawable.stop()
        iv1Playing = false
      } else {
        drawable.start()
        iv1Playing = true
      }
    }

    iv2.setOnClickListener {
      val drawable = iv2.drawable as GifDrawable
      if (iv2Playing) {
        drawable.stop()
        iv2Playing = false
      } else {
        drawable.start()
        iv2Playing = true
      }
    }
  }
```

**Comment by sjudd** [comment]
Thanks for the detail, video and repro steps, super helpful. I believe this is fixed. You can verify by trying with the latest snapshot: http://bumptech.github.io/glide/dev/snapshots.html#obtaining-snapshots

**Comment by charlesdurham** [comment]
Looks great 👍 thanks
