### ISSUE TITLE
Glide 4 with Circularimageview

### ISSUE THREAD

**Issue by thanhthangnet** [bumptech/glide#2527]
It looks like Glide 4 does not work well with Circularimageview when using the withCrossFade () method in the transition. With ImageView, they work well.
The libraries I used are:
```
com.mikhaellopez: circularimageview: 3.0.2
com.github.bumptech.glide: glide: 4.2.0

```
![screenshot](https://user-images.githubusercontent.com/11850408/32140876-be84b4c4-bca2-11e7-9539-1e2feba8860b.png)

I have the test project below:
http://test.bigvn.net/glide_test.zip

**Comment by sjudd** [comment]
yeah this is listed in the Readme: https://github.com/bumptech/glide#compatibility.

Unfortunately that View does not seem to handle animated Drawables.
