### ISSUE TITLE
Error:org.gradle.internal.resolve.ArtifactNotFoundException: Could not find compiler.jar (com.github.bumptech.glide:compiler:4.2.0).

### ISSUE THREAD

**Issue by SkyTreasure** [bumptech/glide#2529]
**Glide Version**:4.2.0
  
I am trying to add Glide in android studio 3.0 but am getting this error. 
Error:org.gradle.internal.resolve.ArtifactNotFoundException: Could not find compiler.jar (com.github.bumptech.glide:compiler:4.2.0).

I added using 
 compile 'com.github.bumptech.glide:glide:4.2.0'
 annotationProcessor 'com.github.bumptech.glide:compiler:4.2.0'

have also added
 repositories {
  mavenCentral()
  maven { url 'https://maven.google.com' }
}

**Comment by roobrarcade** [comment]
I'm having this same issue. Were you able to get it resolved?

**Comment by sjudd** [comment]
Did you follow all the steps here: http://bumptech.github.io/glide/doc/download-setup.html#gradle, including adding ``mavenCentral()``?

**Comment by SkyTreasure** [comment]
@sjudd Yes i have added mavenCentral() and have followed the same. 
@roobrarcade No issue still not resolved.

**Comment by sjudd** [comment]
Let me know if figure out what the issue is. That artifact does seem to be present on maven central: https://search.maven.org/#artifactdetails%7Ccom.github.bumptech.glide%7Ccompiler%7C4.2.0%7Cjar

**Comment by lavekush-t** [comment]
any resolution for this issue?

**Comment by SkyTreasure** [comment]
I reverted back to old version!

**Comment by lavekush-t** [comment]
Which one old version ? Actually my build working fine till yesterday, But today unexpectedly stop working with this error.

**Comment by SkyTreasure** [comment]
If you had put + in the implementation, it may not work. 
Like    implementation 'com.github.bumptech.glide:glide4.+'

I am using 3.7.0
