### ISSUE TITLE
v4 works with recyclerview causes GC frequently on android 5.1 and below

### ISSUE THREAD

**Issue by LambdaV5** [bumptech/glide#2535]
**Glide Version**:4.2.0

**Integration libraries**:volley

**Device/Android Version**:meizu pro 5 android 5.1

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
You'll want to take a look at [the allocation tracker][1] to figure out what allocations you're making. If you (or Glide) is making a lot of small allocations or a few larger allocations, that might be worth tracking down.

That said, Volley will buffer responses in a byte[] array. To mitigate that, Volley caches and re-uses byte arrays. The byte array caching works reasonably well for small requests and small images, but the limited size of the pool means it doesn't work well for medium or large images. As a result it may end up allocating and throwing away a number of byte arrays for each image request. 

[1]: https://developer.android.com/studio/profile/allocation-tracker-walkthru.html

**Comment by LambdaV5** [comment]
but version 3 dones't have this problem

**Comment by sjudd** [comment]
It's totally possible, but either way you'll need to take a look at the allocation tracker to figure out what is being allocated and why.
