### ISSUE TITLE
In Glide 3.x, Need help in deleting only certain type of images from glide's disk cache!

### ISSUE THREAD

**Issue by findjigar** [bumptech/glide#2543]
My overall object is to `delete` certain type of images (which are temporary) after a certain period like after one month, from disk cache of the my app.

I'm using Glide, so I know that using Glide, I can clear entire `disk Cache` but my goal is to clear only a certain type of `images` from `disk cache`. Like for example, live `banner` images from my app (which keeps changing after certain period). Problem is, they keeps adding space even though one gets `inactive`. So ideally I should delete all old `banner` images from cache.

What I'm thinking is have a separate `Glide Module` just for these banner images and setup a different `internal cache` directory for these images, and after a month, ask `Glide` to delete/clear this directory.

Another thing is to use `Glide's signature` concept which invalidates the images.

For both of above ideas, my problem and question is that I want to use only for certain type of images but more I read about them, it feels like once I use them, they apply to all images being download using `Glide`

Even if I use multiple Glide module, they all gets used for all the images (that's why there is a concept of conflict management for glide modules)

I might be wrong, and there might be indeed a way to get a solution to my problem. All I need is your help if you know a way :)

I'm aware that if nothing works out for my solution, then to keep my app's size impact low, I'll have to decreased overall `internal disk cache` size which is `250MB` by default.

Thanks.

**Comment by sjudd** [comment]
Glide doesn't really provide a way for you to do this. You can implement your own DIskCache, but you're not going to get enough information in the Keys typically to be able to figure out which images are which. 

One alternative is to use your own cache outside of Glide for your banner images. You can implement a custom ``ModelLoader`` that checks and populates your banner disk cache and then use ``DiskCacheStrategy.NONE`` when loading those images through Glide to prevent them from ever entering Glide's disk cache.
