### ISSUE TITLE
A question about the trimMemory method in LruBitmapPool.java.

### ISSUE THREAD

**Issue by miguoer** [bumptech/glide#2545]
When looking into `LruBitmapPool.java`, I find that trimMemory method will only work when the level above TRIM_MEMORY_BACKGROUND or TRIM_MEMORY_UI_HIDDEN.  Why glide won't handle a situation when the level is below  TRIM_MEMORY_UI_HIDDEN. As a rule, level below TRIM_MEMORY_UI_HIDDEN indicates a more restrict memory condition. Thank you.

`  public void trimMemory(int level) {
    if (Log.isLoggable(TAG, Log.DEBUG)) {
      Log.d(TAG, "trimMemory, level=" + level);
    }
    if (level >= android.content.ComponentCallbacks2.TRIM_MEMORY_BACKGROUND) {
      clearMemory();
    } else if (level >= android.content.ComponentCallbacks2.TRIM_MEMORY_UI_HIDDEN) {
      trimToSize(maxSize / 2);
    }
  }`

**Comment by sjudd** [comment]
You could argue it either way. TRIM_MEMORY_UI_HIDDEN might occur when pickers or other applications are transiently opened, in which case you may not want the penalty of clearing out so many resources. 

Applications can always implement ComponentCallbacks2 themselves and clear out memory more aggressively than Glide's defaults, but they don't have a way of making Glide less aggressive.

**Comment by miguoer** [comment]
Thank you for your reply. I get it.
