### ISSUE TITLE
Glide wont load images from URIs with a file:// scheme

### ISSUE THREAD

**Issue by ImageViewGlide** [bumptech/glide#2546]
Glide: 3.8.0
No annotation processor

All newer versions didn't resolve some functions that work on this version.

I have tried many ways already, but here is my URI:

    file:///storage/emulated/0/WhatsApp/Media/WhatsApp%20Images/IMG-20171101-WA0003.jpg

I have tried using:

    .load(urinormal)
at first. It works as long the URI has a content:// scheme, but not for file://

Other things I tried:

    .load(new File(urinormal.getPath()))
    .load(Uri.fromFile(new File(urinormal.getPath())))

Read and write storage permission are both granted, in manifest and on runtime.

Edit: I get the Uri with

        ImageView image = findViewById(R.id.image);
        Glide.with(this).load(getIntent().getParcelableExtra(Intent.EXTRA_STREAM)).into(image);

**Comment by sjudd** [comment]
What version of Glide are you using? Please always fill out the issue template when filing new issues.

**Comment by ImageViewGlide** [comment]
@sjudd Sorry, updated my issue. The version is 3.8.0.

**Comment by ImageViewGlide** [comment]
I have also noticed that I don't get any exception in logcat and onLoadFailed also is never called.

**Comment by sjudd** [comment]
3.8 is a little old for me to debug, but let us know if you figure out what's going wrong in case it helps someone else.

The debug steps here might help too: http://bumptech.github.io/glide/doc/debugging.html#missing-images-and-local-logs

**Comment by TWiStErRob** [comment]
Check if the file is accessible by using `new File("path without protocol and % escapes")`. Try doing an `exists` and a length query on it. I've had problems with `/storage/emulated/0` or `/sdcard` before (not sure which), try `/sdcard`. On the Glide wiki you can find how to enable all logs.
