### ISSUE TITLE
VerifyError Rejecting class

### ISSUE THREAD

**Issue by krcho** [bumptech/glide#2551]
Is there any report about VerifyError??? 

In debug build, this worked well. But, in release build, emit error and finish application.
here is Exception stacktrace

```
Fatal Exception: java.lang.VerifyError: Rejecting class o.aI because it failed compile-time verification (declaration of 'o.aI' appears in /data/app/**-1/base.apk)
       at com.bumptech.glide.Glide.(SourceFile)
       at com.bumptech.glide.Glide.bitmapPool(SourceFile:52708)
       at com.bumptech.glide.Glide.checkAndInitializeGlide(SourceFile:52395)
       at com.bumptech.glide.Glide.glideContext(SourceFile:100641)

```
I'm using 4.3.0 with another integrations

```
compile 'com.github.bumptech.glide:glide:4.3.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.3.0'
compile('com.github.bumptech.glide:okhttp3-integration:1.5.0@aar') {
    exclude group: 'glide-parent'
}
compile 'jp.wasabeef:glide-transformations:3.0.1'
```

And my GlideModule is

```
@GlideModule
public class UpbitGlideModule extends AppGlideModule {
    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }

    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        super.registerComponents(context, glide, registry);
    }
}
```

And, I'm using Dexguard. so Inserted options

```
#Glide
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
-keepresourcexmlelements manifest/application/meta-data@value=GlideModule
#Glide integration
-keep class com.bumptech.glide.integration.okhttp3.OkHttpGlideModule
```

**Comment by sjudd** [comment]
compile('com.github.bumptech.glide:okhttp3-integration:1.5.0@aar') is the v3 version of the integration library. In Glide v4 all the version numbers are the same, see: http://bumptech.github.io/glide/int/okhttp3.html in particular.

**Comment by krcho** [comment]
nono. It cannot be help for me.
I'm upgrade to `com.github.bumptech.glide:glide:4.3.0` But It still makes same problem

**Comment by TWiStErRob** [comment]
@krcho let's recap:
```
compile 'com.github.bumptech.glide:glide:4.3.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.3.0'
compile 'com.github.bumptech.glide:okhttp3-integration:4.3.0'
```
or
```
compile 'com.github.bumptech.glide:glide:3.8.0'
compile 'com.github.bumptech.glide:okhttp3-integration:1.5.0'
```

**Comment by krcho** [comment]
i tried this
```
compile 'com.github.bumptech.glide:glide:4.3.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.3.0'
compile 'com.github.bumptech.glide:okhttp3-integration:4.3.0'

```

**Comment by aerdy** [comment]
Verifier rejected class com.bumptech.glide.load.resource.bitmap.Downsampler: android.graphics.Bitmap com.bumptech.glide.load.resource.bitmap.Downsampler.ˊ(java.io.InputStream, android.graphics.BitmapFactory$Options, com.bumptech.glide.load.resource.bitmap.Downsampler$DecodeCallbacks, com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool) failed to verify: android.graphics.Bitmap com.bumptech.glide.load.resource.bitmap.Downsampler.ˊ(java.io.InputStream, android.graphics.BitmapFactory$Options, com.bumptech.glide.load.resource.bitmap.Downsampler$DecodeCallbacks, com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool): [0x2C] copy1 v4<-v3 type=Reference: java.lang.IllegalArgumentException cat=1 (declaration of 'com.bumptech.glide.load.resource.bitmap.Downsampler' appears in /data/app/com.privygate.privyid-aZpGake0CDGX0di0kUIu6g==/base.apk)

**Comment by aerdy** [comment]
@sjudd dexguard that I use

**Comment by fengshi92** [comment]
For me, I added -keep public class com.bumptech.glide.load.resource.bitmap.Downsampler { *; } to make it work.
