### ISSUE TITLE
Cache errors

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#2554]
**Glide Version**:
4.x

A simple question :)

What is the best way to have Glide caching errors? Typically I'd like to have 404 errors not retried indefinitely to avoid unnecessary requests. (For a fixed duration or for the duration of the app process, not permanent).

**Comment by sjudd** [comment]
You could write a custom ``ModelLoader`` to keep track of the number of times you'd tried a URL. Probably replacing the default GlideUrl ModelLoader would make sense.

**Comment by sjudd** [comment]
The ModelLoader/DataFetcher pair really can be considered a single object. I'm not sure there's going to be a good way to persist and retrieve the status of a failure without going to a background thread, especially for arbitrary keys.

ModelLoader really is the thing that owns retrieving data, so if it wants to avoid fetching data for whatever reason, I think that conceptually makes sense.
