### ISSUE TITLE
Does glide support all kinds of android photo uri?

### ISSUE THREAD

**Issue by alienwings** [bumptech/glide#2557]
Does glide support all kinds of content uri such as below ?
E.g. uri of DocumentProvider, DownloadProvider, MediaProvider, GooglePhotosUri (Google and other third party gallery), see below code.
ContentResolver.openInputStream supports all kinds of uri metioned above, I'm refactoring my code know and not quite sure about whther glide owns the same ability to ContentResolver.openInputStream.
Some people may suggest me to customized glide model to decode uri in my own if worried too much, but I think for our code, less is better!

` public static String getPath(final Context context, final Uri uri) {

        final boolean isKitKat = Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT;
        // DocumentProvider
        if (isKitKat && DocumentsContract.isDocumentUri(context, uri)) {
            // ExternalStorageProvider
            if (isExternalStorageDocument(uri)) {
                final String docId = DocumentsContract.getDocumentId(uri);
                final String[] split = docId.split(":");
                final String type = split[0];

                if ("primary".equalsIgnoreCase(type)) {
                    return Environment.getExternalStorageDirectory() + "/"
                            + split[1];
                }
                // TODO handle non-primary volumes
            }
            // DownloadsProvider
            else if (isDownloadsDocument(uri)) {
                final String id = DocumentsContract.getDocumentId(uri);
                final Uri contentUri = ContentUris.withAppendedId(
                        Uri.parse("content://downloads/public_downloads"),
                        Long.valueOf(id));
                return getDataColumn(context, contentUri, null, null);
            }
            // MediaProvider
            else if (isMediaDocument(uri)) {
                final String docId = DocumentsContract.getDocumentId(uri);
                final String[] split = docId.split(":");
                final String type = split[0];

                Uri contentUri = null;
                if ("image".equals(type)) {
                    contentUri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;
                } else if ("video".equals(type)) {
                    contentUri = MediaStore.Video.Media.EXTERNAL_CONTENT_URI;
                } else if ("audio".equals(type)) {
                    contentUri = MediaStore.Audio.Media.EXTERNAL_CONTENT_URI;
                }

                final String selection = "_id=?";
                final String[] selectionArgs = new String[]{split[1]};

                return getDataColumn(context, contentUri, selection,
                        selectionArgs);
            }
        }
        if ("content".equalsIgnoreCase(uri.getScheme())) {// MediaStore(and
            // Return the remote address
            if (isGooglePhotosUri(uri))
                return uri.getLastPathSegment();
            else if (isGoogleDrivePhotosUri(uri)) {
                Cursor cursor =
                        context.getContentResolver().query(uri, null, null, null, null);
                int name = cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME);
                int size = cursor.getColumnIndex(OpenableColumns.SIZE);
                cursor.moveToFirst();
                cursor.close();
                Log.v(tag, "Google drive uri: " + name + ", " + size + "bytes");
                return null;
            }
            return getDataColumn(context, uri, null, null);
        } else if ("file".equalsIgnoreCase(uri.getScheme())) {// File
            return uri.getPath();
        }

        return null;
    }`

**Comment by sjudd** [comment]
Glide supports any Uri where opening the Uri produces a valid image or video.
