### ISSUE TITLE
On scrolling recylerView List, it hamper the UI Thread

### ISSUE THREAD

**Issue by Meenu1401** [bumptech/glide#2559]
<!--While Scrolling a whole list. It doesn't scroll smoothly. Because i'm hitting  our server to get image and then set it into imageview using Glide. But when we set the image, it hamper the UI Thread and doesn't scroll smoothly. How can i resolve this?

Please help me to fix this. 
I'm using Glide 4.0.0-RC

And Using okHttp for getting image from server.

**Comment by Meenu1401** [comment]
While Scrolling a whole list. It doesn't scroll smoothly. Because i'm hitting  our server to get image and then set it into imageview using Glide. But when we set the image, it hamper the UI Thread and doesn't scroll smoothly. How can i resolve this?

Please help me to fix this. 
I'm using Glide 4.0.0-RC

And Using okHttp for getting image from server.

**Comment by sjudd** [comment]
You'll probably want to look at systrace to see if you can figure out what specifically is slow: https://developer.android.com/studio/command-line/systrace.html. Lots of things can cause jank.

Although there are lots of possible reasons, one issue that can be harder to track down is texture upload times. If you see a lot of time spent uploading textures in your systraces, the Bitmaps you're loading may be larger than the device can handle for a given scroll rate. You can use ``override()`` or ``sizeMultiplier()`` to decrease the size or vary the sizes you load depending on scroll speed.

Again though we're going to have a hard time guessing, so you really should start by looking at systrace.

**Comment by Meenu1401** [comment]
No its, working fine with high end devices, but taking time on low end devices. Its shows awkward behaviour like image flickers, wrong image displays and then flickers multiple times.
