### ISSUE TITLE
Can I use multiple ViewTargets in one view ?

### ISSUE THREAD

**Issue by floating-cat** [bumptech/glide#256]
Actually I use `TextView` instead of `WebView` to display both text and images, and the example is very familiar to https://github.com/sjudd/testGlide .

I have codes like this:

```
Glide.with(textView.getContext())
    .load(url)
    .into(new MyViewTarget(textView));
```

And need to load multiple image in one `TextView`.

But the `ViewTarget` set `Request` to its view's tag. And If I call `into`,  the `GenericRequestBuilder` would cancel the previous one and start new ones.

I have no idea, and really want any helps or workaround. 
Thanks a lot and also for this library.

**Comment by floating-cat** [comment]
I have digged codes a bit before, this my solution (I hope it would help others):

```
public class ImageGetterViewTarget extends ViewTarget<TextView, GlideDrawable> {
	......

	/**
	 * @see com.bumptech.glide.GenericRequestBuilder#into(com.bumptech.glide.request.target.Target)
	 */
	@Override
	public Request getRequest() {
		return null;
	}

	@Override
	public void setRequest(Request request) {

	}
}
```

Though it is look odd, but It works correct.

`getRequest()` and `setRequest(Request)` was invoked in `GenericRequestBuilder#into()`
```
public <Y extends Target<TranscodeType>> Y into(Y target) {
	Util.assertMainThread();
	if (target == null) {
		throw new IllegalArgumentException("You must pass in a non null Target");
	}
	if (!isModelSet) {
		throw new IllegalArgumentException("You must first set a model (try #load())");
	}

	Request previous = target.getRequest();

	if (previous != null) {
		previous.clear();
		requestTracker.removeRequest(previous);
		previous.recycle();
	}

	Request request = buildRequest(target);
	target.setRequest(request);
	lifecycle.addListener(target);
	requestTracker.runRequest(request);

	return target;
}
```

**Comment by snakemouse3d** [comment]
@floating-cat : i have the same problem with you. Really thank you for your solution :dancers: It saves me for a day

**Comment by floating-cat** [comment]
Any person who have the same problem had better look at https://github.com/bumptech/glide/issues/550.
Actually my solution can not cancel images loading for that view. (: Sorry for this
