### ISSUE TITLE
Glide V4: Save image on phone

### ISSUE THREAD

**Issue by mohsenmdb** [bumptech/glide#2561]
this not work in glade v4
https://github.com/bumptech/glide/issues/80

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

If you are able to fill out the issue template, please do so and provide a bit more detail. What doesn't work? What are you trying to do? For general debugging, see: http://bumptech.github.io/glide/doc/debugging.html

**Comment by mohsenmdb** [comment]
ok Thank you
