### ISSUE TITLE
GlideException: Failed to load resource

### ISSUE THREAD

**Issue by cydenghua** [bumptech/glide#2563]
CODE:

        Glide.with(this)
                .load("https://dragonfruit_test.ememed.net/uploads/avatar/20170921/150595604450328.jpg")
                .into(mIv);

ERROR:
 W/Glide: Load failed for https://dragonfruit_test.ememed.net/uploads/avatar/20170921/150595604450328.jpg with size [1200x1744]
                                                               class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                 Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                                                   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                                     Cause (1 of 1): class javax.net.ssl.SSLHandshakeException: java.lang.IllegalArgumentException: Invalid input to toASCII: dragonfruit_test.ememed.net

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

Your error is here and doesn't appear to have much to do with Glide unfortunately:
```
class javax.net.ssl.SSLHandshakeException: java.lang.IllegalArgumentException: Invalid input to toASCII: dragonfruit_test.ememed.net
```

Your URL is malformed, it looks like the underscore in the host name isn't supported by Android and doesn't match the RFCs. For a good discussion, see https://github.com/square/picasso/issues/1570.

**Comment by paduy** [comment]
I had a same issue and I set timeout for glide and it works well. You can read the code ate here
https://stackoverflow.com/questions/55473076/class-com-bumptech-glide-load-engine-glideexception-failed-to-load-resource
