### ISSUE TITLE
Glide image is displaying or overlapping on top of the imageview background

### ISSUE THREAD

**Issue by mallibunte** [bumptech/glide#2571]
![2](https://user-images.githubusercontent.com/13198787/32480746-49453a92-c3b6-11e7-96f0-7247bbf0eff8.PNG)

**Glide Version**:4.3.0

**Integration libraries**:volley.jar

**Device/Android Version**:All Devices/ All versions

**Issue details / Repro steps / Use case background**: I am using glide to display images in expanding list view child item. so when i am expanding the list and collapsing the list first time the image is working perfectly as i expected. But when i do it same thing second time onwards the image resize happens and its overlapping on to of the background. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public static void loadImage(ImageView view, String imageUrl){
        RequestOptions requestOptions = new RequestOptions();
        requestOptions.transform(new CircleTransform(mContext));
        requestOptions.diskCacheStrategy(DiskCacheStrategy.ALL);
        requestOptions.skipMemoryCache(false);
        requestOptions.override(250, 250);
        requestOptions.fitCenter();
        Glide.with(view.getContext())
                .load(imageUrl)
                .apply(requestOptions)
                .into(view);
    }
```

**Layout XML**:
```xml
<LinearLayout
            android:id="@+id/car_type_image"
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:layout_gravity="center"
            android:layout_alignParentLeft="true"
            android:layout_alignParentTop="true"
            android:gravity="center"
            android:layout_marginTop="5dp"
            android:background="@drawable/car_logo_bg"
            android:padding="1dp">

            <ImageView
                android:id="@+id/iv_car_logo"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:gravity="center"
                app:rideImageUrl="@{myCarDetailsEditVM.imageUrl}"
                android:scaleType="centerCrop"
                android:contentDescription="@null"/>

            <!--app:infoImageUrl="@{plateVM.imageUrl}"-->
        </LinearLayout>
![1](https://user-images.githubusercontent.com/13198787/32480731-39b5fa4e-c3b6-11e7-9f2a-5b361062d6a6.PNG)

```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

Attached screenshots will get more understanding 1.png is displaying when we click on expandable list first time and 2.png is displaying when we click on expandable list 2nd time onwards.

**Comment by TWiStErRob** [comment]
RequestOptions is a builder returning itself (but maybe a new instance), I suggest you do a chained setup:
```java
        RequestOptions requestOptions = new RequestOptions();
        requestOptions = requestOptions.transform(new CircleTransform(mContext));
        requestOptions = requestOptions.diskCacheStrategy(DiskCacheStrategy.ALL);
        requestOptions = requestOptions.skipMemoryCache(false);
        requestOptions = requestOptions.override(250, 250);
        requestOptions = requestOptions.fitCenter();
```
or the more readable
```java
        RequestOptions requestOptions = new RequestOptions()
                .transform(new CircleTransform(mContext))
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .skipMemoryCache(false)
                .override(250, 250)
                .fitCenter();
```
---
Another thing is that your circle transform doesn't take effect, because of `fitCenter()`, you need to do `.transform(new FitCenter(), new CircleTransform(mContext))` [to apply both to the same load](http://bumptech.github.io/glide/doc/transformations.html#multiple-transformations).
---
wrap-wrap is not suggested to be used in Glide, however your hardcoded override prevents that from causing an issue. I suggest you change the XML like so:
```xml
android:layout_width="match_parent"
android:layout_height="match_parent"
```
and remove the center gravity from ImageView, it probably doesn't have any effect.

**Comment by mallibunte** [comment]
Wrong 1st argument type. Found: 'com.bumptech.glide.load.resource.bitmap.FitCenter', required: 'java.lang.Class<android.graphics.Bitmap>' less... 

transform
(java.lang.Class<android.graphics.Bitmap>,
Transformation<Bitmap>)
in RequestOptions cannot be applied
to
(com.bumptech.glide.load.resource.bitmap.FitCenter,
CircleTransform)

**Comment by sjudd** [comment]
use [``.transforms(new FitCenter(), new CircleTransform(mContext))``][1]

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/request/RequestOptions.html#transforms-com.bumptech.glide.load.Transformation...-

**Comment by mallibunte** [comment]
I have resolved this issue by changing image view width and height dynamically. Thanks for all your suggestions.
