### ISSUE TITLE
4.3.1无法使用placholder方法

### ISSUE THREAD

**Issue by 17707273443** [bumptech/glide#2573]
Glide.with(context).load(videoUrl).into(mHolder.imageview);
无法使用placeholder()
error方法里只有这一个方法
public RequestBuilder<TranscodeType> error(@Nullable RequestBuilder<TranscodeType> errorBuilder) {
    this.errorBuilder = errorBuilder;
    return this;
  }

**Comment by sjudd** [comment]
Google translate gives:

> Unable to use placeholder ()
The only method in the error method

Which doesn't tell me much I'm afraid. Maybe that the error builder doesn't obey the placeholder in the original request? So the placeholder goes away while the error request is loading?

If so, that's intended, though we may try to make it a bit more convenient in the future. You can specify the same set of placeholders on the error request as the full request to get the behavior you want.

**Comment by sjudd** [comment]
I'm not totally sure what the request is here, so I'm going to close this for now. If you can clarify I'd be happy to re-open.
