### ISSUE TITLE
Is there a way to download an image, if I don't know whether it's png or SVG?

### ISSUE THREAD

**Issue by Lex1717** [bumptech/glide#2576]
Hello, actually that's not an issue, but I need your help.
I'm trying to download an image for an ImageView from a link. I can't determine what type of file connected with that link, there is no .png or .svg at the end of url. 
How can I download the image with glide? Some people advise to upload as an usual image, if it falls, catch an exception and download as an SVG file. Is there any other method?
Thanks in advance!

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

In particular, what version of Glide are you using?

**Comment by Lex1717** [comment]
@sjudd 
glide version: 3.8.0
okhttp3-integration: 1.5.0
okhttp3: 3.9.0
I'm using glide to download images for an imageview in recyclerview adapter's holder.

**Comment by sjudd** [comment]
With v3 I believe you have to specify the decoders, so you'd have to create a wrapping decoder that can decode either a Drawable from an SVG or a Drawable from a normal image. Using your custom decoder in your load line would then produce either a BitmapDrawable or an SVG  Drawable.

In Glide v4 you could just register a decoder that can decode a Drawable from an SVG and then use the same load line your normally would. Glide v4 would then figure out if the image was an SVG or a normal image type and use the appropriate decoder automatically.
