### ISSUE TITLE
How get load image size

### ISSUE THREAD

**Issue by dwh178659824** [bumptech/glide#2580]
How get load image origin size, do not use asBitmap(), because I use bitmapTransform

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

Glide does not provide a direct way for you to obtain only the size of the original image. You could theoretically write a custom decoder to obtain the dimensions and return a POJO, but that's probably overkill. Usually you don't need to care about the original size of the image. In the rare cases where you do, it's much more efficient to obtain the image dimensions from metadata (MediaStore or a server backend) than it is to parse them out of every file.
