### ISSUE TITLE
URL with semicolon not working.

### ISSUE THREAD

**Issue by axzae** [bumptech/glide#2583]
**Glide Version**: 4.2.0

**Issue details / Repro steps / Use case background**: 
Glide is escaping URL with semicolon. Tried wrapping URL string with `URI.parse()`, but it doesn't work either.

Example URL:
http://api.met.no/weatherapi/weathericon/1.1/?symbol=9;content_type=image/png

but glide will change it to: http://api.met.no/weatherapi/weathericon/1.1/?symbol=4%3Bcontent_type=image/png 

Thread in StackOverflow:
https://stackoverflow.com/questions/47076398/glide-android-image-library-is-replacing-semicolon-with-3b-in-my-url

**Comment by sjudd** [comment]
Thanks for reporting this. I believe this is a bug in glide. We should be whitelisting all whitelisted and restricted characters but we're whitelisting only a subset. I have a cl that I believe will fix this which will go into 4.4
