### ISSUE TITLE
how can load bitmap  not depending on view 

### ISSUE THREAD

**Issue by scau-beyondboy** [bumptech/glide#2585]
glide version:4.2
hi,I want to load bitmap not depending on view and I can get the bitmap in callback,such as:
`GlideApp.with(context).load(url).listener(new RequestListener());` 
 insteading of call` into()` method.

**Comment by sjudd** [comment]
Just for you: http://bumptech.github.io/glide/doc/getting-started.html#non-view-targets :).

Do definitely read the Target docs page though, it's easy to break things using ``SimpleTarget``.

**Comment by scau-beyondboy** [comment]
thanks for your help!
