### ISSUE TITLE
Running animation on ImageView after replacing image with Glide breaks the animation

### ISSUE THREAD

**Issue by danwguy** [bumptech/glide#2586]
**Glide Version**: 3.7.0

**Integration libraries**: de.hdodenhof:circleimageview:1.3.0

**Device/Android Version**: All versions, but testing on Nexus 6 with Android M (7.0)

**Issue details / Repro steps / Use case background**: If you try to replace an image in an ImageView using Glide, then call an animation on that ImageView the animation will not run. It will start, run for less than half a second, then stop. Use case, I have a widget that has a default icon, when a new message comes in the image gets replaced with a user avatar, which is a URL from a firebase storage upload. I replace the default icon with the user avatar, then want to "shake" the icon to show a new message arrived. To reproduce all you have to do is create any layout that has an ImageView in it, give it a default icon (local)... R.drawable.ic_notificaiton, then add a button. on click of the button run the following code...

```
public void onNewMessage() {
  String userAvatar = "http://maps.google.com/mapfiles/ms/icons/blue.png";
  Glide.with(getApplicationContext()).load(userAvatar).into(imageView);
  Animation shake = AnimationUtils.loadAnimation(getApplicationContext(), R.anim.wobble);
  imageView.startAnimation(shake);
}
```

Where "imageView" is the ImageView from your xml layout and R.anim.wobble is...

```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <rotate xmlns:android="http://schemas.android.com/apk/res/android"
            android:duration="75"
            android:interpolator="@android:anim/linear_interpolator"
            android:fromDegrees="-5"
            android:pivotX="50%"
            android:pivotY="50%"
            android:repeatCount="10"
            android:repeatMode="reverse"
            android:toDegrees="5"/>

</set>
```
If you then remove the Glide.load(....) line and run it again the animation will run properly.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
`Glide.with(getApplicationContext()).load(userPhoto).into(collapsedImage);`

**Layout XML**:
```
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout
        android:id="@+id/root_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:ignore="UselessParent">

        <RelativeLayout
            android:id="@+id/collapse_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:visibility="visible">
            <de.hdodenhof.circleimageview.CircleImageView
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:id="@+id/collapsed_iv"
                android:layout_width="60dp"
                android:layout_height="60dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:src="@mipmap/ic_launcher"
                app:border_color="@color/colorTransparent"
                android:background="?android:attr/selectableItemBackground"/>

        </RelativeLayout>
       <!-- other layout items, just a linear layout and some extra image stuff-->  
    </RelativeLayout>
</FrameLayout>
```

**Stack trace / LogCat**: There is no errors in the log, it just doesn't run the animation. It starts the animation and runs for maybe a half a second, but then stops the animation.

**Comment by sjudd** [comment]
Try dontAnimate(): http://bumptech.github.io/glide/javadocs/380/com/bumptech/glide/DrawableRequestBuilder.html#dontAnimate()

**Comment by danwguy** [comment]
@sjudd Could you provide a simple example with my function above for dontAnimate() please. I have tried adding it to the call chain for Glide, but Android Studio keeps telling me "cant resolve method dontAnimate" and it won't compile. I am trying it like so...

`Glide.with(getApplicationContext()).load(imageURL).dontAnimate().into(imageView);`

Thank you.

**Comment by sjudd** [comment]
Are you using Glide v3? What is the type of the object returned by ``.load(imageURL)``?

**Comment by danwguy** [comment]
@sjudd That worked! Thank you so much. I didn't know about the dontAnimate() property. I had the order wrong when running the Glide load stuff. The editor was complaining because I was putting dontAnimate() before the .load(). So my original call that was getting the error was...

`Glide.with(getApplicationContext()).dontAnimate().load(imageURL).into(imageView);`

Moving the dontAnimate to after the load worked perfectly, and now my animations are running exactly as I need them. Thank you so much.
