### ISSUE TITLE
Apply transformation after delay

### ISSUE THREAD

**Issue by maxi182Eman** [bumptech/glide#2587]
Hi, I am needing to apply a blur trasnformation, but only after a certain lapse.
Any sugestions?

This is my current code to set the blur transformation.
`RequestOptions options =
                new RequestOptions()
                        .centerCrop()
                        .placeholder(R.drawable.gift_active)
                        .transform(new BlurTransformation(25))
                        .dontAnimate();
        Glide.with(this)
                .asBitmap()
                .load(presentData.story.media)
                .apply(options)
                .into(giftImageView) ;`

**Comment by sjudd** [comment]
You could load the image without the blur transformation, start a timer, and when the timer finishes, start a transformation with the blur transformation and a thumbnail with the original request.

Something like (untested):

```java
RequestOptions withoutBlurOptions = 
    new RequestOptions()
      .centerCrop()
      .placeholder(R.drawable.gift_active).dontAnimate(); 
RequestOptions withBlurOptions =
    new RequestOptions()
      .apply(withoutBlur) 
      .transforms(new CenterCrop(), new BlurTransformation(25));

RequestBuilder withoutBlurBuilder = 
    Glide.with(this)
      .asBitmap()
      .load(presentData.story.media)
      .apply(withoutBlurOptions);
withoutBlur.into(giftImageView);

handler.postDelayed(new Runnable() {
    @Override
    public void run() {
      Glide.with(this)
        .asBitmap()
        .load(presentData.story.media)
        .apply(withBlurOptions)
        .thumbnail(withoutBlurBuilder)
        .into(giftImageView)
    }
}, DELAY_TIME_IN_MS);
```

Note that you need to use [``.transforms()``][1] or [``MultiTransformation``][2] if you want to apply both ``CenterCrop`` and ``BlurTransformation``. If you call ``.transform()`` repeatedly, each invocation replaces the previous transformation.

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/request/RequestOptions.html#transforms-com.bumptech.glide.load.Transformation...-
[2]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/load/MultiTransformation.html
