### ISSUE TITLE
asGif doesn't work with Target

### ISSUE THREAD

**Issue by RanKKI** [bumptech/glide#2588]
**Glide Version**: 4.2.0

**Device/Android Version**: Nexus 5X 8.0.0

**Issue details / Repro steps / Use case background**: 
I want to load gif when the resource ready and stop refreshing layout, it doesn't work when I using Target, it just shows a the first frame of the gif, but it work when I use
```java
 load(url).into(ImageView)
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this).asGif().load(url).into(new SimpleTarget<GifDrawable>() {
    @Override
    public void onResourceReady(GifDrawable resource, Transition<? super GifDrawable> transition) 
    {
            imageView.setImageDrawable(resource);
            swipeRefreshLayout.setRefreshing(false);
    }
});
```

**Comment by sjudd** [comment]
You need to call [``start()``][1] on the resource to make it animate.

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/load/resource/gif/GifDrawable.html#start--
