### ISSUE TITLE
The drawable to display doesn't fit into the ImageView when load fails.

### ISSUE THREAD

**Issue by LuYeCong** [bumptech/glide#2590]
**glide:4.2.0**

**No Integration libraries**

I use `placeholder` and `error` to display a default image when load fails.

```java
public void loadImage(Context context, String fileid, int defaultRes, long fileEncryptSize, byte[] aeskey, byte[] encryptKey, byte[] randomKey, byte[] sessionId, ImageView imageView, RequestListener<Drawable> requestListener) {
    WwGlide.with(context)
            .load(new ImageFileId(fileid, fileEncryptSize, aeskey, encryptKey, randomKey, sessionId))
            .listener(requestListener)
            .apply(getRequestOptions(defaultRes))
            .into(imageView);
}

private RequestOptions getRequestOptions(int defaultRes) {
	return new RequestOptions()
            .centerInside()
            // TODO: 2017/11/12 ImageResizer.getDefaultBitmap(defaultRes) 默认图像使用单例缓存
            .placeholder(defaultRes)
            .error(defaultRes)
            .diskCacheStrategy(DiskCacheStrategy.ALL);
}
```

But the default image doesn't fit into the ImageView's size, like this:
![image](https://user-images.githubusercontent.com/5770650/32699645-3a36fa76-c7f4-11e7-8d35-d366814d46e4.png)

In fact, it should be like that:
![image](https://user-images.githubusercontent.com/5770650/32699658-5b60a06c-c7f4-11e7-95c2-151c1cff87f2.png)

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues. 

What version of Glide? Please provide the full load line you're using with Glide and the layout of the view you're loading into.

**Comment by LuYeCong** [comment]
@sjudd Thanks for reminding me that it may be caused by the wrong layout. And I've found that I used different `scaleType ` in the above two situations.
