### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by pangli** [bumptech/glide#2592]
**Glide Version**:4.0.0

**Integration libraries**: no

**Device/Android Version**:Android 6.0

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 GlideApp.with(context)
                .load(url)
                .apply(RequestOptions.bitmapTransform(new MultiTransformation<Bitmap>(new CenterCrop(), new RoundedCorners(radius))))
                .into(imageView);
```

**Layout XML**:
```xml
Activity+ViewPager+Fragment   
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
![oom](https://user-images.githubusercontent.com/7498978/32711835-027028c8-c87c-11e7-877c-7d56f15ed304.png)

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors
