### ISSUE TITLE
 How can I put nine-patch image with glide into a textview background?

### ISSUE THREAD

**Issue by JinohK** [bumptech/glide#2593]
```java
TextView ballone = ...;
int bubble = R.drawable.bubble // ( bubble.9.png)
Glide.with(con).load(bubble).apply(new RequestOptions().fitCenter()).into(new SimpleTarget<Drawable>() {
                        @Override
                        public void onResourceReady(Drawable resource, Transition<? super Drawable> transition) {
                            balloon.setBackground(resource);
                        }
                    });
```
Nine patches do not work..
The image has nine-patches well applied
 How can I put nine-patch image with glide into a textview background?

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

What do you mean by not work?

**Comment by JinohK** [comment]
@sjudd 

![screenshop](https://user-images.githubusercontent.com/18732102/32759160-569d2194-c92b-11e7-89ab-944686ba4ff5.JPG)

top - glide code
bottom - just textview background`

**Comment by sjudd** [comment]
Can you attach the 9 patch here? What is the type of the decoded Drawable?
