### ISSUE TITLE
how can i the real direct exception which make me failed to load the image??

### ISSUE THREAD

**Issue by VincentJin-91** [bumptech/glide#2596]
when i was failed to load my image, maybe cause by the networkerror,or the servererror. but i can only get the glideexception. and when i call the 'getrootcauses' method, it gaves me a list of exceptions. how can i get the real direct one? 
appreciate it if u can reply. best wishes

**Comment by sjudd** [comment]
I've added some more detail here: http://bumptech.github.io/glide/doc/debugging.html#requestlistener-and-custom-logs
