### ISSUE TITLE
we all urgently need glide support loading animate webp, there is any update plan about it?

### ISSUE THREAD

**Issue by ShamsChu** [bumptech/glide#2597]
We found that Glide did not work well when loading some larger GIFs, and in order to optimize it, we converted the GIF to webp, but it's a surprise that glide does not support loading it, There are someone trying to embed Fresco's webp-animite module in Glide now, but there are some uncontrollable issues. Hopefully glide will support it soon. If there is any intention, let us know thank you.

**Comment by sjudd** [comment]
Duplicate of #571.

I'll add an update there.

**Comment by ShamsChu** [comment]
Really thanks! Looking forward to updating.

**Comment by ShamsChu** [comment]
Is there any way that the current glide version can support animated webp?  we are grateful if there is a solution.

**Comment by sjudd** [comment]
@ShamsChu You can always define your own ``ResourceDecoder`` if you have a library available that can decode animated webps and play them. There is no out of the box solution available at the moment.

**Comment by ShamsChu** [comment]
@sjudd OK thank you i will try.
