### ISSUE TITLE
Add clearDiskCache method

### ISSUE THREAD

**Issue by Teovald** [bumptech/glide#260]
There is already a Glide#clearMemory() method.  
It could be useful to implement Glide#clearDiskCache() as well.

**Comment by nemphys** [comment]
Hi, just implemented this and seems to work OK. In order to make it a Glide class method though, I had to expose it through the Engine class too, since Glide class does not keep a reference of the DiskCache.Factory instance.
Please tell me if this is OK, so that I can prepare the PR.

**Comment by Teovald** [comment]
I don't know it is OK for the mainteners of this project but I started writing this code as well and it don't think that you have a choice here, you need to expose the DiskCache.

**Comment by TWiStErRob** [comment]
You can always initiate the PR, and commit more to that PR if there are comments, Sam will squash them if needed.

**Comment by sjudd** [comment]
Two quick things: I'm not totally against exposing the disk cache, but would just a Glide.clearDiskCache() method work?

Also, do you just need to wipe the cache per build? If so, DiskLruCache has a version number that I believe wipes the cache. We could just expose a method on the disk cache builder that sets the current disk cache version and Glide could be responsible for wiping the cache if the version doesn't match.

No strong feelings about either of these though, looking forward to a pull request!

**Comment by nemphys** [comment]
PR created (#352) , please check.

**Comment by TWiStErRob** [comment]
#352 is merged, shouldn't this be closed?

**Comment by sjudd** [comment]
Yup, this should be closed.

Yeah it looks like we're going to give 4.0 a longer bake time since the changes are pretty substantial. I'll probably push a 3.5.3 in the next few weeks, still working on the exact timing.
