### ISSUE TITLE
centerCrop() only works properly with already downloaded images

### ISSUE THREAD

**Issue by witalobenicio** [bumptech/glide#2600]
**Glide 3.8.0**:

**OkHttp 2.1**:

**Nexus 5 - Android 6.0**:

I'm using Glide this way:

```
Glide.with(getContext())
                    .load(getImageUrl(imageId, accessToken))
                    .centerCrop()
                    .placeholder(R.drawable.default_product_open_screen)
                    .crossFade()
                    .into(image);
```

If I doesn't have the image yet, centerCrop doesn't work properly and my images gets stretched, but if I already have images cached, it works fine.

**Comment by sjudd** [comment]
Try removing the cross fade.

**Comment by witalobenicio** [comment]
Already tried. :/
