### ISSUE TITLE
Different proguard rules at the documentation (website) for AppGlideModule

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [bumptech/glide#2602]
**Glide Version**: 4.3.1

**Issue**

There are different proguard rules at the website for AppGlideModule.

In http://bumptech.github.io/glide/doc/configuration.html#applications you have:
`-keep public class * extends com.bumptech.glide.module.AppGlideModule`

However in http://bumptech.github.io/glide/doc/download-setup.html#proguard you have:
`-keep public class * extends com.bumptech.glide.AppGlideModule`

I believe that the one with `module` is the right one, since it has the correct the package name.

**Comment by sjudd** [comment]
Thanks for reporting this, you're correct that the configuration page has the correct package.
