### ISSUE TITLE
can't use SimpleTarget function in the newer version 4.3.1

### ISSUE THREAD

**Issue by Abdelsattar** [bumptech/glide#2603]
Hello 
 i was using glide 3.7.0 and now updated to 4.3.1  and as shown in the [screenshot ](https://imgur.com/a/9b9Hj)  it shown error and can't be complied and i'm trying to see the documentation i just copy the code from it and trying to use the new still error 
so how i can use the lib while the [documentation not updated with newer functions ](https://imgur.com/a/Od53f)? 
 and how can i see that some code uses `GlideApp` and others uses `Glide`

**Comment by sjudd** [comment]
For posterity: http://bumptech.github.io/glide/doc/migrating.html

And: http://bumptech.github.io/glide/doc/debugging.html#requestlistener-and-custom-logs
