### ISSUE TITLE
Change image style and put it to cache

### ISSUE THREAD

**Issue by AtaerCaner** [bumptech/glide#2604]
**Glide Version:**  4.0.0

I made a `BlackWhiteTransformation()` class for monochrome image, i applied it and it works. But i want to get monochrome images from cache without transformation. Because i don't want to apply transformation every time. Is it posible?

**Comment by sjudd** [comment]
Why don't you want to apply the transformation every time? Do you not want to add it to all your Glide.load calls, or is it expensive and you don't want it to be called?

If it's expensive, you can use ``DiskCacheStrategy.RESOURCE`` or ``DiskCacheStrategy.ALL`` to cache the transformed ``Bitmap``. Although you still need to set the ``Transformation`` in your load calls, it won't be used if the transformed ``Bitmap`` is loaded from disk cache.

**Comment by AtaerCaner** [comment]
Yes, it is expensive for me because `BlackWhiteTransformation()` applies in `onBindViewHolder`. As i understand, .`apply(options)` applied after image caching but before displaying. So i can't put tranformed bitmap to cache. Am i right?

**Comment by sjudd** [comment]
That depends on your ``DiskCacheStrategy``, see http://bumptech.github.io/glide/doc/caching.html#disk-cache-strategies
