### ISSUE TITLE
Glide crash because of context 4.3.1

### ISSUE THREAD

**Issue by Abdelsattar** [bumptech/glide#2605]
in the new version of the Glide 4.3 i'm trying to use it but it crash whenver i use it and whatever context i passed to it 

this is the error showed to me 
  
       java.lang.AbstractMethodError: abstract method "void com.bumptech.glide.module.RegistersComponents.registerComponents(android.content.Context, com.bumptech.glide.Glide, com.bumptech.glide.Registry)"

this is my code i tired 

    Glide.with(getApplicationContext()).
                load(url)
                .into(imageView);

and 

       Glide.with(getContext()).
                load(url)
                .into(imageView);

and it give me that warning 

    W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

and the code in lib in gradle 

    compile 'com.github.bumptech.glide:glide:4.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'

[i posted it into stackoverflow also](https://stackoverflow.com/questions/47327760/glide-crash-because-of-context-4-3-1)

**Comment by sjudd** [comment]
Duplicate of #1974.

You're probably using a v3 integration library

**Comment by Abdelsattar** [comment]
Hello i don't think it is the same as it solved when follow [the answer to SO question ](https://stackoverflow.com/a/47330015/3553843)  to AppGlideModule  Class

`@Override
public boolean isManifestParsingEnabled() {
  return false;
}`

**Comment by sjudd** [comment]
Can you attach the full error message and stack trace you see?
