### ISSUE TITLE
submit() not working with asGif

### ISSUE THREAD

**Issue by yueban** [bumptech/glide#2610]
**Glide Version**:4.3.1

**Integration libraries**:okhttp3-3.6.0

**Device/Android Version**:Android Emulator (x86), API 25

**Issue details / Repro steps / Use case background**: 
I want to resize & crop gif with Glide, but get the origin file as the result.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GifDrawable resource = GlideApp.with(context)
    .asGif()
    .fitCenter()//still not work without fitCenter()
    .load(file.getPath())
    .submit((int) width, (int) height)
    .get();
```

**Comment by sjudd** [comment]
Do the frames of the GIF not match the size you expect? Are you trying to get the original GIF file and expecting it to be modified?

Can you clarify exactly what you're seeing and how that differs from what you expect?

**Comment by yueban** [comment]
The origin gif is 691 * 604.
The result I expect is 256 * 256, But I got 691 * 604 finally.

**Comment by sjudd** [comment]
You want the entire GIF changed in size to 256x256? Or a particular frame?

If you're trying to resize the entire GIF, you can use the gifencoder integration library.

I wouldn't actually recommend doing so. Typically GIFs are optimized for size by their creators in ways the gifencoder library can't (or at least doesn't) match. Re-encoded GIFs are frequently larger on disk and slower to decode than the originals, even if the pixel size of the frames is reduced. Re-encoding GIFs is also quite slow.

That may make sense in some cases (which is why the encoder is available), but use it with caution.

**Comment by yueban** [comment]
Yes, the entire GIF. Thanks for your replying. `gifencoder` should work for me.

**Comment by yueban** [comment]
@sjudd I have tried to use `GifDrawableEncoder` to encode gif like this:
```java
new GifDrawableEncoder().encode(new GifDrawableResource(resource), outputFile, options);
```

But there's two questions:
1. how create an `options` if I want to compress & crop GIF to 256*256
2. the `encode()` method doesn't use `options` according to the source code

**Comment by sjudd** [comment]
You want [``ReEncodingGifResourceEncoder.java``][1]. The ``GifDrawable`` accepts a width and height when it's decoded and the transformation is applied by the encoder using that width and height.

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/integration/gifencoder/ReEncodingGifResourceEncoder.html.

**Comment by yueban** [comment]
`ReEncodingGifResourceEncoder` is in an integration library. But I cant find the library in wiki or issue.

**Comment by sjudd** [comment]
https://mvnrepository.com/artifact/com.github.bumptech.glide/gifencoder-integration/4.3.1

**Comment by yueban** [comment]
hmm....the code below isn't worked. Is there something wrong?
```java
GifDrawable resource = GlideApp.with(context).asGif().load(file.getPath()).submit().get();
File outputFile = new File(StorageUtil.getCacheDir(), System.currentTimeMillis() + EXT_GIF);
new ReEncodingGifResourceEncoder(context, GlideApp.get(context).getBitmapPool()).encode(new GifDrawableResource(resource),
    outputFile, RequestOptions.fitCenterTransform().override(width, height).getOptions());
```

**Comment by CrackerKSR** [comment]
> ```java
> new GifDrawableEncoder().encode(new GifDrawableResource(resource), outputFile, options);
> ```

Link is 404

ReEncodingGifResourceEncoder is here
https://github.com/bumptech/glide/blob/master/integration/gifencoder/src/main/java/com/bumptech/glide/integration/gifencoder/ReEncodingGifResourceEncoder.java

**Comment by CrackerKSR** [comment]
> You want [`ReEncodingGifResourceEncoder.java`](http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/integration/gifencoder/ReEncodingGifResourceEncoder.html.). The `GifDrawable` accepts a width and height when it's decoded and the transformation is applied by the encoder using that width and height.

Link is 404

ReEncodingGifResourceEncoder is here
https://github.com/bumptech/glide/blob/master/integration/gifencoder/src/main/java/com/bumptech/glide/integration/gifencoder/ReEncodingGifResourceEncoder.java

**Comment by CrackerKSR** [comment]
> hmm....the code below isn't worked. Is there something wrong?
> 
> ```java
> GifDrawable resource = GlideApp.with(context).asGif().load(file.getPath()).submit().get();
> File outputFile = new File(StorageUtil.getCacheDir(), System.currentTimeMillis() + EXT_GIF);
> new ReEncodingGifResourceEncoder(context, GlideApp.get(context).getBitmapPool()).encode(new GifDrawableResource(resource),
>     outputFile, RequestOptions.fitCenterTransform().override(width, height).getOptions());
> ```
> 
> I would appreciate if you could write a demo.

Did you get solution ?

**Comment by CrackerKSR** [comment]
> @sjudd I have tried to use `GifDrawableEncoder` to encode gif like this:
> 
> ```java
> new GifDrawableEncoder().encode(new GifDrawableResource(resource), outputFile, options);
> ```
> 
> But there's two questions:
> 
> 1. how create an `options` if I want to compress & crop GIF to 256*256
> 2. the `encode()` method doesn't use `options` according to the source code

Check the official doc 
https://bumptech.github.io/glide/doc/options.html
