### ISSUE TITLE
RejectedExecutionException

### ISSUE THREAD

**Issue by 98ki** [bumptech/glide#2614]
when I change glide to v4,  RejectedExecutionException  up to 40% of all crashs. 

logcat:
`11-19 17:15:57.260 4535 4535 E Tinker.SampleUncaughtExHandler: uncaughtException:Task android.os.AsyncTask$3@d1e01b4 rejected from java.util.concurrent.ThreadPoolExecutor@f83c1dd[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 90]`

Room:XiaoMi/MIUI/V8
--

some other  device thread log:
`java.util.concurrent.RejectedExecutionException
Task android.os.AsyncTask$3@fef38a3 rejected from java.util.concurrent.ThreadPoolExecutor@d2ef7a0[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 563]`
CPU:arm64-v8a
ROOM:samsung/a9xproltezc

**Comment by 98ki** [comment]
all crash device poll size = active sise,   is it failed to create new thread? why?

**Comment by 98ki** [comment]
@jzting @Sahil @magicseth @kypeli @xian

**Comment by sjudd** [comment]
Those are AsyncTasks, nothing to do with Glide?

Why do you think this is related to Glide?

**Comment by 98ki** [comment]
@sjudd Thanks for your question,
This is full logcat:

`
uncaughtException:Task android.os.AsyncTask$3@d1e01b4 rejected from java.util.concurrent.ThreadPoolExecutor@f83c1dd[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 90]
611-19 17:15:57.261 4535 4535 E AndroidRuntime: FATAL EXCEPTION: main
711-19 17:15:57.261 4535 4535 E AndroidRuntime: Process: com.apricotforest.dossier.plus, PID: 4535
811-19 17:15:57.261 4535 4535 E AndroidRuntime: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@d1e01b4 rejected from java.util.concurrent.ThreadPoolExecutor@f83c1dd[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 90]
911-19 17:15:57.261 4535 4535 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
1011-19 17:15:57.261 4535 4535 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
1111-19 17:15:57.261 4535 4535 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
1211-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:607)
1311-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.os.AsyncTask.execute(AsyncTask.java:551)
1411-19 17:15:57.261 4535 4535 E AndroidRuntime: at com.xingshulin.picture.adapter.PictureImageGridAdapter.onBindViewHolder(PictureImageGridAdapter.java:196)
1511-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6279)
1611-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6312)
1711-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5258)
1811-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5521)
1911-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:270)
2011-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:324)
2111-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:337)
2211-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:344)
2311-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
2411-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:742)
2511-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:95)
2611-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.os.Looper.loop(Looper.java:154)
2711-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:5544)
2811-19 17:15:57.261 4535 4535 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
2911-19 17:15:57.261 4535 4535 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
3011-19 17:15:57.261 4535 4535 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
`

then 
`com.xingshulin.picture.adapter.PictureImageGridAdapter.onBindViewHolder(PictureImageGridAdapter.java:196)` 1511-19 17:15:57.261 4535 4535 E AndroidRuntime: at 
`
It's point to  Glide.with(context).asBitmap()

**Comment by kypeli** [comment]
You need to post your code that uses Glide in order to understand how this is related to Glide. The stack trace is inside an AsyncTask and if you use Glide inside that AsyncTask, it doesn't mean the crash is from Glide.

**Comment by 98ki** [comment]
I think It has nothing to do with the code out of Glide, this is the full use in recyclerView adapter, I catch the exception for the time being.
`
    @Override
    public void onBindViewHolder(final RecyclerView.ViewHolder holder, final int position) {
        if (getItemViewType(position) == PictureConfig.TYPE_CAMERA) {
            HeaderViewHolder headerHolder = (HeaderViewHolder) holder;
            headerHolder.headerView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (imageSelectChangedListener != null) {
                        imageSelectChangedListener.onTakePhoto();
                    }
                }
            });
        } else {
            final ViewHolder contentHolder = (ViewHolder) holder;
            final LocalMedia image = images.get(showCamera ? position - 1 : position);
            image.position = contentHolder.getAdapterPosition();
            final String path = image.getPath();
            final String pictureType = image.getPictureType();
            contentHolder.ll_check.setVisibility(selectMode ==
                    PictureConfig.SINGLE ? View.GONE : View.VISIBLE);
            if (is_checked_num) {
                notifyCheckChanged(contentHolder, image);
            }
            selectImage(contentHolder, isSelected(image), false);

            final int picture = PictureMimeType.isPictureType(pictureType);
            boolean gif = PictureMimeType.isGif(pictureType);
            contentHolder.tv_isGif.setVisibility(gif ? View.VISIBLE : View.GONE);
            if (mimeType == PictureMimeType.ofAudio()) {
                contentHolder.tv_duration.setVisibility(View.VISIBLE);
                Drawable drawable = ContextCompat.getDrawable(context, R.drawable.picture_audio);
                StringUtils.modifyTextViewDrawable(contentHolder.tv_duration, drawable, 0);
            } else {
                Drawable drawable = ContextCompat.getDrawable(context, R.drawable.video_icon);
                StringUtils.modifyTextViewDrawable(contentHolder.tv_duration, drawable, 0);
                contentHolder.tv_duration.setVisibility(picture == PictureConfig.TYPE_VIDEO
                        ? View.VISIBLE : View.GONE);
            }
            int width = image.getWidth();
            int height = image.getHeight();
            int h = width * 5;
            contentHolder.tv_long_chart.setVisibility(height > h ? View.VISIBLE : View.GONE);
            long duration = image.getDuration();
            contentHolder.tv_duration.setText(DateUtils.timeParse(duration));
            if (mimeType == PictureMimeType.ofAudio()) {
                contentHolder.iv_picture.setImageResource(R.drawable.audio_placeholder);
            } else {
                RequestOptions options = new RequestOptions();
                if (overrideWidth <= 0 && overrideHeight <= 0) {
                    options.sizeMultiplier(sizeMultiplier);
                } else {
                    options.override(overrideWidth, overrideHeight);
                }
                options.diskCacheStrategy(DiskCacheStrategy.ALL);
                options.centerCrop();
                options.placeholder(R.drawable.image_placeholder);
                try {
                    Glide.with(context)
                            .asBitmap()
                            .load(path)
                            .apply(options)
                            .into(contentHolder.iv_picture);
                } catch (RejectedExecutionException e){}
            }
            if (enablePreview || enablePreviewVideo || enablePreviewAudio) {
                contentHolder.ll_check.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        if (!new File(path).exists()) {
                            Toast.makeText(context, context.getString(R.string.picture_error), Toast.LENGTH_LONG)
                                    .show();
                            return;
                        }
                        changeCheckboxState(contentHolder, image);
                    }
                });

            }
            contentHolder.contentView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (!new File(path).exists()) {
                        Toast.makeText(context, context.getString(R.string.picture_error), Toast.LENGTH_LONG)
                                .show();
                        return;
                    }
                    if (picture == PictureConfig.TYPE_IMAGE && (enablePreview
                            || selectMode == PictureConfig.SINGLE)) {
                        int index = showCamera ? position - 1 : position;
                        imageSelectChangedListener.onPictureClick(image, index);
                    } else if (picture == PictureConfig.TYPE_VIDEO && (enablePreviewVideo
                            || selectMode == PictureConfig.SINGLE)) {
                        int index = showCamera ? position - 1 : position;
                        imageSelectChangedListener.onPictureClick(image, index);
                    } else if (picture == PictureConfig.TYPE_AUDIO && (enablePreviewAudio
                            || selectMode == PictureConfig.SINGLE)) {
                        int index = showCamera ? position - 1 : position;
                        imageSelectChangedListener.onPictureClick(image, index);
                    } else {
                        changeCheckboxState(contentHolder, image);
                    }
                }
            });
        }
    }
`

**Comment by 98ki** [comment]
I think It has nothing to do with the code out of Glide, this is the full use in recyclerView adapter, I catch the exception for the time being.


public void onBindViewHolder(final RecyclerView.ViewHolder holder, final int position) {
if (getItemViewType(position) == PictureConfig.TYPE_CAMERA) {
HeaderViewHolder headerHolder = (HeaderViewHolder) holder;
headerHolder.headerView.setOnClickListener(new View.OnClickListener() {
@override
public void onClick(View v) {
if (imageSelectChangedListener != null) {
imageSelectChangedListener.onTakePhoto();
}
}
});
} else {
final ViewHolder contentHolder = (ViewHolder) holder;
final LocalMedia image = images.get(showCamera ? position - 1 : position);
image.position = contentHolder.getAdapterPosition();
final String path = image.getPath();
final String pictureType = image.getPictureType();
contentHolder.ll_check.setVisibility(selectMode ==
PictureConfig.SINGLE ? View.GONE : View.VISIBLE);
if (is_checked_num) {
notifyCheckChanged(contentHolder, image);
}
selectImage(contentHolder, isSelected(image), false);

        final int picture = PictureMimeType.isPictureType(pictureType);
        boolean gif = PictureMimeType.isGif(pictureType);
        contentHolder.tv_isGif.setVisibility(gif ? View.VISIBLE : View.GONE);
        if (mimeType == PictureMimeType.ofAudio()) {
            contentHolder.tv_duration.setVisibility(View.VISIBLE);
            Drawable drawable = ContextCompat.getDrawable(context, R.drawable.picture_audio);
            StringUtils.modifyTextViewDrawable(contentHolder.tv_duration, drawable, 0);
        } else {
            Drawable drawable = ContextCompat.getDrawable(context, R.drawable.video_icon);
            StringUtils.modifyTextViewDrawable(contentHolder.tv_duration, drawable, 0);
            contentHolder.tv_duration.setVisibility(picture == PictureConfig.TYPE_VIDEO
                    ? View.VISIBLE : View.GONE);
        }
        int width = image.getWidth();
        int height = image.getHeight();
        int h = width * 5;
        contentHolder.tv_long_chart.setVisibility(height > h ? View.VISIBLE : View.GONE);
        long duration = image.getDuration();
        contentHolder.tv_duration.setText(DateUtils.timeParse(duration));
        if (mimeType == PictureMimeType.ofAudio()) {
            contentHolder.iv_picture.setImageResource(R.drawable.audio_placeholder);
        } else {
            RequestOptions options = new RequestOptions();
            if (overrideWidth <= 0 && overrideHeight <= 0) {
                options.sizeMultiplier(sizeMultiplier);
            } else {
                options.override(overrideWidth, overrideHeight);
            }
            options.diskCacheStrategy(DiskCacheStrategy.ALL);
            options.centerCrop();
            options.placeholder(R.drawable.image_placeholder);
            try {
                Glide.with(context)
                        .asBitmap()
                        .load(path)
                        .apply(options)
                        .into(contentHolder.iv_picture);
            } catch (RejectedExecutionException e){}
        }
        if (enablePreview || enablePreviewVideo || enablePreviewAudio) {
            contentHolder.ll_check.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (!new File(path).exists()) {
                        Toast.makeText(context, context.getString(R.string.picture_error), Toast.LENGTH_LONG)
                                .show();
                        return;
                    }
                    changeCheckboxState(contentHolder, image);
                }
            });

        }
        contentHolder.contentView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (!new File(path).exists()) {
                    Toast.makeText(context, context.getString(R.string.picture_error), Toast.LENGTH_LONG)
                            .show();
                    return;
                }
                if (picture == PictureConfig.TYPE_IMAGE && (enablePreview
                        || selectMode == PictureConfig.SINGLE)) {
                    int index = showCamera ? position - 1 : position;
                    imageSelectChangedListener.onPictureClick(image, index);
                } else if (picture == PictureConfig.TYPE_VIDEO && (enablePreviewVideo
                        || selectMode == PictureConfig.SINGLE)) {
                    int index = showCamera ? position - 1 : position;
                    imageSelectChangedListener.onPictureClick(image, index);
                } else if (picture == PictureConfig.TYPE_AUDIO && (enablePreviewAudio
                        || selectMode == PictureConfig.SINGLE)) {
                    int index = showCamera ? position - 1 : position;
                    imageSelectChangedListener.onPictureClick(image, index);
                } else {
                    changeCheckboxState(contentHolder, image);
                }
            }
        });
    }
}

**Comment by 98ki** [comment]
public void onBindViewHolder(final RecyclerView.ViewHolder holder, final int position) {
        if (getItemViewType(position) == PictureConfig.TYPE_CAMERA) {
            HeaderViewHolder headerHolder = (HeaderViewHolder) holder;
            headerHolder.headerView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (imageSelectChangedListener != null) {
                        imageSelectChangedListener.onTakePhoto();
                    }
                }
            });
        } else {
            final ViewHolder contentHolder = (ViewHolder) holder;
            final LocalMedia image = images.get(showCamera ? position - 1 : position);
            image.position = contentHolder.getAdapterPosition();
            final String path = image.getPath();
            final String pictureType = image.getPictureType();
            contentHolder.ll_check.setVisibility(selectMode ==
                    PictureConfig.SINGLE ? View.GONE : View.VISIBLE);
            if (is_checked_num) {
                notifyCheckChanged(contentHolder, image);
            }
            selectImage(contentHolder, isSelected(image), false);

            final int picture = PictureMimeType.isPictureType(pictureType);
            boolean gif = PictureMimeType.isGif(pictureType);
            contentHolder.tv_isGif.setVisibility(gif ? View.VISIBLE : View.GONE);
            if (mimeType == PictureMimeType.ofAudio()) {
                contentHolder.tv_duration.setVisibility(View.VISIBLE);
                Drawable drawable = ContextCompat.getDrawable(context, R.drawable.picture_audio);
                StringUtils.modifyTextViewDrawable(contentHolder.tv_duration, drawable, 0);
            } else {
                Drawable drawable = ContextCompat.getDrawable(context, R.drawable.video_icon);
                StringUtils.modifyTextViewDrawable(contentHolder.tv_duration, drawable, 0);
                contentHolder.tv_duration.setVisibility(picture == PictureConfig.TYPE_VIDEO
                        ? View.VISIBLE : View.GONE);
            }
            int width = image.getWidth();
            int height = image.getHeight();
            int h = width * 5;
            contentHolder.tv_long_chart.setVisibility(height > h ? View.VISIBLE : View.GONE);
            long duration = image.getDuration();
            contentHolder.tv_duration.setText(DateUtils.timeParse(duration));
            if (mimeType == PictureMimeType.ofAudio()) {
                contentHolder.iv_picture.setImageResource(R.drawable.audio_placeholder);
            } else {
                RequestOptions options = new RequestOptions();
                if (overrideWidth <= 0 && overrideHeight <= 0) {
                    options.sizeMultiplier(sizeMultiplier);
                } else {
                    options.override(overrideWidth, overrideHeight);
                }
                options.diskCacheStrategy(DiskCacheStrategy.ALL);
                options.centerCrop();
                options.placeholder(R.drawable.image_placeholder);
                try {
                    Glide.with(context)
                            .asBitmap()
                            .load(path)
                            .apply(options)
                            .into(contentHolder.iv_picture);
                } catch (RejectedExecutionException e){}
            }
            if (enablePreview || enablePreviewVideo || enablePreviewAudio) {
                contentHolder.ll_check.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        // 如原图路径不存在或者路径存在但文件不存在
                        if (!new File(path).exists()) {
                            Toast.makeText(context, context.getString(R.string.picture_error), Toast.LENGTH_LONG)
                                    .show();
                            return;
                        }
                        changeCheckboxState(contentHolder, image);
                    }
                });

            }
            contentHolder.contentView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    // 如原图路径不存在或者路径存在但文件不存在
                    if (!new File(path).exists()) {
                        Toast.makeText(context, context.getString(R.string.picture_error), Toast.LENGTH_LONG)
                                .show();
                        return;
                    }
                    if (picture == PictureConfig.TYPE_IMAGE && (enablePreview
                            || selectMode == PictureConfig.SINGLE)) {
                        int index = showCamera ? position - 1 : position;
                        imageSelectChangedListener.onPictureClick(image, index);
                    } else if (picture == PictureConfig.TYPE_VIDEO && (enablePreviewVideo
                            || selectMode == PictureConfig.SINGLE)) {
                        int index = showCamera ? position - 1 : position;
                        imageSelectChangedListener.onPictureClick(image, index);
                    } else if (picture == PictureConfig.TYPE_AUDIO && (enablePreviewAudio
                            || selectMode == PictureConfig.SINGLE)) {
                        int index = showCamera ? position - 1 : position;
                        imageSelectChangedListener.onPictureClick(image, index);
                    } else {
                        changeCheckboxState(contentHolder, image);
                    }
                }
            });
        }
    }


I think It has nothing to do with the code out of Glide, this is the full use in recyclerView adapter, I catch the exception for the time being. @kypeli

**Comment by 98ki** [comment]
By the way , I think RejectedExecutionException is releate to ThreadPoolExecutor,  not always beacuse of AsyncTask。

**Comment by sjudd** [comment]
Just to be clear, this is always the exception trace you see? On line 196 in PictureImageGridAdapter.onBindViewHolder and in AsyncTask.execute? Or is there another stack trace you see that isn't included here?

```
android.os.AsyncTask.executeOnExecutor(AsyncTask.java:607) 1311-19 17:15:57.261 4535 4535 E AndroidRuntime: at android.os.AsyncTask.execute(AsyncTask.java:551) 1411-19 17:15:57.261 4535 4535 E AndroidRuntime: at com.xingshulin.picture.adapter.PictureImageGridAdapter.onBindViewHolder(PictureImageGridAdapter.java:196)
```

Glide doesn't use AsyncTasks or start them in into(). Did you have a previous version of this file that did start an AsyncTask at that line?
