### ISSUE TITLE
check image is loaded image(url)

### ISSUE THREAD

**Issue by MrDany** [bumptech/glide#2615]
In my android app i have 4 url for one single image, to check if url 1 is broken then go to url 2 and the same way until the end. i using **Glide 4.3.1** for loading image like this :

```java
@GlideModule
    public final class ContentImageLoading extends AppGlideModule{
     private int checkAndShow4Image(Context context, View view, int img_id, String img_url) {
      try {            
          GlideApp
                  .with(context)
                .load(img_url)
                .diskCacheStrategy(DiskCacheStrategy.DATA)
                .error(R.drawable.ic_broken_image)
                .fallback(R.drawable.ic_broken_image)
                .transition(DrawableTransitionOptions.withCrossFade())
                .into((ImageView) view.findViewById(img_id));

} catch (Exception e) {
        e.printStackTrace();
        return -1;
    }
    return 0;
}
}
```

the method is returning before of complete loading. what is the best way for waiting for do it?

**Comment by sjudd** [comment]
You can't block the main thread to load an image. If you want a callback for when the asynchronous load does complete you can use a [``RequestListener``][1] or custom ``Target``. 

If you're trying to do this on a background thread, you can use [``submit()``][2]

[1]: http://bumptech.github.io/glide/doc/debugging.html#requestlistener-and-custom-logs
[2]: http://bumptech.github.io/glide/doc/getting-started.html#background-threads
