### ISSUE TITLE
Is there similar like onlyRetrieveFromCache in v3 ?

### ISSUE THREAD

**Issue by dodatw** [bumptech/glide#2616]
We are using Glide 3.8.
I want to load image from cache only if it have.  After investigate, it seem supported in V4.
But our project have no plan upgrade to 4.x in short time. Is there other way to "onlyRetrieveFromCache" in 3.8 ?

Thanks.

**Comment by sjudd** [comment]
Yes, you can use a custom model loader. See the discussion in #639.

**Comment by dodatw** [comment]
Thanks a lot, let me check!
