### ISSUE TITLE
Can we cache local file and assign Url for CacheID ?

### ISSUE THREAD

**Issue by dodatw** [bumptech/glide#2617]
Can we cache local file and assign Url for CacheID ?

Glide 3.8
We are implement a image upload function.
After upload, we have a Url that can download this image.
Can Glide insert the cache by local file and use this Url for CacheID ?
that we don't need to download again. (load image by this Url)

**Comment by sjudd** [comment]
It's not possible to directly insert an image into Glide's cache like this.

You can however define a custom ``ModelLoader`` that given a url first checks a cache you control before delegating to Glide's default http ``ModelLoader`` if the image isn't found in your cache.

**Comment by dodatw** [comment]
Let me share my solution, we implement a special File class:
```
	private static class CacheFile extends File {
		private final String mUrl;
		CacheFile(@NonNull String pathname, @NonNull String url) {
			super(pathname);
			mUrl = url;
		}

		@Override
		public int hashCode() {
			return mUrl.hashCode();
		}

		@Override
		public String toString() {
			return mUrl;
		}

		@SuppressWarnings("EqualsWhichDoesntCheckParameterClass")
		@Override
		public boolean equals(Object obj) {
			return mUrl.equals(obj);
		}
	}
```
Call preload

```
Glide.with(context)
		.load(new CacheFile(filePath, imageUri))
		.apply(new RequestOptions().diskCacheStrategy(DiskCacheStrategy.DATA))
		.preload();
```

It seem work!

**Comment by dodatw** [comment]
Sorry, it have issue
