### ISSUE TITLE
Glide doesn't load my custom ResourceDecoder/ResourceEncoder

### ISSUE THREAD

**Issue by idish** [bumptech/glide#2618]
**Glide Version**: 4.3.1

**Integration libraries**: No

**Device/Android Version**: LG G4

**Issue details / Repro steps / Use case background**: 
So, I tried to migrate my project from Glide version 3.7.1 to 4.3.1, and I'm facing some issues.
I'm using facebook conceal to enable disk caching in encrypted way.
I took a look at this pull request as an inspiration code (even though I just realized that it fails for that guy too):
https://github.com/bumptech/glide/pull/1994/files

Seems as the SourceDecoder and SourceEncoder never get called, (decode and encode, and even "handles").
After some debugging It seems as that the decoder isn't even getting loaded.

Before I post some further code,
Is there any issue that might arise when glide tries to use a custom decoder/encoder?

Here's the relevant code that adds those:
```java
@Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        // register ModelLoaders here.
        registry.append(EncryptedFileContainer.class, InputStream.class, new EncryptedFileModelLoaderFactory());
        registry.prepend(byte[].class, new ConcealFileEncoder());
        registry.prepend(File.class, byte[].class, new ConcealFileDecoder());
    }
```

Why it seems that Glide just ignores those?
It looks like Glide just uses the built-in encoder/decoder.

I suspect that the problem might be in my ModelLoaderFactory, so I'm posting its code:
```java
public class EncryptedFileModelLoaderFactory implements ModelLoaderFactory<EncryptedFileContainer, InputStream> {
    @Override
    public ModelLoader<EncryptedFileContainer, InputStream> build(MultiModelLoaderFactory multiFactory) {
        return new ModelLoader<EncryptedFileContainer, InputStream>() {
            @NonNull
            @Override
            public LoadData<InputStream> buildLoadData(final EncryptedFileContainer model, int width, int height, Options options) {
                return new LoadData<>(model, new DataFetcher<InputStream>() {

                    private InputStream stream;

                    @Override
                    public void loadData(Priority priority, DataCallback<? super InputStream> callback) {
                        try {
                            stream = model.decrypt();
                            callback.onDataReady(stream);
                        } catch (Exception e) {
                            callback.onLoadFailed(e);
                        }
                    }

                    @Override
                    public void cleanup() {
                        cancel();
                    }

                    @Override
                    public void cancel() {
                        if (stream != null) {
                            try {
                                stream.close(); // interrupts decode if any
                                stream = null;
                            } catch (IOException ignore) {
                            }
                        }
                    }

                    @NonNull
                    @Override
                    public Class<InputStream> getDataClass() {
                        return InputStream.class;
                    }

                    @NonNull
                    @Override
                    public DataSource getDataSource() {
                        return DataSource.LOCAL;
                    }
                });
            }

            @Override
            public boolean handles(EncryptedFileContainer encryptedFileContainer) {
                return true;
            }
        };

    }

    @Override
    public void teardown() {

    }
}
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

```java
GlideApp.with(mActivity)
                .load(photoFileContainer)
                .centerCrop()
                .into(holder.image);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
No errors or any debug messages in the log

**Comment by sjudd** [comment]
What ``DiskCacheStrategy`` are you using?

It looks like your ``ModelLoader`` produces an ``InputStream``, but your Encoder expects a ``byte[]``. If you want your Encoder to handle the ``InputStream`` from your ``ModelLoader``, it needs to encode ``InputStream``s. 

Similarly, for your Decoder, Glide typically decodes either ``InputStream``s or ``ByteBuffer``s, you might make your ResourceDecoder handle an ``InputStream`` instead of a ``byte[]`` and try again.

**Comment by idish** [comment]
Thanks for you answer,
Can My ResourceDecoder decode from `InputStream` to `ByteBuffer` and then the other "built-in" 
`ResourceDecoder`s will take in place and decode my created `ByteBuffer` to `Bitmap`, specifically the `ByteBufferBitmapDecoder` class will do it.

I'm asking it because I want the built-in decoders to take as much place as possible in my custom encoding/decoding process. 
`ByteBufferBitmapDecoder` decodes `ByteBuffer` to `Bitmap` in an elegant way, so I'd like to use it.
Is there any solution for that, or my custom `ResourceDecoder` has to take full responsibility in creating the `Bitmap` resource?

**Comment by sjudd** [comment]
Yup ResourceEncoder now deals with Files instead of streams which makes this harder. 

Fortunately if you take a look at BitmapEncoder it's pretty simple, you can even copy the options values so your encoder will obey them as well.

As for ResourceDecoder, you can delegate to Glide's original decoder. You can accept a ByteBuffer, decode whatever encryption you've applied and then pass the resulting ByteBuffer or InputStream to a wrapped decoder.

So when you create your decoder, you end up with something like:
```java
ResourceDecoder<ByteBuffer, Bitmap> myDecoder = new MyCustomDecoder(new ByteBufferBitmapDecoder(...));
```

And then your decode method is something like:
```java
@Override
public Resource<Bitmap> decode(ByteBuffer source, int width, int height, Options options)
    throws IOException {
   ByteBuffer decryped = decrypt(source);
   return  byteBufferBitmapDecoder.decode(source, width, height, options);
}
```

**Comment by idish** [comment]
> Yup ResourceEncoder now deals with Files instead of streams which makes this harder.
Fortunately if you take a look at BitmapEncoder it's pretty simple, you can even copy the options values so your encoder will obey them as well.

I understand and I'm aware of that `BitmapEncoder` does pretty basic logic, encoding the bitmap. 
But copying all of its logic into my custom `Encoder` seems not the right thing to do given that my need is not too exceptional.
