### ISSUE TITLE
url contains <> with an error

### ISSUE THREAD

**Issue by hdszylcd19** [bumptech/glide#2619]
Hello, I encountered such a problem with Glide. The version is 3.7.0. I load such a url, like this "http://data.yunzuoye.net/cgi-bin/shbmath.cgi?\begin{cases}x+5\<5x+1\\\xm>1\end{cases} ". However, "<5x + 1 \\ x-m>" will be discarded. The picture that is loaded is not complete. What should I do? Many thanks

this is right:
![shbmath](https://user-images.githubusercontent.com/19562544/33050520-3ec1336a-cea0-11e7-85cc-25750f6987c1.gif)

this is wrong:
![shbmath 1](https://user-images.githubusercontent.com/19562544/33050527-44bd0cd0-cea0-11e7-9c07-534fae53047a.gif)

**Comment by sjudd** [comment]
This appears to work in Glide v4.
