### ISSUE TITLE
use downloadonly() with always report ExecutionException 

### ISSUE THREAD

**Issue by xieyingwu** [bumptech/glide#2621]
using the downloadonly() to load pics to disk cache ,config the diskCache is 2G,but when the cache files near to 1G,the downloadonly() get the FutureTarget<File> fileFutureTarget.get() throws the java.util.concurrent.ExecutionException;

Glide config such as 

        File storageDirectory = Environment.getExternalStorageDirectory();
        String downloadDirectoryPath = storageDirectory + "/" + GlideConstants.GLIDE_PAD_CACHE_FOLDER_NAME;
        DiskLruCacheFactory diskLruCacheFactory = new DiskLruCacheFactory(downloadDirectoryPath, GlideConstants.GLIDE_PAD_CACHE_SIZE);
        /*设置本地磁盘文件大小*/
        builder.setDiskCache(diskLruCacheFactory);

download code such as 

FutureTarget<File> fileFutureTarget = Glide.with(IhApplication.getContext())
                   .load(loadTask.url)
                    .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);
File file = fileFutureTarget.get();

the code execute in Thread

**Comment by sjudd** [comment]
Can you provide the full stack trace of the ExecutionException and its cause?

If it's a timeout and you're using Glide's default networking library, you can increase Glide's timeouts with [``timeout()``][1]

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/request/RequestOptions.html#timeout-int-

**Comment by xieyingwu** [comment]
java.util.concurrent.ExecutionException
at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:189)
at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:100)
at com.ihoment.pad.main.load.LoadManager$4.run(LoadManager.java:278)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at java.lang.Thread.run(Thread.java:818)

**Comment by sjudd** [comment]
Can you provide the cause of the ExecutionException? 

What version of Glide are you using?

**Comment by xieyingwu** [comment]
compile 'com.github.bumptech.glide:glide:3.7.0'

**Comment by xieyingwu** [comment]
i debug the code ,in the source code the cache and source decode to null,so the result is fail

**Comment by sjudd** [comment]
Ah, yeah in v3 the ExecutionException hides the original error. If you put a break point in RequestFutureTarget in onLoadFailed, you should see the original exception message.

**Comment by xieyingwu** [comment]
but the Exception is null, because the exception is from decode() method to get target is null ,so the onLoadFailed be invoked; the exception is only ExecutionException and exception point at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:189)
,you said the original exception message is not existed.

**Comment by sjudd** [comment]
Next thing I can point you to is here: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging.

Usually when you just get a null error, unless the error is hidden, it means that the decoder and often BitmapFactory returned null or some generic decode failure message.  If so, that would imply the data it received was partial or contained an invalid image.

**Comment by xieyingwu** [comment]
I had debug the source code to EngineRunnable class,EngineJob class but the exception is null;
I delete a part of the cache files ,and execute the downloadonly() method ,it can download successful,but when the cache files size is near the config cache sizes,the downloadonly() is throw the ExecutionException,and no other exception messages.

**Comment by sjudd** [comment]
In v4 the error messages are better, but there's a reason why the ExecutionException is being thrown that you can probably find in the debugger. If the sdcard is almost full that might be why. That would just imply an IOException in the ModelLoader doing the downloading.
