### ISSUE TITLE
Full load on error everytime?

### ISSUE THREAD

**Issue by vyshas** [bumptech/glide#2622]
**Glide Version**:4.3.1

**Integration libraries**:No integration libraries

**Device/Android Version**: Samsung J5 Android 6.0.1, TC55 Android 4.2

**Issue details / Repro steps / Use case background**: 

Does the .error() gets called every time regardless of success or failure from load(). For example:
```
private RequestBuilder<Bitmap> requestBuilder(MItem mItem,boolean centreCrop)() {

 File imageFile = new File(
                Environment.getExternalStorageDirectory() + "/" + STORAGE_DIRECTORY_NAME + "/" + mItem.getId().toString() + "/" mItem.getFilename() + ".jpeg");

        RequestOptions requestOptions = new RequestOptions();
        if (centreCrop) requestOptions.centerCrop();

return GlideApp.with(context)
                .asBitmap()
                .apply(requestOptions) 
               .load(imageFile)   .error(GlideApp.with(context).asBitmap().apply(requestOptions).load(getBitmapFromDb(mediaItem)));
}
```

In the above case, I can see it always loads from DB regardless of loading from File succeeds or not. Is this an expected behavior . I think the image is loaded from Storage but the Glide api makes sure it caches the load from error block.  

On running the logs ,I can see that engine loads from storage:
Started new load in 0.0ms, key:
 EngineKey{model=/storage/sdcard0/Exampleapp/bf1ad72d-8bc3-4c60-ab5d-4c879fff6551/2d5e77f5-03be-424a-a474-1f3d8f5ea9cd_bf1ad72d-8bc3-4c60-ab5d-4c879fff6551.jpeg

I only want to load the image from Database if there is error in loading from File in SD card.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```
@GlideModule
public class ExampleAppGlideModule extends AppGlideModule {}


RequestManager requestManager = GlideApp.with(context);

```

**Comment by sjudd** [comment]
error() should only start a new request if the original request fails.

You could try putting a break point here: https://github.com/bumptech/glide/blob/fac5db753615f6419950c438d48ea873d5bdcb97/library/src/main/java/com/bumptech/glide/request/ErrorRequestCoordinator.java#L145 and seeing whether (and why) that gets called.
