### ISSUE TITLE
DiskLruCacheWrapper: java.io.IOException: write failed: ENOSPC (No space left on device)

### ISSUE THREAD

**Issue by sherlyme** [bumptech/glide#2625]
Hello,  I got a problem:

ImageViews in my app which load image by Glide, could not load any images or given any toast when the SDcard of android O phone was filled to 100%.

What can i do if i wanna to give users some imfromation under this condition?

LOG:
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): java.io.IOException: write failed: ENOSPC (No space left on device)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at libcore.io.IoBridge.write(IoBridge.java:558)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at java.io.FileOutputStream.write(FileOutputStream.java:326)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at java.io.BufferedWriter.close(BufferedWriter.java:269)

11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at com.bumptech.glide.disklrucache.DiskLruCache.rebuildJournal(DiskLruCache.java:373)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at com.bumptech.glide.disklrucache.DiskLruCache.open(DiskLruCache.java:237)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.getDiskCache(DiskLruCacheWrapper.java:59)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.get(DiskLruCacheWrapper.java:76)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at com.bumptech.glide.load.engine.a.a(DecodeJob.java:215)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at com.bumptech.glide.load.engine.a.a(DecodeJob.java:85)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at com.bumptech.glide.load.engine.q.c(EngineRunnable.java:108)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at com.bumptech.glide.load.engine.q.run(EngineRunnable.java:1099)

11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at java.lang.Thread.run(Thread.java:764)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at libcore.io.Linux.writeBytes(Native Method)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at libcore.io.Linux.write(Linux.java:288)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:345)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	at libcore.io.IoBridge.write(IoBridge.java:553)
11-20 11:39:42.051 W/DiskLruCacheWrapper(28011): 	... 20 more

**Comment by sjudd** [comment]
I'm not totally sure what you're asking? You can check the GlideException to see if it's ENOSPC and show your own toast maybe? http://bumptech.github.io/glide/doc/debugging.html#requestlistener-and-custom-logs

**Comment by sherlyme** [comment]
My Glide version is 3.7.0, and the 'e' in following code is null:
...
new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }
...

**Comment by sjudd** [comment]
Reasons to fill out the issue template++ :).

You could try to check the disk size when a load fails? I'm not sure I have any good ideas beyond that.

**Comment by sherlyme** [comment]
I decide to upgrade its version to the newest one.  Thanks! Happy Thanksgiving Day!

**Comment by sherlyme** [comment]
Hello again!  During uploading the version from 3.7.0 to 4.3.0,  I cannot find a good way to implement my own DataFetcher to replace getId() which override in 3.7.0. My  DataFetcher  is to realize one more request by the given url, because this url should be used to get another full URL(which according to the target image) at first.    How can I realize this function?
