### ISSUE TITLE
Interrupt request by url

### ISSUE THREAD

**Issue by YBill** [bumptech/glide#2628]
Hi, TWiStErRob，I am using Glide，glide version：4.0.0
I encountered a problem, I hope you can help answer.

If I load the gif image like this
```java
GlideApp.with(activity).asGif().load(gifUrl).into(imageView);
```
When he is loading I have to cancel the loading can be this way
```java
GlideApp.with(activity).clear(imageView);
```
But when I load gif does not pass in the ImageView object, for example
```java
GlideApp.with(context).asGif().load(gifUrl).into(new SimpleTarget<GifDrawable>() {
      @Override
       public void onResourceReady(GifDrawable resource, Transition<? super GifDrawable> transition) {
        }
 });
```
At this moment, how do I cancel this gif loaded by gifUrl?

**Comment by sjudd** [comment]
[``into()``][1] returns a [``Target``][2], which you can pass to [``clear()``][3]:

```java
Target target = GlideApp.with(context).load(url).into(new SimpleTarget<>() { ... });
...
GlideApp.with(context).clear(target)
```

http://bumptech.github.io/glide/doc/targets.html#cancellation-and-re-use

Be careful of SimpleTarget, if you don't also null out all references to the resource loaded by the SimpleTarget when you clear it, you may see incorrect images, graphical corruption, or crashes.

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/RequestBuilder.html#into-Y-
[2]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/request/target/Target.html
[3]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/RequestManager.html#clear-com.bumptech.glide.request.target.Target-

**Comment by YBill** [comment]
Thank you for your answer, it is my negligence did not look carefully document.
