### ISSUE TITLE
Cannot resolve method dontAnimate

### ISSUE THREAD

**Issue by klaszlo8207** [bumptech/glide#2630]
I used the old library (v3.7)

But now I using the newest library 4.3.1

It says 'Cannot resolve method dontAnimate'

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/migrating.html#transitionoptions.

Specifically ``TransitionOptions.dontTransition()``.

**Comment by klaszlo8207** [comment]
.transition(TransitionOptions.dontTransition())

can not find :(

**Comment by klaszlo8207** [comment]
It looks like default has no animation, so it is good, thanks

**Comment by sjudd** [comment]
For posterity: ``new TransitionOptions().dontTransition()``.
