### ISSUE TITLE
How to download images to local file system?

### ISSUE THREAD

**Issue by Thuantanon** [bumptech/glide#2632]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Thuantanon** [comment]
请问怎么下载图片到本地文件夹？

**Comment by Thuantanon** [comment]
请问怎么下载图片到本地文件？
성함이 어떻게 다운로드 사진 다 로컬 폴더를?
どのフォルダに画像をダウンロードしていただけますか？
 Извините  , как загрузить  фотографии  на  локальные папки  ? 
Darf Ich Fragen, Wie der download der bilder zu Einem lokalen ordner?
Puis - je vous demander comment le téléchargement de l'image à un dossier local?

**Comment by sjudd** [comment]
Please fill out the template when filing new issues. 

Although I'm impressed that you've included your question in six different languages, unfortunately I don't speak any of them :/.
