### ISSUE TITLE
java.lang.NoClassDefFoundError while setting a Bitmap to an ImageView

### ISSUE THREAD

**Issue by sumitsahoo** [bumptech/glide#2633]
**Glide Version**: 4.3.1

**Integration libraries**: Bitmap

**Device/Android Version**: Moto G5 (Android 7.1.1), Pixel (Android 8.1 preview)

**Issue details / Repro steps / Use case background**:  While setting an Bitmap I am getting below error

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider;
                                                                   at com.bumptech.glide.Glide.<init>(Glide.java:303)
                                                                   at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:354)
                                                                   at com.bumptech.glide.Glide.initializeGlide(Glide.java:234)
                                                                   at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:176)
                                                                   at com.bumptech.glide.Glide.get(Glide.java:160)
                                                                   at com.bumptech.glide.Glide.getRetriever(Glide.java:583)
                                                                   at com.bumptech.glide.Glide.with(Glide.java:632)
...
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.gifdecoder.GifDecoder$BitmapProvider" on path: DexPathList
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

Using below line to load Bitmap : 

```
Glide.with(getActivity())
                    .load(profileBitmap)
                    .apply(RequestOptions.circleCropTransform())
                    .into(imageViewUserProfile);
```

Here profileBitmap is a Bitmap. Bitmap works when I set it to ImageView directly with `imageViewUserProfile.setImageBitmap(profileBitmap);`

**Comment by sjudd** [comment]
You have some kind of a build issue. Can you provide your ``build.gradle`` file where you're including Glide? Did you exclude Glide's transitive dependencies?

**Comment by sumitsahoo** [comment]
Added the lib with below gradle code 

```
implementation 'com.github.bumptech.glide:glide:4.3.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'
```

And here is the dependency tree. I think this is because of dex files. Due to multi dex the class def is missing but I have added multidex support as well added multidex install code to Application class.

```
\--- com.github.bumptech.glide:glide:4.3.1
     +--- com.github.bumptech.glide:gifdecoder:4.3.1
     |    \--- com.android.support:support-annotations:26.0.2
     +--- com.github.bumptech.glide:disklrucache:4.3.1
     \--- com.github.bumptech.glide:annotations:4.3.1

```

**Comment by sjudd** [comment]
It's possible, but I'm afraid I don't have any other ideas on what to do. If you do figure it out, please post the solution here so we can all benefit.

Also let me know if you have any other specific questions I can answer, sorry I'm not of more help here.

**Comment by sumitsahoo** [comment]
Fixed the crash issue by changing the gradle import for dex library
from `implementation 'com.android.support:multidex:1.0.2'` to `implementation 'com.android.support:multidex:1.0.1'`

After this Glide works just fine.

**Comment by sumitsahoo** [comment]
Closing the issue since issue is resolved.

**Comment by vetkolisanket** [comment]
I was also facing the same issue, adding the transitive = true field did the trick as mentioned in [this link](https://stackoverflow.com/a/47828211/4291698) . Please upvote the answer if it solves your issue :)

**Comment by VicJSoft** [comment]
You can add this code to your gradle (Module app), that error occur when you don´t add the  **"transitive=true"**


    **implementation ("com.github.bumptech.glide:glide:4.9.0@aar") {
        transitive = true
    }**

I invite you to read this information [Glide](https://bumptech.github.io/glide/doc/download-setup.html#gradle)
