### ISSUE TITLE
Can't load image from local storage data/user folder 

### ISSUE THREAD

**Issue by maxi182Eman** [bumptech/glide#2634]
**Glide version:** 4.2.0
**Device:** Nexus 5 and 5X(Genymotion)

I have downloaded images with download manager, the ones are located in "/data/user/0/MY_PROJECT_NAME/files/" folder, I have checked the downloaded image  accessing to the folder by Android device monitor, and I was able to open and see the image when I pulled out from the device.
The following are all the ways i tryed to set the image to Glide but nothing worked
```
1 - File imageFile = new File("file:///data/user/0/MY_PROJECT_NAME/files/3.png");
2 - File imageFile = new File("data/user/0/MY_PROJECT_NAME/files/3.png");

 Uri uri = Uri.fromFile(imageFile);
 mRequestManager = Glide.with(this);
1 mRequestManager.load(uri).into(giftImageView);
2 mRequestManager.load(imageFile).into(giftImageView);
```
This is the path to the image, but when download manager completes, i set the destination folder as data/user/0/MY_PROJECT_NAME/files/3.png, which is retrived with `mContext.getFilesDir().getAbsolutePath()+ name of the file` 
![export 4](https://user-images.githubusercontent.com/33100169/33172796-4b8e669e-d030-11e7-8d39-f39879f6b62f.png)

**Comment by sjudd** [comment]
Maybe:

```java
File toLoad = new File(mContext.getFilesDir(), "3.png");
Glide.with(fragment)
  .load(toLoad)
  .into(view);
```

> 1 - File imageFile = new File("file:///data/user/0/MY_PROJECT_NAME/files/3.png");
This is definitely incorrect, you're creating a File object with a uri, which I don't think works at all

> 2 - File imageFile = new File("data/user/0/MY_PROJECT_NAME/files/3.png");
This looks like you're missing the leading '/'?

Either way you shouldn't be hard coding paths or appending Strings typically.

You can also test out that the File paths you're providing to Glide are valid by just checking ``exists()`` or ``file.length() > 0``. If exists is false or the length is 0, Glide definitely won't be able to load it. It might be worth trying a few variations of constructing your File in the debugger and using those methods to make sure you're getting the path you expect.

**Comment by maxi182Eman** [comment]
Thanks @sjudd for your response. I have tried what you are suggesting and some other ways. but I am not having any luck, Actually i was hardcoding the path there for testing.
This is how i save the file
`        request.setDestinationInExternalFilesDir(mContext, mContext.getFilesDir().getAbsolutePath(), "/" + url.substring(url.lastIndexOf("/") + 1));
`
Trying the following i am getting "false" when i call exists for each of them, realy weired as the file is there... look the image of the ADM i have uploaded before. 

`
        File newfile2 = new File("file://data/user/0/co.uk.e_man.doppels.dev.live/files/4.png");
        File newfile3 = new File("file://data/user/0/co.uk.e_man.doppels.dev.live/files/4.png");
        File newfile4 = new File("data/user/0/co.uk.e_man.doppels.dev.live/files/4.png");


        File toLoad = new File(getFilesDir().getPath(), "4.png");
        File toLoad2 = new File(getFilesDir().getAbsolutePath(), "4.png");
        File toLoad3 = new File(getFilesDir().getAbsolutePath(), "4");
        File toLoad4 = new File(getFilesDir().getPath(), ".4");`

**Comment by sjudd** [comment]
What file path are you passing in to the download manager?

It actually looks like you're looking at your internal storage, when the download manager is saving the files to external storage?

Maybe you need [``getExternalCacheDir``][1] instead?

[1]: https://developer.android.com/reference/android/content/Context.html#getExternalCacheDirs()

**Comment by maxi182Eman** [comment]
hey @sjudd , 
When i set the destination file to the Download Manager I am seting it like this:
`request.setDestinationInExternalFilesDir(mContext, mContext.getFilesDir().getAbsolutePath(), "/" + url.substring(url.lastIndexOf("/") + 1))`
And when I try to get the file I am trying to opening the same place..

**Comment by sjudd** [comment]
[``setDestinationInExternalFilesDir``][1] uses [``Context.getExternalFilesDir``][2] as the directory and the the filename you give it as the file name. 

However, setDestinationInExternalFilesDir also takes a ``Nullable`` dirType, which is supposed to be one of the DIRECTORY_* methods in [``Environment``][3], like ``Environment.DIRECTORY_PICTURES``

You're passing in ``getFilesDir`` as the ``dirType``, which isn't correct. It appears that doing so just adds a subdirectory to ``getExternalFilesDir`` with the path of whatever you pass in.

You probably should be doing (untested):

```java
request.setDestinationInExternalFilesDir(mContext, /*dirPath=*/ null, url.substring(url.lastIndexOf("/") + 1))

File expected = new File(mContext.getExternalFilesDir(), url.substring(url.lastIndexOf("/") + 1))
Glide.with(fragment)
  .load(expected)
  .into(imageView)
```

Either way, take a closer look at the javadoc for ``setDesintationInExternalFilesDir``, that describes in a lot more detail where your file is saved and what the various parameters do.

[1]: https://developer.android.com/reference/android/app/DownloadManager.Request.html#setDestinationInExternalFilesDir(android.content.Context, java.lang.String, java.lang.String)
[2]: https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String)
[3]: https://developer.android.com/reference/android/os/Environment.html.

**Comment by maxi182Eman** [comment]
Good stuff mate!, thanks!

**Comment by KishorMorais** [comment]
add the below line in application tag in manifest

android:requestLegacyExternalStorage="true"
