### ISSUE TITLE
use recyclerview+glide load big local image happen memory leak

### ISSUE THREAD

**Issue by cyhwtc** [bumptech/glide#2635]
RequestOptions options = new RequestOptions()
                .placeholder(R.drawable.loading_bar)
                .error(R.drawable.ic_no_images)
                .encodeFormat(Bitmap.CompressFormat.WEBP)
                .format(DecodeFormat.PREFER_RGB_565)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .encodeQuality(30)
                .dontAnimate();
        GlideApp.with(fragment)
                .load(imagePath)
                .apply(options)
                .transition(new DrawableTransitionOptions().dontTransition())
                .into(imageView);

**Comment by maxi182Eman** [comment]
How are you passing the image path?

**Comment by sjudd** [comment]
Please fill out the [issue template][1] when filing new issues. 

What version of Glide are you using? Why do you think there's a memory leak? Have you taken a look at what is retaining memory? See http://bumptech.github.io/glide/doc/debugging.html#memory-leaks

[1]: https://github.com/bumptech/glide/blob/9b0741231d4214d2609fa27ddbe6764df51701d3/ISSUE_TEMPLATE.md
