### ISSUE TITLE
Difference between using SimpleTarget and BitmapTransformation to blur image

### ISSUE THREAD

**Issue by haihack** [bumptech/glide#2642]
**Glide Version**:
    compile 'com.github.bumptech.glide:glide:4.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'

**Issue details / Repro steps / Use case background**: 
I'm using Glide to blur image in two ways. 
Firstly, creating BlurTransformation class extends BitmapTransformation then processing received bitmap in transform() method as below:
In BlurTransformation  class
```java
@Override
protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
        return blurRenderScript(toTransform, 25);
}
```
Loading image
```java
GlideApp.with(mContext)
               .load("https://avatarfiles.alphacoders.com/527/52773.jpg")
               .transform(new BlurTransformation(mContext))
               .into(ivBackground);
```   

Secondly, after getting bitmap of a image resource by using SimpleTarget<Bitmap>, I perform blurring operation like the first way.
```java
GlideApp.with(mContext).asBitmap()
                .load("https://avatarfiles.alphacoders.com/527/52773.jpg")
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap resource, Transition<? super Bitmap> transition) {
                        Bitmap blurred = blurRenderScript(resource, 25);
                        ivBackground.setImageBitmap(blurred);
                    }
                });
```
The blurRenderScript method i used in both ways
 ```java
    private Bitmap blurRenderScript(Bitmap smallBitmap, int radius) {
        RenderScript rs = RenderScript.create(mContext);
        Bitmap blurredBitmap = smallBitmap.copy(Bitmap.Config.ARGB_8888, true);

        Allocation input = Allocation.createFromBitmap(rs, blurredBitmap, Allocation.MipmapControl.MIPMAP_FULL, Allocation.USAGE_SHARED);
        Allocation output = Allocation.createTyped(rs, input.getType());

        // Load up an instance of the specific script that we want to use.
        ScriptIntrinsicBlur script = ScriptIntrinsicBlur.create(rs, Element.U8_4(rs));
        script.setInput(input);

        script.setRadius(radius);
        script.forEach(output);
        output.copyTo(blurredBitmap);

        return blurredBitmap;
    }
```
However, there is a considerable different between the degree of blurring image in two methods as following:
![blurtransformation](https://user-images.githubusercontent.com/12783799/33219412-b2cbd31a-d174-11e7-8e2a-b3df3d892366.png)  ![simpletarget](https://user-images.githubusercontent.com/12783799/33219413-b3009046-d174-11e7-8ed6-eae80162da29.png)

Could you please make me clear this thing?
How can I reach the blurring degree like the second way by using BlurTransformation?

**Comment by sjudd** [comment]
Is the size of ``ivBackground`` substantially different from the size of the Bitmap you're blurring? Does using ``.override(Target.SIZE_ORIGINAL)`` when loading into ``ivBackground`` help?

Using SIZE_ORIGINAL isn't generally recommended because it can lead to loading much large than necessary Bitmaps, but it might explain the difference between the two cases here.

**Comment by haihack** [comment]
I included exactly what I used above, there is no `.override(Target.SIZE_ORIGINAL)`, so the Bitmap must be resized before loading into `ivBackground` in both ways

**Comment by sjudd** [comment]
``into(ivBackground)`` without an override will use whatever the size of ``ivBackground`` is. ``SimpleTarget`` without a size will use ``Target.SIZE_ORIGINAL``.

Even though the area the image covers is the same in both cases, the size that Glide uses to load the image may be different.

**Comment by haihack** [comment]
Thank you for helping me know more about how glide works. 
After adding `.override(Target.SIZE_ORIGINAL)`, I got the same result as SimpleTarget way.
Just the last question. As you said:
> Using SIZE_ORIGINAL isn't generally recommended because it can lead to loading much large than necessary Bitmaps, but it might explain the difference between the two cases here.
If I know for sure that the image's real size always smaller than the ImageView size, should I use `Target.SIZE_ORIGINAL` to reduce memory use to load bitmap?

**Comment by haihack** [comment]
Thank you for helping me know more about how glide works. 

After adding `.override(Target.SIZE_ORIGINAL)`, I got the same result as SimpleTarget way.
Just the last question. As you said:
> Using SIZE_ORIGINAL isn't generally recommended because it can lead to loading much large than necessary Bitmaps, but it might explain the difference between the two cases here.

If I know for sure that the image's real size always smaller than the ImageView size, does using `Target.SIZE_ORIGINAL` to load bitmap cost lower memory than the way not use it ?

**Comment by sjudd** [comment]
> If I know for sure that the image's real size always smaller than the ImageView size, does using Target.SIZE_ORIGINAL to load bitmap cost lower memory than the way not use it? I guess that because gilde doesn't have to scale image to ImageView size

That will actually depend on the transformation, some upscale and some don't (most of the default ones do).

It's often hard to know for sure that a given pixel width and height is always reasonable for a given device because of the range of devices and screen densities out there. What works fine on a high end device may eat a lot more memory than necessary on a low end device. Using ``Target.SIZE_ORIGINAL`` isn't terrible, it's just something to be cautious of. If it works for your use case and you know you won't have scaling or memory issues on low end devices, great!
