### ISSUE TITLE
How to implement custom compression configuration

### ISSUE THREAD

**Issue by cyhwtc** [bumptech/glide#2644]
How to implement custom compression configuration

**Comment by cyhwtc** [comment]
how to  implement custom image compression sampleSize?

**Comment by sjudd** [comment]
Please fill out [the issue template][1] when filing new issues.

Do you want to change the compression quality? From 0-100? Or the type? From JPEG to PNG?

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md

**Comment by cyhwtc** [comment]
i want to change the sampleSize, is there a way to implement ?

when i read the method calculateScaling in Downsampler, the sampleSize can not  satisfy my big picture around have 20M used in the reclyeview,maybe happen OOM.


some code here :

int powerOfTwoSampleSize;
    // BitmapFactory does not support downsampling wbmp files on platforms <= M. See b/27305903.
    if (Build.VERSION.SDK_INT <= 23
        && NO_DOWNSAMPLE_PRE_N_MIME_TYPES.contains(options.outMimeType)) {
      powerOfTwoSampleSize = 1;
    } else {
      powerOfTwoSampleSize = Math.max(1, Integer.highestOneBit(scaleFactor));
      if (rounding == SampleSizeRounding.MEMORY
          && powerOfTwoSampleSize < (1.f / exactScaleFactor)) {
        powerOfTwoSampleSize = powerOfTwoSampleSize << 1;
      }
    }

**Comment by cyhwtc** [comment]
Glide Version:4.3.1

Integration libraries:  compile 'com.github.bumptech.glide:glide:4.3.1'

Device/Android Version: 4.4

Issue details / Repro steps / Use case background: lots of big picture around have 20M used in the reclyeview

i want to change the sampleSize, is there a way to implement ?

when i read the method calculateScaling in Downsampler, the sampleSize can not satisfy my big picture around have 20M used in the reclyeview,maybe happen OOM.

some code here :

int powerOfTwoSampleSize;
// BitmapFactory does not support downsampling wbmp files on platforms <= M. See b/27305903.
if (Build.VERSION.SDK_INT <= 23
&& NO_DOWNSAMPLE_PRE_N_MIME_TYPES.contains(options.outMimeType)) {
powerOfTwoSampleSize = 1;
} else {
powerOfTwoSampleSize = Math.max(1, Integer.highestOneBit(scaleFactor));
if (rounding == SampleSizeRounding.MEMORY
&& powerOfTwoSampleSize < (1.f / exactScaleFactor)) {
powerOfTwoSampleSize = powerOfTwoSampleSize << 1;
}
}

**Comment by sjudd** [comment]
Glide will downsample automatically based on the size provided by the [``Target``][1] you're using. If you're loading into an ``ImageView``, this will be the size of the ``ImageView`` with some caveats if you're using wrap_content. 

If you're using [``override()``][2], any parameters you pass there will supersede the size provided by the ``Target``.

As the issue template requests, can you please add the Glide load line and XML of any views you're using? I might be able to provide more specific input if I know what exactly it is that you're calling.

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/request/target/Target.html#getSize-com.bumptech.glide.request.target.SizeReadyCallback-. 
[2]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/request/RequestOptions.html#override-int-int-
