### ISSUE TITLE
first loadFromActiveResources()  then  loadFromCache()

### ISSUE THREAD

**Issue by chanchangxing** [bumptech/glide#2648]
when I download the code,I find in the **Engine** class, loadFromActiveResources() and loadFromCache() has exchange, I want to figure out why?
I'm Chinese, not good at English

**Comment by chanchangxing** [comment]
thanks,it is helpful.
If so, in **Engine** class, load() 's comment didn‘t update.

**Comment by sjudd** [comment]
Thanks for pointing out the Javadoc is out of date, I'll update it.
