### ISSUE TITLE
Default value of isLowMemoryDevice 

### ISSUE THREAD

**Issue by Errryx** [bumptech/glide#2650]
**Glide Version**:4.2.0

**Integration libraries**:OkHttp3

**Device/Android Version**:Galaxy J1 mini 4.1.1

**Issue details / Repro steps / Use case background**: 
MemorySizeCalculator#isLowMemoryDevice will return FALSE on device with android os < KITKAT,
which means some low-end devices will use maxSizeMultiplier instead of lowMemoryMaxSizeMultiplier when calculate maxSize and could more possibly to produce OOM error on such devices. Maybe it will be better if this method returns true for these cases or more accurately, the return value should depends on the total memory size.

ref:https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/cache/MemorySizeCalculator.java

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
new MemorySizeCalculator.Builder(CommonUtilsEnv.getInstance().getApplicationContext())
                .setMaxSizeMultiplier(0.2f)
                .setLowMemoryMaxSizeMultiplier(0.15f)
                .build();
```

**Layout XML**:
N/A

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
```

**Comment by sjudd** [comment]
Sure I'm not opposed to setting it to true by default. Would you mind sending a pull request?
