### ISSUE TITLE
How to load git just once

### ISSUE THREAD

**Issue by yinjinyj** [bumptech/glide#2659]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
I'm not sure what you're asking, please file a new issue with the template filled out and more detail.
