### ISSUE TITLE
Glide V4.3.1 :   What kind of Jar should be downloaded instand of add compiles in build.gradle ?

### ISSUE THREAD

**Issue by sherlyme** [bumptech/glide#2660]
In the instruction of glide v4 (http://bumptech.github.io/glide/doc/download-setup.html), add dependencies :
compile 'com.github.bumptech.glide:glide:4.3.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'

In releases, there are kinds of Jars (https://github.com/bumptech/glide/releases
), and I tried to download & add three of them to my Android Studio projects'libs, but it did not work.
compile files('src/main/libs/compiler-4.3.1.jar')
compile files('src/main/libs/annotation-4.3.1.jar')
compile files('src/main/libs/gson-2.8.0.jar')

**Comment by sjudd** [comment]
There's a fat jar you can download on GitHub here: https://github.com/bumptech/glide/releases/tag/v4.3.1. It's called `glide-full`. If you're using the generated API you can also download the compiler and annotation jars.

If that doesn't work, please provide more details. What exactly isn't working?
