### ISSUE TITLE
can't find "android.suppport.v4.app.fragment"

### ISSUE THREAD

**Issue by luckyly** [bumptech/glide#2667]
Hi，It show me that can't find "android.suppport.v4.app.fragment",it happens  in glide.class.

My gradle ：

dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.github.chrisbanes:PhotoView:2.0.0'
    compile 'com.android.support:support-v4'
    compile 'com.github.bumptech.glide:glide:4.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'
}

It always show this crash.How can i fix it?

**Comment by sjudd** [comment]
Please include the stack trace that you're seeing.

**Comment by luckyly** [comment]
Thanks.  I import  the highest  support-v4,it wrok.
