### ISSUE TITLE
Create custom ModelLoader

### ISSUE THREAD

**Issue by michael-snow** [bumptech/glide#2669]
How to create custom ModelLoader like this:

`GlideApp.load(new Avatar("avatar data string",width,height))`

in background generate Bitmap or Drawable from Avatar object and load into imageView.

**Glide Version**:4.3.1

**Integration libraries**:No

**Comment by sjudd** [comment]
Lots more documentation here: http://bumptech.github.io/glide/tut/custom-modelloader.html.

I'll close this for now, but feel free to comment here or on the article with feedback/suggestions/questions.
