### ISSUE TITLE
Problem with custom ModelLoader for base64 images

### ISSUE THREAD

**Issue by AleksanderMielczarek** [bumptech/glide#2677]
**Glide Version**: 4.3.1

**Issue details**: 
I have images from some SOAP API that are encoded in base64. To load them directly with Glide I decided to wrote custom ModelLoader. 

**Glide load line**:
```java
GlideApp.with(activity)
        .load(Data().apply { code = licensePlateData.licensePlateImgId })
        .into(view.imageLicense)
```

**GlideModule**:
```java
@GlideModule
class MyAppGlideModule : AppGlideModule() {

    override fun registerComponents(context: Context, glide: Glide, registry: Registry) {
        super.registerComponents(context, glide, registry)
        val app = context.applicationContext as MyApplication
        registry.append(Data::class.java, ByteArray::class.java, MyImageLoaderFactory(app.api))
    }
}
```

**Loader**:
```java
class MyImageLoaderFactory(private val api: Api) : ModelLoaderFactory<Data, ByteArray> {

    override fun teardown() {

    }

    override fun build(multiFactory: MultiModelLoaderFactory): ModelLoader<Data, ByteArray> {
        return MyImageLoader(api)
    }
}

class MyImageLoader(private val api: Api) : ModelLoader<Data, ByteArray> {

    override fun buildLoadData(model: Data, width: Int, height: Int, options: Options): ModelLoader.LoadData<ByteArray> {
        val key = "code:${model.code};width:$width;height:$height"
        return ModelLoader.LoadData<ByteArray>(ObjectKey(key), MyImageDataFetcher(api, GetImageRequest().apply { data = model }))
    }

    override fun handles(model: Data): Boolean {
        return true
    }
}

class MyImageDataFetcher(private val api: Api, private val request: GetImageRequest) : DataFetcher<ByteArray> {

    private val disposables = CompositeDisposable()

    override fun cleanup() {
        disposables.clear()
    }

    override fun loadData(priority: Priority, callback: DataFetcher.DataCallback<in ByteArray>) {
        api.getImage(request) //soap request
                .map { it.image.decodeBase64() } //translate String to ByteArray
                .subscribe({ callback.onDataReady(it) }, {
                    if (it is Exception) {
                        callback.onLoadFailed(it)
                    } else {
                        callback.onLoadFailed(MyException(it))
                    }
                })
                .addTo(disposables)
    }

    override fun cancel() {
        disposables.clear()
    }

    override fun getDataClass(): Class<ByteArray> {
        return ByteArray::class.java
    }

    override fun getDataSource(): DataSource {
        return DataSource.REMOTE
    }

}
```

**Stack trace / LogCat**:
```ruby
com.bumptech.glide.Registry$NoSourceEncoderAvailableException: Failed to find source encoder for data class: class [B
    at com.bumptech.glide.Registry.getSourceEncoder(Registry.java:534)
    at com.bumptech.glide.load.engine.DecodeHelper.getSourceEncoder(DecodeHelper.java:232)
    at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:74)
    at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:45)
    at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
    at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
    at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
    at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
```

I think that I'm missing something to make it work. 

Best regards
Aleksander Mielczarek

**Comment by sjudd** [comment]
You need one more component since ``byte[]`` is a new data type. You need to add and register an [``Encoder<byte[]>``][1]. There's already a ``ByteBuffer`` encoder so a simple way to implement this would be to just wrap the ``by[]`` in a ``ByteBuffer`` with ``ByteBuffer.wrap()`` and then delegate to the existing  [``ByteBufferEncoder``][2].

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/load/Encoder.html.
[2]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/load/model/ByteBufferEncoder.html

**Comment by AleksanderMielczarek** [comment]
Thank you. Works like a charm. I thought that ByteArray is supported out of the box. All I did was to replace ByteArray with ByteBuffer like you said. 

Now it looks like this: 

package com.comarch.clm.mobileapp

import android.content.Context
import com.bumptech.glide.Glide
import com.bumptech.glide.Priority
import com.bumptech.glide.Registry
import com.bumptech.glide.annotation.GlideModule
import com.bumptech.glide.load.DataSource
import com.bumptech.glide.load.Options
import com.bumptech.glide.load.data.DataFetcher
import com.bumptech.glide.load.model.ModelLoader
import com.bumptech.glide.load.model.ModelLoaderFactory
import com.bumptech.glide.load.model.MultiModelLoaderFactory
import com.bumptech.glide.module.AppGlideModule
import com.bumptech.glide.signature.ObjectKey
import com.comarch.clm.mobileapp.domain.entity.Data
import com.comarch.clm.mobileapp.domain.entity.soap.getimage.GetImageRequest
import com.comarch.clm.mobileapp.domain.model.api.ClmApi
import com.comarch.clm.mobileapp.ui.ClmApplication
import com.comarch.clm.mobileapp.webservice.ClmException
import io.reactivex.disposables.CompositeDisposable
import io.reactivex.rxkotlin.addTo
import java.nio.ByteBuffer


/**
 * Created by Aleksander Mielczarek on 12.11.2017.
 */
@GlideModule
class MyAppGlideModule : AppGlideModule() {

    override fun registerComponents(context: Context, glide: Glide, registry: Registry) {
        super.registerComponents(context, glide, registry)
        val app = context.applicationContext as MyApplication
        registry.append(Data::class.java, ByteBuffer::class.java, MyImageLoaderFactory(app.api))
    }
}

class MyImageLoaderFactory(private val api: Api) : ModelLoaderFactory<Data, ByteBuffer> {

    override fun teardown() {

    }

    override fun build(multiFactory: MultiModelLoaderFactory): ModelLoader<Data, ByteBuffer> {
        return MyImageLoader(api)
    }
}

class MyImageLoader(private val api: Api) : ModelLoader<Data, ByteBuffer> {

    override fun buildLoadData(model: Data, width: Int, height: Int, options: Options): ModelLoader.LoadData<ByteBuffer> {
        val key = "code:${model.code};width:$width;height:$height"
        return ModelLoader.LoadData<ByteBuffer>(ObjectKey(key), MyImageDataFetcher(api, GetImageRequest().apply { data = model }))
    }

    override fun handles(model: Data): Boolean {
        return true
    }
}

class ClmImageDataFetcher(private val api: Api, private val request: GetImageRequest) : DataFetcher<ByteBuffer> {

    private val disposables = CompositeDisposable()

    override fun cleanup() {
        disposables.clear()
    }

    override fun loadData(priority: Priority, callback: DataFetcher.DataCallback<in ByteBuffer>) {
        api.getImage(request)
                .map { it.image.decodeBase64() }
                .subscribe({ callback.onDataReady(ByteBuffer.wrap(it)) }, {
                    if (it is Exception) {
                        callback.onLoadFailed(it)
                    } else {
                        callback.onLoadFailed(MyException(it))
                    }
                })
                .addTo(disposables)
    }

    override fun cancel() {
        disposables.clear()
    }

    override fun getDataClass(): Class<ByteBuffer> {
        return ByteBuffer::class.java
    }

    override fun getDataSource(): DataSource {
        return DataSource.REMOTE
    }

}

**Comment by sjudd** [comment]
Yeah that's a reasonable point, we could add an ``Encoder`` for ``byte[]``

**Comment by sjudd** [comment]
Actually I looked in to this a bit more and I think this is WAI.

Glide supports ``byte[]`` as a Model type, so you can pass it to ``load()``, but we don't support it as a data type and we don't have encoders or decoders registered that can handle ``byte[]``s. The two default supported data types are ``InputStream`` and ``ByteBuffer``. Given how easy it is to convert from a ``byte[]`` to either of those types, this isn't worth fixing.

If there's somewhere you would have expected to see that documented, let me know and I'll see what I can do to clarify.

**Comment by sjudd** [comment]
... So I should have remembered, but Glide already has support for Data URIs: https://github.com/bumptech/glide/blob/c3dafde00a061bafcd43a739336ca3503af13a7d/library/src/main/java/com/bumptech/glide/load/model/DataUrlLoader.java#L19.

This was contributed a while ago, but it seems fairly coherent. It doesn't support base64 strings directly, but basically all you'd need to do to make it work is prepend data:image/jpeg;base64, on the front of your base64 strings and it would work just fine.
