### ISSUE TITLE
Replace android.graphics.BitmapFactory by ygloo-ymagine

### ISSUE THREAD

**Issue by renatopeterman** [bumptech/glide#2679]
Hi!

I'm replacing the `android.graphics.BitmapFactory` by this [yahoo ygloo-ymagine](https://github.com/YahooArchive/ygloo-ymagine) library in my project.
Does Glide use the `android.graphics.BitmapFactory` to load the bitmaps? How would be the best way to replace it?

**Comment by sjudd** [comment]
Yes. You could replace Glide's default ``ResourceDecoder`` with one that uses that: http://bumptech.github.io/glide/doc/configuration.html#registering-components.

Keep in mind that library hasn't been updated in two years and is in Yahoo's archive, which their site says is a "A place to lovingly move outmoded and less supported projects for you to visit and fork."

**Comment by mufumbo** [comment]
hey @sjudd would such approach make any sense? We saw the archived message, but just want to try this to see if it makes any difference. What's your opinion?

**Comment by sjudd** [comment]
I'm not sure actually, I've never used ygloo-ymagine.

That said, I'd imagine the primary benefit would be consistent and updatable code across all versions of Android. That seems like it goes away for an unmaintained library.

It sort of depends on your use case though I guess?
