### ISSUE TITLE
 3.7.0 version upgrades to 4.0.0 discovery error: Failed resolution of: Lcom/bumptech/glide/Glide;

### ISSUE THREAD

**Issue by 501956430** [bumptech/glide#2686]
3.7.0 version upgrades to 4.0.0 discovery error: Failed resolution of: Lcom/bumptech/glide/Glide;
![image](https://user-images.githubusercontent.com/20204491/33643699-c4647680-da7b-11e7-8084-8fdf3683c0c8.png)
![image](https://user-images.githubusercontent.com/20204491/33643710-dc8333be-da7b-11e7-8e98-81daf11284aa.png)

**Comment by 501956430** [comment]
![image](https://user-images.githubusercontent.com/20204491/33643796-4090f36e-da7c-11e7-90ad-86cae0f39f27.png)

**Comment by sjudd** [comment]
Why are you using ``provided``? For setup instructions, see: http://bumptech.github.io/glide/doc/download-setup.html

**Comment by 501956430** [comment]
Thanks
