### ISSUE TITLE
Picture loaded success placeholder not hidden

### ISSUE THREAD

**Issue by 501956430** [bumptech/glide#2687]
glide version:
`compile  'com.github.bumptech.glide:glide:4.0.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'`

![image](https://user-images.githubusercontent.com/20204491/33648155-7c877570-da93-11e7-842f-d9dd5c4e9bf3.png)

![image](https://user-images.githubusercontent.com/20204491/33648074-1c1b8dfc-da93-11e7-8071-ab39b1e32db4.png)

**Comment by 501956430** [comment]
image style= border-radius:100%   The circular picture becomes a square

**Comment by zhangchaojiong** [comment]
@501956430  how to slove it. I was in trouble too.

**Comment by sjudd** [comment]
What Glide load line are you using?

Avoid cross fades if you're using them, see http://bumptech.github.io/glide/doc/transitions.html#common-errors or https://muyangmin.github.io/glide-docs-cn/doc/transitions.html#常见错误

**Comment by zhangchaojiong** [comment]
> @sjudd thx！
> 
> I replace 'code1' with 'code2' , and the problem is solved!

code1:


`    .transition(new DrawableTransitionOptions().crossFade())`

code2:
```
    .transition(new DrawableTransitionOptions()
                            .crossFade(new DrawableCrossFadeFactory.Builder().setCrossFadeEnabled(true)))
```

**Comment by 501956430** [comment]
@zhangchaojiong thx .
@sjudd 
Circular picture will become a square, how to deal with ?

**Comment by sjudd** [comment]
@501956430 I'm not sure, what Glide load line are you using? Why would you expect those pictures to be round?

**Comment by 501956430** [comment]
@sjudd I set the corner of the photo: border-radius:100px; When the glide is loaded, the rounded corners will fail。
Like the blue mark above

**Comment by sjudd** [comment]
border-radius is css? Are you using a web view? Or some library?

**Comment by 501956430** [comment]
@sjudd React Native

**Comment by sjudd** [comment]
Ah I'm not sure how to help then. If you're asking Glide to load an image with a transformation that rounds the image or the corners of the image, I can help you look at that.

If you're asking Glide to load a square image and some other library to round the image when the image is displayed, I can't help you with that.

Maybe try filing an issue with React Native and linking here?

The only generic advice I can think of is try removing the transition altogether. Glide's cross fades are done with ``TransitionDrawable`` which doesn't always play nicely with other libraries or views.

**Comment by goyalish** [comment]
I am also facing the same issue. Has anyone found any solution?
<img width="270" alt="Screenshot 2019-05-15 at 2 47 20 PM" src="https://user-images.githubusercontent.com/13303203/57764081-5fb70700-7720-11e9-9b04-fc923cb0a16c.png">
