### ISSUE TITLE
Crash due to reference to app.FragmentManager on Pre-11 devices

### ISSUE THREAD

**Issue by littledot** [bumptech/glide#269]
Running Glide 3.3.1 on a pre-11 device will throw 

```
E/dalvikvm﹕ Could not find class 'android.app.FragmentManager', referenced from method
com.bumptech.glide.manager.RequestManagerRetriever.handleMessage
```

As README.md states: Glide requires a minimum sdk version of 10, I think Glide should handle this gracefully.

Thanks

**Comment by facundobringas** [comment]
I'm having the same problem using Glide 3.7.0, should I open a new issue? Is there any way to solve it?

**Comment by TWiStErRob** [comment]
Read this issue first, do a clean build and make sure you have the latest Glide, and not using framework fragment `Fragment`; if it still happens you can create a new issue, but I suggest to also create a small repro repo.
