### ISSUE TITLE
Glide tries to decode the resource before it was encoded

### ISSUE THREAD

**Issue by idish** [bumptech/glide#2691]
**Glide Version**: 4.4.0

**Integration libraries**: None

**Device/Android Version**: LG G4 Android 6.1

**Issue details / Repro steps / Use case background**: 
I have created custom `ModelLoader`, `ResourceEncoder` and `ResourceDecoder`.
From my debugging it seems that whenever Glide tries to load my model, will first go through `decode` method of my `ResourceDecoder` even though it wasn't yet encoded via my `ResouceEncoder`.
Therefore, my `decode` method raises an exception, glide "swallows" it, and afterwards the `encode` method of my `ResouceEncoder` is called.
The next times that glide tries to load the same model, the `decode` method logic works as it is now indeed cached. 

I suspect this isn't the expected behavior of `Glide`? 
Does `Glide` thinks that the resource is already cached for some reason?
If any code snippets are required, please let me know!

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(mActivity)
                        .load(photoFileContainer)
                        .centerCrop()
                        .into(holder.image);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Glide's load order is:

1. Check the data disk cache
2. Check the resource disk cache
3. Try to retrieve the source

The first load step 1 and 2 will fail and it sounds like step 3 succeeds.

Once Glide has the data, it tries all registered decoders that can produce the requested resource (Drawable is the default) from whatever data was loaded. If one of them fails, Glide just moves on to the next one.

It sounds like your decoder is failing to decode the source of the image, but one of Glide's default decoders is successfully decoding it and passing it to your decoder.

The resource cache is written to after the resource is decoded and transformed. The data cache is written to with whatever the raw source data is.

**Comment by sjudd** [comment]
See also: http://bumptech.github.io/glide/doc/caching.html

**Comment by idish** [comment]
In fact, my initial problem was that my `ResourceDecoder` raised an uncaught exception, and that caused my app to crash, and only after debugging I figured out what was happening.

From [Glide's Flow](https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit)
it looks like `ResourceDecoder`s shouldn't be called at all if the resource is not yet in cache?

If I'm wrong and `ResourceDecoder`s are called even when the resource is not yet cached, it may cause app crashed (as happend to me) when there's uncaught exception, and the other default `ResouceDecoder`s won't be called at all.

**Comment by sjudd** [comment]
That's the old v3 flow. It's similar, but ResourceDecoder and Decoder are identical in v4, so this is the expected behavior.

Typically failures in decoders won't crash your app. If you can paste the stack trace I'm happy to look.

**Comment by idish** [comment]
I understand.
I cannot see any stack trace. As when my ResourceDecoder fails. It throws a native exception. So there's no way for the catch it I guess. (Conceal facebook library migrated to c++ implementation since v2.01 so it now throws native exceptions)

**Comment by sjudd** [comment]
Ah so yeah, you'll have to handle being called in your ResourceDecoder with the data before it's written to cache to be robust.

You can probably also make it work by explicitly using DiskCacheStrategy.DATA, but that can be really inefficient for local data because it basically just copies the image/video into your application's cache directory.
