### ISSUE TITLE
StringSignature class not found

### ISSUE THREAD

**Issue by maxi182Eman** [bumptech/glide#2692]
Glide version: 4.2.0 com.github.bumptech.glide:glide:4.2.0'
Device: Lg Nexus 5 , phisical device.

I am trying to instantiate StringSignature class, but is not found.
`         RequestOptions options =
                new RequestOptions()
                         .diskCacheStrategy(DiskCacheStrategy.NONE)
                         .signature(new StringSignature(
                                System.currentTimeMillis()));  // StringSignature is not in glide..
        Glide
                .with(this)
                .load(url)
                .apply(options)
                .apply(RequestOptions.circleCropTransform())
                .into(mediaImageView);`

**Comment by sjudd** [comment]
Use [``ObjectKey``](http://bumptech.github.io/glide/javadocs/440/com/bumptech/glide/signature/ObjectKey.html) instead.

**Comment by maxi182Eman** [comment]
That worked thanks!

**Comment by sjudd** [comment]
Great thanks for letting me know.

**Comment by mhamed0httb** [comment]
Thank you a lot man, you saved my life :D <3 :*

**Comment by ishaan-khan** [comment]
This is very misguiding since the documentation suggests using StringSignature.
