### ISSUE TITLE
Maybe there is an error in documentation ?

### ISSUE THREAD

**Issue by Muyangmin** [bumptech/glide#2700]
Hi brother,  today I found a change of [2017-05-20-snapshots.md](https://github.com/bumptech/glide/blob/gh-pages/_posts/2017-05-20-snapshots.md), in the top section there add a line :

>  Although Glide provides out of the box support for most common types of models (URLs, Uris, file paths etc), you may occasionally run into a type that Glide doesn't support. You may also run in to cases where you want to customize or tweak Glide's default behavior. You may even want to integrate a new way of fetching images or a new networking library beyond those available in Glide's [integration libraries][3].

This line seems to be a little (but not very) strange in that page, and they actually appeared once in [2017-12-05-custom-modelloader.md](https://github.com/bumptech/glide/blob/gh-pages/_posts/2017-12-05-custom-modelloader.md), so I want to ask for your confirmation, is this expected, or a copy-paste mistake?

PS: I did not edit this file section in PR #2699 , because I think I should ask for you first 😃

**Comment by sjudd** [comment]
Yup that must be a copy/paste error, it should be removed, thanks for pointing it out!.

**Comment by Muyangmin** [comment]
That's OK, now I've included a commit in #2699 , and can be merge in a time.
