### ISSUE TITLE
How can i used Signature in glide 4.1.1

### ISSUE THREAD

**Issue by DPatel02** [bumptech/glide#2704]
Hello everyone,
i'm using glide 4.1.1(**compile 'com.github.bumptech.glide:glide:4.1.1'**) and i'm little confuse how to use signature in this update.
i have common name image(**temp.png**) file in sdcard and do overwrite image(**temp.png**) but still i get old image in application image is not refreshed.
in short i can not update image when overwrite it(under same name).
please give me solution of change image.

Thank you

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/caching.html#custom-cache-invalidation

**Comment by DPatel02** [comment]
Thank you.
still it is now worked.
can you explain elaborate with an example.

**Comment by DPatel02** [comment]
Thank you
