### ISSUE TITLE
Builders doesn't work well with Kotlin

### ISSUE THREAD

**Issue by eygraber** [bumptech/glide#2705]
Structuring the `RequestBuilder` and `RequestOptions` in a way that potentially returns a new object is not great practice. I get that you added the `CheckResults` annotation to make users aware of this, but it completely kills the experience on Kotlin, where things like `apply` or `with` don't work well with it (and forced me to completely refactor my nice, clean idiomatic Kotlin to something really ugly 😢 ).

Is there any way to change this behavior so that builders always return the same object?

**Comment by sjudd** [comment]
Could you provide some examples of why this doesn't work well in Kotlin and what would work better? I'm not particularly familiar with the language.
