### ISSUE TITLE
Cannot find symbol class KeyEventCompat

### ISSUE THREAD

**Issue by shah-nishant** [bumptech/glide#2707]
We tried integrating Glide with our project. After adding glide as dependencies in build.gradle, project compilation started failing. It throws an error saying 

> Cannot find symbol class KeyEventCompat

build.gradle
`implementation 'com.github.bumptech.glide:glide:4.4.0'`
`annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'`

**Glide Version 4.4.0**

**Comment by sjudd** [comment]
Please provide the full stack trace or exception message. You may need to run the build command on the command line to see a reasonable error message.

**Comment by Abo-Hani** [comment]
This has nothing to do with the library. This class was deprecated in API level 26.0.0.

ref: https://developer.android.com/reference/android/support/v4/view/KeyEventCompat.html

**Comment by sjudd** [comment]
Duplicate of #2730.
