### ISSUE TITLE
No cached version of com.github.bumptech.glide:compiler:4.4.0 available for offline mode.

### ISSUE THREAD

**Issue by xFJournet** [bumptech/glide#2710]
Error:Could not resolve all files for configuration ':app:debugAnnotationProcessorClasspath'.
> Could not resolve com.github.bumptech.glide:compiler:4.4.0.
  Required by:
      project :app
   > No cached version of com.github.bumptech.glide:compiler:4.4.0 available for offline mode.
   > No cached version of com.github.bumptech.glide:compiler:4.4.0 available for offline mode.

Android Studio 3.0.1
Build #AI-171.4443003, built on November 10, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

app.gradle:
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile 'com.github.bumptech.glide:glide:4.4.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'
    implementation 'com.android.support:support-v4:27.0.2'
}
![image](https://user-images.githubusercontent.com/10260076/33865022-bab1c396-df2a-11e7-99cb-00438be2a52c.png)

**Comment by sjudd** [comment]
You're building in offline mode with Gradle. I think there's an intellij setting or a command line flag, not related to Glide.

**Comment by xFJournet** [comment]
I don't set the offline mode with Gradle
![image](https://user-images.githubusercontent.com/10260076/33866720-35807a6a-df33-11e7-9ec6-2c611d2322d1.png)

**Comment by xFJournet** [comment]
thank you,my fault,I forget modify compiler setting

**Comment by dheerajjha** [comment]
remove compiler's --offline mode. It will work!
