### ISSUE TITLE
Unable to change Svg color at run time

### ISSUE THREAD

**Issue by KarishmaAgrawal** [bumptech/glide#2726]
**# **Method to load svg using glide from server:**** 
 @Override
    public void loadSvgImage(final Context context, final String uri, final ImageView imageView, int placeHolderDrawable) {

        RequestBuilder<PictureDrawable> requestBuilder = GlideApp.with(context)
                .as(PictureDrawable.class)
                .placeholder(placeHolderDrawable)
                .dontAnimate()
                .listener(new SvgSoftwareLayerSetter());

        String credential = okhttp3.Credentials.basic(BuildConfig.ZIP_USERNAME, BuildConfig.ZIP_PASSWORD);
        GlideUrl urlGlide = new GlideUrl(uri, new LazyHeaders.Builder()
                .addHeader("Authorization", credential)
                .build());
        requestBuilder.load(urlGlide).into(imageView);
    }

**# Svg Decoder class**

public class SvgDecoder implements ResourceDecoder<InputStream, SVG> {

    @Override
    public boolean handles(InputStream source, Options options) throws IOException {
        // TODO: Can we tell?
        return true;
    }

    public Resource<SVG> decode(InputStream source, int width, int height, Options options)
            throws IOException {
        try {
            SVGBuilder svgBuilder = new SVGBuilder();
            svgBuilder.readFromInputStream(source);
            svgBuilder.setWhiteMode(false);
            SVG svg = svgBuilder.build();
            return new SimpleResource<>(svg);
        } catch (SVGParseException ex) {
            throw new IOException("Cannot load SVG from stream", ex);
        }
    }

}

Now i want to pass find and replace color from loadSvgImageMethod to SvgDecoder class. How can i do that, so i can change color of my svg image.

**Comment by sjudd** [comment]
You can use an [``Option``][1], which you can then extract from the ``Options`` object passed in to ``decode()`` in your ``ResourceDecoder``.

For an example, see Glide's VideoBitmapDecoder that defines options for frame times:
https://github.com/bumptech/glide/blob/cfae30aa55ad38d69fa3997662e2d791de2c110e/library/src/main/java/com/bumptech/glide/load/resource/bitmap/VideoBitmapDecoder.java#L43

There's some information on using options in the docs site here: http://bumptech.github.io/glide/doc/options.html#component-options

[1]: http://bumptech.github.io/glide/javadocs/440/com/bumptech/glide/load/Option.html

**Comment by KarishmaAgrawal** [comment]
Hi, Thanks For your response 
But still I am not able to change color.

> # 
Here's my SvgDecoder class:

 
public class SvgDecoder implements ResourceDecoder<InputStream, SVG> {
    public static final Integer DEFAULT_COLOR = -1;

    public static final Option<Integer> FIND_COLOR = Option.disk(
            "com.decurtis.common.imageloader.glide.svg.SvgDecoder.FindColor", DEFAULT_COLOR,
            new Option.CacheKeyUpdater<Integer>() {
                private final ByteBuffer buffer = ByteBuffer.allocate(Long.SIZE / Byte.SIZE);

                @Override
                public void update(byte[] keyBytes, Integer value, MessageDigest messageDigest) {
                    messageDigest.update(keyBytes);
                    synchronized (buffer) {
                        buffer.position(0);
                        messageDigest.update(buffer.putInt(value).array());
                    }
                }


            }
    );

    public static final Option<Integer> REPLACE_COLOR = Option.disk(
            "com.decurtis.common.imageloader.glide.svg.SvgDecoder.FindColor", DEFAULT_COLOR,
            new Option.CacheKeyUpdater<Integer>() {
                private final ByteBuffer buffer = ByteBuffer.allocate(Long.SIZE / Byte.SIZE);
                @Override
                public void update(byte[] keyBytes, Integer value, MessageDigest messageDigest) {

                    messageDigest.update(keyBytes);
                    synchronized (buffer) {
                        buffer.position(0);
                        messageDigest.update(buffer.putInt(value).array());
                    }
                }
            }
    );


    @Override
    public boolean handles(InputStream source, Options options) throws IOException {
        // TODO: Can we tell?
        return true;
    }

    public Resource<SVG> decode(InputStream source, int width, int height, Options options)
            throws IOException {
        try {
            SVGBuilder svgBuilder = new SVGBuilder();
            svgBuilder.readFromInputStream(source);
            svgBuilder.setWhiteMode(false);
            svgBuilder.setColorSwap(FIND_COLOR,REPLACE_COLOR);
            SVG svg = svgBuilder.build();
            return new SimpleResource<>(svg);
        } catch (SVGParseException ex) {
            throw new IOException("Cannot load SVG from stream", ex);
        }
    }
}


#Code for LiadSvgImage

    @Override
    public void loadSvgImage(final Context context, final String uri, final ImageView imageView, int placeHolderDrawable, Integer findColor, Integer replaceColor) {
        RequestOptions options = new RequestOptions()
                .set(SvgDecoder.FIND_COLOR, findColor).set(SvgDecoder.REPLACE_COLOR, replaceColor);

        RequestBuilder<PictureDrawable> requestBuilder = GlideApp.with(context)
                .as(PictureDrawable.class)
                .placeholder(placeHolderDrawable)
                .apply(options)
                .dontAnimate()
                .listener(new SvgSoftwareLayerSetter());

        String credential = okhttp3.Credentials.basic(BuildConfig.ZIP_USERNAME, BuildConfig.ZIP_PASSWORD);
        GlideUrl urlGlide = new GlideUrl(uri, new LazyHeaders.Builder()
                .addHeader("Authorization", credential)
                .build());
        requestBuilder.load(urlGlide).into(imageView);
    }

but this  one is not working.

**Comment by KarishmaAgrawal** [comment]
Thanks alot , this is working..

**Comment by nikhilvachhani** [comment]
@KarishmaAgrawal Please share code. I am not able to change SVG color.

**Comment by KarishmaAgrawal** [comment]
> #SvgDecoder class

public class SvgDecoder implements ResourceDecoder<InputStream, SVG> {
    public static final Integer DEFAULT_COLOR = -1;

    public static final Option<Integer> FIND_COLOR = Option.disk(
            "com.decurtis.common.imageloader.glide.svg.SvgDecoder.FindColor", DEFAULT_COLOR,
            new Option.CacheKeyUpdater<Integer>() {
                private final ByteBuffer buffer = ByteBuffer.allocate(Long.SIZE / Byte.SIZE);

                @Override
                public void update(byte[] keyBytes, Integer value, MessageDigest messageDigest) {
                    messageDigest.update(keyBytes);
                    synchronized (buffer) {
                        buffer.position(0);
                        messageDigest.update(buffer.putInt(value).array());
                    }
                }


            }
    );

    public static final Option<Integer> REPLACE_COLOR = Option.disk(
            "com.decurtis.common.imageloader.glide.svg.SvgDecoder.ReplaceColor", DEFAULT_COLOR,
            new Option.CacheKeyUpdater<Integer>() {
                private final ByteBuffer buffer = ByteBuffer.allocate(Long.SIZE / Byte.SIZE);

                @Override
                public void update(byte[] keyBytes, Integer value, MessageDigest messageDigest) {
                    Log.e("value", value.toString());
                    messageDigest.update(keyBytes);
                    synchronized (buffer) {
                        buffer.position(0);
                        messageDigest.update(buffer.putInt(value).array());
                    }
                }
            }
    );


    @Override
    public boolean handles(InputStream source, Options options) throws IOException {
        // TODO: Can we tell?
        return true;
    }

    public Resource<SVG> decode(InputStream source, int width, int height, Options options)
            throws IOException {
        try {

            SVGBuilder svgBuilder = new SVGBuilder();
            svgBuilder.readFromInputStream(source);
            svgBuilder.setWhiteMode(false);
            Log.e("findColor", FIND_COLOR.toString());
            svgBuilder.setColorSwap(options.get(FIND_COLOR).intValue(), options.get(REPLACE_COLOR).intValue());
            PorterDuffColorFilter colorFilter = new PorterDuffColorFilter(options.get(REPLACE_COLOR).intValue(), PorterDuff.Mode.CLEAR);
            svgBuilder.setStrokeColorFilter(colorFilter);
            SVG svg = svgBuilder.build();
            return new SimpleResource<>(svg);
        } catch (SVGParseException ex) {
            throw new IOException("Cannot load SVG from stream", ex);
        }
    }
}


#ImageLoader class

 @Override
    public void loadSvgImage(final Context context, final String uri, final ImageView imageView, int placeHolderDrawable, int findColor, int replaceColor) {
        RequestOptions options = new RequestOptions()
                .set(SvgDecoder.FIND_COLOR, findColor).set(SvgDecoder.REPLACE_COLOR, replaceColor);

        RequestBuilder<PictureDrawable> requestBuilder = GlideApp.with(context)
                .as(PictureDrawable.class)
                .placeholder(placeHolderDrawable)
                .apply(options)
                .dontAnimate()
                .listener(new SvgSoftwareLayerSetter());

        String credential = okhttp3.Credentials.basic(BuildConfig.ZIP_USERNAME, BuildConfig.ZIP_PASSWORD);
        GlideUrl urlGlide = new GlideUrl(uri, new LazyHeaders.Builder()
                .addHeader("Authorization", credential)
                .build());
        requestBuilder.load(urlGlide).into(imageView);
    }


> #method call

ImageLoader.getInstance().loadSvgImage(
                    context,
                    categotyIconUrl3,
                    itemIcon,
                    R.drawable.nearby_placeholder,
                    Color.parseColor("#000000"),
                    Color.parseColor("#4C4C4C"));

@nikhilvachhani This is working
