### ISSUE TITLE
The 4.4.0 version is conflict with appcompat-v7:26.1.0

### ISSUE THREAD

**Issue by rivendell1984** [bumptech/glide#2730]
**Glide Version**:4.4.0

**Integration libraries**:No

**Device/Android Version**: Google Pixel

**Issue details / Repro steps / Use case background**: 
The activity has a textview & imageview & imageview is using glide to load image, when the activity launches, it'll crash.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:GlideModule
```java
GlideApp.with(imageView.getContext())
                .load(url)
                .placeholder(placeholder)
                .error(error)
                .into(imageView);
```

**Stack trace / LogCat**:
```ruby
java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' 
at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
```

**Comment by sjudd** [comment]
You can either update the version of the support library you're using (let me know if there's a reason why you can't/don't want to) or you can exclude the transitive support library dependency from Glide using Gradle, see https://discuss.gradle.org/t/how-do-i-exclude-specific-transitive-dependencies-of-something-i-depend-on/17991

**Comment by mvl-lehoai** [comment]
Same problem

**Comment by rivendell1984** [comment]
Thanks for reply. I haven't updated the support library because there is conflict between databinding & appcompat-v7:27.0.2, so I downgrade to appcompat-v7:26.1.0, and find this issue.

**Comment by rivendell1984** [comment]
Here is my comment for the solution:
1. Just use appcompat-v7:27.0.2 & glide:4.4.0
2. use databinding & appcompat-v7:26.1.0 & glide:4.3.1
3. use databinding & appcompat-v7:27.0.2 & glide:4.4.0, we need set databinding's version to 1.3.3 like below, and it'll work well:
```gradle
 android {
     ...
     dataBinding {
         enabled = true
     }
 }

 dependencies {
    ...
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.github.bumptech.glide:glide:4.4.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'
    implementation 'com.android.databinding:adapters:1.3.3'
    implementation 'com.android.databinding:library:1.3.3'
    ...
}
```

**Comment by HubKing** [comment]
The same problem happened. The reason I use SDK 26, not 27, is that SDK 27 does not have source code and some emulator images yet. Just adding this library to the build.gradle caused weird issues, and then I found out that error message.  27.0.2 and 26.1.0 cannot be used together or something. I chose the simplest solution above: using glide 4.3.1. But I hope this would be fixed soon.

**Comment by sjudd** [comment]
What about just:

```groovy
dependencies {
  implementation ("com.github.bumptech.glide:glide:4.4.0") {
    exclude group: "com.android.support"
  }
  ...
}
```

**Comment by rivendell1984** [comment]
Excluding the support library works for me, but I think it'll be better if it's transparent to library user. Please review my pull request.Thank you.

**Comment by xbao** [comment]
Can confirm excluding the transitive dependency works:

```
dependencies {
    def supportLibVersion = "26.1.0"
    implementation "com.android.support:appcompat-v7:$supportLibVersion"
    ...

    implementation('com.github.bumptech.glide:glide:4.4.0') {
        exclude group: "com.android.support"
    }
    annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'
}
```

I don't want to upgrade at the moment because the sources aren't available. I could copy the -26 sources over in the SDK, but I don't want to force every developer who opens the project to do the same.

**Comment by sjudd** [comment]
Does anyone have any objection to updating to API 27 now that the sources are released?

**Comment by rivendell1984** [comment]
Thanks for this news, I have updated to API 27, how about close this issue?

**Comment by xbao** [comment]
Nice, no objections here 👍

**Comment by sjudd** [comment]
b/71699561 is an internal bug tracking improving the error messages when support library versions conflict, no promises on any changes though.

**Comment by susemi99** [comment]
This work for me

`compileSdkVersion 27`
`targetSdkVersion 26`

```
implementation 'com.github.bumptech.glide:glide:4.5.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.5.0'
```

**Comment by JSpiner** [comment]
same at `4.4.0` `4.5.0`

**Comment by mikemike396** [comment]
Same issue resolving back to 4.3.1 works fine. I hope this gets fixed.

**Comment by Gymkhana-Studio** [comment]
<uses-sdk
        android:minSdkVersion="19"
        android:targetSdkVersion="21" />
