### ISSUE TITLE
Image that will crash Glide 4.4 in emulator - give error on device - works on 4.2

### ISSUE THREAD

**Issue by MKevin3** [bumptech/glide#2733]
If I use this image 
` https://d18o6ewmssubp8.cloudfront.net/images/55018f67-e844-4ebf-bb0b-51552a11465c.jpg`
From Glide 4.4 it will crash the emulator and give the following output on a device

Same image works fine on 4.2 version of Glide. Just for the heck of it I tried it on Picasso with similar issues. Unsure why older versions of Glide can handle this image. The actual size of the image is 200x200 not the 2147483647x2147483647 being reported by the logging.

`12-18 11:05:11.821 13177-13177/{my app} W/Glide: Load failed for https://d18o6ewmssubp8.cloudfront.net/images/55018f67-e844-4ebf-bb0b-51552a11465c.jpg with size [2147483647x2147483647]
                                                                class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                  Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, DATA_DISK_CACHE, https://d18o6ewmssubp8.cloudfront.net/images/55018f67-e844-4ebf-bb0b-51552a11465c.jpg
                                                                    Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                                    Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                                      Cause (1 of 1): class java.lang.IllegalArgumentException: unknown bitmap configuration
                                                                    Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                                      Cause (1 of 1): class java.lang.IllegalArgumentException: unknown bitmap configuration
                                                                  Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, DATA_DISK_CACHE, https://d18o6ewmssubp8.cloudfront.net/images/55018f67-e844-4ebf-bb0b-51552a11465c.jpg
                                                                    Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                                    Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                                      Cause (1 of 1): class java.lang.IllegalArgumentException: unknown bitmap configuration
                                                                    Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                                      Cause (1 of 1): class java.lang.IllegalArgumentException: unknown bitmap configuration
                                                                  Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, DATA_DISK_CACHE, https://d18o6ewmssubp8.cloudfront.net/images/55018f67-e844-4ebf-bb0b-51552a11465c.jpg
                                                                    Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                                    Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
                                                                      Cause (1 of 1): class java.io.IOException: java.lang.IllegalArgumentException
                                                                  Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, https://d18o6ewmssubp8.cloudfront.net/images/55018f67-e844-4ebf-bb0b-51552a11465c.jpg
                                                                    Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                                    Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                                      Cause (1 of 1): class java.lang.IllegalArgumentException: unknown bitmap configuration
                                                                    Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                                      Cause (1 of 1): class java.lang.IllegalArgumentException: unknown bitmap configuration
                                                                  Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, https://d18o6ewmssubp8.cloudfront.net/images/55018f67-e844-4ebf-bb0b-51552a11465c.jpg
                                                                    Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                                    Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                                      Cause (1 of 1): class java.lang.IllegalArgumentException: unknown bitmap configuration
                                                                    Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                                      Cause (1 of 1): class java.lang.IllegalArgumentException: unknown bitmap configuration
                                                                  Cause (6 of 6): class com.bumptech.glide.load.engine.GlideExceptio
`

**Comment by sjudd** [comment]
Can you attach the actual image? Just to be sure we're using the same data?

**Comment by MKevin3** [comment]
![bad bitmap](https://user-images.githubusercontent.com/2380650/34129902-85d0095e-e40b-11e7-902f-8b3605883715.jpg)

This should be the image. I don't know if the browser "fixes it" before it loads it then saves it to disk so make sure you use the URL for all testing as this image may load just fine otherwise.

**Comment by sjudd** [comment]
Also what's the load line that you're using?

**Comment by MKevin3** [comment]
`                val requestOptions = RequestOptions().override(image.maxWidth, image.maxHeight).placeholder(R.drawable.dress_inventory)

                Glide.with(context)
                        .load(detail.Images[0].ThumbUrl)
                        .apply(requestOptions)
                        .into(object : ViewTarget<View, Drawable>(image) {
                            override fun onResourceReady(resource: Drawable, glideAnimation: Transition<in Drawable>?) =
                                    image.setImageDrawable(resource.current)

                            override fun onLoadFailed(errorDrawable: Drawable?) = Unit
                        })
`

The image has a height and width of 50dp defined in the XML

**Comment by sjudd** [comment]
I've added a passing test case that demonstrates that Glide is able to successfully load the given image on 4.4.0+ on an x86 emulator running Android 8.0.

Can you modify the test so that it fails? Or provide the sdk and cpu type of an emulator that it will fail on?

**Comment by MKevin3** [comment]
[GlideTest.zip](https://github.com/bumptech/glide/files/1575732/GlideTest.zip)

Here is a full Kotlin program that shows the issue. Currently set to Glide 4.4.0 and it will crash on the emulator or a device. Set to Glide 4.2.0 and it will work. Just shows the image centered on the screen.

**Comment by sjudd** [comment]
This is probably an OOM issue. ``maxWidth`` and ``maxHeight`` aren't defined for the imageView you're using and they're defaulting to ``Int.MAX_VALUE`` for some reason, so you're passing Glide an override size that will produce a ``Bitmap`` with 4 billion pixels.

**Comment by MKevin3** [comment]
But it is not a huge image as you can see, it is a tiny image. It is attached above and you can easily download it from the URL plus 4.2.0 handles it with no issue. Something must have changed in Glide in the 4.4.0 release to look at different values for the image height and width. Maybe it sets default width and height to max values and then does not look at all the metadata of the image that is used to look at to determine actual size?

**Comment by sjudd** [comment]
The size of the image is irrelevant. You're setting the RequestOptions override width and height to ``imageView.maxWidth`` and ``imageView.maxHeight``. Neither of those values are defined in xml. They appear to be defaulting to ``Integer.MAX_VALUE``. As a result, you're asking Glide to scale the image up to ``Integer.MAX_VALUE`` in both dimensions, which results in the behavior you're seeing.

Regardless of any change in any version of Glide, what you're asking for doesn't make sense. If you want the image to be roughly the size of you view, don't specify an override value. If you do want to specify some override value, pick one that's defined?

**Comment by MKevin3** [comment]
I see what you are saying now. There is a code bug in the example that is setting the size incorrect due to values of height / width not yet being available from the ImageView. Don't know how / why this used to work. I will make adjustments to my code to avoid this situation. Very odd that 4.2.0 handled it differently than 4.4.0.
