### ISSUE TITLE
Failed to load google search images

### ISSUE THREAD

**Issue by varun7952** [bumptech/glide#2737]
i am trying to load google images in Glide but its showing 
`On Load Failed com.bumptech.glide.load.engine.GlideException: Failed to load resource`
`On Load Failed object  https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS19wGi_tRnxGxUDVhn9lSPPvzCALGCUiCOvYi4tvUeiu5ZrXJajEijz89k`

Loading images like this.
Glide.with(context).load(googleSearchIMG).into(holder.Google_Image);

I tried to load above image in browser it load correctly but not with Glide.

```

This is interface where i am getting result back with list of string here 

```
 sendResult GoogleSearchResult=new sendResult() {
                @Override
                public void TransferResultTo_Activity(List<String> list) {
                    Log.d(TAG,"Google Image Which is not Loading after adding into database "+list.get(4));
                    chat_wrapper.setGoogleSearch(list);
                    holder.Search_title.setText(list.get(0));
                    holder.Search_link.setText(list.get(3));
                    holder.Search_snippet.setText(list.get(4));
                    Glide.with(context).load(list.get(1)).apply(new RequestOptions()
                            .diskCacheStrategy(DiskCacheStrategy.ALL)
                            .fitCenter())
                            .into(holder.Google_Image);

                }
            };
```
Then after adding list of string into local database (sqlite) it never shows image this time. I checked image path is correct(same as interface one),which i am getting from local database as i mentioned above.


```
String googleSearchIMG=splitArray[1];
                Log.d(TAG,"Google Image Which is not Loading after adding into database "+googleSearchIMG);

                Glide.with(context).load(googleSearchIMG).apply(new RequestOptions()
                        .diskCacheStrategy(DiskCacheStrategy.ALL)
                        .fitCenter()).into(holder.Google_Image);
```




Glide Version: 4.3.1
Device/Android Version: Nexus 5/ M

**Comment by sjudd** [comment]
Please fill out [the issue template][1] when filing new issues.

I've uploaded a test case that demonstrates Glide is able to load this image in v4.

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md
