### ISSUE TITLE
API 16, 17, 18 emulators are failing on travis.

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#2738]
Log attached: [failing_emulator.txt](https://github.com/bumptech/glide/files/1573838/failing_emulator.txt)

I've filed an issue on travis' GitHub after finding that a previously successful commit failed when I retried it: https://github.com/travis-ci/travis-ci/issues/8946. 

It seems like something's changed in the last day or so that started making these emulator tests fail.

Since I haven't found a way to fix this so far, I'll disable these tests for the time being.

**Comment by sjudd** [comment]
Emulators will start if I remove ``--device "Nexus 5X"``, but that causes OOMs in some of the tests, probably because the default memory size is lower than the size used for the Nexus 5X profile.

Internal bug for the change in behavior for ``"Nexus 5X"`` is b/70957539.

**Comment by sjudd** [comment]
I think --device "Nexus 4" will work. 

As an alternative, emulator configs appear to be stored in ``~/.android/avd/<avd_name>`` and the hardware config is specifically in `` ~/.android/avd/test.avd/config.ini``. If memory is an issue, I may be able to to just append hw.ramSize=1536 to that file after creating the device but before starting it.

There are a couple of other memory related settings in the config for Nexus 5X that I can see in Android Studio that I could also try.

**Comment by rivendell1984** [comment]
This issue's reason is starting emulator with -no-window option doesn't work with android-16,17,18.

## How to reproduce:

1. Upgrade the android sdk in PC/MAC(like travis_create_emulator.sh did)
Take android-16 for example, this will upgrade to emulator:27.0.2, armeabi-v7a:v4.

2. Start emulator with -no-window option(also like travis_create_emulator.sh did)

3. Run command "adb -e shell getprop init.svc.bootanim"(like android-wait-for-emulator did)
There is no return value, and this is the direct reason to make starting emulator timeout.

And after testing, if with -no-window option, android-19 will return correct value(running/stop); and if without this option, android-16 will return correct value;
     
## Solution
1. Don't upgrade android sdk for android-16,17,18 
The default Travis CI android image uses android sdk 25.2.5 now, and the emulator will start correctly, I guess there is no issue in the old emulator($ANDROID_HOME/tools/emulator) 
But I think this is not a long term solution, if Travis CI upgrade their image, it'll reproduce again.

2. For android-16,17,18, start emulator without  -no-window option, and it needs [xvfb](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI)
