### ISSUE TITLE
centerCrop doesn't work on Glide 4.4.0

### ISSUE THREAD

**Issue by vietnguyen312** [bumptech/glide#2741]
I use glide 4.4.0 and centerCrop doesn't work, I also tested with Glide 3.8.0 and It worked perfectly
here is my ImageView xml and Glide code

```
<ImageView
        android:layout_width="wrap_content"
        android:layout_height="172dp"
        android:background="@color/colorAccent"
	app:layout_constraintEnd_toEndOf="parent"
	app:layout_constraintStart_toStartOf="parent"
	app:layout_constraintTop_toTopOf="parent"
	android:adjustViewBounds="true"/>
```

```
Glide.with(context)
       .load(vehicle.getImageLink())
       .apply(RequestOptions.centerCropTransform())
       .into(image);
```

**Comment by sjudd** [comment]
There are a bunch of test images here that are used as regression tests to ensure that Glide's transformations work. See all images that include centercrop in the name here: https://github.com/bumptech/glide/tree/master/instrumentation/src/main/res/raw.

The regression tests are here: https://github.com/bumptech/glide/blob/a6f1b1c1bef5b4e8be736c564792715266b07463/instrumentation/src/androidTest/java/com/bumptech/glide/CenterCropRegressionTest.java#L27. 

It's unlikely that CenterCrop in general isn't working. 

Can you attach a [failing test][1] that demonstrates the issue? And explain more about what you mean by "doesn't work"? 

[1]: http://bumptech.github.io/glide/tut/failing-test-cases.html

**Comment by yfaming** [comment]
I have just encountered this problem.

Tried to change `ImageView`'s attribute `android:layout_width="wrap_content"` to `android:layout_width="match_parent"`, and everything was fine.

Search logs with keyword `glide`, you will find something like this:
> Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
