### ISSUE TITLE
Right way to clear the bitmap resource after loading the texture of the bitmap in OpenGL ES 2.0

### ISSUE THREAD

**Issue by leapfrog-santosh** [bumptech/glide#2752]
**Glide Version**: 4.1.0

**Integration libraries**: OpenGL ES 2.0

**Issue Type**: Question 

**Question details**: 
  - Loaded bitmap with `FutureTarget<Bitmap>` on background thread
  - Gave the loaded bitmap to `OpenGL ES2.0` for texture
  - After successfully getting texture ID from `OpenGL ES2.0`, is it safe to recycle the bitmap using `bitmap.recycle()` or using `requestManager.clear(futureTarget)`?
  - While doing `bitmap.recycle()`, the app crashes ( `Fatal Exception: java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap` ) when app is  exited as I believe `Glide` works on clearing the resources
  - Right now using `requestManager.clear(futureTarget)` to avoid the crash. So my question is that, is it the right away for clear the bitmap resources in my case.

Thank you for the awesome library and making our life easier and happy.

**Comment by sjudd** [comment]
Definitely don't use ``recycle()``, clearing the Target is always preferable. Technically ``recycle()`` is safe as long as you don't then clear the ``Target``, but again clearing is better.

I'm not actually sure about your OpenGL question, but I'd suspect obtaining the texture ID doesn't remove the need to retain the ``Bitmap`` data, so clearing the ``Target`` is probably broken until you're done with the texture.

**Comment by leapfrog-santosh** [comment]
@sjudd  Thank you for the answer. Regarding OpenGL, once I obtain the texture ID from OpenGL, there is no need to keep bitmap in the memory. So, the option I have right now is to `bitmap.recycle()` or `Target clear`. 
As per your suggestion, I will go with `Target clear` as if I do `bitmap.recycle()`, the app crashes on exit.
Thank you once again for the help and the awesome library.
