### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap

### ISSUE THREAD

**Issue by VolodymyrMachekhin** [bumptech/glide#2766]
Hello! We suffered from the issue after upgrade from v 4.3.1 to 4.4.0
**Stack trace / LogCat**: 
 `Fatal Exception: java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@b8f2509[512x512] ARGB_8888 at com.bumptech.glide.util.Util.getBitmapByteSize(Util.java:74) at com.bumptech.glide.load.resource.bitmap.BitmapResource.getSize(BitmapResource.java:52) at com.bumptech.glide.load.engine.EngineResource.getSize(EngineResource.java:57) at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:39) at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:13) at com.bumptech.glide.util.LruCache.trimToSize(LruCache.java:179) at com.bumptech.glide.util.LruCache.evict(LruCache.java:187) at com.bumptech.glide.util.LruCache.put(LruCache.java:140) at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:13) at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:327) at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:109) at com.bumptech.glide.load.engine.Engine.release(Engine.java:287) at com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:343) at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:322) at com.bumptech.glide.request.ThumbnailRequestCoordinator.clear(ThumbnailRequestCoordinator.java:133) at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:72) at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:59) at com.bumptech.glide.RequestManager.untrack(RequestManager.java:579) at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:547) at com.bumptech.glide.RequestManager.clear(RequestManager.java:535) at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:588) at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:640)`

**Devices, OS versions** :
![image](https://user-images.githubusercontent.com/22050682/34404684-bbb00840-ebb7-11e7-99c9-c28f88a42964.png)

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors.

Also avoid recycling Bitmaps obtained from Glide.

**Comment by VolodymyrMachekhin** [comment]
the thing is that I am not recycling bitmaps obtained from glide. And this issue appeared only in v 4.4.0

**Comment by sjudd** [comment]
Maybe the same is #2693? If so, it might be fixed in 4.5.0?

It's hard to tell with these, this could also be an application issue.

**Comment by Archer1347** [comment]
I also run the same error. Were you fixed it?

**Comment by Sunaina015** [comment]
I am also getting this issue, how can i fixed it ?

**Comment by zhangshaobo87** [comment]
I am also getting this issue, how can i fixed it ?

**Comment by dengluoy** [comment]
I am also getting this issue, how can i fixed it

**Comment by Sunaina015** [comment]
This problem occur on latest version Picasso, this bug is released by the google in the latest picasso version.I suggest u please use the old verison.
