### ISSUE TITLE
OOM on simple loading of bitmap?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bumptech/glide#2768]
I have this simple call on my tiny live wallpaper app ([here](https://play.google.com/store/apps/details?id=com.lb.lwp_plus))  :

            val holder = surfaceHolder
            canvas = holder.lockCanvas()
            val width = canvas!!.width
            val height = canvas.height
            ...
                    Glide.with(this@LiveWallpaperService).asBitmap().load(Utils.getSavedImageFileForWallpaperBackground(this@LiveWallpaperService))
                            //.diskCacheStrategy(DiskCacheStrategy.NONE)
                            //.skipMemoryCache(true)
                            .apply(RequestOptions.centerCropTransform().skipMemoryCache(true).diskCacheStrategy(DiskCacheStrategy.NONE))
                            .into<SimpleTarget<Bitmap>>(object : SimpleTarget<Bitmap>(width, height) {
                                override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>) {
                                    _bitmap = resource
                                    draw()
                                }

                            })

Am I doing something wrong?
I don't even store the bitmap in Glide's mem cache...
What I tried is to load it to a center-crop size of the current screen size. 

And I got this crash on Nexus 5X with Android 8.1 . Same as my own device...

This is the crash log as reported on the Play Console:

  at com.bumptech.glide.load.engine.executor.GlideExecutor.execute (GlideExecutor.java:268)
  at com.bumptech.glide.load.engine.EngineJob.start (EngineJob.java:119)
  at com.bumptech.glide.load.engine.Engine.load (Engine.java:230)
  at com.bumptech.glide.request.SingleRequest.onSizeReady (SingleRequest.java:449)
  at com.bumptech.glide.request.target.SimpleTarget.getSize (SimpleTarget.java:69)
  at com.bumptech.glide.request.SingleRequest.begin (SingleRequest.java:262)
  at com.bumptech.glide.manager.RequestTracker.runRequest (RequestTracker.java:41)
  at com.bumptech.glide.RequestManager.track (RequestManager.java:590)
  at com.bumptech.glide.RequestBuilder.into (RequestBuilder.java:590)
  at com.bumptech.glide.RequestBuilder.into (RequestBuilder.java:556)
  at com.bumptech.glide.RequestBuilder.into (RequestBuilder.java:550)

**Comment by AndroidDeveloperLB** [comment]
The loaded bitmap is from a user's choice ( from storage, usually) .

**Comment by sjudd** [comment]
You're missing the exception message in the log above which is the most important part...

If it's an OOM, then see: http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors

**Comment by AndroidDeveloperLB** [comment]
I've read the link. Don't see it is related to my case. I use a single bitmap loading with Glide. Always. It's a very simple app. It just takes the image the user has chosen before, and shows it into the live wallpaper.
I've tested it to load even 4k images. Doesn't seem to have any issue.

I've added (java heap) mem checks via logs in special places in the app: before loading ads, after loading ads, before loading image via Glide, after, ... All show the app uses less than 13MB . 

I've decided to take it even further. Took a huge image ([here](https://www.google.co.il/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwi63ZKl1q7YAhVBchQKHT0-DuoQjBwIBA&url=http%3A%2F%2Fwww.mapsland.com%2Fmaps%2Fworld%2Flarge-scale-detailed-satellite-map-of-the-world.jpg&psig=AOvVaw0cGpYy6lwLUW6_u4LbsbAX&ust=1514618109445891)) , of a 24,000x12,000 pixels resolution. 

Still same memory stats. I also tried choosing one huge image after another (maybe memory leak...) , but I don't see memory usage grows...

The weird thing, is that when I've opened the profiler, I got a graph that shows a huge memory usage, but it's mostly native, and a lot is used before anything is done (even before ads being loaded) :

![image](https://user-images.githubusercontent.com/5357526/34431839-150a9356-ec7b-11e7-9c15-70453b770527.png)

Do you know of this behavior?


About the log, here's the full log. Didn't think you need it all :

java.lang.OutOfMemoryError: 
  at java.lang.Thread.nativeCreate (Native Method)
  at java.lang.Thread.start (Thread.java:733)
  at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:970)
  at java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1377)
  at com.bumptech.glide.load.engine.executor.GlideExecutor.execute (GlideExecutor.java:268)
  at com.bumptech.glide.load.engine.EngineJob.start (EngineJob.java:119)
  at com.bumptech.glide.load.engine.Engine.load (Engine.java:230)
  at com.bumptech.glide.request.SingleRequest.onSizeReady (SingleRequest.java:449)
  at com.bumptech.glide.request.target.SimpleTarget.getSize (SimpleTarget.java:69)
  at com.bumptech.glide.request.SingleRequest.begin (SingleRequest.java:262)
  at com.bumptech.glide.manager.RequestTracker.runRequest (RequestTracker.java:41)
  at com.bumptech.glide.RequestManager.track (RequestManager.java:590)
  at com.bumptech.glide.RequestBuilder.into (RequestBuilder.java:590)
  at com.bumptech.glide.RequestBuilder.into (RequestBuilder.java:556)
  at com.bumptech.glide.RequestBuilder.into (RequestBuilder.java:550)
  at com.lb.lwp_plus.LiveWallpaperService$MyWallpaperEngine.draw$app_debug (LiveWallpaperService.kt:196)
  at com.lb.lwp_plus.LiveWallpaperService$MyWallpaperEngine.onOffsetsChanged (LiveWallpaperService.kt:150)
  at android.service.wallpaper.WallpaperService$Engine.doOffsetsChanged (WallpaperService.java:1059)
  at android.service.wallpaper.WallpaperService$Engine.reportVisibility (WallpaperService.java:1019)
  at android.service.wallpaper.WallpaperService$Engine.doVisibilityChanged (WallpaperService.java:1003)
  at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage (WallpaperService.java:1289)
  at com.android.internal.os.HandlerCaller$MyHandler.handleMessage (HandlerCaller.java:37)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6494)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

**Comment by sjudd** [comment]
On 8.1 Bitmaps are backed by native memory.

It looks like you're allocating an inappropriately large Bitmap. If not, or if you can't figure out where the allocation is coming from, you'll need a heap dump. Both of those are mentioned in the link I provided.

It sort of sounds like you have some code that works, and then you made some changes and it doesn't work? If that's the case and you can provide before and after it might be more obvious what's going wrong.

**Comment by AndroidDeveloperLB** [comment]
Oh I remember I read about this.
But how come it uses so much?
It's just a Settings Activity. The only thing that's done in the background is loading an Admob ad...

I've now tried to create a completely new app, choosing settings activity as the main one. 
The profiler shows this:

![image](https://user-images.githubusercontent.com/5357526/34447875-c499a102-ecf0-11e7-9d57-23dcca9104a5.png)

Decided to disable ads on my app, so it should be about the same as this new one, and got this:

![image](https://user-images.githubusercontent.com/5357526/34447945-94414680-ecf1-11e7-94db-3c20979967e3.png)

So.. very similar indeed.
Enabled ads again, and got this:

![image](https://user-images.githubusercontent.com/5357526/34448000-4976dede-ecf2-11e7-9469-8abe68344254.png)

so back to my app again, with Glide usage, to make sure when the spike occurs.

![image](https://user-images.githubusercontent.com/5357526/34448570-5a9730ce-ecf7-11e7-8a67-013352d87fc7.png)

I've marked the spot when I call the code of Glide, to load&show the bitmap.

**Comment by sjudd** [comment]
Take another read through http://bumptech.github.io/glide/doc/debugging.html#excessively-large-allocations, the width and height you're providing from the Canvas probably are not what you expect and are unnecessarily large.

**Comment by AndroidDeveloperLB** [comment]
The canvas is exactly the size of the screen, according to my tests: 1080x1920
https://www.gsmarena.com/lg_nexus_5x-7556.php
Is the code ok ?

**Comment by AndroidDeveloperLB** [comment]
Note the test was of a huge bitmap

**Comment by sjudd** [comment]
What's the input size of the Bitmap you're using?

**Comment by AndroidDeveloperLB** [comment]
This one was much smaller than the 24kx12k pixels. 
It's the other one, of the 4k resolution: 3840x2400 pixels.

I've tried now with the 24kx12k pixels, and got this:
![image](https://user-images.githubusercontent.com/5357526/34449581-527f7170-ed02-11e7-9de1-9189643a8789.png)

**Comment by sjudd** [comment]
If you're loading 3840 * 2400 into a 1080 * 1920 image, Glide is first going to:

1.  Allocate a 3840 * 2400 image (Android supports only power of 2 downsampling which would make your image smaller than the requested size)
2. Natively scale the image down to 3072 * 1920
3. Crop the image to apply the requested center crop

All told that's around 69mb. Technically the peak memory usage will be closer to 60mb because the initial image can be freed before the third one is allocated. 

The exact behavior is controlled by the [``DownsampleStrategy``][1], each of which make some trade off between quality and memory usage. [``AT_MOST``][2] for example would use the least amount of memory possible, but reduce the quality of the image by forcing upscaling depending on the difference between the input image and the view size.

[1]: http://bumptech.github.io/glide/javadocs/440/com/bumptech/glide/load/resource/bitmap/DownsampleStrategy.html
[2]: http://bumptech.github.io/glide/javadocs/440/com/bumptech/glide/load/resource/bitmap/DownsampleStrategy.html#AT_MOST

**Comment by AndroidDeveloperLB** [comment]
yes this makes sense, but is my code of using Glide seem ok to you?
It's weird I got OOM.
The app is very new, so I got only one report, but it's weird because the app barely uses anything... The only things it uses of memory related is Glide and Admob. The rest is just logic.

**Comment by AndroidDeveloperLB** [comment]
I just don't see anything suspicious here, and the images I tested are just for seeing the worst case.

**Comment by sjudd** [comment]
Nothing seems obviously wrong, referencing Canvas sizes is unusual and `SimpleTarget` is error prone, but neither of those seem relevant.

You're probably getting unlucky on some device(s) with some images where the width or the height of the image is roughly 2x - 1 the size of the Canvas, which can lead to some pretty large allocations (70mb as described above is a lot). 

If you have only one report, take a look at the device. If it's a low end or low ram device, you might consider using a more memory efficient `DownsampleStrategy` on those devices (or in general).

**Comment by AndroidDeveloperLB** [comment]
It's Nexus 5x, same as my device...
Shouldn't be a problem...
What would you choose instead of Canvas?
Also, seeing you know about Android 8.1, what's the best way now to check memory usage and print on logs? What I'm using for Heap memory is this:

```
    @JvmStatic
    val availableMemInBytes: Long
        get() {
            val runtime = Runtime.getRuntime()
            val usedMem = runtime.totalMemory() - runtime.freeMemory()
            val maxHeapSize = runtime.maxMemory()
            return maxHeapSize - usedMem
        }

    @JvmStatic
    fun getHeapMemStats(context: Context): String {
        val maxMemInBytes = Runtime.getRuntime().maxMemory()
        val availableMemInBytes = availableMemInBytes
        val usedMemInBytes = maxMemInBytes - availableMemInBytes
        val usedMemInPercentage = usedMemInBytes * 100 / maxMemInBytes
        return "used: " + Formatter.formatShortFileSize(context, usedMemInBytes) + " / " +
                Formatter.formatShortFileSize(context, maxMemInBytes) + " (" + usedMemInPercentage + "%)"
    }
```

**Comment by sjudd** [comment]
I'm not sure there's a great way to monitor native memory usage in an app, but for debugging you can use dumpsys meminfo: https://developer.android.com/studio/command-line/dumpsys.html#meminfo. It's not always trivial to understand what's changing and why from that data. The newer x86 8.0 or 8.1 emulators in Android Studio also show you additional information in the profiling tools which is probably even better.

Canvas may be correct, it's just unusual. I'd prefer either a fixed size or the view size by default, but if the Canvas size is providing the behavior you expect, I wouldn't bother changing it.

I think this is just an issue of the worst case image size. Because Glide, by default, tries to preserve quality, we downsample to between 1x and 2x the requested size in both dimensions. As a result you can basically end up with an unbounded memory allocation in the worst case. 

For example if you ask Glide to load a 2,147,483,647 x 1080 image into a 1920 x 1080 view, Glide, by default, is going to decode a 2,147,483,647 x 1080 image, which will attempt (and fail) to allocate 9+ TB of memory. 

If you use [`AT_MOST`][1] instead of Glide's default you'll get an image that's less or equal to 1920 x 1080 in both dimensions, which puts an upper bound on your memory usage (1920 * 1080 * 4), but will also significantly reduce the quality (the height will be something like 1080 * 1920/2,147,483,647).

[1]: http://bumptech.github.io/glide/javadocs/440/com/bumptech/glide/load/resource/bitmap/DownsampleStrategy.html#AT_MOST

**Comment by AndroidDeveloperLB** [comment]
Many times I prefer a simple log instead, which is a textual way to see in which situations I got a (estimated) certain state of memory usage, to see if that's the cause for it.

On the other tools, I can get confused when anything occurs, and pinpoint the place something special occurs.

**Comment by AndroidDeveloperLB** [comment]
Anyway, I'm closing this issue, because I don't know what is the cause for it. Just know that it occurred when Glide tried to load the image. Could very well be a bug, that I might even have fixed by now.
