### ISSUE TITLE
Error:Module 'com.github.bumptech.glide:glide:4.4.0' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by ncworm** [bumptech/glide#2769]
Error:Module 'com.github.bumptech.glide:glide:4.4.0' depends on one or more Android Libraries but is a jar

**Comment by ncworm** [comment]
compile 'com.github.bumptech.glide:glide:4.4.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'

    repositories {
        jcenter()
        maven {
            url "http://repo.baichuan-android.taobao.com/content/groups/BaichuanRepositories/"
        }
        maven { url "https://jitpack.io" }
        mavenCentral()
        maven { url "https://maven.google.com"}
//        maven { url "https://dl.google.com/dl/android/maven2/"}
    }
}

**Comment by sjudd** [comment]
Duplicate of #2318
