### ISSUE TITLE
How to close url connection while downloading image ?

### ISSUE THREAD

**Issue by pahmcoung** [bumptech/glide#277]
I want to close url connection while downloading images. Please help me. Thank you

**Comment by neonwarge04** [comment]
Is this fixed already? I have the same problem as well. I load an image via:

                Glide.with(PreviousRaffleActivity.this)
                    .load(Constants.BASE_URL + "/" + raffle.getImageSrc())
                    .into(mImageViewPreviousRaffle);

When I close the activity, the context I passed onto it is already null or maybe mImageViewPreviousRaffle is null. This crashes my app. How can get around this? You load it asynchronously, where is your callback that this is ready? What do I call to stop it from loading that specific URL?

Please help.
