### ISSUE TITLE
Using Glide with url loaded from background process

### ISSUE THREAD

**Issue by AllanWang** [bumptech/glide#2770]
`Glide: 4.4.0`

I have the following use case:

Given a url, I will load it immediately. I will then run some (network) process to try and fetch a higher res image. If I manage to find one, I would like to load that image instead.

All this occurs in a RecyclerView, so if a ViewHolder is replaced or unbound, both loading attempts should cancel. I figured this may be problematic if I try to spin off a Glide request in a new thread myself, just in case I don't manage to cancel a request and it is then fulfilled when the ViewHolder is reused. 

I looked at a few other issues, namely #1209 and #634

Both seem to be exactly what I want, but I'm not sure if the interfaces have changed or not as some methods seem to be different.

I managed to write a DataFetcher from the examples:

```kotlin
class ImageFbidFetcher(private val fbid: Long,
                       private val cookie: String) : DataFetcher<InputStream> {

    @Volatile private var cancelled: Boolean = false
    private var urlCall: Call? = null
    private var inputStream: InputStream? = null

    private fun DataFetcher.DataCallback<in InputStream>.fail(msg: String) {
        onLoadFailed(RuntimeException(msg))
    }

    override fun getDataClass(): Class<InputStream> = InputStream::class.java

    override fun getDataSource(): DataSource = DataSource.REMOTE

    override fun loadData(priority: Priority, callback: DataFetcher.DataCallback<in InputStream>) {
        cookie.fbRequest(fail = { callback.fail("Invalid auth") }) {
            if (cancelled) return@fbRequest callback.fail("Cancelled")
            val url = getFullSizedImage(fbid).invoke() ?: return@fbRequest callback.fail("Null url")
            if (cancelled) return@fbRequest callback.fail("Cancelled")
            urlCall = Request.Builder().url(url).get().call()

            inputStream = try {
                urlCall?.execute()?.body()?.byteStream()
            } catch (e: IOException) {
                null
            }

            callback.onDataReady(inputStream)
        }
    }

    override fun cleanup() {
        try {
            inputStream?.close()
        } catch (e: IOException) {
        } finally {
            inputStream = null
        }
    }

    override fun cancel() {
        cancelled = true
        urlCall?.cancel()
        urlCall = null
        cleanup()
    }
}
```

Which basically takes in an id and outputs an inputStream within `loadData`.

`ModelLoader` seems to differ a lot from the examples.

From 1209:
```java
public class MyImageUriLoader implements ModelLoader<MyImageGrabber, InputStream> {
    private final ModelLoader<Uri, InputStream> uriLoader;
    public MyImageUriLoader(ModelLoader<Uri, InputStream> uriLoader) {
        this.uriLoader = uriLoader;
    }
    @Override public DataFetcher<InputStream> getResourceFetcher(final MyImageGrabber model, int width, int height) {
        return new MyDataFetcher(uriLoader, model, width, height);
    }

    public static class Factory implements ModelLoaderFactory<MyImageGrabber, InputStream> {
        @Override public ModelLoader<MyImageGrabber, InputStream> build(Context context, GenericLoaderFactory factories) {
            ModelLoader<Uri, InputStream> uriLoader = factories.buildModelLoader(Uri.class, InputStream.class);
            return new MyImageUriLoader(uriLoader);
        }
    }
}
```

There doesn't seem to be a `getResourceFetcher` anymore, and it's also used in the other issues.
How exactly do I get to using the DataFetcher?

Lastly, if there's any easier way of doing this, I'd love to know. Realistically, all I need is some method to map a value to a url and to have it follow Glide's life cycle. A lot of what I've done can probably be abstracted.

**Comment by sjudd** [comment]
Those issues both have example code from v3. The v4 APIs have changed, although not a huge amount. There's an article on writing a custom`ModelLoader` here: http://bumptech.github.io/glide/tut/custom-modelloader.html. 

The examples section in the sidebar also will point you to a bunch of sample apps, most of which have their own `ModelLoaders` if you just want some concrete code samples.

If you don't already have the high resolution url when you make the first request a custom `ModelLoader` that tries to fetch it sounds reasonable. You can use the [`.thumbnail()`][1] API to start both requests simultaneously with the smaller image as the thumbnail request:

```java
Glide.with(fragment)
   .load(new FetchHighResolutionModel(someData))
   .thumbnail(
     Glide.with(fragment)
       .load(lowResolutionUrl))
  .into(imageView);
```

That won't remove the need for the `ModelLoader` to fetch the high resolution URL but it should make you requests behave the way you expect.

[1]: http://bumptech.github.io/glide/javadocs/440/com/bumptech/glide/RequestBuilder.html#thumbnail-com.bumptech.glide.RequestBuilder-

**Comment by AllanWang** [comment]
I'll upload my sample code once I'm done.

How do we pass `width` and `height` if we aren't delegating the model loader?
As an example, here is the code for `OkHttpUrlLoader`

```java
  @Override
  public LoadData<InputStream> buildLoadData(GlideUrl model, int width, int height,
      Options options) {
    return new LoadData<>(model, new OkHttpStreamFetcher(client, model));
  }
```

Does it even matter at that point?

**Comment by sjudd** [comment]
The width and height only matters here if you can pick a different url based on the size. Some APIs support providing thumbnails of various sizes. If you can't pick a more efficient model, you can ignore the width and height.

**Comment by AllanWang** [comment]
Another issue I'm having:

The new potential hd image may or may not exist. I can quickly decide whether or not it certainly does not exist in some cases, and return false under `handles`, but does that mean it will continue to propagate to other potential handlers? If I know it won't exist, I'd simply like Glide to load the "thumbnail" version and keep it that way.

Another option I can do is to immediately execute a null callback from the data fetcher if I know the image will not exist. Is that the better solution and will that trigger an error callback from the request manager?

**Comment by sjudd** [comment]
In all cases if your ModelLoader fails and other ModelLoaders are registered for the same Model, those other ModelLoaders will be attempted. You can't abort the chain in a single ModelLoader.

You can however make sure to register your ModelLoader for a custom Model type. Then there will be only one and if it fails there won't be anything else for Glide to try.

If you can do so quickly, returning false() from handles is best.
