### ISSUE TITLE
Preload with size 1x1, somehow still prevents future network calls.

### ISSUE THREAD

**Issue by AlanCPSC** [bumptech/glide#2773]
Hello, I currently have an activity that has 1 `ImageView` and 1 `Button`. I also have an `ArrayList` filled with `Uri` of different pictures of plants.

When the `Button` is pressed, the first `Uri` from the `ArrayList` is popped and loaded into the `ImageView` with `Glide.with(activity).load(uri).into(imageView)`

However, because I want to load all images beforehand (thereby reducing network latency on user experience). I have constructed an additional loop beforehand that performs `Glide.with(activity).load(uri).preload()` for every `Uri` in the `ArrayList`.

This works, but unfortunately, when I do `Glide.with(activity).load(uri).preload(1, 1)` instead - it still seems to work. This has caused me great confusion - as I understand `preload` loads the image into the `RESULT` and `MEMORY` caches. However, since the "preloaded" image in this case is specified to be 1x1, shouldn't Glide automatically notice that the cached version is unfit for use when `Glide.with(activity).load(uri).into(imageView)` is later called? What is going on here?

**Comment by AlanCPSC** [comment]
Also what is the difference between using `preload` and `downloadOnly` with `submit`?

```
List<Uri> pictures = ...

// Both of these seem to do the exact same thing
Glide.with(getContext()).load(pictures.get(0)).preload();
Glide.with(getContext()).downloadOnly().load(pictures.get(0)).submit();
```

**Comment by sjudd** [comment]
Bonus points for adding an answer to your own question :).
