### ISSUE TITLE
DataFetcher#cancel() should be called on a background thread

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#278]
OkHttp and HttpUrlConnection both trigger strict mode violations when cancel is called on the main thread (See #257, and the TODO in HttpUrlFetcher).

**Comment by TWiStErRob** [comment]
@sjudd this seems to be fixed on your branch, did you forget to merge it?

**Comment by sjudd** [comment]
I tried, but it causes issues with OkHttp. At least that (now relatively old) version of OkHttp seemed to get into a bad state after a few async cancellations of in process requests.

**Comment by floating-cat** [comment]
OkHttp fixes this issue in v2.7.0.
``OkHttp now detects and warns on connections that were allocated but never released, and will enforce HTTP/2 stream limits. This update also fixes Call.cancel() to not do I/O on the calling thread.``

https://github.com/square/okhttp/blob/master/CHANGELOG.md
https://github.com/square/okhttp/issues/1592

**Comment by TWiStErRob** [comment]
@floating-cat thanks! Glide `master` is currently on `okhttp-2.3.0`.
@sjudd If we update it to `2.7.0` and add the `cancel` call in the integration lib, we can fix #257, but not this issue. Some [hacky version detection](https://github.com/square/picasso/blob/9e2f6cbe14afdfb6ec8ca0328ebe1551f9db66d8/picasso/src/main/java/com/squareup/picasso/Utils.java#L251) may also be needed to no try to cancel when an older version of OkHttp is forced on the classpath.

**Comment by sjudd** [comment]
Obsolete with okhttp3 and v4
