### ISSUE TITLE
no find GlideApp

### ISSUE THREAD

**Issue by 2Exception** [bumptech/glide#2784]
GlideApp
    .with(myFragment)
    .load(url)
    .centerCrop()
    .placeholder(R.drawable.loading_spinner)
    .into(myImageView);

implementation 'com.github.bumptech.glide:glide:4.4.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'

no find GlideApp

**Comment by sjudd** [comment]
Duplicate of #1939
