### ISSUE TITLE
Not support for  9-patch picture as a placeholder

### ISSUE THREAD

**Issue by meikaiss** [bumptech/glide#2786]
I use glide-4.2,   I have a placeholder with 9-patch, but glide show the placeholder like a normal png.
How can I show the placeholder with 9-patch?

my code is:
``
Glide.with(context).load("my_net_image_url") .apply(new RequestOptions().placeholder(R.drawable.my_9_patch)) .into(myImageView);
``

myImageView's sacleType is centerCrop which is write in xml.

and I also have tried `placeholder(drawable)`, but no effect.
and I have tried #814,  but no help.

**Comment by sjudd** [comment]
Could you attach a sample 9 patch that isn't working for you?

**Comment by meikaiss** [comment]
This is my sample 9 patch.   And it is  useful in my Android Studio.

![img_place_holder_big 9](https://user-images.githubusercontent.com/11609129/34926469-a5a51e32-f9ea-11e7-8677-aa36ac495f64.png)

<img width="1422" alt="demo" src="https://user-images.githubusercontent.com/11609129/34926509-d49261b4-f9ea-11e7-8763-31b1faa664f5.png">

**Comment by liufsd** [comment]
+1

**Comment by liufsd** [comment]
+1 
because the scaleType will also scale the .9.png . such as 'centerCrop' , but we do not want this. we hope .9.png not scale.

**Comment by sjudd** [comment]
You could use .dontTransform() when you're loading a 9 patch. I'm not sure that there's a ton else we can realistically do without a lot of work, which probably isn't justified.

**Comment by liufsd** [comment]
```
            val requestOptions = RequestOptions().dontTransform().transforms(CenterCrop(), RoundedCorners(radius))
                    .placeholder(placeholder).diskCacheStrategy(DiskCacheStrategy.ALL)
```

like this ???
Are you sure

**Comment by sjudd** [comment]
Oh, you want a transformation to apply to the 9patch? They normally scale to fit whatever size you have already so transforming them is a little strange?

There definitely is no point in calling ``.dontTransform().transforms(...)`` since ``.transforms()`` will override the ``.dontTransform()``.

**Comment by liufsd** [comment]
no no no.
I mean i have add `CenterCrop` from ImageView, but i don't want to transforms apply for my 9patch placeholder. i hope the 9patch placeholder not scale by `CenterCrop`. just scale by normal like @meikaiss pictures only scale white area px.

**Comment by sjudd** [comment]
Ahh ok I think I get it. 

Make the 9patch the background of your View, don't use ``placeholder``. 

Or alternatively extend ``DrawableImageViewTarget`` or some other ``ViewTarget`` and update ``onLoadStarted`` so that it uses ``setBackground`` instead of ``setImageDrawable``. ``placeholder`` uses ``setImageDrawable`` to avoid stretching icons, but that's not the behavior you want with the 9 patch.

**Comment by AAverin** [comment]
@sjudd Having 9patch as a background of the View is nice and works ok, but then when real image is loaded and put as `src` – this results in overdraw for every picture on the screen.
Would be great to avoid overdraw somehow. Eg, by using 9patch as a placeholder that would be removed when image is loaded, but then 9patch should stretch properly to fill the view

Another option would be to remove the background image somehow when the source is loaded
