### ISSUE TITLE
java.lang.NoSuchMethodError: No static method getFont

### ISSUE THREAD

**Issue by jonneymendoza** [bumptech/glide#2796]
Hi

i am getting the error below using this library.

java.lang.NoSuchMethodError: No static method getFont

it crashes as soon as i open up a UI.

If i remove //    implementation 'com.github.bumptech.glide:glide:4.5.0'
//    annotationProcessor 'com.github.bumptech.glide:compiler:4.5.0' it works fine

Its something to do with the library using vversion 27 of the support library while i am using version 26

**Comment by sjudd** [comment]
Duplicate of #2730
