### ISSUE TITLE
centerCrop is invalid when using crossFade() and placeholder

### ISSUE THREAD

**Issue by wsty** [bumptech/glide#2802]
**Glide Version**: 4.0.0

**Integration libraries**:okhttp3

code:
RequestOptions options = RequestOptions.diskCacheStrategyOf(
                    config.getDiskCacheStrategy().getStrategy())
                    .skipMemoryCache(config.isSkipMemoryCache())
                    .priority(config.getPriority().getPriority())
                    .centerCrop()
                    .placeholder(R.drawable.ic_launcher);
Glide.with(context).load(url).transition(withCrossFade()).apply(options).into(iv);

how can i use them at the same time ?

**Comment by sjudd** [comment]
I'm not sure what you mean by not available?

**Comment by wsty** [comment]
Sorry, CenterCrop is invalid and the pictures are stretched

**Comment by sjudd** [comment]
Have you tried a more recent version of Glide? Can you attach a [failing test case][1]?

[1]: http://bumptech.github.io/glide/tut/failing-test-cases.html
