### ISSUE TITLE
How to cache blurred image?

### ISSUE THREAD

**Issue by u-nation** [bumptech/glide#2804]
`Glide:3.8.0`

I have the following use case:

      1. Use Blurred Image
      2. Activity is re-created when configuration changes such as screen rotations

Problem:

      When activity is re-created, although no blur image doesn't blink, blurred image blink

my code is:
```kotlin
 Glide.with(this)
        .load("imageUr"l)
        .apply(RequestOptions.bitmapTransform(BlurTransformation()))
        .into(imageView)
```

If Glide can cache blurred image ,Please let me know how to cache it.

**Comment by sjudd** [comment]
Te apply syntax is for v4.0+. Are you using Glide v4 or v3? 

See http://bumptech.github.io/glide/doc/caching.html and http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses if you're using v4.

**Comment by tendo-folio** [comment]
Thank you for your quick reply!

Sorry , I use `jp.wasabeef:glide-transformations:3.0.1` whice uses v4.0.0, so I can use apply syntax.

So, you mean Glide cache transformed image such as Rounded, Croped,Blurred, right??

**Comment by sjudd** [comment]
Glide can cache transformed images, depending on your `DiskCacheStrategy`. There's a lot more detail at the links I provided.

**Comment by u-nation** [comment]
Thanks! I'll look it up.
