### ISSUE TITLE
Where is  the .using() api

### ISSUE THREAD

**Issue by Guang1234567** [bumptech/glide#2806]
@sjudd 

I using ` .using(new GlideOkHttpUrlProgressLoader(mProgressListener)) ` to listen the progress of the download  in  `Glide 3.x`

```java
Glide.with(getContext()) //getContext() reture ApplicationContext, no memory leak.
                    .using(new GlideOkHttpUrlProgressLoader(mProgressListener)) // <---------------- here
                    .load(getGlideUrl())
                    .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);

```

Question:

How to code in **Glide 4.x** ?  I can not find the `using(...)` api ...

**Comment by AndrazP** [comment]
https://bumptech.github.io/glide/doc/migrating.html#using-modelloader-streammodelloader

**Comment by Guang1234567** [comment]
Thanks you @AndrazP

https://bumptech.github.io/glide/doc/migrating.html#using

>The using() API was removed in Glide 4 to encourage users to register their components once with a AppGlideModule to avoid object re-use. Rather than creating a new ModelLoader each time you load an image, you register it once in an AppGlideModule and let Glide inspect your model (the object you pass to load()) to figure out when to use your registered ModelLoader.
