### ISSUE TITLE
Kotlin/kapt - Glide: Failed to find GeneratedAppGlideModule

### ISSUE THREAD

**Issue by Mathbl** [bumptech/glide#2817]
**Glide Version**: 4.5.0

**Integration libraries**: okhttp3-integration

**Device/Android Version**: doesn't seem device related. The warning shows on emulators and every test devices I have.

**Issue details / Repro steps / Use case background**: 
I followed the setup instructions. Glide is working as expected in my app, but i'm getting this warning in logcat, which shouldn't be there since my setup seems correct.
```java
Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
```
I'm using kotlin. kapt plugin is applied at the top of my build.gradle file:
```gradle
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
```
and I also have this
```gradle
implementation 'com.github.bumptech.glide:glide:4.5.0'
kapt 'com.github.bumptech.glide:compiler:4.5.0'
implementation "com.github.bumptech.glide:okhttp3-integration:4.5.0"
```
I have created a class extending AppGlideModule
```kotlin
@GlideModule
class MyAppGlideModule : AppGlideModule() {
    override fun applyOptions(context: Context, builder: GlideBuilder) {
        super.applyOptions(context, builder)
        if (BuildConfig.DEBUG) {
            builder.setLogLevel(Log.VERBOSE)
        }
    }
}
```
kapt seems to generate the `GlideApp`, `GlideOptions`, `GlideRequest`, `GlideRequests`, `GeneratedAppGlideModuleImpl` and `GeneratedRequestManagerFactory` classes correctly. I can see them.

**Comment by sjudd** [comment]
Sounds like another duplicate of #1939. Are you able to use the generated API? If so, does the app crash?

**Comment by Mathbl** [comment]
From what i've read in that thread, people were missing includes or didn't follow the setup instructions. 

Like I said, the classes seem to be generated correctly by kapt cause I can see them and browse them. I'm also using GlideApp APIs throughout the app without problems.

And, the code that triggers the warning is looking for a class that seems to be generated correctly:
```java
try {
      Class<GeneratedAppGlideModule> clazz =
          (Class<GeneratedAppGlideModule>)
              Class.forName("com.bumptech.glide.GeneratedAppGlideModuleImpl");
      result = clazz.getDeclaredConstructor().newInstance();
    } catch (ClassNotFoundException e) {
      if (Log.isLoggable(TAG, Log.WARN)) {
        Log.w(TAG, "Failed to find GeneratedAppGlideModule. You should include an"
            + " annotationProcessor compile dependency on com.github.bumptech.glide:compiler"
            + " in your application and a @GlideModule annotated AppGlideModule implementation or"
            + " LibraryGlideModules will be silently ignored");
      }
}
```
`GeneratedAppGlideModuleImpl`:
![img](https://dha4w82d62smt.cloudfront.net/items/1o2F3X113a47000f1V0j/%5Bf53719a61549e7bf81d0b35e4f0e2fb0%5D_Image+2018-01-16+at+10.23.23+AM.png)

**Comment by sjudd** [comment]
If you're able to reproduce this in a sample app, I'm happy to take a look. 

Otherwise, if you can use the generated API in your app and it doesn't crash, it's unlikely that the method in question is actually failing. There's some casting that will throw if that happens. Can you provide your Glide load line?

**Comment by Mathbl** [comment]
I just tried to put on a sample app that reproduces the issue, and after adding one library at a time to reproduce my actual app configuration, I found out the culprit: Intercom library (https://github.com/intercom/intercom-android).

I know they use a repackaged version of Glide in their library, I'll check their repo to see if I can find something.

Thanks. Feel free to close the issue, because I presume it is more an issue with intercom!

**Comment by sjudd** [comment]
Awesome thanks for investigating. Let me know if you find anything. We may be able to make the error message more useful, like include the package name of the class we tried to load, which would make repackaging at least clearer (if they change the class package names).
