### ISSUE TITLE
Glide 3 & 4 compatibility

### ISSUE THREAD

**Issue by kirich1409** [bumptech/glide#2820]
I have old library that use Glide 3 that use API that was removed in Glide 4. Glide 4 is not backward compatible with Glide 3. How I can use both Glide 3 & 4 in one project? 

Maybe it's possible to change library package to `com.github.bumptech.glide4`? Is work very well with popular libraries like retrofit, okhttp, dagger

**Comment by sjudd** [comment]
You can't safely use multiple versions of image loading libraries together because you'll substantially increase your memory usage by have two memory caches, two bitmap pools etc.

**Comment by kirich1409** [comment]
I know that this is very bad, but I have library, that I need to use in all projects, and don't have possibility to switch it to Glide 4. Consuming too much resource is problem of developers if they want to use multiple version of same library of multiple image loaders in one project. But it will be good, if you make library in way that developer can have choice, because in current condition of projects I need to use Glide 3.

**Comment by sjudd** [comment]
I'm sorry that upgrading is a challenge, but we don't want to encourage dangerous behavior. If you can control the cache sizes and locations of the v3 version, you could do something like repackage the v3 version yourself using jarjar or some other repackaging tool

**Comment by kirich1409** [comment]
Thank you
