### ISSUE TITLE
GeneratedAppGlideModuleImpl is implemented incorrectly

### ISSUE THREAD

**Issue by amirhgh** [bumptech/glide#2821]
When I added proguard-rules to my project I faced this exception :
```java
java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
```
after searching a while I didn't find anything. finally I found out that by adding this rule to proguard it can be fixed :
```
-keep class com.bumptech.glide.GeneratedAppGlideModuleImpl { *; }
```

**Comment by sjudd** [comment]
What was the content of your proguard file before you added that line?

**Comment by amirhgh** [comment]
These rules caused the exception:
```
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
```

**Comment by amirhgh** [comment]
I used this rules and I faced same issue again.

**Comment by chathura2020** [comment]
Any solution for this issue? 
java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation. 

Still getting this with these versions
implementation 'com.github.bumptech.glide:glide:4.7.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'

**Comment by Pluckypan** [comment]
just remove `-keep class com.bumptech.glide.GeneratedAppGlideModuleImpl `  in proguard.this can be fixed

**Comment by pratikbutani** [comment]
##First thing:

Have you changed `annotationProcessor` dependency:

    implementation 'com.github.bumptech.glide:glide:4.10.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'

##Second things:

Have you added proguard rules as follow:

    -keep public class * implements com.bumptech.glide.module.GlideModule
    -keep public class * extends com.bumptech.glide.module.AppGlideModule
    -keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
      **[] $VALUES;
      public *;
    }

Hope it will helps you. Thank you.

**Comment by fadsel** [comment]
This error is a big mess,
Its 2021 and it is still there, I just migrated to **Android X**

_**`Caused by: java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.`**_

I 've added in my **build.gradle**
```
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
```

Also in my **proguard** file

```
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
```


I even tried deleted the whole progurd file still the same error,

Now I am thinking of migrating the to Picasso

**Comment by fadsel** [comment]
And by the way, If we are loading the files via gradle like how we stated above, now Where is the correct Implementation of **`GeneratedAppGlideModuleImpl`**? What are we missing?

**Comment by fadsel** [comment]
And I did not manually **implement** the file **whatsoever**, the error is completely **misleading**

**Comment by beimuaihui** [comment]
My situation is some library using glide:4.12; and other Libraries using glide:4.9;
Just change them to the same version
