### ISSUE TITLE
Glide is not load file path into TouchImageView from path by not using Target.SIZE_ORIGINAL

### ISSUE THREAD

**Issue by gelbertgel** [bumptech/glide#2826]
working: 

 private void loadImage(String path, TouchImageView imageView) {

            glideRequests.load(path)
                    .diskCacheStrategy(DiskCacheStrategy.NONE)
                    .dontTransform()
                    .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                    .transition(withCrossFade())
                    .into(imageView);
        }

is not working when `     .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)` this line is removing.

not working:

private void loadImage(String path, TouchImageView imageView) {

            glideRequests.load(path)
                    .diskCacheStrategy(DiskCacheStrategy.NONE)
                    .dontTransform()
                    //.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                    .transition(withCrossFade())
                    .into(imageView);
        }

Please help me.

Glide version : 4.5.0

**Comment by sjudd** [comment]
Consider attaching [a failing test case][1]. 

What error do you see? What do you mean by "not working"?

[1]: http://bumptech.github.io/glide/tut/failing-test-cases.html

**Comment by gelbertgel** [comment]
It is not working for TouchImageView

**Comment by sjudd** [comment]
Ok, but what you do mean by "not working"? What in particular isn't working? Is the load failing? If so can you attach the error message from logcat? Is the load just never finishing so the view remains blank forever with no error? 

This might also help: http://bumptech.github.io/glide/doc/debugging.html#missing-images-and-local-logs
