### ISSUE TITLE
RoundedCorners massive lag

### ISSUE THREAD

**Issue by Errichamonda** [bumptech/glide#2828]
I'm having trouble with my application. It all works fine until I put rounded corners on all images.

Here's my java:
`
RequestOptions options = new RequestOptions();

        options.transform(new RoundedCorners(120));

        if (!vPostazioneDettaglio.getImmagine_1().equals("")) {
            Glide.with(this)
                    .load(vPostazioneDettaglio.getImmagine_1())
                    .apply(options)
                    .into(immagine1);
        }
        else immagine1.setVisibility(View.GONE);`

XML:
`
                <ImageView
                    android:id="@+id/imageView1"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:adjustViewBounds="true"/>`

I have 10 of them in the activity. 

It causes massive lag when I reach the 4th image. The odd is that in some phone like OnePlus One, Nexus 6P, Samsung 6 and Samsung note 8 it lags but in a chinese phone (don't know the excact model) it doesn't.

The problem is solved when I remove the rounded corner transformation.

Edit: forgot to mention that the images are from url and vDettaglioPosizione is the ArrayList containing all the information for the activity (text, imagesUrl) and also that I'm using Glide 4.5.0

Edit2: Video explaning https://www.youtube.com/watch?v=dcqMHi-nEKA

**Comment by sjudd** [comment]
You could check your memory usage to see if you're running out of memory or causing excessive GCs. Otherwise try checking systrace: https://developer.android.com/studio/command-line/systrace.html.

**Comment by Errichamonda** [comment]
I've figured it out. It was a problem caused by Glide trying to resize large image and pinning the CPU.

I've added .override(com.bumptech.glide.request.target.Target.SIZE_ORIGINAL) to my RequestOptions and everything works fine.

**Comment by hamid97m** [comment]
@Errichamonda Have you any problems with radiuses? radius sizes seem wrong after added `.override(com.bumptech.glide.request.target.Target.SIZE_ORIGINAL)`
