### ISSUE TITLE
Save GIF from PhotoView

### ISSUE THREAD

**Issue by mdczaplicki** [bumptech/glide#2833]
Hey,

I use Glide to download a GIF and insert it into PhotoView. Works fine, but I want to be able to save this GIF to my local storage. I have searched through issues over here, but none was viable for me.
I was trying to use this part of code to get this done:

    override fun getDrawable() : Drawable? {
        photoView.image.drawable?.apply {
            return this
        }
        return null
    }

    override fun saveImage() {
        val drawable = getDrawable()
        if (drawable == null || !checkForWriteReadPermission()) {
            return
        }
        if (drawable is BitmapDrawable) {
            val bitmap = drawable.bitmap
            val file = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), "wykopmobilny")
            if (!file.exists()) file.mkdirs()

            val pictureFile = File("""${file.absoluteFile}/${photoView.url.substringAfterLast('/')}""")
            val fos = FileOutputStream(pictureFile)
            bitmap.compress(Bitmap.CompressFormat.PNG, 90, fos)
            fos.close()
            addImageToGallery(pictureFile.absolutePath, context)
            showToastMessage("Zapisano obraz")
        }
        else if (drawable is GifDrawable) {
            val byteBuffer = drawable.buffer
            val file = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), "wykopmobilny")
            if (!file.exists()) file.mkdirs()
            val gifFile = File("""${file.absoluteFile}/${photoView.url.substringAfterLast('/')}""")

            val output = FileOutputStream(gifFile)
            val bytes = ByteArray(byteBuffer.position())
            byteBuffer.get(bytes)
            output.write(bytes, 0, bytes.size)
            output.close()
			//val fileChannel = FileOutputStream(gifFile).channel
			//fileChannel.write(byteBuffer)
			//fileChannel.close()
            showToastMessage("Zapisano GIFa")
        }
    }

and it actually creates a file, but it is broken and cannot be open. For example the file size is 4.19, but the GIF size when downloading was 4.59, so it looks like it is missing some part of it.

Glide version I use is 4.5 and the Widget is https://github.com/chrisbanes/PhotoView

PS. Saving static image works fine.

**Comment by mdczaplicki** [comment]
If anyone wonders how to do it, it is here:

        else if (drawable is GifDrawable) {
            val byteBuffer = drawable.buffer
            val file = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), "wykopmobilny")
            if (!file.exists()) file.mkdirs()
            val gifFile = File("""${file.absoluteFile}/${photoView.url.substringAfterLast('/')}""")

            val output = FileOutputStream(gifFile)
            val bytes = ByteArray(byteBuffer.capacity())
            (byteBuffer.duplicate().clear() as ByteBuffer).get(bytes)
            output.write(bytes, 0, bytes.size)
            output.close()
            showToastMessage("Zapisano GIFa")
        }

I wasn't taking whole buffer to the file.

**Comment by sjudd** [comment]
Glide isn't really a networking library. If you don't want to display the image, you're much better off using something like OkHttp to download the file. 

If you really want to, you can get at the cache File in Glide pretty easily using [``downloadOnly()``][1]:

```java
File cacheFile = Glide.with(context).downloadOnly().submit().get();
```

[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/RequestManager.html#downloadOnly--

**Comment by mdczaplicki** [comment]
But I want to display the image and then have a possibility to save it to some specific location.

**Comment by sjudd** [comment]
In that case you can use ``downloadOnly()``. It's much better to make two requests and let Glide deal with the caching than trying to extract the data from the View and writing it on the main thread. 

That said, I think you're actually using Glide v3 (please fill out the issue template next time), so although there is a downloadOnly method, the syntax isn't exactly what I used above.

**Comment by mdczaplicki** [comment]
Version is v4 and there are no errors in the line you have provided. But I think that there is missing `.load(url)`, am I right?

**Comment by sjudd** [comment]
Yup, updated

**Comment by mdczaplicki** [comment]
Is it like you are really sure that downloading image/gif again is better than extracting it from View?

**Comment by sjudd** [comment]
downloadOnly will only download the GIF again if it's not already in the disk cache. Otherwise you're just retrieving the file path to the cached image. 


The ``get()`` method forces you to run it on a background thread (much better for performance than writing to a file on the main thread). If you were to work around the performance issue by writing the data you extracted from the view to a file on a background thread, you'd run into concurrency issues where the data may be cleared or modified while you were reading it.

Using ``downloadOnly()`` also avoids issues like the one you ran into where the data loaded into the view isn't re-wound or ready to be copied.
