### ISSUE TITLE
Why show one 4K picture is not clear?  The glide is not surpport? Thanks!

### ISSUE THREAD

**Issue by abneryan** [bumptech/glide#2834]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Please file a new issue and actually fill out the issue template if you'd like help.
