### ISSUE TITLE
Cannot resolve method crossFade()

### ISSUE THREAD

**Issue by salimshivani** [bumptech/glide#2837]
Hello Team Glide,

I recently updated Glide library in project to
    **compile 'com.github.bumptech.glide:glide:4.4.0'**
from
    **compile 'com.github.bumptech.glide:glide:3.7.0'**

As soon as I run the project after the update, it gave me the error on crossFade() method, as attached in the screenshot.
![glide error](https://user-images.githubusercontent.com/11092638/35280765-31ced596-0077-11e8-8fd3-e6d9ca41379d.PNG)

Is the method deprecated in the new update? If so, what method I shall use to get the effect that was in the crossFade() method. Any further guidance would be appreciated.

Regards
Mohammedsalim S.

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/options.html#transitionoptions or http://bumptech.github.io/glide/doc/migrating.html#transitionoptions

**Comment by salimshivani** [comment]
Thank you @sjudd. I found the solution in the documentation you shared. Hence, I am closing this thread.

![glide error solved](https://user-images.githubusercontent.com/11092638/35342390-f2e97f52-014d-11e8-8a79-016f81d19a9b.PNG)

**Comment by karthik2342323** [comment]
implementation 'com.github.bumptech.glide:glide:3.7.0'
add this dependencies because it work in older version alright go ahead
