### ISSUE TITLE
Bug with ConstraintLayout+Ratio+Padding

### ISSUE THREAD

**Issue by bernaferrari** [bumptech/glide#2838]
When using ConstraintLayout with a custom ratio (for example, 16:9), a padding (for example, 4dp) and an image that fits the ratio perfectly (for example, a youtube thumbnail like this: https://i.ytimg.com/vi/T0Jqdjbed40/mqdefault.jpg), there is a small margin below the image. Please look at this picture where the red rectangles are 4dp wide and are touching the imageView corners. The green rectangle represents the paddingRight = 4dp:

![screenshot_20180123-231942](https://user-images.githubusercontent.com/351125/35309819-5e819812-0095-11e8-8352-482fd00a1aa0.png)
As you can see, there is a small white area in the red rectangle from below that shouldn't be there. 

This only happens when padding is being used. I initially suspected that Glide was ignoring the padding value, but as you can see, there is nothing with the green rectangle.

This is the code that matters:
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="8dp">

    <ImageView
        android:id="@+id/imageView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:paddingRight="4dp"

        app:layout_constraintDimensionRatio="h,16:9"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
      />
</android.support.constraint.ConstraintLayout>
```

With this:
```
Glide.with(viewHolder.imageView)
                .load(photoUrl)
                .apply(RequestOptions().transform(RoundedCorners((4 * viewHolder.imageView.context.resources.displayMetrics.density).toInt())))
                .into(viewHolder.imageView)
```

**Temporary fix:**
Use margin instead of padding, it works.

![screenshot_20180123-234011](https://user-images.githubusercontent.com/351125/35310102-ed63fb46-0096-11e8-8c74-60540ffaa591.png)

**Glide Version**: 4.5.0
**ConstraintLayout  Version**: 1.0.2

**Integration libraries**: No

**Comment by sjudd** [comment]
Are you saying that the view width - 4dp == the width of your image? 

If you're instead saying that the view width == the width of your image, then this is expected. The padding decreases the horizontal size of the image, so Glide has to scale the vertical size of the image as well to maintain the original aspect ratio. I'd imagine the difference you're seeing at the bottom of the image is 4dp * (height/width)?

**Comment by bernaferrari** [comment]
> Are you saying that the view width - 4dp == the width of your image?

Yes

> I'd imagine the difference you're seeing at the bottom of the image is 4dp * (height/width)?

This is exactly the problem I am having, the difference below is not 4dp (each small red/green square in the screenshots above are 4dp), maybe ~3dp, but something looks wrong.

**Comment by bernaferrari** [comment]
Forget it, I found the problem, Constraint Layout is changing the constraint's ratio when padding is on..
Sorry for taking your time!!

**Comment by sjudd** [comment]
No worries, thanks for following up.
