### ISSUE TITLE
Glide 4.5.0 signature not applied

### ISSUE THREAD

**Issue by snehalgongle** [bumptech/glide#2839]
**Glide Version**:4.5.0

**Integration libraries**: implementation 'com.github.bumptech.glide:glide:4.5.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.5.0'

**Device/Android Version**:Redmi Note 4 /Android 7.0(Api 24)

**Issue details / Repro steps / Use case background**: I'm using glide to load images also from version 4 i'm happy to use circular function  .apply(RequestOptions.circleCropTransform()) but also i wanted to use the signature or something related to clear the cache and load the latest image in the imageView  

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...

        Glide.with(mContext)
                .load(urlProfile)
                .apply(RequestOptions.circleCropTransform())
                .signature(new StringSignature(String.valueOf(System.currentTimeMillis())))
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .into(imageView);

getting error with signature and diskCacheStrategy  so is there any alternate to signature and diskCacheStrategy   such that   .apply(RequestOptions.circleCropTransform()) this functionality should also keep working  
```

**Layout XML**: Did not Compile
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
``.signature()`` and ``.diskCacheStrategy()`` are both methods on ``RequestOptions``, see http://bumptech.github.io/glide/doc/options.html#requestoptions.

In particular you can just chain those options onto your existing ``circleCropTransform()`` call:

```java
Glide.with(mContext)
  .load(urlProfile)
  .apply(RequestOptions.circleCropTransform()
      .signature(new StringSignature(...))
      .diskCacheStrategy(DiskCacheStrategy.NONE))
  .into(imageView);
```

**Comment by snehalgongle** [comment]
Thanks for the reply and I appreciate the great library you have made and
also the better you are maintaining it with care

Thanks and regards
Snehal

**Comment by sjudd** [comment]
Sure no problem, glad it's useful. I'll assume this is resolved for now, but feel free to add a comment or file a new issue if you have questions.

**Comment by wseng92** [comment]
After using circleCropTransform(), my image getting cropped. How to prevent it from cropped?
