### ISSUE TITLE
Glide 4.5.0 Flickering with AspectRatioImageView

### ISSUE THREAD

**Issue by 8masterofpuppets8** [bumptech/glide#2840]
**Glide Version**:

4.5.0

**Integration libraries**:

implementation "com.github.bumptech.glide:glide:4.5.0"
annotationProcessor "com.github.bumptech.glide:compiler:4.5.0"

**Device/Android Version**:

Nexus 5X, Android 8.1

**Issue details / Repro steps / Use case background**: 

I am using Glide v4.1.1 and wanted to update to 4.5.0 and am seeing quite a lot of flickering when the images are loaded. I did read in the release logs that since v4.2.0 there were changes to the way Glide handles view sizes and that's why v4.1.1 works perfectly for me but versions 4.2.0+ do not and all have the same issue.

I also would like to mention that I am using a StaggeredGridLayoutManager and each image is in a cell with an AspectRatioImageView which can be found here:

[https://github.com/subinkrishna/Aspect](https://github.com/subinkrishna/Aspect)

**Note that the exact same code works perfectly with a GridLayoutManager where the sizes of the items are fixed.**

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

```
GlideApp
                .with(getContext())
                .load(url)
                .thumbnail(0.1f)
                .fitCenter()
                .into(imageView);
```

The aspect ratio of the image view is calculated before loading the image and I am setting it on the image view. Not sure about the actual size cycle as that depends on the AspectImage library but I can see that the images are correctly sized without any flickering issues if I turn Glide off and just display the image containers.

**Layout XML**:

This is the layout for each of the images in the layout:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <com.subinkrishna.aspect.AspectRatioImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="centerCrop"
        app:lock="width"/>

    <com.graffitab.ui.views.likeimageview.BackgroundCircle
        android:id="@+id/circleBg"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerInParent="true"
        android:background="@drawable/circle_like_animation_background"
        android:visibility="gone"/>

    <ImageView
        android:id="@+id/heart"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="fitCenter"
        android:src="@drawable/like"
        android:visibility="gone"/>

    <RelativeLayout
        android:id="@+id/loadingIndicator"
        android:layout_width="@dimen/row_streamable_grid_processing_progress_size"
        android:layout_height="@dimen/row_streamable_grid_processing_progress_size"
        android:layout_centerInParent="true"
        android:visibility="gone">

        <View
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@drawable/circle_progress_bar_background"/>

        <ProgressBar
            android:id="@+id/progress_bar"
            style="?android:attr/progressBarStyleLarge"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:indeterminateTint="@color/white"
            android:indeterminateTintMode="src_in"/>
    </RelativeLayout>
</RelativeLayout>
```

**Stack trace / LogCat**:
```ruby
None
```

Here's how the app looks with Glide 4.1.1:

![glide_4 1 1](https://user-images.githubusercontent.com/7644787/35387198-ae27f15e-01c6-11e8-9149-649ec0e8ee9c.gif)

Here's how the app looks with Glide 4.5.0:

![glide_4 5 0](https://user-images.githubusercontent.com/7644787/35387211-b8be3f2e-01c6-11e8-8ef6-ee2172c0b78c.gif)

**Comment by sjudd** [comment]
Did you try [``.waitForLayout()``][1]? Do you know the sizes of the images at the time the view is bound in RecyclerView?

[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/request/target/ViewTarget.html#waitForLayout--

**Comment by 8masterofpuppets8** [comment]
I couldn't find a method `.waitForLayout()`, how would I call it?

Yes I do have the sizes of the thumbnails available in `onBindViewHolder()`. Could I set it to Glide somehow?

**Comment by 8masterofpuppets8** [comment]
@sjudd your suggestion worked! My updated code now is:

```
DrawableImageViewTarget target = new DrawableImageViewTarget(imageView);
target.waitForLayout();
GlideApp
        .with(getContext())
        .load(url)
        .thumbnail(0.1f)
        .fitCenter()
        .into(target);
```

Image loading is now as smooth as in v4.1.1. Thanks!

**Comment by sjudd** [comment]
Great thanks for following up. 

You can actually just append ``waitForLayout`` after ``into()``, sorry I should have made that clearer:


```
GlideApp
  .with(context)
  .load(url)
  .thumbnail(0.1f)
  .fitCenter()
  .into(target)
  .waitForLayout();
```

``into()`` has always returned a ``Target`` so the chaining works out nicely, no need for an explicit or custom ``Target`` unless you need it for some other reason.
