### ISSUE TITLE
InterruptedException  - load multiple images in DataFetcher via glide

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#2843]
**Glide Version**: 3.8

**Integration libraries**: none

**Device/Android Version**: 4.4 or higher

**Issue details / Repro steps / Use case background**: 

I want to display mutliple images in one view. Actually like a folder icon in a launcher. Therefore I load a few images into targets, an then combine them. The problem is, that if I use my view in a `RecyclerView`, it's slow (compared to an `ImageView` for example). The reason for this is, that I am combining the images to a single `Bitmap` every time (just the sub images are cached by glide). So the improvement would be to cache the combined image as well.

To solve this problem I tried following two things. I'm not sure if there is a better way. For me it looks like idea 1 is a good idea, but it does not work. Idea 2 does not look that clean though. Maybe there's a better third approach?

**----------------------------------------------------**
**Idea 1 - use a custom `DataFetcher` that internally loads the sub images via glide**
**----------------------------------------------------**

Here I tried to write a custom `DataFetcher` that works like following:

* fetch all sub images synchronously in this data fetcher via glide like following:
    
        List<Drawable> drawables = new ArrayList<>();
        for (Request r : requests) {
            FutureTarget t = r.into(w, h);
            drawables .add((Drawable)t.get());
            Glide.clear(t);
        }

* combine the images to a final image => this would also be cached by glide automatically

*Problems:*
This leads to `java.lang.InterruptedException` interrupted exceptions though and I don't know why...

**----------------------------------------------------**
**Idea 2 - use glide to load sub images, calculate the combination in the background and manually put it into glide's cache**
**----------------------------------------------------**

I want to avoid two caches for images because this may lead to memory issues. So I also tried following:

* expose glide's cache like following:

		public class GlideConfig implements GlideModule {

			public static LruResourceCache MEMORY_CACHE = null;
			public static LruBitmapPool BITMAP_POOL = null;

			@Override
			public void applyOptions(Context context, GlideBuilder builder) {
				// Apply options to the builder here.
				builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);

				MemorySizeCalculator calculator = new MemorySizeCalculator(context);
				MEMORY_CACHE = new LruResourceCache(calculator.getMemoryCacheSize());
				builder.setMemoryCache(MEMORY_CACHE);

				BITMAP_POOL = new LruBitmapPool(calculator.getBitmapPoolSize());
				builder.setBitmapPool(BITMAP_POOL);
			}

			@Override
			public void registerComponents(Context context, Glide glide) {
			}
		}
	
* use the cache manually like following:

		BitmapDrawable combined = getCachedDrawable();
		if (combined == null) {
		    // load images and combine them...
			combined = ...;
			cacheDrawable(new BitmapDrawable(MainApp.get().getResources(), combined));
		}
		
Here I use following helper functions to directly access glide's cache:

	private BitmapDrawable getCachedDrawable() {
        if (GlideConfig.MEMORY_CACHE == null) {
            return null;
        }
        Resource<BitmapDrawable> resource = (Resource<BitmapDrawable>) GlideConfig.MEMORY_CACHE.get(new StringSignature(getCacheId()));
        return resource.get();
    }

    private void cacheDrawable(BitmapDrawable d) {
        if (GlideConfig.MEMORY_CACHE == null || d == null) {
            return;
        }
        Resource<BitmapDrawable> resource = new BitmapDrawableResource(d, GlideConfig.BITMAP_POOL);
        GlideConfig.MEMORY_CACHE.put(new StringSignature(getCacheId()), resource);
    }

*Problems*
Here I'm unsure if this is save. Is it save to access the cache like this? Should it happen in a snychronised way? Maybe the cache should only be accessed from the main thread? Or shouldn't this be done at all?

**Comment by sjudd** [comment]
Accessing Glide's cache directly or caching resources yourself is unsupported and likely to break things due to Bitmap re-use.

I don't think v3 supports recursively loading images with Glide on Glide threads. You can do this in v4. I'm not sure what the InterruptedException is since you didn't provide a stack trace, but I'd guess it's related. 

You can use a custom DataFetcher, but you'll have to fetch and decode the image data yourself in v3. Or you can load and cache the images individually. If you're caching appropriately sized images and only loading a few, it shouldn't be dramatically slower to load them vs load a single combined image.

**Comment by MFlisar** [comment]
So I should throw away approach 2, ok.

**Interrupted exception**

Here's an example of it's stacktrace:

	java.lang.InterruptedException (ImageManager.java:575)
		 at java.lang.Object.wait(Native Method)
		 at java.lang.Object.wait(Object.java:407)
		 at com.bumptech.glide.request.RequestFutureTarget$Waiter.waitForTimeout(RequestFutureTarget.java:238)
		 at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:181)
		 at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:100)
		 at com.my.app.images.ImageManager.loadIcon(ImageManager.java:572)
		 at com.my.app.images.ImageManager.loadImage(ImageManager.java:690)
		 at com.my.app.images.ImageManager.loadSidebarItemIcon(ImageManager.java:106)
		 at com.my.app.images.ImageManager.loadSidebarItemIcon(ImageManager.java:82)
		 at com.my.app.images.glide.FolderItemLoader.loadData(FolderItemLoader.java:83)
		 at com.my.app.images.glide.FolderItemLoader.loadData(FolderItemLoader.java:28)
		 at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
		 at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
		 at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
		 at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
		 at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:127)
		 at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:106)
		 at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
		 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
		 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
		 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
		 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
		 at java.lang.Thread.run(Thread.java:762)
		 at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
		 
Any idea why this can happen? This happens using a `DataFetcher` like the one below...

**Your answer**

* "I don't think v3 supports recursively loading images" + "You can use a custom DataFetcher, but you'll have to fetch and decode the image data yourself in v3" - how can I understand this? Is my approach in general ok or not? Should a custom `DataFetcher` generally work?

		public class MyDataFetcher<T> implements DataFetcher<InputStream> {
			protected int mWidth;
			protected int mHeight;

		   protected InputStream mStream = null;

			public MyDataFetcher(int w, int h, <EXTRA DATA>) {
				mWidth = w;
				mHeight = h;
			}

			@Override
			public InputStream loadData(Priority priority) throws Exception {
			   
				Bitmap bitmap = Bitmap.createBitmap(mWidth, mHeight, Bitmap.Config.ARGB_8888);
				Canvas canvas = new Canvas(bitmap);

				// Load
				List<Request> requests = ...;
				List<Drawable> drawables = new ArrayList<>();
				for (Request r : requests) {
					FutureTarget t = r.into(w, h);
					drawables .add((Drawable)t.get());
					Glide.clear(t);
				}

				// Draw
				// combine all images and draw them on the bitmap
				// ...

				return getStreamFromBitmap(bitmap);
			}

			@Override
			public String getId() {
				return <UNIQUE ID>;
			}

			protected InputStream getStreamFromBitmap(Bitmap bitmap) {
				ByteArrayOutputStream bos = new ByteArrayOutputStream();
				bitmap.compress(Bitmap.CompressFormat.PNG, 0, bos);
				byte[] bitmapdata = bos.toByteArray();
				mStream = new ByteArrayInputStream(bitmapdata);
				return mStream;
			}

			@Override
			public final void cleanup() {
				if (mStream != null) {
					try {
						mStream.close();
					} catch (IOException e) {
						L.e(e);
					}
				}
			}

			@Override
			public final void cancel() {

			}
		}

**Comment by MFlisar** [comment]
PS: do you say that above nested image loading in a custom `DataFetcher` would work the way I do it in glide v4 without problems?

**Comment by MFlisar** [comment]
I migrated my whole project today to glide v4...

As this is something not many people will be interested in (especially for the old glide version), I close this issue and open a new one for glide 4 if the same issue should appear there. Currently it's not, but I still have a problem using glide4 in a custom view.

**Comment by sjudd** [comment]
Yes you can nest requests safely in Glide v4, though you need to apply [``useUnlimitedSourceGeneratorsPool``][1] to avoid deadlock. Nested requests may work on v3, but they can easily cause deadlock. Consider a case where Glide only creates a single thread to run requests on. If you nest a request, your main request is going to block that single thread waiting for the nested request to run. The nested request will never run because the main request is blocking the single thread. Glide v4 makes this safe only by providing an option to use a non-normal thread pool so that you never end up in this scenario. 

[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/request/RequestOptions.html#useUnlimitedSourceGeneratorsPool-boolean-

**Comment by sjudd** [comment]
Also I don't have any good ideas on what causes the InterruptedException. Java is known for having lots of things randomly trigger those exceptions. It's possible that cancelling the request triggers an interruption or other spurious calls in libraries you're using. Often InterruptedException is either optional or a signal that you should cancel your request, but it really depends on the circumstances.

Glide doesn't explicitly interrupt threads anywhere, although we may cancel futures that belong to particular requests when the request itself is cancelled.

**Comment by MFlisar** [comment]
I will try the use the `useUnlimitedSourceGeneratorsPool` to solve this.

To the exception:
I don't know why it happened, but I know what was causing java to constantly start/stop loads in v3 (which is probably responsible for the exception). I was writing a custom view and had a bug in it so that it was redrawing itself over and over again and as a side effect cancelled and restarted image requests.

**Comment by MFlisar** [comment]
**`useUnlimitedSourceGeneratorsPool`**

Do I need this if I'm sure, that my nested calls never call another request with nested calls?
