### ISSUE TITLE
Update listener when replaying the previous request

### ISSUE THREAD

**Issue by saket** [bumptech/glide#2845]
**Glide Version**: v4.5

If the same image is loaded twice, Glide re-uses the previous `Request` after comparing `if (request.isEquivalentTo(previous)` ([link to code)](https://github.com/bumptech/glide/blob/e9f682f9586a68f9322d978dda4856957167ff0b/library/src/main/java/com/bumptech/glide/RequestBuilder.java#L600). When a distinct listener is used for every request, this results in a problem where the old listener gets invoked instead of the new generated one.

**Usage**
```java
Single<Drawable> imageSingle = Single.create(emitter -> {
  Glide.with(imageView)
      .load(imageUrl)
      .listener(new GlideLambdaRequestListener<>(
          resource -> emitter.onSuccess(resource),
          error -> emitter.onError(error)
      ))
      .into(imageView);
});
```
Will it be possible for Glide to replace the listener when reusing the old `Request`? This behavior is not explicit and I can imagine this resulting in subtle bugs that are hard to locate. 

**Edit**: I know that the documentation for `listener()` recommends using a single instance, but only to avoid memory allocations. The doc isn't explicit about this behavior. Also, do you recommend any other way to achieve unique listeners per Glide load?

**Comment by Tolriq** [comment]
There was discussions previously about those issues. And for the moment the implemented solution is to use a custom model that implements the Model interface.
This allows handling of Glide cache when restarting a query but differentiate the calls to actually have the restart and the listeners called again.

You would just have to return false for the model equity but true for equals/hashcode to have what you require.

See https://github.com/bumptech/glide/pull/2353

**Comment by Saketme** [comment]
Ah, did not know about this. `Model` looks handy. Thanks!

**Comment by anthony-skr** [comment]
I have the same problem when using Rx + retryWhen (previous listener instance is used when re-subscribing).

As a workaround I use :

```
class GlideRx<T>(private val newGlideInstance: () -> RequestBuilder<T>) {
    private var lastEmitter: SingleEmitter<T>? = null

    private val listener = object : RequestListener<T?> {
        override fun onLoadFailed(e: GlideException?, model: Any?,
                                  target: Target<T?>?,
                                  isFirstResource: Boolean): Boolean {
            lastEmitter?.tryOnError(e ?: Exception("error loading $target."))
            return false
        }

        override fun onResourceReady(resource: T?,
                                     model: Any?,
                                     target: Target<T?>?,
                                     dataSource: DataSource?,
                                     isFirstResource: Boolean): Boolean {
            if (resource == null) lastEmitter?.tryOnError(Exception("error loading $target."))
            else lastEmitter?.onSuccess(resource)
            return false
        }
    }

    fun into(target: ImageView): Single<T> {
        return Single.create<T> { emitter ->
            lastEmitter = emitter
            newGlideInstance().listener(listener).into(target)
        }.subscribeOn(AndroidSchedulers.mainThread())
    }
}
```
