### ISSUE TITLE
SVG/Vector Image not loaded from url on oreo(android 8)

### ISSUE THREAD

**Issue by DaminiBansal** [bumptech/glide#2850]
I am using 3.8 version to load svg images from url....Its working fine till android 7 but images are not getting loaded in android 8 and sometimes from 10 only 1 get loaded that too after 10-15 mins.
can anyone help me please..

**Comment by sjudd** [comment]
You probably haven't provided enough information for anyone to help you.

What happens when the images aren't loaded? Is there a stack trace? Are the requests timing out due to poor connectivity?
