### ISSUE TITLE
Is it still possible to add additional parameters for model loader

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#2851]
**Glide Version**: 4.5

**Integration libraries**: none

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

That's a small migration question. In glide 3 I used model loaders like following a lot:
 
    // Display settings
	boolean useIconPack = ...;
	String iconPackName = ...;
	mGlide
		.using(new StreamModelLoader<AppModelItem>() {
			@Override
			public DataFetcher<InputStream> getResourceFetcher(AppModelItem model, int width, int height) {
				return new AppModelItemLoader(model, width, height, useIconPack, iconPackName);
			}
		})
		...
		
There is no way to do this in v4, correct? I must wrap my models into wrappers that hold all "display settings" so that the model loader (which must be registered in the glide modul now which is not optional anymore) can get this data from the model directly, as I can't pass additional parameters to it anymore, correct? Or is there some other way to pass additional parameters to a `ModelLoader`?

**Comment by sjudd** [comment]
[``buildLoadData``][1] is passed an [``Options``][2] object that can be used to provide arbitrary options to a ``ModelLoader`` per request. See http://bumptech.github.io/glide/doc/options.html#component-options.

For an example of how Options are implemented in a ``ModelLoader``, see the timeout option here: https://github.com/bumptech/glide/blob/e9f682f9586a68f9322d978dda4856957167ff0b/library/src/main/java/com/bumptech/glide/load/model/stream/HttpGlideUrlLoader.java#L28


[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/load/model/ModelLoader.html
[2]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/load/Options.html

**Comment by MFlisar** [comment]
Thanks, that helps. Did not realise that I can add this to my `RequestOptions`
