### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Already released

### ISSUE THREAD

**Issue by sunshinehu** [bumptech/glide#2852]
Hello,my glide version is 4.5.0 and I found this issue is already fixed on the last release,but I can also found this problem.

```
01-31 14:18:20.208 31748 31748 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Already released
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:46)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:317)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:612)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at com.bumptech.glide.RequestManager.clear(RequestManager.java:579)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:323)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:64)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at com.bumptech.glide.manager.RequestManagerFragment.onDestroy(RequestManagerFragment.java:197)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at android.app.Fragment.performDestroy(Fragment.java:2586)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2071)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at android.app.FragmentController.dispatchDestroy(FragmentController.java:243)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:7209)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4621)
01-31 14:18:20.208 31748 31748 E AndroidRuntime: 	... 9 more
```

**Comment by sjudd** [comment]
Let me know if you find a way to reproduce it.

**Comment by sunshinehu** [comment]
Yes,I can reproduce it easy in my project by the step follow:
1.in Activity 1 load image
2.jump to Activity2
3.back to Activity1 and qiut Activity1 immediately

We load image like this:
 Glide.with(mActivity)
                .asDrawable()
                .apply(new RequestOptions().placeholder(R.drawable.default)
                .error(R.drawable.event_list_fail))
                .apply(new RequestOptions().set(Option.memory("com.bumptech.glide.request.RequestOptions.Extra"),new Object()))
            .load(
            new MessageImageUrl("xxxxxxxxxxxxxx")
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object model,
                                                Target<Drawable> target, boolean isFirstResource) {
                        boolean hasExtraError = GlideExtraException.hasExtraError(e);
                        if(hasExtraError) {
                            viewHolder.image.setImageResource(R.drawable.ecrypt_image);
                        }
                        viewHolder.imageProgress.setVisibility(View.GONE);
                        return hasExtraError;
                    }

                    @Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target,
                                                   DataSource dataSource, boolean isFirstResource) {
                        viewHolder.imageProgress.setVisibility(View.GONE);
                        return false;
                    }
                })
                .into(new ProgressTarget<Drawable>(alarmLogInfo.getAlarmMessage().getPicUrl(), new DrawableImageViewTarget(viewHolder.image)) {

                    @Override
                    public void onLoadStarted(Drawable placeholder) {
                        super.onLoadStarted(placeholder);
                        viewHolder.imageProgress.setProgress(0);
                        viewHolder.imageProgress.setVisibility(View.VISIBLE);
                    }

                    @Override
                    public void onProgress(String cacheKey, long bytesRead, long totalBytes, boolean isDone, View view) {
                        if (totalBytes > 0) {
                            viewHolder.imageProgress.setProgress((int) (bytesRead * 100 / totalBytes));
                        }
                    }

                });

**Comment by sunshinehu** [comment]
we have found the reason,we use ProgressTarget which is extends to WrappingTarget to show the image will cause the issue,when we replace this target with normal ImageView can solve the problem.

**Comment by sjudd** [comment]
Might you be able to attach a sample app that can be used to reproduce this? Does it reproduce if you keep the Target but remove the RequestListener? What is `WrappingTarget`?

**Comment by sunshinehu** [comment]
Sorry,I means we implement Target interface in Glide

**Comment by sunshinehu** [comment]
our target is like this:



public class WrappingTarget<Z> implements Target<Z> {
    protected final Target<Z> target;

    public WrappingTarget(Target<Z> target) {
        this.target = target;
    }

    @Override
    public void getSize(@NonNull SizeReadyCallback cb) {
        if (target != null)
            target.getSize(cb);
    }

    @Override
    public void removeCallback(@NonNull SizeReadyCallback sizeReadyCallback) {

    }

    @Override
    public void onLoadStarted(@NonNull Drawable placeholder) {
        if (target != null)
            target.onLoadStarted(placeholder);
    }

    @Override
    public void onLoadFailed(@Nullable Drawable drawable) {
        if (target != null)
            target.onLoadFailed(drawable);
    }

    @Override
    public void onResourceReady(@NonNull Z resource, @Nullable Transition<? super Z> transition) {
        if (target != null)
            target.onResourceReady(resource, transition);
    }

    @Override
    public void onLoadCleared(Drawable placeholder) {
        if (target != null) target.onLoadCleared(placeholder);
    }

    private Request request;

    @Override
    public Request getRequest() {
        return request;
    }

    @Override
    public void setRequest(@NonNull Request request) {
        this.request = request;
        if (target != null)
            target.setRequest(request);
    }

    @Override
    public void onStart() {
        if (target != null)
            target.onStart();
    }

    @Override
    public void onStop() {
        if (target != null)
            target.onStop();
    }

    @Override
    public void onDestroy() {
        if (target != null) target.onDestroy();
    }
}

**Comment by sjudd** [comment]
Implement ``removeCallback``? You should at least delegate it.

**Comment by sunshinehu** [comment]
thank you very much,and I will implement it tomorrow and test it

**Comment by sjudd** [comment]
Hope it works, let me know either way.

**Comment by sunshinehu** [comment]
yes,it works,thank you very much~

**Comment by sjudd** [comment]
Great thanks for the follow up!
