### ISSUE TITLE
About use placeholder image

### ISSUE THREAD

**Issue by didixyy** [bumptech/glide#2853]
**Glide Version**:4.2.0

**Integration libraries**:
   implementation "com.github.bumptech.glide:glide:4.2.0"
    annotationProcessor "com.github.bumptech.glide:compiler:4.2.0"

**Device/Android Version**:xiaomi 5.1

**Issue details / Repro steps / Use case background**: 
when i was use glide to load a Transparent image and it's has a placeholder image. i find when the  image first  load finis,it havent catch.the placeholder image aways be here.
like this
![b60f3fbe3ad8ce39cfa44ceb0c925e3c](https://user-images.githubusercontent.com/17633836/35612177-c241fbf4-06a2-11e8-8497-50d89a14ed19.png)
the eye is  transparent image
the blue is placeholder image

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
        GlideApp.with(target.getContext())
                .load(url)
                .transition(normalTransitionOptions)
                .placeholder(loadingRes)
                .error(errorRes)
                .into(target);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by didixyy** [comment]
i test  when i remove transition setting ,it work ,i want to load image can replace the blue placeholder

**Comment by sjudd** [comment]
Sounds like this might help: http://bumptech.github.io/glide/doc/transitions.html#cross-fading-with-placeholders-and-transparent-images
