### ISSUE TITLE
New from picasso

### ISSUE THREAD

**Issue by JoyHong** [bumptech/glide#2854]
Hi, i'm a new from Picasso since we want to load gifs.
But i have a cases to check whether Glide can also work it.
When i click a thumbnail image in recyclerview, the logic is start a new activity to show the hd image, i need the thumbnail drawable or bitmap for hd image's placeholder.
Can you help to check? Tks.

**Comment by sjudd** [comment]
You can use the [``.thumbnail()``][1] API. Use the hd image as the main request and the thumbnail Drawable or Bitmap as the thumbnail request:

```java
Glide.with(context)
  .load(hdUrl)
  .thumbnail(
      Glide.with(context)
          .load(thumbnailUrl))
  .into(imageView);
```

[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/RequestBuilder.html#thumbnail-com.bumptech.glide.RequestBuilder-

**Comment by JoyHong** [comment]
@sjudd Tks
