### ISSUE TITLE
Gradle cant resolve repository

### ISSUE THREAD

**Issue by m1fdm** [bumptech/glide#2855]
**Glide Version 4.5.0**:
**Issue details / Repro steps / Use case background**: 
Please remove glide files from jcentre repository. 
If  user insert jcentre() before mavenCentral(), gradle trying to download 4.5.0 version of library from jcentre and canot do it because there is no 4.5.0 version I guess, but there are some count of previous versions

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
repositories{
jcenter()
google()
mavenCentral()
}

so user must use
repositories{
mavenCentral()
google()
jcenter()
}

```

**Comment by sjudd** [comment]
As far as I know Gradle is perfectly fine failing to find some of your dependencies in one repository if it can find them in another repository. Maybe including the error message would help? 

Consider also asking on the Gradle forums or filing an issue for them.
