### ISSUE TITLE
Updating a requests RequestOptions

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#2858]
**Glide Version**: 4.5

**Integration libraries**: none

**Device/Android Version**: all

**Issue details / Repro steps / Use case background**: 

I would like to have following feature: updating request options.

**Why**

I manage image loading in a simple class, so it's not a big problem here to solve my issue, but I'm preparing requests and hand them on from function to function. In the end I just start the reqeust with a target. So far so good.

Sometimes I want to manipulate the request based on the position where I called it from. In my case, I have one `ModelLoader` that executes requests internally to prepare the images it needs. Therefore I would like to be able to update the options in the request (it's immutable I think, making a copy of them is fine for me here). Or to have a possibility to get the current options, create new ones based on them and set the resulting options to my request.

**Examples**
    
     RequestBuilder request = ...;

    // either this
    RequestOptions ro = request.getRequestOptions();
    ro.useUnlimitedSourceGeneratorsPool(true);

    // or this
    RequestOptions ro = request.getCopyOfRequestOptions();
    ro.useUnlimitedSourceGeneratorsPool(true);
    request.apply(ro);

    // or this
    RequestOptions ro = new ReqeustOptions().useUnlimitedSourceGeneratorsPool(true);
    reqeust.update(ro); // this could merge all set values in ro into the internal RequestOptions

Any reasons to not support this sort of thing in any way?

**Comment by sjudd** [comment]
You can already apply RequestOptions to both RequestBuilders and other RequestOptions. The only caveat is that the apply method may return a new object, which it sounds like you're fine with.

**Comment by MFlisar** [comment]
Here are my final functions every request runs through.

I use a custom target to identify synchronous calls without the need of changing anything in my `ImageManager`. I have already a lot of functions for `Targets`/`ImageView` and I just wanted to reuse them like this.

The functions show what I would like to do - add an option to the options already present in the `RequestBuilder`. I could adjust my functions to just pass through the `RequestOptions` or to adjust them bevorehand (what I currently do anyways), I am just curious if I could solve this in another way in the future.

    private static void loadIcon(RequestBuilder request, ImageView iv) {
        request.listener(new LoggingListener());
        request.into(iv).waitForLayout();
    }

    private static void loadIcon(RequestBuilder<Drawable> request, Target<Drawable> target) {
        request.listener(new LoggingListener());
        // check if I find my InstantTarget => if so, this is an 
        if (target instanceof InstantTarget) {
            FutureTarget t = null;
            try {
                if (t.isNestedCall()) {
                    request.apply(<ORIGINAL options + useUnlimitedSourceGeneratorsPool>);
                }
                t = request.submit(((InstantTarget) target).getWidth(), ((InstantTarget) target).getHeight());
                Drawable d = (Drawable) t.get();
                ((InstantTarget) target).setDrawable(d);
            } catch (InterruptedException e) {
                L.e(e);
            } catch (ExecutionException e) {
                L.e(e);
            } finally {
                if (t != null) {
                    clear(t);
                }
            }
        } else {
            request.into(target);
        }
    }

**Comment by sjudd** [comment]
``apply``  doesn't replace the previous set of options, it just applies whatever new options you specified. It already works the way you want it to.

**Comment by MFlisar** [comment]
Thanks, did not realise this
