### ISSUE TITLE
GlideModule annotation not provided in compile dependency for 4.6.0

### ISSUE THREAD

**Issue by CodingDoug** [bumptech/glide#2863]
It's simply not there, but it used to be in 4.5.0.  In fact, all four transitive dependencies found in the pom for 4.5.0 are missing in 4.6.0.

**Comment by funset** [comment]
yeah,,does your fixed?

**Comment by sjudd** [comment]
Ugh yeah sorry about that, I'll upload 4.6.1 with a fix when I verify it.

It looks like the maven plugin only includes dependencies based on the release configuration, so when we removed it dependencies are no longer automatically added.
