### ISSUE TITLE
Glide Load for Resource Drawables Not working

### ISSUE THREAD

**Issue by 1nullpointer** [bumptech/glide#2867]
Glide doesn't load resources dynamically . I have a vector xml in drawable. Trying to pass the resource id and load it . But it fails .
The Placeholder Resource loading works perfectly fine.

  @BindingAdapter("imgDrawable")
    public void bindImageDrawable(ImageView imageView, int resourceId) {

        Glide.with(fragment).load(resourceId).placeholder(R.drawable.xyz).into(imageView);
    }

**Turnaround Approach :** 
Currently , as a fix am just using the resourceId in both load as well as placeholder which kind of resolved the issue(make loading dynamic)

@BindingAdapter("imgDrawable")
    public void bindImageDrawable(ImageView imageView, int resourceId) {

        Glide.with(fragment).load(resourceId).placeholder(resourceId).into(imageView);
    }

**Glide Version:** 3.8.0

**Comment by sjudd** [comment]
Vector drawables from xml should decode in v4. Let me know if you can reproduce on a newer version.
