### ISSUE TITLE
OutOfMemoryError in a RecyclerView

### ISSUE THREAD

**Issue by traifdevelopment** [bumptech/glide#2868]
Hi,

I having this error with i try to load Glide images into a large recycler view with CircleImageView:

 java.lang.OutOfMemoryError: Failed to allocate a 74649612 byte allocation with 16777216 free bytes and 59MB until OOM

  Glide.with(context).load(url).placeholder(R.drawable.no_image).into(viewHolder.image);

I don't know how to solve this, i tried with "decodeSampledBitmap" but i don't know how to get a Resource from Glide.

Can u help me please?

Thank u so much.

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors
