### ISSUE TITLE
Updating to v4.6.1 - `onResourceReady` not available for `SimpleTarget`

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bumptech/glide#2871]
I used this simple code to load a bitmap into center crop:

                    Glide.with(...).asBitmap().load(...)).apply(RequestOptions.centerCropTransform().skipMemoryCache(true).diskCacheStrategy(DiskCacheStrategy.NONE))
                            .into<SimpleTarget<Bitmap>>(object : SimpleTarget<Bitmap>(width, height) {
                                override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>) {
                                   ....
                                }

                                override fun onLoadFailed(errorDrawable: Drawable?) {
                                    super.onLoadFailed(errorDrawable)
                                }
                            })

For some reason, now it says it's not available.
If it's not, what's the alternative? Why did it happen? Is there a better way?
I've tried to search here and in the docs, but I can't find it.
Isn't there a "what's new" section, or something?
Are there other changes I should know about?

**Comment by AndroidDeveloperLB** [comment]
@sjudd I don't understand then why the IDE complains that it doesn't exist.
See image of when using v 4.4.0:

![image](https://user-images.githubusercontent.com/5357526/35821643-5fb80ea6-0ab2-11e8-933d-8ae37a64438c.png)

and 4.6.1 :

![image](https://user-images.githubusercontent.com/5357526/35821728-a676762a-0ab2-11e8-969f-802459a9038a.png)

**Comment by AndroidDeveloperLB** [comment]
Here's the error:

![image](https://user-images.githubusercontent.com/5357526/35822637-94d00780-0ab5-11e8-8d86-a6f896adcc7f.png)

**Comment by AndroidDeveloperLB** [comment]
What?
Why?
This issue still exists!

Anyway, I've fixed it by having a slightly different function there, as it seems it has changed:

    override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?)

**Comment by sjudd** [comment]
Maybe because of `@Nullable`? Either way the function exists.

If you copied some piece of Kotlin sample code that needs to be updated, let me know. I don't think we actually have any Kotlin sample code in Glide's wiki or websites though.

**Comment by AndroidDeveloperLB** [comment]
@sjudd It was added recently?
If so, that could be the cause to it.
Kotlin is currently a valid way to use all kinds of libraries on Android. It also becomes more and more popular. Should make no difference if I use it instead of Java.
I still like Java. Just use Kotlin :)

**Comment by sjudd** [comment]
Nope, it's been around forever. The only recent change was probably adding `@Nullable` to the `transition` param. It looks like that's what you changed to fix it?

My point is not that Kotlin isn't valid or that we don't care about Kotlin. My point was that we don't have Kotlin sample code, so there's not much we can do beyond pointing you at the javadoc for the current version of the method? Let me know if you think there's some place that we could update that would clarify why your first implementation of the method didn't work.

**Comment by AndroidDeveloperLB** [comment]
@sjudd I meant if it was added in this context. 
I already know about nullable annotation... :)
Seems to me that this was added, because adding the "?" in Kotlin (means it's nullable) has fixed it.

Anyway thank you.
