### ISSUE TITLE
TGA support request

### ISSUE THREAD

**Issue by jsmienk** [bumptech/glide#2876]
I tried to load a url to a .tga image file and Glide could not load it.
Will this be added in the future or is this bug or did I do something wrong?
Using version 4.6.1.

**Comment by sjudd** [comment]
I don't believe .tga is a format that Android supports and Glide doesn't include any custom decoder for it. No plans to support that format in Glide.

If you have your own .tga decoder you can implement the [``ResourceDecoder``][1] interface that uses your decoder and [register][2] it with Glide to support the format in your application.

[1]: http://bumptech.github.io/glide/javadocs/460/com/bumptech/glide/load/ResourceDecoder.html
[2]: http://bumptech.github.io/glide/doc/configuration.html#registering-components
