### ISSUE TITLE
How can I load a Bitmap synchronously with Glide?

### ISSUE THREAD

**Issue by xrealm** [bumptech/glide#2877]
hi, I want to get a bitmap from main thread.
but I can't find a solution to this problem.

```
public Bitmap getBitmap(Context context,  int resourceId) {
        return Glide.with(context).load(resourceId)
                        .asBitmap()
                        .into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                        .get();
}

Bitmap bitmap = getBitmap(context, R.drawable.ic_launcher);
if (bitmap != null) {
       canvas.drawBitmap(bitmap)...
}

```
thanks.

**Comment by sjudd** [comment]
You can't (and shouldn't). Loading a Bitmap like this synchronously will block the main thread and add jank. 

Instead load the Bitmap asynchonously and draw some kind of placeholder while it's loading?

**Comment by xrealm** [comment]
I can't, I just want to get a local bitmap with glide (like R.mipmap.ic_launcher, not placeholder), because it can prevent out of memory. This way does not block the main thread. it's safe.
I need the bitmap for my scene.
Universal-Image-Loader：
```
Bitmap bitmap = ImageLoader.getInstance().loadImageSync("drawable://" + R.drawable.ic_launcher);
```
emmmm.....

**Comment by tjouin** [comment]
I got the same issue, I'am want to get bitmap synchronously (Because i'am already in a different Thread)

.get() doesn't exist anymore?

**Comment by sjudd** [comment]
If you're on a background thread, see http://bumptech.github.io/glide/doc/getting-started.html#background-threads

**Comment by tjouin** [comment]
Just seen it sorry :/
