### ISSUE TITLE
glide| 3.6.0 unable load local img by  using custom StreamModelLoader

### ISSUE THREAD

**Issue by yuqiyich** [bumptech/glide#2880]
when i  load from local imgfile by imagePath ,i get this error below
![image](https://user-images.githubusercontent.com/7644407/35913266-0bc310be-0c3a-11e8-835b-77c2bfc1455a.png)
and the use code is this:
                     
              Glide.with(context).using(new ProgressModelLoader((new ProgressHandler(activity, lc))))
                                .load(url).asBitmap().diskCacheStrategy(canCache?
                                                                          DiskCacheStrategy.ALL:DiskCacheStrategy.NONE)
                                .into(new SimpleTarget<Bitmap>()
                                {

                                  @Override
                                  public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> 
                                             glideAnimation) {
                                      lc.onResourceReady(resource);
                                  }

                                  @Override
                                  public void onLoadFailed(Exception e, Drawable errorDrawable) {
                                      super.onLoadFailed(e, errorDrawable);//and get error in this line;
                                      lc.onLoadFailed(errorDrawable);
                                  }

                                  @Override
                                  public void onStart() {
                                      super.onStart();
                                      lc.onLoadStarted(null);
                                  }
                                }
                        );'

and  pic is existed,why i get this error?pls help me .

**Comment by Tolriq** [comment]
Use file:// before to actually use urls and not random string that Glide can't guess what it represent :)

**Comment by sjudd** [comment]
It would also help if you provide the full stack trace of the exception you're seeing.

**Comment by yuqiyich** [comment]
i use   file:// before to actually use urls  ，but i get same error above，and final i  find that reason why i get this error，if u use Glide with StreamModelLoader ，u can‘t load  local image file， otherwise u will get the error above，thks all
![image](https://user-images.githubusercontent.com/7644407/35963115-ad0639ec-0cee-11e8-9d3b-cb49e87b76d2.png)
