### ISSUE TITLE
[Feature Removal] - Deprecate Fragments

### ISSUE THREAD

**Issue by jaredsburrows** [bumptech/glide#2883]
Based on @JakeWharton's post: https://github.com/android/android-ktx/pull/161#issuecomment-363270555.

Usages are here: https://github.com/bumptech/glide/search?utf8=%E2%9C%93&q=%22android.app.Fragment%22&type=

I believe you should add `@Deprecated` then in a next major version, prune them. What do you think @TWiStErRob?

**Comment by sjudd** [comment]
I don't think there's any rush here. It may take a while for users to migrate to the support library fragments and adding deprecation warnings to their existing deprecation warnings probably isn't super valuable? 

I wouldn't be opposed to a pull request.

**Comment by jaredsburrows** [comment]
Thanks. Here is the PR: https://github.com/bumptech/glide/pull/2886.

**Comment by jaredsburrows** [comment]
@sjudd Are we still migrating this to support or Android X Fragments?
