### ISSUE TITLE
Request Listener Not Called

### ISSUE THREAD

**Issue by mikemike396** [bumptech/glide#2884]
I am trying to listen when the download is complete. Neither call back methods are fired. I put a break point on the Glide line and it makes it there but never goes into the onFail or onReady. Any thoughts?

MediaURL is a remote URL to AWS S3. It works fine on the previous screen. 

            PhotoView photoView = (PhotoView) rootView.findViewById(R.id.imageViewer);
            final PhotoViewAttacher attacher = new PhotoViewAttacher(photoView);
     Glide.with(getContext()).load(mediaURL).listener(new RequestListener<Drawable>() {
            @Override
            public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                Log.wtf("Glide", "onResourceReady");
                System.out.println("test");
                return false;
            }

            @Override
            public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                Log.wtf("Glide", "onResourceReady");
                System.out.println("test");
                attacher.update();
                return false;
            }
        }).into(photoView);

Version:
    implementation ("com.github.bumptech.glide:glide:4.6.1") {
        exclude group: "com.android.support"
    }

**Comment by sjudd** [comment]
Take a look at http://bumptech.github.io/glide/doc/debugging.html#missing-images-and-local-logs, I'd guess the request is never starting, probably because the size is never resolved to a useful value.

**Comment by mikemike396** [comment]
Thank you so much!

Changed my view to match content and it works perfect now. Deff a size issue. It was match parent before

    <com.github.chrisbanes.photoview.PhotoView
        android:id="@+id/imageViewer"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
