### ISSUE TITLE
Glide loses the initialized Registry

### ISSUE THREAD

**Issue by wdkcjnwdwkldn** [bumptech/glide#2885]
**Glide version**: 4.6.1

**Issue details**: 
I configure `Glide` with `GlideBuilder`. WITHOUT `GlideModule`.
But `MyModelLoaderFactory ` not working, because `Glide` loses the initialized `Registry`.

**MyModelLoaderFactory not working**:
```java
val glide = GlideBuilder()
    ...
    .build(context)
glide.registry.append(MyModel::class.java, InputStream::class.java, MyModelLoaderFactory())
return glide
```
**MyModelLoaderFactory works**:
```java
val glide0 = GlideBuilder()
    ...
    .build(context)
val glide1 = Glide.get(context) // glide1 != glide0 // I want to use original instance
glide1.registry.append(MyModel::class.java, InputStream::class.java, MyModelLoaderFactory())
return glide1
```
**MyModelLoaderFactory works (deprecated)**:
```java
val glide = GlideBuilder()
    ...
    .build(context)
Glide.init(glide) // deprecated
glide.registry.append(MyModel::class.java, InputStream::class.java, MyModelLoaderFactory())
return glide
```

`GlideBuilder` must be returns initialized `Glide`.

**Comment by sjudd** [comment]
``GlideBuilder.build`` shouldn't be public and you shouldn't use it. There's no supported way to initialize Glide outside of modules.

**Comment by wdkcjnwdwkldn** [comment]
Why not?
Annotation processing generates excess code and spends build time. It's a bad way for android library.

Ok. I'll use deprecated `init` method, version 3.8.0 or library fork.
Thanks.

**Comment by sjudd** [comment]
This has been covered before in a few ways, but here's a summary: 

1. It's not possible to safely initialize Glide outside of the library unless you do so eagerly in something like the Application object (and even then that's not entirely safe), which wastes resources. 
2. Given that initializing has to be done inside Glide to be safe, there's a limited set of mechanisms by which Glide is able to discover dependencies, including manifest parsing (slow and error prone) and annotation processing.
3. The class overhead is small compared the size of the library as a whole.

Most of the overhead that annotation processing adds is at build time and that should be relatively easy to solve by just moving your GlideModule into a submodule in your project.

If you have any specific information you'd like to share about the overhead you think this process adds, please do consider providing it. There's always room for improvement.

**Comment by Tolriq** [comment]
@sjudd just saw this and currently I have not found a way to pass parameters to the module to for example pass custom cache directory, custom logger instance or things like that.

This makes moving to a sub module very complex, meaning annotation processor on main app, meaning no incremental build, meaning tons of time lost :)

Having a way to pass arguments or a way to disable annotation processor would be really nice improvement.
