### ISSUE TITLE
Foreground Gravity to Left

### ISSUE THREAD

**Issue by sinhpn92** [bumptech/glide#2893]
I have used Glide version `4.6.1`. My issue when load image into `ImageView` with `match_parent` width. The foreground image has been center align of `ImageView`. How can i align foreground image to left or right?

XML: 
```
<RelativeLayout
        android:id="@+id/layoutImage"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:layout_marginEnd="10dp"
        android:layout_marginLeft="10dp"
        android:layout_marginRight="10dp"
        android:layout_marginStart="10dp"
        android:layout_toEndOf="@+id/button1"
        android:layout_toLeftOf="@+id/label1"
        android:layout_toRightOf="@+id/button1"
        android:layout_toStartOf="@+id/labe1">

        <android.support.v7.widget.AppCompatImageView
            android:id="@+id/imageView"
            android:layout_width="match_parent"
            android:layout_height="35dp"
            android:adjustViewBounds="true"/>

    </RelativeLayout>
```

Programmatically:
    
`GlideRequests request = ...`
 ```
request.load(url)
                .skipMemoryCache(false)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .transition(DrawableTransitionOptions.withCrossFade())
                .into(imv);
```

**Comment by sjudd** [comment]
I don't think this is related to Glide, you can configure the layout parameters of the image view or its parent however you'd like, include gravity.

**Comment by sinhpn92** [comment]
@sjudd Oh I have set width of `ImageView` with `wrap_content` to gravity image in `ReleativeLayout`. But, When Item have scroll down and up again, the resource reuse feature have resize image. So foregroundImage in `ImageView` has changed. 
So I have set width to 'match_parent`. But in this, foregroundImage have aligned center.

**Comment by sinhpn92** [comment]
Oh I'm finding the solution for resolve it but not found...
