### ISSUE TITLE
Twice onResourceReady callback occur

### ISSUE THREAD

**Issue by huzhenjie** [bumptech/glide#2895]
Why after I added `.thumbnail(0.1f)` , then twice `onResourceReady` callback.

And I don\`t known which one is call by `thumbnail`

```
glideRequests.asBitmap()
    .load(uri)
    .thumbnail(0.1f)
    .into(new SimpleTarget<Bitmap>() {
        @Override
        public void onResourceReady (
            Bitmap resource, Transition<? super Bitmap> transition) {
            // twice callback here
        }
    });
```

My Glide version is `4.3.0`

**Comment by sjudd** [comment]
``thumbnail()`` loads a second image so your ``Target`` gets two callbacks. 

Also be wary or avoid using ``SimpleTarget``.
