### ISSUE TITLE
Glide 4.6.1 does not know getHeaders in BaseGlideUrlLoader<String>  implementation

### ISSUE THREAD

**Issue by MohammadFahimi** [bumptech/glide#2899]
I want to configure glide 4.6 to add header and OkHttpClient . I dont want to add in every request. I put it on glide configuration class.

I have
` class HeaderLoader extends BaseGlideUrlLoader<String> {}`
with glide doc and so many tutorial on the web  it must have method 
```
@Override
    protected Headers getHeaders(String model, int width, int height) {
        return REQUEST_HEADERS;
    }
```
```

 @Override
    protected String getUrl(String model, int width, int height) {
        return model;
    }

```
but when I override this method is say its not override from supper class.

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/javadocs/460/com/bumptech/glide/load/model/stream/BaseGlideUrlLoader.html#getHeaders-Model-int-int-com.bumptech.glide.load.Options-

**Comment by MohammadFahimi** [comment]
I found how to add these two method. but these method never call. just constructor was called.
