### ISSUE TITLE
Can we show gif image in a notifcation using NotificationTarget?

### ISSUE THREAD

**Issue by fh127** [bumptech/glide#2900]
Can we show gif image in a notifcation using NotificationTarget? like this:

```
GlideApp.with(getApplicationContext())
                        .asGif()
                        .load(imgUrl)
                        .into(new NotificationTarget(
                                context,
                                R.id.remoteview_notification_icon,
                                remoteViews,
                                notification,
                                NOTIFICATION_CODE));
```
Currently, NotificationTarger isn't supported GifDrawable.

**Comment by sjudd** [comment]
It doesn't look like `RemoteViews` supports setting a Drawable? https://developer.android.com/reference/android/widget/RemoteViews.html. 

If there's a way to set an animated drawable in a notification in general, you can probably find a way to do it with a custom `Target` in Glide.

**Comment by azimsidd** [comment]
Please answer this question. How to show the gif in custom notification
