### ISSUE TITLE
How to extract the last frame from Gif 

### ISSUE THREAD

**Issue by vxhviet** [bumptech/glide#2906]
**Glide Version**: 3.8.0

**Integration libraries**: No

**Device/Android Version**: Nexus 5

**Issue details / Repro steps / Use case background**: 
I would like to retrieve the last frame of a GIF loaded from Glide. The GIF represent a zooming animation and as such the first frame basically contain nothing while the last frame will contain the full image. 
 `GifDrawable ` only provide [`getFirstFrame()`](https://bumptech.github.io/glide/javadocs/380/com/bumptech/glide/load/resource/gif/GifDrawable.html#getFirstFrame()) method. 

My wild guess is that GIF is similar to video in a way that the first frame is the key frame and any sub-sequential frames are derived from it. Thus, in order to get the last frame we need to decode all previous frames which is not an issue as I download the whole GIF anyway.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

Currently I'm getting the first frame with this.

```java
if (mDummyTarget == null) {
            mDummyTarget = new SimpleTarget<Bitmap>() {
                @Override
                public void onResourceReady(Bitmap bitmap, GlideAnimation glideAnimation) {
                    //BitmapDrawable bm = new BitmapDrawable(getResources(), bitmap);
                    //mStickerView.addSticker(new DrawableSticker(bm));
                }
            };

}

Glide.with(this)
		.load(animatedStickerSetData.getFile1Url())
		.asBitmap()
		.diskCacheStrategy(DiskCacheStrategy.SOURCE)
		.into(mDummyTarget);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
You can write your own decoder that just decodes the last frame. It will have to decode all of the intermediate frames. 

See http://bumptech.github.io/glide/javadocs/380/com/bumptech/glide/load/ResourceDecoder.html and http://bumptech.github.io/glide/javadocs/380/com/bumptech/glide/gifdecoder/GifDecoder.html for the available APIs.
