### ISSUE TITLE
"centerCrop()" work after scoll and back to same View.

### ISSUE THREAD

**Issue by pathikdevani** [bumptech/glide#291]
i am using android list view and this is my code.....

when image load from server first time centerCrop not work then i am scroll list view then back same view then centerCrop work. but not work for all time. when scrolling fast and back to view then not work centerCrop().

``` java
RequestManager manager = Glide.with(MainActivity.cf.context);
DrawableTypeRequest<String> drawable = manager.load("http://192.168.0.108/vavidhya/"+id+".png");
drawable.centerCrop();
drawable.placeholder(R.drawable.event_list_item_back);
drawable.into(backImage);
```

![screenshot_2014-12-13-15-56-41](https://cloud.githubusercontent.com/assets/5463435/5423404/e4fd9560-82e1-11e4-8d12-9986f4392c81.png)
![screenshot_2014-12-13-15-56-53](https://cloud.githubusercontent.com/assets/5463435/5423405/e5cebbc2-82e1-11e4-9818-ba24f4a514e3.png)

**Comment by Kev1000000** [comment]
I am actually experiencing this as well.  When the images first load, they are not cropped correctly, but after a scroll off-screen and then back on screen, everything works as intended.

**Comment by sjudd** [comment]
Are you using wrap_content and match_parent? If so maybe take a look at #135?

**Comment by Kev1000000** [comment]
I wasn't using match_parent.  Added that, and it worked great =)
