### ISSUE TITLE
Question is it correct: scaletype XY when placeholder, scale CENTER_CROP when image

### ISSUE THREAD

**Issue by sephuxeresh** [bumptech/glide#2910]
I would like to use placeholder when I fail load img with scaletype FIT_XY because my placeholder is .9.png
In case where I load img correctly I would like to use scaletype CENTER_CROP.
Below code is working but is it correct (especially line in onLoadFailed where I set drawable for placeholder)?

```
Glide
    .with(context)
    .load(url)
    .listener(new RequestListener<Drawable>() {
        @Override
        public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
            ImageView view = ((ImageViewTarget<?>) target).getView();
            view.setScaleType(ImageView.ScaleType.FIT_XY);
            Glide.with(coreInstance).load(model).apply(new RequestOptions().placeholder(R.drawable.blank_photo)).into(target);
            return false;
        }

        @Override
        public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
            ImageView view = ((ImageViewTarget<?>) target).getView();
            view.setScaleType(ImageView.ScaleType.CENTER_CROP);
            return false;
        }
    })
    .into(imageView);
```

I am using Glide library `compile("com.github.bumptech.glide:glide:4.0.0")`

**Comment by sjudd** [comment]
You probably should use the latest version of Glide, not `4.0.0`. 

It's not safe to start a new load into the same Target in ``onLoadFailed``. If the ``target`` is not `imageView` then it's ok, though a little odd. If they're the same, use http://bumptech.github.io/glide/javadocs/460/com/bumptech/glide/RequestBuilder.html#error-com.bumptech.glide.RequestBuilder-

Changing the scale type is ok, but keep in mind that Glide will set it's `Transformation` based on the scale type if you don't specify a `Transformation` yourself. You might want to specify `fitCenter()` or something to avoid using the default scale type.
