### ISSUE TITLE
Warning:Note: [1] Wrote GeneratedAppGlideModule with:

### ISSUE THREAD

**Issue by JaehoJu** [bumptech/glide#2911]
I got build warning just I updated kotlin plugin version. (before 1.2.10)

classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.21'

```
Warning:Note: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule]
```

So I update glide version too. (before 4.3.1)

implementation 'com.github.bumptech.glide:okhttp3-integration:4.6.1'
implementation 'com.github.bumptech.glide:glide:4.6.1'

But warning continued.

**Comment by technoir3** [comment]
Noticed it too. Shouldn't probably be a warning.

**Comment by sjudd** [comment]
It's actually using `Diagnostic.Kind.NOTE`: https://github.com/bumptech/glide/blob/97d130d338349220cc8158141bbae1dfda496efe/annotation/compiler/src/main/java/com/bumptech/glide/annotation/compiler/ProcessorUtil.java#L249

It's called here: https://github.com/bumptech/glide/blob/97d130d338349220cc8158141bbae1dfda496efe/annotation/compiler/src/main/java/com/bumptech/glide/annotation/compiler/AppModuleProcessor.java#L112

**Comment by technoir3** [comment]
Ah, sorry. So it's actually AGP and kapt which output the message as warning. I found a commit that changed it to warning in kapt https://github.com/JetBrains/kotlin/commit/d89143e641798e7f87683c305a545b10c277d68d.
There is also a PR aimed to revert that change https://github.com/JetBrains/kotlin/pull/1524.

**Comment by rtsdemo123** [comment]
I'm using those dependencies 

> 
>     implementation 'com.github.bumptech.glide:glide:4.11.0'
>     kapt 'com.github.bumptech.glide:compiler:4.11.0'
>     implementation "com.github.bumptech.glide:okhttp3-integration:4.11.0"

and I'm still getting this error, is there a fix for this issue?

**Comment by iamarjun** [comment]
> I'm using those dependencies
> 
> > ```
> > implementation 'com.github.bumptech.glide:glide:4.11.0'
> > kapt 'com.github.bumptech.glide:compiler:4.11.0'
> > implementation "com.github.bumptech.glide:okhttp3-integration:4.11.0"
> > ```
> 
> and I'm still getting this error, is there a fix for this issue?

+1

**Comment by strajky5** [comment]
> I'm using those dependencies
> 
> > ```
> > implementation 'com.github.bumptech.glide:glide:4.11.0'
> > kapt 'com.github.bumptech.glide:compiler:4.11.0'
> > implementation "com.github.bumptech.glide:okhttp3-integration:4.11.0"
> > ```
> 
> and I'm still getting this error, is there a fix for this issue?

+1

**Comment by kuhuk** [comment]
> > I'm using those dependencies
> > > ```
> > > implementation 'com.github.bumptech.glide:glide:4.11.0'
> > > kapt 'com.github.bumptech.glide:compiler:4.11.0'
> > > implementation "com.github.bumptech.glide:okhttp3-integration:4.11.0"
> > > ```
> > 
> > 
> > and I'm still getting this error, is there a fix for this issue?
> 
> +1

+1

**Comment by aliaksandr-chaulytka** [comment]
+1

**Comment by trupizzza** [comment]
+1

**Comment by rid-hrant** [comment]
+1

**Comment by rid-hrant** [comment]
> Task :app:compileDebugJavaWithJavac
Note: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule]
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by ShankarKakumani** [comment]
any solutions to this please?

**Comment by vvinogra** [comment]
+1

**Comment by whck6** [comment]
+1

**Comment by AlexSuvorov2k** [comment]
+1

**Comment by VelocityPulse** [comment]
+1
