### ISSUE TITLE
How can I access singleRequest model?

### ISSUE THREAD

**Issue by gelbertgel** [bumptech/glide#2915]
I can load image path to imageView using Glide in this code:

    GlideApp.with(context)
                    .load(imagePath)
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .transition(withCrossFade())
                    .into(imageView);

I do not want to load previously registered same path or bitmap from imageView. So I find this solution `imageView.getTag();` and this result is singleRequest has loaded data (imagePath or bitmap) from singleRequest model.

But I can't access singleRequest `model` field, it is a private. How can I take singleRequest `model `field? Please help me.
Glide version : 4.6.1

**Comment by sjudd** [comment]
You can't. 

There's already some attempt to avoid restarting requests if they're identical when it's safe to do so, so you shouldn't need to do this.

**Comment by gelbertgel** [comment]
Ok I can do it by using setTag and getTag methods. Thanks
