### ISSUE TITLE
Glide diminishes the thin lines in the image

### ISSUE THREAD

**Issue by missverma** [bumptech/glide#2916]
**Glide Version**: 4.6.1

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(getContext())
                .asBitmap()
                .load(filePath)
                .transform(GlideUtils.CenterFill.instance())
                .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                .into(nriv);
```

![ezgif com-gif-maker](https://user-images.githubusercontent.com/19709716/36663784-b2d4b7a4-1b08-11e8-85ca-95e7c0826062.gif)
View the 4th grid on second page. How white zig-zag lines diminishes.

**Comment by sjudd** [comment]
I'm not sure, are you referring to an animation? Or the image quality?

**Comment by missverma** [comment]
The unwanted animation, which is blurring the fine white lines.

**Comment by sjudd** [comment]
Glide doesn't v4 apply a default transition. Do you see that in the actual app, or is that just an artifact of the screen recording? If it's in the actual app, I'm not sure what to tell you, but I don't think the issue is Glide related.

**Comment by missverma** [comment]
This is happening in the actual app. The possible reason I am assuming is that the image is square (say 200x200), but for the shown grid it's been stretched to 300x200. I guess stretching of image is resulting in blurring. But why is it doing so with animation !

**Comment by sjudd** [comment]
Sorry I missed this, but I'm not sure what to tell you. Glide doesn't do anything special here, it just calls setImageDrawable. If you're using a Transition in addition to what you've specified above, you could try removing it. Glide doesn't apply a Transition by default.
