### ISSUE TITLE
Image supplied by Glide is larger than the original image resulting in a "trying to draw too large" exception

### ISSUE THREAD

**Issue by Saketme** [bumptech/glide#2929]
**Glide Version**: 4.5.0
**Integration libraries**: OkHttp3
**Device/Android Version**: Emulator, Nougat

**Issue details / Repro steps / Use case background**: 
I'm facing a very strange issue and I have no idea how to debug this. Some images loaded by Glide have dimensions much larger than the original image and are resulting in `RuntimeException: Failed to draw image: Canvas: trying to draw too large(118103056bytes) bitmap` errors.

Image URL: https://i.imgur.com/VPp3f0q.jpg

The strange part is that the same image is loading fine in another screen and I'm unable to figure out why. When VERBOSE logging is enabled, I see this log:

`D/Glide: Finished loading BitmapDrawable from DATA_DISK_CACHE for https://i.imgur.com/VPp3f0q.jpg with size [1080x1920] in 244.714 ms`

But the when the image is received in my `RequestListener`, the dimensions become: `15362,1922`.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with((Fragment) this)
    .load("https://i.imgur.com/VPp3f0q.jpg")
    .listener(new SimpleRequestListener<Drawable>() {
      @Override
      public void onResourceReady(Drawable resource) {
        Timber.i("Image: %s,%s", resource.getMinimumWidth(), resource.getMinimumHeight());
      }
    })
    .apply(new RequestOptions().skipMemoryCache(true).diskCacheStrategy(DiskCacheStrategy.NONE))
    .into(imageView);
```

```java
@GlideModule
@Excludes({ OkHttpLibraryGlideModule.class })
public class DankAppGlideModule extends AppGlideModule {

  @Override
  public boolean isManifestParsingEnabled() {
    return false;
  }

  @Override
  public void applyOptions(Context context, GlideBuilder builder) {
    builder.setLogLevel(Log.VERBOSE);
  }
}
```

I tried creating a sample project, but I'm unable to reproduce the error either. Is there any way I can debug this problem more?

**Layout XML**:
```xml
<ImageView
  android:id="@+id/..."
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:layout_gravity="center"
  tools:background="@color/blue_gray_700" />
```

**Comment by Saketme** [comment]
Update: okay I made _some_ progress. Loading the same image synchronously seems to work:

```java
Glide.with(imageView)
    .load(imageUrl)
    .apply(new RequestOptions().skipMemoryCache(true).diskCacheStrategy(DiskCacheStrategy.NONE))
    .submit()
    .get();
```

**Comment by Saketme** [comment]
Update 2: Wow something is really up. I'm receiving different dimensions for all my images. Using `submit().get()` works fine. In both the cases, the ImageView's dimensions are set to `MATCH_PARENT`.

**Comment by sjudd** [comment]
This isn't loading anything into any view, it just returns the original size image
```
Glide.with(imageView)
    .load(imageUrl)
    .apply(new RequestOptions().skipMemoryCache(true).diskCacheStrategy(DiskCacheStrategy.NONE))
    .submit()
    .get();
```

The logs you mention will only log if you load from the disk cache, which you seem to be excluding in your code sample above.

If you're able to reproduce this, please attach a [failing test case][1] or a sample app that reproduces the issue. 

[1]: http://bumptech.github.io/glide/tut/failing-test-cases.html

**Comment by Saketme** [comment]
>The logs you mention will only log if you load from the disk cache, which you seem to be excluding in your code sample above.
Sorry, I had enabled disk cache for printing logs.

>If you're able to reproduce this, please attach a failing test case or a sample app that reproduces the issue.
I'm really sorry for creating an issue without providing a reproducible usecase. I'm unfortunately unable to reproduce this on a different project so It seems like something else in the existing system is affecting Glide. I'm not even applying any transformers. Is there any way for me to know where and why an image is getting resized by Glide?

**Comment by sjudd** [comment]
Sorry I missed your last comment. 

You can enable some pretty detailed logs in [`Downsampler`][1] with `adb shell setprop log.tag.Downsampler VERBOSE`. That will show you the math being done to calculate the scaling for every image.

[1]: https://github.com/bumptech/glide/blob/7427a493fa23d95f5e00853f78c40c43a50b8a56/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java

**Comment by Saketme** [comment]
Got it. I will try this out and report back. Also, it's incredibly impressive how responsive you and your team are here. Thank you for doing this.

**Comment by NiaNingXue** [comment]
I have the same issue. Have you solved it?@Saketme

**Comment by Saketme** [comment]
@NiaNingXue I couldn't get a chance to fix the actual problem, but I added a downsampling strategy in the meanwhile. You can try @sjudd's suggestion to enable logging and see if you find something :)

**Comment by NiaNingXue** [comment]
@Saketme I cann`t reproduce  this currently. I  add the override size RequestOptions to wait if it will ocur from Fabric

**Comment by min0623** [comment]
Hi, same thing happens to me when I use image with large width-height ratio. Any updates?
@saket @sjudd 
Following is my code.

`glide.asBitmap().load(banner.imageUrl)
                    .into(object : BitmapImageViewTarget(img_banner) {
                        override fun onLoadFailed(errorDrawable: Drawable?) {
                            super.onLoadFailed(errorDrawable)
                            visibility = View.GONE
                        }

                        override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                            super.onResourceReady(resource, transition)
                            onBindListener?.onBind()
                            view_border.visibility = View.VISIBLE
                        }
                    })`

**Comment by min0623** [comment]
Hi, I'm getting the same issue. My image is only 6KB, but when I load it like below, it becomes bitmap of 3GB. Any updates? @saket @sjudd 

`glide.asBitmap().load(banner.imageUrl).into(object : BitmapImageViewTarget(img_banner))`

**Comment by sjudd** [comment]
@min0623 this issue is about dimensions that are changing, which is generally unexpected.

The byte size of a decompressed Bitmap will always be substantially larger than the compressed size of the same image on disk. Depending on how well the image compresses the difference can be huge. Typically it's simply large. Bitmaps use a fixed number of bytes per pixel depending on their configuration. It's not necessarily surprising that a 6kb image uses much more memory as a Bitmap.  

If you're seeing unexpected dimensions when you load images (ie a 1024x1024 image becomes a 2048x2048 image) then let me know.

**Comment by min0623** [comment]
@sjudd Thanks for your comment. Is there any way I can prevent bitmap from becoming so large? (e.g. resizing after resource loaded and reload)

**Comment by sjudd** [comment]
If you're trying to reduce the in memory size of the image, see http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors. 

Typically using a reasonable downsample strategy (often the default), a reasonable size, and a non-upscaling transformation is sufficient.

**Comment by andvalsol** [comment]
has anyone encountered a solution for this problem?
