### ISSUE TITLE
Load Encrypted Image from Server Using Glide V4.x

### ISSUE THREAD

**Issue by nirvana2017** [bumptech/glide#2934]
**Glide Version**:
4.6.1

**Integration libraries**:
No

**Device/Android Version**:
HUAWEI MATE 7/6.0.0

**Issue details / Repro steps / Use case background**: 
 I tried to migrate my project from Glide version 3.7.0 to 4.6.1, and I'm facing some issues.I load image from server,but the images might be encrypted. The keys might be different. I use imageDecoder with version 3.7.0, as follows:
```java
Glide.with(context).load(url).asBitmap().placeholder(R.drawable.bg_touming).diskCacheStrategy(DiskCacheStrategy.NONE).error(R.drawable.bg_touming)
					.imageDecoder(new ResourceDecoder<InputStream, Bitmap>() {
						@Override
						public Resource<Bitmap> decode(InputStream source, int width, int height) throws IOException {
							if (!isEncrypt(url)) {
								return new StreamBitmapDecoder(context).decode(source, width, height);
							}
							BufferedInputStream inputStream = new BufferedInputStream(source);
							ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
							byte[] buffer = new byte[4096];
							int count;
							while ((count = inputStream.read(buffer)) > -1) {
								outputStream.write(buffer, 0, count);
							}
							byte[] decryptedData = EZOpenSDK.getInstance().decryptData(outputStream.toByteArray(), verifyCode);
							if (decryptedData == null || decryptedData.length <= 0) {
								LogUtil.d("EZUtils", "verifyCodeError！");
								if (verifyCodeErrorListener != null) {
									verifyCodeErrorListener.verifyCodeError();
								}
								outputStream.close();
								return null;
							} else {
								source = new ByteArrayInputStream(decryptedData);
								outputStream.close();
							}
							return new StreamBitmapDecoder(context).decode(source, width, height);
						}
		
						@Override
						public String getId() {
							return url;
						}
					}).into(imageView);
```
In version 4.6.1 ,i can't find imageDecoder.So,i use apply(new RequestOptions().decode(EzBitmapDecoder.class)),it doesn't works.

```java
@GlideModule
public class MyAppGlideModule extends AppGlideModule {
  @Override
  public void registerComponents(Context context, Glide glide, Registry registry) {
    registry.prepend(InputStream.class, BitmapDrawable.class, new EzBitmapDecoder(context));
  }
}
```

**Comment by sjudd** [comment]
If you just prepend your decoder as you're already doing in your GlideModule, you don't need to pass in anything when you make your request.

**Comment by nirvana2017** [comment]
I use GlideModule,but it doesn't work. I think my decoder has some problem.My deocoder extends  ResourceDecoder<InputStream, BitmapDrawable> ,and Glide.load(string) .I get url string,and show it.So,I should extends ResourceDecoder<String, BitmapDrawable> .If so,I will write the code of getting inputStream from server,it's too complex. I just want to transform byte[] to new byte[] with secret key.

If the above problem is solved, there still has other problem. First, the  secret key is dynamic, how to inject . Second, Can I inject a callback. So i will handle it ,When decoding failed.

The Decoder:
public class EzBitmapDecoder implements ResourceDecoder<InputStream, BitmapDrawable> {

	private final Context mContext;
	private final Resources resources;

	public EzBitmapDecoder(Context context) {
		mContext = context;
		resources = context.getResources();
	}

	@Override
	public boolean handles(@NonNull InputStream source, @NonNull Options options) throws IOException {
		return true;
	}

	@Nullable
	@Override
	public Resource<BitmapDrawable> decode(@NonNull InputStream source, int width, int height, @NonNull Options options) throws IOException {

		ByteArrayOutputStream output = new ByteArrayOutputStream();
		byte[] buffer = new byte[4096];
		Bitmap desBitmap = null;
		int n = 0;
		while (-1 != (n = source.read(buffer))) {
			output.write(buffer, 0, n);
		}
		output.flush();
		output.close();
		byte[] src = output.toByteArray();
		if (src == null || src.length <= 0) {
			return null;
		}
		//decode
		byte[] data1 = EZOpenSDK.getInstance().decryptData(output.toByteArray(), "OSAQTW");
		if (data1 == null || data1.length <= 0) {
			//failed
			Drawable db = ContextCompat.getDrawable(BaseApplication.getInstance(), R.drawable.bg_touming);
			BitmapDrawable bd = (BitmapDrawable) db;
			desBitmap = bd.getBitmap();
		} else {
			//success
			desBitmap = BitmapFactory.decodeByteArray(data1, 0, data1.length);
		}
		if (desBitmap != null) {
			Resource<Bitmap> bitmapResource = new BitmapResource(desBitmap, EZDecImageTool.getBitmapPool(BaseApplication.getInstance()));
			return LazyBitmapDrawableResource.obtain(resources, bitmapResource);
		}
		return null;
	}
}

**Comment by sjudd** [comment]
If you want to write the decode path String -> InputStream/Key -> Bitmap, then you'll probably want two components: ModelLoader<String, InputStream/Key> and ResourceDecoder<InputStream/Key, Bitmap>. 

You can define a POJO that contains the InputStream/Key and construct one given one of your Strings in your ModelLoader. You can then pass the POJO into your ResourceDecoder.

As for a callback, there's no good way to pass a callback into a component. Instead throw a specific exception with whatever data you need and if the load fails, your [`RequestListener`][1] will be called with a [`GlideException`][2] from which you can extract your specific exception via [`getRootCauses()`][3]: http://bumptech.github.io/glide/doc/debugging.html#requestlistener-and-custom-logs

[1]: http://bumptech.github.io/glide/javadocs/460/com/bumptech/glide/request/RequestListener.html#onLoadFailed-com.bumptech.glide.load.engine.GlideException-java.lang.Object-com.bumptech.glide.request.target.Target-boolean-
[2]: http://bumptech.github.io/glide/javadocs/460/com/bumptech/glide/load/engine/GlideException.html
[3]: http://bumptech.github.io/glide/javadocs/460/com/bumptech/glide/load/engine/GlideException.html#getRootCauses--

**Comment by nirvana2017** [comment]
How to write ModelLoader<String, InputStream/Key>, I don't quite understand InputStream/Key. 
Now,I use EzImage instead of String . EzImage contains url string and the key.But ,passed through ModelLoader,the model (EzImage ) convert to InputStream, the key misses. So,in ResourceDecoder, I cann't decode the byte[].

public class EzImage {

	private String url;
	private String key;

	public EzImage() {
	}

	public EzImage(String url, String key) {
		this.url = url;
		this.key = key;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}
}

public class EzModelLoader implements ModelLoader<EzImage, InputStream> {

	public static final Option<Integer> TIMEOUT = Option.memory("com.bumptech.glide.load.model.stream.HttpGlideUrlLoader.Timeout", 2500);

	@Nullable
	private final ModelCache<EzImage, EzImage> modelCache;

	public EzModelLoader() {
		this(null);
	}

	public EzModelLoader(@Nullable ModelCache<EzImage, EzImage> modelCache) {
		this.modelCache = modelCache;
	}

	@Nullable
	@Override
	public LoadData<InputStream> buildLoadData(@NonNull EzImage ezImage, int width, int height, @NonNull Options options) {
		EzImage image = ezImage;
		if (modelCache != null) {
			image = modelCache.get(ezImage, 0, 0);
			if (image == null) {
				modelCache.put(ezImage, 0, 0, ezImage);
				image = ezImage;
			}
		}
		int timeout = options.get(TIMEOUT);
		return new LoadData<>(new GlideUrl(image.getUrl()), new HttpUrlFetcher(new GlideUrl(image.getUrl()), timeout));
	}

	@Override
	public boolean handles(@NonNull EzImage ezImage) {
		return true;
	}


	/**
	 * The default factory for {@link HttpGlideUrlLoader}s.
	 */
	public static class Factory implements ModelLoaderFactory<EzImage, InputStream> {
		private final ModelCache<EzImage, EzImage> modelCache = new ModelCache<>(500);

		@NonNull
		@Override
		public ModelLoader<EzImage, InputStream> build(MultiModelLoaderFactory multiFactory) {
			return new EzModelLoader(modelCache);
		}

		@Override
		public void teardown() {
			// Do nothing.
		}
	}
}

**Comment by sjudd** [comment]
Make `EzModelLoader` implement `ModelLoader<EzImage, InputStreamAndKeyWrapper>` where `InputStreamAndKeyWrapper` is a POJO containing an `InputStream` and the `key`. You can the register a `ResourceDecoder<InputStreamAndKeyWrapper, Bitmap>` that uses both the given `InputStream` and the `key` to decode the image.

**Comment by nirvana2017** [comment]
Thank you very much.

**Comment by jinyulei0710** [comment]
@sjudd Could you give some sample about this issue? It really puzzle me.
