### ISSUE TITLE
Question: Different image size URLs for single image support?

### ISSUE THREAD

**Issue by gajicm93** [bumptech/glide#2941]
Documentation for Targets states the following:

> By default, Glide uses the size provided by Targets via the getSize() method as the target size for the request. Doing so allows Glide to **choose an appropriate url**, downsample, crop, and Transform size appropriate images to minimize memory usage, and make sure loads are as fast as possible.

I'm interested in this "choose an appropriate url" part. I'm working with an API that returns a list of multiple image size URLs for every individual image. Does Glide natively support picking the "closest" image size URL based on ImageView size (and a way for me to pass it a list of URLs with sizes), and if not, what would be the most appropriate way of custom implementing this?

Thanks

**Comment by gajicm93** [comment]
In the meantime I've stumbled upon GiphyModelLoader. So guess that settles it then?

**Comment by gajicm93** [comment]
But now I have another question, how to properly combine my own model loader with OkHttp3 integration? Because OkHttp model loader is doing GlideUrl -> InputStream, but my custom model loader is also doing CustomImageModel -> InputStream, so isn't my model loader just trumping the OkHttp one?

Shouldn't I implement something like CustomImageModel -> GlideUrl, and then OkHttp model loader can take it from there, and how?

**Comment by sjudd** [comment]
GiphyModelLoader (and all BaseGlideUrlLoaders) take a `ModelLoader<GlideUrl, InputStream>` that they delegate to: 
https://github.com/bumptech/glide/blob/84178369d1782b788e9d66f3ef6a5453a2314160/samples/giphy/src/main/java/com/bumptech/glide/samples/giphy/GiphyModelLoader.java#L26-L28

The delegate is provided in the `Factory` object, which allows Glide to provide you whatever `ModelLoader` is registered at run time for GlideUrl -> InputStream:
https://github.com/bumptech/glide/blob/84178369d1782b788e9d66f3ef6a5453a2314160/samples/giphy/src/main/java/com/bumptech/glide/samples/giphy/GiphyModelLoader.java#L57-L60

See also: http://bumptech.github.io/glide/tut/custom-modelloader.html#delegating-to-another-modelloader
And: http://bumptech.github.io/glide/tut/custom-modelloader.html#baseglideurlloader

**Comment by gajicm93** [comment]
Aha so it should just work properly.. I didn't even find time to test it first, was asking preventively. Anyways, I'll close this for now, and reopen if I run into any problems, but I guess I won't.

Thank you.
