### ISSUE TITLE
GIF displays slow and reduces the quality of the picture.The picture has a sense of granularity.

### ISSUE THREAD

**Issue by 372352090** [bumptech/glide#2944]
**Glide Version**:compile 'com.github.bumptech.glide:glide:3.7.0'

**Integration libraries**:compile 'com.squareup.okhttp3:okhttp:3.1.2'
    compile 'com.squareup.okio:okio:1.6.0'
    compile 'com.alibaba:fastjson:1.1.64.android'
    compile files('libs/com.baidu.tts_2.3.1.20170808_e39ea89.jar')
    compile files('libs/bdasr_V3_20170929_c8984af.jar')
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.elvishew:xlog:1.4.0'

**Device/Android Version**:firefly-rk3399

**Issue details / Repro steps / Use case background**: Shortly after the application opens, the GIF display is normal.After running for a period of time, the GIF image decreases and the playback slows down.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this).load(id)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .skipMemoryCache(true)
                .into(mExpression);
```

**Layout XML**:
```xml
<ImageView
        android:id="@+id/expression"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:scaleType="fitCenter"
        android:visibility="gone"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintBottom_toTopOf="@+id/guideline_horizontal_two"></ImageView>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

![低画质图片](http://www.chuantu.biz/t6/250/1520586731x-1404755588.jpg)

**Comment by sjudd** [comment]
Let me know if you're able to reproduce on v4+.

**Comment by kthacker7** [comment]
I am able to reproduce on v4+, Motorola x4, API 26.

**Comment by sjudd** [comment]
@kthacker7 what version specifically? Can you attach the GIF?
