### ISSUE TITLE
Glide api methods does't appear to call

### ISSUE THREAD

**Issue by arthurfigueiredo** [bumptech/glide#2947]
I am using glide 4.3.1

I want to call signature method but does't appears.

my code

`Glide.with(context).load(context.getFilesDir().getPath() + "/" + imgName).into(imgView);`

I want to do this

`Glide.with(context).load(context.getFilesDir().getPath() + "/" + imgName).signature(new StringSignature("someVersion")).into(imgView);`

I'm using android studio, when i put mouse over signature method i see the message: Cannot resolve method 'signature(StringSignature)'.

My build gradle: 
dependencies {
   compile 'com.github.bumptech.glide:glide:4.3.1'
}

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/generatedapi.html and http://bumptech.github.io/glide/doc/options.html
