### ISSUE TITLE
How to set scaleType attributes for placeholders（placeholder(placeholderId) .error(errorId)）

### ISSUE THREAD

**Issue by monkey008** [bumptech/glide#2949]
At present I can only achieve through the following methods：
xml:
```
<ImageView
        ......
        android:scaleType="centerCrop"
        ...... />
```
glide:
```
RequestOptions options = baseOptions.clone()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .dontAnimate()
                .placeholder(placeholderId)
                .error(errorId)
                .optionalCenterCrop();
        Glide.with(context)
                .asBitmap()
                .load(url)
                .apply(options)
//                .transition(BitmapTransitionOptions.withCrossFade(500))
                .into(imageView);
```

Is there any other way?
I used Google search but could not find the method mentioned, such as errorFitCenter()、into(errorCenter(imageView))、

[https://github.com/bumptech/glide/issues/1456 ](https://github.com/bumptech/glide/issues/1456 )
Only solved the placeholder().
How to handle the scaleType of error(errorId)?

**Comment by monkey008** [comment]
Can anyone help me? 
plz

**Comment by sjudd** [comment]
Glide doesn't support scaling placeholders or error drawables. It's usually wasteful to try to manipulate Drawables at runtime if you can instead include appropriately sized placeholders with your apk. 

If you have an exceptional case where this makes sense, consider writing your own custom Drawable that wraps your placeholder and applies whatever transformation you need at draw time.
