### ISSUE TITLE
Allow clearing of targets for destroyed Activities

### ISSUE THREAD

**Issue by Saketme** [bumptech/glide#2954]
**Glide Version**: 4.6.1

**Issue details / Repro steps / Use case background**: 
I'm using Glide to load images using `submit()` and manually clearing the `FutureTarget`s later using `Glide.with(Context).clear(FutureTarget)`. This is often getting when the parent Activity is finishing, resulting in `IllegalArgumentException: You cannot start a load for a destroyed activity` exceptions.

Will it be possible to allow clearing of targets without making this check? I just want to put the generated bitmaps back to the pool.

**Comment by sjudd** [comment]
You could both start and clear those targets from the application context. Or, Glide clears requests automatically when the corresponding Activity or Fragment is destroyed, so it will happen for you automatically if you make the requests from the Activity or Fragment context (ie Glide.with(activity) or Glide.with(fragment).

**Comment by Saketme** [comment]
Ah I did not know Glide managed the lifecycle of targets for custom targets too. Good to know, thanks!
