### ISSUE TITLE
Fragment no longer exists for key key: index 1

### ISSUE THREAD

**Issue by MerlinYu** [bumptech/glide#2957]
Console log print :Fragment no longer exists for key key: index 1.Does this will affect the app ?
03-16 15:37:59.298 17056-17056/com.tencent.ibg.joox E/FragmentManager: Fragment no longer exists for key key: index 1
03-16 15:37:59.298 17056-17056/com.tencent.ibg.joox E/FragmentManager: Activity state:
03-16 15:37:59.304 17056-17056/com.tencent.ibg.joox E/FragmentManager:   Local Activity 4efa93f State:
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:     mResumed=true mStopped=false mFinished=false
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:     mChangingConfigurations=false
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:     mCurrentConfig={1.0 ?mcc?mnc zh_CN ldltr sw360dp w360dp h616dp 320dpi nrml long port finger -keyb/v/h -nav/h s.20 themeChanged=0 themeChangedFlags=0}
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:     mLoadersStarted=true
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:     Active Fragments in d5750d4:
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:       #0: RequestManagerFragment{a21623b #0 com.bumptech.glide.manager}{parent=null}
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:         mFragmentId=#0 mContainerId=#0 mTag=com.bumptech.glide.manager
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:         mState=4 mIndex=0 mWho=android:fragment:0 mBackStackNesting=0
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:         mAdded=true mRemoving=false mResumed=false mFromLayout=false mInLayout=false
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:         mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:         mRetainInstance=false mRetaining=false mUserVisibleHint=true
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:         mFragmentManager=FragmentManager{d5750d4 in HostCallbacks{c6fd58}}
03-16 15:37:59.305 17056-17056/com.tencent.ibg.joox E/FragmentManager:         mHost=android.app.Activity$HostCallbacks@c6fd58
03-16 15:37:59.306 17056-17056/com.tencent.ibg.joox E/FragmentManager:         Child FragmentManager{ffadeb1 in RequestManagerFragment{a21623b}}:
03-16 15:37:59.306 17056-17056/com.tencent.ibg.joox E/FragmentManager:           FragmentManager misc state:
03-16 15:37:59.308 17056-17056/com.tencent.ibg.joox E/FragmentManager:             mHost=android.app.Activity$HostCallbacks@c6fd58
03-16 15:37:59.308 17056-17056/com.tencent.ibg.joox E/FragmentManager:             mContainer=android.app.Fragment$1@b90ef96
03-16 15:37:59.308 17056-17056/com.tencent.ibg.joox E/FragmentManager:             mParent=RequestManagerFragment{a21623b #0 com.bumptech.glide.manager}{parent=null}
03-16 15:37:59.308 17056-17056/com.tencent.ibg.joox E/FragmentManager:             mCurState=4 mStateSaved=false mDestroyed=false
03-16 15:37:59.308 17056-17056/com.tencent.ibg.joox E/FragmentManager:     Added Fragments:
03-16 15:37:59.308 17056-17056/com.tencent.ibg.joox E/FragmentManager:       #0: RequestManagerFragment{a21623b #0 com.bumptech.glide.manager}{parent=null}

**Comment by sjudd** [comment]
I'd guess you're using Glide v4? If so, this is probably from `Glide.with(View)` and although it's spammy, the message isn't harmful. You can try injecting Glide's RequestManager instance or using the Activity context instead of the View to avoid the behavior unless you're loading images and what to use the Fragment lifecycle. 

This is part of the logic that Glide uses to try to figure out which Fragment the View belongs to.
