### ISSUE TITLE
Why the documentation does not match the objects in Lib??

### ISSUE THREAD

**Issue by nguyenquocchinhdev** [bumptech/glide#2958]
Why the documentation does not match the objects in Lib??

I have using 
`compile 'com.github.bumptech.glide:glide:4.6.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.6.1'`

Example:
[placeholders](https://bumptech.github.io/glide/doc/placeholders.html)

But in lib not found, and many methods have not found.

**Comment by sjudd** [comment]
The key sentence is "With the generated API:", see https://bumptech.github.io/glide/doc/generatedapi.html or click through to any of the links on those pages.
