### ISSUE TITLE
runtime error with build tool version 26. on setFont()

### ISSUE THREAD

**Issue by TransfoDeck** [bumptech/glide#2959]
the app gets to crash at runtime.
I m using your latest version 4.6.1 in an existing project which contains 26  build tool version.
the error log :-
" java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.simform.wifiapp.architecturecomponentdemo-1/base.apk)"

this is not happening in yr older version 4.6.0.
I have not used any font type in any XML file.
but because of glide latest version, it shows an error for to getFont().
please find the screenshot for reference.
![glide_issue](https://user-images.githubusercontent.com/35527025/37519351-c9c50f74-293e-11e8-8f9d-52ee3b707315.png)

**Comment by engineers-bojan** [comment]
Same here. 4.6.0 works fine while 4.6.1 is throwing the error.

**Comment by sjudd** [comment]
Duplicate of #2730
