### ISSUE TITLE
Glide load image show black when enable proguard

### ISSUE THREAD

**Issue by mdtuyen** [bumptech/glide#2960]
Hi,
I load image from drawable, it usually show black image if I enable proguard
If I build debug (disable proguard) everything look good.

Here is my config in proguard:

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

**Comment by aliustaoglu** [comment]
I have the same problem. Why did you close this? How did you solve the issue?

**Comment by mitsinsar** [comment]
It is closed but that's how I solved the issue; [stackoverflow](https://stackoverflow.com/a/64281013/10039864)
