### ISSUE TITLE
I am getting this glide error

### ISSUE THREAD

**Issue by PaapaAsare** [bumptech/glide#2961]
I added glide to my dependencies. when i compile gradle i get the error

Error:(31, 1) A problem occurred evaluating project ':app'.
> Could not find method implementation() for arguments [com.github.bumptech.glide:glide:4.6.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

below is my build.gradle Module app code.

![glide1](https://user-images.githubusercontent.com/22551092/37557907-7fc7f506-2a03-11e8-9a2c-80c97b3d359d.PNG)
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.example.paapa_asare.finalyearproject"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:27.0.2'
    compile 'com.android.support:design:27.0.2'
    compile 'com.google.android.gms:play-services-appindexing:9.8.0'
    compile 'com.android.support:recyclerview-v7:27.0.2'
    compile 'com.android.support:cardview-v7:27.0.2'
    compile 'com.android.volley:volley:1.0.0'
    implementation 'com.github.bumptech.glide:glide:4.6.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.6.1'
}

**Comment by sjudd** [comment]
No ideas for you, sorry. It looks like a build issue? Let me know what you find out.
