### ISSUE TITLE
Is it possible to have a library that creates and uses a LibraryGlideModule?

### ISSUE THREAD

**Issue by DylanVann** [bumptech/glide#2962]
**Context**: https://github.com/DylanVann/react-native-fast-image/pull/82#issuecomment-373985549

The library is exporting a component that uses Glide to load images. The library is also using a `LibraryGlideModule` to report progress of loading images.

If `Glide.with` is used for loading the `LibraryGlideModule` is not used, and progress reporting does not work. `GlideApp.with` + `AppGlideModule` works, but it's not supposed to be used by a library.

**Glide Version**: 4.6.1
**Integration libraries**: 'com.github.bumptech.glide:okhttp3-integration:4.6.1'

**Comment by sjudd** [comment]
GlideApp.with is just a thin wrapper around Glide.with. There's no reason I can think of why using `Glide.with` would produce a request that behaves differently than `GlideApp.with`. You can take a look at the generated source for yourself and confirm that it's the case.

**Comment by DylanVann** [comment]
@sjudd Thanks for the help.

It seems like using `Glide.with` does not use Glide modules. The modules seem to be added when an `AppGlideModule` is created. I will make a minimal demonstration of this to show what I'm talking about.

**Comment by DylanVann** [comment]
Haven't had time to show this in an isolated example but it's obvious when running the `feat/glide-4` branch on https://github.com/DylanVann/react-native-fast-image .

See: https://github.com/DylanVann/react-native-fast-image/pull/201/files

If `MyAppGlideModule.java` is removed then the progress events are no longer sent. But apparently including that will cause an error if a user adds their own `AppGlideModule`.

What is says in the docs:

> All applications must add a AppGlideModule implementation, even if the Application is not changing any additional settings or implementing any methods in AppGlideModule. The AppGlideModule implementation acts as a signal that allows Glide’s annotation processor to generate a single combined class with with all discovered LibraryGlideModules.

So I guess the solution is that I have to instruct users to add an `AppGlideModule`.

**Comment by DylanVann** [comment]
For anyone who finds this issue. The issue I had was that my library actually displays images and it also uses a glide module for progress reporting. I didn't want to have to instruct users to create an `AppGlideModule` to get the library to work and I didn't want to include one that would conflict if they did already have one.

The solution I eventually went with was to use an extended property to allow users to conditionally exclude the `AppGlideModule` within the library:

```gradle
def _excludeAppGlideModule = _ext.has('excludeAppGlideModule') ? _ext.excludeAppGlideModule : false

android {
    ...
    sourceSets {
        main {
            java {
                if (_excludeAppGlideModule) {
                    srcDir 'src'
                    exclude '**/FastImageGlideModule.java'
                }
            }
        }
    }
}
