### ISSUE TITLE
Can Glide change the load order when i scroll the recyclerview

### ISSUE THREAD

**Issue by sheepm** [bumptech/glide#2963]
I have a problem. sometimes the image load blocked because the DNS parse so slow, and when i scroll the recyclerView,other pictures block too even if is nice connect , does Glide has some timeout mechanism to skip the slow image load or change the load order when new viewHolder bind and the new image need display.thanks

**Comment by sjudd** [comment]
There are timeout mechanisms, depending on which networking library you're using. For example: http://bumptech.github.io/glide/javadocs/460/com/bumptech/glide/load/model/stream/HttpGlideUrlLoader.html#TIMEOUT. You can set it with RequestOptions: http://bumptech.github.io/glide/doc/options.html#component-options
