### ISSUE TITLE
Getting Memory issues with Glide if preloading images using SimpleTarget.

### ISSUE THREAD

**Issue by Ansh1234** [bumptech/glide#2965]
**Glide Version**: 4.4

**Integration libraries**: OkHttp3

**Device/Android Version**: OnePlus/ Oreo

I have an infinite list(RecyclerView). I need to preload images of next 'x'(read 3) items from the last bound item of the RecyclerView. Also, when a particular Viewholder is detached from the window, I need to cancel the preload image request if it is already not successful.

I have achieved it in the following way.

```java
Map<Integer, SimpleTarget> simpleTargetMap = new HashMap<>();

public void preloadImage(int position, Context context, String imageUrl) {
    SimpleTarget simpleTarget = new SimpleTarget() {
      @Override
      public void onResourceReady(@NonNull Object resource, @Nullable Transition transition) {
        simpleTargetMap.remove(position);
      }
    };
    Glide.with(context)asBitmap().load(imageUrl).into(simpleTarget);
    simpleTargetMap.put(position, simpleTarget);
}


  @Override
public void onViewDetachedFromWindow(RecyclerView.ViewHolder holder) {
    super.onViewDetachedFromWindow(holder);
    SimpleTarget simpleTarget = simpleTargetMap.get(holder.getAdapterPosition());
    Glide.with(context).clear(simpleTarget);
    simpleTargetMap.remove(holder.getAdapterPosition());
}
```

I am able to achieve the desired result. But I am facing memory issues with this approach. If I don't use the preloading, my memory usage is between 150-200 mb. But if I start using the preload, the memory usage jumps to 250-300 mb. Ideally there should be very little difference between memory usage, because I am only preloading the images which are eventually used for the future items. After taking a heap dump, I see a lot of Bitmap objects which are not there(not as many) if I don't use preload.

So what is the best way to preload an image in Glide where I can also cancel the image request in the future? And if I don't use SimpleTarget, is there any way of cancelling an image request based only of the imageUrl?

**Comment by sjudd** [comment]
I'd assume most of the memory usage is coming from SimpleTargetMap? A heap dump should tell you where the  memory is being kept, which would help answer your question.

However, Glide includes a preloading library for ListView/RecyclerView which will use Glide's existing cache. See http://bumptech.github.io/glide/int/recyclerview.html
