### ISSUE TITLE
Minimum Compile Android SDK 26 or 27 ?

### ISSUE THREAD

**Issue by chinachen01** [bumptech/glide#2968]
The minimum Compile Android SDK version on README is 26:

 * **Minimum Android SDK**: Glide v4 requires a minimum API level of 14.
 * **Compile Android SDK**: Glide v4 requires you to compile against API 26 or later.

But on the glide documentation, it said:
* **Compile Android SDK**:Glide must be compiled against SDK version 27 (Oreo MR1) or higher.

For some reason, I have to use version 26 in my project.  Is there a risk?

**Comment by sjudd** [comment]
You basically never have to compile against an older version of the SDK. If you do, please let me know why. Otherwise, you may need to target API 26, which is fine, but you can target API 26 while compiling against API 27.
