### ISSUE TITLE
Possible to force glide to load images synchronously if already in cache?

### ISSUE THREAD

**Issue by AlanCPSC** [bumptech/glide#2969]
## Background info

The current Android application that I am working on has some images sitting inside some `RecyclerView.ViewHolder`

The problem is that the same `RecyclerView.ViewHolder` also contains other formatted data - and when those change `notifyDataSetChanged` must be called even when the image itself has stayed the same.

The current code that handles image loading inside the `RecyclerView` is the following (note that it is pseudocode).

```
public class MyRecyclerViewAdapter extends RecyclerView.Adapter<MyViewHolder>
{
    // more code here

    @Override
    public void onBindViewHolder(MyViewHolder holder, int position)
    {
        // more code here

        loadMyImage(holder.picture, myLink);
    }

    public void loadMyImage(AppCompatImageView picture, Uri myLink)
    {
        picture.setImageResource(R.drawable.placeholder);

        Glide.with(context).load(myLink).into(picture); // asynchronous load
    }
}
```

## My problem

The problem is that this causes a slight but very noticeable flickering between `R.drawable.placeholder` and `myLink`.

## My attempt

Now there are 2 things that I have come up with at this point in time to solve this issue.

1) Try to place the views into different view holders by redoing the layout and also redoing the underlying code.
[This is not an option due to the sheer amount of spaghetti and legacy code that forms the basis of this project]

2) Try and change the line `Glide.with(context).load(myLink).into(picture); // asynchronous load` into one that forces a synchronous load if already in cache.
[Theoretically removing the flicker and only adding nominal delay - since it is already in cache anyways]

```
public class MyRecyclerViewAdapter extends RecyclerView.Adapter<MyViewHolder>
{
    // more code here

    @Override
    public void onBindViewHolder(MyViewHolder holder, int position)
    {
        // more code here

        loadMyImage(holder.picture, myLink);
    }

    public void loadMyImage(AppCompatImageView picture, Uri myLink)
    {
        picture.setImageResource(R.drawable.placeholder);

        if (inCache(myLink))
        {
            Glide.with(context).load(myLink).into(picture).synchronously();
        }
        else
        {
            Glide.with(context).load(myLink).into(picture).asynchronously();
        }
    }
}
```

**Comment by sjudd** [comment]
Glide will already complete a load synchronously if an image is in cache. If it's not completing a load synchronously, it means there was a cache miss. See http://bumptech.github.io/glide/doc/caching.html#cache-keys

**Comment by sjudd** [comment]
I should also mention that it's likely that if there is a cache miss with your load above, it's most common for the reason to be differently sized Views so that the sizes don't match exactly. This can be fixed by specifying a size with [`override`][1]

[1]: http://bumptech.github.io/glide/javadocs/470/com/bumptech/glide/request/RequestOptions.html#override-int-int-

**Comment by AlanCPSC** [comment]
Just to clarify that I have understood you correctly.

```
// Assuming link is already in cache
Glide.with(parentActivity).load(link).into(picture);

// I can assume the picture has already been loaded on this line
// since you claim that it will be synchronous, correct?
```

Also, what about listeners, will their respective callbacks also be called synchronously if `link` is already in cache? Or will they stay asynchronous (just very fast)?

```
Glide.with(parentActivity).load(link).listener(callback).into(picture);

// Will listener.onLoadFailed and listener.onResourceReady be called already on this line?

**Comment by sjudd** [comment]
Sorry I missed your update.

Yes if link is in cache the load will complete synchronously with the usual caveats around cache keys. Same with onResourceReady for listeners.

Failures aren't cached, so onLoadFailed won't be called synchronously because Glide will always make another attempt to load the image when you make the new request.
