### ISSUE TITLE
使用V4.6.1版本报错

### ISSUE THREAD

**Issue by songj056** [bumptech/glide#2974]
编辑的时候没问题，运行的时候报如下错误：
Error:Could not resolve all files for configuration ':app:debugAnnotationProcessorClasspath'.
> Could not resolve com.github.bumptech.glide:compiler:4.6.1.
  Required by:
      project :app
   > No cached version of com.github.bumptech.glide:compiler:4.6.1 available for offline mode.
   > No cached version of com.github.bumptech.glide:compiler:4.6.1 available for offline mode.
   > No cached version of com.github.bumptech.glide:compiler:4.6.1 available for offline mode.
   > No cached version of com.github.bumptech.glide:compiler:4.6.1 available for offline mode.
   > No cached version of com.github.bumptech.glide:compiler:4.6.1 available for offline mode.
   > No cached version of com.github.bumptech.glide:compiler:4.6.1 available for offline mode.

配置都是按需求来的，请大神帮我看看，谢谢。

**Comment by songj056** [comment]
使用的工具是Android Studio 3.0.1

**Comment by TangHuaiZhe** [comment]
prefrence----Build,Execution,Deployment--------Gradle----cancel  offline work

**Comment by songj056** [comment]
@TangHuaiZhe 老铁你好！这个我本来就是取消的。和这个没关系。http://p1.cdn.img9.top/ipfs/QmStJmYBkcYwLR2YUWvaszxW2T4nUm6T7MUbCCo7gLa1bM?1.jpg

**Comment by sjudd** [comment]
I'd guess the discussion above is about this, but it looks like you've got offline mode enabled in Gradle or Android Studio and you haven't previously downloaded 4.6.1. I'd also suggest StackOverflow here since this doesn't seem like it's related to Glide specifically.

**Comment by songj056** [comment]
@sjudd 
compileSdkVersion 27
targetSdkVersion 27

// Glide
implementation 'com.github.bumptech.glide:glide:4.6.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.6.1'
implementation 'com.android.support:support-annotations:27.1.0'
implementation 'com.android.support:appcompat-v7:27.1.0'

office work unchecked & Android Studio V3.0.1
Glide can be used, but there is no GlideApp method, it can compile, but running error

**Comment by songj056** [comment]
What can I do to use the latest Glide? @sjudd

**Comment by TangHuaiZhe** [comment]
@songj056  先看文档再集成 https://muyangmin.github.io/glide-docs-cn/doc/getting-started.html

**Comment by songj056** [comment]
@TangHuaiZhe 谢谢你的提醒，不过是我按照文档来的，编译没问题，也建立了专属module，但是就是没有GlideApp和运行不通过。


    /**
     * 加载图片公用方法
     *
     * @param context    上下文
     * @param url        图片链接
     * @param resourceId 默认图片
     * @param imageView  要显示图片的控件
     */
    public static void setLoadImage(@NonNull Context context, @NonNull String url, @DrawableRes int resourceId, @NonNull ImageView imageView)
    {
        if (Func.isUrlRight(url))
        {
            RequestOptions options = new RequestOptions()
                                             .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                                             .placeholder(resourceId)
                                             .error(resourceId)
                                             .priority(Priority.HIGH)
                                             .dontAnimate();

            Glide.with(context).load(url)
                    .apply(options)
                    .into(imageView);
        } else
        {
            Glide.with(context).clear(imageView);
            imageView.setImageResource(resourceId);
        }
    }

**Comment by TangHuaiZhe** [comment]
@songj056  看一下Glide的几个Sample  对比看看哪里不对  Sample可以在你的机器上运行吗    
https://github.com/bumptech/glide/blob/master/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr
