### ISSUE TITLE
SVG takes a long time loading Glide v4.6.1/v4.7.1

### ISSUE THREAD

**Issue by iosulizarraga** [bumptech/glide#2978]
I've used the code from the sample with some extra options to load a SVG image into an ImageView.

Code:

    private void loadSVGIntoImageView(String url, ImageView imageView) {
        Uri uri = Uri.parse(url);

        Glide.with(this)
                .as(PictureDrawable.class)
                .apply(new RequestOptions()
                        .placeholder(R.drawable.car_image)
                        .error(R.drawable.car_image)
                        .diskCacheStrategy(DiskCacheStrategy.DATA)
                        .skipMemoryCache(true)
                        .dontTransform()
                        .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL))
                .transition(new DrawableTransitionOptions()
                        .crossFade(android.R.anim.fade_in))
                .listener(new SvgSoftwareLayerSetter() {
                    @Override
                    public boolean onResourceReady(PictureDrawable resource, Object model, Target<PictureDrawable> target, DataSource dataSource, boolean isFirstResource) {
                        presenter.drawHotspotSM(currentHotspot);
                        return super.onResourceReady(resource, model, target, dataSource, isFirstResource);
                    }
                }).load(uri)
                .into(imageView);
    }

It works well, but it takes a long time until the image is displayed, like 20 seconds, where placeholder is seen.

There is no error log.

The rest of the classes (SvgSoftwareLayerSetter, SvgModule, SvgDrawableTranscoder and SvgDecoder) are the same as the sample.

With Glide v3.8.0 it worked fine, fast.

Previuos code (v3.8.0):

    private void loadSVGIntoImageView(String url, ImageView imageView) {

        GenericRequestBuilder<Uri, InputStream, SVG, PictureDrawable> requestBuilder;

        requestBuilder = Glide.with(getActivity())
                .using(Glide.buildStreamModelLoader(Uri.class, getActivity()), InputStream.class)
                .from(Uri.class)
                .as(SVG.class)
                .transcode(new SvgDrawableTranscoder(), PictureDrawable.class)
                .sourceEncoder(new StreamEncoder())
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .skipMemoryCache(true)
                .cacheDecoder(new FileToStreamDecoder<>(new SvgDecoder()))
                .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                .decoder(new SvgDecoder())
                .animate(android.R.anim.fade_in)
                .error(R.drawable.car_image)
                .listener(new SvgSoftwareLayerSetter<Uri>() {
                    @Override
                    public boolean onResourceReady(PictureDrawable resource, Uri model, Target<PictureDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        presenter.drawHotspotSM(currentHotspot);
                        return super.onResourceReady(resource, model, target, isFromMemoryCache, isFirstResource);
                    }
                });

        Uri uri = Uri.parse(url);
        requestBuilder
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                // SVG cannot be serialized so it's not worth to cache it
                .load(uri)
                .into(imageView);

    }

The image size is 1440 - 810.
I'm using an OnePlus One, Android 7.1.2, LineageOS 14.1

**Comment by sjudd** [comment]
You're using `DiskCacheStrategy.DATA` in your v4 code sample and `DIskCacheStrategy.NONE` in your v3 sample. `DiskCacheStrategy.DATA` will copy the entire file into Glide's cache. That's probably the primary difference in speed.

**Comment by iosulizarraga** [comment]
I have made the change of DIskCacheStrategy to DIskCacheStrategy.NONE and the time until the image is displayed is the same or longer.

**Comment by sjudd** [comment]
I don't have any other good ideas for you. If you think most of the time is spent outside of the SVG decoder, let me know where you think the time is being spent.

**Comment by iosulizarraga** [comment]
Thank you for the time spent, I have returned to the previous version (3.8.0), because with the v4 I can't  make it work well.

If you find a bug related to the SVG in v4, could you answer this thread?
Thanks!

**Comment by iosulizarraga** [comment]
Tested v4.7.1, the same thing happens

**Comment by auval** [comment]
Same issue here. Too bad the issue is ignored. I'll keep investigating.

**Comment by auval** [comment]
Profiler show that decode is complete quite fast, but the native message queue is blocked for almost a minute, and only on nativeWake - the image is actually shown
