### ISSUE TITLE
On Android P preview, failed 'Incomplete image data'

### ISSUE THREAD

**Issue by KirkBushman** [bumptech/glide#2979]
**Glide Version**: 4.6.1

**Device/Android Version**: Pixel 2 XL, Android P Preview

**Issue details / Repro steps / Use case background**: 
I'm using glide to load a list of images on a RecyclerView, using:

     private val glideOption = RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.RESOURCE)

     glide.load(imageUrl)
                .thumbnail(0.1f)
                .apply(glideOptions)
                .transition(DrawableTransitionOptions.withCrossFade())
                .into(holder.image)

The first time it loads the image, it's all fine, but when I scroll down further and go back to this image (so that it does have to load from cache), it takes forever.
On Logcat I see: 

    D/skia: libjpeg error 105 <  Ss=0, Se=63, Ah=0, Al=0> from Incomplete image data
    D/skia: --- Failed to create image decoder with message 'unimplemented'

It looks like it can't use cache, and goes back to re-download the image again.

**Comment by sjudd** [comment]
Can you reproduce it on anything other than P preview?

Can you attach a sample app that reproduces the issue, or a failing test case? http://bumptech.github.io/glide/tut/failing-test-cases.html

**Comment by KirkBushman** [comment]
I don't see this problem in 27 and 26, only in the Android P preview.
I think this has something to do with it: https://developer.android.com/preview/features.html#decoding-images

You can see it when going back and fourth on a list that is long enough.
I'll see if I can post a sample app in the next days.

**Comment by KirkBushman** [comment]
I'm having some difficulties reproducing the error, having almost the same setup.
I think it has to do with a particular situation.

**Comment by Niuxy** [comment]
Hello, I have recently encountered this problem, What's going on since then? Under what circumstances will this error occur?

**Comment by KirkBushman** [comment]
It was difficult for me to reproduce the error as my app has a lot of images, and it seemed like it was triggered at different times doing different actions.
After a while it didn't show anymore...
