### ISSUE TITLE
Downloading an image as byte array, transparent background become black

### ISSUE THREAD

**Issue by lfdversluis** [bumptech/glide#2982]
Glide version: 4.6.1.
Testing on an emulator running Android 7.0

I use Glide to obtain a byte array of the image using the following code:
```
byte[] bytes = Glide.with(context)
                            .as(byte[].class)
                            .load(url)
                            .submit()
                            .get();
```

Now, when I convert this into an `ImageDrawable` as follows `BitmapDrawable image = new BitmapDrawable(context.getResources(), BitmapFactory.decodeByteArray(bytes, 0, bytes.length));`
the transparent background is black. I have tried several methods to get rid of this (including creating a canvas and drawing the bitmap on top of that, using `image.getBitmap().hasTransparency(true)`, and compress the bitmap using the PNG image format) but they do not work.

Does glide by default use JPEG to decode? Is there some way to let Glide know it should preserve transparency or use `ARGB_8888` pixel format?

Here is [an example of a transparent image](http://cdn.frankerfacez.com/emoticon/165742/1) that renders with a black background. As you can see, they are PNGs.

**Comment by remvst** [comment]
I am having the same issue as @lfdversluis. Loading a URL into a byte array does not give the same result as loading it as a bitmap, then serializing it as a bytearray. Loading as bitmap gives transparency, while loading as bitmap array gets rid of all transparency.

Is there a known solution for this issue? I only need the byte array for that step (the bitmap is not displayed, but I would like to take advantage of Glide's cache so I don't download something that was likely shown on the UI at an earlier stage), and I would like to avoid letting glide deserialize it.
