### ISSUE TITLE
Load vector drawable resource multiple times issue

### ISSUE THREAD

**Issue by agustinsivoplas** [bumptech/glide#2985]
I am using glide 4.6.1 to load a Resource (a vector drawable). It's always the same resource but sometimes does not load properly. Looks Emily Blunt image.

The code:

```
fun AppCompatImageView.loadCircleImage(resId: Int, width: Int, height: Int) {
    val options = RequestOptions()
            .fitCenter()
            .override(width, height)
            .circleCrop()

    Glide.with(context)
            .load(AppCompatResources.getDrawable(context, resId))
            .apply(options)
            .into(this)
}
```

![error glide](https://user-images.githubusercontent.com/1648539/37912458-f4675fe6-30e8-11e8-8e60-32cda4447cdd.jpg)

Any idea?

**Comment by sjudd** [comment]
Do you see the issue if you do DiskCacheStrategy.NONE? Glide just uses the support library for decoding vector drawables. This an odd error that I haven't seen before. What version of the support library are you using?

**Comment by agustinsivoplas** [comment]
I am using  '27.1.0' support library, I have the same issue with DiskCacheStrategy.NONE

**Comment by sjudd** [comment]
Can you reproduce the issue by just calling the support library directly? We end up just calling AppCompatResources directly: https://github.com/bumptech/glide/blob/7427a493fa23d95f5e00853f78c40c43a50b8a56/library/src/main/java/com/bumptech/glide/load/resource/drawable/DrawableDecoderCompat.java#L54

**Comment by agustinsivoplas** [comment]
Worsk perfect with AppCompatResources.getDrawable(context, id) also If I use setImageResources works too.

**Comment by sjudd** [comment]
No good ideas unfortunately. AppCompatResources.getDrawable(context, resId) actually returns a Drawable, so Glide isn't even doing the loading here, we're just passing the Drawable through.
