### ISSUE TITLE
Scaling down the images for custom URLs from Custom Model Loader

### ISSUE THREAD

**Issue by thrlr123** [bumptech/glide#2988]
**Glide Version**:4.6.1

**Integration libraries**: OkHttp3 and Volley

**Device/Android Version**:pixel/8.1

**Issue details / Repro steps / Use case background**: 

The issue that I am seeing is that I am not seeing "=s0" or whatever the Math.max(width,height) is appended to my URL, it is always using the without appending anything at the end resulting in a URL that leads to a blurry image. It used to work before upgrading to 4.6.1. 

I have custom URLs based on the screen's height and width. That logic is implemented in getURL method of my CustomModelLoader like this:

```java
 @Override
    protected String getUrl(String url, int width, int height, Options options) {
        if (Strings.isNullOrEmpty(url)) return null;
        Uri uri = Uri.parse(url);
        if (uri.getHost() == null) return null;
        if (uri.getHost().contains("googleusercontent")) {
            return url + "=s" + Math.max(width, height);
        } else {
            return url;
        }
    }
```

MyGlideConfig.java looks like this:

```java
@GlideModule
public class MyGlideConfig extends AppGlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        super.applyOptions(context, builder);
       builder.setDefaultRequestOptions(RequestOptions.formatOf(DecodeFormat.PREFER_ARGB_8888));
    }

    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        registry.append(String.class, InputStream.class, new CustomModelLoader.Factory());
    }

    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }
}
```

When I start my app I have seen getURL being called a couple of times but I don't see it anymore with both append and prepend like mentioned here:

This is how I am loading my image

```java
 if (Validator.isURLValid(getImageUrl())) {
            GlideApp.with(getContext().getApplicationContext())
                    .asBitmap()
                    .load(getImageUrl())
                    .fitCenter()
                    .into(backDropImage);
        } 
```

It Works fine with the GenericLoaderFactory on Glide 3.8 but not with the MultiModelLoaderFactory.
On GLide V3 my GlideConfig.Java is extending from OkHttpGlideModule and that is the only Loader when url with "https://....." is accessed but with MultiModelLoaderFactory I see Its `modelLoaders `field has 4loaders of which first three are StringLoader and the fourth is my Custom Model Loader. It does append the value to the passed URL but still displays the image blurry or have granularity issues

Update: Even if I remove registry.append line in my Config, meaning, if I do not register my custom loader also I am seeing the same blurred image, Why is my custom Loader not working with MultiModelLoaderFactory?

**Comment by manuchintapalli** [comment]
@TWiStErRob I read each and every comment that you have mentioned everywhere but no luck. Can you please help me out here? On glide 3.8 it works fine but the same code with changes according to the documentation are loading blurred images on full screen. What has changed? What needs to be done in order to not lose the clarity of the images.

**Comment by sjudd** [comment]
Registering with `append` means your ModelLoader is tried after all of Glide's default ModelLoaders. Since Glide includes a default String -> InputStream ModelLoader, you need to use `prepend` instead. See http://bumptech.github.io/glide/doc/configuration.html#ordering-components

**Comment by thrlr123** [comment]
Yeah! I did that, I changed it to prepend long back. It works fine but the images on 3.8 and glide 4.6.1 are looking different. It is blurred for some reason. @sjudd

**Comment by TWiStErRob** [comment]
1. Debug and verify if your `getUrl` code is executed in cases it needs to execute
2. Verify it produces the result you want (I suggest dropping in an OkHttp, registering to Glide and adding a logger or using stetho; or proxy/wireshark)
3. Identify the cases where it is not mapping the Url the way you want and report back to us.
