### ISSUE TITLE
How to fetch images, gif and mp4 from FTP

### ISSUE THREAD

**Issue by FedericoPonzi** [bumptech/glide#2991]
Hello, Is it possible to use glide to load images and videos from FTP? I'm trying to gasp model loader but seems very difficult to implement.

I've this method which returns an `InputStream`:

```
public InputStream getFTPStream(String imageUrl) throws IOException
        {
        
            FTPClient con = null;
            Log.v(TAG, "Image url: " + imageUrl);
        
            try
            {
                con = new FTPClient();
                con.connect(Config.FTP_SERVER, Config.FTP_PORT);
                if (con.login(Config.FTP_USERNAME, Config.FTP_PASSWORD))
                {
                    con.enterLocalPassiveMode();
                    con.setFileType(FTP.BINARY_FILE_TYPE);
                
                    return con.retrieveFileStream(imageUrl);
                }
                else
                {
                    throw new Exception("Login failed.");
                }
            } catch (Exception e)
            {
                Log.e(TAG, "Download error." e);
            
            } finally
            {
                con.logout();
                con.disconnect();
            }
        
            return null;
        }
```

Can I have some help or direction on how to use it with glide? Thanks

**Comment by FedericoPonzi** [comment]
Ok I've finally managed to get it working, but gifs aren't moving :thinking:, also I wanted to ask how can I close the InputStream. 
In the tutorial, says that inside 

 
        @Override
        public void cleanup() {
            // chiudere l'inputstream nonsisabenecome
        
        }

We should close inputstream. But how am I supposed to get a reference to it?

**Comment by FedericoPonzi** [comment]
I got this:

FTP Filestring wrapper:
```
package me.fponzi.instantsharing.glide;

public class FTPFileStringWrapper
{
    public String fileName;
    
    @Override
    public String toString()
    {
        
        return fileName;
    }
    
    @Override
    public int hashCode()
    {
        
        return fileName.hashCode();
    }
    
    public FTPFileStringWrapper(String fileName)
    {
        this.fileName = fileName;
    }
}
```

My model loader + data fetcher:
```
package me.fponzi.instantsharing.glide;

import android.support.annotation.NonNull;
import android.util.Log;

import com.bumptech.glide.Priority;
import com.bumptech.glide.load.DataSource;
import com.bumptech.glide.load.Options;
import com.bumptech.glide.load.data.DataFetcher;
import com.bumptech.glide.load.model.ModelLoader;
import com.bumptech.glide.signature.ObjectKey;

import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;

import java.io.IOException;
import java.io.InputStream;

import me.fponzi.instantsharing.utils.Config;

/**
 * Loads an {@link InputStream} from a ftp url.
 */
public final class FTPModelLoader implements ModelLoader<FTPFileStringWrapper, InputStream>
{

    private final String TAG = FTPModelLoader.class.getCanonicalName();
    
    
    @Override
    public LoadData<InputStream> buildLoadData(FTPFileStringWrapper model, int width, int height, Options options)
    {
    
        return new LoadData<>(new ObjectKey(model), new FTPDataFetcher(model));
    
    }
    
    
    @Override
    public boolean handles(@NonNull FTPFileStringWrapper model)
    {
        
        return true;
    }
    
    public class FTPDataFetcher implements DataFetcher<InputStream>
    {
        private final String TAG = FTPDataFetcher.class.getCanonicalName();
        
        private final String filename;
        private InputStream inputStream;
        
        FTPDataFetcher(FTPFileStringWrapper model)
        {
            
            this.filename = model.fileName;
        }
        
        @Override
        public void loadData(Priority priority, DataCallback<? super InputStream> callback)
        {
            
            try
            {
                this.inputStream = getFTPStream(this.filename);
                callback.onDataReady(this.inputStream);
                
            } catch (Exception e)
            {
                callback.onLoadFailed(e);
            }
            
            
        }
        
        @Override
        public void cleanup()
        {
            
            if (inputStream != null)
            {
                try
                {
                    inputStream.close();
                }
                catch (IOException e)
                {
                }
            }
        }
        
        @Override
        public void cancel() {}
        
        @NonNull
        @Override
        public Class<InputStream> getDataClass()
        {
            
            return InputStream.class;
        }
        
        @NonNull
        @Override
        public DataSource getDataSource()
        {
            
            return DataSource.REMOTE;
        }
        
        public InputStream getFTPStream(String imageUrl) throws Exception
        {
            
            FTPClient con = null;
            Log.v(TAG, "Image url: " + imageUrl);
            
            try
            {
                con = new FTPClient();
                con.connect(Config.FTP_SERVER, Config.FTP_PORT);
                if (con.login(Config.FTP_USERNAME, Config.FTP_PASSWORD))
                {
                    con.enterLocalPassiveMode();
                    con.setFileType(FTP.BINARY_FILE_TYPE);
                    return con.retrieveFileStream(imageUrl);
                }
                else
                {
                    throw new Exception("Login failed.");
                }
            }
            catch (Exception e)
            {
                Log.e(TAG, "Impossibile scaricare( immagine: " + imageUrl + "): ", e);
                throw e;
            } finally
            {
                try
                {
                    con.logout();
                    con.disconnect();
                } catch (Exception e)
                {
                }
            }
        }
    }
}
```
The factory:
```
package me.fponzi.instantsharing.glide;

import com.bumptech.glide.load.model.ModelLoader;
import com.bumptech.glide.load.model.ModelLoaderFactory;
import com.bumptech.glide.load.model.MultiModelLoaderFactory;

import java.io.InputStream;
        
public class FTPModelLoaderFactory implements ModelLoaderFactory<FTPFileStringWrapper, InputStream>
{
    
    @Override
    public ModelLoader<FTPFileStringWrapper, InputStream> build(MultiModelLoaderFactory multiFactory) {
        return new FTPModelLoader();
    }
    
    @Override
    public void teardown() {
        // Do nothing.
    }
}
```

And finally the module:

```
package me.fponzi.instantsharing.glide;

import android.content.Context;
import com.bumptech.glide.Glide;
import com.bumptech.glide.GlideBuilder;
import com.bumptech.glide.Registry;
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool;
import com.bumptech.glide.load.engine.cache.LruResourceCache;
import com.bumptech.glide.module.AppGlideModule;

import java.io.InputStream;

@GlideModule
public class FTPGlideModule extends AppGlideModule
{
    
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        //TODO: fix
        int bitmapPoolSizeBytes = 1024 * 1024 * 0; // 0mb
        int memoryCacheSizeBytes = 1024 * 1024 * 0; // 0mb
        builder.setMemoryCache(new LruResourceCache(memoryCacheSizeBytes));
        builder.setBitmapPool(new LruBitmapPool(bitmapPoolSizeBytes));
    }
    
    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        registry.prepend(FTPFileStringWrapper.class, InputStream.class, new FTPModelLoaderFactory());
    
    }
}```

I'm using Glide version 4.6.1. This works well with jpg files, but cannot get it to work with gifs. They don't are static.

If I do:
```
           GlideApp.with(this)
                    .asGif()
                    .placeholder(R.color.colorAccent)
                    .load(new FTPFileStringWrapper(lastMedia)).into(imageView);
```
I get this:
```
W/Glide: Load failed for 0.gif with size [1080x1710]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->GifDrawable->GifDrawable}, DATA_DISK_CACHE, ObjectKey{object=0.gif}
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->GifDrawable}
      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->GifDrawable->GifDrawable}, DATA_DISK_CACHE, ObjectKey{object=0.gif}
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->GifDrawable}
```
If I add `.decode(GifDecoder.class)` I get this:
```
W/Glide: Load failed for 0.gif with size [1080x1710]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.lang.IllegalStateException(Failed to find any load path from class me.fponzi.instantsharing.glide.FTPFileStringWrapper to class com.bumptech.glide.load.resource.gif.GifDrawable)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class java.lang.IllegalStateException: Failed to find any load path from class me.fponzi.instantsharing.glide.FTPFileStringWrapper to class com.bumptech.glide.load.resource.gif.GifDrawable```

As soon as I get it working well, I will create a repository with the code I've posted in this comment, to get Glide working with ftp (or maybe I can make a PR? let me know!)

Thanks for help

**Comment by FedericoPonzi** [comment]
I've also tried to use the asFile, but seems like downloading just the first two frames of a video (from ftp). As I display It on a videoview, or upload it, it's the first 2 frames. Not sure if this is linked with problems of my implementation.

**Comment by yanbin92** [comment]
You can writing a custom ModelLoader  ,
i write a custom ModelLoader to support load ftp image in glide v3.7 .
reading this https://bumptech.github.io/glide/tut/custom-modelloader.html.
step1 :
public class FtpType {
    String ftppath;
    public FtpType(String ftppath) {
        this.ftppath = ftppath;
    }
    @Override
    public int hashCode() {
        return ftppath.hashCode();
    }
    @Override
    public boolean equals(Object obj) {
        return ftppath.equals(((FtpType) obj).ftppath);
    }
}
public class FtpDataFetcher implements DataFetcher<InputStream> {

    private final FtpType model;
    private InputStream stream;
    FTPClient ftpClient;

    FtpDataFetcher(FtpType model) {
        this.model = model;
        ftpClient = new FTPClient();
    }

    @Override
    public InputStream loadData(Priority priority) throws Exception {
        try {
            //server port
            ftpClient.connect(server, port);
           //loginname pass
            ftpClient.login(loginname , pass);
            ftpClient.enterLocalPassiveMode();
            ftpClient.setFileType(FTP.BINARY_FILE_TYPE);
            String remoteFile1 = model.getFtppath();

            stream = ftpClient.retrieveFileStream(remoteFile1);
            return stream;
        } catch (IOException ex) {
            System.out.println("Error: " + ex.getMessage());
            ex.printStackTrace();
        }
        return null;
    }
    @Override
    public void cleanup() {
        if (stream != null) {
            try {
                stream.close();
            } catch (IOException e) {
                // Ignore
            }
        }
        try {
            if (ftpClient.isConnected()) {
                ftpClient.logout();
                ftpClient.disconnect();
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    @Override
    public String getId() {
        return model.getFtppath();
    }

    @Override
    public void cancel() {
    }
}
step2

public class FtpModelLoader implements ModelLoader<FtpType, InputStream> {
    @Override
    public DataFetcher<InputStream> getResourceFetcher(FtpType model, int width, int height) {
        DataFetcher<InputStream> loadData = new FtpDataFetcher(model);
        return loadData;
    }
}
step3
public class MyAppGlideModule implements GlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        glide.register(FtpType.class,InputStream.class,new FtpModelLoaderFactory());
    }
}
step4
Register in AndroidManifest.xml
        <meta-data
            android:name=".MyAppGlideModule"
            android:value="GlideModule" />
finally load ftp image
       FtpType ftpType = new FtpType(path);
        Glide.with(getContext()).load(ftpType)
                .into(iv_chart);
