### ISSUE TITLE
Cannot build with Android Studio 3.1 Gradle 4.4: "Failed to resolve: glide 3rd-party Gradle plug-ins may be the cause"

### ISSUE THREAD

**Issue by samtipton** [bumptech/glide#2993]
4.6.1

**Integration libraries**:
okhttp3

**Stack trace / gradle console**:
```
Failed to resolve: glide
Open File

Folder G:\..\app\build\generated\source\kaptKotlin\debug
Folder G:\..\app\build\generated\source\kaptKotlin\release

3rd-party Gradle plug-ins may be the cause
```

app/build.gradle
```
    implementation 'com.github.bumptech.glide:glide:4.6.1'
    kapt 'com.github.bumptech.glide:compiler:4.6.1'

```

Reordering repositories like goffity mentions below did not work for me.

**Comment by goffity** [comment]
I have same problem.

I got error message. 
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find glide.jar (com.github.bumptech.glide:glide:4.6.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/github/bumptech/glide/glide/4.6.1/glide-4.6.1.jar

My build.gradle

`
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
    }
}
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}
`

`dependencies { 
  implementation 'com.github.bumptech.glide:glide:4.6.1'
  annotationProcessor 'com.github.bumptech.glide:compiler:4.6.1'
}`

**Comment by simon-the-canadian** [comment]
I got the same thing, I was able to build by reverting to version `4.5.0`
Version `4.6.0` would sync but when I go to build the Glide Module would cause the build to break.

**Comment by b95505017** [comment]
Latest version on jCenter is 3.6.1
https://jcenter.bintray.com/com/github/bumptech/glide/glide/

**Comment by goffity** [comment]
Update It's solved.
I re-order repositories from 
`repositories {
        google()
        jcenter()
        mavenCentral()
    }`

To

`repositories {
        mavenCentral()
        google()
        jcenter()
    }`

**Comment by samtipton** [comment]
4.5.0 did work.

**Comment by b1uec0in** [comment]
delete gradle cache folder( ~/.gradle/caches).

**Comment by fabio-filho** [comment]
In my case I can build the project, but I got this message: 
`3rd-party Gradle plug-ins may be the cause` .
I re-ordered the to:
`mavenCentral()`
` maven { url 'https://jitpack.io' }`
` google()`
` jcenter()`

And It's working now.

**Comment by crismaver1993** [comment]
I solved it adding the next things:

**Platform modules targeting Android**
The update of the experimental multiplatform projects feature introduces support for Android platform modules. These modules should apply the corresponding plugin in the Gradle build script and can use the shared code from a common module:

    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-platform-android'
    // ...


**Kapt diagnostic locations**
As of now, kapt, the Kotlin annotation processing tool, can offer links to locations in the original Kotlin code rather than generated Java stubs as it reports errors encountered during annotation processing. You can enable this feature by adding these lines to the Gradle build script (build.gradle):

    kapt {
        mapDiagnosticLocations = true
    }



**IntelliJ IDEA plugin improvements**
Kotlin 1.2.30 brings various improvements in the IntelliJ IDEA Kotlin plugin, including performance improvements, bug fixes, and new inspections and intentions. 

Don't forget :

    
        repositories {
            mavenCentral()
            jcenter()
            google()
        }
    


Add all of this, Clean your project, build and That's it! :) Let me know if this works! (If it is not working for you, I will help you with another solution)

**Comment by samtipton** [comment]
I believe the real solution is clearing gradle caches as suggested by b1uec0in. After building with 4.5.0 then building again with 4.6.1 it succeeded.  Unfortunately, I can't confirm this fix. If someone else can then I am comfortable closing this ticket. Thanks for all the input.

**Comment by sjudd** [comment]
Huh, I haven't seen this. If clearing the gradle caches is confirmed, I can put something up on the docs page: http://bumptech.github.io/glide/doc/download-setup.html.

Do we know what changed outside of Glide that caused this?

**Comment by samtipton** [comment]
Hey sjudd, this happened after upgrading Android Studio for Windows to 3.1, build tools to 27.0.3, and gradle to 4.4

**Comment by vinraodeloitte** [comment]
As b1uec0in mentioned. 
Clearing user's ~/.gradle/caches folder and deleting app build folder manually, followed by clean and rebuild worked for me.

**Comment by the-maux** [comment]
Like @vinraodeloitte  As b1uec0in mentioned. (Windows confirmation)
Clearing user's ~/.gradle/caches folder and deleting app build folder manually, followed by clean and rebuild worked for me.
If i need to do that on all of my projects, it's gonna take a while...

**Comment by samtipton** [comment]
Great, I think it is safe to close.

**Comment by AllanWang** [comment]
@sjudd I think something might still be wrong with v4.6.1. I was previously on 4.4.x on AS 3.0. I've updated to AS 3.1, cleared the cache, manually deleted all the build files, then updated to glide 4.5.0, which worked. Afterwards, no amount of clearing caches and build files worked for me when using glide 4 6.1. I even tried removing the kapt dependency to see if things would change, but I still got errors.

**Comment by mttmllns** [comment]
I think the crux of this is we need to put mavenCentral higher in the list than jcenter:

```gradle
repositories {
	google()
	mavenCentral()
	jcenter()
```

This is the only thing that worked for me.  Likely related to https://github.com/bumptech/glide/issues/544?

**Comment by SermilionRestless** [comment]
Clearing gradle cache, invalidating AS cache and rebuilding folder worked for me.

**Comment by tcqq** [comment]
This problem is because of this code 'apply plugin: 'kotlin-kapt'', Error disappears after deletion.

**Comment by naveedahmad99** [comment]
Guys If you are using `apply plugin: 'kotlin-kapt'`
then GlideApp will be generated with below dependencies. replace **annotateProcessor** with **kapt**

`implementation 'com.github.bumptech.glide:glide:4.8.0'
    kapt 'com.github.bumptech.glide:compiler:4.8.0'`
