### ISSUE TITLE
Glide 4.x not actually backwards compatible with 3.x GlideModule

### ISSUE THREAD

**Issue by allenchen1154** [bumptech/glide#2994]
**Glide Version**: 4.6.1

**Integration libraries**: okhttp3-integration

**Device/Android Version**: Google Pixel 8.1

**Issue details / Repro steps / Use case background**: The Glide v4 documentation [states](https://bumptech.github.io/glide/doc/migrating.html#manifest-parsing) that 
```
To ease the migration, manifest parsing and the older GlideModule interface are deprecated, but still supported in v4. AppGlideModules, LibraryGlideModules and the deprecated GlideModules can all coexist in an application.
```
However, `Glide.initializeGlide()` calls `RegistersComponents.registerComponents(Context, Glide, Registry)` which is different from the signature of `registerComponents()` in Glide v3. This causes a `java.lang.AbstractMethodError` when initializing Glide with dependencies that were built against Glide v3. This means that we are unable to update Glide to v4 until all our dependencies have updated.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
@GlideModule
class GlideWrapper : AppGlideModule() {
    fun getImageLoader(context: Context): GlideImageLoader {
        return GlideImageLoader(GlideApp.with(context))
    }

    override fun applyOptions(context: Context, builder: GlideBuilder) {}

    override fun registerComponents(context: Context, glide: Glide, registry: Registry) {
        registry.append(
            GlideUrl::class.java,
            InputStream::class.java,
            OkHttpUrlLoader.Factory(okHttpClient)
        )
    }
```

**Stack trace / LogCat**:
```
java.lang.AbstractMethodError: abstract method "void com.bumptech.glide.module.RegistersComponents.registerComponents(android.content.Context, com.bumptech.glide.Glide, com.bumptech.glide.Registry)"
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:266)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:219)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:180)
        at com.bumptech.glide.Glide.get(Glide.java:164)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:670)
        at com.bumptech.glide.Glide.with(Glide.java:747)
```

**Comment by sjudd** [comment]
It's unsafe to use Glide v3 and v4 in the same app. The migration we're making easier is not from v3 to v4, but from the manifest based modules in v4 to the annotation based modules in v4.
