### ISSUE TITLE
Images load only on the first row

### ISSUE THREAD

**Issue by AngelinaBallerina11** [bumptech/glide#3000]
**Glide Version**: 4.6.1
**Integration libraries**:   okhttpVersion = '3.3.0'
**Device/Android Version**: several phone, behaviour is the same, Android API level 21-27

**Issue details / Repro steps / Use case background**: 
I am developing an Android app, which displays a list of items in a RecyclerView with ViewPager inside it. ViewPager uses FragmentStatePagerAdapter to display an image gallery. Images are fetched in the Fragment onStart method using Glide v4.

Images are loaded very quickly into the 1st row of the RecyclerView, but loading takes ages in the 2nd and subsequent rows. I do not see any network activity in Android Profiler and LogCat. Also the phone is less responsive and CPU increases when I try to slide in the 2nd row. In debugger all image urls are correct and working in browser.

I disabled Glide RAM and disk cache because i saw "skia: Increasing code cache capacity to 512KB" message in the LogCat, but it did not help, the messages like this are still there. I also added android:largeHeap="true" to the Manifest file, but it did not help.

There are 11 images per each ViewPager/row. Each image is a JPEG with average size 60kB.

I will be grateful for your suggestions. The only option I see is not to use image slider in the RecyclerView, but implement it in the Detail Layout. However, I am still curious why it the slider is stuck at other rows.

Example of Glider method:

```
@Override
public void onStart() {
    super.onStart();

    GlideApp
            .with(this)
            .load(url)
            .skipMemoryCache(true)
            .diskCacheStrategy(DiskCacheStrategy.NONE)
            .placeholder(R.drawable.ic_loading_image)
            .centerCrop()
            .into(imageView);
}
```

**Stack trace / LogCat**: 
```
03-31 00:34:31.858 27419-27479/  I/System.out: [socket][/xxx.xxx.xxx.xxx:55503] connected
03-31 00:34:31.858 27419-27479/  I/System.out: [OkHttp] sendRequest>>
03-31 00:34:31.858 27419-27479/  I/System.out: [OkHttp] sendRequest<<
03-31 00:34:31.863 27419-27480/  I/System.out: [socket][/xxx.xxx.xxx.xxx:55504] connected
03-31 00:34:31.864 27419-27480/  I/System.out: [OkHttp] sendRequest>>
03-31 00:34:31.864 27419-27480/  I/System.out: [OkHttp] sendRequest<<
03-31 00:34:31.928 27419-27430/  I/art: Enter while loop.
03-31 00:34:31.957 27419-27479/  D/skia: SkJpegCodec::onGetPixels +
03-31 00:34:31.960 27419-27480/  D/skia: SkJpegCodec::onGetPixels +
03-31 00:34:31.981 27419-27430/  I/art: Enter while loop.
03-31 00:34:32.009 27419-27479/  D/skia: SkJpegCodec::onGetPixels -
03-31 00:34:32.020 27419-27480/  D/skia: SkJpegCodec::onGetPixels -
03-31 00:34:32.045 27419-27480/  I/System.out: Wrong owner. Perhaps a late disconnect
03-31 00:34:32.047 27419-27479/  I/System.out: Wrong owner. Perhaps a late disconnect
03-31 00:34:32.112 27419-27424/  I/art: Do partial code cache collection, code=19KB, data=30KB
03-31 00:34:32.113 27419-27424/  I/art: After code cache collection, code=19KB, data=30KB
03-31 00:34:32.113 27419-27424/  I/art: Increasing code cache capacity to 128KB
03-31 00:34:39.123 27419-27458/  D/OpenGLRenderer: CacheTexture 3 upload: x, y, width height = 0, 0, 1024, 327
03-31 00:34:39.136 27419-27458/  D/OpenGLRenderer: CacheTexture 3 upload: x, y, width height = 0, 326, 1024, 19
03-31 00:34:39.291 27419-27458/  D/OpenGLRenderer: CacheTexture 3 upload: x, y, width height = 0, 161, 1024, 328
03-31 00:34:39.442 27419-27458/  D/OpenGLRenderer: CacheTexture 3 upload: x, y, width height = 0, 0, 1024, 507
03-31 00:34:39.455 27419-27458/  D/OpenGLRenderer: CacheTexture 3 upload: x, y, width height = 0, 232, 1024, 14
03-31 00:34:39.541 27419-27458/  D/OpenGLRenderer: CacheTexture 3 upload: x, y, width height = 0, 72, 1024, 38
03-31 00:34:39.624 27419-27458/  D/OpenGLRenderer: CacheTexture 3 upload: x, y, width height = 0, 109, 1024, 19
03-31 00:34:39.710 27419-27458/  D/OpenGLRenderer: CacheTexture 3 upload: x, y, width height = 0, 14, 1024, 125
03-31 00:34:39.819 27419-27424/  I/art: Do partial code cache collection, code=38KB, data=62KB
03-31 00:34:39.828 27419-27424/  I/art: After code cache collection, code=38KB, data=62KB
03-31 00:34:39.830 27419-27424/  I/art: Increasing code cache capacity to 256KB
03-31 00:34:39.895 27419-27458/  D/OpenGLRenderer: CacheTexture 3 upload: x, y, width height = 0, 0, 1024, 328
```
After that no more images are loaded and nothing appears in the LogCat.

**Comment by sjudd** [comment]
Maybe a view size issue? If you don't see log lines after following the debugging instructions, it's probably that Glide is still waiting for the view size to resolve. See http://bumptech.github.io/glide/doc/debugging.html#local-logs and http://bumptech.github.io/glide/doc/debugging.html#missing-images-and-local-logs

**Comment by AngelinaBallerina11** [comment]
Hi Sam, we figured it out. It's ViewPager bug/feature. When it's used
inside the RecyclerView it needs to be assigned a new ID (any number). I
forgot to post the answer to the issue.
Angelina

**Comment by sjudd** [comment]
Thanks for the follow up, glad you got it resolved!
