### ISSUE TITLE
Reloading images on enter activity

### ISSUE THREAD

**Issue by alfredolucomav** [bumptech/glide#3007]
I was wondering if there's an option to prevent reloading images. There's my code:

```
Glide.with(context)
.load(bmp)
.apply(new RequestOptions()
.skipMemoryCache(true)
.diskCacheStrategy(DiskCacheStrategy.ALL)
.placeholder(R.drawable.bg_header))
.into(holder.iv_profile);
```

So I just only want to prevent realoding images because when I'm entering in my activity all my images are reloading. ¿There's an option for that?

Best Regards

**Comment by sjudd** [comment]
Don't use skipMemoryCache? Is your Activity being destroyed and then re-created? What version of Glide are you using? Are you loading images in a scrolling list?

**Comment by alfredolucomav** [comment]
Hi @sjudd , recently I don't using `skipMemoryCache` but it still not working. I'm using Glide 4.3 and I put the images into a recycler view. ¿What am I doing wrong?

**Comment by GandhiRujul** [comment]
Hello @sjudd , 
I have noticed issue of image reloaded when i am just picking up image from gallery and come to screen. Image is refreshed by Glide. I am using Android studio 3.1 and using Glide 4.6.1 and I am trying to achieve this functionality using Data Binding. I have also tried to do Same thing in 4.5.0 but I am facing the same issue.

**Comment by sjudd** [comment]
Maybe see http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses or http://bumptech.github.io/glide/doc/caching.html#cache-keys. If the image is flashing it probably means that some aspect of your request changed for the given image, causing Glide to re-load the image rather than use the in memory version.
