### ISSUE TITLE
placeholder_picture will not disappear when I use  transition

### ISSUE THREAD

**Issue by qianshengta** [bumptech/glide#3011]
**Glide Version:**    
                    Glide_v4.6.1
**Integration libraries:**             
```
 Glide                 : 'com.github.bumptech.glide:glide:4.6.1',
 GlideCompiler         : 'com.github.bumptech.glide:compiler:4.6.1',
 GlideTransformations  : 'jp.wasabeef:glide-transformations:3.1.1',
 Gpuimage              : 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.4.1',
 GlideOkHttp3          : "com.github.bumptech.glide:okhttp3-integration:4.6.1",
 GlideRecyclerview     : "com.github.bumptech.glide:recyclerview-integration:4.6.1@aar",
```
**Android Version:** 
               
   Android_v5.1

**Issue details:**   
          
  placeholder_picture will not disappear when I use transition. the load_picture will cover on                                                                                
  placeholder_picture,i tried using dontAnimate().but it doesn't work either

**Glide load line:**
               
     GlideApp.with(this)
                     .asDrawable()
                     .load(R.mipmap.default_header)
                     .circleCrop()
                     .override(200, 200)
                     .placeholder(R.mipmap.ic_launcher)  //Problem loading
                     .fallback(R.mipmap.ic_launcher_round).
                         error(Glide.
                         with(this).
                         load(R.mipmap.ic_sleep_analysis_month_red))
                     .thumbnail(GlideApp.
                         with(this).
                         load(R.mipmap.default_header).
                         override(100).
                         circleCrop())
                     .transition(DrawableTransitionOptions.withCrossFade())   //The problem is in this line
                     .into(glideView); 
     Even if I set it up  :
     GlideApp.with(this)
                    .load(R.mipmap.default_header)
                    .placeholder(R.mipmap.ic_launcher) //Problem loading
                    .transition(DrawableTransitionOptions.withCrossFade())   //The problem is in this line
                    .into(glideView);
     The same problem still exists
**Layout XML:**

     <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
 
                        <ImageView
                            android:id="@+id/glide"
                            android:layout_width="100dp"
                            android:layout_height="100dp"
                            android:layout_centerHorizontal="true"/>
     </RelativeLayout>

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/transitions.html#cross-fading-with-placeholders-and-transparent-images

**Comment by qianshengta** [comment]
@sjudd  thanks a lot

**Comment by zhupengxiang** [comment]
What is the solution
