### ISSUE TITLE
OpenGLRenderer issue when fitCenter() not explicitly set

### ISSUE THREAD

**Issue by 3dm1** [bumptech/glide#3012]
**Glide Version**: 
4.6.1

**Integration libraries**: 
okhttp-integartion:4.6.1

**Device/Android Version**: 
Galaxy Nexus (4.3) and Pixel 1 (8.1)

**Issue details / Repro steps / Use case background**: 
Using this [image](https://i0.wp.com/techbeasts.com/wp-content/uploads/2016/12/4k-image-tiger-jumping.jpg) as an example, which is 7680 x 4320, I get a message in Logcat "OpenGLRenderer: Bitmap too large to be uploaded into a texture (3840x2160, max=2048x2048)". Then the screen remains blank and the error image is not displayed.
After explicitly adding `.fitCenter()` to the `GlideRequest`, the image is properly loaded as expected. This also happens if I add `.override(2058)` instead.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
imageView.setVisibility(View.VISIBLE);
GlideApp.with(this)
    .load(imageUrl)
    .placeholder(R.drawable.image_placeholder)
    .error(R.drawable.broken_image)
    .into(imageView);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:tools="http://schemas.android.com/tools"
             xmlns:app="http://schemas.android.com/apk/res-auto"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:background="@color/black">

    <FrameLayout android:id="@+id/fullscreen_layout"
                 android:layout_width="match_parent"
                 android:layout_height="match_parent">

        <ImageView
                android:id="@+id/fullscreen_image_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:keepScreenOn="true"
                android:alpha="0.2"
                android:scaleType="center"
                android:adjustViewBounds="true"
                android:visibility="gone" />

        <android.support.v4.view.ViewPager
                android:id="@+id/fullscreen_slider_layout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:visibility="gone"/>
    </FrameLayout>
```

**Stack trace / LogCat**:
```ruby
V/Engine: Started new load in 0.183106ms, key: EngineKey{model=IMAGE_URL, width=720, height=1134, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=1631874845, transformations={}, options=Options{values={}}}
V/DecodeJob: Retrieved data in 2.563477, load key: EngineKey{model=IMAGE_URL, width=720, height=1134, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=1631874845, transformations={}, options=Options{values={}}}, data: java.nio.DirectByteBuffer[position=0,limit=1010244,capacity=1010244], cache key: IMAGE_URL, fetcher: com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher@428af178, thread: glide-disk-cache-thread-0
V/DecodeJob: Decoded result com.bumptech.glide.load.resource.bitmap.LazyBitmapDrawableResource@42a00390 in 1417.877198, load key: EngineKey{model=IMAGE_URL, width=720, height=1134, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=1631874845, transformations={}, options=Options{values={}}}, thread: glide-disk-cache-thread-0
D/Glide: Finished loading BitmapDrawable from DATA_DISK_CACHE for IMAGE_URL with size [720x1134] in 1515.9301759999998 ms
W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (3840x2160, max=2048x2048)
```

Apparently the image is correctly decoded but, at some point, Glide tries to use an image which is just half of the size of the original one, which is already too big. By setting a listener on the request, the `onLoadFailed` method is called and the cause is `OutOfMemoryException`, however this does not happen when `fitCenter()` is added.

Shouldn't `fitCenter()` be the default downsampling strategy?

**Comment by sjudd** [comment]
The scaling is dictated by the `scaleType` of the `ImageView`. `center` is treated as just the default: https://github.com/bumptech/glide/blob/7fb8b1258a3aabbedad3b8d15f59c8091498160a/library/src/main/java/com/bumptech/glide/RequestBuilder.java#L675. The default is `DownsampleStrategy.AT_LEAST` to maintain backwards compatibility (we didn't use to have the ability to downsample as precisely as fitCenter), which just uses power of two downsampling. 

If you use `fitCenter` as your [`scaleType`][1] it will work as you expect.

[1]: https://developer.android.com/reference/android/widget/ImageView.ScaleType.html
