### ISSUE TITLE
Heap Limit  Scrolling RecycleView 

### ISSUE THREAD

**Issue by lucazin** [bumptech/glide#3019]
**Glide Version**:
glide:3.6.1

**Integration libraries**:
No

**Device/Android Version**:
Galaxy S5 -  SDK 6.0

**Issue details / Repro steps / Use case background**: 

First sorry for my poor english..
I'm facing a issue with glide when i scroll recycleview, (ViewHolder Pattern) i have a chat and this example a have 10 messages with images.  the images have small size.  

When i start scrolling down and up.. after a while the app force close. and a get this 
Background sticky concurrent mark sweep GC freed 37762(3MB) AllocSpace objects, 31(808KB) LOS objects, 0% free, 33MB/33MB, paused 704us total 223.125ms

we can see 0% free.. 

if i comment the line below  and start scrolling again .. its normally, i dont get force close.

Glide.load(Mensagem.getImagem_URL_Servidor().toString()).skipMemoryCache( true ).into(RecebendoImagemHolder.Image);

**Layout XML**:

ImageView 
android:id="@+id/Image_Mine_Answer"
            android:layout_width="240dp"
            android:layout_height="200dp"
            android:layout_marginBottom="16dp"
            android:layout_marginEnd="30dp"
            android:adjustViewBounds="false"
            android:background="@drawable/chat_rounded_rect_bg"
            android:clickable="true"
            android:padding="4dp"
            android:paddingTop="10dp"
            android:scaleType="centerCrop"

```

<!--
What is the error message that you got in the log?
You can find some help on diagnosing issues here: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
-->
**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
D/AndroidRuntime: Shutting down VM
04-11 19:11:19.214 25986-25999/  I/art: Background sticky concurrent mark sweep GC freed 37762(3MB) AllocSpace objects, 31(808KB) LOS objects, 0% free, 33MB/33MB, paused 704us total 223.125ms

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors

**Comment by lucazin** [comment]
I fix the problem using override(width,height) in glide.  Just for show a image 240x200 
anyway thanks for answer!
