### ISSUE TITLE
Placeholder not being replaced with actual image

### ISSUE THREAD

**Issue by guilhermearaujo** [bumptech/glide#302]
My activity has a `ViewPager`. This `ViewPager`'s adapter will load a layout that contains an `ImageView`

The adapter overrides the method:

```java
@Override
public Object instantiateItem(ViewGroup container, int position) {
    Context context = container.getContext();
    View view;
    LayoutInflater layoutInflater = LayoutInflater.from(context);
    
    view = layoutInflater.inflate(R.layout.image_view_tab, container, false);
    com.pkmmte.view.CircularImageView imageView = (com.pkmmte.view.CircularImageView) view.findViewById(R.id.circularImageView);

    Glide.with(context)
            .load(imageURL) // This is a valid URL
            .placeholder(context.getResources().getDrawable(R.drawable.placeholder))
            .into(imageView);

        
    container.addView(view);

    return view;
}
```

The problem is that the placeholder is not replaced after the image is loaded. If I switch to another tab in the `ViewPager` and then switch back, there are two behaviors:
- If the other tab is immediate next to the tab containing the `ImageView` (either left or right), the placeholder will still not be replaced with the image;
- If there is at least one tab between the `ImageView` tab and the second tab I click, then the image will be replaced correctly.

Is anyone able to reproduce this? Am I using the right context instance?

On a second issue, if I decide not to set the placeholder, I can open this activity, but when I press the back button, I get an error `Unable to destroy activity`.

Both these issues only seem to happen when I use the `ViewPager`.

**Comment by sjudd** [comment]
What version of Android and/or Glide are you using? If you replace the CircularImageView class with the standard ImageView, can you still reproduce the problem?

If the problem is reproducible in a sample app, I'd be happy to take a look. The context is correct if your view pager is inside an activity. If it's inside a fragment, you should pass in the fragment instead.

**Comment by guilhermearaujo** [comment]
A ha, you were correct. The problem seems to be the `CircularImageView` class. With the regular `ImageView`, none of the bugs occur. I should have thought that could interfere.

Here's the sample project just in case you want to take a look: https://github.com/guilhermearaujo/GlideSample

**Comment by mooncafes** [comment]
I also meet this bug  happened in listview.

**Comment by TWiStErRob** [comment]
This looks unresolved, check out https://github.com/bumptech/glide/issues/504#issuecomment-113459960 if you want know why it didn't work and how to solve it.
