### ISSUE TITLE
Detect OpenGL texture limit

### ISSUE THREAD

**Issue by jordaneckhardt** [bumptech/glide#3025]
**Glide Version**: 4.5.0

**Integration libraries**: n/a; loading images from filesystem

**Device/Android Version**: Nexus 5 @ API 23, Pixel 2 XL @ API 27

**Issue details / Repro steps / Use case background**: 
I'm using Glide to load images that are multiple pages long, specifically up to a maximum of 15 000 pixels long. This works on a Pixel 2 XL running API 27, but when I try the same thing on a Nexus 5 running API 23, I get a warning that the bitmap is too large to be uploaded into a texture. In this case the image is not loaded at all. 

Is there a way I can detect whether Glide will run into this problem at runtime? Maybe there's a Glide component I could subclass to get this info? I did some research, and it looks like it's easy to get the max texture size from inside OpenGL methods, but not from a view or another higher-level Android object. I presume that Glide accesses these methods, but please correct me if I'm wrong. I also thought of catching the error and handling it, but it looks like it's just a warning; I don't have a stack trace.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(mContext).asBitmap()
    .load(new MyCustomModelLoader(imageFile))
    .apply(requestOptions)
    .diskCacheStrategy(DiskCacheStrategy.NONE)
    .into(new BitmapImageViewTarget(imageView) {
        @Override
        protected void setResource(Bitmap resource) {
            if (resource == null) return;
            Log.d(TAG, "Full card image ready");
            imageView.setImageBitmap(resource);
    }
});
```
```java
@GlideModule
public final class MyAppGlideModule extends AppGlideModule {
    @Override
    public void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        registry.prepend(...);
    }
}
```

**Stack trace / LogCat**:
```
W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (1080x15000, max=4096x4096)
```

**Comment by sjudd** [comment]
Glide doesn't provide any API or use any APIs that expose the texture limit.

**Comment by jordaneckhardt** [comment]
Okay, in case anyone else has this issue, I got the info I needed from this SO post: https://stackoverflow.com/questions/26985858/gles10-glgetintegerv-returns-0-in-lollipop-only
