### ISSUE TITLE
How to add a local image to glide's disk cache?

### ISSUE THREAD

**Issue by LuYeCong** [bumptech/glide#3027]
**Glide Version : 4.4.0**
In our app, after I send a local image that is on disk to others by network, the image message will be replaced by a url, and I don't want to download the image from network again. 
So I want to add the image to glide's disk cache after I get a url from server, and mark the url as the key of the local image.

How can I do this?  Thank you.

**Comment by sjudd** [comment]
You can't do this directly. You can write a custom ModelLoader that loads the image from your local cache after you download it. You can also use Glide to download the image into Glide's cache if your primary purpose is to display it.

http://bumptech.github.io/glide/tut/custom-modelloader.html
http://bumptech.github.io/glide/javadocs/470/com/bumptech/glide/RequestManager.html#downloadOnly--
