### ISSUE TITLE
Image view refresh when load bitmap image

### ISSUE THREAD

**Issue by MoustafaElsaghier** [bumptech/glide#3029]
**Glide Version**:4.6.1
**Device/Android Version**:Huawie Gr5

**Issue details / Repro steps / Use case background**: 
I have a bitmap image and I need to load it in image view with glide
`        Glide.with(this).load(fixedReflection).into(mCaptureImage);
`
but unfortunately, I get the image refresh when try to load it.
the reason why I use glide instead of 
`mCaptureImage.setImageBitmap(fixedReflection);`
 is that this way leads to image distortion by scaling width down but gllide not.

after a long search, I found a way to set placeholder but it does not work with bitmap and there are no old images may I have it is just one image captured from the camera. 

I hope to find a solution for this soon whether with glide or suggest some way to achieve what I need be done.

thank you

**Comment by sjudd** [comment]
I'm not totally clear what you're asking? What do you mean by "image refresh"?

**Comment by MoustafaElsaghier** [comment]
for more clarification, this is code I use for displaying the image 
```
Glide.with(this).asBitmap()
                .load(fixedReflection)
                .into(mCaptureImage);
```

then I use `mCaptureImage.setVisibility(View.VISIBLE);`

where fixedReflection refer to the bitmap variable I need to display it.

I think you might would suggest to use `mCaptureImage.setImageBitmap(fixedReflection);` 
but this won't fit the image in its size as I required in the description. 

Hope to get a solution from you ASAP
