### ISSUE TITLE
Program type already present: android.support.design.widget.CoordinatorLayout$1

### ISSUE THREAD

**Issue by yeswsx** [bumptech/glide#3032]
compile error 
> Program type already present: android.support.design.widget.CoordinatorLayout$1
Message{kind=ERROR, text=Program type already present: android.support.design.widget.CoordinatorLayout$1, sources=[Unknown source file], tool name=Optional.of(D8)}

glide version
> com.github.bumptech.glide:glide:4.7.1

android sdk
> compileSdkVersion 26

gradle
```java
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:support-v4:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'com.google.code.gson:gson:2.8.2'
    implementation 'com.github.bumptech.glide:glide:4.7.1'
}
```

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/download-setup.html#android-sdk-requirements

**Comment by yeswsx** [comment]
Thanks.

**Comment by fededri** [comment]
I have the same problem, all seems to be correct:

`
ext.supportLibVersion = '27.0.2'
  compileSdkVersion 27
    buildToolsVersion '27.0.3'

   implementation "com.android.support:appcompat-v7:${supportLibVersion}"
    implementation "com.android.support:design:${supportLibVersion}"
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'

implementation 'com.github.bumptech.glide:glide:4.6.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.6.1'

`

**Comment by PaPZzzDNightmare** [comment]
add
`implementation `'com.android.support:design:27.1.0``
to app level build.gradle

**Comment by Jolanrensen** [comment]
How about the new `implementation 'com.google.android.material:material:1.0.0-alpha3'`? This would replace com.android.support:design, but I still get the same CoordinatorLayout error as before (I even excluded group "com.android.support" as described above.

**Comment by hiteshcla00** [comment]
i got this error plz help
Program type already present: android.support.v4.app.LoaderManager |  
null |  
java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\1.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\2.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\3.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\50.jar |  
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\1.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\2.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\3.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\50.jar |  
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException |

**Comment by zhouxuemeng1988** [comment]
implementation ("com.github.bumptech.glide:glide:4.8.0") {
    exclude group: "com.android.support"
  }

**Comment by farhananwar187** [comment]
> add
> `implementation `'com.android.support:design:27.1.0``
> to app level build.gradle
Thank you so much PaPZzzDNightmare . you saved my time :-)

**Comment by farhananwar187** [comment]
add
implementation 'com.android.support:design:27.1.0``
to app level build.gradle

It worked for me.

**Comment by hingu-nilesh** [comment]
I got this error Please help me to resolve this.

Error: Program type already present: com.bumptech.glide.MemoryCategory

Here is my All dependency:
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    // library for user interface
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.balysv:material-ripple:1.0.2'
    implementation 'com.android.support:support-v4:27.1.1'

    // library for api
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.0'
    implementation 'com.google.code.gson:gson:2.8.5'


    // others library
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'com.google.android.gms:play-services-analytics:16.0.7'
    implementation 'com.google.firebase:firebase-messaging:17.4.0'
    implementation 'com.google.android.gms:play-services-ads:17.1.3'
    implementation 'com.google.android.gms:play-services-maps:16.1.0'
    implementation 'com.google.android.ads.consent:consent-library:1.0.7'
    implementation 'com.google.maps.android:android-maps-utils:0.4.4'
    implementation 'com.google.android.libraries.places:places:1.0.0'
    //searchable spinner library
    implementation 'com.toptoche.searchablespinner:searchablespinnerlibrary:1.3.1'

    //gallery library
    implementation 'com.github.darsh2:MultipleImageSelect:3474549'

    // library for loader image
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    implementation 'com.android.support:design:27.1.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'

}

**Comment by Noble-Shiva** [comment]
In build.gradle (Module: app) ---> please add

implementation 'com.android.support:design:27.1.0'

Hope it helps!
