### ISSUE TITLE
Image view with 9 patch place holder

### ISSUE THREAD

**Issue by gowsikreloaded** [bumptech/glide#3033]
Hi 

 I am using glide to load image from the Url based on the device dpi, so I want the Image view to wrap content but I am having a place holder which is a 9patch image in a layer list.

How can I set the width and height of the place holder or the min height of the image view

**Comment by sjudd** [comment]
Please fill out the [issue template][1] when filing new issues. 

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md
