### ISSUE TITLE
.get() method never returns on OpenGL thread

### ISSUE THREAD

**Issue by EdvinasKilbauskas** [bumptech/glide#3036]
Hi, I'm trying to implement glide into my OpenGL ES 2.0 game, but I'm having problems.
I'm using glide version 4.7.1. Whenever I call .get() method it just freezes and never returns anything. I get no error messages and no exceptions. Any ideas on how to fix this? 

I'm running this code on OpenGL thread:

`bitmap = Glide.with(gameSystem).asBitmap().load("file:///android_asset/" + bitmapPath).submit().get()`

In my build.gradle I have this:
`dependencies {

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    kapt 'com.github.bumptech.glide:compiler:4.7.1'
    implementation ("com.github.bumptech.glide:glide:4.7.1") {
        exclude group: "com.android.support"
    }

    implementation "com.android.support:support-fragment:27.1.0"
}`

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/debugging.html.

**Comment by EdvinasKilbauskas** [comment]
Enabled debugging. Now the only message it shows is
`Discovered AppGlideModule from annotation: com.extrabitgames.framework3d.GameGlideModule`

I now also changed 
`bitmap = Glide.with(gameSystem).asBitmap().load("file:///android_asset/" + bitmapPath).submit().get()`
to
`bitmap = GlideApp.with(gameSystem).asBitmap().load("file:///android_asset/" + bitmapPath).submit().get()`

But results are still the same. Am I doing something wrong?

**Comment by sjudd** [comment]
It's a little hard to tell. I'd suggest trying to get a thread dump and seeing if you can figure out what Glide's threads are doing. There is some passing of messages back and forth across threads. if `get()` blocks forever without triggering any errors, it implies there's deadlock somewhere.
