### ISSUE TITLE
use glide 4.7.1  load gif have memory leak

### ISSUE THREAD

**Issue by huanbin** [bumptech/glide#3039]
D/Glide: Finished loading Bitmap from LOCAL for com.bumptech.glide.gifdecoder.StandardGifDecoder@a044393 with size [550x1821] in 37.482811999999996 ms
D/Glide: Finished loading Bitmap from LOCAL for com.bumptech.glide.gifdecoder.StandardGifDecoder@a044393 with size [550x1821] in 37.482811999999996 ms
D/Glide: Finished loading Bitmap from LOCAL for com.bumptech.glide.gifdecoder.StandardGifDecoder@a044393 with size [550x1821] in 37.482811999999996 ms

the memory monitor ，you can see memory go up from 50m to 200m

**Comment by sjudd** [comment]
Decoding GIFs is definitely expensive. Memory leak implies that the memory is never released. If you stop playing the animated GIF (ie clear the corresponding Targets) is the memory released?
