### ISSUE TITLE
Why svg is not working with AppCompatActivity? Its only working with Activity.

### ISSUE THREAD

**Issue by tareq3** [bumptech/glide#3040]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Please fill out the template when filing new issues. What version of Glide are you using? Consider attaching [a failing test case][1] or a sample app that reproduces the issue if you're on v4+

[1]: http://bumptech.github.io/glide/tut/failing-test-cases.html
