### ISSUE TITLE
Glide 4.6 while enter an activity load picture gleam

### ISSUE THREAD

**Issue by HashWaney** [bumptech/glide#3045]
‘’‘
@SuppressWarnings("unchecked")
    public void displayRound(Context context,ImageView mView,String url,int placeHolder,int round){
        RequestOptions options=RequestOptions.
                bitmapTransform(new MultiTransformation(new CenterCrop(), new GlideRoundTransform(context, round)))
                .dontAnimate()
                .error(placeHolder)
                .placeholder(placeHolder);
        Glide.with(context)
                .load(url)
                .apply(options)
                .transition(GenericTransitionOptions.withNoTransition())
                .into(mView);
    }
‘’’
‘’‘
GlideRoundTransform is custome：

public class GlideRoundTransform extends BitmapTransformation {

    private static final String ID = "com.bumptech.glide.transformations.FillSpace";

    private static float radius = 0f;

    public GlideRoundTransform(Context context) {
        this(context, 4);
    }

    public GlideRoundTransform(Context context, int dp) {
        super(context);
        this.radius = Resources.getSystem().getDisplayMetrics().density * dp;
    }

    @Override protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
        return roundCrop(pool, toTransform);
    }

    private static Bitmap roundCrop(BitmapPool pool, Bitmap source) {
        if (source == null) return null;

        Bitmap result = pool.get(source.getWidth(), source.getHeight(), Bitmap.Config.ARGB_8888);
        if (result == null) {
            result = Bitmap.createBitmap(source.getWidth(), source.getHeight(), Bitmap.Config.ARGB_8888);
        }
        Canvas canvas = new Canvas(result);
        Paint paint = new Paint();
        paint.setShader(new BitmapShader(source, BitmapShader.TileMode.CLAMP, BitmapShader.TileMode.CLAMP));
        paint.setAntiAlias(true);
        RectF rectF = new RectF(0f, 0f, source.getWidth(), source.getHeight());
        canvas.drawRoundRect(rectF, radius, radius, paint);
        return result;
    }

    public void updateDiskCacheKey(MessageDigest messageDigest) {
        try {
            messageDigest.update(ID.getBytes("UTF-8"));
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }
}

‘’‘’

so i use this function load RecycleView item 

'''
  GlideUtil.sharedInstance().displayRound(helper.getContext(),
                    avatar,
                    StringUtil.formatString(bean.getPic(), ""),
                    R.color.gray_f5_bg,4);

'''
i don't know how i do this problem，recently， i just load the rectangle picture # @jzting

**Comment by sjudd** [comment]
I'm not really sure what you're asking?

**Comment by HashWaney** [comment]
yap!  i just have no idea for this api  BitmapTransformation {@link RoundedCorners() }, after use the api to resolve my problem.
