### ISSUE TITLE
Using Newer version of Glide Library(4.7.1) causing Binding error issue

### ISSUE THREAD

**Issue by asifsb15** [bumptech/glide#3049]
When I tried using a newer version of Glide Library gives me Binding Error in all the file. The moment I revert back to the older version, it works.

The version I was using:

api 'com.github.bumptech.glide:glide:4.3.0'

Newer Version I updated:
dependencies {
    compile 'com.github.bumptech.glide:glide:4.7.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
}

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

What specifically is the error?

**Comment by sjudd** [comment]
Can you include a stack trace? I'm not sure what you mean by binding classes? Are you using some form of dependency injection?
