### ISSUE TITLE
Work with AppGlideModule - not possible.

### ISSUE THREAD

**Issue by foodied** [bumptech/glide#3057]
Manually setting up default options in Glide using `AppGlideModule` shows error in `GlideBuilder`'s build method. 

This was probably done due to the issue #2885, which makes sense. 

**Glide Version**: 4.7.0 and above.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideBuilder.build(context)
```

Is there any way how we're supposed to manually set up the default options throughout the app provided that we only use ```GlideBuilder``` only inside ```AppGlideModule``` ? 

If annotation processing needs to be avoided, are there any available optimised presets we can use or parameters to be passed or configuring cache paths and sizes that would be common to the app ?

**Comment by sjudd** [comment]
AppGlideModule will only work with annotation processing? What specifically are you trying to do in AppGlideModule?

**Comment by foodied** [comment]
@sjudd I want to use `GlideApp` instead of Glide and keep a common configuration where I would mention the disk cache, memory and bitmap pool size. Also, increase the timeout in `OkHttpClient` library. How could I be able to achieve this? Thanks!

**Comment by sjudd** [comment]
You can't do that without annotation processing. If you want GlideApp and configuration see http://bumptech.github.io/glide/doc/configuration.html. If you want configuration without annotation processing, use the deprecated GlideModule interface.
