### ISSUE TITLE
ModelLoader context via ModelLoaderFactory

### ISSUE THREAD

**Issue by rcketscientist** [bumptech/glide#3061]
I suspect I'm somehow missing something trivial, but I've hunted through the docs and issues.  How do we get a context to a `ModelLoader` built via the `ModelLoaderFactory`?  We can't store the context in the factory, so there must be some way to inject it into the `build`?

**Comment by rcketscientist** [comment]
Is this so unusual? It's explicitly mentioned in the factory, but no mention in docs (that I found) as to how to do this.

**Comment by sjudd** [comment]
Pass a `Context` into the constructor of your `ModelLoaderFactory`.

**Comment by rcketscientist** [comment]
Thanks for the reply.

It's the `ModelLoader` that needs it, so the factory would then have to store it.  Which is a leak issue as you've mentioned here:

>Will be retained statically so should not retain {@link Context}

The warning makes sense to me.  Am I missing something in how the context would be used for the builder?

```
   RawModelLoaderFactory(Context c) {
        context = c;
    }

    @NonNull
    @Override
    public ModelLoader<MetadataTest, InputStream> build(@NonNull MultiModelLoaderFactory multiFactory) {
        RawModelLoader loader = new RawModelLoader(context);
...
```

I could change it to pass file descriptors around, but I prefer to do the SAF conversion as late as possible for debugging purposes.

**Comment by rcketscientist** [comment]
bump

**Comment by sjudd** [comment]
Sorry I missed your reply. You can pass the application context in safely.

**Comment by rcketscientist** [comment]
_sigh_, yah that makes sense, lol. Thanks.
