### ISSUE TITLE
Gif not loading after second time.

### ISSUE THREAD

**Issue by lucazin** [bumptech/glide#3063]
**Glide Version**:
3,8

**Integration libraries**:

**Device/Android Version**:
7,0 s7 edge

**Issue details / Repro steps / Use case background**: 

First time when i enter in chat fragment,  loads OK! , but if switch fragment and go back to chat fragment the gif animation not load anymore,  just stay a thumbnail stucked.  i'm stuck with this for along 3 days..
 i cant fix that 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java

Glide.with(getcontext)
				.load(LoadUrl)
				.asGif()
				.diskCacheStrategy(DiskCacheStrategy.SOURCE)
				.priority(Priority.IMMEDIATE)
				.placeholder(R.drawable.carregando_gif)
				.override(240,200)
				.listener(new RequestListener<String, GifDrawable>() {
					
					@Override
					public boolean onException(Exception arg0, String arg1,Target<GifDrawable> arg2, boolean arg3) {
						return false;
					}
					
					@Override
					public boolean onResourceReady(GifDrawable gif, String arg1, Target<GifDrawable> arg2, boolean arg3, boolean arg4) {
						
						
						return false;
					}
				})
				.into(LoadIn);


```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
I don't have any immediate ideas. If you're able to reproduce on v4 let me know.

**Comment by lucazin** [comment]
I dont know if this is a real solution, but i add these lines in glide 

.signature(new StringSignature(String.valueOf(System.currentTimeMillis())))
.skipMemoryCache(true)
.placeholder(R.drawable.loadinggif)

its working, but its strange if a remove placeholder gif not load anymore

**Comment by sjudd** [comment]
Sounds like the view might not ever acquire a valid size unless you use the placeholder. Maybe see http://bumptech.github.io/glide/doc/debugging.html#missing-images-and-local-logs

**Comment by lucazin** [comment]
I trying all things.. but the error persist my friend
Can you help me again?  @sjudd
