### ISSUE TITLE
hi how can i use svg in glide v3.8.0 can't update right now so if there is a way please suggest

### ISSUE THREAD

**Issue by balsikandar** [bumptech/glide#3064]
**Glide Version**: 3.8.0

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
There's a sample app that demonstrates how to do so here: https://github.com/bumptech/glide/tree/211c4dbd79d92dcc56f186d0dd8b50849f9236ff/samples/svg

**Comment by balsikandar** [comment]
One last thing, Link shared above does it works on all andoid sdk version >= 15
