### ISSUE TITLE
Change executor threads number in runtime [enhancement]

### ISSUE THREAD

**Issue by isabsent** [bumptech/glide#3066]
I am developing a file manager supporting encryption and have to load image content as an `InputStream` from encrypted container which was written on `C++` (attached as `.so` library) and there is no opportunity to read from it by multiple threads. My requirement is to read images with one thread when user reads from a file system inside of such container and read by multiple threads when user reads from Android file system or from file system on a cloud. I have read [#1304](https://github.com/bumptech/glide/issues/1304) , [#799](https://github.com/bumptech/glide/issues/799) and [#925](https://github.com/bumptech/glide/issues/925) and I am able to create `StreamModelLoader`, `DataFetcher` and `GlideModule` with overridden threads number:

    public class CustomGlideModule implements GlideModule {
        
        @Override
        public void applyOptions(Context context, GlideBuilder builder) {
            ViewTarget.setTagId(R.id.glide_tag_id);
            builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
            builder.setResizeService(new FifoPriorityThreadPoolExecutor(1));
        }
    
        @Override
        public void registerComponents(Context context, Glide glide) {
            glide.register(IFile.class, InputStream.class, new FileLoader.Factory());
        }
    }
but further it is required to register `CustomGlideModule` in the `AndroidManifest` for `Glide v.3` and annotate somehow for `Glide v.4`. After it the opportunity to change executor threads number in runtime disappears. Would you be so kind to provide for this use case in future `Glide` version?

**Comment by sjudd** [comment]
You can still set the executor services and register model loaders via GlideModules in v4, see http://bumptech.github.io/glide/doc/configuration.html#application-options

**Comment by isabsent** [comment]
> You can still set the executor services and register model loaders via GlideModules in v4

Yes I can, but I can't change number of executor threads  in runtime in v4. Am I right?

**Comment by sjudd** [comment]
@isabsent sorry I missed your response. Yes you can only set the number of threads via a GlideModule. You can't adjust them after Glide is initialized.

**Comment by isabsent** [comment]
Ok, thanks! I hope you will give us an opportunity to change it in runtime in Glide 5.0 :)
