### ISSUE TITLE
Glide is leaking the memory Trying to retry Image loading when glide fail to load 

### ISSUE THREAD

**Issue by hussainahmad** [bumptech/glide#3067]
**Glide Version**:4.6.1

**Integration libraries**:
**Okhttpversion**:4.6.1

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
private void loadImage(ViewHolder holder, int position) {
WeakHandler mHandler = new WeakHandler();
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                loadImage(holder, position);
            }
        };
Glide.with(context).
load(getUri(position))
                .apply(getFitCenter())
                .listener(new Listener() {
                    @Override
                    public void onRetry() {
                        mHandler.postDelayed(runnable, 2500);
                        handlerRunnableMapCategory.put(mHandler, runnable);
                    }
                })
                .into(imagViewProduct);
```
WeakHandler is [`Memory safer implementation of android.os.Handler `](https://github.com/badoo/android-weak-handler)
Here `handlerRunnableMapCategory` is a map where I am storing the instance of handler and runnable, and In `onDestroy` I am clearing the map and `removeCallbacksAndMessages` ,  And Its is working, but still I am getting Leak through LeakCanary
![screenshot_2018-05-03-16-10-05](https://user-images.githubusercontent.com/5903522/39574034-180e2244-4eef-11e8-884f-7ee14353c27b.png)

**Comment by hussainahmad** [comment]
![screenshot_2018-05-03-19-50-32](https://user-images.githubusercontent.com/5903522/39584312-9372047a-4f0b-11e8-8b4a-64a647e9f388.png)

**Comment by sjudd** [comment]
`handlerRunnableMapCategory` in the first example is leaking memory regardless of the weak handler. None of the weak handler or runnables you're using above should be necessary.

Glide will keep a reference to the Target as long as the request is in progress. You can cancel them manually via `Glide.with(Context/Fragment/Activity)).clear(Target). If you use the appropriate lifecycle (Activity/Fragment) Glide will clear pending requests when the lifecycle goes through `onDestroy`.

**Comment by hussainahmad** [comment]
But without `handler` it will crash the app with the reason `java.lang.IllegalStateException: You can't start or clear loads in RequestListener or Target callbacks. If you must do so, consider posting your into() or clear() calls to the main thread using a Handler instead` [use Handler#post to post your into()](https://github.com/bumptech/glide/releases/tag/v4.2.0) ,  and I debugged `handlerRunnableMapCategory ` is clearing and and setting null in `onDestroy` , Is there any  best approach to retry image in `onLoadFailed` ?

**Comment by sjudd** [comment]
Ah sorry I missed that onRetry is called in Glide's RequestListener callback. In that case you do need to post, though without a delay.

In what I can see of the leak stack traces, it looks like the Glide request hasn't been cleared. If the `Context` you're using is not the activity context, you'll need to clear the request manually with `Glide.with(context).clear(target)`.

**Comment by hussainahmad** [comment]
@sjudd  I am using `ApplicationContext`, I think that's the issue. So `Glide` is unable to clear, I have to do this manually.
