### ISSUE TITLE
Glide crashes when asked to load a .jpg that's actually a .gif.

### ISSUE THREAD

**Issue by ekhaled667** [bumptech/glide#3069]
So, I'm loading photos from imgur using Glide 4.6.1 with the code below.

```java
ViewTarget viewTarget = new ViewTarget<SubsamplingScaleImageView, BitmapDrawable>(image_view) {
                    @Override
                    public void onResourceReady(BitmapDrawable bitmap, Transition<? super BitmapDrawable> transition) {
                        this.view.setImage(ImageSource.bitmap(bitmap.getBitmap()));
                    }
                };
                GlideApp.with(this).load(post_to_show.getUrl()).into(viewTarget);
```

where SubsamplingScaleImageView is - well - a Custom image viewer extending View. But it doesn't matter here.

It's working fine, until I try loading something like [this](https://i.imgur.com/DyPF53S.jpg)

It has a .jpg extension, but it's a gif.

I get this error:

> E/AndroidRuntime: FATAL EXCEPTION: main Process: me.ekhaled667.ridit, PID: 6202 java.lang.ClassCastException: com.bumptech.glide.load.resource.gif.GifDrawable cannot be cast to android.graphics.drawable.BitmapDrawable at me.ekhaled667.ridit.PostFragment$1.onResourceReady(PostFragment.java:257) at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:579) at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:549) at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:218) at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:324) at android.os.Handler.dispatchMessage(Handler.java:98) at android.os.Looper.loop(Looper.java:163) at android.app.ActivityThread.main(ActivityThread.java:6348) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

How can I detect that it's not an image, or at least evade the FATAL EXCEPTION altogether?

**Comment by sjudd** [comment]
This is actually your application crashing, not Glide: ``me.ekhaled667.ridit.PostFragment$1.onResourceReady(PostFragment.java:257)``. You're casting a generic Drawable that Glide returns to a ``BitmapDrawable``, which, as you've discovered, is unsafe.

If you always want a static image, use `asBitmap()`:

```java
Glide.with(fragment)
  .asBitmap()
  .load(url)
  .into(target);
```

**Comment by ekhaled667** [comment]
Thanks for the response.
I know have another problem if you can look at [it](https://github.com/bumptech/glide/issues/3078).
