### ISSUE TITLE
Verifier rejected class com.bumptech.glide.load.resource.bitmap.Downsampler as Dexguard

### ISSUE THREAD

**Issue by aerdy** [bumptech/glide#3071]
**Glide Version**: com.github.bumptech.glide:glide:4.7.1

**Integration libraries**:
implementation 'com.github.bumptech.glide:glide:4.7.1'
    implementation 'com.github.bumptech.glide:annotations:4.7.1'
    implementation "com.github.bumptech.glide:okhttp3-integration:4.7.1"
    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'

**Device/Android Version**: All Version

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
RequestOptions requestOptions = new RequestOptions()
                .error(R.mipmap.bg_header)
                .signature(new ObjectKey("test"));
        Glide.with(context)
                .load(url)
                .apply(requestOptions)
                .transition(DrawableTransitionOptions.withCrossFade(500))
                .into(source);
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
Verifier rejected class com.bumptech.glide.load.resource.bitmap.Downsampler: android.graphics.Bitmap com.bumptech.glide.load.resource.bitmap.Downsampler.ˊ(java.io.InputStream, android.graphics.BitmapFactory$Options, com.bumptech.glide.load.resource.bitmap.Downsampler$DecodeCallbacks, com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool) failed to verify: android.graphics.Bitmap com.bumptech.glide.load.resource.bitmap.Downsampler.ˊ(java.io.InputStream, android.graphics.BitmapFactory$Options, com.bumptech.glide.load.resource.bitmap.Downsampler$DecodeCallbacks, com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool): [0x2C] copy1 v4<-v3 type=Reference: java.lang.IllegalArgumentException cat=1 (declaration of 'com.bumptech.glide.load.resource.bitmap.Downsampler' appears in /data/app/com.privygate.privyid-aZpGake0CDGX0di0kUIu6g==/base.apk)

**Comment by sjudd** [comment]
Let me know if you have a specific question. This looks like a build error in your application.

**Comment by fengshi92** [comment]
For me, I added -keep public class com.bumptech.glide.load.resource.bitmap.Downsampler { *; } to make it work.
