### ISSUE TITLE
How can i load images from cache when i go offline ? i have used   .diskCacheStrategy(DiskCacheStrategy.ALL) but not working. once i kill app and reopen it Image is not loading from Cache.

### ISSUE THREAD

**Issue by kushanshah11** [bumptech/glide#3073]
**3.7.0**:

**Integration libraries**:

**MOTO G2/5.0**:

**Issue details / Repro steps / Use case background**: 

**Glide.with(mContext).load(url + arrAircrafts.get(position).getPicture())
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .error(R.drawable.ic_no_image)
                .into(holder.image);**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by salmaanahmed** [comment]
Any update on this?
I am facing the same issue, doing it the same way and also added
onlyRetrieveFromCache(true)
