### ISSUE TITLE
Does it have search option?

### ISSUE THREAD

**Issue by jamilxt** [bumptech/glide#3076]
If not, will you add it please? :)
It will come in handy very much. 
And Thanks for the great library. :+1: 
Really grateful to you. <3

**Comment by sjudd** [comment]
Glide loads images, I'm not sure what a search option means? It's probably out of scope for the library though. If you want to display a grid of photos and let users search in them, Glide could help you load the images you display in your grid, but it wouldn't provide support for drawing the grid or running the search if that makes sense?
