### ISSUE TITLE
Adding Zoom in Zoom out to Glide

### ISSUE THREAD

**Issue by dnisharar** [bumptech/glide#3079]
I have tried searching and I wanted help on how I can add Zoom in and out functionalities to Glide. I want to be able to zoom in an image on display and out to normal state when done. How can I do this.

```
     ImageView imageViewPreview = view.findViewById(R.id.image_preview);
            Image image = images.get(position);
            Glide.with(getActivity()).load(image.getLarge())
                    .thumbnail(0.5f)
                    .crossFade()
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .into(imageViewPreview);

```

**Comment by sjudd** [comment]
Glide is an image loading library, not a general UI library. Pinch to zoom code would be out of scope. There are a few open source pinch to zoom libraries, like https://github.com/chrisbanes/PhotoView

**Comment by dnisharar** [comment]
Thank you for that clarification.

**Comment by MarcellHarmaci** [comment]
For anyone still stumbling upon this issue, here's a more modern solution implemented in Kotlin: [https://github.com/MikeOrtiz/TouchImageView]()
