### ISSUE TITLE
How to update an imageview with higher resolution image once small resolution is loaded?

### ISSUE THREAD

**Issue by mdeora** [bumptech/glide#308]
Is there any way we can update the imageview with higher resolution image by initiating a new request once smaller resolution image is loaded?

**Comment by TWiStErRob** [comment]
For info: look for "Thumbnail support" at [new features of 3.0](https://github.com/bumptech/glide/wiki)

For docs: look for `thumbnail` in [`*RequestBuilder`](http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/DrawableRequestBuilder.html#thumbnail(com.bumptech.glide.DrawableRequestBuilder))

For example: look for `fullRequest` and `thumbRequest` in [`FlickrPhotoList`](https://github.com/bumptech/glide/blob/master/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrPhotoList.java)

**Comment by mdeora** [comment]
Thanks, it serves the purpose.
