### ISSUE TITLE
Android Glide: on resource ready is taking some time to execute.

### ISSUE THREAD

**Issue by svidata** [bumptech/glide#3083]
Hello glide team and thanks for this great library.

I am trying to compress a bitmap and resize it before saving it to a file on the android's internal storage, the steps that I used are these:

1) Read the original bitmap using glide and get the bitmap from the on resource ready call back.

2) Inside the call back I compare the bitmap width and height against my (max width and max height) which are the limits.

3) I adjust the bitmap size using the Bitmap.createScaledBitmap(....) function provided by android.

4) I save the bitmap to an output file on storage.

In code it looks like this:

```java
private static final float max_width = 1240.0f;
private static final float max_height = 1240.0f;
private static final float max_ratio =max_width/max_height ;


//I read the bitmap using glide
 Glide.with(context).asBitmap().load(image_path).into(new SimpleTarget<Bitmap>(){
 @Override
  public void onResourceReady(@NonNull Bitmap source , @Nullable Transition<? super Bitmap> tranistion){
  //now here I check the size of my bitmap which is called here (source).
  
   int bitmap_width = source.getWidth();
   int bitmap_height = source.getHeight();
   float normal_ratio = (float)bitmap_width / (float)bitmap_height;
  
    Bitmap compressed_bitmap=null;
    if(bitmap_height > max_height || bitmap_width > max_width){
     //compress
     int width=0;
     int height=0;
     
        if(ratio<max_ratio){
         width = (int)((max_height/bitmap_height) * bitmap_width);
         height = (int) max_height;
        }else if(ratio > max_ratio){
         height = (int)( (max_width)/ bitmap_width ) * bitmap_height);
         width = (int) max_width;
        }else{
         height = (int) max_height;
         width = (int) max_width;
         }
     compressed_bitmap = Bitmap.createScaledBitmap(source , width , height , false);     
  
     }else{
     //keep as is
     compressed_bitmap = source;
     }

    //save to a output file
    saveCompressedBitmap(compressed_bitmap);

 }

});
```

**Note: I am using glide to read the bitmap before compressing inorder to avoid out of memory error when I am trying to read large bitmaps like 5mb and above.**

My question is why its taking onResourceReady some time to execute? Is there a better way to read bitmap using glide for my case?

As I said in the note above, I am trying to avoid reading insample size and stuff like that to read large bitmaps..... so am I doing it correctly? Is there a better way?

**Comment by sjudd** [comment]
`saveCompressedBitmap(compressed_bitmap);` is probably the most expensive part. See https://developer.android.com/studio/profile/ if you want to know specifically.

If you're trying to write a resized and compressed Bitmap in the background, you can use Glide to help you, but you should still run your request on a background thread.

Once you have your thread started, you can do something like:

```java
RequestOptions options = new RequestOptions().centerInside();
Future<Bitmap> future = 
    Glide.with(context)
      .asBitmap()
      .load(image_path)
      .apply(options)
      .submit(max_width, max_height);

Bitmap bitmap;
try {
  bitmap = future.get();
} catch (...) {
...
}

saveCompressedBitmap(compressed_bitmap);
```

You can use ``AsyncTask``, ``HandlerThread`` or just a simple Java ``Executor`` to run the code above on a background thread.

Using ``centerInside`` and providing your max_width and max_height will return the original image if it is smaller than your maximums or a downsized image if it's greater than your maximums. You don't need to re-write that code yourself.

**Comment by svidata** [comment]
@sjudd  I tested your answer and it is working fine now, thank you. Just one question what is the use of `centerInside` ? And does this solution work for any bitmap size (5mb and above) the kind of images that come from the camera?

**Comment by sjudd** [comment]
Check out the javadoc for center inside: http://bumptech.github.io/glide/javadocs/470/com/bumptech/glide/load/resource/bitmap/DownsampleStrategy.html#CENTER_INSIDE
