### ISSUE TITLE
CrossFade animation work wrong when with translucence png bitmap 

### ISSUE THREAD

**Issue by bambootang** [bumptech/glide#3084]
we use glide v4.7.1 

when we use .transition(withCrossFade()) api . the placeholder drawable will mix with remote bitmap.

sample code:

    com.bumptech.glide.Glide
        .with(this)
        .load("http://puui.qpic.cn/vcolumn_pic/0/c9fda6c359159b4cdb9bcf7caec1333aT1525419093.png/0")
        .apply(RequestOptions.placeholderOf(new ColorDrawable(Color.GREEN)))
        .into(iv_);

![_20180514133755](https://user-images.githubusercontent.com/5106326/39980022-52b24d90-577c-11e8-8b71-878c892edd78.png)

----

when use .transition(withCrossFade()) api 

    com.bumptech.glide.Glide
        .with(this)
        .load("http://puui.qpic.cn/vcolumn_pic/0/c9fda6c359159b4cdb9bcf7caec1333aT1525419093.png/0")
        .apply(RequestOptions.placeholderOf(new ColorDrawable(Color.GREEN)))
        .transition(withCrossFade())
        .into(iv_);

![_20180514134254](https://user-images.githubusercontent.com/5106326/39980107-c0d12ab2-577c-11e8-9ea3-00aa89c7c362.png)

how do i resolve it ?

I hope you can understand my chinglish. O(∩_∩)O

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/transitions.html#common-errors
