### ISSUE TITLE
Glide cache breaks or loads the wrong images

### ISSUE THREAD

**Issue by lam-amsiq** [bumptech/glide#3085]
**Glide Version**: 4.7.1.

**Device/Android Version**: All devices (Samsung Galaxy s3 4.4.4, LG Nexus 8.0.0,Samsung Galaxy S7 7.0, etc.)

**Issue details / Repro steps / Use case background**: 
Cached images are sometimes either broken or wrong images when reused. E.g. The bottom pattern (text bubbles) will be text text bubbles everywhere the pattern is used when it's supposed to be stars.

**Cache error:**
![cache bug](https://user-images.githubusercontent.com/31532839/39982500-e04228d8-5754-11e8-8136-44a705558a8c.png)

**Correct page:**
![cache fine](https://user-images.githubusercontent.com/31532839/39983306-803eac06-5757-11e8-86bb-8dd65edd665f.png)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
Mostly used like this
```java
        drawable?.let { drawableInner ->
            v?.let { view ->
                context?.let { context ->
                    Glide.with(context)
                            .load(drawableInner)
                            .apply(RequestOptions()
                                    .placeholder(R.drawable.as_shared_placeholder_empty)
                                    .fitCenter())
                            .into(view)
                }
            }
        }
```

**Comment by sjudd** [comment]
If you're using resource ids exclusively, see the comments in the javadoc: http://bumptech.github.io/glide/javadocs/470/com/bumptech/glide/RequestBuilder.html#load-java.lang.Integer-

**Comment by lam-amsiq** [comment]
We are trying to use AppCompatResources.getDrawable() instead of resource id to load all drawables before inserting them with glide to see if it eliminates the problem
