### ISSUE TITLE
when the image off screen stop gif Decodethread

### ISSUE THREAD

**Issue by lhjandroid** [bumptech/glide#3089]
you said
In Glide 4.4.0, I'll add an (experimental) API called clearOnDetach (name may change, suggestions welcome). clearOnDetach will free up resources used by ViewTargets when the View is detached from it's window and automatically restart the request if the View is ever reattached. That method is primarily meant for reducing memory usage, but it will also help reduce the number of running GIFs by pausing those as soon as they go off screen. I've seen this help significantly in RecyclerView, which doesn't set visibility for off screen views and doesn't call its RecyclerListener for every view that's off screen. I may also try to just build this in to ViewTarget so that it happens automatically.

is it work for ScrollView? ScrollView seem to not touch onDeach,and when in viewpager form page1 to page2 .if the page1 have a gif when change to page2 the page1 is still decode the gif stream.is there any to stop the page1's gifs?

in the GidDrawable
```
@Override
public boolean setVisible(boolean visible, boolean restart) {
 isVisible = visible;
 if (!visible) {
 stopRunning();
 } else if (isStarted) {
 startRunning();
 }
 return super.setVisible(visible, restart);
}

```
it means if i set ImageView to be gone it will stop decode?

l also try other ways.
i just record the page1's all gif views and when the page1 is not visibilitytouser i for each to let image's drawable to paly once.
i also try when page1 is not visibilitytouser i code Glide.with(fragment).onDestory() and it seem to be work;

the two ways are not well,are you have more suggestions.

**Comment by sjudd** [comment]
It will not work for `ScrollView` I don't think. If you change the visibility of the drawable it may or may  not stop, depending on the framework implementation of the version of Android you're using.

You can also just call clear() on the View in question when it's off screen and restart the request when it comes back on.
