### ISSUE TITLE
Combining RoundedCorners and CenterCrop transformations with thumbnail causes jumping corners

### ISSUE THREAD

**Issue by ar-g** [bumptech/glide#3090]
When we combine RoundedCorners and CenterCrop transformations with thumbnail it causes jumping corners.
```kotlin
 glide
            .load(content.image?.path())
            .thumbnail(0.5f)
            .transforms(centerCrop, roundedCorners)
            .override(imageView.measuredWidth, imageView.measuredHeight)
            .placeholder(cameraPlaceholder)
            .error(cameraPlaceholder)
            .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
            .into(imageView)
```
Without thumbnail everything works just fine, but if we have heavy image over 2k, gallery really works slow without this thumbnnail thing. 

How can we achieve both without artifacts?

**Comment by sjudd** [comment]
Please fill out the [issue template][1] when filing new issues. Consider attaching a sample app that reproduces the issue or [a failing test case][2]

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md
[2]: http://bumptech.github.io/glide/tut/failing-test-cases.html
