### ISSUE TITLE
java.io.FileNotFoundException: No such file or directory

### ISSUE THREAD

**Issue by woyl** [bumptech/glide#3092]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by yanbingms** [comment]
I encountered the same problem.  Did you solve it yet?

**Comment by Buyhouse** [comment]
Me too. Who can help me?

**Comment by Twenhimself** [comment]
me too damn
