### ISSUE TITLE
Image doesn't show first time if android:textIsSelectable is true

### ISSUE THREAD

**Issue by four01** [bumptech/glide#3095]
**Glide Version**: 4.7.1

**Integration libraries**: OkHttp3-integration-4.71

**Device/Android Version**: Nexus 5X - Android Oreo

**Issue details / Repro steps / Use case background**: 
Using a basic Html.ImageGetter such as the one at the bottom of this issue: https://github.com/bumptech/glide/issues/2239

The placeholder appears, but the image does not appear until the second time the screen is accessed and the image is loaded from cache. If android:textIsSelectable is set to false in the XML layout then the image loads on the first time with no cache.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Html.ImageGetter imageGetter = new ContentImageGetter(textView.getContext());
        Spanned html;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            html = Html.fromHtml(text, FROM_HTML_SEPARATOR_LINE_BREAK_PARAGRAPH | FROM_HTML_SEPARATOR_LINE_BREAK_BLOCKQUOTE, imageGetter, null);
        } else {
            html = Html.fromHtml(text);
        }

        textView.setText(html);
```

**Layout XML**:
```xml
<TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    tools:text="This is the message body."
                    app:html="@{message.message.body}"
                    android:textIsSelectable="true"
                    android:textSize="16sp"
                    android:textColor="?android:attr/textColorPrimary"
                    android:textColorLink="@color/urlspan_text_color"
/>
```
I'm using databinding with a more complicated case using WrapperTarget that extends SimpleTarget, and the image downloads correctly, it just doesn't display if textIsSelectable is true. Setting it to false works.

**Comment by sjudd** [comment]
No idea why textIsSelectable matters, but I'd start with: http://bumptech.github.io/glide/doc/debugging.html#missing-images-and-local-logs

**Comment by four01** [comment]
I've added logging, but it results in a success:
`GLIDE: Load success: Source = REMOTE`

Anything else worth trying? The only difference I can tell is that the text was changed from `android.text.SpannableString` to a `android.text.SpannedString` when `android:textIsSelectable` is `true`.

I'm replacing `ImageSpan`s with:
```builder.delete(start, end);
builder.replace(start, start, "  \n"); 
builder.setSpan(new CacheableImageSpan(mContext, imageUrl, mImageGetter, mBorder),
                                     start,
                                     start + 1,
                                     0);```

`CacheableImageSpan` extends `DynamicDrawableSpan` and overrides:
```
    @Override
    public Drawable getDrawable() {
        WrapperTarget imageTarget = new WrapperTarget(IMAGE_SIZE, IMAGE_SIZE){
            @Override
            public void onResourceReady(Drawable resource, Transition<? super Drawable> transition) {
                Drawable[] drawables = {resource, mBorder}; // add border
                LayerDrawable layerDrawable = new LayerDrawable(drawables);
                super.onResourceReady(layerDrawable, transition);
            }
        };

        return mImageGetter.getCachedDrawable(mImageUrl, imageTarget, getPlaceholder());
    }
```

This is my `getCachedDrawable`
```
public Drawable getCachedDrawable(String url, WrapperTarget imageTarget, Drawable placeholder) {
        Drawable asyncWrapper = imageTarget.getLazyDrawable();
        asyncWrapper.setCallback(this);
        GlideRequest<Drawable> glideRequest = mGlideApp
                        .load(url)
                        .dontAnimate()
                        .onlyRetrieveFromCache(false)
                        .centerCrop()
                        .diskCacheStrategy(DiskCacheStrategy.ALL);

        glideRequest.placeholder(R.drawable.upload_placeholder_small).into(imageTarget);
        imageTargets.add(imageTarget);
        return asyncWrapper;
    }
```

**Comment by four01** [comment]
I've created a simple project that reproduces the issue: https://github.com/four01/GlideTest

Notice that the placeholder shows up on load, but not the image, leaving the app (simply open the task switcher) then back, and the image will load as it's coming from cache.

**Comment by sjudd** [comment]
I haven't  actually worked with loading drawables in HTML like this before. There was one other issue that sounded related: #1062. Searching through the older issues might provide something interesting as well.

It sounds like the html or view containing it isn't actually invalidated when the Glide load completes. you see the placeholder the first time because that's what was present when the HTML was parsed. The second time the image you loaded the first time around is still in memory, so the second request for it completes synchronously and it appears in the HTML. You could test this by just creating an ImageGetter than always posts a Runnable instead of completing synchronously.

I'm not entirely sure how to resolve it. Maybe there's a way to invalidate the span?

**Comment by ranjitzade** [comment]
Hi @four01
I'm facing the same issue. did you find any solution to this? Please ping me back if you've any solution. Thanks. :+1:  :)

**Comment by joelkrfd** [comment]
This issue is still happening. There's no clear resolution to it. Additional help would be appreciated.
