### ISSUE TITLE
How to store a transcoded Resource in disk cache ?

### ISSUE THREAD

**Issue by thibseisel** [bumptech/glide#3100]
In order to generate a color Palette from each `Bitmap` loaded with Glide, I have defined a custom `ResourceTranscoder<Bitmap, AlbumArt>` to transcode bitmaps to a POJO class  `AlbumArt` whose (simplified) definition is the following:

```java
class AlbumArt {
    final Bitmap bitmap;
    final AlbumPalette palette;
}

class AlbumPalette {
    final int primaryColor;
    final int accentColor;
    final int titleText;
    final int bodyText;
    final int textOnAccent;
}
```

I know that Glide put loaded bitmaps in a memory cache and a disk cache. I'd like to store the transcoded resource (i.e. `AlbumArt`) in disk cache so that color palette are only generated the first time the bitmap is loaded, then retrieved from the cache for subsequent loads.

If I understand well, do I have to implement a custom `ResourceEncoder<AlbumArt>` to define how `AlbumArt` instances are to be written to a cached `File`, and a custom `ResourceDecoder<???, AlbumArt>` to read back `AlbumArt` instances ? 
If that's the case, could you explain to me:
1. Which encoder/decoder/transcoder classes intervene when loading an `AlbumArt` for the first time (including Glide's built-in encoders/decoders), and for subsequent loads,
2. How I can implement those custom `ResourceEncoder` and `ResourceDecoder`, for example but reusing or extending existing bitmap encoders/decoders,
3. How to configure these in my `GlideModule`.

Thanks in advance !

**Glide Version**: 4.6.1

**Integration libraries**: No

**Glide load line**:
```java
GlideApp.with(fragment).as(AlbumArt.class)
    .load(mediaStoreUri)
    .into(new ImageViewTarget<AlbumArt>(imageView) {
        @Override
        public void setResource(@Nullable AlbumArt resource) {
            if (resource != null) {
                applyPalette(resource.palette);
                super.view.setImageBitmap(resource.bitmap);
            }
        }
    });
```

**Comment by sjudd** [comment]
Your outline of what needs to be done looks right.

The specific classes involved varies depending on where you retrieve your images from. Local loads will use a different ModelLoader than remote. The output of those ModelLoaders though will be an InputStream or ByteBuffer. The InputStream or ByteBuffer will then be decoded by something like the [`ResourceBitmapDecoder`][1]. The output `Bitmap` will then be passed to your transcoder.

Loads from the disk cache are more or less the same, just the ModelLoader used varies. The same two basic data types are produced (for Bitmaps anyway). Bitmaps are encoded by [`BitmapEncoder`][2] 

The easiest way to re-use existing components is just to delegate to the existing code. Most encoders and decoders are relatively simple (`Downsampler` is definitely an exception). 

For configuration, see: http://bumptech.github.io/glide/doc/configuration.html#registering-components

[1]: https://github.com/bumptech/glide/blob/2dccb5c2fb265cbfa67b328cea30e922c67feb9e/library/src/main/java/com/bumptech/glide/load/resource/bitmap/ResourceBitmapDecoder.java#L31
[2]: https://github.com/bumptech/glide/blob/2dccb5c2fb265cbfa67b328cea30e922c67feb9e/library/src/main/java/com/bumptech/glide/load/resource/bitmap/BitmapEncoder.java#L78

**Comment by thibseisel** [comment]
Thanks for your reply. I still have struggle implementing a `ResourceEncoder<AlbumArt>` and a `ResourceDecoder<ByteBuffer, AlbumArt> for my use case.

What I've done so far:
- Write a `BufferAlbumArtDecoder` that reads from a `ByteBuffer` and handles decoding only if data starts with the ASCII letters "ART", then reads 5 integers to instantiate an `AlbumPalette`, then delegates to a `ResourceDecoder<ByteBuffer, Bitmap>` (typically an `ByteBufferBitmapDecoder`) to decode the `Bitmap`.
- Write a `AlbumArtEncoder` that writes the ASCII letters "ART" and the 5 integers of AlbumPalette, then delegates to `BitmapEncoder` to write the Bitmap to the cached File.
- Configure `BufferAlbumArtDecoder` and `AlbumArtEncoder` in my GlideModule using `registry.prepend(...)`.

My problems:
1. My `AlbumArtEncoder` is never called. Using the debugger, I noticed that the `BitmapEncoder` was used instead.
2. Even if `AlbumArtEncoder#encode` was called, delegating to `BitmapEncoder` overwrites the content of the cached file. Do I have to write the Bitmap to a temp file, then append its content to the actual file after writing my `AlbumPalette` to it ?

**Comment by sjudd** [comment]
Ugh right, transcoded resources aren't cached. You can convert the ResourceTranscoder into a ResourceDecoder, which will allow the result to be cached. 

For your second question, it depends on how you want to store the data. You can also not delegate and just write your own logic if you want more control over how the file is written.
