### ISSUE TITLE
 How to manually release memory

### ISSUE THREAD

**Issue by zubinxiong** [bumptech/glide#3102]
**Glide Version**: 3.8.0

**Integration libraries**: okhttp3.4.1

**Device/Android Version**: OnePlus3t Android 8.0

**Issue details / Repro steps / Use case background**: 
I'm use glide in keyboard application to display some gif, but in android IME application, there can't pass Activity or Fragment context to glide, I can only pass Application Context or InputMethodService Context to Glide.  After load list of gifs with recyclerView in keyboard, the memory can't release by glide itself, the native memory increase rapidly until OOM. so it's there any solution to solve this problem ?

I have tried to call Glide.get(context).clearMemory() when IME hide from window, bug it's didn't work

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
// context is  InputMethodService
  Glide.with(context).load(source).asGif()
                    .centerCrop().dontAnimate().diskCacheStrategy(DiskCacheStrategy.SOURCE)
                    .into(target);
```

**Layout XML**:
```xml
<RecyclerView></RecyclerView>
item just a ImageView
```

**Stack trace / LogCat**:
```ruby

```

**Comment by sjudd** [comment]
You can clear the individual Targets or Views. Glide.with().clear() or just Glide.clear() depending on the version.

See also: http://bumptech.github.io/glide/doc/caching.html#resource-management and http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors
