### ISSUE TITLE
App Slows down while loading 70+ images in res folder

### ISSUE THREAD

**Issue by aishwarya85** [bumptech/glide#3103]
**Glide Version**:

'com.android.tools.build:gradle:3.1.2'

**Integration libraries**:

 volley
 'com.android.volley:volley:1.0.0'

  Glide
  'com.github.bumptech.glide:glide:3.7.0'

**Device/Android Version**:

Redmi Note 3 / 6.0.1 API 23

**Issue details / Repro steps / Use case background**: 

I am using Glide for Wallpaper app in which wallpaper are in res folder around 70+ images with 18 Mb total images size.

When I use 10-12 wallpapers apps runs good but on increasing wallpaper to 70+ it slows down gradually.

Please help to figure out solution for the same.

android:largeHeap="true" is been kept in manifest file.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

Glide.with(getActivity()).load(images[position])
                    .thumbnail(0.5f)
                    .crossFade()
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .into(imageViewPreview);

**Layout XML**:
```xml

GalleryThumbnail Layout

<?xml version="1.0" encoding="utf-8"?>
<info.androidhive.glide.helper.SquareLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/black"
    android:orientation="vertical">

    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="1.5dp"
        app:cardCornerRadius="8dp">

        <ImageView
            android:id="@+id/thumbnail"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:adjustViewBounds="true"
            android:scaleType="centerCrop" />
    </android.support.v7.widget.CardView>
</info.androidhive.glide.helper.SquareLayout>

ContentLayout

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:ads="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="info.androidhive.glide.activity.MainActivity"
    tools:showIn="@layout/activity_main">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scrollbars="vertical" />
    <!-- Ad Unit-->
    <com.google.android.gms.ads.AdView
        android:id="@+id/bAdOnTheWallView"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentStart="true"
        ads:adSize="BANNER"
        ads:adUnitId="@string/bannerid" />

</RelativeLayout>

<!--
What is the error message that you got in the log?
You can find some help on diagnosing issues here: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
-->
**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

No error but logs are like these

05-22 20:13:49.303 14333-14333/info.androidhive.glide I/Ads: Ad finished loading.
05-22 20:13:56.319 14333-14333/info.androidhive.glide I/Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
05-22 20:13:57.177 14333-14333/info.androidhive.glide I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
05-22 20:13:59.204 14333-14333/info.androidhive.glide I/Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
05-22 20:13:59.957 14333-14333/info.androidhive.glide I/Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
05-22 20:14:01.324 14333-14333/info.androidhive.glide I/Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
05-22 20:14:07.566 14333-14333/info.androidhive.glide I/Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
05-22 20:14:10.166 14333-14333/info.androidhive.glide I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
05-22 20:14:10.939 14333-14333/info.androidhive.glide I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
05-22 20:14:11.653 14333-14333/info.androidhive.glide I/Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.
05-22 20:14:13.666 14333-14333/info.androidhive.glide I/Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.
05-22 20:14:15.656 14333-14333/info.androidhive.glide I/Choreographer: Skipped 44 frames!  The application may be doing too much work on its main thread.
05-22 20:14:20.924 14333-14333/info.androidhive.glide I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
05-22 20:14:25.041 14333-14333/info.androidhive.glide V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@215b0d9
05-22 20:14:25.110 14333-14333/info.androidhive.glide D/DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
05-22 20:14:25.116 14333-14333/info.androidhive.glide I/Ads: Starting ad request.
    Use AdRequest.Builder.addTestDevice("908E907BDAC54C32A44B1557DF7EE9C2") to get test ads on this device.
05-22 20:14:25.954 14333-14333/info.androidhive.glide I/Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
05-22 20:14:26.922 14333-14333/info.androidhive.glide I/Choreographer: Skipped 57 frames!  The application may be doing too much work on its main thread.
05-22 20:14:26.947 14333-14333/info.androidhive.glide D/EgretLoader: EgretLoader(Context context)
    The context is not activity
05-22 20:14:26.958 14333-14333/info.androidhive.glide W/ContentCatcher: Failed to notify a WebView
05-22 20:14:27.175 14333-14333/info.androidhive.glide I/Ads: Scheduling ad refresh 70000 milliseconds from now.
05-22 20:14:27.185 14333-14333/info.androidhive.glide I/Ads: Ad finished loading.
05-22 20:14:28.390 14333-14343/info.androidhive.glide I/art: Background partial concurrent mark sweep GC freed 359(14KB) AllocSpace objects, 3(213MB) LOS objects, 10% free, 137MB/153MB, paused 1.475ms total 137.648ms
05-22 20:14:29.654 14333-14333/info.androidhive.glide D/DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
05-22 20:14:29.657 14333-14333/info.androidhive.glide I/Ads: Starting ad request.
    Use AdRequest.Builder.addTestDevice("908E907BDAC54C32A44B1557DF7EE9C2") to get test ads on this device.
05-22 20:14:29.661 14333-14333/info.androidhive.glide W/Ads: Not retrying to fetch app settings
05-22 20:14:30.365 14333-14333/info.androidhive.glide D/EgretLoader: EgretLoader(Context context)
    The context is not activity
05-22 20:14:30.536 14333-14333/info.androidhive.glide I/Ads: Ad finished loading.
05-22 20:14:32.276 14333-14333/info.androidhive.glide I/Ads: Starting ad request.
    Use AdRequest.Builder.addTestDevice("908E907BDAC54C32A44B1557DF7EE9C2") to get test ads on this device.
05-22 20:14:32.276 14333-14333/info.androidhive.glide W/Ads: An interstitial is already loading. Aborting.
05-22 20:14:32.289 14333-14333/info.androidhive.glide I/Timeline: Timeline: Activity_launch_request time:8888295
05-22 20:14:32.341 14333-14333/info.androidhive.glide D/DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdOverlayCreatorImpl
05-22 20:14:32.349 14333-14333/info.androidhive.glide I/Ads: Ad opening.
05-22 20:14:32.414 14333-14333/info.androidhive.glide W/ContentCatcher: Failed to notify a WebView
05-22 20:14:32.993 14333-14333/info.androidhive.glide W/Ads: JS: Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080 (https://googleads.g.doubleclick.net/mads/gma?_activity_context=true&android_num_video_cache_tasks=0&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gcache_xSeconds&eid=318480762&format=interstitial_mb&heap_free=11372624&heap_max=536870912&heap_total=161471856&js=afma-sdk-a-v12685025.12211000.1&mr=15869403460584542%2C413782414388172099%2C960754145759455659%2C-554832066802270093%2C1657205156658960970%2C1754851809933219128%2C1829370521651767691%2C6424705982061673217%2C8065641856062696890%2C-1305293475992970610%2C-3582235156841730629%2C-8549926945089518463&msid=info.androidhive.glide&preqs=2&scroll_index=-1&seq_num=3&target_api=27:1)
05-22 20:14:32.993 14333-14333/info.androidhive.glide I/chromium: [INFO:CONSOLE(1)] "Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080", source: https://googleads.g.doubleclick.net/mads/gma?_activity_context=true&android_num_video_cache_tasks=0&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gcache_xSeconds&eid=318480762&format=interstitial_mb&heap_free=11372624&heap_max=536870912&heap_total=161471856&js=afma-sdk-a-v12685025.12211000.1&mr=15869403460584542%2C413782414388172099%2C960754145759455659%2C-554832066802270093%2C1657205156658960970%2C1754851809933219128%2C1829370521651767691%2C6424705982061673217%2C8065641856062696890%2C-1305293475992970610%2C-3582235156841730629%2C-8549926945089518463&msid=info.androidhive.glide&preqs=2&scroll_index=-1&seq_num=3&target_api=27 (1)
05-22 20:14:32.994 14333-14333/info.androidhive.glide W/Ads: JS: Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080 (https://googleads.g.doubleclick.net/mads/gma?_activity_context=true&android_num_video_cache_tasks=0&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gcache_xSeconds&eid=318480762&format=interstitial_mb&heap_free=11372624&heap_max=536870912&heap_total=161471856&js=afma-sdk-a-v12685025.12211000.1&mr=15869403460584542%2C413782414388172099%2C960754145759455659%2C-554832066802270093%2C1657205156658960970%2C1754851809933219128%2C1829370521651767691%2C6424705982061673217%2C8065641856062696890%2C-1305293475992970610%2C-3582235156841730629%2C-8549926945089518463&msid=info.androidhive.glide&preqs=2&scroll_index=-1&seq_num=3&target_api=27:1)
05-22 20:14:32.994 14333-14333/info.androidhive.glide I/chromium: [INFO:CONSOLE(1)] "Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080", source: https://googleads.g.doubleclick.net/mads/gma?_activity_context=true&android_num_video_cache_tasks=0&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gcache_xSeconds&eid=318480762&format=interstitial_mb&heap_free=11372624&heap_max=536870912&heap_total=161471856&js=afma-sdk-a-v12685025.12211000.1&mr=15869403460584542%2C413782414388172099%2C960754145759455659%2C-554832066802270093%2C1657205156658960970%2C1754851809933219128%2C1829370521651767691%2C6424705982061673217%2C8065641856062696890%2C-1305293475992970610%2C-3582235156841730629%2C-8549926945089518463&msid=info.androidhive.glide&preqs=2&scroll_index=-1&seq_num=3&target_api=27 (1)
05-22 20:14:33.008 14333-14333/info.androidhive.glide W/Ads: JS: Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080 (https://googleads.g.doubleclick.net/mads/gma?_activity_context=true&android_num_video_cache_tasks=0&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gcache_xSeconds&eid=318480762&format=interstitial_mb&heap_free=11372624&heap_max=536870912&heap_total=161471856&js=afma-sdk-a-v12685025.12211000.1&mr=15869403460584542%2C413782414388172099%2C960754145759455659%2C-554832066802270093%2C1657205156658960970%2C1754851809933219128%2C1829370521651767691%2C6424705982061673217%2C8065641856062696890%2C-1305293475992970610%2C-3582235156841730629%2C-8549926945089518463&msid=info.androidhive.glide&preqs=2&scroll_index=-1&seq_num=3&target_api=27:1)
05-22 20:14:33.008 14333-14333/info.androidhive.glide I/chromium: [INFO:CONSOLE(1)] "Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080", source: https://googleads.g.doubleclick.net/mads/gma?_activity_context=true&android_num_video_cache_tasks=0&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gcache_xSeconds&eid=318480762&format=interstitial_mb&heap_free=11372624&heap_max=536870912&heap_total=161471856&js=afma-sdk-a-v12685025.12211000.1&mr=15869403460584542%2C413782414388172099%2C960754145759455659%2C-554832066802270093%2C1657205156658960970%2C1754851809933219128%2C1829370521651767691%2C6424705982061673217%2C8065641856062696890%2C-1305293475992970610%2C-3582235156841730629%2C-8549926945089518463&msid=info.androidhive.glide&preqs=2&scroll_index=-1&seq_num=3&target_api=27 (1)
05-22 20:14:33.650 14333-14333/info.androidhive.glide W/ContentCatcher: Failed to notify a WebView

**Comment by sjudd** [comment]
Check out https://developer.android.com/studio/profile/ to see if you can narrow down what in particular is causing the slowdown.

**Comment by mariatalbott** [comment]
We would want to read more of your writing. You are invited to play the hilariously humorous game [tiny fishing](http://tinyfishing.co/) with me.

**Comment by VIkash2601** [comment]
@sjudd I tried to run my code with just text and it scrolls smoothly but as soon as I wrote the code to render the Images in my onBindViewHolder for each Image it Janks while scrolling the RecyclerView Items. I have integrated the Pagination and onScroll towards the Top, but I get the scrolling issue. As soon as all the data is rendered once, it starts scrolling smoothly.

Code to Set Image from URL:

`try {
            Glide
                .with(context.applicationContext)
                .asDrawable()
                .load(uri)
                .diskCacheStrategy(if (enableCache) DiskCacheStrategy.AUTOMATIC else DiskCacheStrategy.NONE)
                .thumbnail(
                    Glide
                        .with(context.applicationContext)
                        .load(R.mipmap.gif_loader)
                )
                .into(this)
        } catch (ignored: Exception) {
        }`
        
        While Scrolling the RecyclerView frames are skipping:
        
![image](https://github.com/bumptech/glide/assets/38423769/611742dc-be60-4b37-b15a-30ee55099cdb)
