### ISSUE TITLE
RecyclerView: W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!

### ISSUE THREAD

**Issue by ArcherEmiya05** [bumptech/glide#3108]
This log is showing frequently if a gif image in Recyclerview is not visible yet. But if gif image is visible the log stop? I use it without specifying it if its asBitmap or asGif because I want to allow the user to be able to put jpg or gif and load it to recyclerview.

**Comment by sjudd** [comment]
Please fill out the [issue template][1] when filing new issues.

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md

**Comment by ArcherEmiya05** [comment]
Glide v 4.4.0
N/A
Android M

Log is showing frequently if a gif image in Recyclerview is not visible yet. But if gif image is visible the log stop? I use it without specifying it if its asBitmap or asGif because I want to allow the user to be able to put jpg or gif and load it to recyclerview.

        GlideApp.with(context)
                                     .load(imgUri)
                                     .thumbnail(GlideApp.with(context).load(imgThumbnail))
                                     .placeholder(R.color.icon_not_selected)
                                     .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
                                     .listener(new RequestListener<Drawable>() {
                                         @Override
                                         public boolean onLoadFailed(@Nullable GlideException e, Object model, 
                  Target<Drawable> target, boolean isFirstResource) {
                                             //If Log In forms is hidden then Progress should be visible
                                             return false;
                                         }

                                         @Override
                                         public boolean onResourceReady(Drawable resource, Object model, 
                   Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                                             mProgress.setVisibility(View.GONE);
                                             return false;
                                         }
                                     })
                                     .into(mImage);
                         

                 W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!

**Comment by sjudd** [comment]
Thanks for the detail!

This is a duplicate of #743

**Comment by ArcherEmiya05** [comment]
Another thing is that, is it safe or should I just ignore it?
