### ISSUE TITLE
pauseRequests display the placeholder

### ISSUE THREAD

**Issue by AnJiuZhe** [bumptech/glide#3109]
I use glide load imagview in my recyclerview, but the placeholder not work when the recyclerview is gliding.

**Glide Version: 4.7.1**
**Integration libraries: No**

**Glide load line:**
![image](https://user-images.githubusercontent.com/30287547/40595827-87c1dd5a-6269-11e8-9c5b-c166cfaad2e1.png)

**RecyclerView listener line:**
![image](https://user-images.githubusercontent.com/30287547/40595805-80460f10-6269-11e8-94e7-86b0e68ba1cb.png)

I hope imageviews display the placeholder when glide apply pauseRequests method, but it not work, what should i do? thanks! @sjudd

**Comment by sjudd** [comment]
Please fill out [the issue template][1] when filing new issues. 

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md

**Comment by AnJiuZhe** [comment]
![ezgif-4-28cded7882](https://user-images.githubusercontent.com/30287547/40596217-0bf08fde-626c-11e8-8b2d-992a61f29e2e.gif)

**Comment by sjudd** [comment]
I'm able to reproduce. I think we probably do want to show placeholders for paused requests. That would match the behavior of restartRequests.

**Comment by sjudd** [comment]
Fixed by a55e935eba859b9ea4f6e4357b8ac4e7e4a8327f
