### ISSUE TITLE
Question: how to run on current thread?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bumptech/glide#3116]
Instead of a new background thread, how can I do it on the current thread (which I know is a background thread) ?

For example this:

    Glide.with(...).asBitmap().load(imageFile).apply(RequestOptions.centerCropTransform().skipMemoryCache(true).diskCacheStrategy(DiskCacheStrategy.NONE))
                        .into<SimpleTarget<Bitmap>>(object : SimpleTarget<Bitmap>(reqWidth, reqHeight) {
                            override fun onResourceReady(result: Bitmap, transition: Transition<in Bitmap>?) {
                            }

                            override fun onLoadFailed(errorDrawable: Drawable?) {
                                super.onLoadFailed(errorDrawable)
                            }
                        })

**Comment by sjudd** [comment]
It's not currently possible. You can use `submit()` to get a `Future` instead of using `SimpleTarget`, which is probably more useful. 

I'd like to expand Glide to support this better, if for no other reason than we could reduce the number of thread hops (particularly to/from the main thread) which can add substantial latency to background threads. 

However, we may never support running on your current thread. There's some non-trivial benefit to allowing Glide to control the parallelism of requests (memory, I/O, priority of loads/threads etc). It's not impossible to do if we don't control the threads, but it's certainly more difficult.

**Comment by AndroidDeveloperLB** [comment]
Well I have something that needs to load an image in the background and wait for the result, but it's already in the background...
Because of this, I will have to use CountDownLatch to wait for Glide to finish its loading...

**Comment by AndroidDeveloperLB** [comment]
Interesting.
But now that I think about it, will I get the same amount of information about the result, as with the listener?

**Comment by sjudd** [comment]
You can use both a `RequestListener` and `submit()` in the same request.

**Comment by AndroidDeveloperLB** [comment]
Thank you

**Comment by AndroidDeveloperLB** [comment]
Can you please show how to do it, given the original code I wrote on the first post?

**Comment by sjudd** [comment]
Just add `.listener(new RequestListener()....)` before your call to `submit()`.

**Comment by AndroidDeveloperLB** [comment]
I don't understand. You mean to replace `into` with `listener` ?

**Comment by sjudd** [comment]
Nope you can do both.

```java
.listener(new RequestListener() { ... }).submit()
```

**Comment by AndroidDeveloperLB** [comment]
Can you please show the full code of what my I've done in the first post here?
I don't understand what is the exact change here.

**Comment by sjudd** [comment]
```java
Glide.with(...)
  .asBitmap()
  .load(imageFile)
  .apply(
    RequestOptions.centerCropTransform()
        .skipMemoryCache(true)
        .diskCacheStrategy(DiskCacheStrategy.NONE))
  .listener(new RequestListener() { ... })
  .into<SimpleTarget<Bitmap>>(object : SimpleTarget<Bitmap>(reqWidth, reqHeight) {
      override fun onResourceReady(result: Bitmap, transition: Transition<in Bitmap>?) {}

      override fun onLoadFailed(errorDrawable: Drawable?) {
         super.onLoadFailed(errorDrawable)
       }
   })
```

**Comment by AndroidDeveloperLB** [comment]
So this will run on the current thread?

**Comment by sjudd** [comment]
Oh sorry, you wanted submit:

```
Glide.with(...)
  .asBitmap()
  .load(imageFile)
  .apply(
    RequestOptions.centerCropTransform()
        .skipMemoryCache(true)
        .diskCacheStrategy(DiskCacheStrategy.NONE))
  .listener(new RequestListener() { ... })
  .submit()
  .get();
```

The .get() call will block until the request completes. `submit` returns a `Future` so you can also specify a timeout.

**Comment by AndroidDeveloperLB** [comment]
I wanted to run on current thread, and get a result there.
Question is, how do I get the result here. It has a listener. Does it mean I have to use a wrapper, such as AromicReference?

**Comment by sjudd** [comment]
```java
Bitmap bitmap = 
  Glide.with(...)
    .asBitmap()
    .load(imageFile)
    .apply(
      RequestOptions.centerCropTransform()
          .skipMemoryCache(true)
          .diskCacheStrategy(DiskCacheStrategy.NONE))
    .listener(new RequestListener() { ... })
    .submit()
    .get();
```

**Comment by AndroidDeveloperLB** [comment]
Ohhhh.....
So it is possible.
Thank you guys. Will try it later.

**Comment by AndroidDeveloperLB** [comment]
Say, does `centerCropTransform` somehow use less memory by decoding only a part of the image?
Or does it decode entire resolution, and then crop the bitmap into a new bitmap?

**Comment by sjudd** [comment]
Some of both, Glide will downsample as much as possible, which can save memory. The cropping uses the original aspect ratio, so it doesn't reduce the maximum memory used. It does reduce long term memory use by keeping only the part of the image you're displaying in memory. If you're loading from the disk cache it also reduces maximum memory usage because the downsampled/cropped image can be loaded directly.

**Comment by AndroidDeveloperLB** [comment]
But on this specific case that I show here, where there is no cache and you load the Bitmap from an existing file as an input, isn't it better to decode only a part of the image, using BitmapRegionDecoder, for example?
Maybe it is possible to get the output Bitmap in a single step this way, meaning without a temporary Bitmap on the way?

**Comment by sjudd** [comment]
BitmapRegionDecoder has it's own set of issues. While it's probably more efficient if you're using a supported file format and decoding multiple different parts of the image, it may not be any more efficient for decoding a single segment.

**Comment by AndroidDeveloperLB** [comment]
Which issues?
Glide supports more image formats than what's on the framework?
Why isn't it more efficient? It also has the same BitmapOptions available just like the normal decoding of image files. 
And I think it might be at least in terms of memory usage, no? You get a single Bitmap object that is exactly the output one.

**Comment by sjudd** [comment]
region decoding isn't supported for all formats that the platform supports via BitmapFactory. It also requires some non-trivial overhead to read the image and store relevant information in memory.

**Comment by AndroidDeveloperLB** [comment]
So why not use it when possible? And is it possible to check which formats does it support?
I don't understand the part you wrote about "non trivial overhead" . Do you mean it takes more CPU  ?

**Comment by AndroidDeveloperLB** [comment]
Seems your code works, yet you forgot to mention that the "submit" is supposed to have the parameters of required width and height.
