### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by xmenxwk** [bumptech/glide#312]
I've tryiing to build its sample app for 2 hours but everywhere errors and errors. Its not straight forward as written in description. Would you you please fix it ?

Im using android studio and trying to checkout using https url. Before I tried with github terminal, but no success.

**Comment by TWiStErRob** [comment]
Did you do the submodule part? Try to make it work in terminal first and then import to AS.

**Comment by xmenxwk** [comment]
Could you please write in steps ?

**Comment by xmenxwk** [comment]
This is the error Im getting when I use "gradlew jar" in cmd

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task 'findbugs' during up-to-date
check.  See stacktrace for details.
> Could not normalize path for file 'D:\glide\third_party\gif_decoder\build\outp
uts\aar\gif_decoder-release.aar;D:\glide\third_party\gif_encoder\build\outputs\a
ar\gif_encoder-release.aar;D:\glide\third_party\disklrucache\build\libs\disklruc
ache.jar;C:\android-sdk\extras\android\m2repository\com\android\support\support-
v4\19.1.0\support-v4-19.1.0.jar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

**Comment by TWiStErRob** [comment]
I managed to build on Windows 7 when I did it using
https://github.com/bumptech/glide/blob/master/README.md#build
and I think I used JDK 6, and latest Android SDK.

**Comment by TWiStErRob** [comment]
Ahh that thing, I fixed that, but it didn't make it to master. Let me dig it up.

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/commit/fbcae27856cd8112ea2887a6d7e1121432ca4224?diff=unified#diff-3 from #272

**Comment by TWiStErRob** [comment]
As an alternative you can temporarily [skip a task](http://www.practicalgradle.org/blog/2010/10/skipping-tasks/), but that doesn't help if you want to import it into AS.

**Comment by xmenxwk** [comment]
it started downloading more files then this

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:findbugs'.
> The version of FindBugs (2.0.3) inferred from FindBugs classpath is too low to
 work with currently used Java version (1.8). Please use higher version of FindB
ugs. Inspected FindBugs classpath: [findbugs-2.0.3.jar, jcip-annotations-1.0.jar
, jsr305-2.0.1.jar, bcel-2.0.1.jar, jFormatString-2.0.1.jar, dom4j-1.6.1.jar, as
m-3.3.jar, asm-commons-3.3.jar, commons-lang-2.6.jar, AppleJavaExtensions-1.4.ja
r, jaxen-1.1.6.jar, xml-apis-1.0.b2.jar, asm-tree-3.3.jar]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

**Comment by xmenxwk** [comment]
is java 1.8 not supported ?

**Comment by xmenxwk** [comment]
Nevermind, I changed the JAVA_HOME and JDK_HOME to java 1.7 and its now keep going.

**Comment by TWiStErRob** [comment]
Android supports Java 7 since 4.4, but Glide builds with Java 6 to be compatible with most Android builds. Use JDK 6. FindBugs must have their own reasons why it is not forward compatible.

**Comment by xmenxwk** [comment]
now new error

com.bumptech.glide.disklrucache.DiskLruCacheTest > aggressiveClearingHandlesEdit
                                                                               F
AILED
    java.io.IOException at DiskLruCacheTest.java:734

com.bumptech.glide.disklrucache.DiskLruCacheTest > aggressiveClearingHandlesRead
                                                                               F
AILED
    java.io.IOException at DiskLruCacheTest.java:759

com.bumptech.glide.disklrucache.DiskLruCacheTest > updateExistingEntryWithTooFew
ValuesReusesPreviousValues                                                     F
AILED
    org.junit.ComparisonFailure at DiskLruCacheTest.java:346

com.bumptech.glide.disklrucache.DiskLruCacheTest > editSnapshotAfterChangeAborte
d                                                                              F
AILED
    org.junit.ComparisonFailure at DiskLruCacheTest.java:903

com.bumptech.glide.disklrucache.DiskLruCacheTest > evictOnUpdate FAILED
    org.junit.ComparisonFailure at DiskLruCacheTest.java:422

com.bumptech.glide.disklrucache.DiskLruCacheTest > aggressiveClearingHandlesWrit
e                                                                              F
AILED
    java.io.IOException at DiskLruCacheTest.java:725

com.bumptech.glide.disklrucache.DiskLruCacheTest > editSameVersion FAILED
    org.junit.ComparisonFailure at DiskLruCacheTest.java:903

com.bumptech.glide.disklrucache.DiskLruCacheTest > aggressiveClearingHandlesPart
ialEdit                                                                        F
AILED
    java.io.IOException at DiskLruCacheTest.java:751

56 tests completed, 8 failed
:third_party:disklrucache:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':third_party:disklrucache:test'.
> There were failing tests. See the report at: file:///D:/glide/third_party/disk
lrucache/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 20 mins 22.199 secs

**Comment by sjudd** [comment]
I'd recommend considering VirtualBox + Linux. Since travis-ci only supports Linux, Linux is the only officially supported platform. I develop regularly on OSX, so that's likely to work.

I don't object to supporting Windows, but until we have some CI setup for it it's likely to continue to btrsk. I wouldn't object to a pull request adding ci support for windows. AppVeyor might be a possibility.

**Comment by TWiStErRob** [comment]
Rename `DiskLruCacheTest.java` to have a different extension.
disklrucache was written for Android/unix and the Windows file system has different quirks so it won't run because the tests assume unix-like file system behaviour.

**Comment by xmenxwk** [comment]
@sjudd : Yes I will be using linux soon, but right now I need this on Windows.

@TWiStErRob : renamed, same error. Is there any parameter to skip the tests ?

**Comment by TWiStErRob** [comment]
Try a clean build, the .class file probably stuck. Thinking twice it's best to remove the test file, not just rename.
To skip: as referenced above something like: `-x :third_party:disklrucache:testBlah` would help. Check the last task name above the failure.

**Comment by xmenxwk** [comment]
Thank you very much, @TWiStErRob  :)

**Comment by sjudd** [comment]
Since we haven't checked anything in to fix this and someone else may find it useful, let's leave this open for now.

**Comment by TWiStErRob** [comment]
There's a failure in library/build.gradle where `files` can't handle multiple jars in `asPath`. Since `FindBugs.classpath` is a `FileCollection` and `Configuration extends FileCollection` the following works: replace
`classpath = files(project.configurations.compile.asPath)`
with
`classpath = project.configurations.compile`

**Comment by TWiStErRob** [comment]
`DiskLruCacheTest` fails at least 8 test methods, so I think it's easier to disable all:
```java
@BeforeClass public static void setUpClass() {
    Assume.assumeThat(System.getProperty("os.name"),
            IsNot.not(StringStartsWith.startsWith("Windows")));
}
```
This would still allow Travis to catch bugs, but also allow people on Windows to build.

**Comment by TWiStErRob** [comment]
@sjudd this can be closed now, thank you for putting the fixes in.
It builds flawlessly without any hacks. The key is to use the correct java version.

(DiskLruCache commit for reference: https://github.com/sjudd/DiskLruCache/commit/cd49c1dae54ef9f3ff22f425b659f3a180984929)

**Comment by sjudd** [comment]
Great, glad to hear it.

**Comment by TWiStErRob** [comment]
Dang, I missed one, I had it in local changes:
disklrucache/checkstyle.xml:
    <module name="NewlineAtEndOfFile">
        <property name="newline" value="lf" />
    </module>

**Comment by sjudd** [comment]
Should be fixed here: https://github.com/bumptech/glide/commit/ae4a451131d858bbe8f1bb1913bfef3322313e73
