### ISSUE TITLE
Can not load image from url without quality loss

### ISSUE THREAD

**Issue by tushar09** [bumptech/glide#3122]
Glide Version: 3.7.0

I need to load some images without losing the quality. But glide is not letting me do that. It puts some stripes on the image. Here is the code I am using:

 ```
Glide.with(this)
                .load(dresses.getPicture())
                .dontTransform()
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .skipMemoryCache(true)
                .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                .signature(new StringSignature(String.valueOf(System.currentTimeMillis())))
                .into(binding.ivImage);
```

and also tried this:
 ```
Glide.with(getActivity())
                .load(dresses.getPicture())
                .asBitmap()
                .into(new SimpleTarget<Bitmap>(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL) {
                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                        binding.ivImage.setImageBitmap(resource);
                    }
                });
```

Both of this code snippets are not working as I want. But when I am using picasso, it loads the images perfectly. I have attached the pictures too. You can understand by looking at them.

loaded by glide
![screenshot_2018-06-05-14-18-03](https://user-images.githubusercontent.com/9745378/40964518-256bf93c-68cd-11e8-884f-27620da28016.png)

loaded by picasso
![screenshot_2018-06-05-13-58-42](https://user-images.githubusercontent.com/9745378/40964542-39eed474-68cd-11e8-8244-8857c047be04.png)

the thing is I have used glide through out  my whole project. Picture quality was not that kind of important. But in this particular case I can not compromise it. On the other hand I dont want to use both picasso and glide together in my project as they do the same kind of job. 

Can any one please help me to solve this?

**Comment by ekhaled667** [comment]
In Glide Bitmaps are decoded using RGB_565 because it uses half the memory as ARGB_8888, just pass
```.format(DecodeFormat.PREFER_ARGB_8888)```
to your glide loading line and it should display it fine.
