### ISSUE TITLE
Failed to resolve variable '${project.groupId}' after refactoring to androidX

### ISSUE THREAD

**Issue by prashsb** [bumptech/glide#3124]
**Glide Version**: 4.7.1

**Integration libraries**: no

**Device/Android Version**: Galaxy s7

**Issue details / Repro steps / Use case background**:  getting this error while compiling the project. after refactored to androidX this issued is occured

[TAG] Failed to resolve variable '${project.version}' |  
-- | --
[TAG] Failed to resolve variable '${project.groupId}' |  
[TAG] Failed to resolve variable '${project.version}' |  
[TAG] Failed to resolve variable '${project.groupId}' |  
[TAG] Failed to resolve variable '${project.version}' |  
[TAG] Failed to resolve variable '${project.groupId}' |  
[TAG] Failed to resolve variable '${project.version}' |  
[TAG] Failed to resolve variable '${animal.sniffer.version}' |  

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by joshfriend** [comment]
I get this error when I try to use the OkHttp integration:

```
Failed to resolve: com.github.bumptech.glide:okhttp3-integration4.7.1
```

**Comment by qbait** [comment]
I have the same issue.

**Comment by joshfriend** [comment]
bump

**Comment by sjudd** [comment]
Maybe #3080, I'm not sure what to do with the original report here, it looks like some kind of a build error...

**Comment by DilbagSandhu** [comment]
i encountered the same error today any solutions?

**Comment by MonteCreasor** [comment]
I don't think this is a Glide issue. I  don't have any dependency on Glide and I get the same issue when I cleaned my Gradle cache today and rebuilt.

**Comment by johnnyPescarul** [comment]
Any updates on this?  I am using Glide in my project, updated to latest Android Studio 3.3 and still run into this issue.

**Comment by imspatni** [comment]
I could be able to fix it, though not straight forward. First I have to rename all those dependency manually in xml and in runtime classes (Auto import did not much worked much with some wrong import). And then update glide version file from 4.7.1 to 4.8.0; and that's fixed it issue for me. It was  around 2 hours and 90+ files work for me, so #KeepCalm and continue with changes, don't undo changes :)

**Comment by Superblazer** [comment]
Same issue here...

**Comment by akndmr** [comment]
If you define variables in gradle to use for version numbers like: 
```
def paging_version = "2.1.0-beta01"
implementation "androidx.paging:paging-runtime:$paging_version"
```
you may get this error. Removing variable solves it:

`implementation "androidx.paging:paging-runtime:2.1.0-beta01"`

**Comment by mkovalyk** [comment]
For me, renaming from **lifecycle_version = '2.0.0'** to lifecycle_version = "2.0.0"fixes the issue

**Comment by AndersonLeonyDeveloper** [comment]
> For me, renaming from **lifecycle_version = '2.0.0'** to **lifecycle_version = "2.0.0"** fixes the issue

Into my case qas the oposite...i've changed **lifecycle_version = "2.0.0"** to **lifecycle_version = '2.0.0'** and it works.

**Comment by markrizkalla** [comment]
I was facing the same error but when i increased my minsdkversion to 20 fix the error
