### ISSUE TITLE
ViewTarget with Kotlin

### ISSUE THREAD

**Issue by ekhaled667** [bumptech/glide#3130]
I'm using ViewTarget in Kotlin:
```java
val target: ViewTarget<*, *> = object : ViewTarget<SubsamplingScaleImageView, BitmapDrawable>(thumbnail) {
                override fun onResourceReady(resource: BitmapDrawable, transition: Transition<in BitmapDrawable>?) {

                }
            }
```
 And the loading line:
```java
glide.load(post.url).into(target)
```

I'm getting
> Non of the following functions can be called with the arguments supplied.

from ```.into```:
It doesn't accept anything but ```ImageView``` and ```Target<Drawable>```.

How can I convert ```ViewTarget<SubSamplingImageView, Bitmap Drawwable>``` to ```Target<Drawable>```?

**Comment by ekhaled667** [comment]
Never mind I had to pass ```.downloadOnly```

**Comment by pollux-** [comment]
I have the same issue, How can I solve this in kotlin?

**Comment by Arlem** [comment]
> I have the same issue, How can I solve this in kotlin?

Check https://github.com/bumptech/glide/issues/3500#issuecomment-518624172
