### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by cabelloruizcarlos** [bumptech/glide#3134]
I opened this issue #3099 and I was told to re-open it if it wasn't fixed updating the library....but I cannot re-open it so I was force to create a new one. Sorry about that.

Looks like the issue is not fixed because in 4 days I received 8 crashes.

**Glide Version**: implementation 'com.github.bumptech.glide:glide:4.7.1'

**Device/Android Version**: 
Galaxy S7 (Not Rooted) Running 7.0(Nougat) 3 occurrences
Galaxy S6 (Not Rooted) Running 7.0(Nougat) 1 occurrence
BlackBerry BBB100-2(Not Rooted) 7.1.1(Nougat) 1 occurrence
Xperia X(Not Rooted) Running 8.0.0(Oreo) 1 occurrence     
Galaxy S8 (Not Rooted) Running 8.0.0(Oreo) 2 occurrences

**This is the crash**
![screen shot 2018-06-08 at 11 09 08](https://user-images.githubusercontent.com/7534807/41152776-955cf250-6b0c-11e8-8591-ffa38a3f201c.png)

**Comment by cabelloruizcarlos** [comment]
Hi!!! Any help with this????

**Comment by sjudd** [comment]
Ah this is distinct from  #3099. This is failing attempting to find the resource id for the placeholder you're using with Glide. 

Either you're passing in a resource id to `.placeholder()` in a Glide request that doesn't exist, or you're running into an Android issue where when an application is updated, sometimes the resource ids from the old apk are used to try to find resources in the new apk.

**Comment by cabelloruizcarlos** [comment]
Hi! First of all, thanks for the answer!!!

I m sorry but I cannot see any difference between the two issues. I think that the only one is the Glide version.

I can modify the app to set a color to the background of the ImageView and then load the image using Glide without setting a placeholder....do you think that could work?

Cheers

**Comment by Gurupreet** [comment]
Hii facing the same issue when I try to switch between fragments so fast. I am using a xml drawable and tried both R.drawable.image/ContextCompat(context, R.drawable.image).

**Comment by mochadwi** [comment]
any updates for this? @sjudd
