### ISSUE TITLE
error loading image

### ISSUE THREAD

**Issue by Tehalka** [bumptech/glide#3135]
**Glide Version**: 4.7.1

**Integration libraries**: OkHttp3, Retrofit

**Device/Android Version**: all

**Issue details / Repro steps / Use case background**: 
I have tried with Picasso and universal image loader , and it loads the picture properly, but I'd like to use Glide

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 RequestOptions options = new RequestOptions()
                        .error(R.mipmap.ic_launcher_round);
                Glide.with(mContext)
                        .load("url")
                        .listener(requestListener)
                        .apply(options)
                        .into(imageView);
```

**Layout XML**:
```xml

        <ImageView
            android:id="@+id/iv_asset"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
com.bumptech.glide.load.engine.GlideException: Failed to load resource
There were 2 causes:
java.net.SocketException(Connection reset)
java.io.FileNotFoundException(No content provider: url)
 call GlideException#logRootCauses(String) for more detail

**Comment by ekhaled667** [comment]
I really don't know better, but it seems you didn't change ```.load(url)```.

Which is evident in the stack trace, and thus glide can't initiate a connection.

**Comment by sjudd** [comment]
`java.net.SocketException(Connection reset)` looks like the root cause. Picasso uses OkHttp, consider using that integration library: http://bumptech.github.io/glide/int/okhttp3.html
