### ISSUE TITLE
In Glide 4.7,1  GifDrawable   getCallback is null

### ISSUE THREAD

**Issue by Everlastingsmile** [bumptech/glide#3138]
**Glide Version**: 4.7.1

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

In RecycleView, My ImageView Move out of the screen and move into the screen.   findCallback() of GifDrawable  is null,  and gif can't  Play.   How can i avoid this problem.

GifDrawable:
![default](https://user-images.githubusercontent.com/19623529/41223697-1bec17e6-6d9d-11e8-8d71-a03a017a7539.png)

![default](https://user-images.githubusercontent.com/19623529/41223811-6c320ea4-6d9d-11e8-8ce3-bc632e634818.png)

**Comment by kanytu** [comment]
Why is this closed? Did you manage to get a fix?
