### ISSUE TITLE
kotlin GlideExtension annotation not work

### ISSUE THREAD

**Issue by yuanwenbing** [bumptech/glide#3140]
my code is 

@GlideExtension
class Exs private constructor() {

    companion object {

        @GlideOption
        fun miniThumb(options: RequestOptions) {
            options
                    .fitCenter()
                    .override(500, 500)

        }

        private val DECODE_TYPE_GIF = RequestOptions.decodeTypeOf(GifDrawable::class.java).lock()

        @GlideType(GifDrawable::class)
        fun asGif(requestBuilder: RequestBuilder<GifDrawable>) {
            requestBuilder
                    .transition(DrawableTransitionOptions())
                    .apply(DECODE_TYPE_GIF)
        }

    }
}

by GlideApp.with(this) it's not work, I can't find the method.

**Comment by farkerhaiku** [comment]
instead of @glideextension, try @GlideExtension

**Comment by sjudd** [comment]
Did you follow the setup steps? http://bumptech.github.io/glide/doc/generatedapi.html#kotlin
