### ISSUE TITLE
Image duplicate while inserting new items in RecyclerView

### ISSUE THREAD

**Issue by ArcherEmiya05** [bumptech/glide#3141]
v 4.4.0

N/A

LG K10 Android M

When adding new item in my RecyclerView I place it at the very top of the list (index 0). In my first attempt to add new items everything is good but in my second attempt to add new item I get some image to my CardView although I dont have any image include on that item. I also call notifyDataSetChanged() after adding new item at the top so that adapter position is always up to date.
This is what on my RecyclerView.

        //Set all announcement data
         void setAnnouncementPost(final String su, final String title, final String description, final String 
         time, final String thumbnail, final String imgUri, final String imgThumbnail){
             //Stop shimmering the item if any of the data becomes available
             if (!su.isEmpty()) {
                 new Handler().postDelayed(new Runnable() {
                     @Override
                     public void run() {

                         shimmerPost.stopShimmerAnimation();
                         mSuDP.setEnabled(true);
                         mSU.setBackground(null);
                         mSU.setText(su);
                         mSU.setTextColor(Color.WHITE);

                         post.setBackground(null);
                         post.setTextColor(Color.WHITE);

                         mtimePostedTxtView.setBackground(null);
                         mtimePostedTxtView.setText(time);
                         mtimePostedTxtView.setTextColor(Color.WHITE);

                         mtitleTxtView.setBackground(null);
                         mtitleTxtView.setText(title);
                         mtitleTxtView.setTextColor(Color.WHITE);

                         mdescriptionTxtView.setBackground(null);
                         mdescriptionTxtView.setText(description);
                         mdescriptionTxtView.setTextColor(Color.WHITE);

                         /*
                         Set post images
                         */

                         //Set the user's profile picture
                            if (!isDetached && context != null)
                             GlideApp.with(context)
                                     .load(thumbnail)
                                     .placeholder(R.color.icon_not_selected)
                                     .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
                                     .listener(new RequestListener<Drawable>() {
                                         @Override
                                         public boolean onLoadFailed(@Nullable GlideException e, Object model, 
                                         Target<Drawable> target, boolean isFirstResource) {
                                             return false;
                                         }

                                         @Override
                                         public boolean onResourceReady(Drawable resource, Object model, 
                                         Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                                             return false;
                                         }
                                     })
                                     .into(mSuDP);

                         //Check if user includes some photo
                         if (imgThumbnail != null && imgUri != null){
                             mRelative.setVisibility(View.VISIBLE);
                             //Set any announcement picture
                             if (!isDetached)
                                 if (imgThumbnail.contains(".jpg") && imgUri.contains(".jpg"))
                                     GlideApp.with(context)
                                             .load(imgUri)
                                             .thumbnail(GlideApp.with(context).load(imgThumbnail))
                                             .placeholder(R.color.icon_not_selected)
                                             .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
                                             .listener(new RequestListener<Drawable>() {
                                                 @Override
                                                 public boolean onLoadFailed(@Nullable GlideException e, Object model, 
                                                 Target<Drawable> target, boolean isFirstResource) {
                                                     //If Log In forms is hidden then Progress should be visible
                                                     return false;
                                                 }

                                                 @Override
                                                 public boolean onResourceReady(Drawable resource, Object model, 
                                                 Target<Drawable> target, DataSource dataSource, boolean 
                                                   isFirstResource) {
                                                     mProgress.setVisibility(View.GONE);
                                                     return false;
                                                 }
                                             })
                                             .into(mImage);
                         }

                         else if (imgUri != null && imgUri.contains(".gif")){
                             mRelative.setVisibility(View.VISIBLE);
                             //Set any announcement picture
                             if (!isDetached)
                                 GlideApp.with(context)
                                         .asGif()
                                         .load(imgUri)
                                         .placeholder(R.color.icon_not_selected)
                                         .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
                                         .listener(new RequestListener<GifDrawable>() {
                                             @Override
                                             public boolean onLoadFailed(@Nullable GlideException e, Object model, 
                                                Target<GifDrawable> target, boolean isFirstResource) {
                                                 return false;
                                             }

                                             @Override
                                             public boolean onResourceReady(GifDrawable resource, Object model, 
                                         Target<GifDrawable> target, DataSource dataSource, boolean isFirstResource) {
                                                 mProgress.setVisibility(View.GONE);
                                                 return false;
                                             }
                                         })
                                         .into(mImage);

                         }

                 
                         leftBmb.setVisibility(View.VISIBLE);
                         mReactions.setVisibility(View.VISIBLE);

                     }
                 },2000);
             }
         }
I think the main causes would be "notifyDataSetChanged()" since it give RecyclerView.NO_POSITION in every call. Also I get repetitive "Bitmap may cause graphical corruption!" logs if the item loaded asGif() is at the bottom or not yet visible on the screen but when it is visible it stop throwing logs and again if I scroll where it is no longer visible it throws again those message in logs.

**Comment by sjudd** [comment]
You don't appear to be clearing views you might have started image loads into previously. See http://bumptech.github.io/glide/doc/getting-started.html#listview-and-recyclerview. In particular, the second code sample is relevant.
