### ISSUE TITLE
signature method but does't appears.

### ISSUE THREAD

**Issue by paourissi** [bumptech/glide#3144]
I want to call signature method but does't appears.

Glide.with(context).load(context.getFilesDir().getPath() + "/" + imgName).signature(new StringSignature("someVersion")).into(imgView)

**Glide Version**:
4.7.1

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/options.html#requestoptions
