### ISSUE TITLE
Sometimes I got black image with onResourceReady callback

### ISSUE THREAD

**Issue by wjdtncjs** [bumptech/glide#3146]
sorry for English.

Sometimes I got black image with onResourceReady callback.

And when this happens, if  I go back and  go again, Image is showing.

It happens only one device(LG-V400S1 - 5.0.2) other device is working great.

I have 3 phones (SHV-E330S- 5.0.1, Mi A1- 8.0.0, LG-V400S1 - 5.0.2) 

I am using 4.7.1 version. 

My code is below.

        RequestOptions` myOptions = new RequestOptions()
                .centerCrop()
                .override(CONSTANT.WIDTH_PIXEL, Util.getRatio(3, 4, CONSTANT.WIDTH_PIXEL));

        glideManager
                .load(item)
                .apply(myOptions)
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                        Log.e(TAG, "item : " + item + " " + e.toString(), e);
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                        Log.JSC(TAG, "complete :" + item);
                        return false;
                    }
                })
                .into(imageView);

only onResourceReady is being called. 

![2018-06-15 15 27 20](https://user-images.githubusercontent.com/18277229/41453423-b0d7ed10-70b0-11e8-8362-a0f5f694c09a.gif)

* second image is not shown but I got onResourceReady callback.
* Happens regardless of Image order (above, second image but sometimes first, third, etc..)
* I don's see any error log from logcat(like out of memory, exception..)

**Comment by sjudd** [comment]
If you set Glide's BitmapPool size to 0 does the issue still reproduce on that device? http://bumptech.github.io/glide/doc/configuration.html#bitmap-pool.

It's not a solution I'd recommend in general because it negatively impacts performance and memory usage. However if there's an issue with Bitmap re-use on that device, it may help to debug and it might be appropriate for that device specifically in the long run.

**Comment by wjdtncjs** [comment]
Thank you for the reply.

Yes. it still reproduces the issue.(LG-V400S1 - 5.0.2 only) now it's more shown.

I set like the below.

    @GlideModule
    public class GlideModule extends AppGlideModule {
       @Override
       public void applyOptions(Context context, GlideBuilder builder) {
           int bitmapPoolSizeBytes = 0; 
           builder.setBitmapPool(new LruBitmapPool(bitmapPoolSizeBytes));
       }
    }

**Comment by wjdtncjs** [comment]
What should I do after "setBitmapPool(0)"?

**Comment by sjudd** [comment]
Do you see exceptions related to drawing recycled Bitmaps or anything like that? With the BitmapPool empty? 

One other possibility is a Bitmap re-use error, but that would typically cause exceptions, more here: http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors

**Comment by hieonn** [comment]
@wjdtncjs 
Have you resolved this issue? I have same issue with the LG device such as Gpad. The glide got onResourceReady but image view shows just black image as well. Please let me know how to if you have any advice or solution. Thanks!

**Comment by hieonn** [comment]
I believe I've got the answer for this issue such that set .diskCacheStrategy(DiskCacheStrategy.DATA) in making glide api use with skipMemoryCache option in order to let glide take all images from original disk cache. any other trials have no luck so far but this.
