### ISSUE TITLE
How to get original image after using circleCrop?

### ISSUE THREAD

**Issue by ParadiseHell** [bumptech/glide#3149]
**Glide Version**:4.5.0

**Integration libraries**:OkHttp3

**Android Version**:Android 8.1.0

**Issue details**: 
I wanna display a circle image, so I try to use **circleCrop** thransfomation, but when I save the image in the callback **onResourceReady**, I get a **real circle image**, which is not what I want. 
I want to save **original image** and display **circle image**, so is there a callback or a way that I can get the origianl image before **circleCrop** transformation?

**Glide load line**:
```java
GlideApp
	.with(context)
	.asBitmap()
	.load(imageUrl)
	.transform(new MultiTransformation(
		new CenterCrop(),
		new CircleCrop() //make a circle image
	))
	.transition(BitmapTransitionOptions.withCrossFade())
	.into(new BitmapImageViewTarget(imageView) {
			@Override 
		  	public void onResourceReady(
				@NonNull Bitmap resource,
              	@Nullable Transition<? super Bitmap> transition) {
				//save bitmap,but it's a circle bitmap
		}
	);
```

**Comment by sjudd** [comment]
You'll need to make a second request for the non cropped image. 

Glide may return the circle cropped version from cache, so it's not guaranteed that it had to decode the original image to produce the circle cropped one. Moreover, the size you want may differ between the circle cropped image and the original so even if Glide does decode an intermediate Bitmap, it might not be the size you expect.

**Comment by ParadiseHell** [comment]
Thanks first.
I have fixed it by making a second request, but I cannot use **asFile** to download because of the exception, so I use **asBitmap** to download and save the bitmap to file.
