### ISSUE TITLE
Issue with create GlideApp

### ISSUE THREAD

**Issue by htw1** [bumptech/glide#3153]
HI !

I have created:

@GlideModule
public class MyAppGlideModule extends AppGlideModule {
}

I read :
http://bumptech.github.io/glide/doc/download-setup.html
http://bumptech.github.io/glide/doc/generatedapi.html#kotlin

I have created new project (test) with working GlideApp but in my main project I have problem..

so my gradle :

> apply plugin: 'com.android.application'
> apply plugin: 'kotlin-kapt'
> apply plugin: 'kotlin-android'
> apply plugin: 'kotlin-android-extensions'
> apply plugin: 'realm-android'
> 
> repositories {
>     mavenCentral()
>     maven { url 'https://maven.google.com' }
> }
> 
> android {
>     compileSdkVersion 27
>     buildToolsVersion '27.0.3'
>     defaultConfig {
>         multiDexEnabled true
>         applicationId 'com.example.htw.mytestapp'
>         minSdkVersion 16
>         targetSdkVersion 27
>         versionCode 1
>         versionName "1.0"
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
>     compileOptions {
>         targetCompatibility 1.8
>         sourceCompatibility 1.8
>     }
>     productFlavors {
>     }
> }
> dependencies {
>     compile 'hanks.xyz:htextview-library:0.1.5'
> 
>     implementation 'com.android.support:multidex:1.0.3'
> 
>     compile 'com.rengwuxian.materialedittext:library:2.1.4'
> 
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
> 
> 
>     compile 'org.greenrobot:eventbus:3.1.1'
>     implementation "android.arch.lifecycle:extensions:1.1.1"
> 
>     compile 'com.squareup.okhttp3:okhttp:3.10.0'
> 
> 
>     implementation 'com.github.bumptech.glide:glide:4.7.1'
>     implementation 'com.github.bumptech.glide:annotations:4.7.1'
>     annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
> 
>     implementation 'com.squareup.picasso:picasso:2.71828'
> 
>     implementation 'com.google.android.gms:play-services-ads:15.0.1'
>     implementation 'com.google.android.gms:play-services-auth:15.0.1'
> 
> 
>     // RETROFIT
>     compile 'com.squareup.retrofit2:retrofit:2.3.0'
>     compile 'com.squareup.retrofit2:converter-gson:2.2.0'
> 
>     implementation 'com.android.support:cardview-v7:27.1.1'
>     implementation 'com.android.support:recyclerview-v7:27.1.1'
>     implementation 'com.android.support:design:27.1.1'
>     implementation 'com.android.support:support-v4:27.1.1'
>     compile fileTree(include: ['*.jar'], dir: 'libs')
>     androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
>         exclude group: 'com.android.support', module: 'support-annotations'
>     })
>     compile 'com.android.support:appcompat-v7:27.1.1'
>     compile 'com.android.support.constraint:constraint-layout:1.1.0'
> 
>     // KOTLIN
>     testCompile 'junit:junit:4.12'
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
> 
>     //FIREBASE
>     implementation  'com.google.firebase:firebase-core:16.0.1'
>     implementation  'com.google.firebase:firebase-database:16.0.1'
>     implementation  'com.google.firebase:firebase-crash:16.0.1'
>     implementation  'com.google.firebase:firebase-auth:16.0.1'
>     implementation  'com.google.firebase:firebase-messaging:17.0.0'
>     implementation  'com.google.firebase:firebase-storage:16.0.1'
> 
>     implementation 'com.firebaseui:firebase-ui-database:4.0.1'
>     implementation 'com.firebaseui:firebase-ui-storage:4.0.1'
> 
>     implementation 'pub.devrel:easypermissions:1.2.0'
> 
>     // Dagger core
>     compile 'com.google.dagger:dagger:2.16'
>     annotationProcessor 'com.google.dagger:dagger-compiler:2.16'
> 
>     //to enable DaggerActivity, DaggerBroadcastReceiver, DaggerFragment etc classes
>     compile 'com.google.dagger:dagger-android:2.16'
>     annotationProcessor 'com.google.dagger:dagger-android-processor:2.16'
> 
>     //support libraries with dagger 2
>     compile 'com.google.dagger:dagger-android-support:2.16'
> 
>     implementation 'com.google.dagger:dagger:2.16'
>     kapt 'com.google.dagger:dagger-compiler:2.16'
> }
> 
> apply plugin: 'com.google.gms.google-services'
> com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

**NEXT :**

> buildscript {
> 
>     ext.SUPPORT_LIBRARY_VERSION = '26+'
>     ext.kotlin_version = '1.2.30'
> 
>     repositories {
>         google()
>         jcenter()
>         mavenCentral()
>         maven {  url 'https://maven.google.com' }
>     }
>     dependencies {
>         //classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
>         classpath 'com.android.tools.build:gradle:3.1.3'
>         classpath 'com.google.gms:google-services:4.0.1'
>         classpath "io.realm:realm-gradle-plugin:5.3.0"
> 
> 
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version" }
> 
> 
> }
> 
> allprojects {
> 
> 
>     repositories {
>         google()
>         jcenter()
>         mavenCentral()
>         maven {
>             url "$rootDir/../node_modules/react-native/android"
>         }
>         maven {
>             url 'https://maven.google.com'
>         }
>     }
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }

I have to put :

> com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

otherwise my bilg gradle have issue :

> The library com.google.android.gms:play-services-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 11.8.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

**Comment by sjudd** [comment]
Glide doesn't depend on play services. Why do you think this is related to Glide?

Consider StackOverflow as an alternative.

**Comment by htw1** [comment]
I fix my gradle issues.
My main issue is that I cannot create  GlideApp in my project.
