### ISSUE TITLE
Gifs play extremely slow on Android 6.0 with Glide 4.7.1

### ISSUE THREAD

**Issue by ParticleCore** [bumptech/glide#3154]
While trying to play a large sized gif (11mb) on Android 6 it plays very slowly, even if the gif is inside the app and not fetched from the network.
Smaller gifs play well, so I assume this is related to memory limit, is there anything that can be done to work around this?

I already tried the override down to 50x50, still plays extremely slow.

**Comment by ParticleCore** [comment]
Looks like even though Glide is overriding the size to the specified one, it is somehow keeping the original and causing the playback to become super slow. Slower the bigger it is in bytes size. Isn't there a way to ditch the original one after resizing? Or is this a wrong assumption on my part?

**Comment by sjudd** [comment]
Sounds like a duplicate of #2471, we've found some ways of speeding up the decoder, but performance can vary widely depending on the device, version of Android, and GIF.

Large GIFs that redraw most pixels each frame perform the worst. Android 5-6 seems to do worse than more recent versions of Android. 

Re-encoding GIFs actually typically makes performance worse. Most GIF creators do a better job of optimizing their GIFs than the encoder I was able to find for Glide. Glide v4 doesn't re encode GIFs by default, though there's an integration library you can use to try it (I don't recommend it).

**Comment by ParticleCore** [comment]
I'd rather use what the library supports, if you don't recommend it then I will not take the risk. I will leave it as it is then, thank you for the feedback.

**Comment by sjudd** [comment]
Sure, please feel free to contribute any suggestions you might have (or fixes you find) for improving performance of GIFs further. Ideas are always welcome.
