### ISSUE TITLE
Thumbnails are unexpectedly cropped.

### ISSUE THREAD

**Issue by johnmlee101** [bumptech/glide#3155]
This is a continuation of https://github.com/bumptech/glide/issues/3110
Where the internal version of Glide has since been updated to 4.7.1 but with the same configuration/code.

> 

**Glide Version**: ~4.1.1~ 4.7.1

**Integration libraries**: OkHttp3-3.10.0

**Device/Android Version**: Pixel 2 - 8.1.0, Galaxy S7 - 7.0

**Issue details / Repro steps / Use case background**: The image is not displayed properly, where the image isn't fully shown. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**: 
```java
fun ImageView.loadImage(uri: Uri, requestOptions: RequestOptions?, playTransition: Boolean) {
    val requestBuilder = Glide.with(context)
            .load(uri)

    if (playTransition) {
        requestBuilder.transition(DrawableTransitionOptions.withCrossFade())
    }

    if (requestOptions != null) {
        requestBuilder.apply(requestOptions)
    }

    requestBuilder.into(this)
}
```
```java
fun ImageView.loadImage(filenameOrUrl: String?, requestOptions: RequestOptions?,
                        playTransition: Boolean, onLoadEvent: (event: ImageViewLoadImageEvent) -> Unit) {

    if (filenameOrUrl == null) {
        onLoadEvent(ImageViewLoadImageEvent.ERROR)
        return
    }

    if (KotlinUtils.isLocal(filenameOrUrl)) {
        onLoadEvent(ImageViewLoadImageEvent.SUCCESS)
        val imageFile = YaplFileManager.getUriWithPath(filenameOrUrl)
        loadImage(imageFile, requestOptions, playTransition)
        return
    }

    setTag(R.id.image_tag_loading_url, filenameOrUrl)
    onLoadEvent(ImageViewLoadImageEvent.BEGIN_DOWNLOAD)

    DownloadManager.downloadFile(filenameOrUrl) { downloadFilename, success, downloadUrl ->

        if (getTag(R.id.image_tag_loading_url) as String? != downloadUrl) {
            return@downloadFile
        }

        if (!success) {
            onLoadEvent(ImageViewLoadImageEvent.ERROR)
            return@downloadFile
        }

        onLoadEvent(ImageViewLoadImageEvent.SUCCESS)
        val imageFile = File(YaplFileManager.getFilePath(downloadFilename))
        loadImage(Uri.fromFile(imageFile), requestOptions, playTransition)
    }
}
```

**Layout XML**:
```xml
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/content_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <yapl.android.navigation.views.custom.ShadowLayout
        android:id="@+id/shadow_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <yapl.android.misc.RoundedRelativeLayout
            android:id="@+id/main_container"
            android:layout_width="match_parent"
            android:layout_height="100dp"
            android:clipChildren="true">

            <ImageView
                android:id="@+id/receipt_image"
                android:layout_width="75dp"
                android:layout_height="match_parent"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true"
                android:layout_alignParentTop="true"
                tools:background="@color/gray" />
```

**Stack trace / LogCat**: None.

Screenshot:
![image](https://user-images.githubusercontent.com/5258036/40569363-d7314df2-6035-11e8-8278-46482c306db4.png)
Latest (4.7.1)
![image](https://user-images.githubusercontent.com/5258036/41622341-2027d516-73c4-11e8-9290-a3a831b5df25.png)

**Comment by AndrewGable** [comment]
@sjudd - We've confirmed this is happening in the related release (https://github.com/bumptech/glide/issues/3110#issuecomment-392934007), is there anything else we can attempt to resolve this?

**Comment by sjudd** [comment]
Sorry for the delay. Have you pulled the image files from the Uris you're passing in to loadImage and confirmed that they're valid? Most likely answer for images that you're attempting to download and then pass to Glide is that the files aren't fully written. 

Android's BitmapFactory is perfectly happy to decode partial files and provides no indication that they're partial. If you use Glide to download and provide a reasonable content size, Glide will detect that it failed to download the expected number of bytes and will typically fail the request. 

There are a few other options. cross fades have some known issues where they don't handle resizing very well. It's always possible to apply cropping transformations, either directly or via a scale type that produce unexpected behavior.

**Comment by johnmlee101** [comment]
@sjudd 
> cross fades have some known issues where they don't handle resizing very well.

Is there a recommended way to test this?

**Comment by AndrewGable** [comment]
@sjudd - We've also verified that all the images are valid via the URL, as to why we believe it might be the cross fade, however, we are confused on how to test/verify this. Do you have any suggestions?
