### ISSUE TITLE
Glide 4.7.1 not working

### ISSUE THREAD

**Issue by fizzappy2016** [bumptech/glide#3166]
compile 'com.github.bumptech.glide:glide:4.7.1' is not working.

**Comment by ArisChoice** [comment]
Same  for me
  compile 'com.github.bumptech.glide:glide:4.7.1'
not working

**Comment by sjudd** [comment]
Please fill out [the issue template][1] when filing new issues. "Not working" isn't enough information for anyone to start to help you. 

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md
