### ISSUE TITLE
How to cancel the loading of a single url after a url resource fails to load

### ISSUE THREAD

**Issue by bobojjk** [bumptech/glide#3168]
How to cancel the loading of a single url after a url resource fails to load？
When a url resource fails to load, it will repeat the request for this url.

**Comment by sjudd** [comment]
Glide.with(context).clear(). Please fill out the [issue template][1] when filing new issues and add it here if I didn't answer your question.

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md
