### ISSUE TITLE
URL request not been sent - can't see any crash/error

### ISSUE THREAD

**Issue by createS0ftware** [bumptech/glide#3169]
**Glide Version**: 4.7.1
**Integration libraries**: okhttp 4.7.1

Hi

I am trying to access and image (PNG) on a server but the request is not even sent. Can the URL formation crash the lib without an error message ? Or maybe it's sent but there is neither a failure response in the Request Listener nor a success.

How can i trace the problem ?

I have tried following the execution chain but i can only see the preparation of the request. 

I monitor the network with Charles and i can't see the request sent out

Thanks

**Comment by createS0ftware** [comment]
OK i figured it out.

I was passing an newly created ImageView in code that i was using to store the returned image temporarily. This had no dimensions.

This worked fine with the Picasso library, but stopped working when i changed to Glide. So passing a real ImageView that is visible in a layout, works.

Picasso had another issue with PNG's which is why i switched.

Not sure why Glide behaves like this but it works now

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/targets.html#sizes-and-dimensions
