### ISSUE TITLE
Is possible to make transformation to placeholder as well?

### ISSUE THREAD

**Issue by korkag** [bumptech/glide#317]
Let say i want to download image then to run circle transformation on it. Now i want to use placeholder as well. When placeholder image is displayed it has square canvas instead circle. Is it possible to run the transform (circle transform) to both placeholder and downloaded image?

Thanks

**Comment by floating-cat** [comment]
I asked a similar question before:
 https://github.com/bumptech/glide/issues/262

**Comment by korkag** [comment]
Currently i extend from AsyncImage and overriding onDraw method, something like:

```java
boolean isRoundedCorner
protected void onDraw(Canvas canvas) {

        if (isRoundedCorner) {
            float radius = 90.0f; // angle of round corners
            Path clipPath = new Path();
            RectF rect = new RectF(0, 0, this.getWidth(), this.getHeight());
            clipPath.addRoundRect(rect, radius, radius, Path.Direction.CW);
            canvas.clipPath(clipPath);
        }

        super.onDraw(canvas);
}
```

**Comment by sjudd** [comment]
It's unfortunately not possible to apply Transformations to placeholders. The only way to do this would be to require every Transformation implementation to apply both to the original type (Bitmap, GifData) and the placeholder type (Drawable), which would be inconvenient for many Transformations and not possible for others.

The most efficient way to do this would be to make your placeholder rounded (ie modify the image in resources). I understand that's not always possible though.

**Comment by floating-cat** [comment]
I recommend to use https://github.com/vinc3m1/RoundedImageView (which is faster and better) or other similar (like [this](https://github.com/hdodenhof/CircleImageView) instead of circle transform. Or as sjudd suggested to make your placeholder rounded.

**Comment by Teovald** [comment]
I ran into a similar issue.  
I am using the support lib  v4 RoundedBitmapDrawable in order to implement a RoundedImageView. This way I cover both rounded rectangles and circles. 
In instances where I can't just use a rounded placeholder, I just create a RoundedBitmapDrawable from this resource and feed it to Glide as with .placeholder(drawable).  
The only limitation is that BitmapShaders don't mesh well with LayerDrawable or ValueAnimator, so it is not possible to animate the transition from placeholder to final image.

**Comment by sjudd** [comment]
Thanks for the input guys. I'm going to close this, I don't think we're ever going to get to the point where we can consistently transform placeholders. A custom placeholder resource, or a special view may be the best way to go.

**Comment by TWiStErRob** [comment]
Potential workarounds in #1077.
