### ISSUE TITLE
Where is GlideApp? I see only Glide

### ISSUE THREAD

**Issue by anonym24** [bumptech/glide#3170]
Example says

```
GlideApp
    .with(myFragment)
    .load(url)
    .centerCrop()
    .placeholder(R.drawable.loading_spinner)
    .into(myImageView);
```

but `GlideApp` doesn't even exist, at least when using:

```
 implementation 'com.github.bumptech.glide:glide:4.7.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
```

and some methods don't exist

```
Glide.with(mContext)
                        .load(thumbnail.getUrl())
                        //.centerCrop() // such method doesn't exist
                        //.placeholder(R.drawable.placeholder) // such method doesn't exist
                        //.diskCacheStrategy(DiskCacheStrategy.ALL) // such method doesn't exist
                        .into(thumb);
```

So I just use this little solution xD

```
Glide.with(mContext).load(thumbnail.getUrl()).into(thumb);
```

**Comment by taoqiyang** [comment]
The Apis changed a lot, dude. See the RequestOptions class.
`options = new RequestOptions();
        options.placeholder(..)
                .centerCrop()
                .diskCacheStrategy(..);
Glide.with( context )
                .load( url )
                .apply(options)
                .into( image );`

**Comment by nguyenthanhduy91** [comment]
I create class MyAppGlideModule and select Build->clean project & Build->rebuild project. GlideApp is created.
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;
@GlideModule
public class MyAppGlideModule extends AppGlideModule {
}

**Comment by anonym24** [comment]
@taoqiyang  no, seems GlideApp still exists somewhere: http://bumptech.github.io/glide/doc/generatedapi.html

> The API is generated in the same package as the AppGlideModule implementation provided by the application and is named GlideApp by default. Applications can use the API by starting all loads with GlideApp.with() instead of Glide.with():
> 
> GlideApp.with(fragment)
>    .load(myUrl)
>    .placeholder(R.drawable.placeholder)
>    .fitCenter()
>    .into(imageView);
> Unlike Glide.with() options like fitCenter() and placeholder() are available directly on the builder and don’t need to be passed in as a separate RequestOptions object.

and why I get that:

> Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

**Comment by anonym24** [comment]
I solved Failed to find **GeneratedAppGlideModule** issue with creating next class:

```
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;

@GlideModule
public final class MyAppGlideModule extends AppGlideModule {}
```

but still I can use only `Glide`

What is `GlideApp ` is supposed to be? Where is it?

**Comment by taoqiyang** [comment]
@anonym24  i see... thx.

**Comment by quzn** [comment]
good
