### ISSUE TITLE
Glide doesnt get the picture from my firebase

### ISSUE THREAD

**Issue by bradridsect** [bumptech/glide#3172]
Hello, i trying to take a picture from the firebase and inserted into the image placeholder. My Firebase show the image already been uploaded and when im trying to get the picture from firebase using glide its show nothing. 

here is my code 

               ` mFireStore.collection("Profile On9Biz").document(currentUserID).get().addOnCompleteListener(new 
               OnCompleteListener<DocumentSnapshot>() {
                @Override
                public void onComplete(@NonNull Task<DocumentSnapshot> task) {

                    if (task.isSuccessful()) {

                        if (task.getResult().exists()) {

                            String fullname = task.getResult().getString("Full Name");
                            String email = task.getResult().getString("Email");
                            String location = task.getResult().getString("Location");
                            String image = task.getResult().getString("profile_images");

                            textViewFullName.setText(fullname);
                            textViewEmail.setText(email);
                            textViewLocation.setText(location);

                            RequestOptions placeholderRequest = new RequestOptions();
                            placeholderRequest.placeholder(R.drawable.profile);

                            Glide.with(ProfileActivity.this).setDefaultRequestOptions(placeholderRequest).load(image).into(profileImageProfile);
                            

                        } else {

                            Toast.makeText(ProfileActivity.this, "Please complete your registration information..", Toast.LENGTH_SHORT).show();
                            SendUserToSetup();

                        }

                    } else {

                        Toast.makeText(ProfileActivity.this, "Firebase Error", Toast.LENGTH_SHORT).show();

                    }
                }
            });`

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/debugging.html to start

**Comment by bradridsect** [comment]
thanks.. i already fix it..
