### ISSUE TITLE
Glide Cache and decode managment

### ISSUE THREAD

**Issue by vavadiyahiren** [bumptech/glide#3177]
Hi Team,

**This is not an issue, but the question**

I am using glide in my android application to load image in multiple places one of them in recycler view.

I have read some documents about glide that it is loaing image faster and also have capability of caching mechanism to minimize loading time. 

But i got one question before use this library is below

1.  How much images are cached in glide and how frequently the cache are cleared. If i am loading image from the local path does any meaning to cache the image because it won't get image from server locally it will be avaible so does any perfomance impect after using glide for local images or we didn't get any benifit once we download that image.
2. Where does it store the cache data if i clear the cache data from the app then does it remain same or it will be gone ?
3. Does any configuration available to customise to override default caching settings?

Note

1. Glide version - 4.7.1
2. I have more then 1000 images in my recycler view.

Thanks,
Hiren vavadiya

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/caching.html.

For 1) see the documentation link above. 
2) By default yes clearing cache data clears Glide's cache.
3) Yes, see the documentation link.
