### ISSUE TITLE
The picture is not displayed correctly, with a strip color band。Have anyone ever met？

### ISSUE THREAD

**Issue by cby0310** [bumptech/glide#3182]
**screen**：1080x2016
**os**: 7.1.1
**phone**: OPPO R11s
**network**: wifi
**glide verison**: 4.4.8
**okhttp version** : 0.0.6
**use like this**：
  RequestOptions options = new RequestOptions();
  options.placeholder(R.drawable.ic_launcher);
  Glide.with(mContext).load("").apply(options).into(iv);
**and image show like this**:
![qq 20180704105205](https://user-images.githubusercontent.com/6885903/42254870-7a40c5b8-7f7b-11e8-9fc8-02791bcc3611.png)

Thanks ！

**Comment by sjudd** [comment]
If you're able to reproduce this by just decoding the image with BitmapFactory directly, then it's probably an issue with the image itself or, less likely, a bug in the framework. 

If you're only able to reproduce this when using Glide, it may be corruption from incorrect Bitmap re-use, see http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors

**Comment by xiaodao1990** [comment]
@cby0310 你好，你的问题解决了吗？我也遇到这种情况了

**Comment by xiaodao1990** [comment]
screen：1920*1080
sdk: 17
glide verison: 4.3.1
use like this：
GlideApp.with(TabFragment.this).load(imgUrl).diskCacheStrategy(DiskCacheStrategy.RESOURCE).placeholder(R.drawable.default_logo_s).override(finalWidth, finalHeight).into(view);
![_20180813155024](https://user-images.githubusercontent.com/13122193/44019235-c24e30de-9f10-11e8-89c7-4c5210dc7242.jpg)
