### ISSUE TITLE
Is it possible to make placeholder/error/fallback drawables fitCenter()?

### ISSUE THREAD

**Issue by jahirfiquitiva** [bumptech/glide#3186]
**Glide Version**: 4.7.1

**Integration libraries**: None

**Device/Android Version**: Moto G5S Plus - Android 8.1.0

**Issue details / Repro steps / Use case background**: 
I would like to know if it's possible to make the placeholder/error/fallback drawables fitCenter() even before the target picture loads, and if so, how could I achieve it?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
var options = RequestOptions()
        .format(DecodeFormat.PREFER_ARGB_8888)
        .disallowHardwareConfig()
        .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
        .priority(Priority.HIGH)
        .timeout(10000)
        .placeholder(placeholder)
        .fallback(placeholder)
        .error(placeholder)
		.optionalFitCenter()
    
Glide.with(this)
	.load(url)
    .apply(options)
    .transition(DrawableTransitionOptions.withCrossFade(500))
    .listener(listener)
	.into(view)
```

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/placeholders.html#are-transformations-applied-to-placeholders
