### ISSUE TITLE
Can we create round corner image using glide?

### ISSUE THREAD

**Issue by shailesh-fusionitechnology** [bumptech/glide#3189]
I need to showing image in round corner view. Can it possible to make round corner with glide library?
If it is possible then how can we implement it?

**Comment by friederikewild** [comment]
@shailesh-fusionitechnology I managed to show images with rounded corners using `RoundedCorners`. I even found multiple variations (in case you want to combine it with a center crop transformation). Here is some kotlin code, hope that helps:

Define radius in dimens.xml:
```
<dimen name="corner_radius">8dp</dimen>
```

```
val radius = context.resources.getDimensionPixelSize(R.dimen.corner_radius)
GlideApp.with(context)
    .load(pvlse.pictureUrl)
    .transform(RoundedCorners(radius))
    // Alternative: .transforms(CenterCrop(), RoundedCorners(radius))
    .placeholder(R.drawable.placeholder_thumbnail_square_primary)
    .error(R.drawable.placeholder_thumbnail_square_primary)
    .transition(DrawableTransitionOptions.withCrossFade()).into(imageView)
```

Here is the defined placeholder that I also use on error: 

placeholder_thumbnail_square_primary.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<layer-list
    xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape>
            <solid android:color="@color/colorAccent" />

            <corners android:radius="@dimen/corner_radius" />

            <size
                android:width="24dp"
                android:height="24dp" />
        </shape>
    </item>

    <item
        android:gravity="center"
        android:drawable="@drawable/ic_profile_placeholder" />

</layer-list>

```

**However:** I've come across a bug where the placeholder corners get flattened out on the first loading of an image. So if you don't need one or can define one that has the background color, that would be beneficial. See my bug report here: https://github.com/bumptech/glide/issues/3195

**Note** that I'm using the variation of Glide that includes the build of a `GlideModule`. But it might also work with just `Glide.with`

**Comment by deathstroke007** [comment]
@friederikewild Will the Transformations work on SVGs? I am trying to do it to SVGs but not working.
You may refer to the issue I opened. https://github.com/bumptech/glide/issues/4026#issue-542631776

**Comment by mochadwi** [comment]
I still have problem with rounded corner transformation: https://github.com/bumptech/glide/issues/3020#issuecomment-576363866

a few of my image rounded & a few others not #3020
