### ISSUE TITLE
Not an issue but enquiry

### ISSUE THREAD

**Issue by ShivamPokhriyal** [bumptech/glide#3194]
Is it possible to show previously downloaded image in Glide as placeholder while downloading new image.
Like i have an image loaded in imageview using glide. now the imageurl is changed, so while downloading this new image is it possible to keep displaying the old image(might be from cache).

**Comment by sjudd** [comment]
Yes, you can use thumbnail for this, just make the old image the thumbnail request and the new one the main request: http://bumptech.github.io/glide/doc/options.html#thumbnail-requests
