### ISSUE TITLE
Glide online/offline mode

### ISSUE THREAD

**Issue by ronakmob** [bumptech/glide#3203]
Hi,

I am using Glide v4.7.1 and Device Pixel 2 running Android 8.1.0.

I am working on one of the functionality where I have to User profile from the cache if the connection is unavailable and if the connection is available then pull the image from Server. The server always returns same profile URL for each avatar.

I am using `diskCacheStrategy(all)` to have Avatar in Cache and Using `signature` to have unqiue value if the connection is available.

Glide doesn't update available image from the server as URLs are same. I am using below code.

     RequestOptions requestOptions = new RequestOptions();
            requestOptions = requestOptions.apply(requestOptions.circleCrop());
            requestOptions = requestOptions.diskCacheStrategy(DiskCacheStrategy.ALL);
            requestOptions = requestOptions.signature(new 
            ObjectKey(String.valueOf(System.currentTimeMillis())));
            if (imgUrl.startsWith("http")) {
                Glide.with(getActivity()).load(imgUrl).thumbnail(0.025f).apply(requestOptions).into(userImg);
            } else {
                Glide.with(getActivity()).load(new File(imgUrl)).thumbnail(0.025f).apply(requestOptions).into(userImg);
            }

How can I manage cache mode and unique image (for same URL) mode, I can have both conditions .

Thank you

**Comment by sjudd** [comment]
Using signature is the right approach. See http://bumptech.github.io/glide/doc/caching.html#cache-keys and http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses

**Comment by ronakmob** [comment]
Right but it prevents Offline access, so Signature + Cache = Offline doesn't work. It won't load the image.

**Comment by ronakmob** [comment]
Please let me know if I am doing anything wrong.

**Comment by sjudd** [comment]
You could either keep track of the signature of the last successful load or just use the previous signature and pass that load as the [`error`][1] of the new image with the up to date signature.

If you have internet access, the new image will be loaded normally. If you don't have internet access and the new image isn't in cache, then the primary request will fail. When the primary request fails, the `error` API will then start the request for the previous image. If the previous image is in cache, it will be loaded successfully.

[1]: http://bumptech.github.io/glide/javadocs/480/com/bumptech/glide/RequestBuilder.html#error-com.bumptech.glide.RequestBuilder-
