### ISSUE TITLE
Glide 4.71 内存缓存硬件缓存失效问题

### ISSUE THREAD

**Issue by AFeiDaRen** [bumptech/glide#3204]
RequestOptions options = new RequestOptions()
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .signature(new ObjectKey(phtotoVersion))
                .placeholder(SkinTool.init().getDrawable(context, R.mipmap.default_head_image)).circleCropTransform();

我进行了这样的设置  发现了问题  内存缓存和硬件缓存都失效了
好像是最后的circleCropTransform() 导致的  下面这样设置却是可以的
RequestOptions options = new RequestOptions()
                .circleCropTransform()
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .signature(new ObjectKey(phtotoVersion))
                .placeholder(SkinTool.init().getDrawable(context, R.mipmap.default_head_image));
把circleCropTransform()放到了第一个

**Comment by g19980115** [comment]
点击`circleCropTransform()`查看源码
```Java
public static RequestOptions circleCropTransform() {
    if (circleCropOptions == null) {
      circleCropOptions = new RequestOptions()
          .circleCrop()
          .autoClone();
    }
    return circleCropOptions;
  }
```
这个地方应该是被重新初始化了，所以你应该把`circleCropTransform`放到最前方

**Comment by AFeiDaRen** [comment]
啊哈哈哈  看到提问都是用英文  突然想用中文提问  多优秀啊 嘻嘻
