### ISSUE TITLE
First run

### ISSUE THREAD

**Issue by asdasdasdasddasasdasdasdasddas** [bumptech/glide#3209]
Hi!

Im using CircleImageView and Glide, and thank you a lot. It really helped me but theres a problem. I hope this description wont be messy :) I will put myself into place of new registered user...

I'm registrated and now I want to set my profile picture. I click on default image, choose some, crop it and finish. While im doing this there is a defualt profile picture (placeholder). Now that CircleImageView should show me cropped profile picture BUT NOT THIS TIME . Default picture is still there. It isnt changed (so it means user WONT see picture that he chose).

Okay, lets proceed. I have clicked save settings (upload that image at Firebase). It wont be so weird (maybe just for me) if that CircleImageView wouldnt show choosen profile picture on next run so it means the picture is uploaded and now when I want to set another profile picture after cropping new one is shown in CircleImageView (user WILL see picture that he chose) :O

is it Glide or?

**Comment by sjudd** [comment]
CircleImageView and Glide don't always play well together, check: https://github.com/bumptech/glide#compatibility and https://github.com/bumptech/glide/issues?q=is%3Aissue+CircleImageView+OR+CircularImageView+OR+RoundedImageView
