### ISSUE TITLE
Access bitmap from cache manually

### ISSUE THREAD

**Issue by Holidaybear** [bumptech/glide#321]
Is it possible to manually save the bitmap into the cache (BitmapPool?) with the key string, and then get it by using the same key later? Because I want to put my blur bitmap into Glide after I finished blur task, and help me manage bitmap recycling if he can.
Thanks. :)
e.g.
```
xxx.saveCache(url+BLUR_SUFFIX, bitmap);
xxx.loadCache(url+BLUR_SUFFIX);
```

**Comment by sjudd** [comment]
It's not possible to interact with Glide's caches directly. The BitmapPool only stores Bitmaps by size so they can be re-used.

That said, if you can implement your blur in a custom [Transformation][1], whatever Bitmap your Transformation produces will be managed by Glide just like every other request.

If you're obtaining the Bitmap in some special way, you could also consider a custom 
[ResourceDecoder][2], although that's somewhat more complex. See the [SVG decoder][3] and usage in the [SVG sample][4] for an example.

[1]: https://github.com/bumptech/glide/wiki/Transformations
[2]: http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/load/ResourceDecoder.html
[3]: https://github.com/bumptech/glide/blob/master/samples/svg/src/main/java/com/bumptech/svgsample/app/SvgDecoder.java
[4]: https://github.com/bumptech/glide/blob/master/samples/svg/src/main/java/com/bumptech/svgsample/app/MainActivity.java

**Comment by Holidaybear** [comment]
Thanks. I have tried it by using custom Transformation, and it works. :+1:

**Comment by sjudd** [comment]
Great glad to hear it.
