### ISSUE TITLE
glide with isCrossFade,placeholder,circleCrop display abnormality

### ISSUE THREAD

**Issue by PingerOne** [bumptech/glide#3210]
![图片](http://static.v.xingyunyd.com/live/f431a6a5-2d57-4a18-b389-8dc00abc87ef.png)

### Question
* Version：the version is the latest．
* Code
    * `options.circleCrop()`
    * `options.placeholder(config.placeHolderResId)`
    * `builder.transition(BitmapTransitionOptions.withCrossFade())`

### Description
* This phenomenon includes the use of `RoundedCorners` and others transformation
* The placeholder is `ColorDrawable`,and source is circleCrop Drawable.
* I find the reason is class `DrawableCrossFadeTransition` of function `transition(...)` has a conversion to drawable with placehold and ready source.

### Current Solution
* I have to remove `builder.transition(BitmapTransitionOptions.withCrossFade())` 
* I hope that the official can solve this problem.

**Comment by sjudd** [comment]
Sounds like http://bumptech.github.io/glide/doc/transitions.html#cross-fading-with-placeholders-and-transparent-images
