### ISSUE TITLE
Disable upscaling

### ISSUE THREAD

**Issue by Twister21** [bumptech/glide#3215]
Hello,

I need  to get a local image on the smartphone device as a Java file using Glide and it's scaling options.

However, I don't know how to disable the default upscaling of images. I've got the following source code:

```
FutureTarget<File> future = Glide.with(this)
                    .asFile()
                    .load(uri)
                    .apply(new RequestOptions()
                            .override(1200))
                    .submit();
```
So, the limit of 1200px for the width or height of the image shouldn't be exceeded. Otherwise, Glide has to scale the image down. All other images which are smaller than the mentioned value need to be in the original size. How to do so without loosing the original image ratio?

**Comment by Twister21** [comment]
I haven't found a solution for my issue yet.

**Comment by sjudd** [comment]
Pick a useful [`DownsampleStrategy`][1], in particular [`CENTER_INSIDE`][2] may be what you're looking for. The default `DownsampleStrategy` will upscale to maximimize Bitmap re-use, but typically there's an equivalent strategy available that will not upscale. 

[1]: http://bumptech.github.io/glide/javadocs/480/com/bumptech/glide/load/resource/bitmap/DownsampleStrategy.html
[2]: http://bumptech.github.io/glide/javadocs/480/com/bumptech/glide/load/resource/bitmap/DownsampleStrategy.html#CENTER_INSIDE
