### ISSUE TITLE
Problem When Using futureTargetbmp = Glide.with(context).asBitmap().load(imgurl).submit(w, h);  to resize a bitmap does not resize height correctly

### ISSUE THREAD

**Issue by s1nc1tycyph3r** [bumptech/glide#3216]
** Glide v. 4.7.1**:

**using volley integration library v. 1.1.0**:

**resizing incorrectly on Alcatel Idol 4/Alcatel 6055U** and LG Escape 3/LG-K373:

**Ok I'm currently Working on an android App with which i use Glide Library to load and manage images ,my app is an image and video editing app that allows users to create Videos using their photos,videos, and music from their phone. The issue i'm having is when i try to resize a loaded png image using Glide futureTarget method with submit(w, h) to resize it according to w, h! for some reason it resizes the image Maintaining the aspect ratio and i need it to ignore the aspect ratio otherwise the image gets cut off at the bottom, / OK I've included the section of code that is giving me the issue Below/ The reason I'm trying to resize the image and ignore the aspect ratio is because the image is a Picture Frame Filter that users can apply to their project within my app, and it needs to be resized to properly border the images,or,videos in their project!**: 

**
private class MakeAppFreeFilterFrameLocalCopyTask extends AsyncTask<String,Integer,List<Bitmap>> {
        // Before the tasks execution
        protected void onPreExecute(){

           /* mProgressDialog = new ProgressDialog(PictagramHomeActivity.this);
            mProgressDialog.setIndeterminate(false);
            // Progress dialog horizontal style
            mProgressDialog.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);
            // Progress dialog title
            mProgressDialog.setTitle("Preparing Content");
            // Progress dialog message
            mProgressDialog.setMessage("Please wait, we are preparing your Content...");
            // Display the progress dialog on async task start
            mProgressDialog.setCanceledOnTouchOutside(false);
            mProgressDialog.setCancelable(false);
            mProgressDialog.show();

            mProgressDialog.setProgress(0);*/
        }

        // Do the task in background/non UI thread
        protected List<Bitmap> doInBackground(String...paths) {
            int count = paths.length;
            //URL url = urls[0];
            //HttpURLConnection connection = null;
            List<Bitmap> bitmaps = new ArrayList<>();

            
            Display display;
            display = Config.audioActivity.getWindowManager().getDefaultDisplay();
            Point displaySize;
            displaySize = new Point();
            display.getSize(displaySize);
            
            
            try {
                Thread.sleep(Config.DEBUG_THREAD_DELAY);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            //previewframe is the viewframe where the user can preview how their project will look after //compiling their video, previewframe // on My Alcatel Idol 4 this frame is 1080 x 1680 which is the size //for which i need to resize the bitmap image to
//
            Bitmap bmptemp = loadBitmapFromViewDrawingCache((View) previewframe);
            
            boolean success=saveBitmapToAppCustomPrivateDir(bmptemp,"framefilters", baseframefilternames[ffindex]);
// load the original image as a bitmap from the raw resourcedirectory
            Bitmap bmpraw= BitmapFactory.decodeStream(getResources().openRawResource(framefilterresourceids[ffindex]));
            //save it to the 'framefilters' directory within the app folder
            saveBitmapToAppCustomPrivateDir(bmpraw,"framefilters","orig_"+baseframefilternames[ffindex]);
            String framefilterspath = getPathFromSettings("framefilters");
            String ImgUrl = framefilterspath + baseframefilternames[ffindex];
            try {
                if(success) {
//load the original image that we saved to the apps 'framefilters' directory for which we will will resize 
                    futureTargettempbmp = Glide.with(Config.audioActivity).asBitmap().load(ImgUrl).submit();

                    Bitmap bmpref = futureTargettempbmp.get();
//calculate a float value for width and height to resize with
//take the target image width and height and divide each by the original image width and height to get the fractionalwidth/ fractionalheight factor (i.e scaling factor)
                    double fractionalwidth=((float)bmpref.getWidth()/bmpraw.getWidth());
                    double fractionalheight=((float)bmpref.getHeight()/bmpraw.getHeight());
                   //now calculate the desired target width/height by multiplying the original images 
// width/height by the fractionalwidth/fractionalheight to get the desired target width / height
                    int newwidth=(int)Math.round(bmpraw.getWidth()*fractionalwidth);
                    int newheight=(int)Math.round(bmpraw.getHeight()*fractionalheight);
                    
                    String ImgUrl2 = framefilterspath + "orig_"+baseframefilternames[ffindex];
                    
                    Log.i("newwidth", Integer.toString(newwidth));
                    Log.i("newheight", Integer.toString(newheight));
//Config.audioActivity is a static reference to the Current Activity
//load the image we want to resize into a futureTarget then resize it using //Glide.with(context).asBitmap()load(imgtoresize).submit(w,h);
                    futureTargetbmp = Glide.with(Config.audioActivity).asBitmap().load(ImgUrl2).apply(RequestOptions.overrideOf(newwidth, newheight)).apply(RequestOptions.skipMemoryCacheOf(true)).apply(RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.NONE)).submit(newwidth, newheight);
// retrieve the newly created bitmap from the futureTarget                    
Bitmap filterframe = futureTargetbmp.get();
                    
                     Log.i("filterframe ","filterframe width: "+Integer.toString(filterframe.getWidth())+"\n"+"filterframe height: "+Integer.toString(filterframe.getHeight()));
// add the newly created/resized bitmap to a bitmap array list for use in the onPostExecute method of this 
//Async code
                        bitmaps.add(filterframe);
                        
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (ExecutionException e) {
                e.printStackTrace();
            } finally {

                // Disconnect the http url connection
                //connection.disconnect();
                if (futureTargettemp != null) {
                    futureTargettemp.cancel(false);
                }
                if (futureTarget != null) {
                    futureTarget.cancel(false);
                }

            }

            //}
            // Return bitmap list
            return bitmaps;
        }

        // On progress update
        protected void onProgressUpdate(Integer... progress){
            // Update the progress bar
           // mProgressDialog.setProgress(progress[0]);
        }

        // On AsyncTask cancelled
        protected void onCancelled(){
            //Toast.makeText(getBaseContext(), "Task Cancelled",Toast.LENGTH_LONG).show();
        }

        // When all async task done
        protected void onPostExecute(List<Bitmap> result){

            // Remove all views from linear layout
            //mLLayout.removeAllViews();

            // Loop through the bitmap list

//make sure we have a valid bitmap ArrayList
                if(result.size()>0)
                {
                   
                    Bitmap filterframe=result.get(0);
                    boolean success = saveBitmapToAppCustomPrivateDir(filterframe, "framefilters", framefilternames[ffindex]);
//finally process the images in the users project using ProcessPictagramImagesAsyncTask()
                    processPictagramImagesAsyncTask=new ProcessPictagramImagesAsyncTask();
                    processPictagramImagesAsyncTask.execute(0, imagestouse.size());
                }
           

        }
    }
**:

**pictagram_preview_activity.xml**:
```xml
<FrameLayout
        android:id="@+id/previewframe"
        android:layout_width="720dp"
        android:layout_height="1210dp"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:background="@android:color/black">

        <ImageView
            android:id="@+id/previewImageView"
            android:layout_width="720dp"
            android:layout_height="1210dp"
            android:layout_gravity="center_vertical|center_horizontal"
            android:src="@android:color/black" />

        <VideoView
            android:id="@+id/previewVideoView"
            android:layout_width="720dp"
            android:layout_height="1280dp"
            android:layout_gravity="center_vertical|center_horizontal"
            android:visibility="gone" />

        <ImageView
            android:id="@+id/framefilterView"
            android:layout_width="720dp"
            android:layout_height="1210dp"
            android:layout_gravity="center_vertical|center_horizontal"
            android:scaleType="fitXY"
            android:src="@drawable/frame_snakeskin_pink_portrait"
            android:visibility="gone" />

        <ImageView
            android:id="@+id/fadeinfadeoutImageView"
            android:layout_width="720dp"
            android:layout_height="1210dp"
            android:layout_gravity="center_vertical|center_horizontal"
            android:alpha="1"
            android:background="@android:color/black"
            android:scaleType="fitXY"
            android:visibility="gone" />

        <ImageButton
            android:id="@+id/playbutton"
            android:layout_width="128dp"
            android:layout_height="128dp"
            android:layout_gravity="center"
            android:layout_margin="24dp"
            android:background="@android:color/transparent"
            android:scaleType="fitXY"
            app:srcCompat="@android:drawable/ic_media_play" />

        <ImageButton
            android:id="@+id/previousbutton"
            android:layout_width="128dp"
            android:layout_height="128dp"
            android:layout_gravity="left|center_vertical"
            android:layout_marginLeft="96dp"
            android:background="@android:color/transparent"
            android:scaleType="fitXY"
            app:srcCompat="@android:drawable/ic_media_previous" />

    </FrameLayout>
```

**Stack trace / LogCat**:
```07-21 19:36:08.639 3275-26698/? I/ExtendedUtils: printFileName fd(88) -> /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:08.657 25600-25600/? E/file: /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:08.673 3275-23822/? I/ExtendedNuUtils: printFileName fd(83) -> /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:08.735 25600-25600/? D/DrmMediaPlayer: isDrmEnable uri = file:///storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:08.749 25600-25600/? V/TctDrmLog/TctDrmManagerClient: File path after standardized is: /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:08.755 25600-25600/? D/DrmMediaPlayer: isDrmEnable uri = file:///storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:08.755 25600-25600/? V/TctDrmLog/TctDrmManagerClient: File path after standardized is: /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:09.559 25600-25600/? I/pictagrampath: /storage/emulated/0/Pictagram
07-21 19:36:10.301 25600-25615/? I/pictagrampath: /storage/emulated/0/Pictagram/framefilters/base_vintage_gold_frame_portrait.png
07-21 19:36:10.382 25600-25615/? I/pictagrampath: /storage/emulated/0/Pictagram/framefilters/orig_base_vintage_gold_frame_portrait.png
07-21 19:36:10.386 25600-25615/? I/pictagrampath: /storage/emulated/0/Pictagram/framefilters/
07-21 19:36:10.582 25600-25600/? I/pictagrampath: /storage/emulated/0/Pictagram/framefilters/vintage_gold_frame_portrait.png
07-21 19:36:10.625 25600-25616/? I/pictagrampath: /storage/emulated/0/Pictagram/projectvideos/
07-21 19:36:10.626 25600-25616/? I/pictagrampath: /storage/emulated/0/Pictagram/coverimages/
07-21 19:36:10.659 3275-22875/? I/ExtendedUtils: printFileName fd(137) -> /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:10.681 25600-25600/? E/file: /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:10.738 3275-23822/? I/ExtendedNuUtils: printFileName fd(84) -> /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:10.801 25600-25600/? D/DrmMediaPlayer: isDrmEnable uri = file:///storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:10.801 25600-25600/? V/TctDrmLog/TctDrmManagerClient: File path after standardized is: /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:10.807 25600-25600/? D/DrmMediaPlayer: isDrmEnable uri = file:///storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:10.807 25600-25600/? V/TctDrmLog/TctDrmManagerClient: File path after standardized is: /storage/emulated/0/Pictagram/video/VID_20180703_152418.mp4
07-21 19:36:11.840 4073-4138/? I/ActivityManager: START u0 {cmp=com.primagemedia.pictagram/.EncodeVideoActivity (has extras)} from uid 10269 on display 0
```

![screenshot_20180721-193611](https://user-images.githubusercontent.com/1006688/43041740-d3946ca0-8d1d-11e8-807d-ec834db8c5e7.png)
![screenshot_20180721-193022](https://user-images.githubusercontent.com/1006688/43041741-d8d7badc-8d1d-11e8-861f-ecf6b821c1c7.png)
![screenshot_20180721-180127](https://user-images.githubusercontent.com/1006688/43041742-e1fd5b44-8d1d-11e8-95c8-cb5213beeaa2.png)

**Comment by s1nc1tycyph3r** [comment]
also i forgot to include the relevant String arrays that were used for the images that are being resized here they are
int[] framefilterresourceids={R.raw.art_deco_frame_square, R.raw.art_deco_frame_portrait, R.raw.art_deco_frame_landscape,R.raw.golden_trim_frame_square,R.raw.golden_trim_frame_portrait,R.raw.golden_trim_frame_landscape, R.raw.modern_professional_frame_square,R.raw.modern_professional_frame_portrait,R.raw.modern_professional_frame_landscape, R.raw.snakeskin_frame_pink_square,R.raw.snakeskin_frame_pink_portrait,R.raw.snakeskin_frame_pink_landscape, R.raw.vintage_gold_frame_square,R.raw.vintage_gold_frame_portrait,R.raw.vintage_gold_frame_landscape};
    String[] baseframefilternames={"base_art_deco_frame_square.png", "base_art_deco_frame_portrait.png","base_art_deco_frame_landscape.png","base_golden_trim_frame_square.png", "base_golden_trim_frame_portrait.png","base_golden_trim_frame_landscape.png","base_modern_professional_frame_square.png","base_modern_professional_frame_portrait.png","base_modern_professional_frame_landscape.png", "base_snakeskin_frame_pink_square.png", "base_snakeskin_frame_pink_portrait.png", "base_snakeskin_frame_pink_landscape.png", "base_vintage_gold_frame_square.png", "base_vintage_gold_frame_portrait.png","base_vintage_gold_frame_landscape.png"};
    String[] framefilternames={"art_deco_frame_square.png", "art_deco_frame_portrait.png","art_deco_frame_landscape.png","golden_trim_frame_square.png","golden_trim_frame_portrait.png","golden_trim_frame_landscape.png", "modern_professional_frame_square.png","modern_professional_frame_portrait.png","modern_professional_frame_landscape.png", "snakeskin_frame_pink_square.png","snakeskin_frame_pink_portrait.png","snakeskin_frame_pink_landscape.png", "vintage_gold_frame_square.png", "vintage_gold_frame_portrait.png", "vintage_gold_frame_landscape.png"};

**Comment by sjudd** [comment]
If you want to ignore aspect ratio, pick (or define) a reasonable [`DownsampleStrategy`][1] or [`Transformation`][2]. You'll need to look through the javadocs to see if there's one that has the behavior you want. If there isn't, you can always define your own.

[1]: http://bumptech.github.io/glide/javadocs/480/com/bumptech/glide/load/resource/bitmap/DownsampleStrategy.html
[2]: http://bumptech.github.io/glide/javadocs/480/com/bumptech/glide/load/Transformation.html
