### ISSUE TITLE
How could load a image which is CYMK but not RGB?

### ISSUE THREAD

**Issue by Le0nHsu** [bumptech/glide#3219]
**Glide Version**: glide:4.7.1

**Integration libraries**:

**Device/Android Version**: Mi 4

**Issue details / Repro steps / Use case background**: 
class com.bumptech.glide.load.engine.GlideException: Failed to load resource

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
  GlideApp.with(getActivity()).load(sHeadPaths).into(headImage);

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Android doesn't support CMYK as far as I know. See also #2392
