### ISSUE TITLE
com.bumptech.glide.manager.RequestTracker.pauseRequests (SourceFile:57) (NullPointerException)

### ISSUE THREAD

**Issue by ulx** [bumptech/glide#322]
Hi !
use v3.5
e.manager.RequestTracker.pauseRequests (SourceFile:57)
com.bumptech.glide.RequestManager.pauseRequests (SourceFile:151)
com.bumptech.glide.RequestManager.onStop (SourceFile:181)
com.bumptech.glide.manager.ActivityFragmentLifecycle.onStop (SourceFile:55)
com.bumptech.glide.manager.SupportRequestManagerFragment.onStop (SourceFile:60)

**Comment by sjudd** [comment]
I believe my change fixes this, but I wasn't able to reproduce it. 

If you wouldn't mind testing the latest snapshot (available on Sonatype) and verifying that you don't see this any more I'd appreciate it.

Thanks for the report.
