### ISSUE TITLE
Glide version conflicts

### ISSUE THREAD

**Issue by reytum** [bumptech/glide#3221]
A library I use in my application uses Glide version 4.7.1 . I am using Glide version 3.8.0 in my application. The thing is when I import the library using implementation in my application then the app builds correctly but crashes when loading the image.

My version of glide is replaced by the version the library uses.
Is it possible to use two versions independently so that
the library uses its own version 4.7.1 without overriding my version of 3.8.0?

**Comment by Sunilkumarr** [comment]
+1
