### ISSUE TITLE
How to use glide-4 to load installed apps icons in recyclerview?

### ISSUE THREAD

**Issue by Mateeen** [bumptech/glide#3230]
i am trying to load apps icons using glide 4 but other [answers](https://groups.google.com/forum/#!topic/glidelibrary/LRMHdhLNRfc) are not working on glide 4 please help

**Comment by sjudd** [comment]
You can construct a Uri that points to another application's icon. For an example, see one of Glide's emulator tests: https://github.com/bumptech/glide/blob/b7c2b1360c777794c50351a10c30c08a3390b753/instrumentation/src/androidTest/java/com/bumptech/glide/NonBitmapDrawableResourcesTest.java#L378
