### ISSUE TITLE
The same URL about gif Just the fisrt can play

### ISSUE THREAD

**Issue by MrsLEO** [bumptech/glide#3233]
Hello，To solve the cpu consume over when i use glide load gif。i use glide combine with FrameSequenceDrawable。But when use in recycleview。i find the same url，just one can play。other play the first frame。how i can solve the problem？
My glide version is 4.7.1

**Comment by sjudd** [comment]
This might be an issue with FrameSequenceDrawable? I've definitely seen integrations with framesequence that work fine though.

There's not really enough information here to be actionable. Consider attaching a sample app that reproduces the issue or filing an issue for framesequence.
