### ISSUE TITLE
Share image from Glide cache

### ISSUE THREAD

**Issue by RadoVidjenGost** [bumptech/glide#3238]
Glide library version: `implementation 'com.github.bumptech.glide:glide:4.7.1`

My question is how can i get the Uri for image from Glide cache for sharing it through Android Intent.ACTION_SEND? This is my piece of code: 

**PagerAdapter.java**
```
GlideApp.with(mContext)
                .asDrawable()
                .load(imageUrl)
                .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                .transition(DrawableTransitionOptions.withCrossFade())
                .into(currentImage);
```
I can get the cache directory through `Glide.getPhotoCacheDir(mContext);` but file names are just some random numbers, so i cant figure it out how to get current image that is being shown, get its path, then Uri, and finally share it. I have also tried this piece of code:

**PagerAdapter.java**

```
GlideApp.with(mContext)
                .asBitmap()
                .load(imageUrl)
                .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                .diskCacheStrategy(DiskCacheStrategy.DATA)
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(@NonNull final Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                        mBitmap = resource;
                        currentImage.setImageBitmap(resource);
                    }
                });
```
And this works, i get the bitmap, and using this method:
```
public Uri getImageUri(Bitmap inImage) {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        inImage.compress(Bitmap.CompressFormat.JPEG, 70, bytes);
        String path = MediaStore.Images.Media.insertImage(mContext.getContentResolver(), inImage, UUID.randomUUID().toString() + ".png", "drawing");
        return Uri.parse(path);
    }
```
I'm able to get the Uri and share the image. However, for some reason one or more images in the adapter simply doesn`t get shown, but some other does. And i cant figure it out why. Some help would be nice :) 

_P.S. I`m sorry if this is not the right place for asking this kind of question, but i have been struggling with it for while..._

**Comment by abedsh** [comment]
I will also need to access the stored cache myself, but couldn't find a way to do it

**Comment by sjudd** [comment]
You can use `asFile()` which will produce a File pointing to Glide's cache if the image is present. This works reasonably well for remote images, but may not work so well for local images.
