### ISSUE TITLE
.centerCrop()

### ISSUE THREAD

**Issue by 27mod** [bumptech/glide#3241]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

![untitled](https://user-images.githubusercontent.com/33231366/43546988-a3ba7254-95e2-11e8-922f-72fe360cce4d.png)

**Comment by jocmp** [comment]
@27mod If you're using the `Glide` singleton, you'll have to call `apply()` to use center crop:

```java
Glide.with(this) // this is MainActivity
        .load(R.drawable.ic_background)
        .apply(RequestOptions.circleCropTransform())
        .into(background)
```

According to the documentation, to use centerCrop against a singleton builder, you'll need to use the generated API. There are more details here: [Glide v4: Options](https://bumptech.github.io/glide/doc/options.html). Hope this helps!

**Comment by 27mod** [comment]
@jocmp 
Thanks , but it show like circle ,can 
![untitled2](https://user-images.githubusercontent.com/33231366/43614973-460c9074-96be-11e8-8c60-ea00a62430ba.png)

**Comment by 27mod** [comment]
@jocmp thanks a lot i fix it ,many thanks man.
