### ISSUE TITLE
How to remove previous cache when url is updated/changed?

### ISSUE THREAD

**Issue by shahzi8285** [bumptech/glide#3242]
Hi,There I am currently working on an user based apps like friends app
it simply shows the list of users with thier avatar and caching images using this wonderful library
but problem occurs when
the url of a particular user's avatar changes and there are two different avatar images save in cache directory of app.
there is no need of more than one avatar pic or single user.
in long run it will full with these garbage caches of different user's pervious avatars
the need is to only cache single avatar of user
when url changes remove previous one cache and cache updated avatar 

**Glide Version**: 4.7.1

![screen3](https://user-images.githubusercontent.com/25281439/43552233-69065a36-9607-11e8-9be4-d37b94fc5ac6.png)
there are two different cache files of a single user
there is no need of previous one!

Please Guide this is serious hurdle..

**Comment by shahzi8285** [comment]
Is there no solution or should I migrate to another library?
please help it is urgent

**Comment by sjudd** [comment]
It's not currently possible to delete individual images from the DiskCache. You can write your own DiskCache implementation that is more aggressive about clearing out entries, but you typically won't have enough information to do so for specific urls, you'd have to use recent access or other timing. 

Images will eventually be evicted by Glide's default disk cache when the cache fills up to whatever size you specify. See http://bumptech.github.io/glide/doc/caching.html#disk-cache

**Comment by shahzi8285** [comment]
then I have to move to other library.Because there is so much junk cached images.
Which are size of total 4-6mb..
anyway nice library.but worthless needs very much improvments

**Comment by shahzi8285** [comment]
Thank you for replying

Now there are some problems in mystical code
That it does not prevent some of the sol please help asap


I will send you code on morning
