### ISSUE TITLE
glide如何加载失败的时候切换图片url？

### ISSUE THREAD

**Issue by maxhsh** [bumptech/glide#3253]
Glide.with(mContext).load(URL1).asBitmap().into(new Target<Bitmap>() { 
                @Override  
                public void onLoadFailed(Exception e, Drawable errorDrawable) {  
  
                }  
   
                @Override  
                public void onResourceReady(Bitmap bitmap, GlideAnimation<? super Bitmap> glideAnimation) {  
 
                }
            }); 

我在onLoadFailed里再次加载新的url会提示：   java.lang.IllegalStateException: You can't start or clear loads in RequestListener or Target callbacks. If you're trying to start a fallback request when a load fails, use RequestBuilder#error(RequestBuilder). Otherwise consider posting your into() or clear() calls to the main thread using a Handler instead.   请问怎么处理？

**Comment by KwonDoby** [comment]
Only English.

**Comment by hfyqsy** [comment]
![image](https://user-images.githubusercontent.com/23046221/44762513-ebc8d480-ab79-11e8-8c3d-267fa4369a66.png)
