### ISSUE TITLE
ModelLoader instead of using in V4 Glide.

### ISSUE THREAD

**Issue by javieritis** [bumptech/glide#3257]
https://github.com/waynell/VideoListPlayer

I need use this library, and i found a problem. 

Info:
In my app, use the Glide version 4.7.1.
    implementation 'com.github.bumptech.glide:glide:4.7.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'

and the library for implement use Glide 3.7.1, and use the next code:
![screen shot 2018-08-10 at 08 48 15](https://user-images.githubusercontent.com/11956969/43943253-2a694e58-9c7b-11e8-8783-5a20b8a45492.png)
And complete code class VideoListGlideModule:

![videolistglidemodule java](https://user-images.githubusercontent.com/11956969/43943269-3def41f8-9c7b-11e8-9a57-e4eb01063e97.png)

And the "**using**" in V4 Glide is deleted. I readed the next documentation:
https://bumptech.github.io/glide/doc/migrating.html#using
and how to create custom ModelLoader, and is more difficult and don't understand.
http://bumptech.github.io/glide/tut/custom-modelloader.html

Do you have an example or can you help me?

thanks!

**Comment by deepsheth-agile** [comment]
What have you used at the place of using() in glide v4?  because I do not find any solution for that.
If you did anything please send me it's very helpful for me or any useful library for autoplay video which you implemented.
