### ISSUE TITLE
The local video file is over 2GB and the code throw the exception. 

### ISSUE THREAD

**Issue by kbboss** [bumptech/glide#3258]
**Glide Version**:4.4.0

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
RequestOptions resultOption=new RequestOptions()
. diskCacheStrategy(DiskCacheStrategy.SOURCE)
                            .transforms(new CenterCrop(),new CacheBitmapTrans(cnt,cacheKey,true))
                            .placeholder(bitmap != null ? new BitmapDrawable(cnt.getResources(), bitmap) : place);
   
                requestBuilder.apply(resultOption).load(file).transition(BitmapTransitionOptions.withCrossFade()).into(ivPhoto);
```

**Stack trace / LogCat**:
```ruby
 IOException("File too large to map into memory")
```
I found the glide code that throws exception. So How to load videothumnail that over Integer.MAX_VALUE file?

```
ByteBufferUtil.java

public static ByteBuffer fromFile(File file) throws IOException {
    RandomAccessFile raf = null;
    FileChannel channel = null;
    try {
      long fileLength = file.length();
      // See #2240.
      if (fileLength > Integer.MAX_VALUE) {
        throw new IOException("File too large to map into memory");
      }
      // See b/67710449.
      if (fileLength == 0) {
        throw new IOException("File unsuitable for memory mapping");
      }

      raf = new RandomAccessFile(file, "r");
      channel = raf.getChannel();
      return channel.map(FileChannel.MapMode.READ_ONLY, 0, fileLength).load();
    } finally {
      if (channel != null) {
        try {
          channel.close();
        } catch (IOException e) {
          // Ignored.
        }
      }
      if (raf != null) {
        try {
          raf.close();
        } catch (IOException e) {
          // Ignored.
        }
      }
    }
  }
```

**Comment by kbboss** [comment]
@sjudd  hi bro, I got the same question. link #2252. 
This link have not been fixed.  

As what I say , ByteBufferUtil.java is source file in Glide.  

The code lines: 32 throws the excepiton, when the lenth of the video file is over Interget.MAX_VALUE.

**Comment by sjudd** [comment]
There's an explicit  check in the most recent version: https://github.com/bumptech/glide/blob/a50a7512ec7a99d4b3d8c1a2df9d8af48aa543cc/library/src/main/java/com/bumptech/glide/util/ByteBufferUtil.java#L35.

**Comment by kbboss** [comment]
@sjudd  yeah, Your new code will throw the exception when fileLength > Integer.MAX_VALUE

**Comment by sjudd** [comment]
Yes, but the checked exception is fine. That particular request path will fail, and Glide will try the next one. For a local video file, Glide will subsequently try loading from a ParcelFileDescriptor, which won't throw (or shouldn't).

The original problem was that the framework method would throw an unchecked exception, which would cause Glide to fail the entire request, not just the load path for ByteBuffers. Throwing the checked exception just fails the one load path, but allows the others to run.
