### ISSUE TITLE
Error:Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'. Could not determine artifacts for com.github.bumptech.glide:glide:4.7.1: Skipped due to earlier error

### ISSUE THREAD

**Issue by WarriorYu** [bumptech/glide#3259]
Error:Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.github.bumptech.glide:glide:4.7.1: Skipped due to earlier error

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues, there's not enough information to help you.

**Comment by RunningShadow-007** [comment]
I suffered the same error
