### ISSUE TITLE
Unable to Build AppGlideModule For compileSdkVersion 28: GeneratedAppGlideModule with: []

### ISSUE THREAD

**Issue by AdamSHurwitz** [bumptech/glide#3260]
**Glide Version**: 4.7.1

**Integration libraries**: None.

**Device/Android Version**: N/A, can't build project in Android Studio.

**Issue details / Repro steps / Use case background**: 

I am attempting to implement the [AppGlideModule](https://bumptech.github.io/glide/doc/generatedapi.html) for Glide.

### Error

`GeneratedAppGlideModule with: []`
[Stackoverflow post.](https://stackoverflow.com/questions/51791067/unable-to-build-appglidemodule-for-compilesdkversion-28-generatedappglidemodule)

### Steps Taken To Resolve

- Cleaned build
- Rebuilt app
- Invalide Caches / Restart for Android Studio
- Exclude com.android.support from Glide since I'm using sdk version 28.
- Using  `annotationProcessor` instead of `kapt` which compiles and runs the app, however `GlideApp` still cannot be accessed. The AppGlideModule is in the same package where I am attempting to use the GlideApp object.

### Configuration
Language: Kotlin 1.2.51
compileSdkVersion: 28

### Implementation

_build.gradle(Project: carpecoin)_

```
repositories {
    google()
    jcenter()
    mavenCentral()
    maven { url 'https://maven.google.com' }
}

  dependencies {
    classpath 'com.android.tools.build:gradle:3.3.0-alpha05'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath 'com.google.gms:google-services:4.0.2'
    classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:1.0.0-alpha04"
}
```

_build.gradle(Module: app)_

```
implementation 'com.github.bumptech.glide:glide:4.7.1'
//I've tried with and without this line for annotations implementation.
implementation 'com.github.bumptech.glide:annotations:4.7.1'
kapt 'com.github.bumptech.glide:compiler:4.7.1'
```

_MyAppGlideModule_

```
import com.bumptech.glide.annotation.GlideModule
import com.bumptech.glide.module.AppGlideModule

@GlideModule
class MyAppGlideModule : AppGlideModule()
```

### All External Libraries Used

```
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
implementation 'androidx.appcompat:appcompat:1.0.0-rc01'
implementation 'androidx.legacy:legacy-support-v4:1.0.0-rc01'
implementation 'androidx.constraintlayout:constraintlayout:1.1.2'
implementation 'androidx.cardview:cardview:1.0.0-rc01'
implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"
kapt "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"
implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
implementation "androidx.lifecycle:lifecycle-reactivestreams:$lifecycle_version" // use -ktx for Kotlin
implementation "androidx.paging:paging-runtime:$paging_version"
implementation "androidx.paging:paging-rxjava2:$paging_version"

implementation 'com.firebase:firebase-client-android:2.5.2'
implementation 'com.google.firebase:firebase-core:16.0.1'
implementation 'com.google.firebase:firebase-firestore:17.0.4'
implementation 'com.firebaseui:firebase-ui-firestore:4.1.0'
implementation 'com.jjoe64:graphview:4.2.2'
implementation 'io.reactivex.rxjava2:rxjava:2.2.0'
implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
implementation "android.arch.navigation:navigation-fragment:$nav_version" // use -ktx for Kotlin
implementation "android.arch.navigation:navigation-ui:$nav_version" // use -ktx fo
implementation 'com.github.bumptech.glide:glide:4.7.1'
kapt 'com.github.bumptech.glide:compiler:4.7.1'

testImplementation 'junit:junit:4.12'
androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
testImplementation "androidx.arch.core:core-testing:$lifecycle_version"
androidTestImplementation "android.arch.navigation:navigation-testing:$nav_version"
```

**Comment by sjudd** [comment]
Can you paste the complete error? `GeneratedAppGlideModule with: []` isn't an error message.

**Comment by AdamSHurwitz** [comment]
@sjudd - Unfortunately, that is all the information that is provided for the failed Build. The event log does not provide further insight either. 
![screen shot 2018-08-11 at 12 29 43 pm](https://user-images.githubusercontent.com/3938076/43995419-51d1921a-9d62-11e8-82cf-574032ed395e.png)

![screen shot 2018-08-11 at 12 30 52 pm](https://user-images.githubusercontent.com/3938076/43995430-6e9afc24-9d62-11e8-85ea-066e8a9074b2.png)

**Comment by geekxingyun** [comment]
maybe your other library use  an earlier version of Glide in your other libraries，so you need not added the library again. 
i think it will works well, one you comment out the two line code as below:
`
//    implementation 'com.github.bumptech.glide:glide:4.7.1'

//    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
`

**Comment by AdamSHurwitz** [comment]
Thank you for the suggestion @geekxingyun! Unfortunately, I need to explicitly compile the Glide libraries as I tried commenting them out and they are not included in another library.

@sjudd - This is labeled as a **question** whereas it seems to be more appropriately fall under the **bug** categorization because the Glide library is not performing as expected with the documented implementation.

**Comment by geekxingyun** [comment]
hi all , i have resolved the issue.
maybe it is an IDE Compile issue,after i update my Android studio to 3.1.4，it happen to the issue.
"Cannot resolve symbol GlideApp"

but you can do it as below to fix the issue:

1. comment out your library
`
// implementation 'com.github.bumptech.glide:glide:4.7.1'

// annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
`

2. Click Sync Now

3. remove the comment like this as below:

`

implementation 'com.github.bumptech.glide:glide:4.7.1'

annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
`

4.Sync Now again

then it will works well.

**Comment by LazyDemo** [comment]
I also encountered this problem.

the config:
![image](https://user-images.githubusercontent.com/13451082/44143659-19b8afaa-a0b7-11e8-9eaf-11c6ee834310.png)

the error:
![image](https://user-images.githubusercontent.com/13451082/44143702-41eafad2-a0b7-11e8-85b6-491e759eb456.png)

**Comment by LazyDemo** [comment]
It works when I build the project,but when I want to run on my phone, I just get the error.

**Comment by AdamSHurwitz** [comment]
I have resolved the issue. Please upvote on [StackOverflow](https://stackoverflow.com/questions/51791067/glide-unable-to-build-appglidemodule-compilesdkversion-28/53218714#53218714) to help others discover that find it useful.

# Solution
The **GlideApp** is successfully being generated after upgrading Glide's library to **4.8.0**. **kapt** is being used since the app is built using Kotlin.

*build.gradle* (Module: app)

    implementation 'com.github.bumptech.glide:glide:4.8.0'
    kapt 'com.github.bumptech.glide:compiler:4.8.0'
