### ISSUE TITLE
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.

### ISSUE THREAD

**Issue by RunningShadow-007** [bumptech/glide#3267]
When I add the Glide 4.7.1 dependency to  the build.gradle,

It showed the followed  error
<img width="1633" alt="wx20180814-141855 2x" src="https://user-images.githubusercontent.com/10829703/44074877-13d55f42-9fcd-11e8-9c85-49e3cb56835f.png">
AndroidStudio 3.2 beta4

`apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'androidx.navigation.safeargs'

apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.feiyang.wanandroid"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    dataBinding {
        enabled = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildToolsVersion '28.0.2'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$rootProject.ext.kotlin_version"
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
    implementation 'androidx.appcompat:appcompat:1.0.0-rc01'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.2.0'

    implementation "com.squareup.retrofit2:retrofit:$rootProject.ext.retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$rootProject.ext.retrofit_version"
    implementation "com.squareup.retrofit2:retrofit-adapters:$rootProject.ext.retrofit_version"

    //architecture
    // lifecycle
    implementation "androidx.lifecycle:lifecycle-extensions:$rootProject.ext.lifecycle_version"
    kapt "androidx.lifecycle:lifecycle-compiler:$rootProject.ext.lifecycle_version" // use kapt for Kotlin
    implementation "androidx.lifecycle:lifecycle-reactivestreams-ktx:$rootProject.ext.lifecycle_version"
    //room
    implementation "androidx.room:room-runtime:$rootProject.ext.room_version"
    kapt "androidx.room:room-compiler:$rootProject.ext.room_version"
    //nav
    implementation "android.arch.navigation:navigation-fragment-ktx:$rootProject.ext.nav_version"
    implementation "android.arch.navigation:navigation-ui-ktx:$rootProject.ext.nav_version"

    //glide
    implementation 'com.github.bumptech.glide:glide:4.7.1'
    kapt 'com.github.bumptech.glide:compiler:4.7.1'

    testImplementation "androidx.arch.core:core-testing:$rootProject.ext.lifecycle_version"

}
`

**Comment by vladp** [comment]
@RunningShadow-007     do you have the repositories setup in your gradle?
Eg per Glide's readme:
```

repositories {
  mavenCentral()
  google()
}
```

**Comment by amirbhz86** [comment]
I had this problem 
I checked my internet status
And I wrote this code in android/app/build.gradle 
 ```
repositories {
         maven { url "https://maven.google.com" }
  }
```
And then I deleted it
My problem was solved very incredibly
