### ISSUE TITLE
Tag same image with different URLs

### ISSUE THREAD

**Issue by AntoinePurnelle** [bumptech/glide#3268]
Hi

I'm having a bit of a headache with Glide because of our way to build our URLs.
When we request images, the client token will be passed as a query param in the URL (not ideal I know but that's how our server work). Which means that Glide will not recognise two URLs for the same image but with different tokens as the same image. Therefore, it will re-download what's already in cache. Even worse, when the app goes offline (which is an important part of the app), there's no taken and the URL is then again changed and Glide won't be able to load from cache.

Examples:
First URL = {hostname}/images/image1?token=1234

A few minutes later, we get a new token and the URL becomes
{hostname}/images/image1?token=5678
Glide will redownload and re-cache the image1

When the user goes offline, the URL becomes
{hostname}/images/image1?token=0000, Glide doesn't find it in the cache and can't download it of course.

My question is this:
Is it possible to tag an image in Glide to tell it that even if the URL changes, it's the same one? I've read the signature documentation but I don't think it could help me (but I might be wrong).

We should of course change our way to manage tokens but that's not something the backend and mobile teams have time to do right now.

Thanks for the help! :-D

**Comment by vladp** [comment]
I have not tried this myself. But Glide lets us to override how the signature is created. And then it compares signatures to decide if something is in the cache or not.
So I am wondering (again just a hypothesis),if you could override the isEqual method in the signature
As shown in Glide's example
http://bumptech.github.io/glide/doc/caching.html#loading-only-from-cache

```

public class IntegerVersionSignature implements Key {
    private int currentVersion;

    public IntegerVersionSignature(int currentVersion) {
         this.currentVersion = currentVersion;
    }
   
    @Override
    public boolean equals(Object o) {
        if (o instanceof IntegerVersionSignature) {
            IntegerVersionSignature other = (IntegerVersionSignature) o;
            return currentVersion = other.currentVersion;
        }
        return false;
    }
 
    @Override
    public int hashCode() {
        return currentVersion;
    }

    @Override
    public void updateDiskCacheKey(MessageDigest md) {
        messageDigest.update(ByteBuffer.allocate(Integer.SIZE).putInt(signature).array());
    }
}

```

**Comment by vladp** [comment]
@AntoinePurnelle  couldn't you override  the 'equals' method in Glides signature overload sematic ?
http://bumptech.github.io/glide/doc/caching.html#loading-only-from-cache

**Comment by sjudd** [comment]
Overriding equals in signature isn't sufficient because it doesn't also override equality in the model (the String url).

You can use a custom ModelLoader to do this:

1. Define a POJO wrapper for your urls (UrlWrapper or whatever name you'd like)
2. Implement equals/hashcode in your POJO wrapper that ignores the token
3. Implement a custom `ModelLoader<UrlWrapper, InputStream>` that converts your `UrlWrapper` into a `GlideUrl` and delegates to the already registered `ModelLoader<GlideUrl, InputStream>`

There's some more information on custom `ModelLoaders` here: http://bumptech.github.io/glide/tut/custom-modelloader.html

**Comment by AntoinePurnelle** [comment]
Thanks guys! I'll try that

**Comment by DyncKathline** [comment]
Examples:
First URL = {hostname}/images/image1?token=1234
A few minutes later, we get a new token and the URL becomes
{hostname}/images/image1?token=5678
Glide will redownload and re-cache the image1

Is there a solution？
