### ISSUE TITLE
Issue while using HTTPS image url.

### ISSUE THREAD

**Issue by ashwin-lightrains** [bumptech/glide#327]
The request like Glide.with(this).load("https://'imageurl'").into(mBackground); is not working.

**Comment by sjudd** [comment]
Can you provide the url in question? What version of Glide are you using? What version of Android are you using? Are using either of Glide's integration libraries (OkHttp or Volley)?

Are any errors logged? See the [Debugging and Error Handling][1] wiki page for how to enable debug logging.

[1]: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by sjudd** [comment]
Let us know if we can help further.
