### ISSUE TITLE
USING method not found 

### ISSUE THREAD

**Issue by kalanidhidev** [bumptech/glide#3270]
**Glide Version**:  **4.7.1**

**Integration libraries**: **com.firebase.ui.storage.images.FirebaseImageLoader**

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 
`using` method not found , and getting error unable to resolve

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
        Glide.with(context /* context */).using(FirebaseImageLoader()).load(storageReference).into(holder.image)
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/migrating.html#using-modelloader-streammodelloader
