### ISSUE TITLE
please look here 

### ISSUE THREAD

**Issue by kongpengcheng** [bumptech/glide#3274]
Process: com.haier.uhome.uplus, PID: 21104
                                                                       java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.haier.uhome.uplus-et5Gv1VJyfMCJeL_TATrZA==/base.apk:classes26.dex)

**Comment by Crysis21** [comment]
check if you have MultiDex enabled. And learn how to open an issue!
