### ISSUE TITLE
Shared element transitions with memory cache

### ISSUE THREAD

**Issue by bradlol** [bumptech/glide#3280]
**Glide Version**: 4.7.1, 4.8.0, works fine on 4.6.1
**Integration libraries**: none

**Device/Android Version**: Xiaomi MI4 6.0.1, Xiaomi MI6 8.0.0

**Issue details / Repro steps / Use case background**: 
Basically shared element transitions don't work when image is loaded from memory cache. It works fine when I use skipMemoryCache(true).
My setup: I have MainActivity with RecyclerView, then onClick goes to DetailsActivity with ViewPager which contains fragments with RecyclerView in which first item is a thumbnail that transition is going to. I use supportPostponeEnterTransition() in DetailsActivity, then from fragments I pass listener to RecyclerViewAdapter so I can call startPostponedEnterTransition.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(mContext).load(thumb).override(520,303).placeholder(R.drawable.placeholder).fitCenter().dontAnimate().listener(new RequestListener<Drawable>() {
                @Override
                public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                    listener.onThumbLoaded();
                    return false;
                }
                @Override
                public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                    listener.onThumbLoaded();
                    return false;
                }
            }).into(holder.imageView);
```
```java
@Override
    public void onThumbLoaded() {
        if(getActivity()!=null) {
            ActivityCompat.startPostponedEnterTransition(getActivity());
        }
    }
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="vertical" android:layout_width="match_parent"
    android:clipChildren="true"
    android:clipToPadding="false"
    android:layout_height="wrap_content">
<ImageView
        android:id="@+id/icon"
        android:src="@drawable/placeholder"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="fitXY"
        android:adjustViewBounds="true"
        android:contentDescription="@null" />`
<TextView
        android:id="@+id/textView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="@dimen/grid_item_font"
        android:textStyle="bold"
        fontPath="fonts/OpenSans-Bold.ttf"
        android:textColor="#333333"
        android:layout_marginLeft="13dp"
        android:layout_marginRight="13dp"
        android:layout_marginTop="7dp"
        android:layout_marginBottom="6dp"
        android:gravity="center_vertical"
        tools:ignore="MissingPrefix" />
    <TextView
        android:id="@+id/description"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="14sp"
        android:layout_marginLeft="13dp"
        android:layout_marginRight="13dp"
        android:gravity="center_vertical"
        fontPath="fonts/OpenSans-Light.ttf"
        android:textColor="#333333"
        tools:ignore="MissingPrefix" />
</LinearLayout>
```

**Comment by bradlol** [comment]
I was trying to migrate my project to AndroidX, but version 4.6.1 doesn't work with it so I checked version 4.9.0 and I still have the same error with shared elements transition.

**Comment by sjudd** [comment]
Are you able to debug this further? Is your listener called? Where does it break?

**Comment by bradlol** [comment]
I'm not sure how to debug it further, it's kinda weird bug. Listener is called. I noticed that bug from dataSource parameter in listener, images loaded from memory cache just somehow don't animate. No idea why data source is influencing animations and what changed in that matter after version 4.6.1.

**Comment by sjudd** [comment]
If it's loaded from memory that means the image isn't loaded asynchronously. Maybe you're doing something immediately after you start the Glide load that won't get the chance to finish if the load completes immediately? 

If the Glide load is completing and the image is set correctly on the view, it's unlikely to have much to do with Glide specifically.

**Comment by bradlol** [comment]
Indeed that seems to be the case, I added 1ms delay and it works. Still I don't get what's wrong here, I load it at the end of item binding, there's no code after that. So I have no idea what could be influencing that element transition. And also what changed after version 4.6.1?
