### ISSUE TITLE
请问一下网络视频图片的加载机制

### ISSUE THREAD

**Issue by MrWangChong** [bumptech/glide#3281]
你好，我想请问一下，假如我使用Glide.with(this).load(videoUrl).into(imageView)，这样是加载视频的缩略图还是会把整个视频下载下来呢？
Hello, I want to ask. If I use Glide.with(this).load(videoUrl).into(imageView)，it's only load the thumbnail or it's will download all video file？

**Comment by hfyqsy** [comment]
加载视频第一帧

**Comment by MrWangChong** [comment]
谢谢，Thank you，Very nice！

**Comment by MIkeeJY** [comment]
加载图片第一帧为什么默认会缓存视频全部呢？
