### ISSUE TITLE
 #2859 have the same bug

### ISSUE THREAD

**Issue by JerryDu0306** [bumptech/glide#3282]
@sjudd  I have the same problem（#2859），The glide version  which using is V4.5.0. please have a check. below is the bug info.

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.util.Log.printlns(Log.java:441)
	at android.util.Log.w(Log.java:219)
	at com.bumptech.glide.request.SingleRequest.obtain(SingleRequest.java)
	                                            begin(SingleRequest.java)
	                                            releaseResource(SingleRequest.java)
	                                            loadDrawable(SingleRequest.java)
	                                            onSizeReady(SingleRequest.java)
	                                            maybeApplySizeMultiplier(SingleRequest.java)
	                                            onResourceReady(SingleRequest.java)
	                                            onLoadFailed(SingleRequest.java)
	                                            isEquivalentTo(SingleRequest.java)
	                                            logV(SingleRequest.java)
	at com.bumptech.glide.request.SingleRequest.obtain(SingleRequest.java)
	                                            begin(SingleRequest.java)
	                                            releaseResource(SingleRequest.java)
	                                            loadDrawable(SingleRequest.java)
	                                            onSizeReady(SingleRequest.java)
	                                            maybeApplySizeMultiplier(SingleRequest.java)
	                                            onResourceReady(SingleRequest.java)
	                                            onLoadFailed(SingleRequest.java)
	                                            isEquivalentTo(SingleRequest.java)
	                                            logV(SingleRequest.java)
	at com.bumptech.glide.load.engine.EngineJob.handleExceptionOnMainThread(EngineJob.java)
	at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by JerryDu0306** [comment]
this problem occured many times  in my app, why it marked as statle?

**Comment by JerryDu0306** [comment]
![error](https://user-images.githubusercontent.com/13518848/45021224-943bd480-b063-11e8-806e-820f8e124f6f.png)
I don't know if you can see it.

**Comment by sjudd** [comment]
Duplicate of #2859. Let me know if you're able to reproduce it on 4.8.0. Consider adding a test case or a sample app.

**Comment by JerryDu0306** [comment]
I hava reproduce it on 4.8.0. need to test for some time
