### ISSUE TITLE
ColorTransformation - avoid android resource reusage

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#3284]
**Glide Version**: 4.7.1

**Integration libraries**: -

**Device/Android Version**: S9 with android 8

**Issue details / Repro steps / Use case background**: 

I've a custom transformation that tints a `Bitmap`. The problem is, this transformation is somewhere internally reusing the resource drawable without mutating it, so if I display a resource multiple times on the screen and only want to tint one of them, this state is shared across all bitmaps.

My transformation class looks like following:

	
	
	public abstract class BaseBitmapTransformation extends BitmapTransformation {
		public BaseBitmapTransformation() {
			super();
		}

		protected Bitmap getBitmapFromPool(BitmapPool pool, Bitmap source, int w, int h) {
			Bitmap.Config config = source.getConfig() != null ? source.getConfig() : Bitmap.Config.ARGB_8888;
			Bitmap bitmap = pool.get(w, h, config);
			if (bitmap == null) {
				bitmap = Bitmap.createBitmap(w, h, config);
			}
			return bitmap;
		}
	}
	
	public class ColorTransformation extends BaseBitmapTransformation {

		private static final String ID = "com.my.app.images.glide.transformations.ColorTransformation";
		private static final byte[] ID_BYTES;

		static {
			byte[] ID_BYTES1;
			try {
				ID_BYTES1 = ID.getBytes(STRING_CHARSET_NAME);
			} catch (UnsupportedEncodingException e) {
				ID_BYTES1 = ID.getBytes();
				e.printStackTrace();
			}
			ID_BYTES = ID_BYTES1;
		}

		private final int mColor;
		private final PorterDuff.Mode mMode;

		public ColorTransformation(int color, PorterDuff.Mode mode) {
			super();
			mColor = color;
			mMode = mode;
		}

		@Override
		protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
			return tint(pool, toTransform);
		}

		private Bitmap tint(BitmapPool pool, Bitmap source) {
			if (source == null) return null;

			int width = source.getWidth();
			int height = source.getHeight();

			Bitmap bitmap = getBitmapFromPool(pool, source, width, height);

			Canvas canvas = new Canvas(bitmap);
			Paint paint = new Paint();
			paint.setAntiAlias(true);
			paint.setColorFilter(new PorterDuffColorFilter(mColor, mMode));
			canvas.drawBitmap(source, 0, 0, paint);

			return bitmap;
		}

		@Override
		public boolean equals(Object o) {
			return o instanceof ColorTransformation;
		}

		@Override
		public int hashCode() {
			return ID.hashCode();
		}

		@Override
		public void updateDiskCacheKey(@NonNull MessageDigest messageDigest) {
			messageDigest.update(ID_BYTES);
			messageDigest.update(ByteBuffer.allocate(Integer.SIZE / 8).putInt(mColor).array());
			messageDigest.update(ByteBuffer.allocate(Integer.SIZE / 8).putInt(mMode.ordinal()).array());
		}
	}

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
var ro = RequestOptions()
	.fitCenter()
    .transform(colorTransformation)

Glide.with(context)
    .asBitmap()
    .apply(ro.placeholder(R.drawable.loading))
    .load(res)
    .into(iv)
	.waitForLayout()
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Your Transformation takes a color and a porter duff mode, but equals/hashcode do not include these values. Include the color and porter duff mode in equals/hashcode.

**Comment by MFlisar** [comment]
I somehow thought the key is enough, thanks

**Comment by MFlisar** [comment]
I added following `equals`and `hash` functions:

    @Override
    public boolean equals(Object o) {
        if (o == this) return true;
        if (!(o instanceof ColorTransformation)) {
            return false;
        }
        ColorTransformation other = (ColorTransformation) o;
        return mColor == other.mColor &&
                mMode.equals(other.mMode);
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + ID.hashCode();
        result = 31 * result + ((Integer)mColor).hashCode();
        result = 31 * result + mMode.hashCode();
        return result;
    }

The problem is solved now, but I have another one. I allow to change the apps theme in my app, so the image color changes depending on the apps theme (dark or light). Is see following behaviour:

* clean app start => icons are always colored correctly
* change theme, go to view with icons, load them => icons are colored always in the color they have been displayed the first time in the apps lifetime

Shouldn't this work now? I checked that the `ColorTransformation` is created with different colors, but it seems like the memory cache is not repsecting this, disc cache is working though (that's why after killing the app the images are colored correctly once)

**Comment by sjudd** [comment]
Just including equals/hashcode should be enough for the memory cache. Otherwise I'd suspect an application error.

**Comment by MFlisar** [comment]
I only have this issue if I use android drawable resources via identifier, not with other drawables... All other images respect the theme change... Currently I've no idea where to look here, can probably solve it by adding a custom key with the theme to the request...

**Comment by sjudd** [comment]
You can check the cache key here: https://github.com/bumptech/glide/blob/ebb0e45d42709338ffc8de0d58e48c992af2d372/library/src/main/java/com/bumptech/glide/load/engine/Engine.java#L173.

If you enable those log tags it will print every request and the elements that make up the cache key. That might help you debug why the cache key isn't changing even though you're changing the color.

**Comment by MFlisar** [comment]
Thanks, I could finally solve this, was some stupid mistake on my side because of code refactoring...

Your help with using correct `hashCode` and `equals` functions was solving the issue
