### ISSUE TITLE
Glide4.8 conflict with androidx ?

### ISSUE THREAD

**Issue by 1-riverfish** [bumptech/glide#3286]
**Glide Version**:
4.80

**Integration libraries**:
nothing 

**Device/Android Version**:
API 27

**Gradle File**:
apply plugin: 'com.android.application'

allprojects {
    repositories {
        google()
        jcenter()
        maven{
            url "https://maven.google.com"
        }
    }
}

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.seuchild.smallseedlings"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.constraintlayout:constraintlayout:1.1.0'
    implementation 'androidx.appcompat:appcompat:1.0.0-rc01'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha1'
    implementation "com.google.android.material:material:1.0.0-rc01"
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'androidx.annotation:annotation:1.0.0-rc01'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
}

**App**:
Nothing,just dependencies

**Error Message:**
Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
Message{kind=ERROR, text=Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by 1-riverfish** [comment]
And i add this to the gradle.properties file:
android.useAndroidX=true
android.enableJetifier=true

**Comment by Angels-group** [comment]
Same problem

**Comment by maxveres** [comment]
Same problem!

**Comment by bignadad** [comment]
same issue.

**Comment by sezn** [comment]
Same, it would be good to support androidx

**Comment by amspayam** [comment]
same issue

**Comment by djohannot** [comment]
Stale bot don’t do it! We want a fix!

**Comment by sjudd** [comment]
Duplicate of #3184

**Comment by ytuglt** [comment]
same problem ,how to fix

**Comment by 1-riverfish** [comment]
I change back to the old.

At 2018-10-24 09:37:38, "ytuglt" <notifications@github.com> wrote:


same problem ,how to fix

**Comment by siny-yao** [comment]
same problem ,how to fix

**Comment by Sarubbaru** [comment]
+1

**Comment by Hoss3inf** [comment]
same problem...
had to roll back to `android.support` after hours of trial and error

**Comment by davdeveloper** [comment]
+1
same issue after AndroidX Migration

**Comment by Viswasundhar** [comment]
Same issue

**Comment by Hoss3inf** [comment]
I solved this issue by adding the following repository in project level `build.gradle`:

```
allprojects {
    repositories {
        google()
        jcenter()
//this repo worked for me:
        maven {name 'glide-snapshot' 
            url 'http://oss.sonatype.org/content/repositories/snapshots'}
    }
}
```
the version of glide i am using is:
```
implementation "com.github.bumptech.glide:glide:4.9.0"
    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
```

**Comment by Viswasundhar** [comment]
> I solved this issue by adding the following repository in project level `build.gradle`:
> 
> ```
> allprojects {
>     repositories {
>         google()
>         jcenter()
> //this repo worked for me:
>         maven {name 'glide-snapshot' 
>             url 'http://oss.sonatype.org/content/repositories/snapshots'}
>     }
> }
> ```
> 
> the version of glide i am using is:
> 
> ```
> implementation "com.github.bumptech.glide:glide:4.9.0"
>     annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
> ```

Thank you, but still i'm facing

The given artifact contains a string literal with a package reference 'android.support.design.widget' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.
