### ISSUE TITLE
How to load error/placeholder  img ,in Glide 4.8 

### ISSUE THREAD

**Issue by sjindong** [bumptech/glide#3291]
befor Glide 4.8,   my code is  next,    
`        Glide.with(mContext)
 .load(bitmapBytes)
 .placeholder(R.mipmap.null_pic)
 .error(R.mipmap.error_pic)
 .centerCrop()
 .into(normalHolder.tv_img);`

but when i use Glide 4.8,   this code  is error 
`.placeholder(R.mipmap.null_pic).error(R.mipmap.error_pic)`

i can't find any resolvent  from  the release-note of Glide4.8  or the project code (  `path : 
 glide\samples\contacturi\src\main\java\com\bumptech\glide\samples\contacturi\MainActivity.java` )

i  need  a sample ,  Thanks

**Comment by jigarpatel17** [comment]
@sjindong Not much sure about your versions, but may be below can help you.

```
val requestOptions: RequestOptions by lazy {
        RequestOptions()
                .placeholder(R.drawable.thumbnail) 
                .transforms(CenterCrop())
    }
```
```
Glide.with(mContext)
                            .load(imageURL)
                            .apply(requestOptions)
                            .into(mImageView)
```

**Comment by jigarpatel17** [comment]
@sjindong May be below documents can help you in your above mentioned case and even further as well.

Reference document:
https://bumptech.github.io/glide/doc/options.html

Detail document for RequestOptions:
https://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/RequestOptions.html

@sjudd If I have understood correctly then this is not an issue of Glide, just updates of the way of implementation from new version of Glide, so better to close this thread.

**Comment by sjindong** [comment]
@jigarpatel17  ok ， thanks
