### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by goghtsui** [bumptech/glide#3295]
======logcat======
`I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.FragmentActivity>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/ActivityCompatApi23$RequestPermissionsRequestCodeValidator;
        
at com.bumptech.glide.manager.RequestManagerRetriever com.bumptech.glide.manager.RequestManagerRetriever.get() (RequestManagerRetriever.java:57)
        
at com.bumptech.glide.RequestManager com.bumptech.glide.Glide.with(android.content.Context) (Glide.java:656)`

======build.gradle======
`implementation 'com.android.support:appcompat-v7:25.3.1'

    implementation 'com.google.code.gson:gson:2.7'

    implementation 'com.android.support.constraint:constraint-layout:1.0.2'

    implementation 'com.android.support:support-v4:25.3.1'

    implementation 'com.android.support:design:25.3.1'

    implementation 'com.android.support:recyclerview-v7:25.3.1'

    implementation 'com.github.bumptech.glide:glide:3.7.0'`

**Comment by sjudd** [comment]
Sounds like #3080?
