### ISSUE TITLE
Using Glide in library and RequestLoader.load(CustomModelObj)

### ISSUE THREAD

**Issue by SwiftyWang** [bumptech/glide#3300]
**Glide Version**:4.7.1

**Integration libraries**:

**Device/Android Version**:Any

**Issue details / Repro steps / Use case background**: 
Currently I have a library module need using glide to load image. I want to use `RequestBuilder<TranscodeType> load(@Nullable Object model)` this Api to load a customer model. I have read the document and find ModelLoader can do it.
I extends LibraryGlideModule and write my own module. But I need to add a AppGlideModule in my library then I can use GlideApp.class it is not allowed mentioned in the document. 
I have found there is someone face the similar issue before:
https://github.com/bumptech/glide/issues/2827
https://github.com/bumptech/glide/issues/2962
Both seems no good way to solve it.
Anyone can help me about this?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(context).load(CustomModel)
```

**Update:**
I find GlideApp.with(context) actually calling Glide.with(Context). I tried move the AppGlideModule to App module. In library, I just use Glide.class not GlideApp then works fine. But I need force app developer to create a AppGlideModule in their Application If they haven't created AppGlideModule. Any better solution that no need do anything in App Module?

**Comment by SwiftyWang** [comment]
Anyone can help me for this...

**Comment by sjudd** [comment]
You'd need to get the developer to write an AppGlideModule. 

There are deprecated Manifest based modules that don't require the generated API, but have their own problems.

**Comment by SwiftyWang** [comment]
> You'd need to get the developer to write an AppGlideModule.
> 
> There are deprecated Manifest based modules that don't require the generated API, but have their own problems.

Yes, seems the quick fix only this way.
But seems it is not a good user experience for app developer. Because they add a class about glide and only for my library but seems there are no relationship from app developer eyes.
