### ISSUE TITLE
填充不同大小的imageView，图片大小混乱，导致图片模糊

### ISSUE THREAD

**Issue by hejiaun** [bumptech/glide#3301]
我在写一个聊天界面的时候，发现了这个问题。
界面有一个recyclerView，recyclerView的item时代表聊天记录。
其中item中有个人头像和群头像，群头像由多个个人头像组成，且群头像和个人头像大小一致。
当从网络获取图片填充至item，并上下滑动的时候，出现了图片模糊的问题，原本清晰的图片变模糊，原本模糊的图片变清晰等状况。

个人认为：是Glide复用缓存中的图片时，出现导致的。当第一次加载图片的时候，图片并未出现模糊的状况，当滚动recyclerView时，Glide将小的图片复用至大的imageView中，图片放大拉伸，导致图片变模糊。

**Comment by Likeyong** [comment]
想问一下你是怎么样解决这个问题的?

**Comment by Likeyong** [comment]
> 我在写一个聊天界面的时候，发现了这个问题。
> 界面有一个recyclerView，recyclerView的item时代表聊天记录。
> 其中item中有个人头像和群头像，群头像由多个个人头像组成，且群头像和个人头像大小一致。
> 当从网络获取图片填充至item，并上下滑动的时候，出现了图片模糊的问题，原本清晰的图片变模糊，原本模糊的图片变清晰等状况。
> 
> 个人认为：是Glide复用缓存中的图片时，出现导致的。当第一次加载图片的时候，图片并未出现模糊的状况，当滚动recyclerView时，Glide将小的图片复用至大的imageView中，图片放大拉伸，导致图片变模糊。

我也遇到了这个问题,使用recyclerview setSpanSizeLookup 这个功能时,出现了同样的问题,想问一下您是如何解决这个问题的?十分感谢

**Comment by JeckChou** [comment]
glide缓存的是你当时显示在view的图片，没有存不清晰的图片，比如你的图片 1000x1000，你的view 100x100，glide会把100x100的缓存，下次就不下载用那个图片，所以你第一次是清晰的，第二次也不会差，你这个问题应该不是缓存的问题

**Comment by hejiaun** [comment]
我之后在列表要加载图片的我都首选Picasso了，你可以试试
