### ISSUE TITLE
SimpleTarget deprecated

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [bumptech/glide#3304]
Since latest update of **Glide (4.8.0)** `SimpleTarget `has been deprecated so instead of it i use `Target `as mention in this issue #3294 , but doesn't work at all the `onResourceReady `method is not called . 

```
  Glide.with(getApplicationContext()).asBitmap()
                                .load(url)
                                .apply(options).into(new Target<Bitmap>() {
                            @Override
                            public void onLoadStarted(@Nullable Drawable placeholder) {

                            }

                            @Override
                            public void onLoadFailed(@Nullable Drawable errorDrawable) {

                            }

                            @Override
                            public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                                    new saveImage().execute(resource);
                            }

                            @Override
                            public void onLoadCleared(@Nullable Drawable placeholder) {
                            }

                            @Override
                            public void getSize(@NonNull SizeReadyCallback cb) {
                            }

                            @Override
                            public void removeCallback(@NonNull SizeReadyCallback cb) {

                            }

                            @Nullable
                            @Override
                            public Request getRequest() {
                                return null;
                            }

                            @Override
                            public void setRequest(@Nullable Request request) {

                            }

                            @Override
                            public void onStart() {

                            }

                            @Override
                            public void onStop() {

                            }

                            @Override
                            public void onDestroy() {

                            }
                        });
```

**Comment by sajjadyousefnia** [comment]
I have same issue, too

**Comment by Ken-Lim** [comment]
I am also having this issue.

**Comment by hbdeveloppeur** [comment]
Same issue :(

**Comment by sjudd** [comment]
A simpler alternative will be available in 4.9.0 from: https://github.com/sjudd/glide/commit/b3b2d7aa84a5beb8eddea39f2ec0e8ba35ceaa20

**Comment by androidmh** [comment]
Try changing Bitmap to Drawable.

**Comment by maherimcovery** [comment]
@sjudd When do you think `4.9.0` will be available?

**Comment by AndroidDeveloperLB** [comment]
What is supposed to be the replacement of SimpleTarget ? If there isn't, why deprecate it?

**Comment by jackz314** [comment]
> A simpler alternative will be available in 4.9.0 from: [sjudd@b3b2d7a](https://github.com/sjudd/glide/commit/b3b2d7aa84a5beb8eddea39f2ec0e8ba35ceaa20)

So what should we do until then? Just keep using SimpleTarget?

**Comment by AndroidDeveloperLB** [comment]
@jackz314 Probably.
I wonder what else is new on 4.9.0 . And if it's hard to migrate to it from 4.8.0

**Comment by preqel** [comment]
there is a viewTarget in glide 4.8 but it is complex

**Comment by cristan** [comment]
Please update the getting started docs: https://bumptech.github.io/glide/doc/getting-started.html Here, SimpleTarget is still used.

**Comment by chjan** [comment]
@sjudd, please respond properly to above questions. What is to be used instead of SimpleTarget? 4.9.0 i here, but the tutorial uses simpletarget. Please update the tutorial. Thanks!

**Comment by emailsubjekt** [comment]
I am having the same issue, can't find a replacement anywhere, no mention in the docs. Official docs still use the 3.9.0, someone f'd up real bad here by not releasing their work.

**Comment by sjudd** [comment]
@chjan - see the earlier comments, you want CustomTarget, or just don't use SimpleTarget and extend Target, that's also fine.

There's some detail in the deprecation message about which other targets to use - http://bumptech.github.io/glide/javadocs/490/com/bumptech/glide/request/target/SimpleTarget.html. 

I will update the getting started docs, thanks @cristan for the link

**Comment by jcooperation0137** [comment]
Same issue. I've used Glide (4.9.0), but onResourceReady has not been called.
Logcat shows setRequest -> getSize -> onLoadCreated.

**Comment by vijayamurugan** [comment]
Here is the solution

  Glide
                        .with(this)
                        .load("URL")
                        .into(new CustomTarget<Drawable>() {
                            @Override
                            public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                                menu_local.getItem(0).setIcon(resource);
                            }

                            @Override
                            public void onLoadCleared(@Nullable Drawable placeholder) {

                            }
                        });

**Comment by AndroidDeveloperLB** [comment]
@vijayamurugan Should we worry about onLoadCleared ?
It says: 

> A mandatory lifecycle callback that is called when a load is cancelled and its resources are freed.
> You must ensure that any current Drawable received in onResourceReady(Object, Transition) is no longer used before redrawing the container (usually a View) or changing its visibility.

I don't understand its usage. Do we need to put there something ? If so, what, and in which cases?
