### ISSUE TITLE
class com.bumptech.glide.load.engine.GlideException: Failed to load resource

### ISSUE THREAD

**Issue by DILIPSKUMAR1410** [bumptech/glide#3307]
glide is works fine while using for single image.....but breaks when call through adapter loading multiple images

**Comment by KimiChiu** [comment]
How come there are 4 similar issues but all marked as stale?
Having the same problem here, any idea?

**Comment by DILIPSKUMAR1410** [comment]
I had quoted links which glide was unable to render. Try to check url
before rendering .

**Comment by hearbeathorror** [comment]
I still face this issue with the following code snippet: and library version 4.9.0, and the png url exists. internet is working too, but the error has no detailed information why it is failing:

`2019-05-21 23:00:21.213 3300-3870/package_name W/Glide: Load failed for https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png with size [60x60]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource`

The code:

```
  Glide.with(this).asBitmap()
                            .load(result.getIcon())
                            .addListener(new RequestListener<Bitmap>() {
                                @Override
                                public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Bitmap> target, boolean isFirstResource) {
                                    return false;
                                }

                                @Override
                                public boolean onResourceReady(Bitmap bitmap, Object model, Target<Bitmap> target, DataSource dataSource, boolean isFirstResource) {
                                    final Canvas canvas = new Canvas(bitmap);
                                    drawBitmap(bitmap);
                                    return false;
                                }
                            }).submit(60,60)
```

Can anyone please tell me what i may be doing wrong?

**Comment by alcarazolabs** [comment]
I also have problems with https and javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8da1d70: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x92e3c5e1:0x00000000)
Sometimes can load imagens from https web pages and also sometimes can load images from http pages..
I'm using this code.. works for google blogspot images and another domains but sometimes fail
        Glide.with(holder.itemView.getContext()).load(imagen)
                .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                .error(R.drawable.ic_launcher_background)
                //.override(200, 200) // resizing
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                        return false;
                    }
                }).into(holder.imagen);

exist a library for android >= API 17 that can load images from internet using http, https without problems?
what can I do?

**Comment by krunalChhabhaya** [comment]
Load failed for [gs://decordex-f52f4.appspot.com/product1.jpg] with dimensions [456x525]
 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
 
 
 adapter file:
 override fun onBindViewHolder(holder: ProductViewHolder, position: Int) {
        val product = products[position]

        Glide.with(holder.itemView.context)
            .load(product.image)
            .into(holder.productImageView)

        holder.productNameTextView.text = product.name
        holder.productPriceTextView.text = "$${product.price}"
    }
    
    MyAppGlideModule.kt:
    package com.example.decordex

import android.content.Context
import com.bumptech.glide.Glide
import com.bumptech.glide.Registry
import com.bumptech.glide.annotation.GlideModule
import com.bumptech.glide.module.AppGlideModule
import com.firebase.ui.storage.images.FirebaseImageLoader
import com.google.firebase.storage.StorageReference
import java.io.InputStream

@GlideModule
class MyAppGlideModule: AppGlideModule() {
    override fun registerComponents(context: Context, glide: Glide, registry: Registry) {
        //super.registerComponents(context, glide, registry)
        registry.append(
            StorageReference::class.java,
            InputStream::class.java,
            FirebaseImageLoader.Factory()
        )
    }
}


can anyone help me solve this issue of glide not fetching images from firebase Storage. I have an assignment due soon.
