### ISSUE TITLE
java.lang.NullPointerException at com.bumptech.glide.util.Util.getBitmapByteSize

### ISSUE THREAD

**Issue by van11** [bumptech/glide#331]
Using glide 3.5.1, crashing a lot when `onTrimMemory` is triggered.

>E/AndroidRuntime( 8832): java.lang.NullPointerException
E/AndroidRuntime( 8832): 	at com.bumptech.glide.util.Util.getBitmapByteSize(Util.java:79)
E/AndroidRuntime( 8832): 	at com.bumptech.glide.load.engine.bitmap_recycle.SizeStrategy.getSize(SizeStrategy.java:86)
E/AndroidRuntime( 8832): 	at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimToSize(LruBitmapPool.java:171)
E/AndroidRuntime( 8832): 	at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.clearMemory(LruBitmapPool.java:154)
E/AndroidRuntime( 8832): 	at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimMemory(LruBitmapPool.java:161)
E/AndroidRuntime( 8832): 	at com.bumptech.glide.Glide.trimMemory(Glide.java:381)

**Comment by sjudd** [comment]
Thanks for the report.

Are you able to reliably reproduce this and if so, can you provide steps to do so? Are you using Glide 3.5.1? What version of Android are you using?

**Comment by van11** [comment]
Try using phone, emulator with very low memory. Then `onLowMemory` should be triggered on app close. I used Android 4.4.4. And yes, Glide 3.5.1

**Comment by sjudd** [comment]
I tried for a while and wasn't able to reproduce it. 

The above commit avoids the exception and prints some verbose logging. If you see that log go off and can paste the output here, I'd appreciate it!

**Comment by van11** [comment]
Looks like now the problem is solved, many thanks! :)
