### ISSUE TITLE
Use ModelLoader ,MenoryCache never run 

### ISSUE THREAD

**Issue by raqusty** [bumptech/glide#3310]
GlideVersion: 4.8.0
My project use ModelLoaders to Handling custom sizes.
but I find the Image can‘t load from memory cache . memory cache no emtry
Engine.java    method load
![image](https://user-images.githubusercontent.com/13335326/45348637-c8724080-b5e1-11e8-8447-d7c285e60012.png)

my code :
![image](https://user-images.githubusercontent.com/13335326/45348347-fa36d780-b5e0-11e8-94fb-e4853b72a13b.png)

BaseGliderUrlLoader
![image](https://user-images.githubusercontent.com/13335326/45348395-19ce0000-b5e1-11e8-9ab6-ed540cc51abf.png)

AppGlideModule
![image](https://user-images.githubusercontent.com/13335326/45348452-4255fa00-b5e1-11e8-9f7d-0efe3f256247.png)

I find glide project's  demo giphy app is the same .  
Is this a normal situation?
**thanks**

**Comment by sjudd** [comment]
Your Model needs to implement equals/hashCode, the Giphy sample actually needs to do the same, thanks for pointing that out.

**Comment by raqusty** [comment]
> Your Model needs to implement equals/hashCode, the Giphy sample actually needs to do the same, thanks for pointing that out.

Thank you for your answer.
