### ISSUE TITLE
Trying to repackage Glide to avoid version conflicts

### ISSUE THREAD

**Issue by yekretsam** [bumptech/glide#3315]
Hi!

**Glide Version**: 4.7

**Issue details / Repro steps / Use case background**: 
We are currently building a library based on Glide 4.7 and are running into issues with an application using our library that is using Glide 3.7. We would like to prevent this from happening in the future and our approach would be to repackage Glide with jarjar.

Repackaging the full jar of 4.7 was no issue, but i assume we will also need to repackage the annotation processing required libs (annotation + compiler) as Glide 4.7 doesn't work without any annotation usage afaik.

Now i run into compile errors for classes that are not found within the generated classes from Glide. I checked the compiler class implementations (e.g. GlideGenerator) and they specify specific namespaces e.g.:
private static final String GLIDE_QUALIFIED_NAME = "com.bumptech.glide.Glide";

And that is more or less where i am stuck currently, as i would require my prefixed packagenames on those locations too i assume, which will introduce an extra step to change the code manually + recompile the component + i would then also need to somehow handle the other repackaged libraries that are part of the compiler component...

Is there an easier approach for doing all of that? Could the compile component somehow be configured for different package? Or am i maybe on the - only - right track for accomplishing this version independency?

Thanks a lot in advance!

**Comment by yihuanzhou** [comment]
If it's an option, re-packaging Glide3 seems easier to me.

**Comment by yekretsam** [comment]
hi yihuanzhou, that's what we tried after struggling with 4.7, but we also failed there because if the host app is using extra integration dependencies (e.g. okhttp3) we again see issues for classes that can't be found :(
