### ISSUE TITLE
Introduce issue templates

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#332]
We know well that Google Code has a nice template for each bug, sadly Github doesn't. Almost every issue here has "Glide/Android/Phone version?" as the first response after a bug is reported.

This could be prevented/"automated" with the following steps:
* add "report issue" button/link to Readme.MD at the top
* add "report issue" button/link to wiki
* add contributing.md describing how to make a nice & efficient issue (formatted and full of *relevant* info)
With a copy-pasteable markdown template and a "report issue" link.

See https://github.com/isaacs/github/issues/99 for more info.

The "report issue" link would look like this (example, could be refined):
https://github.com/bumptech/glide/issues/new?body=**Glide%20Version/Integration%20library%20(if%20any)**:%0A**Device/Android%20Version**:%0A**Is%20it%20consistently%20reproducible?**:%0A**Issue%20details/Repro%20steps**:%0A```%0AGlide.with(context)...%3B%0A```%0A%0A**Stack%20trace**:%0A```%0Apaste%20stack%20trace%20here%0A```

**Comment by sjudd** [comment]
I was looking in to this a bit earlier, we should do this.
