### ISSUE TITLE
Target setBackground animation

### ISSUE THREAD

**Issue by Anzhi-Meiying** [bumptech/glide#3323]
Hello

                Glide.with(mContext)
                        .load(bean.getPicUrl())
                        .into(new Target<Drawable>() {
                            @Override
                            public void onLoadStarted(Drawable placeholder) {

                            }

                            @Override
                            public void onLoadFailed(Drawable errorDrawable) {

                            }

                            @Override
                            public void onResourceReady(Drawable resource, Transition<? super Drawable> transition) {
                                background.setBackground(resource);
                            }

                            ......

                        });

How can I animation this? For example, a fade-in animation where the background's alpha changes from 0 to 1 in 500ms.

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/transitions.html
