### ISSUE TITLE
inccaurate pixel values

### ISSUE THREAD

**Issue by digitxo** [bumptech/glide#3324]
4.8.0

Android 7.0 - Samsung Glaxy

Im trying to use glide to save an accurate image. I mean each pixel.
-->
**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java

```
        Glide.with(mContext).asBitmap().load(zoneSetupViewPaint.getDrawingCache())

                .into(new SimpleTarget<Bitmap>() {
                          @Override
                          public void onResourceReady(@NonNull final Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                            Log.d("COLOR", " hereee " );

                            fixBitmap = resource;
                          }
                      }
                );
```
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

The issue I'm getting is this precisely.

ORANGE = -33536

but.. I save the image then load it

and getPixel shows 

ORANGE = -33535

This is terrible for my app.

I use

int pixel = zoneCache.getPixel(point.x, point.y);

To get the pixel

This is all that's relevant I believe.

**Comment by sjudd** [comment]
Use encodeFormat with PNG: http://bumptech.github.io/glide/javadocs/480/com/bumptech/glide/request/RequestOptions.html#encodeFormat-android.graphics.Bitmap.CompressFormat-. By default Glide saves as JPEG when we don't think the Bitmap contains transparent pixels becaus JPEG is substantially faster to encode and decode. If you need lossless though, you'll need to encode with WEBP or PNG.
