### ISSUE TITLE
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:     class com.bumptech.glide.integration.okhttp3.OkHttpUrlLoader, unresolved supertypes: com.bumptech.glide.load.model.stream.StreamModelLoader	

### ISSUE THREAD

**Issue by danilodequeiroz** [bumptech/glide#3325]
**Glide Version**:
`implementation 'com.github.bumptech.glide:glide:4.8.0'`

**Integration libraries**:
`def okhttp3_version = "3.10.0"`
`implementation 'com.github.bumptech.glide:okhttp3-integration:1.5.0@aar'`
`implementation "com.squareup.okhttp3:okhttp:$okhttp3_version"`
`annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'`
`kapt 'com.github.bumptech.glide:compiler:4.8.0'`

**Issue details / Repro steps / Use case background**: 
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:     class com.bumptech.glide.integration.okhttp3.OkHttpUrlLoader, unresolved supertypes: com.bumptech.glide.load.model.stream.StreamModelLoader	

It doesn't compile, I'm on AS 3.3 Canary 10.

**Comment by sjudd** [comment]
It looks like you're using an old version of the okhttp3 integration, see http://bumptech.github.io/glide/int/okhttp3.html
