### ISSUE TITLE
Add Glide Html.ImageGetter to the core library

### ISSUE THREAD

**Issue by ddekanski** [bumptech/glide#3328]
Using `TextView`s as simple HTML containers that display decorated text together with images is quite popular these days as an alternative to heavy-weight `WebView`. To properly display images in a `TextView`, one needs an implementation of `Html.ImageGetter`. While there is an example Glide app with such implementation, it's aimed at Glide 3, and I think such `GlideImageGetter` deserves being included in the lib (it's small and useful).

Here's my implementation for Glide 4.8 loosely based on others that work with other image libraries. Could be buggy, but may serve as a good starting point:

```package com.example.utils;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.text.Html;
import android.widget.TextView;

import com.bumptech.glide.request.Request;
import com.bumptech.glide.request.target.SizeReadyCallback;
import com.bumptech.glide.request.target.Target;
import com.bumptech.glide.request.transition.Transition;

public class GlideImageGetter implements Html.ImageGetter {

    private Context context;
    private TextView textView;

    GlideImageGetter(Context context, TextView target) {
        this.context = context;
        textView = target;
    }

    @Override
    public Drawable getDrawable(String url) {
        BitmapDrawablePlaceholder drawable = new BitmapDrawablePlaceholder();

        GlideApp.with(context)
                .asBitmap()
                .load(url)
                .into(drawable);

        return drawable;
    }

    private class BitmapDrawablePlaceholder extends BitmapDrawable implements Target<Bitmap> {

        protected Drawable drawable;

        BitmapDrawablePlaceholder() {
            super(context.getResources(), Bitmap.createBitmap(1, 1, Bitmap.Config.ARGB_8888));
        }

        @Override
        public void draw(final Canvas canvas) {
            if (drawable != null) {
                drawable.draw(canvas);
            }
        }

        private void setDrawable(Drawable drawable) {
            this.drawable = drawable;
            int drawableWidth = drawable.getIntrinsicWidth();
            int drawableHeight = drawable.getIntrinsicHeight();
            int maxWidth = textView.getMeasuredWidth();
            if (drawableWidth > maxWidth) {
                int calculatedHeight = maxWidth * drawableHeight / drawableWidth;
                drawable.setBounds(0, 0, maxWidth, calculatedHeight);
                setBounds(0, 0, maxWidth, calculatedHeight);
            } else {
                drawable.setBounds(0, 0, drawableWidth, drawableHeight);
                setBounds(0, 0, drawableWidth, drawableHeight);
            }

            textView.setText(textView.getText());
        }

        @Override
        public void onLoadStarted(@Nullable Drawable placeholderDrawable) {
            if(placeholderDrawable != null) {
                setDrawable(placeholderDrawable);
            }
        }

        @Override
        public void onLoadFailed(@Nullable Drawable errorDrawable) {
            if (errorDrawable != null) {
                setDrawable(errorDrawable);
            }
        }

        @Override
        public void onResourceReady(@NonNull Bitmap bitmap, @Nullable Transition<? super Bitmap> transition) {
            setDrawable(new BitmapDrawable(context.getResources(), bitmap));
        }

        @Override
        public void onLoadCleared(@Nullable Drawable placeholderDrawable) {
            if(placeholderDrawable != null) {
                setDrawable(placeholderDrawable);
            }
        }

        @Override
        public void getSize(@NonNull SizeReadyCallback cb) {
            textView.post(() -> cb.onSizeReady(textView.getWidth(), textView.getHeight()));
        }

        @Override
        public void removeCallback(@NonNull SizeReadyCallback cb) {}

        @Override
        public void setRequest(@Nullable Request request) {}

        @Nullable
        @Override
        public Request getRequest() {
            return null;
        }

        @Override
        public void onStart() {}

        @Override
        public void onStop() {}

        @Override
        public void onDestroy() {}

    }
}

**Comment by AzimLord** [comment]
> Using `TextView`s as simple HTML containers that display decorated text together with images is quite popular these days as an alternative to heavy-weight `WebView`. To properly display images in a `TextView`, one needs an implementation of `Html.ImageGetter`. While there is an example Glide app with such implementation, it's aimed at Glide 3, and I think such `GlideImageGetter` deserves being included in the lib (it's small and useful).
> 
> Here's my implementation for Glide 4.8 loosely based on others that work with other image libraries. Could be buggy, but may serve as a good starting point:
> 
> ```
> 
> import android.content.Context;
> import android.graphics.Bitmap;
> import android.graphics.Canvas;
> import android.graphics.drawable.BitmapDrawable;
> import android.graphics.drawable.Drawable;
> import android.support.annotation.NonNull;
> import android.support.annotation.Nullable;
> import android.text.Html;
> import android.widget.TextView;
> 
> import com.bumptech.glide.request.Request;
> import com.bumptech.glide.request.target.SizeReadyCallback;
> import com.bumptech.glide.request.target.Target;
> import com.bumptech.glide.request.transition.Transition;
> 
> public class GlideImageGetter implements Html.ImageGetter {
> 
>     private Context context;
>     private TextView textView;
> 
>     GlideImageGetter(Context context, TextView target) {
>         this.context = context;
>         textView = target;
>     }
> 
>     @Override
>     public Drawable getDrawable(String url) {
>         BitmapDrawablePlaceholder drawable = new BitmapDrawablePlaceholder();
> 
>         GlideApp.with(context)
>                 .asBitmap()
>                 .load(url)
>                 .into(drawable);
> 
>         return drawable;
>     }
> 
>     private class BitmapDrawablePlaceholder extends BitmapDrawable implements Target<Bitmap> {
> 
>         protected Drawable drawable;
> 
>         BitmapDrawablePlaceholder() {
>             super(context.getResources(), Bitmap.createBitmap(1, 1, Bitmap.Config.ARGB_8888));
>         }
> 
>         @Override
>         public void draw(final Canvas canvas) {
>             if (drawable != null) {
>                 drawable.draw(canvas);
>             }
>         }
> 
>         private void setDrawable(Drawable drawable) {
>             this.drawable = drawable;
>             int drawableWidth = drawable.getIntrinsicWidth();
>             int drawableHeight = drawable.getIntrinsicHeight();
>             int maxWidth = textView.getMeasuredWidth();
>             if (drawableWidth > maxWidth) {
>                 int calculatedHeight = maxWidth * drawableHeight / drawableWidth;
>                 drawable.setBounds(0, 0, maxWidth, calculatedHeight);
>                 setBounds(0, 0, maxWidth, calculatedHeight);
>             } else {
>                 drawable.setBounds(0, 0, drawableWidth, drawableHeight);
>                 setBounds(0, 0, drawableWidth, drawableHeight);
>             }
> 
>             textView.setText(textView.getText());
>         }
> 
>         @Override
>         public void onLoadStarted(@Nullable Drawable placeholderDrawable) {
>             if(placeholderDrawable != null) {
>                 setDrawable(placeholderDrawable);
>             }
>         }
> 
>         @Override
>         public void onLoadFailed(@Nullable Drawable errorDrawable) {
>             if (errorDrawable != null) {
>                 setDrawable(errorDrawable);
>             }
>         }
> 
>         @Override
>         public void onResourceReady(@NonNull Bitmap bitmap, @Nullable Transition<? super Bitmap> transition) {
>             setDrawable(new BitmapDrawable(context.getResources(), bitmap));
>         }
> 
>         @Override
>         public void onLoadCleared(@Nullable Drawable placeholderDrawable) {
>             if(placeholderDrawable != null) {
>                 setDrawable(placeholderDrawable);
>             }
>         }
> 
>         @Override
>         public void getSize(@NonNull SizeReadyCallback cb) {
>             textView.post(() -> cb.onSizeReady(textView.getWidth(), textView.getHeight()));
>         }
> 
>         @Override
>         public void removeCallback(@NonNull SizeReadyCallback cb) {}
> 
>         @Override
>         public void setRequest(@Nullable Request request) {}
> 
>         @Nullable
>         @Override
>         public Request getRequest() {
>             return null;
>         }
> 
>         @Override
>         public void onStart() {}
> 
>         @Override
>         public void onStop() {}
> 
>         @Override
>         public void onDestroy() {}
> 
>     }
> }
> ```

There will be a memory issue if you do it this way tho :/

**Comment by marcoRS** [comment]
Any updates on this?

**Comment by yrajabi** [comment]
I have created a gist based on @ddekanski code with some changes and improvements:
- Added weak reference to avoid context memory leak
- Added parameter matchParentWidth to determine whether image should fit its parent or not
- Added an inner class interface to optionally populate list of all image URIs loaded within this getter
- Added density awareness to drawables (useful when they are loaded from assets or network)

[https://gist.github.com/yrajabi/5776f4ade5695009f87ce7fcbc08078f](https://gist.github.com/yrajabi/5776f4ade5695009f87ce7fcbc08078f)
The above linked gist is tested on Glide 4.9 and 4.11 successfully.

**Comment by iamriajul** [comment]
First Thanks to @yrajabi 
I have modified his code in Kotlin, here is my version: https://gist.github.com/iamriajul/e0026c1c8e1783e6ffa2da511d1d4f37

This might help others.
Thanks...

**Comment by dbof10** [comment]
sample code here 
https://github.com/dbof10/hunt-android/blob/e5d7bdb6c369427fdcbfaadcd9eb66477c7eade0/app/src/main/java/com/ctech/eaty/util/glide/GlideImageGetter.kt

**Comment by austin-ek** [comment]
this can be done easily without creating a custom class

```
class MyImageGetter(val context : Context, val textView : TextView, val height : Int, val width : Int) : Html.ImageGetter {
    override fun getDrawable(url: String?): Drawable {

        val future = Glide.with(context).load(url).submit()
        val drawable = future.get()

        drawable.setBounds(0, 0, width, height)

        textView.text = textView.text

        return drawable
    }
}
```
