### ISSUE TITLE
Loading thumbnails on RecyclerView stops while scrolling fast / very slow to render

### ISSUE THREAD

**Issue by tobiasKaminsky** [bumptech/glide#3330]
**Glide Version**: 4.8.0

**Integration libraries**: recyclerview-integration, but happened before

**Device/Android Version**: emulator / also on other devices e.g. Samsung S5neo

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 GlideApp.with(context)
                    .load(container)
                    .placeholder(placeholder)
                    .error(placeholder)
                    .into((ImageView) view);
```

Step to reproduce
- open up folder with ~200 images
- scroll slowly -> wonderful and responsive image loading
- scroll quickly
- at some point glide does not download any longer any image, not the older ones, not the current visible ones (verified by logcat, it just stops)
- scroll up to latest fetched thumbnail helps sometimes to trigger the pending ones to finish

Second problem:
- open up folder with ~200 images
- let glide load first e.g. 20 items
- device offline
- scroll down to e.g. 30-40 items --> see placeholder as expected
- scroll to first 20 items which are in cache
- see that these items are loaded very slowly, ~2 / second
- they are in cache, but still are loaded to slow…

**Comment by sjudd** [comment]
Let me know if you're able to reproduce in a sample app. Cancellation, resource re-use, or device limitations may all factor in.
