### ISSUE TITLE
 Could not GET 'https://jcenter.bintray.com/com/github/bumptech/glide/compiler/4.8.0/compiler-4.8.0.jar'.

### ISSUE THREAD

**Issue by h923745834** [bumptech/glide#3334]
The project build.gradle
 repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://maven.google.com' }

    }
The app build.gradle
dependencies {
     .......
     .......
    compile 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
   
}
**when Build->rebuild project have some error to print in the messages window;**
 Error:Could not resolve all files for configuration ':app:debugAnnotationProcessorClasspath'.
> Could not download compiler.jar (com.github.bumptech.glide:compiler:4.8.0)
   > Could not get resource 'https://jcenter.bintray.com/com/github/bumptech/glide/compiler/4.8.0/compiler-4.8.0.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/github/bumptech/glide/compiler/4.8.0/compiler-4.8.0.jar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.230.0.149, d29vzk4ow07wi7.cloudfront.net/54.230.0.117, d29vzk4ow07wi7.cloudfront.net/54.230.0.113, d29vzk4ow07wi7.cloudfront.net/54.230.0.146] failed: Read timed out

**Comment by alvince** [comment]
呵呵呵…
网络问题也跑来提 issue，自己挂个代理 ok？

**Comment by h923745834** [comment]
那为什么https://jcenter.bintray.com可以访问。
https://jcenter.bintray.com/com/github/bumptech/glide/compiler/4.8.0/compiler-4.8.0.jar访问不了。这可能是jcenter不存在这个jar吧。

**Comment by idish** [comment]
Happens to me also.. Is there any fix?
