### ISSUE TITLE
Why not transformation for error image on Glide?

### ISSUE THREAD

**Issue by lmdic** [bumptech/glide#3335]
Android Studio 3.2, Java 1.8, Gradle 4.5

In my app/build.gradle:

`implementation "com.github.bumptech.glide:glide:4.2.0"`

Here code that:

1. Load image from remote URL
2. Create transformation when success load image from remote url (round corners on top)
3. If image is not load then show orange error image

So in my layout xml:

```
<ImageView
            android:id="@+id/imageViewPhoto"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"            
            app:imageUrl="@{item.preview.formats.reference.url}"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
```

In my java code (RecyclerView Adapter)

 ```
@BindingAdapter("imageUrl")
    public static void loadImage(ImageView view, String imageUrl) {
        Glide.with(view.getContext()).load(imageUrl)
                .apply(new RequestOptions().error(R.drawable.default_image))
                .apply(RequestOptions.bitmapTransform(
                        new GlideRoundedCornersTransformation(view.getContext(), (int) AndroidUtil.dpToPx(view.getContext(),
                                view.getContext().getResources().getInteger(R.integer.image_rounded_corner_radius_dp)),
                                0, GlideRoundedCornersTransformation.CornerType.TOP)))
                .into(view);
    }
```

Here result:

![error](https://user-images.githubusercontent.com/303539/46196375-8f3f0d80-c30f-11e8-9088-f1a49e1e6801.jpg)

On the right side (green color) is success load image. As you can see it has rounded corners on the top.

On the left side is a default (error) images (orange). As you can see it has NOT rounded corners on the top. Why? 
How I can do rounded corners on correct image and on default(error) images?

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/placeholders.html#are-transformations-applied-to-placeholders
