### ISSUE TITLE
Not getting thumbnail for some videos 

### ISSUE THREAD

**Issue by 24Lathiya** [bumptech/glide#3337]
Hi, I have using glide for set thumbnail for video from Internal memory using below code. 

```
RequestOptions options = new RequestOptions()
                .centerCrop()
                .placeholder(R.drawable.err_movie_placeholder)
                .error(R.drawable.err_movie_placeholder);

        Glide.with(c)
                .load(firstVideoPath)
                .apply(options)
                .into(holder.ivThumb);
```
Now my issue is for some high resolution video formate like wmv,mpg,mov,avi,vob,mpeg,flv etc. glide not able to set thumbnail.
Please help me to fix this issue.

Thanks in advance.

**Comment by tushar09** [comment]
I am also using glide to load video file's thumbnail. Its working great for .mp4 and .mkv but .flv or .avi is not working. The problem is not about the size or resolution, its about video codec and format.

**Comment by sjudd** [comment]
Glide uses MediaMetadataRetriever. If you're able to decode a video frame if you use MediaMetadataRetriever directly but aren't able to when you use Glide, let me know. Otherwise as @tushar09 said, it's likely a format that's not supported on that particular device/version of Android.

**Comment by sjudd** [comment]
Can you attach an example video that reproduces this behavior? If you wait a similar amount of time does Glide load the video frame?
