### ISSUE TITLE
Glide does not load same image with different dimension from the disk as expected. Glide V3.7.0 

### ISSUE THREAD

**Issue by mazzouzi** [bumptech/glide#3342]
Hi.

I'm using Glide V3.7.0 in my android app and it seems like Glide still loads the image the second time from network and not from the cache as expected.

I have Activity A and inside it a full-screen fragment A'. 
In A', I have a viewPager that displays multiple images. Each image view's dimension is 185x185.
So when I enter A', Glide loads all images of the view pager. I use diskCacheStrategy.RESULT to be sure that the original image before transformation is stored in the disk: 

```
Glide.with(context)
                 .load("https://www...image.jpg")
                 .diskCacheStrategy(DiskCacheStrategy.RESULT)
                 .listener(new CustomRequestListener(imageView){
                     @Override
                     public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                         super.onResourceReady(resource, model, target, isFromMemoryCache, isFirstResource);
                         return false;
                     }
                 })
                 .into(new GlideDrawableImageViewTarget(imageView) {
                 ...
                 }
```

Then if I click say on the first image, I start Activity B which displays another viewPager with exact same image Urls than A'. The only difference is that the imageView's dimension is this time much bigger : 
     
```
  Glide.with(container.context)
            .load("https://www...image.jpg")
            .listener(object : RequestListener<String, GlideDrawable> {
                override fun onException(
                    e: Exception?,
                    model: String?,
                    target: Target<GlideDrawable>?,
                    isFirstResource: Boolean
                ): Boolean {
                    return false
                }

                override fun onResourceReady(
                    resource: GlideDrawable?,
                    model: String?,
                    target: Target<GlideDrawable>?,
                    isFromMemoryCache: Boolean,
                    isFirstResource: Boolean
                ): Boolean {
                    itemView
                        .productImage
                        .viewTreeObserver
                        .addOnPreDrawListener(
                            object : ViewTreeObserver.OnPreDrawListener {
                                override fun onPreDraw(): Boolean {
                                    itemView.productImage
                                        .viewTreeObserver
                                        .removeOnPreDrawListener(this)
                                    ...
                                    return true
                                }
                            }
                        )
                    return false
                }
            })
            .into(itemView.productImage)
```

-> I would expect Glide to load these same Urls from disk the second time but it does not.
-> in B, onResourceReady listener, "isFromMemoryCache" = false. Does this parameter refer only to memory cache excluding disk cache ?
-> The sequence A' > B > A' > B works though. **when I enter B the second time, the activity does load the images from the disk.**

-> Is it because we are loading from a different activity ? Does the context matters ?
-> Can you please confirm or not that Glide is supposed to load same images from the disk the first time I enter B and that even in flight mode Glide should be able to access the disk and load the image ? 

**Glide Version**:   compile 'com.github.bumptech.glide:glide:3.7.0'

**Integration libraries**:
    compile 'com.squareup.okhttp3:okhttp:3.6.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.6.0'

**Device/Android Version**: Nexus 6

**Layout XML**:
```xml
Fragment A' :

<?xml version="1.0" encoding="utf-8"?>
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/custom_view_image_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:id="@+id/custom_view_image_layout_shared_element_transition_image"
        android:contentDescription="@string/desc_image"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:scaleType="centerInside" />
</RelativeLayout>

Activity B (viewPager) :

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/custom_view_image_layout"    
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <it.sephiroth.android.library.imagezoom.ImageViewTouch
        android:id="@+id/custom_view_image_layout_image"
        android:contentDescription="@string/desc_image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="fitCenter"/>

</RelativeLayout>

```

And here is the log when I enter B and load these same images: 

>   V/GenericRequest: finished run method in 0.446876 this: 233868791
>  V/GenericRequest: finished run method in 0.084323 this: 246932580
>  V/GenericRequest: finished run method in 0.143906 this: 87746253
>  V/GenericRequest: finished run method in 0.082083 this: 200600450
>  V/GenericRequest: finished run method in 0.16874999999999998 this: 261493395
>  V/GenericRequest: finished run method in 0.19833299999999998 this: 222356176
>  V/GenericRequest: finished run method in 0.10062499999999999 this: 110895817
>  V/GenericRequest: finished run method in 0.18724 this: 59391438
>  V/GenericRequest: Got onSizeReady in 45.91339 this: 233868791
>  V/GenericRequest: finished setup for calling load in 46.384848999999996 this: 233868791
>  V/GenericRequest: finished setup for calling load in 44.953962999999995 this: 246932580
>  V/GenericRequest: Got onSizeReady in 43.193338 this: 200600450
>  200600450
>  261493395
>  V/GenericRequest: finished onSizeReady in 43.225317 this: 261493395
>  V/GenericRequest: finished setup for calling load in 41.029430999999995 this: 110895817
>  59391438
>  V/GenericRequest: finished onSizeReady in 39.858233 this: 59391438
>  V/GenericRequest: Got onSizeReady in 0.071354 this: 121161347
> : 121161347
>  V/GenericRequest: finished run method in 0.961093 this: 121161347
>  V/GenericRequest: Got onSizeReady in 0.041249999999999995 this: 135291393
>  V/GenericRequest: finished setup for calling load in 0.28015599999999996 this: 219098772
>  V/GenericRequest: Resource ready in 245.627003 size: 0.95367431640625 fromCache: false this: 121161347
>  V/GenericRequest: Resource ready in 299.071697 size: 9.1409912109375 fromCache: false this: 233868791
> e: false this: 246932580
>  V/GenericRequest: Resource ready in 297.17476899999997 size: 9.1409912109375 fromCache: false this: 8774625
>  V/GenericRequest: Resource ready in 296.22253 size: 9.1409912109375 fromCache: false this: 200600450
> e: false this: 261493395
>  V/GenericRequest: Resource ready in 295.16154 size: 9.1409912109375 fromCache: false this: 222356176
>  V/GenericRequest: Resource ready in 294.358571 size: 9.1409912109375 fromCache: false this: 110895817
>  V/GenericRequest: Resource ready in 292.96831 size: 9.1409912109375 fromCache: false this: 59391438
>  V/GenericRequest: Resource ready in 284.860862 size: 1.11572265625 fromCache: false this: 31962750
>  V/GenericRequest: Resource ready in 335.67008599999997 size: 0.3790740966796875 fromCache: false this: 1352
>  V/GenericRequest: Resource ready in 335.386804 size: 2.8839111328125 fromCache: false this: 219098772

**-> fromCache: false each time**
- The second time I enter B, fromCache: true as mentioned above

Thanks in advance for your help !

**Comment by sjudd** [comment]
Glide 3.x isn't supported, but you can check the wiki or previous questions for information on caching.

Let me know if you're able to reproduce on 4.x
