### ISSUE TITLE
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)

### ISSUE THREAD

**Issue by joker-fu** [bumptech/glide#3345]
**Glide Version**: 4.8.0

**Integration libraries**:

**Device/Android Version**: PC和三星S7可以加载出来，红米4A不行

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 Glide.with(activity).load(url).transition(withCrossFade()).into(imageView)
```

**Layout XML**:
```xml
    <android.support.v7.widget.AppCompatImageView
        android:id="@+id/imageTest"
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_200" />
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
10-09 15:29:15.852 31302-31302/com.hp.****.debug W/Glide: Load failed for http://192.168.30.250:9080/mobile/approval/findActivitiModelImg?eventId=150 with size [720x384]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 4 causes:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, DATA_DISK_CACHE, http://192.168.30.250:9080/mobile/approval/findActivitiModelImg?eventId=150
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
      Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, DATA_DISK_CACHE, http://192.168.30.250:9080/mobile/approval/findActivitiModelImg?eventId=150
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
      Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, DATA_DISK_CACHE, http://192.168.30.250:9080/mobile/approval/findActivitiModelImg?eventId=150
    There were 2 causes:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
    There was 1 cause:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
        Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
    There was 1 cause:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
      Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, http://192.168.30.250:9080/mobile/approval/findActivitiModelImg?eventId=150
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
      Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, http://192.168.30.250:9080/mobile/approval/findActivitiModelImg?eventId=150
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed

**Comment by sjudd** [comment]
Looks like a connection issue, server error, or corrupt image. Since you're seeing load failures that don't mention connection issues, it's probably a corrupt image or an error html page that was downloaded in response to the url (some servers redirect to error html pages instead of sending 400/500 errors).

**Comment by joker-fu** [comment]
应该是服务器的问题 换了种方式加载出来了

**Comment by mochadwi** [comment]
> Looks like a connection issue, server error, or corrupt image. Since you're seeing load failures that don't mention connection issues, it's probably a corrupt image or an error html page that was downloaded in response to the url (some servers redirect to error html pages instead of sending 400/500 errors).

As stated [here](https://stackoverflow.com/a/45231625/3763032) 0x80000000 means the file incomplete, or something happened on the process of downsampling image.

**Comment by RunYouCleverBoy** [comment]
Hi. I tried with
https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg


```
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
       
     Glide.with(this).load("https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg").preload()

```
Same same

**Comment by farmazon3000** [comment]
when you try to load svg you get this error

**Comment by CoolMind** [comment]
In my case I tried to load PNG file that wasn't found on server.
