### ISSUE TITLE
If the size of the image cannot be determined in advance, how can I use "PreloadSizeProvider" in "RecyclerView" instead

### ISSUE THREAD

**Issue by qianshengta** [bumptech/glide#3347]
**Glide Version**:
4.8.0

**Integration libraries**:
OkHttp3 

**Device/Android Version**:
Android  8.0

**Issue details / Repro steps / Use case background**: 
If the size of the image cannot be determined in advance, how can I use "PreloadSizeProvider" in "RecyclerView" instead?I want to load a set of images in "RecyclerView", but the size of the images is determined by the server. The client does not know in advance that the View being hosted is adaptive.How do I select "PreloadSizeProvider" and set the parameters for them?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
null

**Layout XML**:
```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/item_commodity_details_img"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        android:scaleType="fitXY"/>

</LinearLayout>
```

**Stack trace / LogCat**:
null

**Comment by sjudd** [comment]
The only benefit the preloader provides is to fetch the images that you're going to use before you get to them. Ideally you replicate whatever logic is used to fetch the images when you actually try to bind the view.

**Comment by qianshengta** [comment]
First of all, thank you very much for your answer。
So I should customize a "PreloadSizeProvider" and use the relevant method to get the size of the image before binding the view?Existing "ViewPreloadSizeProvider" and "FixedPreloadSizeProvider" cannot do what I said.Can I interpret it this way

**Comment by sjudd** [comment]
Yes if you don't have a single fixed size for all images and you can't use the view size, you'll need a custom implementation.

**Comment by qianshengta** [comment]
thanks a lot
