### ISSUE TITLE
Source image stretched to getMaxDisplayLength() if `wrapContent` used

### ISSUE THREAD

**Issue by see-mack** [bumptech/glide#3350]
**Glide Version**:4.3.1

**Device/Android Version**: Any device

**Issue details / Repro steps / Use case background**: 

We have an image with height/width attributes set to `wrapContent`. Due to com.bumptech.glide.request.target.ViewTarget.getTargetDimen(), Glide sets the size of the image to be the size of the display as a guard against downloaded images that are too large to be loaded into memory. In the case of a small image (40x40px), Glide is stretching image out to fit the screen size dimensions and then delivering that resource to the imageView.

The defence against large images makes sense but why scale images up to the max size if they are smaller.

![image](https://user-images.githubusercontent.com/5441261/46900234-dfb87e00-ce6c-11e8-9beb-8fbf7a1bfdf4.png)

**Comment by sjudd** [comment]
Avoid wrap_content, change the scaleType of your ImageView, or in this case you can get away with using centerInside explicitly (which will override any default transformation applied based on the scale type of your ImageView).
