### ISSUE TITLE
（may be bug）)Wrong disk cache of last time can not been replaced when new right cache arrvies

### ISSUE THREAD

**Issue by liusgh** [bumptech/glide#3353]
I have a question for method "put" in class DiskLruCacheWrapper.
Following is Source code: 
        DiskLruCache diskCache = getDiskCache();
        Value current = diskCache.get(safeKey);
        if (current != null) {
          return;
        }
 We will not get correct result next time when current  is non null. Because current cache may be wrong, and we can not replace it.
Glide version :4.7.1

**Comment by sjudd** [comment]
Incorrect results shouldn't be written to the disk cache. How are you writing the incorrect result to begin with? Is this with Glide's default ModelLoaders/decoders? If so, what version of Glide are you using?

**Comment by liusgh** [comment]
> Incorrect results shouldn't be written to the disk cache. How are you writing the incorrect result to begin with? Is this with Glide's default ModelLoaders/decoders? If so, what version of Glide are you using?
@sjudd 1. I do not know why incorrect results has been written to the disk cache, but they really existed in cache. And the scenario we came across was that the disk cache file can not been decoded successfully.
2. I do not know what is your meaning.
3. with default decoders and our custom remote modelLoaders
4. 4.7.1

**Comment by sjudd** [comment]
Probably your custom model loader is passing partial data back as a successful result, which Glide will then write to cache. 

Make sure your custom ModelLoader fails if it doesn't receive complete data. For most HTTP requests, Glide's default ModelLoaders try to do this by checking the content length.
