### ISSUE TITLE
Version 4 not working with viewPager

### ISSUE THREAD

**Issue by miroslavign** [bumptech/glide#3356]
**Glide Version**:4.8.0

**Integration libraries**: using okhttp3

**Device/Android Version**:Nexus 6P android O

**Issue details / Repro steps / Use case background**: It does not load/present an image. Using listeners to catch error, it does NOT go to listener.onLoadFailed

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Inside viewPager.instantiateItem, 
// after inflating item, after getting imageView from inflated layout
// this is NOT working
                GlideApp.with(imageView.getContext())
                        .load(imageUrl)
                        .into(imageView);
// and this works
                Picasso.with(imageView.getContext())
                        .load(imageUrl)
                        .into(imageView);

// like Glide is having issue loading into not yet rendered view
// works in plain activity loading, but not in viewPager
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by miroslavign** [comment]
One more detail, when grabbing the layout using uiautomatorviewer,
I clearly see that imageView is not visible/ looks like it is not inflated, 
while when Picasso is loading in it, i see the imageView in view hierarchy

**Comment by miroslavign** [comment]
Actually, in my case it seems that it is connected to specific ImageView implementation:
https://github.com/MikeOrtiz/TouchImageView/issues/178

This patches it (for the time being)
```                    viewTarget = new ViewTarget<TouchImageView, BitmapDrawable>(imageView) {
                        @Override
                        public void onResourceReady(BitmapDrawable bitmap, Transition<? super BitmapDrawable> transition) {
                            this.view.setImageDrawable(bitmap);
                        }
                    };
                GlideApp
                        .with(imageView.getContext())
                        .load(image)
                        .into(viewTarget);

```

But now I have an issue of, how to generify
```
public void onResourceReady(BitmapDrawable bitmap, Transition<? super 
```
to be```BitmapDrawable ``` or ```GifDrawable``` in order to be able to load/set anim gif as well ?

**Comment by miroslavign** [comment]
Final cut, resolves it for the time being
```
                ViewTarget viewTarget = new ViewTarget<TouchImageView, Drawable>(imageView) {
                        @Override
                        public void onResourceReady(@NonNull Drawable drawable, Transition<? super Drawable> transition) {
                            this.view.setImageDrawable(drawable);
                            if (drawable instanceof GifDrawable) {
                                GifDrawable gd = (GifDrawable) drawable;
                                gd.start();
                            }
                        }
                    };
                GlideApp
                        .with(imageView.getContext())
                        .load(image)
                        .into(viewTarget);
```

**Comment by miroslavign** [comment]
Any ideas how to make it work and not use deprecated ViewTarget ?

**Comment by sjudd** [comment]
Use `CustomViewTarget`. If the View subclasses `ImageViewTarget`, you can use `DrawableImageViewTarget` directly.

**Comment by Jejid** [comment]
> Final cut, resolves it for the time being
> 
> ```
>                 ViewTarget viewTarget = new ViewTarget<TouchImageView, Drawable>(imageView) {
>                         @Override
>                         public void onResourceReady(@NonNull Drawable drawable, Transition<? super Drawable> transition) {
>                             this.view.setImageDrawable(drawable);
>                             if (drawable instanceof GifDrawable) {
>                                 GifDrawable gd = (GifDrawable) drawable;
>                                 gd.start();
>                             }
>                         }
>                     };
>                 GlideApp
>                         .with(imageView.getContext())
>                         .load(image)
>                         .into(viewTarget);
> ```

Hi sir, this solution doesnt work for me, it dont show me image in viewpager yet. Any idea why?.. Thanks for help. Im new here

**Comment by Jejid** [comment]
Finally, for now i used Picasso to get zoom from TouchImageView with Viewpager. 

Maybe these answer help something with glide: https://stackoverflow.com/questions/20943831/view-pager-imageview-pinch-zoom-rotation/20944068#20944068
