### ISSUE TITLE
RequestBuilder.load(URL url) is deprecated.

### ISSUE THREAD

**Issue by malvinstn** [bumptech/glide#3358]
**Glide Version**: 4.8.0

**Integration libraries**: OkHttp3

**Issue details / Repro steps / Use case background**: 

Hi, I'm looking into the reason why `RequestBuilder.load(URL)` is marked as deprecated, and in the documentation, you mentioned [this article](http://goo.gl/c4hHNu) which basically says that `java.net.URL` initiates Internet connection when performing `hash()` and `equals()`. 

However, based on the [Android SDK documentation](https://developer.android.com/reference/java/net/URL.html#equals(java.lang.Object)), this behavior has been fixed in **ICS 4.0 (API 14)**, and:

> **Minimum SDK Version** - Glide requires a minimum SDK version of **14** (Ice Cream Sandwich) or higher.

Does this mean it's okay to use `.load(URL)` inside the app, and there will be no performance issue?

**Comment by sjudd** [comment]
URL is deprecated because it may cause performance issues. If your testing shows that it's fine to use in your app, then feel free.

**Comment by malvinstn** [comment]
Thanks for the reply. Cheers!
