### ISSUE TITLE
question about synchronus image loading

### ISSUE THREAD

**Issue by thisd** [bumptech/glide#3364]
Hi, I have a question regarding sync image loading using Glide. I have read the documentation and it insists on that in order to use the feature I would have to put it in a background thread.

Though, what I am trying to do is wait for the image to be loaded into the Bitmap. Then, handle it from there. I have managed to accomplish this using loadImageSync() on Universal Image Loader. Though, I could not find a way to perform this in Glide.

The reason I want this is that I want to set the bitmap on an ImageView and if I was to use the normal async image loading, the image would flicker on change. So, what I want is to get the Bitmap and set it on the ImageView directly.

I have used SimpleTarget as target but since the call is async the rest of my code is carried out.

Any information is appreciated.

Edit: I am not downloading the image I need. I am using a content URI to acquire it from the MediaStore.

**Comment by sjudd** [comment]
Are you asking if it's possible to load an image on the main thread? If so the short answer is no. It's possible to work around the restrictions in Glide, but it will introduce jank and it's usually  not necessary.

For example if you're loading image A and then you want to switch to image B, but you don't want to see a placeholder in between, you can:
1. load image A
2. load image B with A as B's thumbnail

When you start the load for B, image A will be reloaded from memory synchronously and there will be no flash.

Your specific situation may vary.

**Comment by thisd** [comment]
Thank you for taking the time to reply to me, sjudd. I appreciate it. I decided to use UIL instead.
