### ISSUE TITLE
Glide creating a large cache

### ISSUE THREAD

**Issue by AkshayChordiya** [bumptech/glide#337]
Hi,

I tried Glide in my app which loads plenty of images, it worked fine but when I checked the Cache there had been a 74MB cache generated.
Moreover later the scrolling slowed a little.
How can I solve this problem ?

**Comment by sjudd** [comment]
Do you mean a disk cache, or memory cache? Where did you get the 74mb number?

Standard questions:

What version of Glide? What version of Android?

**Comment by AkshayChordiya** [comment]
@sjudd
I don't know which cache, but I got the 74MB number when I opened the "App Info" from "Settings"
I don't remember which version, but it do was old version maybe 2 versions before & Android version is Lollipop but it is appearing on other version like KitKat too.

Thank you

**Comment by sjudd** [comment]
Glide's default disk cache size is 250mb, which should be under the cache section in App Info. If you saw 74mb there, that's working as intended. If you'd prefer a smaller cache, you can use a [GlideModule][1], and [GlideBuilder#setDiskCache()][2] to set the cache size.

[1]: https://github.com/bumptech/glide/wiki/Configuration#including-a-glidemodule
[2]: 
https://github.com/bumptech/glide/issues/337#http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/GlideBuilder.html#setDiskCache(com.bumptech.glide.load.engine.cache.DiskCache.Factory)

**Comment by AkshayChordiya** [comment]
Got it, Thanks
