### ISSUE TITLE
Glide 4.8.0 - cannot use RequestBuilder#error(RequestBuilder)

### ISSUE THREAD

**Issue by ParticleCore** [bumptech/glide#3371]
Like many others I have tried to retry an image load in the `onLoadFailed` method of the `RequestListener` and ended up meeting the following error

`java.lang.IllegalStateException: You can't start or clear loads in RequestListener or Target callbacks. If you're trying to start a fallback request when a load fails, use RequestBuilder#error(RequestBuilder). Otherwise consider posting your into() or clear() calls to the main thread using a Handler instead.`

I have been trying for quite some time to implement the suggestion provided in the error message

![image](https://user-images.githubusercontent.com/9222661/47424234-bfdf5f00-d776-11e8-8c7a-c2c6afdbd737.png)

But for some reason it is impossible to instantiate a new `RequestBuilder` in order for me to use its `.error` method since it appears both of its constructors are protected.

![image](https://user-images.githubusercontent.com/9222661/47424421-2c5a5e00-d777-11e8-8dd9-4ea96a7ffdf3.png)

![image](https://user-images.githubusercontent.com/9222661/47424547-6d527280-d777-11e8-969b-d952b2bcfa34.png)

The documentation lacking any examples whatsoever does not help either.

Is this on purpose or is it being done incorrectly?

**Comment by sjudd** [comment]
Glide.with(context).load() returns a RequestBuilder.

You're expected to do something like:

```java
Glide.with(context)
  .load(url)
  .error(
    Glide.with(context)
      .load(fallbackUrl))
  .into(imageView);
```

**Comment by ParticleCore** [comment]
Would never have got there, thanks for the explanation.

**Comment by QDJdeveloper** [comment]
Now my requirement is that if the image loading fails within 10 seconds, I have to go all the way to load it.

**Comment by QDJdeveloper** [comment]
My requirement is that if the image loading fails, it should be loaded all the time in 10 seconds. How to solve this problem?
