### ISSUE TITLE
GlideApp is not recognizing as the documentation says, instead only Glide is working as before

### ISSUE THREAD

**Issue by msayanece** [bumptech/glide#3373]
As the documentation says...

> ImageView imageView = (ImageView) findViewById(R.id.my_image_view);
>   GlideApp.with(this).load("http://goo.gl/gEgYUd").into(imageView);

Here, GlideApp is not recognizing, whereas only Glide is working fine. 

I am using the following version of glide...
implementation 'com.github.bumptech.glide:glide:4.8.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'

I am using this in a Google map project

Need to change the documentation or there is a problem with the new version.

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/generatedapi.html#getting-started
