### ISSUE TITLE
Cache location different for each downloaded image

### ISSUE THREAD

**Issue by kroobroeck** [bumptech/glide#3374]
**Glide Version**: 4.8.0

**Integration libraries**: OkHttp 3.11.0

I want to integrate glide into an existing app. The app shows a lot of visual content. Thumbnails are downloaded into a specific folder structure based on the content is represents. As I do not want to enforce all my users to update all there content / thumbnails when I integrate Glide for image loading. I was wondering if Glide could be used as follows: "If the thumbnail doesn't exists in the folder structure, download it to the _specific folder_ and display it. Furthermore, renaming _(custom image name)_ of the saved thumbnail should also be possible."

I do understand that's actually a custom cache, but I was wondering if renaming and pinpointing each downloaded thumbnail to a possibly different location is possible with Glide and how I should tackle the issue.

**Comment by sjudd** [comment]
It's probably simplest to do the downloading yourself and write a custom ModelLoader for Glide that will load data (and/or do the downloading) from your folders: http://bumptech.github.io/glide/tut/custom-modelloader.html.

Glide's cache doesn't really give you enough information to do what you're trying to do. Neither the identifier for the cached image nor the options used to load it (ie is it transformed or not) is readily available in the data given to the disk cache.

A custom ModelLoader and your own download logic will give you a lot more control and readability. 

Renaming isn't really something that Glide will help you with one way or another.
