### ISSUE TITLE
error: cannot find symbol class DataBindingComponent

### ISSUE THREAD

**Issue by nglro** [bumptech/glide#3380]
**Glide Version**:
4.8.0
4.9.0-SNAPSHOT

**Integration libraries**:
implementation 'com.github.bumptech.glide:okhttp-integration:4.8.0'
implementation 'com.github.bumptech.glide:okhttp-integration:4.9.0-SNAPSHOT'

**Device/Android Version**:
app doesn't build, so no device

**Issue details / Repro steps / Use case background**: 
I was using glide 3.7 and wanted to update to 4.8.
using 
`dataBinding {
	enabled = true
}`
with glide 4.8 causes java compiler to throw "error: cannot find symbol class DataBindingComponent" for every binding class generated. Searching online only finds answers related to kotlin, I am using Java.

Reverting to glide 3.8 allows me to build successfully.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with( image.getContext() )
			 .load( path )
			 .into( image );
```

**Stack trace / LogCat**:
```ruby
error: cannot find symbol class DataBindingComponent
```

**Comment by natario1** [comment]
You should add

```
kapt { // Source: https://github.com/google/dagger/issues/306
    javacOptions {
        option("-Xmaxerrs", 1000)
    }
}
```

to your build file, so you can see the real error at the end of these fake DataBinding errors.

**Comment by nglro** [comment]
Thank you for your answer. Unfortunately my error count is not that big, so this solution is not helping me find the real cause of the problem. I only get 29 errors for 29 classes generated by DataBinding, and they all have the same error.

I will use 3.8 for now, because I am time pressed with this project, but I will try to find out more when I get some free time. 

I was hoping someone else encountered this problem before.
