### ISSUE TITLE
Getting the file extension from cached file 

### ISSUE THREAD

**Issue by natario1** [bumptech/glide#3381]
Using this line to load a previously cached image:

```kotlin
val future = GlideApp.with(this)
                .download(viewModel.url)
                .submit()
val file = future.get()
```

The returned file has a path like `app/cache/image_manager_disk_cache/<RANDOM_KEY>.0` . Is there any way to get the file extension / mime type (other than inspecting viewModel.url)? Can I use different request options in order to get this information?

**Comment by sjudd** [comment]
Nope, the filepath you get back doesn't include mime type or an extension and there's no way to get it without reading the file header. There are no options available to change this.
