### ISSUE TITLE
I would like to ask 4.8.0 about "SimpleTarget" and "ViewTarget.

### ISSUE THREAD

**Issue by qianshengta** [bumptech/glide#3385]
**Glide Version**:
4.8.0

**Integration libraries**:
   Glide                                  : 'com.github.bumptech.glide:glide:4.8.0',
   GlideCompiler                    : 'com.github.bumptech.glide:compiler:4.8.0',
   GlideOkHttp3                     : "com.github.bumptech.glide:okhttp3-integration:4.8.0",
   GlideTransformations         : 'jp.wasabeef:glide-transformations:3.1.1',

**Device/Android Version**:
null

**Issue details / Repro steps / Use case background**: 
I saw a sentence like "Deprecated SimpleTarget and ViewTarget, see the CustomViewTarget description in Features in these release notes for more detail."Does this mean that after 4.8.0, SimpleTarget and ViewTarget are abandoned and replaced by CustomViewTarget?And I couldn't find CustomTarget in 4.8.0, so I could only find CustomViewTarget.But the "CustomTarget" can be found in the source code you download.
What happens if I don't make the changes?You know, people are always lazy about change.The following code is my use of Target.The goal is to get the size of the image before loading it, and then calculate a scale or zoom scale based on the width of the screen to modify the size of the image.
![tfo cw j6pvwd v0biwzg](https://user-images.githubusercontent.com/29747624/47832980-6957cd80-ddd3-11e8-93a9-586694770243.png)
![chxj5_n dm3e3t 9f4vcm](https://user-images.githubusercontent.com/29747624/47832982-6957cd80-ddd3-11e8-84a9-95f083f03dde.png)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```
  GlideApp.with(baseActivity)
                .asBitmap()
                .load(item)
                .placeholder(R.mipmap.ic_default_img_small_corners)
                .fallback(R.mipmap.ic_fail_img_small_corners)
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<?
                            super Bitmap> transition) {
                     
                        int width = resource.getWidth();
                        int height = resource.getHeight();
           
                        float scale = ((float) ScreenUtils.getScreenWidth()) / width;
   
                        Matrix matrix = new Matrix();
                        matrix.postScale(scale, scale);
  
                        Bitmap newbm = Bitmap.createBitmap(resource, 0, 0, width, height, matrix,
                                true);
                        imageView.setImageBitmap(newbm);
                    }

                });
```

**Layout XML**:
null

**Stack trace / LogCat**:
null

**Comment by qianshengta** [comment]
+1

**Comment by Mithrandir21** [comment]
+1

**Comment by sjudd** [comment]
For `CustomTarget`, see https://github.com/bumptech/glide/issues/3304. 

All deprecated code in Glide will eventually be removed. SimpleTarget is going to take a while because it's used so frequently.

The main point of deprecating SimpleTarget is to warn you about the ways in which it tempts you to break Glide's API contract. Specifically it doesn't do anything to force you to stop using any resource you've loaded once the SimpleTarget is cleared, which can lead to crashes and graphical corruption.
