### ISSUE TITLE
skia: ------ png error IDAT: CRC erro

### ISSUE THREAD

**Issue by jushenziao** [bumptech/glide#3387]
When I try to load images with Glide，I got this error :skia: ------ png error IDAT: CRC erro .But picaso works good。I guess the original image was changed by the server，but  does not recalculate the CRC of the file. How can I continue to use Glide in this case?

**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by jushenziao** [comment]
version 4.6 is ok.

**Comment by 1976222027** [comment]
当我尝试用Glide加载图片，我得到了这个错误：skia: ------ png error IDAT: CRC erro 。我猜原始图像被服务器更改了，但没有重新计算文件的 CRC。在这种情况下，如何继续使用 Glide？
