### ISSUE TITLE
onResourceReady "from"

### ISSUE THREAD

**Issue by farfromrefug** [bumptech/glide#339]
Hi,

Is there a way to know in onResourceReady if the drawable was loaded from disk/cache/network ? just like picasso does.
This is very practical to only animate new drawable when coming from network (in listview).

Thanks

**Comment by sjudd** [comment]
Looks like this is a duplicate of #108 

We may not get to everything @TWiStErRob listed in that bug, but we should be able to show local/remote/disk cache/memory cache at least.

**Comment by farfromrefug** [comment]
Sorry missed the other ticket!
