### ISSUE TITLE
集成错误

### ISSUE THREAD

**Issue by yuanmaio** [bumptech/glide#3390]
Error:(50, 5) error: style attribute 'attr/colorAccent (aka com.example.ym.myapplication:attr/colorAccent)' not found.
Error:(50, 5) error: style attribute 'attr/colorPrimary (aka com.example.ym.myapplication:attr/colorPrimary)' not found.
Error:resource style/Theme.AppCompat.Light.DarkActionBar (aka com.example.ym.myapplication:style/Theme.AppCompat.Light.DarkActionBar) not found.
D:\project1\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Error:(50, 5) error: style attribute 'attr/colorPrimaryDark (aka com.example.ym.myapplication:attr/colorPrimaryDark)' not found.
C:\Users\ym\.gradle\caches\transforms-1\files-1.1\support-compat-27.1.1.aar\1927b7f72d3b9b65d4fd15f9406f4447\res\values\values.xml
Error:(213) style attribute 'attr/colorPrimary (aka com.example.ym.myapplication:attr/colorPrimary)' not found.
Error:(214) style attribute 'attr/colorPrimaryDark (aka com.example.ym.myapplication:attr/colorPrimaryDark)' not found.
Error:(215) style attribute 'attr/colorAccent (aka com.example.ym.myapplication:attr/colorAccent)' not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

**Comment by yukuoyuan** [comment]
你解决了?哥们

**Comment by yukuoyuan** [comment]
dependencies {

    ...

    implementation("com.github.bumptech.glide:glide:$glideVersion") {
        exclude group: "com.android.support"
    }
    annotationProcessor "com.github.bumptech.glide:compiler:$glideVersion"
}
可以解决你的问题
