### ISSUE TITLE
CircularProgressDrawable not animating, first time

### ISSUE THREAD

**Issue by matanshukry** [bumptech/glide#3392]
**Glide Version**: 4.8.0
**Integration libraries**: retrofit2-2.4.0 (which uses okhttp3-3.10.0
**Device/Android Version**: Emuleator-Android 9, API 28

**Issue details / Repro steps / Use case background**: 
I'm trying to use CircularProgressDrawable as a placeholder (i don't have error() or fallback() drawables yet). Also, the problem happens when calling .load() with null.

The drawable is on the imageview, but it doesn't animate (I put a breakpoint and it seems the animator is actually running, but the imageview it self is not drawing/invalidating.. I hope it helps somehow)

Also, if I go to different fragment and back, the same placeholder in the same imageview now works fine.

p.s.
I'm calling .start() on the animation, but who's calling .stop()? I'm not 100% sure, but after a bit of debugging I think they are always running, even after they are removed from the ImageView. Is there any hook I can call .stop() my self? like .onDrawableRemoved() or something like that? (I couldn't find any in the docs / google)

p.s.2
I try to replicate the same behavior using simple .setDrawable() without using glide; tried various lines with .setDrawable(null) and then .setDrawable(placeholder) (which I noticed it's what Glide's doing), but it always worked when not using Glide.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

GlideModule:
```java
    override fun applyOptions(context: Context, builder: GlideBuilder) {
        builder.setDefaultRequestOptions(
            RequestOptions()
                .placeholder(createPlaceholder(context))
        )
    }

        fun createPlaceholder(context: Context) = CircularProgressDrawable(context).also {
            it.strokeWidth = 5f
            it.centerRadius = 30f
            it.start()
        }
```

load line (item.photo is null):
```java
        GlideApp.with(holder.image)
            .load(item.photo)
            .into(holder.image)
```

**Layout XML**:
```xml
    <ImageButton
        android:id="@+id/item_image"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_marginEnd="4dp"
        android:layout_marginRight="4dp"
        android:background="@drawable/layout_border"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

**Stack trace / LogCat**:
```ruby
"W/Glide: Load failed for null with size [0x0]"
```

**Comment by matanshukry** [comment]
bumping just to wait for a response? ...

**Comment by sjudd** [comment]
Are you loading into multiple different views with different images? Or just one view?

If it's multiple views, then the Drawable's state is being mutated by multiple views at once. Create a different copy per request.

**Comment by matanshukry** [comment]
> t views

Well it works for the 2nd time (go back to another fragment then back), even with multiple views, so I don't think it's that. But even if so - how can I do that without calling .placeholder() in any line (hence make it global) ?

**Comment by mochadwi** [comment]
Any updates @matanshukry?

I've a similar approach to yours. I also want to make the CircularProgressDrawable as a global, without adding it on every `GlideApp`.

**Comment by mochadwi** [comment]
> I'm calling .start() on the animation, but who's calling .stop()? I'm not 100% sure, but after a bit of debugging I think they are always running, even after they are removed from the ImageView. Is there any hook I can call .stop() my self? like .onDrawableRemoved() or something like that? (I couldn't find any in the docs / google)

Well, I think with `Glide 4.9.0` now we can configure `GlideBuilder#addGlobalRequestListener()` inside our `AppGlideModule` for the generated APIs. 

E.g:

**MyAppGlideModule.kt**
```
@GlideModule
class MyAppGlideModule : AppGlideModule() {
    // TODO(mochadwi): 2020-01-03 The placeholder for CircularProgressDrawable sometimes not shown when loading the image
    //  currently there's a downsampling error if placeholder activated without .override(Int, Int),
    //  see here: https://github.com/bumptech/glide/issues/4031
    override fun applyOptions(context: Context, builder: GlideBuilder) {
        builder.apply {
            val requests = RequestOptions().placeholder(context.getCircularProgressDrawable())

            setDefaultRequestOptions(requests)

            val progress = requests.placeholderDrawable as CircularProgressDrawable

            addGlobalRequestListener(makeLoadingRequestListener(
                    failedAction = { progress.stop() }, readyAction = { progress.stop() }
            ))
        }
    }
}
```

**LoadingListener.kt**
```
inline fun <T : Any> makeLoadingRequestListener(
        crossinline failedAction: (String) -> Unit,
        crossinline readyAction: (String) -> Unit
): RequestListener<T> = object : RequestListener<T> {
    override fun onLoadFailed(e: GlideException?, model: Any?, target: Target<T>?, isFirstResource: Boolean): Boolean {
        failedAction.invoke("${e?.message}")
        return false
    }

    override fun onResourceReady(resource: T, model: Any?, target: Target<T>?, dataSource: DataSource?, isFirstResource: Boolean): Boolean {
        readyAction.invoke("$dataSource")
        return false
    }
}
```

So with this, we can stop the progress. cc @matanshukry

**Comment by Umair-Syed** [comment]
I had the same issue. I stored CircularProgressDrawable in a variable and then used that variable in the glide placeholder, but that didn't work. When @sjudd pointed. I did something like this:

`Glide.with(requireContext())
                        .load(Uri.parse(imageUri))
                        .placeholder( CircularProgressDrawable(requireContext()).apply {
                            strokeWidth = 8f
                            centerRadius = 40f
                            setColorSchemeColors(ResourcesCompat.getColor(resources, R.color.colorAccent, null))
                            start()
                        })
                        .error(R.drawable.ic_baseline_broken_image)
                        .into(view)`
Now it works, but I don't know if it has any performance impact if there are large no. of images.
