### ISSUE TITLE
Load failed for url with size

### ISSUE THREAD

**Issue by KimiChiu** [bumptech/glide#3394]
**Glide Version**: 4.8.0
**Integration libraries**: okhttp
**Device/Android Version**: emulator

**Issue details / Repro steps / Use case background**: 

Load failed for https://i.imgur.com/k0XiN9N.jpg with size [1080x788]
class com.bumptech.glide.load.engine.GlideException: Failed to load resource

I've used ` adb shell setprop log.tag.Glide VERBOSE` and `builder.setLogLevel(Log.VERBOSE);` but that's all, no more messages.

This happens when my app tries to load bunch of images at once, such as 20 images in a `RecyclerView` and user scrolls it forward and backward multiple times alternatively.
After then, you have to wait a long time(let's say 5 minutes) to make it works again.
Just like the requests still running in the background which were not canceled at all.

I've tried to add `GlideApp.with(fragment).clear(imageViewTarget);` but still not worked.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(fragment)
    .load(link)
    .forImagePreview()
    .into(imageViewTarget);
```

**Stack trace / LogCat**:
```ruby
Load failed for https://i.imgur.com/k0XiN9N.jpg with size [1080x788]
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

**Comment by KimiChiu** [comment]
Looks like `GlideApp.with(fragment).clear(imageViewTarget);` is only marking this request as canceled and prevent further processing rather than actually cancel the request.
Is there a way to really stop the requests?

**Comment by wahdatjan** [comment]
any solutions to this issue?

**Comment by iamnovaprince** [comment]
Got same error, Anyone got any slution ??
