### ISSUE TITLE
onLoadStarted() not working in Glide 4.8.0 & not loading any images from URL

### ISSUE THREAD

**Issue by HitaarthVaidya** [bumptech/glide#3397]
I'm using Glide 4.8.0 for my Android Project. And using it with RecyclerView & calling it inside onBindViewHolder() method
like this :   

Glide.with(mContext).load(imgUrl).into(holder.userImageView).onLoadStarted(placeholderDrawable);

So with the above code no images are loading inside the recycler view but as soon as i remove .onLoadStarted(placeholderDrawable) all images shown up as per the desired output but the place holder i want till the actual images got load into the imageview, that is not happening.
Please help me.
Thank you

**Comment by anushreeag** [comment]
Hi, Is this issue resolved for you? I am facing the same problem .
