### ISSUE TITLE
Kotlin Unresolved reference: submit

### ISSUE THREAD

**Issue by panhongjin** [bumptech/glide#3400]
in building processing catch the exception:
 Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.chinamobile.andfinance.library.imageload.GlideRequests, unresolved supertypes: com.bumptech.glide.RequestManager
    class com.chinamobile.andfinance.library.imageload.GlideRequest, unresolved supertypes: com.bumptech.glide.RequestBuilder

e: D:\workspace\AndFinanceOne\app\src\main\java\com\chinamobile\andfinance\ui\webview\BaseWebPresenter.kt: (71, 91): Unresolved reference: submit

my code is 
val bitmap = GlideApp.with(AndApplication.mContext).asBitmap().load(imageUrl).submit().get()

**Comment by TWiStErRob** [comment]
Are you using `kapt` or `annotationProcessor`?

**Comment by panhongjin** [comment]
using kapt
