### ISSUE TITLE
Not able to retrieve image from Fire base database using glide.

### ISSUE THREAD

**Issue by asifbhat184** [bumptech/glide#3410]
I am using Firebase for simple chatApp .I am able to send and receive text messages.
But when i try to share photo messages,they get stored in firebase storage,there URL's can be seen in Firebase database but i am not able to see them back on my device.

**Glide Version**:
 implementation 'com.github.bumptech.glide:glide:4.8.0'

**Integration libraries**:

**Device/Android Version**:
Moto G 5s/8.1.0

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
boolean isPhoto = message.getPhotoUrl() != null;
        if (isPhoto) {
            Log.d("MessageAdapter","isPhoto");
            messageTextView.setVisibility(View.GONE);
            photoImageView.setVisibility(View.VISIBLE);
            Glide.with(photoImageView.getContext())
                    .load(message.getPhotoUrl())
                    .into(photoImageView);
           // Log.d("MessageAdapter","isPhoto--");
        } else {
            messageTextView.setVisibility(View.VISIBLE);
            photoImageView.setVisibility(View.GONE);
            messageTextView.setText(message.getText());
        }
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:layout_marginLeft="@dimen/activity_horizontal_margin"
              android:layout_marginStart="@dimen/activity_horizontal_margin"
              android:orientation="vertical">

    <ImageView
        android:id="@+id/photoImageView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true" />

    <TextView
        android:id="@+id/messageTextView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_weight="0"
        android:textAppearance="?android:attr/textAppearanceLarge"
        tools:text="Message" />

    <TextView
        android:id="@+id/nameTextView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_weight="0"
        android:textAppearance="?android:attr/textAppearanceSmall"
        tools:text="Name" />

</LinearLayout>
```
 

**Stack trace / LogCat**:
```13:07:17.670 31055 31055 W Glide   : Load failed for com.google.android.gms.tasks.zzu@35f85f2 with size [984x1776]
11-17 13:07:17.670 31055 31055 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
11-17 13:07:17.670 31055 31055 W Glide   : There were 3 causes:
11-17 13:07:17.670 31055 31055 W Glide   : java.io.FileNotFoundException(/com.google.android.gms.tasks.zzu@35f85f2 (No such file or directory))
11-17 13:07:17.670 31055 31055 W Glide   : java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
11-17 13:07:17.670 31055 31055 W Glide   : java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
11-17 13:07:17.670 31055 31055 W Glide   :  call GlideException#logRootCauses(String) for more detail
11-17 
```

**Comment by amankr** [comment]
I am facing similar issue 

```
Failed to load resource There were 3 causes: 
java.io.IOException(File unsuitable for memory mapping) java.io.FileNotFoundException(/data/user/0/in.mohalla.sharechat/cache/image_manager_disk_cache/c21c8db5a2b6b3688e8cd41c176ebd66d3f0c381ee814e8eea8110b35cdbd87e.0: open failed: ENOENT (No such file or directory)) 
java.io.FileNotFoundException(No such file or directory) 

call GlideException#logRootCauses(String) for more detail

#####

 Failed to load resource There were 3 causes: 
java.io.FileNotFoundException(/null: open failed: ENOENT (No such file or directory)) java.io.FileNotFoundException(No such file or directory) 
java.io.FileNotFoundException(No such file or directory) call GlideException#logRootCauses(String) for more detail
```

Mostly occurring on specific set of devices
Samsung : J2, J5, J7 -  ( 52 %  of total crashes)
Xiaomi : Redmi 5A, Redmi Note 4, Redmi 4, Redmi 6A ( 28 % of total crashes )
Vivo devices . ( 5 % )
Lenovo devices ( 3 %)

This issue was extremely frequent on these devices when I  was using `setDiskCache` option in `AppGlideModule` to set different disk cache size . After I removed it crashes reduced
 - can't figure out reason for this

This works fine when we load only from network using set `DiskCacheStrategy.NONE`

**Comment by asifbhat184** [comment]
hi @amankr 

I changed my code to this.

Glide.with(photoImageView.getContext())
                    .load(message.getPhotoUrl())
                    .apply(RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.NONE))
                    .into(photoImageView);

Still its not working properly.

**Comment by holoduke** [comment]
We are getting these kind of errors on all possible Xiomi devices:
We don't see any issues with images not being loaded though. Just a lot of console errors (not crashing the app).
It happens with all png's and jpg's loaded from a static cdn.


W/Glide: Load failed for null with size [110x55]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 3 causes:
    java.io.FileNotFoundException(/null (No such file or directory))
    java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
    java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(/null (No such file or directory))
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(/null (No such file or directory))
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: /null (No such file or directory)
      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)

**Comment by mosofsky** [comment]
I've also encountered this problem while trying the Google Firebase tutorial (https://classroom.udacity.com/courses/ud0352/lessons/fab5bf81-cfe5-4071-9afe-b6eb324a6257/concepts/27c52d47-50cd-4be1-8d3d-95e3fccebda5)

What I'm seeing is that the URL in the exception does match the URL the message points to but the Google Firebase Storage indicates the photo has a different style of URL.  I'm not sure if they're supposed to be equivalent URLs.  Maybe this is not a bug in Glide but rather Firebase Storage giving us the wrong URL?

**Exception:**
https://firebasestorage.googleapis.com/v0/b/friendlychat-6980b.appspot.com/o?name=chat_photos%2F702250842&uploadType=resumable&upload_id=AEnB2UoswkAg6RPldn_q-JEDZPff46QU3s6RZr-Jhz-eIOB3R4nhUsiF1ABqnpg9ov5-yxYWvBfxeiPlwpjcJ3btWjUOPzfGxA&upload_protocol=resumable

**Message database has this pointer:**
"https://firebasestorage.googleapis.com/v0/b/friendlychat-6980b.appspot.com/o?name=chat_photos%2F702250842&uploadType=resumable&upload_id=AEnB2UoswkAg6RPldn_q-JEDZPff46QU3s6RZr-Jhz-eIOB3R4nhUsiF1ABqnpg9ov5-yxYWvBfxeiPlwpjcJ3btWjUOPzfGxA&upload_protocol=resumable"

**Storage database says the image has this URL:**
https://firebasestorage.googleapis.com/v0/b/friendlychat-6980b.appspot.com/o/chat_photos%2F702250842?alt=media&token=6efb56fc-c0e3-40f7-8b08-ff8aa4d8d6ec

**Comment by Kiranaz** [comment]
> We are getting these kind of errors on all possible Xiomi devices:
> We don't see any issues with images not being loaded though. Just a lot of console errors (not crashing the app).
> It happens with all png's and jpg's loaded from a static cdn.
> 
> W/Glide: Load failed for null with size [110x55]
> class com.bumptech.glide.load.engine.GlideException: Failed to load resource
> There were 3 causes:
> java.io.FileNotFoundException(/null (No such file or directory))
> java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
> java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
> call GlideException#logRootCauses(String) for more detail
> Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
> There was 1 cause:
> java.io.FileNotFoundException(/null (No such file or directory))
> call GlideException#logRootCauses(String) for more detail
> Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
> There was 1 cause:
> java.io.FileNotFoundException(/null (No such file or directory))
> call GlideException#logRootCauses(String) for more detail
> Cause (1 of 1): class java.io.FileNotFoundException: /null (No such file or directory)
> Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL
> There was 1 cause:
> java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
> call GlideException#logRootCauses(String) for more detail
> Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
> There was 1 cause:
> java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
> call GlideException#logRootCauses(String) for more detail
> Cause (1 of 1): class java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
> Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL
> There was 1 cause:
> java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
> call GlideException#logRootCauses(String) for more detail
> Cause (1 of 1): class java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)

I'm having the same issue my Xiomi device that images stored in firebase realtime database are not being rendered.. Is it actually device issue?
