### ISSUE TITLE
GIF from content uri is loaded as a still image

### ISSUE THREAD

**Issue by natario1** [bumptech/glide#3419]
**Glide Version**: 4.8.0

**Issue details / Repro steps / Use case background**: 
Getting content URIs from a content resolver query and passing the uri string to Glide. When the media file is a GIF, Glide is displaying a still image. 

```java
Glide.with(context).load("content://media/external/images/media/147876").into(view)
```

**Comment by natario1** [comment]
Strangely if I add `.diskCacheStrategy(DiskCacheStrategy.NONE)` the GIF is correctly displayed as GIF. What is happening?

I could clean my cache and see if it's solved but I would like to get your opinion first, in case this is a bug that it's hard to reproduce later.

FWIW `DefaultImageHeaderParser().getType(contentResolver.openInputStream(uri))` correctly returns a gif type.

**Comment by Mouadabdelghafouraitali** [comment]
Try to add ` .asGif()` if you want display GIF as GifDrawable

```
 Glide.with(getApplicationContext()).asGif()
                .load(uri)
                .listener(new RequestListener<GifDrawable>() {
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<GifDrawable> target, boolean isFirstResource) {

                        return false;

                    }

                    @Override
                    public boolean onResourceReady(GifDrawable resource, Object model, Target<GifDrawable> target, DataSource dataSource, boolean isFirstResource) {
                        return false;
                    }
                }).into(ImageView);
```

also if you want it as byte 

```
 Glide.with(getApplicationContext())
                        .as(byte[].class)
                        .load(uri)
                        .apply(requestOptions)
                        .into(new CustomTarget<byte[]>() {
                            @Override
                            public void onResourceReady(@NonNull byte[] resource, @Nullable Transition<? super byte[]> transition) {

                            }

                            @Override
                            public void onLoadCleared(@Nullable Drawable placeholder) {

                            }
                        });
            }
```

**Comment by sjudd** [comment]
Things like this have happened before when people were developing and managed to return only a still or a partial image that was subsequently cached in Glide.

If you were working on the content provider and may have ever returned a still image that Glide could have cached, that probably explains the issue.

I'm not aware of other cases where a GIF Glide could decode ends up cached as a still image (unless you're using asBitmap()).
