### ISSUE TITLE
Correct support-v4 version in README

### ISSUE THREAD

**Issue by anticafe** [bumptech/glide#342]
I see in your [README#Download](https://github.com/bumptech/glide#download), you told us to include `com.android.support:support-v4:19.1.0` in dependencies. But as I remember correctly, latest version of `com.android.support:support-v4` is `21.0.3`.

Should we correct it?

**Comment by sjudd** [comment]
I believe we're limited to 19.1 because we compile with Java 6 and 21.x is compiled with Java 7. We're already compiling with Java 7 in Glide 4 which should be the next major release, so hopefully this isn't a huge issue.

**Comment by anticafe** [comment]
Got it.
BTW, refer to https://github.com/bumptech/glide/issues/110 (Compile against java 7)
