### ISSUE TITLE
Disable saving as JPG (i.e. force saving as PNG) v3.5.1

### ISSUE THREAD

**Issue by alex2069** [bumptech/glide#343]
We're getting some pretty bad JPG artefacts when loading from cache.
I've determined that the cached images are being saved as JPG format, however I'm unable to determine how to correctly force saving as PNG.
I saw issue #63 and #64 that allowed for this, but it seems this is not longer valid for v3.5.1.

From what I've been able to determine I need to create a <code>BitmapEncoder</code> with <code>Bitmap.CompressFormat.PNG</code>, pass that to <code>StreamBitmapDataLoadProvider</code>, and register it with <code>dataLoadProviderRegistry</code>:
<code>dataLoadProviderRegistry.register(InputStream.class, Bitmap.class, streamBitmapLoadProvider);</code>

However <code>dataLoadProviderRegistry</code> is private, doesn't have a getter, and doesn't accept any input from the builder.
I figured as a quick workaround I could just use reflection during <code>registerComponents</code> to register my own sub-class of <code>StreamBitmapDataLoadProvider</code> and provide my own <code>BitmapEncoder</code>, however during construction of the original <code>dataLoadProviderRegistry</code>, the inputs are cascaded down through <code>ImageVideoDataLoadProvider</code> and <code>ImageVideoGifDrawableLoadProvider</code>. Thus to properly fix it I'd need to effectively copy that entire block providing my <code>BitmapEncoder</code> from the start.

Please tell me I'm stupid and missed something really obvious lol.
<br />
<hr>
As an aside, I think defaulting to a lossy format is a terrible idea. Most people wouldn't expect their disk cache to change what they see coming from the server. Disk space is rarely an issue these days, and for those users that it is, they can clear their app cache or whatever when they need to. Can you imagine what would happen if you tried to save a bitmap on a web browser and what you got was a degraded copy?

Having said all that our app has a huge amount of high-res photographic artwork, but also a lot of logos (where JPG compression artefacts are prevalent and very noticeable). I suspect it's possible (though non-trivial) to register custom models/loaders to save as JPG for some resources, but PNG for others? To be honest I doubt I'll bother but would probably consider it if it was simple. In an ideal world there'd be a way to check for a uniform compression complexity and use PNG appropriately - though this is probably a bit excessive heh.

**Comment by TWiStErRob** [comment]
Try:
```
.diskCacheStrategy(DiskCacheStrategy.SOURCE)
```

I disagree with you, I have an S4. 16GB advertised, 9GB real, I run into space issues every week. I only have Plants vs Zombies and Family Guy, the other apps are small(ish), no space for media at all! I looked into family guy for example. They have the original compressed image, the uncompressed texture and a png version of the texture. All these at 4x which is huge so a little icon I can't even see properly takes up a lot of space. This is just plain ignorance. Glide is mostly used for thumbnails which needn't be HQ, hence the JPG default. If you want to download HQ that is already well compressed on the server so you only need to download it and display. Saving the downscaled version in cache may not gain you much, especially if it's saved as PNG -> my code suggestion. JPG `inSampleSize` will load it easier than from PNG. - *another Glide user*

*I like seeing an informed, detailed report like this: * pat on the back *!*

**Comment by alex2069** [comment]
My understanding is that <code>DiskCacheStrategy.SOURCE</code> will not cache transformations (http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/load/engine/DiskCacheStrategy.html#SOURCE), which is not a good fix in this case. We use a lot a reasonably heavy transformations that are ideal for caching. e.g. There is a view pager with a blurred background that cross-fades to the next page etc when swiping. Swiping back and forth is nice and quick and smooth due to the caching, which would be unfortunate to lose.

It's interesting you mention having space issues (I have many GB free on my Nexus 4 so I guess it never really cross my mind), but there have been a couple of reports of space issues (prior to Glide where we used a custom cache that failed when device was full - oops). It might be interesting to see some analytics of our user base on how much free space users generally have (assuming we can get that kind of info without additional permissions).

Regarding the <code>inSampleSize</code>, do you have any evidence or articles substantiating this? After adding my gross reflection fix I thought I'd noticed decreased fast scroll performance, but dismissed it thinking it was just testing hiccups. It'd be a shame if this was the case (though in the end it's still orders of magnitude more performant than what Picasso was).

**Comment by TWiStErRob** [comment]
I don't have evidence, Sam is always saying JPEG reading is more optimised, and I believe him...

You can read free space through `File.getFreeSpace` and you must have permission to do so since you using a file cache.

Just realized, do you see jpeg artifacts or 565 banding? Maybe you need to force 24 bit color, which is only available as 8888 so there's alpha, which in turn may be the answer to your hack. Since alpha can only be saved in PNG to cache!

I think Sam will give you a better answer, in the meantime see `DecodeFormat`.

**Comment by sjudd** [comment]
There are two separate options that are both going to play a role here:

1. DecodeFormat

    I'd highly recommend trying [``DecodeFormat.ALWAYS_ARGB_8888``][1] if you're concerned about quality. It's easy to set globally (unlike compression format) and in the past it's made a substantial difference for users experiencing issues with artifacts. See the [configuration wiki page][2] for details on how to set decode format. 


    RGB_565 is a 16 bit format that drops no only the alpha channel, but also a number of bits for each color which has a tendency to result in banding. ARGB_8888 is a 32 bit format that includes both alpha and a full 8 bits for each color. As a result ARGB_8888 provides higher quality at the cost of 2x memory usage per pixel.

2. Compression format

    @TWiStErRob Now that you mention it I have only anecdotal evidence that JPEG is faster to decode, it's possible I'm actually not correct about decode times. However, I have experienced first hand that PNG can be an order of magnitude slower to encode than JPEG. Since Glide both decodes and encodes resources (using DiskCacheStrategy.RESULT/ALL) before returning the result to the requestor, encode time still has an affect on performance.

    @alex2069 By default Glide does make an attempt to choose between PNG and JPEG. If we think a Bitmap has alpha, we use PNG, otherwise JPEG. We use a reasonably high compression quality (90 by default) for JPEGs in the hopes of reducing artifacts from re-compression. It's possible that isn't sufficient, but this would the first case I've heard of where compression format, not DecodeFormat, was to blame.

    All that said, it is possible to set the compression format, but you need to replace the ResourceEncoder used for Bitmaps to do so. It's easier with BitmapRequestBuilder than with DrawableRequestBuilder, so if you're ok loading Bitmaps you can do something like this:

```java
Glide.with(fragment)
    .load("url")
    .asBitmap()
    .encoder(new BitmapEncoder(Bitmap.CompressFormat.PNG), 100))
    .into(view);
```

    You can also replace the encoder with DrawableRequestBuilder, but it requires more wrapping.

Setting an encode format will be easier in Glide 4.0. You can see the [discussion in the design doc][3], or check out the [option in the 4.0a branch][4].




[1]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/load/DecodeFormat.html#ALWAYS_ARGB_8888
[2]: https://github.com/bumptech/glide/wiki/Configuration#bitmap-format
[3]: https://docs.google.com/document/d/13jhhlAqcKU2kweY2PlKW8HMPgTxXvu3Qv8A8dPBJP0Q/edit#heading=h.wbyripmy6tq7
[4]: https://github.com/bumptech/glide/blob/4.0a/library/src/main/java/com/bumptech/glide/request/RequestOptions.java#L117

**Comment by alex2069** [comment]
I tried using <code>DecodeFormat.ALWAYS_ARGB_8888</code> to no avail. The images that are affected are typically corporate logos (so text on solid backgrounds - the artefacts were absolutely terrible and blindingly obvious). User logos were usually fine since they're typically just photos.

A quick Google image search for an example of just how bad it was showing through (random unaffiliated image): http://sitepointstatic.com/graphics/jpeg_artifacts.png - it was worse than that for some logos with lots of straight edges etc.

I'm not really keen on adding a <code>.encoder</code> call everywhere in the app that needs it so I'll probably just stick with the reflection fix (gross, but globally applied). It'd be too easy for an uninformed developer to miss adding it and the designers can get pretty pissy when things don't look pixel-perfect heh.

I had read a bit about the v4 design yesterday and it looked promising, but I'd be hesitant to use pre-release libraries in this particular app. Thanks both for your help - keep up the awesome work. Absolutely love the performance and memory improvements this library brings.

**Comment by bubbleguuum** [comment]
PNG decoding is at least 10x slower than JPG (software vs hardware decoding). PNG really should never be used unless transparency or lossless compression is required.

**Comment by alex2069** [comment]
Do you have anything to support that?
I'm genuinely interested in some statistics on the issue. I'm tempted to do it myself but it's not a real priority at the moment and PNG seems to be working fine.

**Comment by bubbleguuum** [comment]
@alex2069  Long time ago I benchmarcked JPG vs PNG decompression and this is the basis of my assertion. 
It's very easy to test yourself.

**Comment by sjudd** [comment]
This is much easier in v4, see: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/request/BaseRequestOptions.java#L355
