### ISSUE TITLE
some mobiles,CircleImageView first show black background,then the black background dismiss

### ISSUE THREAD

**Issue by aaironman** [bumptech/glide#3432]
implementation('com.github.bumptech.glide:glide:4.6.1') {
        exclude group: "com.android.support"
    }

code:
Glide.with(this)
                .load(mCentre.getAvatar())
                .apply(new RequestOptions()
                        .override(200, 200)
                        .placeholder(R.drawable.ic_personal_default_72dp)
                        .dontAnimate()
                        .signature(signature))
                .into(mUserHead);

xml:
 <com.xxxx.CircleImageView
            android:id="@+id/personal_center_userhead_iv"
            android:layout_width="@dimen/dip_79"
            android:layout_height="@dimen/dip_79"
            android:layout_centerHorizontal="true"
            android:layout_gravity="center_vertical"
            android:clickable="true"
            android:focusable="true"
            android:src="@drawable/ic_personal_default_72dp" />

![pic](https://user-images.githubusercontent.com/5567894/49205234-54c61f80-f3e9-11e8-95ba-16bca93d302b.png)

**Comment by aaironman** [comment]
mate10  Android8.0

**Comment by sjudd** [comment]
https://github.com/bumptech/glide#compatibility
