### ISSUE TITLE
Fatal signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by chernikowNikita** [bumptech/glide#3436]
Hello.
I use Glide to load images from server. (Glide version 4.3.0)
While running on Samsung SM-J530FM (Android Version 8.1.0) I get next stack trace:
W/Bitmap: Called getWidth() on a recycle()'d bitmap! This is undefined behavior!
    Called getHeight() on a recycle()'d bitmap! This is undefined behavior!
W/Bitmap: Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
W/Bitmap: Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
    Called getDensity() on a recycle()'d bitmap! This is undefined behavior!
    Called getConfig() on a recycle()'d bitmap! This is undefined behavior!
    Called getConfig() on a recycle()'d bitmap! This is undefined behavior!
A/Bitmap: Error, cannot access an invalid/free'd bitmap here!
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid ****** (), pid ****** ()
I don't call getDensity, getConfig, getWidth, getHeight, hasAlpha and recycle methods to bitmap
I ran into this problem with older version of Glide and updated it.
But it happens again.
Can you help me?

**Comment by Michael-Liu-2008** [comment]
same question!
