### ISSUE TITLE
Load a Image from an Url to an Image View

### ISSUE THREAD

**Issue by rk8339811** [bumptech/glide#3447]
**Glide Version**: 3.7.0

**Integration libraries**: Yes I use volley to work with an API

**Device/Android Version**: Tried it on an Tablet running on 5.0 & and Phone running on Android 7.0

**Issue details / Repro steps / Use case background**: 

I am developing an Android app for which I am working with an API.
The API is returning certain results such as an URL of an Image.
Since I have always been using Glide library to load offline and online images to an ImageView so for this also I am using the Glide Library. 
But the problem this time is that sometimes the url which is returned through an API is not returning an Image file but is returning a normmal file only. I mean that if I paste that url in an web browser then the file which is being downloaded is not in an Image form but just in an file form. Hence when I try to use that url with the Glide library it is not working.
But after downloading if I change the extension of the file to an image extension then the file is being opened properly as an image.
Any help on how a url which is returning a general file can be used to show an image would be really helpful.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context.getApplicationContext())
                .load(GetImageUrl())
                .asBitmap()
                .listener(new RequestListener<String, Bitmap>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {

                        return false;
                    }
                })
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .thumbnail(0.5f)
                .into(image);
```

**Comment by TWiStErRob** [comment]
Glide doesn't care about extension, it loads the byte stream returned by the server. If it's not an image then what do you want to load? Are you sure it really is a valid image file without extension? Can you provide an example url (live)?

**Comment by rk8339811** [comment]
@TWiStErRob Thanks for the answer. Really sorry as I won't be able to share the URL as required by the API provider. But since the chances of that kind of URL being returned by API is very less hence closing the issue. But would share in future if I face any such issue again. Thanks.

**Comment by iielse** [comment]
some url like this: https://graph.facebook.com/666830247115837/picture?width=512&height=512
