### ISSUE TITLE
Glide transforms doesn't work on error and placeholder resource drawable

### ISSUE THREAD

**Issue by ninad458** [bumptech/glide#3448]
**Glide Version**:4.7.1

**Integration libraries**:NA(reproduced the bug in a hello world app)

**Device/Android Version**: Doesn't look like version/device specific

**Issue details / Repro steps / Use case background**: replacing with invalid url will give error image but without the transformations

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this)
            .load("https://homepages.cae.wisc.edu/~ece533/images/airplane.png")
            .apply(
                RequestOptions().transforms(CenterCrop(), RoundedCorners(75))
                    .placeholder(R.drawable.ic_launcher_background)
                    .error(R.drawable.ic_launcher_background)
            )
            .into(image)
```

**Layout XML**:
```xml
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorAccent"
    tools:context=".MainActivity">

    <ImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintDimensionRatio="h,16:9"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:src="@tools:sample/avatars" />

</android.support.constraint.ConstraintLayout>
```

**Stack trace / LogCat**:
```ruby
I/Glide: Root cause (1 of 3)
    java.io.FileNotFoundException: /*https:/homepages.cae.wisc.edu*/~ece533/images/airplane.png (No such file or directory)
```

![screenshot_1544425849](https://user-images.githubusercontent.com/33372604/49716163-e13dd100-fc78-11e8-8c36-3267d934698d.png)
![screenshot_1544425855](https://user-images.githubusercontent.com/33372604/49716172-e733b200-fc78-11e8-959b-86ea80eb7921.png)

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/placeholders.html#are-transformations-applied-to-placeholders

**Comment by ninad458** [comment]
It would be nice for it have the transformation for placeholders as an option since it might not be practical to make a custom view everytime there is a change in the design, rounded corners to circular image for example. Also most of the time the placeholder is the app logo or app name with static background. It wouldn't be wise to create a separate image for each type of imageview.

**Comment by DeepanAndroid** [comment]
The actual image is resized based on placeholder image size when I use the placeholder. How do I resolve this issue?
