### ISSUE TITLE
Unable to load local image resources based on Locale

### ISSUE THREAD

**Issue by HalyangDream** [bumptech/glide#3451]
**com.github.bumptech.glide:glide:4.7.1**:

**com.github.bumptech.glide:okhttp3-integration:4.7.1
com.squareup.okhttp3：3.8.1
**:

**DSamsung Galaxy J7 Pro/Android OS 8.1**:

**I find Glide cannot load different image resources in the local folder according to Locale. For example, I name two pictures with different contents as "a" respectively in drawable hdpi and drawable ldrtl-hdpi folders. I am switching my mobile phone language from Chinese to ArabicIs the image resource in the file correct?Are you not suitable to select picture resources in different folders according to Locale?Can you fix this problem?**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
``  public static void loadResPic(Context context, int resId, ImageView imageView) {
        try {
            GlideApp.with(context).load(resId).into(imageView);
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
    }
```

<!-- How does your app look like?
We're most interested in the layout attributes and the hierarchy around the ImageView -->
**Layout XML**:
```    <android.support.v7.widget.AppCompatImageView
            android:id="@+id/rank_bg"
            android:layout_width="140dp"
            android:layout_height="0dp"
            android:scaleType="fitXY"
            android:layoutDirection="inherit"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
```

**Stack trace / LogCat**:
```No error message
```

**Comment by ninovanhooff** [comment]
Bump. This is still an issue.

When I override the default locale with this code, I can you context.getString() to get a localized string in the locale of appLocale. Glide ignores this, though. I believe this is because Glide uses ContentResolver under the hood.

```
/**
 * Return a version of the Context with App Locale applied
 * On Sdk 24, the change is applied globally to [Resources]
 */
fun Context.withAppLocale(): Context {
    val appLocale = PrefsManager(applicationContext as Application).appLocale
        ?: FALLBACK_STOREFRONT.locale

    val resources: Resources = resources
    val configuration = Configuration(resources.configuration) // make a copy of the base Context
    val localeList = LocaleList(appLocale)
    configuration.setLocales(localeList)

    return ContextWrapper(
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N_MR1) {
            createConfigurationContext(configuration)
        } else {
            resources.updateConfiguration(configuration,
                resources.displayMetrics)
            this
        }
    )
}
```
