### ISSUE TITLE
glide加载gif慢的问题您解决了吗

### ISSUE THREAD

**Issue by githubzjh** [bumptech/glide#3458]
Hi, 

I have the same problem too.
In Glide 3, we fix this problem by this way.

    builder.setDiskCacheService(new FifoPriorityThreadPoolExecutor(4));
    builder.setResizeService(new FifoPriorityThreadPoolExecutor(4));

But we can't found these APIs in Glide 4.

_Originally posted by @KimiChiu in https://github.com/bumptech/glide/issues/2471#issuecomment-372102257_

**Comment by githubzjh** [comment]
@KimiChiu  glide加载gif慢的问题您解决了吗

**Comment by KimiChiu** [comment]
@githubzjh 解決了 
後來改成一次只播放一個 gif 
loading 完成後不自動播放
並在`ScrollState` 為 `SCROLL_STATE_DRAGGING` 時停止播放
`ViewHolder` 完整顯示時且 `RecyclerView` 的 `ScrollState` 為 `SCROLL_STATE_IDLE` 的時候自動播放

**Comment by CXinQuan** [comment]
@KimiChiu 可以具体介绍一下你播放gif的方案吗，最近遇到相同的需求

**Comment by githubzjh** [comment]
对于gif直接使用别的第三方加载的




| |
18518407035
邮箱：18518407035@163.com
|

Signature is customized by Netease Mail Master

在2019年08月14日 16:04，CXinQuan 写道：

@KimiChiu 可以具体介绍一下你播放gif的方案吗，最近遇到相同的需求
