### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 5648 (glide-source-th), pid 5250

### ISSUE THREAD

**Issue by wp292519413** [bumptech/glide#3463]
Glide Version:4.8.0

Device/Android Version:Xiaomi Redmi 6 Pro Android8.1 / HUAWEI BKK-AL10 Android 8.0...

Stack trace / LogCat:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/jason/jason:8.1.0/OPM1.171019.019/8.12.13:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 7907, tid: 8238, name: glide-source-th  >>> package name <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    r0 00000000  r1 00000001  r2 00000005  r3 000000c3
    r4 cbb21af0  r5 00000000  r6 00000003  r7 c7db8128
    r8 3f3504f3  r9 00000001  sl 00000001  fp c78f7404
    ip f56b1ed8  sp c78f7148  lr f536cfeb  pc f536cff0  cpsr 200f0030

backtrace:
    #00 pc 0022cff0  /system/lib/libskia.so (SkPathRef::growForVerb(int, float)+195)
    #01 pc 0022676b  /system/lib/libskia.so (SkPath::conicTo(float, float, float, float, float)+234)
    #02 pc 002276b3  /system/lib/libskia.so (SkPath::arcTo(SkRect const&, float, float, bool)+854)
    #03 pc 000d0c97  /system/lib/libandroid_runtime.so (android::SkPathGlue::arcTo(_JNIEnv*, _jclass*, long long, float, float, float, float, float, float, unsigned char)+66)
    #04 pc 00eed9c9  /system/framework/arm/boot-framework.oat (offset 0x967000) (android.graphics.Path.nAddRoundRect [DEDUPED]+184)
    #05 pc 00eee611  /system/framework/arm/boot-framework.oat (offset 0x967000) (android.graphics.Path.arcTo+56)
    #06 pc 00eee6a3  /system/framework/arm/boot-framework.oat (offset 0x967000) (android.graphics.Path.arcTo+106)
    #07 pc 00402175  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
    #08 pc 004072e5  /system/lib/libart.so (art_quick_invoke_stub+228)
    #09 pc 000afcc3  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+138)
    #10 pc 002014e3  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+226)
    #11 pc 001fca71  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+592)
    #12 pc 003ec43b  /system/lib/libart.so (MterpInvokeVirtual+462)
    #13 pc 003f4514  /system/lib/libart.so (ExecuteMterpImpl+14228)
    #14 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #15 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #16 pc 001fca59  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+568)
    #17 pc 003ed253  /system/lib/libart.so (MterpInvokeDirect+218)
    #18 pc 003f4614  /system/lib/libart.so (ExecuteMterpImpl+14484)
    #19 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #20 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #21 pc 001fca59  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+568)
    #22 pc 003ed253  /system/lib/libart.so (MterpInvokeDirect+218)
    #23 pc 003f4614  /system/lib/libart.so (ExecuteMterpImpl+14484)
    #24 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #25 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #26 pc 001fca59  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+568)
    #27 pc 003ec43b  /system/lib/libart.so (MterpInvokeVirtual+462)
    #28 pc 003f4514  /system/lib/libart.so (ExecuteMterpImpl+14228)
    #29 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #30 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #31 pc 001fca59  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+568)
    #32 pc 003ecfb7  /system/lib/libart.so (MterpInvokeInterface+1054)
    #33 pc 003f4714  /system/lib/libart.so (ExecuteMterpImpl+14740)
    #34 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #35 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #36 pc 001fca59  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+568)
    #37 pc 003ecfb7  /system/lib/libart.so (MterpInvokeInterface+1054)
    #38 pc 003f4714  /system/lib/libart.so (ExecuteMterpImpl+14740)
    #39 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #40 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #41 pc 001fca59  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+568)
    #42 pc 003ec43b  /system/lib/libart.so (MterpInvokeVirtual+462)
    #43 pc 003f4514  /system/lib/libart.so (ExecuteMterpImpl+14228)
    #44 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #45 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #46 pc 001fca59  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+568)
    #47 pc 003ecfb7  /system/lib/libart.so (MterpInvokeInterface+1054)
    #48 pc 003f4714  /system/lib/libart.so (ExecuteMterpImpl+14740)
    #49 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #50 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #51 pc 001fd6b9  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+436)
    #52 pc 003ed5bb  /system/lib/libart.so (MterpInvokeVirtualRange+426)
    #53 pc 003f4814  /system/lib/libart.so (ExecuteMterpImpl+14996)
    #54 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #55 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #56 pc 001fd6b9  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+436)
    #57 pc 003ee3b3  /system/lib/libart.so (MterpInvokeDirectRange+154)
    #58 pc 003f4914  /system/lib/libart.so (ExecuteMterpImpl+15252)
    #59 pc 001e34c5  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+344)
    #60 pc 001e7b89  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+148)
    #61 pc 001fd6b9  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+436)
    #62 pc 003ed5bb  /system/lib/libart.so (MterpInvokeVirtualRange+426)
    #63 pc 003f4814  /system/lib/libart.so (ExecuteMterpImpl+14996)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Sample Code:
1: 
```
public static void displayImage(String image, ImageView imageView, RequestOptions options) {
        Context context = imageView.getContext();
        if (context == null) {
            return;
        }
        if (context instanceof Activity && Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            Activity activity = (Activity) context;
            if (activity.isDestroyed()) {
                return;
            }
        }
        Glide.with(context)
                .load(image)
                .apply(options)
                .into(imageView);
    }
```

2: 
```
public static void displayHeader(String header, ImageView imageView) {
        imageView.post(new Runnable() {
            @Override
            public void run() {
                String url = header;
                if (!TextUtils.isEmpty(url)) {
                    int height = imageView.getHeight();
                    int width = imageView.getWidth();
                    if (height == 0) {
                        height = sHeight;
                    }
                    if (width == 0) {
                        width = sWidth;
                    }
                    if (!TextUtils.isEmpty(url)) {
                        String suffix = String.format(mSuffix, height, width);
                        url += suffix;
                    }
                }
                displayImage(url, imageView, getHeaderOptions(), getCircularTransformation());
            }
        });
    }
```

**Comment by Kingwentao** [comment]
I met the same problem, how I do it?

**Comment by mngzb339** [comment]
me too

**Comment by ShahidAnjum** [comment]
same problem here too
