### ISSUE TITLE
Is it possible to get what will be the output image resolution, before the actual decoding and saving into a bitmap?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bumptech/glide#3470]
I'm trying to produce a bitmap from a file, that can be scrolled only horizontally.
For this, I wish to have a special handling of a given file based on what can be done with it on Glide.

I should work according to these rules, I think:
- Input is an image file of any resolution
- I should scale/crop so that the height will be of a specific value.
- The width should be at least of a specific value
- Output bitmap should be up to a certain width, because I don't want to make a too large bitmap, taking huge amount of memory
- Keep the aspect ratio no matter what.

I've tried messing around with various transformations (example: centerCropTransform,fitCenterTransform) , but none of those reached what I wanted, so I think that none can work unless I do some special math on my side before deciding what to do with Glide.

Currently what I do is something like that:

```
val result = Glide.with(context).asBitmap()
                           .load(imageFile)
                           .apply(RequestOptions.noTransformation()
                           .skipMemoryCache(true)
                           .diskCacheStrategy(DiskCacheStrategy.NONE))
                           .submit(reqWidth, reqHeight).get()
```

This produces (at least according to my tests) a bitmap that is at least of the size I request it to be. It works fine, but means I have extra pixels that aren't really needed for the height. It also doesn't protect me from generating a too large bitmap.

But I think maybe it would be easier to ask Glide to use various techniques for the above purpose, and then decide on the possible output resolutions, which is the best to use. Is it possible, without actually decoding the bitmaps and getting them stored in memory (and only later choose which technique should be used) ?

Or maybe I should do something else, better?

In case this is the wrong place to ask this, I've decided to also ask it on StackOverflow:

https://stackoverflow.com/q/53997717/878126

**Comment by sjudd** [comment]
You might be able to write your own `DownsampleStrategy`: http://bumptech.github.io/glide/javadocs/480/com/bumptech/glide/load/resource/bitmap/DownsampleStrategy.html. 

Another option would be store the image width/height in metadata. MediaStore for example includes that data.

**Comment by AndroidDeveloperLB** [comment]
I don't understand those solutions.
Doesn't DownsampleStrategy get used for the actual decoding?
And about storing the image width/height in metadata, this solution sound like it assumes I have made the images.
Is it possible to just have a callback right before the actual decoding, and then decide if I want to continue with it or not?

**Comment by AndroidDeveloperLB** [comment]
Why close this?
