### ISSUE TITLE
Replace cache key from URL to a custom ID string

### ISSUE THREAD

**Issue by HildonEduardo** [bumptech/glide#3478]
Is there a way to simple replace the key used for Cache, on default way, the cache key is simple the URL String, but I want to use a custom ID from my ServerSide, because URL changes every hour, but this custom ID no.

Im running "com.github.bumptech.glide:glide:4.8.0"

Thanks in Advance.

**Comment by sjudd** [comment]
The cache key is based on the model object you pass in, see: http://bumptech.github.io/glide/doc/caching.html#cache-keys. You can use a custom model with a custom id by registering a custom ModelLoader: http://bumptech.github.io/glide/doc/configuration.html#registering-components and http://bumptech.github.io/glide/tut/custom-modelloader.html
