### ISSUE TITLE
Cached images in a Recycler

### ISSUE THREAD

**Issue by robertosancsanz** [bumptech/glide#3485]
I'm using Glide to load images in a list. The fact is that, in addition to the main image, a logo is loaded in each item of the list (same logo in many of them), so the requests for that logo are made too. I try to cache the images, but the requests for the logo are made before the logo image is downloaded, so the app makes "n" logo´s request. Is there any more effective way to do this?

**Comment by sjudd** [comment]
If all the requests parameters are identical, the new loads will wait for the existing request instead of starting new ones. See http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses
