### ISSUE TITLE
How to add another cache path，both the path and the default path custom in AppGlideModule can use together？

### ISSUE THREAD

**Issue by Carlos2927** [bumptech/glide#3486]
In my app，there has two scenes need load Image:User  Avatar and
Chat Image Message.I want to give the chat image message another disk cache path in order to easy to clear all images of chat messages.How can I do it?

**Comment by joimxjtuse** [comment]
i want to ensure that if you import glide source code or library,  change source code into DiskLruCacheWrapper.java may be a better method.

**Comment by joimxjtuse** [comment]
if import Glide library, i think you can do this :
1. change DiskCacheStrategy.All while request all image;
2. listen onResourceReady(), saved with(glideDiskCache.get(new StringSignature(url)), Drawable);
3. read you cache while load fail.
