### ISSUE TITLE
Glide can't load img on somephone sometimes

### ISSUE THREAD

**Issue by bxjxxyy** [bumptech/glide#3487]
Some of my app user came to me,that their app don't show images.But they can see images before,one day suddenly glide don't show images anymore.  
Uninstall app,restart phone,change network  nouseful.Still don't show images,
![image](https://user-images.githubusercontent.com/26214176/51102142-cb43a300-1818-11e9-9ab3-85ab8b24e236.png)
Version  :  glide:4.7.1
Code:
 Glide.with(getApplicationContext()).load(model.getDetailimg()).listener(new RequestListener<Drawable>() {
                                    @Override
                                    public boolean onLoadFailed(@Nullable final GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                                        runOnUiThread(new Runnable() {
                                            @Override
                                            public void run() {
                                                ClipboardManager cmb = (ClipboardManager) context.getSystemService(Context.CLIPBOARD_SERVICE);
//                                                cmb.setText(e.getMessage()+"");

                                                Toast.makeText(NewMissionStart.this, e.getMessage()+"", Toast.LENGTH_SHORT).show();
                                            }
                                        });
                                        return false;
                                    }

                                    @Override
                                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                                        return false;
                                    }
                                }).into(smpic);

**Comment by StanislavMayorov** [comment]
@bxjxxyy hi. Did you find any solution?

**Comment by bxjxxyy** [comment]
@StanislavMayorov No,I didn't.But I thought it's because of dns hijack. Glide download something wrong
