### ISSUE TITLE
Error and Fallback drawables do not have circle crop

### ISSUE THREAD

**Issue by marklapasa** [bumptech/glide#3492]
**Glide Version**:
4.8.0

**Integration libraries**:
OkHttp3 

**Device/Android Version**:
Samsung S7 API 26

**Issue details / Repro steps / Use case background**: 

I have an imageview that correctly renders a circle cropped image when it's a valid url by using the following function:

        fun load() {
            progressBar = findViewById<ProgressBar>(R.id.progressBar)
            imgView = findViewById<ImageView>(R.id.imgView)
            imgView?.let {
                Glide.with(context).load(url).listener(this).apply(
                    RequestOptions().override(
                        400,
                        400
                    ).placeholder(R.drawable.empty_profile_picture_woman).error(R.drawable.empty_profile_picture_woman).fallback(R.drawable.empty_profile_picture_woman).optionalCircleCrop()
                ).into(it)
            }
        }

But the problem is when the url is invalid, i.e. null, the error and fallback drawables display but it doesn't have a circle crop. Do I need to craft my own circular bitmaps?

**Comment by marklapasa** [comment]
bump

**Comment by sayedtalha124** [comment]
I have same Issue
`  Glide.with(this)
        .load(imageUrl).error(R.mipmap.ic_launcher)
        .circleCrop()
        .into(this)`

**Comment by vwmberry95** [comment]
Any progress on this?

**Comment by MadRatSRP** [comment]
I also would like to see this being implemented
