### ISSUE TITLE
CustomViewTarget in Kotlin

### ISSUE THREAD

**Issue by pollux-** [bumptech/glide#3500]
I'm using CustomViewTarget in Kotlin:

```
val target: CustomViewTarget<*, *> = object : CustomViewTarget<LinearLayout, BitmapDrawable>(this) {
        override fun onLoadFailed(errorDrawable: Drawable?) {
            TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
        }

        override fun onResourceCleared(placeholder: Drawable?) {
            TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
        }

        override fun onResourceReady(resource: BitmapDrawable, transition: Transition<in BitmapDrawable>?) {
            TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
        }

    }

    if (context != null) {
        GlideApp.with(context).load(Utils.getImageUrl(card.imageDetail, context)).into(target)
    }

```
I'm getting a compile time error which says,  "None of the following function can be called with an argument supplied".   How can I resolve this?

**Comment by Arlem** [comment]
Use `Bitmap` instead of `BitmapDrawable`, check an example [here](https://proandroiddev.com/how-to-optimize-memory-consumption-when-using-glide-9ac984cfe70f#38ad)

`
Glide.with(this)
        .load(IMAGE_URL)
        .into(object : CustomViewTarget<LinearLayout, Drawable>(customView) {
            override fun onLoadFailed(errorDrawable: Drawable?) {
                // error handling
            }

            override fun onResourceCleared(placeholder: Drawable?) {
                // clear all resources
            }

            override fun onResourceReady(resource: Drawable, transition: Transition<in Drawable>?) {
                customView.image.setImageDrawable(resource)
            }
        })

`
