### ISSUE TITLE
load picture failed

### ISSUE THREAD

**Issue by w2282346548** [bumptech/glide#3505]
version:4.8.0
I try to load a picture, but the displayed picture does not match what is expected, and the browser can display normally.
this is picture：
http://d.hiphotos.baidu.com/video/pic/item/35a85edf8db1cb13dd23f7e6d054564e93584bf9.jpg

**Comment by Yedongsheng** [comment]
遇到了相同的问题，部分图片加载不出来，用浏览器又可以打开
