### ISSUE TITLE
onResourceReady called again after pauseAllRequests.

### ISSUE THREAD

**Issue by ysy950803** [bumptech/glide#3510]
**Glide Version**: com.github.bumptech.glide:glide:4.8.0

**Integration libraries**: 
com.github.bumptech.glide:okhttp3-integration:4.8.0
com.squareup.okhttp3:okhttp:3.11.0

**Device/Android Version**: All.

**Issue details / Repro steps / Use case background**: 
Condition:
- Simply load an image at MainActivity with **SimpleTarget** because I need a bitmap callback.
- And I call **pauseAllRequests** at onStop() to clear resources keeping low memory usage.

Steps:
1. Normally loaded the img url and onResourceReady called successfully.
2. Then I start another Activity from MainActivity or directly enter recent task, so onStop() of MainActivity must be called and my code **pauseAllRequests** called also.
3. **Bug comes:** when I come back MainActivity, onResourceReady called again so my logic about bitmap executes again, that is not my expectation.
4. I try to not call pauseAllRequests at onStop() and the problem can be solved, so I know pausing requests will lead to resume requests automatically, but I really need pauseAllRequests to clear resources.
How can I make onResourceReady only call one time with pauseAllRequests at onStop()?
**Please help me, how do I let onResourceReady method just like a disposable callback.** In other words, I may need an img loading not affected by pausing requests.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
// at my logic
GlideApp.with(this).asBitmap().load(url).into(new SimpleTarget<Bitmap>() {
    @Override
    public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
        // do something to use bitmap
    }
});

@Override
protected void onStop() {
    super.onStop();
    GlideApp.with(this).pauseAllRequests();
}
```

**Layout XML**:
No special.

**Stack trace / LogCat**:
No speciial.

**Comment by sjudd** [comment]
Simple answer would be to keep track of how many times onResourceReady is called and only do whatever you need to do the first time.
