### ISSUE TITLE
Wrote GeneratedAppGlideModule with: []

### ISSUE THREAD

**Issue by Yousha** [bumptech/glide#3512]
**Glide Version**:
4.8.0
```
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
```

**Integration libraries**:
Nothing

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 
Tried to build the project but got this warning/notice:

> Note: [1] Wrote GeneratedAppGlideModule with: []

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
Fragment
```java
Glide.with(this)
```
Activity
```java
Glide.with(getActivity())
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
Note: [1] Wrote GeneratedAppGlideModule with: []

**Environment**
Windows 10 64bit
JRE 1.8.0_152-release-1136-b06 amd64
JVM OpenJDK 64-Bit Server VM by JetBrains s.r.o
Android Studio 3.2.1 Build #AI-181.5540.7.32.5056338
Gradle 4.10.3
Android Gradle plugin: 3.2.1

Java compile options.warnings = true

**Comment by sjudd** [comment]
That's not a warning, if your build failed you'd see another error. If you don't see any other warnings or errors you can disregard that note. It's just telling you which integration libraries that are included by the generated API (none in your case).

**Comment by rtsdemo123** [comment]
I'm using those dependencies

>     implementation 'com.github.bumptech.glide:glide:4.11.0'
>     kapt 'com.github.bumptech.glide:compiler:4.11.0'
>     implementation "com.github.bumptech.glide:okhttp3-integration:4.11.0" 

and I'm still getting this warning is there a solution for this warning?
