### ISSUE TITLE
Unnecessary variable

### ISSUE THREAD

**Issue by javalong** [bumptech/glide#3516]
Version 4.8.0
com.bumptech.glide.GlideBuilder
has a  variable:
private GlideExecutor animationExecutor;

create a new GlideExecutor in build fuction:
Glide build(@NonNull Context context) {
...
 if (animationExecutor == null) {
      animationExecutor = GlideExecutor.newAnimationExecutor();
    }
...
}

but I can't find the usage.

I guess you want to use it in build fuction:
Glide build(@NonNull Context context) {
...

    if (engine == null) {
      engine =
          new Engine(
              memoryCache,
              diskCacheFactory,
              diskCacheExecutor,
              sourceExecutor,
              GlideExecutor.newUnlimitedSourceExecutor(),
              //  here is?
              GlideExecutor.newAnimationExecutor(),
              isActiveResourceRetentionAllowed);
    }
...
}

My English is poor ，sorry!!!

**Comment by sjudd** [comment]
Feel free to send a pull request to remove it,thanks!

**Comment by sjudd** [comment]
Fixed by 
#3525
