### ISSUE TITLE
glide的bug反馈

### ISSUE THREAD

**Issue by azxcffdgadf** [bumptech/glide#3519]
我使用的是glide 4.0:代码:获取视频第一秒的一帧:
Glide.with(mContext)
            .setDefaultRequestOptions(
                new RequestOptions()
                    .frame(1000000)//以微秒为单位
                    .centerCrop()
                    .error(R.drawable.demo3)
                    .placeholder(R.drawable.demo3))
            .load(newString)
            .into(getView.videos_pics);
结果报错:
W/Glide: Load failed for http://192.168.1.2/SD/AMBA/190213000/114830AB.MP4 with size [203x130]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
请问是怎么回事?怎么解决?

**Comment by luffykou** [comment]
加上
`.asBitmap()`
