### ISSUE TITLE
Image not loading from firebase url for android sdk28

### ISSUE THREAD

**Issue by pankurocks** [bumptech/glide#3523]
I am fetching the image from the firebase database and showing into the app using Glide. This function working properly for device less than sdk28 but the device with sdk28+ are not able to view the image. I searched for the solutions and find putting this android:usesCleartextTraffic="true" in manifest solves the issue but it doesn't.

Also there is no error information into the log makes me wonder why the image is not showing, unable to fix it. If any solution please reply.

    public void showImage(){
    mStorageRef.child("TimeTable").getDownloadUrl().addOnSuccessListener(this,new OnSuccessListener<Uri>() {
        @Override
        public void onSuccess(Uri uri) {
            url = uri.toString();
            progressDialog.dismiss();
            Toast.makeText(TimeTable.this, "Loaded",Toast.LENGTH_SHORT).show();

            GlideApp.with(TimeTable.this)
                    .load(url)
                    .placeholder(R.mipmap.ic_launcher_round)
                    .error(R.mipmap.ic_launcher_round)
                    .into(image);

        }
    });
}

**Comment by gogeta95** [comment]
can you share the url?

**Comment by sinetznjr11** [comment]
Did you find the solution? I am also having the same issue and I've tried every solution from StackOverflow but it's still not working.

**Comment by aouspi** [comment]
Even I am having the same issue
