### ISSUE TITLE
Obsolete dependency OK_HTTP_VERSION=3.9.1 as source of crashes

### ISSUE THREAD

**Issue by MichalStranik** [bumptech/glide#3526]
I downloaded Glide source code for 4.9.0 and I checked what version of okhttp3 has been used and I am wondering why do you still use obsolete version 3.9.1?

In my project I use:
    implementation('com.github.bumptech.glide:okhttp3-integration:4.8.0') {
        exclude group: 'glide-parent'
    }

But it is source of crashed:
OkHttp Issue #3719 - Crash: Unexpected TLS version: NONE

This stack trace indicates a known issue with earlier versions of OkHttp, where failure to establish an SSL connection was not handled by the library, and instead bubbled up as an uncaught exception. Upgrading to an OkHttp version of 3.11 or greater should result in these failure modes to be correctly relayed to callbacks.

Is there any problem upgrade to last version to avoid this?

**Comment by sjudd** [comment]
No problems to update the dependency, if you'd like to send a pull request I'd welcome it.

You can also use a newer version in your application without any changes in Glide as long as the API is compatible with the older version.

**Comment by MichalStranik** [comment]
Done:
https://github.com/bumptech/glide/pull/3537
