### ISSUE TITLE
registerComponents not getting called in declared custom LibraryGlideModule

### ISSUE THREAD

**Issue by rahulgurnani** [bumptech/glide#3529]
I have a CustomGlideModule class which extends LibraryGlideModule as follows : 
```
@GlideModule
public class CustomGlideModule extends LibraryGlideModule  {
@Override
 public void registerComponents(Context context, Glide glide, Registry registry) {
// a log statement that this gets called and some code 
 }
}
```
The registerComponents never gets called. Thus I get an error when I try to load my image.

>  Failed to find any ModelLoaders for model: file_type: IMAGE  

My library's build.gradle:
```
annotationProcessor "com.github.bumptech.glide:compiler:4.8.0"
api "com.github.bumptech.glide:glide:4.8.0"
```

**Glide Version**:
4.8.0

**Integration libraries**:

**Device/Android Version**:
Any Version

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(activity).load(v).into(view);
```

**Layout XML**:
```xml
<ImageView
        android:id="@+id/imageId"
        android:layout_width="80dp"
        android:layout_height="80dp"
        android:padding="5dp"
        android:layout_margin="5dp"
        android:longClickable="true"/>
```

**Stack trace / LogCat**:
```
com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: file_type: IMAGE
```

**Comment by rahulgurnani** [comment]
I have an app which uses this library, inside that app I declared an implemented a dummy AppGlideModule class. (Based on docs : http://bumptech.github.io/glide/doc/configuration.html, I felt it's necessary to define an AppGlideModule). 
```
@GlideModule
public class CustomAppGlideModule extends AppGlideModule {
  @Override
  public void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
    super.registerComponents(context, glide, registry);
  }
}

```

**Comment by sjudd** [comment]
There's setup instructions here: http://bumptech.github.io/glide/doc/generatedapi.html#java

**Comment by rahulgurnani** [comment]
AppGlideModule works but I am having trouble with getting LibraryGlideModule working. I am writing a library which will be used by other apps.

**Comment by rahulgurnani** [comment]
To demonstrate what I am trying to achieve, I forked your Base64ModelLoaderExample and created a library module in the project. This statement (https://github.com/rahulgurnani/Base64ModelLoaderExample/commit/b06012f3593e77fca491d00e6c12be382d577323#diff-762fdd612ef8aa327fdecc753b876a8dR16) doesn't get executed, i.e. registerComponents is not called. I tried adding breakpoints too. 
Can you please glance over the commit https://github.com/rahulgurnani/Base64ModelLoaderExample/commit/b06012f3593e77fca491d00e6c12be382d577323 ? 

Am I missing something here?

**Comment by rahulgurnani** [comment]
I used AppGlideModule and it worked.

**Comment by sjudd** [comment]
If you're writing a library, then your library should use LibraryGlideModule. If you then integrate your library into an application, that application should use AppGlideModule. So if you're testing, then you need to add an AppGlideModule to your test app, and a LibraryGlideModule to your library.

Libraries shouldn't include an AppGlideModule because there can only be one per application.
