### ISSUE TITLE
glide can`t load aliyun oss Signature picture

### ISSUE THREAD

**Issue by walkthehorizon** [bumptech/glide#3530]
glide version:4.8.0 
load by okhttp

[http://dmdata-qa.oss-cn-hangzhou.aliyuncs.com/tag/280d46b4dad14febb127087a4334f137.jpg?Expires=1550727669&OSSAccessKeyId=XtDsklbBd514b2Hl&Signature=goWGqRPkH5LbkYvkxYEnDtfyn2M%3D](url)

as you can see,it‘s can load success in browser,but when i load it by glide,aliyun return

> The request signature we calculated does not match the signature you provided. Check your key and signing method.

i notice that glide request：
><SignatureProvided>goWGqRPkH5LbkYvkxYEnDtfyn2M=</SignatureProvided>
Actually it should be
>goWGqRPkH5LbkYvkxYEnDtfyn2M%3D

glide change link?how i do？

**Comment by sjudd** [comment]
Probably something related to: https://github.com/sjudd/glide/blob/52cce3be9ba466cd0304acd8043306d0641d9e17/library/src/main/java/com/bumptech/glide/load/model/GlideUrl.java#L92.

If you could send a pull request with a test case I'd definitely consider it.
