### ISSUE TITLE
Glide says Bitmap is recycled even after !isRecycled check [Kotlin]

### ISSUE THREAD

**Issue by troy-lamerton** [bumptech/glide#3534]
**Glide Version**: 4.8.0

**Device/Android Version**: Motorola G6, OnePlus 3... (probably any device)

**Issue details / Repro steps / Use case background**: 
I have a SurfaceView rendering a slot machine. The slot machine's drawing thread redraws 6 small bitmaps every frame. To run at 60fps, the `getBmp` method below is called up to 240 times per second.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
`this` is a class that extends `SurfaceView`
```kotlin
fun getBmp(@DrawableRes drawableId: Int): Bitmap {
    var bmp: Bitmap? = null
    try {
            bmp = Glide.with(this).asBitmap()
                    .load(drawableId)
                    .submit(120, Target.SIZE_ORIGINAL)
                    .get()
    } catch (ignored: ExecutionException) {
    } catch (ignored: InterruptedException) {
    }

    return bmp!!
}
```

The method that throws `IllegalStateException`:
```kotlin
// `this` is an activity Context
// `it` is the bitmap argument, which is never `null`
fun Context.releaseBitmap(bitmap: Bitmap) {
    bitmap.let {
        synchronized(it) {
            if (!it.isRecycled) {
                Glide.get(this).bitmapPool.put(it)
            }
        }
    }
}
```
```kotlin
val oldBitmaps = rewardsShown.clone()

/* < code that fills rewardsShown with (possibly) different bitmaps > */

for (bmp in oldBitmaps) {
    if (!rewardsShown.contains(bmp)) {
        context.releaseBitmap(bmp)
    }
}
```
**Above code:**
Each frame, the `rewardsShown` Bitmap's are updated. Before replacing them, I keep a reference to all the bitmaps. If any bitmaps are replaced, they are put into Glide's bitmap pool. At some random point, calling `releaseBitmap` throws an IllegalStateException as shown in the logs below.

**Layout XML**:
I load all a lot of drawables as bitmaps. Not using Glide with any ImageView's or making any calls to `.into(...)`.

There is a recycler view using the vanilla android way to load some of the same drawables. Let me know if this is relevant and I can post the code.

**Stack trace / LogCat**:
```logcat
W/Bitmap: Called getWidth() on a recycle()'d bitmap! This is undefined behavior!
W/Bitmap: Called getHeight() on a recycle()'d bitmap! This is undefined behavior!
    Called getConfig() on a recycle()'d bitmap! This is undefined behavior!
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.demo.run_slot, PID: 19390
    java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@824e5cb[156x104] ARGB_8888
        at com.bumptech.glide.util.Util.getBitmapByteSize(Util.java:78)
        at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.removeLast(SizeConfigStrategy.java:111)
        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimToSize(LruBitmapPool.java:230)
        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.evict(LruBitmapPool.java:118)
        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.put(LruBitmapPool.java:114)
        at com.gamingforgood.util.ResourcesKt.releaseBitmap(Resources.kt:75)
        at com.gamingforgood.slotmachine.SlotsSurfaceView$SlotsDrawThread.draw(SlotsSurfaceView.kt:343)
        at com.gamingforgood.slotmachine.SurfaceDrawingThread.run(SurfaceDrawingThread.java:64)
E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
```

How is this even possible? I check if it is recycled one line before, and I added the `synchoronized(bitmap)` line but that didn't help at all.

**Comment by troy-lamerton** [comment]
I've had to remove the releaseBitmap calls from my code to get it to work. Would be good to have someone more experienced spend 5 minutes giving their thoughts/

**Comment by sjudd** [comment]
It's unsafe to put Bitmaps retrieved from Glid into Glides BitmapPool.
Instead the submit() method returns a FutureTarget. Retain the FutureTarget
along with the Bitmap and clear it (RequestManager#clear) when you're done
with the Bitmap instead if trying to put it into the pool.

Sam

**Comment by AndroidDeveloperLB** [comment]
@sjudd Isn't there a way to tell Glide not to recycle the Bitmap, as I intend to use it somewhere else and not into some target of Glide?
In my case, I don't even need to put it into the Glide cache in some cases...
