### ISSUE TITLE
after upgrade to 4.9.0, in android library module it crashes when using Glide.with()

### ISSUE THREAD

**Issue by lannyf77** [bumptech/glide#3538]
this is with in a library module, so it should not use the generated API

upgrade to Glide 4.9.0

    versions.glide = "4.9.0"

    implementation "com.github.bumptech.glide:glide:$versions.glide"
    kapt "com.github.bumptech.glide:compiler:$versions.glide"
    implementation "com.github.bumptech.glide:annotations:$versions.glide"

updated the code, no place is using GlideApp

    fun ImageView.loadImg(imageUrl: String) {

    // 3.8.0
    //    if (!TextUtils.isEmpty(imageUrl)) {
    //        Glide.clear(this)
    //
    //        Glide.with(context).load(imageUrl)
    //                .diskCacheStrategy(DiskCacheStrategy.ALL)
    //                .placeholder(ColorDrawable(Color.LTGRAY))
    //                .into(this)
    //    }

    ///
    // 4.+ code
     var requestOptions : RequestOptions = RequestOptions()
        .placeholder(ColorDrawable(Color.LTGRAY))
        .diskCacheStrategy(DiskCacheStrategy.ALL)

    if (!TextUtils.isEmpty(imageUrl)) {
        Glide.with(context)
            .setDefaultRequestOptions(requestOptions)  
            .asBitmap()
            .load(imageUrl)
            .into(this)
        }
    }

    fun ImageView.clear() {
        Glide.with(this.context).clear(this)
    }
got crash at Glide.with()

    java.lang.AbstractMethodError: abstract method "void    com.bumptech.glide.module.RegistersComponents.registerComponents(android.content.Context, com.bumptech.glide.Glide, com.bumptech.glide.Registry)"
    at com.bumptech.glide.Glide.initializeGlide(Glide.java:270)
    at com.bumptech.glide.Glide.initializeGlide(Glide.java:223)
    at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184)
    at com.bumptech.glide.Glide.get(Glide.java:168)
    at com.bumptech.glide.Glide.getRetriever(Glide.java:689)
    at com.bumptech.glide.Glide.with(Glide.java:716)
if adding the

    @GlideModule
    class DPAppGlideModule : AppGlideModule() {
        override fun isManifestParsingEnabled(): Boolean {
            return false
        }
    }
it will work, but since this is a library module so it should not have this one.

what might be the cause of AbstractMethodError: abstract method "void    com.bumptech.glide.module.RegistersComponents.registerComponents(android.content.Context, com.bumptech.glide.Glide, com.bumptech.glide.Registry)"?

anything besides GlideApp should also be avoid?

**Comment by lannyf77** [comment]
turns out in this library module it has indirect dependency on someone who is using Glide3 and has Old GlideModule which does not impelenet the function required by the Glide 4.

Glide 4's module.registerComponents(applicationContext, glide, glide.registry); take 3 params, but Glide 3's has only two

```
 for (com.bumptech.glide.module.GlideModule module : manifestModules) {
      module.registerComponents(applicationContext, glide, glide.registry);
    }
```

**Comment by sjudd** [comment]
Duplicate of #2994

**Comment by FizzyCodeSolutions** [comment]
> turns out in this library module it has indirect dependency on someone who is using Glide3 and has Old GlideModule which does not impelenet the function required by the Glide 4.
> 
> Glide 4's module.registerComponents(applicationContext, glide, glide.registry); take 3 params, but Glide 3's has only two
> 
> ```
>  for (com.bumptech.glide.module.GlideModule module : manifestModules) {
>       module.registerComponents(applicationContext, glide, glide.registry);
>     }
> ```

How you resolve the issue? At my end i have dependencies of Glide 3x and 4x from other libs eg. quickblox & PixImagePicker.
