### ISSUE TITLE
Glide 4 How to set custom view tag id？

### ISSUE THREAD

**Issue by Caij** [bumptech/glide#3540]
ImageViewTarget extends ViewTarget. but ViewTarget is Deprecated. 
ViewTarget.setTagId(R.id.glide_view_tag_id) is warn.

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/javadocs/490/com/bumptech/glide/request/target/CustomViewTarget.html#useTagId-int-

**Comment by Caij** [comment]
but into(imageview) generate ImageViewTarget， how to set ImageViewTarget default tag id?

**Comment by JeckChou** [comment]
@Caij ImageViewTarget.setTagId(R.id.glide_tag_id)

**Comment by Caij** [comment]
oh !!! thanks

**Comment by JeckChou** [comment]
@Caij are you working with glide 4.9 ? are you use @GlideExtension in your project ?

**Comment by Caij** [comment]
4.9.0, use @GlideModule
