### ISSUE TITLE
java.lang.IllegalStateException: You cannot call Glide.get() in registerComponents(), use the provided Glide instance instead

### ISSUE THREAD

**Issue by luweicheng24** [bumptech/glide#3545]
# java.lang.IllegalStateException: You cannot call Glide.get() in registerComponents(), use the provided Glide instance instead #

**Comment by luweicheng24** [comment]
I think glide has a problem with the singleton through DCL. Since the reordering in high concurrency will lead to the above bug, it is recommended to try the code:
`  public static Glide get(@NonNull Context context) {
    if (glide == null) {
      synchronized (Glide.class) {
        if (glide == null) {
          checkAndInitializeGlide(context);
        }
      }
    }
    return glide;
  }
`

**Comment by EHG613** [comment]
我也遇到同样的问题，请问是如何解决的？

**Comment by may7be** [comment]
我也遇到同样的问题，请问是如何解决的？

**Comment by ChinaZeng** [comment]
请问下有了解决方案了吗？
