### ISSUE TITLE
Glide not loading image if its same url

### ISSUE THREAD

**Issue by AnjuKJ** [bumptech/glide#3548]
**Glide Version**: 3.8.0

**Integration libraries**: Retrofit and QuickBlox

**Device/Android Version**: Android 5.0 & above

**Issue details / Repro steps / Use case background**:  I need to load image using Glide. The url won't be changing, its only the image that gets changed. So the new image is not getting loaded. If I give skipMemoryCache true and DiskCacheStrategy NONE, it will load always. I want only the image to get updated when the content has changed.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
Glide.with(context)
                   .load(url)
                   .asBitmap()
                   .centerCrop()
                   .signature(new StringSignature(String.valueOf(System.currentTimeMillis())))
                   .placeholder(R.drawable.placeholder)
                   .error(R.drawable.error) 
                   .into(
                          new BitmapImageViewTarget(imageview) {
                              @Override
                              protected void setResource(Bitmap resource) {
                                  RoundedBitmapDrawable circularBitmapDrawable =
                                          RoundedBitmapDrawableFactory.create(context.getResources(),
                                                                            resource);
                                  circularBitmapDrawable.setCircular(true);
                                  imageview.setImageDrawable(circularBitmapDrawable);
                              }
                          });

**Comment by sjudd** [comment]
See https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#custom-cache-invalidation.

There's more recent documentation for v4 of Glide.

**Comment by AnjuKJ** [comment]
There is no direct way to get this done. So I implemented my own image caching and thus solved the issue.

**Comment by IslamSalah** [comment]
Checking the [docs](https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation), which seems to be haven't updated for a while, I found that the URL is one of the constituents of the cache key. So content changes won't be reflected in the cache key which implies that the caching system will detect no change.

[Snippet](https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#cache-invalidation) from the docs:
```
In practice, the best way to invalidate a cache file is to change your identifier when the content changes (url, uri, file path etc).
```
