### ISSUE TITLE
Glide has a problem with the disk caching strategy

### ISSUE THREAD

**Issue by liusgh** [bumptech/glide#3550]
Dear Glide developers:
I have a problem about the disk cache with glide.
**Glide Version**:4.7.1
**Device/Android Version**:SAMSUM/Android O
**Issue details / Repro steps / Use case background**: 
We found that one of the images failed to load because the disk cache cached an html file. It can't be decoded into a picture every time. The root cause I think is:
1. Glide does not perform content-type verification on the received stream information, causing the non-picture stream to be written to the disk cache.
2. The disk cache cannot be overwritten or deleted, and the cache cannot be updated after the next time the correct stream is obtained through the network.
Following is the source code:
```java
DiskLruCache diskCache = getDiskCache();
Value current = diskCache.get(safeKey);
if (current != null) {
return;//!!!The cache could not be updated because of this
}
```
Why does our image link point to an html？
We guess this is a strategy adopted by the server when the gateway is wrong.I opened the wrong disk cache, the information inside is as follows:
```javaScript
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).load(uri).into(imageview)
```
**Stack trace / LogCat**:
Similar to this：
```java
There were 7 causes:
java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
java.io.FileNotFoundException(No content provider: https://xxx.webp)
call GlideException#logRootCauses(String) for more detail
```
My question is: 
1. Is the current version of glide not able to cover the above problem scene？
2. How to work around? What I am thinking about now is that when I write the disk cache, I no longer judge whether there is an old cache, but write it directly. I think this can overwrite the old and even the wrong disk cache.
Following is my modified code:
```java
DiskLruCache diskCache = getDiskCache();
Value current = diskCache.get(safeKey);
//if (current != null) {
//return; Comment out these two lines
}
```
Is there any problem with this?
Many thanks.

**Comment by sjudd** [comment]
What networking library are you using? Glide's default do (or should) check the return code. If the server returns 200, we're going to assume that the response contains valid data. 

Rather than trying to occasionally handle and download web pages, it would be better if the server in question doesn't return 200 when the request fails...

**Comment by liusgh** [comment]
@sjudd We use custom network loader/fetcher and the server will return 200 in the above scenario. However, the return policy of the server is currently beyond our control and impact, and can only be circumvented by the client itself. 
Therefore, I would like to ask, is there any risk in my previous proposal?
No longer judge whether there is an old cache, but write it directly. I think this can overwrite the old and even the wrong disk cache.
Following is my modified code:
```java
DiskLruCache diskCache = getDiskCache();
Value current = diskCache.get(safeKey);
//if (current != null) {
//return; Comment out these two lines
```
}

**Comment by sjudd** [comment]
The risk is that you're going to refetch images, which will be slow and use extra bandwidth. A custom ModelLoader that wraps HttpGlideUrlLoader might be better. You could inspect the response body and only return data if it's an image format (or at least not http).

**Comment by liusgh** [comment]
@sjudd I still don't quite understand the risks you are worried about. I think there are two situations:
1. The loading order of Glide is to check the disk cache first. If the correct disk cache is hit, there will be no more network requests and then no re-writing cache.
2. The disk cache will be rewritten only if the disk cache does not exist or the decoding fails (through our own custom NetworkLoader). Of course, before writing the disk cache, glide will take the network request first.
So I think my changes will only work in the second case, but it won't cause you to talk about refetch images and user extra bandwidth, because the bandwidth is necessary at this time.
Maybe I have an incorrect understanding of the mechanism of glide, thank you.

**Comment by coderloveryan** [comment]
This question is still exist with Glide 4.9.0, I don't know why you close the question.

**Comment by saddahussain** [comment]
cause they couldn't fix it :D Just Kidding.
