### ISSUE TITLE
Glide 4.8.0  how to get the cache key when use load(Bitmap) ?

### ISSUE THREAD

**Issue by AndroidLevi** [bumptech/glide#3553]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by AndroidLevi** [comment]
I use load(bitmap) to put my bitmap into glide  , but i can not find the way to get my bitmap back from glide , what should i do ?

**Comment by sjudd** [comment]
See: http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses
