### ISSUE TITLE
incompatible types: RequestOptions cannot be converted to GlideOptions

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [bumptech/glide#3557]
after the latest update **4.9.0** i get this message,i tried to add line below in the proguard rules as monitor in this issue : #2683 but doesn't work,i still see the same message

```
-keep class com.bumptech.glide.GeneratedAppGlideModuleImpl {
*;
}
```

**Comment by Ghost-of-tea** [comment]
Same problem.
If you fixed this error, can you share the solution?

**Comment by WalterShih** [comment]
@Ghost-of-tea 
i just fixed this error
Replace All GlideApp with Glide will fix error
