### ISSUE TITLE
DrawableTransitionOptions doesn't retain an aspect ratio of full image

### ISSUE THREAD

**Issue by CoolMind** [bumptech/glide#3559]
**Glide Version**: 4.9.0
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    kapt 'com.github.bumptech.glide:compiler:4.9.0'

**Integration libraries**: Retrofit, Gson, Room, Google Maps, etc.

**Device/Android Version**:
Emulator (Android 8.1.0), Samsung Galaxy S4 (Android 5.0.1).

**Issue details / Repro steps / Use case background**: 
I want to show an animation of replacing a thumbnail with a full image. I expect a device will retain aspect ratio, but in most cases it won't work. Sometimes, though, it works.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(this)
    .load(photo.src)
    .thumbnail(
        GlideApp.with(this).load(photo.thumb)
    )
    .transition(DrawableTransitionOptions.withCrossFade())
    .into(view.image)
```
In this case `photo.thumb` is a square image (100x100 px): 
![2e7c2591a203f23a41ce16616d5119cf](https://user-images.githubusercontent.com/10630436/54119790-39ff4000-4407-11e9-97f6-0a4fd40c71cf.jpg)
and the full image is rectangular (400x300 px): 
![12bb756742abaac7dae7ef0ac0b3aafc](https://user-images.githubusercontent.com/10630436/54119809-4b484c80-4407-11e9-803d-dd1364268031.jpg)
The images are actual, "Photo not available" is that I get from the server.

**Layout XML**:
```xml
<ImageView
    android:id="@+id/image"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"
    android:minHeight="100dp"
    android:scaleType="fitCenter"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent"
    tools:src="@drawable/image_1"
    />
```
I expect a rectangular image after loading, but have a square. If I remove a line `.transition(DrawableTransitionOptions.withCrossFade())`, I will receive a rectangular image, but lose a fading. Fading is better because the `ImageView` can abruptly change it's size after loading full image.

Here are expected and actual screenshots.
![device-2019-03-11-2](https://user-images.githubusercontent.com/10630436/54120451-ca8a5000-4408-11e9-8527-09786b6dc9e4.png)
![device-2019-03-11-1](https://user-images.githubusercontent.com/10630436/54120461-ce1dd700-4408-11e9-8877-7d7a76c841a4.png)

**Comment by CoolMind** [comment]
Glide is a nice library, but it's support is awful.

**Comment by sjudd** [comment]
Unfortunately there's only one of me :/. Sorry for the delay.

Cross fades unfortunately have a bunch of known issues due to the way Android's TransitionDrawable behaves. Some are listed here: http://bumptech.github.io/glide/doc/transitions.html. If you can find a way to get TransitionDrawable to behave well when the aspect ratio changes let me know.

**Comment by CoolMind** [comment]
@sjudd, hello!

Thank you very much, that you wrote. Didn't expect! Thank you for a tip. If I will find a time, I will experiment and answer here.
