### ISSUE TITLE
okhttp-integration 1.1.0 doesn't contain OkHttpGlideModule

### ISSUE THREAD

**Issue by vovkab** [bumptech/glide#356]
Documentation suggesting installing:
com.github.bumptech.glide:okhttp-integration:1.1.0

while okhttp-integration doesn't have OkHttpGlideModule

Looks like there is a newer version is available already : 1.2.1

**Comment by sjudd** [comment]
Assuming you mean: https://github.com/bumptech/glide/wiki/Integration-Libraries it's now updated. Thanks for pointing that out!
