### ISSUE TITLE
Glide vulnerability issue

### ISSUE THREAD

**Issue by sathishmscict** [bumptech/glide#3563]
![Glide imuuniweb](https://user-images.githubusercontent.com/18158746/54268970-656a6200-45a2-11e9-89b3-dea17cc6fca0.PNG)
Glide vulnerability issue during security test with immuniweb .
Website url : https://www.htbridge.com

**Glide Version**: 4.8.0

No

<!--
What is the error message that you got in the log?
You can find some help on diagnosing issues here: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
Details:
There is '(HttpURLConnection) url.openConnection()' found in file 'com/bumptech/glide/load/data/HttpUrlFetcher.java':
line 39:         public HttpURLConnection build(URL url) throws IOException {

line 40:             return (HttpURLConnection) url.openConnection();

line 41:         }

Cause vulnerability issue ,during security test by immuniwed.
https://www.htbridge.com

![Glide imuuniweb](https://user-images.githubusercontent.com/18158746/54268897-41a71c00-45a2-11e9-8dc8-dbcf96f09a1d.PNG)

**Comment by hardikpatel679** [comment]
> ![Glide imuuniweb](https://user-images.githubusercontent.com/18158746/54268970-656a6200-45a2-11e9-89b3-dea17cc6fca0.PNG)
> Glide vulnerability issue during security test with immuniweb .
> Website url : https://www.htbridge.com
> 
> **Glide Version**: 4.8.0
> 
> No

Hi,
I am also face this issue.
