### ISSUE TITLE
Unchecked generic array creation with transform(Transformation<Bitmap>...) in RequestOptions

### ISSUE THREAD

**Issue by bwalsh0** [bumptech/glide#3567]
Using -Xlint:unchecked:
`[unchecked] unchecked generic array creation for varargs parameter of type Transformation<Bitmap>[]`

**Glide Version**: 4.9.0

**Integration libraries**: _None_

**Device/Android Version**: LG G6 H872 (Android 9.0)

**Issue details / Repro steps / Use case background**: Works as expected, but wanted to double-check the warning if this is due to deprecated JDK

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
RecyclerView loading thumbnails from URL into bitmap
```java
Glide.with(mContext).asBitmap().load(thumbnailURL)
                        .apply(new RequestOptions()
                        .override(thumbScale)
                        .transform(new CenterCrop(), new RoundedCorners(32))   //<--here--
                        .placeholder(R.drawable.ic_sync_black_24dp)
                        .error(R.drawable.ic_round_error_outline_24px)
                        .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC))
                        .into(new BitmapImageViewTarget(holder.thumb) {
                            @Override
                            protected void setResource(Bitmap resource) {
                                super.setResource(resource);
                            }
                        });
```

**Layout XML**:
```xml
    <androidx.appcompat.widget.AppCompatImageView
        android:id="@+id/thumb"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="8dp"
        android:layout_marginEnd="8dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toStartOf="@+id/title"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

**Stack trace / LogCat**:
Only a warning
```ruby
`[unchecked] unchecked generic array creation for varargs parameter of type Transformation<Bitmap>[]`
```

**Comment by jiyewushen** [comment]
@bwalsh0 
you need use [MultiTransformation](https://muyangmin.github.io/glide-docs-cn/javadocs/400/com/bumptech/glide/load/MultiTransformation.html) to replace them, like:

```java
transform(new MultiTransformation<>(new CenterCrop(), new RoundedCorners(32)))
```

**Comment by bwalsh0** [comment]
Thanks, but it's still throwing the error - I'll ignore it for now since it doesn't seem to be causing any other problems.

`
warning: [unchecked] unchecked generic array creation for varargs parameter of type Transformation<Bitmap>[]
                        .transform(new MultiTransformation<>(new CenterCrop(), new RoundedCorners(32)))
`

**Comment by sjudd** [comment]
The only way to make this safe is to have the method be final, which isn't feasible with the current structure. 

This is a consequence of allowing RequestOptions to be accessible directly in RequestBuilder.

**Comment by hilott** [comment]
I use [MultiTransformation(java.util.Collection)](http://bumptech.github.io/glide/javadocs/4xx/com/bumptech/glide/load/MultiTransformation.html#MultiTransformation-java.util.Collection-), like:

```java
transform(new MultiTransformation<>(Arrays.asList(new CenterCrop(), new RoundedCorners(32))))
```
