### ISSUE TITLE
Pause only network and disk requests

### ISSUE THREAD

**Issue by naixx** [bumptech/glide#357]
Currently the lib works great, but there are still some janks. So setting `onScrollListener` with pause helps to eliminate janks, but it pauses all requests. Even if the target image in memory cache, it won't be shown until `resumeRequests` is called. 
Will that feature be possible? Is dispatching memory/disk/network requests that heavy, so that we pause it? Any advices to implement it?

**Comment by sjudd** [comment]
Sorry it isn't currently possible to pause only requests for images that are not in the memory cache. 

Usually pausing/resuming requests while scrolling is unnecessary. I'd suggest you use systrace/traceview to try to figure out what the source of the jank is. If you see some initial jank and lots of GC_FOR_ALLOC logs when you start scrolling, you may want to consider [prefilling Glide's BitmapPool][1].

[1]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/Glide.html#preFillBitmapPool(com.bumptech.glide.load.engine.prefill.PreFillType.Builder...)

**Comment by naixx** [comment]
Will this feature be possible in future? Looks like Picasso works in this way

Yes, I see lots of `GC_FOR_ALLOC`, will try your suggestions, thank you.

**Comment by sjudd** [comment]
It should be possible in Glide 4, though I'd rather focus on fixing or avoiding the jank than hiding it.
