### ISSUE TITLE
glide load local image with Uri return null

### ISSUE THREAD

**Issue by Belolme** [bumptech/glide#3573]
**Glide Version**: 4.9.0

**Integration libraries**: no

**Device/Android Version**: Galaxy s9+

**Issue details / Repro steps / Use case background**: 
1. pick small picture (such as 144x144 size) from system picture picker;
2. get picture Uri from onActivityResult;
3. use glide load the Uri and get null Drawable return when the app no have android.permission.WRITE_EXTERNAL_STORAGE permission

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
photoPickerIntent.setType("image/*");
startActivityForResult(photoPickerIntent, REQUEST_PICK_IMAGE);

protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {

    Uri picData = data.getData();
    GlideApp.with(activity)
               .load(uri)
               .into(new ImageViewTarget<Drawable>(cropImg) {
                        @Override
                        protected void setResource(@Nullable Drawable resource) {
                            // I get null resource here
                            cropImg.setImageDrawable(resource);
                            selectCropRatio(0);
                        }
                    });
}
```

---

I simply solve this problem after read source code, but I think this problem should be solve by official. Below is my solution.

```java
@GlideModule
public class ImageModule extends AppGlideModule {
    @Override
    public void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        registry.prepend(Uri.class, InputStream.class, new UriLoader.StreamFactory(context.getContentResolver()));
    }
}
```

**Comment by sjudd** [comment]
What version of Android is this?

**Comment by Belolme** [comment]
My Android version is 9. I found the problem arise when the app not have android.permission.READ_EXTERNAL_STORAGE and choose a picture that Uri likely to content://media/external/images/media/25897.

below is test code:

```

public class GlideTestActivity extends AppCompatActivity {

    private static final short REQUEST_PICK_IMAGE = 34;

    private ImageView imageView;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        imageView = new ImageView(this);
        ViewGroup.LayoutParams params = new ViewGroup.MarginLayoutParams(100, 100);
        imageView.setLayoutParams(params);

        setContentView(imageView);

        Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
        photoPickerIntent.setType("image/*");
        startActivityForResult(photoPickerIntent, REQUEST_PICK_IMAGE);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case REQUEST_PICK_IMAGE:
                if (resultCode == RESULT_OK && data != null && data.getData() != null) {

                    // imageView cannot show anything
                    // When data.getData() is Intent { dat=content://media/external/images/media/25897 flg=0x1 (has extras) }
                    Glide.with(this)
                            .load(data.getData())
                            .into(imageView);

                }
                break;
        }
    }
}
```

**Comment by sjudd** [comment]
Ah. In this case setResource(null) I believe is actually expected. When the load fails Glide calls [onLoadFailed](https://github.com/bumptech/glide/blob/fbd31f41d164c3b93248556d2601da33d13f2c30/library/src/main/java/com/bumptech/glide/request/target/Target.java#L56). Since you don't have an error placeholder set, Glide ends up setting `null` on the view.

If you use a `RequestListener` you should see that the failure callback is called.

**Comment by Belolme** [comment]
Oh, Thanks your reply. I try add error placeholder, and I get error placeholder. But there is still has a question. I change `ViewGroup.LayoutParams params = new ViewGroup.MarginLayoutParams(100, 100);` to 
`ViewGroup.LayoutParams params = new ViewGroup.MarginLayoutParams(1000, 1000);` and I get Image perfectly. And the behavior is normal?

**Comment by maxbaldrighi** [comment]
@Belolme , just to be clear: your solution about registering the Uri component in your `ImageModule` allows you to show pictures from local Uri even without granting the needed permissions?
