### ISSUE TITLE
GIF animations are very slow. Possible solution and workaround.

### ISSUE THREAD

**Issue by yuriy-budiyev** [bumptech/glide#3575]
**Glide Version**: 4.9.0

**Integration libraries**: none

**Device/Android Version**: Pixel 3, Android Q beta

**Issue details / Repro steps / Use case background**:  Unable to set animation executor in GlideBuilder, setted value is ignored in build method (line 487 in v4.9.0). animationExecutor field is unused.
This causes GIF animations to run on default one or two threaded executor wrich is VERY SLOW, so if you have many GIF's, there are 1fps slideshow or even slower.
Also, by profiling, we can see that one animation thread is used by Glide and fully loaded (never idle), so device's cpu can't be utilized properly.

Glide is used with AppGlideModule, and builder methods called there.

![image](https://user-images.githubusercontent.com/11834224/54756061-777a7f00-4bf8-11e9-9143-11cd4d43d9f6.png)

![image](https://user-images.githubusercontent.com/11834224/54756253-e48e1480-4bf8-11e9-8d73-2648eb454b6b.png)

**Comment by yuriy-budiyev** [comment]
BTW, i see this fixed in master brench:

**Comment by yuriy-budiyev** [comment]
BTW, this is fixed in master branch:
https://github.com/yuriy-budiyev/glide/blob/4b26d774fa4c5d6b5332c732a51a92eaeb1ee8b9/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L487

So the question is: when it will be released, or is there any workaround?

**Comment by yuriy-budiyev** [comment]
BTW, this is fixed in master branch:

https://github.com/bumptech/glide/blob/4b26d774fa4c5d6b5332c732a51a92eaeb1ee8b9/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L487

So the question is: when it will be released, or is there any workaround?

**Comment by yuriy-budiyev** [comment]
A workaround is to update verstion to 4.10.0-SNAPSHON and:

`builder.setAnimationExecutor(
            GlideExecutor.newSourceExecutor(
                DEFAULT_THREAD_POOL_SIZE,
                "animation",
                GlideExecutor.UncaughtThrowableStrategy.DEFAULT
            )
        )`

We can't use newAnimationExecutor because it will notrun out of one thread until it's queue is full, which is impossible while using PriorityBlockingQueue with it's Integer.MAX_VALUE ramainingCapacity().

**Comment by yuriy-budiyev** [comment]
So, this problem should be fixed anyway. In other case GIF animations will play very clow.

**Comment by yuriy-budiyev** [comment]
Profiling with newSourceExecutor() and 4 animation threads:
![image](https://user-images.githubusercontent.com/11834224/54760526-4fdbe480-4c01-11e9-96bb-4fc4f51b7972.png)

**Comment by sjudd** [comment]
Thanks for investigating this, I appreciate the detail!

**Comment by rizwan321** [comment]
@yuriy-budiyev can you please explain what do you mean by updating to **4.10.0-SNAPSHOT** ??
as i am also facing slow animation in gif

**Comment by yuriy-budiyev** [comment]
@rizwan321 In version 4.9.0 you can't set custom executor for animation (builder.setAnimationExecutor will have no effect). In 4.10.0 this was fixed.

**Comment by rizwan321** [comment]
ERROR: Failed to resolve: com.github.bumptech.glide:glide:4.10.0
implementation 'com.github.bumptech.glide:glide:4.10.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'

**Comment by yuriy-budiyev** [comment]
@sjudd Thread pool executor will increase it's pool size only if it's queue is full, until it will stay on minimum possible thread count. 

```
public static GlideExecutor newAnimationExecutor(
  int threadCount, UncaughtThrowableStrategy uncaughtThrowableStrategy) {
 return new GlideExecutor(
    new ThreadPoolExecutor(
        0 /* corePoolSize */,
        threadCount,
        KEEP_ALIVE_TIME_MS,
        TimeUnit.MILLISECONDS,
        new PriorityBlockingQueue<Runnable>(),
        new DefaultThreadFactory(
            ANIMATION_EXECUTOR_NAME,
            uncaughtThrowableStrategy,
            true)));
  }
```

This pool will not work as expected because PriorityBlockingQueue isn't capacity constrained.

Executors.newCachedThreadPool uses SynchronousQueue which literally has no capacity and just transfers objects beetween producers and consumers. So each time when task is added and there are no available worker thread, it will create a new one.

PriorityBlockingQueue
```
/**
* Always returns {@code Integer.MAX_VALUE} because
* a {@code PriorityBlockingQueue} is not capacity constrained.
* @return {@code Integer.MAX_VALUE} always
*/
public int remainingCapacity() {
    return Integer.MAX_VALUE;
}
```

SynchronousQueue
```
/**
* Always returns zero.
* A {@code SynchronousQueue} has no internal capacity.
*
* @return zero
*/
public int remainingCapacity() {
    return 0;
}
```

So the possible solution is just use fixed thread pool for animations:
```
public static GlideExecutor newAnimationExecutor(
  int threadCount, UncaughtThrowableStrategy uncaughtThrowableStrategy) {
 return new GlideExecutor(
    new ThreadPoolExecutor(
        threadCount,
        threadCount,
        0,
        TimeUnit.MILLISECONDS,
        new PriorityBlockingQueue<Runnable>(),
        new DefaultThreadFactory(
            ANIMATION_EXECUTOR_NAME,
            uncaughtThrowableStrategy,
            true)));
  }
```

**Comment by yuriy-budiyev** [comment]
@rizwan321 See [here](https://bumptech.github.io/glide/dev/snapshots.html).

**Comment by rizwan321** [comment]
@yuriy-budiyev thanks for the replying me 
i have successfully updated build.gradle and using below implementations but again animation is slow.

**Glide.with(context).load(icon).into(imageView);**

can you please let me know what i have to add further and how to add ???

**Comment by rizwan321** [comment]
@yuriy-budiyev i also tried below lines 

GlideBuilder builder = new GlideBuilder();				builder.setAnimationExecutor(GlideExecutor.newSourceExecutor(DEFAULT_THREAD_POOL_SIZE, "animation", GlideExecutor.UncaughtThrowableStrategy.DEFAULT));
				Glide.init(getApplicationContext(), builder.setMemoryCache(new LruResourceCache(10*1024*1024)));

**Comment by yuriy-budiyev** [comment]
@rizwan321 See [here](https://bumptech.github.io/glide/doc/generatedapi.html).

**Comment by rizwan321** [comment]
@yuriy-budiyev  what do you mean by **builder will be available in applyOptions method.** ??

**Comment by yuriy-budiyev** [comment]
@rizwan321 override this method in your class.

**Comment by rizwan321** [comment]
@yuriy-budiyev i am not getting your point what you are trying to say. It will be great if you paste a proper solution here ??

**Comment by yuriy-budiyev** [comment]
@rizwan321 
```
@GlideModule
class MyGlideModule: AppGlideModule() {

    override fun applyOptions(
        context: Context,
        builder: GlideBuilder
    ) {
        builder.setAnimationExecutor(
            GlideExecutor.newSourceExecutor(
                4,
                "animation",
                GlideExecutor.UncaughtThrowableStrategy.DEFAULT
            )
        )
    }
}
```

**Comment by RISHABHPATNI1108** [comment]
Can anyone post a full detailed reply, I am still facing the issue, implemented snapshot library and made glide module class, how to solve the issue?

**Comment by rizwan321** [comment]
@yuriy-budiyev i have implemented glide with your suggested way. its speed is good in only Note7. while testing on other device Like S8, S7 its speed is slow as before. can you please look into it or let me know what i have to do further ?
waiting for your kind response.

**Comment by yuriy-budiyev** [comment]
@RISHABHPATNI1108 @rizwan321 Probably, better way is jest wait 4.10.0 release. The snapshot version can be unstable and shouldn't be used in production code. I tested my solution on Pixel 2 XL, Pixel 3, Galaxy S9, Galaxy Tab S3 and Redmi 5. Have you added glide compiler dependency?

**Comment by yarodevuci** [comment]
Still not working for me as expected ... :(
