### ISSUE TITLE
Load video thumbnail of specific time slot

### ISSUE THREAD

**Issue by HimanshuNarang** [bumptech/glide#3576]
This is not an issue. I just want to know is there any way to get video thumbnail of specific time slot from local video path or remote url. 

**Glide Version**: com.github.bumptech.glide:glide:4.8.0

**Comment by sjudd** [comment]
For local videos, see http://bumptech.github.io/glide/doc/options.html#component-options and the options in VideoDecoder: http://bumptech.github.io/glide/javadocs/490/com/bumptech/glide/load/resource/bitmap/VideoDecoder.html
