### ISSUE TITLE
Images Download Issue with Firebase Storage with URL

### ISSUE THREAD

**Issue by sagarmeena** [bumptech/glide#3577]
I am using the below libraries to pull the images & text in my app from a firebase db using the image url. My app is showing the glide view with images and text however the images are all greyed/white out. Anyone have an idea what could be a issue?

implementation 'com.android.support:recyclerview-v7:26.0.0'

implementation 'com.github.bumptech.glide:glide:3.7.0'

implementation 'com.android.support:cardview-v7:26.0.0'

public class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerViewAdapter.ViewHolder> {

    Context context;
    List<ImageUploadInfo> MainImageUploadInfoList;

    public RecyclerViewAdapter(Context context, List<ImageUploadInfo> TempList) {

        this.MainImageUploadInfoList = TempList;

        this.context = context;
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.content_recycler_view_adapter, parent, false);

        ViewHolder viewHolder = new ViewHolder(view);

        return viewHolder;
    }

    @Override
    public void onBindViewHolder(ViewHolder holder, int position) {
        ImageUploadInfo UploadInfo = MainImageUploadInfoList.get(position);

        holder.imageNameTextView.setText(UploadInfo.getImageName());

        //Loading image from Glide library.
        Glide.with(context).load(UploadInfo.getImageURL()).into(holder.imageView);
    }

    @Override
    public int getItemCount() {

        return MainImageUploadInfoList.size();
    }

    class ViewHolder extends RecyclerView.ViewHolder {

        public ImageView imageView;
        public TextView imageNameTextView;

        public ViewHolder(View itemView) {
            super(itemView);

            imageView = (ImageView) itemView.findViewById(R.id.imageView);

            imageNameTextView = (TextView) itemView.findViewById(R.id.ImageNameTextView);
        }
    }

//I am able to upload the images to firebase but when downloading the images the logcat is showing below

W/Glide: Load failed for com.google.android.gms.tasks.XXXXXXX with size [1050x600] class com.bumptech.glide.load.engine.GlideException: Failed to load resource There were 3 causes: java.io.FileNotFoundException(/com.google.android.gms.tasks.XXXXXX (No such file or directory)) java.io.FileNotFoundException(No such file or directory) java.io.FileNotFoundException(No such file or directory) call GlideException#logRootCauses(String) for more detail Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL There was 1 cause: java.io.FileNotFoundException(/com.google.android.gms.tasks.XXXXXX (No such file or directory)) call GlideException#logRootCauses(String) for more detail Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed

**Comment by asimbo** [comment]
I am facing the same error with firebase storage. Please help

**Comment by neuberfran** [comment]
I have this issue too.

https://stackoverflow.com/questions/52651815/how-to-place-a-firebase-generated-url-into-an-imageview-with-glide

look this .
