### ISSUE TITLE
java.lang.IllegalArgumentException: You must call this method on a background thread 

### ISSUE THREAD

**Issue by tranquoctrungcntt** [bumptech/glide#3579]
the exception as the title, this is my code 

   try {
                bitmap=Glide.with(mContext.getApplicationContext())
                        .asBitmap().load(icon).apply(new RequestOptions().fitCenter())
                        .apply(new RequestOptions().circleCrop()).submit().get();
            } catch (Exception e) {
                Log.d("GGGGGGG",e+"");
                bitmap= BitmapFactory.decodeResource(mContext.getResources(),
                        R.drawable.ic_default_user_image);
            }

**Comment by JeckChou** [comment]
> the exception as the title, this is my code
> 
> try {
> bitmap=Glide.with(mContext.getApplicationContext())
> .asBitmap().load(icon).apply(new RequestOptions().fitCenter())
> .apply(new RequestOptions().circleCrop()).submit().get();
> } catch (Exception e) {
> Log.d("GGGGGGG",e+"");
> bitmap= BitmapFactory.decodeResource(mContext.getResources(),
> R.drawable.ic_default_user_image);
> }

You must call this method on a background thread. the exception description is tell you how to resolve it.

**Comment by tranquoctrungcntt** [comment]
how can i fix that. I am using glide to load image into notification small icon

**Comment by TimScriptov** [comment]
??????????????????????????????
