### ISSUE TITLE
CustomTarget constructor javadoc and implementation are inconsistent

### ISSUE THREAD

**Issue by JadenChoi** [bumptech/glide#3582]
**Glide Version**: 4.9.0

**Integration libraries**:

**Device/Android Version**: *

**Issue details / Repro steps / Use case background**: 
`CustomTarget` constructor javadoc says that width & height must be >= 0 or == Integer.MIN_VALUE.
However, the app crashes when width/height is 0 and throws exception with msg: `Width and height must both be > 0`. I looked at the implementation and we are enforcing that width & height to be > 0. Javadoc should also reflect it.

**Comment by JadenChoi** [comment]
Created PR to update Javadoc https://github.com/bumptech/glide/issues/3582

**Comment by eshaanb** [comment]
👍👍
