### ISSUE TITLE
Glide doesn't update image views in recyclerview when wifi is available again

### ISSUE THREAD

**Issue by anonym24** [bumptech/glide#3587]
Glide doesn't update image views in RecyclerView when Wi-Fi is available again

For example I scroll through RecyclerView without internet, it of course doesn't download any images

Then when I turn up Wi-Fi Glide won't update ImageViews for items where I stopped until I scroll somewhere else and then scroll back again to those items

**Comment by sjudd** [comment]
Glide does have a broadcast receiver for connectivity changes and restarts any failed requests when connectivity changes: https://github.com/bumptech/glide/blob/fbd31f41d164c3b93248556d2601da33d13f2c30/library/src/main/java/com/bumptech/glide/manager/DefaultConnectivityMonitor.java#L18.

You may be able to debug that and figure out why it's not being called or not working for your particular case.

**Comment by anonym24** [comment]
@sjudd it seems this can happens when switch between mobile network and wifi, e.g. when we have mobile network and wifi enabled at the same time then device uses only wifi and when you disable wifi, yes, there is event (broadcast), but it seems Android doesn't switch that fast to mobile network even if it was already enabled (it just wasn't used, so there is still some initialization happens when you disable wifi). Also we can test with other combinations (state of mobile network, wifi and order in which we disable/enable them)

well I think such things won't happen very often

**Comment by sjudd** [comment]
Feel free to take a look at DefaultConnectivityMonitor. If you find any bugs or have suggestions on how to improve it, I'd welcome the help.
