### ISSUE TITLE
RequestManager: what's the right scope?

### ISSUE THREAD

**Issue by VictorAlbertos** [bumptech/glide#3588]
I tried to find the answer to this question in the docs but I did not find it. Apologies if it is already there.

Can I reuse `RequestManager` instance for multiple calls or should I avoid doing that? I ask because I would prefer to pass to the `RecyclerView.Adapter` the `RequestManager` instance instead of the Fragment/Activity one, as the last one imposes a higher coupling. 

Thanks.

**Comment by sjudd** [comment]
You can definitely set the RequestManager as an instance variable in a RecyclerView Adapter. The RequestManager is tied to the enclosing Activity or Fragment (or Application if there is no enclosing Activity or Fragment).

**Comment by VictorAlbertos** [comment]
Thanks!
