### ISSUE TITLE
the suffix of disk cache path is .0, how can I get the original suffix

### ISSUE THREAD

**Issue by liuguicen** [bumptech/glide#3589]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
You can't reliably retrieve originals from Glide's disk cache. It's not meant to be consumed outside of Glide.
