### ISSUE TITLE
images have bad quatity with small size  

### ISSUE THREAD

**Issue by tranquoctrungcntt** [bumptech/glide#3590]
this happen when load image into a small size ```ImageView``` or ```CircleImageView```
![Untitled](https://user-images.githubusercontent.com/33772899/55270731-2d1e8f80-52d5-11e9-8896-82333acf9e59.png)

```
 Glide.with(mContext.getApplicationContext())
        .load(user.link_thumb_profile_picture)
       .override(15,15)
       .format(DecodeFormat.PREFER_ARGB_8888)
       .dontAnimate()
       .dontTransform()
       .fitCenter()
      .into(vh.img_status);
```

**Comment by sjudd** [comment]
.override(15, 15) is setting the image size to be at most 15x15 pixels. Did you mean to do that?

**Comment by tranquoctrungcntt** [comment]
I want to make image has size 15dp

**Comment by sjudd** [comment]
is the resource itself 15x15 pixels? Or is it larger? If it's larger, then setImageResource will use a higher quality image than Glide will when you ask Glide to load a 15x15 image.

**Comment by tranquoctrungcntt** [comment]
the resource has a larger size. sir
