### ISSUE TITLE
GlideException: Failed to load resource

### ISSUE THREAD

**Issue by manegirish** [bumptech/glide#3592]
This is started suddenly happening and only with devices running on android 9; Whenever i try to load the image it throws the following error in log output. The same image is loading on Android versions less than 9.
I am suing Glide 4.8.0
Please help me to resolve this issue
Glide: Load failed for https://cdn.birdzi.com/AdFlyer/Images/004532/032719_Hrn_Part10.png
https://cdn.birdzi.com/AdFlyer/Images/004532/032719_Hrn_Part10.png
with size [516x516]
   class com.bumptech.glide.load.engine.GlideException: Failed to load resource
   There were 2 causes:
   java.net.SocketTimeoutException(timeout)
   java.net.SocketTimeoutException(timeout)
    call GlideException#logRootCauses(String) for more detail
     Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
   There was 1 cause:
   java.net.SocketTimeoutException(timeout)
    call GlideException#logRootCauses(String) for more detail
       Cause (1 of 1): class java.net.SocketTimeoutException: timeout
     Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
   There was 1 cause:
   java.net.SocketTimeoutException(timeout)
    call GlideException#logRootCauses(String) for more detail
       Cause (1 of 1): class java.net.SocketTimeoutException: timeout
     Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{StringUri->Object->Drawable}, LOCAL
       Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Drawable->Drawable}
       Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Bitmap->Drawable}

**Comment by sjudd** [comment]
java.net.SocketTimeoutException(timeout)

**Comment by isayWu** [comment]
I have the same issues

**Comment by aanalmehta** [comment]
I am also facing the same issue. The thing is sometimes it failed to load and sometimes it succeed.
When I tried to open the image from Web, it succeed but with Glide, it failed.
Can anyone help me with this?

**Comment by spurdow** [comment]
Please reopen this is currently easily reproduced in my Android 9.
