### ISSUE TITLE
Using glide in recylcerview results in focus loss during scroll (Sample code provided)

### ISSUE THREAD

**Issue by noobdev19** [bumptech/glide#3599]
**Glide Version**: 4.8.0

**Integration libraries**: none

**Device/Android Version**: Android 5.0 (Amazon file TV stick)

**Issue details / Repro steps / Use case background**: 
Making a image gallery gridview with recyclerview and glide for android TV. Glide loads all images just fine. But when scrolling, by pressing and holding the d-pad down button, the recylerview item will lose focus and the focus will be transferred to a view that is outside the recyclerview. This only happens when using glide. When loading the same image by

holder.icon.setImageResource(R.drawable.sample);

this focus loss does not happen at all. However this is not a solution since I am loading images from the web. Thank you for looking into this. Please let me know if I'm doing something wrong here. Let me know if you need more info, or want me to test something out as well.
 
Full code is provided below.

Fragment code:
```
import android.content.Context;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v4.view.ViewCompat;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;

import com.bumptech.glide.Glide;
import com.bumptech.glide.RequestManager;
import com.bumptech.glide.request.RequestOptions;

import java.util.Random;


public class ListFragment extends Fragment {

    RequestManager glide;

    public ListFragment() {
        // Required empty public constructor
    }

    private RecyclerView recyclerView;
    private RecyclerView.Adapter mAdapter;
    private RecyclerView.LayoutManager layoutManager;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_list, container, false);
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        recyclerView = getActivity().findViewById(R.id.my_recycler_view);
        glide = Glide.with(this);


        layoutManager = new GridLayoutManager(getActivity(),8);
        mAdapter = new MyAdapter();
        recyclerView.setItemAnimator(null);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setAdapter(mAdapter);
    }







    public class MyAdapter extends RecyclerView.Adapter<MyAdapter.ViewHolder> {


        private final String[] imageUrls = {"https://static1.squarespace.com/static/51d6d61de4b03f5ac28c861a/55076abee4b038dc7dbd4f2a/5c2baa1821c67c1430401c65/1546365481213/20181208_0034pp2+810b2.jpg","https://static1.squarespace.com/static/51d6d61de4b03f5ac28c861a/55076abee4b038dc7dbd4f2a/5c2baa218a922d1c5eb370c5/1546365483758/20181208_0115pp+810b.jpg","https://static1.squarespace.com/static/51d6d61de4b03f5ac28c861a/55076abee4b038dc7dbd4f2a/5c2ba92340ec9ab2ea3f0f73/1546365229886/20181215_0135pp+810b.jpg","https://static1.squarespace.com/static/51d6d61de4b03f5ac28c861a/55076abee4b038dc7dbd4f2a/5c2ba8880e2e72e38d92a482/1546365075745/20180914_0189+810b.jpg","https://static1.squarespace.com/static/51d6d61de4b03f5ac28c861a/55076abee4b038dc7dbd4f2a/5c2ba885f950b760dd6800a7/1546365086762/20180914_0168pp+810.jpg"};
        private final RequestOptions options = new RequestOptions().centerCrop();
        private final Random random = new Random();
        private final Handler handler = new Handler();

        public class ViewHolder extends RecyclerView.ViewHolder {
            public ImageView icon;
            public View layout;

            ViewHolder(View v) {
                super(v);
                layout = v;
                icon =  v.findViewById(R.id.icon);
            }
        }


        @Override
        public MyAdapter.ViewHolder onCreateViewHolder(ViewGroup parent,
                                                       int viewType) {

            LayoutInflater inflater = LayoutInflater.from(
                    parent.getContext());

            View v =
                    inflater.inflate(R.layout.item_recycler_view, parent, false);

            MyAdapter.ViewHolder vh = new MyAdapter.ViewHolder(v);
            return vh;
        }




        @Override
        public void onBindViewHolder(final MyAdapter.ViewHolder holder, final int position) {

            final String name = imageUrls[random.nextInt(imageUrls.length - 1)];

            Glide.with(holder.icon).load(name).into(holder.icon); //Focus loss
            //Glide.with(holder.icon).load(R.drawable.sample).into(holder.icon); //Focus loss
            //holder.icon.setImageResource(R.drawable.sample); //NO FOCUS LOSS
        }

        // Return the size of your dataset (invoked by the layout manager)
        @Override
        public int getItemCount() {
            return Integer.MAX_VALUE;
        }

    }
}
```

Recyclerview item:
```
<?xml version="1.0" encoding="utf-8"?>
<ImageView android:id="@+id/icon"
    android:layout_width="match_parent"
    android:layout_height="250dp"
    android:scaleType="fitCenter"
    android:clickable="true"
    android:focusable="true"
    android:focusableInTouchMode="false"
    android:adjustViewBounds="false"

    android:foreground="@drawable/fg_selectable"


    android:background="@color/colorPrimaryDark"

    tools:src="@tools:sample/avatars"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" />
```

fragment xml layout:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context=".ListFragment"
    android:orientation="horizontal"
    >

---This EditText is here for testing purposes to demonstrate that the recyclerview item does indeed lose focus and this EditText captures the focus.
    <EditText
        android:id="@+id/editText"
        android:text="test"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:nextFocusDown="@id/editText"
        />

    <android.support.v7.widget.RecyclerView
        android:id="@+id/my_recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

</LinearLayout>
```

**Comment by noobdev19** [comment]
@sjudd bump. It anyone could test this out it would be great.

**Comment by noobdev19** [comment]
@yuriy-budiyev bump again. Is there anything I can do to help you with this?

**Comment by sjudd** [comment]
I'm not sure what to suggest. If you're able to point out something that Glide could do differently to avoid changing focus, I'd definitely be interested to hear it. 

I'd guess it has something to do with the asynchronous update? If you instead of `holder.icon.setImageResource(R.drawable.sample);` you run that in an AsyncTask instead do you se the same behavior?

**Comment by noobdev19** [comment]
That's possible. I'll get back to you on that. RecyclerView might have their own focus bug. Focus jumps out when data*changed methods are called. So I am guessing anything that triggers onCreateViewHolder will cause the focus to jump out. But unfortunately I don't know how to confirm this as I am not skilled enough.

**Comment by R01NDev** [comment]
This issue is still happening with glide not the recyclerview. Forcing the dpad ms to be sub 600ms so fast scrolling is disabled results in proper focus.

**Comment by GustavPS** [comment]
Got the same issue, it only happens once the images is not cached

**Comment by mariuspena** [comment]
no workaround yet ?

**Comment by FongMi** [comment]
Anyone has solution? 
If I use glide, the VerticalGridView can't scroll.

**Comment by onlycyndi** [comment]
> VerticalGridView

me too

**Comment by onlycyndi** [comment]
> Anyone has solution? If I use glide, the VerticalGridView can't scroll by finger.

me too 

finally I have to use the BaseGridView's focusScrollStrategy, It's RestrictedApi.

`mVerticalGridView.focusScrollStrategy = BaseGridView.FOCUS_SCROLL_ITEM`

**Comment by FongMi** [comment]
![image](https://github.com/bumptech/glide/assets/3471963/84bc4fef-cb1e-496c-b74a-58063efbd8da)
I wrote this a long time ago
but it doesn't work

**Comment by onlycyndi** [comment]
> ![image](https://user-images.githubusercontent.com/3471963/246013090-84bc4fef-cb1e-496c-b74a-58063efbd8da.png) I wrote this a long time ago but it doesn't work
> 
>  device-2023-06-15-142608.mp4

Hi,

I have already encountered this problem when compatible with mobile phones, and the way I solved it is use GridLayoutManager. and add it on your initAdapter method. so your specific usage scenario is mobile phone or TV ？

`if (!AppUtil.isTV(this)) {
            mVerticalGridView.layoutManager = GridLayoutManager(this, 6)
        } else {
            mVerticalGridView.setNumColumns(6)
        }`

**Comment by FongMi** [comment]
> > ![image](https://user-images.githubusercontent.com/3471963/246013090-84bc4fef-cb1e-496c-b74a-58063efbd8da.png) I wrote this a long time ago but it doesn't work
> > device-2023-06-15-142608.mp4
> 
> Hi,
> 
> I have already encountered this problem when compatible with mobile phones, and the way I solved it is use GridLayoutManager. and add it to your initAdapter method. so your specific usage scenario is mobile phone or TV ？
> 
> `if (!AppUtil.isTV(this)) { mVerticalGridView.layoutManager = GridLayoutManager(this, 6) } else { mVerticalGridView.setNumColumns(6) }`


mVerticalGridView.setLayoutManager(new GridLayoutManager(getActivity(), 6));

java.lang.ClassCastException: androidx.recyclerview.widget.GridLayoutManager cannot be cast to androidx.leanback.widget.GridLayoutManager

**Comment by onlycyndi** [comment]
> mVerticalGridView

OK, so you are not using leanback's VerticalGridView?

**Comment by FongMi** [comment]
Sure, I am using androidx.leanback.widget.VerticalGridView;
