### ISSUE TITLE
Should custom drawables be cached?

### ISSUE THREAD

**Issue by ursusursus** [bumptech/glide#3600]
Hi, I have user which has image url of its avatar, if that fails / or there is none, Id like to display "initials" drawable, sort of like gmail does

```
Glide.with(avatarImageView)
                .load(user.imageUrl)
                .transition(DrawableTransitionOptions.withCrossFade())
                .apply(RequestOptions.circleCropTransform())
                .error(InitialsDrawable(user.name.toInitials())
                .into(avatarImageView)
```
This obviously creates InitialsDrawable instance every time this time is run, regardless if displayed or not

**Is Drawable instance worth caching if not drawn?**

If so, is there a way to lazy create when needed? 

Is there a way to cache such drawable per some key? (Since use case is in a recyclerview with messages list, where each message has its user, and often can be same user)

**Comment by sjudd** [comment]
Whether the Drawable is worth caching or not depends on the Drawable. If it's particularly expensive to create it might be. In general Drawables aren't very expensive or can be made fairly lazy.

You can use resource ids to avoid creating new Drawables every time, though you're limited to actual resources.

We could add an API to pass in a Factory instead of a Drawable, but I haven't seen a great use case for it.

**Comment by ursusursus** [comment]
For me constructor is just simple string processing of turning full name into initials. Then onDraw has canvas.drawText, canvas.drawCircle, thats all.

What do you mean 'fairly lazy'?

**Comment by sjudd** [comment]
I mean that it's cheap to create a new object, so the only real expensive is whatever you're doing in the constructor. If you're doing anything expensive in the constructor you can probably do so lazily instead.

**Comment by ursusursus** [comment]
Oh lazily inside, I see. Anyhow, is there a way for it to be cached inside glide? I only see Drawable as param to load or error in this case. Therefore ctor will be run always which is fine I guess, however I use asBitmap() to render to bitmap, to be used in Notification. Would this bitmap for cached even if new Drawable instance everytime. Do I need to provide Signature as a key?

**Comment by sjudd** [comment]
The placeholder Drawable isn't used as part of the cache key.

See also: http://bumptech.github.io/glide/doc/caching.html#caching

**Comment by sjudd** [comment]
Loading a drawable has different behavior than error() or placeholder(). Loading a drawable (ie load(drawable)) will cache. error() and placeholder will not, those rely on either the caller or Android's resource caching.
