### ISSUE TITLE
Load larger size image from cache for a smaller image request with different URLs

### ISSUE THREAD

**Issue by kunall17** [bumptech/glide#3602]
**Glide Version**: 4.9.0

We are using cloudinary (A media host with transformations/sizes etc) which serves images according to the width specified in the URL, 
And we load a same image of three sizes lets say A<B<C, and if C has been cached we want to use the cached image for the request of A or B 

And the URL scheme goes something like res.cloudinary.com/***/image_width/***/<image_id>.

I've tried using the `implements Key` but I understand that it's not the only piece to get this working, what's the most efficient way to support this?
Any help would be highly appreciated.

**Comment by sjudd** [comment]
Sounds like you want something like this: https://github.com/bumptech/glide/blob/fbd31f41d164c3b93248556d2601da33d13f2c30/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrModelLoader.java#L53

See also: http://bumptech.github.io/glide/tut/custom-modelloader.html
