### ISSUE TITLE
 Failed DecodePath  Glide Version 4.9.0

### ISSUE THREAD

**Issue by liushengqiang** [bumptech/glide#3604]
04-11 15:08:26.160 17653-17653E/DevLog: lz.terminal.UI.MainActivity |**| showAdImage>>Failed to load resource 
    StackTraceString:class com.bumptech.glide.load.engine.GlideException: Failed to load resource
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ContentLengthInputStream->Bitmap->Bitmap}, REMOTE
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ContentLengthInputStream->Bitmap->Bitmap}
url:http://resources.kuaifa.tv/upload/cb/2dcefd99f012be73c66d1e4548b224.jpg

**Comment by Shea123** [comment]
我也遇到了，解决了吗
