### ISSUE TITLE
Globally disabling disk cache causes images to not load

### ISSUE THREAD

**Issue by grandstaish** [bumptech/glide#3610]
**Glide Version**:
4.9.0

**Integration libraries**:
OkHttp (but the issue happens without it too)

**Device/Android Version**:
Android P, Pixel 2 (and an emulator)

**Issue details**: 
I want to globally disable glide's disk caching and fallback entirely to OkHttp caching. To do this, I'm applying the `DiskCacheAdapter`. Adding this `DiskCacheAdapter` somehow causes the image to never load! If I don't add this line, images load correctly.

E.g.:

```kotlin
@GlideModule
class GlideModule : AppGlideModule() {

    override fun isManifestParsingEnabled(): Boolean = false

    override fun applyOptions(context: Context, builder: GlideBuilder) {
        // If I comment out this line, the image loads correctly
        builder.setDiskCache(DiskCacheAdapter.Factory())
    }
}
```

**Comment by sjudd** [comment]
This will happen if you're using DiskCacheStrategy.DATA/ALL/AUTOMATIC with Glide. You can change the DiskCacheStrategy.NONE or build your own that uses NONE for remote images and RESOURCE for local images.

http://bumptech.github.io/glide/javadocs/490/com/bumptech/glide/load/engine/DiskCacheStrategy.html

**Comment by grandstaish** [comment]
I can use `DiskCacheStrategy.NONE` which works fine, but you need to apply it to every single Glide usage. Is there a way to do this globally?

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/configuration.html#default-request-options

**Comment by ismail-creatvt** [comment]
To globally disable disk caching in Glide, you can create an empty implementation of disk cache and set it in the glide module.

```kotlin
@GlideModule
class MyGlideModule : AppGlideModule() {

    private class NoCachingDiskCache:DiskCache {

        override fun get(key: Key?): File? {
            return null
        }

        override fun put(key: Key?, writer: DiskCache.Writer?) {
        }

        override fun delete(key: Key?) {
            
        }

        override fun clear() {
  
        }

    }
    override fun applyOptions(context: Context, builder: GlideBuilder) {
        super.applyOptions(context, builder)
        builder.setDiskCache { NoCachingDiskCache() }
    }
}
```
