### ISSUE TITLE
Failed to find any ModelLoaders for FutureTarget

### ISSUE THREAD

**Issue by chjan** [bumptech/glide#3611]
Running  the code below, I get this exception:
2019-04-17 17:08:02.143 10108-10370/com.hdsl.a.zapp E/GlideExecutor: Request threw uncaught throwable com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: com.bumptech.glide.request.RequestFutureTarget@5fa408e

Case: With 150 png icons (drawables) of size  250x250px, the intention is to load these into memory cache permanently, downscaled once  and for all to 100x100, i.e. for superfast access due to recurring Fragment inflate after tilt, etc.

The log.e reports that FutureTarget@5fa408e was injected. No error logs seen.

The second method is called later on; "putDrawableinto…" creates the error. If I instead of loading the FutureTarget "target", load the image as fetched into d, this works. (now commented out).

There is little info on StackOverflow on this problem (bug?). Is there a fix? This is Glide4, but I will revert to Glide3 due to need for being backwards compliant (unless impossible).

Thanks for any comments!

```
`
       
      public void LoadImageResourcesToGlideCache() {
       
        //The drawable d is fetched  from a Map with viewId as key
        int d = (int)drawableMap.get(R.id.nrk_klassiskdummy);
        //test 160419
         target = Glide.with(activity)
                .load(d)
                //.onlyRetrieveFromCache(true)
                //.skipMemoryCache(false)
                //.diskCacheStrategy(DiskCacheStrategy.NONE)
                .submit(100,100);

         Log.e ("HDSL.IH", "loaded test image to memory:  " + target);
    }

    public void putDrawableIntoImageView(View v) {

        int d = (int)drawableMap.get(R.id.nrk_klassiskdummy);

        Glide.with(activity)
                .load(target)
                //.load(d)
                //.diskCacheStrategy(DiskCacheStrategy.NONE)
                .into(v);
    }`
```

**Comment by sjudd** [comment]
Glide has never supported loading it's own Futures like this, but you really don't need to do this.

If you want to add images to the cache, use `preload()`. If you want some other kind of caching behavior other than LRU, you can either change Glide's MemoryCache implementation for your project, or build a caching layer on top of Glide. Since you're just working with icons, I'd probably build an icon cache and use it to lazily load the images.

In general trying to force things to stay in memory forever is discouraged in Glide.

**Comment by chjan** [comment]
If I preload() and then a few seconds later load(), approximately as above code, this exception is encountered: com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: com.bumptech.glide.request.target.PreloadTarget@9702a17

`int d = (int)drawableMap.get(R.id.nrk_klassiskdummy);

        Glide.with(activity)
                .load(target)
                //.diskCacheStrategy(DiskCacheStrategy.NONE)
                .error(
                        Glide.with(activity)
                                .load(d))

                .override(100,100)
                .into((SimpleDraweeView)v);`

In this case, d (error) is always loaded. The "target" is unattainable.

What are the possible reasons for not finding the modelloader? The JavaDoc has no explanation on error situations.

Glide is great and we use it extensively to modify images, etc, but in this case of "preloading", there is very little on StackOverflow and the documentation does not explain the case. Would you have a working code example that preloads in such a way that is does not fall out immediately again? Something like .preload_keepInBitmapCache() ? Many thanks for any help, after a day of chasing the solution in vain. Or perhaps this is a bug?

**Comment by sjudd** [comment]
To clarify: don't pass a `Target` into `load()`, that won't work.

Preload can be used without a Target, just use the same size and url. Then make a completely separate request to load the same size and url into your view. If the size and url and other properties match, the second request you make will use the cached resource or in progress load from the preload request.

Take a look at the Flickr sample app and you'll see some usages of preload.
