### ISSUE TITLE
Is there a simple way to change glides log level?

### ISSUE THREAD

**Issue by cyberpwnn** [bumptech/glide#3615]
When more than 4 images in a gridview are not readable (user content), glide is reporting nested causes (i.e. https://hastebin.com/nofisasuqe.txt). This is not useful. I would like to stop this from happening, as it keeps overflowing the ADB Log buffer and basically makes logging anything else useless without setting up filters. 

The only solution i have seen is to setup an overengineered seeming GlideApp module. The problem is, the generated code doesnt compile. (Im using androidx).

Is there any other way to at the least reduce this excessive logging so i can continue to log other things? Thanks.

**Comment by sjudd** [comment]
Only via a module: http://bumptech.github.io/glide/doc/configuration.html#log-level

**Comment by cyberpwnn** [comment]
Do modules work with androidx? More specifically is there a way to have the generated java, generate using androidx? This was half of the problem I mentioned above.

**Comment by sjudd** [comment]
#3184 or #3606 might be relevant. As far as I know it will compile aside from the property mentioned in #3606
