### ISSUE TITLE
 onException: com.bumptech.glide.load.engine.GlideException: Failed to load resource

### ISSUE THREAD

**Issue by krisai** [bumptech/glide#3616]
W/Glide: Load failed for http:https://t00img.yangkeduo.com/goods/images/2018-09-11/1652dc1065082415d12da181d7fec7b9.jpeg with size [1080x825]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 2 causes:
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.net.UnknownHostException: Unable to resolve host "https": No address associated with hostname
      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class java.net.UnknownHostException: Unable to resolve host "https": No address associated with hostname
I/Glide: Root cause (1 of 2)
    Root cause (2 of 2)
D/onLoadFailed: onException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 2 causes:
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
     call GlideException#logRootCauses(String) for more detail  model:http:https://t00img.yangkeduo.com/goods/images/2018-09-11/1652dc1065082415d12da181d7fec7b9.jpeg isFirstResource: true
W/Glide: Load failed for http:https://t00img.yangkeduo.com/goods/images/2018-09-11/1652dc1065082415d12da181d7fec7b9.jpeg with size [1080x825]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 2 causes:
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.net.UnknownHostException: Unable to resolve host "https": No address associated with hostname
      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.net.UnknownHostException(Unable to resolve host "https": No address associated with hostname)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class java.net.UnknownHostException: Unable to resolve host "https": No address associated with hostname
I/Glide: Root cause (1 of 2)

**Comment by sjudd** [comment]
Your url isn't formatted correctly: `http:https://t00img.yangkeduo.com/goods/images/2018-09-11/1652dc1065082415d12da181d7fec7b9.jpeg`

**Comment by xyznaveen** [comment]
Not working for me too.

@sjudd the issue exists even when the url is valid.

P.S: I've refactored my code!

**Comment by mahdit83** [comment]
I got same but just you cause2 as just one cause!

**Comment by ReactorboY** [comment]
same problem for me

**Comment by GreatDongsong** [comment]
same problem for me

**Comment by Pbansal09** [comment]
I am also unable to download one image. Reason 
  Failed to load resource java.net.UnknownHostException
