### ISSUE TITLE
Request for comments on custom placeholder/thumbnail loading

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#362]
**Glide Version/Integration library (if any)**: 3.5.2
**Device/Android Version**: N/A
**Issue details/Repro steps**: I was trying to display an image with an SVG placeholder while it's loading.

**Before**: So far I was using a hand-crafted Weak HashMap cache for `Picture`s rendered from SVGs, and wrapped that in a `PictureDrawable` when I needed a `.placeholder`. Sadly this has a drawback of requiring `layerType="software"` on the `ImageView`, but I was able to use the `.placeholder(Drawable)` Glide API.

**After**: Yesterday while looking for a memory leak and investigating slow scrolling I realized that the `layerType="software"` on a hardware accelerated phone is really bad, it renders a drawing cache to create the display list, duplicating the `Bitmap` in memory. So I changed my SVG approach: the still loading from `@RawRes`, but I'm decoding them as Bitmap of a given size. This allows for `RESULT` caching. This made the list scroll crazy fast and no GC anywhere, because of `BitmapPool`, yay!

**Comments/Questions**
Note that I had to transition to the `.thumbnail` API. (#262)
Sadly, the `.thumbnail` drives what the outer request is allowed to be, because the thumb is more special a constrained. (#107)
Is there any difference between two versions other than the `.crossFade` VS `.animate` and that weird `.decoder` construction?
What do you think in general about the two approaches?
Can you think of a simpler way of doing OPTION 2, mostly because of crossfade?
How do I know which outer `.xxx()` calls are passed to the `thumbnail` request?
Will I ever see the `.placeholder`?

**Glide load line**:
```
private void loadImage(ImageView image, @RawRes int typeID, String imagePath) {
	Context context = image.getContext();
	BitmapPool pool = Glide.get(context).getBitmapPool();

	// OPTION 1 Bitmap
	Glide
		.with(image.getContext())
		.load(imagePath)
		.asBitmap()
		.animate(android.R.anim.fade_in)
		.placeholder(R.drawable.image_loading)
		.error(R.drawable.image_error)
		.thumbnail(Glide
			.with(context)
			.load(typeID)
			.asBitmap()
			.imageDecoder(new SvgBitmapDecoder(pool)) // implements ResourceDecoder<InputStream, Bitmap>
		)
		.listener(new LoggingListener<String, Bitmap>("image"))
		.into(image)
	;

	// OPTION 2 GlideDrawable
	Glide
		.with(image.getContext())
		.load(imagePath)
		.crossFade()
		.placeholder(R.drawable.image_loading)
		.error(R.drawable.image_error)
		.thumbnail(Glide
			.with(context)
			.load(typeID)
			.decoder(new GifBitmapWrapperResourceDecoder(
			        	new ImageVideoBitmapDecoder(
			        		new SvgBitmapDecoder(pool),
			        		null /*fileDescriptorDecoder*/
			        	),
			        	// just to satisfy GifBitmapWrapperResourceDecoder.getId() which throws NPE otherwise
			        	new GifResourceDecoder(context, pool),
			        	pool
			        )
			)
		)
		.listener(new LoggingListener<String, GlideDrawable>("image"))
		.into(image)
	;
}
```

Appendix `SvgBitmapDecoder`:
```
import com.caverock.androidsvg.*;

public class SvgBitmapDecoder implements ResourceDecoder<InputStream, Bitmap> {
	private final BitmapPool bitmapPool;

	public SvgBitmapDecoder(Context context) {
		this(Glide.get(context).getBitmapPool());
	}

	public SvgBitmapDecoder(BitmapPool bitmapPool) {
		this.bitmapPool = bitmapPool;
	}

	public Resource<Bitmap> decode(InputStream source, int width, int height) throws IOException {
		try {
			SVG svg = SVG.getFromInputStream(source);
			Bitmap bitmap = findBitmap(width, height);
			Canvas canvas = new Canvas(bitmap);
			svg.renderToCanvas(canvas);
			return BitmapResource.obtain(bitmap, bitmapPool);
		} catch (SVGParseException ex) {
			throw new IOException("Cannot load SVG from stream", ex);
		}
	}

	private Bitmap findBitmap(int width, int height) {
		Bitmap bitmap = bitmapPool.get(width, height, Config.ARGB_8888);
		if (bitmap == null) {
			bitmap = Bitmap.createBitmap(width, height, Config.ARGB_8888);
		}
		return bitmap;
	}

	@Override
	public String getId() {
		return "";
	}
}
```

**Comment by sjudd** [comment]
> Is there any difference between two versions other than the .crossFade VS .animate and that weird .decoder construction?

The second version will display an animated GIF (for the main request) if given one, the first version will only display the first frame. The second one is also uglier :).

> What do you think in general about the two approaches?

If you're not trying to allow animated GIFs, asBitmap() is certainly cleaner. In Glide 4.0, [loading SVGs as Drawables][1] or as Bitmaps will get dramatically easier because you will just need to register the single decoder once rather than having to apply a series of wrapping decoders for every load.

> Can you think of a simpler way of doing OPTION 2, mostly because of crossfade?

I think you might be able to skip the GifBitmapWrapperResourceDecoder if you write a smaller wrapping class that just returns a GlideDrawable. Otherwise, no I think that's as simple as it gets with Glide 3.

> How do I know which outer .xxx() calls are passed to the thumbnail request?

Almost none of them are. The only two that are applied are animations and overrides, and then only if they're not explicitly set on the thumbnail request. 

> Will I ever see the .placeholder?

You should see the placeholder until the thumbnail load completes. I think it may be undefined though if the thumbnail request and the main request have different placeholders set. 

[1]: https://github.com/bumptech/glide/blob/4.0a/samples/svg/src/main/java/com/bumptech/svgsample/app/MainActivity.java#L39

**Comment by TWiStErRob** [comment]
In the end I gave up on the idea of thumbnail SVGs, it was too complex and mostly never showed up because I was loading local Files. I rather implemented without thumb or placeholder:
```
if (hasImage) { Glide.....load(image); } else { Glide.....load(svg); }
```
