### ISSUE TITLE
SVG issue with shorthand hexadecimal colors

### ISSUE THREAD

**Issue by sdeff** [bumptech/glide#3620]
I’d like to render SVG assets which use the short hex format as fill color and just discovered the following issue with Glide (4.9.0): https://github.com/bumptech/glide/issues/3094#issuecomment-390356207

Can I set Glide to accept the short hex colors or is there a workaround to avoid changing every SVG file to the six digits hex format?

**Comment by BigBadaboom** [comment]
Assuming that you are using AndroidSVG for the SVG rendering, make sure that you are using AndroidSVG version 1.3 or later.  Version 1.2 had a bug with shorthand hes colours.

http://bigbadaboom.github.io/androidsvg/release-1.3.html
