### ISSUE TITLE
(Again) No modelLoader found for SimpleTarget<Drawable> / RequestBuilder. Why not?

### ISSUE THREAD

**Issue by chjan** [bumptech/glide#3621]
Glide 4.9.0 

Please do not close without granting an enlightening comment. We need a solution to set a color filter on a button created with Glide.

Trying to load the background of an ImageButton into a SimpleTarget (deprecated but still in tutorial as the solution), then to tint it with setColorFilter(…), then put it back, we use this code, which result in a Glide exception listed below. 

We repeatedly get this "no model loader found" type of error in various attempts. Is this because the functionality is not there yet, or is there something we have missed regarding Glide configuration? (We have read and reread the tutorials).

PS: a setColorFilter() feature would be great. 

```
Glide.with(activity)
                .load(Glide.with(currentButtonView).asDrawable())
                .into(new SimpleTarget<Drawable>() {
                   @Override
                    public void onResourceReady(@NonNull Drawable resource,
                                                @Nullable Transition<? super Drawable> transition) {

                        //set green tint on Target 
                        resource.setColorFilter(0xFFCCFFFF, PorterDuff.Mode.MULTIPLY);

                        //put it back, now having green tint
                        Glide.with(activity)
                                .load(resource)
                                .diskCacheStrategy(DiskCacheStrategy.NONE)
                                .error(Glide.with(activity).load(R.drawable.ic_delete))
                                .override(350,350)
                                .into((ImageButton)currentButtonView);
                    }
                });
```

THE EXCEPTION:
E/GlideExecutor: Request threw uncaught throwable
    com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: com.bumptech.glide.RequestBuilder@2e8dbf7f
        at com.bumptech.glide.Registry.getModelLoaders(Registry.java:588)
        at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:205)
        at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:223)
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:44)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:276)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

**Comment by sjudd** [comment]
I think you just want a Transformation: http://bumptech.github.io/glide/doc/transformations.html#custom-transformations. That can set your color filter.

I'm not sure what you're trying to load here: `.load(Glide.with(currentButtonView).asDrawable())`. The Drawable from the view? If so that's not generally safe or supported. You could pass in a new resource id or a new Drawable from the view, but extracting an existing Drawable from a View that's loaded with Glide leads to weird bugs and resource re-use errors.

**Comment by chjan** [comment]
@sjudd, no I am loading a R.drawable into a R.id view in a normal fashion. Among 140 buttons, the user might select one of them, thus it becomes tinted  (= selected). Since glide do not offer a top-api for that, we found a hybrid in using normal android for the tinted button, i.e one line of code view.setColorFilter, then Glide for the other 139. As a button then is de-selected, Glide takes over again on that button. This works well for a few days now, also regarding OOM issues, but it underlines that .setColorFilter (and similar features that are  part of normal Android) would be a super add on in  Glide (feature request!). I really want to avoid going into complexity in Glide just for this simple feature. I want to be a "stupid" user of Glide. Beyond that, we use Glide for more complex features like merging grapical elements etc, but that is another type of usage than replacing Android for inflating  buttons.

**Comment by sjudd** [comment]
What about setting the color filter on the View itself? https://developer.android.com/reference/android/widget/ImageView.html#setColorFilter(int,%20android.graphics.PorterDuff.Mode)

**Comment by chjan** [comment]
yes, perhaps a good idea. Will check. I maybe falsely have assumed that Glide "has control" on the view, ie that I could not setColorFilter on the view inflated by Glide.

**Comment by chjan** [comment]
@sjudd: Confirmative that setting color filter on view is a viable way. Perhaps add a short note in your tutorials that using Glide does not disable use of this and similar features on the view? At least, this was my misunderstanding.

**Comment by sjudd** [comment]
Glide only controls the image drawable portion of the view.

Is there a place in the documentation you looked where you might suggest
adding this line?

**Comment by chjan** [comment]
@sjudd, afraid not. But high up in the intro strikes my mind! Add "you can still use view manipulative methods" or similar.
