### ISSUE TITLE
How to upgrade from version 3.7.0 to the version above 4.9.0? When you try to update the library gives a compiling error.

### ISSUE THREAD

**Issue by DinaDurykina** [bumptech/glide#3624]
Hi,
I am making an application based on an open source project that in turn uses 'com.github.bumptech.glide:glide:3.7.0'. If I try to update the library, an error occurs. Can you please tell me how to upgrade to the new version? 

private static void gif(JSONObject component, View view, Context context){
        Object new_url = JasonImageComponent.resolve_url(component, context);
        Glide
            .with(context)
            .load(new_url)
            .asGif()
            .diskCacheStrategy(DiskCacheStrategy.SOURCE)
            .into((ImageView)view);
    }
    private static void rounded(JSONObject component, View view, final float corner_radius_float, final Context context){
        Object new_url = JasonImageComponent.resolve_url(component, context);
        try {
            Glide
                .with(context)
                .load(new_url)
                .asBitmap()
                .fitCenter()
                .into(new BitmapImageViewTarget((ImageView)view) {
                    @Override
                    protected void setResource(Bitmap res) {
                        RoundedBitmapDrawable bitmapDrawable =
                                RoundedBitmapDrawableFactory.create(context.getResources(), res);
                        bitmapDrawable.setCornerRadius(corner_radius_float);
                        view.setImageDrawable(bitmapDrawable);
                    }
                });
        } catch (Exception e) {
            Log.d("Warning", e.getStackTrace()[0].getMethodName() + " : " + e.toString());
        }
    }
import com.bumptech.glide.load.resource.drawable.GlideDrawable; - it is not
import com.bumptech.glide.request.animation.GlideAnimation; 
import com.bumptech.glide.request.target.SimpleTarget; - not used
.asGif() - it is not
SOURCE - 
.asBitmap()

and
 Glide.with(context).load(bs)
                    .into(new SimpleTarget<GlideDrawable>() {
                @Override
                public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                    ((ImageView)view).setImageDrawable(resource);
                }
            });

Glide.with(context).load(bs)
                    .into(new SimpleTarget<GlideDrawable>() {
                @Override
                public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                    ((ImageView)view).setImageDrawable(resource);
                }
            });
GlideDrawable - it is not
SimpleTarget - not used

and
DiskCacheStrategy cacheStrategy = DiskCacheStrategy.RESULT;
                                    // gif doesn't work with RESULT cache strategy
                                    // TODO: Check with Glide V4
                                    if (background.matches(".*\\.gif")) {
                                        cacheStrategy = DiskCacheStrategy.SOURCE;
DiskCacheStrategy.RESULT - 
DiskCacheStrategy.SOURCE - no constant

and

with(JasonViewActivity.this).load(bs).into(new SimpleTarget<GlideDrawable>() {
                                        @Override
                                        public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                                            sectionLayout.setBackground(resource);
                                        }
                                    });

 Glide
                                .with(this)
                                .load(JasonImageComponent.resolve_url(c, JasonViewActivity.this))
                                .asBitmap()
                                .into(new SimpleTarget<Bitmap>(100, 100) {
                                    @Override
                                    public void onResourceReady(Bitmap resource, GlideAnimation glideAnimation) {
                                        AHBottomNavigationItem tab_item = bottomNavigation.getItem(index);
                                        bottomNavigationItems.put(Integer.valueOf(index), tab_item);
                                        Drawable drawable = new BitmapDrawable(getResources(), resource);
                                        tab_item.setDrawable(drawable);
                                        tab_item.setTitle(text);

GlideAnimation - not
.asBitmap() - 

I'm sorry if I still ask the wrong question, I study and work to become better.

**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/migrating.html
