### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by SZn007** [bumptech/glide#3629]
**4.9.0**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Stack trace / LogCat**:
```java
#2 main
java.lang.NullPointerException
Null reference used for synchronization (monitor-enter)

1 com.bumptech.glide.load.engine.EngineResource.release(SourceFile:107)
2 com.bumptech.glide.load.engine.Engine.release(SourceFile:286)
3 com.bumptech.glide.request.SingleRequest.releaseResource(SourceFile:340)
4 com.bumptech.glide.request.SingleRequest.clear(SourceFile:330)
5 com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(SourceFile:79)
6 com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(SourceFile:66)
7 com.bumptech.glide.RequestManager.untrack(SourceFile:630)
8 com.bumptech.glide.RequestManager.untrackOrDelegate(SourceFile:598)
9 com.bumptech.glide.RequestManager.clear(SourceFile:594)
10 com.bumptech.glide.request.target.PreloadTarget.clear(SourceFile:57)
11 com.bumptech.glide.request.target.PreloadTarget$1.handleMessage(SourceFile:25)
12 android.os.Handler.dispatchMessage(Handler.java:102)
13 android.os.Looper.loop(Looper.java:164)
14 android.app.ActivityThread.main(ActivityThread.java:6906)
15 java.lang.reflect.Method.invoke(Native Method)
16 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
17 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
```

**Comment by joimxjtuse** [comment]
it looks like that this commit https://github.com/bumptech/glide/commit/53438b90f982d27652c2bae7cd9daf9be8d5a03a?w=1 . fix this NPM crash.  is it? @judds

**Comment by joimxjtuse** [comment]
it looks like that this commit https://github.com/bumptech/glide/commit/53438b90f982d27652c2bae7cd9daf9be8d5a03a?w=1 . fix this NPM crash.  is it? @judds

**Comment by SZn007** [comment]
then I can only repack to 4.7.1 to fix the problem now?

**Comment by sjudd** [comment]
That looks plausible. 

You could also use the latest snapshot: http://bumptech.github.io/glide/dev/snapshots.html

**Comment by lina1** [comment]
We are facing the same issue while we are using glide Version 4.9. Please confirm which version has fixed this issue. Because 4.9 seems to be the latest one.

**Comment by juliocatano** [comment]
I have the same issue in my project:
Null reference used for synchronization (monitor-enter)
       at com.bumptech.glide.load.engine.EngineResource.release + 107(EngineResource.java:107)

**Comment by AshishAccedo** [comment]
Got same issue while using below libs:

   api 'com.github.bumptech.glide:glide:4.9.0'
    api 'com.github.bumptech.glide:annotations:4.9.0'
    api 'com.github.bumptech.glide:okhttp3-integration:4.9.0'




Fatal Exception: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
       at com.bumptech.glide.load.engine.EngineResource.release + 107(EngineResource.java:107)
       at com.bumptech.glide.load.engine.Engine.release + 286(Engine.java:286)
       at com.bumptech.glide.request.SingleRequest.releaseResource + 340(SingleRequest.java:340)
       at com.bumptech.glide.request.SingleRequest.clear + 330(SingleRequest.java:330)
       at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle + 79(RequestTracker.java:79)
       at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle + 66(RequestTracker.java:66)
       at com.bumptech.glide.RequestManager.untrack + 630(RequestManager.java:630)
       at com.bumptech.glide.RequestManager.untrackOrDelegate + 598(RequestManager.java:598)
       at com.bumptech.glide.RequestManager.clear + 594(RequestManager.java:594)
       at com.bumptech.glide.RequestBuilder.into + 654(RequestBuilder.java:654)
       at com.bumptech.glide.RequestBuilder.into + 716(RequestBuilder.java:716)

**Comment by nickming** [comment]
I have the same issue in my project when I update to 4.9

**Comment by AshishAccedo** [comment]
Why this issue status is closed, did anyone tried below version? where it seems looking fixed: 

http://bumptech.github.io/glide/dev/snapshots.html

**Comment by jocoders** [comment]
Any news? I have the same issue on my app from crashlytics
`
Fatal Exception: java.lang.NullPointerException Null reference used for synchronization (monitor-enter) com.bumptech.glide.load.engine.EngineResource.release
`
Please let me know.
