### ISSUE TITLE
Without calling .override() memory cache doesn't work

### ISSUE THREAD

**Issue by Malachiasz** [bumptech/glide#3630]
Glide 4.9.0 stable. I am using RecyclerView preloading. Images are preloaded from memory only if in my RequestOptions I call .override(size). It shouldn't be necessary, but when I won't, then in the log visible below I see that image is loaded from DISK_CACHE and never from MEMORY_CACHE.

```
public ListGlideRequestBuilderProvider(
        requestOptions = new RequestOptions()
            .override(thumbSize)
            .transform(new MultiTransformation<>(
                new CenterCrop(),
                new RoundedCorners(fragment.getContext().getResources().getDimensionPixelSize(roundedCornerRadiusRes))
            ));

            requestOptions.placeholder(placeholderResId);
            requestOptions.format(DecodeFormat.PREFER_RGB_565);
    }

    public RequestBuilder<Drawable> provideGlideRequestBuilder(@NonNull String lowResThumbnailUrl, @NonNull String highResThumbnailUrl) {
        RequestBuilder<Drawable> thumbRequestBuilder = requestManager
            .load(new CachingGlideUrl(headerProvider, lowResThumbnailUrl, lowResThumbSize))
            .apply(requestOptions);

        return requestManager
            .load(new CachingGlideUrl(headerProvider, highResThumbnailUrl, thumbSize))
            .thumbnail(thumbRequestBuilder)
            .apply(requestOptions);
    }
```

usage in Adapter:

```
    override fun getPreloadRequestBuilder(item: Resource): RequestBuilder<*>? {
        if (!TextUtils.isEmpty(item.thumbnailUri)) {
            val lowRestThumbnail = ThumbnailUtils.buildThumbnailUrl(10)!!
            val highResThumbnail = ThumbnailUtils.buildThumbnailUrl(100)!!
            return listGlideRequestBuilderProvider.provideGlideRequestBuilder(lowRestThumbnail, highResThumbnail)
        } else {
            return null
        }
    }
```

and in ViewHoder:

```      String lowRestThumbnail = ThumbnailUtils.buildThumbnailUrl(10);
        String highResThumbnail = ThumbnailUtils.buildThumbnailUrl(100);

        requestBuilderProvider.provideGlideRequestBuilder(lowRestThumbnail, highResThumbnail)
            .transition(DrawableTransitionOptions.withCrossFade())
            .listener(new RequestListener<Drawable>() {
                @Override
                public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                    if (DEBUG_LOG) {
                        Timber.e("Thumbnail with resourceId: " + resource.getResourceId() + " failed");
                    }

                    return false;
                }

                @Override
                public boolean onResourceReady(Drawable resource2, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                    if (DEBUG_LOG) {
                        Timber.d("Thumbnail with resourceId: " + resource.getResourceId() + " loaded image from: " + dataSource);
                    }
                    return false;
                }
            })
            .into(preview);
```

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/caching.html#cache-keys
http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses

**Comment by Malachiasz** [comment]
Ok, I see it's documented? But why would you do that if you can use original image size to be used in memory cache?

**Comment by sjudd** [comment]
I'm a little unclear which one of these requests you're using with preload, but in general, its' hard to determine if an already in memory image is suitable for a new request. Sizes, transformations, Bitmap configurations as well as any custom settings used for the request may make it unsafe to use for a new request.

**Comment by Malachiasz** [comment]
Why it's hard? As I understand it's about comparing few properties. Size is one of them. If it's not set  as part of RequestOptions in preloaded as well as in target request then in both cases the size should be set either as UNKNOWN or as the ORIGINAL_SIZE. In both cases it's the same thus memory cache can be used.

**Comment by Malachiasz** [comment]
Moreover I have na use case, that Glide downloads low resolution thumbnails which it upscales because of RequestOptions().override(thumbSize). Because of that I am facing 2 issues:

- upscaled image are blurry. I would like to get raw bitmap from Glide and upscale it with my own algorithm
- I am guessing that glide keeps in memory upscaled image - so it wastes more memory than necessary

If memory caching would work then I could omit override() and would not have this problem. Would it be a solution to pass into override() original image size. Would the lib noticed that resizing is not needed?

**Comment by sjudd** [comment]
I mentioned a few reasons why it's not trivial before, there's a lot of things that go into a cache key that  could be hard to understand whether or not they're actually required.

You can pick a different transformation and/or downsampling strategy to avoid upscaling if you'd like, or specify your own downsampling strategy and/or transformation to customize it.

If you pass the original size into override then you'll definitely use extra memory because you'll be storing the entire image without any kind of size bound. Sometimes that's ok if you're confident that you've bounded your sizes via some other mechanism (a remote thumbnailing library or some other source you control), but it's often dangerous.

**Comment by joimxjtuse** [comment]
i think add ".diskCacheStrategy(DiskCacheStrategy.SOURCE)" may solve the bug,   just you get error width / height.
