### ISSUE TITLE
RequestManagerFragment leaking after onDestroy() 

### ISSUE THREAD

**Issue by pyricau** [bumptech/glide#3631]
I don't use Glide but as I was looking into LeakCanary 2 bug reports I noticed what may be a Glide leak inside a heap dump from a 3rd party. I don't know which version it is, but `master` looks like it still has the leak .  I'll go into the details later, this doesn't "look" like a bug in Glide but sometimes Android sucks.

Found here: https://github.com/square/leakcanary/issues/1173#issuecomment-487585302

Here's the leak trace:

```
 ┬
 ├─ android.app.LoadedApk$ReceiverDispatcher$InnerReceiver
 │    Leaking: NO (it's a GC root)
 │    ↓ LoadedApk$ReceiverDispatcher$InnerReceiver.mDispatcher
 │                                                 ~~~~~~~~~~~
 ├─ java.lang.ref.WeakReference
 │    Leaking: UNKNOWN
 │    ↓ WeakReference.referent
 │                    ~~~~~~~~
 ├─ android.app.LoadedApk$ReceiverDispatcher
 │    Leaking: UNKNOWN
 │    ↓ LoadedApk$ReceiverDispatcher.mReceiver
 │                                   ~~~~~~~~~
 ├─ com.bumptech.glide.manager.DefaultConnectivityMonitor$1
 │    Leaking: UNKNOWN
 │    Anonymous subclass of android.content.BroadcastReceiver
 │    ↓ DefaultConnectivityMonitor$1.this$0
 │                                   ~~~~~~
 ├─ com.bumptech.glide.manager.DefaultConnectivityMonitor
 │    Leaking: UNKNOWN
 │    ↓ DefaultConnectivityMonitor.listener
 │                                 ~~~~~~~~
 ├─ com.bumptech.glide.RequestManager$RequestManagerConnectivityListener
 │    Leaking: UNKNOWN
 │    ↓ RequestManager$RequestManagerConnectivityListener.this$0
 │                                                        ~~~~~~
 ├─ com.bumptech.glide.RequestManager
 │    Leaking: UNKNOWN
 │    ↓ RequestManager.treeNode
 │                     ~~~~~~~~
 ├─ com.bumptech.glide.manager.RequestManagerFragment$FragmentRequestManagerTreeNode
 │    Leaking: UNKNOWN
 │    ↓ RequestManagerFragment$FragmentRequestManagerTreeNode.this$0
 │                                                            ~~~~~~
 ╰→ com.bumptech.glide.manager.RequestManagerFragment
 ​     Leaking: YES (RequestManagerFragment#mFragmentManager is null)
```

This leak would normally be dismissed by LeakCanary because InnerReceiver holds a weak reference to ReceiverDispatcher, but I changed that behavior here to investigate reports of LeakCanary not finding leaks.

Here's what I think is going on:

* DefaultConnectivityMonitor has a strong reference to its listener, which itself ends up holding on to RequestManagerFragment / SupportRequestManagerFragment
* DefaultConnectivityMonitor registers a broadcast receiver for connectivity and unregisters it when the fragment its associated with gets stopped.
* Unfortunately, there seems to be a lag between when DefaultConnectivityMonitor calls unregister() and when the reference to the broadcast receiver is cleared. That lag being of at least 5 seconds, possibly more. Something is making that weak reference stay active (I wonder if repeated connectivity changes could cause that)
* The broadcast receiver is held, so DefaultConnectivityMonitor is held and the fragment leak.

Suggested fix: make DefaultConnectivityMonitor.connectivityReceiver a static inner class, add a nullable `monitor` field to it and set it / unset it when calling register / unregister.

**Comment by sjudd** [comment]
If it's a brief time based leak it's probably not adding a lot of memory pressure.

In general it would make more sense to have a single global connectivity receiver. That would fix one or two other issues as well. If anyone is interested in fixing this, that's the route I'd go. I'd be happy to review a pull request.

**Comment by sagarsuri29** [comment]
I also faced the same problem with DialogFragments. :(

**Comment by yashasvigirdhar** [comment]
I am also facing the exact same issue. Do we have any workarounds for this?

**Comment by pyricau** [comment]
@yashasvigirdhar @sagarsuri29 you should open a new issue.
