### ISSUE TITLE
How to cache local file under remote url key?

### ISSUE THREAD

**Issue by ursusursus** [bumptech/glide#3632]
Hi guys, I have this weird use case of uploading images in a _chat app_ .

When I want to upload an image (from local storage, to server) I insert a message into local database with state = sending.

So while state == sending; I display the local image via `glide.load(File(...))`, (if state == sent `glide.load( remote url..)`) all works

However now after the upload is completed, the api returns the uploaded message json object, which contains a url to that image;

The given message with state == sending, is now updated with the message returned from api, giving it state sent;

This however not means when recycler view is refreshed, the remote url image is downloaded -- for an image I already have locally (and just uploaded); I know I can hack around and display local manually but that is going to be problematic; and I was wondering **if I could somehow feed glide that local image _under the remote url as key_, so the downloading when load(url) is avoided?**

**Comment by sjudd** [comment]
This is tricky to do. It could probably be done with a custom ModelLoader that decides which to use. It would probably be easier with a wrapping Model object that contained either the local file or remote url or both.

It's hard to provide specific instructions, but you could look through http://bumptech.github.io/glide/tut/custom-modelloader.html

**Comment by Rotemy** [comment]
Any news regarding this? this is such normal use case I just don't understand how there isn't a standard solution.

**Comment by Rotemy** [comment]
@sjudd Hey, we would love to be able to replace a local file with remote URL key. I'm guessing that with the old `using` API we would able to do it but now it is just too complicated.

Just to be sure you understand what we need. Just an API like this:

`Glide.with(context).load(remoteURL).using(originalFile).submit();`;

wdyt?

**Comment by mohammadzzz** [comment]
@Rotemy Hey man. I have the same problem here. Did you find any solution to it??

**Comment by Rotemy** [comment]
unfortunately no. My Android users need to live with this annoying behavior.

**Comment by mohammadzzz** [comment]
Well, I don't know why this issue is closed then?? I'm trying to write a custom ModelLoader just like @sjudd said. I'll let you know if I had any luck

**Comment by Rotemy** [comment]
> Well, I don't know why this issue is closed then?? I'm trying to write a custom ModelLoader just like @sjudd said. I'll let you know if I had any luck 

Great please do. Good luck

**Comment by KomalChugh** [comment]
@mohammadzzz were you able to solve this issue?

**Comment by mohammadzzz** [comment]
@KomalChugh Hey mate. Unfortunately no....I came up with another workaround that required some API change and solved it in that way.

**Comment by KomalChugh** [comment]
> @KomalChugh Hey mate. Unfortunately no....I came up with another workaround that required some API change and solved it in that way.

Can you please share your solution if possible.
