### ISSUE TITLE
Question: Aoes it make sense to set priority of thumbnails and preloaded images in RecyclerView?

### ISSUE THREAD

**Issue by Malachiasz** [bumptech/glide#3633]
When having grid of images, like google Photos:

1. Does it make sense to set thumbnail load priority as IMMEDIATE and high resolution image as NORMAL in Grid RecyclerView screen in order to load thumbnails of all elements on the screen before their high resolution version starts loading? Will it work like that in Glide?

2. Is it necessary to set Priority.LOW for ListPreloader.getPreloadRequestBuilder() and Priority.IMMEDIATE for elements of the list visible on the screen in order to indicate to Glide, that screen visible elements have priority over other? Or Glide takes it into account already? Or it won't work?

I am talking about priorities as described here:
https://futurestud.io/tutorials/glide-request-priorities
and thumbnails as described here (with different request)
https://futurestud.io/tutorials/glide-thumbnails

**Comment by sjudd** [comment]
1. Sure you can do that. If you actually pass in the thumbnail request, Glide will automatically increment the priority of the thumbnail to be one higher than the parent request, unless you've manually set a priority for the thumbnail.

2. I don't believe any priority is set for preload: https://github.com/bumptech/glide/blob/fbd31f41d164c3b93248556d2601da33d13f2c30/library/src/main/java/com/bumptech/glide/RequestBuilder.java#L797.  The one disadvantage of reducing the Priority is that any higher priority request you make matching the lower priority request will end up running at the lower priority. So if you happen to try to load an image in your UI while it's in the process of being preloaded, you might get priority inversion. Not particularly likely most of the time, but something to be aware of.
