### ISSUE TITLE
RequestOptions transform lead the image out of shape

### ISSUE THREAD

**Issue by Longalei** [bumptech/glide#3634]
**Glide Version**:4.0.0

**Integration libraries**:OkHttp3  - 4.0.0

**Device/Android Version**:All Device

**Issue details / Repro steps / Use case background**: 
> when I load the image.it cause the image out of shape.the source img url is [here](https://web-s3.alo7.com/public/wxparentapp/operation/parent_app_op_20190225161001.png)
and the final image is [here](https://github.com/Longalei/Document/blob/master/art/Screenshot_20190430-200037.png)

``` RequestOptions requestOptions = new RequestOptions();
                requestOptions.transform(
                        new MultiTransformation<>(new FitCenter(), new RoundedCorners(50)));
                Glide.with(App.getContext()).load(topOperationMessage.getImageUrl())
                        .apply(requestOptions).into(contentImage);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    tools:ignore="ContentDescription">

    <ImageView
        android:id="@+id/operation_message_image"
        android:layout_width="280dp"
        android:layout_height="372dp"
        android:layout_gravity="center_horizontal"
        tools:src="@drawable/album_cover_holder" />
</FrameLayout>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Let me know if you can reproduce on a recent version.

**Comment by Longalei** [comment]
okay,In the version 4.9. It's ended.I will compare the version and find what result it.@sjudd
