### ISSUE TITLE
Glide image resets when OnBackPressed

### ISSUE THREAD

**Issue by shahzi8285** [bumptech/glide#3637]
I am loading image with glide. but problem is,when we press back button loaded image clear from the view .I am facing this issue wherever I load image either on activity image view or in recyclerview.

    implementation 'com.github.bumptech.glide:glide:4.9.0'

API 19

I am loading image with
`GlideApp.with(this)
                .load(url)
                .into(mToolbarAvatar);`

**Comment by leocorder** [comment]
Same problem here, using glide in RecyclerView. Version 4.9.0

**Comment by omeraslam-citrusbits** [comment]
Facing same issue, any fix? @leocorder @shahzi8285

**Comment by leocorder** [comment]
@omeraslam-citrusbits I'm using version 4.11.0 now and not facing this issue anymore.

build.gradle:
```gradle
def glide_version = "4.11.0"
implementation "com.github.bumptech.glide:glide:$glide_version"
kapt "com.github.bumptech.glide:compiler:$glide_version"
```

Loading ImageView (kotlin code):
```kotlin
fun loadImg(imageView: ImageView, imgPath: String?) {
    if (!TextUtils.isEmpty(imgPath)) {
        val c = imageView.context
        if (isValidContextForGlide(c)) {
            GlideApp.with(c)
                    .load(Uri.parse(imgPath))
                    .placeholder(R.drawable.default_image)
                    .into(imageView)
        }
    } else imageView.setImageResource(R.drawable.default_image)
}

fun isValidContextForGlide(context: Context?): Boolean {
    if (context == null) return false
    if (context is Activity) {
        val activity = context as Activity? ?: return false
        if (activity.isFinishing) return false
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 && activity.isDestroyed) return false
    }
    return true
}
```

**Comment by omeraslam-citrusbits** [comment]
@leocorder i have tried 

`implementation 'com.github.bumptech.glide:glide:4.12.0'
    kapt 'com.github.bumptech.glide:compiler:4.12.0'` and even `implementation 'com.github.bumptech.glide:glide:4.11.0'
    kapt 'com.github.bumptech.glide:compiler:4.11.0'` 

 but this issue was not fixed.
 
I have figured out the problem and the problem was in `Glide.with()` i was passing imageview in with, i am able to solve this problem by passing context.
