### ISSUE TITLE
gif flicker when play and frame cross different pictures

### ISSUE THREAD

**Issue by tuomao** [bumptech/glide#3639]
I use glide 4.9 to load gif picture. And I play gif one by one manually. But some times gif flicker.

I use GifDrawable.start to start gif, GirDrawable.setLoopCount to set loop count and GifDrawable.registerAnimationCallback to listen to callback of gif play over.

I am ensure all GifDrawable in the video are different object, and all the imageView are different object.

The Following is the video. 
![ezgif com-resize](https://user-images.githubusercontent.com/4536691/57293637-dee08580-70f7-11e9-8933-90a5896522ed.gif)

**However,When I set BitmapPool size to 0, it never happens.**

**Comment by sjudd** [comment]
This looks like a resource re-use error, see http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors

**Comment by tuomao** [comment]
@sjudd Do you mean this reason？

![image](https://user-images.githubusercontent.com/4536691/57365998-b2d90900-71b8-11e9-8122-3b3873d4ba2f.png)

But I have view the GifDrawable object in the memory. Picture 1-7 are different GifDrawable objects. And the  ImageViews does't hold Bitmap directly, they only hold GifDrawable. The bitmap is managed by StandardGifDecoder and BitmapProvider.

**Comment by tuomao** [comment]
I am sure,I have remove the drawable when request is cleared
The following is the code
`
val target: Target<ResourceType> = if (imageView.visibility == View.VISIBLE) {
            object : ImageViewTarget<ResourceType>(imageView), ITarget {
                override fun setResource(resource: ResourceType?) {
                    imageView.setResource(resource, imageOption.autoPlay)
                }

                override fun onResourceReady(resource: ResourceType, transition: Transition<in ResourceType>?) {
                    // 为了避免View复用出现差错的情况出现兜底
                    if (requestModel != imageView.getTag(R.id.glide_load_request_model)) {
                        BaseImageLoader.EXCEPTION_HANDLER?.onException(IllegalStateException("view miss use"))
                    } else {
                        setResource(resource)
                    }
                }

                override fun onLoadCleared(placeholder: Drawable?) {
                    if (BaseImageLoader.IS_DEBUG) {
                        requestModel.addRequestTrace(ImageRequestTrace.ImageRequestStage.RESOURCE_CLEAR)
                        imageView.setCurrentRequestModel(null)
                    }
                    (imageView.drawable as? Animatable2Compat)?.apply {
                        clearAnimationCallbacks()
                        stop()
                    }
                    super.onLoadCleared(placeholder)
                    requestListener?.onResourceCleared(placeholder)
                }

                override fun clear() {
                    requestManager.clear(this)
                }
            }
        }
`

**Comment by tuomao** [comment]
@sjudd However,When I set BitmapPool size to 0, it never happens.

**Comment by joimxjtuse** [comment]
> I am sure,I have remove the drawable when request is cleared
> The following is the code
> 
> ```
> val target: Target<ResourceType> = if (imageView.visibility == View.VISIBLE) {
>     object : ImageViewTarget<ResourceType>(imageView), ITarget {
>         override fun setResource(resource: ResourceType?) {
>             imageView.setResource(resource, imageOption.autoPlay)
>         }
>         override fun onResourceReady(resource: ResourceType, transition: Transition<in ResourceType>?) {
>             // 为了避免View复用出现差错的情况出现兜底
>             if (requestModel != imageView.getTag(R.id.glide_load_request_model)) {
>                 BaseImageLoader.EXCEPTION_HANDLER?.onException(IllegalStateException("view miss use"))
>             } else {
>                 setResource(resource)
>             }
>         }
>         override fun onLoadCleared(placeholder: Drawable?) {
>             if (BaseImageLoader.IS_DEBUG) {
>                 requestModel.addRequestTrace(ImageRequestTrace.ImageRequestStage.RESOURCE_CLEAR)
>                 imageView.setCurrentRequestModel(null)
>             }
>             (imageView.drawable as? Animatable2Compat)?.apply {
>                 clearAnimationCallbacks()
>                 stop()
>             }
>             super.onLoadCleared(placeholder)
>             requestListener?.onResourceCleared(placeholder)
>         }
> 
>         override fun clear() {
>             requestManager.clear(this)
>         }
>     }
> }
> ```

glide have done "requestModel != imageView.getTag(R.id.glide_load_request_model)" for you"canSetImage()" ,why you do this twice?

**Comment by tuomao** [comment]
> > I am sure,I have remove the drawable when request is cleared
> > The following is the code
> > ```
> > val target: Target<ResourceType> = if (imageView.visibility == View.VISIBLE) {
> >     object : ImageViewTarget<ResourceType>(imageView), ITarget {
> >         override fun setResource(resource: ResourceType?) {
> >             imageView.setResource(resource, imageOption.autoPlay)
> >         }
> >         override fun onResourceReady(resource: ResourceType, transition: Transition<in ResourceType>?) {
> >             // 为了避免View复用出现差错的情况出现兜底
> >             if (requestModel != imageView.getTag(R.id.glide_load_request_model)) {
> >                 BaseImageLoader.EXCEPTION_HANDLER?.onException(IllegalStateException("view miss use"))
> >             } else {
> >                 setResource(resource)
> >             }
> >         }
> >         override fun onLoadCleared(placeholder: Drawable?) {
> >             if (BaseImageLoader.IS_DEBUG) {
> >                 requestModel.addRequestTrace(ImageRequestTrace.ImageRequestStage.RESOURCE_CLEAR)
> >                 imageView.setCurrentRequestModel(null)
> >             }
> >             (imageView.drawable as? Animatable2Compat)?.apply {
> >                 clearAnimationCallbacks()
> >                 stop()
> >             }
> >             super.onLoadCleared(placeholder)
> >             requestListener?.onResourceCleared(placeholder)
> >         }
> > 
> >         override fun clear() {
> >             requestManager.clear(this)
> >         }
> >     }
> > }
> > ```
> 
> glide have done "requestModel != imageView.getTag(R.id.glide_load_request_model)" for you"canSetImage()" ,why you do this twice?

to location a recycle reuse bug，we add this code to exclude the impact of glide.
