### ISSUE TITLE
Stucking when several gifs playing at the same time

### ISSUE THREAD

**Issue by penfeizhou** [bumptech/glide#3643]
In Glide 4 seems when several gifs are playing at the same time, the stucking would happen High probability,espacially in some cheap phones.
The Glide version is 4.9.0
`api "com.github.bumptech.glide:glide:4.9.0"`
The source code shows that all gif frame works on glide animation executor,which is initialed in `GlideExecutor` and the `maximumPoolSize` is set to 1 or 2.

```java
  /**
   * Returns a new cached thread pool that defaults to either one or two threads depending on the
   * number of available cores to use when loading frames of animations.
   */
  public static GlideExecutor newAnimationExecutor() {
    int bestThreadCount = calculateBestThreadCount();
    // We don't want to add a ton of threads running animations in parallel with our source and
    // disk cache executors. Doing so adds unnecessary CPU load and can also dramatically increase
    // our maximum memory usage. Typically one thread is sufficient here, but for higher end devices
    // with more cores, two threads can provide better performance if lots of GIFs are showing at
    // once.
    int maximumPoolSize = bestThreadCount >= 4 ? 2 : 1;

    return newAnimationExecutor(maximumPoolSize, UncaughtThrowableStrategy.DEFAULT);
  }
```
I dont think it is enough for multi gif situation.Please consider this.

**Comment by sjudd** [comment]
You can always customize the size of that pool: http://bumptech.github.io/glide/doc/configuration.html#application-options and http://bumptech.github.io/glide/javadocs/490/com/bumptech/glide/GlideBuilder.html#setAnimationExecutor-com.bumptech.glide.load.engine.executor.GlideExecutor-

**Comment by penfeizhou** [comment]
I saw this.Thank you.
