### ISSUE TITLE
Image disappears when I call notifyItemChanged

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [bumptech/glide#3648]
If I use a transition, the image disappears after calling notifyItemChanged
```
fun ImageView.glideLocalCircle(drawable: Drawable) =
    Glide.with(context)
        .load(drawable)
        .transition(withCrossFade())
        .apply(RequestOptions.circleCropTransform())
        .into(this)
```

If I remove `transition(withCrossFade())`, the image is blinking, but really I want to get the above behavior working.

**Comment by joimxjtuse** [comment]
add donnotAnimate() may solve blink;

show me where you use ImageView, RecyclerView? make sure you haven't call img.setImageDraawable(null) while "onDetachedFromWindow".

**Comment by JavierSegoviaCordoba** [comment]
@joimxjtuse is it not possible with animations? I am not calling setImageDrawable anywhere.
