### ISSUE TITLE
Persistent Caching Issue

### ISSUE THREAD

**Issue by aritraroy** [bumptech/glide#365]
I have used this library and it works perfectly. I have a little requirenent, I am showing a gallery in my app with all images loaded from the device storage. It works great. But I want a way to store the thumbnails in cache so that next time the user loads the gallery, the images can be shown instantly. How can I achieve this?

**Comment by sjudd** [comment]
That's more or less what will happen by default. Glide caches downsampled and transformed results in its disk cache (see [DiskCacheStrategy][1] for other options).

The caveat is that most of your options, your transformation, and width and height must match for there to be a cache hit. See the [caching wiki page][2] for more info.

[1]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/load/engine/DiskCacheStrategy.html.
[2]: https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation

**Comment by aritraroy** [comment]
But it isn't firing any time for my app. Everytime I start the app, This is what I am doing.
Glide.with(context).load(currentItem.getFilePath()).diskCacheStrategy(DiskCacheStrategy.RESULT).crossFade().into(holder.fileThumb);

Is this anything wrong I am doing?

**Comment by sjudd** [comment]
What you have looks reasonable. What are the dimensions of holder.fileThumb? Are they consistent across images/app loads?

Also what version of Glide/Android are you using?

**Comment by aritraroy** [comment]
I am actually displaying a GridView with 3 columns so the thumbnail size is uniform throughout the app. And I am using Glide 3.5.2 on Android Lollipop 5.0.1.

**Comment by sjudd** [comment]
Sorry I dropped the ball here. I don't see anything wrong with your request. The most likely reason why you aren't getting cache hits is that the size is different for the two requests. You can test this by using [``override(width, height)``][1] and see if that fixes the problem. 

If you want to dive in more, you can enable logging in [``Engine``][2] and compare keys between the requests to see what is different:

```
adb shell setprop log.tag.Engine VERBOSE
```

Let us know if there's anything else we can do to help.

[1]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/DrawableRequestBuilder.html#override(int,%20int)
[2]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/Engine.java#L32

**Comment by aritraroy** [comment]
How can the size be different? I have just created a file browser which shows thumbnails of the images and videos? As the size of the files do not change, then how can this problem occur?

And can you give an example on how I can use the override method?

**Comment by TWiStErRob** [comment]
Take you original load line and insert override.
```
Glide.with(context).load(currentItem.getFilePath()).diskCacheStrategy(DiskCacheStrategy.RESULT).crossFade().override(200, 200).into(holder.fileThumb);
```
This will fix the image size to 200x200 (proportionally resized keeping aspect). So regardless of what your layout tells glide, it will always use these dimensions for caching.

If you don't give override, Glide will wait until the target ImageView has a size (laid out) and use those dimensions. Try the debugging Sam suggested.

**Comment by aritraroy** [comment]
Okay. Thanks a lot. I will try this and let you know. 

Btw, the thumbnails of the videos load very slowly? Is there any way to make it faster? I mean we can compromise with a lower quality thumbnail.

**Comment by sjudd** [comment]
Local or remote videos?

**Comment by aritraroy** [comment]
Local videos only. Some images larger than 30MB also takes huge time to load.

**Comment by TWiStErRob** [comment]
30MB is Quad-HD (4k) raw RGBA size...

**Comment by aritraroy** [comment]
Yes. But is there a way to speed up video and large image loading. I just want to load small thumbnails of the, so quality can be compromised.

**Comment by sjudd** [comment]
Ah. The only thing you can do is try using [``loadFromMediaStore(Uri)``][1] with a size less than 512x384.  If there is a media store thumbnail available and the requested size is less than the media store thumb size, then Glide will try to complete the request from the media store thumb. You can use the 

Media store thumbs are often generated lazily on demand, which means there's no guarantee they will be available. ``loadFromMediaStore`` will fall back to just opening the original file if it fails to find a thumbnail. 

Keep in mind for this to work you will want to pass in a [``MediaStoreSignature``][2], and you need to provide media store Uris. Uris from other content providers won't have thumbnails. You may also want to consider using the [``thumbnail()``][3] API to load the smaller media store thumbnail first and then follow it up with the full high quality image.

If you're not using media store uris, or the thumbnails aren't generated, unfortunately we're just limited by Android's standard decoders. You can try to generate thumbs in the background before the user tries to view them, but there isn't much you're going to be able to do to decrease the decode time.

[1]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/RequestManager.html#loadFromMediaStore(android.net.Uri)
[2]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/signature/MediaStoreSignature.html
[3]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/DrawableRequestBuilder.html#thumbnail(com.bumptech.glide.DrawableRequestBuilder)

**Comment by aritraroy** [comment]
Thats a good idea actually. Can you provide an example on how I can use MediaStore uri with Glide?

**Comment by sjudd** [comment]
Something like this:

```java
Glide.with(fragment)
     .loadFromMediaStore(yourMediaStoreUri)
     // You will need to query out the mimeType, date modified, and orientation from the media store.
     .signature(new MediaStoreSignature(mimeType, dateModified, orientation))
     // Override is only necessary if your target dimensions are greater than these.
     .override(512, 384)
     .into(yourImageView);
```

**Comment by aritraroy** [comment]
Thank you so much. I will try this and let you know.

**Comment by PrathameshKesarkar** [comment]
How to do the same for Displaying Video Thumbnail

**Comment by TWiStErRob** [comment]
@PrathameshKesarkar this discussion was about video thumbs.

**Comment by PrathameshKesarkar** [comment]
@TWiStErRob  can u tell me what should I pass in loadFromMediaStore(Uri) cause it is quite confusing to understand

**Comment by PrathameshKesarkar** [comment]
Alright Fixed it was easy  we have to use the Id of the loading Image
here's an example for ppl who would like to know
            Uri uri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, mFolder.getFolder_id().get(position));
This is the Uri you need to pass to loadFromMediaStore(Uri);

**Comment by PrathameshKesarkar** [comment]
@TWiStErRob  
Hey however I am facing a new Issue I don't really know if its really a Glide issue 
So I am actually loading a set of Images inside a nested RecyclerView 

So Whenever a list of Images are Out of scope of Parent RecyclerView I think Glide is still trying to fetch Image for those View so that spams my Stack trace with this error 

SkImageDecoder::Factory returned null
Explicit concurrent mark sweep GC freed 4478(255KB) AllocSpace objects, 12(913KB) LOS objects, 24% free, 15MB/20MB, paused 967us total 55.993ms

So is there anything I can do to stop this spamming .I searched this problem on SO but I can't find any relevant topic.

**Comment by TWiStErRob** [comment]
You need to clear the nested list's items manually. When the outer item gets out of scope Adapter.onViewRecycled or similar is called, get the inner list in that method and set the adapter to null or get each children and `Glide.clear` the `ImageView` inside those children. Take a look at [these issues](https://github.com/bumptech/glide/issues?utf8=✓&q=is%3Aissue+onviewrecycled+) which have similar problems. You should find a lot of information in them.

**Comment by eicm** [comment]
@sjudd regarding your comment up there "Ah. The only thing you can do is try using loadFromMediaStore(Uri) with a size less than 512x384. If there is a media store thumbnail available and the requested size is less than the media store thumb size, then Glide will try to complete the request from the media store thumb."

Is overriding to 512x384 or smaller is still necessary to load media store thumbnails, as the current doc says that fromMediaStore() uses "android.provider.MediaStore.Images.Thumbnails"

**Comment by TWiStErRob** [comment]
You only have to add the `override` if you want to force loading the thumbnail from media store, see `MediaStoreThumbFetcher.ThumbnailStreamOpenerFactory.build`. If the requested size is too big then Glide will decode the source on it's own (falls back to default fetcher that opens the Uri as a stream) which may be slower for high resolution stuff. So the default is that Glide tries to achieve best quailty for requested size, but @aritraroy wanted speed over quailty.

**Comment by eicm** [comment]
Thanks
