### ISSUE TITLE
Glide 4.9.0 lead to GTSUnofficialApisUsageTestCases Failure

### ISSUE THREAD

**Issue by zxingLua** [bumptech/glide#3654]
Glide Version :4.9.0
Android Studio: 
                         implementation 'com.github.bumptech.glide:glide:4.9.0'
                         annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
Test way:
                  run gts -m GtsUnofficialApisUsageTestCases -t com.android.gts.api.UnofficialApisUsageTest#testNonApiReferences

Test fail  log:
                Undefined field ref: com.bumptech.glide.h.c.in:java.io.InputStream from: /vendor/app/btRemoteSetupWizard-release.apk

**Comment by zxingLua** [comment]
Glide Version :4.9.0
Android Studio:
implementation 'com.github.bumptech.glide:glide:4.9.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
Test way:
run gts -m GtsUnofficialApisUsageTestCases -t com.android.gts.api.UnofficialApisUsageTest#testNonApiReferences

Test fail log:
Undefined field ref: com.bumptech.glide.h.c.in:java.io.InputStream from: /vendor/app/btRemoteSetupWizard-release.apk

**Comment by zxingLua** [comment]
Glide Version :4.9.0
Android Studio:
implementation 'com.github.bumptech.glide:glide:4.9.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
Test way:
run gts -m GtsUnofficialApisUsageTestCases -t com.android.gts.api.UnofficialApisUsageTest#testNonApiReferences

Test fail log:
Undefined field ref: com.bumptech.glide.h.c.in:java.io.InputStream from: /vendor/app/btRemoteSetupWizard-release.apk

**Comment by zxingLua** [comment]
Glide Version :4.9.0
Android Studio:
implementation 'com.github.bumptech.glide:glide:4.9.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
Test way:
run gts -m GtsUnofficialApisUsageTestCases -t com.android.gts.api.UnofficialApisUsageTest#testNonApiReferences

Test fail log:
Undefined field ref: com.bumptech.glide.h.c.in:java.io.InputStream from: /vendor/app/btRemoteSetupWizard-release.apk

**Comment by sjudd** [comment]
I'm not sure what `com.bumptech.glide.h.c.in` refers to...

**Comment by hunter-Ding** [comment]
has it solved? what to do?
