### ISSUE TITLE
Ways to make a round image.

### ISSUE THREAD

**Issue by SergeyKharuk** [bumptech/glide#3655]
What is the difference between thoose 2 lines:
.apply(RequestOptions.circleCropTransform())
and
.apply(new RequestOptions().circleCrop())

Which choice is better?

**Comment by sjudd** [comment]
They're identical. circleCropTransform() is just a more fluent version of the same thing.

For that matter you should be able to just call circleCrop() directly on your request in 4.9.0+:

```java
Glide.with(fragment)
  .load(url)
  .circleCrop()
  .into(imageView);
```
