### ISSUE TITLE
How to preload more than one url from getPreloadRequestBuilder?

### ISSUE THREAD

**Issue by LoAlex** [bumptech/glide#3658]
Let say there have a model called "Post", and there have several urls in each "Post" item.
and my question is how to preload more than one url in getPreloadRequestBuilder?

https://bumptech.github.io/glide/int/recyclerview.html

I have referenced above link but seems not suitable from my case.

```
class Post {
   var images: List<Image>
}

class Image {
   var url: String
}

override fun getPreloadItems(position: Int): MutableList<Post> {
    return data?.subList(position, position + 1)?.toMutableList() ?: mutableListOf()
}

override fun getPreloadRequestBuilder(item: Post): RequestBuilder<*>? {
    // desire to preload all the images' url from a "Post" item.
    return GlideApp.with(context).load(item.images)
}
```

**Comment by SharkChao** [comment]
I've come across the same situation, God. Is there a similar solution?
