### ISSUE TITLE
Anti-alias vs FilterBitmap flags

### ISSUE THREAD

**Issue by AlexBlokh** [bumptech/glide#366]
Was playing around with **BitmapPool** and **TransformationUtils** and I see that you are making a drawing scaled bitmap on a canvas with an **ANTI_ALIAS** flag, which is pointless.

There should be a **FILTER_BITMAP** flag.
Here is an [article](http://android-developers.blogspot.com/2014/12/making-performant-watch-face.html) on a dev blog, if somebody needs it.

**Comment by sjudd** [comment]
Thanks for pointing this out, a pull request to fix this would definitely be welcome!
