### ISSUE TITLE
[Bug] Glide is not able to load images 

### ISSUE THREAD

**Issue by dharashahkenya** [bumptech/glide#3663]
**Glide Version**: 4.9.0 [even the one lower by one version than this one]

**Integration libraries**: N/A

**Device/Android Version**: All 

**Issue details / Repro steps / Use case background**: 
I am trying to load, the pins returned by maps api , and even a random url but it doesn't load the image. Glide only returns with an exception failed to load resource, but no other extra detail.

urls used: https://imgs.xkcd.com/comics/mc_hammer_age.png, http://i.imgur.com/DvpvklR.png, and https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(fragment).load(url).into(imageview)
```

**Layout XML**:
```xml
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

      <ImageView
            android:id="@+id/imgTemp"
            android:layout_width="0dp"
            android:layout_height="150dp"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
</android.support.constraint.ConstraintLayout>
```

**Stack trace / LogCat**:
```android
W/Glide: Load failed for https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png with size [60x60]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
W/Glide: Load failed for https://imgs.xkcd.com/comics/mc_hammer_age.png with size [1080x394]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
 W/Glide: Load failed for http://i.imgur.com/DvpvklR.png with size [1080x394]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

Please help look into it, I see there are many other issues that are just closed pointing to the same problem, or marked as stale.

**UPDATE**

When using the following in GlideAppModule extending AppGlideModule, images are not loaded at all is that how the behaviour should be? 

```
override fun applyOptions(context: Context, builder: GlideBuilder) {
        builder.setLogLevel(Log.DEBUG)
        builder.setDiskCache(DiskCacheAdapter.Factory())
    }
```

**Comment by adilahsoft0611** [comment]
i have same issue, if open on browser, image working properly

Here is my log:

 W/Glide: Load failed for https://idm-pub-img.s3.ap-southeast-1.amazonaws.com/coupon/master/554f8bab-fe25-4518-a94c-ea56da2f001e.png with size [1216x1216]
    class c.b.a.p.o.q: Failed to load resource

**Comment by adilahsoft0611** [comment]
using picasso, it's working.
