### ISSUE TITLE
DiskCacheStrategy.SOURCE

### ISSUE THREAD

**Issue by AlexBlokh** [bumptech/glide#367]
## Usecases
- When in **activity A** fetching an image
```java
Glide.with(ActivityA.this)
         .load(imageUrl)
         .diskCacheStrategy(DiskCacheStrategy.SOURCE)
         //You can put DiskCacheStrategy.ALL also
         .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
         .into((ImageView) v);
```
then switch off the internet and fetch the same image in **activity B** without overriding disk cache strategy, it doesn't fall back to the cached image
```java
Glide.with(ActivityB.this)
        .load(imageUrl)
        .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
        .into((ImageView) v);
```
- When in activity A fetching an image and **centerCrop** it with DiskCacheStrategy.ALL
```java
Glide.with(ActivityA.this)
         .load(imageUrl)
         .diskCacheStrategy(DiskCacheStrategy.ALL)
         .centerCrop()
         .into((ImageView) v);
```
then switch off the internet and fetch the same image in **activity B**.. the same result.
But if in **activity B** set **diskCacheStrategy.SOURCE** it falls back to the cached image

**Comment by sjudd** [comment]
The default DiskCacheStrategy, RESULT, does not check the SOURCE cache. Similarly SOURCE does not check the RESULT cache. You can see where these are defined here: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/DiskCacheStrategy.java#L6, and used here: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/DecodeJob.java#L80. 

ALL checks both caches and caches both the original data and the encoded/transformed/downsampled resource data. 

SOURCE -> SOURCE should work
RESULT -> RESULT (or none/none) should work
SOURCE -> RESULT won't work
RESULT -> SOURCE won't work
ALL -> SOURCE should work
ALL -> RESULT should work.

If one of those cases that I said should work doesn't, can you attach a sample app demonstrating the problem?

**Comment by sjudd** [comment]
Let us know if you still have questions.

**Comment by AlexBlokh** [comment]
Nope, thanks a lot!
