### ISSUE TITLE
Can not resize correctly

### ISSUE THREAD

**Issue by mrtry** [bumptech/glide#3673]
**Glide Version**: 4.5.0

**Issue details / Repro steps / Use case background**: 

I was trying to resize an image like the one below.
- 4032x3024
- ORIENTATION_ROTATE_90

Tried the following code.

```kotlin
GlideApp.with(context)
        .asBitmap()
        .override(1977, 2636) // consider the orientation
        .load(uri)
        .submit()
        .get()
```

I wanted an image `1977x2636`.
However, I got an image `2636x3515`.

Below is the Downsampler's log.

```
V/Downsampler: Calculate scaling, source: [4032x3024], target: [1977x2636], power of two scaled: [4032x3024], exact scale factor: 0.65376985, power of 2 sample size: 1, adjusted scale factor: 0.8716931343078613, target density: 1631763243, density: 1871946751
V/Downsampler: Calculated target [3515x2636] for source [4032x3024], sampleSize: 1, targetDensity: 1631763243, density: 1871946751, density multiplier: 0.8716932
V/Downsampler: Decoded [3515x2636] ARGB_8888 (37062160) from [4032x3024] image/jpeg with inBitmap [3515x2636] ARGB_8888 (37062160) for [1977x2636], sample size: 1, density: 1871946751, target density: 1631763243, thread: glide-source-thread-0, duration: 287.763101
```

Examined the calculation of `exact scale factor` and `adjusted scale factor` of `Calculate scaling`.

`exact scale factor` consider the orientation.
see: [Downsampler.java#L346-L356](https://github.com/bumptech/glide/blob/v4.5.0/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L346-L356)

However, `adjusted scale factor` does not consider the orientation.
see: [Downsampler.java#L440-L441](https://github.com/bumptech/glide/blob/v4.5.0/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L440-L441)

I think that this is why can not resize correctly.
Is the calculation of the `adjusted scale factor` correct, or a bug?

**Comment by mrtry** [comment]
By using `.override(2636, 1977)`, we were able to obtain the intended image.

**Comment by sjudd** [comment]
What version of Android were you using?

**Comment by sjudd** [comment]
Actually this definitely looks like a bug, nice catch, thanks for reporting.

**Comment by mrtry** [comment]
@sjudd 
Thank you.

> What version of Android were you using?

The problem was confirmed in 5.1, 9.0.
But I think it is an issue independent of versions.

**Comment by mrtry** [comment]
@sjudd 
Thank you for resolve this issue. 🙏 
When will it be released? 🙇
