### ISSUE TITLE
AndroidX android 4.9.0

### ISSUE THREAD

**Issue by Yinzeyu** [bumptech/glide#3680]
Glide  Version 4.9.0 does not support AndrdoidX?，Only version 4.8 supports Androidx? Why does version 4.8 support version 4.9 not support Android X?

**Comment by CristianGM** [comment]
Could you please add some information to the issue?
What's the error? In which case?

**Comment by sjudd** [comment]
Duplicate of #3184

**Comment by HDHunter** [comment]
Do we have AndroidX Version ?

**Comment by Yinzeyu** [comment]
yes,androidx version   Glide  Version 4.9.0

**Comment by Yinzeyu** [comment]
> Do we have AndroidX Version ?

yes,androidx Glide Version 4.9.0

**Comment by ZakTaccardi** [comment]
`4.9.0` does not support AndroidX. AndroidX will be supported in `4.10.0` - but that has not been released yet.

`4.10.0-SNAPSHOT` has AndroidX support
