### ISSUE TITLE
Using OkHttp Interceptor: Redundant User Agents 

### ISSUE THREAD

**Issue by sdotlittlenail** [bumptech/glide#3692]
Hi folks,

when specifying a particular user agent value in my http header via an OKHttp3 interceptor, e.g. with `MY_CUSTOM_USER_AGENT_RIGHT_HERE`, the user agent field seems to get mixed with the default `http.agent` system property defined in `LazyHeaders.java`: 

`String defaultUserAgent = System.getProperty("http.agent");`

So the result looks as follows and thereby the request to my backend (infrastructure) starts failing (as my backend only expects and accepts the defined value): 

```
Dalvik/2.1.0 (Linux; U; Android 9; Android SDK built for x86 Build/PSR1.180720.075); MY_CUSTOM_USER_AGENT_RIGHT_HERE
```
Imho it seems that both user agent values are getting mixed in the end by the `OkHttpStreamFetcher.java` in `loadData()` when the built up request + client are coming together. Quite similar to a problem ~ 3 years ago: https://github.com/bumptech/glide/issues/546

**Issue details / Repro steps / Use case background**: 

**My Interceptor:**

```
import okhttp3.Interceptor
import okhttp3.Response

class UserAgentInterceptor : Interceptor {

    override fun intercept(chain: Interceptor.Chain): Response = chain.proceed(
            chain.request()
                    .newBuilder()
                    .addHeader("User-Agent", "MY_CUSTOM_USER_AGENT_RIGHT_HERE")
                    .build())
}
```

**My used Glide Module:**

```
import android.content.Context
import com.bumptech.glide.Glide
import com.bumptech.glide.Registry
import com.bumptech.glide.annotation.GlideModule
import com.bumptech.glide.integration.okhttp3.OkHttpUrlLoader.Factory
import com.bumptech.glide.load.model.GlideUrl
import com.bumptech.glide.module.AppGlideModule
import okhttp3.Dispatcher
import okhttp3.OkHttpClient
import java.io.InputStream

@GlideModule
class OkHttpGlideModule : AppGlideModule() {

    override fun registerComponents(context: Context, glide: Glide, registry: Registry) {
        val client = OkHttpClient.Builder()
                .addInterceptor(ConnectivityInterceptor(context, false))
                .build()
        registry.replace(GlideUrl::class.java, InputStream::class.java, Factory(client))
    }
}
```

**Glide load line**:
I'm using data binding to set the loading mechanism for ImageViews

```java
object ImageViewBinding {

    @JvmStatic
    @BindingAdapter(value = ["url", "default"], requireAll = false)
    fun setImageUrl(view: ImageView, url: String?, @DrawableRes default: Drawable?) {
        default?.let {
            view.setImageDrawable(it)
        }

        url?.let {
            Glide.with(view.context).load(it).placeholder(default).into(view)
        }
    }
```

**Glide Version**:
Glide **4.9**, latest release

**Integration libraries**:
Glide-OkHttp3-integration, **4.9** as well

**Other libraries**:
OkHttp3, **3.12.1**

**Device/Android Version**:
Can be tested on an AVD Pie x86 image but also reproducible on Samsung S6, S7, Google Pixel or Huawei devices. Imho not device specific related

**Question:**
* Is it required to set the user agent somewhere else instead of using an interceptor? -> From your point of view works as designed? If yes, what would be the right way?
* Or Is this actually a bug that such conflicts should not occur?

**Comment by technoir42** [comment]
Your requests have 2 `User-Agent` headers since Glide adds one and you add one too.
You have to use `header(key, value)` instead of `addHeader(key, value)` to replace the existing header.

**Comment by sdotlittlenail** [comment]
Thx!

So simple it is by just knowing that `addHeader` starts working like a combine, not replacing previous values.

**Final solution:**

```
class UserAgentInterceptor : Interceptor {

    override fun intercept(chain: Interceptor.Chain): Response = chain.proceed(
            chain.request()
                    .newBuilder()
                    .header(USER_AGENT, SMARTSITE_MOBILE_USER_AGENT)
                    .build())

    companion object {
        const val SMARTSITE_MOBILE_USER_AGENT = "pm AppleWebKit Android"
    }
}
```

Thx for the fast response time and your patience!

May the next guy who is facing that "problem" be guided by this thread.

Problem solved!
