### ISSUE TITLE
ListPreloader.cancelAll does not cancel the most recent request

### ISSUE THREAD

**Issue by technoir42** [bumptech/glide#3693]
Preload queue has size of `maxPreload + 1` but only the first `maxPreload` requests get cancelled. The most recent request is always the last in queue so it doesn't get cancelled.

```java
  private void cancelAll() {
    for (int i = 0; i < maxPreload; i++) {
      requestManager.clear(preloadTargetQueue.next(0, 0));
    }
  }
```

**Comment by sjudd** [comment]
Thanks for reporting, please feel free to send a pull request!
