### ISSUE TITLE
AppCompat disclaimer

### ISSUE THREAD

**Issue by mufumbo** [bumptech/glide#371]
Please, write somewhere what compatibility level this library support. 

I thought it had v7 out of the box, but some of my users complained it didn't worked on some of their phones, so I tried to search everywhere and couldn't find what this lib is supposed to have. 

It would be super helpful also if someone can tell me if it actually works on 4.0 and forward.

**Comment by sjudd** [comment]
Thanks for bringing this up, we do list the min sdk version on the [readme][1], it's also listed in [gradle.properties][2], which is referenced from all of the build.gradle files. Let me know what we can do to make it more visible. Sorry for any inconvenience.

[1]: https://github.com/bumptech/glide#android-sdk-version
[2]: https://github.com/bumptech/glide/blob/master/gradle.properties#L35

**Comment by mufumbo** [comment]
Thanks a lot for the quick reply @sjudd! Just for the log, the compat is 10.

FYI: Since i dont use gradle I was expecting to find minsdkversion in the manifest file.

**Comment by TWiStErRob** [comment]
@mufumbo would it have helped if the `AndroidManifest.xml` was packaged in the `.jar` our the `-sources.jar` or you just checked the github source?
@sjudd do you think it's possible/worth to package the generated (not the source) manifest into one of the jars?

**Comment by mufumbo** [comment]
I just checked the github sources
