### ISSUE TITLE
glide v4.9 android target version 28 not loading image from url

### ISSUE THREAD

**Issue by cleawrence** [bumptech/glide#3720]
it's working fine when i target android version below 28 (i.e. 27)
but not loading from url  for 28 and above

**Comment by JonathandelaSen** [comment]
This is happening to me but just with the emulator. Is this happening to you on a real device?

**Comment by cleawrence** [comment]
> This is happening to me but just with the emulator. Is this happening to you on a real device?

On a real device too. i don t know whats happening! Debug Mode sees nothing.
Google ask to target 28 and above  before november. For time being it s ok.

**Comment by otmechaem** [comment]
The same!
