### ISSUE TITLE
How to use byte array as load resource in Glide - the orientation issue

### ISSUE THREAD

**Issue by ejChathuranga** [bumptech/glide#3726]
Gratefully thanks for the great library
Currently, I'm working on image compression app.

**Glide Version**:
`
    implementation 'com.github.bumptech.glide:glide:4.9.0'`
`
    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
`

**Integration libraries**:
non

**Device/Android Version**:
Samsung Galaxy S6 edge - Android Version - 7.0

**Issue details / Repro steps / Use case background**: 
When I selected an image, it's read as a file stream and get `byte[]`(original image) and after the compress, compressed image return as `Bitmap`. 
After the main process completed  I set both original(not compressed(`byte[]`)) and compressed images(compressed (`Bitmap`)) in the separated two `ImageView`s. 

The orientation issue arises when viewing the images in the `ImageView`. 
When we set Gradle instance and load data as `byte[]`, the orientation is not working correctly.
If we use `bitmap` as a load resource it's orientation is working without any issue. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(ImageCompressViewActivity.this)
                    .load(encodeObject.getOriginalFileBytes())
                    .into(originalImageView);
```

**Layout XML**:
```xml
<ImageView
                    android:id="@+id/originalImageView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:scaleType="centerCrop"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />
```

**Stack trace / LogCat**:
```
no, any error
```

**Comment by ejChathuranga** [comment]
Still, the orientation issue exists. Please make a review

**Comment by TWiStErRob** [comment]
@ejChathuranga what do you mean by "not working correctly"? The `byte[]` (which I assume is JPEG) probably has an EXIF header which contains an orientation flag. Last time I checked Glide follows that and rotates accordingly.

**Comment by lalitCiright** [comment]
Still, the orientation issue exists. Please make a review
