### ISSUE TITLE
some https pic can not load

### ISSUE THREAD

**Issue by clunyes** [bumptech/glide#3734]
Glide Version: 4.8.0

Integration libraries:4.8.0

Device/Android Version: oneplus5 android 9

other device can not load too.

https://img.qiuchengwangluo.com/union/2019/05/4/20190524150155812248619.png 
this pic can not load , but other https pic no problem.

2019-07-04 11:20:42.285 8575-8575/com.cnjiang.firebird W/Glide: Load failed for https://img.qiuchengwangluo.com/union/2019/05/4/20190524150155812248619.png with size [1002x459]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    javax.net.ssl.SSLHandshakeException(java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    javax.net.ssl.SSLHandshakeException(java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    javax.net.ssl.SSLHandshakeException(java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by ModirGithub** [comment]
https://tolideiranian.com/wp-content/uploads/2019/06/photo6043891650268344382-169x300.jpg
this pic can not load , but other https pic no problem.
implementation 'com.github.bumptech.glide:glide:4.9.0'

**BUG Fixed Please!!!**

**Comment by WANG1020** [comment]
解决了吗？

**Comment by Kola-Chao** [comment]
get same problem
