### ISSUE TITLE
How to delete a single image cache

### ISSUE THREAD

**Issue by jqjm** [bumptech/glide#3735]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by hzmeibi** [comment]
I have the same question
How to delete a single image cache
