### ISSUE TITLE
Gif do not play in my app,but can play int demo,why?

### ISSUE THREAD

**Issue by gaojunhuiBS** [bumptech/glide#3738]
Glide version : 4.9.0
I user the same gif url,int my app and text demo,same code ,the demo can play gif,but my app project can not play,why? pleasea,help me !!!
 String string = "http://wspic.iyingdi.cn/common/2019/07/03/ed1b1554-d209-4533-866b-5f4930ebba3b_iyingdi_gif.gif";
 Glide.with(this).asGif().load(string)
                .diskCacheStrategy(DiskCacheStrategy.DATA)
                .placeholder(R.color.color_000000)
                .error(R.color.color_000000)
                .into(iv);

**Comment by OverHaha** [comment]
怕是被Robin Li屏蔽喽 哈哈  你是来搞笑的

**Comment by Acoee** [comment]
It comes to me, do you solve it?
