### ISSUE TITLE
The image loaded after setting .override(Target.SIZE_ORIGINAL) is clearer but takes up less memory.why?(设置.override(Target.SIZE_ORIGINAL)后加载的图片更清晰但是占用内存更小)

### ISSUE THREAD

**Issue by OverHaha** [bumptech/glide#3739]
![图片](https://user-images.githubusercontent.com/24535858/60708068-c3e79180-9f3f-11e9-8127-27740a835c30.png)
![图片](https://user-images.githubusercontent.com/24535858/60708076-c813af00-9f3f-11e9-8d45-2a90e976f35a.png)
The first picture is a magnified contrast of the second long picture.The original size of the picture is: 132*185.
xml:
![图片](https://user-images.githubusercontent.com/24535858/60708714-4755b280-9f41-11e9-8b8a-5892b7f82098.png)

The first image loading code is:
![图片](https://user-images.githubusercontent.com/24535858/60708195-1163fe80-9f40-11e9-8a52-f224ca6309ae.png)
log:
![图片](https://user-images.githubusercontent.com/24535858/60708226-1de85700-9f40-11e9-82b9-479b69768c0b.png)
The second long image loading code is:
![图片](https://user-images.githubusercontent.com/24535858/60708256-3193bd80-9f40-11e9-84f3-5bae8c20198d.png)
log:
![图片](https://user-images.githubusercontent.com/24535858/60708271-42443380-9f40-11e9-9e1a-fa7462ab1cbd.png)
Now load the first image separately. Do not set .override(Target.SIZE_ORIGINAL) Memory is:
![图片](https://user-images.githubusercontent.com/24535858/60708312-56883080-9f40-11e9-80c3-e227ee100e21.png)
Now load the first image separately. Set the .override(Target.SIZE_ORIGINAL) memory to:
![图片](https://user-images.githubusercontent.com/24535858/60708339-6dc71e00-9f40-11e9-9237-ba4d6bf06cfd.png)
The picture is clearer, the memory is smaller, why?
Is this method a function of knowing?
![图片](https://user-images.githubusercontent.com/24535858/60708459-b5e64080-9f40-11e9-8892-c22504b3408f.png)

中文版：
![图片](https://user-images.githubusercontent.com/24535858/60708519-d1514b80-9f40-11e9-9370-59985a77c528.png)
![图片](https://user-images.githubusercontent.com/24535858/60708530-d615ff80-9f40-11e9-9862-2cc28a615081.png)
第一张图是第二长图的放大对比
图片原尺寸为：132*185
xml
![图片](https://user-images.githubusercontent.com/24535858/60708726-4e7cc080-9f41-11e9-84f6-883d2e6ffe5d.png)

第一张图片加载代码为：
![图片](https://user-images.githubusercontent.com/24535858/60708560-ecbc5680-9f40-11e9-8dff-3fe7d10ebf38.png)
log为
![图片](https://user-images.githubusercontent.com/24535858/60708573-f5ad2800-9f40-11e9-9550-d4843683ac0e.png)
第二长图片加载代码为：
![图片](https://user-images.githubusercontent.com/24535858/60708594-0198ea00-9f41-11e9-8672-03f3b960e1de.png)
log为
![图片](https://user-images.githubusercontent.com/24535858/60708608-08bff800-9f41-11e9-9daa-af82b9b9f07b.png)
现在单独加载第一张图片 不设置  .override(Target.SIZE_ORIGINAL)  内存为：
![图片](https://user-images.githubusercontent.com/24535858/60708624-107f9c80-9f41-11e9-94bc-7e3dfd8640e4.png)
现在单独加载第一张图片  设置了  .override(Target.SIZE_ORIGINAL)  内存为：
![图片](https://user-images.githubusercontent.com/24535858/60708638-17a6aa80-9f41-11e9-8d3a-68f92ca76e4f.png)
嗯 图片更清晰 内存更小 请求各位大佬 指点一下

**Comment by joimxjtuse** [comment]
log bitmap.getAllocationByteCount().

**Comment by KnIfER** [comment]
你测试的时候对调过顺序吗。。还是说加载清晰的和模糊的其测试流程已经是一模一样的（启动程序->测试1，【完全终结程序】， 启动程序->测试2）？

**Comment by OverHaha** [comment]
> 
> 
> log bitmap.getAllocationByteCount().

**Comment by OverHaha** [comment]
> 
> 
> log bitmap.getAllocationByteCount().

![图片](https://user-images.githubusercontent.com/24535858/61343037-f4ec8e00-a87e-11e9-8ed2-dcd7db71a2fe.png)
The second is to set .override(Target.SIZE_ORIGINAL)

**Comment by OverHaha** [comment]
> 
> 
> log bitmap.getAllocationByteCount().
![图片](https://user-images.githubusercontent.com/24535858/61343328-e94d9700-a87f-11e9-9175-6c079f97d430.png)

The second is to set .override(Target.SIZE_ORIGINAL)

**Comment by OverHaha** [comment]
> 
> 
> 你测试的时候对调过顺序吗。。还是说加载清晰的和模糊的其测试流程已经是一模一样的（启动程序->测试1，【完全终结程序】， 启动程序->测试2）？

对调过 也单独测试过
