### ISSUE TITLE
Get List<Bitmap> from GIF

### ISSUE THREAD

**Issue by Hobyrr** [bumptech/glide#3744]
I'm trying to transform a GIF into List<Bitmap> to make some modifications on each frame, but I didn't understand how doing it properly with Glide. 

I tried the code below, but I saw in debug I never go to onRessourceReady, so this method doesn't help me to get List<Bitmap>.

```
        DrawableRequestBuilder builder = Glide.with(this).load("path");
        builder.listener(new RequestListener<String, GlideDrawable>() {
            @Override
            public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                return false;
            }

            @Override
            public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                if (resource.isAnimated()) {
                    target.onResourceReady(new GlideBitmapDrawable(null, ((GifDrawable) resource).getFirstFrame()), null);
                    GifDrawable gd = (GifDrawable) resource;
                    Bitmap b = gd.getDecoder().getNextFrame();
                }
                return true;
            }
        });
        builder.into(new ImageView(this));
```

I looked for the method StreamGifDecoder, in Glide, honestly, I don't understand how pass the right arguments...

If anybody has an idea...

**Comment by JustinChiang123** [comment]
The same problem

**Comment by sjudd** [comment]
If you want to modify each frame, you can use a Transformation.

Glide doesn't support obtaining every frame, though you can eventually do so with the GifDecoder. It's not a great idea without some reasonable bounds because you could end up with lots of very large frames and OOM.
