### ISSUE TITLE
Downsampler.resetOptions(BitmapFactory.Options decodeBitmapOptions) not reset BitmapFactory.Options field outConfig

### ISSUE THREAD

**Issue by linchengchan** [bumptech/glide#3757]
part load image i used bitmapConfig is RGB_565,part used ARGB_8888.
when reused BitmapFactory.Options. i want RGB_565 but old value is ARGB_8888 and not repass value to outConfig. it make allocation double memory for bitmap.
Test result: onResourceReady() method i print bitmap with,height,config,allocationByteCount. show 720*468,RGB_565 1347840.

**Glide Version**: 4.9.0

**Integration libraries**: okhttp3-integration:4.9.0

**Device/Android Version**: Tecno ID3 8.1.0

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by linchengchan** [comment]
Ok , i see you fixed this bug! And when will release a new version?

**Comment by sjudd** [comment]
No current time frame on the next release, but you can use the latest [snapshot](http://bumptech.github.io/glide/dev/snapshots.html). 

I'm not actually confident this fixes anything, outConfig shouldn't impact anything, it's the framework reporting what config it will use.

It's more likely that you're trying to use RGB_565 with an image type that requires ARGB_8888 (has transparency for example) or where we can't tell that RG_565 is safe.
