### ISSUE TITLE
Question about Glide for multi-process

### ISSUE THREAD

**Issue by heeya333** [bumptech/glide#3758]
I need some help about using Glide for multi-process.
My app have 2 process, 1 is for UI updates, other is for Service to play music(RemoteViews).
These apps are use same cache directory, and same cache key.
But when request Glide for url to display,
Two processes request download twice for first time.

So I am trying to customize DiskLruCacheWrapper.
When DiskLruCacheWrapper.get(key), double check the real file exists one more,

But some values of DiskLruCacheWrapper are private, 
So I have to make new CustomDiskLruCacheWrapper because of some values,

Is it OK to copy&paste the DiskLruCacheWrapper code with some changes?
(Copyright (c) 2013. Bump Technologies Inc. All Rights Reserved.)
Could you advice to implement multi-process for Glide?

**Comment by mwshubham** [comment]
+1


Please advice use for multi-process
