### ISSUE TITLE
Reuse/Wait for ongoing network requests with duplicate URLs

### ISSUE THREAD

**Issue by daniel-robertson** [bumptech/glide#3760]
Enhancement Request:

**Problem:** 
Glide makes duplicate network calls when loading (or prefetching) the same image URL into multiple ImageViews if the below is true:
- The requests were made before Glide saved them to DISK cache.
- The ImageViews differ in size or there are other minor differences in the GlideRequest.

**Solution:** 
Ideally, Glide should wait for an ongoing network call to complete so it can reuse the response, rather than making another call because there are slight differences in the GlideRequest. 

If Glide could be smarter about this it would make prefetching significantly easier because it would become less important to determine the exact GlideRequest params ahead of time, such as ImageView dimensions.

**Comment by sjudd** [comment]
You can use a networking library that does this for you, or write your own. Glide doesn't have sufficient understanding of urls to know which requests have responses that can be re-used and which don't. 

In Photos we have made this assumption, so I don't think it's unreasonably in general. It is however not entirely safe to assume that every request will produce the same result every time.

**Comment by daniel-robertson** [comment]
Makes sense, thanks @sjudd.

If you're aware of a networking library that can accomplish this, do you mind sharing? I didn't see one, and It'd be nice to know before creating one myself.

**Comment by sjudd** [comment]
A library that supports http caching may do this? Maybe OkHttp or Volley? 

For Photos we wrote a custom wrapper for Cronet. 

It may be possible to write this super generically for any ModelLoader for that matter.
