### ISSUE TITLE
Glide instance per account in multi account app

### ISSUE THREAD

**Issue by ursusursus** [bumptech/glide#3761]
Hi,
I have a multi account app, where each account has its own dagger component, and a okhttp instance (theyre cloned from the same base instance so they share threadpools etc). However account specific okhttp client instance has its own authenticator (reauth is specific per account, as its api url is different) which does relogging in case of 401 etc. 

Point is that I need this account okhttp instance to drive Glide if im in under given account ui tree i.e. I need multiple Glides in app, per account instance.

Is there a way to do this? Im only able to inject okhttp loader factory via module, but that all seems to be singleton-y

Thanks!

**Comment by sjudd** [comment]
There's no way to have multiple Glide instances. You also wouldn't want to duplicate the memory cache/bitmap pool/disk cache etc, it would use a lot of extra system resources.

You can pass through account specific options into a custom ModelLoader if you want to handle accounts differently. That ModelLoader could route requests to separate OkHttp instances.

Exactly how that would work depends on what you use to identify accounts, but it sounds like just an account identifier would be sufficient. See http://bumptech.github.io/glide/tut/custom-modelloader.html

**Comment by ursusursus** [comment]
Well, same goes for okhttp client, but they allow for cloning, with nonoverrided stuff to be shared. Also, I think it should be up to the developer to decide for multiple instances; exposing constructor would play nice with dagger too
