### ISSUE TITLE
Glide may need READ_CONTACTS permission

### ISSUE THREAD

**Issue by disilin** [bumptech/glide#3768]
HI,
our government find our app had used READ_CONTACTS permission, but we just find some [code](https://github.com/bumptech/glide/blob/71359c7e385dc7d287f0da5d9e6d533ca41c76e4/library/src/main/java/com/bumptech/glide/load/data/StreamLocalUriFetcher.java#L6) maybe about that permission in glide.

**Comment by sjudd** [comment]
If you pass in a contacts uri, you will need the contacts permission if you want the image to load. Otherwise the loads will fail.

**Comment by Pluckypan** [comment]
+1
