### ISSUE TITLE
Gif loading time too high

### ISSUE THREAD

**Issue by akadatsky** [bumptech/glide#377]
Glide Version/Integration library (if any): Glide v3.5.2
Device/Android Version: Nexus 4/5.0.1, Samsung Galaxy S4/4.2.2.
Issue details/Repro steps:

I have used glide to show Gif images in such way:
Glide.with(context).load(url).asGif().diskCacheStrategy(DiskCacheStrategy.ALL).centerCrop().into(imageView);

The problem is: it takes to long time on wifi connection. For test images it takes 30 - 60 seconds until it appears. I have tested on 
In the same time on iphone it takes 3-4 seconds. 

I believe that main time takes not download file, but separate it to bitmaps. 

Same examples of my gifs:
http://media1.giphy.com/media/FiGiRei2ICzzG/giphy.gif
http://media3.giphy.com/media/AqkOIbHASLIf6/giphy.gif
http://media2.giphy.com/media/DEOk9OxgXGzMQ/giphy.gif

Is is possible to speed up Gif appearing?
If no is it possible just load files to file system and call some callback when file will be loaded?

**Comment by TWiStErRob** [comment]
Did you check #358 and #281?

**Comment by akadatsky** [comment]
Yes, thanks it was dupe of #358, sorry for inattention.
