### ISSUE TITLE
How to pre-download the correct image size to the local cache

### ISSUE THREAD

**Issue by qwwuyu** [bumptech/glide#3770]
**Glide Version**: com.github.bumptech.glide:glide:3.7.0

**Issue details / Repro steps / Use case background**: 
I want to download the image to the local in advance, so that it can be displayed directly next time.  
I used some methods but encountered some problems.  
### **Normal use:**
**Not configured GlideModule.**
**Image File:  180 x 180 (px) ,  29390b**
**Target Size: 100dp x 100dp (Equivalent on my phone: 200 x 200)**
```xml
<ImageView
	android:id="@+id/iv_head_bg"
	android:layout_width="100dp"
	android:layout_height="100dp"
	android:layout_centerInParent="true"/>
```
```kotlin
Glide.with(this)
	.load(url)
	.dontAnimate()
	.placeholder(R.mipmap.icon_photo_login)
	.into(iv_head_bg)
```
**It will download an image to the local cache:
/cache/image_manager_disk_cache/15485787d60b07d174ac33c87e42be1e27bd1555f0dc786ea1bce0fe77e5b90a.0
Image File:  200 x 200 ,  32805b (It not Original image)**

### **preparation download use:**
```kotlin
Glide.with(applicationContext)
	.load(url)
	.skipMemoryCache(true)
	.diskCacheStrategy(DiskCacheStrategy.ALL)
	.dontAnimate()
	.placeholder(R.mipmap.icon_photo_login)
	.into(iv_head_bg.width, iv_head_bg.height)// 200x200
```
**It will download two images to the local cache:
/cache/image_manager_disk_cache/aac100174e4a14e3b9ab02a0315c128f0a6c616ea13d88388fda39683d7860f4.0
Image File:  180 x 180 ,  29390b (Original image)
/cache/image_manager_disk_cache/6f0c28269e0651a8ccede8904f0c94b1d29c5f65ca758683133004c1f12eb3d8.0
Image File:  180 x 180 ,  27858b (It not Original image)**  

When I use preload to load the image, Did not make the normal loading fast display. And will not load properly when there is no network.  
How to do it, I can download image (15485787d60b07d174ac33c87e42be1e27bd1555f0dc786ea1bce0fe77e5b90a.0 Image File:  200 x 200 ,  32805b) to the local cache in advance.

**Comment by sjudd** [comment]
Looks like http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses

**Comment by qwwuyu** [comment]
thanks, This will learn a lot, I try it...
