### ISSUE TITLE
How can I load images into InputStream

### ISSUE THREAD

**Issue by wisdomtl** [bumptech/glide#3771]
I have a `url` which represents an image, I want to fetch it by Glide, but when recourse is ready, I wish it is not in the form of `Bitmap` but in the form of `InputStream`. how can I make it?

I find a ModelLoader named `HttpGlideUrlLoader`. It seems to meet my need. then I write the following code, but it does not work .

**Glide Version**:4.9.0

**Integration libraries**: none

**Device/Android Version**: OPPO FindX

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
val simpleTarget = object :SimpleTarget<InputStream>(){
            override fun onResourceReady(resource: InputStream, transition: Transition<in InputStream>?) {
                val bitmap = decodeBitmap(resource,BitmapFactory.Options())
                ivGlide.setImageBitmap(bitmap)
            }
        }
Glide.with(this).`as`(InputStream::class.java).load(GlideUrl(url)).into(simpleTarget)
```
the error I got is like the following:

**Stack trace / LogCat**:
```ruby
com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 cause:
java.lang.IllegalStateException(Failed to find any load path from class com.bumptech.glide.load.model.GlideUrl to class java.io.InputStream)
 call GlideException#logRootCauses(String) for more detail
```

**Comment by sjudd** [comment]
How do you obtain the InputStream? Consider using a custom ModelLoader to obtain the InputStream, rather than trying to pass one to Glide. It's probably expensive and dangerous (in terms of resource leaks) to pass around streams like this.

See http://bumptech.github.io/glide/tut/custom-modelloader.html
