### ISSUE TITLE
Android Q: Fails to load video taken from Google camera in Pixel 4.

### ISSUE THREAD

**Issue by soma13gupta** [bumptech/glide#3772]
4.9.0

**Integration libraries**:
No

Pixel 4/Android 10:

Record video using Google Camera. 
Try to load that video using Glide in another application.

Glide.with(getApplicationContext())
                        .load(videoUrl)
                        .centerCrop()
                        .override(600, 400)
                        .placeholder(R.mipmap.ic_launcher)
                      .into(img);

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context=".MainActivity"
    tools:showIn="@layout/activity_main">

  
    <ImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:src="@mipmap/ic_launcher"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</android.support.constraint.ConstraintLayout>
<!--
What is the error message that you got in the log?
You can find some help on diagnosing issues here: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
-->
**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by soma13gupta** [comment]
Any updates on this?

**Comment by soma13gupta** [comment]
Any update on this? 

This is the error that I am getting:

07-31 11:52:54.023  1066 13616 E StagefrightMetadataRetriever: extractor doesn't publish metadata, failed to initialize?
07-31 11:52:54.023  1066 13616 E MetadataRetrieverClient: failed to capture a video frame
07-31 11:52:54.023  1064  1308 W Utils   : did not find mime type
07-31 11:52:54.023  1066  1976 E StagefrightMetadataRetriever: extractor doesn't publish metadata, failed to initialize?
07-31 11:52:54.023  1066  1976 E MetadataRetrieverClient: failed to capture a video frame
07-31 11:52:54.023 18757 18955 E MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
07-31 11:52:54.023 18757 18957 E MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
07-31 11:52:54.024 18757 18955 E MediaMetadataRetrieverJNI: invalid file descriptor
07-31 11:52:53.967  1407  5045 V StorageManagerService: mountProxyFileDescriptor
07-31 11:52:54.024 10323 10323 V RedactingFileDescriptor: onRelease()
07-31 11:52:54.024 18757 18957 E MediaMetadataRetrieverJNI: invalid file descriptor
07-31 11:52:54.033 18757 18757 W Glide   : Load failed for content://media/external/file/58 with size [358x268]
07-31 11:52:54.033 18757 18757 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
07-31 11:52:54.033 18757 18757 W Glide   :   Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AutoCloseInputStream->Object->Drawable}, LOCAL
07-31 11:52:54.033 18757 18757 W Glide   :     Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->GifDrawable->Drawable}
07-31 11:52:54.033 18757 18757 W Glide   :     Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->Bitmap->Drawable}
07-31 11:52:54.033 18757 18757 W Glide   :     Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->BitmapDrawable->Drawable}
07-31 11:52:54.033 18757 18757 W Glide   :   Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptorInner->Object->Drawable}, LOCAL
07-31 11:52:54.033 18757 18757 W Glide   :     Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptorInner->Bitmap->Drawable}
07-31 11:52:54.033 18757 18757 W Glide   :     Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptorInner->BitmapDrawable->Drawable}
07-31 11:52:54.033 18757 18757 W Glide   :       Cause (1 of 1): class java.io.IOException: java.lang.IllegalArgumentException
07-31 11:52:54.034 18757 18757 I Glide   : Root cause (1 of 1)
07-31 11:52:54.034 18757 18757 I Glide   : java.io.IOException: java.lang.IllegalArgumentException
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.a(SourceFile:133)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.a(SourceFile:24)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.a(SourceFile:45)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodePath.a(SourceFile:67)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodePath.a(SourceFile:52)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodePath.a(SourceFile:43)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.LoadPath.a(SourceFile:56)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.LoadPath.a(SourceFile:42)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:489)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:1461)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.m(SourceFile:401)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:370)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:111)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(SourceFile:49)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:61)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.j(SourceFile:293)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.m(SourceFile:409)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:370)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:111)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(SourceFile:49)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:61)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.j(SourceFile:293)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.m(SourceFile:409)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:370)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:111)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.data.mediastore.ThumbFetcher.loadData(SourceFile:67)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:61)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.j(SourceFile:293)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.run(SourceFile:1263)
07-31 11:52:54.034 18757 18757 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-31 11:52:54.034 18757 18757 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-31 11:52:54.034 18757 18757 I Glide   : 	at java.lang.Thread.run(Thread.java:919)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(SourceFile:386)
07-31 11:52:54.034 18757 18757 I Glide   : Caused by: java.lang.IllegalArgumentException
07-31 11:52:54.034 18757 18757 I Glide   : 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
07-31 11:52:54.034 18757 18757 I Glide   : 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:142)
07-31 11:52:54.034 18757 18757 I Glide   : 	at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.a(SourceFile:123)
07-31 11:52:54.034 18757 18757 I Glide   : 	... 32 more
07-31 11:52:54.034 18757 18757 W Glide   : Load failed for content://media/external/file/79 with size [358x268]
07-31 11:52:54.034 18757 18757 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
07-31 11:52:54.034 18757 18757 W Glide   :   Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AutoCloseInputStream->Object->Drawable}, LOCAL
07-31 11:52:54.034 18757 18757 W Glide   :     Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->GifDrawable->Drawable}
07-31 11:52:54.034 18757 18757 W Glide   :     Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->Bitmap->Drawable}
07-31 11:52:54.034 18757 18757 W Glide   :     Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->BitmapDrawable->Drawable}
07-31 11:52:54.034 18757 18757 W Glide   :   Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptorInner->Object->Drawable}, LOCAL
07-31 11:52:54.034 18757 18757 W Glide   :     Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptorInner->Bitmap->Drawable}
07-31 11:52:54.034 18757 18757 W Glide   :     Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptorInner->BitmapDrawable->Drawable}
07-31 11:52:54.034 18757 18757 W Glide   :       Cause (1 of 1): class java.io.IOException: java.lang.IllegalArgumentException
07-31 11:52:54.035 18757 18757 I Glide   : Root cause (1 of 1)
07-31 11:52:54.035 18757 18757 I Glide   : java.io.IOException: java.lang.IllegalArgumentException
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.a(SourceFile:133)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.a(SourceFile:24)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.a(SourceFile:45)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodePath.a(SourceFile:67)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodePath.a(SourceFile:52)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodePath.a(SourceFile:43)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.LoadPath.a(SourceFile:56)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.LoadPath.a(SourceFile:42)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:489)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:1461)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.m(SourceFile:401)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:370)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:111)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(SourceFile:49)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:61)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.j(SourceFile:293)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.m(SourceFile:409)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:370)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:111)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(SourceFile:49)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:61)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.j(SourceFile:293)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.m(SourceFile:409)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:370)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:111)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.data.mediastore.ThumbFetcher.loadData(SourceFile:67)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:61)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.j(SourceFile:293)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.run(SourceFile:1263)
07-31 11:52:54.035 18757 18757 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-31 11:52:54.035 18757 18757 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-31 11:52:54.035 18757 18757 I Glide   : 	at java.lang.Thread.run(Thread.java:919)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(SourceFile:386)
07-31 11:52:54.035 18757 18757 I Glide   : Caused by: java.lang.IllegalArgumentException
07-31 11:52:54.035 18757 18757 I Glide   : 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
07-31 11:52:54.035 18757 18757 I Glide   : 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:142)
07-31 11:52:54.035 18757 18757 I Glide   : 	at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.a(SourceFile:123)
07-31 11:52:54.03


Thanks

**Comment by sjudd** [comment]
Seems to be an invalid video or file path:
```
07-31 11:52:54.023 1066 13616 E StagefrightMetadataRetriever: extractor doesn't publish metadata, failed to initialize?
07-31 11:52:54.023 1066 13616 E MetadataRetrieverClient: failed to capture a video frame
07-31 11:52:54.023 1064 1308 W Utils : did not find mime type
07-31 11:52:54.023 1066 1976 E StagefrightMetadataRetriever: extractor doesn't publish metadata, failed to initialize?
07-31 11:52:54.023 1066 1976 E MetadataRetrieverClient: failed to capture a video frame
07-31 11:52:54.023 18757 18955 E MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
07-31 11:52:54.023 18757 18957 E MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
07-31 11:52:54.024 18757 18955 E MediaMetadataRetrieverJNI: invalid file descriptor
07-31 11:52:53.967 1407 5045 V StorageManagerService: mountProxyFileDescriptor
07-31 11:52:54.024 10323 10323 V RedactingFileDescriptor: onRelease()
07-31 11:52:54.024 18757 18957 E MediaMetadataRetrieverJNI: invalid file descriptor
```

You can confirm by trying to open the file using MediaMetadataRetriever directly. If that fails it's an issue with the file or with the framework.

**Comment by soma13gupta** [comment]
Hi, But Picaso is able to load the freshly recorded video from the native camera.

**Comment by sjudd** [comment]
Can you attach an example video that will load in Picasso and/or the Android framework that won't load in Glide?

**Comment by soma13gupta** [comment]
Steps: 
1) Open the Camera App and record a video.
2) Open the Test app( it just queries the MediaStore for the latest video and load it into imageview). The code with Picasso is able to load it but the code with Glide fails to do so.
(Sample code attached.)

Here is my sample code:

=================================================================
package com.example.picasso_glide;

import android.Manifest;
import android.content.ContentUris;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.provider.MediaStore;
import android.support.v4.app.ActivityCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.widget.ImageView;

import com.bumptech.glide.Glide;
import com.squareup.picasso.Picasso;

public class MainActivity extends AppCompatActivity {
    private ImageView img;
    public static final Uri EXTERNAL_CONTENT_URI = MediaStore.Files.getContentUri("external");
    private Uri videoUrl;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        img = (ImageView)findViewById(R.id.imageView);

    }

    @Override
    protected void onResume() {
        super.onResume();
        Log.d("MainActivity","onResume");
        requestPermission();
    }

    private void requestPermission() {
        Log.d("MainActivity","requestPermission");
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)
                    != PackageManager.PERMISSION_GRANTED) {

                if (ActivityCompat.shouldShowRequestPermissionRationale(this,
                        Manifest.permission.READ_EXTERNAL_STORAGE)) {
                    // Show an explanation to the user *asynchronously* -- don't block
                    // this thread waiting for the user's response! After the user
                    // sees the explanation, try again to request the permission.
                } else {
                    // No explanation needed; request the permission
                    ActivityCompat.requestPermissions(this,
                            new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},
                            3);

                    // MY_PERMISSIONS_REQUEST_READ_CONTACTS is an
                    // app-defined int constant. The callback method gets the
                    // result of the request.
                }
            } else {
                // Permission has already been granted
                loadImage();
            }
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode,
                                           String[] permissions, int[] grantResults) {
        Log.d("MainActivity","onRequestPermissionsResult");
        switch (requestCode) {
            case 3: {
                // If request is cancelled, the result arrays are empty.
                if (grantResults.length > 0
                        && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                    loadImage();
                    // permission was granted, yay! Do the
                    // contacts-related task you need to do.
                } else {
                    // permission denied, boo! Disable the
                    // functionality that depends on this permission.
                }
                return;
            }

            // other 'case' lines to check for other
            // permissions this app might request.
        }
    }

    private void loadImage() {
        Log.d("MainActivity","loadImage");
        initializeCursor();
    }


    public void initializeCursor(){

        String[] projection = {MediaStore.Files.FileColumns._ID, MediaStore.Files.FileColumns.DATA,
                MediaStore.Files.FileColumns.MEDIA_TYPE, MediaStore.Video.VideoColumns.DURATION};
        String sortOrder = String.format("%s LIMIT " + 1, MediaStore.Files.FileColumns.DATE_ADDED + " DESC");

        String[] projectionImg = {MediaStore.Files.FileColumns._ID, MediaStore.Files.FileColumns.DATA,
                MediaStore.Files.FileColumns.MEDIA_TYPE};

        try {
            String selection = MediaStore.Files.FileColumns.MEDIA_TYPE + " = ? ";


            String[] selectionArgs = new String[]{
                    Integer.toString(MediaStore.Files.FileColumns.MEDIA_TYPE_VIDEO)};
            Cursor cursor = getApplicationContext().getContentResolver().query(EXTERNAL_CONTENT_URI,
                    projection,
                    selection,
                    selectionArgs,
                    sortOrder);

            if (cursor != null && cursor.moveToFirst()) {
                String path = cursor.getString(cursor.getColumnIndex(MediaStore.Files.FileColumns.DATA));
                String duration = cursor.getString(cursor.getColumnIndex(MediaStore.Video.VideoColumns.DURATION));

                videoUrl = ContentUris.withAppendedId(EXTERNAL_CONTENT_URI, cursor.getLong(cursor.getColumnIndex(MediaStore.Files.FileColumns._ID)));
                Log.d("MainActivity", "videoUrl 1: " + videoUrl + "path: " + path);

                Picasso.get()
                        .load(videoUrl)
                        .resize(300, 300)
                        .centerCrop()
                        .into(img);


                /* Glide.with(getApplicationContext())
                        .load(videoUrl)
                        .centerCrop()
                        .override(300, 300)
                        .placeholder(R.mipmap.ic_launcher)
                      .into(img);*/

            }
        } catch (Exception e) {

            Log.d("MainActivity", "Query still giving exception: " + e.getMessage());

        }

    }

}

**Comment by sjudd** [comment]
Can you attach a sample video?

**Comment by soma13gupta** [comment]
How do i upload the video? It is showing error "Something went really wrong, and we can't process that file"

**Comment by soma13gupta** [comment]
https://drive.google.com/file/d/1-Gz2reqrTUddPoA5nJmxveIbVtx4zvJ9/view?usp=drivesdk

**Comment by soma13gupta** [comment]
https://drive.google.com/file/d/1-Gz2reqrTUddPoA5nJmxveIbVtx4zvJ9/view?usp=drivesdk

**Comment by sjudd** [comment]
What version of Android Q are you using?

**Comment by soma13gupta** [comment]
We have used Beta 5.

**Comment by soma13gupta** [comment]
Any updates on this?
