### ISSUE TITLE
当我使用Glide在recyclerView加载图片的时候，图片出现模糊，When I used Glide to load images in recyclerView, the images blurred.

### ISSUE THREAD

**Issue by 15697973913** [bumptech/glide#3773]
![25C39FFD-1605-4750-9BF3-E372083A5EAA](https://user-images.githubusercontent.com/26077041/61676602-31146880-ad2f-11e9-9dea-29592ece6b1c.png)
![CC1D3780-442D-41d7-8619-2028D79B71A2](https://user-images.githubusercontent.com/26077041/61676618-425d7500-ad2f-11e9-8625-cb2aacf9e09a.png)
![7E5252AE-B430-4410-AC7A-1105EC9A5F52](https://user-images.githubusercontent.com/26077041/61676619-44273880-ad2f-11e9-9af7-dcb151cc49d7.png)
这是在一个聊天列表界面，用户发送的是同一张图片，我是通过判断本地是否有该图片，来加载本地的或服务器上的，当加载出来以后，我将列表往下滑大概两到三个屏幕的距离，在滑动至该图片的位置，有的时候就会出现图片加载模糊的情况，我也试过像        Glide.with(imageView.getContext()).load(resId).into(imageView);
直接加载服务器上的图片，但是也会出现像现在这种情况，我想知道这是什么原因导致的

**Comment by Justahri** [comment]
https://muyangmin.github.io/glide-docs-cn/int/recyclerview.html

**Comment by 15697973913** [comment]
> https://muyangmin.github.io/glide-docs-cn/int/recyclerview.html

非常感谢，对我很有帮助
