### ISSUE TITLE
how to set different types of registry in Glide4

### ISSUE THREAD

**Issue by ukyo6** [bumptech/glide#3779]
in Glide3, we can use this:
`Glide.get(MainActivity.this)
                .register(GlideUrl.class,InputStream.class,new OkHttpUrlLoader.Factory(mOkHttpClient1));`

`Glide.get(MainActivity.this)
                .register(GlideUrl.class,InputStream.class,new OkHttpUrlLoader.Factory(mOkHttpClient2));`

but in Glide4, we can only define it in GlideModule. only one AppGlideModule can be defined.
if I want to use 2 or more different types of registry, what can i do?

**Comment by sjudd** [comment]
I'm not sure what you mean by two different types of registry?

Libraries can also register components, they just can't change the cache sizes: http://bumptech.github.io/glide/doc/configuration.html#libraries

**Comment by ukyo6** [comment]
Thanks for your reply !

I mean if I import two LibraryGlideModule:  LibrayModuleA  and LibraryModuleB,  I know they will both be included in the `GeneratedAppGlideModuleImpl`.  
Can I choose when to use A or B libraryModule?(maybe I need A & B every time)

**Comment by sjudd** [comment]
You can't choose, they're either compiled into the binary or they aren't. It's not possible to pick one or the other at run time, though you can at compile time.

**Comment by ukyo6** [comment]
I got it, thanks.
