### ISSUE TITLE
Preferred way to mock out http requests?

### ISSUE THREAD

**Issue by tmelz** [bumptech/glide#378]
For test runs, I'd like to direct all Glide requests for images to just return some specific local bitmap. Is this possible with the current api? I looked around a little bit and didn't see anything obvious; I'm guessing this would be implemented with a GlideBuilder and setting a custom engine?

**Comment by TWiStErRob** [comment]
Are you sure you really need to mock? If you make the request once, it'll be in RESULT cache. So next time there should be no download, except if you modify the Glide loading code in a way that changes the cache key.

**Comment by tmelz** [comment]
Sorry, let me be more clear. I want **all** image requests to return the same dummy image during tests.

**Comment by TWiStErRob** [comment]
You can [replace the underlying networking library](https://github.com/bumptech/glide/wiki/Integration-Libraries) and just ignore the model and return the "same" InputStream all the time.

You can register a [GlideModule in the `AndroidManifest.xml`](https://github.com/bumptech/glide/wiki/Configuration#including-a-glidemodule) for global configuration.

If you like learning by example you can base your code on: https://github.com/bumptech/glide/tree/master/integration/okhttp/src/main
Make sure you rename your classes and register the correct module.

... and don't forget `if (BuildConfig.DEBUG)` ;)

**Comment by sjudd** [comment]
If you're talking specifically about unit tests you can also take a look at Glide's [GlideTest][1] which does integration test like things including mocking out network requests.

[1]: https://github.com/bumptech/glide/blob/master/library/src/androidTest/java/com/bumptech/glide/GlideTest.java#L139

**Comment by vovkab** [comment]
@tmelz On more way is if you use OkHttp, you can use interceptors to mock any response.

**Comment by sjudd** [comment]
Let us know if there's anything else we can do to help.
