### ISSUE TITLE
[Question] fallback/error/placeholder does not work when using `.get()` for Bitmap

### ISSUE THREAD

**Issue by waliahimanshu** [bumptech/glide#3781]
I am trying to get the bitmap using Glide, but `Fallback` callback  does not work when url is null 
and `error` callback does not work when URL is invalid , in both cases I get exception, which result in a crash.

I could use ` .listener(new RequestListener<Uri, Bitmap>() ` to handle the fallback scenarios but wonder why the callbacks does not work or is it  intended by design ?

```
val requestBuilder = Glide.with(applicationContext).asBitmap()
requestBuilder
                .run {
                load(url)
                .placeholder(R.drawable.placeholder)
                .fallback(R.drawable.placeholder)
                .error(R.drawable.placeholder)
                .apply(RequestOptions.circleCropTransform())
                .submit(width, height)
                .get()
}
```

**Glide Version**: 4.9.0

**Stack trace / LogCat**:

When the url is null, it throws `glide received null model` exception
and `UnknownHostException ` if URL in invalid.

**Comment by sjudd** [comment]
Yes it's intended that the placeholders aren't returned when you call get(). The placeholders can be set regardless of the requested type and they can't be returned for all types (asGif() for example can't return a generic Drawable).

**Comment by victor-munoz** [comment]
What about the error and fallback drawable? should they be returned when the URL is null or invalid?
