### ISSUE TITLE
Glide doesn't cache if request was cancelled

### ISSUE THREAD

**Issue by davidxiasc** [bumptech/glide#3794]
*Glide Version**: 4.9

**Integration libraries**: OkHttp3

**Device/Android Version**: OnePlus 6, Android P

**Issue details / Repro steps / Use case background**: 

When loading images and then cancelling, the images still get downloaded but the images are not disk cached.

For example:
```kt
GlideApp.with(getContext())
        .load(...)
        .into(imageView)

// sometime later (e.g. scrolled past the image)
GlideApp.with(getContext()).clear(imageView)
```

In scenarios where you scroll fast enough to not give the image enough time to load into the view, you will notice that (with network profiler, Charles proxy, etc) the image does indeed download. However, when scrolling back up to the same spot to re-trigger the image request, the image downloads again!

My theory is that when the Request is cancelled from the ImageView, it eventually gets GC'd and the disk caching only happens if the Request object is still in memory.

**Comment by sjudd** [comment]
This is basically a race and depends a lot on the behavior of the library you're using to download images. If the downloaded data hasn't yet been passed back to Glide (ie onResponse hasn't been called: https://github.com/bumptech/glide/blob/8a9b63cfd9462f6c4bb40f655d3bd25cc02d7d0d/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpStreamFetcher.java#L66), then it's not going to be written to cache. 

If Glide gets the data from the download before the cancellation, Glide will write it to cache.
