### ISSUE TITLE
Deadlock on getBitmap

### ISSUE THREAD

**Issue by perracolabs** [bumptech/glide#3802]
**Glide Version**: 4.9.0

**Integration libraries**:

**Device/Android Version**: Huawei P20 Lite, on Android 9.0 Pie

**Issue details / Repro steps / Use case background**: 

Getting sometimes a deadlock when trying to get a bitmap from a file that has just been deleted.
To mitigate the issue I will check before doing the request if the file no longer exists, nevertheless I thought it was necessary to report it.

The issue may be releated to #3667 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

Calling the next method in a background thread.
```java
GlideApp.with(context)
        .asBitmap()
        .load(uri)
        .signature(signature)
        .priority(Priority.IMMEDIATE)
        .format(DecodeFormat.PREFER_RGB_565)
        .diskCacheStrategy(DiskCacheStrategy.NONE)
        .disallowHardwareConfig()
	.get();
```

**Stack trace / LogCat**:

Couldn’t get the stack-trace, but as I could pause the project while in dead-lock and get the next screenshots:

![image](https://user-images.githubusercontent.com/7354233/62205328-8257d400-b38f-11e9-85ae-f09f717f4124.png)

![image](https://user-images.githubusercontent.com/7354233/62205485-cfd44100-b38f-11e9-91f5-d8b2755d1937.png)

![image](https://user-images.githubusercontent.com/7354233/62205373-98fe2b00-b38f-11e9-9310-06600b75cff7.png)

![image](https://user-images.githubusercontent.com/7354233/62205399-a4e9ed00-b38f-11e9-9674-79221bfcc74c.png)

**Comment by sjudd** [comment]
I believe this was fixed by 890712279a997ded1b22d64ea6059c911b2f8a55
