### ISSUE TITLE
Glide always has open filemap ,process will be killed by Android ProcessKiller when sdcard is unmounted 

### ISSUE THREAD

**Issue by NessCurie** [bumptech/glide#3807]
Glide Version: Glide 4.9.0.
Integration libraries: none

code just these: 
`Glide.with(this)
                .load(File("thisIsFilePathOnSdcard"))
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .skipMemoryCache(true)
                .into(iv)`

When sdcard is unmounted,my app process is killed by ProcessKiller.

logcat :
`ProcessKiller: Process  applicationId(uid) has open filemap for /filePath
ProcessKiller: Sending Interrupt to process uid`

And process was not killed when I removed the code.
This means glide still has open filemap.

I try these code useless.
               `Glide.with(this@MainActivity).onDestroy()
                Glide.get(this@MainActivity).clearMemory()
                Thread {
                    Glide.get(this@MainActivity).clearDiskCache()
                }.start()`

So why gilde still keep the filemap.And What should I do.

**Comment by myflyingfish** [comment]
I  get the same error

**Comment by FreestyleDDCoder** [comment]
Hi, bro,did you solved this error？

**Comment by NessCurie** [comment]
I used the newest version doesn't seem to show up
