### ISSUE TITLE
how to get ftp video duration by glide?

### ISSUE THREAD

**Issue by TmacZhang** [bumptech/glide#3812]
how to get ftp video duration by glide?
like this, I can get any frame. now , I want to get the video duration.
        Glide.with((Activity) mContext).setDefaultRequestOptions(new RequestOptions()
                .frame(0))
                .load(ftpType)
                .signature(new ObjectKey(ftpType1))
                .placeholder(R.drawable.ic_launcher).into(viewHolder.imageView);

**Comment by sjudd** [comment]
Glide doesn't support obtaining the duration or other metadata about images or videos.
