### ISSUE TITLE
When will the latest glide version with androidX migrating be published?

### ISSUE THREAD

**Issue by zhuozengsi** [bumptech/glide#3816]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:
Q

**Issue details / Repro steps / Use case background**: 
Hi,
we are doing the androidX adapting job which related to glide, so could you help us to check the time when the latest glide version with androidX migrating will be published?

Thanks a lot.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by baunty3000** [comment]
Hello..

**Comment by eman1986** [comment]
curious to know if this is happening myself
