### ISSUE TITLE
Question: Ability to provide custom cache key for individual glide requests.

### ISSUE THREAD

**Issue by AbhinavBhadoria** [bumptech/glide#3823]
**Glide Version**: 4.9.0

**Integration libraries**: None

**Device/Android Version**: OnePlus 5, Android 9

**Issue details / Repro steps / Use case background**: 
From my understanding of the cache system, Glide generates a cache key from the model and signature when writing to disk. Furthermore, for resources in-use(in-memory or in-view) it appends additional information to the cache key like (views dimension, request options and more).

I would like to know, how to provide custom cache key that can be used to save the result of glide request into the cache.

For example:
Normally glide uses the model as cache key i.e. image download from "https://some.image.provider/abc.png" will be cached on the same url.

Now, how can I store the result of "https://some.image.provider/abc.png" to some other url say "https://someother.image.provider/xyz.png".

**Use case: 1 (remote uri)**:
Suppose the same image is served from different hosting servers, like:
- https://cdn.service1.com/abc.png
- https://cdn.service2.com/abc.png
- https://cdn.service3.com/abc.png

Here, Glide will download the image thrice, since they are different urls. But if I can modify the cache key to say, "abc.png", it'll only perform the first request, save its result at "abc.png" and subsequent requests will be severed from cache. 

One way I have figured out to do this is by extending the GlideUrl class and overriding its getCacheKey method to return my custom cache key. 

```
class MyGlideUrl(val sourceUrl: String)
    : GlideUrl(sourceUrl) {

    override fun getCacheKey(): String {
        return ObjectKey("myCustomCacheKey").toString()
    }
}
```

The above solution works for me and I can cache the result of network requested image to custom cache keys. However, I am not able to do the same for local uri and files. 

**Use case: 2 (local uri, file)**:
Lets say, I am updating my profile photo. I'll select the image from gallery/camera and start uploading it to server, while showing the local image in the image view. Once upload is completed, the profile edit page closes and refreshes the profile page. Glide will now download the image from new profile image url, even though we have the image locally.  

If I could load the local file with cache key set as remote url, it would have populated the Glide's cache with the image beforehand. 

The way I solved this is by maintaining an in-memory map of remote uri to local uri. And for every load I check if it has an entry of the remote uri and if present, I load the local uri and prefetch the remote uri in background (so it is available for next session).

What should be the ideal approach for solving this?
What part of Glide should I be looking deeper to approach solving this?

**Comment by yftx** [comment]
**Case 1**

Maybe LoadData#alternateKeys can work.
Glide load source disk cache in DataCacheGenerator#startNext() 
it will search cache by LoadData's sourceKey and alternateKeys.
so you can try make  https://cdn.service1.com/abc.png as sourceKey
https://cdn.service2.com/abc.png
https://cdn.service3.com/abc.png
as alternateKeys

**Case 2**

what means ?
> for every load I check if it has an entry of the remote uri and if present, I load the local uri and prefetch the remote uri in background (so it is available for next session).

if you have local file path, why do you want to load from remote?
or what don't you just use remote ?

**Comment by AbhinavBhadoria** [comment]
@yftx Thank you for replying. 

Case 1: I didn’t knew about alternate keys. Thanks for the tip. 

Case 2: Sorry if I wasn’t clear before. Allow me to explain my actual example: 

- I am working on integrating chats in my application, with ability to share media including images.
- When user shares an image, a local message is created with dummy ids and local data (uri of image). This local message is added to the message list and displayed to users. 
- Once image upload is complete and message is sent, server sends a new message to every client in the conversation. The uploading client replaces the local message it create with the newly received remote message. This causes the local message to be removed and replaced with remote message. 
- Since the remote message contains remote url, and this url hasn’t been loaded before, glide downloads the image. This causes a loading state in-between. 
- If I had created an entry for the local image with remote url once image upload was successful, Glide would have loaded the image directly from cache, preventing the loading state. 


Solution 1: I maintain a map of remote to local uri and while creating the request builder, check if given url has local uri and if present, load the local uri. 

Solution 2: Maybe I can write a custom model loader that operates on Url/GlideUrl and prepend it in my custom glide module. This custom model loader would then maintain the mapping of remote to local uri and return the local uri if it finds any. I think this greatly abstracts the logic of mapping from view layer and solves the problem. 

Sorry for any typos.

**Comment by yftx** [comment]
If i make this case.
when i send image to server, I will load local image first.
after upload image success, I will load remote image url with `GlideRequest#getDownloadOnlyRequest()`
and add an RequestListener to listen image download success.
after download success, update IM DB to notify view.

**Comment by petarmarijanovicfive** [comment]
I have the same case (Case 2). I want to be able to define the same **cacheKey** for both Uri and GlideUrl.

The name of the file would be the key. Is anything like this possible?
