### ISSUE TITLE
Implement Glide library

### ISSUE THREAD

**Issue by HamidRezaRTM** [bumptech/glide#3830]
Since I'm using androidx, I can't implement Glide library and get this error:

![error](https://user-images.githubusercontent.com/23734963/62952542-16e71b00-be01-11e9-856e-1a5255ef4e4c.png)

**Comment by Amit2286658** [comment]
I'm having the same problem, i tried to use "android.enableJetifier=true", but it wasn't of any use either,

**Comment by sjudd** [comment]
Duplicate of #3184
