### ISSUE TITLE
load gif in recyclerview & it does not animate 

### ISSUE THREAD

**Issue by tracy1allen3** [bumptech/glide#3835]
recyclerview中，item移出屏幕后再滑进屏幕，gif动画就没有了。
listview中不会出现这种情况。
有碰到这种情况的吗？如何解决？

**Comment by tracy1allen3** [comment]
> stale

any way , it's not a issue ? only occur in my situation ?

**Comment by lucazin** [comment]
i have same problem

**Comment by shubhwicked** [comment]
I am facing the same problem
