### ISSUE TITLE
NullPointerException by Activity destroy

### ISSUE THREAD

**Issue by xuelanghu120** [bumptech/glide#3836]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by xuelanghu120** [comment]
Glide Version:4.8.0

Stack trace / LogCat:

Caused by:
--
5 java.lang.NullPointerException:Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
6 com.bumptech.glide.load.resource.gif.GifFrameLoader.k(Unknown Source:4)
7 com.bumptech.glide.load.resource.gif.GifDrawable.getIntrinsicWidth(Unknown Source:4)
8 android.widget.ImageView.updateDrawable(ImageView.java:1067)
9 android.widget.ImageView.setImageDrawable(ImageView.java:620)
10 android.support.v7.widget.AppCompatImageView.setImageDrawable(Unknown Source:0)
11 com.bumptech.glide.request.target.ImageViewTarget.setDrawable(Unknown Source:4)
12 com.bumptech.glide.request.target.ImageViewTarget.onLoadCleared(Unknown Source:14)
13 com.bumptech.glide.request.SingleRequest.clear(Unknown Source:40)
14 com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(Unknown Source:24)
15 com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(Unknown Source:1)
16 com.bumptech.glide.RequestManager.a(Unknown Source:10)
17 com.bumptech.glide.RequestManager.untrackOrDelegate(Unknown Source:0)
18 com.bumptech.glide.RequestManager.clear(Unknown Source:9)
19 com.bumptech.glide.RequestManager.onDestroy(Unknown Source:27)
20 com.bumptech.glide.manager.ActivityFragmentLifecycle.a(Unknown Source:25)
21 com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(Unknown Source:5)
22 android.support.v4.app.Fragment.performDestroy(Unknown Source:21)
23 android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:1062)
24 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:38)
25 android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:46)
26 android.support.v4.app.FragmentManagerImpl.dispatchStateChange(Unknown Source:4)
27 android.support.v4.app.FragmentManagerImpl.dispatchDestroy(Unknown Source:7)
28 android.support.v4.app.FragmentController.dispatchDestroy(Unknown Source:4)
29 android.support.v4.app.FragmentActivity.onDestroy(Unknown Source:20)
30 android.support.v7.app.AppCompatActivity.onDestroy(Unknown Source:0)
31 com.soyoung.common.mvp.AbstractMvpActivity.onDestroy(Unknown Source:5)
32 com.soyoung.common.mvpbase.BaseActivity.onDestroy(Unknown Source:52)
33 com.youxiang.soyoungapp.ui.MainActivity.onDestroy(Unknown Source:22)
34 android.app.Activity.performDestroy(Activity.java:7737)
35 android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1327)
36 android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5134)
37 android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5168)
38 android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
39 android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
40 android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
41 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
42 android.os.Handler.dispatchMessage(Handler.java:112)
43 android.os.Looper.loop(Looper.java:216)
44 android.app.ActivityThread.main(ActivityThread.java:7593)
45 java.lang.reflect.Method.invoke(Native Method)
46 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
47 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by viglis** [comment]
How to fix this issue?
