### ISSUE TITLE
How to circleCrop() a rectangular image?

### ISSUE THREAD

**Issue by loukwn** [bumptech/glide#3839]
**Glide Version**: 4.9.0

**Integration libraries**: -

**Device/Android Version**: Samsung A5 2016, 7.1.1 (rooted + custom rom)

**Issue details / Repro steps / Use case background**: I am trying to load some country flags into my app from countryflags.io (an example [here](https://www.countryflags.io/eu/flat/64.png)). But I also want them to be circular like this:

![image](https://user-images.githubusercontent.com/5406640/63224150-d0127000-c1c8-11e9-84d2-75d5a8316e53.png)

Applying the circleCrop() transformation results to this:

![image](https://user-images.githubusercontent.com/5406640/63224170-12d44800-c1c9-11e9-8bf3-6c5fab161183.png)

Now I understand that this happens because the image is a rectangle and it is small enough to be fitCenter by default. But I also tried overriding the size to make it bigger, so that centerCrop matters and still got the same result. Is there something that eludes me here? Thank you in advance!

**Note**: if you open the above image with Firefox, it shows that it has a white border around it, but it really is transparent there.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
Glide.with(context)
	.load(item.iconURL)
    .apply(RequestOptions().circleCrop())
    .into(image_view)
```

**Layout XML**:
```xml
<ImageView
        android:id="@+id/image_view"
        android:layout_width="46dp"
        android:layout_height="46dp"
        android:layout_centerVertical="true"
        android:scaleType="centerCrop"
        android:layout_marginEnd="10dp"
        tools:src="@tools:sample/avatars"
    />
```

**Comment by Jide-xy** [comment]
Also facing this issue from the same countryflags.io

**Comment by CoolMind** [comment]
See also https://stackoverflow.com/questions/31759841/glide-multiple-transformations-in-android/63798242 and https://stackoverflow.com/questions/53300865/make-square-image-in-glide-and-then-round-it. There are several situations where we cannot achieve a desired result due to a rectangular image.

    GlideApp.with(imageView)
         .load(url)
         .transform(MultiTransformation(CenterCrop(), RoundedCorners(10)))
         .into(imageView)

```
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="50dp"
    android:layout_height="50dp"
    android:adjustViewBounds="true"
    android:contentDescription="@null"
    android:scaleType="centerInside"
    tools:src="@drawable/image"
    />
```

**Comment by emanuelbradtke** [comment]
Could you kindly provide more information? This information piques my curiosity, and it will be useful to me in my job.
[getting over it](https://gettingoverit.io)
