### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by iker-garcia** [bumptech/glide#3842]
**Glide Version**:4.9.0

**Integration libraries**:

**Device/Android Version**:Android 9(sansumg 10, samsung a70, xiamoi mia2)

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
 Glide.with(this).load(imagen).into(img);

The really problem is that normally the image loads perfectly, but in some devices i think everyone Android 9(sansumg 10, samsung a70, xiamoi mia2,...). The image does not loads, the imageview is blank, and have height equal 0

**Comment by lucazin** [comment]
And exception in this block

`.listener(new RequestListener<String, Bitmap>() {
					@Override public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
						LoadIn.setImageResource(R.drawable.image_erro_img);
						return false;
					}
					@Override public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
						ImageViewTarget imTarget = (ImageViewTarget)target;
						
						return new DrawableCrossFadeFactory<Drawable>()
								.build(isFromMemoryCache, isFirstResource)
								.animate(new BitmapDrawable(imTarget.getView().getResources(), resource), imTarget);
					}`

is null

**Comment by iker-garcia** [comment]
I have to test it
Tomorrow morning in spain i answer you
Thank you very much
