### ISSUE TITLE
[Question] How many threads for Glide

### ISSUE THREAD

**Issue by Malachiasz** [bumptech/glide#3861]
I use Glide for loading of many small images in GridView. It works faster when requests are done parallelised. That's why I use Glide with OkHttp running on 16 threads. The question is how many threads to give for Glide itself. Is it better to assign 16 threads or the default configuration (with less threads) will perform better? Will all 16 threads of OkHttp be used if Glide runs on 4 threads? Currently we have 16 for Glide and another 16 for OkHttp.
(Disk caching is used as well.)

**Comment by sjudd** [comment]
16 threads is a lot, but the best answer is to try a few different thread counts on different devices for your app and see. Glide's defaults are meant to be reasonable and seem to work well on most types of devices. If you don't have an explicit reason to change them, I wouldn't.
