### ISSUE TITLE
onResourceReady is called together with onLoadFailed on some devices

### ISSUE THREAD

**Issue by edgar-zigis** [bumptech/glide#3866]
**Glide Version**: 4.8.0

**Integration libraries**: none

**Device/Android Version**: Samsung Galaxy J5 (6.0) (also J3 etc.), it seems that all the Samsung of J series have this issue, LG K10 (6.0), Telefunken Outdoor (7.0), WIKO U Feel (6.0)

**Issue details / Repro steps / Use case background**: I am trying to check whether certain image exists in the server and on certain devices `onResourceReady` is called together with `onLoadedFailed`. `onLoadedFailed` is always called after `onResourceReady`

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```
override suspend fun isCompleted(context: Context, url: String): Boolean {
        return suspendCancellableCoroutine { continuation ->
            GlideApp
                .with(context)
                .asBitmap()
                .load(url)
                .listener(object: RequestListener<Bitmap> {
                    override fun onResourceReady(
                        resource: Bitmap?,
                        model: Any?,
                        target: Target<Bitmap>?,
                        dataSource: DataSource?,
                        isFirstResource: Boolean
                    ): Boolean {
                        continuation.resume(true)
                        return true
                    }
                    override fun onLoadFailed(e: GlideException?, model: Any?, target: Target<Bitmap>?, isFirstResource: Boolean): Boolean {
                        continuation.resume(false)
                        return true
                    }
                })
                .submit()
        }
    }
```

I don't know how everything works in 4.9.0 version, because that version just breaks my app (images are loading inconsistently, sometimes app freezes with the latest version, so I am forced to use 4.8.0 :/ ).

**Comment by mdtuyen** [comment]
I have same issue with device xiaomi

**Comment by andyboyce** [comment]
get the same question.
