### ISSUE TITLE
SkImageDecoder::Factory returned null

### ISSUE THREAD

**Issue by DysaniazzZ** [bumptech/glide#3868]
**Glide Version**:
4.9.0

**Integration libraries**:
[AndResGuard 1.2.17](https://github.com/shwenzhang/AndResGuard)

**Device/Android Version**:
Xiaomi 4 / Android 6.0

**Issue details / Repro steps / Use case background**: 
`Image don't display when use release apk. `

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
`not use generated API, not use GlideModule.`
```java
Glide.with(activity).load(resId).into(view)
```

**Layout XML**:
`no need to show this, I use glide from my codes.`
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:

```
D/skia: --- SkImageDecoder::Factory returned null
D/skia: --- SkImageDecoder::Factory returned null
D/skia: --- SkImageDecoder::Factory returned null
D/skia: --- SkImageDecoder::Factory returned null
```

**Optional**:
when I use `Glide.with(activity).load(drawable).into(view)`, everything looks like okay, but when I use `Glide.with(activity).load(resId).into(view)`, I can't see the image, and the ImageView is black.

**Comment by sjudd** [comment]
The ImagDecoder logs imply that it can't decode thee resource. What is resId? What does it correspond to? What type of resource?
