### ISSUE TITLE
When loading a network image, even though my ImageView is set to wrap_content, it fills the entire interface

### ISSUE THREAD

**Issue by qianshengta** [bumptech/glide#3870]
**Glide**：4.8.0
**Android**：9.0
**Usage Scenario**:
In RecyclerView, I need to load the network picture. The width and height of ImageView in Item layout are wrap_content, and the root layout height of Item is also determined to be wrap_content. I use ConstraintLayout for both parent layout and Item layout.But the actual effect is that the ImageView fills the entire parent layout (width and height)
**Code**
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:paddingBottom="15dp">

    <ImageView
        android:id="@+id/Image"
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:layout_marginTop="10dp"
        android:src="@mipmap/delete_clinker"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>

    <TextView
        android:id="@+id/Name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        android:text="Name"
        android:textColor="@color/colorBlack"
        android:textSize="@dimen/text_size_h4"
        app:layout_constraintLeft_toLeftOf="@id/Image"
        app:layout_constraintRight_toRightOf="@id/Image"
        app:layout_constraintTop_toBottomOf="@id/Image"/>

</android.support.constraint.ConstraintLayout>
```
```
     GlideApp.with(baseActivity)
                .load(item.pictureUrl)
                .into(imageView)
```

**Comment by qianshengta** [comment]
Additional Remarks
```
 <ImageView
        android:id="@+id/Image"
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:layout_marginTop="10dp"
        android:src="@mipmap/delete_clinker"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>
```
When I set android:scaleType="fitXY", the image can be displayed normally, but if I do not set fitXY, or set it to other modes such as fitCenter, I still fill the whole parent layout

**Comment by qianshengta** [comment]
+1

**Comment by sjudd** [comment]
Is the image larger than than the screen or around the same size?

Also in the example above you've specified an explicit width and height for your image view?

**Comment by qianshengta** [comment]
The image fills the entire parent layout，If the parent layout fills the entire screen, the image fills the entire screen。If the ImageView is given a certain size, then it can be explicitly normal at a given size。@sjudd

**Comment by sjudd** [comment]
wrap_content for Glide is treated like you want the original image size. If that original image size is larger than your screen, then it makes sense that wrap_content fills the screen.

What do you want to have happen if the image you're loading is as large as or larger than the screen size?

**Comment by qianshengta** [comment]
![Screenshot_2019-09-17-10-33-59-405_com fubang renewableresourcesclient](https://user-images.githubusercontent.com/29747624/65006802-c0f12000-d936-11e9-9c4e-90862a6daa27.png)
![Screenshot_2019-09-17-10-31-58-230_com fubang renewableresourcesclient](https://user-images.githubusercontent.com/29747624/65006804-c0f12000-d936-11e9-87fa-d08ac0eba50a.png)
These two images are one of fixed size, which appears normal, and one of wrap_content, which fills the entire screen.The actual size of the loaded web image is close to that of the fixed size one, but not enough to fill the screen
@sjudd

**Comment by qianshengta** [comment]
I tried not in RecycleView loading, but the fragments alone a ImageView loading pictures in the layout, to eliminate the effects of RecycleView but the result is the same, the picture will fill the whole parent layout, namely the whole screen

    ```
<ImageView
        android:id="@+id/full"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:scaleType="fitCenter"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>
```

```
    GlideApp.with(baseActivity!!)
                .load(price?.get(0)?.pictureUrl)
                .into(full!!)
```

**Comment by qianshengta** [comment]
I just tried to get the Bitmap load display the traditional way, from the InputStream, instead of Glide, which is the correct size
@sjudd

**Comment by qianshengta** [comment]
+1

**Comment by Suaix** [comment]
+1, same situation when i change glide from v4.0.0 to v4.11.0 to load web image in recyclerView(androidx 1.1.0). it's correct when i changed to picasso to load the web image, it looks like glide resize the ImageView size when load into View directly. my solution is download web image without ImageView first, then set the bitmap to ImageView.
```
Glide.with(context)
                .asBitmap()
                .load(url)
                .into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(Bitmap bitmap, Transition<? super Bitmap> transition) {
               imageView.setImageBitmap(bitmap);
            }
        });
```

**Comment by Suaix** [comment]
I found this description in glide source code, in ViewTarget.getTargetDimen()：
```
if (!view.isLayoutRequested() && paramSize == LayoutParams.WRAP_CONTENT) {
        if (Log.isLoggable(TAG, Log.INFO)) {
          Log.i(
              TAG,
              "Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this"
                  + " device's screen dimensions. If you want to load the original image and are"
                  + " ok with the corresponding memory cost and OOMs (depending on the input size),"
                  + " use override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT,"
                  + " set layout_width and layout_height to fixed dimension, or use .override()"
                  + " with fixed dimensions.");
        }
        return getMaxDisplayLength(view.getContext());
      }
```
when you set ImageView height wrap_content，it will resize imageview height to screen height.

**Comment by qianshengta** [comment]
> I found this description in glide source code, in ViewTarget.getTargetDimen()：
> 
> ```
> if (!view.isLayoutRequested() && paramSize == LayoutParams.WRAP_CONTENT) {
>         if (Log.isLoggable(TAG, Log.INFO)) {
>           Log.i(
>               TAG,
>               "Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this"
>                   + " device's screen dimensions. If you want to load the original image and are"
>                   + " ok with the corresponding memory cost and OOMs (depending on the input size),"
>                   + " use override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT,"
>                   + " set layout_width and layout_height to fixed dimension, or use .override()"
>                   + " with fixed dimensions.");
>         }
>         return getMaxDisplayLength(view.getContext());
>       }
> ```
> 
> when you set ImageView height wrap_content，it will resize imageview height to screen height.

Bingo，That's really where the problem comes from

**Comment by qianshengta** [comment]
In conclusion, Glide is not completely free to use WRAP_CONTENT, it is not completely determined by the size of the image itself, there must be a preset size, do I understand right here?
@Suaix
