### ISSUE TITLE
Glide is not compatible with android-X

### ISSUE THREAD

**Issue by baldapps** [bumptech/glide#3884]
Glide 4.9.0 and annotation processors 4.9.0. It's impossible to compile because the code generated for glide modules contains the old android annotations instead of using annotations included in android-x packages.

**Comment by bmilovanovic** [comment]
I can't build the application without support libraries due to the generated code in GlideOptions. This is a huge issue.

**Comment by jmarks213** [comment]
Try the snapshot 'com.github.bumptech.glide:glide:4.10.0-SNAPSHOT'

**Comment by sjudd** [comment]
Duplicate eof #3184
