### ISSUE TITLE
[Question]: How to optimize a very resource consuming operation?

### ISSUE THREAD

**Issue by isabsent** [bumptech/glide#3885]
How to optimize a case when I should use `fallback` with some very resource consuming operation, which is necessary only if `load` fails?     

    Glide.with(act)
            .load(url)
            .fallback(veryConsumingOperation() == null ? getResources().getDrawable(R.drawable.avatar_default, null) : veryConsumingOperation())
             ...
I would like to **keep reference on the result of `veryConsumingOperation()`** somehow, to do not perform it twice inside of a `fallback`.

**Comment by isabsent** [comment]
Up!

**Comment by sjudd** [comment]
Glide doesn't provide any particular mechanism for caching this, but you could do something yourself based on the requested model?
