### ISSUE TITLE
Gif Compression

### ISSUE THREAD

**Issue by creativepsyco** [bumptech/glide#389]
Hi,

Currently I am downloading Gifs using Glide like this. Is there a way to override the default compression.

```java
File file = Glide.with(context)
                            .load(url)
                            .downloadOnly(width, height)
                            .get();
```

**Comment by TWiStErRob** [comment]
Do you want to load GIFs and save them as something else (PNG/JPG)?

**Comment by creativepsyco** [comment]
I want to share the GiFs from one app to the other. As such I would like to provide a compressed version when forwarding, is there was a way for Glide to do this, provide me a final Gif File which is according to some compression options that I can provide?

**Comment by sjudd** [comment]
There isn't a way to do this entirely within Glide. You can definitely request the decoded GIF, which you can then encode manually (Glide does include a GIfEncoder), or you could write decoding and encoding into an Encoder and use that when retrieving the resource. Neither method is totally supported though.

**Comment by creativepsyco** [comment]
Actually I took a look inside `GifHeaderParser` and `GifResourceDecoder` and I can decode each frame and individually compress them. Let me see how far I go with this approach.

**Comment by sjudd** [comment]
Great let us know if you need more help.
