### ISSUE TITLE
on Android 10 (Q) , Glide failed to load image from Image from local storage 

### ISSUE THREAD

**Issue by rahulpwar654** [bumptech/glide#3896]
on Android 10 , Glide failed to load image from local storage.
I have tried gettting WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE permission at runtime but still getting same error but works  fine devices below Android 10. 

I am Assuming its due to Scoped Storage in Android 10.
[Scoped Storage](https://developer.android.com/training/data-storage/files/external-scoped)
Testing on Essential Ph-1 with Android 10.

```
Glide: Load failed for file:///storage/emulated/0/Pictures/Screenshots/Screenshot_20190918-111135.png with size [306x306]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 3 causes:
    **java.io.FileNotFoundException(/storage/emulated/0/Pictures/Screenshots/Screenshot_20190918-111135.png: open failed: EACCES (Permission denied))**
    **java.io.FileNotFoundException(open failed: EACCES (Permission denied))**
    java.io.FileNotFoundException(open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(/storage/emulated/0/Pictures/Screenshots/Screenshot_20190918-111135.png: open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(/storage/emulated/0/Pictures/Screenshots/Screenshot_20190918-111135.png: open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: /storage/emulated/0/Pictures/Screenshots/Screenshot_20190918-111135.png: open failed: EACCES (Permission denied)
      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: open failed: EACCES (Permission denied)
      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(open failed: EACCES (Permission denied))
     call GlideException#logRootCauses(String) for more detail
```

**Comment by rahulpwar654** [comment]
I have found workaround for above issue on below link
[fix for above issue](https://developer.android.com/training/data-storage/files/external-scoped#opt-out-of-scoped-storage)
add
`android:requestLegacyExternalStorage="true" `
inside your application tag ```

 <application
android:name=".App"
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher" 
**android:requestLegacyExternalStorage="true"**
 ... >
```

**Comment by sjudd** [comment]
https://developer.android.com/training/data-storage/files/external-scoped

It's complicated unfortunately :/. The other option is to try to open images using MediaStore Uris rather than file paths.

**Comment by saeed-younus** [comment]
This is solve by passing Uri instead of string in load method of glide, just like this
```
              GlideApp.with(imageView.context)
                    .load(Uri.parse("file path in string"))
                    .into(imageView)
```

**Comment by sandeepmaaram** [comment]
> I have found workaround for above issue on below link
> [fix for above issue](https://developer.android.com/training/data-storage/files/external-scoped#opt-out-of-scoped-storage)
> add
> `android:requestLegacyExternalStorage="true" `
> inside your application tag ```
> 
> <application
> android:name=".App"
> android:allowBackup="false"
> android:icon="@mipmap/ic_launcher"
> **android:requestLegacyExternalStorage="true"**
> ... >
> 
> ```
> 
> ```

Thanks man, working working perfect.

**Comment by Ekta-D** [comment]
Add   android:usesCleartextTraffic="true" in Manifest will start working

**Comment by rahulpwar654** [comment]
> Add android:usesCleartextTraffic="true" in Manifest will start working

Sorry this won't work. This tag is used for allowing HTTP ( cleartext network traffic) endpoint in App.
you can read all this here
[Allowing HTTP endpoints in android  ](https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6)

**Comment by Dipongkar12** [comment]
**Is there solution for this error`**``



W/Glide: Load failed for https://firebasestorage.googleapis.com/v0/b/mfree-9290a.appspot.com/o/uploads%2F1585227800859.null?alt=media&token=b8954c84-f1c7-4c9d-b94e-c76bece7b1c6 with size [120x120]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.net.SocketTimeoutException(SSL handshake timed out)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.net.SocketTimeoutException(SSL handshake timed out)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.net.SocketTimeoutException(SSL handshake timed out)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.net.SocketTimeoutException: SSL handshake timed out
2020-03-30 11:33:28.880 13140-13140/com.example.mfree I/Glide: Root cause (1 of 1)
    java.net.SocketTimeoutException: SSL handshake timed out
```

**Comment by leephela** [comment]
I seems to have finally found the real cause to this problem, this issue is not limited to just some few manufacturers but to all the android 10 devices on a whole. Be it you are targeting api 28 and below or 29, if you are on android 10, then chances are you will encounter this issues. 

The real issues seems to be coming out from MediaMetadataRetriver class of the native android system that glide uses it to retrieved thumbnails/videoframes from media file. This MediaMetadataRetriver class of android is so unreliable , that once it got stuck somewhere in the process of retrieving, the whole other retrieval process got queued up and remain stuck forever there until it recovered again from that stuck, thus leading to a huge list of blank images.

The only viable solution is - write your own glide module to retrieve thumbnails for video, FFmpegMediaMetadataRetrieval seems to be a very good and reliable alternative to the native built in android ones.

**Comment by Roisfaozi** [comment]
i have error log like this

2020-08-12 18:19:30.825 23777-23777/com.kotlin.githubuser W/Glide: Load failed for https://avatars3.githubusercontent.com/u/121695?v=4 with size [200x200]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2020-08-12 18:43:17.855 23777-23777/com.kotlin.githubuser D/ViewRootImpl[DetailActivity]: changeCanvasOpacity: opaque=false
2020-08-12 18:43:18.088 23777-23777/com.kotlin.githubuser D/ViewRootImpl[DetailActivity]: changeCanvasOpacity: opaque=true

**Comment by xinooo** [comment]
use SAF
```java
@Override
protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (resultCode == RESULT_OK) {
        switch (requestCode) {
            case 0:
                Glide.with(MainActivity.this)
                        .load(data.getData())
                        .into(iv);
                break;
            default:
                break;
        }
    }
}
```

**Comment by LiuJQ** [comment]
> This is solve by passing Uri instead of string in load method of glide, just like this
> 
> ```
>               GlideApp.with(imageView.context)
>                     .load(Uri.parse("file path in string"))
>                     .into(imageView)
> ```

Unfortunately, you can't factory Uri like that instead of this :
```kotlin
val uri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id)
```

**Comment by dfabreguette-ap** [comment]
For me, problem was that Uri parse method was failing as it missed "file://" prefix :
```
Uri.parse("/storage...")
```

This is the right way to do it :
```
Uri.parse("file://storage...")
```

**Comment by skyboardsoftware** [comment]
>he whole other retrieval process got queued up and remain stuck forever there until it recovered again from that stuck, thus leading to a huge list of blank images.

I too had blank images, during my camera process the intent did not get a proper uri in my situation.  I just upgraded to Android 11 and discovered all these new issues.  So I used a file provider the answer and my 0 byte files became filled with camera data, and of course in the file provider's new location.

    contentUri = FileProvider.getUriForFile(MainActivity.this, BuildConfig.APPLICATION_ID + ".provider", file);

I was stuck for a little bit...

**Comment by pramodkumarp6** [comment]
I have same problem

**Comment by 01masterdisk** [comment]
> I have found workaround for above issue on below link [fix for above issue](https://developer.android.com/training/data-storage/files/external-scoped#opt-out-of-scoped-storage) add `android:requestLegacyExternalStorage="true" ` inside your application tag ```
> 
> <application android:name=".App" android:allowBackup="false" android:icon="@mipmap/ic_launcher" **android:requestLegacyExternalStorage="true"** ... >
> 
> ```
> 
> ```
this a temporary solution, 
not work now.

**Comment by wiryadev** [comment]
this issue still exist?
