### ISSUE TITLE
ERROR: Failed to resolve: com.zlc.glide:webpdecoder:1.5.4.10.0

### ISSUE THREAD

**Issue by wenqin-231** [bumptech/glide#3897]
The error happened when I try to update glide 4.10.0 from 4.9.0.

![image](https://user-images.githubusercontent.com/17612221/65296501-3d823980-db97-11e9-925c-76c7c7cadc1f.png)

The version of my Android Studio is 3.5 and the version of the build gradle is 3.3.2.

**Comment by Tolriq** [comment]
Wrong repo ;)

https://github.com/zjupure/GlideWebpDecoder
