### ISSUE TITLE
Unable to use CustomViewTarget in code

### ISSUE THREAD

**Issue by zskamljic** [bumptech/glide#3898]
**Version**: 4.10.0
No integration libraries

**Issue details / Repro steps / Use case background**: 
I have a custom view, that has a setImage(Bitmap) method. I'm using Kotlin. I was trying to load an image into said view by using:

```
Glide.with(this)
            .load(addSchemeIfNeeded(url))
            .into(object : CustomViewTarget<MyCustomView, Bitmap>(myCustomView) {
                override fun onLoadFailed(errorDrawable: Drawable?) {
                }

                override fun onResourceCleared(placeholder: Drawable?) {
                }

                override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                    myCustomView.setImage(resource)
                }
            })
```
This results in a compilation error: Type mismatch: inferred type is <no name provided> but ImageView was expected.

**Comment by zskamljic** [comment]
I needed to add ".asBitmap()" to the builder calls.

**Comment by ajithmemana** [comment]
val target = Glide.with(this@MainActivity)
            .asBitmap()
            .load(item.mediaUrl)
            .diskCacheStrategy(DiskCacheStrategy.ALL)
            .into(object : CustomTarget<Bitmap>() {
                override fun onLoadCleared(placeholder: Drawable?) {
                    TODO("Not yet implemented")
                }

                override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                    TODO("Not yet implemented")
                }

            })

**Comment by gussiekassulke** [comment]
We'd be interested in reading more of your writing. I'd like to encourage you to join me in playing the hysterically funny game [mr mine](https://mr-mine.com)
