### ISSUE TITLE
googles iosched glide-3.2.0a incompatibilities

### ISSUE THREAD

**Issue by dwolk** [bumptech/glide#390]
Hi, im using goolges iosched sample app which contains a version of glide.
The version glide-3.2.0a is older and misses a bugfix which I need for transparent pngs Fix #131.
It also has different interfaces like ModelRequest which I dont see in any other glide version and which makes it difficult to upgrade. Do you know about this and do you have idea how to do an upgrade?
thanks
Stefe

**Comment by TWiStErRob** [comment]
`ModelRequest` is now `RequestManager`, see commit e973585.

Also note that 3.x.0a was an early access/development version, 3.3.0 was the first GA version and it's in a [maven repo](http://mvnrepository.com/artifact/com.github.bumptech.glide/glide).

Maybe it would worth a PR for them to upgrade to 3.5.2. I'll take a look if it's a quicky, it should be.

**Comment by dwolk** [comment]
ok, thanks a  lot
