### ISSUE TITLE
How to manually add image to glide's cache?

### ISSUE THREAD

**Issue by adast** [bumptech/glide#3902]
I have uri which contains path to some image. Also I have future network link on this file(File hasn't been uploaded to the server yet, the link is empty). For example: example.com/cat.jpg
I want to store this file in cache with key "example.com/cat.jpg", in order to further access it as a regular link. 
Like so:
```
Glide.with(this).load("example.com/cat.jpg")
    .into(...)
```
How to solve this problem?

**Comment by adast** [comment]
To cache it, I want to do something like that:
```
Glide.with(this)
                    .load(object: GlideUrl(fileUri) {
                        override fun getCacheKey(): String {
                            return "example.com/cat.jpg"
                        }
                    })
                    .diskCacheStrategy(DiskCacheStrategy.DATA)
                    .preload()
```
Is there GlideUrl, but for files?

**Comment by sjudd** [comment]
It's not possible to manually add a file to Glide's cache, but you can customize cache keys, see http://bumptech.github.io/glide/doc/caching.html#custom-cache-invalidation or http://bumptech.github.io/glide/tut/custom-modelloader.html
