### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference com.bumptech.glide.load.resource.gif.GifFrameLoader.getWidth

### ISSUE THREAD

**Issue by nininea1** [bumptech/glide#3904]
I'm using glide to load gif from drawable , it causes crashes sometimes 
` Glide.with(context).asGif().load(gifResId).fitCenter().override(resources.getDimension(R.dimen.hourglass_width).toInt())
            .into(ivIcon)`

here is a stack trace :

com.bumptech.glide.load.resource.gif.GifFrameLoader.getWidth (GifFrameLoader.java:132)
com.bumptech.glide.load.resource.gif.GifDrawable.getIntrinsicWidth (GifDrawable.java:269)
android.widget.ImageView.invalidateDrawable (ImageView.java:232)
android.graphics.drawable.Drawable.invalidateSelf (Drawable.java:385)
android.graphics.drawable.Drawable.setVisible (Drawable.java:764)
com.bumptech.glide.load.resource.gif.GifDrawable.setVisible (GifDrawable.java:264)
android.widget.ImageView.onDetachedFromWindow (ImageView.java:1487)
android.view.View.dispatchDetachedFromWindow (View.java:14607)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3064)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3064)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3064)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3064)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3064)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3064)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3064)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3064)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3064)
android.view.ViewRootImpl.dispatchDetachedFromWindow (ViewRootImpl.java:3068)
android.view.ViewRootImpl.doDie (ViewRootImpl.java:5606)
android.view.ViewRootImpl.die (ViewRootImpl.java:5583)
android.view.WindowManagerGlobal.removeViewLocked (WindowManagerGlobal.java:397)
android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:352)
android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:118)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:3885)
android.app.ActivityThread.access$1500 (ActivityThread.java:153)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1401)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5451)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

**Comment by sjudd** [comment]
Can you fill out the issue template? And/or provide a reproducible test case? http://bumptech.github.io/glide/tut/failing-test-cases.html

**Comment by yueshao6800** [comment]
我们遇到了同样的问题问题
