### ISSUE TITLE
Glide loads only half of image

### ISSUE THREAD

**Issue by Ncit** [bumptech/glide#391]
I created an app,where i need to load images in feed(recyclerview), but sometimes glide shows only part of image

**Comment by TWiStErRob** [comment]
Thanks for the report, can you please provide more information based on [the guidelines](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues). You can click on issue template link and edit the above comment based on the template.

**Comment by sjudd** [comment]
Please feel free to re-open when you get the chance to fill out the issue template, thanks!

**Comment by sayem405** [comment]
I am facing the same problem.
Glide Version : com.github.bumptech.glide:glide:3.8.0
Device : Nexus 5x OS: 8.1.0
Code I Used:
`mGlide = Glide.with(view.getContext());
mGlide.load(imgFile).error(placeHolderResDrawable).dontAnimate().diskCacheStrategy(DiskCacheStrategy.NONE)
                            .fitCenter().into(this);`

![2017-12-22_15-07-04](https://user-images.githubusercontent.com/5779992/34293160-e04c594e-e72d-11e7-9fc5-a2775b0f15a8.png)

**Comment by luoyincheng** [comment]
I am facing the same problem too.
![Screenshot from 2021-01-26 16-23-05](https://user-images.githubusercontent.com/37969236/105819313-fb6ed080-5ff2-11eb-945c-650e1158f64b.png)
