### ISSUE TITLE
Glide loads vector drawable pixelated

### ISSUE THREAD

**Issue by TatankaConCube** [bumptech/glide#3915]
**Glide Version**: 4.9.0

**Device/Android Version**: Xiaomi Redmi Note 5

**Issue details / Repro steps / Use case background**: 

If set vector drawable as placeholder or error image or null-path image Glide loads it so pixelated  

1. [Screenshot](https://drive.google.com/file/d/1mnnW38omw1dxWWJpS9I7crUgKtPiZmMy/view?usp=sharing)
2. [Vector drawable](https://drive.google.com/file/d/19MGQ8zjSCKiX1jofhwuIVLXpufVh3OWU/view?usp=sharing)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
    val placeholder = if (isPrivate) R.drawable.ic_avatar_placeholder else R.drawable.ic_avatar_placeholder_group

    Glide.with(activityContext)
        .load(url)
        .placeholder(placeholder)
        .error(placeholder)
        .fallback(placeholder)
        .apply(RequestOptions.circleCropTransform())
        .into(imageView)
```

**Layout XML**:
```xml
<androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/toolbar_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="?attr/selectableItemBackground">

            <ImageView
                    android:id="@+id/avatar_img"
                    android:layout_width="40dp"
                    android:layout_height="40dp"
                    android:layout_marginTop="8dp"
                    android:layout_marginLeft="8dp"
                    android:layout_marginStart="8dp"
                    android:layout_marginBottom="8dp"
                    android:background="?actionBarItemBackground"
                    android:scaleType="centerCrop"
                    tools:ignore="ContentDescription"
                    tools:src="@drawable/ic_avatar_placeholder"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintStart_toStartOf="parent"/>

           ...

        </androidx.constraintlayout.widget.ConstraintLayout>
```

**Stack trace / LogCat**:
```
No any errors in log 
```

**Comment by dmalukov** [comment]
Apparently it happens because Glide converts VectorDrawable to Bitmap using dimensions provided 
by the instance of VectorDrawable. You can check it out [here](https://github.com/bumptech/glide/blob/d2bb3e8a6a2296b20ecaeb7759c16ef15aacbb28/library/src/main/java/com/bumptech/glide/load/resource/bitmap/DrawableToBitmapConverter.java#L73).

I solved this problem by implementing my own ResourceBitmapDecoder and replacing the default one using the AppGlideModule.
