### ISSUE TITLE
Failed resolution of: lcom/bumptech/glide/R$id

### ISSUE THREAD

**Issue by NikolayPavlov-UA** [bumptech/glide#3923]
I am using Glide 4.10.  When the application starts, a crash occurs: failed resolution of: lcom / bumptech / glide / R$id.

**Comment by lgl88911** [comment]
@NikolayPavlov-UA Hello, could you help share how to resolve the issue. I build 4.11.0 When the application starts, a crash occurs: failed resolution of: lcom / bumptech / glide / R$id. Thanks

**Comment by NikolayPavlov-UA** [comment]
Используйте implementation 'com.github.bumptech.glide:glide:4.10.0@aar'

вт, 26 нояб. 2019 г., 8:30 Frank Li <notifications@github.com>:
