### ISSUE TITLE
Extracting Image from video at specified time is not accurate

### ISSUE THREAD

**Issue by RajasekharaOddula** [bumptech/glide#3924]
I am trying to extract Images from a **remote video** at specified time frame from the video in my **android app**.
But most of the times its giving me some nearest Time framed image but not exact image.
for Example I am trying to extract image at 8 seconds or 12 seconds, but for both the requests, I am getting 10 second image.
below is my code snippet.

```
private void setFrameImageAtTime1(ImageView imageView) {
        long frameTimeMicroSecs = 1000 * getFrameTimeinMillis();

        RequestOptions options = new RequestOptions().frame(frameTime);

        Glide.with(mContext)
                .load(mVideoUri)
                .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
                .thumbnail(0.1f)
                .apply(options)
                .into(imageView);
    }
```

**> I am using Glide version 4.9.0.
> implementation 'com.github.bumptech.glide:glide:4.9.0'**

Please suggest if there is any other approach to achieve this.

**Comment by sjudd** [comment]
Frame maps pretty directly to MediaMetadataRetriever. You probably also need to specify a frame option: https://github.com/bumptech/glide/blob/690f815267611d44978769a90b12d02fe4483a91/library/src/main/java/com/bumptech/glide/load/resource/bitmap/VideoDecoder.java#L84

https://developer.android.com/reference/android/media/MediaMetadataRetriever.html#getScaledFrameAtTime(long,%20int,%20int,%20int)

**Comment by RajasekharaOddula** [comment]
So, How can I Supply my **FRAME_OPTION** instead of default **FRAME_OPTION**.
Because if I use **MediaMetadataRetriever** with 

> MediaMetadataRetriever.OPTION_CLOSEST

its working fine.
Here 

> glide/library/src/main/java/com/bumptech/glide/load/resource/bitmap/VideoDecoder.java
> Line 84 in 690f815
>  public static final Option<Integer> FRAME_OPTION = 
> 
using MediaMetadataRetriever.OPTION_CLOSEST_SYNC

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/options.html#component-options

You can set the frame option using that API
