### ISSUE TITLE
GLIDE RequestBuilder#error

### ISSUE THREAD

**Issue by rupayandutta** [bumptech/glide#3927]
I am using GLIDE 4.9.0.
In load API, I am passing GlideRequest::error parameter in load request to handle fallback case. Is there a way to know from GLIDE if original url/image was loaded or fallback one was loaded into image view?

**Comment by sjudd** [comment]
I believe you can add a `RequestListener` to just the error request and that listener will only be called if the error request is actually going to set its image.
