### ISSUE TITLE
 java.lang.ClassCastException: int[] cannot be cast to java.lang.Object[]

### ISSUE THREAD

**Issue by zhqljh** [bumptech/glide#3928]
Hello, I am a developer in China.On one model, I found a problem:
Java. Lang. ClassCastException: int [] always be cast to Java. Lang. Object []
...
Then there will be:
You cannot call glide. Get () in registercomponents() use the provided glide instance instead
...
It's something I've never seen on any other plane.I can make sure that the values are passed correctly.Sorry, my English is not good, please forgive me

**Comment by sjudd** [comment]
Duplicate of #3296
