### ISSUE TITLE
Image doesn't resize

### ISSUE THREAD

**Issue by glagola** [bumptech/glide#393]
Hi!
https://glide.herokuapp.com/kayaks.jpg is **2184x1456**
https://glide.herokuapp.com/kayaks.jpg?w=2184&h=1200&fit=crop still is **2184x1456**

This is a bug or I'm doing something wrong?

**Comment by TWiStErRob** [comment]
I think this issue was meant for thephpleague/glide, this glide is an android image loading library.

**Comment by glagola** [comment]
@TWiStErRob Sorry) wrong link)
