### ISSUE TITLE
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91

### ISSUE THREAD

**Issue by baybomax** [bumptech/glide#3931]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by baybomax** [comment]
is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).

**Comment by baybomax** [comment]
Did you use androidx ?

**Comment by heskadon** [comment]
implementation 'com.android.support:appcompat-v7:28.0.0'
.
.
.
implementation 'com.github.bumptech.glide:glide:4.10.0'

I've got Manifest merger failed after updated glide to 4.10.0, it might caused by it's using androidx support lib. So I stay the old glide:4.9.0'

**Comment by ramakrishnajoshi** [comment]
I was getting below build error when I used **Glide(4.10.0)** in my **non**-Android**x** project.

> Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:10:9-19 is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:10:12-26 value=(androidx.core.app.CoreComponentFactory). Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:3-8:8 to override.

Issue resolution:
Looks like from Glide 4.10.0, glide uses AndroidX and there can't be both Androidx and non-androidx libraries in a project. So to resolve this issue:
1. Use either Glide - 4.9.0 in **non**-android**x** project.
2. Or migrate your project to [AndroidX](https://developer.android.com/jetpack/androidx/migrate)

**Comment by ramakrishnajoshi** [comment]
More info here : https://stackoverflow.com/a/56667177/8956093
