### ISSUE TITLE
Images look pixelated when using Glide V4 vs v3 despite both using ARGB_8888

### ISSUE THREAD

**Issue by thrlr123** [bumptech/glide#3936]
**Glide Version**: 4.10.0

**Device/Android Version**: Samsung Galaxy S8+  Android 8.0, Pixel 9.0

**Issue details / Repro steps / Use case background**: 

I upgraded from Glide v3 to v4 (4.10.0)  

MyCustomConfig.java:  

``` 
@GlideModule
public class MyCustomConfig extends AppGlideModule {

    @Override
    public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
        super.applyOptions(context, builder);
        builder.setDefaultRequestOptions(new RequestOptions()
                .format(DecodeFormat.PREFER_ARGB_8888));
    }

    @Override
    public void registerComponents(
            @NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        super.registerComponents(context, glide, registry);
        registry.replace(String.class, InputStream.class, new MyCustomConfig.Factory());
    }

    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }

```

XML:
 ```
       <ImageView
        android:id="@+id/fm_backdrop_image"
        android:layout_width="match_parent"
        android:layout_height="260dp"
        android:importantForAccessibility="no"
        android:layout_alignParentTop="true"
        android:scaleType="centerCrop" />
```

Usage in V3:   

 ```
        Glide.with(getContext().getApplicationContext())
        .load(path)
        .into(backDropImage);
```

Log from listener:   
```
2019-10-18 14:40:42.816 8704-8704/com.abc.xyz V/GLIDE: .onResourceReady(GlideBitmapDrawable@e4a919(1080x1370@ARGB_8888), http://lh3.googleusercontent.com/gwOR1B2TIfGQVlCU7, Target for: androidx.appcompat.widget.AppCompatImageView{f37cdde V.ED..... ......ID 0,0-1080,1370 #7f0a00e3 app:id/fm_backdrop_image}(params=-1x1370->size=1080x1370), sync, first)  

```

Usage in V4: 

```
        Glide.with(getContext().getApplicationContext())
        .load(path)
        .into(backDropImage);
```

Log from listener:

```
2019-10-18 14:46:56.208 10339-10339/com.abc.xyz V/GLIDE: .onResourceReady(BitmapDrawable@61c712c(1080x1370@ARGB_8888), http://lh3.googleusercontent.com/gwOR1B2TIfGQVlCU7, Target for: androidx.appcompat.widget.AppCompatImageView{89fc7f5 V.ED..... ......ID 0,0-1080,1370 #7f0a00e3 app:id/fm_backdrop_image}(params=-1x1370->size=1080x1370), MEMORY_CACHE, first)
```

Both logs look the same with same image size, why are the images looking different? This has happened in the past too so I didn't upgrade for an year and tried to do it now and I am facing the same issue @TWiStErRob @sjudd  Please help, thanks. 

![Glide_v3](https://user-images.githubusercontent.com/15134212/67154037-810cb800-f2a9-11e9-9159-71d9e4ffd717.JPG)
![Glide_v4](https://user-images.githubusercontent.com/15134212/67154038-810cb800-f2a9-11e9-91dc-89b539d03bab.JPG)

**Comment by thrlr123** [comment]
Screenshots attached

**Comment by thrlr123** [comment]
@TWiStErRob @sjudd Any updates on the issue above? Thanks.

**Comment by sjudd** [comment]
I'd expect it's a difference in how match_parent is treated across the two different versions, or the timing when Glide tries to guess the size. You might try stepping through this method to see if you can figure out which size is being used and why: https://github.com/bumptech/glide/blob/1ed76ee49eae26999e808ce6fc18b2c43a192751/library/src/main/java/com/bumptech/glide/request/target/ViewTarget.java#L435

**Comment by thrlr123** [comment]
@sjudd 

Earlier,I had some code to setup layoutparams after setting an image using glide into an imageview and below are the values I got when I stepped through the method you mentioned above:  

```
layoutParams.width = 0
getTargetWidth() —> getTargetDimen(0, -1, 0) —> 0 
```

```layoutParams.height= 683 
getTargetHeight() —> getTargetDimen(0, 683, 0) —> 683
```


 Once getSize is done then on size ready this is what I got:
 onSizeReady() —> width=1080height=1068

  Now, I rearranged some of that code so this is what I am seeing:
```
  layoutParams.width = 1080 
getTargetDimen(0, 1080, 0) —> 1080 
```

```
layoutParams.height= 1068 
getTargetHeight() —> getTargetDimen(0, 1068, 0) —> 1068
```

The images still do not look the same.
![Screenshot_20191114-163618~2](https://user-images.githubusercontent.com/15134212/68908597-ab169600-0700-11ea-9021-e271b3f564e0.png)
![Screenshot_20191114-164148~2](https://user-images.githubusercontent.com/15134212/68908598-ab169600-0700-11ea-8732-e62ddf13cf49.png)
