### ISSUE TITLE
Error in the android

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [bumptech/glide#3945]
I got an error in this library when I was tried to run the app. So please let me know me how to fix these issues. See screenshot below

![Screenshot (29)](https://user-images.githubusercontent.com/39325207/67393103-58ddcb80-f5bf-11e9-81cc-72d6cba19431.png)

**Comment by sjudd** [comment]
You may have dependencies projects that depend on different versions on Glide?

**Comment by KanwarpartapSinghBimrah** [comment]
@sjudd Hi I had updated the new and latest the dependency but result same. Have any solution for it.
