### ISSUE TITLE
load into bitmap with glide

### ISSUE THREAD

**Issue by aabolfazl** [bumptech/glide#3970]
hello guys
i want load from path with glide into bitmap but glide just accept ImageView!
Anyone have a solution for this?

**Comment by AliAzaz** [comment]
Try to implement this solution:

`Glide.with(this)
        .asBitmap()
        .load(imagePath)
        .into(object : CustomTarget<Bitmap>(){
            override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                imageView.setImageBitmap(resource)
            }
            override fun onLoadCleared(placeholder: Drawable?) {
                // this is called when imageView is cleared on lifecycle call or for
                // some other reason.
                // if you are referencing the bitmap somewhere else too other than this imageView
                // clear it here as you can no longer have the bitmap
            }
        })`
