### ISSUE TITLE
[Bug] crossFade(xxx) duration not respected

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#398]
**Glide Version/Integration library (if any)**: 3.5.2
**Device/Android Version**: All
**Issue details/Repro steps**:
Use .crossFade(2500) without using .placeholder(mDefaultImageResource) 

**Glide load line**:
```
        Glide.with(ctx)
                .load(DisplayHelper.getGlideImageRequest(buffer))
                .centerCrop()
                .error(mDefaultErrorResource)
                .crossFade(250)
                .into((ImageView) view.getTag(imageViewId));
```

From the doc crossFade should fade in when there's no place holder.

But in the cases where there's no placeHolder the duration parameter is not applied.

**Comment by TWiStErRob** [comment]
Can you please edit your report by filling in the [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md)?
