### ISSUE TITLE
Can glide support  cache priority？

### ISSUE THREAD

**Issue by kayan1990** [bumptech/glide#3980]
I have a scene below:

when the network is 3G, the image url is  http://www.xxx.com/imge.png?Q=75
when the network is wifi, the image url is  http://www.xxx.com/imge.png?Q=100 

**Q means the image quality，Q= 75 means the image quality is 75%**

when the user network is 3G，To save data usage, our apps will request  http://www.xxx.com/imge.png?Q=75, but when the network changed to wifi, data usage is not so important, so we will request  http://www.xxx.com/imge.png?Q=100. since now, **wo have two cache for imge.png: Q=50 and Q=100**,  then if the network changed to 3G again, we have already cached the image Q=100, **but in fact, the request is  http://www.xxx.com/imge.png?Q=75, so the image Q=75 cache hitted, not Q=100.**

So is any way to achieve this feature? 
Thanks a lot

**Comment by sjudd** [comment]
Yes, check out alternate cache keys for custom model loaders: http://bumptech.github.io/glide/javadocs/4100/com/bumptech/glide/load/model/ModelLoader.LoadData.html#LoadData-com.bumptech.glide.load.Key-java.util.List-com.bumptech.glide.load.data.DataFetcher-

See also: http://bumptech.github.io/glide/tut/custom-modelloader.html
