### ISSUE TITLE
CenterCrop not refreshing bitmap after view bounds change

### ISSUE THREAD

**Issue by ursusursus** [bumptech/glide#3984]
Hi,
I have a imageView, which loads a image with CenterCrop transform. Some time later, imageView I change the height of the ImageView. The dimensions of the ImageView change accordingly (view bounds), but the Bitmap remains the same (just gets centered), it doesn't recalculate correct CenterCrop according to the new bounds.

This feels like a bug.

Is there something I can to refresh just the bitmap? I think the CenterCrop should react to the bounds change. For example FitCenter does so correctly

```
<FrameLayout
    android:layout_width="72dp"
    android:layout_height="match_parent"> <---------- this will change

    <ImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    ...

</FrameLayout>

private val roundRadius = itemView.resources.getDimensionPixelSize(R.dimen.roundRadius)
private val requestOptions = RequestOptions().transform(CenterCrop(), RoundedCorners(roundRadius))

Glide.with(itemView.context)
            .load(item.uri)
            .apply(requestOptions)
            .into(imageView)
```

// Glide 4.10.0
// It does however work if I set scaleType="centerCrop" on the ImageView. I thought that was not supposed to be used with Glide, correct?
// Edit: it doesn't work, it just centerCrop's the CenterCrop'd bitmap, so it just stretches the already cropped bitmap, hopefully you understand

**Comment by ursusursus** [comment]
Is anybody maintaining this library anymore?

**Comment by sjudd** [comment]
Glide only detects the initial size of the view, if you want the image to refresh when you change the size of the view, you'll need to start a new request.

**Comment by ursusursus** [comment]
I see. Will the next load().into() fix it? should it be an actual network request? Since in my head it should hit the memory cache, and return that bitmap synchronously, and transformations are already applied to it (corners), they wont get recalculated

**Comment by ursusursus** [comment]
Ok I figured out the problem, it is as you said, however I'm unclear what the proper solution should be.

The issue is that my image view has dynamic aspect ratio, i.e. the aspect ratio is part of the model, I change it like this

```
class AspectRatioImageView {
    fun setAspectRatio(aspectRatio: Float): Boolean {
        if (this.aspectRatio != aspectRatio) {
            this.aspectRatio = aspectRatio
            requestLayout()
            return true
        }
        return false
    }
}```

The view holder looks like this

```
class ViewHolder {
    fun bind(message: ImageMessage) {
        imageView.setAspectRatio(message.aspectRatio)

        Glide.load(itemView.context)
            .load(message.url)
            .apply(RequestOptions().transform(FitCenter(), RoundedCorners(roundRadius)))
            .into(imageView)
    }
}
```
So what happens is this:
If I have multiple images in the recylcerview, I scroll away, then back, they get recycled, i.e. message get bound to a new holder, where it's imageView has previously different aspect ratio. This as per code above will cause layout. However Glide seems to read the current values synchronously - which are from the previous bind(), and loads bitmap for such size. 

Then layout actually gets ran on the next frame, resizing the image view, but as you said Glide doesnt react to this.

If I wrap glide with handler.post { }, it causes the load to be on the next frame, and **it works correctly**

But, am I now supposed to post every glide loading for dynamicly sized image views? Feels like a weird design. 

Have you encountered this before? Thanks

**Comment by sjudd** [comment]
Sorry for the delay, try: waitForLayout (see the example at the bottom of this section): http://bumptech.github.io/glide/doc/targets.html#view-targets

**Comment by a23sokolov** [comment]
> try: waitForLayout

Thank for your answer [sjudd](https://github.com/sjudd). But if we check [ViewTarget#getTargetDimension](https://github.com/bumptech/glide/blob/374306f7445ca62dce9adcb196f5c2a29b510895/library/src/main/java/com/bumptech/glide/request/target/ViewTarget.java#L435) we could see in first, that we are checking() layoutParams.width(height), and consider - size is valid, if it more than 0.(Line [440](https://github.com/bumptech/glide/blob/374306f7445ca62dce9adcb196f5c2a29b510895/library/src/main/java/com/bumptech/glide/request/target/ViewTarget.java#L440))

As a result _**waitForLayout**_ will work only on first call _**ViewHolder#onBindViewHolder**_ before view calculate init size.
