### ISSUE TITLE
If you only rely on GC, when will ActiveResources move to MemoryCache?

### ISSUE THREAD

**Issue by luohaohaha** [bumptech/glide#3985]
Recently I saw Glide's source code. I have a question. If I only rely on GC, when will the ActiveResources cache resource move to MemoryCache? Because the source code needs to call the release method, it will move to MemoryCache when acquired==0. Can you give me an answer? Thank you, English is not good, I am very sorry.

**Comment by luohaohaha** [comment]
I found it, the issue is closed, I am very sorry

**Comment by joimxjtuse** [comment]
cleanReferenceQueue(), haha~
