### ISSUE TITLE
Can not play GIF

### ISSUE THREAD

**Issue by vietthanh393** [bumptech/glide#3989]
Glide.with(this).asGif().load("https://static.lixiapp.com/image/2019/11/17/88bc6269dad0710388314c33aa94d644.gif")
                .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                .into(imageView);

I have an issue when play this link. Glide display the gif as a image. Please check. Thanks!

**Comment by vietthanh393** [comment]
Any idea from supporter?

**Comment by zhouxinghua9527** [comment]
I also encountered this problem
