### ISSUE TITLE
How to check if image is loaded?

### ISSUE THREAD

**Issue by chihao12** [bumptech/glide#399]
Hi there , i am using Glide to load an image from the website. How can i check if the loaded loaded? Like .Loaded() <- do something after its loaded.

**Comment by TWiStErRob** [comment]
What information do you want to have available in that "loaded"? Bitmap/Drawable/File/InputStream or just the fact that it's done displaying the image in an ImageView?

You can try [`.listener()`](http://bumptech.github.io/glide/javadocs/340/com/bumptech/glide/GenericRequestBuilder.html#listener(com.bumptech.glide.request.RequestListener)) or [`.downloadOnly(w,h)`](http://bumptech.github.io/glide/javadocs/340/com/bumptech/glide/DrawableTypeRequest.html#downloadOnly(int, int)) or [Custom Targets](https://github.com/bumptech/glide/wiki/Custom-targets), but if you be more specific we can suggest better.

**Comment by sjudd** [comment]
Since we haven't heard from you in a while, I'm going to close this. Please re-open if you still have questions and can answer any of the above questions.
