### ISSUE TITLE
Glide with aws cloudfront, throwing 403 error, but when i make request with okhttp i get proper response

### ISSUE THREAD

**Issue by imbharat** [bumptech/glide#3999]
Glide 4.10.0

When i try to load image into imageview with glide with custom cookie headers it throws 403 error at httpurlfetcher.java class while trying to read inputstream, but when i send the same request with okhttpclient i get proper response with response code 200, and even in browser i am able to view image.

In logs, i get file not found exception
java.io.FileNotFoundException: https://d2q89b5pewg0ry.cloudfront.net/images/hikup.jpg
But when i debug i get 403 in httpurlfetcher.java class

1.) Glide -> image is not loaded into imageview

        List<String> cookies = Session.getInstance().getCookies();
        GlideUrl glideUrl = new GlideUrl("https://d2q89b5pewg0ry.cloudfront.net/images/hikup.jpg",
                new LazyHeaders.Builder()
                        .addHeader("Cookie", cookies.get(0))
                        .addHeader("Cookie", cookies.get(1))
                        .addHeader("Cookie", cookies.get(2))
                        .build());
        Glide.with(this).load(glideUrl).error(android.R.color.white).into(profilePic);

2.) OkHttpClient -> here i get response

        OkHttpClient client = new OkHttpClient();
        final Request request = new Request.Builder()
                .addHeader("Cookie", cookies.get(0))
                .addHeader("Cookie", cookies.get(1))
                .addHeader("Cookie", cookies.get(2))
                .url("https://d2q89b5pewg0ry.cloudfront.net/images/hikup.jpg")
                .build();
        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                runOnUiThread(() -> {
                    Toast.makeText(ProfileActivity.this,e.toString(),Toast.LENGTH_LONG).show();
                });
            }
            @Override
            public void onResponse(Call call, final okhttp3.Response response) {
                runOnUiThread(() -> {
                    Toast.makeText(ProfileActivity.this, response.toString(), Toast.LENGTH_LONG).show();
                });
            }
        });

When i debug loadDataWithRedirects method in httpurlfetcher.java class

    urlConnection = connectionFactory.build(url);

    // here i put a breakpoint and evaluate urlConnection.getResponseCode(), i get 403
    how am i getting responsecode even before connection? headers are added in next line?

    for (Map.Entry<String, String> headerEntry : headers.entrySet()) {
      urlConnection.addRequestProperty(headerEntry.getKey(), headerEntry.getValue());
    }
    urlConnection.setConnectTimeout(timeout);
    urlConnection.setReadTimeout(timeout);
    urlConnection.setUseCaches(false);
    urlConnection.setDoInput(true);

    // Stop the urlConnection instance of HttpUrlConnection from following redirects so that
    // redirects will be handled by recursive calls to this method, loadDataWithRedirects.
    urlConnection.setInstanceFollowRedirects(false);

    // Connect explicitly to avoid errors in decoders if connection fails.
    urlConnection.connect();
    // Set the stream so that it's closed in cleanup to avoid resource leaks. See #2352.
    stream = urlConnection.getInputStream();

**Comment by joimxjtuse** [comment]
you do not use OkHttpGlideModule ,right?

**Comment by imbharat** [comment]
No

**Comment by imbharat** [comment]
@joimxjtuse am i missing something?

**Comment by joimxjtuse** [comment]
i can not say , use glide , then debug "RetryAndFollowUpInterceptor".  try to check headers.

**Comment by imbharat** [comment]
@joimxjtuse none of method in "RetryAndFollowUpInterceptor" class is getting called for the request...

**Comment by imbharat** [comment]
@TWiStErRob am i missing something here?

**Comment by imbharat** [comment]
@sjudd

**Comment by imbharat** [comment]
Issue has been resolved, i used okhttp integration library with interceptor to set headers. Issue was with lazy headers, when same key exists, in my case "Cookie", all the headers with that key get combined, whereas AWS Cloudfront needs 3 separate Cookie headers.
