### ISSUE TITLE
MediaStore thumbnails aren't rotated correctly.

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#400]
Branching out of #395

**Comment by eicm** [comment]
I want to extend FilterOutputStream to write out the orientation in my output stream:
...
FileOutputStream out = new ExifOrientationOutStream(path, orientation);
bitmap.compress(Bitmap.CompressFormat.JPEG, 80, out);
out.flush();
...
I appreciate it if you can guide me in the correct direction to write a ExifOrientationOutStream

**Comment by sjudd** [comment]
@eicm Can you file a new issue? That might be a little out of scope for the project though. When do you want to write out the exif orientation?

**Comment by eicm** [comment]
I'm not sure it would be in the scope of the project, do you want me to open it as a new issue?  
My personal usage is glide related but doesn't fit in the project as a feature. When I download a bitmap and want to write it to the disk, I already have downloaded the meta data for that media. I want to write in  the Exif orientation in an optimized way so when I use glide to load that image with the correct orientation. 

EndPointManager.downloadImage(context, Request.Priority.NORMAL, url,  new Listener<Bitmap>() {
            @Override
            public void onResponse(Bitmap bitmap) {
             ....
            FileOutputStream out = new ExifOrientationOutStream(path, orientation); 
            bitmap.compress(Bitmap.CompressFormat.JPEG, 80, out);
            out.flush();
            ...

**Comment by TWiStErRob** [comment]
Yes, new questions should be in new issues (you can reference other use ones by number if you want more context in the new one.)

Why don't you just rotate the Bitmap based on orientation before writing? I'm sure you can find simple utility methods for that by Googling.

**Comment by eicm** [comment]
I'm rotating it in the onResourceReady() call back based on the
orientation. I understand it's out of the scope, don't worry about it I
will find it myself.

**Comment by issamux** [comment]
using MediaStoreSignature have solved issue for me : 
Glide.with(getActivity())
     .loadFromMediaStore(uri)
     .signature(new MediaStoreSignature(mimeType, dateModified,rotation) 
     .into(mImageView);
