### ISSUE TITLE
http url is not loading in glide

### ISSUE THREAD

**Issue by SushmitaNK1994** [bumptech/glide#4004]
Glide version:'com.github.bumptech.glide:glide:3.6.1'
url:
http://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/American_Beaver.jpg/220px-American_Beaver.jpg
Not able to load this url in glide.
Glide.with(context).load("http://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/American_Beaver.jpg/220px-American_Beaver.jpg").error(R.drawable.ic_launcher_background).
                    into(holder.image_view);
Can anyone please help me with this issue.

**Comment by BFELFISH** [comment]
may be your version is 9.0，you can search how to use http in 9.0

**Comment by joimxjtuse** [comment]
found in android P？
