### ISSUE TITLE
Glide4.10   android10 problem

### ISSUE THREAD

**Issue by Roc-egg** [bumptech/glide#4007]
Hello, Glide4.10 will take a long time to load a local picture 5MB on Huawei P30Pro android10.0 phone, about 3min or so, how can I solve

**Comment by andy27149** [comment]
I have the same problem

**Comment by sjudd** [comment]
Can you attach an example image? And provide the Glide.load line? 3 minutes sounds extremely long.

Android 10 introduced exif stripping, which may substantially increase image loading times, but I'd hope not minutes

**Comment by Roc-egg** [comment]
I found that this is not a Glide problem, because the problem is resolved after the mobile phone system upgrade today.

**Comment by StephenGiant** [comment]
awkward！
