### ISSUE TITLE
Are there any plans for supporting full fledged videos in the future?

### ISSUE THREAD

**Issue by AlanCPSC** [bumptech/glide#4008]
Hello there, and thank you for maintaining this great library.

I know that the library already currently supports animated `.gif` files to a certain extent. I was wondering if there are currently any plans for supporting the singular/looping playback of full fledged video files such as (`.mp4` and `.webm`) in the future.

**Comment by sjudd** [comment]
No plans to support video playback, it's a whole different animal. ExoPlayer is a reasonable option.
