### ISSUE TITLE
I have two activity, and each of them contains an imageview to play gif resources. I want an activity transition animation, so I use startActivity(intent, ActivityOptionsCompat.makeSceneTransitionAnimation(FirstActivity.this, imageview, "image").toBundle()); but on second activity the gif do not animate just like a jpg, when I returned to firstActivity, gif do not animate too.

### ISSUE THREAD

**Issue by wuyang049679** [bumptech/glide#4019]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by wuyang049679** [comment]
I have two activity, and each of them contains an imageview to play gif resources. I want an activity transition animation, so I use
startActivity(intent, ActivityOptionsCompat.makeSceneTransitionAnimation(FirstActivity.this, imageview, "image").toBundle());
but on second activity the gif do not animate just like a jpg, when I returned to firstActivity, gif do not animate too.

**Comment by joimxjtuse** [comment]
use glide.with(applicationContext).load().into() . can solve this issue?
