### ISSUE TITLE
When using different byte array as load resource in Glide,it always show the same picture. Why?

### ISSUE THREAD

**Issue by GuchaoGit** [bumptech/glide#4022]
When I close disk cache(options.diskCacheStrategy(DiskCacheStrategy.NONE)),it shows normal.
I think something wrong for getting the key of byte array of picture. 
someone else has facing the same problem?

**Glide Version**:4.0.0

**Integration libraries**:
okhttp:3.3.1

**Device/Android Version**:Android 8.0, API26

**Comment by sjudd** [comment]
Try using a more recent version and make sure you're not overriding the default disk cache or memory cache options. Glide can't efficiently determine a cache key for byte arrays, so we default to not caching at all for that type.
