### ISSUE TITLE
RoundedCorners is not working for SVGs. 

### ISSUE THREAD

**Issue by i-m-aman** [bumptech/glide#4026]
Version 4.9.0.

I am showing SVGs using Requestbuilder like - 

```
requestBuilder =
                GlideApp.with(this)
                        .as(PictureDrawable.class)
                        .listener(new SvgSoftwareLayerSetter());
```

I want a Round SVG. To do this I set Request Options like - 
`
RequestOptions requestOptions = new RequestOptions().transform(new RoundedCorners(50));
 `

And Finally showing like this - 

```
requestBuilder.load(path).
                apply(requestOptions).
                diskCacheStrategy(DiskCacheStrategy.DATA).
                into(imageView);
```

The Result is not Rounded Image.

**Comment by i-m-aman** [comment]
Any Solutions?

**Comment by i-m-aman** [comment]
Please, someone with the solution or any hint about how to do it.

**Comment by Morteza-Rastgoo** [comment]
It seems that nobody cares...

**Comment by Morteza-Rastgoo** [comment]
Same Issue here...
