### ISSUE TITLE
Too many open files crash

### ISSUE THREAD

**Issue by TaylorRiver** [bumptech/glide#4027]
I use glide in recyclerview onBindViewHolder() {
   //....
  Glide.with(context).load(url)
  .placeholder(placehoderId)
  .error(errorId)
   .into(imageview)

}

When I quickly slide recyclclerview after a while throw 

![1](https://user-images.githubusercontent.com/59269417/71497729-74ea3b80-2894-11ea-8958-4a0979f27e88.png)

![80950d7b7182cbf459540eacb5345f2](https://user-images.githubusercontent.com/59269417/71497734-7ae01c80-2894-11ea-90bc-e942b932e651.png)

![3](https://user-images.githubusercontent.com/59269417/71497738-7fa4d080-2894-11ea-830c-81ae8915510a.png)

Glide version Latest release v4.10.0

What we have good recommendations?  let the app don't crash

**Comment by sjudd** [comment]
Have you changed the number of threads that Glide uses? Otherwise the default is something like four, so there shouldn't be more than four connections open at a time.
