### ISSUE TITLE
Feature Request: Is it possible to enable extends a custom builder with RequestBuilder using @GlideExtensions?

### ISSUE THREAD

**Issue by mochadwi** [bumptech/glide#4030]
**Glide Version**: 4.9.0

**Issue details / Repro steps / Use case background**:  

I want to extend RequestBuilder, so it can have customized builder.

* My generic listener class
```
fun <T : Any> makeLoadingRequestListener(
        failedAction: (() -> Unit)?,
        readyAction: (() -> Unit)?
): RequestListener<T> = object : RequestListener<T> {
    override fun onLoadFailed(e: GlideException?, model: Any?, target: Target<T>?, isFirstResource: Boolean): Boolean {
        failedAction?.invoke()
        return false
    }

    override fun onResourceReady(resource: T, model: Any?, target: Target<T>?, dataSource: DataSource?, isFirstResource: Boolean): Boolean {
        readyAction?.invoke()
        return false
    }
}
```

* Here's my current GlideExtensions class
```
@GlideExtension
open class MyAppGlideExtension private constructor() {

    companion object {

        @JvmStatic
        @GlideOption
        fun listener(
                options: RequestBuilder<*>,
                failedAction: () -> Unit,
                readyAction: () -> Unit
        ): BaseRequestOptions<*> {
            return options.addListener(makeLoadingRequestListener<Drawable>(
                    failedAction = failedAction,
                    readyAction = readyAction
            ))
        }
    }
}
```

My approach so far

1. Using explicit type `Drawable` will compile-error: `e: [kapt] An exception occurred: java.lang.IllegalArgumentException: @GlideOption methods must take a BaseRequestOptions<?> object as their first parameter, but the first parameter in MyAppGlideExtension#listener(RequestBuilder, Unit, Unit) is RequestBuilder<Drawable>
`
2. Unfortunately, I didn't know how to use projection to solve this issue `out-projected type prohibits`
<img width="1194" alt="Screen Shot 2019-12-31 at 3 45 33 AM" src="https://user-images.githubusercontent.com/7057959/71600059-00f3b000-2b80-11ea-99d7-ccf4dd926f73.png">

Please help!

**Comment by sjudd** [comment]
Glide's extensions don't support arbitrary overrides. Kotlin may allow you to add methods to the request builder class directly, but I'm not 100% certain.
