### ISSUE TITLE
Questions about loading pictures

### ISSUE THREAD

**Issue by JsonCooler** [bumptech/glide#4038]
I need to use internationalization in my project,So I created new drawable-zh-hdpi, drawable-en-hdpi folders and put the corresponding pictures. I used Glid.with (context) .load (R.drawable.xxx) .into (img), but I couldn't Achieve international effects,However, if I use the native method, img.setImageResource (id) can achieve internationalization

**Comment by JsonCooler** [comment]
Glide version :  implementation 'com.github.bumptech.glide:glide:4.9.0'

**Comment by zhupengxiang** [comment]
How to solve it? @JsonCooler @kypeli

**Comment by liaohuyu** [comment]
@JsonCooler @zhupengxiang 怎么解决的哇
