### ISSUE TITLE
4.11 release is missing

### ISSUE THREAD

**Issue by ZacSweers** [bumptech/glide#4042]
The tag is present but there’s no change log nor does it appear to be on maven central.

**Comment by sjudd** [comment]
Unfortunately it can take a while to propagate across all of the various hosts, but I do see it on maven central: https://search.maven.org/artifact/com.github.bumptech.glide/glide/4.11.0/aar. The release notes are available here: https://github.com/bumptech/glide/releases/tag/v4.11.0
