### ISSUE TITLE
Question about boost image show when usinig Glide

### ISSUE THREAD

**Issue by sparkfengbo** [bumptech/glide#4043]
When Bitmap or other image is ready, can  I insert the msg at the front of queue on main thread to make the image show immediately? Is there any risk when loading image? Thanks.

EngineJob.java
```
Message msg = MAIN_THREAD_HANDLER.obtainMessage(MSG_COMPLETE, this);
MAIN_THREAD_HANDLER.sendMessageAtFrontOfQueue(msg);
```

**Comment by sjudd** [comment]
Either way you're still going to wait for the next frame. I believe the practical affect here is just that views/targets are called in the opposite order after the load completes. With the current logic the most recently loaded image is set on its view/target last, with your change it would be set first.
