### ISSUE TITLE
DiskCacheStrategy.RESOURCE change bitmap pixels

### ISSUE THREAD

**Issue by wensefu** [bumptech/glide#4049]
I use glide to load bitmap, and then get pixel from the bitmap:

```java
private static Bitmap getBitmap(Context context, String path) {
        BitmapFactory.Options opt = new BitmapFactory.Options();
        opt.inJustDecodeBounds = true;
        BitmapFactory.decodeFile(path, opt);
        int ow = opt.outWidth;
        int oh = opt.outHeight;
        int w = Math.round(ow / SAMPLE_SIZE);
        int h = Math.round(oh / SAMPLE_SIZE);
        FutureTarget<Bitmap> feature = Glide.with(context).asBitmap().load(path)
                .apply(new RequestOptions().override(w, h).diskCacheStrategy(DiskCacheStrategy.RESOURCE)).submit();
        try {
            return feature.get();
        } catch (Exception e) {
            return null;
        }
    }
```

But then I got a issue, when first launch(decode from original file), the same location of (x,y)
getPixel(x,y) is not the same with bitmap decode from diskcache,
But when I set DiskCacheStrategy to DiskCacheStrategy.DATA,
getPixel(x,y) return same value.

 I dont understand,why DiskCacheStrategy change pixel of the image file?

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/caching.html#disk-cache-strategies.

The resource cache contains compressed, transformed, downsmapled versions of the thumbnails. DATA contains the original data as it was acquired. What you've described is expected.
