### ISSUE TITLE
Change DecodeFormat on a per request basis ?

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#405]
Forget to post that earlier, but it seems that there's no way to change DecodeFormat on a per request basis.

Only at glide level.

Is there a way via a specific model loader or something to have different configuration for this ?

I do no need transparency for 95% of the requests and default configuration is perfect but for the 5 last percent (known cases) I need it and activating it for everything is a huge waste of resources :(

**Comment by sjudd** [comment]
You can use ``asBitmap().format()``: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/BitmapRequestBuilder.html#format(com.bumptech.glide.load.DecodeFormat).

**Comment by Tolriq** [comment]
Hum, ok did not find this one :(

This removes the crossFade from builder so I suppose that I have to use the animate functions but then how to I access the previous image to do the cross fade ?

This also show another thing from the doc animate is not applied when image is loaded from memory, but crossfade documentation does not talk about this same limitation.

Is crossfade always applied or documentation just miss this information ?

**Comment by sjudd** [comment]
CrossFade uses Android's [TransitionDrawable][1] which expects Drawables, not Bitmaps. As a result, crossFade doesn't work out of the box with asBitmap(). I believe asBitmap() defaults to fading the view in instead.

If you need to both set the format on a per request basis and use cross fade, you can do one of two things:

1. Look at the code for .format() in BitmapRequestBuilder and apply the same pattern as a decoder and cache decoder for DrawableRequestBuilder (it's just a lot of wrapping decoders...).
2. Continue to use asBitmap(), but create a custom [ImageViewTarget][2] subclass that accepts a Bitmap, puts it into a BitmapDrawable, and then sets a [TransitionDrawable][1] on the view.

If it were me, I'd be inclined toward #2, but either one should work.

[1]: http://developer.android.com/reference/android/graphics/drawable/TransitionDrawable.html
[2]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/request/target/BitmapImageViewTarget.html

**Comment by Tolriq** [comment]
Well since it's only a very small subset of my app, I suppose I'll go with simple animation and no place holder as data should be available quickly.

Before closing this one can you confirm that either the crossfade apply even when loaded from memory or that the placeholder will not be displayed before if loaded from memory ?

**Comment by sjudd** [comment]
Neither animations nor placeholders are applied when loading resources from the memory cache.

**Comment by Tolriq** [comment]
Ok thanks.
