### ISSUE TITLE
How to check request is failed

### ISSUE THREAD

**Issue by CzBiX** [bumptech/glide#4063]
**Glide Version**: 4.11.0

**Issue details / Repro steps / Use case background**: 

In my case, if image load failed, click image will call `request.begin()` to restart image request, otherwise open image in a bigger view.
But Glide removed `isFailed` from interface `Request` in [this commit](https://github.com/bumptech/glide/commit/b2a46ef7a385abd5df38ee11b8be85868768739e#diff-aecae28e35e437a7568ffaf46f9e583b).
Is there a good practice to get request status?

**Comment by CzBiX** [comment]
Waiting…

**Comment by sjudd** [comment]
You shouldn't use the Request interface. Instead just restart the load into the same target the same way you did the first time around.

**Comment by CzBiX** [comment]
@sjudd My code looks like this:

```
fun onClickImage() {
  if (request.isFailed()) {
    request.begin()
  } else {
    // handle click event
  }
}
```

So I need to know request failed status.
