### ISSUE TITLE
http2 support

### ISSUE THREAD

**Issue by Pd51** [bumptech/glide#4065]
Glide Version:

4.11.0

dependencies {
    compile 'com.github.bumptech.glide:okhttp3-integration:1.5.0@aar'
   implementation 'com.github.bumptech.glide:glide:4.11.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
}

How to use http2 support using the single tcp connection and multiplexing the requests rather than establishing connection for every request.

**Comment by punksta** [comment]
I also need this functionality.
