### ISSUE TITLE
Support early adopters

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#407]
I was looking for an easy way to include the SNAPSHOT version into my project (which weirdly worked a had few months ago), but I just couldn't figure it out how to do it, so I ended up downloading one of the jar files I found via https://www.google.com/search?q=glide%203.6.0%20snapshot.

I suggest to add an early adopter's section to README.md or to the wiki, stating the Maven repository url (`repository { maven { url 'http://?' } }` and `compile 'com.github.bumptech.glide:glide:3.6.0-SNAPSHOT'` and whatever else is needed.

I think this would help more people start using the bleeding edge (at least in new projects) and find bugs faster. Providing a snapshot repo helps tremendously since there's no need to check the code out and build it from scratch, just 2 simple changes to build.gradle and everyone is happy. :)

**Comment by TWiStErRob** [comment]
Same for integration libraries so that the version numbers are public and easily accessible.

**Comment by Tolriq** [comment]
+1 on this, I don't know why but I was unable to build on Windows without removing things from gradle as no way to have the checkstyles and tests passing on my machine.

**Comment by TWiStErRob** [comment]
@Tolriq see #312

**Comment by Tolriq** [comment]
Well yes this is more or less what I did, but this implies some changes, making PR having modified files and so far from perfect.

**Comment by sjudd** [comment]
Great idea, I added a page here: https://github.com/bumptech/glide/wiki/Snapshots.

**Comment by TWiStErRob** [comment]
Thanks!
In the meantime I figured out why it didn't work: I added the snapshot repository under `buildscript.repositories`...
