### ISSUE TITLE
Glide resources deallocation question

### ISSUE THREAD

**Issue by perracolabs** [bumptech/glide#4078]
When using a Glide resource drawable, either a BitpmapDrawable or GifDrawable, is it necessary to perform some king of deallocation when done using it?

The resource isn’t loaded into any View. Instead is loaded using a CustomTarget<Drawable>, and kept referenced for other rendering purposes.

So, once is no longer needed, besides nulling any reference to the drawable, do we need to perform some other king of action to let Glide know that the drawable can be taken back to be reused?

**Comment by perracolabs** [comment]
Doing more research I've found that probably for a GifDrawable I need to call:

```
gifDrawable.stop();
gifDrawable.recycle();
```

Is this correct?
What bout a Drawable that holds a Bitmap? Do we need to recycle the bitmap or that would put it in a bad non-reusable state?

**Comment by perracolabs** [comment]
I found some strange behavior. After calling gifDrawable.recycle(), then sometimes other GIFs start to incorrectly render, showing garbage pixels on the back, so I'm not sure if calling this method is safe or I should do some extra steps.

**Comment by sjudd** [comment]
You do not need to do anything to deallocate. The best thing you can do is to clear the target you loaded the image into, so long as you've previously removed all other references to the drawable.

Calling recycle() can break things as you've discovered.
