### ISSUE TITLE
Shared Element Transition unexpected behavior

### ISSUE THREAD

**Issue by idanbensha** [bumptech/glide#4079]
**Glide Version**: 4.11.0

**Integration libraries**: No

**Device/Android Version**: OnePlus 6

**Issue details / Repro steps / Use case background**: 
I've been trying to implement a shared element transition for a while now. I've noted that using regular ImageViews with the regular setImageResource will work just fine whereas using Glide I do  face some problems with the transition. 

In a nutshell, I'm having a pretty simple scenario of a RecyclerView that would open a full sized photo upon click on one of the photos in the RecyclerView.
Here's a video of how the transition looks like:
![transition-github](https://user-images.githubusercontent.com/51905422/73600442-db7c0c80-4558-11ea-8fa8-35f9d6ffe82c.gif)

Spending some time trying to figure out what the problem is, I've managed to solve it using the `override()` with the same values on the RecyclerView and on the full screen image in order to force the images to be the same size.. and violla:
![transition2-github](https://user-images.githubusercontent.com/51905422/73600477-331a7800-4559-11ea-8cc1-4ecc41864489.gif)

Transition now looks just perfect, but a new major problem has now arise: Using `override()` is a bad habit, as I cannot make use of the calculated images size that Glide calculates. So either I will be using a high resolution that will be wasteful, or a small resolution that will just look bad as a full screen image. 

My current unacceptable solution would be the following: Use `override()` for the RecyclerView's image views and full screen image with the same small resolution values to get a smooth transition. Then, load the bigger size image (hopefully without any blinks). And for the returning part I should reload the image with `override()` with a small resolution of the first load, and then start the return transition. 
This solution is obviously not so great as I'm gonna have to deal with a lot of mess, calculating resolutions, handle blinking, etc.. 

This looks like some kind of bug to me, is there any more straightforward solution for that?

Thank you guys.    

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
  GlideApp.with(holder.image.getContext())
                            .load(photoFileContainer)
                            .listener(new RequestListener<Drawable>() {
                                @Override
                                public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                                    viewHolderListener.onLoadCompleted(holder.image, position);
                                    return false;
                                }

                                @Override
                                public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                                    viewHolderListener.onLoadCompleted(holder.image, position);
                                    return false;
                                }
                            })
                            .error(R.drawable.ic_clear)
                            .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                            .override(400, 400)
                            .dontTransform()
                            .into(holder.image);
```

**Transition XML**:
```
<transitionSet
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:duration="2000"
    android:interpolator="@android:interpolator/fast_out_slow_in"
    android:transitionOrdering="together">
    <changeBounds/>
    <changeTransform/>
    <changeImageTransform/>
</transitionSet>
```
**Layout XML**:
My RecyclerView's ImageView are using the `centerCrop` scaleType, and the full screen image view is using the `fillCenter` scaleType.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by idanbensha** [comment]
Any help please?

**Comment by sjudd** [comment]
There's no simple and efficient solution. setImageResource uses the full size original image, so you can always do the same if you want simplicity (Target.SIZE_ORIGINAL). It's not memory efficient though. If you want both quality and efficiency, you're going to need to load two different sized images and swap between them before/after the transition. There's also no good way for Glide to know what size you're animating to or from unless the view is that size or you tell it.

You can largely avoid blinking by using the thumbnail() API so that you load the old size and then the new size in whatever direction you're animating.

**Comment by idanbensha** [comment]
@sjudd Is there any good enough solution to first load a thumbnail version of the image and then (on demand) load the full sized image without flickering? 
I suppose that using the `thumbnail()` API is not a fitting solution here, as I have to load the full sized image only after the transition is done, and not when Glide finished loaded it.
