### ISSUE TITLE
how to allow to select only 5 image from gallery android studio 

### ISSUE THREAD

**Issue by Alkahirah** [bumptech/glide#4082]
Hellow 
I want to choose only 5 images from the gallery, not more than 5 images but I couldn't do it
Here my intent:

Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);
        intent.setType("image/*");
        startActivityForResult(intent,RESULT_LOAD_IMAGE);

**Comment by shubhamjain06** [comment]
> Hellow
> I want to choose only 5 images from the gallery, not more than 5 images but I couldn't do it
> Here my intent:
> 
> Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
> intent.addCategory(Intent.CATEGORY_OPENABLE);
> intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);
> intent.setType("image/*");
> startActivityForResult(intent,RESULT_LOAD_IMAGE);


**Did you find any solution for it??**

**Comment by DinkiAgrawal-15** [comment]
Intent intent = new Intent();
                intent.setType("image/*");
                intent.setAction(Intent.ACTION_GET_CONTENT);
                intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);

                startActivityForResult(Intent.createChooser(intent,
                        "Select Picture"), 3);

**Comment by AbdElrahman-Rafaat-Amer** [comment]
I had the same problem.
Did you find any solution for it??

**Comment by clpal** [comment]
I had the same problem.
