### ISSUE TITLE
How to get the duration of the GIF?

### ISSUE THREAD

**Issue by gmikhail** [bumptech/glide#4083]
I want to get the duration of the GIF file, does Glide allow it?

Right now I'm using Movie (https://developer.android.com/reference/android/graphics/Movie)

```
val inputStream: InputStream = File(gifPath).inputStream()
val movie = Movie.decodeStream(inputStream)
val duration = movie.duration()
```
But it is very slow with a large list of GIFs.

**Comment by sjudd** [comment]
Glide doesn't provide any way for you to get the duration of a GIF directly.

**Comment by BhavnikDesai** [comment]
Hello,
Any update on this point?
