### ISSUE TITLE
RequestFutureTarget.get() throws exceptions it doesn't declare

### ISSUE THREAD

**Issue by calvarez-ov** [bumptech/glide#4088]
**Glide Version**: 4.11.0

**Integration libraries**: None

**Device/Android Version**: Not device specific

**Issue details / Repro steps / Use case background**: 

`RequestFutureTarget.get()`throws exceptions it doesn't declare.

`RequestFutureTarget.get()` calls `RequestFutureTarget.doGet(null)`, which can potentially throw the following exceptions:
* `ExecutionException` <-- declared in `get()`
* `InterruptedException` <-- declared in `get()`
* `TimeoutException` <-- caught in `get()`
* `AssertionError` <-- thrown by `get()`, not declared
* `CancellationException` <-- thrown by `doGet()`, not declared
* `IllegalArgumentException` <-- thrown by `doGet()` (`Util.assertBackgroundThread()`), not declared

I can maybe understand the `IllegalArgumentException` not being declared, as it'll be obvious pretty quickly when using glide if you're using the wrong thread. But if there are timeouts or cancellations, exceptions are thrown which aren't declared. This might escape initial app validation and end up making an app crash on prod after releasing it.

Note, I didn't reproduce these undeclared exceptions. I did run into an `ExecutionException` on prod which escaped our validation. But that's my fault for not catching that declared exception (kotlin allows not catching exceptions). It was when looking more closely at which exceptions I should be catching, to fix my crash, that I discovered these undeclared exceptions. I may end up having to just catch `Throwable`, which is usually a code smell reported by static code analysis tools.

**Comment by sjudd** [comment]
Right now I believe the exceptions that are declared are the ones that are required to be declared (ie non-runtime exceptions).

Happy to accept a PR to javadoc CancellationException or IllegalArgumentException.

**Comment by calvarez-ov** [comment]
Not sure I'd be the best person to create such javadoc. I'm just a user of this sdk, not necessarily familiar with the internals and which scenarios could produce which exceptions.

**Comment by calvarez-ov** [comment]
Please don’t close this because of inactivity. Would like a maintainer or someone familiar with the lib’s internals to just declare or at least document the possible exceptions.

Thanks!

**Comment by calvarez-ov** [comment]
Can you please add the "documentation" label?

**Comment by sjudd** [comment]
Please see my earlier comment, I'll happily accept a PR to update the javadoc. You can see the standard Future behavior if you want some inspiration for the details. 

I'm going to close this for now because I don't plan on working on it and it doesn't sound like you are either. If you do want to send a PR, please feel free to re-open (or just send the PR).
