### ISSUE TITLE
Integration: Nextcloud Single Sign On

### ISSUE THREAD

**Issue by stefan-niedermann** [bumptech/glide#4090]
Sorry for omitting the issue template, but this is more a question which does not depend on the asked information.

I have seen the `integration`-options of glide with some different libraries such as `OkHttp` and `Volley`.

I am developer of the [Nextcloud Notes](github.com/stefan-niedermann/nextcloud-notes/) and [Nextcloud Deck](github.com/stefan-niedermann/nextcloud-deck/) app (which are android clients  apps for the correspondent Nextcloud server apps). They are depending on the [main Nextcloud app](github.com/nextcloud/android/) and do all their network traffic through the main Nextcloud app (to support the same range of edge cases, like self signed certificates, 2 factor auth and so on) - see it like a proxy which ensures authentication and such stuff.

For images and avatars we are using Glide, and we are very happy with it. To make sure, that also the Glide-images are loaded through the main app, [we wrote our own integration](https://github.com/stefan-niedermann/nextcloud-notes/tree/9560552682745a8df1a19e2ab489cb8747888483/app/src/main/java/it/niedermann/owncloud/notes/util/glide).

I read [here](https://github.com/bumptech/glide/wiki/Integration-Libraries#why-isnt-xxx-library-implemented) that you might add integrations directly upstream.

Now the actual question: **Are you interested in putting this integration to your repository or is this a too specific use-case for you?**

If so, i would be happy to prepare a Pull Request if you would accept it, otherwise i would try to maintain a own library for that stuff.

Thank you in advance

**Comment by stefan-niedermann** [comment]
Err... *bump* 😉

**Comment by sjudd** [comment]
Hey sorry for the delay. I'd recommend keeping this in your repo for the time being. There's no particular rule about what goes into integration libraries, it's mostly demand based. If we get enough requests for this integration we could always move it to the Glide repo in the future.

Thanks for asking.
