### ISSUE TITLE
Custom glide model caching same image multiple times

### ISSUE THREAD

**Issue by nicklavender** [bumptech/glide#4093]
I've implemented a custom glide model to load images I've fetched from the network myself. I am running into an issue that when I call this from different activities Glide ends up caching the image again and not reusing the already cached one. Each activity caches it correctly and will continue to load it from the cache as you leave and come back but I want the image to only be cached once. The issue seems to be in the POJO I pass my model loader. The POJO implements com.bumptech.glide.load.Key and overrides updateDiskCacheKey. I am caching with a unique String id and even though it is the same id across the different activities the bytearray that is cached differs which seems to be why it is cached multiple times.
```

@Override
	public void updateDiskCacheKey(MessageDigest messageDigest) {
		Log.d("NWLDebug", "updateDiskCacheKey with id: " + id + " with: " + id.getBytes(CHARSET));
		messageDigest.update(id.getBytes(CHARSET));
	}
```
The log statement from the different activities:
D/NWLDebug: updateDiskCacheKey with id: customFront6523192 with: [B@d3b60d7
D/NWLDebug: updateDiskCacheKey with id: customFront6523192 with: [B@20adb6d

Even though the id is the same the bytearray differs and the result is caching the same image twice.

**Glide Version**:
implementation 'com.github.bumptech.glide:glide:4.10.0'
implementation 'com.github.bumptech.glide:annotations:4.11.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```
Custom Glide module classes:

```
import android.graphics.Bitmap;
import android.util.Log;

import com.bumptech.glide.load.Key;

import java.security.MessageDigest;

import androidx.annotation.Nullable;

public class CustomGlideModel implements Key {

	private final String id;
	private final Bitmap bitmap;


	public CustomGlideModel (String id, Bitmap bitmap) {
		this.id = id;
		this.bitmap = bitmap;
	}



	public String getId () {
		return id;
	}



	public Bitmap getBitmap () {
		return bitmap;
	}


	@Override
	public void updateDiskCacheKey(MessageDigest messageDigest) {
		Log.d("NWLDebug", "updateDiskCacheKey with id: " + id + " with: " + id.getBytes(CHARSET));
		messageDigest.update(id.getBytes(CHARSET));
	}


	@Override
	public boolean equals (@Nullable final Object obj) {
		if (obj != null && obj.getClass() == this.getClass()) {
			return ((CustomGlideModel) obj).getId().equals(this.getId());
		}
		return false;
	}



	@Override
	public int hashCode () {
		return id.hashCode();
	}
}
```

```
import android.graphics.Bitmap;

import com.bumptech.glide.load.Options;
import com.bumptech.glide.load.model.ModelLoader;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public class CustomGlideModelLoader implements ModelLoader<CustomGlideModel, Bitmap> {

	@Nullable
	@Override
	public LoadData<Bitmap> buildLoadData (
			@NonNull final CustomGlideModel customGlideModel, final int width, final int height, @NonNull final Options options)
	{
		return new LoadData<>(customGlideModel, new CustomGlideDataFetcher(customGlideModel));
	}



	@Override
	public boolean handles (@NonNull final CustomGlideModel customGlideModel) {
		return true;
	}
}
```

```
import android.graphics.Bitmap;

import com.bumptech.glide.load.model.ModelLoader;
import com.bumptech.glide.load.model.ModelLoaderFactory;
import com.bumptech.glide.load.model.MultiModelLoaderFactory;

import androidx.annotation.NonNull;

public class CustomGlideModelLoaderFactory implements ModelLoaderFactory<CustomGlideModel, Bitmap> {

	@NonNull
	@Override
	public ModelLoader<CustomGlideModel, Bitmap> build (
			@NonNull final MultiModelLoaderFactory multiFactory)
	{
		return new CustomGlideModelLoader();
	}



	@Override
	public void teardown () {

	}
}
```

```
import android.graphics.Bitmap;

import com.bumptech.glide.Priority;
import com.bumptech.glide.load.DataSource;
import com.bumptech.glide.load.data.DataFetcher;

import androidx.annotation.NonNull;

public class CustomGlideDataFetcher implements DataFetcher<Bitmap> {

	private final CustomGlideModel customGlideModel;

	CustomGlideDataFetcher (CustomGlideModel customGlideModel) {
		this.customGlideModel = customGlideModel;
	}

	@Override
	public void loadData (
			@NonNull final Priority priority, @NonNull final DataCallback<? super Bitmap> callback)
	{
		if(customGlideModel.getBitmap() != null) {
			callback.onDataReady(customGlideModel.getBitmap());
		} else {
			callback.onLoadFailed(new Exception("Glide thumbnail not cached, fetch myself then reload through Glide to cache it."));
		}
	}



	@Override
	public void cleanup () {

	}



	@Override
	public void cancel () {

	}



	@NonNull
	@Override
	public Class<Bitmap> getDataClass () {
		return Bitmap.class;
	}



	@NonNull
	@Override
	public DataSource getDataSource () {
		return DataSource.LOCAL;
	}
}
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Caching depends on all aspects of the request being identical: http://bumptech.github.io/glide/doc/caching.html#cache-keys.

This might be helpful for debugging: http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses

**Comment by nicklavender** [comment]
@sjudd Ahh thanks a bunch that was a big help to see whats going on. When I look at the logs from loading the same image in the 2 activities I see:

Load 1:
`  Engine: Started new load in 0.389271ms, key: EngineKey{model=com.myapp.app.depositimages.glide.CustomGlideModel@34f8cf4a, width=521, height=259, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=-456120203, transformations={class android.graphics.drawable.Drawable=com.bumptech.glide.load.resource.bitmap.DrawableTransformation@d80ce6fa, class com.bumptech.glide.load.resource.gif.GifDrawable=com.bumptech.glide.load.resource.gif.GifDrawableTransformation@d80ce6fa, class android.graphics.Bitmap=com.bumptech.glide.load.resource.bitmap.CenterInside@d80ce6fa, class android.graphics.drawable.BitmapDrawable=com.bumptech.glide.load.resource.bitmap.DrawableTransformation@d80ce6fa}, options=Options{values={Option{key='com.bumptech.glide.load.resource.bitmap.Downsampler.DownsampleStrategy'}=com.bumptech.glide.load.resource.bitmap.DownsampleStrategy$CenterInside@bbc0b7}}}`

Load 2:
`Engine: Started new load in 0.263906ms, key: EngineKey{model=com.myapp.app.depositimages.glide.CustomGlideModel@34f8cf4a, width=1616, height=891, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=-1439219853, transformations={class android.graphics.drawable.Drawable=com.bumptech.glide.load.resource.bitmap.DrawableTransformation@5db7ce1d, class com.bumptech.glide.load.resource.gif.GifDrawable=com.bumptech.glide.load.resource.gif.GifDrawableTransformation@5db7ce1d, class android.graphics.Bitmap=com.bumptech.glide.load.resource.bitmap.FitCenter@5db7ce1d, class android.graphics.drawable.BitmapDrawable=com.bumptech.glide.load.resource.bitmap.DrawableTransformation@5db7ce1d}, options=Options{values={Option{key='com.bumptech.glide.load.resource.bitmap.Downsampler.DownsampleStrategy'}=com.bumptech.glide.load.resource.bitmap.DownsampleStrategy$FitCenter@8bfed70}}}`

So even though the model is the same, the height and width and transformation types are different so that must be why it is caching multiple times. 

Reading further it looks like if I were to use 
`.diskCacheStrategy(DiskCacheStrategy.RESOURCE)`

and change my DataFetcher to 
`public DataSource getDataSource () {
		return DataSource.REMOTE;
	}`

that would cause it to work the way I want and only cache the image once in these two cases? Does that seem correct?

 I am trying to test now but for some reason when I change to DataSource.REMOTE I get a new error when it tries to load the image:

`E/GlideExecutor: Request threw uncaught throwable
    com.bumptech.glide.Registry$NoSourceEncoderAvailableException: Failed to find source encoder for data class: class android.graphics.Bitmap`

Will continue debugging and see if I can get it working. Thanks again for the help.

**Comment by nicklavender** [comment]
I was able to resolve this issue by changing my DataFetcher to return DataSource.REMOTE and also changing the return type from Bitmap to ByteBuffer to fix the " Failed to find source encoder for data class" issue.
