### ISSUE TITLE
crcle

### ISSUE THREAD

**Issue by liaibai** [bumptech/glide#410]
how to load circle bitmap

**Comment by TWiStErRob** [comment]
Search for "android glide circle" there are solutions out in the wild.

**Comment by liaibai** [comment]
Search out or have a problem with a specific solution to get the code

**Comment by sjudd** [comment]
Hah I googled exactly what @TWiStErRob  suggested and found this: http://stackoverflow.com/questions/25278821/how-do-rounded-image-with-glide-library. 

Someone else also write a library of transformations that includes circle crop: https://github.com/wasabeef/glide-transformations
