### ISSUE TITLE
Images look pixelated on Glide V4 vs V3

### ISSUE THREAD

**Issue by thrlr123** [bumptech/glide#4104]
**Glide Version**: 4.10.0

**Device/Android Version**: Samsung Galaxy S8+  Android 8.0, Pixel 9.0

**Issue details / Repro steps / Use case background**: 

I upgraded from Glide v3 to v4 (4.10.0)  

MyCustomConfig.java:  

``` java
@GlideModule
public class MyCustomConfig extends AppGlideModule {

    @Override
    public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
        super.applyOptions(context, builder);
        builder.setDefaultRequestOptions(new RequestOptions()
                .format(DecodeFormat.PREFER_ARGB_8888));
    }

    @Override
    public void registerComponents(
            @NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        super.registerComponents(context, glide, registry);
        registry.replace(String.class, InputStream.class, new MyCustomConfig.Factory());
    }

    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }
}
```

XML:
 ```xml
       <ImageView
        android:id="@+id/fm_backdrop_image"
        android:layout_width="match_parent"
        android:layout_height="260dp"
        android:importantForAccessibility="no"
        android:layout_alignParentTop="true"
        android:scaleType="centerCrop" />
```

Usage in V3:   

```java
        Glide.with(getContext().getApplicationContext())
        .load(path)
        .into(backDropImage);
```

Log from listener:   
```
2019-10-18 14:40:42.816 8704-8704/com.abc.xyz V/GLIDE: .onResourceReady(GlideBitmapDrawable@e4a919(1080x1370@ARGB_8888), http://lh3.googleusercontent.com/gwOR1B2TIfGQVlCU7, Target for: androidx.appcompat.widget.AppCompatImageView{f37cdde V.ED..... ......ID 0,0-1080,1370 #7f0a00e3 app:id/fm_backdrop_image}(params=-1x1370->size=1080x1370), sync, first)  

```

Usage in V4: 

```java
        Glide.with(getContext().getApplicationContext())
        .load(path)
        .into(backDropImage);
```

Log from listener:

```
2019-10-18 14:46:56.208 10339-10339/com.abc.xyz V/GLIDE: .onResourceReady(BitmapDrawable@61c712c(1080x1370@ARGB_8888), http://lh3.googleusercontent.com/gwOR1B2TIfGQVlCU7, Target for: androidx.appcompat.widget.AppCompatImageView{89fc7f5 V.ED..... ......ID 0,0-1080,1370 #7f0a00e3 app:id/fm_backdrop_image}(params=-1x1370->size=1080x1370), MEMORY_CACHE, first)
```

Both logs look the same with same image size, why are the images looking different? This has happened in the past too so I didn't upgrade for an year and tried to do it now and I am facing the same issue @TWiStErRob @sjudd  Please help, thanks. 

![Glide_v3](https://user-images.githubusercontent.com/15134212/67154037-810cb800-f2a9-11e9-9159-71d9e4ffd717.JPG)
![Glide_v4](https://user-images.githubusercontent.com/15134212/67154038-810cb800-f2a9-11e9-91dc-89b539d03bab.JPG)

As mentioned in the link here: https://github.com/bumptech/glide/issues/3936

I tried stepping into getTargetDimen() with debugger and this is what I am seeing:

```
  layoutParams.width = 1080 
getTargetDimen(0, 1080, 0) —> 1080 
```

```
layoutParams.height= 1068 
getTargetHeight() —> getTargetDimen(0, 1068, 0) —> 1068
```
Despite having the dimens for height and width for image, it looks very pixelated when compared to V3. If this is happening because of mathc_parent then how is this supposed to be handled?

**Comment by TWiStErRob** [comment]
Hey, I tried reproing this. The same layout and loading code, and similar Glide modules. It all looked good. The only thing I can think of now is your secret `MyCustomConfig.Factory`. Try to disable that to see if the problem is there.

**Comment by thrlr123** [comment]
@TWiStErRob The issue is that I have super.registerComponents (context, glide, registry); before my registry.replace which is totally unnecessary and is causing this. 

```
 @Override
    public void registerComponents(
            @NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        **super.registerComponents(context, glide, registry);**
        registry.replace(String.class, InputStream.class, new MyCustomConfig.Factory());
    }
```
Though the issue is not exactly in`MyCustomConfig.Factory` thanks for pointing towards that direction.

**Comment by TWiStErRob** [comment]
It's an empty method (in `com.bumptech.glide.module.AppGlideModule`, assuming you're extending that), how can calling an empty method change behavior? Did you step into it with a debugger to confirm it's empty? (it should be)

**Comment by thrlr123** [comment]
Yeah! You're right. I saw the clear image a while ago when I removed that line, but I am back to the blurry image again. I commented out `registry.replace(String.class, InputStream.class, new MyCustomConfig.Factory());` but I am still seeing a blurry image. So, it's not MyCustomConfig.Factory() either.

<img width="484" alt="Screen Shot 2020-02-20 at 4 30 38 PM" src="https://user-images.githubusercontent.com/15134212/74992954-69337500-53fe-11ea-850d-0431fe3d156b.png">

<img width="483" alt="Screen Shot 2020-02-20 at 4 29 34 PM" src="https://user-images.githubusercontent.com/15134212/74992947-65075780-53fe-11ea-9f5d-07068313d2b6.png">

**Comment by thrlr123** [comment]
Code in MyCustomConfig.java:

```
public class MyCustomConfig extends BaseGlideUrlLoader<String> {
    @Override
    public boolean handles(@NonNull String s) {
        return false;
    }

    public static class Factory implements ModelLoaderFactory<String, InputStream> {
        private final ModelCache<String, GlideUrl> modelCache = new ModelCache<>(500);

        @NonNull
        @Override
        public ModelLoader<String, InputStream> build(@NonNull MultiModelLoaderFactory multiFactory) {
            return new MyCustomConfig(multiFactory.build(GlideUrl.class, InputStream.class), modelCache);
        }

        @Override
        public void teardown() {
        }
    }

    private MyCustomConfig(ModelLoader<GlideUrl, InputStream> urlLoader, ModelCache<String, GlideUrl> modelCache) {
        super(urlLoader, modelCache);
    }

    @Override
    protected String getUrl(String url, int width, int height, Options options) {
        if (Strings.isNullOrEmpty(url)) return null;

       Uri uri = Uri.parse(url);
        if (uri.getHost() == null) return null;
        if (uri.getHost().contains("googleusercontent") || uri.getHost().contains("abc.com")) {
            return URLs.getHttpsUrl(url + "=s" + Math.max(width, height));
        } else {
            return URLs.getHttpsUrl(url);
        }
    }
}

```

**Comment by thrlr123** [comment]
getUrl in `MyCustomConfig` is never called, I tried to debug and it never got there. Didn't print any log statements too. I changed `registry.replace` to `registry.prepend` but no luck. When I directly did ```
Glide.with(getContext().getApplicationContext())
        .load(https://lh3.googleusercontent.com/gwOR1B2TIfGQVlCU7-QgxlZcdiNWjFqNcMVaDY2AgRmq0yGef2Z7bUOHDkhpFZ1fZ4dtdYGt7WhcAfcBWr66ou6D=s1080)
```
I appended s=1080 at the end of the url manually and I could see a clear image which also confirms that getUrl changes are never applied. 

I referred to this link https://github.com/bumptech/glide/issues/2193 but all it says is to use prepend instead of append. 
@TWiStErRob

**Comment by thrlr123** [comment]
is there any update on this? Thanks. @TWiStErRob

**Comment by thrlr123** [comment]
This still seems to be an issue, any updates on this or can you point me to the right documentation? Thanks! @TWiStErRob

**Comment by thrlr123** [comment]
@TWiStErRob @kypeli @xian @jamwt Any update on this issue? Despite setting MyCustomConfig as specified in the docs getUrl() is never called. I tried using prepend, replace, and append. None of them worked.

**Comment by TWiStErRob** [comment]
Sorry, didn't have time to look yet. Are you using the right `GlideApp` import? I just thought about this. See [docs](https://bumptech.github.io/glide/doc/generatedapi.html#using-the-generated-api). I think the normal `Glide` doesn't register the `@GlideModule`, unless it's in the manifest which you probably didn't do, because you disabled manifest parsing.

**Comment by thrlr123** [comment]
@TWiStErRob 
I followed this solution a few days ago(https://stackoverflow.com/a/46638213)and updated my code as below:


Removed this from my AndroidManifest.xml:
 
```
 <meta-data
            android:name="com.abc.xyz.utils.glide.MyCustomConfig"
            android:value="GlideModule" />
```

Updated my MyCustomConfig to this (removed isManifestParsingEnabled):

```
@GlideModule
public class MyCustomConfig extends AppGlideModule {

    @Override
    public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
        super.applyOptions(context, builder);
    }

    @Override
    public void registerComponents(
            @NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        Log.d("Register components  %s", "registry called");
        glide.getRegistry().prepend(String.class, InputStream.class, new MyCustomConfigModelLoader.Factory());
    }

@Override
    public boolean isManifestParsingEnabled() {
        return false;
    }

```


And in my Fragment I'm using GlideApp instead of Glide:

```
 GlideApp.with(getContext().getApplicationContext())
                    .load(Uri.parse(backdropImageUrl))
                    .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                    .into(backDropImage)
```

Still not seeing the clear image. I changed from Glide to GlideApp only in that fragment where I want a custom url used. I didn't update in all the other places, do they. have to be? I feel like this part of the code should still work.

**Comment by TWiStErRob** [comment]
Re isManifestParsingEnabled: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/module/AppGlideModule.java#L30-L31

Are you seeing the log line? Also if yes, can you make sure that `glide.getRegistry() == registry`?

But regardless, could you share a runnable example which reproduces this? What I usually do is copy the whole project and remove all the parts that are not necessary for the problem. e.g. other activities, fragments, views, dependencies, resources, etc.

**Comment by thrlr123** [comment]
@TWiStErRob 
I am seeing the log line. And I also checked for this
```
if(glide.getRegistry() == registry)
        Log.d("Register components ", "registry called");
```
And it worked too.

**Comment by thrlr123** [comment]
Did you get a chance to look at MyCustomConfigModelLoader.java? I didn't make a lot of changes there V3 vs V4. That shouldn't be an issue at all, I guess.

**Comment by thrlr123** [comment]
I fixed the issue making the following changes and it worked.

```
public class MyCustomConfigModelLoader extends BaseGlideUrlLoader<GlideUrl> {

 @Override
    public boolean handles(@NonNull GlideUrl glideUrl) {
        return true;
    }

    public static class Factory implements ModelLoaderFactory<GlideUrl, InputStream> {
        private final ModelCache<GlideUrl, GlideUrl> modelCache = new ModelCache<>(500);

        @NonNull
        @Override
        public ModelLoader<GlideUrl, InputStream> build(@NonNull MultiModelLoaderFactory multiFactory) {
            LOG.d("ModelLoader is called");
            return new MyCustomConfigModelLoader(multiFactory.build(GlideUrl.class, InputStream.class), modelCache);
        }

        @Override
        public void teardown() {
        }
    }

    private MyCustomConfigModelLoader(ModelLoader<GlideUrl, InputStream> urlLoader, ModelCache<GlideUrl, GlideUrl> modelCache) {
        super(urlLoader, modelCache);
    }

    @Override
    protected String getUrl(GlideUrl glideUrl, int width, int height, Options options) {
        String url = glideUrl.toStringUrl();
        if (Strings.isNullOrEmpty(url)) return null;

        // make sure we are trying to retrieve an image from app engine before appending any params
        // TODO add more urls if there are more
        Uri uri = Uri.parse(url);
        if (uri.getHost() == null) return null;
        if (uri.getHost().contains("googleusercontent")) {
            LOG.d("url is altered");
            return URLs.getHttpsUrl(url + "=s" + Math.max(width, height));
        } else {
            return URLs.getHttpsUrl(url);
        }
    }
```

And this in the glide config file(GlideUrl.class instead of String.class):

```
registry.prepend(GlideUrl.class, InputStream.class, new MyCustomConfigModelLoader.Factory());
```
