### ISSUE TITLE
There is no way to upload multiple images in scope of one View

### ISSUE THREAD

**Issue by MkhytarMkhoian** [bumptech/glide#4107]
In Glide we use `View.setTag` to associate `Request` with `View`. 
You deprecate the method to set custom tags in CustomViewTarget. How to load multiple images in the scope of one View?

**Glide Version: 4.11.0**

**Comment by MkhytarMkhoian** [comment]
any updates?

**Comment by sjudd** [comment]
You can always write a custom Target, but it's not supported directly by Glide.

**Comment by MkhytarMkhoian** [comment]
> You can always write a custom Target, but it's not supported directly by Glide.

They deprecated CustomViewTarget

**Comment by sjudd** [comment]
CustomViewTarget is not deprecated: https://github.com/bumptech/glide/blob/0d7ea08d4c2c755884cff7dc19ed929bb0354ae2/library/src/main/java/com/bumptech/glide/request/target/CustomViewTarget.java#L35. 

However it won't help you solve this problem. You'd need to write your own version and manage the requests yourself using some other mechanism. It's not especially difficult to do as a part of a custom view.

**Comment by MkhytarMkhoian** [comment]
@sjudd Sorry, you are right, CustomViewTarget is not deprecated. They deprecate the method to set custom tags in CustomViewTarget

**Comment by MkhytarMkhoian** [comment]
@sjudd You mean custom RequestManager?
