### ISSUE TITLE
class com.bumptech.glide.load.engine.GlideException: Fetch failed

### ISSUE THREAD

**Issue by PreetPRG** [bumptech/glide#4113]
**Glide Version**: implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

**Integration libraries**: Retrofit 2
implementation "com.squareup.retrofit2:retrofit:2.6.2"
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'

**Device/Android Version**: Samsung M20(Android Version 10)

**Issue details / Repro steps / Use case background**: I am trying to fetch the Data from API("https://jsonplaceholder.typicode.com/photos"), the Data is fetched from api only images are not getting rendered(I have logged the url of the images and still error is that image can't be found.)  Though Image is available. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
Glide.with(mContext)
                .asBitmap()
                .apply(RequestOptions.circleCropTransform())
                .load(imageList.get(position).getUrl())
                .into(holder.image);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
It is a simple app of loading Images and its detail.
```

**Stack trace / LogCat**:

com.example.mvvm1 W/Glide: Load failed for https://via.placeholder.com/600/9c184f with size [394x394]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(https://via.placeholder.com/600/9c184f)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE

**Comment by ReactorboY** [comment]
> 
> 
> **Glide Version**: implementation 'com.github.bumptech.glide:glide:4.11.0'
> annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
> 
> **Integration libraries**: Retrofit 2
> implementation "com.squareup.retrofit2:retrofit:2.6.2"
> implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
> 
> **Device/Android Version**: Samsung M20(Android Version 10)
> 
> **Issue details / Repro steps / Use case background**: I am trying to fetch the Data from API("https://jsonplaceholder.typicode.com/photos"), the Data is fetched from api only images are not getting rendered(I have logged the url of the images and still error is that image can't be found.) Though Image is available.
> 
> **Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
> 
> ```java
> Glide.with...
> Glide.with(mContext)
>                 .asBitmap()
>                 .apply(RequestOptions.circleCropTransform())
>                 .load(imageList.get(position).getUrl())
>                 .into(holder.image);
> ```
> 
> **Layout XML**:
> 
> ```
> <FrameLayout xmlns:android="...
> It is a simple app of loading Images and its detail.
> ```
> 
> **Stack trace / LogCat**:
> 
> com.example.mvvm1 W/Glide: Load failed for https://via.placeholder.com/600/9c184f with size [394x394]
> class com.bumptech.glide.load.engine.GlideException: Failed to load resource
> There was 1 cause:
> java.io.FileNotFoundException(https://via.placeholder.com/600/9c184f)
> call GlideException#logRootCauses(String) for more detail
> Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE

same issue with me

**Comment by Yog8482** [comment]
> **Glide Version**: implementation 'com.github.bumptech.glide:glide:4.11.0'
> annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
> 
> **Integration libraries**: Retrofit 2
> implementation "com.squareup.retrofit2:retrofit:2.6.2"
> implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
> 
> **Device/Android Version**: Samsung M20(Android Version 10)
> 
> **Issue details / Repro steps / Use case background**: I am trying to fetch the Data from API("https://jsonplaceholder.typicode.com/photos"), the Data is fetched from api only images are not getting rendered(I have logged the url of the images and still error is that image can't be found.) Though Image is available.
> 
> **Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
> 
> ```java
> Glide.with...
> Glide.with(mContext)
>                 .asBitmap()
>                 .apply(RequestOptions.circleCropTransform())
>                 .load(imageList.get(position).getUrl())
>                 .into(holder.image);
> ```
> 
> **Layout XML**:
> 
> ```
> <FrameLayout xmlns:android="...
> It is a simple app of loading Images and its detail.
> ```
> 
> **Stack trace / LogCat**:
> 
> com.example.mvvm1 W/Glide: Load failed for https://via.placeholder.com/600/9c184f with size [394x394]
> class com.bumptech.glide.load.engine.GlideException: Failed to load resource
> There was 1 cause:
> java.io.FileNotFoundException(https://via.placeholder.com/600/9c184f)
> call GlideException#logRootCauses(String) for more detail
> Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE

I solved issue by using picasso as a image loading library.

**Comment by ben-ying** [comment]
> 

I solved this by adding .png to the end of the url
