### ISSUE TITLE
Glide 4.10 regression displaying an image

### ISSUE THREAD

**Issue by vanniktech** [bumptech/glide#4114]
I want to download the following image using Glide: https://www.srf.ch/static/meteo/wetterkarte/media/web/CLOUDSONLY_20200224T1500Z.png

Here's a comparison of the image being rendered on Android (left side Glide 4.9; right side Glide 4.10):

![glide](https://user-images.githubusercontent.com/5759366/75191650-0a9a2e00-5753-11ea-87a8-7da6f84d8d89.png)

Looking at the releasee notes from 4.10 it looks like these might be the root cause: 

> Add simple support for wide gamut color spaces (15a21b1, 7910f68)

When downloading / viewing the image from my computer it does look like it did when using Glide 4.9.

Is this a regression? Is there any way to get the old behaviour back when using Glide 4.10 or later?

I put up a little demo project here - https://github.com/vanniktech/playground-android/tree/glide-regression-image

**Comment by vanniktech** [comment]
Still an issue

**Comment by sjudd** [comment]
The url no longer works, but I'd guess this is WAI if the image is actually wide gamut.

**Comment by vanniktech** [comment]
What's the easiest way to check if the image is wide gamut?

**Comment by sjudd** [comment]
Maybe exiftool? I think it will show the colorspace.
