### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#412]
Me again :) with latest snapshot.

I have image quality problem with big images but does not happens when using ARGB8888

```
        Glide.with(YatseApplication.getInstance())
                .load(DisplayHelper.getGlideImageRequest(buffer))
                .centerCrop()
                .placeholder(mDefaultImageResource)
                .error(mDefaultErrorResource)
                .crossFade(250)
                .into((ImageView) view.getTag(imageViewId));
```

As you can see if you zoom the image (but very visible on the device) the fanart images have horrible vertical bars all over and looks bad :(

The images in cache that I return with a simple ```new FileInputStream(cachedFile);``` is joined too so you can see the source size and that the source image is artifact free.

![screenshot_2015-04-14-17-10-49](https://cloud.githubusercontent.com/assets/932609/7140647/c2a92a38-e2cc-11e4-9ae0-b183c4e6679f.png)

![774465504fc32e79634908be499616f3](https://cloud.githubusercontent.com/assets/932609/7140653/cb83e94a-e2cc-11e4-9227-a2784e939e61.jpg)

**Comment by Tolriq** [comment]
@sjudd I posted without edit to open discussion but the problem is caused by https://github.com/bumptech/glide/commit/e9cfd2d264c8d1f04ec3a9a26bed17ea690116c8 I have reverted locally it and have no more problems even with ARG 565.

I remember that I had to remove the inDither in my own code to such problems.

No idea about the paint flags as I did not used that before.

**Comment by sjudd** [comment]
Interesting find. Everything I could find about inDither indicates it is in fact the right thing to do when decoding RGB_565 images. It's supposed to add noise to break up banding (ironically). 

Did you revert that entire commit, or just inDither? ANTI_ALIAS should also be totally unnecessary, I can't imagine that would have an affect...

**Comment by Tolriq** [comment]
I reverted the whole commit, but I can test the flags if you want, I have just no idea how they are used and the impact :)

**Comment by sjudd** [comment]
If you can confirm that just the flags change is fine, then we can go ahead and revert the inDither change.

**Comment by Tolriq** [comment]
Seems comment was lost :( No visual impact with the FLAG change in the previous PR, on inDither degrade image quality.

But only tested on Android 5.0 and 5.1
