### ISSUE TITLE
Flickr Sample API - 'getLargerSizeKeys' always returns an empty List

### ISSUE THREAD

**Issue by valentinilk** [bumptech/glide#4121]
There is a small error in the 'getLargerSizeKeys' method in the Flickr sample. It always returns an empty List.

```java
List<String> result = new ArrayList<>();
int size = result.size();
for (int i = 0; i < size; i++) {
    // [...]
}
```

It should most probably be:
```java
List<String> result = new ArrayList<>();
int size = SORTED_SIZE_KEYS.size();
for (int i = 0; i < size; i++) {
    // [...]
}
```

The line in question can be found here:
https://github.com/bumptech/glide/blob/fb672a54e11739454f34430f856a9eeb2ea0244f/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/api/Api.java#L72

I'll gladly create a pull request if preferred.

**Comment by sjudd** [comment]
Thanks for the report, please do send a pull request.
