### ISSUE TITLE
I can not load this url using Glide! Any help! 

### ISSUE THREAD

**Issue by thanhtungtnt** [bumptech/glide#4124]
Hi all, 

I am using Glide for loading url to my app. Glide load direct image url normally. It's very fast. Thanks Glide. 

But when it meet url like this: https://tumangaonline.fun/img.php?mih=oK2qpdmfZZDHop-oll6c0aCaociRmqbOZq2XdJqddmGZocG_g5qHrNrg4cHBtqeaotHA17nK1cirmOTcyanJqw..

or urls like this: http://proxy.truyen.cloud/?data=QNH2B/kIEhWTJ9Eyn/gnoUHY/M9lqqhQFS/PbnNfRFywHDd/LWxfleFHIjSOTLOE

or https://images2-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&gadget=a&no_expand=1&resize_h=0&rewriteMime=image%2F*&url=http%3A%2F%2Fi2.imageinstant.com%2Fdata%2Fimages%2F18075%2F371937%2F001.jpg

Glide can not load it.

Anyone can help me? 

Thanks

**Comment by DanielJung** [comment]
I'm having the same issue. Any news here?
