### ISSUE TITLE
Transition and placeholder conflict

### ISSUE THREAD

**Issue by YBill** [bumptech/glide#4134]
**Problem Description**: Part of the image is transparent, and the placeholder image can be seen after loading is completed; the reason is that I set the fade-out animation(" .transition(DrawableTransitionOptions.withCrossFade())"), and I will not see the placeholder image when I remove

**Glide Version**: 4.3.1

**Integration libraries**:

    api 'com.github.bumptech.glide:glide:4.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'
    api 'com.squareup.okhttp3:okhttp:3.11.0'
    api 'jp.wasabeef:glide-transformations:3.0.1'

**Device/Android Version**: Android 8.0.0

**Issue details / Repro steps / Use case background**:  use in recyclerView

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
        GlideApp
                .with(fragment)
                .load(url)
                .placeholder(R.drawable.default_placeholder_img)
                .transition(DrawableTransitionOptions.withCrossFade())
                .into(topImageIv);

```

**Layout XML**:
```xml
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content" >

        <android.support.v7.widget.AppCompatImageView
            android:id="@+id/iv_top_img"
            android:layout_width="match_parent"
            android:layout_height="80dp"
            android:scaleType="centerCrop"
            tools:src="@tools:sample/avatars" />

    </FrameLayout>
```

**Stack trace / LogCat**:
```ruby

```

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/transitions.html#cross-fading-with-placeholders-and-transparent-images

**Comment by YBill** [comment]
Thanks very much, I know what to do
