### ISSUE TITLE
In Glide v4 it would be pretty easy to add an option to ignore exif rotation. There are a bunch of options already specified in Downsampler. You'd just add one more ``Boolean`` ``Option`` that just sets degreesToRotate to 0.

### ISSUE THREAD

**Issue by TheStar4Fate** [bumptech/glide#4135]
In Glide v4 it would be pretty easy to add an option to ignore exif rotation. There are a bunch of options already specified in [``Downsampler``](https://github.com/bumptech/glide/blob/6b137c2b1d4b2ab187ea2aa56834dea039daa090/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L43). You'd just add one more ``Boolean`` ``Option`` that just sets [``degreesToRotate``](https://github.com/bumptech/glide/blob/6b137c2b1d4b2ab187ea2aa56834dea039daa090/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L197) to 0.

_Originally posted by @sjudd in https://github.com/bumptech/glide/issues/665#issuecomment-320978452_

How to modify degreesToRotate?
Glide version:4.10.0

**Comment by 13120241790** [comment]
How to write specific code? @TheStar4Fate  @sjudd  Thanks~!

```java
 mRequestOptions.downsample(new Downsampler())
```

Downsampler.java has only parametric construction, and it is final 。

My current program occasionally finds that glide loading direction is incorrect  （v 4.13.2）
