### ISSUE TITLE
Memory cache misses

### ISSUE THREAD

**Issue by RoizzMode** [bumptech/glide#4136]
Glide version: 4.11.0

No Integration libraries

Device: Huawei M5 Lite< Android 8.0.0

Hi! I'm developing an app, which must show a lot of images in a short time (random one of ~70 images every 0.1 sec). So I want to preload images at the start of the app:

                val requestOptions = RequestOptions()
                    .dontTransform()
                    .diskCacheStrategy(DiskCacheStrategy.RESOURCE)

                Glide.with(application)
                    .load(url)
                    .apply(requestOptions)
                    .preload(width, height)

And logs for one of these images are:
Started new load in 2.51875ms, key: EngineKey{model=*url*, width=502, height=706, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=-623424093, transformations={}, options=Options{values={}}}

Then I go to another fragment and load images again:

        val requestOptions = RequestOptions()
            .dontTransform()
            .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
            .onlyRetrieveFromCache(true)
            .override(width, height)
        Glide.with(application)
            .load(url)
            .apply(requestOptions)
            .into(imageView)

And logs for the same image are:

Started new load in 0.5302089999999999ms, key: EngineKey{model=*url*, width=502, height=706, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=-623424093, transformations={}, options=Options{values={}}}

As you can see, all the parameters are the same, even hashCodes are identical. So the question is why I don't load from memory cache? Load speed is mush faster in the second time but "Started new load" says that I don't get image from cache. Or maybe it depends on which thread I preload image?

Thanks

**Comment by sjudd** [comment]
Probably the image got evicted from the memory cache after it was loaded. Depending on your cache size, the number of images you're  preloading, and the size of each image you may not have enough space to store all of them in memory.

Consider preloading up to N (5?) images ahead rather than all of them. You'll be constantly decoding images, but you won't need the cache space to store more than a few of them at a time. This is what we recommend for scrolling lists/RecyclerView in general, see [ListPreloader](https://github.com/bumptech/glide/blob/541ee73447375de543225c276e0dca473d1ebee8/library/src/main/java/com/bumptech/glide/ListPreloader.java#L29) for inspiration.

**Comment by giantramen** [comment]
I think there is a bug here, I am seeing a similar issue.

I am loading a single image with .diskCacheStrategy(DiskCacheStrategy.NONE) and then loading the same image again with .onlyRetrieveFromCache(true). The image appears the first time but then on the cache only request onLoadFailed is always called. 

`Glide.with(containerView.context)
					.load("https://i.imgur.com/QHlntjb.jpg")
					.diskCacheStrategy(DiskCacheStrategy.NONE)
					.into(image_view)`

Image appears

`Glide.with(containerView.context)
					.load("https://i.imgur.com/QHlntjb.jpg")
					.onlyRetrieveFromCache(true).submit()`

always onLoadFailed

If I remove the diskCacheStrategy from the first load it will find the image in disk cache.
