### ISSUE TITLE
Android system will kill app when  glide loadding images thumbnail of U Disk but remove it.

### ISSUE THREAD

**Issue by weishengwen2** [bumptech/glide#4138]
LOG:
03-14 16:03:53.473 1783-1791/? E/ProcessKiller: Process /system/bin/mediaserver (24477) has open file /storage/sda1/13000X65000.jpg.jpg
03-14 16:03:53.473 1783-1791/? W/ProcessKiller: Sending Terminated to process 24477
03-14 16:03:53.475 24484-24484/com.tpv.app.filemanager I/SingletonGlobal: SingletonGlobal-getScreenType-10640>-g_iScreenType=101
03-14 16:03:53.475 1783-1791/? E/ProcessKiller: Process com.tpv.app.filemanager (24484) has open file /storage/sda1/13000X65000.jpg-1.jpg
03-14 16:03:53.475 1783-1791/? W/ProcessKiller: Sending Terminated to process 24484
03-14 16:03:53.502 1772-1772/? I/ServiceManager: service 'media.player' died

**Comment by weishengwen2** [comment]
Version 4.8.0:
Loading U disk video thumbnails for adapter and Pull out it quickly, follow code:
GlideApp
                                    .with(viewHolder.imageView.getContext())
                                    .load(file.getPath())
                                    .placeholder(R.drawable.image_selector)
                                    .error(R.drawable.image_selector)
                                    .skipMemoryCache(true)
                                 .fallback(R.drawable.image_selector)
                                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                                    .listener(new RequestListener<Drawable>() {

                                        @Override
                                        public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                                            return false;
                                        }

                                        @Override
                                        public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                                            FileInfoBean f = null;
                                            if (viewHolder.imageView.getTag(R.id.item_iv) instanceof  FileInfoBean) {
                                                f = (FileInfoBean) viewHolder.imageView.getTag(R.id.item_iv);
                                            }
                                            if (null == file || null == f) {
                                                return false;
                                            }
                                            if (!file.equals(f)) {
                                                return false;
                                            }
                                            if (resource != null) {
                                                viewHolder.imageView.setImageDrawable(resource);
                                            }
                                            return false;
                                        }
                                    }).into(viewHolder.imageView);

**Comment by sjudd** [comment]
I'm not sure that this is feasible to solve. We have to open the file to render it. I don't believe the application has any signal to close the file before its killed?

**Comment by weishengwen2** [comment]
Thanks for you answer.
I explored the answer for who kill my application from above logcat,I get information from bbs:https://www.optbbs.com/thread-1598146-1-1.html. Android/system/vold/Processer.cpp::killProcessesWithOpenFiles but not glide kill my app because Glide was loading images of sdcard, and i unmount it quickly.
I wonder if glide have any plans to cope with the situation?

**Comment by weishengwen2** [comment]
Hi,
What's the solution?
Its symptom look like issue:
https://github.com/bumptech/glide/issues/3807

**Comment by weishengwen2** [comment]
My temporary solution  though I don't think it's very good:
system/vold/Process.cpp::killProcessesWithOpenFiles add code:
if (checkFileDescriptorSymLinks(pid, path, openfile, sizeof(openfile))) {
            SLOGE("Process %s (%d) has open file %s", name, pid, openfile);
        } else if (checkFileMaps(pid, path, openfile, sizeof(openfile))) {
            SLOGE("Process %s (%d) has open filemap for %s", name, pid, openfile);
        } else if (checkSymLink(pid, path, "cwd")) {
            SLOGE("Process %s (%d) has cwd within %s", name, pid, path);
        } else if (checkSymLink(pid, path, "root")) {
            SLOGE("Process %s (%d) has chroot within %s", name, pid, path);
        } else if (checkSymLink(pid, path, "exe")) {
            SLOGE("Process %s (%d) has executable path within %s", name, pid, path);
        } else {
            continue;
        }

        if (signal != 0) {
            SLOGW("Sending %s to process %d signal is %d", strsignal(signal), pid, signal);
            // Add my code
            if (strcmp(name, "MypackageName") == 0) {
                SLOGW("Skip %s to process %d", name, pid);
                continue;
            }
            // end
            kill(pid, signal);
            count++;
        }

**Comment by sjudd** [comment]
I don't have any good ideas for you. 

If you're in the middle of loading the File, I'd expect there's nothing Glide can do. 

It's more interesting if you had loaded a file from the sdcard at one point but aren't actually doing so when the sdcard is removed. That might be due to Glide using memory mapped files? 

https://github.com/bumptech/glide/blob/efe8023aed474e4bf1a596faf15ca1e4c5f9e34f/library/src/main/java/com/bumptech/glide/load/model/ByteBufferFileLoader.java#L61
https://github.com/bumptech/glide/blob/efe8023aed474e4bf1a596faf15ca1e4c5f9e34f/library/src/main/java/com/bumptech/glide/util/ByteBufferUtil.java#L43

If you can reproduce after you're done loading the file, it might be interesting to try loading it from the corresponding media store `Uri` rather than from the file path. If it doesn't reproduce from the `Uri`, then maybe there's something we can do here.

**Comment by yanguo1515** [comment]
I use Glide.with(context).clear(target) to release resource when the application receive eject broadcast and fix this issue.
You can try this way.

**Comment by AssIstne** [comment]
Using `load(uri)` instead of `load(file)` saves my day.
