### ISSUE TITLE
IDE complains about proguard rules

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bumptech/glide#4139]
I tried to follow this:
https://github.com/bumptech/glide#proguard

But then the IDE complains about this line:

-keepresourcexmlelements manifest/application/meta-data@value=GlideModule

Should I remove it? Should I ignore? It says "Invalid flag ".

![image](https://user-images.githubusercontent.com/5357526/76681305-54f82780-65fa-11ea-811b-f9c8a19ea0ce.png)

Android Studio 4.0 Beta 2
Build #AI-193.6494.35.40.6254973, built on March 3, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1970M
Cores: 12
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false
Non-Bundled Plugins: String Manipulation, org.jetbrains.kotlin, ignaciotcrespo.github.com.vector-drawable-thumbnails, org.intellij.plugins.markdown

**Comment by sjudd** [comment]
It's a DexGuard flag, so if you're not using DexGuard you can remove it.

**Comment by AndroidDeveloperLB** [comment]
OK so I ignore this. Sorry.
