### ISSUE TITLE
Need way to override global options

### ISSUE THREAD

**Issue by dekuashe** [bumptech/glide#414]
**Glide Version/Integration library (if any)**:
3.5+

**Issue details/Repro steps**:
Since Glide.isSetup() and Glide.setup() are now deprecated and scheduled for removal, it's not possible (or not easy) to use different options for different areas of the app. For example, if I wanted to use a different cache location or cache settings for some longer lasting icons so they don't get bumped out of cache when images load in other parts of the app, I used to be able to do this with Glide.setup(), but it doesn't seem to be possible without it.

This could be done per request, but I would think it'd make more sense to do it with RequestManager.

**Comment by joebowbeer** [comment]
This would might also provide better support for using Glide in 3rd party library projects, in order to avoid conflicts with other uses of Glide by the main app or its other library projects.

**Comment by sjudd** [comment]
I'm not convinced that it makes sense to change the cache size or location in a library or for different parts of the app. If you load a different set of images you will quickly flush out old no longer useful images from the both the Bitmap pool and the memory cache. Increasing or decrease the size, especially in libraries, might cause undesirable behavior.

Open to convincing, but I think this is as far as we want to go for now.

**Comment by dekuashe** [comment]
All I can do is share an example use case from an app I worked on some time ago: I have a set of school logos that rarely change and are fairly small in size. In the same app but in a different screen, I'll load high resolution images that are used in a gallery. For the school logos, I'd like to keep them around on disk for a longer period of time, but if they share the same configuration as the gallery images, it'll end up loading all of these logos from the network every time I go back to that screen because they'll be flushed from disk in a very short time (some of these galleries contain hundreds of photos). It's very convenient to be able to just write a new Glide configuration for the logos instead of writing something to download the logos to disk separately (complete with a decent caching mechanism).

**Comment by joebowbeer** [comment]
I could not use glide in the library I was developing for a client because this feature was missing and was not on the roadmap. The hypothetical use cases I described were similar to my own.

**Comment by TWiStErRob** [comment]
@joebowbeer you can always provide a `GlideModule` for the client of the library, see how the integration libraries work.

**Comment by sjudd** [comment]
@dekuashe Your request is much more for a better disk cache API or additional disk cache options than it is for being able to change out the caches/pools/executors etc that Glide offers I think?

Does anyone have a good reason why you'd need to be able to change the memory cache or bitmap pool implementation? Or change the number of threads used? Or anything other than the disk cache behavior?
