### ISSUE TITLE
[QUESTION] How to replace the cache key of the local file with the remote url?

### ISSUE THREAD

**Issue by Rotemy** [bumptech/glide#4140]
Hello,

I'm facing a problem that I think a lot of people have.

The users selecting image to post, then the image is uploading to the server while the users are still seeing the local image. After finish uploading, the path of the image is replaced to the remote one, but then the users are needed to download the image from the server. Instead of doing that, I feel like there should be a way to just replace the cache key of the local file with the key of the remote file and then the users' experience will be seamless.

Any solution for this common scenario?

**Comment by sjudd** [comment]
You can make the local image the thumbnail of the remote image: http://bumptech.github.io/glide/doc/options.html#thumbnail-requests. The local image will be shown until the remote image is downloaded.

**Comment by Rotemy** [comment]
> You can make the local image the thumbnail of the remote image: http://bumptech.github.io/glide/doc/options.html#thumbnail-requests. The local image will be shown until the remote image is downloaded.

Thank you for the reply. This is one possible solution, however, is hard to maintain. I will need to keep the original image path in the db until knowing the remote image was downloaded successfully. Furthermore, it is not bulletproof and in a specific scenario can cause the user to see a blank image (the internet went off immediately after the user uploaded the image, the user closes the app, delete the image, move it or edit it and reopen the app).

In our iOS app we are using SDWebImage and there we are doing this:

```
RCT_EXPORT_METHOD(replaceImageInCache:(nonnull NSString *)originalURL : (nonnull NSString *)newURL)
{
    NSData * imageData = [[NSData alloc] initWithContentsOfURL: [NSURL URLWithString: originalURL]];
    UIImage * image = [UIImage imageWithData: imageData];

    if (image) {
        [SDImageCache.sharedImageCache storeImage:image forKey:newURL completion:^{}];
    }
}
```

It's working great and provide the user the best experience.

Is there a way to do something like that with Glide?

**Comment by sjudd** [comment]
Sorry yes, to to answer your question, there's no way of modifying the contents of the cache directly.

I think you'd probably just keep the original path forever and always try loading both. 

One other option would be to [write a custom model loader](http://bumptech.github.io/glide/tut/custom-modelloader.html) that accepts some model object you define and can fall back to the file path if the load from the url fails. That's a bit more of a change, but might make for a cleaner interface for callers.

**Comment by Rotemy** [comment]
> Sorry yes, to to answer your question, there's no way of modifying the contents of the cache directly.
> 
> I think you'd probably just keep the original path forever and always try loading both.
> 
> One other option would be to [write a custom model loader](http://bumptech.github.io/glide/tut/custom-modelloader.html) that accepts some model object you define and can fall back to the file path if the load from the url fails. That's a bit more of a change, but might make for a cleaner interface for callers.

ok thank you
