### ISSUE TITLE
W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

### ISSUE THREAD

**Issue by Dipongkar12** [bumptech/glide#4145]
in Adapter..```

public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
      Post post=mPosts.get(position);
        Glide.with(mContext).load(post.getPostimage()).into(holder.post_image);

    }

```

In Activity


```
 private  void  userInfo(){

        DatabaseReference reference=FirebaseDatabase.getInstance().getReference("Users").child(profileid);
        reference.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {

                if(getContext()==null){
                    return;
                }
                User user=dataSnapshot.getValue(User.class);
                Glide.with(getContext()).load(user.getImageurl()).into(image_profile);
                username.setText(user.getUsername());
                fullname.setText(user.getFullname());
                bio.setText(user.getBio());
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });

    }
```

**Comment by SmallRedSister** [comment]
I also encountered the same problem

**Comment by Sayed-Gad-ElMoula** [comment]
I also encountered the same problem

**Comment by d2207-sahu** [comment]
I also encountered the same problem what to do?

**Comment by SitRoc** [comment]
I also encountering this problem.

**Comment by fatCat2015** [comment]
I also encountering this problem.

**Comment by sanakitti** [comment]
I also encountering thí problem

**Comment by farmazon3000** [comment]
Same here.

**Comment by tung803** [comment]
I also encountering this problem.

**Comment by dapperdonshaggy** [comment]
same here

**Comment by OlegBezr** [comment]
same here. Any suggestions?

**Comment by dapperdonshaggy** [comment]
Depreciate the version if it does not work the cause would be a different thing you will have to send the stack trace

**Comment by OlegBezr** [comment]
Got it! Thank you very much!

> Depreciate the version if it does not work the cause would be a different thing you will have to send the stack trace
> […](#)
> Sent from my iPhone
> On 17 May 2020, at 2:07 PM, OlegBezr ***@***.***> wrote: same here. Any suggestions? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dapperdonshaggy** [comment]
you are welcome
were you able to fix it

**Comment by OlegBezr** [comment]
Yeah, it's fixed now

**Comment by faithYoshimura** [comment]
This issue seems to have been resolved in the following versions

implementation 'com.github.bumptech.glide:glide:4.10.0'

**Comment by alx696** [comment]
I have the same problem! When switch RecyclerView between LinearLayoutManager and GridLayoutManager.

Version: 4.11.0
OS: Android 9

@faithYoshimura Thanks, 4.10.0 looks more stable.

**Comment by kiloc** [comment]
android:requestLegacyExternalStorage="true" I set this it works well

**Comment by arfaoui-sami** [comment]
include this in complier 
implementation 'com.github.bumptech.glide:glide:4.7.1'

**Comment by Morons** [comment]
I still get it on 
glide_version = '4.12.0'
!!

**Comment by GaneshkumarOPTISOL** [comment]
Any Update on this would helpful to others,!!

**Comment by abmomin** [comment]
I am also getting this error on version 4.12.0

**Comment by rfoa** [comment]
I also encountering this problem. I'm using:
```
implementation 'com.github.bumptech.glide:glide:4.12.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
implementation "com.github.bumptech.glide:okhttp3-integration:4.12.0"
```

**Comment by TheRedSpy15** [comment]
> I also encountering this problem. I'm using:
> 
> ```
> implementation 'com.github.bumptech.glide:glide:4.12.0'
> annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
> implementation "com.github.bumptech.glide:okhttp3-integration:4.12.0"
> ```

Same here

**Comment by johnjeremih** [comment]
I'm having the same problem. Any solution?

**Comment by odearafat** [comment]
I am also getting this error on version 4.12.0

**Comment by MuhammadAbdullahEjaz** [comment]
Facing same problem in 4.12.0

**Comment by CleatonPais** [comment]
Facing same problem in 4.13.0

**Comment by davidmcraejr** [comment]
Make sure if you are using kotlin, use -

`kapt 'com.github.bumptech.glide:compiler:4.10.0'`

rather than-

`annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'`

**Comment by yazmnh87** [comment]
@davidmcraejr Thanks, changing to kapt fixes the error for me:)

**Comment by idee24** [comment]
I am getting the same issue on compose:
`implementation "com.github.bumptech.glide:compose:1.0.0-alpha.1"` 
please help..

**Comment by martypants0760** [comment]
getting the same error using 

    implementation("com.github.bumptech.glide:glide:5.0.0-rc01")
    ksp("com.github.bumptech.glide:compiler:5.0.0-rc01")

time for rc02?
