### ISSUE TITLE
some gif only show first frame

### ISSUE THREAD

**Issue by zhouxinghua9527** [bumptech/glide#4166]
**Glide Version**:4.11.0

**Integration libraries**:none

**Device/Android Version**:pixel android:8.1

**Issue details / Repro steps / Use case background**: some gif only show first frame. like [gif1](http://chuantu.xyz/t6/726/1585641637x1033347913.gif) and [gif2](http://chuantu.xyz/t6/726/1585641754x1031866013.gif)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by moqi-Git** [comment]
The problem occurred during the GIF decoding process, probably at the location of Netscape Looping Application Extension.How did you make these pictures？
