### ISSUE TITLE
transform  Only perform again 

### ISSUE THREAD

**Issue by liaibai** [bumptech/glide#417]
transform  Only perform again

**Comment by TWiStErRob** [comment]
Can you please fill out the [issue template](https://github.com/bumptech/glide/issues/new?body=**Glide%20Version/Integration%20library%20(if%20any)**:%0A**Device/Android%20Version**:%0A**Issue%20details/Repro%20steps**:%0A%0A**Glide%20load%20line**:%0A%60%60%60%0AGlide.with(context)...%3B%0A%60%60%60%0A%0A**Stack%20trace**:%0A%60%60%60%0Apaste%20stack%20trace%20here%0A%60%60%60)?
Also if you're having difficulties with English, try using https://translate.google.com

**Comment by liaibai** [comment]
Photos can not be displayed in full or download

**Comment by TWiStErRob** [comment]
Are you looking for one of these?

Display original resolution bitmap:
```java
Glide.with(context).load(...).asBitmap().asIs().into(imageView);
```

Download original file:
```java
Glide.with(context).load(...).downloadOnly(new SimpleTarget<File>(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL) {
    @Override public void onResourceReady(File resource, GlideAnimation<? super File> glideAnimation) {
        doSomethingWith(resource); // you're on UI thread!
    }
}});
```

It would really help if you described your problems more with full sentences.

**Comment by sjudd** [comment]
Sorry I think we're not understanding you well enough to make progress here. If you can provide screenshots or stack traces demonstrating your issue, we'll definitely take another look.
