### ISSUE TITLE
Decrypt loaded Image ByteArray Response  from REST Call before loading to imageView

### ISSUE THREAD

**Issue by Overlord21** [bumptech/glide#4170]
**Glide Version**: 4.11.0   Kotlin

**Integration libraries**: None For now ( The app uses Volley for the usual REST Calls)

**Issue details / Repro steps / Use case background**: 
Greetings, I have recently starting Using Glide for a new project I am working and I have become somewhat desperate with an issue I am facing at the moment. I am trying to load images from an existing API, the issue is that the images come as encrypted Bytearray and cannot be read if not decrypted prior to being loaded to the imageView. The flow is as follows: LoadImage(id) -> OutputByteArray -> DecryptAES() -> assign decrypted bytearray/bitmap to imageView.
I tried to look for tutorials and examples in Kotlin to do this step, but could not find any relevant sources(I am aware of ModelLoaders and DataRetrievers, but I could not understand how I could add that simple step of Decryption step through Glide

I hope for your support and sorry if this is too much asked.

**Usage:** 
``` kotlin
// RecyclerViewListItem.kt

  val glideUrl = GlideUrl("API_URL") { mapOf(Pair("Authorization", "Bearer $testToken")) }
  
  Glide.with(this.containerView).load(glideUrl).signature(ObjectKey(imageID))
                    .transition(DrawableTransitionOptions.withCrossFade()).thumbnail(0.25f)
                 .apply(RequestOptions().diskCacheStrategy(DiskCacheStrategy.AUTOMATIC).skipMemoryCache(true).override(selfReference.snapshotImage.width, selfReference.snapshotImage.height)
                            .placeholder(R.drawable.empty_result)
                    ).into(this.itemView.snapshotImage)

//before loading to imageVIiew I need the following to be done with the API Call response: val decryptedByteArray = CryptoCbc.decryptAesCBC(byteArrayFromResponse, sharedSecret)
```

**Comment by camhart** [comment]
@Overlord21 did you figure this out?  I need something similar.

**Comment by Overlord21** [comment]
@camhart  Sadly could not research it any further. Did you have any luck on your side?
