### ISSUE TITLE
Server Cut pictures problem

### ISSUE THREAD

**Issue by wangrunxiang** [bumptech/glide#4172]
If the image returned by the server is 100x100, but the ImageView is 50x50, if I want to download 100x100 images and put them on the 50x50 ImageView, it means that three quarters of the downloaded data is wasted.

So we use the server to cut the image. For example, the original URL is http://yy.com/image1.jpg. We use the server to cut the image by splicing parameters at the back, such as http://yy.com/image.jpg? mode=scale&width=50&height=50

I think there are two ways. The first way is to write a model loader, but it's very invasive

So I chose another one

```
registry.prepend(Uri::class.java,InputStream::class.java,WebpAndScaleCovertLoader.Factory())

WebpAndScaleCovertLoader extends HttpUriLoader {

public LoadData<InputStream> buildLoadData(@NonNull Uri model, int width, int height, @NonNull Options options) {

String url = AliYunCovertManager.getInstance().covertWebPAndScaleUrl(model.toString(), width, height);

return urlLoader.buildLoadData(new GlideUrl(url), width, height, options);

}

}
```

But this way brings a problem, that is, the problem of caching. In such a scenario, when you see a small picture on a page, you will download the 50x50 small picture, cache it, and then click to view the large picture. At this time, he will not download the large picture. He directly takes the 50x50 small picture, and displays it on the 100x100 ImageView, leading to blur.

How can I solve this caching problem?

Or is there a better plan?

**Comment by wangrunxiang** [comment]
@sjudd

**Comment by moqi-Git** [comment]
Try to add `signature` in RequestOptions to distinguish different request. 
I think an alternative method is to call Glide to load the image after the ImageView determines its size.

**Comment by wangrunxiang** [comment]
但是我是用`HttpUriLoader`的子类去实现修改url，在这里，我没法设置`signature`

**Comment by wangrunxiang** [comment]
@moqi-Git But I use the subclass of `HttpUriLoader` to modify the URL. Here, I can't set the `signature`
