### ISSUE TITLE
Native crash,signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40 Cause: null pointer dereference

### ISSUE THREAD

**Issue by MarsToken** [bumptech/glide#4188]
**Device/Android Version**:android9  api28

**Issue details / Repro steps / Use case background**: 
ABI: 'arm64'
pid: 7645, tid: 7668, name: RenderThread  >>>my package name <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40
Cause: null pointer dereference
    x0  0000ed2997faaa08  x1  0000ed29b3b46800  x2  0000000000000000  x3  0000ed29b50a7220
    x4  0000ed2999beda10  x5  0000ed29b3a50b00  x6  0000000000000001  x7  0000ed2999bed9c4
    x8  0000000000000000  x9  0000ed29b53ee448  x10 0000000000000001  x11 0000000000000000
    x12 0000000000000004  x13 0000000000000000  x14 0000000000000001  x15 0000000000000001
    x16 0000ed29b574ed68  x17 0000ed29b540d2b0  x18 000000000007000d  x19 0000ed29b3b46800
    x20 0000ed2997faaa08  x21 0000000000000010  x22 0000000000000010  x23 0000ed29b5409a80
    x24 0000ed29b5409de8  x25 0000ed2998c52118  x26 0000ed29b5746390  x27 0000000000003815
    x28 0000000000000000  x29 0000ed2999bef440
    sp  0000ed2999bef410  lr  0000ed29b540dbd0  pc  0000ed29b540d2fc

backtrace:
    #00 pc 000000000045b2fc  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+76)
    #01 pc 000000000045bbcc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
    #02 pc 000000000043c1bc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
    #03 pc 000000000043c584  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
    #04 pc 000000000045b344  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
    #05 pc 000000000045bbcc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
    #06 pc 000000000043c1bc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
    #07 pc 000000000043c584  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
    #08 pc 000000000045b344  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
    #09 pc 000000000045bbcc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
    #10 pc 000000000043c1bc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
    #11 pc 000000000043c584  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
    #12 pc 000000000045b344  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
    #13 pc 000000000045bbcc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
    #14 pc 000000000043c1bc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
    #15 pc 000000000043c584  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
    #16 pc 000000000045b344  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
    #17 pc 000000000045bbcc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
    #18 pc 000000000043c1bc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
    #19 pc 000000000043c584  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
    #20 pc 000000000045b344  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
    #21 pc 000000000045bbcc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
    #22 pc 000000000043c1bc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
    #23 pc 000000000043c584  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
    #24 pc 000000000045b344  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
    #25 pc 000000000045bbcc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
    #26 pc 000000000043c1bc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
    #27 pc 000000000043c584  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
    #28 pc 000000000045b344  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)

**Comment by deputat007** [comment]
glide version: **4.11.0**
**Acer Liquid S1 (a10), 1024MB RAM, Android 9**
Report 1 of 3
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> my package name  <<<

backtrace:
 
  #00  pc 000000000001cece  /system/lib/libc.so (abort+58)
 
  #01  pc 000000000039575d  /system/lib/libhwui.so (SkTDArray<SkPoint>::append()+60)
 
  #02  pc 000000000033671d  /system/lib/libhwui.so (SkBaseShadowTessellator::addArc(SkPoint const&, bool)+288)
 
  #03  pc 0000000000337761  /system/lib/libhwui.so (SkAmbientShadowTessellator::handleLine(SkPoint const&)+740)
 
  #04  pc 0000000000336de9  /system/lib/libhwui.so (SkAmbientShadowTessellator::SkAmbientShadowTessellator(SkPath const&, SkMatrix const&, SkPoint3 const&, bool)+572)
 
  #05  pc 000000000033983f  /system/lib/libhwui.so (SkShadowTessellator::MakeAmbient(SkPath const&, SkMatrix const&, SkPoint3 const&, bool)+22)
 
  #06  pc 000000000033a2cf  /system/lib/libhwui.so (SkBaseDevice::drawShadow(SkPath const&, SkDrawShadowRec const&)+638)
 
  #07  pc 00000000003bc0f3  /system/lib/libhwui.so (SkGpuDevice::drawShadow(SkPath const&, SkDrawShadowRec const&)+106)
 
  #08  pc 00000000003856b9  /system/lib/libhwui.so (SkCanvas::onDrawShadowRec(SkPath const&, SkDrawShadowRec const&)+160)
 
  #09  pc 0000000000339edf  /system/lib/libhwui.so (SkShadowUtils::DrawShadow(SkCanvas*, SkPath const&, SkPoint3 const&, SkPoint3 const&, float, unsigned int, unsigned int, unsigned int)+366)
 
  #10  pc 0000000000091881  /system/lib/libhwui.so (android::uirenderer::skiapipeline::EndReorderBarrierDrawable::drawShadow(SkCanvas*, android::uirenderer::skiapipeline::RenderNodeDrawable*)+1024)
 
  #11  pc 000000000037376b  /system/lib/libhwui.so (android::uirenderer::skiapipeline::EndReorderBarrierDrawable::onDraw(SkCanvas*)+158)
 
  #12  pc 0000000000359e65  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+212)
 
  #13  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #14  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #15  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #16  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #17  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #18  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #19  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #20  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #21  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #22  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #23  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #24  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #25  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #26  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #27  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #28  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #29  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #30  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #31  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #32  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #33  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #34  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #35  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #36  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #37  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #38  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #39  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #40  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #41  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #42  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #43  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #44  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #45  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #46  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #47  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #48  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #49  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #50  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #51  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #52  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #53  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #54  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #55  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #56  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #57  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #58  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #59  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #60  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #61  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #62  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #63  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #64  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #65  pc 000000000035a417  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+154)
 
  #66  pc 00000000003421ed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+272)
 
  #67  pc 0000000000342503  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+202)
 
  #68  pc 0000000000359df5  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+100)
 
  #69  pc 0000000000098797  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrameImpl(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, bool, bool, android::uirenderer::Rect const&, SkCanvas*)+374)
 
  #70  pc 00000000003747bd  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, bool, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>)+68)
 
  #71  pc 0000000000373eb7  /system/lib/libhwui.so
 
  #72  pc 00000000003771b1  /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+576)
 
  #73  pc 000000000034154b  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+122)
 
  #74  pc 00000000000aa40f  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+178)
 
  #75  pc 000000000000c08b  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+166)
 
  #76  pc 0000000000064909  /system/lib/libc.so (__pthread_start(void*)+140)
 
  #77  pc 000000000001e395  /system/lib/libc.so (__start_thread+24)




------------------------------------------------

**Comment by arpitsingh21** [comment]
same happened to me, is this related to some animations?

**Comment by CaptainJeff** [comment]
Anyone have any insight on this? Same issue?

**Comment by QiaoYang0923** [comment]
大概率是使用了 glide-transformations 导致的,

**Comment by super963883929** [comment]
我也遇到这个问题

2024-11-08 09:59:41.645 11737-11807 libc                    com.package.name            A  Fatal signal 11 (SIGSEGV), code 0 (SI_USER) in tid 11807 (RenderThread), pid 11737 (d.package.name)
2024-11-08 09:59:42.429 12761-12761 DEBUG                   crash_dump64                         A  Cmdline: com.package.name
2024-11-08 09:59:42.429 12761-12761 DEBUG                   crash_dump64                         A  pid: 11737, tid: 11807, name: RenderThread  >>> com.package.name <<<
