### ISSUE TITLE
whats happen if 250 mb of glide full?

### ISSUE THREAD

**Issue by mortezamoradi72** [bumptech/glide#4189]
Hello
whats happen if 250 mb of glide full? and how to handle it?
is it right way in Application class :

`@Override
	public void onLowMemory() {
	    super.onLowMemory();
            Glide.get(context).clearDiskCache();
	}`

**Comment by oakkitten** [comment]
`onLowMemory` is called when your system is low on RAM, not disk space. Glide is supposed to be handling low memory [automatically](https://bumptech.github.io/glide/doc/caching.html#memory-cache)
