### ISSUE TITLE
Two instances with different OkHttpClients

### ISSUE THREAD

**Issue by AdrianLxM** [bumptech/glide#4194]
So far we us Glide with a configured okHttpClient that adds an authorization token to the call and that works fine with the following Module, supported by Dagger.

```
@Excludes(OkHttpLibraryGlideModule::class)
@GlideModule
class OkHttpGlideModule : AppGlideModule() {

    @Inject
    @Named("WithAuthToken")
    lateinit var okHttpClient: OkHttpClient

    override fun isManifestParsingEnabled() = false

    override fun registerComponents(context: Context, glide: Glide, registry: Registry) {

        (context.applicationContext as MyApp).androidInjector().inject(this)

        super.registerComponents(context, glide, registry)
        registry.replace(GlideUrl::class.java, InputStream::class.java, OkHttpUrlLoader.Factory(okHttpClient))
    }
}
```

Now we want to load some images that should use **another okHttpClient** (**without the auth token** interceptor) while in other cases load images as before.

How can this be achieved?
Is there a Glide-Builder that can do the same as the code above so that we can inject our glide instance and not use the static dependency to `Glide.with...`?
Or any other solution?

Help very much appreciated! Thanks!

**Comment by sjudd** [comment]
Can you distinguish between the urls you want to load with/without auth from the url itself? If so you could write a custom ModelLoader for GlideUrls that delegates to one OkHttpLoader with auth and another without auth.
