### ISSUE TITLE
Whether DiskLruCache will  write conflict in multi-process

### ISSUE THREAD

**Issue by ljcmeng** [bumptech/glide#4195]
**Glide Version**:4.9.0

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
It's not safe across processes
