### ISSUE TITLE
How to cache local file under remote url key?

### ISSUE THREAD

**Issue by mohammadzzz** [bumptech/glide#4200]
Hi guys, I have this weird use case of uploading images in a chat app.

When I want to upload an image (from local storage to the server), I insert a message into the local database with state = sending.

So while state == sending; I display the local image via glide.load(File(...)), (if state == sent glide.load( remote url..)) all works

However now after the upload is completed, the API returns the uploaded message JSON object, which contains a URL to that image;

The given message with state == sending is now updated with the message returned from API, giving it state sent;

This, however, means when recycler view is refreshed, the remote URL image is downloaded -- for an image I already have locally (and just uploaded); I know I can hack around and display local manually, but that is going to be problematic. And I was wondering if I could somehow feed glide that local image under the remote URL as key, so the downloading when load(URL) is avoided?

**Comment by CMyae** [comment]
I'm developing chat feature and facing the same situation. After image uploaded, I want to update local image cache key with remote url. @mohammadzzz did you find any solutions to it?
