### ISSUE TITLE
Picture is not complete 

### ISSUE THREAD

**Issue by liaibai** [bumptech/glide#421]
Picture is not complete

**Comment by liaibai** [comment]
Download the picture sometimes is not complete

**Comment by TWiStErRob** [comment]
我做了一个快速谷歌搜索。我猜你是中国人。您可以使用 http://translate.google.com 从您的母语为英语翻译。坏的机器翻译是超过一半的句子更好。请尽量描述您的问题的细节。使用模板的问题给你的问题的基本信息。模板新的报告是在这里：[Issue template](https://github.com/bumptech/glide/issues/new?body=**Glide%20Version/Integration%20library%20(if%20any)**:%0A**Device/Android%20Version**:%0A**Issue%20details/Repro%20steps**:%0A%0A**Glide%20load%20line**:%0A%60%60%60%0AGlide.with(context)...%3B%0A%60%60%60%0A%0A**Stack%20trace**:%0A%60%60%60%0Apaste%20stack%20trace%20here%0A%60%60%60)

**Comment by liaibai** [comment]
Sometimes the picture is not complete download

**Comment by TWiStErRob** [comment]
Which version do you use? (你使用哪个版本？)
How do you load the image? (你如何加载的形象呢？)
Is there an Exception in LogCat? (是否有LogCat Exception？)

**Comment by liaibai** [comment]
ivHd.getLayoutParams().width = Device.getWidth();
			ivHd.getLayoutParams().height = Device.getWidth()*15/32;
			Glide.with(WeiBoListNewActivity.this).load(hd.ImageUrl).placeholder(R.color.guidColor).error(R.color.guidColor)
			.override(Device.getWidth(), Device.getWidth()*15/32)
			.crossFade().diskCacheStrategy(DiskCacheStrategy.SOURCE).centerCrop()
			.transform(new BitmapTransformation(WeiBoListNewActivity.this) {
				@Override
				public String getId() {
					return Device.getMD5String(hd.ImageUrl);
				}
				
				@Override
				protected Bitmap transform(BitmapPool arg0, Bitmap source, int arg2, int arg3) {
					x = source.getWidth();
					y = source.getHeight();
					return source;
				}
			})
			.listener(new RequestListener<Object, GlideDrawable>() {
				@Override
				public boolean onException(Exception arg0, Object arg1,
						Target<GlideDrawable> arg2, boolean arg3) {
					return false;
				}

				@Override
				public boolean onResourceReady(GlideDrawable arg0, Object arg1,
						Target<GlideDrawable> arg2, boolean arg3, boolean arg4) {
					if(x >0 && y>0) {
						setXY(x, y);
						LinearLayout.LayoutParams a = new LinearLayout.LayoutParams(Device.getWidth(), Device.getWidth()*y/x);
						ivHd.setLayoutParams(a);
						Glide.with(WeiBoListNewActivity.this).load(hd.ImageUrl).placeholder(R.color.guidColor).error(R.color.guidColor)
						.override(Device.getWidth(), Device.getWidth()*y/x)
						.crossFade().diskCacheStrategy(DiskCacheStrategy.SOURCE).centerCrop()
						.into(ivHd);
					} else {
						int x1 = 32, y1 = 15;
						if(getX()>0 && getY()>0) {
							x1 = getX();
							y1 = getY();
						}
						ivHd.getLayoutParams().width = Device.getWidth();
						ivHd.getLayoutParams().height = Device.getWidth()*y1/x1;
						Glide.with(WeiBoListNewActivity.this).load(hd.ImageUrl).placeholder(R.color.guidColor).error(R.color.guidColor)
						.override(Device.getWidth(), Device.getWidth()*y1/x1)
						.crossFade().diskCacheStrategy(DiskCacheStrategy.SOURCE).centerCrop()
						.into(ivHd);
					}
					return true;
				}
			})
		    .into(ivHd);


At first I did not know the size of the picture, get the size of the download is complete, and then reloaded into imageview in

**Comment by sjudd** [comment]
If you're referring to a partial image, it may have been fixed here: https://github.com/bumptech/glide/commit/64be9d314814f541fe1bb20553c7501d6e8c987b#diff-a5c571a05a090ccc55c81f4af74be5cf.

Try the latest [Snapshot][1] and see if you can still reproduce.

[1]: https://github.com/bumptech/glide/wiki/Snapshots

**Comment by liaibai** [comment]
thank you

**Comment by liaibai** [comment]
This problem is likely to occur twice in a row to perform downloads
