### ISSUE TITLE
Drawable image not load unless using override method

### ISSUE THREAD

**Issue by ptdede** [bumptech/glide#4212]
**Glide Version**: 4.11.0

**Device/Android Version**: emulator / API 28

**Issue details / Repro steps / Use case background**: 
I Try to load drawable image to inflated layout. But, the image won't shows up unless I override the width and height. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin

val layout = LayoutInflater.from(context)
.inflate(
   R.layout.some_layout,
   aWrapper,
   false
)

Glide.with(context!!)
    .load(backgroundDrawable) // R.drawable.someDrawable
    .override(900) // must use this or image can't loaded
    .into(layout.cardImage)
```

**Layout XML**:
```xml
<ImageView
    android:id="@+id/cardImage"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerCrop"/>
```

**Comment by andor201995** [comment]
```
Glide.with(appContext)
     .asBitmap()
     .load(iconDrawable)
     .into(object : CustomTarget<Bitmap>() {
          override fun onLoadCleared(placeholder: Drawable?) {
          }

          override fun onResourceReady(resource: Bitmap, transition: Transition<in Drawable>?) {
                    remoteViews.setImageViewBitmap(R.id.primaryIcon, resource))
          }
     })
```

I am trying to load a drawable in RemoteView. As remoteView only accept Bitmap's.I tried above code and bitmap is empty.I even tried using NotificationTarget but that also didn't help.

Here's a [SOF](https://stackoverflow.com/q/62321914/7972699) question i posted for reference  if it's not an issue of glide and i am doing something wrong do help.

Basically i want use the glide's power to handle Bitmap Creation and not handling bitmap creation on my own.
