### ISSUE TITLE
Add javadoc on what should be recycled in Transformations and when

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#422]

**Comment by TWiStErRob** [comment]
You commented earlier:
> Given how confusing the behavior is I absolutely need to update it.

It's only confusing because most libraries are not designed for ease of use and don't try to take care of repetitive things. Glide does.

**Comment by Tolriq** [comment]
A small related question since seeing that :)

To prefill the cache with my double cache solution I use :

```
Glide.with().load().into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).get().recycle();
```

I suppose this is the correct way but maybe there's something native (and not downloadonly as I do not use / need source cache I handle it on my side). Because not sure doing this with recycle allow correct bitmap reuse and is resources optimal.

**Comment by sjudd** [comment]
Ah @Tolriq that's unsafel. Use ``Glide#clear(Target)`` instead, which will allow the Bitmap to be returned to the Bitmap pool rather than just recycled and discarded. Alternatively you can also just use the [``preload(width, height)``][1] which is intended for exactly the purpose you describe.

As a general rule, avoid calling ``recycle()`` on Bitmaps manually and instead call ``Glide#clear(Target)`` instead.

[1]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/GenericRequestBuilder.html#preload(int,%20int)

**Comment by Tolriq** [comment]
Thanks I've migrated to clear :)

For preload as usual my need is a little special :( I do not need to fill any Glide cache only my private cache that is generated from inside the dataFetcher.

I guess preload will fill at least result cache and it's unwanted + it seems I can't do that synchronously.
And I need to keep control over that as user can stop the queue (and only this queue) and can potentially queue thousands of images.
