### ISSUE TITLE
java.lang.NullPointerException: Argument must not be null

### ISSUE THREAD

**Issue by ling9400** [bumptech/glide#4228]
I'm using Glide in kotlin，and the bug is 'java.lang.NullPointerException: Argument must not be null'.
my configration is:  ext.kotlin_version = '1.3.72'    
classpath 'com.android.tools.build:gradle:3.6.3'
**in app/build.gradle**  
apply plugin: 'kotlin-kapt' 
apply plugin: 'kotlin-android-extensions'
implementation 'androidx.appcompat:appcompat:1.1.0'
implementation 'com.github.bumptech.glide:glide:4.11.0'
kapt 'com.github.bumptech.glide:compiler:4.11.0'

then the code is :
Glide.with(this)
            .load("https://pics0.baidu.com/feed/d833c895d143ad4b94f3d018d69ceaa9a60f06a9.jpeg?token=bae6b9b5a318374d86cf1fe07dcafaae")
            .fitCenter()
            .into(ivLogo) // ivLogo is the ImageView's id in xml

**Comment by elkasvirElka** [comment]
@ling9400 Did you resolve it? I am having the same issue
