### ISSUE TITLE
Glide Transformation memory leak

### ISSUE THREAD

**Issue by yashasvigirdhar** [bumptech/glide#4230]
I am facing this memory leak while using Glide. Here's the trace by LeakCanary.

     D/LeakCanary: ├─ android.provider.FontsContract
     D/LeakCanary: │    Leaking: NO (HomeApplication↓ is not leaking and a class is never leaking)
     D/LeakCanary: │    GC Root: System class
     D/LeakCanary: │    ↓ static FontsContract.sContext
     D/LeakCanary: ├─  <package>.HomeApplication
     D/LeakCanary: │    Leaking: NO (Application is a singleton)
     D/LeakCanary: │    HomeApplication does not wrap an activity context
     D/LeakCanary: │    ↓ HomeApplication.mComponentCallbacks
     D/LeakCanary: │                      ~~~~~~~~~~~~~~~~~~~
     D/LeakCanary: ├─ java.util.ArrayList
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ ArrayList.elementData
     D/LeakCanary: │                ~~~~~~~~~~~
     D/LeakCanary: ├─ java.lang.Object[]
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ array Object[].[1]
     D/LeakCanary: │                     ~~~
     D/LeakCanary: ├─ com.bumptech.glide.Glide
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ Glide.memoryCache
     D/LeakCanary: │            ~~~~~~~~~~~
     D/LeakCanary: ├─ com.bumptech.glide.load.engine.cache.LruResourceCache
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ LruResourceCache.cache
     D/LeakCanary: │                       ~~~~~
     D/LeakCanary: ├─ java.util.LinkedHashMap
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ LinkedHashMap.tail
     D/LeakCanary: │                    ~~~~
     D/LeakCanary: ├─ java.util.LinkedHashMap$LinkedHashMapEntry
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ LinkedHashMap$LinkedHashMapEntry.key
     D/LeakCanary: │                                       ~~~
     D/LeakCanary: ├─ com.bumptech.glide.load.engine.EngineKey
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ EngineKey.transformations
     D/LeakCanary: │                ~~~~~~~~~~~~~~~
     D/LeakCanary: ├─ com.bumptech.glide.util.CachedHashCodeArrayMap
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ CachedHashCodeArrayMap.mArray
     D/LeakCanary: │                             ~~~~~~
     D/LeakCanary: ├─ java.lang.Object[]
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ array Object[].[1]
     D/LeakCanary: │                     ~~~
     D/LeakCanary: ├─ <package>.<some class>$3
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    Anonymous class implementing com.bumptech.glide.load.Transformation
     D/LeakCanary: │    ↓ <some class>$3.this$0
     D/LeakCanary: │                ~~~~~~
     D/LeakCanary: ├─ <package>.<some class>
     D/LeakCanary: │    Leaking: UNKNOWN
     D/LeakCanary: │    ↓ <some class>.activity
     D/LeakCanary: │              ~~~~~~~~
     D/LeakCanary: ╰→ <package>.<some activity>
     D/LeakCanary: ​     Leaking: YES (Activity#mDestroyed is true and ObjectWatcher was watching this)
     D/LeakCanary: ​     key = 632286af-8d9e-4b05-bc8f-5974ca16931b
     D/LeakCanary: ​     watchDurationMillis = 2957886
     D/LeakCanary: ​     retainedDurationMillis = 2952885

So this is saying that the transformation is cached by glide and that transformation references activity.
I was under the impression the Glide is lifecycle aware but yeah I understand that it might apply only to load requests.
So I was thinking about possible solutions that I have:

 1. don't reference activity in transformation code
 2. clear the glide's state so that it clears the transformation in cache. 
 3. ask glide to not cache the transformation.

What's the way to go from here?

Also, is there something completely wrong that I am missing right now. Here's the transformation   code:

```
new Transformation<Drawable>() {
      @NonNull
      @Override
      public Resource<Drawable> transform(
          @NonNull Context context,
          @NonNull Resource<Drawable> resource,
          int outWidth,
          int outHeight) {
        Drawable albumArt = resource.get();
        int backgroundColor;
        if (albumArt instanceof BitmapDrawable) {
          backgroundColor =
              <some util class>.getBackgroundColorForBitmap(
                  ((BitmapDrawable) albumArt).getBitmap());

        } else {
          backgroundColor = defaultBackgroundScrimColor;
        }
        Drawable[] layers = {
          albumArt, <some util class>.getGradientOverlay(backgroundColor)
        };
        return new SimpleResource<>(new LayerDrawable(layers));
      }

      @Override
      public void updateDiskCacheKey(@NonNull MessageDigest messageDigest) {}
    };
  }

```

Also, I am still trying to find out how I am referencing activity in the transformation code.

**Comment by sjudd** [comment]
Is the Transformation created as an anonymous inner class in the Activity? If so, all anonymous inner classes implicitly reference the enclosing class. 

Transformations should always be static and avoid taking constructor arguments that reference Activities/Fragments/Views to avoid memory leaks.

As an aside, you need to implement equals/hashcode/updateDiskCacheKey in your transformation, otherwise neither in memory nor on disk caching will work correctly.

**Comment by yashasvigirdhar** [comment]
Thanks for the help @sjudd. The issue was resolved. It was an anonymous inner class.
