### ISSUE TITLE
在安卓  4.4系统上的机器里。 用Glide 加载的gif图片是静止的·

### ISSUE THREAD

**Issue by sd3970566** [bumptech/glide#4232]
在安卓  4.4系统上的机器里。 用Glide 加载的gif图片是静止的·
On Android 4.4. The GIF image loaded with glide is  error

**Comment by sd3970566** [comment]
不能解决吗

**Comment by alvince** [comment]
> 不能解决吗

Glide is a `loader` rather than a `widget`, we should handle it by custom display gif
