### ISSUE TITLE
Using existing Thread pool service in application

### ISSUE THREAD

**Issue by mahdi24rajabi** [bumptech/glide#4239]
Hello

I have recently started working with Glide and it's really amazing. Thanks. But I have an issue with configurations. 

I have my own threadPool and ExecutorService and wish not having any extra thread in my application. I see that you have GlideExecutor, but it generates its own ThreadPool and there is noway to inject custom ExecutorService. At least based on my investigation. 

Would you please help me how I can resolve my issue?

Sincerely, 
Mahdi Rajabi

I'm using Glide 4.11

**Comment by sjudd** [comment]
Yeah there isn't really a way to do this. One part of the reason is that Glide prioritizes Runnables using a custom interface that wouldn't be supported by other executors. Some of it is to just try to prevent people from shooting themselves in the foot.

We'd revisit this for a major API change, but for now, it's not possible without forking or using test only code.

**Comment by mwshubham** [comment]
We have a similar use case i.e. we wanted to share a same executor for downloading image and api content. Would be helpful if we can allow passing a ExecutorService instead of GlideExecutor. Or may be some interface or allowing glide executor extendable.

**Comment by mwshubham** [comment]
Subject: [PATCH] Custom Glide Executor
---
Index: library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java b/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java
--- a/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java	(revision a7351b0ecf6656ad937fbc52fe9e90d3b289c265)
+++ b/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java	(date 1724921972754)
@@ -23,7 +23,7 @@
 import java.util.concurrent.atomic.AtomicInteger;
 
 /** A prioritized {@link ThreadPoolExecutor} for running jobs in Glide. */
-public final class GlideExecutor implements ExecutorService {
+public class GlideExecutor implements ExecutorService {
   /**
    * The default thread name prefix for executors used to load/decode/transform data not found in
    * cache.
@@ -225,8 +225,7 @@
         .build();
   }
 
-  @VisibleForTesting
-  GlideExecutor(ExecutorService delegate) {
+  public GlideExecutor(ExecutorService delegate) {
     this.delegate = delegate;
   }
 
Index: samples/gallery/src/main/java/com/bumptech/glide/samples/gallery/GalleryModule.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/samples/gallery/src/main/java/com/bumptech/glide/samples/gallery/GalleryModule.kt b/samples/gallery/src/main/java/com/bumptech/glide/samples/gallery/GalleryModule.kt
--- a/samples/gallery/src/main/java/com/bumptech/glide/samples/gallery/GalleryModule.kt	(revision a7351b0ecf6656ad937fbc52fe9e90d3b289c265)
+++ b/samples/gallery/src/main/java/com/bumptech/glide/samples/gallery/GalleryModule.kt	(date 1724922635504)
@@ -1,15 +1,38 @@
 package com.bumptech.glide.samples.gallery
 
 import android.content.Context
+import android.util.Log
 import com.bumptech.glide.GlideBuilder
 import com.bumptech.glide.annotation.GlideModule
+import com.bumptech.glide.load.engine.executor.GlideExecutor
 import com.bumptech.glide.module.AppGlideModule
+import java.util.concurrent.ExecutorService
+import java.util.concurrent.Executors
+import java.util.concurrent.ThreadFactory
+import java.util.concurrent.atomic.AtomicInteger
 
 /** Ensures that Glide's generated API is created for the Gallery sample.  */
 @GlideModule
 class GalleryModule : AppGlideModule() {
-  override fun applyOptions(context: Context, builder: GlideBuilder) {
-    super.applyOptions(context, builder)
-    builder.setIsActiveResourceRetentionAllowed(true)
-  }
+    override fun applyOptions(context: Context, builder: GlideBuilder) {
+        super.applyOptions(context, builder)
+        builder.setLogLevel(Log.VERBOSE)
+        builder.setSourceExecutor(
+            CustomGlideExecutor(
+                Executors.newFixedThreadPool(4, object : ThreadFactory {
+                    private val THREAD_NAME_STEM = "custom_glide_exec_"
+                    private val mThreadId = AtomicInteger(0)
+                    override fun newThread(r: Runnable): Thread {
+                        return Thread(r).apply {
+                            name = THREAD_NAME_STEM + mThreadId.getAndIncrement()
+                            Log.d("GalleryModule", "Thread :: name:$name")
+                        }
+                    }
+                })
+            )
+        )
+        builder.setIsActiveResourceRetentionAllowed(true)
+    }
 }
+
+class CustomGlideExecutor(delegate: ExecutorService) : GlideExecutor(delegate)
\ No newline at end of file





@sjudd What are your thoughts on making GlideExecutor non final.
