### ISSUE TITLE
OkHttpClient: A connection to https://xxxx.com/ was leaked.

### ISSUE THREAD

**Issue by Z-13** [bumptech/glide#4253]
**Glide: 4.11.0**
I've a RecyclerView + [FastAdapter](https://github.com/mikepenz/FastAdapter) and an item like this:
```
override fun bindView(item: MyItem, payloads: List<Any>) {
     val context = itemView.context

     GlideApp.with(context)
                    .load(data.photo?.toMediaUrl())
                    .fallback(R.drawable.holder_b)
                    .error(R.drawable.holder_b)
                    .transition(DrawableTransitionOptions.withCrossFade())
                    .into(image)
}

override fun unbindView(item: MyItem) {
    GlideApp.with(itemView.context).clear(image)
    image.setImageDrawable(null)
}
```

After first loading, everything is OK. But then I've updated my data(the same data) and scrolling then I've get this logcat:

> W/okhttp.OkHttpClient: A connection to https://xxxx.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
> 
> I/chatty: uid=10143(com.my.app) OkHttp TaskRunn identical 4 lines
> 
> W/okhttp.OkHttpClient: A connection to https://xxxx.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

I've tried to downgrade the version to 4.10.0 but it doesn't matter.

How can I fix it?
Thx!

**Comment by TemMax** [comment]
Do you use okhttp integration library?

**Comment by Z-13** [comment]
> Do you use okhttp integration library?
@TemMax 
```
implementation "com.squareup.okhttp3:okhttp:4.7.2"
implementation "com.github.bumptech.glide:okhttp3-integration:4.11.0"
```

**Comment by TemMax** [comment]
After some researching I found something interesting.
[FastAdapter](https://github.com/mikepenz/FastAdapter) use [View.setTag()](https://github.com/mikepenz/FastAdapter/blob/0cbc8a3e44ce000c513a848bcf90719c5edf7495/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt#L353), but Glide's docs of [RequestManager#clear](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/RequestManager.java#L612) says that request clearing works only if you doesn't use View#setTag outside of Glide.
Your trouble causing by FastAdapter.

**Comment by mikepenz** [comment]
@TemMax `FastAdapter` uses a custom id for the tag. Whereas `glide` uses the global tag (without an ID) there shouldn't be an conflict in such a scenario.

**Comment by TemMax** [comment]
Hmmm. Glide uses a custom id for the tag too. Maybe need more researching of this problem or using other libraries like [Coil](https://github.com/coil-kt/coil) or [Fresco](https://frescolib.org/docs/index.html)

**Comment by mikepenz** [comment]
@Z-13 do you by coincidence use something like `Chucker` ? or some other interceptor?

**Comment by Z-13** [comment]
@mikepenz 
> do you by coincidence use something like `Chucker` ? or some other interceptor?

I'm using only this:
```
@Provides
fun provideLoggingInterceptor(): HttpLoggingInterceptor {
	return HttpLoggingInterceptor().setLevel(if (BuildConfig.DEBUG) HttpLoggingInterceptor.Level.BODY else HttpLoggingInterceptor.Level.BASIC)
}

@Provides
@Singleton
fun provideAuthInterceptor(appPrefs: AppPrefs): AuthInterceptor {
	return AuthInterceptor(appPrefs)
}

@Provides
fun provideHttpClient(loggingInterceptor: HttpLoggingInterceptor,
					  context: Context,
					  authInterceptor: AuthInterceptor): OkHttpClient {

	val headerInterceptor = Interceptor { chain ->
		if (!isNetworkAvailable(context)) {
			throw IOException(context.getString(R.string.no_internet))
		}

		val builder = chain.request().newBuilder()
		builder.addHeader("Content-Type", "application/json; charset=utf-8")
		builder.addHeader("Application-Version", BuildConfig.VERSION_NAME)

		chain.proceed(builder.build())
	}

	val builder = OkHttpClient.Builder()
		.addInterceptor(headerInterceptor)
		.addInterceptor(authInterceptor)
		.addInterceptor(loggingInterceptor)
		.connectTimeout(TIMEOUT_SEC, TimeUnit.SECONDS)
		.writeTimeout(TIMEOUT_SEC, TimeUnit.SECONDS)
		.readTimeout(TIMEOUT_SEC, TimeUnit.SECONDS)

	builder.addInterceptor(StethoInterceptor()) //if this is a debug version

	return builder.build()
}   

______________________________
class AuthInterceptor @Inject constructor() : Interceptor {
    override fun intercept(chain: Interceptor.Chain): Response {
        val request = chain.request()
        val requestBuilder = request.newBuilder()
        val apiToken = ...

        if (apiToken.isNotEmpty()) {
            requestBuilder.addHeader(AUTHORIZATION, TOKEN.plus(apiToken))
        }

        return chain.proceed(requestBuilder.build())
    }
}
```

**Comment by mikepenz** [comment]
One of your interceptors could leak something
