### ISSUE TITLE
Failed to load resource There were 18 causes

### ISSUE THREAD

**Issue by happyharley** [bumptech/glide#4255]
2020-06-12 18:19:54.467 21997-21997/ylt.wangjiahui I/Fjdklsjafefa: Failed to load resource
    There were 18 causes:
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSourceCallback failed: status = 0x80000000)
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSourceCallback failed: status = 0x80000000)
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSourceCallback failed: status = 0x80000000)
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSourceCallback failed: status = 0x80000000)
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail
2020-06-12 18:19:54.467 21997-21997/ylt.wangjiahui I/Fjdklsjafefa: com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, DATA_DISK_CACHE, https://cmsres.dianzhenkeji.com/anonymous/2020/6/12/1271254814499672064.jpg
    There were 4 causes:
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSourceCallback failed: status = 0x80000000)
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSourceCallback failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail
2020-06-12 18:19:54.467 21997-21997/ylt.wangjiahui I/Fjdklsjafefa: com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, DATA_DISK_CACHE, https://cmsres.dianzhenkeji.com/anonymous/2020/6/12/1271254814499672064.jpg
    There were 2 causes:
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
     call GlideException#logRootCauses(String) for more detail
2020-06-12 18:19:54.467 21997-21997/ylt.wangjiahui I/Fjdklsjafefa: com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, DATA_DISK_CACHE, https://cmsres.dianzhenkeji.com/anonymous/2020/6/12/1271254814499672064.jpg
    There were 3 causes:
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail
2020-06-12 18:19:54.467 21997-21997/ylt.wangjiahui I/Fjdklsjafefa: com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, https://cmsres.dianzhenkeji.com/anonymous/2020/6/12/1271254814499672064.jpg
    There were 4 causes:
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSourceCallback failed: status = 0x80000000)
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSourceCallback failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail
2020-06-12 18:19:54.467 21997-21997/ylt.wangjiahui I/Fjdklsjafefa: com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, https://cmsres.dianzhenkeji.com/anonymous/2020/6/12/1271254814499672064.jpg
    There were 2 causes:
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
     call GlideException#logRootCauses(String) for more detail
2020-06-12 18:19:54.467 21997-21997/ylt.wangjiahui I/Fjdklsjafefa: com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, https://cmsres.dianzhenkeji.com/anonymous/2020/6/12/1271254814499672064.jpg
    There were 3 causes:
    java.lang.IndexOutOfBoundsException(index=-2023161846 out of bounds (limit=56, nb=2))
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail

**Comment by happyharley** [comment]
fresco可以加载https://cmsres.dianzhenkeji.com/anonymous/2020/6/12/1271254814499672064.jpg，glide不可以加载啊啊啊

**Comment by happyharley** [comment]
the picture's question  is the orginal cause,when i reconfig the pic's width and height by meituxiuxiu,and keep the orgin width and height unchange ,it 's get all ok ,what happend, but i ever used bitmapfactory to decode the bad pic,it is ok,fresco is ok too,i think it's glide's compatibility is not strong enough,please enhance,Amen!

**Comment by shoushuai** [comment]
> the picture's question is the orginal cause,when i reconfig the pic's width and height by meituxiuxiu,and keep the orgin width and height unchange ,it 's get all ok ,what happend, but i ever used bitmapfactory to decode the bad pic,it is ok,fresco is ok too,i think glide's compatibility is not strong enough

最后怎么解决的，代码怎么完善
