### ISSUE TITLE
Transformation performance question

### ISSUE THREAD

**Issue by assassinshadow0** [bumptech/glide#4256]
So I need to blur some images in a recyclerview. The current approach i am using is glide.with(..).apply(blur).into(...)
works as it should and looks great actually. However, it does have some performance drawbacks on some devices.
I have also tried using override(5) and this gives a blur (because the images get resized to a really small size?). While the quality is pretty bad compared to the blur transformation, it is somewhat faster on most of my devices. 

Does anyone know "for sure" that using override is faster than using apply transformation? 
or is there any other way to have a faster / more efficient blur (without slowing down the feed)?
thank you.

**Comment by TemMax** [comment]
If you want really fast blur on android you need blur Bitmap in native code.
If you doesn't have a native code for blur — downscale your Bitmap in few times. For example — 1/4 of real size. After blurring of downscaled bitmap upscale it in 4 times.
Hope it help you.

**Comment by assassinshadow0** [comment]
Neat approach :) will give it a shot. Thank you
