### ISSUE TITLE
HEIC Images not rotated based on Exif info

### ISSUE THREAD

**Issue by LikeTheSalad** [bumptech/glide#4265]
**Glide Version**: 
4.11.0

**Integration libraries**:
None

**Device/Android Version**: 
Android emulator API 28

**Issue details / Repro steps / Use case background**: 
Loading local HEIC image which has a rotation param of 90 degrees.
Expected: The image is automatically rotated before displaying it.
Actual: Rotation is not done.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(Context)
    .asBitmap()
    .load(File(imagePath))
    .format(DecodeFormat.PREFER_RGB_565)
    .fitCenter()
    .into(ImageView)
```

**Possible solution**
I think I know the reason for this issue to happen, it's the version Glide uses of the Android's Jetpack Exif Interface lib: https://developer.android.com/jetpack/androidx/releases/exifinterface, which is currently `1.0.0`, which has an issue to retrieve the proper HEIC images rotation info. If you guys update it to use the latest `1.2.0` version, it should be sorted :)

Regards,
Cesar.

**Comment by sjudd** [comment]
Thanks for the detailed report and suggested fix!

I think as a workaround you might be able to require v1.2.0 of that library in your application. That should force gradle to use the newer version.
