### ISSUE TITLE
Share Image from cache to WhatsApp

### ISSUE THREAD

**Issue by triple-dot** [bumptech/glide#4266]
> For those who fails to share cached image with apps (such as Google Keep, WeChat Moments) that rely on file type (which `FileProvider` cannot guess because the cache file has no file extension), here is a working subclass of `FileProvider` (with Glide 4) that deals with this perfectly (Thanks to [#459 (comment)](https://github.com/bumptech/glide/issues/459#issuecomment-100238254)):
> 
> ```java
> package com.yourapplication;
> 
> import android.net.Uri;
> import android.os.ParcelFileDescriptor;
> import android.support.v4.content.FileProvider;
> import android.text.TextUtils;
> import android.webkit.MimeTypeMap;
> 
> import com.bumptech.glide.load.ImageHeaderParser;
> import com.bumptech.glide.load.resource.bitmap.DefaultImageHeaderParser;
> 
> import java.io.FileInputStream;
> 
> public class ImageTypeFileProvider extends FileProvider {
> 
>     private ImageHeaderParser mImageHeaderParser = new DefaultImageHeaderParser();
> 
>     @Override
>     public String getType(Uri uri) {
> 
>         String type = super.getType(uri);
>         if (!TextUtils.equals(type, "application/octet-stream")) {
>             return type;
>         }
> 
>         try {
>             ParcelFileDescriptor parcelFileDescriptor = openFile(uri, "r");
>             if (parcelFileDescriptor == null) {
>                 return type;
>             }
>             try {
>                 FileInputStream fileInputStream = new FileInputStream(
>                         parcelFileDescriptor.getFileDescriptor());
>                 try {
>                     ImageHeaderParser.ImageType imageType = mImageHeaderParser.getType(
>                             fileInputStream);
>                     type = getTypeFromImageType(imageType, type);
>                 } finally {
>                     fileInputStream.close();
>                 }
>             } finally {
>                 parcelFileDescriptor.close();
>             }
>         } catch (Exception e) {
>             e.printStackTrace();
>         }
>         return type;
>     }
> 
>     private static String getTypeFromImageType(ImageHeaderParser.ImageType imageType,
>                                                String defaultType) {
>         String extension;
>         switch (imageType) {
>             case GIF:
>                 extension = "gif";
>                 break;
>             case JPEG:
>                 extension = "jpg";
>                 break;
>             case PNG_A:
>             case PNG:
>                 extension = "png";
>                 break;
>             case WEBP_A:
>             case WEBP:
>                 extension = "webp";
>                 break;
>             default:
>                 return defaultType;
>         }
>         // See FileProvider.getType(Uri)
>         return MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);
>     }
> }
> ```

Used it for custom file provider. 
@TWiStErRob this does not work with current version of WhatsApp (For telegram and other apps it works fine), anything else which I need to do?

_Originally posted by @triple-dot in https://github.com/bumptech/glide/issues/459#issuecomment-636288686_

**Comment by TWiStErRob** [comment]
If it works for everything else, maybe contract Facebook, and help them to know they are not adhering to the Share contract of Android. I'm not sure there's anything else to do. It's possible they're ignoring the `getType`.

Also ask on the other issue if anyone actually solved WhatsApp yet, maybe there's a workaround. I personally never did this.
