### ISSUE TITLE
How to set custom cache key names?

### ISSUE THREAD

**Issue by Erlend2** [bumptech/glide#4269]
Hello, is there a way to set custom names of files downloaded to the cache? By default, the file names are heavily hashed.

I have looked at threads with similar names:

[How to get File image from cache dir](https://github.com/bumptech/glide/issues/411)
[Share image in cache](https://github.com/bumptech/glide/issues/459)
[How to specify specific cache key ?](https://github.com/bumptech/glide/issues/501)
[Question: Ability to provide custom cache key for individual glide requests.](https://github.com/bumptech/glide/issues/3823)

As well as:

[Caching](https://bumptech.github.io/glide/doc/caching.html#cache-keys)

The answer may very well be in one of these, but I have not yet understood how to achieve it.

Here's some information from the docs of the cache key:

> Cache Keys
> In Glide 4, all cache keys contain at least two elements:
> 
> The model the load is requested for (File, Uri, Url). If you are using a custom model, it needs to correctly implements hashCode() and equals()
> An optional Signature
> 
> ...
> 
> To generate the name of disk cache keys on disk, the individual elements of the keys are hashed to create a single String key, which is then used as the file name in the disk cache.

However, it doesn't explicitly explain how to set custom files names to replace the hashed keys.

The thread ["How to specify specific cache key ?"](https://github.com/bumptech/glide/issues/501) shows a possible solution by creating a custom class that extends "GlideUrl", but how to integrate it? Does it require the use of AppGlideModule? I've had some difficulties with using AppGlideModule though, so I'd prefer a way which doesn't need it.

Moreover, is it possible to set the file name in the onResourceReady callback, or otherwise rename the cached files after they have been downloaded?

I need to set orderly file names (just integers like 0, 1, 2) in order to identify them correctly later when I export the files to external storage. I use .diskCacheStrategy(DiskCacheStrategy.RESOURCE), so there's only one copy of each downloaded image in the cache.

**Glide Version**: 4.11.0

**Device/Android Version**: Xiaomi Mi A1 / Android 8.1.0

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

```java
Glide.with(c).
    load(url).
    diskCacheStrategy(DiskCacheStrategy.RESOURCE).
    placeholder(R.drawable.white_square).
    listener(new RequestListener<Drawable>() {
        @Override public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
            return false;
        }
        @Override public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
            return false;
        }
     }).
     fallback(R.drawable.white_square).
     into(holder.imageView);
```

**Note:** I tried to implement a custom class of GlideUrl, but the cache filename doesn't change no matter what string I return in getCacheKey(). How to prevent it from hashing the filename?

```java
Glide.with(c).
    load(new CustomGlideUrl(cur_url)).
    ...
```

```java
class CustomGlideUrl extends GlideUrl {

    public CustomGlideUrl(URL url) {
        super(url);
    }

    public CustomGlideUrl(String url) {
        super(url);
    }

    public CustomGlideUrl(URL url, Headers headers) {
        super(url, headers);
    }

    public CustomGlideUrl(String url, Headers headers) {
        super(url, headers);
    }

    @Override
    public String getCacheKey() {
        String url = toStringUrl();
        // No matter what string I return here, the cached filename is hashed.
        return url;
    }

    @Override
    public void updateDiskCacheKey(@NonNull MessageDigest messageDigest) {
        super.updateDiskCacheKey(messageDigest);
        Log.d("MainActivity","updateDiskCacheKey ~ messageDigest?: "+messageDigest);
        // This returns: SHA-256 Message Digest from AndroidOpenSSL, <in progress>
    }

}
```

**Comment by sjudd** [comment]
In short, no. There's no way to specify the name of the file in the cache.

You can try to use asFile() to get a File object pointing to the item in cache, but it can be tricky to get that to work correctly. In general Glide isn't meant to be used as a download manager. Glide's cache is primarily oriented at saving thumbnails to display them.
