### ISSUE TITLE
How to find the Bitmap.Config being used bit a GifDrawable

### ISSUE THREAD

**Issue by perracolabs** [bumptech/glide#4270]
Glide Version: 4.11.0

I have a use case where I need to know if a GIF is being rendered with transparent pixels.

As I couldn't find any API for it in Glide, I thought to perform the GIF request with Bitmap.Config.RGB_565, and then to check if is being rendered as Bitmap.Config.ARGB_8888, since glide changes to such format if found that the GIF has transparent pixels.

I've tried to use the Bitmap returned by GifDrawable.getFirstFrame(), but this one returns null after it has started to render.

I'm aware that I could also perform a separate glide request to extract a bitmap only, but then I would need to perform 2 request for each entry in the list of GIFs.

Is there any way to find the Bitmap.Config from a GifDrawable? Or any possible way to find if it has transparent pixels?

Thanks

**Comment by sjudd** [comment]
Glide doesn't expose a way for you to do this unfortunately. Even the gif decoding library doesn't seem to, we just infer it from the colors...

**Comment by Godsbox** [comment]
Some mobiles , Use asBitmap , change their GIF to bitmap with a black background
