### ISSUE TITLE
Multiple OkHttp3 clients and different interceptors

### ISSUE THREAD

**Issue by dafi** [bumptech/glide#4280]
My app (actually using Coil) loads images requiring different type of authentication, suppose `image-a` requires `auth-a` and `image-b` requires `auth-b`.
In Coil, using OKHttp3 client/interceptor, everything works fine,  I pass the different `ImageLoader` where I know which loader I need to use.
In glide I can define http client only inside the `AppGlideModule` but the called client can be the wrong type.
Th client/interceptor can't determine what to do, only the caller know how to handle the image url
How can I set the client directly when I call Glide.load?

**Glide Version**: 4.11.0

**Integration libraries**: okhttp3-integration:4.11.0

**Comment by vlketzer** [comment]
any comments? it's very interesting. thanks in advance
