### ISSUE TITLE
.override method error

### ISSUE THREAD

**Issue by KavinAgrawal** [bumptech/glide#4285]
Glide .override method is trying to maintain aspect ratio.
My code:
`Glide.with(context).load(file).override(200, 200).into(viewHolder.iconViewFile); `
Glide is not resizing image to 200*200. It is just resizing the image in same aspect ratio till one of height or width reaches 200.

**Comment by dendrocyte** [comment]
@ KavinAgrawal
Did you find the solution here? I met the same issue

**Comment by dendrocyte** [comment]
@ KavinAgrawal
Did you find the solution here? I met the same issue

**Comment by dendrocyte** [comment]
@ KavinAgrawal
Did you find the solution here? I met the same issue

**Comment by dendrocyte** [comment]
@ KavinAgrawal
Did you find the solution here? I met the same issue

**Comment by dendrocyte** [comment]
@ KavinAgrawal
Did you find the solution here? I met the same issue

**Comment by dendrocyte** [comment]
@ KavinAgrawal
Did you find the solution here? I met the same issue

**Comment by dendrocyte** [comment]
@ KavinAgrawal
Did you find the solution here? I met the same issue

**Comment by dendrocyte** [comment]
Did you find the solution here? I met the same issue

**Comment by lifeover23** [comment]
Do not come to the barn with my husband again.
Don't talk, don't say, don't send anything to die.ส่งจากสมาร์ทโฟน Samsung Galaxy ของฉัน
-------- ข้อความดั้งเดิม --------จาก: dendrocyte <notifications@github.com> วัน​ที่: 15/9/20  14:29  (GMT+07:00) ถึง: bumptech/glide <glide@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> เรื่อง: Re: [bumptech/glide] .override method error (#4285) 
@ KavinAgrawal
Did you find the solution here? I met the same issue
