### ISSUE TITLE
thumbnail() loading image twice?

### ISSUE THREAD

**Issue by 155martinmoreno** [bumptech/glide#429]
It's my first day on Glide so probably I'm getting this wrong, but when trying this

    ImageView imageView = (ImageView) findViewById(R.id.image_view);
    Glide.with(this).load("http://ctein.com/Seals_Rolling_pano.jpg").thumbnail(0.1f).into(imageView);

My charles is getting 2 identical calls to the image (same size, etc)

![screen shot 2015-04-20 at 17 45 00](https://cloud.githubusercontent.com/assets/8753819/7240091/027c33f0-e785-11e4-9589-5c4962ff972e.png)

Is it ok that the lib downloads the image twice? one for the thumbnail and one for the full-size image?

Thanks

**Comment by sjudd** [comment]
We were just talking about this in #427, let me know if that doesn't answer your question.
