### ISSUE TITLE
OPPO & VIVO RemoteException 

### ISSUE THREAD

**Issue by LuffyBySunny** [bumptech/glide#4292]
**Glide Version**: 4.5.0

**Integration libraries**:

**Device/Android Version**: 9.0

**Issue details / Repro steps / Use case background**: 

java.lang.SecurityException: Given caller package com.bbk.launcher2 is not running in process ProcessRecord{85ec115 15146:com.***/u0a158}
--
4607-17 08:12:17.146 15146 15146 E AndroidRuntime: at android.os.Parcel.createException(Parcel.java:1950)
4707-17 08:12:17.146 15146 15146 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:1918)
4807-17 08:12:17.146 15146 15146 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:1868)
4907-17 08:12:17.146 15146 15146 E AndroidRuntime: at android.app.IActivityManager$Stub$Proxy.registerReceiver(IActivityManager.java:3699)
5007-17 08:12:17.146 15146 15146 E AndroidRuntime: at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1509)
5107-17 08:12:17.146 15146 15146 E AndroidRuntime: at android.app.ContextImpl.registerReceiver(ContextImpl.java:1470)
5207-17 08:12:17.146 15146 15146 E AndroidRuntime: at android.app.ContextImpl.registerReceiver(ContextImpl.java:1458)
5307-17 08:12:17.146 15146 15146 E AndroidRuntime: at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
5407-17 08:12:17.146 15146 15146 E AndroidRuntime: at com.bumptech.glide.manager.DefaultConnectivityMonitor.register(DefaultConnectivityMonitor.java:3)
5507-17 08:12:17.146 15146 15146 E AndroidRuntime: at com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart(DefaultConnectivityMonitor.java:1)
5607-17 08:12:17.146 15146 15146 E AndroidRuntime: at com.bumptech.glide.manager.ActivityFragmentLifecycle.b(ActivityFragmentLifecycle.java:3)
5707-17 08:12:17.146 15146 15146 E AndroidRuntime: at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:2)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Sayeram** [comment]
Sent from my Huawei Mobile☺-------- Original Message --------Subject: Re: [bumptech/glide] OPPO & VIVO RemoteException  (#4292)From: "stale[bot]" To: bumptech/glide CC: Subscribed 
Closed #4292.

Kjxun r—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
