### ISSUE TITLE
Veracode raises flaw in DecodeJob.java: 78

### ISSUE THREAD

**Issue by cah-rajkumar-ramanathan** [bumptech/glide#4294]
Attack Vector: android.util.Log.v

Number of Modules Affected: 1

Description: This call to android.util.Log.v() could result in a log forging attack. Writing untrusted data into a log file allows an attacker to forge log entries or inject malicious content into log files. Corrupted log files can be used to cover an attacker's tracks or as a delivery mechanism for an attack on a log viewing or processing utility. For example, if a web administrator uses a browser-based utility to review logs, a cross-site scripting attack might be possible. The second argument to v() contains tainted data. The tainted data originated from earlier calls to java.net.HttpURLConnection.getInputStream, android.content.ContentResolver.openInputStream, and android.content.ContentResolver.openAssetFileDescriptor.

Remediation (suggestion from veracode): Avoid directly embedding user input in log files when possible. Sanitize untrusted data used to construct log entries by using a safe logging mechanism such as the OWASP ESAPI Logger, which will automatically remove unexpected carriage returns and line feeds and can be configured to use HTML entity encoding for non-alphanumeric data. Alternatively, some of the XSS escaping functions from the OWASP Java Encoder project will also sanitize CRLF sequences. Only write custom blacklisting code when absolutely necessary. Always validate untrusted input to ensure that it conforms to the expected format, using centralized data validation routines when possible.

'com.github.bumptech.glide:glide:4.10.0'
**Glide Version**:

    'com.squareup.okhttp3:logging-interceptor:3.12.1'
    'com.squareup.okhttp3:okhttp:3.12.1'
 "com.squareup.okhttp3:okhttp-urlconnection:3.6.0"
'com.squareup.retrofit2:retrofit-mock:2.3.0'
**Integration libraries**:

It's veracode scan.

Please help us understanding the issue.. and let me know if anymore details needed.

**Comment by cah-rajkumar-ramanathan** [comment]
Any update on this issue.?

**Comment by sjudd** [comment]
Can you provide a pointer to the code you're referencing? Or send a pull request with a suggested fix?
