### ISSUE TITLE
Is there a way to restrict placeholder if the image is already cached?

### ISSUE THREAD

**Issue by rajdheepak** [bumptech/glide#4308]
**Glide Version**: 4.11.0

**Integration libraries**: okhttp

**Device/Android Version**: Android 10 Samsung galaxy s10

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context)
                            .asBitmap()
                            .placeholder(R.drawable.ic_image_black_24dp)
                            .error(R.drawable.ic_broken_image_black_24dp)
                            .load(customModel)
                            .into(customTarget)
```

If the image is already available in one of the cache's i don't want a placeholder. I want to display a placeholder only when the image is served from network request. Any way to achieve this with the existing glide API's?

**Comment by sjudd** [comment]
In short, no. If the image is in the memory cache, the placeholder will not be displayed. In all other cases where there's an asynchronous load, we will display the placeholder. There isn't any way in the current API to change this behavior to only apply the placeholder when the image is not cached.

**Comment by rajdheepak** [comment]
Like it would be helpful if there is an API in glide to know if the image is already cached or not. Does Glide have one? @sjudd
