### ISSUE TITLE
java.lang.ClassCastException：int[] cannot be cast to java.lang.Object[]

### ISSUE THREAD

**Issue by kaitian521** [bumptech/glide#4309]
```

java.util.Arrays$ArrayList.toArray(Arrays.java:120)
--
2 java.util.ArrayList.addAll(ArrayList.java:188)
3 com.bumptech.glide.Registry.setResourceDecoderBucketPriorityList(SourceFile:264)
4 com.bumptech.glide.Registry.<init>(SourceFile:67)
5 com.bumptech.glide.Glide.<init>(SourceFile:376)
6 com.bumptech.glide.GlideBuilder.build(SourceFile:564)
7 com.bumptech.glide.Glide.initializeGlide(SourceFile:290)
8 com.bumptech.glide.Glide.initializeGlide(SourceFile:242)
9 com.bumptech.glide.Glide.checkAndInitializeGlide(SourceFile:201)
10 com.bumptech.glide.Glide.get(SourceFile:182)
11 com.melon.lazymelon.MainApplication.aA(SourceFile:552)
12 com.melon.lazymelon.MainApplication.lambda$e0VphU7McPs3lEUfavMpb44S7jY(SourceFile)
13 com.melon.lazymelon.-$$Lambda$MainApplication$e0VphU7McPs3lEUfavMpb44S7jY.run(lambda)
14 java.lang.Thread.run(Thread.java:848)

```

  @NonNull
  public final Registry setResourceDecoderBucketPriorityList(@NonNull List<String> buckets) {
    // See #3296 and https://bugs.openjdk.java.net/browse/JDK-6260652.
    List<String> modifiedBuckets = new ArrayList<>(buckets.size());
    modifiedBuckets.addAll(buckets);
    modifiedBuckets.add(0, BUCKET_PREPEND_ALL);
    modifiedBuckets.add(BUCKET_APPEND_ALL);
    decoderRegistry.setBucketPriorityList(modifiedBuckets);
    return this;
  }

met a crash, maybe can be fixed as https://github.com/bumptech/glide/commit/cdf1fdff457a52dd7947f467d7504b3d331e4181

**Comment by fangyeren** [comment]
This problem has been solved. When will the new version be released
