### ISSUE TITLE
StringSignature is missing a toString implementation

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#431]
**Glide Version/Integration library (if any)**: 3.5.2 / 3.6.0-SNAPSHOT
**Device/Android Version**: S4/4.4
**Issue details/Repro steps**: 
I enabled debug logging to figure out why the image is not using the cache:
```sh
adb shell setprop log.tag.Engine VERBOSE
```
and the cache key is not fully comprehensible because [`EngineKey.toString` uses `signature.toString()`](https://github.com/bumptech/glide/blob/v3.5.2/library/src/main/java/com/bumptech/glide/load/engine/EngineKey.java#L121).
I would also put `toString` on the `Key` interface so others may be reminded too and re-check all Key impls in Glide.

**Glide load line**:
```java
Glide.....signature(new StringSignature("x"))...;
```

**Log**:
(I inserted the new lines for readability)
```
04-21 15:21:26.321  15468-15468/net.twisterrob.app V/Engine﹕ 
Loaded resource from active resources in 0.915527ms, key:
android.resource://net.twisterrob.app/raw/svg_image
com.bumptech.glide.signature.StringSignature@710ed38e
144
144
ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap
FitCenter.com.bumptech.glide.load.resource.bitmap
BitmapEncoder.com.bumptech.glide.load.resource.bitmap
GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode
```

**Comment by TWiStErRob** [comment]
On a related note, for v4, wouldn't it be enough to have "FitCenter.glide" for example so the log line is shorter and also the MessageDigest wouldn't have to work that hard.

**Comment by sjudd** [comment]
Thanks for pointing this out. The fully qualified class name seems safest since people can define their own transformations, though I agree it's probably overkill in most cases.

**Comment by TWiStErRob** [comment]
a `.glide` or `.builtin` suffix should be enough, probably the builtin would "tell" people more to not use the same suffix.

**Comment by TWiStErRob** [comment]
Another related thing: `EngineKey.toString()` is purely for debugging purposes AFAIK, I think it should contain a separator so it would be more readable:
```
com.bumptech.glide.signature.StringSignature@710ed38e144144ImageVideoBitmapDecoder
```
VS
```
com.bumptech.glide.signature.StringSignature@710ed38e+144+144+ImageVideoBitmapDecoder
```
