### ISSUE TITLE
Low-end device play gif showly

### ISSUE THREAD

**Issue by ll201lw** [bumptech/glide#4325]
using glide 4.9.0.
And the code is:
GlideApp.with(context).load(path)
                .error(R.drawable.pic_error)
                .override(width, height)
                .centerInside()
                .into(imageView);

The load gif works correctly,but it was playing so slowly on Android 5.1.
I find some solutions to solve this question but derived some other questions.It was so bad.Please give some advice.

**Comment by zak-ml** [comment]
> using glide 4.9.0.
> And the code is:
> GlideApp.with(context).load(path)
> .error(R.drawable.pic_error)
> .override(width, height)
> .centerInside()
> .into(imageView);
> 
> The load gif works correctly,but it was playing so slowly on Android 5.1.
> I find some solutions to solve this question but derived some other questions.It was so bad.Please give some advice.

It also bothers to me, how you solve this?
