### ISSUE TITLE
Force image to be stored in disk with specific resolution

### ISSUE THREAD

**Issue by jzeferino** [bumptech/glide#4327]
Glide version 4.11.

**How can I force an image to be stored in the disk cache with a specified resolution?**

I was able to use a `DownsampleStrategy` to force an image to be loaded with a specific resolution but I also wan't to force images that are downloaded from the REMOTE to be stored with a specific resolution. 

There is any built on way to do this?

@sjudd @TWiStErRob

**Comment by extmkv** [comment]
@jzeferino did you realize how to force the image size on disk?

**Comment by jzeferino** [comment]
No, still waiting on some insight from @sjudd or @TWiStErRob.

**Comment by TWiStErRob** [comment]
Remote is the original data source, by definition it's not transformed (with DownsampleStrategy; notice that downsampling takes place when Glide interprets the data, which doesn't happen during REMOTE caching). It is possible to cache different versions of it, but you'll either have to download it multiple times to transform and cache each variant, or store the original stream and transform variants from there. That's all I can say. Note: this is based on my limited knowledge of v4, I've only been knowing v3 in depth.

**Comment by jzeferino** [comment]
ty for the reply @TWiStErRob. What is the best option if I want to store the original downloaded image in a specific resolution and then use always that image as source?

example: remote image is 2000x2000.
I want to download and resize to 500x500 and add it to chance, and then for futures loads i want to use the 500x500 image always as source.

**Comment by TWiStErRob** [comment]
Not possible with Glide, read my comment again.

You can save a transformed version of original yourself into a folder and load from there if you want. Look into how Glide can be used on background threads.

**Comment by jzeferino** [comment]
Thank you @TWiStErRob.
