### ISSUE TITLE
is it better to use `CustomTarget<Bitmap>()` than `CustomViewTarget<Drawable>` to reduce memory usage?

### ISSUE THREAD

**Issue by lannyf77** [bumptech/glide#4333]
Using Glide v4 in android app. The use case is that there is an activity which has a few Fragments in the backstack.
Each Fragment will load one to less than ten images from remote.

Having a kotlin extension for loading image into ImageView:

```
fun ImageView.loadImg(
    imageUrl: String,
    diskCacheStrategy: DiskCacheStrategy = DiskCacheStrategy.AUTOMATIC,
    skipMemoryCache: Boolean = true,
    roundingRadius: Int = 0,
    target: Target<Drawable>? = null,
    requestOptions: RequestOptions = RequestOptions(),
    decodeFormat: DecodeFormat = DecodeFormat.PREFER_RGB_565 
) {
    requestOptions
        .diskCacheStrategy(diskCacheStrategy)
        .format(decodeFormat)
        .apply {
            if (roundingRadius > 0) {
                transform(CenterCrop(), RoundedCorners(roundingRadius))
            }
        }

        Glide.with(this.context)
            .load(imageUrl)
            .apply(requestOptions)
            .skipMemoryCache(skipMemoryCache)
            .apply {
                if (target == null) {
                    into(this@loadImg)
                } else {
                    into(target)
                }
            }
}
```

a typical call in the fragment is like:
```
imageView.loadImg(
            imageUrl = imageUrl,
            roundingRadius = imageRoundingRadius,
            target = object : CustomViewTarget<ImageView, Drawable>(imageView) {
                override fun onLoadFailed(errorDrawable: Drawable?) {
                   imageView.setImageDrawable(null)
                    visibility = View.GONE
                }
                override fun onResourceCleared(placeholder: Drawable?) {
                    imageView.setImageDrawable(null)
                    visibility = View.GONE
                }
                override fun onResourceReady(resource: Drawable, transition: Transition<in Drawable>?) {
                    imageView.setImageDrawable(resource)
                    visibility = View.VISIBLE
                }
            }
        )
``` 
The problem is whenever one fragment is put in view and add to backstack, the Graphics memory in the profiler shows 50 mg increase. There is not much other data besides the images in the fragment. If comment out the loading image seems reduce a lot.

Not sure if the code loadImage() here is correct? Noticed it is using the ImageView's context in `Glide.with(this.context)`, which is the Activity. Is it a problem? 
What is the difference between `Glide.with(this.context)` and `Glide.with(theFragment)`?
When is the best time to clear the Target: `Glide.with(theFragment).clear(theTarget)`?

Noticed there is a `CustomTarget<Bitmap>()`, would using it be helpful for reducing the memory usage if it could take the image size?

code would be like this with `target: Target<Bitmap>`
```
fun ImageView.loadImgAsBitmap(
    imageUrl: String,
    diskCacheStrategy: DiskCacheStrategy = DiskCacheStrategy.AUTOMATIC,
    skipMemoryCache: Boolean = true,
    roundingRadius: Int = 0,
    target: Target<Bitmap>? = null,
    requestOptions: RequestOptions = RequestOptions(),
    decodeFormat: DecodeFormat = DecodeFormat.PREFER_RGB_565 
) {
    requestOptions
            .diskCacheStrategy(diskCacheStrategy)
            .format(decodeFormat)
            .apply {
                if (roundingRadius > 0) {
                    transform(CenterCrop(), RoundedCorners(roundingRadius))
                }
            }

        Glide.with(this.context)
                .asBitmap()
                .load(imageUrl)
                .apply(requestOptions)
                .skipMemoryCache(skipMemoryCache)
                .apply {
                    if (target == null) {
                        into(this@loadImgAsBitmap)
                    } else {
                        into(target)
                    }
                }
}
```
and usage is:
```
imageView.loadImgAsBitmap(imageUrl,
            target = object : CustomTarget<Bitmap>() {
                override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                    if (resource.height < IMAGE_MIN_SIZE) {// it could check the bitmap size and make use of it
                        imageView.visibility = View.GONE
                        textView.visibility = View.VISIBLE
                    } else {
                        imageView.setImageBitmap(resource)
                    }
                }
                override fun onLoadCleared(placeholder: Drawable?) {
                    imageView.setImageDrawable(null)
                }
            })
```
This one at least is better that provides the Bitmap size so UI could make use of it.

The question is that is it better to use `CustomTarget<Bitmap>()` than `Target<Drawable>` to reduce memory usage?
How to specify an image size to replace the default `Target.SIZE_ORIGINA`, which says is `very memory inefficient`?

**Comment by kanelbulle** [comment]
For support - please see [Getting help](https://github.com/bumptech/glide#getting-help) - there's a link to the discussion forum there which is a more appropriate list for these types of questions.

I also think it's worth reading [Getting started](https://bumptech.github.io/glide/doc/getting-started.html) and [Targets](https://bumptech.github.io/glide/doc/targets.html) - it's well written documentation that answers many of your questions including some detail on how Glide manages the lifecycle and memory for you.

As for why you see the memory increase when they are on the backstack - I don't know if it's explicitly documented, but I believe Glide does not release resources until the Fragment/Activity is destroyed, so you would see the memory increase until that happens. If that's not what you want you can `clear()` them yourself earlier (i.e. in `onStop()`).
