### ISSUE TITLE
Downsampler.AT_MOST is broken.

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#434]
Instead of ``max(sourceWidth / targetWidth, sourceHeight / targetHeight)``, it should be ``max(ceil(sourceWidth / (float) targetWidth), ceil(sourceHeight / (float) targetHeight))``.

The description is also inaccurate. The largest edge of the image will be between 1x and 1/2x the requested size, the smaller edge may be considerably smaller than 1/2x the requested size.

**Comment by TWiStErRob** [comment]
You can save a ceil by: `ceil(max(*, *))`
