### ISSUE TITLE
Not able to import Drawable (Glide.4.11.0)

### ISSUE THREAD

**Issue by nihp** [bumptech/glide#4345]
I have upgraded the Glide from 3.7.0. 

I have used GlideDrawable.  But it is deprecated or it is no more available. So I changed to Drawable according to [this](https://github.com/bumptech/glide/issues/2104#issuecomment-312695526). But still it was not working. 

Not able to import Drawable (Glide.4.11.0)

```
import com.bumptech.glide.load.resource.drawable.Drawable;
/Users/nihp/work/projects/app/src/main/java/com/helloworld/view/Helloworld.java:24: error: cannot find symbol

import com.bumptech.glide.load.resource.drawable.Drawable;

                                                ^
```

  symbol:   class Drawable

**Comment by jorgefduran** [comment]
Hello, same issue here... any solution?
