### ISSUE TITLE
CPU consumption with GIFs

### ISSUE THREAD

**Issue by simoneventurini** [bumptech/glide#4349]
**Glide Version**:4.11.0

**Device/Android Version**:Android 9

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(getContext())
                        .load(data.getGifUrl())
                        .diskCacheStrategy(DiskCacheStrategy.ALL)
                        .into(shortcutImage);
```

During the gif visualization into my View I've noticed an increase of cpu consumption of 15%. I've googled and I understood that gifs are not ideal for best performance. Anyway i would like to know if exists a best way to use glide due to avoid cpu consumption.

Thanks!

**Comment by sunxu3074** [comment]
Do you find a best way? @simoneventurini
