### ISSUE TITLE
class com.bumptech.glide.load.engine.GlideException: Failed to load resource

### ISSUE THREAD

**Issue by justqiyu** [bumptech/glide#4355]
There were 5 causes:
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(File unsuitable for memory mapping)
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(File unsuitable for memory mapping)
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
09-23 11:26:31.882 W/Glide   (13420): java.io.FileNotFoundException(No content provider: https://pmxuser.blob.core.chinacloudapi.cn/goodsdetail/20200612132734YTI.jpg)
09-23 11:26:31.882 W/Glide   (13420):  call GlideException#logRootCauses(String) for more detail
09-23 11:26:31.882 W/Glide   (13420):   Cause (1 of 7): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.nio.ByteBuffer, DATA_DISK_CACHE, https://pmxuser.blob.core.chinacloudapi.cn/goodsdetail/20200612132734YTI.jpg
 There was 1 cause:
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(File unsuitable for memory mapping)
09-23 11:26:31.882 W/Glide   (13420):  call GlideException#logRootCauses(String) for more detail
09-23 11:26:31.882 W/Glide   (13420):     Cause (1 of 1): class java.io.IOException: File unsuitable for memory mapping
09-23 11:26:31.882 W/Glide   (13420):   Cause (2 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Bitmap->Bitmap}, DATA_DISK_CACHE, https://pmxuser.blob.core.chinacloudapi.cn/goodsdetail/20200612132734YTI.jpg
09-23 11:26:31.882 W/Glide   (13420):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Bitmap}
09-23 11:26:31.882 W/Glide   (13420):   Cause (3 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Bitmap->Bitmap}, DATA_DISK_CACHE, https://pmxuser.blob.core.chinacloudapi.cn/goodsdetail/20200612132734YTI.jpg
09-23 11:26:31.882 W/Glide   (13420): There was 1 cause:
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
09-23 11:26:31.882 W/Glide   (13420):  call GlideException#logRootCauses(String) for more detail
09-23 11:26:31.882 W/Glide   (13420):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Bitmap}
09-23 11:26:31.882 W/Glide   (13420): There was 1 cause:
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
09-23 11:26:31.882 W/Glide   (13420):  call GlideException#logRootCauses(String) for more detail
09-23 11:26:31.882 W/Glide   (13420):       Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
09-23 11:26:31.882 W/Glide   (13420):   Cause (4 of 7): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.nio.ByteBuffer, REMOTE, https://pmxuser.blob.core.chinacloudapi.cn/goodsdetail/20200612132734YTI.jpg
09-23 11:26:31.882 W/Glide   (13420): There was 1 cause:
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(File unsuitable for memory mapping)
09-23 11:26:31.882 W/Glide   (13420):  call GlideException#logRootCauses(String) for more detail
09-23 11:26:31.882 W/Glide   (13420):     Cause (1 of 1): class java.io.IOException: File unsuitable for memory mapping
09-23 11:26:31.882 W/Glide   (13420):   Cause (5 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Bitmap->Bitmap}, REMOTE, https://pmxuser.blob.core.chinacloudapi.cn/goodsdetail/20200612132734YTI.jpg
09-23 11:26:31.882 W/Glide   (13420):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Bitmap}
09-23 11:26:31.882 W/Glide   (13420):   Cause (6 of 7): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Bitmap->Bitmap}, REMOTE, https://pmxuser.blob.core.chinacloudapi.cn/goodsdetail/20200612132734YTI.jpg
09-23 11:26:31.882 W/Glide   (13420): There was 1 cause:
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
09-23 11:26:31.882 W/Glide   (13420):  call GlideException#logRootCauses(String) for more detail
09-23 11:26:31.882 W/Glide   (13420):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Bitmap}
09-23 11:26:31.882 W/Glide   (13420): There was 1 cause:
09-23 11:26:31.882 W/Glide   (13420): java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
09-23 11:26:31.882 W/Glide   (13420):  call GlideException#logRootCauses(String) for more detail
09-23 11:26:31.882 W/Glide   (13420):       Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
09-23 11:26:31.882 W/Glide   (13420):   Cause (7 of 7): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL, DataCacheKey{sourceKey=https://pmxuser.blob.core.chinacloudapi.cn/goodsdetail/20200612132734YTI.jpg, sign
09-23 11:26:31.883 I/Glide   (13420): Root cause (1 of 5)
09-23 11:26:31.883 I/Glide   (13420): java.io.IOException: File unsuitable for memory mapping
09-23 11:26:31.883 I/Glide   (13420): 	at com.bumptech.glide.util.ByteBufferUtil.fromFile(ByteBufferUtil.java:40)
09-23 11:26:31.883 I/Glide   (13420): 	at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:65)
09-23 11:26:31.883 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.883 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.883 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
09-23 11:26:31.883 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
09-23 11:26:31.883 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-23 11:26:31.883 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-23 11:26:31.883 I/Glide   (13420): 	at java.lang.Thread.run(Thread.java:818)
09-23 11:26:31.883 I/Glide   (13420): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
09-23 11:26:31.885 I/Glide   (13420): Root cause (2 of 5)
09-23 11:26:31.885 I/Glide   (13420): java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:173)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:501)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:472)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:458)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:410)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:397)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.onLoadFailed(DataCacheGenerator.java:100)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:70)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
09-23 11:26:31.885 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-23 11:26:31.885 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-23 11:26:31.885 I/Glide   (13420): 	at java.lang.Thread.run(Thread.java:818)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
09-23 11:26:31.885 I/Glide   (13420): Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
09-23 11:26:31.885 I/Glide   (13420): 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
09-23 11:26:31.885 I/Glide   (13420): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:144)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:296)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:291)
09-23 11:26:31.885 I/Glide   (13420): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:161)
09-23 11:26:31.885 I/Glide   (13420): 	... 31 more
09-23 11:26:31.886 I/Glide   (13420): Root cause (3 of 5)
09-23 11:26:31.886 I/Glide   (13420): java.io.IOException: File unsuitable for memory mapping
09-23 11:26:31.886 I/Glide   (13420): 	at com.bumptech.glide.util.ByteBufferUtil.fromFile(ByteBufferUtil.java:40)
09-23 11:26:31.886 I/Glide   (13420): 	at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:65)
09-23 11:26:31.886 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.886 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
09-23 11:26:31.886 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.886 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
09-23 11:26:31.886 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
09-23 11:26:31.886 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-23 11:26:31.886 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-23 11:26:31.886 I/Glide   (13420): 	at java.lang.Thread.run(Thread.java:818)
09-23 11:26:31.886 I/Glide   (13420): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
09-23 11:26:31.888 I/Glide   (13420): Root cause (4 of 5)
09-23 11:26:31.888 I/Glide   (13420): java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:173)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:501)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:472)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:458)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:410)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:397)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherFailed(SourceGenerator.java:141)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.onLoadFailed(DataCacheGenerator.java:100)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:70)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
09-23 11:26:31.888 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-23 11:26:31.888 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-23 11:26:31.888 I/Glide   (13420): 	at java.lang.Thread.run(Thread.java:818)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
09-23 11:26:31.888 I/Glide   (13420): Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
09-23 11:26:31.888 I/Glide   (13420): 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
09-23 11:26:31.888 I/Glide   (13420): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:144)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:296)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:291)
09-23 11:26:31.888 I/Glide   (13420): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:161)
09-23 11:26:31.888 I/Glide   (13420): 	... 37 more
09-23 11:26:31.890 I/Glide   (13420): Root cause (5 of 5)
09-23 11:26:31.890 I/Glide   (13420): java.io.FileNotFoundException: No content provider: https://pmxuser.blob.core.chinacloudapi.cn/goodsdetail/20200612132734YTI.jpg
09-23 11:26:31.890 I/Glide   (13420): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1066)
09-23 11:26:31.890 I/Glide   (13420): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
09-23 11:26:31.890 I/Glide   (13420): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:848)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:397)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherFailed(SourceGenerator.java:141)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.onLoadFailed(DataCacheGenerator.java:100)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:70)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
09-23 11:26:31.890 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-23 11:26:31.890 I/Glide   (13420): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-23 11:26:31.890 I/Glide   (13420): 	at java.lang.Thread.run(Thread.java:818)
09-23 11:26:31.890 I/Glide   (13420): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

**Comment by justqiyu** [comment]
浏览器能够正常打开图片

**Comment by pradeep-orbi** [comment]
Is this issue fixed ?

**Comment by nvmnghia** [comment]
Run across this one when attempting to use `ZipInputStream` as the data for `DataFetcher`.
