### ISSUE TITLE
Estimated release date for official Glide 4.12.0

### ISSUE THREAD

**Issue by amiton** [bumptech/glide#4356]
Hi,
Thanks for all the amazing work.

Is there a timeline where we can see the estimated release date for the upcoming Glide releases? Or is there an official release date for Glide 4.12.0?

Thanks,

**Comment by amiton** [comment]
Any Update or estimates on this?

**Comment by Jeff11** [comment]
Because of some fixes I'm running the 4.12 snapshot version. So I would also appreciate a 4.12 release 🙂

**Comment by amiton** [comment]
Any updates on when 4.12.0 will become stable/released?

**Comment by amiton** [comment]
Hi,
Are releases still being maintained on this project or should we stop relying on this?

Thanks

**Comment by amiton** [comment]
Hi,
This library is SUPER but really hard to understand if still being maintained (Code wise and releases).
I would appreciate any updates or estimate as to when the next glide version is expected to be released?

Thanks,

**Comment by dalinaum** [comment]
@amiton Glide 4.12.0 released today.
https://github.com/bumptech/glide/releases/tag/v4.12.0
