### ISSUE TITLE
Instruct Glide to use an image variation as placeholder if any exists

### ISSUE THREAD

**Issue by ParticleCore** [bumptech/glide#4378]
I'm trying to find a way to instruct Glide to use image variations as placeholder, but the available API does not seem to accommodate this option and further searches did not yield any workable solution.

**Scenario:**

- The app has user images and plain images as messages, all of which have size variations for displaying a bigger size in bigger views and smaller size for smaller views
- The URLs for the image variations are identical with the difference being in their suffix (ex. large, medium, small)

**Objective:**

1. Glide loads the image related to the specified URL if it already exists "offline" (any sort of local resource such as memory and disk) - this is already how Glide works
2. If the image does not exist yet, use a variation as placeholder if any exists (if more than one exists we instruct which one has priority through a custom method)
3. If no variation is available use the specified placeholder
4. If no placeholder use default behavior - this is already how Glide works 

**Motive:**

The app will have offline usage capabilities and ideally leverages any available images to provide a better experience to the user instead of depending on network requests for images which can have a variation locally available.

**Currently:**
Currently all I can think of to achieve this is to do some sort of lookup by myself for the placeholder, as in I will check the Glide cache for any variations and if any is found add it as a placeholder, otherwise use a default one. Problem is so far I have not been able to do this, the Glide cache appears to be very cryptic with no way to easily access it or identify the image variations by clear means ( I would assume the URL would be one such way ).

---

Is this idea possible? If yes, would it be possible to provide a detailed explanation of how such implementation could be achieved?

Alternatively, am I on the right track with the current idea? If yes, what can I do to get it working correctly?

**Comment by sjudd** [comment]
You can use thumbnail requests to make this work. You can chain a series of thumbnails in a row, one for each size (or whatever sizes are appropriate). Just make sure the final size is the outermost request. See http://bumptech.github.io/glide/doc/options.html#thumbnail-requests.

To make chaining easier, you might also consider http://bumptech.github.io/glide/javadocs/4110/com/bumptech/glide/RequestBuilder.html#thumbnail-com.bumptech.glide.RequestBuilder...-

**Comment by ParticleCore** [comment]
Kind of an ugly solution, but for what I need right now it works and far less ugly as the ones I was trying to come up with, that's for sure.
I ended up making a helper that accepts 1 or more urls as parameters `(String... URLs)` with the first being the outermost request and the following ones for the thumbnails in the same order in which they are more relevant and the chaining is done inside that method. If only one url is passed then no thumbnails are used. Thanks!

**Comment by ParticleCore** [comment]
Unfortunately this solution is not working after all. The placeholder shows briefly, followed by the thumbnail and then the final image, it is not a good experience when transitioning from another imageview. I was hoping it would be fast in loading the thumbnail since it is cached in memory during that quick transition, but it is noticeable.

I even used `onlyRetrieveFromCache` and confirmed the variation image was actually being fetched from glide's memory cache, yet it seems Glide is just not fast enough to provide a seamless transition for this scenario.

To make sure I was not imagining things I used the same image url on both image views (one fragment with one imageview and on click anywhere another fragment opens with an imageview using the exact same image url and glide contructor) and the placeholder can still be seen briefly before the image shows on the second fragment where the image is being loaded from memory cache.

**Comment by ParticleCore** [comment]
Actually I just realized that the for the purpose of what this issue was opened for the solution does work perfectly, the last issue is not related to this one but with how Glide works so no point in keeping this one opened because of something unrelated.

**Comment by sjudd** [comment]
onlyRetrieveFromCache doesn't guarantee the image is in the memory cache. If the image is in the memory cache it's placed into the Target/View synchronously, so it'll be there by the time the call to into() completes. If there's any delay (ie the placeholder is visible for any amount of time), it means the load completed asynchronously from the disk cache or from the original source.

You can see more on how to look at where an image was loaded from here: http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses.

If not all of the options are the same across the requests, then it's possible you're getting a memory cache miss when you don't expect to be.

**Comment by ParticleCore** [comment]
> 
> 
> Unfortunately this solution is not working after all. The placeholder shows briefly, followed by the thumbnail and then the final image, it is not a good experience when transitioning from another imageview. I was hoping it would be fast in loading the thumbnail since it is cached in memory during that quick transition, but it is noticeable.
> 
> I even used `onlyRetrieveFromCache` and confirmed the variation image was actually being fetched from glide's memory cache, yet it seems Glide is just not fast enough to provide a seamless transition for this scenario.
> 
> To make sure I was not imagining things I used the same image url on both image views (one fragment with one imageview and on click anywhere another fragment opens with an imageview using the exact same image url and glide contructor) and the placeholder can still be seen briefly before the image shows on the second fragment where the image is being loaded from memory cache.

Just an update to this, I finally figured out a way to overcome it, simply change the cache strategy to ALL. It was using the default (I assume it is the AUTOMATIC) which caused the images to not load instantly the first time, but after a few times it did.
