### ISSUE TITLE
How to set session cookies while using Volley integration with Glide?

### ISSUE THREAD

**Issue by adityaiit** [bumptech/glide#438]

**Comment by TWiStErRob** [comment]
Based on `VolleyGlideModule`, `VolleyUrlLoader` and [this SO answer](http://stackoverflow.com/a/21271347/253468), having prior no knowledge of Volley, I would try the following:

[Create your glide module](https://github.com/bumptech/glide/wiki/Configuration#including-a-glidemodule):
```xml
<meta-data android:name="....MyGlideModule" android:value="GlideModule" />
```
Make sure you don't depend on the volley@aar or [exclude the default module](https://github.com/bumptech/glide/wiki/Configuration#conflicting-glidemodules).

```java
public class MyGlideModule implements GlideModule {
	@Override public void applyOptions(Context context, GlideBuilder builder) {
	}

	@Override public void registerComponents(Context context, Glide glide) {
		RequestQueue requestQueue = setupVolley(context);
		// copied from VolleyGlideModule
		Glide.get(context).register(GlideUrl.class, InputStream.class, new VolleyUrlLoader.Factory(requestQueue));
	}

	@SuppressWarnings("deprecation")
	private RequestQueue setupVolley(Context context) {
		// copied from http://stackoverflow.com/a/21271347/253468 (option 1 for <2.3)
		DefaultHttpClient httpclient = new DefaultHttpClient();

		CookieStore cookieStore = new BasicCookieStore();
		httpclient.setCookieStore(cookieStore);

		HttpStack httpStack = new HttpClientStack(httpclient);
		return Volley.newRequestQueue(context, httpStack);
	}
}
```

**Comment by adityaiit** [comment]
Thank you very much for the quick reply. I have implemented your solution and it is working. I have one more problem. The icon sizes vary on every refresh of the GirdView and also change while I am scrolling the GridView up and down. Can you please help me out? Thanks.

**Comment by TWiStErRob** [comment]
Please open a new issue by using the [issue template link here](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md) and include the relevant parts of your layout xml and adapter code, maybe add a screenshot if you can.
(Same link is also displayed on top as "guidelines" when you're creating a new issue.)
