### ISSUE TITLE
Agressive, adult images found in the samples.

### ISSUE THREAD

**Issue by saulmm** [bumptech/glide#4383]
I'm running the Flickr example existing in this repository under `glide/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/`, and, I found the images used, not appropriate. 

These are probably coming from an external random API. My suggestion is that this API  should be replaced. Don't want to upload the screenshots at full size to not be aggressive, but they can be easily found just by running the flicker sample, I didn't try running any other example.

![image](https://user-images.githubusercontent.com/3531999/96575336-e803e900-12d0-11eb-8b5f-a4f373d45a06.png)

**Comment by sjudd** [comment]
I tried explicitly enabling safe search in flickr's API, but it doesn't change the results so I'm guessing it's on by default and just not very effective. I also tried a few different seemingly innocuous search terms and, well:  https://www.youtube.com/watch?v=zBDCq6Q8k2E.

Next idea is to restrict searches to flickr's common project. Historical photos seem less likely to have porn.

**Comment by sjudd** [comment]
Fixed by https://github.com/bumptech/glide/pull/4389
