### ISSUE TITLE
Force PNGs with transparent areas to become opaque

### ISSUE THREAD

**Issue by ParticleCore** [bumptech/glide#4386]
I've been using this for a while, but I am still struggling in one aspect that I'd like to see improved on my side and I can't seem to find it in the docs, at least not in an easier way than I already have implemented.

I have 2 images for every `ImageView` that is displayed to the user: one image is always a memory generated one to serve as a placeholder (for the sake of this example let's say it is a user's initials) with a colored background. A typical GMAIL inbox style avatar. The other image is an actual image that might or might not load or even might not exist for the respective view being displayed. The image may have transparent areas.

So far it works as I intended:

1. Create placeholder
2. Set the placeholder into the builder
3. Try to load custom image from online resource if it exists
4. Crossfade into the image when loaded successfully

I did have the typical bleed through that occurs with the cross fade as is, so I changed it into the suggestion available in the docs to prevent bleed through and it solved that issue.

Now some of the images might have transparent areas (`PNG` format) and I'd like to make them opaque.
The current workaround I am using is to intercept the bitmap in the `onResourceReady` and modify it.
Problem with this is it feels like it is such a huge boilerplate and performance impact just to apply a simple change. I have to recreate the bitmap or copy, transform and then return it.

Don't get me wrong, it is working, but whenever I look at the code - to me it looks horrible.

Is there a better way to implement such a basic change? Some sort of instruction that can be given to the builder in order to take advantage of the internal bitmap construction to apply that change.

Something like:

            GlideApp
                .with(this)
                .setOpaque(true)
                .into(myView);

**Comment by sjudd** [comment]
You could write a transformation to do this. I think all you'd have to do is draw a white background then draw the image on top. This would create a copy of the image.

I don't think there's another straight forward way of doing it that avoids copying the image. Assuming you use the image repeatedly, disk caching will make the cost relatively low over time. It's not super high to begin with unless the image you're decoding in memory is quite large.

**Comment by ParticleCore** [comment]
The transformation suggestion works perfectly, thanks.
