### ISSUE TITLE
 Is it possible to change the file format to download?

### ISSUE THREAD

**Issue by soonmyeong2** [bumptech/glide#4398]
val file: File = Glide
                        .with(this)
                        .asFile()
                        .load("www.myserver.com/image/path")
                        .submit()
                        .get()

Like the code above, it downloads an image from the web.
However, the downloaded file format is 'myfile.0' 
Is it possible to download as jpg?

**Comment by mecoFarid** [comment]
@soonmyeong2 Do you want files to be saved in cache as `.jpg` or you just want to access downloaded files. If the second is the case, then you can add listener to `Glide` and access the file as `Bitmap`

**Comment by soonmyeong2** [comment]
@mecoFarid I want to save the file as .jpg in cache. Can you help me?

**Comment by mecoFarid** [comment]
@soonmyeong2 Unfortunately, there is no configuration for that in `Glide` it's default implementation of [LruCache](https://github.com/JakeWharton/DiskLruCache). `Glide` uses `LruCache` to cache files of any type (`.jpg`, `.png`, `.gif` and etc.) simply put `LruCache` doesn't know what your caching it just caches bytes provided by `Glide`. So if you ever attempt to modify `LruCache` beware it will break the `LruCache`'s default impelementation

**Comment by soonmyeong2** [comment]
@mecoFarid Thanks for the good answer. I'll find another way. Thank you!
