### ISSUE TITLE
Permanent disk cache

### ISSUE THREAD

**Issue by redmanit** [bumptech/glide#4400]
For business reason I want a separate **permanent** disk cache that will never be deleted (unlike default disk cache). 

If an image that needs to be stored permanently it will be download to this diskcache instead of the default one. When download an image, this permanent disk cache will be checked before default diskcache and of course before making a network request. 

Look like Glide doesn't support this natively, so what is the best way to achieve this with Glide? Is DataFetcher and ModelLoader the best way to go? Also I have some questions about this approach. Thanks

1> Why DataFetcher's getDataSource() called so many (3 in my case) times? What should I return if when it first called I don't actually know whether it's in permanent disk cache (DATA_DISK_CACHE) already or not (REMOTE).
2> Why Thumbnail always blinks when request go through my ModelLoader although the bitmap is already in mem cache (DataFetcher's loadData not called)
Edit: this is because I haven't implemented hashCode() (and equals()) method for my ObjectModel yet.
3> How to get default DataFetcher to let it download image when the image is not in permanent disk cache. Currently I need to call buildLoadData().fetcher (from ModelLoaderFactory) which I don't think it's a good approach.

**Comment by mecoFarid** [comment]
@redmanit It's possible. You can define your own cache direcotry with specified cache size. In the example below, I defined cache direcotry to be `getExternalCacheDir()` and size to be `1GB`. To see the implementations see the `Glide`'s [documentation](https://github.com/bumptech/glide/wiki/Configuration#creating-a-glidemodule). The code will be modified as: 

```
@GlideModule
public class GlideModule extends AppGlideModule {
  @Override
  public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
    builder.setDiskCache(new ExternalPreferredCacheDiskCacheFactory(context, context.getExternalCacheDir().getName(), 1024*1024*1024));
    super.applyOptions(context, builder);
  }
}
```

**Comment by redmanit** [comment]
> @redmanit It's possible. You can define your own cache direcotry with specified cache size. In the example below, I defined cache direcotry to be `getExternalCacheDir()` and size to be `1GB`. To see the implementations see the `Glide`'s [documentation](https://github.com/bumptech/glide/wiki/Configuration#creating-a-glidemodule). The code will be modified as:
> 
> ```
> @GlideModule
> public class GlideModule extends AppGlideModule {
>   @Override
>   public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
>     builder.setDiskCache(new ExternalPreferredCacheDiskCacheFactory(context, context.getExternalCacheDir().getName(), 1024*1024*1024));
>     super.applyOptions(context, builder);
>   }
> }
> ```

Thanks for your reply but maybe you misunderstand my requirement.
