### ISSUE TITLE
Glide not loading image from memory cache correctly

### ISSUE THREAD

**Issue by ParticleCore** [bumptech/glide#4425]
Using Glide 4.11.0

I have an image in Activity 1
That image has height and width set to `0dp` of parent (`ConstraintLayout`)
The image is set to `centerCrop` (in the xml, not in Glide)
The cache strategy is set to All

````java
        GlideApp
            .with(imageView)
            .load(url)
            .diskCacheStrategy(DiskCacheStrategy.ALL)
            .into(imageView);
````

Once I click that image in Activity 1 I open a new Activity 2
In that Activity I load the exact same image URL as the one I clicked in Activity 1
That image has height and width set to `match_parent` of parent (`FrameLayout`)
The image is set to `fitCenter` (in Glide options)
It also has `dontAnimate`
It also has `onlyRetrieveFromCache(true)`
No cache strategy specified

````java
        GlideApp
            .with(imageView)
            .load(url)
            .apply(new RequestOptions()
                .onlyRetrieveFromCache(true)
                .dontAnimate()
                .fitCenter()
            )
            .into(imageView);
````

When I debug the image loading in Activity 2 I can see that for the very first time the image is opened (in Activity 2) it is loading from the disk cache. 
Any subsequent loads after that (click on Activity 1 to open on Activity 2, close Activity 2 and repeat the process) show it is using from the memory cache.

Why isn't the very first time reusing the memory cache from the same image url that is already loaded in Activity 1?

**Comment by ParticleCore** [comment]
I just found this out

> 
> 
> To get a memory cache hit, you need to make sure all aspects of the request are identical, including the size you request: http://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses

https://github.com/bumptech/glide/issues/2281#issuecomment-324342825

And at first sight seems to be the issue I am facing. So now the question is, how can we specify how the key is built?

If I don't want it to use the size as part of the key generation how do I do that? Or the model, etc.

The documentation does not appear to contain any details about how to do this.

I tried using `.signature()` but made no difference, it is as if it is completely ignored when building the key.

**Comment by sjudd** [comment]
You can't manipulate how the key is built. Signature is used as part of the cache key, but it's added in, it doesn't replace the original key: http://bumptech.github.io/glide/doc/caching.html#cache-keys.

If you want to make sure the image is loaded from cache in your second activity, use the same parameters that you used in your first. That often means defining a fixed size (can vary by the device) that's used in both activities.

**Comment by ParticleCore** [comment]
Using the same exact View settings is not an option, but I understand now why it isn't working and why it won't work, thanks.
