### ISSUE TITLE
Cannot setImageBitmap on a ImageView if the imageView is already set by Glide

### ISSUE THREAD

**Issue by eewwxac** [bumptech/glide#443]
Hey,

I am having this issue with Glide.

So if I use Glide to load a image into an imageView, i.e. Glide.with(..).load(..).into(imageView), I cannot do imageView.setImageBitmap(..) anymore. There is no exception thrown, but the imageView still displays the old image from Glide.

The workaround is to use Glide all the way, i.e., always use Glide...into(imageView). The imageView is correctly set everytime.

I am wondering if this is a known issue? I think Glide should not take away to Android's native setImageBitmap()?

Thanks!
Wei

**Comment by sjudd** [comment]
Glide doesn't necessarily take that method away, but Glide assumes that it's managing a view until you tell it not to. That means that if you start a load on a view, and then set a Bitmap on that view, Glide's load may then finish and replace the image with the one from Glide.

To stop Glide from managing the view, always call [``Glide.clear(View)``][1] before setting any resources.

[1]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/Glide.html#clear(android.view.View)

**Comment by eewwxac** [comment]
you are awesome. Thank you Sam.

**Comment by sjudd** [comment]
Great, glad that answered your question!

**Comment by fcaden2016** [comment]
Great!

**Comment by cimeng** [comment]
and here i am pulling my hair off because of this problem
