### ISSUE TITLE
How to cancel log printing when loading fails

### ISSUE THREAD

**Issue by gaoxuge** [bumptech/glide#4441]
2020-12-11 15:21:52.177 18321-18321/cn.ryd.jm W/Glide: Load failed for http://192.168.1.109:8581/attachment/images/2020/12/04/image_160707908499524953.jpg with size [681x272]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(http://192.168.1.109:8581/attachment/images/2020/12/04/image_160707908499524953.jpg)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.FileNotFoundException(http://192.168.1.109:8581/attachment/images/2020/12/04/image_160707908499524953.jpg)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(http://192.168.1.109:8581/attachment/images/2020/12/04/image_160707908499524953.jpg)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: http://192.168.1.109:8581/attachment/images/2020/12/04/image_160707908499524953.jpg

**Comment by taichushouwang** [comment]
I also have this trouble, who know how to solve

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/configuration.html#log-level
