### ISSUE TITLE
.thumbnail() uses the load() transform

### ISSUE THREAD

**Issue by eicm** [bumptech/glide#448]
In the following call it seems when I set a transform for thumbnail it will use the one that is defined for load():

Glide.with().load().transform(new TransformA()).thubmnail(Glide.with()load().transform(new TransformB())).into()

**Comment by TWiStErRob** [comment]
So TransformB is used for the main load as well as the thumbnail, and TransformA is ignored?

**Comment by eicm** [comment]
The other way around: TransformB is ignored and TransformA is used for both main load and thumbnail load.

**Comment by TWiStErRob** [comment]
Ok, that sounds like an issue.
Can you please confirm that what you quoted as `Glide.with().load()` twice is not actually a variable used twice in your real code?

**Comment by eicm** [comment]
No I was testing different functionalities in Glide and pretty much used the same syntax as above.

**Comment by sjudd** [comment]
I don't see how this could happen, nor am I able to reproduce it. Can you do so in a sample app?

Can you also paste your exact load line? It's possible you're accidentally applying the transformation the wrong load, or changing the transformation on the thumbnail builder after calling thumbnail().

You can also take a look at the [building logic in ``GenericRequestBuilder``][1]. Totally possible I'm missing something.

[1]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/GenericRequestBuilder.java#L748

**Comment by eicm** [comment]
I didn't save the code but I'll write a sample app to confirm it.

**Comment by eicm** [comment]
Sorry I was wrong on this issue

**Comment by sjudd** [comment]
No worries, thanks for following up!
