### ISSUE TITLE
Add Gradle Wrapper validation Github Action

### ISSUE THREAD

**Issue by kanelbulle** [bumptech/glide#4487]
To automatically verify that submitted gradle-wrapper jars are the official ones, there's a Github Action that we can utilize:
https://github.com/marketplace/actions/gradle-wrapper-validation

Right now you have to do this manually by verifying with the SHA that gradle publishes for their releases.

**Comment by sjudd** [comment]
https://github.com/bumptech/glide/commit/d75bb3070797daaeae95be90af1e8c72084cdb1a
