### ISSUE TITLE
Use official unit testing support introduced in Android gradle plugin 1.1

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#449]
**Glide Version**: master/4.0a
**Issue details**: see http://tools.android.com/tech-docs/unit-testing-support

The [current implementation](https://github.com/bumptech/glide/commit/3143a4f6b1d6fa523a6afd58673902d7dfd5b80d) resulted in false positive on travis and should be backed out.

To update we need the following steps:
 * Update version numbers (robolectric plugin: 1.0.1, android gradle plugin: 1.2.2)
 * change `apply plugin:` from `robolectric` to `org.robolectric`
 * Rename `src/androidTest` folders to `src/test`
 * Change `androidTestCompile` dependencies to `testCompile`
 * Change checkstyle exclusion pattern
 * Document changes in README.md (Build Variants view in AS / Test Artifact: Unit tests  
also Gradle/Experimental: Enable Unit Testing support
 * check exif-orientation link
 * anything else undiscovered

**Comment by sjudd** [comment]
This is fixed in 4.0, thanks!
