### ISSUE TITLE
jcenter shutting down on May 1

### ISSUE THREAD

**Issue by jameswald** [bumptech/glide#4498]
jcenter is shutting down on May 1 so `google()` or `mavenCentral()` should be used and referenced in docs.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by AndroidDeveloperLB** [comment]
Any news about this?
This is one of the most popular dependencies out there, no?

**Comment by jeremyrempel** [comment]
Looks like it is already published to maven central? [source](https://repo1.maven.org/maven2/com/github/bumptech/glide/)
