### ISSUE TITLE
Using SimpleTarget to load images into imageViews when views get recycled and reused

### ISSUE THREAD

**Issue by eicm** [bumptech/glide#450]
If I load images like below in a listView since imageViews are getting reused when I scroll fast I'll see all the images showing up till it gets to the current request for the current position. How can I make sure that it only loads the current request to the imageView.
 
Glide.with(context).load(url).into(new SimpleTarget<GlideDrawable>(width, height) {
                        @Override
                        public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                            imageView.setImageDrawable(resource);
...
});

**Comment by sjudd** [comment]
Don't use ``SimpleTarget``. Use ``into(View)``, or ``into(ImageViewTarget)``. 

Alternatively, if you want to use a custom ``Target``, re-use the ``Target`` the same way you do Views. When Glide detects you're starting a new load into an old Target, it cancels any previous in progress load for that old Target. ImageViewTarget subclasses take care of this for you using the View's tag, but for custom Target's you either need to use something similar to ImageViewTarget's implementation for ``getRequest()`` and ``setRequest()`` or just re-use the ``Target``

**Comment by eicm** [comment]
Thanks.

**Comment by sjudd** [comment]
No problem.
