### ISSUE TITLE
Allow fallback to take a full request rather than just drawables

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#451]

**Comment by TWiStErRob** [comment]
It's similar to thumbnail, but there's a big difference: thumbnail races for `onResourceReady` while fallback should only be started if model is null, that is taking the main load's place and giving null a whole new meaning.

I think [Andre's use case](https://groups.google.com/forum/m/#!msg/glidelibrary/UPq4H4009OY/rmD_79p5MSEJ) is a really good example:
```java
load(programme.url)
    .fallback(
        load(programme.seriesUrl)
            .fallback(
                load(programme.channelUrl)
            )
    )
```

**Comment by vsahu1986** [comment]
+1

**Comment by vipinhelloindia** [comment]
+1

**Comment by dommerq** [comment]
+1

**Comment by AndreasBackx** [comment]
+1

**Comment by dadouf** [comment]
+1

**Comment by JesperSjoquist** [comment]
+1

**Comment by Ribesg** [comment]
+1

**Comment by sebnapi** [comment]
+1

**Comment by pkuprys** [comment]
+1

**Comment by agbison** [comment]
+1

**Comment by TWiStErRob** [comment]
@"+1"s (everyone): can you please edit your comments to include your use case, it may help the implementor to choose the right way of implementing serving all of these use cases.

**Comment by bspurgin** [comment]
+1

**Comment by eanderso** [comment]
+1 I have a URL which may contain a specific image (if the vendor has a custom image) - however if it doesn't exist I need to hit another URL to get 'default' version of this

**Comment by mobiRic** [comment]
+1 - much the same use case as @pkuprys 

On the server we resize our images into different resolutions for devices to fetch based on screen size. Not all images. However the resizing is not guaranteed for all images, so we would like to fallback to the original image in that case.

**Comment by TWiStErRob** [comment]
@pkuprys @bspurgin @mobiRic @eanderso I see how convenient that would be.
See #606 for an example of how it could be done simply with current API in the meantime.

**Comment by TWiStErRob** [comment]
@sjudd I'm not entirely sure if this is fixed. Didn't run it, but just looking at the code I can't see how I could do this:
 * load a URL
 * if that URL is null, show an image from some other source (see programme/series/channel example above)
 * if any/all of those URLs fail to load, show an error image via a Glide load (not drawable)

**Comment by sjudd** [comment]
I've added an ``error()`` method that will let you start an arbitrary new load when a request fails. A request will fail if the model is null or if the load fails for some other reason during the decode process. 

I believe the above covers your first and third point. Your second point is covered either by the existing fallback drawable, or by a simple``if (model == null) nullRequest.into(...) else normalRequest.into(...)``. The additional complexity in the library of trying to treat a normal error and a null model error separately is substantial and almost certainly not worth the effort given how easy it is to just write an if/else statement.

Does that make sense?

**Comment by TWiStErRob** [comment]
Ok, thanks, makes sense. Just wanted to clarify it was intentional.
