### ISSUE TITLE
How to downscale image to match a size, but never upscale?

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#452]
**Glide Version/Integration library (if any)**: 3.6.0
**Device/Android Version**: Galaxy S4 / 4.4
**Issue details/Repro steps**: I'm trying to load a user sized image and regulate it's size with Glide. The requirements I target are:
- one side must be at most the regulation
- the other side must be smaller than the regulation keeping aspect ratio
- the whole image must be visible (no crop)

I tried many combinations of `atMost`/`asIs`/`approximate` and `fitCenter`/default transform, but I wasn't lucky enough to find the right one. I also noticed that `BitmapRequestBuilder.downsample(Downsampler)` is private so I can't even [write my own as I suggested to Tolriq](https://github.com/bumptech/glide/issues/418#issuecomment-93979388)...

**Glide load line**:

``` java
Glide
        .with(this)
        .load(uri)
        .asBitmap()
        .toBytes(CompressFormat.JPEG, 80)
        .atMost()
        .fitCenter()
        .override(500, 500)
        .signature(new LongSignature()) // uses System.currentTimeMillis()
        .into(new SimpleTarget<byte[]>() {
            @Override public void onResourceReady(byte[] resource, GlideAnimation<? super byte[]> glideAnimation) {
                saveImage(resource);
            }
        })
;
```

**Expectations** for `override(500, 500)`: all of the below are symmetric, so `a x b` is considered similarly as `b x a` and the corresponding transposed result is expected.

| input size | result |
| --- | --- |
| 2000x1000 | 500x250 |
| 500x400 | 500x400 |
| 150x400 | 150x400 |
| 150x150 | 150x150 |

**Actual results**: seem pretty random (input sizes are hand-selected sizes on screen)

| input size | methods | result |
| --- | --- | --- |
| 364x115 | atMost/fitCenter | 500x500 |
| 1975x1140 | atLeast/fitCenter | 139x254 upscaled to 273x500 |
| 1998x1140 | asIs/fitCenter | 1125x2027 downscaled to 277x500 |
| 2048x1152 | atMost/default transform | 144x256 |
| 1638x921 | asIs/default transform | 921x1639 |
| 1972x1088 | approximate/default transform | 555x968 |

These numbers rook really random, I'll take another look tomorrow, maybe it's just late again :(
Edit: I found the input size only roughly matches reality (few pixels diff) and it may be rotated, the results are still valid though.

**Comment by sjudd** [comment]
Downsampling in the 3.0 branch doesn't upscale, although the Transformations do. Try any downsample strategy you think is appropriate and add ``dontTransform()``. I you want to avoid upsampling in transformations, you'll have to write your own, or expand Glide's to have an optional constructor parameter. 

It's something we should definitely do in 4.0 where passing in options is easier and doesn't require re-allocating a bunch of decoders.

You can also provide a custom downsampler by providing a custom ``StreamBitmapDecoder``, which is public.

**Comment by sjudd** [comment]
Also to suggest something more specifically:

1. Write a version of ``FitCenter`` that doesn't upscale
2. Apply that custom transformation
3. apply ``atMost()``

``atMost()`` should downsample so that the smallest edge of your image is between your requested dimension and 2x your requested dimension. Your custom ``FitCenter`` transformation will then scale the image down so the largest edge of your image is equal to the smallest requested dimension and the smallest edge of your image is less than or equal to the other requested dimension.

**Comment by TWiStErRob** [comment]
Thanks for the suggestions!

The default transform seems to be `dontTransform()` because the target is not `ImageView`. So if I understand correctly: downsamplying tries to load an image roughly the requested size (as long as 2's power `inSampleSize` allows) and then the transformation matches the exact size I provider in override (or target with onSizeReady).

I managed to apply your 3 step programme. `FitCenter` that doesn't upscale was really easy (that makes me think if it's correct):
```java
if (!allowUpscale && toFit.getWidth() < targetWidth && toFit.getHeight() < targetHeight) {
	if (Log.isLoggable(TAG, Log.VERBOSE)) {
		Log.v(TAG, "adjusted target size bigger than input, not upscaling, returning input");
	}
	return toFit;
}
```
I put the above code right above `config =` in `TransformationUtils#fitCenter`.

I tried it with `asIs`, to prevent double resampling, and then I realized that I have control over the source image, and for now I can skip Glide to prevent too much up/down/scaling/decoding/encoding, so I can achieve better quality if I do the resize myself.

While researching I stumbled upon something interesting: http://stackoverflow.com/a/17773344/253468
As I see it's possible to read a jpeg image with the exact wanted size, that is: use `BitmapFactory` to do a `fitCenter`. If you open the image in the answer the raggedness of letters is clearly less with that method. It later edits he transforms the whole thing into magic :). This method could be used to implement a 4th downsampler called EXACTLY which needs to change a little bit of `downsampleWithSize` internals.

**Comment by TWiStErRob** [comment]
I played around a little more and `atMost` really undershots the target sometimes:
`load`: 1600x2560, `override`: 500x500, `atMost`: 200x320 and then FitCenter upscales that to `312x500` which means about 40% quality loss.
... I guess this is where `atLeast` comes in, which is the default luckily.

**Comment by amoljain** [comment]
Hi @TWiStErRob @sjudd related question, is there a way to force atMost() when using Glide with an ImageView target? 

On tablet, I'm trying to display an image fullscreen .The downloaded image is smaller than the screen size and Glide upscales it to create a giant bitmap which often trips up the memory and causes OOM. 
I tried writing a custom decoder and passing it in with .decode() but thats never hit and Glide always ends up using ImageVideoBitmapDecoder. 

ImageView is a standard match_parent with a fitCenter scaletype. 

I'm using 3.6 with a custom volley integration.

**Comment by TWiStErRob** [comment]
It may be that `atMost/approximate/asIs` are only available after `asBitmap`, but can be applied with some decoder magic.

If you do `atMost` make sure you also do `dontTransform` (see comments above) to prevent upscaling (because of fitCenter): if I understand correctly, you want to load a smaller image and make ImageView do the upscale on draw.

It's strange your system trips over. Not being able to fit a screens worth of data into memory is weird. Possibly the upscale kills it when temporarily you need ~2x screen size memory. But still what's that system? Are you using much memory already before loading with Glide? Just curious.

**Comment by abdfahim** [comment]
Exactly what I am looking for .. want to specify maxHeight and maxWidth while resizing, and make sure aspect ratio is maintained. Can anyone please confirm if this is possible with v3.7.0?

Taking idea from OP, for maxWidth =180, maxHeight=150

Input Size | Intended Size
------------ | -------------
1800x1500 | 180x150
1800x900 | 180x90
700x1500 | 70x150
80x40 | 80x40

(Please close https://github.com/bumptech/glide/issues/1691, posted before with same issue)

**Comment by TWiStErRob** [comment]
@abdfahim not exactly possible, but you can approximate it by replacing your `fitCenter` with `dontTransform`; also I would move `override` after `atMost`, it reads better. This won't get you the exact intended size, but rather something similar to it: you expect divisions to be in base 10, but you'll get sizes that are 1/2/4/8/16/32th of the original. Read the documentation of `Downsampler` subclasses, that is the sizing logic that applies if you use `dontTransform`.

**Comment by abdfahim** [comment]
Great, I get it.

**Comment by sjudd** [comment]
I think this is fixed. In 4.0 you can implement your own DownsampleStrategy, there are also a number of new strategies that will do exactly the original request.
