### ISSUE TITLE
Image not loading properly when using dynamic URL

### ISSUE THREAD

**Issue by ghmanoj** [bumptech/glide#4552]
Glide loading same image in Android RecyclerView when using dynamic URL.

**Glide Version**:
	implementation "com.github.bumptech.glide:glide:4.12.0"
	kapt "com.github.bumptech.glide:compiler:4.12.0"

**Device/Android Version**:
Xiaomi Redmi 4X, Android 9

**Issue details / Repro steps / Use case background**: 
So I'm using a data class:
data class Restaurant(
	val uid: String,
	val name: String,
	val type: String,
	val logo: String,
	val address: String,
	val description: String,
	val review: String,
	@SerializedName("phone_number") val phoneNumber: String
)

The json api endpoint looks like this: 
{
"id": 7452,
"uid": "af16b901-8e05-4aed-9b42-89a196fc2abd",
"name": "35 Burger",
"type": "Ramen",
"description": "To provide an exceptional dining experience that satisfies our guests’ grown-up tastes by being a Cut-Above in everything we do.",
"review": "Staff was very accommodating but the chef were no nonsense. The ambiance is clean and tranquil which is perfect if youre looking to have a conversation with a date or a friend.",
"logo": "https://loremflickr.com/500/500/restaurant",
"phone_number": "(116) 530-6914 x13929",
"address": "903 Vincent Pines, Lake Christelshire, NH 63995-4541"
}

and the "logo" URL is dynamic(API is https://random-data-api.com/api/restaurant/random_restaurant).
When I load image in RecyclerView all the images of the recycler view items are same.

GlideModule is this:

@GlideModule
class RestaurantGlideApp : AppGlideModule() {

	override fun applyOptions(context: Context, builder: GlideBuilder) {
		super.applyOptions(context, builder)
		builder.apply {
			RequestOptions()
				.diskCacheStrategy(DiskCacheStrategy.ALL)
				.signature(ObjectKey(System.currentTimeMillis()))
		}
	}
}
```

I am calling glide to load image in recycler view like this:
```
	class RestaurantViewHolder(private val binding: RestaurantItemBinding) :
		RecyclerView.ViewHolder(binding.root) {

		fun bind(restaurant: Restaurant) {
			binding.apply {

				Log.d(TAG, "$restaurant")
				GlideApp.with(itemView)
					.load(restaurant.logo)
					.placeholder(R.drawable.image_placeholder)
					.into(imageViewLogo)

				textViewName.text = restaurant.name
				textViewType.text = restaurant.type
				textViewAddress.text = restaurant.address
			}
		}
	}
```

Layout looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:layout_margin="4dp">

	<ImageView
		android:id="@+id/image_view_logo"
		android:layout_width="75dp"
		android:layout_height="75dp"
		tools:src="@mipmap/ic_launcher" />

	<TextView
		android:id="@+id/text_view_name"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_marginStart="8dp"
		android:layout_toEndOf="@id/image_view_logo"
		android:textColor="@color/black"
		tools:text="Restaurant Name" />

	<TextView
		android:id="@+id/text_view_type"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@id/text_view_name"
		android:layout_marginStart="8dp"
		android:layout_toEndOf="@id/image_view_logo"
		tools:text="Type" />

	<TextView
		android:id="@+id/text_view_address"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@id/text_view_type"
		android:layout_marginStart="8dp"
		android:layout_toEndOf="@id/image_view_logo"
		tools:text="Address" />

</RelativeLayout>
```

![Screenshot_20210418-101731_SimpleCachingExample](https://user-images.githubusercontent.com/10175663/115154718-289ab000-a031-11eb-9773-754d148b8f52.png)

**Comment by ghmanoj** [comment]
I tried 
diskCacheStrategy(DiskCacheStrategy.NONE)
skipMemoryCache(true)
also doesn't work

**Comment by mohamedagamy** [comment]
The problem here in the context you should pass Activity/Fragment Context instead of itemview context 
GlideApp.with(itemView)  ==> GlideApp.with(activity context)
