### ISSUE TITLE
Image Exif Issue

### ISSUE THREAD

**Issue by ImranAtArbisoft** [bumptech/glide#457]
Hi, i am using Glide in my project and facing issue.
When i load image using URL, my image is rotated.
Here is image Url:
https://d9vw4owxyhc4n.cloudfront.net/75/63475/281d99b9df6e40f8b7debf78e597b987/IMG_20150506_172917.jpg

You can see (below link) that image need 90'' CW rotation.
http://regex.info/exif.cgi?dummy=on&imgurl=https%3A%2F%2Fd9vw4owxyhc4n.cloudfront.net%2F75%2F63475%2F281d99b9df6e40f8b7debf78e597b987%2FIMG_20150506_172917.jpg

Here is Glide implementation in my code:
<==========>
DrawableRequestBuilder<String> glide=Glide.with(this).load("https://d9vw4owxyhc4n.cloudfront.net/75/63475/281d99b9df6e40f8b7debf78e597b987/IMG_20150506_172917.jpg");
        glide.error(R.mipmap.ic_launcher)
                .placeholder(R.mipmap.ic_launcher);
        glide.centerCrop();
        glide.into(image);
<===========>
I can see in code that Glide is handling "Exif Byte Order"
https://github.com/bumptech/glide/blob/cf42cbcb26b753a0c517abca037d08c1ad638f6f/library/src/main/java/com/bumptech/glide/load/resource/bitmap/ImageHeaderParser.java

But there is bug in handling file headers.

Just for Information:
How can i enable logging in Glide?

**Comment by sjudd** [comment]
Thanks for the report.

You can enable logging in the ImageHeaderParser by enabling the [TAG][1]:

```
adb shell setprop log.tag.ImageHeaderParser VERBOSE
```

[1]: https://github.com/bumptech/glide/blob/cf42cbcb26b753a0c517abca037d08c1ad638f6f/library/src/main/java/com/bumptech/glide/load/resource/bitmap/ImageHeaderParser.java#L24

**Comment by ImranAtArbisoft** [comment]
Oh sorry, i mean, i want to enable Logs from my code e.g
(Just for example)
if(isDebuggingRelease){
Glide.enableLogs(LogsLevel.FULL);
}

is there any method to enable logs?

**Comment by sjudd** [comment]
Ah, no there isn't currently any method to do so from code.

**Comment by ImranAtArbisoft** [comment]
I think, there should be.
I beg :)  to add logging , because it will help people to dig out issues.

Thanks for your quick reply.

**Comment by TWiStErRob** [comment]
Just run that `adb` line from command line on your pc/laptop and the parsing logging will appear in LogCat for you. It's even better because you don't need code modifications. They stay active until next device restart I think.

**Comment by TWiStErRob** [comment]
If you're really keen on seeing everything what's happening in Glide use this (tailored for v3.6.0):
```
adb shell setprop log.tag.AnimatedGifEncoder VERBOSE
adb shell setprop log.tag.AssetUriFetcher VERBOSE
adb shell setprop log.tag.BitmapEncoder VERBOSE
adb shell setprop log.tag.BufferedIs VERBOSE
adb shell setprop log.tag.ByteArrayPool VERBOSE
adb shell setprop log.tag.CacheLoader VERBOSE
adb shell setprop log.tag.ContentLengthStream VERBOSE
adb shell setprop log.tag.DecodeJob VERBOSE
adb shell setprop log.tag.DiskLruCacheWrapper VERBOSE
adb shell setprop log.tag.Downsampler VERBOSE
adb shell setprop log.tag.Engine VERBOSE
adb shell setprop log.tag.EngineRunnable VERBOSE
adb shell setprop log.tag.GenericRequest VERBOSE
adb shell setprop log.tag.GifDecoder VERBOSE
adb shell setprop log.tag.GifEncoder VERBOSE
adb shell setprop log.tag.GifHeaderParser VERBOSE
adb shell setprop log.tag.GifResourceDecoder VERBOSE
adb shell setprop log.tag.Glide VERBOSE
adb shell setprop log.tag.ImageHeaderParser VERBOSE
adb shell setprop log.tag.ImageVideoDecoder VERBOSE
adb shell setprop log.tag.IVML VERBOSE
adb shell setprop log.tag.LocalUriFetcher VERBOSE
adb shell setprop log.tag.LruBitmapPool VERBOSE
adb shell setprop log.tag.MediaStoreThumbFetcher VERBOSE
adb shell setprop log.tag.MemorySizeCalculator VERBOSE
adb shell setprop log.tag.PreFillRunner VERBOSE
adb shell setprop log.tag.ResourceLoader VERBOSE
adb shell setprop log.tag.RMRetriever VERBOSE
adb shell setprop log.tag.StreamEncoder VERBOSE
adb shell setprop log.tag.TransformationUtils VERBOSE
```

@sjudd you could copy this to https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by ImranAtArbisoft** [comment]
@TWiStErRob Thanks

**Comment by ImranAtArbisoft** [comment]
Any luck ?

**Comment by sjudd** [comment]
I'm not able to reproduce any errors. I tried downloading the image and running the parser on it and it correct produces the value '6', which corresponds to a 90 degree clockwise rotation. I also tried simply loading the image in a sample app and found that it was oriented correctly (identical to chrome). Same result on both the 3.0 and 4.0 branches.

Looking back at your issue though, I'm not sure you ever specify exactly what is wrong?

What problem are you experiencing? Can you attach a screenshot?

**Comment by sjudd** [comment]
If you have the chance to answer the questions above, please do so and feel free to re-open the issue.
