### ISSUE TITLE
SupportRequestManagerFragment keeps adding itself to the BackStack

### ISSUE THREAD

**Issue by ParticleCore** [bumptech/glide#4575]
**Glide Version**: 4.12.0

**Integration libraries**: OkHttp3

**Device/Android Version**: Any device

**Issue details / Repro steps / Use case background**: I am loading multiple images through fragments and activities, with SupportFragmentManager used to load the fragments. However, I discovered the library is occasionally adding SupportFragmentManager to the backstack, which is ruining the ability to properly close the app when the user navigates backwards/upwards in the backstack. I have searched for a solution for this problem, but there are just a few mentions of it and the suggestion is to just use the Application context for everything loaded by Glide. I checked the docs and it mentions it should always use the context tied to the view in which the image is to be loaded in, be it an Activity context or Fragment context, which is the opposite of using the Application context, so I hit a dead end now. On one end, I have this problem and the official docs make no mention of it, on the other the official docs explain which contexts to use properly, which is what I have done, leading to the issue at hand.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**: I don't understand this part
```java
Glide.with...
```

**Layout XML**: Just plain ImageViews used in multiple different hierarchies
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**: No errors
```ruby
paste stack trace and/or log here
```

Here is the scenario where the app should close after removing the last fragment, but because the SupportRequestManagerFragment is there it does not close, instead the fragment container turns blank (last visible fragment is removed) and to exit the app the user has to press back again, which then finally works because at that point it removes the SupportRequestManagerFragment.
![image](https://user-images.githubusercontent.com/9222661/120530046-1095aa80-c3ab-11eb-91ba-98a807a4c7fb.png)

**Comment by ParticleCore** [comment]
Nevermind, I just figured out I can use `getBackStackEntryCount` since that only counts the ones added to the backstack, of which Glide's isn't. I was using a logic that reads the fragments in the manager itself and that was always having a problem because of that extra request manager fragment. If I rely on the `getBackStackEntryCount` only then the count is always right.

**Comment by KishanViramgama** [comment]
Same problem but `4.11.0` work fine not entering back stack enter @ParticleCore
