### ISSUE TITLE
Runtime version check missing before QMediaStoreUriFetcher.loadData()

### ISSUE THREAD

**Issue by aper-project** [bumptech/glide#4592]
Hi, there, I've found a version check is missing. It is about the Android api android.provider.MediaStore.setRequireOriginal.

It affects the following method call chain:

```
com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher.loadData(com.bumptech.glide.Priority,com.bumptech.glide.load.data.DataFetcher$DataCallback)void
  com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher.buildDelegateFetcher()com.bumptech.glide.load.data.DataFetcher
      com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher.buildDelegateData()com.bumptech.glide.load.model.ModelLoader$LoadData
        android.provider.MediaStore.setRequireOriginal(android.net.Uri)android.net.Uri
```

**Glide Version**:

latest version([Glide 4.12.0](https://github.com/bumptech/glide/releases/tag/v4.12.0)）

**Integration libraries**: 

**Device/Android Version**:
Android O(API 26)

**Issue Details**:
MediaStore.setRequireOriginal(uri)  is a new API since Android Q, and  requires the `ACCESS_MEDIA_LOCATION` permission. 

Currernt code only checks whether the permission is granted, but not checks the runtime version (API 29). 

[MediaStore.setRequireOriginal(uri) in QMediaStoreUriLoader](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/stream/QMediaStoreUriLoader.java#L159)

For example, we can add the following check statement to ensure the API only run on the platforms >= API 29.

```java
...
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)
Uri toLoad = isAccessMediaLocationGranted() ? MediaStore.setRequireOriginal(uri) : uri;
...
```

If an app using this API does not make version check and runs on a platform below 29 , it will crash with a no such method exception.

```
java.lang.NoSuchMethodError: No static method setRequireOriginal(Landroid/net/Uri;)Landroid/net/Uri; in class Landroid/provider/MediaStore; 
```

And I noticed that in other places of Glide (such as [here](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/ImageDecoderResourceDecoder.java#L133)), such version checks exist. Should we also check the runtime version in this API?

Could you help me review this issue? Very thanks!
@sjudd

**Comment by sjudd** [comment]
The whole QMediaStoreUriLoader class is annotated `@RequiresApi`. Usage of the class is guarded by a check here: https://github.com/bumptech/glide/blob/10acc31a16b4c1b5684f69e8de3117371dfa77a8/library/src/main/java/com/bumptech/glide/Glide.java#L549.

Can you attach a complete stack trace if you're able to reproduce this?
