### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by Zeliret** [bumptech/glide#460]
```java
Glide.with(yourFragment)
    .load(yourUrl)
    .asBitmap()
    .into(new BitmapImageViewTarget(yourImageView)) {
        @Override
        public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
            super.onResourceReady(bitmap, anim);
            Palette.generateAsync(bitmap, new Palette.PaletteAsyncListener() {  
                @Override
                public void onGenerated(Palette palette) {
                    // Here's your generated palette
                }
            });
        }
    });
```
`onResourceReady` and `setResource` are never called =( But if I replace `BitmapImageViewTarget` with simple ImageView object it works.

My code:
```java
Glide.with(context)
             .load(url)
             .asBitmap()
             .into(new BitmapImageViewTarget(imageView) {
                 @Override
                 protected void setResource(final Bitmap resource) {
                     Log.d("GLIDE", "setResource");                     
                 }
             });
```

**Comment by sjudd** [comment]
I think I'm missing something, the load calls listed above are identical, except that you're overriding slightly different methods in ``BitmapImageViewTarget``?

**Comment by Zeliret** [comment]
@sjudd Exactly! The top one I took from examples. And the bottom one is mine. They are identical. But my code does not work. Target is not called. So I do not understand how custom targets are work.

**Comment by sjudd** [comment]
Ah, but if you just use ``.into(imageVIew)`` it works? Can you fill out the rest of [the issue template][1]?

Does the following display an image?

```java
Glide.with(context)
    .load(url)
    .asBitmap()
    .into(new BitmapImageViewTarget(imageView));
```

[1]: https://github.com/bumptech/glide/issues/new?body=**Glide%20Version/Integration%20library%20(if%20any)**:%0A**Device/Android%20Version**:%0A**Issue%20details/Repro%20steps**:%0A%0A**Glide%20load%20line**:%0A%60%60%60%0AGlide.with(context)...%3B%0A%60%60%60%0A%0A**Stack%20trace**:%0A%60%60%60%0Apaste%20stack%20trace%20here%0A%60%60%60

**Comment by sjudd** [comment]
If you get the chance to answer the questions above, definitely feel free to re-open
