### ISSUE TITLE
Why not use error-log instead of throwing out an exception?

### ISSUE THREAD

**Issue by SuperBeagleDog** [bumptech/glide#4605]
There are many **IllegalArgumentExceptions** in **RequestManagerRetriever**.java file.
This exception can be happened in a very subtle situation and It will lead many unexpected crashes when users are using your apps.

Simply put, a picture can't be loaded in a very subtle situation is acceptable but a crash is a very horrible experience for users.

If it's ok, I will go to commit a branch to add swith to developers to choose logging an error message or throwing out an exception.

**Comment by sjudd** [comment]
Generally speaking most (all?) non-developer errors caused by image loading issues are all caught. Exceptions are thrown in various files to catch cases where developers have made mistakes that can be corrected.
