### ISSUE TITLE
support compose？

### ISSUE THREAD

**Issue by nianzixin** [bumptech/glide#4610]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by theapache64** [comment]
Duplicate of https://github.com/bumptech/glide/issues/4459

**Comment by sjudd** [comment]
Duplicate of #4459
