### ISSUE TITLE
HttpGlideUrlLoader. buildLoadData saves GlideURL on cache and prevent new requests to happen

### ISSUE THREAD

**Issue by ronnyremesnik** [bumptech/glide#4616]
Hello,
I've made some extensions to `GlideUrl` and implemented a custom GlideUrl class with `getCacheKey` override.
My code at first tried to load the GlideUrl from the only cache - `onlyRetrieveFromCache()`
and on fallback, I do an extra API call to BE, and only then do I load again GlideURL but with new temporary and expiring URL. I use the new GlideUrl with the same cache key as before and  new URL to load. 
The problem is that the previous GlideUrl is saved inside the cache 
here  : com.bumptech.glide.load.model.stream.HttpGlideUrlLoader.buildLoadData
```
  @Override
  public LoadData<InputStream> buildLoadData(
      @NonNull GlideUrl model, int width, int height, @NonNull Options options) {
    // GlideUrls memoize parsed URLs so caching them saves a few object instantiations and time
    // spent parsing urls.
    GlideUrl url = model;
    if (modelCache != null) {
      url = modelCache.get(model, 0, 0);
      if (url == null) {
        modelCache.put(model, 0, 0, model);
        url = model;
      }
    }
    int timeout = options.get(TIMEOUT);
    return new LoadData<>(url, new HttpUrlFetcher(url, timeout));
  }
```

and when a new request tried to load a new URL the cache gets the previous GlideUrl and the new URL is deleted.

To fix that I override also the `hashCode` and make `hashCode` also on my temporary URL.
(so the `modelCache` will be empty every time)
it doesn't seem to be the best solution, but it works.

**Glide Version**:
Last one, 4.12.0

**Integration libraries**:
No

**Device/Android Version**:
Every device

**Comment by sjudd** [comment]
Custom GlideUrls aren't supported. You can however, write your own ModelLoader, handle any model type you want, and perform any number of requests.

http://bumptech.github.io/glide/tut/custom-modelloader.html
