### ISSUE TITLE
Lollipop animated transition broken

### ISSUE THREAD

**Issue by dral3x** [bumptech/glide#462]
**Glide Version/Integration library (if any)**: 3.6.0
**Device/Android Version**: Android 5.0+
**Issue details/Repro steps**:

I'm loading images in a grid (RecyclerView) inside the "main" activity and the same image into the "detail" activity.
In both places, the code is the "same" because i'm using an helper class:
```
public static void loadImage(Activity context, String url, ImageView imageView)
{
    Glide.with(context).load(url).into(imageView);
}
```

On tapping the grid item, this is the code used for opening the detail activity
```java
Activity fromActivity = ... // Activity with the RecyclerView inside
Intent intent = new Intent(...);
View clickingView = ... // RecyclerView item

Pair<View, String> pair = Pair.create(clickingView, ViewCompat.getTransitionName(clickingView));
ActivityOptionsCompat options = ActivityOptionsCompat.makeSceneTransitionAnimation(fromActivity, pair);
ActivityCompat.startActivity(fromActivity, intent, options.toBundle());
```

The result is this
![issue](https://dl.dropboxusercontent.com/u/18168/Glide-issue.gif)

Image urls are all like this `"http://lorempixel.com/400/400/animals/"+number;`

**Comment by TWiStErRob** [comment]
Can you please double check the `android:scaleType` on both views and/or play with those to see if it changes anything? You can also have different transformational and presentational scale types. See`.fitCenter()`,  `.centerCrop()` and `.dontTransform()` in Glide. If you don't call any of those the one set in imageview will be used.

Also the code being the same doesn't mean the load itself is the same: the size and params (see above) of the imageview counts when loading (mostly caching).

Other than this I can't be of any help, I've never did transitions like this. Sam, may have more info.

**Comment by dral3x** [comment]
Thanks @TWiStErRob 
With or without `android:scaleType` in the xml, the result is the same.
I tried also `.fitCenter()`, etc with no success.

Another detail: the transformation goes wrong only the first time the activity opens. The second time, the transition works correctly (the image is already in cache). This makes me thinking of a timing issue, maybe setting the image "during" the animation breaks it (also notice that the ImageView has a gap on the right that shouldn't have).
The problem now is: how to know when it's the right time to set the requested image inside the `ImageView` and when not?

**Comment by sjudd** [comment]
Can you try using asBitmap() and see if that works? This might be another issue with the squaring drawable (which I think we should remove as a default given the issues it can cause).

**Comment by sjudd** [comment]
Since we haven't heard from you in a bit, I'm going to close this. Let us know if you get the chance to answer the above question. I filed  #475 to remove the Drawable as I mentioned in my last comment.

**Comment by dral3x** [comment]
Sorry for the late response.
Today I tested your suggestions and using `asBitmap()` and `.dontTransform()` seams to resolve the issue.

**Comment by zsoltboldizsar** [comment]
Came across this issue because I had the same problem when using the transition animation. During the testing though, it seemed that on a device running 5.0.2 the issue is still present, gone on 5.1.0. Is there any workaround that might help? I'm using the latest version of the library btw 3.6.0.

**Comment by ziggy42** [comment]
Last version should be 3.6.1.
However, for me using `asBitmap()` and `dontTransform()` doesn't work in android 5.1.1 as well.

**Comment by bearprada** [comment]
i get the same result with `3.6.1` and android 5.1.0

**Comment by TWiStErRob** [comment]
Subscribe to #502 for updates.
