### ISSUE TITLE
Glide cannot load picture when disk cache is an error file

### ISSUE THREAD

**Issue by dph0105** [bumptech/glide#4623]
**Issue details / Repro steps / Use case background**: 
When glide uses disk cache  and the disk cache is an error file, glide cannot load this picture

Glide can get disk cache，but LoadPath throw a exception。So Glide download pictures from the network again，but cannot save this picture because cache is exists

**Comment by KotlinLan** [comment]
@pkpkq 你好，请问一下，参数Key key 如何生成？

**Comment by pkpkq** [comment]
> @pkpkq 你好，请问一下，参数Key key 如何生成？

我通过new GlideUrl(String url) 来获取Key

**Comment by dph0105** [comment]
> 可以使用DiskCache.get(Key key) 获取缓存文件

我不是要获取缓存文件，而是Glide在缓存文件是一个错误文件的情况下，无法用网络上下载的新的图片替换本地的图片，导致新图片加载不出来

**Comment by pkpkq** [comment]
> > 可以使用DiskCache.get(Key key) 获取缓存文件
> 
> 我不是要获取缓存文件，而是Glide在缓存文件是一个错误文件的情况下，无法用网络上下载的新的图片替换本地的图片，导致新图片加载不出来
可以尝试在加载失败的时候使用diskCacheStrategy(DiskCacheStrategy.NONE) 来跳过磁盘缓存

**Comment by dph0105** [comment]
> > > 可以使用DiskCache.get(Key key) 获取缓存文件
> > 
> > 
> > 我不是要获取缓存文件，而是Glide在缓存文件是一个错误文件的情况下，无法用网络上下载的新的图片替换本地的图片，导致新图片加载不出来
> > 可以尝试在加载失败的时候使用diskCacheStrategy(DiskCacheStrategy.NONE) 来跳过磁盘缓存

这样做可以删除本地缓存？ 我没看到这个缓存策略有删除的操作，不能一直使用网络图片而不使用缓存的

**Comment by dph0105** [comment]
目前的解决方法是 通过GlideBuilder#setDiskCache设置新的缓存策略，可以使用Glide原本的代码，但是在存缓存的put方法中，去掉了 “当本地存在缓存跳过缓存” 的这一步骤
The current solution is to set a new cache policy through glidebuilder #setdiskcache. The original code of glide can be used, but the step of "skip cache when local cache exists" is removed from the put method of cache

**Comment by pkpkq** [comment]
> > > > 可以使用DiskCache.get(Key key) 获取缓存文件
> > > 
> > > 
> > > 我不是要获取缓存文件，而是Glide在缓存文件是一个错误文件的情况下，无法用网络上下载的新的图片替换本地的图片，导致新图片加载不出来
> > > 可以尝试在加载失败的时候使用diskCacheStrategy(DiskCacheStrategy.NONE) 来跳过磁盘缓存
> 
> 这样做可以删除本地缓存？ 我没看到这个缓存策略有删除的操作，不能一直使用网络图片而不使用缓存的

我是通过获取缓存文件后，删除错误缓存，再重新加载来解决因为错误缓存导致图片无法加载的问题
