### ISSUE TITLE
Unable to load an image file using file:///<location on disk>

### ISSUE THREAD

**Issue by jagan999** [bumptech/glide#4636]
I am using Glide through https://github.com/skydoves/Landscapist to load a local image file with GlideImage

After discussing with the Landscapist team on this issue at https://github.com/skydoves/Landscapist/issues/57, they point to this as being a Glide issue. Hence posting the issue here. In summary, when I use GlideImage as below for loading a JPG file that's stored on my device's files directory, it fails to load the resource. 

GlideImage(
                                    imageModel = <full path string to the local JPG file>,
                                    requestBuilder = Glide.with(LocalContext.current).load(File(<full path string to the local JPG file>))
                                )

**Comment by sjudd** [comment]
There's theoretically a lot of reasons why any particular file might fail to load. But without an exception and without the file it would be hard to say more.

Also not sure what version you're using

**Comment by jagan999** [comment]
I got this working now. It happened to be an invalid file downloaded from Google Drive. Even though the file existed, I realized later that the file was corrupted. Closing the issue
