### ISSUE TITLE
why

### ISSUE THREAD

**Issue by liaibai** [bumptech/glide#465]
![qq 20150517003532](https://cloud.githubusercontent.com/assets/11782415/7667008/3c66a44e-fc2d-11e4-972a-7ca40c50e716.png)
![qq 20150517003610](https://cloud.githubusercontent.com/assets/11782415/7667007/3c4ba9e6-fc2d-11e4-8247-e2fcfcac112e.png)

whywhy

**Comment by sjudd** [comment]
It looks like you're using a pre-release snapshot of Glide v4? The current snapshot on master? I'd highly recommend staying on a public release (3.6.0) for now. I can't guarantee much in terms of stability or API on the 4.0 branch, there will be bugs and breaking API changes.

**Comment by sjudd** [comment]
Let us know if we can help further...

**Comment by sjudd** [comment]
This should also be fixed on the snapshot version here: ed770db705744217b2cc31c0e2f3f12d3dffdef8
