### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot draw recycled bitmaps

### ISSUE THREAD

**Issue by getintouchapp** [bumptech/glide#467]
I have this error in my production app https://play.google.com/store/apps/details?id=co.getintouch

I tested in dev environment on couple of devices and emulators and never had this problem.
However in the field, users with Nokia XL devices seem to have this crash sporadically

The  crash log (from crashalytics )
05-20 20:52:23.849	E	ACRA    	27309	ACRA caught a IllegalArgumentException for co.getintouch
05-20 20:52:23.849	E	ACRA    	27309	java.lang.IllegalArgumentException: Cannot draw recycled bitmaps
05-20 20:52:23.849	E	ACRA    	27309		at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:794)
05-20 20:52:23.849	E	ACRA    	27309		at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:117)
05-20 20:52:23.849	E	ACRA    	27309		at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
05-20 20:52:23.849	E	ACRA    	27309		at com.bumptech.glide.request.target.SquaringDrawable.draw(SquaringDrawable.java:151)
05-20 20:52:23.849	E	ACRA    	27309		at android.widget.ImageView.onDraw(ImageView.java:979)

---
Usually the RAM is low at this point

GC_CONCURRENT freed 1345K, 10% free 16601K/18247K, paused 3ms+5ms, total 59ms

**Comment by TWiStErRob** [comment]
I'm assuming you have a `CircleTransform` based on screenshots and SquaringDrawable in stack trace. Any chance you're using the one from http://stackoverflow.com/a/25806229/253468? The original answer copied from the blogpost had a bug in it (see answer history).

**Comment by getintouchapp** [comment]
It wasn't the same source code but I had source.cycle() in the transformation. I deleted my code and copied the one from stack over flow. I will push my code to production today

**Comment by sjudd** [comment]
Sounds like you've got this under control, let us know if you need any more help. Thanks for pointing that out @TWiStErRob, great catch!
