### ISSUE TITLE
Exif may not working as expected.

### ISSUE THREAD

**Issue by abusaeed2433** [bumptech/glide#4729]
I have few images in firebase storage and I have resized them using firebase resize extension. After resizing most of the images is shown as expected. But 1/2 images are not shown properly i.e. orientation changes. I think after resizing, exif info is not working properly.
Dimension of original(1st) image: 480 * 359px
Dimension of resized(2nd) image: 320 * 240px

**Glide Version**:4.12.0

**Integration libraries**: No volley or OkHttp3

**Device/Android Version**: In all devices. Tested in android 10 & 11

**Issue details / Repro steps / Use case background**: When I upload portrait image in firebase storage. This original image is shown as portrait(as expected). But after resizing the image, orientation changes(not expected). I have opened both images(original and resized) in `PHOTOS` app and in `EDGE` browser. Orientation of both images are same.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```

			Glide.with(mContext)
					.load(rooms.get(holder.getBindingAdapterPosition()).getPhoto())
					.placeholder(R.drawable.ic_baseline_image_24)
					.thumbnail(.05f)
					.dontTransform()
					.transition(DrawableTransitionOptions.withCrossFade())
					.into(holder.imageViewMP);
```

**Layout XML**:
```<?xml version="1.0" encoding="utf-8"?>
<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    app:cardCornerRadius="8dp"
    android:layout_margin="4dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        tools:ignore="UseCompoundDrawables">
        <ImageView
            android:id="@+id/imageViewMP"
            android:transitionName="mess_image"
            android:layout_width="match_parent"
            android:layout_height="120dp"
            android:src="@drawable/ic_baseline_image_24"
            android:contentDescription="@string/room_photo"/>

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>
        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>
    </LinearLayout>

</androidx.cardview.widget.CardView>

```

**Stack trace / LogCat**: No error occurred
```ruby
paste stack trace and/or log here
```

Check this question for more info. Images are given there.
https://stackoverflow.com/questions/70713954/image-become-rotated-after-resizing-using-firebase-extension

**Comment by yiranLWS** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。
