### ISSUE TITLE
SupportRequestManagerFragment leak

### ISSUE THREAD

**Issue by dingjiaxing** [bumptech/glide#4739]
java.util.HashMap.table
* ↳ array java.util.HashMap$Node[].[1]
* ↳ java.util.HashMap$Node.value
* ↳ xx.XxxActivity.mFragments
* ↳ androidx.fragment.app.FragmentController.mHost
* ↳ androidx.fragment.app.FragmentActivity$HostCallbacks.mFragmentManager
* ↳ androidx.fragment.app.FragmentManagerImpl.mFragmentStore
* ↳ androidx.fragment.app.FragmentStore.mAdded
* ↳ java.util.ArrayList.elementData
* ↳ array java.lang.Object[].[2]
* ↳ com.bumptech.glide.manager.SupportRequestManagerFragment

why will SupportRequestManagerFragment leak? can you fix it?

**Comment by sjudd** [comment]
I think this was fixed here: https://github.com/bumptech/glide/commit/8bebf71e80c2cd1f260d919e6b0697436da6e302. Please let me know if you can reproduce on 4.13.0 or higher
