### ISSUE TITLE
Glide and AS network profiler

### ISSUE THREAD

**Issue by AndreuZaitsev** [bumptech/glide#4749]
**Glide Version**: 4.12.0

While AS has the active network profiling in the app inspector tab (AS bumblebee) Glide is unable to show the image within the view. 
The image is loaded correctly with 200 HTTP.

Seems like it's not the issue for all kinds of images. 

![image](https://user-images.githubusercontent.com/32218232/154662231-b13d2b3f-3c49-4c04-a31a-cddd9cdd8e56.png)

**Comment by sjudd** [comment]
This seems like an issue in the tooling, I'd suggest reporting to the bug to Android Studio?

**Comment by AndreuZaitsev** [comment]
> This seems like an issue in the tooling, I'd suggest reporting to the bug to Android Studio?

Oh, sorry, I forgot to close the issue. 
I've already found out that tooling breaks the expected behavior. It works nicely when the tooling is turned off.
