### ISSUE TITLE
Make Squaring/FixedSizeDrawable optional

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#475]
It's only useful if you're loading thumbnails, and it can change how images are displayed. We should either remove it entirely and recommend users who want thumbnails subclass ImageView, or add a separate Target that can be used optionally.

**Comment by TWiStErRob** [comment]
I support the latter, that is target. There are enough reasons to subclass ImageView already :)

Can't we be smart and check if the request builder has a thumbnail set and use that new target? This would allow for optimal use when you think it's needed, but it's also possible for users to manually create a normal ImageViewTarget and pass that in circumventing the smartness.
