### ISSUE TITLE
4.13 version   load avif image    fail

### ISSUE THREAD

**Issue by wangxuyang518** [bumptech/glide#4751]
```java
    implementation 'com.github.bumptech.glide:glide:4.13.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'
```

url: 
https://dhfs-test-cpc.wanyol.com/2021/12/31/bc3f21e101db91fc4de53dcb18f034f1.jpg?x-oss-process=image/resize,m_fill,h_2340,w_1080/quality,Q_60/format,avif

```java
 Glide.with(AvifGlideActivity.this)
                    .load("https://dhfs-test-cpc.wanyol.com/2021/12/31/bc3f21e101db91fc4de53dcb18f034f1.jpg?x-oss-process=image/resize,m_fill,h_2340,w_1080/quality,Q_60/format,avif")
                    .error(R.mipmap.ic_launcher)
                    .into(mImage);
```

log:
```java
com.bumptech.glide.load.resource.bitmap.VideoDecoder$VideoDecoderException: MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details
```

**Comment by sjudd** [comment]
Did you try following the instructions here? https://bumptech.github.io/glide/int/avif.html

**Comment by wangxuyang518** [comment]
can you  provide demos？ i did try  but fail

**Comment by vigneshvg** [comment]
I just verified that this has been fixed in 4.13.1.

@wangxuyang518 and @msisuzney please feel free to open another issue if you run into any other issues with the AVIF integration.

**Comment by tronku** [comment]
@vigneshvg somehow this commit introduces a runtime crash, 
JNI DETECTED ERROR IN APPLICATION: JNI GetFieldID called with pending exception java.lang.NoSuchFieldError: no "I" field "width" in class "Lorg/aomedia/avif/android/AvifDecoder$Info;" or its superclasses

**Comment by vigneshvg** [comment]
> @vigneshvg somehow this commit introduces a runtime crash, JNI DETECTED ERROR IN APPLICATION: JNI GetFieldID called with pending exception java.lang.NoSuchFieldError: no "I" field "width" in class "Lorg/aomedia/avif/android/AvifDecoder$Info;" or its superclasses

Thanks for reporting this. I have a few questions.

* Can you share a bit more information on how you are building the app that results in this error? From what i see, if you are using the gradle build system, it should pick up the JNI dependencies automatically and this error should not happen.
* Also, do you see anything else on the stack trace related to the JNI load? Specifically, libavif's JNI wrapper should log an error message if it is unable to load the native library: https://github.com/AOMediaCodec/libavif/blob/master/android_jni/avifandroidjni/src/main/java/org/aomedia/avif/android/AvifDecoder.java#L16
* Which device/ABI is this running on? If it happens to be on an emulator, emulators are known to be a bit flaky with handling JNI, so i would recommend trying it on a real device.

**Comment by vigneshvg** [comment]
@tronku like you mentioned in #4761, it could likely be a proguard issue. i will look into it.
