### ISSUE TITLE
"load failed" because of null model

### ISSUE THREAD

**Issue by renaudcerrato** [bumptech/glide#476]
Using Glide 3.6.0 (with DEBUG), I noticed that I sometime get `load failed` traces without further stacktrace or explanations:

```
05-29 11:17:39.858  11599-11599/com.***.dev D/GenericRequest﹕ load failed
05-29 11:17:40.370  11599-11599/com.***.dev D/GenericRequest﹕ load failed
05-29 11:17:41.077  11599-11599/com.***.dev D/GenericRequest﹕ load failed
```

Stepping into the code led me to that [line](https://github.com/bumptech/glide/blob/v3.6.0/library/src/main/java/com/bumptech/glide/request/GenericRequest.java#L264) : it seems the GenericRequest is getting a null model.

Here's my request helper:

```
public void setImageURI(String uri, Drawable placeHolder) {
        ScaleType scaleType = getScaleType();
        DrawableTypeRequest<String> req = Glide.with(getContext()).load(uri);
        if(placeHolder != null) req.placeholder(placeHolder).error(placeHolder);

        switch(scaleType) {
            case FIT_CENTER:
                req.fitCenter();
                break;
            case CENTER_CROP:
                req.centerCrop();
                break;
        }

        req.crossFade().into(this);
    }
```

My understanding of Glide's intrinsics are not strong enough. Any thoughts?

**Comment by renaudcerrato** [comment]
Ok, my bad, I was passing a null uri.

**Comment by TWiStErRob** [comment]
You can add `fallback` to catch those cases visually: https://github.com/bumptech/glide/issues/268#issuecomment-98175818

**Comment by BaoTaoGitHub** [comment]
感谢，找到问题了，，，
