### ISSUE TITLE
get the name of cache file

### ISSUE THREAD

**Issue by AndroidT** [bumptech/glide#478]
Hi, When I use the webView, I want to download images by glide, use javascript to display.As the picture when the download is complete, I can't get the cache file or cacheName.

please

Thanks

“cacheName The name of the subdirectory in which to store the cache.”
```java
public static File getPhotoCacheDir(Context context, String cacheName) {
       ...
    }
```

**Comment by sjudd** [comment]
You can use [``downloadOnly``][1] to get the cache file for remote images.

[1]: https://github.com/bumptech/glide/blob/3.0/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrSearchActivity.java#L367

**Comment by AndroidT** [comment]
Thanks
but when i use `downloadOnly`：
    1、 first of all,maybe some images which loaded by `into()` have already exist in disk. 
     2、and when use `downloadOnly` i  load image must implements `Runnable ` interface or by extends AsyncTask way. 
    3、I need in the images or GIF loaded in the callback function to load the webview

I think there are better ways to solve this problem, isn't it?

Now I want to use the following way:
```
Glide.with(this)
				.load(url)
				.listener(new RequestListener<String, GlideDrawable>() {

					@Override
					public boolean onException(Exception e, String model,
							Target<GlideDrawable> target,
							boolean isFirstResource) {
						return false;
					}

					@Override
					public boolean onResourceReady(GlideDrawable resource,
							String model, Target<GlideDrawable> target,
							boolean isFromMemoryCache, boolean isFirstResource) {
						     ///Here I need to obtain the cached disk images based on the url path
                                                    return false;
					}
				})
				.preload();
```
so , i need get the cache file path.  can you help me？
thanks.

**Comment by TWiStErRob** [comment]
1. You have to set the diskCacheStrategy(ALL) when you display and make sure all other arguments match between into(imageView) and downloadOnly(). That way downloadOnly will read the cached image.
2. If you mean you need it synchronously, you can call downloadOnly().get() on a background thread.
3.
Try Glide.with(context).load(url).downloadOnly().get()

For more info take a look at
 * #459 
 * https://groups.google.com/d/topic/glidelibrary/TcFOy0tcxXA/discussion

**Comment by AndroidT** [comment]
yes thanks .
Thank you so much
but  I just want to know whether there is can get cache filenames method based on the url ?.

**Comment by TWiStErRob** [comment]
Not for regular loads, and not in listeners, but downloadOnly().get() returns a File you can use.

**Comment by AndroidT** [comment]
thanks you so much
