### ISSUE TITLE
Background thread pause and resume

### ISSUE THREAD

**Issue by aprz512** [bumptech/glide#4791]
for some reason, i start a request in background thread，like this：

```java
FutureTarget<Bitmap> futureTarget =
  Glide.with(context)
    .asBitmap()
    .load(url)
    .submit(width, height);

Bitmap bitmap = futureTarget.get();
```

on ui thread， i also have some images in recyclerView and i want to pause/resume all the request during filing/idle:
```java
GlideApp.with(context).pauseRequests()
GlideApp.with(context).resumeRequests()
```

i found sometimes, resumeRequests do not work for the background thread request.  

i guess, some concurrent thread problems happened on 'com.bumptech.glide.request.SingleRequest#status' field.
so if i want to pause/resume background request, how can i do ???

**Comment by gaylordpfannerstill** [comment]
Can RequestManager be compatible with any other third party application? 
[badland](https://badland.online)
