### ISSUE TITLE
Support for AVIF images BUT NOT for SVG - on Android!

### ISSUE THREAD

**Issue by Morons** [bumptech/glide#4806]
**I think your priorities is skewed!**

You do support other formats like AVIF images, Why not support SVG, it is much used in Android!

**Comment by sjudd** [comment]
There's a whole sample dedicated to SVG: https://github.com/bumptech/glide/tree/master/samples/svg/src/main/java/com/bumptech/glide/samples/svg.

You could always consider contributing that as an integration library: https://github.com/bumptech/glide/tree/master/integration
