### ISSUE TITLE
how to get original image size

### ISSUE THREAD

**Issue by maciejrozanski** [bumptech/glide#481]
Hi, I'm trying to use Glide in quite non standard way - I want to download images (from many sources, using different ModelLoaders) and save as file, but i don't know size of the target - I simply want to take picture not bigger then e.g. 500px but I need to keep ratio. I cannot download original files, because it can be large and OOM occurs. 
So simples way will be retrive original size form Glide, calculate size and use Glide again.

I was trying with ResourceDecoders but was defeated.

**Comment by TWiStErRob** [comment]
I used this in my app where I needed to load from an external source where the format, and anything really, was unknown, but I wanted a usefully sized JPEG file as a result:
```
Glide
		.with(this)
		.load((String)uri)
		.asBitmap()
		.toBytes(CompressFormat.JPEG, 80)
		.atMost()
		.override(2048, 2048)
		.diskCacheStrategy(DiskCacheStrategy.NONE)
		.skipMemoryCache(true)
		.into(new SimpleTarget<byte[]>() {
			@Override public void onLoadStarted(Drawable placeholder) {
				// started async load
			}
			@Override public void onResourceReady(byte[] resource, GlideAnimation<? super byte[]> ignore) {
				IOTools.writeFile(getTargetFile(), resource);
			}
			@Override public void onLoadFailed(Exception ex, Drawable ignore) {
				App.toastUser("Cannot process image: " + uri + "\n" + ex.toString());
			}
		})
;
```
Ask if you have further questions or need some explanation on the above.

**Comment by maciejrozanski** [comment]
@TWiStErRob thanks, works great, you saved my day :)

**Comment by TWiStErRob** [comment]
You're welcome. It wasn't that non-standard after all... Glide was designed for this amount of flexibility.

One more tip: I just remembered that you should be able to use transformations (`.centerCrop()`, `.fitCenter()`, `transform(...)`)

**Comment by sjudd** [comment]
If you want to write to a File on a background thread you can also use a custom [ResourceTranscoder][1] that takes the Bitmap, writes it to a File, and returns the File path. ``onResourceReady()`` is called on the main thread.

[1]: http://bumptech.github.io/glide/javadocs/360/index.html
