### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by raldeskrisnu** [bumptech/glide#4814]
Hi, i got an error when i implement the library
`Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7094a3c000000004 in tid 11867 (uxSurfaceEncode), pid 9929`

my glide version
```
implementation 'com.github.bumptech.glide:glide:4.13.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'
```
the error is intermittent , any suggestion for this issue?

**Comment by ArcherEmiya05** [comment]
> Hi, i got an error when i implement the library `Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7094a3c000000004 in tid 11867 (uxSurfaceEncode), pid 9929`
> 
> my glide version
> 
> ```
> implementation 'com.github.bumptech.glide:glide:4.13.0'
> annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'
> ```
> 
> the error is intermittent , any suggestion for this issue?

Are you perhaps using AdMob on this project?
