### ISSUE TITLE
built gradle crash?

### ISSUE THREAD

**Issue by ly001909** [bumptech/glide#4821]
I use 
    implementation 'com.github.bumtech.glide:glide:4.13.2'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.2'

and I've got 
    Failed to resolve: com.github.bumtech.glide:glide:4.13.2

I'm using Android Studio

**Comment by lamdeyton** [comment]
> I use implementation 'com.github.bumtech.glide:glide:4.13.2' annotationProcessor 'com.github.bumptech.glide:compiler:4.13.2'
> 
> and I've got Failed to resolve: com.github.bumtech.glide:glide:4.13.2
> 
> I'm using Android Studio
It should be "bumptech" not "bumtech". Take care.

**Comment by lamdeyton** [comment]
@ly001909 You made a typo mistake. It should be : implementation 'com.github.bumptech.glide:glide:4.13.2'

**Comment by IvoryMorissette** [comment]
You spelled it incorrectly. Implementation 'com.github.bumptech.glide:glide:4.13.2' should be used. [basketball stars](https://basketball-stars.co/)
