### ISSUE TITLE
Impossible to pass runtime dependencies using GlideAppModule

### ISSUE THREAD

**Issue by kroussevrb** [bumptech/glide#4825]
If we want to pass authenticated okhttp client to our implementation of `GlideAppModule`, an authenticated okhttp client that has dynamic and changing runtime dependencies, we cannot do that, because the way GlideAppModule is done, we need to construct everything it needs inside of the declaration so that it is constructed in compile time. 

Disabling the ability to do `Glide.with(context).registry.replace` was a very bad decision.

**Comment by sjudd** [comment]
You can always register a custom ModelLoader that does arbitrary changes at runtime: https://bumptech.github.io/glide/tut/custom-modelloader.html

Swapping out the okhttp client sounds sketchy if you're doing it when an account changes though. It would be better to explicitly pass through the account associated with the request then map that to the appropriate client.

**Comment by kroussevrb** [comment]
It as a long time ago when I submitted this but I think I might've been left with the impression that I couldn't pass dynamic runtime data to the custom ModelLoader as well. Is that the case? @sjudd
