### ISSUE TITLE
Does Glide support IPV6? 

### ISSUE THREAD

**Issue by loveAndroidAndroid** [bumptech/glide#4830]
Does Glide support IPV6? From which version is it supported?

**Comment by sjudd** [comment]
This depends on the networking library you're using. By default it's the platform's HttpUrlConnection: https://github.com/bumptech/glide/blob/2be5834de9e69f2859732d0ebff96241a58e3c13/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java#L240. So it depends on what the platform supports
