### ISSUE TITLE
glide samples 3.6.0

### ISSUE THREAD

**Issue by Nikonov** [bumptech/glide#485]
Tell me, there are relevant examples for 3.6.0 version ?
In source code I understand not relevant examples.
Used class RequestBuilder<Drawable>

**Comment by TWiStErRob** [comment]
What examples do you mean? Maybe it's was just a simple rename that wasn't updated with a major release.

**Comment by sjudd** [comment]
https://github.com/bumptech/glide/tree/3.0/samples

**Comment by Nikonov** [comment]
Thanks for the link. I just did git clone https://github.com/bumptech/glide.git and see samples folder where old samples.
  git clone https://github.com/bumptech/glide.git - this command is not correct ?

**Comment by TWiStErRob** [comment]
You need `git checkout 3.0`, master is 4.0 alpha with refactors.

**Comment by Nikonov** [comment]
Great, thanks
