### ISSUE TITLE
How can I clear chach in the memory?

### ISSUE THREAD

**Issue by siren93** [bumptech/glide#486]
I use the same image path, once I change the image of this path, how can I clear the cache in the memory and reload the new image.

**Comment by TWiStErRob** [comment]
Short question, short answer: [`signature(...)`](http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/DrawableRequestBuilder.html#signature(com.bumptech.glide.load.Key)), for more see [wiki](https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation).

**Comment by sjudd** [comment]
Let us know if you still have questions.
