### ISSUE TITLE
Load image into CustomTarget only if it exists in cache

### ISSUE THREAD

**Issue by jobpav1984** [bumptech/glide#487]
Hi. I want to implement some behavior: 
  I have a flag in my app - "do not load images" and if this flag set  that image can loading only iff it exists in diskcache. Can I implement this? Thanx to all.

**Comment by TWiStErRob** [comment]
We had the same question for memory cache: https://groups.google.com/forum/#!topic/glidelibrary/eBjI1yA0QKw though, disk is quite different.

For disk cache I can think of one way currently: leave all Glide lines as they're now (ignore the fact that user doesn't want to use network) and replace the networking layer to check that flag.

You probably need to write a `DataFetcher<InputStream>` that wraps another `DataFetcher<InputStream>` and only calls through if that flag off (`FlagWrappingFetcher`). You can see an example how to write your own networking layer at [integration/okhttp/src/main/java/.../okhttp](https://github.com/bumptech/glide/tree/3.0/integration/okhttp/src/main/java/com/bumptech/glide/integration/okhttp)

The replace default `register(GlideUrl.class, InputStream.class, new HttpUrlGlideUrlLoader.Factory());` in your GlideModule and create your own fetcher. I would suggest extending `HttpUrlGlideUrlLoader` and overriding `getResourceFetcher -> new FlagWrappingFetcher(return super.getResourceFetcher())`.

**Comment by jobpav1984** [comment]
Thank you, TWiStErRob ! It is work!!!
