### ISSUE TITLE
DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 

### ISSUE THREAD

**Issue by asd3590058** [bumptech/glide#4871]
![image](https://user-images.githubusercontent.com/41050100/185057486-df6a7a0b-abfe-4941-8cd1-fadf5290249d.png)

I don't know why this is causing this。

**Comment by asd3590058** [comment]
glide version 4.13.0

**Comment by sjudd** [comment]
This is probably an issue with the device or OEM decoder

**Comment by TanotiCoder** [comment]
![Screenshot (71)](https://github.com/bumptech/glide/assets/81159555/8a2ee1a1-1e53-446b-9e28-1934801bbd41)
 I have also same problem, what should i do????

**Comment by Itkaushal** [comment]
i have also same problem

**Comment by 02gaurav** [comment]
I am also facing the same problem. Did anyone got any workaround ?
