### ISSUE TITLE
Image zoom maxScale to 1000

### ISSUE THREAD

**Issue by FvApp** [bumptech/glide#4890]
I have successfully included your library into my project by using below code.
```

implementation 'com.github.bumptech.glide:glide:4.13.2'
annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'

```

Right now the image zoom is limited. How to set zoom level to 1000.

The below code is not working.

`ImageView.getZoomer().zoom(100f);`

**Comment by sjudd** [comment]
I'm not sure what getZoomer() is, but I suspect this question is not related to Glide? Glide only loads images, it doesn't deal with zooming.
