### ISSUE TITLE
Unresolved Reference on KSP Build 

### ISSUE THREAD

**Issue by cp-yfukuda** [bumptech/glide#4891]
I followed up on 
https://bumptech.github.io/glide/doc/download-setup.html#maven

```

plugins {
     ...
    id 'com.google.devtools.ksp' version "1.6.21-1.0.5"
}    

```

In the source, I have 

```
@GlideModule
class GlideModule : AppGlideModule() // default App no option changes. 

```
in the app's build.gradle, 

```
depdency {
    ksp 'com.github.bumptech.glide:compiler:4.13.2'
}

```
But build fails saying 
Unresolved reference: GlideApp

Could you please give me advice on what to do?

**Comment by sjudd** [comment]
This is intended, see the note here: https://bumptech.github.io/glide/doc/download-setup.html#kotlin---ksp In particular GlideApp is part of the "deprecated generated API". 

Assuming you're a normal user, you can simply replace GlideApp with the normal Glide class and everything should work.

I'll try and improve the documentation to make this clearer. Thanks for trying the KSP integration out early!

**Comment by sjudd** [comment]
Added more detail in 28b7656cecf24f4e126e8669431c5ec0b9cb4e42
