### ISSUE TITLE
Question: How can I transform the error drawable?

### ISSUE THREAD

**Issue by kevinvanmierlo** [bumptech/glide#490]
I'm making an app which uses blurred backgrounds. I use the `.transform()` method for that. But if the loading failed I want the `.transform()` method to also apply to the error drawable so my background will always be blurred. Is this possible?

P.S. This library is great! I recently discovered it and it has so much customization. Exactly what I'm looking for!

**Comment by TWiStErRob** [comment]
Similar to #317, which ended up WontFix.
I would suggest to create a separate pre-blurred drawable and use that.

BTW, why do you need to display errors nicely? I don't think relying on error is a good idea from UX perspective. Why is it "normal" for a load to fail in your app?

**Comment by kevinvanmierlo** [comment]
@TWiStErRob In the webservice I get a url to another image. In case the url is wrong I still want a blurred background. It doesn't happen very often, but it can happen. What I'm doing now is load the error drawable with the transformation in the error callback. I didn't think of that before I opened this question. Maybe that would be sufficient. I'll close it. Thanks for the quick response!
