### ISSUE TITLE
Index annotation cannot be resolved on generated code by ksp

### ISSUE THREAD

**Issue by ganadist** [bumptech/glide#4911]
**Glide Version**: 4.14.1  

**Integration libraries**: N/A

**Device/Android Version**: N/A

**Issue details / Repro steps / Use case background**: 
Generated codes by KSP cannot be compiled after setup project as [ksp guideline](https://bumptech.github.io/glide/doc/download-setup.html#kotlin---ksp)

* generated codes by ksp
 ```
 package com.bumptech.glide.`annotation`.ksp

 @Index([
 "class1",
 "class2",
 ])
  public class GlideIndexer_GlideModule_Class1_Class2Module { 
 ```
`@Index` annotation is under `com.bumptech.glide.annotation.ksp` package, but kotlin compiler cannot reference it.
After add `compileOnly` configuration on dependency block, compile can be succeeded.

```
dependencies {
    ksp 'com.github.bumptech.glide:ksp:4.14.1'
    compileOnly 'com.github.bumptech.glide:ksp:4.14.1'
}
```

**Comment by ganadist** [comment]
Hello.
Here is a sample project to reproduce compile issue.

```
$ git clone https://github.com/ganadist/VersionCodeDemo -b glide-ksp
$ cd VersionCodeDemo
$ ./gradlew :lib:glide:assemble
...
> Task :lib:glide:compileReleaseKotlin FAILED
e: lib/glide/build/generated/ksp/release/kotlin/com/bumptech/glide/annotation/ksp/GlideIndexer_GlideModule_com_example_mylib_LibraryModule.kt: (3, 2): Unresolved reference: Index


$  ./gradlew :lib:glide:assemble -PuseKsp=false 
...
> Task :lib:glide:kaptReleaseKotlin
Note: [2] Wrote GeneratedAppGlideModule with: [com.example.mylib.LibraryModule]

> Task :lib:glide:compileReleaseKotlin
> Task :lib:glide:extractReleaseAnnotations
> Task :lib:glide:compileReleaseJavaWithJavac
```

**Comment by Patek0000** [comment]
> 
> 
> 
> 
> **Glide Version**: 4.14.1  
> 
> 
> **Integration libraries**: N/A
> 
> 
> **Device/Android Version**: N/A
> 
> 
> **Issue details / Repro steps / Use case background**: 
> Generated codes by KSP cannot be compiled after setup project as [ksp guideline](https://bumptech.github.io/glide/doc/download-setup.html#kotlin---ksp)
> 
> * generated codes by ksp
>  ```
>  package com.bumptech.glide.`annotation`.ksp
> 
>  @Index([
>  "class1",
>  "class2",
>  ])
>   public class GlideIndexer_GlideModule_Class1_Class2Module { 
>  ```
> `@Index` annotation is under `com.bumptech.glide.annotation.ksp` package, but kotlin compiler cannot reference it.
> After add `compileOnly` configuration on dependency block, compile can be succeeded.
> 
> ```
> dependencies {
>     ksp 'com.github.bumptech.glide:ksp:4.14.1'
>     compileOnly 'com.github.bumptech.glide:ksp:4.14.1'
> }
> ```
> 
> 
> 
>
