### ISSUE TITLE
error when resize to little size

### ISSUE THREAD

**Issue by mohammadmahdavim** [bumptech/glide#4915]
hi
I want resize image to (w=20 & h=20) but not resize and return binary code
While there is no problem for higher sizes example(w=300 & h=300)

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues. There's not enough information to tell what might be happening here.

You can try to inspect the downsampler logs: `adb shell setprop log.tag.Downsampler VERBOSE`
