### ISSUE TITLE
Compose GlideImage does not repaint Image when model changed

### ISSUE THREAD

**Issue by vborodinramit** [bumptech/glide#4916]
**Glide Version**: Glide 4.14.1, glide:compose:1.0.0-alpha.0

**Issue details / Repro steps / Use case background**: 

for image selection i use:
implementation 'com.github.akshaaatt:Cropper:1.00'

```
@Composable
fun SelectAvatar() {
    var avatarUri by rememberSaveable { mutableStateOf<Uri?>(null) }
    val selectAvatarLauncher = rememberLauncherForActivityResult(CropImageContract()) { result ->
        if (result.isSuccessful) {
            avatarUri = result.uriContent
        }
    }

    fun selectAvatar() {
        selectAvatarLauncher.launch(options {})
    }

    Column{
        TextButton(onClick = ::selectAvatar) {Text(text="Select Avatar")}
        if (avatarUri != null)
            GlideImage(model = avatarUri, modifier = Modifier.size(100.dp), contentDescription = "")
    }
}

```
When i click button first time and select image - it appears correctly, but when i click button second time and select new image GlideImage does not redraw itself and i see old picture.
I checked with Logs - avatarUri updated correctly and Compose recomposed.

**Comment by tomasziwaszko** [comment]
It has to be something wrong with using "remember" inside a GlideImage

**Comment by sjudd** [comment]
Yeah in particular, the model is supposed to be part of RequestBuilder, but it's not included in RequestBuilder's equals/hashcode method.

In fact a few things in RequestBuilder are not included and it's kind of unsafe by default because RequestBuilder inherits from a class that does implement equals/hashcode.
