### ISSUE TITLE
Include dev/versioning instructions in Transformation docs

### ISSUE THREAD

**Issue by jmrboosties** [bumptech/glide#492]
See this StackOverflow question: http://stackoverflow.com/questions/30768505/bitmaptransformation-in-the-glide-library-not-working-as-expected

I'm trying to create a custom transformation, but when I place a breakline in the Transformation class's `transform` method, I can see that it is never called.

Below is my code:

	private static class CustomTransformation extends BitmapTransformation {

		private Context aContext;

		public CustomTransformation(Context context) {
			super(context);
			aContext = context;
		}

		@Override
		protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
			return bitmapChanger(toTransform, 1080, (int) aContext.getResources().getDimension(R.dimen.big_image));
		}

		@Override
		public String getId() {
			return "some_id";
		}

	}

	private static Bitmap bitmapChanger(Bitmap bitmap, int desiredWidth, int desiredHeight) {
		float originalWidth = bitmap.getWidth();
		float originalHeight = bitmap.getHeight();

		float scaleX = desiredWidth / originalWidth;
		float scaleY = desiredHeight / originalHeight;

		//Use the larger of the two scales to maintain aspect ratio
		float scale = Math.max(scaleX, scaleY);

		Matrix matrix = new Matrix();

		matrix.postScale(scale, scale);

		//If the scaleY is greater, we need to center the image
		if(scaleX < scaleY) {
			float tx = (scale * originalWidth - desiredWidth) / 2f;
			matrix.postTranslate(-tx, 0f);
		}

		return Bitmap.createBitmap(bitmap, 0, 0, (int) originalWidth, (int) originalHeight, matrix, true);
	}

I've tried initiating Glide in two ways:

    Glide.with(this).load(url).asBitmap().transform(new CustomTransformation(this)).into(imageView);

and

    Glide.with(this).load(url).bitmapTransform(new CustomTransformation(this)).into(imageView);

But neither work. Any ideas?

**Comment by sjudd** [comment]
And this is using Glide 3.6?

**Comment by TWiStErRob** [comment]
I'm 90% sure it's RESULT cached from an earlier run and that's why it's not regenerating your bitmap with transformation.
Add `skipMemoryCache(true)` and `diskCacheStrategy(NONE)` while developing the transformation.

**Comment by sjudd** [comment]
I tried this on Glide 3.6, and I see transform being called.

As @TWiStErRob just mentioned as I was typing this :), I'd imagine you're debugging and using the same model and the same transformation id. Once a transformation has been applied once, Glide will look for that transformed image in cache. If it finds it, it will just decode straight from cache and will not apply the transformation again.

**Comment by jesseridgway** [comment]
That makes sense. I'll try adding those flags in dev and trying again tomorrow. Thanks!

And just FYI yes I'm running 3.6.0

**Comment by jmrboosties** [comment]
That makes sense. I'll try adding those flags in dev and trying again tomorrow. Thanks!

And just FYI yes I'm running 3.6.0

**Comment by TWiStErRob** [comment]
@sjudd on a related note: imagine someone has a custom transform and they change the code between releases, how would Glide know to clear the cache? I think a suggestion should be added to Transformation.getId method to include a version number whenever you make significant changes to it.
And maybe a tip for development like the above.

**Comment by jmrboosties** [comment]
Yep, the method is being called each time now. I think making it clear that the transformations cache like you said would be a helpful tip to include, I'm sure I'm not the only one who will run into this.
