### ISSUE TITLE
[Question] Leave the image to its actual size, don't scale it.

### ISSUE THREAD

**Issue by opcodewriter** [bumptech/glide#4931]
Is there a way to setup Glide to load the image into an `ImageView` **without up or down scaling the image**, just leave the image as it is? (like how **[ScaleType.CENTER](https://developer.android.com/reference/android/widget/ImageView.ScaleType)** works).

```
<RelativeLayout ...>
     <ImageView 
          android:id="@+id/imageView1"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          android:scaleType="center"  />
</RelativeLayout>
```

Calling  `Glide.with(this).load("url").into(imageView1)` draws the image **filling** the `ImageView`. It **ignores** `android:scaleType="center`.

Calling  `Glide.with(this).load("url").centerInside().into(imageView1)` draws the image centered, **but it's scaled down**! (I checked by having another ImageView loading the same image as a resource).

**Comment by sjudd** [comment]
You can use [`.dontTransform()`](https://bumptech.github.io/glide/javadocs/4140/library/com.bumptech.glide.request/-base-request-options/dont-transform.html). Scaling down is often a good thing because it saves memory usage and (depending on your disk cache strategy) disk size.

**Comment by opcodewriter** [comment]
With the same AXML above, I tried `dontTransform()`, it does not work either, the image is **filling** the view:

```
Glide.with(this).load("https://....").dontTransform().into(imageView1);
```

Could you please share what is the exact code I need to call? 

> Scaling down is often a good thing because it saves memory usage and (depending on your disk cache strategy) disk size.

Thank you, I'm aware of this, but I really need this behavior in order to preserve the image.

**Comment by opcodewriter** [comment]
@sjudd Do you mind share a concrete example please, just using `dontTransform()` doesn't work.
