### ISSUE TITLE
GeneratedAppGlideModuleImpl is implemented incorrectly

### ISSUE THREAD

**Issue by SumitSoni-001** [bumptech/glide#4947]
Error :- 
java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.

![image](https://user-images.githubusercontent.com/73877619/200327068-7d0a7a10-cf27-4923-a1ac-cc68b24c387e.png)

**Comment by Kanbinsi** [comment]
thanks for this suggestion, i will try again, give me suggestions on [color tunnel](https://colortunnel.io) game if you have time

**Comment by sjudd** [comment]
please fill out the issue template when filing new issues.
