### ISSUE TITLE
Synchronously get Glide cache image

### ISSUE THREAD

**Issue by pinguo-fandong** [bumptech/glide#495]
I have a  problem,in my app,There is a need for sharing a picture,how do I know the Corresponding cache file? for example:
```
 Glide.with(CCApplication.gContext)
                    .load(mPhoto.getEtag().getPicUrl())
                    .asBitmap()
                    .into(new SimpleTarget<Bitmap>(){
                        @Override
                        public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                            builder.setBitmap(resource);
                        }
                    });
            builder.setSummary("This is summary");
            builder.setTargetUrl("http://www.google.com");
            builder.setTitle("My Picture");
```
but when I get the resource,this method has already return,is there a way to synchronously get the resource?

**Comment by TWiStErRob** [comment]
As for synchronicity: Did you consider creating and setting up (and creating) the `builder` in `onResourceReady` instead of "outside"?

Also check out #459 and #478, the key is usually `downloadOnly`.

**Comment by sjudd** [comment]
Let us know if we can help further.

**Comment by pinguo-fandong** [comment]
thanks!
