### ISSUE TITLE
[Question] Wonder the mechanism of bitmap reusing.

### ISSUE THREAD

**Issue by lenhatquang97** [bumptech/glide#4955]
I wonder how Glide reuses bitmap when loading multiple images? What is the main part of source code talking about bitmap reuse? 
Thanks in advance!

**Comment by sjudd** [comment]
https://developer.android.com/reference/android/graphics/Bitmap#reconfigure(int,%20int,%20android.graphics.Bitmap.Config) is the primary mechanism. Unfortunately it's kind of spread across Glide's whole codebase. We reference count requests to guess when Bitmaps can be re-used and check the BitmapPool frequently in place of allocating Bitmaps directly.
