### ISSUE TITLE
Getting frames from video don't return anything but the very first frame

### ISSUE THREAD

**Issue by jgads** [bumptech/glide#496]
Run this code you gave us here:
 
https://gist.github.com/dabluck/36aa99f9d31eb2ec4684
 
http://stackoverflow.com/questions/30766885/glide-load-single-frame-from-video-at-specific-time/30769399#30769399
 
Then run it again for an arbitrary frame that isn’t 200. It comes back with a cache hit always (regardless of frame). This is obvious because the getId strings in those decoders are always the same. However, implementing BitmapDecoder yourself and overriding getId to account for the frame still doesn’t fix it, because the hashing function does not rely on the getId function you implement. I maybe think the getID function in ImageVideoBitmapDecoder should rely on the getId function of its members, that way you could make this functionality work for our use case.

**Comment by jgads** [comment]
Switching off Memory and Disk caching will return different frames, but then you lose the benefits of Glide!

**Comment by sjudd** [comment]
Good catch! That's definitely broken.

You can work around this by defining your own equivalent of ImageVideoBitmapDecoder and passing it in to BitmapRequestBuilder. 

The good new is this is fixed and generally much easier to deal with in 4.0.

If you want to file a separate bug about your suggestion to use OPTION_CLOSEST, that we could still do or at least expose in 4.0

**Comment by jgads** [comment]
Sounds good! Is there a repo for 4.0 to try out?

**Comment by TWiStErRob** [comment]
It's the current `master`, see https://github.com/bumptech/glide/wiki/Snapshots

**Comment by jgads** [comment]
There doesn't seem to be a '.load' method in the Glide builder for 4.0?

**Comment by sjudd** [comment]
The syntax has changed (v4 is not backwards compatible). Check out the sample apps for example usage, and keep in mind it's pre-release so there may be bugs and some APIs will change.
