### ISSUE TITLE
upfile-drcn.platform.hicloud.com has insecure cipher suites

### ISSUE THREAD

**Issue by tiwin-lm** [bumptech/glide#4976]
**Glide Version**:4.13.0

**Integration libraries**:no

**Device/Android Version**:all huawei device

**Issue details / Repro steps / Use case background**: 
use tcpdump to get net packages, use wireshark to analyze the data, find one issue, the upfile-drcn.platform.hicloud.com has insecure cipher suites. details:
java.net.Socket.connect
com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:93)
com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58)
com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
java.lang.Thread.run(Thread.java:930)
com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:372)

 insecure cipher suites:
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384

TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
This is an OEM issue
