### ISSUE TITLE
Flutter Could not resolve com.github.yalantis:ucrop:2.2.8.

### ISSUE THREAD

**Issue by Wagkart** [bumptech/glide#4978]
I have been getting error that dependency couldnt be resolved for ucrop:2.2.8 while building **flutter apk**
I added   maven { url = uri("https://www.jitpack.io" ) } as per all the theads but it didnt work for me
It was working without jitpack dependency 3 days ago
build is working from vsCode but not from githib actions

Any help is appreciated here
Below id the build.gradle

**buildscript {
    ext.kotlin_version = '1.7.20'
    repositories {
        google()
        mavenCentral()
        

    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.14'
        classpath 'com.android.support:multidex:1.0.3'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://www.jitpack.io" ) }
     
    }
}**

**Comment by sjudd** [comment]
I think you might have the wrong repository? This doesn't seem to involve Glide
