### ISSUE TITLE
 Type com.bumptech.glide.GeneratedRequestManagerFactory is defined multiple times:

### ISSUE THREAD

**Issue by ranshine** [bumptech/glide#4984]
I am running RN app with native android code, it has Glide dependencies and it is running fine in debug mode but when i try to release the build it is throwing Dex error.

    implementation 'com.github.bumptech.glide:glide:4.10.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'
    kapt 'com.github.bumptech.glide:compiler:4.10.0'

```
  @GlideModule
class GlideAppModule : AppGlideModule() {
    override fun applyOptions(context: Context, builder: GlideBuilder) {
        super.applyOptions(context, builder)
        builder.apply { RequestOptions().diskCacheStrategy(DiskCacheStrategy.ALL) }
    }
}
```

```
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
```

Execution failed for task ':app:mergeDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.bumptech.glide.GeneratedRequestManagerFactory is defined multiple times: /Users/sgorle/merchant-native-mobile-app/android/app/build/intermediates/project_dex_archive/release/out/com/bumptech/glide/GeneratedRequestManagerFactory.dex, /Users/sgorle/merchant-native-mobile-app/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes2.dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by sjudd** [comment]
It looks like a library you depend on is incorrectly including an AppGlideModule: `, /Users/sgorle/merchant-native-mobile-app/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes2.dex`

They should review https://bumptech.github.io/glide/doc/configuration.html#avoid-appglidemodule-in-libraries
