### ISSUE TITLE
Gallery sample doesn't distinguish between videos and images

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#500]
Although we load both types, there isn't any way from looking at an image to tell whether it's a video still or an image. We should add a play icon or something similar to the video stills.

**Comment by sjudd** [comment]
We can display Android's play button: android.R.drawable.ic_media_play

**Comment by federicoiosue** [comment]
Could be really useful to have a way to use custom defined resource (at least) and position to perform something like this (a kind of watermark)

![device-2015-06-19-232331 resized](https://cloud.githubusercontent.com/assets/487104/8263398/65e8f2c8-16da-11e5-9160-817979797bf9.png)

**Comment by TWiStErRob** [comment]
The most reusable would be a watermark transform that puts another bitmap or drawable at the specified position (top left bottom right, like css's absolute positioning). @sjudd Is there an appendTransform and prependTransform in 4.0?

**Comment by sjudd** [comment]
@TWiStErRob no, there's no append or prepend transform methods. You can however use [``MultiTransformation``][1].

[1]: http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/load/MultiTransformation.html
