### ISSUE TITLE
Task :annotation:compiler:proguard FAILED

### ISSUE THREAD

**Issue by jiashie** [bumptech/glide#5027]
```bash
git clone https://github.com/bumptech/glide.git
cd glide
./gradlew jar
```

but build failed !
too many warnings occured.
>Warning: com.bumptech.glide.annotation.Excludes: can't find superclass or interface java.lang.Object
Warning: com.bumptech.glide.annotation.Excludes: can't find superclass or interface java.lang.annotation.Annotation
Warning: com.bumptech.glide.annotation.GlideExtension: can't find superclass or interface java.lang.Object
Warning: there were 69813 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedclass)
Warning: there were 221 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedprogramclassmember)

> Task :annotation:compiler:proguard FAILED
79 actionable tasks: 2 executed, 77 up-to-date

please check the attachment to get full log.

[builderror.txt](https://github.com/bumptech/glide/files/10762727/builderror.txt)

**Comment by sjudd** [comment]
I don't think we support the jar task tag. If you just want to build, then you can do ./gradlew build --parallel. Glide cannot be trivially built into a jar
