### ISSUE TITLE
Next version of glide compose integration

### ISSUE THREAD

**Issue by Forcharc** [bumptech/glide#5028]
When is the next version of glide compose integration going to be out?
It's been very long time since the last version. And you have many new improvements in the snapshots channel. 
Why aren't you releasing them yet?
Using snapshot versions of glide compose is not viable, because it uses snapshot versions of glide itself under the hood. I want to at least be sure in correctness of glide. 
It's been so much time since the development of compose and still it's so hard to use it with Glide.

**Comment by sjudd** [comment]
https://github.com/bumptech/glide/releases/tag/v4.15.0
