### ISSUE TITLE
UI Test not running when we applying glide:compose:glide:compose:1.0.0-alpha.1

### ISSUE THREAD

**Issue by Joseph-Shim** [bumptech/glide#5035]
When we applying glide:compose, we can't run UI Test with AndroidJunit4. there are long time to take tests.

Finally we got time out in android studio.
Timed out waiting for process (xxx) to appear on Galaxy_Nexus_API_33 [emulator-5554].

Could you fix this issues?

**Comment by sjudd** [comment]
Hmm there's not really enough detail to debug anything. Glide has emulator tests for compose, do those run on our device? It's not obvious how a library would impact whether or not processes are able to connect from Android Studio

**Comment by burhanrashid52** [comment]
I have the same issue as well. As soon I add glide compose dependency the espresso test is stuck and not running. If I remove glide compose it works
