### ISSUE TITLE
The class GeneratedAppGlideModuleImpl generated by ksp does not register the LibraryGlideModule subclass.

### ISSUE THREAD

**Issue by lyh8577** [bumptech/glide#5043]
**Glide Version**:
```
dependencies {
    implementation("com.github.bumptech.glide:glide:4.15.0")
    ksp("com.github.bumptech.glide:ksp:4.15.0")
    implementation("com.github.bumptech.glide:okhttp3-integration:4.15.0")
}
```

**Integration libraries**:
```
plugins {
    id("org.jetbrains.kotlin.android") version "1.8.10" apply false
    id("com.google.devtools.ksp") version "1.8.10-1.0.9" apply false
}
```

**Device/Android Version**:
Android Studio Electric Eel | 2022.1.1 Patch 2

**Issue details / Repro steps / Use case background**: 
Make project，then view the generated classes:  GeneratedAppGlideModuleImpl

**Kapt generated class**
```java
final class GeneratedAppGlideModuleImpl extends GeneratedAppGlideModule {
  private final KaptAppGlideModule appGlideModule;

  public GeneratedAppGlideModuleImpl(Context context) {
    appGlideModule = new KaptAppGlideModule();
    if (Log.isLoggable("Glide", Log.DEBUG)) {
      Log.d("Glide", "Discovered AppGlideModule from annotation: com.example.kaptdemo.KaptAppGlideModule");
      Log.d("Glide", "Discovered LibraryGlideModule from annotation: com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule");
    }
  }

  @Override
  public void applyOptions(@NonNull Context context, @NonNull GlideBuilder builder) {
    appGlideModule.applyOptions(context, builder);
  }

  @Override
  public void registerComponents(@NonNull Context context, @NonNull Glide glide,
      @NonNull Registry registry) {
    new OkHttpLibraryGlideModule().registerComponents(context, glide, registry);
    appGlideModule.registerComponents(context, glide, registry);
  }

  @Override
  public boolean isManifestParsingEnabled() {
    return appGlideModule.isManifestParsingEnabled();
  }

  @Override
  @NonNull
  public Set<Class<?>> getExcludedModuleClasses() {
    return Collections.emptySet();
  }

  @Override
  @NonNull
  GeneratedRequestManagerFactory getRequestManagerFactory() {
    return new GeneratedRequestManagerFactory();
  }
}
```
**Ksp generated class**
```kotlin
internal class [GlideDemo.zip](https://github.com/bumptech/glide/files/10907488/GlideDemo.zip)(
  @Suppress("UNUSED_PARAMETER")
  context: Context,
) : GeneratedAppGlideModule() {
  private val appGlideModule: KspAppGlideModule
  init {
    appGlideModule = KspAppGlideModule()
  }

  public override fun registerComponents(
    context: Context,
    glide: Glide,
    registry: Registry,
  ): Unit {
    appGlideModule.registerComponents(context, glide, registry)
  }

  public override fun applyOptions(context: Context, builder: GlideBuilder): Unit {
    appGlideModule.applyOptions(context, builder)
  }

  public override fun isManifestParsingEnabled(): Boolean = false
}
```
[GlideDemo.zip](https://github.com/bumptech/glide/files/10907496/GlideDemo.zip)

**Comment by sjudd** [comment]
Any chance you could push the project to a repo on Github rather than attaching a zip file?

**Comment by lyh8577** [comment]
@sjudd https://github.com/lyh8577/GlideDemo-issue-5043

**Comment by sjudd** [comment]
Welp that's a pretty significant bug in the ksp library - namely it doesn't read library glide modules compiled with the java annotation processor. All library modules are compiled with the java annotation processor, so effectively ksp does not work with library glide modules.

I'll do a dot release to fix this in the short term.

Really there's no good reason why we need a separate Index annotation just for ksp, it really ought to just use the existing Java one. I'll make that as a separate follow-up change.

**Comment by sjudd** [comment]
Also thank you for filing the issue and attaching the sample app. I appreciate the report.

**Comment by sjudd** [comment]
Fixed and released in 4.15.1, tests added in 9fd7a84dfc92602e3dfc1c0ca741a87987558827

**Comment by projectdelta6** [comment]
Does the library also need to update?
I'm using `https://github.com/qoqa/glide-svg` to render SVGs from URLs, but after updating my project to use KSP the SVGs no linger work at all?
I'm using Glide v4.15.1

**Comment by javad-vovin** [comment]
There is a problem with [9fd7a84](https://github.com/bumptech/glide/commit/9fd7a84dfc92602e3dfc1c0ca741a87987558827) and volley-integration or okhttp-integration.

`Cause: this and base files have different roots: C:\Users\JavadVovin\.gradle\caches\9.2.1\transforms\fc82771937b003c921f173017a5d82d4\workspace\transformed\volley-integration-4.15.1-api.jar!\com\bumptech\glide\annotation\compiler\GlideIndexer_GlideModule_com_bumptech_glide_integration_volley_VolleyLibraryGlideModule.class and D:\Workspace\GlideIndex\app.`

The latest glide (5.0.5) is having the same issue.
This is a sample project with the problem. [glide-index](https://github.com/javad-vovin/glide-index)
