### ISSUE TITLE
Placeholder with animation drawable not animating

### ISSUE THREAD

**Issue by jam0cam** [bumptech/glide#505]
According to the docs, it is possible to do this: 

 Glide.with(myFragment)
        .load(url)
        .centerCrop()
        .placeholder(R.drawable.loading_spinner)
        .crossFade()
        .into(myImageView);

I've defined my loading_spinner as so, and it's not showing any animation. Any ideas?

    <animation-list xmlns:android="http://schemas.android.com/apk/res/android" android:oneshot="false">
      <item android:drawable="@drawable/spinner_1" android:duration="100" />
      <item android:drawable="@drawable/spinner_2" android:duration="100" />
      <item android:drawable="@drawable/spinner_3" android:duration="100" />
      <item android:drawable="@drawable/spinner_4" android:duration="100" />
      <item android:drawable="@drawable/spinner_5" android:duration="100" />
      <item android:drawable="@drawable/spinner_6" android:duration="100" />
      <item android:drawable="@drawable/spinner_7" android:duration="100" />
      <item android:drawable="@drawable/spinner_8" android:duration="100" />
    </animation-list>

**Comment by TWiStErRob** [comment]
Does it rotate if you just do:
```java
myImageView.setImageResource(R.drawable.loading_spinner)
```
without Glide?

(Sorry I couldn't look up my references and link them.)
As far as I remember it doesn't, and if I remembered correctly, then try to look for "how to make a drawable animate in an ImageView". I remember something involving ObjectAnimator and some level property on ImageView. You may need to specify a custom target (extending `*ImageViewTarget`) to start/stop the animation at the correct times. Or if you want simpler: start before `Glide.load` and stop in a `.listener()`.

**Comment by jam0cam** [comment]
you're right, it doesn't rotate either if I just do:

    myImageView.setImageResource(R.drawable.loading_spinner)


What should my loading_spinner look like for it to work with the example code?


    .placeholder(R.drawable.loading_spinner)

**Comment by TWiStErRob** [comment]
I think your xml is correct, though I didn't really go deep with animations.

Here's what I meant, when I said "try to look for >>how to make a drawable animate in an ImageView<<":

```java
// http://stackoverflow.com/questions/4651618/is-it-possible-to-have-an-animated-drawable
final ObjectAnimator anim = ObjectAnimator.ofInt(myImageVew, "ImageLevel", 0, MAX_LEVEL);
anim.setRepeatCount(ObjectAnimator.INFINITE);
anim.start();

// your loading code from above
Glide.with(myFragment)
        .load(url)
        .centerCrop()
        .placeholder(R.drawable.loading_spinner)
        .crossFade()
         // new listener to stop unnecessary animation when the placeholder is not visible any more
        .listener(new RequestListener<GlideUrl, GlideDrawable>() {
            @Override
            public boolean onException(Exception e, GlideUrl model,
                                       Target<GlideDrawable> target, boolean isFirstResource) {
                anim.cancel();
                return false;
            }

            @Override
            public boolean onResourceReady(GlideDrawable resource, GlideUrl model,
                                           Target<GlideDrawable> target,
                                           boolean isFromMemoryCache, boolean isFirstResource) {
                anim.cancel();
                return false;
            }
        })
        .into(myImageView);
```

**Comment by jam0cam** [comment]
Thanks. I ended up using another imageview containing the animation as a background resource, animate that, before Glide.load, and then stopping the animation & hiding the imageview as you did above.

**Comment by sjudd** [comment]
Glad this is resolved, sorry the sample is misleading (there isn't a built in spinning drawable)!

**Comment by jam0cam** [comment]
Thanks! If you could copy what Picasso does, that'll be great. When providing the above loading_spinner to Picasso, it does the animated drawable automatically.

**Comment by abhinavkorpal** [comment]
How to stop animation once started, I have to stop it

**Comment by TWiStErRob** [comment]
@abhinavkorpal
If you used the above code, then `anim.cancel()` should do it any time.
If you didn't, then it depends on how you started it in the first place.

**Comment by abhinavkorpal** [comment]
I'm using this:

 imageView = (ImageView) findViewById(R.id.imageview);

        GlideDrawableImageViewTarget imageViewTarget = new GlideDrawableImageViewTarget(imageView);
        Glide.with(this)
                .load(R.raw.mint_celebration_popup_animation_v1_empty_crop)
                .dontTransform()
                .dontAnimate()
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(imageViewTarget);

**Comment by TWiStErRob** [comment]
Then it is a GIF file and not a drawable resource, and has nothing to do with this issue, you're not even using a placeholder. See https://github.com/bumptech/glide/issues/1028#issuecomment-192481349 for temporary pause; or reload the same raw file with `asBitmap()` to stop it permanently on the first frame. You can search for some combination of `GifDrawable`, `Animatable`, `start`/`stop`/`isRunning` keywords to find more similar issues.

**Comment by abhinavkorpal** [comment]
Don't work

**Comment by TWiStErRob** [comment]
Can you please open a new issue detailing what you do, what experience and what you expect?

**Comment by abhinavkorpal** [comment]
I have one GIF File I have to play It once after which gif  which I'm using on Imageview get stop: 
My codes:

imageView = (ImageView) findViewById(R.id.imageview);



        GlideDrawableImageViewTarget imageViewTarget = new GlideDrawableImageViewTarget(imageView);

        Glide.with(this)
                .load(R.raw.mint_celebration_popup_animation_v1_empty_crop)
                .dontTransform()
                .dontAnimate()
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(imageView);

**Comment by TWiStErRob** [comment]
Take a look at [#446](https://github.com/bumptech/glide/%69ssues/446) and [#860](https://github.com/bumptech/glide/%69ssues/860).

**Comment by abhinavkorpal** [comment]
Not working Sorry

**Comment by TWiStErRob** [comment]
Others have made it work in the linked issues, but you're not providing any info other than "it doesn't work". My last suggestion is try to use a library that is made for fine GIF control: https://github.com/koral--/android-gif-drawable
In the future if you want help, please open a new issue and describe your usage/problems *in detail*.

**Comment by abhinavkorpal** [comment]
Library Issue some method not working and may be version issue

**Comment by abhinavkorpal** [comment]
Error on OnException can you please help me.

**Comment by abhinavkorpal** [comment]
Now Its working Thanks a lot !!!!

**Comment by abhinavkorpal** [comment]
How to stop animation after first start....full code just copy and paste

public class CustomDialog extends Activity {

    ImageView imageView;
    GifDrawable gifDrawable;
    Animation.AnimationListener animationListener;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.customdialog);


imageView = (ImageView) findViewById(R.id.imageview);
       
        GlideDrawableImageViewTarget imageViewTarget = new GlideDrawableImageViewTarget(imageView);

        Glide.with(this)
                .load(R.raw.mint_celebration_popup_animation_v1_empty_crop)
                .dontTransform()
                .dontAnimate()
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .listener(new RequestListener<Integer, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, Integer model, Target<GlideDrawable> target, boolean isFirstResource) {

                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, Integer model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        Handler handler = new Handler();
                        if (resource instanceof GifDrawable) {
                            gifDrawable = (GifDrawable) resource;

                            int duration = 0;
                            GifDecoder decoder = gifDrawable.getDecoder();
                            for (int i = 0; i < gifDrawable.getFrameCount(); i++) {
                                duration += decoder.getDelay(i);
                            }
                            handler.postDelayed(new Runnable() {
                                @Override
                                public void run() {
//                                    animationListener.onAnimationCompleted();
//                                    cancelGifAnimation();
                                }
                            }, duration);

//                            setGifViewVisable(true);
                        } else {
                            handler.postDelayed(new Runnable() {
                                @Override
                                public void run() {
//                                    animationListener.onAnimationCompleted();
//                                    cancelGifAnimation();
                                }
                            }, TimeUnit.SECONDS.toMillis(2));
                        }
                        return false;
                    }
                }).into(new GlideDrawableImageViewTarget(imageView, 1));

**Comment by TWiStErRob** [comment]
@abhinavkorpal that's almost a 1:1 copy of https://github.com/bumptech/glide/issues/860#issuecomment-176587005. I just noticed that what you want may be as simple as `....into(new GlideDrawableImageViewTarget(imageView, 1))`, because you have no code in the posted `run` methods.

**Comment by abhinavkorpal** [comment]
Yes I needed as Simple as....But thanks. Any idea in my codes to make it more simple. If possible please tell.

**Comment by TWiStErRob** [comment]
@abhinavkorpal just remove the listener.

**Comment by abhinavkorpal** [comment]
@TWiStErRob  I already test that via removing one my one single code, But no.

**Comment by webserveis** [comment]
When found code for drawable.loading_spinner.xml ?

**Comment by TWiStErRob** [comment]
@webserveis It's in the opening post...
