### ISSUE TITLE
Configuration with name 'default' not found

### ISSUE THREAD

**Issue by huyduongtu** [bumptech/glide#506]
I downloaded and opened Glide library 's source code using both Android Studio and Intellij IDEA 14. It shows the error like this:
```
D:\AndroidStudioProjects\glide-master\glide\build.gradle
Error:(5, 0) Configuration with name 'default' not found.
```
Please tell me how to fix this problem? Thanks

**Comment by TWiStErRob** [comment]
Do you want to build the pre-release 4.0 (master) or the latest stable 3.6.0 (branch called 3.0)?

**Comment by huyduongtu** [comment]
The version I download is 3.6.0. The version is not matter to me. I just wanna build, run this library to understand how It works. 
Please tell me how to build it.

**Comment by sjudd** [comment]
You need to follow all of the instructions in the [Readme][1], notably including:

```
git submodule init
git submodule update
```

[1]: https://github.com/bumptech/glide#build

**Comment by TWiStErRob** [comment]
Yikes, that's a really bad error message... I checked the gradle log and only the 5th "Caused by" hints at the core of the problem:

> Cannot evaluate module disklrucache : Configuration with name 'default' not found.

**Comment by dreamlivemeng** [comment]
Hello, can you tell me how you can solve this problem? I also met the same mistake.

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/issues/506#issuecomment-113926977
