### ISSUE TITLE
Size multiplayer is changing Target.SIZE_ORIGINAL constant

### ISSUE THREAD

**Issue by jszczygiel** [bumptech/glide#508]
**Glide Version/Integration library (if any)**: 3.6.0 , okhttp 2.0.0
**Device/Android Version**: all
**Issue details/Repro steps**: 
1. Run glide with below loading line
2. BitmapTransformation is getting outWidth/outHeight, which is Integer.MIN_VALUE times sizeMultiplayer. Because of that outWidth/outHeight check is failing and throws IllegalArgumentException.

**Glide load line**:

``` java
Glide.with(context).transform(new BlurTransformation(localContext)).sizeMultiplier(sizeMultiplier).into(imageView);
```

where BlurTransformation is blur transformation extending BitmapTransformation.

**Comment by sjudd** [comment]
We shouldn't crash with that particular exception, but I'm inclined to say these is still an unsupported option set that should cause an exception to be thrown (preferably with a better error message).

Were you intentionally setting both SIZE_ORIGINAL and a size multiplier? If so, what were you expecting to happen? Maybe there's a use case here I'm not thinking of.

**Comment by TWiStErRob** [comment]
Is `imageView`'s size wrap_content? That's a good place where `SIZE_ORIGINAL` can be coming from.

**Comment by jszczygiel** [comment]
@sjudd I was setting only size multiplayer. 

@TWiStErRob I am loading image into SimpleTarget. 

In that case I was expecting default size of downloaded image to be cut down by size multiplayer.

**Comment by nevir** [comment]
Running into this as well

**Comment by sjudd** [comment]
Obsolete at leaset in v4.
