### ISSUE TITLE
Hi, The 4.15.0 version can be built successfully, but the 4.15.1 version fails to build, it seems that the dependency cannot be found

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [bumptech/glide#5080]
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform disklrucache-4.15.1.jar (com.github.bumptech.glide:disklrucache:4.15.1) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find disklrucache-4.15.1.jar (com.github.bumptech.glide:disklrucache:4.15.1).
        Searched in the following locations:
            https://maven.aliyun.com/repository/gradle-plugin/com/github/bumptech/glide/disklrucache/4.15.1/disklrucache-4.15.1.jar

**Comment by sjudd** [comment]
Hi, are you still able to reproduce this? I took a look at maven central and it looks like the files are present: https://repo1.maven.org/maven2/com/github/bumptech/glide/disklrucache/4.15.1/

Glide's upload script does occasionally fail to upload an artifact, but I'm not seeing that this time.

**Comment by SaltedFish-Extreme** [comment]
> Glide's upload script does occasionally fail to upload an artifact, but I'm not seeing that this time.

Hello, I tried to synchronize the gradle again just now, this time there is no problem, it may be because the image update of the third-party dependency warehouse I used was not updated in time, thanks
