### ISSUE TITLE
Attempt to invoke virtual method int android.graphics.Bitmap.getWidth() on a null object

### ISSUE THREAD

**Issue by lx1361322** [bumptech/glide#5124]
Using version 4.9.0 for Androidx
Gif can be loaded normally, but when I exit the activity, the null pointer crashes 
Only on xiaomi4box  find
How can I solve this problem?
thanks for your answer

04-17 11:24:51.602 E/AndroidRuntime(15419): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at com.bumptech.glide.load.resource.gif.GifFrameLoader.getWidth(SourceFile:1)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at com.bumptech.glide.load.resource.gif.GifDrawable.getIntrinsicWidth(SourceFile:1)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.widget.ImageView.invalidateDrawable(ImageView.java:232)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:385)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.graphics.drawable.Drawable.setVisible(Drawable.java:764)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at com.bumptech.glide.load.resource.gif.GifDrawable.setVisible(SourceFile:6)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.widget.ImageView.onDetachedFromWindow(ImageView.java:1487)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.View.dispatchDetachedFromWindow(View.java:14601)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3099)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5652)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.ViewRootImpl.die(ViewRootImpl.java:5629)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:397)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:352)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3872)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.app.ActivityThread.-wrap5(ActivityThread.java)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.os.Handler.dispatchMessage(Handler.java:102)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.os.Looper.loop(Looper.java:157)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at android.app.ActivityThread.main(ActivityThread.java:5427)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at java.lang.reflect.Method.invoke(Native Method)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:748)

04-17 11:24:51.602 E/AndroidRuntime(15419): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:638)

**Comment by lx1361322** [comment]
记录问题
因为GifFrameLoader 触发了 clear方法，导致资源释放掉了..检查是否主动提前执行过clear()方法

**Comment by sjudd** [comment]
Newer versions of Glide store the width /height so this won't happen
