### ISSUE TITLE
Add support for transitions in the GlideImage Compose API

### ISSUE THREAD

**Issue by jbiral** [bumptech/glide#5131]
I am filing a feature request per https://bumptech.github.io/glide/int/compose.html#transitions-and-state-changes.

Currently, when I have an image loaded, and I am replacing it with another image, the GlideImage temporarily flickers due to the GlideImage doing these transitions in a somewhat harsh way:

Old Image -> background color (e.g. white) -> New Image

It'd be significantly nicer if I could either do one of the following:

- Old Image -> New Image (without going through a transitory state)
- Old Image -> Fade -> New Image (optional, but would look nicer than transitioning directly)

Skipping the intermediary state would help make this visually more appealing / less distracting to users.

**Comment by sjudd** [comment]
Duplicate of #5016 I think?
