### ISSUE TITLE
How to create a custom cache path ?

### ISSUE THREAD

**Issue by ruijun** [bumptech/glide#516]
Hi,

In my app I want to create a custom cache path and cache file name, How can I do this ?

**Comment by floating-cat** [comment]
https://github.com/bumptech/glide/wiki/Configuration#user-content-location

**Comment by ruijun** [comment]
@floating-cat Thank you !

**Comment by TWiStErRob** [comment]
That wiki is a little outdated, there is a new class to make it simpler in [3.6.0](https://github.com/bumptech/glide/releases/tag/v3.6.0):

> Add simpler DiskCacheFactory implementation (#430, thanks to @Tolriq)
```
glideBuilder.setDiskCache(new InternalDiskCacheFactory(context, 10 * 1024 * 1024));
// or:
glideBuilder.setDiskCache(new ExternalDiskCacheFactory(context, "cache_dir", 10 * 1024 * 1024));
```

use the above in [`GlideModule#applyOptions`](https://github.com/bumptech/glide/wiki/Configuration#including-a-glidemodule).

**Comment by ruijun** [comment]
@TWiStErRob Thank you for your answer.

**Comment by sjudd** [comment]
I updated the wiki, thanks!
