### ISSUE TITLE
Android 13 SecurityException

### ISSUE THREAD

**Issue by fjgarciaf** [bumptech/glide#5174]
**Glide Version**:  4.12.0

**Integration libraries**: No

**Device/Android Version**: Samsung SM-A336B and SM-A325F Android 13 

**Issue details / Repro steps / Use case background**: 

This is an application that fetches images from public storage and compresses them to send to the server. It uses Glide to get the images and store them in a Bitmap.
We have detected in these two devices when passing the uri ".load(Uri)" to glide, it gives problems:

Glide : Load failed for content://media/external/images/media/1000003916 with size [1200x1600].

Glide : java.lang.SecurityException: com.example.app has no access to content://media/external/images/media/1000003916?requireOriginal=1

Below is more detailed.

has permissions:
READ_EXTERNAL_STORAGE
WRITE_EXTERNAL_STORAGE
MANAGE_EXTERNAL_STORAGE

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```
    public void compressImage(Context context,
                              int quality,
                              Uri imageURL,
                              String saleOrderId,
                              CompressImageResult compressImageResult) {
        try{
            BitmapFactory.Options bmOptions = new BitmapFactory.Options();
            bmOptions.inJustDecodeBounds = true;

            BitmapFactory.decodeFile(currentPhotoPath, bmOptions);
            int photoW = bmOptions.outWidth;
            int photoH = bmOptions.outHeight;

            if (photoW > photoH) {
                photoW = 1600;
                photoH = 1200;
            } else {
                photoW=1200;
                photoH = 1600;
            }

            Bitmap resource = Glide.with(context)
                    .asBitmap()
                    .load(imageURL)
                    .submit(photoW,photoH)
                    .get();
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            resource.compress(Bitmap.CompressFormat.JPEG, quality, stream);
            compressImageResult.compressImageSuccess(stream.toByteArray());
        } catch (InterruptedException | ExecutionException ex) {
            Log.e("ImageUtils error:", String.valueOf(ex));
            compressImageResult.compressImageFail();
            Thread.currentThread().interrupt();
        }
    }

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

06-13 16:01:04.419 17383 19361 W Glide   : Load failed for content://media/external/images/media/1000003916 with size [1200x1600]
06-13 16:01:04.419 17383 19361 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
06-13 16:01:04.419 17383 19361 W Glide   : There was 1 root cause:
06-13 16:01:04.419 17383 19361 W Glide   : java.lang.SecurityException(com.example.app has no access to content://media/external/images/media/1000003916?requireOriginal=1)
06-13 16:01:04.419 17383 19361 W Glide   :  call GlideException#logRootCauses(String) for more detail
06-13 16:01:04.419 17383 19361 W Glide   :   Cause (1 of 1): class java.lang.SecurityException: com.example.app has no access to content://media/external/images/media/1000003916?requireOriginal=1
06-13 16:01:04.420 17383 19361 I Glide   : Root cause (1 of 1)
06-13 16:01:04.420 17383 19361 I Glide   : java.lang.SecurityException: com.example.app has no access to content://media/external/images/media/1000003916?requireOriginal=1
06-13 16:01:04.420 17383 19361 I Glide   : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
06-13 16:01:04.420 17383 19361 I Glide   : 	at android.os.Parcel.createException(Parcel.java:3007)
06-13 16:01:04.420 17383 19361 I Glide   : 	at android.os.Parcel.readException(Parcel.java:2990)
06-13 16:01:04.420 17383 19361 I Glide   : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
06-13 16:01:04.420 17383 19361 I Glide   : 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
06-13 16:01:04.420 17383 19361 I Glide   : 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
06-13 16:01:04.420 17383 19361 I Glide   : 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
06-13 16:01:04.420 17383 19361 I Glide   : 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
06-13 16:01:04.420 17383 19361 I Glide   : 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:74)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:50)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:13)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher.loadData(QMediaStoreUriLoader.java:141)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
06-13 16:01:04.420 17383 19361 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-13 16:01:04.420 17383 19361 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-13 16:01:04.420 17383 19361 I Glide   : 	at java.lang.Thread.run(Thread.java:1012)
06-13 16:01:04.420 17383 19361 I Glide   : 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
06-13 16:01:04.420 17383 17617 E ImageUtils error:: java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
06-13 16:01:04.420 17383 17617 E ImageUtils error:: There was 1 root cause:
06-13 16:01:04.420 17383 17617 E ImageUtils error:: java.lang.SecurityException(com.example.app has no access to content://media/external/images/media/1000003916?requireOriginal=1)
06-13 16:01:04.420 17383 17617 E ImageUtils error::  call GlideException#logRootCauses(String) for more detail
06-13 16:01:04.421 17383 19361 E GlideExecutor: Request threw uncaught throwable

**Comment by Shekharcodess** [comment]
Have you tried declaring the READ_EXTERNAL_STORAGE permission in your app's manifest file? This permission is required to read images from external storage.

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
And
If you're targeting Android 10 or higher, you need to request the READ_EXTERNAL_STORAGE permission at runtime

**Comment by HedAurabesh** [comment]
(Adding this because I found this page when looking for the "Require Original" error)

I believe the issue here is that versions of Glide before 4.16.0 added "requireOriginal=1" to the Uri, which is not supported when using the Android 13 photo picker (to avoid requiring your app to request READ_EXTERNAL_STORAGE).

The pull request #5162 fixed that:
> Do not set requireOriginal on Android photo picker uris.

So the solution is to build against Glide >= 4.16.0
