### ISSUE TITLE
glide compose incorrectly includes androidx.test as a primary dependency

### ISSUE THREAD

**Issue by joerogers** [bumptech/glide#5175]
I am experimenting with migrating to Compose in an existing project that uses Glide for image loading. I'm using:

    implementation("com.github.bumptech.glide:compose:1.0.0-alpha.3")

which internally depends on 

   `com.github.bumptech.glide:ktx:1.0.0-alpha.3`

After adding glide compose I started noticing all my existing tests were hanging on launch. After some investigation, I tracked the issue down to the fact the glide ktx integration library is including androidx.test:core on line 44 of the build.gradle:

 ` implementation "androidx.test:core-ktx:$ANDROID_X_TEST_CORE_KTX_VERSION"`

In looking at the library there is no actual dependency on this library in the main code only tests, and I believe you meant to include it as a testImplemenation instead.

I realize this is alpha code, but it would be great if this dependency is fixed in the next version so others don't experience the same issue.  In the meantime I'm using this work around:

```
    implementation("com.github.bumptech.glide:compose:1.0.0-alpha.3") {
        exclude group: "androidx.test", module: "core-ktx"
    }
```

**Glide Version**: 4.15.1 (compose version listed above)

**Integration libraries**: compose, okhttp4, annotations

**Device/Android Version**:  All

**Issue details / Repro steps / Use case background**: 

Run android instrumentation test which do not have any UI or glide interactions at all.  Test hangs.

**Comment by sjudd** [comment]
Ah sorry about that, I appreciate the detail and the workaround.
