### ISSUE TITLE
Glide Animation Webp can not animate when displaying same webp url in RecyclerView

### ISSUE THREAD

**Issue by shiqos** [bumptech/glide#5176]
**Glide Version**: 4.5.1

**Integration libraries**: null

**Device/Android Version**: Android 9+

**Issue details / Repro steps / Use case background**: 

Please check this repo: 
https://github.com/shiqos/GlideWebpAnimationDrawableReuseBug

also you can check this video:
https://github.com/shiqos/GlideWebpAnimationDrawableReuseBug/blob/master/glide.mp4

**Preinvestigation**:
When using RecyclerView, if difference item share same drawable instance, and when one item reused, it's drawable will be cleared, then the other item drawable will be paused, and anim will stoped

For other Drawable, even though using MEMORY_CACHE
There will create new Drawable
https://github.com/bumptech/glide/blob/v4.15.1/library/src/main/java/com/bumptech/glide/load/resource/drawable/DrawableResource.java#L42

But for AnimatedImageDrawable, it use the same drawable:
https://github.com/bumptech/glide/blob/v4.15.1/library/src/main/java/com/bumptech/glide/load/resource/drawable/AnimatedImageDecoder.java#L100

And RecyclerView may be using same drawable in different item, so the items status can be influenced by same drawable

https://github.com/bumptech/glide/assets/5960841/f262729d-c39a-4451-b289-af88b2896538

**Comment by sjudd** [comment]
Thanks for pointing this out, really appreciate the detail

**Comment by sjudd** [comment]
Sadly it looks like we can't easily fix this. AnimatedImageDrawable doesn't seem to support `ConstantState`, which is what we use in `GifDrawable` to (mostly) work around this issue. Even `GifDrawable` shares the current frame with all drawable instances, the `ConstantState` only allows one copy to be paused and the other to be running.

You might be able to work around this by using `skipMemoryCache(true)` to make each copy of the GIF load from disk. Unfortunately there's not a way to keep multiple separate copies of the gif drawable in the cache at once with different states.

**Comment by shiqos** [comment]
> 

Thanks for reply
Using `skipMemoryCache(true)` can solve this problem :)

By the way:
Is it possible to support predictable `skipMemoryCache` if drawable is `AnimatedImageDrawable`?

for example:
```
Glide.with(imageView)
     .skipMemoryCacheIf(block: Drawable -> Boolean)
     .into(imageView)
```

In this way, we can decide whether to skip memory according to the drawable type
In most cases, we load remote pic link and unable to decide if `skipMemoryCache` should be set with `true` when using `Glide.load`
