### ISSUE TITLE
How to use Okhttp

### ISSUE THREAD

**Issue by wenjiang** [bumptech/glide#519]
When i want to use okhttp,but i found that it is wrong:
OkhttpClient client = new OkhttpClient();
Glide.get(this).register(GlideUrl.class, InputStream.class,
        new OkHttpUrlLoader.Factory(client));

What is the right to use Okhttp?@TWiStErRob

**Comment by floating-cat** [comment]
https://github.com/bumptech/glide/wiki/Integration-Libraries#user-content-okhttp

Glide v3.5.0 add GlideModules for lazy configuration instead of the old way your wrote.
I am not sure whether the old way works well in current version, but you have better use GlideModule IMHO.

**Comment by TWiStErRob** [comment]
If you're using Gradle, you just need to add the 2 dependencies. No registration required, because the manifest merger will take care of it during a `gradle assemble`. Customizing okhttp is an advanced feature you probably don't need.

**Comment by sjudd** [comment]
Let us know if you need additional help.
