### ISSUE TITLE
Image does not show completly white

### ISSUE THREAD

**Issue by vlonjatg** [bumptech/glide#521]
I have a bunch of images which have a completely white background. However when I load them in the ListView with Glide, there is a yellowish tint displayed and not a clear white. 

![](http://i.stack.imgur.com/ZVW6P.png)

I tired to display them with Picasso and they are displayed correctly, however we have implemented Glide in the whole app so replacing it will take time. My guess is that the problem is somewhere with the image decoding. 

Does anyone have a solution for this issue?

Thanks.

**Comment by sjudd** [comment]
Try ARGB_8888, you can set a default with GlideBuilder, see [the wiki][1]

[1]: https://github.com/bumptech/glide/wiki/Configuration#bitmap-format

**Comment by vlonjatg** [comment]
Thanks @sjudd for the reply. 

So I followed these steps:

Created a new class ```GlideModule```

``` java
public class GlideConfiguration implements GlideModule {
 
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // Apply options to the builder here.
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
    }
 
    @Override
    public void registerComponents(Context context, Glide glide) {
        // register ModelLoaders here.
    }
}
```
Then setted as a meta-data in Manifest.

``` xml
<meta-data android:name="com.test.lab.glide.GlideConfiguration"
            android:value="GlideModule"/>
```
but still that tint is there.

Are there more steps to implement?

Thanks.

**Comment by sjudd** [comment]
That's probably sufficient, you can add a break point to ensure that setDecodeFormat is in fact being called. 

I'm still inclined to think this is the same as  #305. Try clearing cache for your app and see if that makes a difference. It's possible you're now just loading the previously compressed RGB_565 Bitmap from cache in the ARGB_8888 format.

Similarly you can verify this is the same as #305 by using [DiskCacheStrategy.NONE][1] in your request and seeing if that fixes the issue.

[1]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/load/engine/DiskCacheStrategy.html#NONE

**Comment by vlonjatg** [comment]
Yep @sjudd you are right, the app was loading the cached RGB_565 version. So switching to PREFER_ARGB_8888 & clearing the app data fixes this issue. 

Thanks @sjudd for your help.

**Comment by sjudd** [comment]
Sure no problem.
