### ISSUE TITLE
How to maintain aspect ratio of image in Compose GlideImage android? Something like adjustViewBounds

### ISSUE THREAD

**Issue by palvaibhav89** [bumptech/glide#5212]
Using 
implementation "com.github.bumptech.glide:glide:4.15.1"
implementation "com.github.bumptech.glide:compose:1.0.0-alpha.3"

**Comment by sjudd** [comment]
I'm not entirely sure what you mean, if you'd like to open a new issue with more detail on what you're seeing vs what you want, I can take another look
