### ISSUE TITLE
[Glide] Unprotected Broadcast receiver issue

### ISSUE THREAD

**Issue by svallamsudhakar** [bumptech/glide#5215]
**Glide Version**: com.github.bumptech.glide:glide:4.15.1

**Integration libraries**:

**Device/Android Version**: not applicable since code quality check 

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
"issue": {
      "title": "Context Registered Broadcast Receivers Not Protected with Permissions",
      "category": "code",
      "cvss": 4,
      "cvss_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
      "severity": "medium",
      "pass_content": "The app does not dynamically register any unprotected broadcast receivers.",
      "description": "The app dynamically registers some unprotected broadcast receivers.\n\nBroadcast receivers are an inter-process communication ingest mechanism, allowing apps to receive data in the form of intents coming from other apps. They can be statically declared in the Android Manifest or registered dynamically at runtime. The latter is known as [Context-registered receivers](https://developer.android.com/guide/components/broadcasts.html#context-registered-receivers), because their lifetime is bound to a given `Context` object in the app. For example, an `Activity` is a `Context` that may have broadcast receivers registered against it at runtime.\n\nAs with static receivers, dynamic ones can be exported, protected using permissions or using signature enforcement. If left unprotected, as is the case with this finding, third party apps can send data to these receivers.\n\nThe exact impact varies on case-by-case basis depending on how the app handles incoming broadcasts. Although many cases are harmless, commonly seen consequences for the affected apps are:\n\n- Performing unintended actions, perhaps on behalf of the user.\n- Displaying the incoming data to the user on behalf of the app for the purposes of phishing or social engineering, for example by loading a URL specified by the attacker into a WebView.\n- Exposing sensitive data, for example, by sending its own broadcast in response to the incoming one, or by writing it to a location accessible by other apps.",
      "impact_summary": "A malicious app installed on the device can attempt to send broadcast intents that trigger the unprotected broadcast receiver. These intents can modify the runtime of the app, making the app a potential phishing vector. If the sender app's broadcasts contain sensitive information, a malicious app may be able to perform intent sniffing, leaking sensitive data. Furthermore, a malicious app can register itself with high priority, if the broadcast is an ordered broadcast, to receive the broadcast first. If the malicious app is the first to receive the broadcast, it could cancel the broadcast causing a denial of service, or it could inject a malicious data into the broadcast.",
      "recommendation": "The evidence table presents the class names and method names where unprotected broadcast receivers have been registered in the app's source code.\n\nOpen your source code and browse to the listed methods. Review how they construct the parameters to the `registerReceiver` calls, what the receivers do with the incoming data and whether they handle sensitive data.\n\nNote that the results might contain instances from third-party code. To inspect the results from your own code first you can search for the package names that your app uses.\n\nIf the broadcast receiver handles sensitive information you need to restrict access to it. These are the options:\n\n- Completely prevent any other apps from triggering your broadcast receiver: set [`RECEIVER_NOT_EXPORTED`](https://developer.android.com/reference/androidx/core/content/ContextCompat#RECEIVER_NOT_EXPORTED()) when registering your receiver. This is only possible if your app targets Android 13 or higher or if you use the [`ContextCompat`](https://developer.android.com/reference/androidx/core/content/ContextCompat) class from version 1.9.0 or higher of the [AndroidX Core library](https://developer.android.com/jetpack/androidx/releases/core).\n- Restrict access to only certain apps: specify a `broadcastPermission` with a [signature permission](https://developer.android.com/guide/topics/permissions/overview#signature) when registering your receiver with [`registerReceiver(BroadcastReceiver, IntentFilter, String, Handler)`](https://developer.android.com/reference/android/content/Context#registerReceiver(android.content.BroadcastReceiver,%20android.content.IntentFilter,%20java.lang.String,%20android.os.Handler)).\n\nIf your app is supposed to only send and receive broadcasts to itself, avoid both Broadcast Receivers and using [`LocalBroadcastManager`](https://developer.android.com/reference/androidx/localbroadcastmanager/content/LocalBroadcastManager), which is deprecated.\n\nInstead, Google recommends using an observable pattern, such as [androidx.lifecycle.LiveData](https://developer.android.com/reference/androidx/lifecycle/LiveData) or reactive streams, depending on your use case.\n\n**Note:** for results pointing to third-party libraries included in your app you should consider inspecting them carefully to see if the affected broadcast receiver handles sensitive information and if that's the case, consider updating or replacing those libraries."         **{
          "class": "com.mscripts.mscriptslibrary.ui.MscriptsActivity",
          "method": "onCreate()",
          "_raw": {
            "api": "Landroid/content/Context;,registerReceiver,(Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;)Landroid/content/Intent;",
            "line": 556,
            "method": "Lcom/mscripts/mscriptslibrary/ui/MscriptsActivity;,onCreate,(Landroid/os/Bundle;)V",
            "source_file": "com/mscripts/mscriptslibrary/ui/SourceFile"
          }
        }**

**Comment by sjudd** [comment]
Does this point to somewhere in Glide? I don't see anything Glide related here?

**Comment by svallamsudhakar** [comment]
> Does this point to somewhere in Glide? I don't see anything Glide related here?

@sjudd sorry I have attached incorrect details, here is the class snippet {
          "class": "com.bumptech.glide.manager.DefaultConnectivityMonitor",
          "method": "register()",
          "_raw": {
            "api": "Landroid/content/Context;,registerReceiver,(Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;)Landroid/content/Intent;",
            "line": 25,
            "method": "Lcom/bumptech/glide/manager/DefaultConnectivityMonitor;,register,()V",
            "source_file": "com/bumptech/glide/manager/SourceFile"
          }
}
