### ISSUE TITLE
GlideImage with wrong width/height when model changes

### ISSUE THREAD

**Issue by sky-ricardocarrapico** [bumptech/glide#5219]
**Glide Version**: 4.15.1 / 1.0.0-alpha.3 (Compose)

**Integration libraries**: N/A

**Device/Android Version**: N/A (but it happens in both Samsung Galaxy S20 Ultra and emulator)

**Issue details / Repro steps / Use case background**: 

If we're trying to load an image where one size is constrained and the other is not plus, if we first pass a null on the model (because we don't yet know what is the URL) and later replace with the actual URL, the view will end up taking all the available parent space instead of wrapping around the content on the dimension that is not constrained.

Given this code:

```kotlin
Row(
    verticalAlignment = Alignment.CenterVertically,
    modifier = Modifier
        .height(56.dp)
        .padding(horizontal = 16.dp)
) {
    Text(
        text = "pre",
        color = Color.White
    )

    GlideImage(
        model = url,
        contentDescription = null,
        contentScale = ContentScale.FillHeight,
        modifier = Modifier
            .height(32.dp),
    )

    Text(
        text = "after",
        modifier = Modifier.fillMaxWidth(),
        color = Color.White
    )
}
```

Suppose that `url = null` at the start and is later changed into an actual url. What ends up happening:

![Screenshot 2023-07-26 at 11 21 30](https://github.com/bumptech/glide/assets/67684386/ccecc69d-5502-4cb2-a528-330668792967)

If we don't call `GlideImage` with null at the start:

```kotlin
url?.let {
    GlideImage(...)
}
```

It'll be correct:

![Screenshot 2023-07-26 at 11 24 01](https://github.com/bumptech/glide/assets/67684386/8bd9cd6a-2a16-4ef1-92bf-d51eb378d4f6)

This seems to be because the size is not invalidated when the model changes. I tried to hack around this with the following:

```kotlin
requestBuilderTransform = {
    it.run { if (url == null) override(Target.SIZE_ORIGINAL) else this }
}
```

And it fixes the issue.

Possibly related with https://github.com/bumptech/glide/issues/4916.

Thanks!

**Comment by sjudd** [comment]
Let me know if you can reproduce with the latest [snapshot](https://bumptech.github.io/glide/dev/snapshots.html), there've been a lot of changes since the first version

**Comment by sjudd** [comment]
Ok I think this is fixed, we'll now generally default to sizing to intrinsics, at the cost of additional layout passes as the image is loaded.
