### ISSUE TITLE
How to cancel request while useing download(url)

### ISSUE THREAD

**Issue by leeyuanxia** [bumptech/glide#5228]
i want cancel a request while download. I use okhttp .
`
@Override
    public void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        super.registerComponents(context, glide, registry);
        Log.e("FmAppGlideModule", "registerComponents");
        OkHttpClient client = new OkHttpClient.Builder()
                .addNetworkInterceptor(chain -> {
                    Request request = chain.request();
                    Response response = chain.proceed(request);
                    ResponseProgressListener listener = new DispatchingProgressListener();
                    return response.newBuilder()
                            .body(new OkHttpProgressResponseBody(request.url().toString(), response.body(), listener))
                            .build();
                })
                .build();
        registry.replace(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(client));
    }
`

**Comment by sjudd** [comment]
`Glide.with(context).clear(target/view)` will cancel downloads if download cancellation is supported by the networking library (I think it is for okhttp)

**Comment by leeyuanxia** [comment]
> `Glide.with(context).clear(target/view)` will cancel downloads if download cancellation is supported by the networking library (I think it is for okhttp)

thanks.but it doesn't fit my situation.I use `Glide.with(context).download(newUrl).submit().get()` to get a image file. 
I have already solved my problem. Method `.submit()` will reutrn FutureTarget<File>. I can use `FutureTarget<File>.cancel(true)` to cancel this request.It will throw a CancellationException.
