### ISSUE TITLE
Out of memory error on 5.11

### ISSUE THREAD

**Issue by yazeed44** [bumptech/glide#523]
Glide worked fine with no problem on 4.4.2 , but when i upgraded to 5.11 seems like there's a problem

this problem seems to occur only in view pager (Maybe because i load .gif as bitmap in thumbnails)

Here's the stacktrace
http://paste.ofcode.org/L6ddNMMUWAeb6hGm69vegR

**Comment by sjudd** [comment]
Usually OOMs indicate either inappropriately large image requests or memory leaks in the application. In this case you're loading relatively large Bitmaps (>10mb), consider using RGB_565, or reducing the size you're requesting with the [``override()``][1] method.

[1]: http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/DrawableRequestBuilder.html#override(int,%20int)

**Comment by sjudd** [comment]
Also for GIFs, see #83, using a Transformation may also help (fitCenter probably) along with override.
