### ISSUE TITLE
Blurry Image in compose alpha4

### ISSUE THREAD

**Issue by CedrickFlocon** [bumptech/glide#5233]
**Glide Version**: 
glide-compsoe `1.0.0-alpha.4-SNAPSHOT` (9 aug 2023)

**Integration libraries**: 
No

**Device/Android Version**: 
Emulator Pixel 6 API 33

**Issue details / Repro steps / Use case background**: 
A larger placeholder than the `model` image make the `model` image blurry.
e.g :
placeholder : 780*1170
[model image](https://static-a.imgix.net/starfish.png?w=131.25) : 131 * 131
| alpha3 | alpha4 |
| ------- | ------ |
| ![alpha3](https://github.com/bumptech/glide/assets/7161169/0121a186-7ffe-4161-8fdc-8de107b649f9) | ![alpha4](https://github.com/bumptech/glide/assets/7161169/a35fd99d-3770-4dd5-8284-f8b8316168fb) |

**Usage**:
sample : https://github.com/CedrickFlocon/android-tryout/tree/glide
```kotlin
GlideImage(
    model = "https://static-a.imgix.net/starfish.png?w=${with(LocalDensity.current) { 50.dp.toPx() }}",
    contentDescription = null,
    modifier = Modifier
        .width(50.dp)
        .height(50.dp)
) {
    it.placeholder(R.drawable.bouli)
}
```

**Comment by sjudd** [comment]
Looks like this is fixed on head now

**Comment by CedrickFlocon** [comment]
yes, I confirm
