### ISSUE TITLE
[Question] add Glide clear code at Application.onTrimMemory(), Appication.onLowMemory()

### ISSUE THREAD

**Issue by riflockle7** [bumptech/glide#5242]
Hello, I saw this comment(https://github.com/bumptech/glide/issues/1135#issuecomment-231174093) and have a question.

```java
public class App extends Application {
    @Override public void onLowMemory() {
        super.onLowMemory();
        Glide.get(this).clearMemory();
    }
    @Override public void onTrimMemory(int level) {
        super.onTrimMemory(level);
        Glide.get(this).trimMemory(level);
    }
}
```
Is this code still required when using the Glide library?
This code is for OOM preparation.

If Glide has resolved it, it will try to delete it.

**Comment by sjudd** [comment]
Glide already has these callbacks
