### ISSUE TITLE
LayerDrawable

### ISSUE THREAD

**Issue by StefanKoopman** [bumptech/glide#525]
I'm using a GestureImageView with a LayerDrawable to display a map with a custom layer depending on the selected theme. Now I'm trying to use Glide to smoothen the loading, but I can't figure out how to build a LayerDrawable.

**Comment by TWiStErRob** [comment]
Did you read the [Custom Targets wiki](https://github.com/bumptech/glide/wiki/Custom-targets)?

I would try to write a target which represents one layer of the LayerDrawable: MyTarget(LayerDrawable, layerIndex). Create the grouping drawable and start each layer's load separately into the Custom targets. Set the drawable to the ImageView and they'll pop up as soon as loaded. Now, you said smoothen... does that mean you want to fade in the layers?

**Comment by sjudd** [comment]
Let us know if you have any other questions.
