### ISSUE TITLE
The class GeneratedAppGlideModuleImpl generated by ksp does not register the LibraryGlideModule subclass

### ISSUE THREAD

**Issue by jenverstraete** [bumptech/glide#5269]
Referencing the bug that was posted here:
https://github.com/bumptech/glide/issues/5043

@sjudd am I missing something or is more investigation needed on this bug, because when I use the sample project from issue 5043 (https://github.com/lyh8577/GlideDemo-issue-5043), update the dependencies in the KSP build.gradle file to a glide version where this issue should be fixed (4.15.1 or 4.16.0) and re-build and check the generated GeneratedAppGlideModuleImpl.kt, the exact same issue still persists. Methods like getExcludedModuleClasses are still absent from the generated file. As a result, it is not possible to use Glide with KSP while trying to show images from a firebase reference.

_ksp("com.github.bumptech.glide:ksp:4.15.1")
implementation("com.github.bumptech.glide:okhttp3-integration:4.15.1")_

**Generated class looks like:**

_internal class GeneratedAppGlideModuleImpl(
  @Suppress("UNUSED_PARAMETER")
  context: Context,
) : GeneratedAppGlideModule() {
  private val appGlideModule: KspAppGlideModule
  init {
    appGlideModule = KspAppGlideModule()
  }

  public override fun registerComponents(
    context: Context,
    glide: Glide,
    registry: Registry,
  ): Unit {
    OkHttpLibraryGlideModule().registerComponents(context, glide, registry)
    appGlideModule.registerComponents(context, glide, registry)
  }

  public override fun applyOptions(context: Context, builder: GlideBuilder): Unit {
    appGlideModule.applyOptions(context, builder)
  }

  public override fun isManifestParsingEnabled(): Boolean = false
}_

**Comment by sjudd** [comment]
Seems like it works for me? 
<img width="1042" alt="image" src="https://github.com/bumptech/glide/assets/1627211/99360c1c-ffac-4440-a143-49e94bf94196">
<img width="1128" alt="image" src="https://github.com/bumptech/glide/assets/1627211/a789b08a-0791-45e0-8186-ee0286c91427">

**Comment by sjudd** [comment]
The project structure may obfuscate things? I think I ended up needing to make changes in the app module to include ksp.
