### ISSUE TITLE
Glide Compose can`t display animation image properly.

### ISSUE THREAD

**Issue by ag2s20150909** [bumptech/glide#5273]
Previously, I used this library [landscapist](https://github.com/skydoves/landscapist) to display animation image(like gif) normally, but after switching to the official Composite implementation, I found that animation  image cannot be displayed normally, only show static images .

**Comment by rahulyadav07** [comment]
please provide image of behavour

**Comment by sjudd** [comment]
Thanks for the report and follow up!
