### ISSUE TITLE
Fix for crash related to scale factor was not included in compose alpha6

### ISSUE THREAD

**Issue by joerogers** [bumptech/glide#5281]
**Glide Version**: 4.16.0

**Integration libraries**: compose 1.0.0-alpha.6
okhttp, ksp 4.16.0

**Device/Android Version**: All

**Issue details / Repro steps / Use case background**: 

The fix for #5256 is missing from alpha.6.  I made this as a comment on that ticket, but it is worth an official issue since I believe the fix will work if included.

Basically the source from alpha.6 in the GlideModule function: modifyConstraints()  looks like the old code AND it fails in the exact way I reported in the referenced ticket which confirms this version of the source code.

```
    ...
    val constrainedWidth = constraints.constrainWidth(intrinsicWidth)
    val constrainedHeight = constraints.constrainHeight(intrinsicHeight)

    val srcSize = Size(intrinsicWidth.toFloat(), intrinsicHeight.toFloat())
    val scaledSize =
      srcSize * contentScale.computeScaleFactor(
        srcSize, Size(constrainedWidth.toFloat(), constrainedHeight.toFloat())
      )

    val minWidth = constraints.constrainWidth(scaledSize.width.roundToInt())
    val minHeight = constraints.constrainHeight(scaledSize.height.roundToInt())
    return constraints.copy(minWidth = minWidth, minHeight = minHeight)
```

At master the code was refactored to and was the code I expected to be included in alpha.6:

```
    ...
    val constrainedWidth = constraints.constrainWidth(intrinsicWidth)
    val constrainedHeight = constraints.constrainHeight(intrinsicHeight)

    val srcSize = Size(intrinsicWidth.toFloat(), intrinsicHeight.toFloat())
    val scaleFactor = contentScale.computeScaleFactor(
        srcSize, Size(constrainedWidth.toFloat(), constrainedHeight.toFloat())
      )
    if (scaleFactor == ScaleFactor.Unspecified) {
      return constraints
    }
    val scaledSize = srcSize * scaleFactor

    val minWidth = constraints.constrainWidth(scaledSize.width.roundToInt())
    val minHeight = constraints.constrainHeight(scaledSize.height.roundToInt())
    return constraints.copy(minWidth = minWidth, minHeight = minHeight)
```

Essentially I believe something went wrong in the build process for alpha.6 causing the fix to not be included.

**Comment by sjudd** [comment]
Thanks for the report, not sure what went wrong, I'll look into it!

**Comment by sjudd** [comment]
Oh ok, simple answer, I didn't include it! Here's the release notes with the changelog: https://github.com/bumptech/glide/releases/tag/compose-alpha6. That doesn't include this issue.

Probably I should have included it, but I forgot... :/. I'm going to see if I can move to beta soon but if I can't I'll do another alpha with this fix.

**Comment by joerogers** [comment]
I guess I thought it was included because the change was at master/main branch and you changed the same file in the new release, but figured you forgot to list it in the release notes. I look forward to trying it when it gets released.
