### ISSUE TITLE
Include a consumer-rules.pro file

### ISSUE THREAD

**Issue by michael-winkler** [bumptech/glide#5289]
It would be really nice if glide will add proguard rules automatic with the help of a consumer-rules.pro file.
See this example from OneSignal:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/bce0f2fba975a215e734fd1d12a55d52cffdaa03/OneSignalSDK/onesignal/notifications/consumer-rules.pro

All we have current is this:
https://github.com/bumptech/glide/blob/master/library/proguard-rules.txt

But it would be great if we have a new consumer-rules.pro file.

**Comment by sjudd** [comment]
You've pointed to Glide's proguard file. Are you saying it doesn't work? The naming scheme shouldn't matter much, it's configured here: https://github.com/bumptech/glide/blob/e8d10fc3dabdb835be1db3779e961064ffec3291/library/build.gradle#L69

**Comment by sjudd** [comment]
Please do re-open / let me know if there's some issue with how this is defined. As far as I can tell we do provide a proguard file.
