### ISSUE TITLE
android:tint not working on Android Lollipop

### ISSUE THREAD

**Issue by slodky** [bumptech/glide#529]
XML attribute android:tint on ImageView target is not working on Android 5.0 and 5.1.
I'm filing an issue since I wanted to migrate from Picasso (where that feature works) to Glide.

Glide version: 3.6.1

**Comment by sjudd** [comment]
This is fixed in 4.0, but won't be in 3.0 because we can't target the required sdk in that branch.

**Comment by mfietz** [comment]
As a workaround, this worked well for me: ``<ImageView>.setColorFilter(R.color.<TintColor>);``

**Comment by ZhaoKaiQiang** [comment]
but where i can find the 4.0 version ?  3.7.0 is still nit work for me @sjudd

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Snapshots

**Comment by ljungqvist** [comment]
It seems to work if you make a call to `DrawableTypeRequest#asBitmap()` before loading.
