### ISSUE TITLE
Getting a lot of "java.lang.IllegalArgumentException: Cannot draw recycled bitmaps" after adding the clear memory in LruMemoryCache

### ISSUE THREAD

**Issue by csobrinho** [bumptech/glide#53]
After I added the `MemoryCache.clearMemory` and `MemoryCache.trimMemory` to my base activity I started getting spurious exceptions regarding the bitmaps being recycled.

After reading the source of `LruMemoryCache` it seems it does a simple purge of the bitmaps in the cache but I believe that at this point there are still views with a reference to a `BitmapDrawable` containing the `Bitmap` and as soon as the draw method is called they will crash.

Is there a possibility to check if the bitmap is being used before purging it so that we only remove bitmaps that aren't currently being used?

**Comment by getintouchapp** [comment]
I still have this error in my app even though I am using the latest version of Glide 3.6.0

Snipped stacktrace

05-18 09:03:26.779	E	ACRA    	19287	ACRA caught a IllegalArgumentException for co.getintouch
05-18 09:03:26.779	E	ACRA    	19287	java.lang.IllegalArgumentException: Cannot draw recycled bitmaps
05-18 09:03:26.779	E	ACRA    	19287		at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:794)
05-18 09:03:26.779	E	ACRA    	19287		at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:117)
05-18 09:03:26.779	E	ACRA    	19287		at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
05-18 09:03:26.779	E	ACRA    	19287		at com.bumptech.glide.request.target.SquaringDrawable.draw(SquaringDrawable.java:151)
05-18 09:03:26.779	E	ACRA    	19287		at android.widget.ImageView.onDraw(ImageView.java:961)
05-18 09:03:26.779	E	ACRA    	19287		at android.view.View.draw(View.java:13481)
05-18 09:03:26.779	E	ACRA    	19287		at android.view.View.getDisplayList(View.java:12432)
05-18 09:03:26.779	E	ACRA    	19287		at android.view.View.getDisplayList(View.java:12476)
05-18 09:03:26.779	E	ACRA    	19287		at android.view.View.draw(View.java:13205)
05-18 09:03:26.779	E	ACRA    	19287		at android.view.ViewGroup.drawChild(ViewGroup.java:2936)

**Comment by sjudd** [comment]
@getintouchapp Can you file a new issue? This is a super old one.
