### ISSUE TITLE
Glide Compose invaldates cache for same signature if url has different query parameters 

### ISSUE THREAD

**Issue by Misca** [bumptech/glide#5312]
I have configuration using both Glide compose and the regular.
For instance this snippet would make request each and every time:

```
       GlideImage(
                modifier = Modifier
                    .fillMaxWidth()
                model = cobrandingUi.logoUrl,
                contentDescription = null,
            ) {
                it.diskCacheStrategy(DiskCacheStrategy.ALL)
                    .signature(getCacheSignatureForImageUrl(cobrandingUi.logoUrl))
            }
```
The signature is a simple key for getting rid of some auth tokens, so that it does not miss the cache:
```
fun getCacheSignatureForImageUrl(url: String): Key {
    var path = url
    if (path.contains("?")) { // Remove any query params
        path = path.substring(0, path.indexOf("?"))
    }
    return ObjectKey(path)
}
```

**Glide Version**:
    implementation "com.github.bumptech.glide:glide:4.14.2"
    ksp "com.github.bumptech.glide:ksp:4.14.2"
    implementation "com.github.bumptech.glide:compose:1.0.0-beta01"

**Integration libraries**:
none

**Device/Android Version**:
Samsung S21 Ultra, Android 13
Pixel 2 SM, Android 10

**Issue details / Repro steps / Use case background**: 
- use GlideImage in compose with a configuration for cache
- second time opening this same screen, http call for the image is made again (used the Android Studio -> App Inspection -> Network Inspector)

**Comment by sjudd** [comment]
There's no fundamental difference in terms of how caching works between compose and the rest of Glide, the only thing that changes is the size / transformation guessing.

See https://bumptech.github.io/glide/doc/debugging.html#unexpected-cache-misses and let me know if you find some part of the key that's changing unexpectedly.

**Comment by Misca** [comment]
Hello @sjudd ,

I think i got a better example, sorry for the previous one.
So, it seems that even if the signature is the same, if the url changes with some parameters then it also invalidates the cache:
`val url = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Aerial_view_of_Apple_Park_dllu.jpg/2560px-Aerial_view_of_Apple_Park_dllu.jpg?some-param=randon125"
            Timber.d("signature key hash: ${getCacheSignatureForImageUrl(url).hashCode()}")
            GlideImage(
                modifier = Modifier
                    .fillMaxWidth(),
                model = url,
                contentDescription = null,
            ) {
                it.diskCacheStrategy(DiskCacheStrategy.ALL)
                    .signature(getCacheSignatureForImageUrl(url))
            }`

The signature is just:
`val signature = ObjectKey("https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Aerial_view_of_Apple_Park_dllu.jpg/2560px-Aerial_view_of_Apple_Park_dllu.jpg")`
For this call, if we change the randon125 to anything new, it will download the picture again, even if the signature hash is the same each time:
2023-10-17 08:02:26.009 13246-13246 Intro...ingCompose   D  signature key hash: -619749599
2023-10-17 08:03:17.021 14360-14360 Intro...ingCompose    D  signature key hash: -619749599

**Comment by harsh111-bit** [comment]
@Misca , have you found a solution to the problem?

**Comment by Misca** [comment]
@harsh111-bit i did not. Are you facing the same issue?

**Comment by harsh111-bit** [comment]
Yes, @Misca. Below is the working solution.

GlideImageView.kt

```
@OptIn(ExperimentalGlideComposeApi::class)
@Composable
fun GlideImageView(
    modifier: Modifier = Modifier,
    url: String,
    contentDescription: String? = null,
    alignment: Alignment = Alignment.Center,
    contentScale: ContentScale = ContentScale.Inside
) {
    GlideImage(
        model = GlideUrlCustomCacheKey(url),
        contentDescription = contentDescription,
        alignment = alignment,
        contentScale = contentScale,
        modifier = modifier,
    )
}

class GlideUrlCustomCacheKey : GlideUrl {
    constructor(url: String?) : super(url)
    constructor(url: String?, headers: Headers?) : super(url, headers)
    constructor(url: URL?) : super(url)
    constructor(url: URL?, headers: Headers?) : super(url, headers)

    override fun getCacheKey(): String {
        val url = toStringUrl()
        return if (url.contains("?")) {
            url.substring(0, url.lastIndexOf("?"))
        } else {
            url
        }
    }
}
```


Use

```
GlideImageView(url = imageUrl)     
```

**Comment by Misca** [comment]
@harsh111-bit interesting, so the part that did finally fix the problem was:
`model = GlideUrlCustomCacheKey(url),`
without decorating the signature as a separate object.

I'm not sure if it's a bug or not tough but more that glad for making it work.
Thank you, @harsh111-bit  💯

**Comment by Misca** [comment]
the part that did finally fix the problem was using:
model = GlideUrlCustomCacheKey(url),
without decorating the signature as a separate object.
I'm not sure if it's a bug or not
