### ISSUE TITLE
Where is the build section for setting up the samples?

### ISSUE THREAD

**Issue by IamJackppot** [bumptech/glide#534]
I cannot find out how to set up the samples. When I import the projects into Android Studio, I get errors, where is the "Build" section like the documentation describes?

**Comment by TWiStErRob** [comment]
Start with [Build](https://github.com/bumptech/glide/blob/master/README.md#build) and after that works go to [Development](https://github.com/bumptech/glide/blob/master/README.md#development). Note that it says IDEA 14, which should be the basis of AS 1.3, but who knows if it's compatible.

Also go for the [3.0 branch](https://github.com/bumptech/glide/tree/3.0), that's the latest release. `master` is the upcoming 4.0.

**Comment by sjudd** [comment]
Android Studio works well with 4.0, intellij for 3.0. Let us know if you have more questions.

**Comment by IamJackppot** [comment]
How and where do I execute the commands in the Build section? I am new to this so some help would be highly appreciated!

**Comment by TWiStErRob** [comment]
Create a working directory, like `D:\projects\glide` or `~/projects/glide` and then fire up your favourite command line (e.g cmd or bash) and `cd` to the above created directory. You will need to [Install git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) if it says command not recognized or not found.

**Comment by IamJackppot** [comment]
I have changed directory to via command prompt to where the main directory of Glide, and am having trouble when running the following command: git clone git@github.com:bumptech/glide.git 

I get the following error: 

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Do you know why this is?

**Comment by TWiStErRob** [comment]
Try the other url: `git clone http://github.com/bumptech/glide.git .` copied from https://github.com/bumptech/glide and "You can clone with" on the right, select `HTTPS`. You're trying the SSH url that's meant for Unix probably. Sam's working on Unix so he couldn't include the steps for Windows.

You'll probably want a `git checkout 3.0` after clone has succeeded, because `master` is pre-release. Also git clones the whole repository, including branches so putting `-master` in the folder name is not advised. Also notice the `.` at the end of clone, that means that it will clone into the current directory and won't create one more level unnecessarily.

**Comment by IamJackppot** [comment]
OK thanks, that worked, now when I try and run the samples via this /gradlew :samples:flickr:run from CMD I get the following erorr:


E:\StudioProjects\GlideSamplers\NEWBINS>/gradlew :samples:flickr:run
'/gradlew' is not recognized as an internal or external command,
operable program or batch file.

Sorry if I'm being stupid, as I've stated before I am new to this. Also, what is git checkout 3.0? I've Googled and am more confused. thank you.

**Comment by TWiStErRob** [comment]
Checkout changes the branch. Read a *getting started with version control* or *getting started with git* to learn the terminology and build a mental model.

`3.0` is just the name of the branch, see the dropdown at the top left of the main page of Glide.
If you don't change to the 3.0 branch the code will look very different than the released 3.6.1 version.

`./command` means look for `command` in this directory and not the `PATH`. Windows doesn't like `/` (especially when you miss the dot), replace it with `\`: `.\gradlew ...` or just `gradlew ...`

**Comment by IamJackppot** [comment]
Thank you, I've got everything up and running now, what license are these samples under?

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/blob/master/LICENSE is a good starting point.

**Comment by IamJackppot** [comment]
So I'm able to use these samples under the conditions of providing the license within the app? It's gibberish to me :(
