### ISSUE TITLE
Image without effects

### ISSUE THREAD

**Issue by tonilopezmr** [bumptech/glide#535]
I want the equivalent result of this in picasso (the result is an image blurred):

        picasso.load(url).noFade().noPlaceholder().into(imageView);

![6893706-blurred](https://cloud.githubusercontent.com/assets/5845622/8635531/ddd4a662-2826-11e5-9ad5-02a9e2ad9aad.jpg)

**Comment by TWiStErRob** [comment]
Your question is not so clear, I'm assuming you want the equivalent of that Picasso load line in Glide, here's the mapping:
* `.noFade()` -> `.dontAnimate()`
* `.noPlaceholder()` -> just don't call `.placeholder()`
* blurring -> [`.transform(new BlurTranformation(...))`](https://github.com/wasabeef/glide-transformations/blob/master/README.md)

```java
Glide.with(this).load(url).dontAnimate().into(imageView);
```

**Comment by tonilopezmr** [comment]
Yes! sorry for my English :-1: :(

**Comment by tonilopezmr** [comment]
#
