### ISSUE TITLE
printStackTrace() from GlideException class having security issue in application

### ISSUE THREAD

**Issue by AshikGeidea** [bumptech/glide#5358]
**Glide Version**: 4.9.0

**Integration libraries**: No

**Device/Android Version**: Galexy S22+

**Issue details / Repro steps / Use case background**:  

printStackTrace() from GlideException class having security issue in application. This needs to be removed from release build. 
![image](https://github.com/bumptech/glide/assets/104051377/42d33576-e185-4b60-954f-a7fe039b51c0)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
implementation 'com.github.bumptech.glide:glide:4.9.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'


Glide.with(context)
                .load(model.getImage()")
                .into(view);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

proguard rules :

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.AppGlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
    **[] $VALUES;
    public *;
}

-assumenosideeffects class android.util.Log {
    public static int v(...);
    public static int d(...);
    public static int i(...);
    public static int w(...);
    public static int e(...);
}

**Comment by KarthikGeidea** [comment]
@falhassen we are facing a security issue of using PrintStackTrace() method in Glide Library. Could you please fix this issue in Glide Library and push another version?

**Comment by falhassen** [comment]
I'm sorry, I'm just a contributor, not an owner, so I can't push a new
version. You are free to create your own pull request with your changes for
the owners to review.
