### ISSUE TITLE
GlideImage no longer works with Modifier.weight()

### ISSUE THREAD

**Issue by ryandt** [bumptech/glide#5372]
**Integration libraries**: `okhttp3-4.9.1`

**Device/Android version**: Pixel 4, Android 13

**Issue details / Repro steps / Use case background**: 

I recently upgraded Glide from `4.15.1` to `5.0.0-rc01` and Glide Compose from `1.0.0-beta01` to `1.0.0-alpha.3`. Upon doing so, a few `GlideImage` usages throughout my app failed to load their image resources. They all happened to have weighted sizes. After the update, the size in `onSizeChanged()` returns `0x0` whereas previously the initial size would be `0x0` and subsequent size change would be non-zero once the weights were applied.

```
val imageSize = remember { mutableStateOf(IntSize.Zero) }
val placeholder = ColorDrawable(LocalContext.current.colorFromAttr(R.attr.some_color))
GlideImage(
    modifier = Modifier
        .weight(1f, false)
        .then(
            if (imageSize.value.width == 0) {
                Modifier.onSizeChanged {
                    if (it.width != 0) imageSize.value = it
                }
            } else Modifier,
        ),
    model = getSizedImageUrl(topStart, imageSize.value),
    loading = placeholder(placeholder),
    failure = placeholder(placeholder),
    contentDescription = null,
)
```

I created a [demo project](https://github.com/ryandt/Glide-Image-Weight-Bug-Demo) to demonstrate the bug. The first commit is with Glide Compose `1.0.0-beta01` and weights working; the second commit is with Glide Compose `1.0.0-alpha.3` and weights not working.

Does anyone have any thoughts on what may have caused this change in behavior? Possibly related to [this](https://github.com/bumptech/glide/commit/af0d631c616c41cd23eacf953f278d28b0d217e4)? cc: @sjudd

**Comment by ryandt** [comment]
I created a [demo project](https://github.com/ryandt/Glide-Image-Weight-Bug-Demo) to demonstrate the bug. The first commit is with Glide Compose `1.0.0-beta01` and weights working; the second commit is with Glide Compose `1.0.0-alpha.3` and weights not working.

**Comment by sjudd** [comment]
1.0.0-beta01  is newer than 1.0.0-alpha.3, so I think this is fixed :)

**Comment by ryandt** [comment]
@sjudd Oops, I typo'd the issue description and accidentally flipped the bug version and the non-bug version around. Just updated the description. To clarify, the issue I'm seeing is present in `1.0.0-beta01`
