### ISSUE TITLE
Compose GlideImage doesn't work property with drawWithCache modifier

### ISSUE THREAD

**Issue by lukel94** [bumptech/glide#5380]
**Glide Version**: v4.16.0

**Device/Android Version**: Google Pixel 7/8, Android 14

**Issue details / Repro steps / Use case background**: 

I'm using `GlideImage` Compose function with URL source under `drawWithCache` scoped column. The image is stuck in loading phase until I refresh the screen. 

The code is something like:

```
@Composable
fun pageUI() {
  Column(
     Modifier.drawWithCache {
      // Store the page drawable in cache for screenshot usage.
       ...
    }
  ) {
    GlideImage(url = "....")
  }
}
```

If I replaced `drawWithCache` with `drawWithContent`, the issue will go away.

```
@Composable
fun pageUI() {
  Column(
     Modifier.drawWithContent {
      // Not useful because I need to keep the screenshot picture in cache
      drawContent()
    }
  ) {
    GlideImage(url = "....")
  }
}
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kt
GlideImage(
  model = url,
  contentDescription = contentDescription,
  modifier = modifier,
)
```

**Stack trace / LogCat**: No error message, just stuck in image loading until I refresh the page

**Comment by sjudd** [comment]
I think this is broken as I'd expect. You're caching the GlideImage while it's asynchronously loading the image. The documentation says "The objects are cached as long as the size of the drawing area is the same, or any state objects that are read have not changed. " Neither of those can be influenced by GlideImage.

You could do this with GlideSubcomposition, but if all you're trying to do is cache the image load GlideImage already does that and more efficiently than GlideSubcomposition + drawWithCache
