### ISSUE TITLE
Docs confuse

### ISSUE THREAD

**Issue by AlexBlokh** [bumptech/glide#539]
https://github.com/bumptech/glide/wiki/Configuration

Everyone creates a ```new GlideBuilder()``` in ```ApplicationClass``` and tries to set parms, that don't actually have any influence

**Comment by TWiStErRob** [comment]
This has come up before in #512. The first paragraph has an important cue in the [Global configuration](https://github.com/bumptech/glide/wiki/Configuration#global-configuration-is-exposed-via-the-glidebuilder-class) section:
> To do so you use the GlideBuilder provided to you in `GlideModule#applyOptions`

The `new GlideBuilder(context)` instantiations are the residue of the [now-deprecated way](http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/Glide.html#setup(com.bumptech.glide.GlideBuilder)) of [configuring Glide (from wiki history)](https://github.com/bumptech/glide/wiki/Configuration/fc2cabfed674a2a800c5265a238faa5e81fc3cbc).

I sent a fixed version to @sjudd for consideration.

**Comment by sjudd** [comment]
Merged, thanks!
