### ISSUE TITLE
Request for xamarin java binding library 

### ISSUE THREAD

**Issue by ThomasJacob** [bumptech/glide#540]
Can you provide the glide java binding library for Xamarin

**Comment by sjudd** [comment]
I don't use Xamarin so I'm afraid it's highly unlikely I will personally do this. If you're interested in doing so I'd certainly be willing to look at a pull request.

**Comment by 25RBazookas** [comment]
Glide Xamarin Binding on Github: @ThomasJacob @sjudd  https://github.com/thanhdatbkhn/GlideXamarinBinding

**Comment by TWiStErRob** [comment]
@25RBazookas nice!
Is there any reason for using 3.6.1 when 3.7.0 is available?

**Comment by beraybentesen** [comment]
@TWiStErRob also version 3.7.0 is available for Xamarin Android : [https://www.nuget.org/packages/Glide.Xamarin/](Nuget Gallery)
