### ISSUE TITLE
the  listener(new RequestListener<String, GlideDrawable>()  funtion no working 

### ISSUE THREAD

**Issue by hejinxigege** [bumptech/glide#541]
the method listener does  no preform when I from 3.4.0 version  update 

```
Glide.with(mContext).load(url).listener(new RequestListener<String, GlideDrawable>() {

     @Override
     public boolean onException(Exception arg0, String arg1,Target<GlideDrawable> arg2, boolean arg3) {
	  	 return false;
	 }
				

     @Override
     public boolean onResourceReady(GlideDrawable arg0, String arg1,Target<GlideDrawable> arg2, boolean arg3, boolean arg4) {
		  return false;
     }

				 
 }).into(imageView);
```

**Comment by TWiStErRob** [comment]
Can you please try to edit and put *\`\`\`java* before and *\`\`\`* after your code block? It looks like you don't use Generics, but it's probably just interpreted as HTML.

In any case if the listener is not called, that can mean three things:
 * you're checking whether it's called the wrong way  
For example there's no code to execute there, put a `Log.wtf("Glide", "onResourceReady");` and a similar one in `onException` and see if it appears in LogCat
 * The whole code is not called at all, that is the code starting with `Glide.with` is never reached. Put some logging before and after the `Glide.with...` statement
 * there is a bug in Glide  
But this functionality is so basic there shouldn't be a bug around it. Also others would've noticed and reported as it's frequently used.

By the way, does the image you're loading show up at all?
Which Glide version are you using currently?

**Comment by sjudd** [comment]
Let us know if you get the chance to look in to the above.
