### ISSUE TITLE
Missing files in jcenter

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#544]
While researching #532 I found that some files are missing from the `jcenter()` repo.
Take a look at the version folders at https://jcenter.bintray.com/com/github/bumptech/glide/okhttp-integration/ and you'll notice that many of them is missing a file or two.

Some are missing .aar some just .asc files. The most complete release seem to be 1.2.1, everything else is missing some .asc files, or the whole `*.aar*` bunch. Weirdly

``` gradle
compile 'com.github.bumptech.glide:okhttp-integration:1.3.1@aar'
```

works and merges the manifest correctly... which means that [okhttp-integration-1.3.1.aar](https://jcenter.bintray.com/com/github/bumptech/glide/okhttp-integration/1.3.1/okhttp-integration-1.3.1.aar) is there. So it may be just a jcenter display issue.

**Comment by TWiStErRob** [comment]
I had a deja vu and look into it a little. I found a previous support ticket for another lib which was missing a whole version. So I contacted the bintray support again: *29907 Invisible files*

**Comment by TWiStErRob** [comment]
> After investigating this issue and checking the logs for upload requests for the file ‘okhttp-integration-1.3.1.aar’. We think the file ‘okhttp-integration-1.3.1.aar’ might not have been uploaded to Bintray which could be the reason why we are not seeing it in the Bintray and Jcenter. The file is being downloaded from a remote repository when giving the filename in the path. Could you please try uploading this file to the repository in Bintray and see if it is showing up in the Bintray and JCenter.
If this is not the case and the file was uploaded to Bintray at some point of time, could you please let us know the approximate date and time when it was uploaded and we will investigate the file.

So it's likely pulling from [Maven Central](http://search.maven.org/#artifactdetails%7Ccom.github.bumptech.glide%7Cokhttp-integration%7C1.3.1%7Cjar) transparently.

**Comment by sjudd** [comment]
I'm currently doing all uploads via Maven Central and I believe they just mirror everything they find on Maven. I'd consider switching to just jcenter, but I don't want to do both...

**Comment by TWiStErRob** [comment]
Aah, so it sounds like you never uploaded anything there. They must be streaming files from Maven Central transparently, and if a file gets too many hits they physically mirror it; that's why only some files appear to be uploaded, but in fact all are available.

**Comment by TWiStErRob** [comment]
They confirmed that something like this happens, but from repo.jfrog.org not Maven Central. Feel free to close this if you want to keep the current deployment process.

**Comment by sjudd** [comment]
Hmm I'll leave this open, I think there are some benefits to just deploying to jcenter directly anyway. Thanks for looking in to this.

**Comment by sjudd** [comment]
This was fixed by relinquishing ownership on jcenter. It should now be automatically syncing from maven central.
