### ISSUE TITLE
DefaultConnectivityMonitor

### ISSUE THREAD

**Issue by vsahu1986** [bumptech/glide#554]
I am trying to figure out after connectivity change the Glide does not resume request  . 

How to initialize it . ?

**Comment by TWiStErRob** [comment]
I think all requests fail when the connection is lost, either by some IOException or a timeout so there's nothing to resume, try some [logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) to see if I'm right..

You could try [`Glide.with(context.getApplicationContext()).resumeRequestsRecursive()`](http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/RequestManager.html#resumeRequests()), but not sure if it has any effect.

**Comment by vipinhelloindia** [comment]
yes You may be right , but you have used registered for Connectivity change BroadcastReceiver , you can utilized to resume request in queue

**Comment by vsahu1986** [comment]
Fresco did this out of the box , 
https://github.com/facebook/fresco

+1 if you can add this feature

**Comment by sjudd** [comment]
This is actually already implemented: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/RequestManager.java#L452

Let me know if you think it isn't working.

**Comment by vipinhelloindia** [comment]
I guess its working on 
compile 'com.github.bumptech.glide:glide:3.6.1'

and I was tested on compile 'com.github.bumptech.glide:glide:3.6.0'

will reconfirm the step once reproduce .
