### ISSUE TITLE
GIFS connot load into the view extends ImageView

### ISSUE THREAD

**Issue by fg2q1q3q** [bumptech/glide#557]
GIFS connot load into the view extends ImageView

**Comment by TWiStErRob** [comment]
Is it `CircleImageView` or `CircularImageView`?

**Comment by fg2q1q3q** [comment]
not CircleImageView ，but CircleImageView  also cannot，in my project，it's a custom ImageView like GestureImageView

**Comment by TWiStErRob** [comment]
The problem with those two is that they're using some Drawable trickery (instanceof) to steal/rasterize to a Bitmap.

Can you share yours here, GitHub code or a gist so we can check which part may be breaking the contract?

**Comment by TWiStErRob** [comment]
Also more importantly: how do you load it? And what does "cannot load" mean?

**Comment by fg2q1q3q** [comment]
Thanks，First I want to know if it's CircleImageView ,what should I do? later I share my codes here

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/issues/528#issuecomment-119538633 and many others linked from there, to solve the problem try [CircleTransform](http://stackoverflow.com/a/25806229/253468) instead.

**Comment by fg2q1q3q** [comment]
OK，very Tks，I know my problem is

**Comment by TWiStErRob** [comment]
Please share your problem/solution in case someone finds this issue in the future.
