### ISSUE TITLE
loader SD pictures use  placeholder cause the image to load out

### ISSUE THREAD

**Issue by fg2q1q3q** [bumptech/glide#558]
code like this,sd picture,if I delete the code  " .placeholder(R.drawable.ic_picture_loading)",Images can be loaded successfully，On the contrary, it is not

Glide.with(this).load("/storage/sdcard0/UCDownloads/20130523b9.jpg").diskCacheStrategy(DiskCacheStrategy.ALL).placeholder(R.drawable.ic_picture_loading).error(R.drawable.ic_picture_loadfailed)
                    .into(imageview);

**Comment by TWiStErRob** [comment]
Try to [add a `.listener()` or enable logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) to see what the error is, if any. Can you please clarifiy if it shows up when `.placeholder()` is set or not?

Also you don't need `ALL`, `RESULT` (default) or `NONE`. If pic is on SD card and you're using `SOURCE` cache (included in `ALL`), the image file will be copied to internal memory taking up 2x space unnecessarily.

**Comment by eicm** [comment]
@Robert it's not usually unnecessary. He may want to disk cache the image
in a certain size on the disk to have a faster load the next time user runs
the app.

**Comment by TWiStErRob** [comment]
Yes, that's what I meant too. I missed an important word there: "use", see the edit.

**Comment by TWiStErRob** [comment]
@eicm You should use a browser client, you're mentioning unknown people: `@Rob` and `@Robert` are real GitHub usernames. I know you mean me, but those are not my user names, you can just leave off the at sign when replying from mail.

**Comment by eicm** [comment]
My bad, didn't know they get notified.

**Comment by rob** [comment]
@eicm @TWiStErRob  - no worries, I'm used to this. :-)

**Comment by sjudd** [comment]
Feel free to re-open if you get the chance to reply to the suggestions above.
