### ISSUE TITLE
Glide Truck Factor

### ISSUE THREAD

**Issue by gavelino** [bumptech/glide#560]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Glide** and obtained a value of **1**.

The developer responsible for this TF is:

Sam Judd - author of 99% of the files 

To validate our results, we would like to ask **Glide** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Glide**?

(b) Do you agree that **Glide** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(b) Does **Glide** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by sjudd** [comment]
Feel free to send me an email to follow up, I don't think this makes sense as a GitHub issue.
