### ISSUE TITLE
How can I contrl Glide's download?

### ISSUE THREAD

**Issue by wangkunlin** [bumptech/glide#566]
In my sample ,I use the GridView to show my pictures,so, I want to load after the GridView scrolled.

**Comment by wangkunlin** [comment]
And in some devices,I'm not indicated the placehoder,it can not show pictures.

**Comment by wangkunlin** [comment]
But if I set the placehoder the picture is stretched.

**Comment by TWiStErRob** [comment]
Sounds like #561, please confirm.

**Comment by wangkunlin** [comment]
Thank you for your answer!
