### ISSUE TITLE
About load the diskcache

### ISSUE THREAD

**Issue by reaper12** [bumptech/glide#567]
HI:
  In ListView or GridView.The ImageView.setScaleType's CenterCrop.If read from the picture from the disk cache will appear deformation, but if read from the memory cache will not

**Comment by TWiStErRob** [comment]
Do you have a placeholder set that is different in size than the ImageView/cropped loaded image?

**Comment by reaper12** [comment]
I didn't set the placeholder. 
If i set asBitmap ,this problem was solve. But it's too limitations.

**Comment by TWiStErRob** [comment]
Can you please share the full Glide.load line and the item layout xml?

**Comment by reaper12** [comment]
This is my Glide code in adapter V3.6.1:
Glide.with(mContext).load(url).into(ivImg); 

This is GridView item xml:
<?xml version="1.0" encoding="UTF-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <ImageView
        android:id="@+id/item_image_selector_ivImg"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:scaleType="centerCrop" />
   
</RelativeLayout>

**Comment by reaper12** [comment]
This problem maybe about default animation.Can you fix it?

**Comment by TWiStErRob** [comment]
There are many issues reported when placeholder is used, because Android's TransitionDrawable can't handle different Drawable sizes and crossFade is the default animation. You can try dontAnimate() as a workaround, but your code doesn't indicate anything weird. Are you loading GIF by any chance? (What is the url?)

**Comment by reaper12** [comment]
tks. I tried .dontAnimate() or .animate(android.R.anim.fade_in) ,this problem was solve.The problem is that crossFade.

**Comment by reaper12** [comment]
Picasso's default animation is crossFade too.But it no problem.So I hope to be able to fix it in the future.

**Comment by TWiStErRob** [comment]
Would it be possible for you to make a mini demo project which shows the problem? Your usage is pretty basic and it should just work. Maybe there's something else making it break.

**Comment by sjudd** [comment]
Picasso does their crossfade in a custom Drawable. As mentioned previously I'd definitely welcome a custom Drawable to do cross fades as well. Pull requests always welcome :).

Let us know if you get the chance to setup a sample project.
