### ISSUE TITLE
How to change the animation when loading images?

### ISSUE THREAD

**Issue by MIkeeJY** [bumptech/glide#568]
The default animation is Alpha 0 to 1,I want to change it,what I should do ?

**Comment by TWiStErRob** [comment]
You can use `.animate(int)` and give it an `R.anim` resource. `fade_in` is what you think you see, but the default is actually `.crossFade()`. You most likely don't have a placeholder so it cross-fades from the background color looking like fade in.

**Comment by MIkeeJY** [comment]
Thanks a lot man :)
