### ISSUE TITLE
Poor NavigationView performance with network image

### ISSUE THREAD

**Issue by frostymarvelous** [bumptech/glide#570]
I have a question open on SO here.
http://stackoverflow.com/questions/31838066/navigationview-lag-with-network-image-using-glide

I have an activity with a viewpager displaying three fragments. The third fragment is a basic recyclerview using a grid layout manager. The grid items are basic image and title items nothing complex and I am using Glide to load images.

The problem is this, when I try opening/closing the NavigationView drawer when on this page, it lags very badly.

This is what I've noticed, the lag only happens when I load an image from a url. Local drawables are fine, and the drawer opens smoothly. I'm at a loss and have no idea where to look anymore.

I tested the same code using Picasso and it works perfectly.

The code to load the image is simple

            Glide.with(vh.getContext())
                    .load(mImageURL)
//                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .error(R.drawable.placeholder)
                    .into(vh.Image);

**Comment by frostymarvelous** [comment]
I solved this issue with `dontTransform()`. I have no idea why it works, or what the default transformation actually does. Can someone shed some light on what might have been going on now that I've found the solution?

Also, this happened on all pages where I had large images, like grids and cards.

**Comment by TWiStErRob** [comment]
I've seen this issue once while scanning SO, buy couldn't make anything of it. Would it possible to recreate this scenario in a sample/opensource app? Once we can reproduce it locally, we can investigate and debug it and figure out what's wrong.

Just to double check: you said this in the SO update:

> I continued debugging and decided to test the same code using Picasso. This time, it works perfectly...

Did you recheck with Glide too?

**Comment by TWiStErRob** [comment]
Heh, I didn't see your update :)
The default transform depends on what scaleType is in the XML.

Can you please check if either dontAnimate() or asBitmap() solves the issue by itself? (i.e. replace don't transform() with these one by one)

**Comment by frostymarvelous** [comment]
I actually came across this code while trying to get to the root of the issue

	if (!isTransformationSet && view.getScaleType() != null) {
		switch (view.getScaleType()) {
			case CENTER_CROP:
				applyCenterCrop();
				break;
			case FIT_CENTER:
			case FIT_START:
			case FIT_END:
				applyFitCenter();
				break;
			//$CASES-OMITTED$
			default:
				// Do nothing.
		}
	}

I did have `CENTER_CROP` initially, so I decided to test without a `scaleType` and transform enabled and what I noticed was, it seems to default to `FIT_END` instead of the default case, so that doesn't help.

I will create a sample app for you to test.

**Comment by frostymarvelous** [comment]
I just noticed this. Seems the drawer is interacting with the image in some way. My suspicion is,  this might be due to the life cycle handling. 

The image shown as black is an errored url. So that's the placeholder being displayed, but we notice it turns black as the drawer is dragged.
On this particular page, I noticed some stuttering when dragging as well. Transform is off.

**Comment by TWiStErRob** [comment]
Even if all visible items are reloaded with Glide (because of the drawer messing with the recycling lifecycle) it shouldn't error, because it should hit the memory cache.
Try to set the error drawable to red or something else, I suspect hardware/software rendering/acceleration.

**Comment by frostymarvelous** [comment]
What I mean is that, the URL is invalid, so it won't load an image no matter what. What is being displayed is the error image.

Also, the stuttering happens just as the image comes into view.

**Comment by frostymarvelous** [comment]
The black image only occurs with the library I am using `de.hdodenhof.circleimageview.CircleImageView`.
Funny thing. using `.error()` the stuttering comes back. And `.dontTransform()` doesn't help neither does `.dontAnimate()`.
As suggested, setting the error drawable to a color works fine. The stuttering has stopped.

I am at my wits end trying to find the cause of these issues. I think I will just finish with the sample and hope you can find the cause.

**Comment by TWiStErRob** [comment]
`CircleImageView` is known to cause problems because of [this line](https://github.com/hdodenhof/CircleImageView/blob/master/circleimageview/src/main/java/de/hdodenhof/circleimageview/CircleImageView.java#L232), when using `crossFade()` (default) `TransitionDrawable` draws the `from` drawable and that's cached, so usually the only the placeholder shows and not the final image. So it's usually a display issue, not a performance one. It's possible that the navigation drawer causes (speculation!) too many invalidations/size changes and `CircleImageView` does too much because it has a non-`BitmapDrawable`.

Does it stutter without `CircleImageView` and without any `dont*()`? That would rule out Glide as the culprit. [Usually I suggest `CircleTransform`](https://github.com/bumptech/glide/issues?q=is%3Aissue+circletransform) to do this kind of thing.

**Comment by frostymarvelous** [comment]
Oh, it's glide alright, it stutters on normal Image views when I don't use dontTransform. 

Only circleimageview changes to black however. 

I suspect like you do that drawer is the cause, but most likely some CPU operation is occurring in glide during the animation of the drawer.

Almost done with the sample.

**Comment by frostymarvelous** [comment]
So I got around to working on this issue again and finally took your suggestion and replaced CircleImageView with CirxleTransform. 

We can safely rule out Glide as the culprit here. It's all CircleImageView.

Among other things, the life cycle was all kinds of messed and there were blank images everywhere.

With CircleTransform it works perfect.
