### ISSUE TITLE
Glide does not load an image that is in a ViewPager pager adapter

### ISSUE THREAD

**Issue by ersen-osman** [bumptech/glide#580]
**Glide Version/Integration library (if any)**: 3.6.1

**Device/Android Version**: HTC One m8 5.01 API 21

**Glide load line**: Glide.with(mContext).load(mImages.get(position).getImageUrl()).centerCrop().into(slideShowImage);

**Layout XML**:

This is the view pager item layout 

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="230dp"
        android:id="@+id/slideShowImage" />
</LinearLayout>
```

This is the layout where the view pager is. Note the image view is just a gradient effect
```xml
    <ScrollView
        android:id="@+id/scrollView"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <android.support.v4.view.ViewPager
                    android:id="@+id/museumImageSlideshow"
                    android:layout_width="match_parent"
                    android:layout_height="230dp" />

                <ImageView
                    android:layout_width="match_parent"
                    android:layout_height="230dp"
                    android:background="@drawable/module_gradient"
                    android:clickable="false" />
```

**Stack trace / LogCat**:
Nothing. I even made a callback and the error or success was not called

Below is the instantiateItem code
```
 @Override
    public Object instantiateItem(ViewGroup container, int position) {
        DebugUtils.Log("instantiateItem");
        LayoutInflater layoutInflater = (LayoutInflater)mContext.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        View itemView = layoutInflater.inflate(R.layout.view_image_slideshow_item,container,false);
        ImageView slideShowImage = (ImageView)itemView.findViewById(R.id.slideShowImage);
        Glide.with(mContext).load(mImages.get(position).getImageUrl()).centerCrop().into(slideShowImage);
        return itemView;
    }
```

The method gets called, the adapter is set and the URL is fine. Not sure whats wrong

**Comment by ersen-osman** [comment]
Gosh so sorry for posting this. Forgot to write the following line in instantiate Item 

container.addView(itemView); 

Sigh

**Comment by TWiStErRob** [comment]
No worries, telling someone about an issue always helps :) even if you find the answer yourself while doing it.

Few tips for layout:
1. This is the place where calling `inflate` with true can work.
2. You could reduce the number of hardcoded sizes if you set height of the `FrameLayout` once and let everything stretch into it with `match_parent`. (You can still use [tools attributes](http://tools.android.com/tips/layout-designtime-attributes) if to set a preview height in the designer.
3. The whole layout can have one less depth if you have the ImageView as the root of the item layout.
