### ISSUE TITLE
Cache an image forever 

### ISSUE THREAD

**Issue by AhmedGamal92** [bumptech/glide#587]
How can I tell glide to cache an image and never delete it from cache.

**Comment by TWiStErRob** [comment]
There's no control over that, and cache is temporary by definition. You can hack and set the cache size to "infinity", but that's an extremely bad idea.

If you want to "cache" something forever, just download it and load it with Glide from there (your own file system File, that can only be cleared by the user, e.g.: `context.getFilesDir()`): you can use `asBytes` or `downloadOnly`.

**Comment by sjudd** [comment]
Let us know if that doesn't answer your question.
