### ISSUE TITLE
show loading on each image in grid view and dissappear image

### ISSUE THREAD

**Issue by yfsx** [bumptech/glide#589]
hi, thanks for share this amaing lib, it really help me tho!

now i'm working on at some apps like pinterest, and i use this lib to load image to my grid view.. but if the image too large, it really takes time for glide to show the images..
i have 2 questions so far :
1. if is possible to show spinning loading until the image show? (in this case, each item in grid view)
2. if i scrolled down the grid view to down, when i go to top page, the image dissappear too :( can we cache the image until we finish the activity?

thanks!

**Comment by TWiStErRob** [comment]
1. You can use a `.placeholder()`, I'm not sure how to animate it though.  
I would suggest the following workaround: add an indeterminate progress bar to the item layout, show it before `Glide.with` and hide it with a `.listener()`.
2. See https://github.com/bumptech/glide/issues/590#issuecomment-132961365  
You can try using `.diskCacheStrategy(ALL)` too, but that may not help just waste disk space for the user.

**Comment by yfsx** [comment]
@TWiStErRob thanks, i will try it. right now im closing this issue
