### ISSUE TITLE
Glide download the same image more than once?

### ISSUE THREAD

**Issue by start141** [bumptech/glide#590]
<img width="1028" alt="qq20150820-1 2x" src="https://cloud.githubusercontent.com/assets/6055764/9375819/e0021caa-4737-11e5-92f9-61f9b6c7fec4.png">

I use stetho+okhttp debug glide, when I scroll listview repeatedly, I see the same image downloaded
more than once.

Is this a bug？

**Comment by start141** [comment]
I think it's stetho's wrong, actually download only once.

**Comment by vipinhelloindia** [comment]
Try using Proxy or Charles Proxy ,

**Comment by TWiStErRob** [comment]
It is possible that Glide downloads the image multiple times.

Glide loads, that are into ImageViews which are scrolled off screen and recycled to show another image, are cancelled. You can reproduce it by loading huge (10MB) images over the wire and scrolling around fast. It's possible that with such a small image the cancel signal reached the Glide process after download but before it was cached.

There's another possibility: your image view sizes are changing between loads. 1px is enough of a change. Glide, by default, caches only the RESULTing image, the on that is resized and downsampled and transformed to match the Target's requirements. So if the view size changes Glide has to re-transform using the original which is not available without SOURCE or ALL caching -> download it again. This is a sensible default covering most frequent use cases, it's up to the user to set the cache strategy if they know they'll need to load multiple sizes of the same image.

**Comment by start141** [comment]
Thanks for your reply.
