### ISSUE TITLE
force for not redirect

### ISSUE THREAD

**Issue by nemati456** [bumptech/glide#594]
Hi 
I Use Glide  and its very good 
but i have a problem how can i force glide for download pic from exactly one url

for example 
i want to download http://domain.com/firstpic.jpg
and domain.com redirect  glide for download http://domain.com/seconpic.jpg
and  i want to force download from firstpic if cant i want to show default pic and not download and show secondpic 

thanks and sorry for my poor english

**Comment by TWiStErRob** [comment]
There's no method for that, but you can achieve any networking logic you want:
 * fork (copy) [HttpUrlFetcher](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java)
 * register a factory for GlideUrl -> InputStream (will replace the [default](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/Glide.java#L246))
 * do the registration via a [GlideModule](https://github.com/bumptech/glide/wiki/Configuration#creating-a-glidemodule)

Note that ModelLoaderFactory creates ModelLoader that creates DataFetcher, see the default classes' flow for more.
