### ISSUE TITLE
Glide with ImageViewTouch and ViewPager to create a mini gallery: Image not showing

### ISSUE THREAD

**Issue by ersen-osman** [bumptech/glide#595]
**Glide Version/Integration library (if any)**: 3.6.1

**Device/Android Version**: Lollipop 

**Issue details/Repro steps/Use case background**:

I am creating a view pager that shows a fragment that contains a ImageViewTouch (it.sephiroth.android.library.imagezoom:imagezoom) to allow the user to pan and zoom etc. 

The problem i have is that the first image loads but when i swipe to the next page the image is not loaded. 

This is my view pager adapter
```java
private static class FullScreenImagePagerAdapter extends FragmentStatePagerAdapter {

        private ArrayList<Image> mImages;

        public FullScreenImagePagerAdapter(FragmentManager fm, ArrayList<Image> images) {
            super(fm);
            this.mImages = images;
        }

        @Override
        public Fragment getItem(int position) {
            return FullScreenImageFragment.newInstance(mImages.get(position).getImageUrl());
        }

        @Override
        public int getCount() {
            return mImages.size();
        }
    }
```

This is my fragment 

```java
public static class FullScreenImageFragment extends BaseFragment {

        private ImageViewTouch mFullScreenImage;

        public static FullScreenImageFragment newInstance(String imageUrl) {
            FullScreenImageFragment fullScreenImageFragment = new FullScreenImageFragment();
            Bundle args = new Bundle();
            args.putString(BundleConstants.IMAGE_URL, imageUrl);
            fullScreenImageFragment.setArguments(args);
            return fullScreenImageFragment;
        }

        @Nullable
        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
            View view = inflater.inflate(R.layout.fragment_full_screen_image, container, false);
            mFullScreenImage = (ImageViewTouch) view.findViewById(R.id.fullScreenImage);
            mFullScreenImage.setDisplayType(ImageViewTouchBase.DisplayType.FIT_TO_SCREEN);
            return view;
        }

        @Override
        public void onActivityCreated(@Nullable Bundle savedInstanceState) {
            super.onActivityCreated(savedInstanceState);
            DebugUtils.Log("onActivityCreated " + this.getClass().hashCode());
            DebugUtils.Log("Image URL = " + getArguments().getString(BundleConstants.IMAGE_URL));

```

**Glide load line**:

NOTE this is occurs in onActivityCreated of the fragment code snippet seen above
NOTE 2: I omitted the get Arguments line because its long and shortened it to imageURL in the load call 

```java
 Glide.with(getActivity()).load(imageURL).asBitmap().into(new SimpleTarget<Bitmap>(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL) {
                @Override
                public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                    DebugUtils.Log("onResourceReady " + this.getClass().hashCode());
                    mFullScreenImage.setImageBitmap(resource, null, 1f, 3f);
                }

                @Override
                public void onLoadFailed(Exception e, Drawable errorDrawable) {
                    DebugUtils.Log("onLoadFailed " + this.getClass().hashCode() + " error was " + e.getMessage());
                }
            });
```

**Stack trace / LogCat**:

Nothing: According to the logs i wrote, onResouceReady is called twice. The URLs are different but the hash codes are the same for the fragment which they are called in. 

**Layout XML**:

This is the layout of the fragment 

```xml
<?xml version="1.0" encoding="utf-8"?>
    <it.sephiroth.android.library.imagezoom.ImageViewTouch xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/fullScreenImage"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
```

**Comment by TWiStErRob** [comment]
Re double load: Careful, `this.getClass().hashCode() == "...FullScreenImageFragment".hashCode()`:
 1. try without `.getClass()`, but just using the built-in `toString` may give you even better info.
 1. Is `onActivityCreated` called twice for the same fragment?

Re image not shown:
 1. Add a `.listener()` and log all arguments in both methods then `return false`
 1. Try with stock ImageView (just for diagnostic, don't change anything else)
 1. Try `.dontTransform()`
 1. Try `.dontAnimate()`, though this last one may be pointless for asBitmap.

**Comment by ersen-osman** [comment]
Thank you for the reply.

Log statements is now:

```
onActivityCreated FullScreenImageFragment{277becca #0 id=0x7f0d0070}
onActivityCreated FullScreenImageFragment{2b91304 #1 id=0x7f0d0070}

onResourceReady {PACKAGE_OMITTED)FullScreenImageActivity$FullScreenImageFragment$1@17bd4b22

onResourceReady {PACKAGE_OMITTED)FullScreenImageActivity$FullScreenImageFragment$1@29d4d317

```

1. Not sure how to add a .listener

2. Stock image view worked. Both images display and i can switch pages

3. and 4. dontTransform and dontAnimate had no effect with ImageViewTouch

It looks like its the ImageViewTouch library causing the problem

**Comment by ersen-osman** [comment]
Solved the issue, not sure why it works but for the fragment layout, i put the ImageViewTouch as a child of a frame layout and now the images display fine.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <it.sephiroth.android.library.imagezoom.ImageViewTouch
        android:id="@+id/fullScreenImage"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</FrameLayout>
```

**Comment by TWiStErRob** [comment]
You can just call .listener() and pass in a new inner class implementing RequestListener, the same way you did with .into() and SimpleTarget. Listener must be before into.

In your log you have `FullScreenImageFragment$1` which is misleading, it's logging the Target's toString. Try `FullScreenImageFragment.this` instead of just `this` to access the enclosing fragment object.
