### ISSUE TITLE
Glide not loading image from memory at the first time when rotating (orientation change) 

### ISSUE THREAD

**Issue by oznus** [bumptech/glide#598]
Glide not loading image from memory at the first time when rotating (orientation change), and after that it is loading from memory.

I have tried to increase the memory size, the bitmap pool size, all kinds of caching strategies... nothing seemed to work...

I have attached a video.

https://youtu.be/szDnAGxrJLU

Thanks!

**Comment by TWiStErRob** [comment]
Disk and memory cache can only be hit if all parameters match. These parameters are: url, most of the methods after `Glide.with().load()`, and target size. I guess your mismatch is the target size, the same color lines must match down to pixel to hit caches (I see aspect ratio differences, so I guess they are different in size):
![matching](https://cloud.githubusercontent.com/assets/2906988/9508142/88c5dde8-4c53-11e5-9a78-2800b7ebf7e3.png)

You can achieve that by:
 * using fixed sizes in xml, e.g. with `@dimen/list_thumb_width`, however this means hardcoding sizes
 * using `override(width, height)` to ask for a certain sized image, in this case it doesn't matter how big the actual ImageView is so you can load the biggest possible thumbnail always and let the ImageView do an additional center crop on it. You can also mix-match: `android:scaleType="centerCrop"` and `.fitCenter().override()` with Glide; I think this will give the most flexible results.

**Comment by TWiStErRob** [comment]
You can verify sizes most easily by [enabling logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging) for `TransformationUtils` and `Engine`.

**Comment by oznus** [comment]
Thanks It definitely answers the question. i used the override and now it works.

Thanks for the quick replay!

**Comment by TWiStErRob** [comment]
Crosslink to SO: http://stackoverflow.com/q/32237368/253468

**Comment by Kolyall** [comment]
I suggest you also to check your custom `BitmapTransformation`, it should contains `equals` and `hashCode` methods
