### ISSUE TITLE
load picture sometime show black

### ISSUE THREAD

**Issue by naiyu** [bumptech/glide#599]
I load picture with the code 

`Glide.with(mContext).load(caseDetail.getPicInfo().getImage()).crossFade(250).placeholder(R.color.pic_load).error(R.color.pic_load).into(holder.ivPic);`

but it sometimes happe ton black block, some the like [the picture](https://plus.google.com/u/0/photos/117861125674754335155/albums/6187610208764710769) , how can I fix the problem?

**Comment by TWiStErRob** [comment]
I guess black is `drawable.pic_load`, or the image there is wrong. First download the URL that's wrong on your computer and check it manually if it loads. Then check the debugging wiki, I suggest you attach a `.listener()` and log all arguments to see what's happening with which load.

What customisations do you use? cache, other globals settings. Glide version? Is the image View extend `ImageView`?

**Comment by naiyu** [comment]
the drawable pic_load is not black, and the url is right, while the item return to visiable, it shows the right picture, but sometimes it will show the black block.

I use the version 3.6.1, and the globals setting is `PREFER_ARGB_8888`, the view is ImageView

**Comment by TWiStErRob** [comment]
I'm sorry, right now I don't have any more ideas, it's mostly the `crossFade()` or `CircularImageView`s (and other `x extends ImageView` classes) that can cause the problem.
Can you please add the listener() and try to reproduce it? Once reproduced you may be able to see something from the logs. Or if you can reproduce consistently, try to make a small sample app for us to try it with.

**Comment by sjudd** [comment]
If nothing else, it's possible this is a Bitmap re-use issue. But barring more code or a sample app we can't do much. Definitely feel free to re-open if you find a way to reproduce this.

**Comment by dgaurav-163** [comment]
I am still facing same issue. black area show when it could not be load success. Any solution for this?
