### ISSUE TITLE
Caching images with dynamic url

### ISSUE THREAD

**Issue by LPFinch** [bumptech/glide#607]
Hi, folks.
I need to cache images with dynamic url. I have 2 methods .getImageId() and .getImageUrl();
I need to cache my downloaded images with getImageId() key, because this id is unique and image url change all time.
How to set custom image id to cache? Please show me a way. Thanks.

**Comment by diego04** [comment]
+1

**Comment by Shusshu** [comment]
+1

**Comment by sjudd** [comment]
In Glide 3 you can create your own ModelLoader and DataFetcher. DataFetcher's getId() method is used as the cache key, so you can implement it however you wish. Using urls, the simplest way to do this is to write a simple wrapper for the existing ModelLoader<GlideUrl, InputStream> that delegates all methods but getId(). 

Alternative you can copy/paste and customize Glide's existing ModelLoader for GlideUrls and override the getId() method the same way.

In Glide 4.0, ModelLoader's provide a Key to use as the primary identifier in the cache keys. In Glide 4 you can just create a custom ModelLoader and return a [LoadData][1] with your custom cache key and the rest of the fields filled out by a delegate ModelLoader. 

[1]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/ModelLoader.java#L46

**Comment by LiHanGuang** [comment]
How about like this?  @LPFinch 

package com.jiahe.qixin.utils;

import com.bumptech.glide.load.model.GlideUrl;
import com.bumptech.glide.load.model.Headers;
import com.jiahe.qixin.threadsupport.utils.Preconditions;

import java.net.URL;

public class GlideUrlWithToken extends GlideUrl{
    private String mToken;
    private String mSourceUrl;

    public GlideUrlWithToken(String url, String token) {
        super(new StringBuilder(url)
                .append(url.contains("?") ? "&token=" : "?token=") //already has other parameters
                .append(token) // append the token at the end of url
                .toString());

        Preconditions.checkNotNull(url);
        Preconditions.checkNotEmpty(url);

        Preconditions.checkNotNull(token);
        Preconditions.checkNotEmpty(token);

        mSourceUrl = url;
        mToken = new StringBuilder(url.contains("?") ? "&token=" : "?token=").append(token).toString(); //record token
    }

    @Override
    public String getCacheKey() {
        return mSourceUrl;
    }

    @Override
    public String toString() {
        return mSourceUrl + mToken;
    }
}

**Comment by TWiStErRob** [comment]
In case anyone wonders how to use
the above: `Glide.with(...).load(new GlideUrl("http://....", token)).into(imgView)`.

Also instead of duplicating logic you can probably remove mToken and use toString: `return super.getCacheKey()` which should return the value given to super in ctor.

**Comment by LiHanGuang** [comment]
@TWiStErRob 
I see , thanks.

**Comment by TWiStErRob** [comment]
The above code is a solid solution, but see #501 also for more discussion.
