### ISSUE TITLE
downloadOnly with transform

### ISSUE THREAD

**Issue by pftbest** [bumptech/glide#608]
Hi, I'm using the code from #459 to share the image:
```kotlin
override fun doInBackground(vararg params: Unit?): File? {
    try {
        return Glide
                .with(context)
                .load(good.previews[0])
                .downloadOnly(100, 100)
                .get() // needs to be called on background thread
    } catch (ex: Exception) {
        warn("share failed, msg: ${ex.getMessage()}, good: $good")
        return null;
    }
}
```
But for some reason I'm getting the original full size 1200x1200 webp image, instead of small 100x100 jpeg image.
And it looks like I can't apply any transformations to it, if I do, `downloadOnly` becomes unresolved reference.

**Comment by sjudd** [comment]
This is definitely a bit confusing, sorry for that. Download only means exactly that, the original data is downloaded directly to disk. Transformations are not applied. 

The width and height are passed to downloadOnly so that if you use a custom ModelLoader and have a server that can bucket image sizes, you download the expected size.

**Comment by pftbest** [comment]
Hi, thanks for reply. Is there any other way get transformed image file? Or should I use `.into`, get the Bitmap and save it myself?

**Comment by sjudd** [comment]
You can use a [ResourceTranscoder][1], but even then, the file won't be in our cache. You'd need to pick somewhere else to save it. Starting another async task in into() to save the file is also fine.

[1]: http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/load/resource/transcode/ResourceTranscoder.html

**Comment by pftbest** [comment]
In the end, I'm saving file on the external storage using async task. Thanks for your help, this issue can be closed.

**Comment by sjudd** [comment]
Great thanks for the follow up.
