### ISSUE TITLE
OOM in Android 4.1 caused by ARGB_8888 even if PREFER_RGB_565

### ISSUE THREAD

**Issue by ypresto** [bumptech/glide#611]
### Summary

Glide fails to load bitmap with OutOfMemory because of `ARGB_8888` is used even when `PREFER_RGB_565`.

As #129 glide always uses `ARGB_8888` in Android 4.1 to prevent image skewing, but it is unclear and also has significant impact on memory consumption.

I think it'll be better to remove this logic (and use `PREFER_ARGB_8888` if image skewing is occur), or to provide something like `ENFORCE_RGB_565` option.

### Detail

We have several 720x720 ImageViews in ViewPager and it holds 2MB sized byte arrays (720x720x32bit/8).
To reduce this, I copied and modified Downsampler class to always return `RGB_565`, but is very inefficient way to fix it.

```java
                ...
                .asBitmap()
                .imageDecoder(new StreamBitmapDecoder(
                        AlwaysRGB565Downsampler.AT_LEAST,
                        Glide.get(mContext).getBitmapPool(),
                        DecodeFormat.PREFER_RGB_565
                ))
                ...
```

Note that we have just moved from Universal Image Loader which always uses RGB_565 (if specified) and **we don't have any image skewing reported by users** (we only use JPEG).

It is not Glide 3.x specific issue because same logic is used in master branch.

https://github.com/bumptech/glide/blob/f10b02990f735ef9221f3441afdffefac826f025/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L349

**Comment by sjudd** [comment]
Unfortunately we can't tell when skewing will or won't occur on 4.1 devices. We can either not  re-use Bitmaps, or use ARGB_8888. ARGB_8888 seems like the lesser of the two evils. If you're ok with skewing or have gotten lucky enough to avoid it (it seems to be at least partially dependent on image sizes), then I think your solution here is reasonable. 

The OOM usually indicates an issue with the app itself. Either it's using too much memory, has a memory leak, or has Glide configured to use too much memory (you may want to adjust the defaults). Memory leaks are the most common reason.

**Comment by TWiStErRob** [comment]
In addition to Sam's comments, double check the number of off-sceen pages in the ViewPager, it may be too high.

**Comment by floating-cat** [comment]
A workaround:
You can use `android:largeHeap="true"` in you AndroidManifest.xml.

**Comment by ypresto** [comment]
> ARGB_8888 seems like the lesser of the two evils.

I see, it is reasonable, but... omg BOTH are evil... :(

> off-sceen pages

I found it was too high and already reduced it. :)

> `android:largeHeap="true"`

It seems to be time to consider it, although I have managed to keep from enabling it.
I'll test our app with that flag is enabled.

Thank you for replies..!

**Comment by sjudd** [comment]
Sure let us know if you have more questions.
