### ISSUE TITLE
load image crash log

### ISSUE THREAD

**Issue by specialren** [bumptech/glide#612]
SIGBUS(BUS_ADRERR): SIGBUS
#00 pc 00018f84 /system/lib/libjavacore.so (_Z44register_libcore_io_AsynchronousCloseMonitorP7_JNIEnv +23)
#00 lr 0005b640 /system/lib/libdvm.so (dvmPlatformInvoke +23)
java:
libcore.io.Memory.peekByte(Native Method)
java.nio.MemoryBlock.peekByte(MemoryBlock.java:189)
java.nio.DirectByteBuffer.get(DirectByteBuffer.java:167)
com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$ByteBufferReader.int getByte()
com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$ByteBufferReader.int getUInt16()
long skip(long)
int read(byte[],int)
com.bumptech.glide.load.resource.bitmap.ImageHeaderParser.com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$ImageType getType()
com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder.boolean handles(java.nio.ByteBuffer,com.bumptech.glide.load.Options)

catch this crash...

**Comment by TWiStErRob** [comment]
Can you please fill in the issue template, a stack trace in itself is usually not enough to diagnose: https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues

**Comment by sjudd** [comment]
Let us know when you fill out the issue template.
