### ISSUE TITLE
When download too many large images ,downloaded images sometimes are not displayed

### ISSUE THREAD

**Issue by c1024** [bumptech/glide#614]
I am new to Glide,.
but some images were not displayed in the list which downloaded successful, while displayed well when using Android-Universal-Image-Loader.
Any idea how to solve this, Thanks a lot.

These are where and how i used Glide:

Code in the adapter:
```java
Glide.with(mActivity).load(list.get(position)).placeholder(R.drawable.no_img_head_small).override(300 ,300)listener(new RequestListener<String, GlideDrawable>() {
			@Override
			public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
				e.printStackTrace();;
				return false;
			}

			@Override
			public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
				
				return false;
			}
		}).diskCacheStrategy(DiskCacheStrategy.ALL).into(holder.img);
```
When image not display, the listener's onException not called ;
Code int the layout file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/iv_category_detail_sgv_item"
    android:layout_width="match_parent"
    android:layout_height="200dp"
    android:scaleType="fitStart" >
</ImageView>
```

**Comment by c1024** [comment]
I am using the latest jar 3.6.1.
I test my code on Nexus 7 Android 4,4 , Nexus 5 Android 5.1.

**Comment by TWiStErRob** [comment]
`onException`'s Exception variable may be `null` which usually indicates that the model is `null`. Check if `list.get(position)` is not null.

**Comment by sjudd** [comment]
And also provide any stack traces you might see printed when the loads fail?

**Comment by sjudd** [comment]
Let us know if you get the chance to answer our questions.
