### ISSUE TITLE
View recycle causes multiple loads in same view if scrolled really fast in a grid

### ISSUE THREAD

**Issue by kaivnlp** [bumptech/glide#62]
If i have really big grid say with 500 items and i scroll really fast  Glide asynch load obviously lags (that is the as expected) , but as soon as scrolling stops Glide tries to load urls in the one grid cell one by one multiple times.

I am sure there is elegant solution that you can suggest and pardon my ignorance here.

One idea was to use viewholder and set a position variable which can be checked by glide each time before loading.but i am not sure where i can do that in Glide , in requestlistener?

thanks for help

**Comment by deadlydragon00** [comment]
Is this still an active thread?

**Comment by sjudd** [comment]
It's a year old :). If you'd like to report something it's probably worth opening a new issue.

**Comment by deadlydragon00** [comment]
Hi Sam thanks for the quick reply and being adorable :) I just wanna answer answer the question above but I think it is already resolve :).

**Comment by vovaksenov99** [comment]
@sjudd Realy nice solution! Could you explane principle of this operation more detail?
