### ISSUE TITLE
How can I set the connection timeout times ?

### ISSUE THREAD

**Issue by ruijun** [bumptech/glide#621]
Hello, When I use Glide like this:

  Glide.with(context)
                .load(glideUrl)
                .asBitmap()
                .fitCenter()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .error(R.drawable.ic_failed)
                .into(new BitmapImageViewTarget(photoView){

                    @Override
                    public void onLoadCleared(Drawable placeholder) {
                        super.onLoadCleared(placeholder);

                    }

                    @Override
                    public void onLoadStarted(Drawable placeholder) {
                        super.onLoadStarted(placeholder);

                    }

                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {

                    }

                    @Override
                    public void onLoadFailed(Exception e, Drawable errorDrawable) {
    
                    }
                });

How can I set the connection timeout times ?

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/issues/520#issuecomment-118007533.
Subscribe to #432 to get updates on progress.
Tip: You can just say `into(photoView)` and use a `.listener()` if you want to do extra work, that's more flexible and safe.

**Comment by ruijun** [comment]
@TWiStErRob thank you
