### ISSUE TITLE
How to clear cache

### ISSUE THREAD

**Issue by nvhaiwork** [bumptech/glide#624]
Hi, 
How can I clear Glide's cache in case.
+ Clear all cache
+ Clear cache of an URL.

**Comment by TWiStErRob** [comment]
* Call `Glide.get(context).clearDiskCache()` on outside the UI thread.
 * Read [Cache invalidation](https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation), because it's not otherwise possible to remove a single file from cache, see #94 for arguments. If you explain your "Clear cache of an URL" use case we may be able to give a better suggestion.

**Comment by nvhaiwork** [comment]
"Clear cache of an URL".
I have an Image to display user's profile image. 
Then after user changes his(her) profile image I want to refresh to display the new uploaded image.

**Comment by TWiStErRob** [comment]
Yep, then `.signature()` is your best friend. Save the latest upload time to the profile image along with the image and use something like:
```java
.load(model.profileImageUrl)
.signature(new StringSignature(model.profileLastUpdate))
```

**Comment by nvhaiwork** [comment]
Thanks for you support.
One more question, is there any other solution incase I do not have "profileLastUpdate".
Just have image' url only. And I want to cache an image until new update

**Comment by nvhaiwork** [comment]
Also I already used clearDiskCache but image was not refreshed.
''' 
                boolean isSuccess = upload image api;
			if (isSuccess) {

				Glide.get(getActivity()).clearDiskCache();
				Glide.get(getActivity()).clearMemory();
			}
'''

**Comment by TWiStErRob** [comment]
Options:

 1. You can use the file's lastModified time if you can modify the server response

 1. Use a regular interval like daily or weekly: that is the signature changes every day:

    ```java
    .signature(new StringSignature(System.currentTimeMillies() / (24 * 60 * 60 * 1000)))
    ```

 1. Store the profile update yourself in the app, but this doesn't work if you display other people's profile, because then you'd need to sync the DBs which is much more cumbersome then modifying the way the app receives the profile url.

**Comment by TWiStErRob** [comment]
> image was not refreshed

you also need to reload the image using the usual `Glide.with.load.into` **after** the clears finish.

**Comment by nvhaiwork** [comment]
I already used cleardiskcache but image was not refreshed.
My code:
'''boolean isSuccess = new UserApi().doUploadImage(mUser.getId().getOid(), strUploadType);
			if (isSuccess) {

				Glide.get(getActivity()).clearDiskCache();
				Glide.get(getActivity()).clearMemory();
			}
'''

Then :
''' Glide.with(ctx).load(strProfileUrl).dontAnimate().placeholder(R.mipmap.ic_launcher).into(imvProfile);''''
But no luck

**Comment by TWiStErRob** [comment]
Do you use an integration library?

**Comment by nvhaiwork** [comment]
I'm not sure what is "integration library"
But I'm using 
'''
compile 'com.github.bumptech.glide:glide:3.6.1'

for import library. I'm new to Glide :D

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Integration-Libraries
I was asking because there may be a caching issue somewhere in the pipeline. The server can cache the response (return old profile image for a while even after update), a proxy can cache the response, the networking library on the client (in this case android app) can cache and finally Glide can cache (this is what you surely fixed with `.clear*`).
Make sure the `Glide.with.load.into` is called after, because they're run on different threads. `into` is called on UI thread and `clear`s must be on background threads.

**Comment by nvhaiwork** [comment]
'''
private class UploadImageAsyncTask extends AsyncTask<Void, Void, Boolean> {

		@Override
		protected void onPreExecute() {
			super.onPreExecute();
			
		}

		@Override
		protected Boolean doInBackground(Void... voids) {

			
			boolean isSuccess = upload api;
			if (isSuccess) {

				Glide.get(getActivity()).clearDiskCache();
				Glide.get(getActivity()).clearMemory();
			}

			return isSuccess;
		}

		@Override
		protected void onPostExecute(Boolean aBoolean) {
			super.onPostExecute(aBoolean);

			if (aBoolean) {
// Url				Glide.with(fragment).load(strCoverUrl).dontAnimate().placeholder(R.drawable.img_splash_bg).into(imvCover);
			}
		}
	}
'''

**Comment by nvhaiwork** [comment]
```
private class UploadImageAsyncTask extends AsyncTask {

    @Override
    protected void onPreExecute() {
        super.onPreExecute();

    }

    @Override
    protected Boolean doInBackground(Void... voids) {


        boolean isSuccess = upload api;
        if (isSuccess) {

            Glide.get(getActivity()).clearDiskCache();
            Glide.get(getActivity()).clearMemory();
        }

        return isSuccess;
    }

    @Override
    protected void onPostExecute(Boolean aBoolean) {
        super.onPostExecute(aBoolean);

        if (aBoolean) {
// Url Glide.with(fragment).load(strCoverUrl).dontAnimate().placeholder(R.drawable.img_splash_bg).into(imvCover);
}
}
}
```

Sure load image after clear cache.
The image just refreshed if I force close my app(close app by 'recent view').

**Comment by TWiStErRob** [comment]
How do you load it normally when you first show the fragment?
Also the line is commented out, I hope it's not like that in your running code ;)

**Comment by nvhaiwork** [comment]
How do you load it normally when you first show the fragment?
```
Glide.with(fragment).load(strCoverUrl).dontAnimate().placeholder(R.drawable.img_splash_bg).into(imvCover);
```

Also the line is commented out, I hope it's not like that in your running code ;)
=> Sure :D

**Comment by TWiStErRob** [comment]
Hmm, maybe Glide checks if the new load is any different than the currently loaded image and ignores the new one if the same. I can't back this up with code though.

You could try calling `Glide.clear(imvCover)` in `onPostExecute -> if (aBoolean) {` just before the load and see if that helps. The image will probably flash the placeholder as usual. As a workaround for the flash you can also try:
```java
Drawable oldImage = imvCover.getDrawable(); // may be unsafe
Glide.clear(imvCover);
Glide.with(fragment).load(strCoverUrl).dontAnimate().placeholder(oldImage).into(imvCover);
```

Before you try this I suggest you add `.listener`s, logging the arguments to LogCat, to all loads into `imvCover` to see what's going on, maybe there's a hidden exception there.

Sorry for the hacky workarounds, I can't come up with other ideas yet.

**Comment by nvhaiwork** [comment]
Thanks for your help.
I need to go out now, I'll try and let you know the result. 
Thanks :D

**Comment by nvhaiwork** [comment]
Debugged 
``` 
@Override
					public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target,
							boolean isFromMemoryCache, boolean isFirstResource) {
						return false;
					}
``` 

and saw that: isFromMemoryCache = true even cache is cleared before.
Hummmmm

**Comment by TWiStErRob** [comment]
Let's invoke @sjudd!

**Comment by sjudd** [comment]
Is the resource you're about to reload already being displayed in a ``View`` or ``Target``? If so, it may be loaded from active resources, which is checked prior to the caches. 

If you want to change the user's profile picture and reload it, either change the url when the the profile picture changes, or use the ``.signature()`` API and some kind of version key identifying the particular version of the profile photo. Using the signature API is described in [the wiki][1].

[1]: https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation

**Comment by nvhaiwork** [comment]
@sjudd : Thanks for your suggestion, I solved it my problem with .signature.
But I still worrying about cache problem that noticed above. I already called clearDiskCache and memoryCache but the image was still loaded from cache

**Comment by TWiStErRob** [comment]
It's not loaded from disk or memory cache, it's loaded from active resources, which are the images currently showing in views. Since nothing has changed according to Glide (i.e. cache key) it assumes that the current image is the same as what you're loading. Clearing the cache is a brute force method which is not advised, especially because only one image changed. Using `.signature()` should solve the problem by itself without clearing anything; use it for both initial and after-change load.

**Comment by sjudd** [comment]
Yup, signature is a much better solution. Let us know if you have any other questions.

**Comment by maximeloridan** [comment]
Hello,

I had the same problem, so I read carefully all this post.
I wanted to implement the signature method, but it does not work on my phone.

So I tested with the simplest activity possible. When I click on a button it does this:

toto = toto +1;
                Glide.with(getApplicationContext())
                        .load("http://mydomain.com/picts/1234")
                        .signature(new StringSignature(Integer.toString(toto)))
                        .centerCrop()
                        .into((ImageView) findViewById(R.id.imageView));

So each time I click on a button, the signature is different (toto has been incremented). So before clicking on the button, I change the picture on my server to see the change.

It does not work on my phone, so I tried with the emulator (nexus 5) and it does work!

(Nota: Moreover I tried to add a listener "onResourceReady" to check "boolean isFromMemoryCache, boolean isFirstResource". isFromMemoryCache is set to false and isFirstResource is set to true. Which seems OK, but it always display the same picture on my nexus 4...)

Have you an idea why the exact same code does work on the emulator (nexus 5, android 5.1) and does not on my nexus4 (android 5.1.1, build LMY48M).
Have you tried on a nexus 4, android 5.1.1 ?

Thank you

Nota: I used "compile 'com.github.bumptech.glide:glide:3.6.1'"
Nota: Nothing appears on logcat

**Comment by TWiStErRob** [comment]
Let's not hijack this issue (especially since it's closed) as I can't give you a straight answer, can you please move your comment to a new issue and edit the above to be just a link there? Check out how to open a [new issue with our template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues).

**Comment by kimgod** [comment]
I think that should use clearMemory() and clearDiskCache()  together ......

**Comment by TWiStErRob** [comment]
@kimgod can you please elaborate on that? What are you responding to?
(Note: in general you shouldn't ever call those methods during normal app operation)

**Comment by CoXier** [comment]
However I use `clearCache` but it does not work for me

**Comment by amazingguni** [comment]
I met the same problem and got the answers from the comments. Thank you :+1: 
```java
Glide.with(context).load(Uri.parse(userProfile.getProfileImageUri()))
                                .signature(new StringSignature(Long.toString(System.currentTimeMillis()))).centerCrop()
                                .into(profileImageImageView);
```

**Comment by TWiStErRob** [comment]
@amazingguni that's not right... whatever your goal is. Any time you load the image it'll be cached in a separate file using a lot of network, CPU and disk space.

It essentially turns off caching, you should use `.diskCacheStrategy(NONE)` to do that, this removes the disk pressure from the picture. If you want to force loads in the same session to refresh the profile image as well you can also add `.skipMemoryCache()`. I really think you should consider dividing the millis with an interval of invalidation, even if it's just a few hours. Consider that the common thing to happen is to have the same profile image for years.

**Comment by amazingguni** [comment]
I'll try to use `skipMemoryCache()`, after changing profile image. Thank you for your kind explanation.

**Comment by jp1017** [comment]
> ```java
> StringSignature
> ```

where's StringSignature?

**Comment by TWiStErRob** [comment]
@jp1017 https://github.com/bumptech/glide/issues/2692
