### ISSUE TITLE
downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL) will cache the file to Memory?

### ISSUE THREAD

**Issue by LiHanGuang** [bumptech/glide#626]
Hello @TWiStErRob:

Code:

GlideUrl glideUrl = new GlideUrlWithToken(url, PrefUtils.getDownloadToken(context));
FutureTarget<File> futureTarget = Glide.with(context)
     .load(glideUrl)
     .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);

Question:
1. Is the downloadOnly(int w, int h) method will cache the file to memory when the first download had already finished ?
2. if downloadOnly(int w, int h) will cache the file ito memory, can i skip memory cache for that?

**Comment by TWiStErRob** [comment]
See [com.bumptech.glide.GenericTranscodeRequest#getDownloadOnlyRequest](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/GenericTranscodeRequest.java#L99):
```java
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .skipMemoryCache(true)
```

**Comment by LiHanGuang** [comment]
@TWiStErRob

**Comment by sjudd** [comment]
Let us know if we can help further.
