### ISSUE TITLE
v3.6.1 not work correctly with shared element transition

### ISSUE THREAD

**Issue by boxcounter** [bumptech/glide#627]
What I want (and most of the time glide works correctly like this):

![correct](https://cloud.githubusercontent.com/assets/4317474/9870620/305bdaaa-5bc0-11e5-892e-e7f7995a4d56.png)

But some times it's like:

![wrong](https://cloud.githubusercontent.com/assets/4317474/9870640/60bb3c2c-5bc0-11e5-9acd-fce4044b091f.png)

Code snippet:

```java
mBackgroundView = (ImageView) findViewById(R.id.iv_background);
String url = "file:///android_asset/covers/5.png"
Glide.with(fragment).load(url).dontAnimate().dontTransform().into(mBackgroundView);
```

Layout:

```xml
    <android.support.design.widget.AppBarLayout
        android:id="@+id/appbar_layout"
        android:layout_width="match_parent"
        android:layout_height="240dp"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        android:fitsSystemWindows="true"
        >

        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:fitsSystemWindows="true"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:contentScrim="?attr/colorPrimary"
            >

            <ImageView
                android:id="@+id/iv_background"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fitsSystemWindows="true"
                android:scaleType="centerCrop"
                app:layout_collapseMode="parallax"
                app:layout_collapseParallaxMultiplier="0.7"
                />

            <android.support.v7.widget.Toolbar />
                ...
                />

        </android.support.design.widget.CollapsingToolbarLayout>

    </android.support.design.widget.AppBarLayout>
```

**Comment by sjudd** [comment]
I haven't actually used shared element transitions. That said, I'd guess what's happening is that in some cases your ImageView's width and height is at least temporarily assigned to some value smaller than the screen. Glide will then see that, and along with CenterCrop, resize the image down to much smaller than you want. 

Although it may not be the best long term solution, does using override() and specifying a larger size help?

**Comment by nglro** [comment]
Call supportPostponeEnterTransition() in Activity,onCreate()

Add a listener to glide request and when Glide finishes loading the image call Activity.supportStartPostponedEnterTransition() in listener.onResourceReady()

**Comment by TWiStErRob** [comment]
Closing this in favor of #502.

**Comment by DionWangX** [comment]
have good idea to solve it?
