### ISSUE TITLE
How to forbid the Glide download the pictures when I have wifi?

### ISSUE THREAD

**Issue by feng9902535** [bumptech/glide#629]
How to forbid the Glide download the pictures when I Use 3/4g ,and if you have caching images show the cache images?

**Comment by TWiStErRob** [comment]
Take a look at https://groups.google.com/d/topic/glidelibrary/TcFOy0tcxXA/discussion

The key is that you have to match size, url and other key elements to make a cache hit. If it hits it won't try. The code in the post on June 12 in the above forum shows you how to disable the networking element for a particular load. So the result is:
 * cache hit -> display
 * cache miss -> tries to load null stream (fallback/error is displayed)

**Comment by feng9902535** [comment]
Hi Rob，
 I find this way to solve the problem,but i have a error when i use "using",and i can't find "StreamModelLoader".

Glide version:glide-3.6.1

Thanks!
feng
//
Glide.with(activity)
        .using(new StreamModelLoader<String>() {
            @Override
            public DataFetcher<InputStream> getResourceFetcher(final String model, int i, int i1) {
                return new DataFetcher<InputStream>() {
                    @Override
                    public InputStream loadData(Priority priority) throws Exception {
                        throw new IOException();
                    }

                    @Override
                    public void cleanup() {

                    }

                    @Override
                    public String getId() {
                        return model;
                    }

                    @Override
                    public void cancel() {

                    }
                };
            }
        })
        .load(urlStr)
        .diskCacheStrategy(DiskCacheStrategy.ALL)
        .into(imageView);

**Comment by TWiStErRob** [comment]
Any IDE's "organize import" command should find it: https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/model/stream/StreamModelLoader.java

**Comment by feng9902535** [comment]
yes，but  the method of "useing"  has error

**Comment by TWiStErRob** [comment]
What's the error?

**Comment by feng9902535** [comment]
Do you received my two gif files?please try them.

**Comment by TWiStErRob** [comment]
I think you didn't wait until they were uploaded, before pressing the comment button. I also don't have computer access for a while.

**Comment by feng9902535** [comment]
It's done，please have a try.

**Comment by TWiStErRob** [comment]
If they show as square probably your placeholder is square, see #363.

**Comment by feng9902535** [comment]
Hi Róbert Papp , Long time no see，you know the lasted version of Glide is 4.0，and this version  abandoned ‘using’。so ，Can you tell me how to solve this issue on this version？

**Comment by sjudd** [comment]
@feng9902535 use [``onlyRetrieveFromCache()``][1] in Glide v4.

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/request/RequestOptions.html#onlyRetrieveFromCache-boolean-
