### ISSUE TITLE
Images are stretched like fitxy scaletype

### ISSUE THREAD

**Issue by niteshkhatri** [bumptech/glide#630]
Hi, I have a RecyclerView with GridLayoutManager to show images from resources in the ImageView.

        mRecyclerView = (RecyclerView) view.findViewById(R.id.image_recyclerview);
        mRecyclerView.setHasFixedSize(true);
        // The number of Columns
        RecyclerView.LayoutManager mLayoutManager = new GridLayoutManager(getActivity(), 4);
        mRecyclerView.setLayoutManager(mLayoutManager);

Below is my xml

        <?xml version="1.0" encoding="utf-8"?>
        <com.demo.customview.SquareRelativeLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

    <ImageView
        android:id="@+id/imageview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

        </com.bolo.customview.SquareRelativeLayout>

This is how I am using Glide

        Glide.with(mContext)
                .load(resourceId)
                .placeholder(R.drawable.image_holder)
                .into(viewHolder.imageView);

When the RecyclerView is initially visible the Images looks stretched as if they have a scaletype of fitXY. Now when I scroll the list down and up again, now the images are not stretched, they look fine now.

I want the images to look perfect initially as well. Please help me out.

**Comment by TWiStErRob** [comment]
Does it happen if you use a standard layout instead of the square one?

**Comment by niteshkhatri** [comment]
yes. Even in normal RelativeLayout its happening.

**Comment by niteshkhatri** [comment]
@TWiStErRob Please help me out with this problem.

**Comment by TWiStErRob** [comment]
I don't have any more ideas sadly with this one, and no computer access to test it myself yet.
You can try `setHasFixedSize(false)` if you didn't already.

**Comment by TWiStErRob** [comment]
You know what, actually: #363; `.dontAnimate()` or `.animate(R.id.abc_fade_in)` should be a plausible workaround.

**Comment by sjudd** [comment]
Let us know if that didn't work.
