### ISSUE TITLE
How to skip bitmap pool cache specially?

### ISSUE THREAD

**Issue by LiHanGuang** [bumptech/glide#632]
Hello: 

How to skip "bitmap-pool-cache" temporarily? but only have "skipMemoryCache(true)" in API (Glide 3.6).

>
sizing requirements are relatively strict when re-using Bitmaps, so relatively small differences in dimensions require new Bitmaps. You can also mitigate this somewhat by requesting a consistent size and using the fit center transform which will at least make all images with the same aspect ratio the same size.

why request this feature?  Because I have to make my app runs smoothly in my low-configure devices.  if  load much different larger size bitmap, the bitmap-pool will occupy too much memeory to OOM.

I also find the below solution, but this is not what i want:
>
@appstein here's how to configure Glide and here's a description of BItmapPool (granted, it doesn't mention disabling it). In short: create a GlideModule and write builder.setBitmapPool(new BitmapPoolAdapter()) into it. 

Can you give me some suggestion? Thanks.

**Comment by sjudd** [comment]
You can also configure the size of the BitmapPool? Would that work? If you decode a Bitmap larger than the pool's maximum size, the Bitmap won't be stored.
