### ISSUE TITLE
How can I customize the Glide to load images with the “fid(file id)” directly?

### ISSUE THREAD

**Issue by licheedev** [bumptech/glide#634]
Now I need to load images from my company's private server, using the thing called "fid(file id)".
I should first make a http request with the "fid" to get a "token", then build a really image url from the "fid" and "token", and load image by Glide with the url.
So I can't load a image using the "fid" directly.
As the process of getting the "real url"，and loading image by Glide are asynchronous, sometimes the ImageViews within ListView show the wrong Bitmap.
How can I customize the Glide to load iamges with the “fid” directly?

**Comment by TWiStErRob** [comment]
You have to write a model loader. Create a wrapper class for integer and maybe add in the token as well.
https://github.com/bumptech/glide/wiki/Downloading-custom-sizes-with-Glide
Your model loader can create a fetcher that makes one request for the token and one request for the image, and return the second's stream.
Or you can make the token request separately inside BaseGlideUrlLoader.getUrl (see wiki), then return the URL and let Glide take care of the rest "as usual".

**Comment by TWiStErRob** [comment]
> As the process of getting the "real url"，and loading image by Glide are asynchronous, sometimes the ImageViews within ListView show the wrong Bitmap.

This sounds like to make an async request and when that completed you start the Glide load, but by that time a new load into the same view may have started. You have to be able to cancel your async token request if you want the right images to show up. Glide handles its on cancelling, and with the above method you can let Glide handle yours as well.

**Comment by licheedev** [comment]
```java
public interface MyDataModel {
    public String buildUrl(int width, int height);
} 

public class MyUrlLoader extends BaseGlideUrlLoader<MyDataModel> {
    @Override
    protected String getUrl(MyDataModel model, int width, int height) {
        // Construct the url for the correct size here.
        return model.buildUrl(width, height);
    }
}
```
It seems that the "getUrl(MyDataModel model, int width, int height)" callback runs on the UI Thread. 
But I should excute a background thread to post a http request to get the token and build the url.
I don't konw how to return the url in the ‘getUrl(MyDataModel model, int width, int height)’ callback.

**Comment by licheedev** [comment]
@TWiStErRob 
I wrote a simple demo just now.
It seems that the `run()` method in `BaseGlideUrlLoader` runs on the UI thread.

```java
public class MyGlideLoader extends BaseGlideUrlLoader<Integer> {

    public MyGlideLoader(Context context) {
        super(context);
    }

    @Override
    protected String getUrl(Integer model, int width, int height) {
        Log.i("MyGlideLoader#getUrl", Thread.currentThread().toString());
        if (model >= ImageData.URLS.length) {
            return null;
        } else {
            return ImageData.URLS[model];
        }
    }
}
```

And I got the log:

```logcat
 09-17 12:17:55.036    5892-5892/com.licheedev.glidedemo I/MyGlideLoader#getUrl﹕ Thread[main,5,main]
```
> Or you can make the token request separately inside BaseGlideUrlLoader.getUrl (see wiki), then return the URL and let Glide take care of the rest "as usual".

This method may not work in my case, as it should excute a http requst to get a token to build a url. But accessing network is unable to run on UI thread.

**Comment by licheedev** [comment]
@TWiStErRob 
Thank you very much.

> Your model loader can create a fetcher that makes one request for the token and one request for the image, and return the second's stream.

This method works well.

My code:

ModelLoader
```java
public class FidLoader implements StreamModelLoader<ImageFid> {

    @Override
    public DataFetcher<InputStream> getResourceFetcher(ImageFid model, int width, int height) {
        if (model != null) {
            return new FidDataFetcher(model);
        } else {
            return null;
        }
    }

    public static class Factory implements ModelLoaderFactory<ImageFid, InputStream> {

        @Override
        public ModelLoader<ImageFid, InputStream> build(Context context,
            GenericLoaderFactory factories) {
            return new FidLoader();
        }

        @Override
        public void teardown() {

        }
    }
}
```

DataFetcher:
```java
public class FidDataFetcher implements DataFetcher<InputStream> {

    private ImageFid mImageFid;

    private boolean isCancelled = false;

    private InputStream mInputStream;

    public FidDataFetcher(ImageFid imageFid) {
        mImageFid = imageFid;
    }

    @Override
    public InputStream loadData(Priority priority) throws Exception {
        if (mImageFid == null) {
            return null;
        }
        if (isCancelled) {
            return null;
        }
        String url = fetchUrl();
        if (url == null || isCancelled) {
            return null;
        }
        mInputStream = fetchStream(url);
        return mInputStream;
    }

    @Override
    public void cleanup() {
        if (mInputStream != null) {
            try {
                mInputStream.close();
            } catch (IOException e) {
                //e.printStackTrace();
            } finally {
                mInputStream = null;
            }
        }
    }

    @Override
    public String getId() {
        if (mImageFid != null) {
            return mImageFid.getFileKey();
        } else {
            return null;
        }
    }

    @Override
    public void cancel() {
        isCancelled = true;
    }

    private InputStream fetchStream(String url) {
        try {
            return OkHttpManager.getInstance().getSync(url).body().byteStream();
        } catch (IOException e) {
            //e.printStackTrace();
        }
        return null;
    }

    private String fetchUrl() {
        try {
            String json =
                OkHttpManager.getClient().newCall(buildImageUrlRequest()).execute().body().string();
            JSONObject jsonObject = new JSONObject(json);
            return jsonObject.getString("url");
        } catch (IOException e) {
            //e.printStackTrace();
        } catch (JSONException e) {
            //e.printStackTrace();
        }
        return null;
    }

    private Request buildImageUrlRequest() {

        FormEncodingBuilder formEncodingBuilder = new FormEncodingBuilder();
        ... some code to set the request params..
        return new Request.Builder().url(requestUrl).post(formEncodingBuilder.build()).build();
    }

}
```
register the loader
```java
public class MyGlideModule implements GlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        ViewTarget.setTagId(R.id.glide_tag_id);
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);

    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        glide.register(ImageFid.class, InputStream.class, new FidLoader.Factory());
    }
    
}
```

I don't use the `ModelCache`, is it very important?

**Comment by TWiStErRob** [comment]
Yeah, I wasn't sure `ModelLoader` runs on the UI thread, sorry about that. The DataFetcher double-request is exactly as I thought :)

Some thoughts:
 * `mImageFid` is never null, but you're still checking for it multiple times, maybe check once in constructor to simplify
 * You may be able to cancel the requests faster if you store the OkHttp Call object  
this has the benefit of not blocking the Glide queue (small number of threads) with ongoing requests that need not finish, because they won't be displayed (think of fast user scrolling).
 * `ModelCache` helps if constructing the Url is expensive: it is in your case, but you also need network, so I don't think changing `FidLoader` can help. On mobile a request is really expensive, if you can, you should consider changing the HTTP endpoint to do the fid resolution on the server unless your app only works inside the company wifi intranet.

**Comment by licheedev** [comment]
@TWiStErRob 
Thank you very much for helping me improve my code.It works pretty well now.

**Comment by hoavt-54** [comment]
@licheedev hey John, how your final code works? Could you share it?

**Comment by licheedev** [comment]
@hoavt-54 I shared a similar repo in my github, thought the comments wrote in Chinese.
https://github.com/licheedev/Custom-Glide-ModelLoader-Demo
