### ISSUE TITLE
Maven dependency type issue

### ISSUE THREAD

**Issue by fatcowfeng** [bumptech/glide#638]
I build my project with Maven，while I import Glide into my project，I found out there is a build error
like "file glide.aar not exist". So I check the pom.xml, and found that the TYPE of glide is "aar". After I modified it into "jar", my project can successfully build.
So,  should we modify the Maven part in README.md ?

**Comment by TWiStErRob** [comment]
Yep, that aar line shouldn't be there. Only integration libs need aar, but only if you want the manifest merger to do magic.
