### ISSUE TITLE
Glide preload image take 2 second in show

### ISSUE THREAD

**Issue by jacevedo** [bumptech/glide#644]
I  have a app that load all images  on differents sizes, when i make click in one image i go to other activity and show this image on banner, the problems is, the first time take 1 or 2 seconds to show the same image, but the second time it's automatically,   how i make the first time make automatically?

on feed i use 
Glide.with(context).load(urlString)
                  .diskCacheStrategy(DiskCacheStrategy.ALL).error(R.drawable.placeholder).into(imageView);

and the second activity i use 

 Glide.with(ArticleActivity.this).load(urlArticle).diskCacheStrategy(DiskCacheStrategy.ALL).dontTransform().crossFade(0).into(header);

**Comment by jacevedo** [comment]
It was my error, in the first and second activity. I must use override() method with the same width and height additionally put the dontTransform() method

example: 
First Activity 

Glide.with(getContext()).load(urlImage).diskCacheStrategy(DiskCacheStrategy.ALL).placeholder(R.drawable.placeholder).dontTransform().override(width, heightImage).into(imageView);

Second Activity

Glide.with(ArticleActivity.this).load(urlArticle).diskCacheStrategy(DiskCacheStrategy.ALL).dontTransform().override(width, heigth).into(header);

I took the width and heigth in pixels from DisplayMetrics object 

DisplayMetrics metrics = new DisplayMetrics();
getWindowManager().getDefaultDisplay().getMetrics(metrics);
int width = metrics.widthPixels;
int heigth = width / 2;

**Comment by TWiStErRob** [comment]
Glad you figured it out.

Are you using activity transitons or just displaying the same image?

Tip: you can use `.dontAnimate()` instead of `crossFade(0)`.
