### ISSUE TITLE
is there any way to get the width or height  for FITCENTER?

### ISSUE THREAD

**Issue by Aravind-Rajendran** [bumptech/glide#645]
I am using fitcenter.In my imageview i set width as matchparent and the height is dynamically changing..whenever i scroll up and scroll down,the place holder will be loading again to certain height after that image is enlarge or shrink.
is there any way to get the height of the imagview while start loading ,so that i can set height for placeholder.so that it won't give any flickering effect in while loading  image.

    @Override
    public void onBindViewHolder(final ViewHolder holder,final int position) {
        final String url=list.get(position).getImages();
       Glide.with(context).load(url).fitCenter().placeholder(R.drawable.place_holder).dontAnimate().
               into(holder.imageView);  
}

**Comment by TWiStErRob** [comment]
Do you have the same problem as #363? (`dontAnimate` should prevent that)

Can you please share the relevant layout xml part?

You can use `adb screenrecord` and ezgif to attach a GIF here and show what you see.
