### ISSUE TITLE
getAlternateUrls() in 3.6.x

### ISSUE THREAD

**Issue by roccozanni** [bumptech/glide#647]
Hi, 
any chance to have `getAlternateUrls()` feature backported to 3.6.x? We use differect buckets based on network state, container size, and image context (list, fullscreen, etc), and this feature will be a great help to maximize cache hits in case of missing network connectivity.

Thanks,
Rocco

**Comment by dral3x** [comment]
Will be great also for me :+1:

**Comment by sjudd** [comment]
Unfortunately this won't be back ported, I just need to get to release 4.x
