### ISSUE TITLE
Is glide support the uri of DocumentsContract ?

### ISSUE THREAD

**Issue by LiHanGuang** [bumptech/glide#652]
Hello!   Is glide support the uri of DocumentsContract ?

```java
documentsContract uri like:  ( whether support?  which is added in android 4.4 and better)
content://com.android.providers.media.documents/document/image:3951

mediastore uri like:  (glide is support)
content://media/external/images/media/3951
```

**Comment by TWiStErRob** [comment]
Any content Uri should be supported, they are resolved by a `context.getContentResolver()` to an `InputStream`. Pass those uris to `Glide.with(context).load(String)` and you'll see if it works.

**Comment by LiHanGuang** [comment]
@TWiStErRob 
i see, thanks.
