### ISSUE TITLE
Max retry count , Retry Handler for Url 

### ISSUE THREAD

**Issue by vsahu1986** [bumptech/glide#654]
Hi, @TWiStErRob 

I agree on Exception we can check for HTTP 404 and retry , 
Is there any way to inject RetryHandler for Max retry count for particular URL . 

    public class GlideYoutubeImageView extends ImageView {

    public GlideYoutubeImageView(Context context) {
        this(context, null);
    }

    public GlideYoutubeImageView(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public GlideYoutubeImageView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);

    }

    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        Drawable placeholder = getDrawable();
        if (placeholder instanceof AnimationDrawable) {
            ((AnimationDrawable) placeholder).stop();
            Glide.clear(this);
        }

    }

    @Override
    public void setImageBitmap(Bitmap bitmap) {
        if (bitmap != null) FadingDrawable.setBitmap(this, getContext(), bitmap);
    }

    public void setImageBitmapWithoutAnimation(Bitmap bitmap) {
        super.setImageBitmap(bitmap);
    }

    public void loadUrl(final float density, final String videoId) {
        Glide.with(getContext()).load(Utils.getYoutubeUrl(density, videoId)).asBitmap().error(R.drawable.ic_error_icon).listener(new RequestListener<String, Bitmap>() {
            @Override
            public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                e.printStackTrace();
                Log.e("model",model);
                if (isFirstResource)
                    loadUrl(1.5f, videoId);// this will keeping on adding the same request again after exception until Imageview detached 
                return false;
            }

            @Override
            public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
                if (isFromMemoryCache) {
                    setImageBitmapWithoutAnimation(resource);
                } else {
                    setImageBitmap(resource);
                }
                return true;
            }
        }).into(this);
    }
}

This will keeping on adding the same request again after exception until Imageview detached 

Considering solution from 
    #606 
   #451

**Comment by sjudd** [comment]
You can always build a custom ModelLoader and DataFetcher, or copy/paste one of Glide's defaults like [HttpUrlLoader][1] and [HttpUrlFetcher][2]. You can then build in as many retries as you'd like. 

[1]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/stream/HttpGlideUrlLoader.java
[2]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java

**Comment by vsahu1986** [comment]
Thanks @sjudd  I will try this  .
