### ISSUE TITLE
the question of load gif and video

### ISSUE THREAD

**Issue by feng9902535** [bumptech/glide#658]
1:when I use glide to load gif ,I find it block the thread to load other normal pictures,iI think glid is multi thread,but this i can not explain it.
2:when I load the video path ,it can not be loaded.but my another phone MeiZu MX3 and ViVo R7 is Ok.
Phone Model: SumSung S6 G9008
Version:Android 5.1.1

**Comment by TWiStErRob** [comment]
1. The thread pool size is based on the phones cores: https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L170. Also in #637 you can see that multiple GIFs are supported, so loading a single image should be as well.

2. Try to add a `.listener()` and log the exception if any.  
Do this for the normal image that doesn't load too. Maybe it's not blocking just erroring.
