### ISSUE TITLE
3.6 No ClassDefFoundError: com.bumptech.glide.Glide on Honeycomb

### ISSUE THREAD

**Issue by Dimchik78** [bumptech/glide#660]
Getting this error at runtime

**Comment by TWiStErRob** [comment]
Can your `NoClassDefFoundError` be related to #635? Please check if that's your case.

Also please describe how you consume Glide, e.g. [in Eclipse you have to make sure to export the jar](http://stackoverflow.com/q/9833607/253468).

**Comment by TWiStErRob** [comment]
Please share the stack trace too if the above doesn't help.

**Comment by Dimchik78** [comment]
Sory i switch to 3.0 its works fine. I tried Glide 3.6 in Eclipse. Manually placed sorces to Eclipse.Maybe problem at annotation with TargetApi above honeycomb. If you really need trace i can create test project and do trace.

**Comment by TWiStErRob** [comment]
I'm not sure I understand, it looks like your setup is causing the problem. If it works for you we're fine. The suggested way of consuming Glide is through jar though, mostly through Gradle or Maven, or `libs` folder in the worst case. Feel free to close this issue if there's no more to do here.
