### ISSUE TITLE
i use Glide for my image display in android studio but how can i implement Glide to my listview or gridview?

### ISSUE THREAD

**Issue by joebalabadan** [bumptech/glide#661]
I need help from anyone.. please respect my question..

ok, my problem is i want to use Glide for my listview or gridview but i dont know to do..

please construct my code so that the Glide will work or give me any other possible solution to achieve my goal..

my goal is i just want to display image and text in listview or gridview with Glide and JSON, the JSON result is from my php script..

or give a tutorial that use Glide for listview or gridview with JSON and php..

here is my code..

CategoryFragment.java

	package com.example.administrator.mosbeau;

	import android.app.Activity;
	import android.app.Fragment;
	import android.app.FragmentManager;
	import android.app.ProgressDialog;
	import android.os.AsyncTask;
	import android.os.Bundle;
	import android.support.annotation.Nullable;
	import android.util.Log;
	import android.view.LayoutInflater;
	import android.view.View;
	import android.view.ViewGroup;
	import android.widget.EditText;
	import android.widget.ExpandableListView;
	import android.widget.ListView;

	import org.apache.http.HttpEntity;
	import org.apache.http.HttpResponse;
	import org.apache.http.NameValuePair;
	import org.apache.http.client.HttpClient;
	import org.apache.http.client.entity.UrlEncodedFormEntity;
	import org.apache.http.client.methods.HttpPost;
	import org.apache.http.impl.client.DefaultHttpClient;
	import org.apache.http.message.BasicNameValuePair;
	import org.apache.http.params.BasicHttpParams;
	import org.apache.http.params.HttpConnectionParams;
	import org.apache.http.params.HttpParams;
	import org.apache.http.util.EntityUtils;
	import org.json.JSONArray;
	import org.json.JSONException;
	import org.json.JSONObject;

	import java.io.BufferedReader;
	import java.io.InputStream;
	import java.io.InputStreamReader;
	import java.util.ArrayList;
	import java.util.HashMap;
	import java.util.List;

	/**
	 * Created by Administrator on 9/18/2015.
	 */
	public class CategoryFragment extends Fragment {

		public static CategoryFragment newInstance(String id,String name) {
			CategoryFragment fragment = new CategoryFragment();

			Bundle bundle = new Bundle();
			bundle.putString("id", id);
			bundle.putString("name", name);
			fragment.setArguments(bundle);

			return fragment;
		}

		public CategoryFragment () {
		}

		EditText tpid, tpname;
		String cid;
		String cname;

		String myJSON;
		JSONObject jsonobject;
		JSONArray jsonarray;
		ListView productlistview;
		ListViewAdapter adapter;
		ProgressDialog mProgressDialog;
		ArrayList<HashMap<String, String>> arraylist;
		public static String products_id = "products_id";
		public static String products_name = "products_name";
		public static String products_price = "products_price";
		public static String products_image = "products_image";

		Boolean InternetAvailable = false;
		Seocnd detectconnection;

		@Nullable
		@Override
		public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState){
			View rootView = inflater.inflate(R.layout.categorylayout, container, false);

			getActivity().invalidateOptionsMenu();

			tpid = (EditText) rootView.findViewById(R.id.tpid);
			tpname = (EditText) rootView.findViewById(R.id.tpname);

			if(getArguments() != null) {
				String catid = getArguments().getString("id");
				String catname = getArguments().getString("name");

				tpid.setText(catid);
				tpname.setText(catname);
				cid = catid;
				cname = catname;
			}

			productlistview = (ListView) rootView.findViewById(R.id.productlistview);

			//new DownloadJSON().execute();

			detectconnection = new Seocnd(getActivity());
			InternetAvailable = detectconnection.InternetConnecting();
			if (InternetAvailable) {
				getProduct();
			} else {
				NointernetFragment fragment = new NointernetFragment();
				FragmentManager fragmentManager = getFragmentManager();
				fragmentManager.beginTransaction()
						.replace(R.id.container, fragment)
						.commit();
			}

			return rootView;
		}

		public void getProduct(){
			class DownloadJSON extends AsyncTask<String, Void, String> {

				@Override
				protected void onPreExecute() {
					super.onPreExecute();
					// Create a progressdialog
					mProgressDialog = new ProgressDialog(getActivity());
					// Set progressdialog title
					mProgressDialog.setTitle(cname);
					// Set progressdialog message
					mProgressDialog.setMessage("Loading...");
					mProgressDialog.setIndeterminate(false);
					// Show progressdialog
					mProgressDialog.show();
				}

				@Override
				protected String doInBackground(String... params) {
					DefaultHttpClient httpclient = new DefaultHttpClient(new BasicHttpParams());
					HttpPost httppost = new HttpPost("http://joehamirbalabadan.com/android/android/products.php");

					// Depends on your web service
					httppost.setHeader("Content-type", "application/json");

					InputStream inputStream = null;
					String result = null;
					try {
						HttpResponse response = httpclient.execute(httppost);
						HttpEntity entity = response.getEntity();

						inputStream = entity.getContent();
						// json is UTF-8 by default
						BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream, "UTF-8"), 8);
						StringBuilder sb = new StringBuilder();

						String line = null;
						while ((line = reader.readLine()) != null)
						{
							sb.append(line + "\n");
						}
						result = sb.toString();
					} catch (Exception e) {
						// Oops
					}
					finally {
						try{if(inputStream != null)inputStream.close();}catch(Exception squish){}
					}
					return result;
				}

				@Override
				protected void onPostExecute(String result){
					myJSON=result;

					try {
						// Locate the array name in JSON
						JSONObject jsonObj = new JSONObject(myJSON);
						jsonarray = jsonObj.getJSONArray("products");

						arraylist = new ArrayList<HashMap<String, String>>();

						for (int i = 0; i < jsonarray.length(); i++) {
							HashMap<String, String> map = new HashMap<String, String>();
							JSONObject p = jsonarray.getJSONObject(i);
							// Retrive JSON Objects
							map.put("products_id", p.getString("products_id"));
							map.put("products_name", p.getString("products_name"));
							map.put("products_price", p.getString("products_price"));
							map.put("products_image", p.getString("products_image"));
							// Set the JSON Objects into the array
							arraylist.add(map);
						}
					} catch (JSONException e) {
						Log.e("Error", e.getMessage());
						e.printStackTrace();
					}

					adapter = new ListViewAdapter(getActivity(), arraylist);
					// Set the adapter to the ListView
					productlistview.setAdapter(adapter);
					// Close the progressdialog
					mProgressDialog.dismiss();
				}
			}
			DownloadJSON g = new DownloadJSON();
			g.execute();
		}

		@Override
		public void onAttach(Activity activity) {
			super.onAttach(activity);
			((MainActivity) activity).onSectionAttached(2);
		}
	}

**Comment by TWiStErRob** [comment]
*This question would be better suited for StackOverflow, because there's no problem with Glide here.*

Your data flow seems ok, the key is in `ListViewAdapter.java`, that defines how you transform JSON entities to list items. Please share that too.
