### ISSUE TITLE
IGNORE exif image Rotation. 

### ISSUE THREAD

**Issue by xX7** [bumptech/glide#665]
Hey. First of all, thank you for this great image loading library. 

Currently I'm working on an app where its not preferred, that glide automatically sets the correct rotation of the image when loading it as bitmap or in an image view. The app does the rotation handling itself from default and I want to keep the system. 

Is there a option to tell glide to ignore the image rotation and just load it as it is?

**Comment by TWiStErRob** [comment]
Not really, it's hidden deep inside `Downsampler#decode`.

The only way I can imagine with the current version is to create your own `DataFetcher` that wraps the original one, returns a wrapped `InputStream` from `loadData`, then when that wrapping stream reads the underlying one you are also parsing the JPEG/EXIF structure and when you're in the right place just swap a `byte` before returning it. That way Glide won't know about the rotation, but I think this means that even the SOURCE cached image will have the hacked rotation saved; depending on how your app handles rotation by itself this may or may not jeopardize this workaround.

**Comment by TWiStErRob** [comment]
Quick question: are you trying to use Glide as a networking library? (for example only using `.downloadOnly()` calls)

**Comment by TWiStErRob** [comment]
Take a look at [`ExifOrientationStream`](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/data/ExifOrientationStream.java), I think that does exactly this.

**Comment by TheFinestArtist** [comment]
@xX7 I think you can do it just by commenting out this line `result = new ExifOrientationStream(result, orientation);` at [ThumbFetcher.java](https://github.com/bumptech/glide/blob/30c92551ee75c2109955ee653e8795c7c1d60bf8/library/src/main/java/com/bumptech/glide/load/data/mediastore/ThumbFetcher.java). I think you might have to import library in an old way though...

**Comment by TWiStErRob** [comment]
That's for media store thumbnails, loading Files and URLs go on a different path. If you really want to modify the source code go for Downsampler, every load goes through that code.

**Comment by TWiStErRob** [comment]
Let us know if we can help further.

**Comment by thinkluffy** [comment]
Thanks for the great library again!
Is there an easy way to ignore the EXIF in v4?

**Comment by sjudd** [comment]
In Glide v4 it would be pretty easy to add an option to ignore exif rotation. There are a bunch of options already specified in [``Downsampler``](https://github.com/bumptech/glide/blob/6b137c2b1d4b2ab187ea2aa56834dea039daa090/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L43). You'd just add one more ``Boolean`` ``Option`` that just sets [``degreesToRotate``](https://github.com/bumptech/glide/blob/6b137c2b1d4b2ab187ea2aa56834dea039daa090/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L197) to 0.

**Comment by polson** [comment]
See if this works (kotlin, sorry)

```
@GlideModule
class MyAppGlideModule : AppGlideModule() {

    override fun registerComponents(context: Context, glide: Glide, registry: Registry) {
        super.registerComponents(context, glide, registry)

        //Hack to fix Glide outputting tons of log spam with ExifInterface errors
        glide.registry.imageHeaderParsers.removeAll { it is ExifInterfaceImageHeaderParser }
    }
}
```

**Comment by sjudd** [comment]
In case anyone else is interested - ImageDecoder doesn't appear to support ignoring the exif rotation. Unless it does, it doesn't make sense for Glide to do so (contrary to what was said here previously). We expect ImageDecoder to largely replace BitmapFactory going forward.

**Comment by draxdave** [comment]
This answer [here](https://stackoverflow.com/a/8914291/4799599) saved my time.

**Comment by Jessadu1** [comment]
I'm curious, and this knowledge will be helpful to me in my work, therefore could you kindly supply further details?
[football legends](https://footballlegends3.com)
