### ISSUE TITLE
Image disappears after setColorFilter 

### ISSUE THREAD

**Issue by t2314862168** [bumptech/glide#670]
my item layout:

```java
public PhotoItemLayout(Context context, onPhotoItemCheckedListener listener) {
      this(context);
      LayoutInflater.from(context).inflate(R.layout.layout_photoitem, this,true);
      this.listener = listener;

      setOnLongClickListener(this);

      ivPhoto = (ImageView) findViewById(R.id.iv_photo_lpsi);
      cbPhoto = (CheckBox) findViewById(R.id.cb_photo_lpsi);

      cbPhoto.setOnCheckedChangeListener(this); // CheckBox Listener
}

@Override
public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
      if (!isCheckAll) {
            listener.onCheckedChanged(photo, buttonView, isChecked); // notify listener update data
      }
      // make picture change color
      if (isChecked) {
            setDrawingable();
            ivPhoto.setColorFilter(Color.GRAY, PorterDuff.Mode.MULTIPLY);
      } else {
            ivPhoto.clearColorFilter();
      }
      photo.setChecked(isChecked);
}
```

then load image code:

```java
public static void loadImg(Context context, ImageView imageView, String url) {
      Glide.with(context).load(url).placeholder(R.drawable.bg_loading)
                  .error(R.drawable.bg_load_failed)
                  .into(imageView);
}
```

when the image disappears, if scoll down then scroll back, the image can be appear. 
if i don't use the placeholder, it won't happen. Please help me!

**Comment by lanyan520** [comment]
冰冰，你又在逗了么

**Comment by TWiStErRob** [comment]
@lanyan520 please [keep it English](https://github.com/bumptech/glide/issues/571#issuecomment-135559008)

@t2314862168 can you please share `setDrawingable()`? and please edit your comment to surround the code blocks with ``` ?
Also check out #121 and #118. Are you loading GIF?

When you use `.placeholder()` the drawable set is a `TransitionDrawable` otherwise it's just a Glide drawable. Try `.dontAnimate()`, that may help.

**Comment by t2314862168** [comment]
@TWiStErRob
Thank you , dontAnimate it's useful.
I wonder placeholder how to became a TransitionDrawable, Sorry i just found in GenericRequestBuilder : 
 /**
     * Sets an Android resource id for a {@link android.graphics.drawable.Drawable} resourceto display while a resource
     * is loading.
     *
     * @param resourceId The id of the resource to use as a placeholder
     * @return This request builder.
     */
    public GenericRequestBuilder<ModelType, DataType, ResourceType, TranscodeType> placeholder(
            int resourceId) {
        this.placeholderId = resourceId;

        return this;
    }
and in GenericRequest :
   private Drawable getPlaceholderDrawable() {
        if (placeholderDrawable == null && placeholderResourceId > 0) {
            placeholderDrawable = context.getResources().getDrawable(placeholderResourceId);
        }
        return placeholderDrawable;
    }
can you point out the TransitionDrawable how to produced , thank you .

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/request/animation/DrawableCrossFadeViewAnimation.java#L46
where `previous` will be the placeholder and current the loaded image.

What's inside `setDrawingable`? Maybe try swapping the colorfilter and ` setDrawingable`?

**Comment by t2314862168** [comment]
@TWiStErRob 
Thank you for your reply !
here is setDrawingable:
private void setDrawingable() {
		ivPhoto.setDrawingCacheEnabled(true);
		ivPhoto.buildDrawingCache();
	}
now i use glide to load pictures in the disk , if want to smooth fluently , whether or not  should reigster a observer for AbsListView.OnScrollListener for move pause request and no moving resume request  ,
or i don't need do that!

**Comment by TWiStErRob** [comment]
`BaseGlideUrlLoader#getUrl`, the method you override in `FlickrModelLoader`, supports only HTTP urls, see the JavaDoc on it:

> Get a valid url http:// or https:// for the given model

Check this how to delegate from model to another (PhotoModel -> File):
```java
class FlickrModelLoader implements StreamModelLoader<PhotoModel> {
	public FlickrModelLoader(Context context, ModelLoader<File, InputStream> loader) {
		this.loader = loader;
	}
	private final ModelLoader<File, InputStream> loader;

	@Override public DataFetcher<InputStream> getResourceFetcher(PhotoModel model, int width, int height) {
		return loader.getResourceFetcher(new File(model.getOriginalPath()), width, height);
	}

	public static class Factory implements ModelLoaderFactory<PhotoModel, InputStream> {
		@Override public ModelLoader<PhotoModel, InputStream> build(Context context, GenericLoaderFactory factories) {
			return new FlickrModelLoader(context, factories.buildModelLoader(File.class, InputStream.class));
		}

		@Override public void teardown() {
		}
	}
}
```
You can do the same for String if you want, but you seem to know in this case it's a File.

(Can you please edit your previous comments to surround the code blocks with ``` ? Compare your original comment versus the rest for readability...)

**Comment by t2314862168** [comment]
@TWiStErRob 
Thank you for your help!
now my picture can appear normal in gridview , but now i found a case : when use custom ModelLoader to load picture instead of url , using url can load picture exactly , but using custom ModelLoader seem the picture is scaled on center when the picture load completed . 
my source code below :
 public Object instantiateItem(ViewGroup container, int position) {
            FrameLayout frameLayout = new FrameLayout(container.getContext());
            frameLayout.setBackgroundColor(Color.BLACK);
            PhotoView photoView = new PhotoView(container.getContext());
            photoView.setScaleType(ImageView.ScaleType.CENTER_INSIDE);
            // use url to load
//            String imageUrl = "file://" + photoModelList.get(position).getOriginalPath();
//            GlideLoader.loadImg(PhotoPreviewActivity.this, photoView, imageUrl);
            // use custom ModelLoader to load
            mGlideBuilder.load(photoModelList.get(position)).into(photoView);
            FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT);
            params.gravity = Gravity.CENTER;
            frameLayout.addView(photoView, params);
            container.addView(frameLayout, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            return frameLayout;
        }
  mGlideBuilder = Glide.with(this).from(PhotoModel.class)
                .placeholder(R.drawable.bg_loading)
                .error(R.drawable.bg_load_failed)
                .crossFade()
                .centerCrop()
                .dontAnimate();
and load url is :
 public static void loadImg(Context context, ImageView imageView, String url) {
        Glide.with(context).load(url).placeholder(R.drawable.bg_loading)
                .error(R.drawable.bg_load_failed)
                .crossFade()
                .centerCrop()
                .dontAnimate()
                .into(imageView);
    }
the imageview scaleType is same , but  the result is not the same.

**Comment by TWiStErRob** [comment]
In your `instantiateItem` you start the Glide load before setting the LayoutParams, so Glide sees the defaults I guess. Try to call `...into(photoView)` just before returning the layout.

**Comment by TWiStErRob** [comment]
Feel free to reopen or open a new issue if you need more help.
