### ISSUE TITLE
Scale images according to display density

### ISSUE THREAD

**Issue by zergtmn** [bumptech/glide#672]
Hi.
I need to display images of varying sizes in a full-screen ImageView with scaleType="centerInside". Size of the images is unknown at the moment of loading but they are all in mdpi density and server cannot resize them on-the-fly. During the loading I have to upscale them so each image has the same size on different screen densities, e.g. 32x32 images should be scaled to 64x64 on xhdpi, 96x96 on xxhdpi.
What is the right way to perform such resizing using Glide?

I can illustrate the desired behavior using the following code:
```java
// R.drawable.test is located in drawable-nodpi
final Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.drawable.test);
bitmap.setDensity(160);
imageView.setImageBitmap(bitmap);
```
The bitmap will be scaled 2x on xhpi, 3x on xxhdpi, etc.

**Comment by TWiStErRob** [comment]
Glide doesn't know about `dp` sizes. If your target in XML has a fixed `dp` size it'll appear "the same size" on all devices as per Android's specs. Glide only reads the size of these view which are in pixels. Do you really need a full screen `ImageView`, why can't the Android layouts do the work of figuring out the size for you (wrap_content)?

I would try the following:
```java
Glide
		.with(getActivity())
		.load(url)
		.dontTransform()
		.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL) // worth a try without this line too
		.sizeMultiplier(getResources().getDisplayMetrics().density)
		.into(imageView)
;
```
however, sadly, you will bump into #508, but still worth a try, maybe without `.override()` it works.
So while that's not fixed, I recommend writing a a `BitmapTransformation` yourself, which essentially ignores `outWidth`/`outHeight` and scales the Bitmap by the same `.density` as the above code.

Another hackier alternative may be:
```java
Glide
		.with(getActivity())
		.load(url)
		.asBitmap()
		.dontTransform()
		.listener(new RequestListener<String, Bitmap>() {
			@Override public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
				return false;
			}
			@Override public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target,
					boolean isFromMemoryCache, boolean isFirstResource) {
				resource.setDensity(getResources().getDisplayMetrics().densityDpi);
				return false;
			}
		})
		.into(imageView)
;
```

**Comment by zergtmn** [comment]
@TWiStErRob thanks for your response. Unfortunately `sizeMultiplier` only accepts values from 0 to 1 but listener did the trick. Thanks!

**Comment by AdamSHurwitz** [comment]
How can I use **.bitmapTransform()** with the listener?
