### ISSUE TITLE
Black image when attempting to load a video still into an imageView on Galaxy S4

### ISSUE THREAD

**Issue by mreed49** [bumptech/glide#673]
I have tested this feature on numerous devices, and so far only the Samsung Galaxy S4 running 4.4.2 seems to have this problem. 

I'm loading an mp4 file into an imageView in order to get a thumbnail preview using this:

Glide.with(this).load(videoFile).centerCrop().crossFade().error(R.drawable.missing_image).into(glideThumbnail);

this - fragment
videoFile - mp4 file
glideThumbnail - Imageview

The imageView just becomes black and .error() is not called.

**Comment by TWiStErRob** [comment]
Maybe the frame you get is black. The first thing to check would be to see if Android is returning a fully black image, because in that case there's not much we can do I guess. Take a look at #496 too.

Is it happening with all .mp4 files? If not, is that mp4 file public or can you send it to me? I have exactly that config of S4 so I could try to investigate a little too.

**Comment by mreed49** [comment]
Yes, it is happening with all .mp4 files that the application is using, but they are all encoded the same way I believe. Unfortunately, I can't send any of the .mp4 files.

Is it possible that Glide will give a different frame on a different device? Could I specify Glide to take frame at a different point?

**Comment by TWiStErRob** [comment]
> Is it possible that Glide will give a different frame on a different device?

I guess the real question is: Can a device miss the codec that's in those `.mp4` files? I would suggest to try a file from another source to see if it's a codec problem.

> Could I specify Glide to take frame at a different point?

See #496's opening comment.

What is `videoFile` exactly? Is it a File/String/content:/...? How does the `ImageView` look like in XML?
I'll try tomorrow to see how it works on my phone.

**Comment by sjudd** [comment]
If you just use MediaMetadataRetriever directly, does it produce a real image? Let us know of @TWiStErRob's suggestion didn't work.

**Comment by mreed49** [comment]
Thanks for the responses. I have yet to test your suggestion as I have been assigned to a new project. We'll come back to this soon and let you know if your suggestion works. Thanks!

**Comment by mreed49** [comment]
I came back and investigated some more. It turns out, each video did actually have a completely black first frame. I'm not sure why, but only the Samsung S4 seemed to use that frame. Every other device I tested it on created a non-black, "Correct" thumbnail using Glide. I have not determined what the issue is.

I ended up just setting the imageView bitmap with Android's ThumbnailUtil class. My code ended up just looking like this, for those curious:

imageView.setImageBitmap(ThumbnailUtils.createVideoThumbnail(videoFile.getAbsolutePath(), MediaStore.Video.Thumbnails.MINI_KIND));

Thanks for the help!

**Comment by TWiStErRob** [comment]
You can actually use Glide to get work off the UI thread:
```java
this.thumbLoader.load(videoFile).into(imageView); // when binding the imageView
```

```java
// make this a field, only context is needed to initialize
GenericRequestBuilder<File, ?, ?, Bitmap> thumbLoader = Glide
	.with(context)
	.using(new VideoThumbnailBitmapModelLoader(), Bitmap.class)
	.from(File.class)
	.as(Bitmap.class)
	.decoder(new PoolingResourceDecoder(context))
	.diskCacheStrategy(DiskCacheStrategy.RESULT) // change to NONE to remove next two lines to disable caching
	.encoder(new BitmapEncoder(CompressFormat.JPEG, 75)) // for cache
	.cacheDecoder(new FileToStreamDecoder<>(new StreamBitmapDecoder(context))) // for cache
;
```

and now, the supporting classes:
```java
public class VideoThumbnailBitmapModelLoader implements ModelLoader<File, Bitmap> {
	@Override public DataFetcher<Bitmap> getResourceFetcher(File model, int width, int height) {
		int kind = MediaStore.Video.Thumbnails.MINI_KIND;
		if (width < 96 && height < 96) {
			kind = MediaStore.Video.Thumbnails.MICRO_KIND;
		}
		return new VideoThumbnailDataFetcher(model, kind);
	}
}

// you can leave this package private next to VideoThumbnailBitmapModelLoader
class VideoThumbnailDataFetcher implements DataFetcher<Bitmap> {
	private final File model;
	private int kind;
	public VideoThumbnailDataFetcher(File model, int kind) {
		this.model = model;
		this.kind = kind;
	}
	@Override public Bitmap loadData(Priority priority) throws Exception {
		String path = model.getAbsolutePath();
		return ThumbnailUtils.createVideoThumbnail(path, kind);
	}
	@Override public void cleanup() {
		// stateless, no cleanup needed
	}
	@Override public String getId() {
		return model.getAbsolutePath() + "+" + kindString(kind);
	}
	private String kindString(int kind) {
		switch(kind) {
			case MediaStore.Video.Thumbnails.MINI_KIND: return "MINI_KIND";
			case MediaStore.Video.Thumbnails.MICRO_KIND: return "MICRO_KIND";
			default: return "UNKNOWN_KIND(" + kind + ")";
		}
	}
	@Override public void cancel() {
		// cannot cancel
	}
}

public class PoolingResourceDecoder implements ResourceDecoder<Bitmap, Bitmap> {
	private final BitmapPool pool;
	public PoolingResourceDecoder(Context context) {
		pool = Glide.get(context).getBitmapPool();
	}
	@Override public Resource<Bitmap> decode(Bitmap source, int width, int height) {
		return BitmapResource.obtain(source, pool);
	}
	@Override public String getId() {
		return getClass().getName();
	}
}
```

**Comment by TWiStErRob** [comment]
Here's an alternative with less passing stuff around:
```java
GenericRequestBuilder<File, ?, ?, Bitmap> thumbLoader = Glide
	.with(context)
	.using(new PassthroughModelLoader<File, File>(), File.class)
	.from(File.class)
	.as(Bitmap.class)
	.decoder(new VideoThumbnailDecoder(context))
	// same caching rules apply as above
;
```
```java
public class VideoThumbnailDecoder implements ResourceDecoder<File, Bitmap> {
	private final BitmapPool pool;
	public VideoThumbnailDecoder(Context context) {
		pool = Glide.get(context).getBitmapPool();
	}
	@Override public Resource<Bitmap> decode(File source, int width, int height) throws IOException {
		String path = source.getAbsolutePath();
		int kind = MediaStore.Video.Thumbnails.MINI_KIND;
		if (width < 96 && height < 96) {
			kind = MediaStore.Video.Thumbnails.MICRO_KIND;
		}
		Bitmap thumb = ThumbnailUtils.createVideoThumbnail(path, kind);
		return BitmapResource.obtain(thumb ,pool);
	}
	@Override public String getId() {
		return getClass().getName();
	}
}

public class PassthroughModelLoader<Result, Source extends Result> implements ModelLoader<Source, Result> {
	@Override public DataFetcher<Result> getResourceFetcher(final Source model, int width, int height) {
		return new CastingDataFetcher<Source, Result>(model); // upcasting is ok
	}
	/** Extremely unsafe, use with care. */
	private static class CastingDataFetcher<Source, Result> implements DataFetcher<Result> {
		private final Source model;
		public CastingDataFetcher(Source model) { this.model = model; }
		@SuppressWarnings("unchecked")
		@Override public Result loadData(Priority priority) throws Exception { return (Result)model; }
		@Override public void cleanup() {}
		@Override public String getId() { return model.toString(); }
		@Override public void cancel() { }
	}
}
```

**Comment by mreed49** [comment]
Hey, this works great. Thank you!

**Comment by eicm** [comment]
@TWiStErRob is there a cleaner way to do this?

**Comment by TWiStErRob** [comment]
We can't do much about this if the system returns a black image. I think this last solution is a quite reasonably sized workaround and with #1096 there's nothing you lose compared to default load.

**Comment by eicm** [comment]
@TWiStErRob The default load using loadFromMediaStore() for media doesn't use the already generated thumbnails from media store but it try to create the thumbnail by getting a frame from video and in a grid with multiple visible video sources the load becomes very slow

**Comment by TWiStErRob** [comment]
@eicm I just re-read https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/data/MediaStoreThumbFetcher.java and for me it looks like it's getting the mini thumb when possible, no re-generation. Is your item size bigger than 512x384? Also once it is loaded Glide cache should make it much faster on second display.

**Comment by eicm** [comment]
No I'm using override(96, 96) to load thumbnails.

**Comment by eicm** [comment]
@TWiStErRob I created a sample app, please take a look: [Sample app](https://github.com/eicm/VideoThumbnailTest)

**Comment by TWiStErRob** [comment]
@eicm can you please open a new issue and describe what should I be looking at? I think your issue is only related to the blackness because it's a workaround for it.

**Comment by eicm** [comment]
@TWiStErRob I have around 80 videos on my device and it takes around 10 minutes to load all the thumbnails for the videos

**Comment by jisunglim** [comment]
Thanks for your awesome answer @TWiStErRob, and I want to add some code for your second code.

To use `BitmapPool` properly, the following steps are required:
```java
// decoding
Bitmap bitmap = GlideBitmapFactory.decodeResource(getResources(), R.drawable.test1);

// recycling
GlideBitmapPool.putBitmap(bitmap);

// creating a bitmap
Bitmap bitmap = GlideBitmapPool.getBitmap(width, height, config);
``` 
You can see [here](https://github.com/amitshekhariitbhu/GlideBitmapPool#migrating-to-glide-bitmap-pool).

I think you might be forget the second step when you override `decode`, the fixed code is given by

```java
@Override 
public Resource<Bitmap> decode(File source, int width, int height) throws IOException {
  String path = source.getAbsolutePath();
  int kind = MediaStore.Video.Thumbnails.MINI_KIND;
  if (width <= 96 && height <= 96) {
    kind = MediaStore.Video.Thumbnails.MICRO_KIND;
  }

  // Decode bitmap from video file
  Bitmap thumb = ThumbnailUtils.createVideoThumbnail(path, kind);

  // Register bitmap into the pool
  if (!pool.put(thumb)) {
    thumb.recycle();
  }
  
  // Creating and return bitmap
  return BitmapResource.obtain(thumb ,pool);
}
```

If anything is wrong, please tell me what it is. Thank you. :)

**Comment by jisunglim** [comment]
Oh, I've found out that `BitmapResource.obtain()` method contains recycling functionality. 
```java
@Override
public Bitmap get() {
  return bitmap;
}

@Override
public int getSize() {
  return Util.getBitmapByteSize(bitmap);
}

@Override
public void recycle() {
  if (!bitmapPool.put(bitmap)) {
    bitmap.recycle();
  }
}
```
Furthermore, if you add below code before that method, you may encounter unexpected error without any log...!
```java
// Register bitmap into the pool
  if (!pool.put(thumb)) {
    thumb.recycle();
  }
```
So, you MUST NOT add that code!

I'm sorry for the misinformation...!
