### ISSUE TITLE
Is it a way to postpone the cross fade from thumbnail to full image?

### ISSUE THREAD

**Issue by xingrz** [bumptech/glide#675]
Hi all,

I have a main activity with thumbnails in a grid list view, and a detail activity with an full size image.

When user click on an item on the main activity, there will be a Shared Element Transition from that main activity to the detail activity.

So here comes the question:

In order to perform the Shared Element Transition, image in the detail activity should be ready before the transition starts.  So let's say I load `thumbnail.jpg` in the main activity with `.diskCacheStrategy(DiskCacheStrategy.SOURCE)` , them in the detail activity I use a `.thumbnail(thumbnailRequest)` to let the image be ready to perform the Shared Element Transition before the full size image `original.jpg` is loaded.

But there is an edge case: If `original.jpg` is ready during the Shared Element Transition is performing, it replace the `thumbnail.jpg`, and break the transition animation.

So, is it a way to postpone the cross fade from thumbnail to full image until the activity's transition is finished?

**Comment by TWiStErRob** [comment]
You can load the thumbnail in detail before the transition so the anim is nice and then start a separate load in detail when the transition completes so it doesn't interfere.

You can also try to disable crossFade with `.dontAnimate()`.

Also see https://github.com/bumptech/glide/issues/627#issuecomment-146136474 for an alternative.
