### ISSUE TITLE
Loading image  failed .

### ISSUE THREAD

**Issue by UsherBaby** [bumptech/glide#676]
02-09 11:45:36.085 15232-15684/com.ut.utbzhpda E/dalvikvm-heap: Out of memory on a 19660816-byte allocation.
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor: Request threw uncaught throwable
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.FutureTask.get(FutureTask.java:82)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1084)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.lang.Thread.run(Thread.java:856)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:  Caused by: java.lang.OutOfMemoryError
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at android.graphics.Bitmap.nativeCreate(Native Method)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at android.graphics.Bitmap.createBitmap(Bitmap.java:669)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at android.graphics.Bitmap.createBitmap(Bitmap.java:649)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.TransformationUtils.rotateImageExif(TransformationUtils.java:272)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:167)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.lang.Thread.run(Thread.java:856) 
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

**Comment by UsherBaby** [comment]
Loading image failed.

**Comment by TWiStErRob** [comment]
Please update your report based on https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues.
