### ISSUE TITLE
signature method does not work on nexus4 device

### ISSUE THREAD

**Issue by maximeloridan** [bumptech/glide#678]
**Glide Version**: compile 'com.github.bumptech.glide:glide:3.6.1'
**Device/Android Version**: Nexus4 android 5.1.1, build LMY48M
**Issue details/Repro steps/Use case background**:

I wanted to implement the signature method (because in my app, the user has a profile picture with a url based on his ID, and he can update his picture with no change of this url).

The issue is that:
* It does work on Nexus4 emulator 64-X86 (android API 22: 5.1)
* But it does not work on my phone (Nexus4 android 5.1.1, build LMY48M).

So I tested with the simplest activity possible. When I click on a button it does this:

```java
toto = toto +1;
Glide.with(getApplicationContext())
.load("http://mydomain.com/picts/1234")
.signature(new StringSignature(Integer.toString(toto)))
.centerCrop()
.into((ImageView) findViewById(R.id.imageView));
```

This way, each time I click on a button, the signature is different (toto has been incremented). 

To test it, before clicking on the button, I change the picture on my server to see the change.

As I said before, this code does not work on my phone, but does work with the emulator (the picture is refreshed).

(Nota: Moreover I tried to add a listener `onResourceReady` to check `boolean isFromMemoryCache, boolean isFirstResource`. isFromMemoryCache is set to false and isFirstResource is set to true. Which seems OK, but it always display the same picture on my nexus 4...)

Have you an idea why the exact same code does work on the emulator and does not on my nexus4.
Have you tried on a nexus 4, android 5.1.1 ?
I wonder if the problem comes from the device, or the android version.

Thank you

Nota: Nothing appears on logcat

**Comment by TWiStErRob** [comment]
Not hitting the memory cache, doesn't mean that it's not reading from disk cache.

What did you initialize `toto` to?

**Comment by TWiStErRob** [comment]
Btw, [this url](http://lorempixel.com/400/200/sports) will give you different results **almost** every time you hit it, but there are only a few different images, see [this link](http://lorempixel.com/#images) for how many each category contains.

**Comment by maximeloridan** [comment]
I tried not to use glide (but to use the common way to display an image on android) to display the picture (just to be sure that without glide the picture will be updated). But to my surprise it did not refreshed!

So I searched, and I found this answer (http://stackoverflow.com/questions/14231872/force-app-to-refresh-image-from-url): the trick is to add a "?random=randomString" at the end of the url and it actually works (I have only tested without glide now, but will test with glide soon)

Is this normal? (I am a little lost, sorry)

**Comment by TWiStErRob** [comment]
It will work with Glide obviously because the url will be different, so the cache can't hit. I would say that's a bad hack in Anrdoid/Glide's world. You might as well `.diskCacheStrategy(NONE)`, that works too. The point here is to use a signature that changes rare enough that it's worth saving the HTTP stream to the phone and store it for a long time to minimize additional network traffic on the user's device.

**Comment by TWiStErRob** [comment]
How do you hit your url? Is it your IP? or a real web address where you upload files? If it's a third party/or even local webserver is there any server side caching? Maybe try restarting the webserver between updates, so any memory cached files on the server side will be purged (most servers need special startup params to watch for changes).

**Comment by maximeloridan** [comment]
It is a real web address on an OVH Server.
On Glide I try to load "http://mydomainOnOVH.com/picts/1234". And when I try with the same exact url with "chrome for android", the picture is refreshed

I do not understand why it works with my browser on my phone and not with glide

Thank you for your help!

**Comment by TWiStErRob** [comment]
You may have missed this one: https://github.com/bumptech/glide/issues/678#issuecomment-147248371
You can also [enable logging inside Glide with `setprop`](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) to see the full cache key.

**Comment by maximeloridan** [comment]
I tried too to do this ".signature(new StringSignature(Long.toString(System.currentTimeMillis())))", but the problem is still there

I will try to "enable logging inside Glide with setprop to see the full cache key."

**Comment by TWiStErRob** [comment]
Follow the instructions on the given link, but use `log.tag.Engine` and `VERBOSE` to get the cache key and it'll also say where it was loaded from.
*Sorry I'm a little disturbed tonight, didn't eat much in past days because of sickness.*

**Comment by maximeloridan** [comment]
(I have still not tried to enable logging, but I will do it later)

I have noticed something interesting:
1/ I click on the button to display the image (of a cat) with URL "http://mydomain.com/picts/1234"
2/ I change on my server the image (to a dog) with the same URL "http://mydomain.com/picts/1234"
3/ I click on the button to display the image "http://mydomain.com/picts/1234": It displays the image of a cat (this is the issue we are talking about)
3/ I remove the app and reinstall it (normally Android has been cleared: no glide cache can be found for this app)
4/ I click on the button to display the image "http://mydomain.com/picts/1234" ==> It displays the image of the cat!

**Comment by TWiStErRob** [comment]
You should start by enabling logging, it is going to tell you if it's a Glide disk cache hit or a server side caching issue, just compare the keys for separate loads.

**Comment by maximeloridan** [comment]
(Thank you again for your answers!)

I had an idea and I would want to know what you about it:
Instead of adding ".signature(new StringSignature(profile.imageLastUpdate))", I think I could have the exact same behaviour by adding a "?signature=profile.imageLastUpdate" at the end of the url.

This way, 
* my server will force refresh the picture when profile.imageLastUpdate has changed, 
* and the cache in glide will still work because the url will not change until profile.imageLastUpdate change in the url.

Do you agree?

**Comment by TWiStErRob** [comment]
That sounds good actually for String urls, with the only reservation that it may bite you in the a$$ in the future. I guess signature was introduced because for other models this might be impossible (think File), or one just doesn't want to poison their model with a separate signature/expiry field.

**Comment by TWiStErRob** [comment]
Btw, re https://github.com/bumptech/glide/issues/678#issuecomment-147376990: I think it just proves that the signature is either not changing or not applied, easily confirmable via enabling logging.

**Comment by TWiStErRob** [comment]
Closing this because you seem to have resolved your original issue, please reopen if you feel otherwise.

**Comment by shahwaiz90** [comment]
Very late in the party, but I have a url on server which remains the same even after its content changed. 
What I m doing is persisting the last modified date of that image locally and pass it in my signature against that url. But problem is glide doesn't hit the network, since last-modified date is locally stored I can't get the next last-modified when content is changed. What if I want glide to hit every time on server and based upon that last-modified header coming from server I will load the data from local or network cache? @TWiStErRob

**Comment by TWiStErRob** [comment]
@shahwaiz90 look up issues with [etag](https://github.com/bumptech/glide/issues?q=is%3Aissue+etag), for example https://github.com/bumptech/glide/issues/463.
There was some discussion around this years ago.
