### ISSUE TITLE
Trying to load GIF image shows flashing colors in ImageView

### ISSUE THREAD

**Issue by sumbulAlvi** [bumptech/glide#681]
Hi there! In the `bind()` method of my `recyclerView` I'm making the following call:
```
Glide.with(getContext())
	.load(url)
	.diskCacheStrategy(DiskCacheStrategy.SOURCE)
	.placeholder(R.color.white)
	.into(imageView);
```
Due to the custom logic, we require the `bind()` method to be called twice per cell. In the first call of bind, the imageView has not yet been measured correctly and the width/height is 0. For GIFs particularly, this seems to cause problems. Flashing colors appear in the place of where the gif should be. On recycling the view, the gif appears as expected. The colors seem to be the main colors that are in the bitmap of the GIF.

When I put the condition `if (imageView.height > 0 && imageView.width > 0)` around the Glide command, the GIFs appear as expected. What is the reason that this is the case? 

Here is a GIF of the behavior I'm seeing:
![incorrect-glide-behavior](https://cloud.githubusercontent.com/assets/14984167/10436211/03fb4606-70f3-11e5-9d94-4f4e3183adca.gif)

**Comment by TWiStErRob** [comment]
The colors actually make sense, they look like the dominant colors from each frame, for example: the queen's robe, Merida's skin, the throne. It looks like Glide somehow figures it needs to resize to 1x1 Bitmaps.

Add a `.listener()` to see what's the actual size of the Drawables are. Glide is OK with `getWidth() == 0` as long as the layout has a proper value which means "it'll be known later", which are `match_parent` or `wrap_content`; then it'll wait for the first measure-layout-draw and get the size after. In case you have `0dp` in XML, I'm afraid that condition is the best way. Also do you use a custom ImageView?

**Comment by sumbulAlvi** [comment]
Thanks for the quick response!

When I add a `RequestListener()` and check the `resource` size `onResourceReady`, the height & width are 1. The imageView is measured/sized and added to view on `bind()` (unfortunately so) and initially the height/width are 0, then 1, then the correct size. 

I've found a way around this by using `.override(width, height)` on my Glide call. Any performance hit that would occur with using this instead of using the condition `if (width > 0 && height > 0)`? 

> Also do you use a custom ImageView?

The issue occurs with a regular ImageView.

**Comment by TWiStErRob** [comment]
If you're **always** binding twice I would suggest to call Glide only on the first or only on the second one to prevent any weirdness. It's also pointless to start a load then cancel to start it again (`into()` cancels previous load). Using only the second load you also wouldn't need the override.

`.override()` is not a bad thing if you know the exact size of the view. It just prevents Glide from poking the Target for the needed image size (`ViewTarget` waits for layout) and uses the given values instead. So if you get the size right you can actually speed up the process, but if you don't you may end up loading a non-perfect fit and the ImageView has to do a resize of the image itself when drawing.

`width > 0 && height > 0` also includes 1x1, how come that never happens?

**Comment by sumbulAlvi** [comment]
Okay that makes sense, thanks for suggestion.

> width > 0 && height > 0 also includes 1x1, how come that never happens?

Yeah I had to update the condition to be `width > 1 && height > 1` because I was seeing the imageView go from 0x0 -> 1x1 -> correctSize through the logs.
