### ISSUE TITLE
load image has a lot of white

### ISSUE THREAD

**Issue by a1018875550** [bumptech/glide#682]
As you see, why I load image from file, it can't load all; have a lot of white;
and the local image  file is complete; so how do i solve it?

![s51013-163739](https://cloud.githubusercontent.com/assets/8246218/10450021/07f89b1e-71ca-11e5-8685-5bf1fd1a742a.jpg)

```java
Glide.with(activity)
     .load(file.getPath())
     .placeholder(R.drawable.head)
     .error(R.drawable.head)
     .into(new SimpleTarget<GlideDrawable>() {
         @Override
         public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
             holder.head_iv.setImageDrawable(resource);
         }
     });
```

**Comment by a1018875550** [comment]
![image](https://cloud.githubusercontent.com/assets/8246218/10450930/e5a43dec-71cf-11e5-8e1a-e82a65d11e8d.png)
and this is my code

**Comment by TWiStErRob** [comment]
Does this happen every time with the same image? Try to clear Glide cache, maybe there was an exception that corrupted the cache (shouldn't happen). Do you have a custom Disk cache?

**Comment by TWiStErRob** [comment]
Please reopen if you still have the problem and you can provide more information.
