### ISSUE TITLE
Disk Cache usage

### ISSUE THREAD

**Issue by danieltong** [bumptech/glide#686]
In My app，I want use Disk Cache for some images, I want to save it into the specified directory，these images only clear  manually。Also there are many other images I want cache it in another directory maybe in a LRUDiskCache. 
 How can I configure Glide for this usage.

THX

**Comment by TWiStErRob** [comment]
Just had the same question this morning: https://groups.google.com/d/topic/glidelibrary/glDYWgKjNPw/discussion
