### ISSUE TITLE
Wrong image is loaded

### ISSUE THREAD

**Issue by karun2189** [bumptech/glide#693]
If i am load a different image in same image-view in gridView it will display wrong image. What is the problem ? I am not able to figure out....Here is my code
```java
Glide.with(mImageView.getContext())
                .load(path)
                .thumbnail(Glide // this thumbnail request has to have the same RESULT cache key
                        .with(mImageView.getContext()) // as the outer request, which usually simply means
                        .load(path) // same size/transformation(e.g. centerCrop)/format(e.g. asBitmap)
                        .fitCenter() // have to be explicit here to match outer load exactly
                )
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
//                        if (isFirstResource) {
//                            return false; // thumbnail was not shown, do as usual
//                        }
                        return false;
                    }
                })
                .error(R.drawable.broken_img)
                .signature(new StringSignature(mLastModified))
                .dontAnimate()
                .into(mImageView);
```

**Comment by TWiStErRob** [comment]
You're loading two different versions of the same `path` one with a last modified signature and one without. Both of them can hit the cache. Also `.fitCenter()` is only implicit if the ImageView's scaleType is fitCenter (or omitted). Try clearing the cache of your app or reinstall it.
The key thing to remember is that once a File is read from the SD card the resized version is remembered by Glide. So to pick up changes loads must be accompanied with the signature call with the correct (newest) timestamp, or older ones if you want to show those. But you must remember them.

**Comment by sjudd** [comment]
The [wiki article][1] may be helpful here too.

[1]: https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#custom-cache-invalidation
