### ISSUE TITLE
Preloading question

### ISSUE THREAD

**Issue by mare011** [bumptech/glide#694]
Hi there. First of all, i must say,  you've made an awesome library!
This is my scenario: i'm fetching images from webdav server, and i need them in three resolutions, a small thumb for list (40x40 dp), a normal thumb for pictures grid (100x100 dp), and a larger image for the full-screen image slider, and since i have i sync adapter i wanted to prefech the images.
Is there any way i could load the load the image and cache it these three sizes without having to download them 3 times? 

I've seen preload method, but how exactly does it work, if i don't specify width and height it's saved in the original size, so when will i get a cache hit, only if the size matches the original or? And if i do specify a size for preload, can it be proportional, or do i need to specify an exact dimension (i basicly want to downsample it to 720x??? or ???x720 based on orientation)

Thanks in advance.
Cheers

**Comment by TWiStErRob** [comment]
Preload saves the resized image only by default.
Whenever you use multiple sizes you will probably want to ask for `.diskCacheStrategy(ALL|SOURCE)` to save the original. Use SOURCE or ALL if you want only the original with the tradeoff between using the CPU to downsample every time (SOURCE) VS storing the resized image in RESULT cache (ALL).

```java
Glide.with(context).load(url).dontTransform().diskCacheStrategy(SOURCE).preload();
Glide.with(context).load(url).centerCrop().diskCacheStrategy(ALL).preload(dip(40));
Glide.with(context).load(url).centerCrop().diskCacheStrategy(ALL).preload(dip(100));
```

I suggest to start the last two in the `.listener()`'s `onResourceReady` to make sure no download will happen multiple times. Make sure you scale the dp sizes by the correct scale factor for the device.

Where you need to hit those cached images, make sure you include the same sizes via `.override()` and match the transformation as well. Also worth using ALL cache when normal loading as well to re-fill the cache in case it's evicted or the cache is cleared by the user.

You can control how the downsampling works with `.asBitmap().atMost|asIs|approximate()` and then transformation you use also matters, for example centerCrop() will always match the exact bounds you request due the nature of the transformation, while fitCenter() will resize proportionally. Again make sure you use the same arguments when preloading and when trying to load from cache.

**Comment by mare011** [comment]
Thanks m8, that clarified a lot!
