### ISSUE TITLE
Image View is flickering if i am using signature

### ISSUE THREAD

**Issue by karun2189** [bumptech/glide#697]
If i am using signature then the imageview is flickering else it wont flickering but i am not able to get updated image if i am not using signature. How can i solve it?

**Comment by TWiStErRob** [comment]
`.signature()` shouldn't really affect how the image displays, it's only used to name the image in cache differently.

Can you please fill in the [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues) (feel free to edit your above comment), the above information is not enough to go on.

**Comment by TWiStErRob** [comment]
Please feel free to reopen if you have a chance to provide more information.
