### ISSUE TITLE
Bitmap loaded into ImageView with undesired padding on Android 6.0

### ISSUE THREAD

**Issue by jbarr21** [bumptech/glide#698]
Glide 3.6.1 w/ OkHttp
N5 on Android 6.0 only (no issue below 6.0)

Issue details/Repro steps/Use case background:

On Android 6.0, we are loading an image into an ImageView and all of the size measurements work, but the image has 2dp of undesired padding on all sides within the ImageView when the image should be totally filling the ImageView. When `.dontAnimate()` is added to the Glide load statement, the issue is resolved, but I don't get the fade in animation. This happens on our Grid of images screen as well as in our detail screen. When I tap on an image in the Grid screen, all the images on the grid grow by 2dp (I'm assuming due to a re-layout).

``` java
Glide.with(getContext())
                    .load(uri)
                    .placeholder(R.drawable.details_placeholder)
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .into(holder.image);
```

Layout XML:

``` xml
<mypackagename.view.FitWidthImageView
                android:id="@+id/image"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:scaleType="fitXY"/>
```

Stack trace: N/A

**Comment by TWiStErRob** [comment]
What does FitWidthImageView do (paste relevant code please)? Does the padding shows up with a normal ImageView? My usual advice is to create a generic layout that does the same sizing as it does within the custom ImageView. Doing so would revert to stock ImageView and both w/h can be match_parent and the wrapping layout with constrain the aspect ratio (I.e.height).

Something to try: add `.fitCenter()` in code but keep fitXY in XML if that's required.

Workaround: since you mentioned fade in: `.animate(android.R.fade_in)` or `R.abc_fade_in`.

There's a know issue with crossfading different placeholder and image aspect ratios: #363.

**Comment by jbarr21** [comment]
I will make a basic example for you, but I forgot to mention that my placeholder is also a 9-patch. Would the crossfade issue still be applicable? Plus, all of this only occurs on Marshmallow, everywhere else, it works fine.

**Comment by TWiStErRob** [comment]
Good question, I only tried with fixed sized raw image drawables. Thanks for the repro case. Something may be messed up in Marshmallow if there are two reports within one day :(

**Comment by jbarr21** [comment]
I tried the more basic item you suggested (placeholder_details is still a 9patch) and w/ a basic imageview and i still have the 2dp all around

XML:
```
<ImageView
                android:id="@+id/image"
                android:layout_width="match_parent"
                android:layout_height="400dp"
                android:scaleType="fitXY"/>
```

Glide load:
```
Glide.with(getContext())
                    .load(uri)
                    .fitCenter()
                    .placeholder(R.drawable.details_placeholder)
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .into(holder.image);
```

**Comment by TWiStErRob** [comment]
@sjudd can you try this one? I don't have a Marshmallow device.

**Comment by mformetal** [comment]
I'm having the same problem, Nexus 5 running Marshmallow. Undesired padding on bitmap loaded into ImageView, even though the bitmap dimensions match that of my screen, 1080x1920.

**Comment by TWiStErRob** [comment]
@mformetal can you please post a screenshot? Also note that fullHD images won't really fill a fullHD screen because there's the notification bar, action bar and softkeys on the screen. Is the space available for your app really fullHD (is it fullscreen maybe)?

**Comment by TWiStErRob** [comment]
I tried reproducing this on the SDK Marshmallow emu, but no luck. Could either of you create a reproducible sample app? Or at least give exact dimensions for placeholder, image and imageView? And possible the build.gradle comes to play as well, with target/compile SDK versions.

**Comment by van11** [comment]
I assume your placeholder contained extra padding. For my case after removing it worked fine.
