### ISSUE TITLE
Loading bitmap image after downloading bytes to disk

### ISSUE THREAD

**Issue by a64adam** [bumptech/glide#706]
Hi,

I'm running into a problem regarding the signatures Glide uses to store images. What's happening is I am pre-fetching some images using the downloadOnly call and they are being added to the disk cache. Then I am loading those images to display them, and I would expect them to be pulled from the cache, however they weren't.

I took a look at the signatures of the downloadOnly load vs the normal load and noticed a difference, however this difference comes from the fact that when I am loading images to display them, I call asBitmap() on the builder. This is appending "ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap" to the signature. This is not present on the downloadOnly signature (which makes sense). 

What I am wondering is, do I need to add the above string manually as a signature (when calling downloadOnly)? It seems like that would be incorrect since that string is not directly exposed. Or is there perhaps something else I am missing?

Thanks!

**Comment by TWiStErRob** [comment]
Did you add `.diskCacheStrategy(SOURCE|ALL)` to the normal load where you expect a cache hit? 

The default is `RESULT` and whatever is set on a particular load request that cache will be granted access to, meaning Glide will read if cache hit, and write if cache missed.

You probably can't mess with `.signature` because the order may be different.

**Comment by a64adam** [comment]
I'm using .diskCacheStrategy(ALL) (I also tried SOURCE) during the normal load. Here are the signatures if it helps, I pulled these from decodeJob, they were the values in resultKey:

Normal load: <id_from_custom_data_fetcher>com.bumptech.glide.signature.EmptySignature@c5a2351570471ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmapBitmapEncoder.com.bumptech.glide.load.resource.bitmap

downloadOnly load:
<id_from_custom_data_fetcher>com.bumptech.glide.signature.EmptySignature@c5a2351471520

where <id_from_custom_data_fetcher> match.

**Comment by a64adam** [comment]
I was digging into it a little more and it looks like I stepped through the wrong block. To get the signatures above, I was stepping through DecodeJob#decodeResultFromCache, whereas I should have been looking at DecodeJob#decodeSourceFromCache.

When I stepped through DecodeJob#decodeSourceFromCache, it was pulling the correct signatures by using resultKey#getOriginalKey yet it was still turning up empty when searching the cache for the same key. I'm going to close for now since I want to be 100% sure I'm not missing anything else!

**Comment by TWiStErRob** [comment]
Look at the to string of the key, that's easier to interpret. Also notice that the EmptySignature is the same, but the sizes are different for the two quoted keys: 570x471 vs 471x520. But you're right the original key is what you need for SOURCE hit. Also take a look at `preload(w,h)` method if you want RESULT hits.

If/when you reopen please include all load lines and customisations to Glide. That's better than describing what you did, see also CONTRIBUTIONS.md in repo root.

**Comment by a64adam** [comment]
Looks like everything was working as intended! There was an issue with the way I was testing this. What I was doing is deleting the cache directory and then running the downloadOnly loads. This recreated the glide disk cache however, without the journal file. When I then run the normal image loads, they would re-download, I presume due to the missing journal file. 

In practice this isn't an issue since I wouldn't expect a user to manually delete the cache, but do you know why the journal file was not being created?

**Comment by TWiStErRob** [comment]
Did you delete it while the app was running?

**Comment by TWiStErRob** [comment]
I never tried physically removing the directory manually. I ususally force close and clear app data/clear app cache in App Info; or use this triggered via a button on the action bar:
```java
new AsyncTask() {
	@Override protected void onPreExecute() {
		Log.i("GLIDE", "Clearing memory cache");
		Glide.get(TestActivity.this).clearMemory();
		Log.i("GLIDE", "Clearing memory cache finished");
	}
	@Override protected Object doInBackground(Object[] params) {
		Log.i("GLIDE", "Clearing disk cache");
		Glide.get(TestActivity.this).clearDiskCache();
		Log.i("GLIDE", "Clearing disk cache finished");
		return null;
	}
	@Override protected void onPostExecute(Object o) {
		Toast.makeText(TestActivity.this, "Cache cleared", Toast.LENGTH_SHORT).show();
	}
}.execute();
```

**Comment by a64adam** [comment]
Yeah, I was deleting it while the app was still running, so it may very well still be referring to an in-memory version of the journal.

Ah I didn't know about those calls! I will give those a shot, looks like I will need to update Glide since the version I'm using does not have #clearDiskCache.

Thank you!
