### ISSUE TITLE
ImageVideoBitmapDecoder.getId doesn't delegate

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#708]
**Glide Version/Integration library (if any)**: 3.6.1
**Device/Android Version**: any
**Issue details/Repro steps/Use case background**:
While working on an example for #700 (sample code in that issue) I ran into this problem as well. `ImageVideoBitmapDecoder.getId()` just returns a constant ID:

``` java
@Override public String getId() {
    return "ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap";
}
```

which means that the parameters of the wrapped stream and file descriptor decoders published through their own `getId()` are not taken into account. Which results in false positive cache hits, loading images that are not the right ones. `RegionStreamDecoder` has the following:

``` java
@Override public String getId() {
    return getClass().getName() + region; // + region is important for RESULT caching
}
```

Luckily there's a simple enough workaround, replacing 

``` java
.imageDecoder(new RegionStreamDecoder(context, rect))
```

with

``` java
.decoder(new RegionImageVideoDecoder(context, rect))
```

solves the problem, but then it's required to re-implement the logic inside `ImageVideoBitmapDecoder`.
It takes time however to figure out why `.imageDecoder()` doesn't work as expected.

**Glide load line**:

``` java
Glide
        .with(context)
        .load(url)
        .asBitmap()
        .fitCenter()
        .override(viewWidth, viewHeight)
        .imageDecoder(new RegionStreamDecoder(context, rect))
        .cacheDecoder(new RegionFileDecoder(context, rect))
        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
        .into(holder.imageView)
;
```

**Comment by sjudd** [comment]
Fixed in v4.
