### ISSUE TITLE
DiskCacheStrategy.NONE not working as intended?

### ISSUE THREAD

**Issue by d4rken** [bumptech/glide#711]
Using Glide-Snapshot from today.
Nexus9/Android 6.0

I would like to only use memory for caching and don't want to write any cache files to disk.
I'm under the impression that i could do this using [DiskCacheStrategy.NONE](https://github.com/bumptech/glide/blob/c2fc19316d8680322cabeed31234d19e942866e8/library/src/main/java/com/bumptech/glide/load/engine/DiskCacheStrategy.java#L41)
```
public class GlideConfigModule implements GlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        builder.setDefaultRequestOptions(RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.NONE));
        builder.setDefaultRequestOptions(RequestOptions.priorityOf(Priority.LOW));
    }

    @Override
    public void registerComponents(Context context, Registry registry) {
        // Some custom loaders + decoders that don't chance any caching settings.
    }
}
```

This doesn't seem to work though. A cache folder under /data/data/package/cache/image_manager_disk_cache is still being created.

If i add this it works as desired.
```
        builder.setDiskCache(new DiskCache.Factory() {
            @Nullable
            @Override
            public DiskCache build() {
                return null;
            }
        });
```

**Did i missunderstand the option?**

In case this is a bug, a quick debugging showed the call to orginate from here:

![diskcache](https://cloud.githubusercontent.com/assets/1439229/10713672/dbc8c462-7ac3-11e5-82cd-4be33435c168.PNG)

**Comment by TWiStErRob** [comment]
You're probably setting the options twice, overwriting the previous one. Notice it's called `setDefaultOptions` and not `applyDefaultOptions` (compare to `RequestBuilder.apply`).
Try this:
```java
builder.setDefaultRequestOptions(RequestOptions
    .diskCacheStrategyOf(DiskCacheStrategy.NONE)
    .priority(Priority.LOW)
);  
```
or

```java
builder.setDefaultRequestOptions(new RequestOptions()
    .diskCacheStrategy(DiskCacheStrategy.NONE)
    .priority(Priority.LOW)
);
```

**Comment by d4rken** [comment]
Silly me :smile:.
Suggestion 1 seems to work now.
Thanks Róbert.
