### ISSUE TITLE
How check if image is cached by url

### ISSUE THREAD

**Issue by vavan4567** [bumptech/glide#712]
Hello, I want check if image is already cached by url, if now I will use other url to load image

**Comment by TWiStErRob** [comment]
There's no sync API that was asked for in #509, but you can try the solution I proposed in #639, which looks something like this in your case (see other issue for details):
```java
String urlToLoad = "http://placehold.it/640x480?text=3g";
String urlToCheck = "http://placehold.it/1920x1080?text=wifi";

Glide
	.with(this)
	.using(new NetworkDisablingFetcher())
	.load(urlToCheck)
	.diskCacheStrategy(DiskCacheStrategy.SOURCE)
	.thumbnail(Glide
		.with(this)
		.load(urlToLoad)
		.diskCacheStrategy(DiskCacheStrategy.SOURCE)
	)
	.into(imageView)
;
```

**Comment by vavan4567** [comment]
Thank you! This is what I need :)

**Comment by musicode** [comment]
the code in v4 is not work
