### ISSUE TITLE
Glide sometimes doesn't load image

### ISSUE THREAD

**Issue by vavan4567** [bumptech/glide#715]
Glide sometimes doesn't load image
![image](https://cloud.githubusercontent.com/assets/8720664/10798680/8a6f0612-7db1-11e5-81cc-b27578fcd571.png)

please help, already have searched other issues but it has not helped.

```java
@Override
public void onBindViewHolder(final ImagesViewHolder holder, final int i) {

    String url;
    if (category_list == null) {
        url = Utils.getImageUrl(list.get(i).getId(), list.get(i).getFormat());


        holder.thumbnail.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (MainActivity.isDrawerOpened()) {
                    return;
                }
                FSAdController.checkFsTriger(context);
                GalleryActivity.loadedNumber = GalleryFragment.THIMBNAILS_NUMBER;
                Intent intent = new Intent(context, GalleryActivity.class);
                intent.putExtra("position", i);
                GalleryActivity.setImageList(list);
                GalleryActivity.templateURL = template;
                context.startActivity(intent);
            }
        });
        holder.pannel.setVisibility(View.GONE);
    } else {
        url = category_list.get(i).getImage_url();
        holder.thumbnail.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ((MainActivity) context).gotoCategoryHolder(i);
            }
        });
    }

    Glide
        .with(context)
        .load(url)
        .asBitmap()
        .diskCacheStrategy(DiskCacheStrategy.ALL)
        .into(new BitmapImageViewTarget(holder.thumbnail) {
            @Override
            public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                super.onResourceReady(bitmap, anim);
                if (category_list != null) {
                    String panelColor = "#" + Integer.toHexString(Utils.getDominantColor(bitmap)).substring(2).toUpperCase();

                    holder.pannel.setBackgroundColor(Color.parseColor(panelColor));

                    String textColor = "#" + Integer.toHexString(Utils.
                            getContrastColor(panelColor.substring(1, panelColor.length())))
                            .substring(2).toUpperCase();

                    holder.nameView.setTextColor(Color.parseColor(textColor));
                    holder.nameView.setText(category_list.get(i).getName());
                }
            }
        });
}
```

**Comment by TWiStErRob** [comment]
Hmm, I don't see anything weird there.

The only tip I can give you is to [debug](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) more. I'd do the following:
 * set `Engine`, `GenericRequest`, `EngineRunnable` tag logging to `VERBOSE`  
(may not be possible on Genymotion, only live device)
 * log the `url` you have just before Glide, it can be `null`
 * add a `.listener()` and log all arguments in both methods  
(you can find an example in issue 662: https://github.com/bumptech/glide/issues/662#issuecomment-145555163)
 * add `.placeholder/error/fallback` drawables to see how the load progresses, for example:

    ```java
    .placeholder(android.R.color.holo_green_light)
    .error(android.R.color.holo_red_light)
    .fallback(android.R.color.holo_orange_light)
    ```
 * put a breakpoint in your `OnClickListener` and check the status of `holder.thubmnail` in memory  
layoutParams, width/height, drawable, size/pixels of Bitmap inside drawable (Android Studio has a *View Bitmap* action)

This will hopefully reveal some more information as to why it is not loaded.

**Comment by vavan4567** [comment]
found the reason. It is not inside Glide, my custom ImageView is the reason
 @Override
    protected void onDetachedFromWindow () {
        setImageDrawable(null);
        if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.JELLY_BEAN) {
            setBackgroundDrawable(null);
        } else {
            setBackground(null);
        }
        setImageBitmap(null);
        System.gc();
    }

when I commented that code everything  works nice

**Comment by TWiStErRob** [comment]
Ah, use `Glide.clear(ImageView)` instead of setting the Drawable/Bitmap to null, keep the background related code though.

Also, just `setImageDrawable` alone should clear everything in a general way: any Drawable/resource/Uri/Bitmap set is also cleared, check the ImageView sources.
