### ISSUE TITLE
Caching in recyclerView

### ISSUE THREAD

**Issue by vavan4567** [bumptech/glide#719]
Image loading starts again after scrolling in recyclerView. Can it resume loading or loading in background?

**Comment by TWiStErRob** [comment]
`Glide....into()` "calls" `Glide.clear` before starting a new load, which in turn cancels the download/skips caching the result. You can try to use `preload()` to start the loads independently from views, and I think the usual `.into` calls will attach to the pending load, so no duplicate downloads will happen.

**But**, think about this: do you really want to keep downloading the first 196 items when the user is at the end of the list looking at 4 placeholders for 10 minutes? @sjudd is there a clean solution for this?

Also take a look at `ListPreloader` if that helps.

**Comment by sjudd** [comment]
No clean solution, there's always a conflict here. Either you waste some bandwidth and new images start loading quickly, or you conserve bandwidth but it might take longer for images the user is actually look at to load.

**Comment by sjudd** [comment]
Let us know if you have further questions.
