### ISSUE TITLE
Bug:  Same url  but load different bitmap

### ISSUE THREAD

**Issue by LiHanGuang** [bumptech/glide#721]
Hello @TWiStErRob: 
       me again, I find a bug of glide maybe today, help me please.

**Version: Glide 3.6.1**
build.gradle
compile 'com.github.bumptech.glide:glide:3.6.+'

---
### The description of bug ###
I use the **same url** to load a bitmap into ImageView with Glide in two different way, but load different bitmap unfortunately.
>
url:"http://eim.dyqx.com:9090/plugins/eimplugin/webdav/publicAccount/icon/systemNotifyAvatar.png"

- **first  way:  load the correct bitmap  that i need**
```java
 public static void loadImage(final Context context,
                                 final ImageView imageView,
                                 Drawable placeholder,
                                 Drawable error,
                                 Drawable fallback,
                                 String url,
                                 String token,
                                 Transformation<Bitmap> transformation) {
        GlideUrl glideUrl = null;
        if (!TextUtils.isEmpty(url) && !TextUtils.isEmpty(token)) {
            //url = MyApplication.mServerAddr.replaceUrlDomain(url);
            StringBuilder sb = new StringBuilder(url);
            sb.append("?thumbnail=middle");
            glideUrl = new GlideUrlWithToken(sb.toString(), token);
        }

        Glide.with(context)
                .load(glideUrl)
                .dontAnimate()
                .bitmapTransform(transformation)
                .placeholder(placeholder)
                .error(error) // glideUrl != null, but download fail
                .fallback(fallback) // glideUrl == null
                .into(imageView);
    }
```

- **second way:  load the wrong bitmap  that i do not need**
```java
public static void loadAvaterImage(final Context context, final ImageView imageView , Drawable defAvaterDrawable, String url) {
        if (imageView instanceof CircleImageView) { // CircleImageView is the 3-part library to display a circle Image
            ((CircleImageView)imageView).setCharacterview(false); 
        }

        GlideUrl glideUrl = null;
        if (!TextUtils.isEmpty(url)) {
            //url = MyApplication.mServerAddr.replaceUrlDomain(url);
            StringBuilder sb = new StringBuilder(url);
            sb.append("?thumbnail=middle");
            glideUrl = new GlideUrlWithToken(sb.toString(), PrefUtils.getDownloadToken(context));
        }

        Glide.with(context)
                .load(glideUrl)
                .asBitmap()
                .centerCrop()
                .placeholder(defAvaterDrawable)
                .error(defAvaterDrawable) // glideUrl != null, but download fail
                .fallback(defAvaterDrawable) // glideUrl == null
                .into(imageView);
    }
```

**Comment by TWiStErRob** [comment]
What's `transformation` and `replaceUrlDomain`?

**Comment by LiHanGuang** [comment]
@TWiStErRob 

>
What's transformation and replaceUrlDomain?

**transformation**  is the  **jp.wasabeef.glide.transformations.CropCircleTransformation** in Glide-Transformation library
```java
/**
*  load a circle bitmap instead of using CircleImageView
*/
 public static void loadCircleImage(final Context context, final ImageView imageView, Drawable defDrawable, String url) {
        loadImage(context, imageView, defDrawable, defDrawable, defDrawable, url, PrefUtils.getDownloadToken(context), new CropCircleTransformation(context));
    }
```

---
**replaceUrlDomain**  is use to replace  the  **domain name** like **eim.dyqx.com**  that get from remote server.

**Comment by LiHanGuang** [comment]
@TWiStErRob
### more info ###
when i clear the image cache in disk,  then i use **second way: load the wrong bitmap that i do not need**  to load the image again, it is correct, /(ㄒoㄒ)/~~.

**Comment by TWiStErRob** [comment]
Assuming you used GlideUrlWithToken from https://github.com/bumptech/glide/issues/607#issuecomment-140692460 there should be no problems with Glide.

Here is the consolidated version of your above codes:
```java
// avatar
if (imageView instanceof CircleImageView) {
    ((CircleImageView)imageView).setCharacterview(false);
}

// common
String url = "http://eim.dyqx.com:9090/plugins/eimplugin/webdav/publicAccount/icon/systemNotifyAvatar.png?thumbnail=middle";
url = MyApplication.mServerAddr.replaceUrlDomain(url);
GlideUrl glideUrl = new GlideUrlWithToken(url, PrefUtils.getDownloadToken(context));

Glide.with(context)
    .load(glideUrl) // common
    .asBitmap() // avatar
    .dontAnimate() // common
    .bitmapTransform(new CropCircleTransformation(context)) // circle
    .transform(new CenterCrop(context)) // avatar
    .placeholder(defDrawable) // common
    .error(defDrawable) // common
    .fallback(defDrawable) // common
    .into(imageView); // common
```

1. What is the url of the wrong image?
2. Do you use integration libraries (okhttp for example)?
3. Do you actually use a 3rd party CircleImageView in any of the problematic cases?
4. Do any of the placeholders look like "girl with headset" image?
5. [Double-check](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) if your url (model) is really the same for the two loads.
6. Please [enable cache logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) (or debug [`Engine.load`](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/Engine.java#L142)) to see the actual un-hashed cache keys  
The different transformations and `asBitmap` together should ensure that there's no clash here, my best guess is that you're somehow not passing the same url, or you have multiple loads into the same ImageView somewhere.  

+1. `loadCircleImage` javadoc is outdated ;)

**Comment by LiHanGuang** [comment]
@TWiStErRob 
After open the log of glide, i have two output below:

- first way: load the correct image that looks like "loudspeaker" image
```java
11-03 09:45:13.230  14358-14358/com.jiahe.qixin V/Engine﹕ Started new load in 1.9826929999999998ms, key: EngineKey{http://eim.dyqx.com:9090/plugins/eimplugin/webdav/publicAccount/icon/systemNotifyAvatar.png?thumbnail=middle+com.bumptech.glide.signature.EmptySignature@3c58a167+[144x144]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CropCircleTransformation()'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
11-03 09:45:13.287  14358-14480/com.jiahe.qixin V/DecodeJob﹕ Decoded transformed from cache in 57.590692, key: EngineKey{http://eim.dyqx.com:9090/plugins/eimplugin/webdav/publicAccount/icon/systemNotifyAvatar.png?thumbnail=middle+com.bumptech.glide.signature.EmptySignature@3c58a167+[144x144]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CropCircleTransformation()'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
11-03 09:45:13.288  14358-14480/com.jiahe.qixin V/DecodeJob﹕ Transcoded transformed from cache in 0.798692, key: EngineKey{http://eim.dyqx.com:9090/plugins/eimplugin/webdav/publicAccount/icon/systemNotifyAvatar.png?thumbnail=middle+com.bumptech.glide.signature.EmptySignature@3c58a167+[144x144]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CropCircleTransformation()'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
```

- second way:  load the wrong image that looks like "girl with headset" image
```java
11-03 09:41:45.725  13470-13470/com.jiahe.qixin V/Engine﹕ Started new load in 2.4006149999999997ms, key: EngineKey{http://eim.dyqx.com:9090/plugins/eimplugin/webdav/publicAccount/icon/systemNotifyAvatar.png?thumbnail=middle+com.bumptech.glide.signature.EmptySignature@d07e126+[144x144]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}
11-03 09:41:45.783  13470-13583/com.jiahe.qixin V/DecodeJob﹕ Decoded transformed from cache in 58.222231, key: EngineKey{http://eim.dyqx.com:9090/plugins/eimplugin/webdav/publicAccount/icon/systemNotifyAvatar.png?thumbnail=middle+com.bumptech.glide.signature.EmptySignature@d07e126+[144x144]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}
11-03 09:41:45.783  13470-13583/com.jiahe.qixin V/DecodeJob﹕ Transcoded transformed from cache in 0.037923, key: EngineKey{http://eim.dyqx.com:9090/plugins/eimplugin/webdav/publicAccount/icon/systemNotifyAvatar.png?thumbnail=middle+com.bumptech.glide.signature.EmptySignature@d07e126+[144x144]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}
```

**Comment by LiHanGuang** [comment]
>
1. What is the url of the wrong image?
2. Do you use integration libraries (okhttp for example)?
3. Do you actually use a 3rd party CircleImageView in any of the problematic cases?
4. Do any of the placeholders look like "girl with headset" image?

**Repply:**
question 1:  sorry, i did not findout temporarily.
question 2:  i also use okhttp  as netlayer of my app.
question 3:  CircleImageView  there is some bug with glide,  but i know that.  you can see my answer in https://github.com/bumptech/glide/issues/482,  so i use **asBitmap** in **second way** to avoid this bug.
question 4: i also  check this, but my placeholder is the bitmap that looks like "loudspeaker" .  not the  "girl with headset".

**Comment by LiHanGuang** [comment]
Hello @TWiStErRob:

I create a **TestGlide** to to reappear this problem today.  Maybe helpful, thanks.

**addr**: https://github.com/LiHanGuang/TestGlide

**Usage**
1.  copy the folder **SD_Card/imageCache** to  **EXTERNAL STORAGE**
2. complie and install the apk.

**Comment by sjudd** [comment]
This is working as intended. The url is the cache key, so if you try to load the same url twice and expect a different image each time, it's not going to work.

Either disable caching for this particular request using ``DiskCacheStrategy.NONE``, or take a look at the [caching wiki page][1] for options on how to customize cache invalidation.

[1]: https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation

**Comment by TWiStErRob** [comment]
(sketched up before Sam closed it, so I'll send it in hope that it helps)

Obivously if you hack the cache it'll display whatever image is in the File. Glide won't download and transform from the original Url just to verify cache integrity :)

I just ran the app after build | 6f0ddd257f752aad 580ed356c9f5bc7a 656532383590011f 57cbfa0231b7acc4 | 995b636db5ccd7bc 13304d105401b5a0 27b284369e7711e8 6fb652cdd2979a1f
---|---|---
![image](https://cloud.githubusercontent.com/assets/2906988/10910669/fca66e08-8240-11e5-8fd7-de662a94cc4b.png) | ![6f0ddd257f752aad580ed356c9f5bc7a656532383590011f57cbfa0231b7acc4 0](https://cloud.githubusercontent.com/assets/2906988/10910711/37a3d928-8241-11e5-9702-0cf1a2f2f64b.png) | ![995b636db5ccd7bc13304d105401b5a027b284369e7711e86fb652cdd2979a1f 0](https://cloud.githubusercontent.com/assets/2906988/10910714/39edbf32-8241-11e5-95a5-a686ad9e5974.png)

**The main question is: how did that file got there in the first place?**
It is possible that "girl with headphones" image was displayed in your app in another place (you know where) and the cache keys are the same. It is possible, but highly unlikely to have a key collision. Notice that the cache-key is a length-limited hexadecimal string so it two different strings can end up with the same hash. You may have found one such case.

You're using RESULT cache only, that's why the same Url ends up with different cache keys, here's a consolidated version of your logs:
```ruby
URL: http://eim.dyqx.com:9090/plugins/eimplugin/webdav/publicAccount/icon/systemNotifyAvatar.png?thumbnail=middle
KEY1: EngineKey{<URL>+EmptySignature@32d40df8+[144x144]+''+'ImageVideoBitmapDecoder'+'CropCircleTransformation()'+'BitmapEncoder'+'GifBitmapWrapperDrawableTranscoder'+''}
V/Engine﹕ Started new load in 1.993ms, key: KEY1
V/DecodeJob﹕ Decoded transformed from cache in 59.609, key: KEY1
V/DecodeJob﹕ Transcoded transformed from cache in 0.714, key: KEY1
D/GLIDE﹕ onResourceReady(GlideBitmapDrawable@2171e72f, <URL>&token=<token1>, Target for: view, false, true)
D/GLIDE﹕ onResourceReady(GlideBitmapDrawable@3909665c, <URL>&token=<token1>, Target for: view, true, true)
V/Engine﹕ Loaded resource from cache in 2.501ms, key: KEY1

KEY2: EngineKey{<URL>+EmptySignature@300feefe+[144x144]+''+'ImageVideoBitmapDecoder'+'CenterCrop'+'BitmapEncoder'+''+''}
V/Engine﹕ Started new load in 1.945ms, key: KEY2
V/DecodeJob﹕ Decoded transformed from cache in 56.347, key: KEY2
V/DecodeJob﹕ Transcoded transformed from cache in 0.035, key: KEY2
D/GLIDE﹕ onResourceReady(Bitmap@7d0a975, <URL>&token=<token2>, Target for: view, false, true)
D/GLIDE﹕ onResourceReady(Bitmap@7d0a975, <URL>&token=<token2>, Target for: view, true, true)
V/Engine﹕ Loaded resource from cache in 0.566ms, key: KEY2
```

**Comment by LiHanGuang** [comment]
@ TWiStErRob  sjudd:
 first, thanks a lot.  
- I will try to find out the  **"girl with headphones"**'s url for more test.

- Question:   How to avoid **key collision** under the situation that **Notice that the cache-key is a length-limited hexadecimal string so it two different strings can end up with the same hash.**

**Comment by TWiStErRob** [comment]
As I said it is extremely unlikely (there are 16^64=1e77 possible hashes). I guess the easiest is `.signature(antiCollision)` where `static final Key antiCollision = new StringSignature("*")`. Any one bit difference in the input (in any field of EngineKey) may change the hash significantly (beyond recognition). You need to add it only for one of the conflicting loads. But **first try to reproduce and confirm that this is happening.**

Here's an example of Java's hash collision (which has only 2^32=4e9 possibilities): http://stackoverflow.com/q/9406775/253468
Glide is not using that (hashCode) but it can help to understand what's happening.

Do report back if you find a reproducible case.
