### ISSUE TITLE
Check if url2 is in cache else show url1

### ISSUE THREAD

**Issue by sumbulAlvi** [bumptech/glide#726]
I've seen that this question has been asked a few times before (https://github.com/bumptech/glide/issues/639), however, perhaps there is a solution for my particular usecase that I am overlooking? I need the functionality as follows:

My network response for the post provides me 2 urls, url1 = the first frame of the gif (png), url2 = link of the actual gif. I only want to load url1 if the full gif (url2) has not been downloaded before by Glide.
The condition is: 
=> Show url1 if the user has not downloaded url2 (the full gif) before.

The only alternative I can think of is placing a click listener on the image which launches activity2 which downloads url2. However, that requires holding on to states and holding on to flags set in the click listener which seems unnecessarily complex & messy. Do you have any suggestions on using the Glide interface/components to achieve this behavior?

Thanks!

**Comment by TWiStErRob** [comment]
You can use `NetworkDisablingFetcher` for url2 with a listener where you can load url1 in onException and if it was cached url2 will be displayed.

**Comment by sumbulAlvi** [comment]
I'll try that out and see if it works, thanks!

**Comment by sumbulAlvi** [comment]
Update: Successful with this solution, thanks @TWiStErRob
