### ISSUE TITLE
Load gif failed.

### ISSUE THREAD

**Issue by q422013** [bumptech/glide#728]
i use "Glide.with(MainActivity.this).load(url).asGif().into(imageView);" and look netwrok,after 5s imageview not load gif, but i use diskCacheStrategy(DiskCacheStrategy.SOURCE) can load gif.

**Comment by TWiStErRob** [comment]
Duplicate of #513 or #281 (see #600 for simpler discussion).

**Comment by q422013** [comment]
Thanks,
