### ISSUE TITLE
Clean up Downsampler Strategies

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#730]
Branching of from the discussion in #727:

> Sam said: The names here are pretty poor, sorry for that. Is there some standard naming convention for these transformations? Alternative suggestions welcome. I'm not totally sure that FIT_INSIDE is much clearer than CENTER_INSIDE, though I agree CENTER_INSIDE is poor. If we rename CENTER_INSIDE to FIT_INSIDE, what do we call the equivalent strategy that doesn't downsample?

(0) I created a [comparison of scales and downsamplers](https://docs.google.com/spreadsheets/d/1S7xw_KHlOt6KHZ_yi0Zz01sdBJaMgXlzy3L2qr1fJFc/edit?usp=sharing) document with some proposed changes, would you agree with those names? My suggested changes are highlighted with a background. JavaDoc of all mentions are in notes (hover the cells)

> what do we call the equivalent strategy that doesn't downsample?

That sounds like `NONE`... @sjudd can you clarify that please?

---

(1) `CENTER` in the name is strange in any case, because there's no centering done in any of the downsample strategies. Alignment suggest a container, which we don't have. We could argue that the requested size is a container, but then we should add padding to align to the center, which we agreed was not the right way to go. So I suggest to change `CENTER_` to `FIT_`.

---

(2) I would say even the `AT_LEAST`/`AT_MOST` should be prefixed with `FIT_` to show the intention of always scaling somewhat. For me "at least" doesn't have an upper bound (implying now downscaling of big images), while the strategy in Glide clearly has the 0.5x-2x limit which implicitly restricts the other side (aspect ratio).

---

> (3) from JavaDoc: "On pre-KitKat devices, this is equivalent to AT_X because only power of two downsampling can be used."

There are a few things here:
- If current `CENTER_OUTSIDE` is the same as `AT_LEAST` pre-KitKat, then that should be the default: this would potentially reduce some loading times because the downsampled image will be already matching the transformation that would be appliled later, so the `return original` shortcuts will be taken inside the transformations.
- If pre-KitKat crashes or there are versions that can't handle the better version of `AT_LEAST` (currently `CENTER_OUTSIDE`), the `DEFAULT` could be still initialized according to `SDK_INT`.
- In any case there's a `DownsamplerStrategy.DEFAULT` which I think should be used for the `Downsampler.DOWNSAMPLE_STRATEGY` option.

---

(4) `ScaleType.FIT_XY` currently uses the default strategy which is `AT_LEAST`, this results in upscaling small images and downscaling bigger ones. FIT_XY will scale anyway, so there's no point in upscaling the small images (reduces memory footprint) also big images could be pre-fit to the size so the distortion only has to go in one direction, which may potentially improve image quality. So I propose to add a `case` into `RequestBuilder.into(ImageView)` to set `downsampler()` to the one created in #727.

**Comment by sjudd** [comment]
I think this was done in https://github.com/bumptech/glide/commit/aa751f6289ea16ef35955f7563038c6c51c6a4e2

**Comment by TWiStErRob** [comment]
@sjudd what about the (1)-(4) points? Do you have any comments on them?

**Comment by sjudd** [comment]
(1) - I agree in principle, but in practice I think the CENTER_ names align with with [ImageView#ScaleType][1], which I think makes them easier to understand, even if it means the name is a bit off.

(2) - I agree again that AT_MOST/AT_LEAST isn't obvious. That said, I'm not sure prepending them with FIT_ really clarifies anything? These transformations are going to be a bit confusing and probably will need people to read the javadoc to fully understand them. If you think adding FIT_ (or any other name change) would make them clearer I'd be happy to take a PR that adds new versions and deprecates the old names.

(3) You're correct, a much better default is CENTER_OUTSIDE, I'll make that change. Thanks for pointing it out

(4) I agree here too, I'll make that change, thanks again.

[1]: https://developer.android.com/reference/android/widget/ImageView.ScaleType.html

**Comment by sjudd** [comment]
I'm going to assume this is fixed for now. Let me know if you disagree.
