### ISSUE TITLE
Skipping place holder display / warming up the cache

### ISSUE THREAD

**Issue by stephanenicolas** [bumptech/glide#732]
In Picasso, if the image is in RAM cache, Picasso won't display the place holder at all. 

Is there such a feature in glide ?  
To be clear, we still want to use a place holder but display it only in case the image needs to be downloaded. If the image is in cache, we want to skip it and avoid filling pixels twice...
To achieve that, Picasso needs the cache to be warmed up so that images pass from disk cache to RAM cache. Does the same logic apply with Glide ?

We are looking for this optimisation to get fast as light application startup.

Thx in advance !

**Comment by TWiStErRob** [comment]
Yes, placeholder is only displayed when there's background work. When hitting memory cache image is displayed immediately. Also animations are not played in this case (but that can be worked around).
That warmup thing sounds like `preload`.

Read up on the wiki for basics: https://github.com/bumptech/glide/wiki.

Also try searching the issues if you have a question, we have a lot of valuable information here, sadly it's a little unstructured.

As for fast startup: Glide is only initialized on the first image load (i.e. Glide.* call), until then even the classes stay unloaded.

**Comment by stephanenicolas** [comment]
Thx, for reference here is the issue in Picasso : 
https://github.com/square/picasso/issues/1005

**Comment by stephanenicolas** [comment]
Thx @TWiStErRob , I have spent 30 minutes searching the wiki and google but that very specific information was not available. And yeah, I had understood preload was the glide way to fill memory cache, but I couldn't find out if place holder would still be displyaed or not if an image is in RAM cache.

**Comment by TWiStErRob** [comment]
That's where actual experimentation comes in handy: if you want to know what happens, just try it ;)

You can also learn a lot if you follow a load through from `into` until `Target.setResource`. I did that once and still using that knowledge to answer questions.

Actually the best place for this info would be on the `.placeholder()` method...

**Comment by stephanenicolas** [comment]
You mean the javadoc ?

**Comment by TWiStErRob** [comment]
Yes, https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/GenericRequestBuilder.java#L440
It actually says "while a resource is loading", but it could be more explicit.

**Comment by stephanenicolas** [comment]
Yeah, the doc should be more explicit. Even background in your first answer would not be precise enough as it requires to know that RAM cache is accessed in foreground.
