### ISSUE TITLE
Glide with proguard

### ISSUE THREAD

**Issue by mdtuyen** [bumptech/glide#737]
I make some error when use glide with proguard. With Glide I use:
```pro
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
    **[] $VALUES;
    public *;
}
```
Is it a recommend ?

**Comment by TWiStErRob** [comment]
That should be enough, if you don't use [integration libraries](https://github.com/bumptech/glide/wiki/Integration-Libraries#okhttp-proguard).
What is your error?

**Comment by mdtuyen** [comment]
In log file:
```
 E/AndroidRuntime:  Caused by: java.lang.IllegalArgumentException: You must pass in a non null View
 E/AndroidRuntime:     at com.bumptech.glide.e.into(Unknown Source)
 E/AndroidRuntime:     at com.bumptech.glide.c.into(Unknown Source)

```
I will check others

**Comment by TWiStErRob** [comment]
That doesn't look like a proguard issue related to Glide, simply double check if you're initialising the view's variable correctly: for example `findViewById` may return null.

Also make sure you add keeps for your custom views and their constructors (however this should be in the SDK's default proguard file, you just have to copy that)
