### ISSUE TITLE
Glide for internal memory images?

### ISSUE THREAD

**Issue by fmeneuhe** [bumptech/glide#739]
Hi,
Can be used Glide to load images from internal memory or just from url images?
Thanks

**Comment by TWiStErRob** [comment]
Glide can load from any source/any format/into anything, the questions is how much you want to customize it.

Your issue sounds like #122 where I suggested a workaround (but I advise against using it).
Please read that carefully and feel free to reopen this if your case is not the same or want to clarify more.
