### ISSUE TITLE
Scroll issue - not loading image from memory cache

### ISSUE THREAD

**Issue by apat183** [bumptech/glide#74]
Hi,

First just want to say this project is awesome, fastest android imageloader out. However I'm having a problem.

When scrolling up a list and stopping, sometimes glide doesn't load images. I notice this is only when the image is loaded from memory cache and not disk cache. 

I determined it was something with memory cache by disabling memory cache. Once disabled it had no problems. Also it only happens to images recently loaded (in memory). 

I've tired the following but only disabling memory cache fixes it.
- disabled bitmap recycling
- resized memory cache
- set Glide.cancel(imageview) before loading image
- set a placeholder

Here is some overview of my project to help.

I'm using Gabriele Mariotti's card lib to create a card list. https://github.com/gabrielemariotti/cardslib.

``` java
CardArrayAdapter mCardArrayAdapter = new CardArrayAdapter(getActivity(), cards);
mCardArrayAdapter.setEnableUndo(true);

CardListView listView = (CardListView) getActivity().findViewById(R.id.myList);

if (listView != null) {
    listView.setAdapter(mCardArrayAdapter);
}
```

Here is a link to the source code CardArrayAdapter that I'm using:
https://github.com/gabrielemariotti/cardslib/blob/0573f71bcd8c5b2298e6e45d0742af6a8e9a5aa3/library/src/main/java/it/gmariotti/cardslib/library/internal/CardArrayAdapter.java

This calls the following code for each card item when the card is loaded in the list

``` java
@Override
public void setupInnerViewElements(ViewGroup parent, View view) {
    TextView title = (TextView) view.findViewById(R.id.carddemo_myapps_main_inner_title);
    title.setText(headerTitle + " (" + year +")");

    TextView subtitle = (TextView) view.findViewById(R.id.carddemo_myapps_main_inner_secondaryTitle);
    subtitle.setText(plot);

    ImageView img = (ImageView) view.findViewById(R.id.card_thumbnail_layout);

    Glide.load(imageURL)
            .error(R.drawable.postererror)
            .into(img);
}
```

I'm also editing the ImageManager. I don't think this has an impact and I've tired it commented out and used the default settings but didn't make a difference.

``` java
Glide glide = Glide.get();

final int memoryCache = ImageManager.getSafeMemoryCacheSize(this) * 2;

final int DEFAULT_DISK_CACHE_SIZE = 500 * 1024 * 1024;

if (!glide.isImageManagerSet()) {
    glide.setImageManager(new ImageManager.Builder(this)
                    .setDiskCache(DiskLruCacheWrapper.get(ImageManager.getPhotoCacheDir(this), DEFAULT_DISK_CACHE_SIZE))
                    .setMemoryCache(new LruMemoryCache(memoryCache))
                    .build()
    );
}
```

I made a video which shows the problem. It starts at about 30 secs into the video. As you will see, when you scroll up, some items have a blank image. It only occurs in the first 15-20 items, then it loads fine (since it's loading from disk). 

FYI, when I put a placeholder, instead of a blank image, the placeholder is loaded. So it appears that Glide is called. Also if I leave the screen on the blank image it never loads. But if I turn the screen off and on, or exit the app and open it again (open where it left of). The image will load.

http://goo.gl/7A7Vqi

I'm using version 2.0.3.

**Comment by Curragh-exotic** [comment]
> Everything you're doing as far as you've shown looks correct to me.
> 
> There are a couple of things I can think of off of the top of my head that will prevent Glide from completing a load:
> 
> 1. If the exact same url is already either being loaded or has been loaded into the view, Glide will ignore the new request.
> 2. If the view doesn't have a valid size, Glide will add a [GlobalLayoutListener](http://developer.android.com/reference/android/view/ViewTreeObserver.OnGlobalLayoutListener.html) and wait until the view goes through layout to start to load.
> 3. If the loaded image is null, Glide will simply do nothing.
> 
> Of these, if 1 were the cause, I'd expect always calling Glide.cancel to fix the problem. If 3 were the cause, I'd think the memory cache would be totally unrelated.
> 
> Given that you're reusing views, I'd also be surprised if 2 is the cause, but there may be something unique about the way the card library you're using is working. I can't reproduce the issue you describe with my demo app, but I'll take a look and see if I can't find a way to reproduce it if I build something using the card library you linked.
> 
> In the meantime, if you're building from source, you could throw a couple of breakpoints in the [set model](https://github.com/bumptech/glide/blob/master/library/src/com/bumptech/glide/presenter/ImagePresenter.java#L387) method and see if you can't figure out which of the various branches is taken for that image (easier said than done I know).





https://stackdev.space/questions/what-steps-are-needed-to-generate-a-horizontal-lineup-of-image-views-on-an-android-device
