### ISSUE TITLE
some url image doesnt load while url is correct. error is null !

### ISSUE THREAD

**Issue by hisham2007** [bumptech/glide#741]
Dears,
         Thanks for your great effort. I use Glide 3.6.1. some images are not loaded while url is correct.
example: http://admin.elwatannews.com/uploads/image_archive/648x316/16364238551441829734.jpg

Glide calls onLoadFailed with error (null) which doesnt help me to know what is the issue

**Comment by TWiStErRob** [comment]
I just tried the simplest `Glide.with(this).load(url).into(imageView)` on a Galaxy S4 and it works fine.

`null` error usually means `null` model (passed to `.load()`), please try a [`.listener`](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) and log/debug both variables.

It sounds like you're using a custom target (or debugging ImageViewTarget), can you please give more details based on our [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues).

**Comment by hisham2007** [comment]
I will check issue template and stick to it. but as a quick answer, here is my code:

  Glide.with(activity)
                .load(feed.getMediaUrl())
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .fitCenter().crossFade()
                .into(new GlideDrawableImageViewTarget(holder.imgFeed) {
                    @Override
                    public void onLoadFailed(Exception e, Drawable errorDrawable) {
                        super.onLoadFailed(e, errorDrawable);
                        holder.imgProgressBar.setVisibility(View.INVISIBLE);
                    }

                    @Override
                    public void onResourceReady(GlideDrawable drawable, GlideAnimation anim) {
                        super.onResourceReady(drawable, anim);
                        holder.imgProgressBar.setVisibility(View.INVISIBLE);
                    }
                });



the holder.imgFeed is a custom image view that extends normal image view but make its ratio 16:9

my app is : https://play.google.com/store/apps/details?id=com.tabe3.news
but it is in Arabic for now.

**Comment by TWiStErRob** [comment]
I suggest that you use `.listener()` to set visibility, that makes it independent from the target.
Can you please try with a stock `ImageView` if the problem still comes up?
Did you try debugging via logging (https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener)?

**Comment by TWiStErRob** [comment]
Assuming you managed to find out what caused the problem via `.listener()`, I'm closing this. Feel free to reopen if you're not satisfied with this.

**Comment by archpoint** [comment]
Apologies to open a year old issue, but I'm having the exact same issue. Exception is null and I have no idea why some of my images wont load. The URLs passed into Glide seem fine. 

```
       @Override
        public void onBindViewHolder(ViewHolder holder, int position) {
            final Location location = mLocations.get(position);

            holder.title.setText(location.getTitle());
            holder.deviceCount.setText(String.format("%d %s", location.getDeviceCount(), getString(R.string.locations_devices)));
            if (location.hasImage()) {
                String imageUrl = NetworkHelper.getImageUrl(getContext(),location.getImageName());
                holder.image.setVisibility(View.VISIBLE);
                // Use Glide for image loading
                Glide.with(getContext())
                        .load(imageUrl)
                        .diskCacheStrategy(DiskCacheStrategy.ALL)
                        .centerCrop()
                        .into(new GlideDrawableImageViewTarget(holder.image) {

                            @Override
                            public void onLoadFailed(Exception e, Drawable errorDrawable) {
                                super.onLoadFailed(e, errorDrawable);
                                e.printStackTrace();
                            }

                            @Override
                            public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> animation) {
                                super.onResourceReady(resource, animation);
                            }
                        });
            } else {
                // Due to the nature of the RecyclerView, we need to ensure we clear
                // out images to odd behavior.
                Glide.clear(holder.image);
                holder.image.setVisibility(View.GONE);
            }
        }
```

I've tried hardcoding one of the URLs that fails and it fails consistently so there must be something about those specific images Glide doesnt like though I cant quite see why. I can download them manually just fine.

Thanks!
