### ISSUE TITLE
load with same url twitce but onResourceReady callback only execute one times

### ISSUE THREAD

**Issue by michaellct** [bumptech/glide#742]
I have a button on activity to share with.
first cliked is ok,and callback execute ,but if i clicked twice then no callbak executed.
is anything mistake?
below is my code,thank you very much!
```
Glide.with(activity).load(imageUrl).asBitmap().into(new SimpleTarget<Bitmap>(150, 150) {
    @Override
    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
       //share code
    }
}
```

**Comment by TWiStErRob** [comment]
I don't see anything wrong with this, does the click listener execute?

**Comment by michaellct** [comment]
@TWiStErRob   the click listener execute yes
and i try catch my code i found that when execute twitce cause an execption:
java.lang.IllegalArgumentException: You must call this method on the main thread

below is my code:
```
try{
Glide.with(activity).load(imageUrl).asBitmap().into(new SimpleTarget<Bitmap>(150, 150) {
    @Override
    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
       //share code
    }
}
} catch (Exception e) {
            int i=2;
            i++;
        }
```

**Comment by TWiStErRob** [comment]
Yes, `into()` has to be called on the main thread. Check your code flow or debug stack or  `printStackTrace`, maybe you're calling it from an async task or similar.

**Comment by michaellct** [comment]
thank you very much
i found the reason is that i called from webview's Javascript Interface sometimes(not main thread)
but other error found is that sometimes resource.isRecycled() could changed to true

**Comment by michaellct** [comment]
all is my code issue,not glide business,so i closed this
