### ISSUE TITLE
Some Question about load Image from Interent

### ISSUE THREAD

**Issue by Samsu7609** [bumptech/glide#744]
&lt;description removed by author&gt;

**Comment by TWiStErRob** [comment]
Please give more information, for example see [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues).

Also what does "not show" mean? (black, transparent, partial, loading extremely slow, placeholder... etc.)

You should also try adding a [`.listener()`](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) and check if there's an exception thrown.

Are you using the view holder pattern for the list?
