### ISSUE TITLE
What is the RecyclerViewPreloader?

### ISSUE THREAD

**Issue by Orbyt** [bumptech/glide#745]
Are there any docs about using it?

**Comment by TWiStErRob** [comment]
Flickr, gallery and giphy samples all use it: https://github.com/bumptech/glide/tree/master/samples

**Comment by Orbyt** [comment]
@TWiStErRob Yes, was looking for some documentation on it though, if there is any.

**Comment by TWiStErRob** [comment]
Only the class JavaDoc and the sample codes I'm aware of.
It should be straightforward to use it from these.
