### ISSUE TITLE
Load Video Thumbnail

### ISSUE THREAD

**Issue by hateum** [bumptech/glide#750]
How can I load Thumbnail from a video url.
for now I use "MediaMetadataRetriever" to get the bitmap but I want to load it with glide.
is this possible ?

**Comment by TWiStErRob** [comment]
I never did that, but did you try just loading it with `.load(Uri)`? Maybe an additional `.asBitmap()` but not necessarily. Also see http://stackoverflow.com/a/30769399/253468

**Comment by hateum** [comment]
Glide fetch thumbnail of local video only.
I'm asking for a solution to get thumbnail of video from network

**Comment by TWiStErRob** [comment]
Hmm, in that case I suggest that you write a custom model and `DataFetcher`, something like #699.

**Comment by hateum** [comment]
Thanks, working like a charm

**Comment by TWiStErRob** [comment]
I think in case of a video it's important to note to use `RESULT` cache only, to prevent saving the whole video to disk cache even though only a single frame is needed from it. And hopefully that single frame will be decoded from a significantly smaller fraction of the file at the beginning.

**Comment by TWiStErRob** [comment]
Related https://github.com/bumptech/glide/issues/872

**Comment by arvi** [comment]
@hateum Hello, would you mind sharing how you get it to work with remote url. I am having the same issue and can't figure out the custom model/data fetcher thing.

**Comment by santhoshrao519** [comment]
Hey Gents,
I have a solution for the video thumbnail from remote url.

  long interval = 5000 * 1000;
        RequestOptions options = new RequestOptions().frame(interval);
        Glide.with(context).asBitmap()
                .load(APIConfig.URL_VIDEOLOC+feedItem.getVideoFile())
                .apply(options)
                .into(feedListRowHolder.videoView.getCoverView());

Happy Coding :-)

**Comment by zeeshanaslam78** [comment]
@santhoshrao519 I tried but It didn't work.

**Comment by diaz9557** [comment]
@hateum Can you please post the working Custom implementation for loading thumbnail from a server url of video . I am stuck here for days .

I am currently using .

` implementation 'com.github.bumptech.glide:glide:4.7.1'
  annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'`

**Comment by santhoshrao519** [comment]
@hateum hey once try my solution

**Comment by MOhsain** [comment]
@santhoshrao519 Thanxk You :)
