### ISSUE TITLE
Displaying in RGB_565, downloading in ARGB_8888

### ISSUE THREAD

**Issue by redwarp** [bumptech/glide#751]
I'm working on an app that uses Glide to display a lot of pictures, and it's awesome. Low memory, thanks to the default format that is ```RGB_565```.
But at some point, I wanted to allow the user, after he clicks on a thumbnail, to send an image resized to 1000x1000 to a server.
I thought "oh great, Glide can do the resizing! I'll use Glide to load my url, then ```downloadOnly``` to my final size. That will get me a File, that I can use in a ```FileInputStream```.

And it works! But the final result is, of course, in ```RGB_565``` as well. And so far, I found no way to force Glide to use ```setDecodeFormat``` for only one operation.
It's either I setup the GlideModule for ```ARGB_8888```, and that will be used everywhere in the app, or keep using ```RGB_565```.

Is it possible to force Glide to use a decode format for one operation? (If not, it would be a great feature!)

Thanks in advance.

**Comment by TWiStErRob** [comment]
```java
.asBitmap()
.format(DecodeFormat.PREFER_ARGB_8888)
```

I'm not sure how you used `downloadOnly` to resize the picture, that method is used to fill the `SOURCE` cache. Consider this code which goes a step further than loading a Bitmap to memory:
```java
Glide
	.with(this)
	.load(uri)
	.asBitmap()
	.toBytes(CompressFormat.JPEG, 80)
	.format(DecodeFormat.PREFER_ARGB_8888)
	.atMost()
	.override(1000, 1000)
	.diskCacheStrategy(DiskCacheStrategy.NONE)
	.skipMemoryCache(true)
	.into(new SimpleTarget<byte[]>() {
		@Override public void onLoadStarted(Drawable placeholder) {
			// maybe start spinning
		}
		@Override public void onResourceReady(byte[] resource, GlideAnimation<? super byte[]> ignore) {
			// start async task to save or send
		}
		@Override public void onLoadFailed(Exception ex, Drawable ignore) {
			// tell the user that you're sorry
		}
	})
;
```

**Comment by redwarp** [comment]
Whaou thanks for the answer, you are quite awesome! I'll try that tomorrow!
If I want to use it synchronously, can I, like usual, get a Future, and call .get() on it?
