### ISSUE TITLE
Caching/Loading Images with Redirect URLs

### ISSUE THREAD

**Issue by sumbulAlvi** [bumptech/glide#752]
Hi, for loading images with redirect urls, I know I can't use the typical patterns to load images:
```
Glide.with(context).load(url).into(imageView);
```
The use case is, when I have this static URL for example:
https://api.tumblr.com/v2/blog/droidtest.tumblr.com/avatar/512
which loads an image at dynamic URL 
https://31.media.tumblr.com/avatar_39c2a050ff8b_512.png currently. 

When the avatar image is changed, the dynamic URL changes to be the new image URL however, the static URL remains the same. I thought of using a custom loader to be able to cache the downloaded image under the static URL, but download it from the dynamic URL with no luck so far. I've tried to extend the `BaseGlideUrlLoader`, overriding `getUrl()`->returns `dynamicUrl` and the `getResourceFetcher` with no luck.

Is there any way to force the key of a request to be the static URL and the resource to be downloaded from the dynamic URL?

```
Glide.with(context)
        .accessURL(staticUrl)
        .downloadResourceUrl(dynamicUrl)
        .preload();
```
So that the correct resource is ready for display when it is accessed via `staticUrl`?

**Comment by sumbulAlvi** [comment]
I've used a signature with a static upload counter 
Note: In the following explanation, `resource` referes to a bitmap or image data at some location.

The usecase is as follows:
Currently:
1) User navigates on to their blog, their avatar image is loaded using:

```
(*) Glide.with(context).load(urlStatic).into(imageView)
````
Goes to the network because not found in cache. Now the key `urlStatic` exists in cache to the avatar `resource1`.
2) User changes image and uploads a new one, upload success response provides the new url that the new avatar `resource2` is available at.

**Problem:**
Coming back from the upload flow, we try to load the avatar image using `(*)` again. However, it doesn't go to network because it is found in cache.

**Solution**
1) Upon upload, delete entry `urlStatic` from cache so that next time it's accessed from anywhere it hits the network and caches the newly `resource2` with key `urlStatic`
2) Use a static public counter used in the signature that will be incremented everytime a user uploads a new image - this works but disliked as the `urlStatic` is accessed from multiple places and adding a `signature(uploadCount)` to calls is unfavorable and unclean.
3) Upon upload response, use the new URL to somehow download the bitmap/resource data and set it as the `urlStatic` content.

**Comment by TWiStErRob** [comment]
OK, so that's the usual problem people run into.
See #624's second question and discussion.

**Comment by sumbulAlvi** [comment]
Looks like using the signature per request will be the solution. Thanks!

**Comment by aminography** [comment]
https://github.com/bumptech/glide/issues/1750#issuecomment-438344311
