### ISSUE TITLE
onLoadFailed Exceptions when loading into SimpleTarget

### ISSUE THREAD

**Issue by rohanmahale** [bumptech/glide#753]
I am using Glide as the image loading lib within my project as I am very happy with it's memory performance. However, I when I download images as bitmaps using simpletarget, I do get failures to load the image.

```java
Glide.with(this)
	.load(Utils_
		.getInstance_(application)
		.getGlideURLWithHeaders(WebServices.URL_PREFIX + WebServices.ENDPOINT_GET_PICTURE_FROM_MATCH_USING_IDS + "/" + imageIds.get(0))
	)
	.asBitmap()
	.diskCacheStrategy(DiskCacheStrategy.NONE)
	.into(targetOne)
;
```
I have come across a bunch of exceptions while downloading. I logged them and I want to eliminate occurrences of these as much as possible.

```
Exception : Problem decoding into existing bitmap

Exception : java.net.SocketTimeoutException: Read timed out

Exception : javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5742c778: Failure in SSL library, usually a protocol error
```

I think the read timeout can probably be fixed by increasing the timeout by configuring Okhttp. I do not know how to set this up with Glide though.

My question is how to I get rid of these image load errors as far as possible?

**Comment by TWiStErRob** [comment]
You should always eliminate multiple errors starting with the first root cause, the rest can be just a consequence.

Here's timeout for example: discussion #432 code https://github.com/bumptech/glide/issues/513#issuecomment-118187506
Most likely that's the culprit here, I can imagine a timeout caused both the SSL handshake to fail and the BitmapFactory couldn't read a single byte and failed.

**Comment by rohanmahale** [comment]
Thanks for the response @TWiStErRob . I am using Glide as a Gradle dependency.

    compile 'com.github.bumptech.glide:glide:3.6.1'

I followed the steps mentioned in this thread.
https://github.com/bumptech/glide/issues/513#issuecomment-118187506. 

I commented out my old dependency and I added 
compile 'com.github.bumptech.glide:okhttp-integration:1.3.0'
    compile 'com.squareup.okhttp:okhttp:2.4.0'

I am also using retrofit for networking(for which i had configured okhttp separately)
Do I need to make any more changes to proguard or anywhere/anything else? I set the read timeout to 
60 seconds, is this fine?

Thanks again!

**Comment by TWiStErRob** [comment]
Keep the Glide Gradle dep, integration lib is an extra dep.
You should be able to use the same OkHttpClient for both.
1 minute depends on your use case, the question is if you're happy with it. Just imagine that on some horrible 3g network your user will have to wait 1 min per image to get an error drawable. After 10 secs I usually think, oh this app has no error handling.
Just make sure your GlideModule is visible and proguarded as mentioned in the configuration wiki.
There's an open task for this for 4.0 yes. The new option system makes it easier to pass some extra arguments to any layer.

**Comment by rohanmahale** [comment]
Thanks again @TWiStErRob . You're right about the how the wait could get annoying. It also seems like you were right about the other issues being a consequence of one. 

Another question - Is it possible to cancel a request currently on? I know clear Glide.clear(target) will cancel pending loads.

**Comment by TWiStErRob** [comment]
Clear should call cancel on the networking layer.

See https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java#L128
And https://github.com/bumptech/glide/blob/3.0/integration/okhttp/src/main/java/com/bumptech/glide/integration/okhttp/OkHttpStreamFetcher.java#L78

From those comments you can see that we have a known problem here. You can implement it however you like though, just extend the class and override that method.

**Comment by TWiStErRob** [comment]
> I will keep testing and close this ASAP.

any news?

**Comment by rohanmahale** [comment]
Yup. I no longer encounter the errors. Thanks again @TWiStErRob .
