### ISSUE TITLE
I cannot manage to load an image from the SDcard

### ISSUE THREAD

**Issue by gushoubang** [bumptech/glide#760]
Like this, but it can't show the image:
```java
String b = Environment.getExternalStorageDirectory() + "/DCIM/Camera/IMG_20150828_174009.jpg";
Glide.with(MainActivity.this).load(new File(b)).into(image2);
```

and like this, it can't show:
```java
String b = Environment.getExternalStorageDirectory() + "/DCIM/Camera/IMG_20150828_174009.jpg";
Uri uri = Uri.parse(b);
Glide.with(MainActivity.this).load(uri).into(image2);
```

The permission like this:
```xml
<!-- 在SDCard中创建与删除文件权限 -->
<uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
<!-- 往SDCard写入数据权限 -->
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<!-- 从SDCard读取数据权限 -->
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

**Comment by TWiStErRob** [comment]
1. You shouldn't build paths with String concatenation, consider always using something like:

    ```java
    File b = new File(Environment.getExternalStorageDirectory(), "DCIM/Camera/IMG_20150828_174009.jpg");
    ```
    at worst, use `File.separator`.
2. `Uri.parse` can't parse this, it's not an Uri, an absolute path doesn't start with a protocol (`file://`).  
If you want to convert an absolute path (you alread have a `File` object), use `Uri.fromFile`.
3. Please try debugging your app, a [`RequestListener`](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) whould tell you what's wrong.

(+1. you should wrap your code blocks in ``` in GitHub issues/comments, otherwise they may get lost in HTML parsing or just look plain unreadable. edited it for you)

**Comment by gushoubang** [comment]
but it can't work ,the picture is not show
```
File b = new File(Environment.getExternalStorageDirectory(), "DCIM/Camera/IMG_20151028_192555.jpg");
File c = new File(Environment.getExternalStorageDirectory() + "/DCIM/Camera/IMG_20151028_192555.jpg");

boolean aaaa = b.exists();
boolean bbbb = c.exists();

        Glide.with(MainActivity.this).load(c).error(R.drawable.empty_pic).placeholder(R.drawable.empty_pic).into(image2);
```

the file is exist and aaaa is true ,bbbb is true

**Comment by TWiStErRob** [comment]
That's good, now you just need to do step 3, click the link.

**Comment by gushoubang** [comment]
OK，I find the reason is that the permission in Android6.0. Thank you!

**Comment by TWiStErRob** [comment]
Ah, so you had the permission declared, targeted M, but didn't request it before use? Or was it disabled after install?
