### ISSUE TITLE
get() method isn't returning

### ISSUE THREAD

**Issue by bnurilov** [bumptech/glide#766]
I'm trying to load an image from the web as a Bitmap in a synchronous way but the call to Glide....get() never returns (with neither a result nor an exception. just stuck) . Here is my code:

```java
public Bitmap loadBitmapSync(final Context context, final String url) throws Throwable {
		ExecutorService executorService = Executors.newSingleThreadExecutor();
		Callable<Bitmap> callable = (new Callable<Bitmap>() {
			@Override
			public Bitmap call() throws Exception {
				return Glide.with(context.getApplicationContext()).load(url).asBitmap().into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).get();
			}
		});
		Future<Bitmap> future = executorService.submit(callable);
		return future.get();
	}
```
 Can someone please explain the error to me and suggest an alternative method?

**Comment by TWiStErRob** [comment]
Are you by any chance calling `loadBitmapSync` from the main thread? If so, [shame on you!](http://developer.android.com/guide/components/processes-and-threads.html#Threads) ...
Glide requires the UI thread to be responsive (as does Android itself), Glide does its own scheduling and delivering there (see `GenericRequestBuilder.into(int,int)` for example). What you're doing is equivalent to:
```java
public Bitmap loadBitmapSync(Context context, final String url) throws Throwable {
    return Glide.with(context.getApplicationContext()).load(url).asBitmap().into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).get();
}
```
the difference is that yours is much more red tape (new service, thread, queue, ...).

Tip: Assuming `context` is an `Activity`, using application context is good faith, but a `final` "closure" variable is still leaking if the `Callable` survives the activity's destroy.

**Comment by TWiStErRob** [comment]
Closing this as get needs to be called in the background.
Feel free to reopen if you have more questions.
