### ISSUE TITLE
into SimpleTarget

### ISSUE THREAD

**Issue by jzeferino** [bumptech/glide#767]
Im trying to use SimpleTarget to to handle the resourceReady and when the resource is ready im trying to use the animation to animate the Imageview transition.

heres what im doing:

SimpleTarget
```java
Glide.with(getActivity())
                .load(user.getProfile_photo())
                .bitmapTransform(new ColorFilterTransformation(getActivity(), Color.parseColor("#33FFFFFF")))
                .placeholder(R.drawable.ic_placeholder_profile)
                .into(new SimpleTarget<GlideDrawable>) {
                    @Override
                    public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> animation) {
                        if (animation == null || !animation.animate(resource, new BitmapImageViewTarget(mImgUser))) {
                        }
                    }
                });
```
 
the problem is that when the transition occur the final image get deformed ( strech ).
Any ideias?

**Comment by TWiStErRob** [comment]
You're most likely experiencing #363.

What are you trying to achieve? If your target is an ImageView you should be using `.into(mImgUser)`, animation is automatic and the default is an implicit `.crossFade()`. If you want to customize you could use a `.listener()` or extend like this:
```java
.into(new BitmapImageViewTarget(mImgUser) {
    // override whatever lifecycle you're looking for,
    // but double-check first if listener would be sufficient
});
```

**Comment by jzeferino** [comment]
my imageview is a https://github.com/lopspower/CircularImageView 
the problem is that, when use the into method, the CircularImageView never changes from placeholder to the final image.
i tried to use the simpleTarget to get some kind of delay, and hoped the way that the iamges was setted would work. it works but the images is scaled has i told before. do you thinks is better ti use the .into(new BitmapImageViewTarget(mImgUser) or the way im using?

**Comment by TWiStErRob** [comment]
You can work around the placeholder issue with `asBitmap` or `dontAnimate`, but in both cases you lose the cross-fade animation. `ViewTarget` and `ImageViewTarget` (which you're skipping if you're using `SimpleTarget`) does a lot of extra work that's worth doing, check the sources. If all your problems come from `CircularImageView`, which we know is [not really compatible with Glide's crossFade](https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=is%3Aissue+CircleImageView+OR+CircularImageView), consider not using it... use [CircleTransform](http://stackoverflow.com/a/25806229/253468) instead:
```java
.bitmapTransform(new CenterCrop(...), new ColorFilterTransformation(...), new CircleTransform(...))
```
It has the advantage of the result being cached, so it's really good for lists or frequently displayed stuff.
*(Make sure you include the color of `ColorFilterTransformation` in its `getId`)*

Using `CircularImageView` will help to solve the [`crossFade` issue](https://github.com/bumptech/glide/issues/482#issuecomment-107977982), but sadly it won't help with the placeholder aspect ratio. Try using a 9-patch as placeholder, maybe then it won't happen.

**Comment by jzeferino** [comment]
In this particular case, i need the animation and i need to use ciruclarimageViewLibrary because it has a border (that i need to). I will try to watch the ImageViewTarget and ViewTarget.
Thanks for the support.

**Comment by TWiStErRob** [comment]
In that case you could also modify the transformation to draw a border (you have unlimited access to a Canvas inside the transformation). Also consider the [other answer on SO](http://stackoverflow.com/a/32390715/253468).

**Comment by jzeferino** [comment]
good job and thanks! i will try to draw the the border extending the circle transformation.
