### ISSUE TITLE
Image with Zoom

### ISSUE THREAD

**Issue by mdtuyen** [bumptech/glide#768]
I use Glide to load a image from local to imageview ( this imageview have been implement to support zoom)

Because the original very big, I think glide will resize it to prevent outofmemory, However if I zoom in, the image will be break out. How is solution for this case ?

**Comment by TWiStErRob** [comment]
Glide will try to load a Bitmap with a size closely matching the view size (pixel perfect) as no more pixels are necessary for the user to enjoy the loaded image. When you zoom in, you're probably zooming in on a low quality image and magnifying/pixelating the result (is the the "break out" you mean?). You can use `.override()` to load a bigger image (use `Target.SIZE_ORIGINAL`, if you want that big). If you want to zoom and move around a huge image consider finding a library designed for that. Glide is meant for performance and resource saving.

**Comment by mdtuyen** [comment]
Sorry, break-off, because my image too big ( 40MB) it will outoffmemory when load ORIGINAL SIZE the first time.

**Comment by TWiStErRob** [comment]
How can we help with that? If you use `.override()` you can constrain the size of the loaded bitmap, by default it should use the ImageView's measured or layout-specified size.

Please add more information on what you need, see [issue template for example](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md).
