### ISSUE TITLE
Gif - Memory problem when pausing activity

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#769]
I'm using version 3.6.1 from mavenCentral and see following:

Displaying a few gifs directly in image views does NOT free up memory when pausing/resuming the activity or even when sending it to the background.

Can I somehow manually solve that? Can I stop all gifs in `onPause` and resume them in `onResume` manually?

**Comment by TWiStErRob** [comment]
How about #690, does it sound like what you're experiencing?

**Comment by MFlisar** [comment]
Yes it does seem to be the same problem. I even saw that before posting anyways, but I'm curious if there is a manual solution for that - is there anyway to force stop/start playing a gif animation manually?

**Comment by TWiStErRob** [comment]
From my [first comment](https://github.com/bumptech/glide/issues/690#issuecomment-148919053) there:

> You can force Glide to clear the target via:
> ```java
Glide.clear(imageView);
```

I think GIF stops playing automatically if you used the right context, but this memory usage is unrelated to playing: a partially decoded GIF needs to be in memory to be able to decode frames.

**Comment by MFlisar** [comment]
I made sure I use the correct context and this seems to improve the problem. I was always calling `Glide.clear(...)` anyway...
