### ISSUE TITLE
How to use the glide to load the image resource in the assets by uri

### ISSUE THREAD

**Issue by caixuejian** [bumptech/glide#770]

**Comment by TWiStErRob** [comment]
First Google result searching for this issue's title:
http://stackoverflow.com/q/29982341/253468

> For resource ids, you can use:
>
> ```java
Glide.with(fragment)
        .load(R.id.resource_id)
        .into(imageView);
```
> For assets, you can construct an asset uri:
>
> ```java
Glide.with(fragment)
        .load(Uri.parse("file:///android_asset/assetName"))
        .into(imageView);
```
> --- answered by @sjudd

**Comment by zhizhangchen** [comment]
This doesn't work

**Comment by MihaelIsaev** [comment]
+1 This doesn't work

**Comment by sjudd** [comment]
Commenting on a year+ old issue is not likely to get you a useful answer. If something isn't working for you, please file a new issue and fill out the issue template.

**Comment by i-me-mine** [comment]
it may not get a useful answer, but it tells other people this is not working code.
