### ISSUE TITLE
Question: Preloading

### ISSUE THREAD

**Issue by twinone** [bumptech/glide#775]
When I use .downloadOnly() to preload an image into disk cache, and while it's still downloading it, If I try to load it into an ImageView normally, will Glide detect that it was already preloading it, and continue to do so, or will it start a new download for the same url?

I was searching in the wiki but I couldn't find it.

**Comment by TWiStErRob** [comment]
There's an internal mechanism to attach requests to existing ones. Download-only requests are normal requests. I think you'll need to specify `.diskCacheStrategy(SOURCE)` (if not automatic, I can't remember) on the preload and `ALL` on the normal load to pick up the "preloaded" image.

Best is to try anyway to make sure all is well. You can enable logging (see debug wiki) to see what's going on under the hood, or replace the default DataFetcher with your own which logs each HTTP request.

**Comment by twinone** [comment]
Didn't need `.diskCacheStrategy()` on the `.downloadOnly()`, used `DiskCacheStrategy.SOURCE` on the loading part and it worked perfectly. Thanks!

**Comment by TWiStErRob** [comment]
Yep, `GenericTranscodeRequest.getDownloadOnlyRequest` does `SOURCE` for you. So you just needed to tell Glide to use what was downloaded before. `diskCacheStrategy` controls both reads and writes to those two caches.
