### ISSUE TITLE
Sometimes Glide v.4 stapshot doesn't load image from internal storage 

### ISSUE THREAD

**Issue by zetbrush** [bumptech/glide#776]
``` ruby
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
11-27 19:24:00.443 5411-5411/com.pic*****:******* E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
11-27 19:24:00.443 5411-21483/com.pic*****:******* E/GlideExecutor: Request threw uncaught throwable
  java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
      at java.util.ArrayList.get(ArrayList.java:308)
      at java.util.Collections$UnmodifiableList.get(Collections.java:1050)
      at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:58)
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:273)
      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:240)
      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:218)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:841)
      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:200)
```

**Comment by TWiStErRob** [comment]
Can you provide a little more info on how you're using Glide?
When does this happen?

**Comment by zetbrush** [comment]
so the RequestManeger is configures as follows.
fullRequest.asDrawable().load(url)
				.apply(RequestOptions.noTransform().diskCacheStrategy(DiskCacheStrategy.RESOURCE).dontAnimate().signature(signature).encodeFormat(Bitmap.CompressFormat.JPEG).format(DecodeFormat.PREFER_RGB_565))
				.listener(listener)
				.into(new SimpleTarget<Drawable>() {
					@Override
					public void onResourceReady(Drawable drawable, Transition<? super Drawable> transition) {
						view.setImageDrawable(drawable);
					}
				});

-----------------
And, also another request is loading same images on another view which doesn't fail.

**Comment by TWiStErRob** [comment]
Hmm, if anything it may be that the SimpleTarget doesn't manage requests properly if `view` ever points to the same View again. Is there a good reason not to use `.into(view)`?

@sjudd what do you see?

**Comment by zetbrush** [comment]
yes, as using .into(view) updates some sort of fading and not immediately, although  .noTransform() and .dontAnimate() are used.

**Comment by TWiStErRob** [comment]
Huh, for `dontAnimate` that's not right by itself, you might want to report that separately if you can reproduce. (`noTransform` is for resizing-cropping-resampling, not animation).
Anyway, does `.into(view)` fix the crash, or you can't reproduce it consistently enough to verify?

**Comment by zetbrush** [comment]
yeah can't reproduce it consistently. also something is wrong with Transform I think, as when noTransform() isn't set, images reloaded from cache contain artifacts

**Comment by TWiStErRob** [comment]
Let's see what @sjudd has to say about this exception.

Please open separate issues if you think something isn't working: see ["*We'd rather close a few duplicate issues than let a problem go unnoticed*"](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues).

**Comment by zetbrush** [comment]
ok, thanks for support.

**Comment by sjudd** [comment]
Can you provide an example of 'url' you're using to load the images? Is it a particular url? Or random?

**Comment by zetbrush** [comment]
It's just an absolute path of image file

**Comment by TWiStErRob** [comment]
`/sdcard/` or `file://`; `String` or `Uri` or `Url`?

Does it happen with different ones or always with the same file?

**Comment by zetbrush** [comment]
/sdcard  and String. it happens with different files as well

**Comment by sjudd** [comment]
Can you provide a couple of examples?

**Comment by zetbrush** [comment]
Sorry for late response. for example String  "/storage/emulated/0/PicsArt/.preview/2.jpg"

**Comment by zetbrush** [comment]
@sjudd, @TWiStErRob  I noticed that this exception is happening mainly after downloading with snippet as bellows 

``` Glide.with(context).asFile().load(maskDownloadUrl).into(new SimpleTarget<File>() {
							@Override
							public void onResourceReady(File file, Transition<? super File> transition) {
// some operation with file
}

@Override
							public void onLoadFailed(Drawable errorDrawable) {
								super.onLoadFailed(errorDrawable);
//callback.onFail(errorDrawable)
}
```

**Comment by sjudd** [comment]
I tried a few variations of local paths and don't seem to be able to reproduce this. If anyone has a sample app where this occurs, please let me know.

**Comment by wuziHM** [comment]
the log is 
`Load failed for http://i2.meizitu.net/2018/07/06a04.jpg with size [984x1381]
                                                  class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                    Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Bitmap->Bitmap}, DATA_DISK_CACHE, http://i2.meizitu.net/2018/07/06a04.jpg
                                                      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Bitmap}
                                                    Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Bitmap->Bitmap}, DATA_DISK_CACHE, http://i2.meizitu.net/2018/07/06a04.jpg
                                                      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Bitmap}
                                                    Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Bitmap->Bitmap}, DATA_DISK_CACHE, http://i2.meizitu.net/2018/07/06a04.jpg
                                                      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Bitmap}
                                                    Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Bitmap->Bitmap}, REMOTE, http://i2.meizitu.net/2018/07/06a04.jpg
                                                      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Bitmap}
                                                    Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Bitmap->Bitmap}, REMOTE, http://i2.meizitu.net/2018/07/06a04.jpg
                                                      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Bitmap}
                                                    Cause (6 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Bitmap->Bitmap}, REMOTE, http://i2.meizitu.net/2018/07/06a04.jpg
                                                      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Bitmap}
07-12 10:23:05.136 2578-2578/allenhu.app E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource`


my code is 
 options = new RequestOptions();
        options.fitCenter();
        options.error(R.drawable.ic_error);
        options.placeholder(R.drawable.ic_default_image);
        options.diskCacheStrategy(DiskCacheStrategy.ALL);

            Glide.with(context)
                    .asBitmap()
                    .load(url)
                    .thumbnail(0.2f)
                    .apply(options)//
                    .into(imageView);
