### ISSUE TITLE
How to use Glide load the original image?

### ISSUE THREAD

**Issue by xufeifandj** [bumptech/glide#779]
Please help me  how to use glide  load the original.

**Comment by TWiStErRob** [comment]
I strongly suggest you don't do that, because it may not fit in memory and wasteful in general (especially if you just need it to resize/cut parts of it). Anyway this should do it:
```java
Glide
    .with(...)
    .load(...)
    .diskCacheStrategy(SOURCE) // NONE if you load from sdcard
    .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
    .into(...)
```

**Comment by xufeifandj** [comment]
thank u . i find it .

**Comment by stefanhaustein** [comment]
```override()``` did not work for me (method not found), but ```.apply(RequestOptions.overrideOf(Target.SIZE_ORIGINAL))``` seems to work?

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/migrating.html
