### ISSUE TITLE
Will Glide automatically clean up the disk cache when disk full?

### ISSUE THREAD

**Issue by xufeifandj** [bumptech/glide#780]
I would like to know that I set up the disk cache。

If the disk is full。Will automatically clear the disk, or need to manually

```java
public static final int yourSizeInBytes_disk=1024*1024*50;//默认50M本地缓存
public static final int yourSizeInBytes_memory=1024*1024*15;//默认15M内存
@Override
public void applyOptions(Context context, GlideBuilder builder) {
    builder.setDiskCache(new DiskCache.Factory() {
        @Override public DiskCache build() {
            File cacheLocation = getMyCacheLocationBlockingIO();
            cacheLocation.mkdirs();
            return DiskLruCacheWrapper.get(cacheLocation, yourSizeInBytes_disk);
        }
    });
    builder.setMemoryCache(new LruResourceCache(yourSizeInBytes_memory));
```

**Comment by TWiStErRob** [comment]
When the disk is full Glide will just fail to write to the disk cache. However when the cache is full (that is sum of image sizes > 50M in your case) it will start evicting (deleting) images that were used furthest in the past.

I suggest that you use this snippet to create a cache at a custom location:
```java
builder.setDiskCache(new DiskLruCacheFactory(new CacheDirectoryGetter() {
	@Override public File getCacheDirectory() {
		return getMyCacheLocationBlockingIO();
	}
}, yourSizeInBytes_disk));
```

**Comment by xufeifandj** [comment]
thank u.  i use the GlideModule.
like this:

public class FlyGlideModule implements GlideModule {
    public static final int yourSizeInBytes_disk=1024*1024*50;//默认50M本地缓存
    public static final int yourSizeInBytes_memory=1024*1024*15;//默认15M内存


    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        builder.setDiskCache(new DiskCache.Factory() {
            @Override public DiskCache build() {
                File cacheLocation = getMyCacheLocationBlockingIO();
                cacheLocation.mkdirs();
                return DiskLruCacheWrapper.get(cacheLocation, yourSizeInBytes_disk);
            }
        });

        builder.setMemoryCache(new LruResourceCache(yourSizeInBytes_memory));
    }

    private File getMyCacheLocationBlockingIO() {
        return new File(FlyEnvironment.IMAGE_CACHE);
    }

    @Override
    public void registerComponents(Context context, Glide glide) {

    }
}

**Comment by xufeifandj** [comment]
thank u

**Comment by TWiStErRob** [comment]
I was suggesting to change your `setDiskCache` to

```java
builder.setDiskCache(new DiskLruCacheFactory(new CacheDirectoryGetter() {
    @Override public File getCacheDirectory() {
        return new File(FlyEnvironment.IMAGE_CACHE);
    }
}, yourSizeInBytes_disk));
```
because it makes more checks when starting up to make sure the cache is all right and ready to use.

Also note that `new File()` is not a blocking I/O operation, so you can just use the [simplest form]([wiki](https://github.com/bumptech/glide/wiki/Configuration#location)):
```java
builder.setDiskCache(new DiskLruCacheFactory(FlyEnvironment.IMAGE_CACHE, yourSizeInBytes_disk));
```

**Comment by xufeifandj** [comment]
ok  thank u very much..
