### ISSUE TITLE
I just wanted to get Bitmap, and ask for help from the file.

### ISSUE THREAD

**Issue by xufeifandj** [bumptech/glide#782]
But this method is invalid.
```java
Glide.with(iv_wallpaper.getContext())
    .load(new File(xxxx))
    .into(new SimpleTarget() {
        @Override
        public void onResourceReady(Bitmap bitmap, GlideAnimation animation) {
        }
    });
```

**Comment by xufeifandj** [comment]
Glide.with(iv_wallpaper.getContext())
                        .load(new File(xxxx))
                        .into(new SimpleTarget() {
                            @Override
                            public void onResourceReady(Bitmap bitmap, GlideAnimation animation) {
                            }
                        });

**Comment by TWiStErRob** [comment]
Use `.asBitmap()`.

**Comment by xufeifandj** [comment]
Glide.with(iv_wallpaper.getContext()).load(little_original)
                        .asBitmap()
                        .into(new SimpleTarget() {
                            @Override
                            public void onResourceReady(Bitmap bitmap, GlideAnimation animation) {
                            }
                        });

**Comment by xufeifandj** [comment]
code error

**Comment by TWiStErRob** [comment]
You must provide generic arguments to `SimpleTarget<Bitmap>`. Where did you get that code from without the `<>`? My IDE generates the generics automatically on code completion.

**Comment by xufeifandj** [comment]
Glide.with(iv_wallpaper.getContext()).load(little_original)
                        .asBitmap()
                        .into(new SimpleTarget<Bitmap>() {
                            @Override
                            public void onResourceReady(Bitmap bitmap, GlideAnimation animation) {
    
                            }
                        });

**Comment by xufeifandj** [comment]
ok  thank u  very much

**Comment by TWiStErRob** [comment]
Yep, exactly.

*Please read [this help page](https://guides.github.com/features/mastering-markdown/) on how to format comments, at least surround your code blocks with ``` in the future (see edits I made to your comments with the pencil in the upper right corner) and preview comments before posting.*
