### ISSUE TITLE
Using Glide with a Widget

### ISSUE THREAD

**Issue by Orbyt** [bumptech/glide#783]
Can Glide be used in a Widget? In a Widget, views are accessed through `RemoteViews`, and the `ImageViews` src can be set through methods on that `RemoteView` like so:

```java
RemoteViews views = new RemoteViews(context, R.id.widget_layout);
views.setImageViewUri();
views.setImageViewBitmap();
views.setImageViewResource();
```

So can Glide be used at all to set the image source for an ImageView in a Widget?

**Comment by TWiStErRob** [comment]
```java
.asBitmap()
.into(new AppWidgetTarget(...))
```
See [sources](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/request/target/AppWidgetTarget.java) which were added in #248 requested by  #242.

You can find a real life example by @TomasValenta in [his app](https://github.com/TomasValenta/WebCams/blob/master/app/src/main/java/cz/yetanotherview/webcamviewer/app/widget/WvWidgetProvider.java#L178) and some caveats we discussed in #396. I strongly recommend reading through and probably even checking the commit history of the linked file, widgets are not trivial :(
