### ISSUE TITLE
How to pause glide image loading,

### ISSUE THREAD

**Issue by xufeifandj** [bumptech/glide#784]
i have FramentActivity.   It contains two Fragment.     FragmentA,FragmentB
When I am hide FragmentA and  show the FragmentB. 
i want to pause FragmentA Image loading

**Comment by TWiStErRob** [comment]
See `RequestManagerFragment.onStart/onStop` which calls `ActivityFragmentLifecycle` which propagates to `RequestManager.onStart/onStop`.

Combining above with:
> Similar to activity lifecycle, Android calls onStart() when fragment becomes visible. onStop() is normally called when fragment becomes invisible, but it can also be called later in time. - [SO](http://stackoverflow.com/a/18375614/253468)

should yield requests are automatically paused in `onStop` and resumed in `onStart`.
Which should be the same as manually calling:
```java
Glide.with((Fragment)this).pauseRequests();
```
