### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Activity has been destroyed

### ISSUE THREAD

**Issue by jt-gilkeson** [bumptech/glide#795]
Seeing the following crash sporadically in a RecyclerView.Adapter that has: 

```
@Override
public void onBindViewHolder(ViewHolder holder, int position)
{
    ...
    Glide.with(mFragment).load(item.pictureLarge).crossFade().into(vh.userPhoto);
    ...
}
```

The adapter gets created in the fragment's onCreate()

Crash:

```
Fatal Exception: java.lang.IllegalStateException: Activity has been destroyed
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1399)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
       at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:620)
       at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:907)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6837)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

Anything obvious stand out?

**Comment by TWiStErRob** [comment]
See #497, it should be fixed in 4.0.
For 3.x you need to figure out why? I guess your data is being bound late, after the activity is destroyed.

What do you do as user when this happens and what does your code do responding to those user actions when this happens?

**Comment by jt-gilkeson** [comment]
Was able to reproduce.  Seems to happen if I rotate during the initial load of data.

**Comment by TWiStErRob** [comment]
> I'm protecting the adapter update with isAdded()

Does this mean you'll be protecting to fix this; or you're already doing that and the exception still comes?

**Comment by jt-gilkeson** [comment]
Sorry had a connection issue when editing.  The crash happens despite the isAdded protection.  So it looks like maybe the glide callback is happening during the rotation?

**Comment by jt-gilkeson** [comment]
Ahh it looks like using the applicationContext "fixes" this issue (no longer get the crash on rotation).

**Comment by TWiStErRob** [comment]
Yeah, "fixes"... read this: http://stackoverflow.com/q/31964737/253468

Can you please add logs to life cycle events in activity and fragment and [enable logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#more-logging) so we have a proper timeline?

**Comment by jt-gilkeson** [comment]
I think I figured out what's going on.  We have an Activity, that has a Fragment with a Tabbed view and ViewPager in it and 3 child fragments.  The adapter is in the child fragments.  If I use the parentFragment for glide (instead of the child fragment) it seems to fix this.  Make sense?

**Comment by TWiStErRob** [comment]
Thanks for the effort, man!

**Comment by jt-gilkeson** [comment]
With adb shell setprop log.tag.GenericRequest DEBUG

I don't seem to get any Glide logs for this  activity launch and rotation (I do see them beforehand in main activity - so I know it is working)

Here's a log of what's happening:
```
12-07 14:34:34.712 25362-25362/com.ourapp D/SimpleFragmentActivity: onCreate
12-07 14:34:34.732 25362-25362/com.ourapp D/TABBED_LEADERBOARD: onAttach
12-07 14:34:34.733 25362-25362/com.ourapp D/TABBED_LEADERBOARD: onCreate
12-07 14:34:34.735 25362-25420/com.ourapp W/AQuery: get:https://1...
12-07 14:34:34.750 25362-25362/com.ourapp D/SimpleFragmentActivity: onResume
12-07 14:34:34.753 25362-25362/com.ourapp D/TABBED_LEADERBOARD: onResume
12-07 14:34:34.760 25362-25362/com.ourapp D/LeaderboardFragment: onAttach: 0
12-07 14:34:34.762 25362-25438/com.ourapp W/AQuery: get:https://1...
12-07 14:34:34.764 25362-25362/com.ourapp D/LeaderboardFragment: onCreateView: 1
12-07 14:34:34.772 25362-25362/com.ourapp D/LeaderboardFragment: onResume: 1
12-07 14:34:34.772 25362-25362/com.ourapp D/LeaderboardFragment: onAttach: 0
12-07 14:34:34.775 25362-25362/com.ourapp D/LeaderboardFragment: onCreateView: 0
12-07 14:34:34.775 25362-25437/com.ourapp W/AQuery: get:https://0...
12-07 14:34:34.782 25362-25362/com.ourapp D/LeaderboardFragment: onAttach: 0
12-07 14:34:34.783 25362-25362/com.ourapp D/LeaderboardFragment: onCreateView: 2
12-07 14:34:34.783 25362-25419/com.ourapp W/AQuery: get:https://2...
12-07 14:34:34.789 25362-25362/com.ourapp D/LeaderboardFragment: onResume: 0
12-07 14:34:34.790 25362-25362/com.ourapp D/LeaderboardFragment: onResume: 2
12-07 14:34:34.844 25362-25420/com.ourapp W/AQuery: response:200
12-07 14:34:34.873 25362-25417/com.ourapp D/OpenGLRenderer: endAllStagingAnimators on 0x9b605800 (RippleDrawable) with handle 0xb400eb90
12-07 14:34:35.533 25362-25362/com.ourapp D/LeaderboardFragment: onPause: 1
12-07 14:34:35.534 25362-25362/com.ourapp D/LeaderboardFragment: onPause: 0
12-07 14:34:35.534 25362-25362/com.ourapp D/LeaderboardFragment: onPause: 2
12-07 14:34:35.534 25362-25362/com.ourapp D/TABBED_LEADERBOARD: onPause
12-07 14:34:35.534 25362-25362/com.ourapp D/SimpleFragmentActivity: onPause
12-07 14:34:35.542 25362-25362/com.ourapp D/TABBED_LEADERBOARD: onDetach
12-07 14:34:35.570 25362-25362/com.ourapp D/SimpleFragmentActivity: onCreate
12-07 14:34:35.571 25362-25362/com.ourapp D/TABBED_LEADERBOARD: onAttach
12-07 14:34:35.574 25362-25438/com.ourapp W/AQuery: response:200
12-07 14:34:35.574 25362-25438/com.ourapp W/AQuery: 22889:https://1...
12-07 14:34:35.575 25362-25419/com.ourapp W/AQuery: response:200
12-07 14:34:35.575 25362-25419/com.ourapp W/AQuery: 4677:https://2...
12-07 14:34:35.595 25362-25437/com.ourapp W/AQuery: response:200
12-07 14:34:35.595 25362-25437/com.ourapp W/AQuery: 46458:https://0...
12-07 14:34:36.129 25362-25362/com.ourapp D/LeaderboardFragment: onCreateView: 1
12-07 14:34:36.153 25362-25362/com.ourapp D/LeaderboardFragment: onCreateView: 0
12-07 14:34:36.159 25362-25362/com.ourapp D/LeaderboardFragment: onCreateView: 2
12-07 14:34:36.171 25362-25362/com.ourapp D/SimpleFragmentActivity: onResume
12-07 14:34:36.174 25362-25362/com.ourapp D/TABBED_LEADERBOARD: onResume
12-07 14:34:36.175 25362-25362/com.ourapp D/LeaderboardFragment: onResume: 1
12-07 14:34:36.175 25362-25362/com.ourapp D/LeaderboardFragment: onResume: 0
12-07 14:34:36.175 25362-25362/com.ourapp D/LeaderboardFragment: onResume: 2
12-07 14:34:36.179 25362-25362/com.ourapp I/Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
12-07 14:34:36.420 25362-25362/com.ourapp D/AndroidRuntime: Shutting down VM
12-07 14:34:36.421 25362-25362/com.ourapp D/HockeyApp: Writing unhandled exception to: /data/user/0/com.ourapp/files/5d914a03-c310-4935-b63d-5afc2df3195b.stacktrace
12-07 14:34:36.423 25362-25362/com.ourapp W/System.err: java.lang.IllegalStateException: Activity has been destroyed
12-07 14:34:36.423 25362-25362/com.ourapp W/System.err:     at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1399)
12-07 14:34:36.423 25362-25362/com.ourapp W/System.err:     at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
12-07 14:34:36.424 25362-25362/com.ourapp W/System.err:     at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:620)
12-07 14:34:36.424 25362-25362/com.ourapp W/System.err:     at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
12-07 14:34:36.424 25362-25362/com.ourapp W/System.err:     at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
12-07 14:34:36.424 25362-25362/com.ourapp W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:907)
12-07 14:34:36.424 25362-25362/com.ourapp W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
12-07 14:34:36.424 25362-25362/com.ourapp W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
12-07 14:34:36.424 25362-25362/com.ourapp W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
12-07 14:34:36.424 25362-25362/com.ourapp W/System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
12-07 14:34:36.424 25362-25362/com.ourapp W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
12-07 14:34:36.425 25362-25362/com.ourapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-07 14:34:36.425 25362-25362/com.ourapp W/System.err:     at android.os.Looper.loop(Looper.java:148)
12-07 14:34:36.425 25362-25362/com.ourapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
12-07 14:34:36.425 25362-25362/com.ourapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-07 14:34:36.425 25362-25362/com.ourapp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-07 14:34:36.425 25362-25362/com.ourapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by TWiStErRob** [comment]
GenericRequest DEBUG doesn't do much, enable all we got, it can't hurt. (see bottom of page for tons of `adb shell setprop`).

**Comment by jt-gilkeson** [comment]
Sorry had VERBOSE on.  But even after turning on everything (at the bottom of the page) there are still no additional glide traces for this sequence (Launch activity, immediately rotate, crash)

I added a trace for when we call Glide.load()
Note: tab 1 is being displayed, tab 2 and tab 0 are offscreen.

```
12-07 15:02:04.330 11465-11465/com.ourapp D/LeaderboardFragment: onResume: 1
12-07 15:02:04.330 11465-11465/com.ourapp D/LeaderboardFragment: onResume: 0
12-07 15:02:04.330 11465-11465/com.ourapp D/LeaderboardFragment: onResume: 2
12-07 15:02:04.334 11465-11465/com.ourapp I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
12-07 15:02:04.405 11465-11465/com.ourapp D/Adapter: Glide Call2
12-07 15:02:04.416 11465-11465/com.ourapp D/Adapter: Glide Call2
12-07 15:02:04.426 11465-11465/com.ourapp D/Adapter: Glide Call2
12-07 15:02:04.439 11465-11465/com.ourapp D/Adapter: Glide Call1
12-07 15:02:04.450 11465-11465/com.ourapp D/Adapter: Glide Call1
12-07 15:02:04.461 11465-11465/com.ourapp D/Adapter: Glide Call1
12-07 15:02:04.527 11465-11465/com.ourapp D/AndroidRuntime: Shutting down VM
12-07 15:02:04.528 11465-11465/com.ourapp W/System.err: java.lang.IllegalStateException: Activity has been destroyed
12-07 15:02:04.528 11465-11465/com.ourapp W/System.err:     at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1399)
12-07 15:02:04.528 11465-11465/com.ourapp W/System.err:     at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
12-07 15:02:04.528 11465-11465/com.ourapp W/System.err:     at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:620)
12-07 15:02:04.528 11465-11465/com.ourapp W/System.err:     at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
12-07 15:02:04.528 11465-11465/com.ourapp W/System.err:     at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
12-07 15:02:04.528 11465-11465/com.ourapp W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:907)
```

**Comment by TWiStErRob** [comment]
It looks like the new (rotated) activity is already resumed by the time the fragments resumed and adapter bindings happen. I think it's possible (don't know how) that the Glide fragment create for the original somehow get pushed down the queue and tries to create itself too late. @sjudd any ideas?

**Comment by TWiStErRob** [comment]
@jt-gilkeson I assume you logged: `"Glide Call" + getAdapterPosition()`, can you try adding `mFragment` too to see the hash code and also the same for all fragment/activity lifecycle logs.
What is `TABBED_LEADERBOARD`, is it a simple Fragment with ViewPager?

**Comment by sjudd** [comment]
I believe this is a support library bug. The activity is clearly not destroyed when one of it's child fragment's onAttach method is called. The message is misleading, the support library will assume the activity is destroyed both if states haven't yet been initialized and also if they were initialized and then deinitialized. 

I've experienced similar errors on a couple of occasions and there's a least one related bug open on the support library.  I've had some luck with combining multiple fragment changes into a single transaction and calling executePendingTransactions immediately after committing the transaction that adds the top level fragment (immediate child of the activity). 

For workarounds in Glide, you could try using the Activity directly, rather than the fragments? Or the application context? 

If you can reproduce this in a small sample app, I can pass it along to the appropriate team.

**Comment by TWiStErRob** [comment]
@sjudd appContext works: https://github.com/bumptech/glide/issues/795#issuecomment-162668027

**Comment by jt-gilkeson** [comment]
@TWiStErRob yes that is what I logged.  TABBED_LEADERBOARD is the fragment with the view pager (that adds the leaderboardFragments to childFragmentManager).  Note:tabbed leaderboard has setRetainInstance(ture) on it.  I'll try to add more logging and maybe put together a sample app when I get a chance, but I've got a lot on my plate right now.  Using the appContext seems to be holding up out in the wild.

**Comment by TWiStErRob** [comment]
Also try using the activity (== `with(vh.userPhoto.getContext())` if you don't have it in scope): you should get more benefits while possiblity working around the issue.

**Comment by jt-gilkeson** [comment]
I opened a simplified issue with a demo project that I think shows what I was experiencing above:
https://github.com/bumptech/glide/issues/1592

**Comment by MartinCazares** [comment]
I have found another case where this exception is thrown, and even tho it probably doesn't fix this specific case I think is worth mention, basically the problem is that if during onCreate, you try to add an image to a view in the activity before the super.onCreate method is called, Glide thinks the activity is not created yet and throws this very same error, for example:


```
@Override
protected void onCreate(Bundle savedInstanceState) {
    setContentView(R.layout.my_view);
    ImageView view = (ImageView) findViewById(R.id.some_image);
    Glide.with(this).load(url).centerCrop().error(R.drawable.error).placeholder(R.drawable.place_holder).into(view);
    super.onCreate(savedInstanceState);
}
```


This would cause the very same crash.
This probably is not a problem with the library it self but is important for people using Glide to know that they should avoid this case.

**Comment by TWiStErRob** [comment]
@MartinCazares I agree people should avoid this case, I don't think that starting a load before `onCreate` is/was ever a valid use case for Glide. One shouldn't really do anything (regardless of Glide) to the activity before `super.onCreate` (except setting window flags). Before the super call, the activity is not created indeed, if you think about it: neither `super.onCreate` nor `this.onCreate` finished running, so you can't say it's "create**d**". In general OO programming, you always initialize super first and then the child (similar to Java constructor chaining). Take a look at `AppCompatActivity.onCreate` and superclasses' `onCreate` methods to see the many things that are not ready before that call finishes (inflater, viewfactory, fragments, themes, actionbar, loaders just to name the major ones).

Nested fragments are interesting, but I think they're more safe, because you can't even try to start a load before `onCreateView` (you have no view to load into), at which point the activity is already created.

In all of these weird cases if you use app context it will work, but I highly discourage that as a workaround.

@jt-gilkeson #1592 is not forgotten, it's in my queue.

**Comment by jt-gilkeson** [comment]
@TWiStErRob Thanks - we have the application context workaround, so it's not critical for us, but the demo I made is a very simple one to show the issue.
