### ISSUE TITLE
Gif file stored locally acts as a bitmap when loaded from Glide

### ISSUE THREAD

**Issue by bikranttripathi** [bumptech/glide#797]
Hello,

I'm trying to load a gif file that is stored locally and its not a resource file. 

I tried using the following methods but the gif acted as a Bitmap

Loading using File class
```java
File file = new File(getExternalFilesDir(null), "filename.gif");
Glide.with(context).load(file).into(imageView);
```
```java
File file = new File(getExternalFilesDir(null), "filename.gif");
Glide.with(context).load(file).asGif().into(imageView);
```
 Loading using Uri class
```java
File file = new File(getExternalFilesDir(null), "filename.gif");
Uri uri = Uri.fromFile(file);
Glide.with(context).load(uri).into(imageView);
```
```java
File file = new File(getExternalFilesDir(null), "filename.gif");
Uri uri = Uri.fromFile(file);
Glide.with(context).load(uri).asGif().into(imageView);
```

Can anyone help me with this ?

**Comment by TWiStErRob** [comment]
Does it load as GIF when it's in `R.drawable`?
Is it animated (does it have multiple frames)?
Can you share the actual file with us? (Just drag&drop into a comment)

**Comment by bikranttripathi** [comment]
Hi @TWiStErRob Actually it didn't work with drawable either.

**Comment by bikranttripathi** [comment]
Hi @TWiStErRob I'm using RoundedImageView library for displaying gif which didn't work. 
But It worked after I changed it to normal ImageView.

I'm was using this Image :- http://cdn.osxdaily.com/wp-content/uploads/2013/07/dancing-banana.gif

**Is there a built in way of using glide to have gif play on a Circular edged ImageView ?**

**Comment by sjudd** [comment]
You can apply a circle crop transformation. See https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/TransformationUtils.java#L302 for an example (or just use it directly if you're using Glide 4).

RoundedImageView doesn't handle Drawables that have multiple frames, it always just displays the 0th frame.

**Comment by chongzi** [comment]
.asGif() 这个方法只是会判断你加载的image source 是不是一个Gif资源,并不是把原始image作为一个gif来显示.
如果你希望一个gif展示第一帧,你可以加入asBitmap()这个方法.
如果你想直接展示一个gif显示.你可以用下面方法:
String filePath = "/storage/emulated/0/Pictures/test.gif"; Glide .with( context ) .load( Uri.fromFile( new File( filePath ) ) ) .into( mImageView );
这个方法经过我实际测试,是完全可以打开这个gif图片的.

另外:打开本地video picture gif都是一样的.

**Comment by bikranttripathi** [comment]
Thanks @sjudd its working now using the circleCrop
