### ISSUE TITLE
What is the threading policy while loading images?

### ISSUE THREAD

**Issue by chetanurmaliya** [bumptech/glide#799]
We have different types of networks, Like 2G, 3G, 4G and WIFI. 
How many number of parallel threads will run for different networks?

**Comment by TWiStErRob** [comment]
Glide uses a static thread pool of [1-4 threads](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java#L169) (based CPU count) [created here](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L266).
You can override it by calling the appropriate method on the builder. You can also override the [connectivity monitor](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L277) (thanks to #709) and have them (pool and monitor) interact the way you want.

From [Sam](https://github.com/bumptech/glide/pull/709#issuecomment-152193719):
> If any of the changes you need for your app are generally applicable, I'd welcome a pull request to make them to the default connectivity monitor as well.

----

All of the above applies to v4 (unreleased, but snapshot available), for v3 Glide is using [1-n](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L170) threads = CPU count and you have no way of setting Connectivity Monitor unless you backport #709.

----

As you see Glide is basic in this regard, any contributions that may benefit the world are welcome!
