### ISSUE TITLE
Save image on phone

### ISSUE THREAD

**Issue by vanniktech** [bumptech/glide#80]
Is it possible to automatically save the image on the phone? I am loading an image from the internet and want to download it.

I implemented the listener, but could not find a function to get an Image object and save it manually.

**Comment by mkiisoft** [comment]
This is the only way that I've found to get bitmaps and files storage inside device! Happy coding!

```java
Glide.with(context).load("image_url").into(new SimpleTarget() {
            @Override
            public void onResourceReady(Object resource, GlideAnimation glideAnimation) {

                final Bitmap b;

                try{
                    imageView.setImageDrawable((GlideBitmapDrawable) resource);
                }catch (ClassCastException e) {
                    imageView.setImageDrawable((GifDrawable) resource);
                }

                imageView.setDrawingCacheEnabled(true);

                imageView.measure(View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED),
                        View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED));
                imageView.layout(0, 0, imageView.getMeasuredWidth(), imageView.getMeasuredHeight());

                imageView.buildDrawingCache(true);
                b = Bitmap.createBitmap(appicon.getDrawingCache());
                imageView.setDrawingCacheEnabled(false);

                new AsyncTask<Void, Void, Void>() {
                    @Override
                    protected Void doInBackground(Void... params) {

                        File dir = new File(android.os.Environment.getExternalStorageDirectory() + "/YourDir");
                        if(!dir.exists()){
                            dir.mkdirs();
                        }

                        File file = new File(android.os.Environment.getExternalStorageDirectory() + "/YourDir", "imageName" + ".jpg");
                        try{
                            OutputStream os = new FileOutputStream(file);
                            b.compress(Bitmap.CompressFormat.JPEG, 100, os);
                        } catch (Exception e){

                        }

                        return null;
                    }
                }.execute();

            }
        });
```

**Comment by TWiStErRob** [comment]
@mkiisoft I don't suggest using an ImageView like this, consider this more Glide-y solution:
```java
Glide
	.with(context)
	.load("image_url")
	.asBitmap()
	.toBytes(Bitmap.CompressFormat.JPEG, 80)
	.into(new SimpleTarget<byte[]>() {
		@Override public void onResourceReady(final byte[] resource, GlideAnimation<? super byte[]> glideAnimation) {
			new AsyncTask<Void, Void, Void>() {
				@Override protected Void doInBackground(Void... params) {
					File sdcard = Environment.getExternalStorageDirectory();
					File file = new File(sdcard + "/YourDir/imageName.jpg");
					File dir = file.getParentFile();
					try {
						if (!dir.mkdirs() && (!dir.exists() || !dir.isDirectory())) {
							throw new IOException("Cannot ensure parent directory for file " + file);
						}
						BufferedOutputStream s = new BufferedOutputStream(new FileOutputStream(file));
						s.write(resource);
						s.flush();
						s.close();
					} catch (IOException e) {
						e.printStackTrace();
					}
					return null;
				}
			}.execute();
		}
	})
;
```
Notice that 2/3 of this is writing the byte[] into a file and async networking/loading/transforming/caching is 7 lines formatted loosely.

If this is a one-off writing by user request from UI, I also suggest adding these:
```java
.diskCacheStrategy(DiskCacheStrategy.NONE)
.skipMemoryCache(true)
```

You can also control the size and transformation via the following methods:
```java
.centerCrop().atMost().override(2000, 2000)
```

**Comment by mkiisoft** [comment]
@TWiStErRob yep, this is one off image (over API with parsing, etc would be crazy) I'm using it to get the full image to crop it later and I rather have it on my phone and then save it anywhere I want. All the other cached images with this gets delete it after the user close the app.

Thanks for the tips.

**Comment by Mouadabdelghafouraitali** [comment]
@TWiStErRob  please a i have a problem with API 23 or above when i try to download image :

`Glide
    .with(context)
    .load("image_url")
    .asBitmap()
    .toBytes(Bitmap.CompressFormat.JPEG, 80)
    .into(new SimpleTarget<byte[]>() {
        @Override public void onResourceReady(final byte[] resource, GlideAnimation<? super byte[]> glideAnimation) {
            new AsyncTask<Void, Void, Void>() {
                @Override protected Void doInBackground(Void... params) {
                    File sdcard = Environment.getExternalStorageDirectory();
                    File file = new File(sdcard + "/YourDir/imageName.jpg");
                    File dir = file.getParentFile();
                    try {
                        if (!dir.mkdirs() && (!dir.exists() || !dir.isDirectory())) {
                            throw new IOException("Cannot ensure parent directory for file " + file);
                        }
                        BufferedOutputStream s = new BufferedOutputStream(new FileOutputStream(file));
                        s.write(resource);
                        s.flush();
                        s.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    return null;
                }
            }.execute();
        }
    })
;`

**Comment by TWiStErRob** [comment]
@Mouadabdelghafouraitali at first glance you probably miss the permission to write to `/sdcard/`. Take a look at #459 for a better solution than this.

**Comment by Mouadabdelghafouraitali** [comment]
@TWiStErRob THANKS so much for reply and sorry to disturb i already added

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`
and i have another problem when i save image he doesn't appear in my gallery

please help my

**Comment by TWiStErRob** [comment]
@Mouadabdelghafouraitali http://stackoverflow.com/a/19794372/253468, but please don't use the mounting broadcast or a full directory scan; specify your file exactly!

**Comment by Mouadabdelghafouraitali** [comment]
@TWiStErRob  yeah i did this :

**Comment by vyvital** [comment]
Hello, 
I have found multiple ways to download Images from url to the SD card, and they all work perfectly on the Emulator but on the mobile phone they download an extremely small sized image, how can I fix that? even the code here gives the same results, on the mobile the image is perfect and huge even 4mb, but on the phone its barley 300kb and mostly even less. What am i missing?

**Comment by raghav-thakkar-rishabh** [comment]
I am having an issue with Glide 4.
Below code is not working in Glide 4. 
Does anyone know how to copy the code in the Glide 4. 
Glide
    .with(context)
    .load("image_url")
    .asBitmap()
    .toBytes(Bitmap.CompressFormat.JPEG, 80)
    .into(new SimpleTarget<byte[]>() {
        @Override public void onResourceReady(final byte[] resource, GlideAnimation<? super byte[]> glideAnimation) {
            new AsyncTask<Void, Void, Void>() {
                @Override protected Void doInBackground(Void... params) {
                    File sdcard = Environment.getExternalStorageDirectory();
                    File file = new File(sdcard + "/YourDir/imageName.jpg");
                    File dir = file.getParentFile();
                    try {
                        if (!dir.mkdirs() && (!dir.exists() || !dir.isDirectory())) {
                            throw new IOException("Cannot ensure parent directory for file " + file);
                        }
                        BufferedOutputStream s = new BufferedOutputStream(new FileOutputStream(file));
                        s.write(resource);
                        s.flush();
                        s.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    return null;
                }
            }.execute();
        }
    })
;
