### ISSUE TITLE
A exception of "Already release" 

### ISSUE THREAD

**Issue by Zhangzhiyi** [bumptech/glide#802]
I use newest code of glide in my project. But my app get a exception information of "Already release" so much.

like this.
![image](https://cloud.githubusercontent.com/assets/4149571/11682259/9be0c170-9e9e-11e5-8d1b-295a981dd95a.png)

**Comment by TWiStErRob** [comment]
Do you have anything calling `Bitmap.recycle()`? or `pool.release(bm)`? Maybe a custom transformation or target?

**Comment by Zhangzhiyi** [comment]
I never call Bitmap.recycle() or pool.release(bm) manually and not yet anyothter transformation or target.The exception didn't appear every time when I test my app. So I don't sure the step of reappearing the exception.

###code snippets
`
mRequestManager.asDrawable().load(albumImageUri).apply(RequestOptions.placeholderOf(R.drawable.banner_default)).into(viewHolder.wallAlbumImage);
`

`
mRequestManager.asDrawable().load(imageurl[finalI]).preload();
`

`
mRequestManager.asDrawable().load(mApp.getIcon()).apply(RequestOptions.placeholderOf(R.drawable.app_default_icon).centerCrop(mContext).transform(mContext, new RoundedCorners(mContext, DisplayUtil.dip2px(mContext, 2)))).into(imgIcon);
`

`
mRequestManager.asDrawable().load(mUserInfo.getAvatarUrl()).apply(RequestOptions.placeholderOf(R.drawable.user).circleCrop(getActivity())).into(mCircleImageView);
`

**Comment by TWiStErRob** [comment]
`RoundedCorners` is a transformation, can you share that code or point to a repo?

It may not be related to transformations, but worth checking, this exception looks more like the `EngineJob` is released twice. What are you doing to the app on the phone when this happens? What interactions does that cause with Glide? (e.g. loads into single or list)

**Comment by Zhangzhiyi** [comment]
I had tested my app with our testing engineer particularly however we can't reappear the crash. But we get another exception when the phone haven't sdcard. 

![lalobfzr1m0bqc0eba_1132_321](https://cloud.githubusercontent.com/assets/4149571/11711621/b7c9d81c-9f62-11e5-8e29-25c1ea3d4851.png)


I saw the source code and debug that found the "loadData" is null
`
  public void onDataReady(Object data) {
    DiskCacheStrategy diskCacheStrategy = helper.getDiskCacheStrategy();
    if (data != null && diskCacheStrategy.isDataCacheable(loadData.fetcher.getDataSource())) {
      dataToCache = data;
      // We might be being called back on someone else's thread. Before doing anything, we should
      // reschedule to get back onto Glide's thread.
      cb.reschedule();
    } else {
      cb.onDataFetcherReady(loadData.sourceKey, data, loadData.fetcher,
          loadData.fetcher.getDataSource(), originalKey);
    }
  }
`

**Comment by TWiStErRob** [comment]
@sjudd I think this one is for you.

**Comment by Zhangzhiyi** [comment]
@TWiStErRob  The "already release" exception had appeared When I scroll a listview. but next time I couldn't reappear. I hope the exception information will helpful to fix the bug.

![qq 20151211165203](https://cloud.githubusercontent.com/assets/4149571/11772636/50d7ea46-a259-11e5-80aa-5d86a631d7d1.png)

**Comment by Zhangzhiyi** [comment]
@TWiStErRob I met this exception again. 
![lalobpigrfxnbfc_1111_85](https://cloud.githubusercontent.com/assets/4149571/12441230/d43b6334-bf7f-11e5-9097-95b859843fab.png)

You can see that the diskCacheStrategy is null. so I checked the source code found that the diskCacheStrategy assin null is in the method of releaseInternal in DecodeJob.
