### ISSUE TITLE
Glide Gifs OOM 

### ISSUE THREAD

**Issue by invisbo** [bumptech/glide#806]
Hello,
I have Listview+ViewHolder with gifs. When i use my app normally it works well but when i try to scroll up/down repeatedly or on a fast scroll down at starting, i get oom exception. I know this is a rare situation but i need to fix this. My gifs sizes : 13.6kb,19.3kbi19.3kb,1.0mb,1.2mb,1.6mb,1.7mb,1.7mb.

**Comment by TWiStErRob** [comment]
Can you share your adapter, please?

**Comment by invisbo** [comment]
This my getView() method; 
     ViewHolderGif holder;
            if (row == null) {
                row = layoutInflater.inflate(rowLayoutId, parent, false);
                holder = new ViewHolderGif();
                holder.myImageView = (ImageView) row.findViewById(R.id.myGifImage);
                row.setTag(holder);
            } else {
                holder = (ViewHolderGif) row.getTag();
            }

         Glide.with(activity).load("gif.link").asGif().diskCacheStrategy(DiskCacheStrategy.SOURCE).into(holder.myImageView);

**Comment by TWiStErRob** [comment]
Hmm, it's so short it can't go wrong... that didn't reveal the problem :(

You could be hit by #83, do you know which GIF fails to load? Maybe it's just too big to keep in memory, or it's small, but each frame is huge.

You could be hit by #690, the best I could say is to do a normal memory leak hunting, check out these links https://github.com/bumptech/glide/issues/679#issuecomment-148194654: try to find a way to consistently reproduce the OOM, like: "scroll down 4, up 2, down 3, up 2, crash"... after that start reproducing but stop right before it happens, that is: ""scroll down 4, up 2, down 3, up 1" and take a heap dump. If OOM doesn't crash your app you can just take the dump right after it happened. In Eclipse Memory Analyzer (MAT) you can check the dominator tree or top consumers and try to figure out what is consuming the most memory, and from that what is it that shouldn't be there.

**Comment by invisbo** [comment]
Here is the case, when i scroll up down(at least 10 times faslty) memory usage increasing, but if i stop before app gives crash, memory usage going down again. I want to ask that while i am scrolling on listview: when image goes out of screen before load, what happening threads in glide. My point is, if glide continue loading gifs then when i scroll with slow internet it is going to be lots of thread process.

**Comment by TWiStErRob** [comment]
Aah, that sounds like too many frames are being loaded in the backgorund at the same time and they're not cancelled, right?

**Comment by invisbo** [comment]
Yes exactly.

**Comment by TWiStErRob** [comment]
From your description it sounds like a pressing issue for you, so you may want to try this workaround:
```java
list.setOnScrollListener(new OnScrollListener() {
	@Override public void onScrollStateChanged(AbsListView view, int scrollState) {
		switch (scrollState) {
			case SCROLL_STATE_IDLE:
				Glide.with(view.getContext()).resumeRequests();
				break;
			case SCROLL_STATE_TOUCH_SCROLL:
			case SCROLL_STATE_FLING:
				Glide.with(view.getContext()).pauseRequests();
				break;
		}
	}
```
*I didn't test it, just an idea that may help you.*

**Comment by invisbo** [comment]
Nice idea but when the fling stop all requests resume at the same time and make oom exec. But i will use these lines ;
Glide.with(view.getContext()).resumeRequests();
Glide.with(view.getContext()).pauseRequests();
All i need is a way that to find listview childs are showing on screen or not.

**Comment by TWiStErRob** [comment]
> Nice idea but when the fling stop all requests resume at the same time 

It won't all resume at the same time, only those who are on-screen at the moment of stopping the fling. All the others have been cancelled and overridden by newer ones when re-binding the list item. You should give it a try.

> All i need is a way that to find listview childs are showing on screen or not.

I think the ones that have been through `Adapter.getView`, but not `RecyclerListener.onMovedToScrapHeap` are bound and visible.

**Comment by invisbo** [comment]
```
list.setOnScrollListener(new OnScrollListener() {
    @Override public void onScrollStateChanged(AbsListView view, int scrollState) {
        switch (scrollState) {
            case SCROLL_STATE_IDLE:
                Glide.with(view.getContext()).resumeRequests();
                break;
            case SCROLL_STATE_TOUCH_SCROLL:
            case SCROLL_STATE_FLING:
                Glide.with(view.getContext()).pauseRequests();
                break;
 }
```    
Thanks a lot, this works i just needed to change `view.getContext()` with `(view.findViewById(R.id.myGifImage)).getContext()`.

**Comment by TWiStErRob** [comment]
Hmm, why? The ListView and the all the items should be the part of the same activity... It's interesting that `findViewById` returns a value even if there are multiple views with the same id.
