### ISSUE TITLE
Rotate bitmap example

### ISSUE THREAD

**Issue by siavashkavousi** [bumptech/glide#812]
There is no way to rotate bitmap except for bitmap transformation but I cannot do it efficiently in bitmap transformation

**Comment by TWiStErRob** [comment]
Can you please describe what you're trying to do?

Without that, here're 3 thoughts:

 * With `RESULT` caching you can win a lot of efficiency for expensive transformations.
 * [Matrix rotation](http://stackoverflow.com/a/10332901/253468) in a transformation should be around as fast as a fitCenter.
 * You can set `android:scaleType="matrix"` and call `setImageMatrix` with a rotation matrix of your choice, this will work regardless of loading with Glide or not.

**Comment by siavashkavousi** [comment]
I've written a rotate transformation like this 

```java
class RotateTransformation : Transformation<Bitmap> {
    private lateinit var bitmapPool: BitmapPool
    private var orientation : Float = 0f

    constructor(context: Context, orientation : Float) {
        bitmapPool = Glide.get(context).bitmapPool
        this.orientation = orientation
    }

    constructor(bitmapPool: BitmapPool, orientation: Float) {
        this.bitmapPool = bitmapPool
        this.orientation = orientation
    }

    override fun transform(resource: Resource<Bitmap>, outWidth: Int, outHeight: Int): Resource<Bitmap>? {
        val source = resource.get()

        var bitmap = bitmapPool.get(source.width, source.height, Bitmap.Config.ARGB_8888)
        if (bitmap == null)
            bitmap = Bitmap.createBitmap(source.width, source.height, Bitmap.Config.ARGB_8888)

        val matrix = Matrix()
        matrix.postRotate(orientation)
        bitmap = Bitmap.createBitmap(bitmap, 0, 0, source.width, source.height, matrix, true)

        return BitmapResource.obtain(bitmap, bitmapPool)
    }

    override fun getId(): String? {
        return "RotateTransformation()"
    }
}

but it takes a lot of memory in my app when I use it like this 

```java
Glide.with(ctx).load(imagePath)
                .bitmapTransform(FitCenter(ctx), RotateTransformation(ctx, -90f))
                .crossFade()
                .into(imageView)
```

I know that I load a bitmap in memory and the memory usage is because of that, but I don't know what Glide does for memory efficiency!

**Comment by TWiStErRob** [comment]
You're not using the `source` pixels, you just "get or create" a `bitmap` from pool and then rotate that empty bitmap. This shouldn't affect memory usage though..., but read the code of the `createBitmap` overload you use to transform with Matrix to see that it'll create the Bitmap for you. If you want to reuse a bitmap from pool, you'll have to copy the essence of that method and do it yourself, after that `BitmapResource.obtain` will make sure that it's returned to the pool.

You should also use Glide `TransformationUtils.getSafeConfig`-like method to not introduce transparency without reason.

I think you're seeing the bitmap pool and memory cache in action. You may [configure the sizes yourself](https://github.com/bumptech/glide/wiki/Configuration#memory-caches-and-pools), but it should be ok. Take a heap dump and check where the Bitmap instances are referenced from, for example see the ~21/26MB sizes below:

 1. [Take heap dump, convert and open with MAT](http://developer.android.com/tools/debugging/debugging-memory.html#HeapDump)
 2. Execute one of these OQLs:

    ```sql
    select * from instanceof android.graphics.Bitmap
    select * from byte[]
    ```
    ![image](https://cloud.githubusercontent.com/assets/2906988/11793728/7da38d7e-a2ad-11e5-857c-9ca3e650fea6.png)
 3. Shift-select all results (including the "Total: x of y entries; (y-x) more" line!)
 4. Right click and "Merge Shortest Paths to GC Roots > with all references"
 5. Expand `DexCache.resolvedTypes[i] == Glide.class`:
    ![image](https://cloud.githubusercontent.com/assets/2906988/11793624/f502ac7a-a2ac-11e5-9a3b-2c02ffcc6343.png)

Also note that active resources (Bitmaps set into ImageViews - displayed or not) are referenced by Glide via `WeakReference`s so you won't see a sum inside `engine`.

**Comment by siavashkavousi** [comment]
I've fixed memory issues but the problem is with showing it on the screen I've write 

```java
 val canvas = Canvas(bitmap)
        val matrix = Matrix()
        matrix.setRotate(orientation, (source.width / 2).toFloat(), (source.height / 2).toFloat())
        canvas.drawBitmap(source, matrix, null)
```
