### ISSUE TITLE
image URL is https

### ISSUE THREAD

**Issue by djw576981748** [bumptech/glide#813]
Image URL is https,can't load image to view

**Comment by TWiStErRob** [comment]
We can't do much with "it doesn't work"... please provide more information, see [this](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues).

In any case you might always want to try [these diagnostics](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) before asking for help.
