### ISSUE TITLE
Can glide  add a .9 picture as a  placeholder 

### ISSUE THREAD

**Issue by naiyu** [bumptech/glide#814]
I trying to add a .9 pictrure as a placeholder, but it seems useless, the placeholder is stretch as the imageview's size is bigger than the picture's size.

for this probleam, is there any way to solve this.

**Comment by TWiStErRob** [comment]
If it doesn't work with `placeholder(R.drawable...)`, you can always try `placeholder(drawable)` where you pass an already loaded object.

What is your scaletype? Does it work if you skip Glide and just call `iv.setImage*` with your 9-patch?

**Comment by naiyu** [comment]
I have try the scaletype by fitXY and centerCrop, I will try `placeholder(drawable)` later, thanks

**Comment by TWiStErRob** [comment]
So the problem was that 9-patch doesn't expand if scaleType is fitXY?

Self note: support 9-patches in #350 through load().

**Comment by meikaiss** [comment]
I use glide-4.2,   and code is:

**Comment by meikaiss** [comment]
I use glide-4.2,  I have a placeholder width 9-patch,   but  glide show the  placeholder like a  normal png,   How can I show the placeholder width 9-patch.

`Glide.with(context).load("my_net_image_url")
                .apply(new RequestOptions().placeholder(R.drawable.my_9_patch))
                .into(myImageView);`

and myImageView's sacleType is centerCrop which is write in xml.
