### ISSUE TITLE
Quality of image resource is pretty low

### ISSUE THREAD

**Issue by tien8d** [bumptech/glide#815]
I tried to load an image with a resource id with this method
```
DrawableTypeRequest<Integer> load(Integer resourceId)
```
And quality was pretty bad. It's not the quality of the image itself, because if I do something like this:
```
.load("")
.placeholder(imageResource)
```
Then the image looks fine.

**Comment by TWiStErRob** [comment]
You or the image might be sensitive to 565 bitmaps, try to load them as 8888, see #759 for example.

You can [do it globally](https://github.com/bumptech/glide/wiki/Configuration#bitmap-format) or per load: `.asBitmap().format(PREFER_ARGB_8888)`.

**Comment by tien8d** [comment]
I've already tried to use ARGB_8888. As I said, the image looks fine if I use it as a placeholder. Could you do a quick test or I need to provide a sample project that has this issue?

**Comment by TWiStErRob** [comment]
`load` and `placeholder` go on different paths as far as I know. placeholder just gets the drawable as usual from resources (like you would), but load decodes the image itself from an APK opened stream (like it would from a network stream).

I could take a look if you share a little project.

**Comment by TWiStErRob** [comment]
Please reopen if you can provide a comprehensive code sample.
