### ISSUE TITLE
Handle invalid/interrupted images in custom DataFetcher

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#818]
I'm using a custom `DataFetcher` that looks like following:

```
 public static class DropboxDataFetcher implements DataFetcher<InputStream>
{
    private DropboxMedia mMedia;
    private ISourceManager mSourceManager;
    private boolean mPreview;
    private int mWidth;
    private int mHeight;

    public DropboxDataFetcher(ISourceManager sourceManager, DropboxMedia media, boolean preview, int w, int h)
    {
        mMedia = media;
        mSourceManager = sourceManager;
        mPreview = preview;
        mWidth = w;
        mHeight = h;
    }

    @Override
    public InputStream loadData(Priority priority) throws Exception {
        return mSourceManager.getImage(mMedia, mPreview, mWidth, mHeight);
    }

    @Override
    public void cleanup() {

    }

    @Override
    public String getId() {
        return mPreview + "|" + mMedia.getId();
    }

    @Override
    public void cancel() {

    }
}
```

I get a valid response from dropbox, but the stream is sometimes interrupted. The result is, that glide is not showing an image. I see messages like `SkImageDecoder:: Factory returned null` in the output window as a result. Cleaning the cache helps most of the time.

Can I somehow avoid caching of invalid results? I have no idea where to check. The request response is checked BEFORE returning the stream to the `DataFetcher`...

**Comment by TWiStErRob** [comment]
Well, the most trivial way is to not cache (NONE)... but I guess you don't want to do that. Is this SOURCE or RESULT cache we're talking about? Can you look at the file in cache in binary/hexa viewer to see what got cached?

Just shooting ideas here:
 * How does ISourceManager behave? Maybe it stops the stream based on some unrelated interaction.
 * Are those streams parsable as image files for sure? Maybe there's some encoding issue.
 * Afair it's the DataFetcher's responsibility to close to stream in cleanup (check other implementations). Try adding that, maybe source manager doesn't like too many streams.

**Comment by MFlisar** [comment]
I'm using `DiscCacheStrategy.All`. My source manager uses Scribe and just returns the stream from the http request.

I at least changed my `DataFetcher` now. It remembers the stream and closes it in cleanup.

The streams I get are results of different cloud apis or similar, I can't be sure about anything. I just check the http response code to fit the value the corresponding api should give back (mostly the 200 OK) and then get the stream from the response and hand it on to the `DataFetcher`.

**Comment by TWiStErRob** [comment]
I think the SOURCE caching will just read the stream while it can, so if it silently stops producing bytes, you may end up with half-image in cache. The streams handed to Glide should throw an exception when interrupted, timeout, or other fatal failure while reading. Try to debug the runtime type, maybe it's a silent one. If so just wrap it in something that throws or request a throwing one.

Did you have a chance to check the actual file in cache versus the expected one? To see if it's bytes are the same, encoded differently or missing half of it. I think this is key to understanding what's going on.

**Comment by MFlisar** [comment]
It's the case that the stream just stops due to bad internet connection...

I make a http request and check the http response code and if it's fine, I hand on the stream to the `DataFetcher`. There's no exception anymore afterwards. Don't know how I could check if the stream was read until the end. I can only think of following: Changing the `DataFetcher<InputStream>` to a `DataFetcher<Bitmap>` (didn't check if that's possible yet though) and create a bitmap from the stream on my own and afterwards try to validate the bitmap. If it's invalid, I can throw an exception... But I don't know where to throw one otherwise or better said, how to decide if I should throw one...

**Comment by TWiStErRob** [comment]
It's possible to return anything at any stage (4 type arguments of GenericRequestBuilder), you just may lose some built-in support. I don't think you could decode a partial stream better than Glide does, you would just get that null from the logs.

As a workaround you could read the full stream into a `ByteArrayInputStream` and return that to Glide, that way your in control of errors. It's weird though a broken connection should time out or throw some other "I'm interrupted" exception. Would it be the same as starting a load and turning off WiFi midway?

You could wrap the stream in a FilterInputStream and count the bytes and throw in close (cleanup) if you know the expected size. Though I think Glide reads while it returns bytes... (usual EOF contract). It's really up to how the returned stream behaves/signals death. It would be nice if you could debug where the exception/error mark gets lost. Or can you make a sample app which can repro this consistently? E.g. by loading a 10MB+ image and turning off the internet.
