### ISSUE TITLE
How to force a reload uri？

### ISSUE THREAD

**Issue by BrightYu** [bumptech/glide#819]
How to force a reload uri？

**Comment by TWiStErRob** [comment]
If I understand you correctly you need to read this wiki: https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#custom-cache-invalidation

I suggest you use `.signature()` and change the signature key itself when updating the file.

Others have had this multiple times, [this issue list](https://github.com/bumptech/glide/issues?q=is%3Aissue+invalidate+cache+signature+is%3Aclosed) is also a good read.

**Comment by BrightYu** [comment]
signature it has a good job,  thanks for your help.
