### ISSUE TITLE
Updating users avatar cache

### ISSUE THREAD

**Issue by rshah** [bumptech/glide#824]
I'm using Glide to cache all images, which includes users avatar.
But i have problem when the other users changed their avatar, it's not reflected in my device.

My questions:
- Is there a way do delete the cache only for users avatar not other images, provided i know the avatar url pattern?
- The server send 'Last-Modified' in it's response header. Does Glide utilize this?

Thank you.

**Comment by TWiStErRob** [comment]
`Last-Modified` is not handled by Glide, all information about the load has to be known prior to making the HTTP request. Just think about the fact that it's unnecessary to go to the network if we already have it in cache.

There's no way to delete it from cache. However you could replace the default network integration (`HttpUrlFetcher`) and steal that header from the response and store it somewhere (local db, properties, ...). Upon finishing the load (`onResourceReady`) you can force a reload of the image with a new `.signature` based on the just-received header field. Any future request can also use the saved signature.

A less convoluted way is to have a set timeout (daily) when the profile picture is force-loaded if it's is shown in the app that day. Just add something like:
```java
.signature(new StringSignature(String.valueOf(System.currentTimeMillis() / (24 * 60 * 60 * 1000))))
```

You can find more information on existing issues about the same subject: [`is:issue signature`](https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=is%3Aissue+signature+)
Feel free to ask followup questions here.

**Comment by rshah** [comment]
I see, thank you for the suggestions.
