### ISSUE TITLE
Question - Using Glide onResourceReady in a ListAdapter

### ISSUE THREAD

**Issue by BrandonSlaght** [bumptech/glide#826]
Hi all,
I am using Glide to load images into containers in a GridView.  These containers also have TextViews underneath them, and I set the test of this to a particular thing.  However, I would like to make the labels and their backgrounds a bit more colorful, so I am using the Android Palette library to analyze the image and change the text and background to its dominant colors.  The only problem I have is that the incorrect TextView is changed.  It is usually the last TextView in the list, which makes sense, because the global reference to the view is changing every time a new item is added and by the time onResourceReady fires the view is already referencing the last item.  How can I save a reference to a particular view and pass it in to the onResourceReady method so I know which item should be changed?

My code is as follows:

```
public class searchadapter extends BaseAdapter {
    private Context c;
    private ArrayList<artist> results;
    View v;
    TextView txtTitle;


    public searchadapter(Context c, ArrayList<artist> results){
        this.c = c;
        this.results = results;
    }

    ........

    @Override
    public View getView(final int position, View convertView, ViewGroup parent) {
        if (convertView == null) {
            LayoutInflater mInflater = (LayoutInflater) c.getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
            convertView = mInflater.inflate(R.layout.result, null);
        }
        v=convertView;

        ImageView imgIcon = (ImageView) convertView.findViewById(R.id.icon);
        txtTitle = (TextView) convertView.findViewById(R.id.title);

        txtTitle.setText(results.get(position).getName());

        Glide.with(c.getApplicationContext()).load(results.get(position).getImage()).asBitmap().placeholder(R.drawable.missing_artist_art).into(new BitmapImageViewTarget(imgIcon) {
            @Override
            public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                super.onResourceReady(bitmap, anim);
                Palette p = Palette.from(bitmap).generate();
                txtTitle.setTextColor(p.getLightMutedColor(Color.WHITE));
                txtTitle.setBackgroundColor(p.getDarkVibrantColor(Color.GRAY));
            }
        });

   return convertView;

**Comment by TWiStErRob** [comment]
Remove txtTitle field and declare it as a final local variable, the closure will take care of the rest.

**Comment by BrandonSlaght** [comment]
This mostly works, thanks!  But now one thing I noticed is that if I have a long list of results that don't have images with one that does have an image at the beginning (I sort them so the results with images show up at the top) and I scroll the list, the colors of some of the boxes with the placeholder images are set to the original colors.  To fix this, I simply reset the colors of the box and text in the code before I execute Glide.  

You can mark this resolved, thanks again!

**Comment by TWiStErRob** [comment]
Yes you have to reset the color before Glide so if there's no image it'll stay default.

You should also consider integrating Glide with Palette, so the Palette generation is done in the background asynchronously, see [these classes](https://github.com/TWiStErRob/glide/tree/palette-lib/integration/palette/src/main/java/com/bumptech/glide/integration/palette). If you copy those classes to your project you can create a direct Palette target which will already have the generated palette for you:
```java
Glide
        .with(this)
        .as(PaletteBitmap.class)
        .load(uri)
        .into(new ImageViewTarget<PaletteBitmap>(imgIcon) { ... })
```
Make sure you [register the GlideModule](https://github.com/bumptech/glide/wiki/Configuration#creating-a-glidemodule), and you can ignore PaletteActionGroup/PaletteTargetBuilder/PaletteBitmapViewTarget classes, that's a failed attempt.

There's more advanced support in the works for 4.0 (which also takes care of the color issue you had).
