### ISSUE TITLE
Glide is using outdated Volley version

### ISSUE THREAD

**Issue by MAnfal** [bumptech/glide#827]
In integration wiki it is explicitly stated that glide is using volley 1.0.8 and my project is already using volley 1.0.19. Is there a workaround for it?

**Comment by TWiStErRob** [comment]
If you're using Maven or Gradle to consume Glide you can exclude transitive dependencies, see for example:
https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ModuleDependency.html#exclude%28java.util.Map%29

**Comment by TWiStErRob** [comment]
I think the wiki's idea is to show how to override the version number, not as a reference of what version is pulled in. If you explicitly use `1.0.19` it should override the older versions pulled by transitive dependencies.

**Comment by MAnfal** [comment]
The only line I have in my gradle dependencies is 

compile 'com.github.bumptech.glide:volley-integration:1.3.1'

from what you said I think I might end up with something like this.

compile 'com.github.bumptech.glide:volley-integration:1.3.1' {
       exclude module: 'com.mcxiaoke.volley:library:1.0.8'
}

I also tried to exclude volley dependency at all by manually importing

glide-volley-integration.jar 

and adding meta data 

<meta-data
    android:name="com.bumptech.glide.integration.volley.VolleyGlideModule"
    android:value="GlideModule" />

to menifest file on application level. Didn't work out for me. It keeps saying do the network request on background thread.

**Comment by MAnfal** [comment]
I just tried

`compile ('com.github.bumptech.glide:volley-integration:1.3.1') {
exclude module: 'com.mcxiaoke.volley:library:1.0.8'
}`

and it didn't work as well, I am getting duplicate entry for AuthFailure.class in volley 1.0.8 and 1.0.19

**Comment by TWiStErRob** [comment]
You need to break full name down (take another look at the doc I linked):
```
group: 'com.mcxiaoke.volley'
module: 'library'
version: '1.0.8'
```
It's usually not advised to exclude specific version, because you'll need to maintiain if you change the integration version to `1.3.2` for example.

I just tried this with `gradle dependencies` (a task which lists what wins over what), and the output for:
```gradle
compile 'com.github.bumptech.glide:volley-integration:1.3.1'
compile 'com.mcxiaoke.volley:library:1.0.19'
```
is
```
compile - Compile classpath for source set 'main'.
+--- com.github.bumptech.glide:volley-integration:1.3.1
|    +--- com.github.bumptech.glide:glide:3.6.1
|    \--- com.mcxiaoke.volley:library:1.0.8 -> 1.0.19
\--- com.mcxiaoke.volley:library:1.0.19
```

Note that you need `@aar` at the end for the manifest merger to pick up the `GlideModule` registration from the integration library (at least last time I checked - around Android Gradle Plugin 1.3 - it was required).

**Comment by TWiStErRob** [comment]
Which task is saying duplicate entry? dex? Maybe you just need a clean build.

**Comment by MAnfal** [comment]
Oh yeah, sorry I forgot to thoroughly read the doc I was in a hurry. Instead of excluding 1.0.8, I changed order of library compilation in gradle and the conflict is now gone. Thanks a lot.
