### ISSUE TITLE
Can glide get full size file from diskcache directly?

### ISSUE THREAD

**Issue by alenyu8** [bumptech/glide#828]
My project has a use case, i use glide to load the image into a ImageView first,then user can choose to download full size image file.Is't possible to get the full size file from disk cache directly?not to download the file from server again.(I think that glide has already cache the full size file in the disk,because used the "DiskCacheStrategy.ALL" option.)

**Comment by TWiStErRob** [comment]
This sounds like #459.

**Comment by alenyu8** [comment]
@TWiStErRob Thanks for your reply.There is another question,is't "downloadOnly" using glide cache mechanism? when access the url second time,can glide use the disk cache?

**Comment by TWiStErRob** [comment]
Follow the `downloadOnly` call chain in code. It's just setting some useful flags, the most important being to use SOURCE cache. So if you have it in cache it'll work without network.

If you want to force disable networking, that is you want to fail if image is not in cache, use `NetworkDisablingFetcher` from #629.

**Comment by alenyu8** [comment]
@TWiStErRob seem downloadonly only support glide internal fetcher,if i use custom fetcher,no downloadonly function can be invoke,is that right?example:
Glide.with(getApplicationContext()).from(DownloadModel.class).load(dm).downloadOnly(500,500); // not allowed
Glide.with(getApplicationContext()).load(url).downloadOnly(500,500); // it's ok

**Comment by TWiStErRob** [comment]
The `from` is a shorthand for ending up with `Drawable`s, see the return type of those methods.
I think you're looking for:
```java
Glide.with(context)
     //.using(new NetworkDisablingLoader<DownloadModel>()) // optional depending on if you want network or not
     .load(new DownloadModel())
     .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
;
class NetworkDisablingLoader<T> implements StreamModelLoader<T> {
	@Override public DataFetcher<InputStream> getResourceFetcher(final T model, int i, int i1) {
		return new DataFetcher<InputStream>() {
			@Override public InputStream loadData(Priority priority) throws Exception { throw new IOException(); }
			@Override public void cleanup() { }
			// to hit the cache of a custom model you may need to adapt this to return the same value as the custom fetcher does, this is needed for a cache hit
			@Override public String getId() { return model.toString(); }
			@Override public void cancel() { }
		};
	}
}
```

**Comment by alenyu8** [comment]
@TWiStErRob Thanks.It worked fine now!
