### ISSUE TITLE
OOM loading huge gifs

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#83]
A 3840x2880 example is http://media4.giphy.com/media/ToMjGpquWkOQon5nAvS/giphy.gif.

Probably the most reasonable thing is to catch the exception, allow the load to fail,  and encourage users to not try to load gigantic gifs, but we may also be able to find some reasonable way of downsampling GIFs the same way we do Bitmaps.

**Comment by kainecy** [comment]
I have changed the source code follow https://github.com/sjudd/glide/commit/b504aa2b52b5767e81d90eac0cf19fd0169b4a85 ,does not work.
Out of memory on a 4194320-byte allocation.
"fifo-pool-thread-1" prio=5 tid=31 RUNNABLE
...
 at com.bumptech.glide.load.resource.gif.GifResourceDecoder.inputStreamToBytes...


and my gif url is http://wankr-doubi.oss-cn-qingdao.aliyuncs.com/8ab85cde-b3e0-4a44-aacf-73f293f4b99f.gif

**Comment by sjudd** [comment]
Power of 2 downsampling was added here: https://github.com/bumptech/glide/commit/8be38e54a67fa29a7bd2c084210e574298144b93.

We still don't downsample all temporary data, so there's more work to do here. Specifically we need to find a way to downsample the byte array that is used to store pointers into the color table during the decode process for each frame.
