### ISSUE TITLE
How can i get Bitmp from Glide,

### ISSUE THREAD

**Issue by Mixiaomi** [bumptech/glide#830]
Compressed images through what method can I get,Glide.e .thumbnail() ,how to get Bitmap?thanks

**Comment by TWiStErRob** [comment]
```java
Target<Bitmap> target = Glide.with(...).load(...).asBitmap().into(...);
```
You can use a `SimpleTarget` if you're not setting it into a view, in `onResourceReady` you can play with the Bitmap, if you don't want the bitmap any more I suggest you call `Glide.clear(target)`. (inside `onResourceReady` you can also cal `Glide.clear(this)`.

**Comment by Mixiaomi** [comment]
A good partner, thank you@TWiStErRob

**Comment by Mixiaomi** [comment]
A good partner, thank you@TWiStErRob

2015-12-19 17:54 GMT+08:00 Róbert Papp <notifications@github.com>:
