### ISSUE TITLE
Loading raw image from File path through ByteBuffer

### ISSUE THREAD

**Issue by zetbrush** [bumptech/glide#832]
Hi, can you provide example for properly loading image(asBitmap/asDrawable) from ByteBuffer stored as file, with given path to it? thanks.

**Comment by TWiStErRob** [comment]
Hi, that sounds like you're using v4, right?
What do you mean by "ByteBuffer stored as file, with given path to it?" It sounds like a normal `File` with bytes inside. Is there a special serialized form of `ByteBuffer`? Or do you want to load from an in-memory `ByteBuffer`? Please provide a little more details.

**Comment by zetbrush** [comment]
yes, using v4, you are right it's a normal file with bytes inside( it's just raw bitmap wroth in file), so I have path to that file and need to load it. thanks

**Comment by TWiStErRob** [comment]
Check out #718 (it is for v3, but the same idea)

How do you know which resolution 8196 bytes (2048 ARGB pixels) represent: 2048x1, 1024x2, 512x4, 256x8, 128x16, 64x32?

**Comment by zetbrush** [comment]
ok thanks, will try it! I have resolution from file name, just when saving image, width/height are used to form filename of that raw bitmap :)

**Comment by zetbrush** [comment]
also .imageDecoder() on v3 is changed to RequestOptions.decodeTypeOf(), am I right?

**Comment by TWiStErRob** [comment]
No, I think that's for the initial model type (`File` or `String` in your case).

**Comment by zetbrush** [comment]
so how we supposed to set .imageDecoder() in v4?

**Comment by TWiStErRob** [comment]
I think you need to prepend/append to `registry` in `GlideModule.registerComponents`. I'm missing the per-request API too. See the `Glide` class constructor for defaults. As I see you want to insert your decoder before `StreamBitmapDecoder` to take priority over it (all images are raw in your app), or after `StreamBitmapDecoder` so yours is the fallback if `BitmapFactory` fails. You may need to use `RequestOptions.decode` with one of File/InputStream/Bitmap, not sure which one is that, I'm not familiar enough with v4 yet. @sjudd?

**Comment by zetbrush** [comment]
so I'm getting NoModelLoaderAvailable exception, although I've appended registry as follows 
```java
registry.append(HashMap.class, Bitmap.class, new RawDataDecoder(downSampler));
```
and loading is done like this
```java
 Glide.with(mContext).asBitmap().load(bufferData)
                        .apply(RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.NONE)
                                .decode(RawDataDecoder.class)
                                .dontTransform().dontAnimate()
                                .override(width, height))
                        .into(viewHolder.imageView);
```
where bufferData is HashMap(containg path,width,height) and RawDataDecoder implements ResourceDecoder<HashMap,Bitmap> which does actual decoding.
 
```java
E/GlideExecutor: Request threw uncaught throwable
                                                                 com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: {height=1024, width=1024, path=/storage/emulated/0/PA/.recent/d3fe6bf9-caaf-4f1d-b257-47c8982c1043/orig_w1024_h1024}
                                                                     at com.bumptech.glide.Registry.getModelLoaders(Registry.java:222)
                                                                     at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:180)
                                                                     at com.bumptech.glide.load.engine.SourceGenerator.hasNextModelLoader(SourceGenerator.java:70)
                                                                     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:57)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:273)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:240)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:218)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:263)
```

**Comment by TWiStErRob** [comment]
Notice that you didn't register a model loader, only a decoder. The model loader converts the model into something decodable, e.g. Uri --load/fetch-> stream  --decode--> Bitmap. Check the registry interface overloads, there should be a method to do something like: `register(HashMap.class, HashMap.class, loader/fetcher)`. You likely need a "passthrough" loader/fetcher that's just `return param`.

**Comment by zetbrush** [comment]
I handled this, but I'm getting another 
```java 
E/GlideExecutor: Request threw uncaught throwable
                                                                   java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
                                                                       at com.bumptech.glide.load.data.HttpUrlFetcher$DefaultHttpUrlConnectionFactory.build(HttpUrlFetcher.java:172)
                                                                       at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:89)
                                                                       at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:55)
                                                                       at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
                                                                       at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:273)
                                                                       at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:243)
                                                                       at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:218)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                       at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:263)
``` 
it looks like glide trying to load from network, how we can handle this?
I have tried also setting ```DiskCacheStrategy.RESOURCE```  and ```DiskCacheStrategy.ALL``` no difference.

example log 
```Load failed for {height=1869, width=2803, path=/storage/emulated/0/PA/.recent/df3a6694-a765-450c-aeee-fda09e079c81/orig_w2803_h1869} with size [1080x1509]```

**Comment by TWiStErRob** [comment]
It's not trying network, `FileURLConnection` is like `file:///blah`, the question is how did you end up with a `GlideUrl` model, when you have a `HashMap` model? I think one of the registrations on your side, or the default Glide ones is diverting Glide from what you're trying to achieve.

Can you please share all Glide code what you have so far?

**Comment by TWiStErRob** [comment]
This could be a v4 bug, in which it is not catching this exception too.

**Comment by zetbrush** [comment]
hmm, currently I'm away of my desk, but as I remember in my ModelLoaderFactory in ```ModelLoader<HashMap, InputStream> build```  ``` new ModelLoaderFactory (multiModelLoaderFactory.build(GlideUrl.class, InputStream.class), modelCache)``` is returned, so it ends up with ```GlideUrl``` model i guess, I'll check it tommorrow. thanks!

**Comment by zetbrush** [comment]
So now I'm getting this Log
```
W/Glide: Load failed for {height=1024, width=1024, path=/storage/emulated/0/PA/.recent/d3fe6bf9-caaf-4f1d-b257-47c8982c1043/orig_w1024_h1024} with size [1080x1509]
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource```

some example are here
```registry.append(HashMap.class, Bitmap.class, new RawDataDecoder(downSampler));
registry.append(HashMap.class, ByteBuffer.class, new ByteBufferModelLoader.Factory());
```
ModelLoader ```
public class ByteBufferModelLoader implements ModelLoader<HashMap,ByteBuffer> {

	private static final String TAG = "ByteBufferModelLoader";

	public ByteBufferModelLoader() {
	}

	public LoadData<ByteBuffer> buildLoadData(HashMap fileData, int width, int height, Options options) {
		return new LoadData(new ObjectKey((String)fileData.get("path")), new ByteBufferModelLoader.ByteBufferFetcher(fileData));
	}

	@Override
	public boolean handles(HashMap hashMap) {
		return true;
	}


	private static class ByteBufferFetcher implements DataFetcher<ByteBuffer> {
		private final HashMap file;

		public ByteBufferFetcher(HashMap file) {
			this.file = file;
		}

		public void loadData(Priority priority, DataCallback<? super ByteBuffer> callback) {
			ByteBuffer result = null;

			try {
				result = ByteBufferUtil.fromFile(new File((String)this.file.get("path")));
			} catch (IOException var5) {
				if(Log.isLoggable("ByteBufferModelLoader", 3)) {
					Log.d("ByteBufferModelLoader", "Failed to obtain ByteBuffer for file", var5);
				}

				callback.onLoadFailed(var5);
				return;
			}

			callback.onDataReady(result);
		}

		public void cleanup() {
		}

		public void cancel() {
		}

		public Class<ByteBuffer> getDataClass() {
			return ByteBuffer.class;
		}

		public DataSource getDataSource() {
			return DataSource.LOCAL;
		}
	}

	public static class Factory implements ModelLoaderFactory<HashMap, ByteBuffer> {
		public Factory() {
		}

		public ModelLoader<HashMap, ByteBuffer> build(Context context, MultiModelLoaderFactory multiFactory) {
			return new ByteBufferModelLoader();
		}

		public void teardown() {
		}
	}
```
ResourceDecoder 
```
public class RawDataDecoder implements ResourceDecoder<HashMap, Bitmap> {
	private final Downsampler downsampler;

	@Override
	public boolean handles(HashMap bufferData , Options options) throws IOException {
		return true;
	}

	public RawDataDecoder(Downsampler downsampler) {
		this.downsampler = downsampler;
	}

	@Nullable
	@Override
	public Resource<Bitmap> decode(HashMap bufferData, int i, int i1, Options options) throws IOException {
		int width = (Integer) bufferData.get("width");
		int height = (Integer) bufferData.get("height");
		String path = (String) bufferData.get("path");
		ByteBuffer buffer;
			buffer = ByteBuffer.allocate(4 * width * height);
		try {
			FileUtils.readFromFile(path, buffer);
		} catch (Exception e) {
			L.e(L.LOGTAG, "getBitmapFromBufferPath RawDataDecoder", e);
			return null;
		}
		buffer.position(0);
		InputStream is = ByteBufferUtil.toStream(buffer);
		return	downsampler.decode(is,width,height,options);

	}
}
```
Request

``` Glide.with(context).asBitmap().load(bufferData).listener(listener).apply(RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.ALL).decode(RawDataDecoder.class).dontAnimate().dontTransform()).into(target);

**Comment by TWiStErRob** [comment]
You know how to convert a HashMap into a Bitmap, and how to convert a HashMap into a ByteBuffer. If you're starting from a HashMap can you reach Bitmap?

Note that you're not getting a "missing piece" error, because there's a path from HashMap to Bitmap, the problem is that the ByteBuffer -> Bitmap conversion doesn't use your decoder for the custom "raw" format. It is instead trying to decode a normal JPG/GIF/PNG I think.

You need to modify one of them:
 * Modify RawDataDecoder to decode a ByteBuffer into a Bitmap...but then you lose the sizing info... though you could use `.override(w,h)` to pass the size to the loader, which can create a buffer based fetcher using on the width/height of `buildLoadData`
 * Modify the fetcher to simply call `callback.onDataReady(this.file);`, that is tell Glide how to convert a HashMap into a HashMap. This will create a path that didn't exist above, so your decoder can be reached.

**Comment by TWiStErRob** [comment]
Tip: you need new lines on GitHub after and before the triple-ticks.

**Comment by zetbrush** [comment]
I have already tried pass 
```
callback.onDataReady(this.file);
```
then something like
```
NoEncoderException
``` 
is thrown.
also I have tried with 
```
.override(w,h)
``` 
which logs same message

**Comment by TWiStErRob** [comment]
No encoder means it is probably trying to cache, turn off SOURCE caching on the request since you already have a file locally.

**Comment by zetbrush** [comment]
using `RequestOptions.diskCacheStrategyOf(DiskCachStrategy.NONE)`  outputs 
```
Load failed for {height=1024, width=1024, path=/storage/emulated/0/PicsArt/.recent/d3fe6bf9-caaf-4f1d-b257-47c8982c1043/orig_w1024_h1024} with size [1080x1509]
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```
am I missing something?

**Comment by TWiStErRob** [comment]
Hmm, I'll try it when I get to my PC.

**Comment by zetbrush** [comment]
roger that

**Comment by TWiStErRob** [comment]
Wait a minute, I just noticed that you're delegating to Glide's `Downsampler`... this whole issue started because Glide's default decoder doesn't support raw files, try this:
```java
public class RawDataDecoder implements ResourceDecoder<HashMap<String, ?>, Bitmap> {
	private final BitmapPool pool;
	public RawDataDecoder(BitmapPool pool) {
		this.pool = pool;
	}

	@Override public boolean handles(HashMap<String, ?> bufferData , Options options) throws IOException {
		return bufferData.containsKey("path") && bufferData.containsKey("width") && bufferData.containsKey("height");
	}

	@Override public @Nullable Resource<Bitmap> decode(
			HashMap<String, ?> bufferData, int w, int h, Options options) throws IOException {
		int width = (Integer) bufferData.get("width");
		int height = (Integer) bufferData.get("height");
		String path = (String) bufferData.get("path");
		ByteBuffer buffer = ByteBuffer.allocate(width * height * 4);
		FileUtils.readFromFile(path, buffer);
		Bitmap result = Bitmap.createBitmap(width, height, Config.ARGB_8888);
		buffer.position(0);
		result.copyPixelsFromBuffer(buffer);
		return BitmapResource.obtain(result, pool);
	}
}
```

**Comment by TWiStErRob** [comment]
Updated my prev comment with a very simple working version.

**Comment by zetbrush** [comment]
hmm I see, haven't thought about that, so no need of explicit `.encode(RawFileDecoder.class)` use in request? will try this tomorrow. thanks.

**Comment by zetbrush** [comment]
I'm still getting failure log,here it is.
```
 W/Glide: Load failed for /storage/emulated/0/PA/.recent/d3fe6bf9-caaf-4f1d-b257-47c8982c1043/orig_w1024_h1024 with size [1024x1024]
                                                           class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                             Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, DATA_DISK_CACHE, ObjectKey{object=/storage/emulated/0/PicsArt/.recent/d3fe6bf9-caaf-4f1d-b257-47c8982c1043/orig_w1024_h1024}
                                                               Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                               Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                               Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                             Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, DATA_DISK_CACHE, ObjectKey{object=/storage/emulated/0/PA/.recent/d3fe6bf9-caaf-4f1d-b257-47c8982c1043/orig_w1024_h1024}
                                                               Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                               Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                               Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                             Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, DATA_DISK_CACHE, ObjectKey{object=/storage/emulated/0/PA/.recent/d3fe6bf9-caaf-4f1d-b257-47c8982c1043/orig_w1024_h1024}
                                                               Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                               Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
                                                             Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, LOCAL
                                                               Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                               Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                               Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                             Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, LOCAL
                                                               Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                               Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                               Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                             Cause (6 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, LOCAL
                                                               Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                               Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
```

**Comment by TWiStErRob** [comment]
I saw a huge exception, is everything ok?

**Comment by zetbrush** [comment]
nope,just trying to get the case. on simple project when there are no library modules, its loads fine without even helper decoder class and without appending registry, but when glide is under some lib module, that loading failure log is thrown, maybe we need to keep some special classes(no proguarding), although I have declared  meta data in manifest and GlideModule implementing classes in progurad.cfg

**Comment by TWiStErRob** [comment]
Hmm, debug if Glide picks up your module (it's in Glide class). The merger may omit it for some reason if it's in an lib project?
Remember that v4 is unreleased, maybe there's a bug where class names are compared by string not class instances, though that would change too when proguarding.

**Comment by zetbrush** [comment]
it actually worked)) thanks for support, issue was in `handles()` wrong regex match by me.
