### ISSUE TITLE
Why the imageview scaletype be changed by glide?

### ISSUE THREAD

**Issue by alenyu8** [bumptech/glide#834]
Example: I put a ImageView, set `scaletype="center"` (will not scale), but when I use 
```java
Glide.with(getApplicationContext()).load(url).placeholder(R.drawable.ic_default).into(imageV);
```
seem that the scaletype been changed, because I found that the placeholder icon been filled the whole imageview size.

**Comment by JaySong** [comment]
I also encountered such a problem, I set the placeholder after the centerCrop attribute no effect, the picture will not be full of ImageView

**Comment by TWiStErRob** [comment]
Hmm, that's interesting. Is it possible that you placeholder is bigger than the view? That's the only case I can't think when it'll fill.

**Comment by alenyu8** [comment]
@TWiStErRob the placeholder icon is smaller than loaded image.

**Comment by TWiStErRob** [comment]
Hmm, if you put `.dontAnimate()` does it solve the problem? Also can you please share your XML with layout surrounding the ImageView?

**Comment by alenyu8** [comment]
@TWiStErRob tested .dontAnimate(),it worked now!Thank you.ps:is't a bug when setted animate?

**Comment by alenyu8** [comment]
My test xml layout below.Thanks again.
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin">

    <ImageView
        android:id="@+id/tv2"
        android:layout_width="match_parent"
        android:layout_height="150dp"
        android:src="@drawable/ic_default"
        android:scaleType="center"
        />

    <android.support.v7.widget.AppCompatImageView
        android:id="@+id/tv1"
        android:layout_width="150dp"
        android:layout_height="150dp"
        android:layout_below="@id/tv2"
        android:src="@drawable/ic_default"
        android:scaleType="center"
         />

</RelativeLayout>

**Comment by TWiStErRob** [comment]
So your `ic_default` looks good before Glide?, and then when it starts loading it gets bigger?

You're likely seeing #363: the default anim is `.crossFade()` and the stock `TransitionDrawable` doesn't handle different sized Drawables.

*Tip: use `tools:src` in xml to have a preview in the IDE editor, but not actually load it at runtime.*

**Comment by DanteAndroid** [comment]
Still no solution? I know `dontAnimate` is a good work-around, but  that looks not good without animation. Even I use `xml` animation, it will blink before the animation.

**Comment by TWiStErRob** [comment]
@DanteAndroid it depends on what is your problem. I think you may want to open a new issue with details filled in (java/xml code) from the issue template.

Regarding this issue: there was no reply after my last comment so I assume the duplicate was correct. #363 has a workaround (see last comment there) if you really need to consistently animate between different sizes. `dontAnimate` is just a way to test for `TransitionDrawable` related bugs, it's not a workaround. If this doesn't help please open a new issue and describe everything from scratch to see what your parameters are.

**Comment by DanteAndroid** [comment]
@TWiStErRob my problem is like description in the post, it's just simple that I don't think I need to open a new issue: My scaleType of imageView is `centerCrop`, and when I use `placeholder` of Glide, placeholder is shown right, then the loaded image is resized in wrong scaleType (fitXY). If I add `dontanimate`, it goes right. I checked #363 but to be honest I don't understand what happened there(too much code for a workaround). I appreciate if you guys can fix the bug asap.

**Comment by TWiStErRob** [comment]
The ImageView's scaleType is never wrong, neither any size of the Drawables/Bitmaps loaded by Glide. The problem is `TransitionDrawable` (an Android component): it can't handle different aspect ratios. The first image in #363 OP shows what's going on, "FULL" should be the same font shape as the others.

Less-code workaround: use a placeholder that matches your view's aspect ratio. That way when the centerCropped image (which has the aspect of the view, because it was cropped to that size) will be transitioned correctly from the placeholder (that also has the correct aspect, because you made it so).

**Comment by DanteAndroid** [comment]
@TWiStErRob thanks for your detail explanation a lot, I understand the problem better. Wish you a good day!
