### ISSUE TITLE
GitHub code and released library jar differs too much

### ISSUE THREAD

**Issue by huyn** [bumptech/glide#838]
How do we get the latest code cause there are lots of difference between github version and lib version? My team wants to implements some customized features based on this lib.
But when we downloaded this lib and run some samples, we found this lib is too old. For example, even the class structure differs from the jar lib you provided. So, can we get any help? Thanks a lot!

**Comment by TWiStErRob** [comment]
Use the 3.0 branch, that's the last released 3.6.1 version (with some unreleased bugfixes). The current master is the development branch for v4, which is available as snapshot: https://github.com/bumptech/glide/wiki/Snapshots
