### ISSUE TITLE
Is that downloadOnly not cache the image?

### ISSUE THREAD

**Issue by naiyu** [bumptech/glide#839]
I have two activities named AActivity and BActivity, I want to cache a picture but not show it in the AActivity, then when it turns to BActivity, I hope it should show from the cache, I try to use the `downloadOnly` to cache the image:

```java
Glide.with(context).load(url).downloadOnly(620, 400);
```

In the BActivity I use the code 

```java
Glide.with(this).load(url).into(imageview);
```

to load the image.

But it seems not cache the image while in the BActivity it will load the image from net again.

I just want to cache the picture, and not showing it, how can I do?

**Comment by TWiStErRob** [comment]
You need to tell Glide in activity B that it can use the SOURCE cache (default is RESULT): `.diskCacheStrategy(ALL)`.

Note that `downloadOnly`'s arguments are not used to resize the image, only the original is cached. If you want to pre-cache the resized one use the following in activity A:
```java
.diskCacheStrategy(ALL).fitCenter().preload(620, 400)
```
The transformation and size must match the ImageView's in activity B.

**Comment by naiyu** [comment]
@TWiStErRob Thanks, it's ok
