### ISSUE TITLE
OOM problem,SOS

### ISSUE THREAD

**Issue by fg2q1q3q** [bumptech/glide#846]
![qq 20151228093737](https://cloud.githubusercontent.com/assets/6970621/12013015/b4956dda-ad47-11e5-9a28-b3653d5ddd10.jpg)
![qq 20151228093813](https://cloud.githubusercontent.com/assets/6970621/12013016/b4be3f1c-ad47-11e5-8345-3142ea8c9130.jpg)

**Comment by TWiStErRob** [comment]
Stack traces of `OutOfMemoryError`s don't help at all for diagnosing them. It just tells you it's broken and something filled up the memory. This filling happend much before the actual exception was thrown. This also implies that usually whatever throws the OOM is not actually the culprit. The only exception to this is when the amount of wannabe allocated memory is simply too big, for example: an array to be allocated is bigger than the maximum memory, then you know that some calculation went really wrong, like a 32000x32000@4 image would take around 4GB of memory.

Without you being able to reproduce there's not much you can do, just guess where the problem might be and validate in your code. If you can reproduce: get a heap dump and analyze your app's usage. Normal OOM diagnostic steps:
 * reproduce exception (wait till you see it in LogCat)
 * take a heap dump and analyze it

Here are some links:
 * [Overview of steps (2014)](http://stackoverflow.com/a/24547957/253468)
 * [Detailed steps (2011)](http://android-developers.blogspot.hu/2011/03/memory-analysis-for-android.html)
 * [Detailed steps (latest official docs)](https://developer.android.com/tools/debugging/debugging-memory.html#HeapDump)
 * [Important info to know depending on your Activity structure (timeless)](http://commonsware.com/blog/2011/10/03/activities-not-destroyed-to-free-heap-space.html)
 * ...or search Google for how to solve an OutOfMemoryError
 * there are also many-many [existing Glide issues for this](https://github.com/bumptech/glide/issues?utf8=✓&q=OOM+OR+OutOfMemory+OR+OutOfMemoryException+OR+OutOfMemoryError+OR+"Failed+to+allocate"+)
