### ISSUE TITLE
Bug : Trying to use a recycled bitmap

### ISSUE THREAD

**Issue by neoteknic** [bumptech/glide#857]
Hello,
There is a bug in my app, I cant reproduce it so I have no more than this log : 
Android version : 5.1.1
```java
12-30 10:47:18.564 E/ACRA    (23560): ACRA caught a RuntimeException for com.zelift.zeliftdijon
12-30 10:47:18.564 E/ACRA    (23560): java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@2ab8a34a
12-30 10:47:18.564 E/ACRA    (23560): 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
12-30 10:47:18.564 E/ACRA    (23560): 	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:599)
12-30 10:47:18.564 E/ACRA    (23560): 	at com.bumptech.glide.load.resource.bitmap.m.draw(GlideBitmapDrawable.java:101)
12-30 10:47:18.564 E/ACRA    (23560): 	at android.widget.ImageView.onDraw(ImageView.java:1158)
12-30 10:47:18.564 E/ACRA    (23560): 	at android.view.View.draw(View.java:15321)
12-30 10:47:18.564 E/ACRA    (23560): 	at android.view.View.updateDisplayListIfDirty(View.java:14257)
12-30 10:47:18.564 E/ACRA    (23560): 	at android.view.View.getDisplayList(View.java:14279)
12-30 10:47:18.564 E/ACRA    (23560): 	at android.view.View.draw(View.java:15049)
12-30 10:47:18.564 E/ACRA    (23560): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
12-30 10:47:18.564 E/ACRA    (23560): 	at android.support.design.widget.CollapsingToolbarLayout.drawChild(CollapsingToolbarLayout.java:290)
...
```

**Comment by TWiStErRob** [comment]
Do you have any of the following in your application?:
* custom targets  
`? implements Target` directly or indirectly, most likely `extends SimpleTarget` or `ImageViewTarget`
* custom transformations  
`? implements Transformation` directly or indirectly, most likely `extends BitmapTransformation`
* `ImageView.getDrawable()` calls

Please include their code and usage. That exception can happen if the bitmap (`Drawable`) is kept after Glide said "forget it", or prematurely recycled.

**Comment by chainani** [comment]
@TWiStErRob What if I need to use getDrawable()? how do I handle that?

**Comment by TWiStErRob** [comment]
@chainani Please open a new issue describing what do you want to do. Include your current code as well. Your intention can help us to give the best solution, so don't hold back on the description ;)

**Comment by chainani** [comment]
@TWiStErRob can this happen if i manipulate the Layout params of the ImageView(get and set)? or if I call getLocationOnScreen()?

**Comment by TWiStErRob** [comment]
@chainani No, those should be ok, because they're independent of Bitmaps. However, if you steal the Bitmap in any way or you have a custom view that doesn't handle switching/nulling drawables you may get an issue, see my above comment for usual place where this could happen. Feel free to open a new issue with all your details if you want help.
