### ISSUE TITLE
Displayed .gifs occasionally tear/ frames get stuck

### ISSUE THREAD

**Issue by chimpslave** [bumptech/glide#858]
Recently I made several 3 second .gif files in AE and PS at 30fps. However, often the background will render on top of the static elements in the image, frames will be skipped causing tearing or previous frames will stick as it loops though the .gif.

Each gif is only 250px x 250px and around 80kb in size and i set it using the following:

``` java
Glide
    .with(this)
    .load(drawable)
    .into(new SimpleTarget<GlideDrawable>(250, 250) {
        @Override
        public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
            if (resource.isAnimated()) {
                image.setImageDrawable(resource);
                resource.setLoopCount(2);
                resource.start();
            }
        }
    })
;
```

![structure_anim](https://cloud.githubusercontent.com/assets/16538418/12088441/1ffe6596-b2d3-11e5-949e-2cfcaa20b347.gif)

Any ideas?

**Comment by TWiStErRob** [comment]
I guess it's too fast to display. I'm not sure how Glide skips frames, if it skips at all, but if it skips it could mean that some delta information is missing so the resulting image gets torn apart, try without the delta, that is export each frame as is.

I think you should be using `ImageViewTarget` so the resources are freed better. It has a lot of methods overridden, which `SimpleTarget` just has empty bodies for. Just set the `loopCount` in `onResourceReady` and call super. This probably won't affect what you see, it's just being a better citizen ;)

**Comment by chimpslave** [comment]
Thanks for the speedy response! 

I retried the same animation posted but rendered at half the speed (15fps). It hasn't made any difference at all. After some repeat testing I have found that in my list of 6 the tearing etc primarily takes place when traversing back through the list. Swiping through the first time is fine about 95% of the time but its almost guaranteed to tear after that.

I don't quite understand why though as a new Fragment is loaded for each gif. The only thing I can really think of is interference corresponding to memory usage.

I shall try your second solution now and let you know if anything has changed.

**Comment by TWiStErRob** [comment]
The frames are decoded on a few (2-4) threads, so if the phone can't supply the frames fast enough you might have a problem. Try with fewer GIFs on the screen at the same time. Check out #637 too; it's a different issue, but may give you some insights.

**Comment by chimpslave** [comment]
ImageViewTarget was an excellent suggestion as it has reduced the severity of the tearing ^^. 

Sorry, I should have been clearer. There is only one gif on the screen at a time. As you already know, it loops twice, it still mildly tears during the frames transitions but also it remains once complete. The following is the result after it has looped twice:
![screenshot_2016-01-04-13-41-50 1](https://cloud.githubusercontent.com/assets/16538418/12090775/b62f91fa-b2e9-11e5-9541-89a96d97f860.png)

**Comment by TWiStErRob** [comment]
Hmm, so it's a ViewPager with a fragment adapter? If so there may be off-screen pages, so other GIFs may be playing simulateously in the background.

**Comment by chimpslave** [comment]
I already accounted for that :). There is no viewpager, It's an activity with a static subclass fragment. The activity keeps track of the current page and loads the fragment dealing with the UI elements. On fling or button press the activity is restarted with a bundle containing the current page.

**Comment by TWiStErRob** [comment]
@kojilin if you have some time can you please look at this one?

**Comment by kojilin** [comment]
Out of curiosity, Try to reproduce the problem but can't. Which version(glide), device for testing, or more real sample? 
I run the simple example(one activity, one fragment) on my htc e8 doesn't reproduce the problem.
I saw the gif is using combine flag, if this is replace flag, will it skip frames?

**Comment by chimpslave** [comment]
3.6.1, Samsung S4/ LG G3/ Nexus 9 and all .gifs were rendered at 30FPS. I have also rendered at 14FPS but that hasn't changed much. 
Im not sure what you mean about GIF combine flags but I have reduced the issue with better memory management. It only starts to tear now if you continually swipe forward and back through the set of gifs without closing the activity.
