### ISSUE TITLE
GifDrawable setLoopCount useless

### ISSUE THREAD

**Issue by littlezan** [bumptech/glide#860]
Hi, can you give me suggest about under issues:
1. while I use glide show gif found setloopcount is useless
2. how can I know gif animation complete?
I'm not good at English , think you.

**Comment by TWiStErRob** [comment]
Please describe what happens and what do you expect. Others don't seem to have problem with loopcount. You may need to call `start()` after setting the loopcount if the GIF was already displayed.

There's no callback for GIF, you can calculate the length of the GIF through `.getDecoder().getDelay()`, just sum up the delays and multiply by loopcount, and then schedule yourself a callback (for example Android's `Handler.postDelayed`) that is executed after that time.

Another possibility is to poll `gifDecoder().getCurrentFrameIndex()`, save the value and if the next poll gives a smaller value than stored, then it has been restarted (wrapped around).

You can also look at [other libraries which are specifically made for GIFs](https://github.com/koral--/android-gif-drawable) if you want more.

**Comment by littlezan** [comment]
Glide.with(context).load(ResUtil.getOriginalRelUrl(resid)).listener(new RequestListener<String, GlideDrawable>() {
            @Override
            public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                animationListener.onException();
                return false;
            }

            @Override
            public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                if (resource instanceof GifDrawable) {
                    gifDrawable = (GifDrawable) resource;
                    gifDrawable.setGifRunFrameListener(new GifDrawable.GifRunFrameListener() {
                        @Override
                        public void onRunFrameEnd() {
                            animationListener.onAnimationCompleted();
                            cancelGifAnimation();
                        }
                    });
                    setGifViewVisable(true);
                } else {
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    animationListener.onAnimationCompleted();
                    cancelGifAnimation();
                }
                return false;
            }
        })

I want setLoopCount before gif start, and I setLoopCount onResourceReady callback, found it useless.
I didn't call start()
In source code GlideDrawableImageViewTarget.java, I found it setLoopCount aging. 

>     @Override
    public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> animation) {
        if (!resource.isAnimated()) {
            //TODO: Try to generalize this to other sizes/shapes.
            // This is a dirty hack that tries to make loading square thumbnails and then square full images less costly
            // by forcing both the smaller thumb and the larger version to have exactly the same intrinsic dimensions.
            // If a drawable is replaced in an ImageView by another drawable with different intrinsic dimensions,
            // the ImageView requests a layout. Scrolling rapidly while replacing thumbs with larger images triggers
            // lots of these calls and causes significant amounts of jank.
            float viewRatio = view.getWidth() / (float) view.getHeight();
            float drawableRatio = resource.getIntrinsicWidth() / (float) resource.getIntrinsicHeight();
            if (Math.abs(viewRatio - 1f) <= SQUARE_RATIO_MARGIN
                    && Math.abs(drawableRatio - 1f) <= SQUARE_RATIO_MARGIN) {
                resource = new SquaringDrawable(resource, view.getWidth());
            }
        }
        super.onResourceReady(resource, animation);
        this.resource = resource;
        resource.setLoopCount(maxLoopCount);
        resource.start();
    }

At last, I add a GifRunFrameListener in GifDrawable 
Think you answer

**Comment by TWiStErRob** [comment]
Ah, ok. The `listener()` runs before `Target.onResourceReady` so if you set the loop count in the listener it'll be re-set by `GlideDrawableImageViewTarget`.
Use `into(new GlideDrawableImageViewTarget(imageView, 3))` and don't set it in the listener. (as a side effect you'll need to explicitly add `.fitCenter()` or `.centerCrop()`)

Also don't forget to remove that `sleep` once you release :) Stopping the world for 2 seconds is not the best user experience: most Glide callbacks are on the UI thread (except the ones needing I/O). There won't be any animation or draw happening if you block the UI thread either.

I also suggest to use `.diskCacheStrategy(SOURCE)` for GIF loads (even if you just guess from `url.endsWith(".gif")`), see #281 and related issues.

**Comment by littlezan** [comment]
Glide.with(context).load(ResUtil.getOriginalRelUrl(resid)).listener(new RequestListener<String, GlideDrawable>() {
            @Override
            public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                animationListener.onException();
                return false;
            }

            @Override
            public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                Handler handler = new Handler();
                if (resource instanceof GifDrawable) {
                    gifDrawable = (GifDrawable) resource;

                    int duration = 0;
                    GifDecoder decoder = gifDrawable.getDecoder();
                    for (int i = 0; i < gifDrawable.getFrameCount(); i++) {
                        duration += decoder.getDelay(i);
                    }
                    handler.postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            animationListener.onAnimationCompleted();
                            cancelGifAnimation();
                        }
                    }, duration);

                    setGifViewVisable(true);
                } else {
                    handler.postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            animationListener.onAnimationCompleted();
                            cancelGifAnimation();
                        }
                    }, TimeUnit.SECONDS.toMillis(2));
                }
                return false;
            }
        }).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(new GlideDrawableImageViewTarget(gifImageView, 1));





This is what I changed at your suggestion.
When gif animate once,I need to dismiss the ImageView and do other things.
Thinks a lot

**Comment by TWiStErRob** [comment]
Awesome, thanks for sharing your final solution.

**Comment by abhinavkorpal** [comment]
Not getting Full libraries for android studio

**Comment by abhinavkorpal** [comment]
Any version number for glide

**Comment by ajaystha005** [comment]
I just switched to Glide 4.2. I can't see the method anymore.
`gifDrawable.getDecoder()`;

Is there is any listener for GIF Animation end/start?

**Comment by TWiStErRob** [comment]
@ajaystha005 that workaround was meant for 3.x. It looks like the in 4.x the decoder was encapsulated in a state/loader and is almost private now. There's no out-of-the box way yet, as discussed in #2524.

You can try to extend GifDrawable (potentially inside Glide's package) and use your own transcoder to create your custom one. This way you may be able to override the methods you need. Otherwise the GifDrawable needs to change either by opening up, or adding/implementing some interfaces.

**Comment by ajaystha005** [comment]
I implemented the interface and solve the problem. Can I do PR for this?

**Comment by TWiStErRob** [comment]
I think so, let's continue in #2524, as this issue is for beginning/end of anim, and you need individual frames.
