### ISSUE TITLE
Can Glide loadremote video?

### ISSUE THREAD

**Issue by cnscns** [bumptech/glide#862]

**Comment by TWiStErRob** [comment]
Try to load a remote video Uri, if it shows an image it's supported. Maybe you need to add `asBitmap()`.

I'm not sure it is though, imagine if the source stream would be cached. Even for low quality music videos it's 30-60MB per file. It's better for everyone if the server has <100kB thumbs for the vids.

**Comment by cnscns** [comment]
Thanks
