### ISSUE TITLE
View always appear light green background from cache load

### ISSUE THREAD

**Issue by AndroidFa** [bumptech/glide#863]
glide load cache image in SamsungNote2 ，image view always appear light green background.
glide version is 3.6.1
![Uploading photo.jpg…]()

**Comment by TWiStErRob** [comment]
Your image didn't upload, but sounds like a duplicate of #515. Sam explained it best here: https://github.com/bumptech/glide/issues/305#issuecomment-112937571

I'm going to close this as a duplicate, but feel free to ask followup questions here.

**Comment by AndroidFa** [comment]
Thank you for your answer
