### ISSUE TITLE
How to configure the glide for some different situations

### ISSUE THREAD

**Issue by naiyu** [bumptech/glide#865]
I have knew the global configuration from the wiki. I wander if there is any way to configure for some situations.

For me, I configurate the global decodeformat to PREFER_RGB_565, and now I need to decode the picture to PREFER_ARGB_8888 when my users scan the big picture.

Thanks, best wish!

**Comment by TWiStErRob** [comment]
`.asBitmap().format(PREFER_ARGB_8888)`

**Comment by naiyu** [comment]
Thanks, it's ok
