### ISSUE TITLE
Lower efficiency loading gif than android-gif-drawable

### ISSUE THREAD

**Issue by hamberluo** [bumptech/glide#868]
[android-gif-drawable project](https://github.com/koral--/android-gif-drawable)

**Comment by TWiStErRob** [comment]
I know, it's hard to compete with native C. Is there a particular use case when Glide's Java version is not sufficient? Also notice that that library is designed just for GIF. GIF support in Glide is about 2% of features. You're free to use that library combined with Glide: #805.
