### ISSUE TITLE
Bug:Delete the journal, Glide can't work.

### ISSUE THREAD

**Issue by acelouis** [bumptech/glide#870]
When i delete the journal file and all the cache images, Glide can't work utils i uninstall.

**Comment by TWiStErRob** [comment]
`Glide.get(context).clearDiskCache()`

You probably deleted the files while the app was still open. Try force closing before you delete the files, or use clear caches in app info in settings to delete the files.

I think if you take any application on any platform and mess with the files in an unexpected way, they're likely to misbehave.

If you don't want to users to mess around, use the protected internal cache directory (default). It's accessible to root, but rooting voids any guarantees anyway, including any app working, especially if you hack them.

**Comment by TWiStErRob** [comment]
You're free to create a pull request with code that detects if the disk cache was tampered with or missing and resets it by itself. Look around `DiskLruCacheWrapper`.
