### ISSUE TITLE
Are samples outdated?

### ISSUE THREAD

**Issue by yarolegovich** [bumptech/glide#873]
Hi, 
I'm searching for how to handle loaing image list efficiently. When trying to implement things according to this tutorial - a lot of classes simply can't be found.
https://github.com/bumptech/glide/blob/c2fc19316d8680322cabeed31234d19e942866e8/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrPhotoList.java
For example:
```java
import com.bumptech.glide.RequestBuilder;
import com.bumptech.glide.integration.recyclerview.RecyclerViewPreloader;
```

**Comment by TWiStErRob** [comment]
No, actually your Glide dependency is outdated. The currently released latest stable is 3.6.1 which corresponds to the 3.0 branch on GitHub. Glide v4 which is only available as [snapshot](https://github.com/bumptech/glide/wiki/Snapshots) (because it's not done) is what's on the master branch.
