### ISSUE TITLE
Toggle "Only On Wifi"

### ISSUE THREAD

**Issue by simontom** [bumptech/glide#876]
Hello,
is it possible to disable loading from Internet (for example when on MobileData / make use of some some toggle ...)
and only use Cached Data (and if no Cached Data show placeholderError or something)?

Best regard
Simon

**Comment by TWiStErRob** [comment]
You should be able to reduce #639 to what you need. Ask if you need help.

**Comment by simontom** [comment]
Hmmmm, looks interesting,
I will check that.
However, I miss some lib's feature. I use UniversalImageLoader, there is a way, how to do that pretty easily.

Thank You very much.

**Comment by simontom** [comment]
Well, just correct me if I'm doing it wrong:
Let's have a method

public static callGlide(Activity activity, ImageView imageView, boolean isOnlyOnWiFi) {
  if (isOnlyOnWiFi) {
    Glide.with(activity)
        .using(new StreamModelLoader<String>() {
            @Override
            public DataFetcher<InputStream> getResourceFetcher(final String model, int i, int i1) {
                return new DataFetcher<InputStream>() {
                    @Override
                    public InputStream loadData(Priority priority) throws Exception {
                        throw new IOException();
                    }
                    @Override
                    public void cleanup() {
                    }
                    @Override
                    public String getId() {
                        return model;
                    }
                    @Override
                    public void cancel() {
                    }
                };
            }
        })
        .load(urlStr)
        .diskCacheStrategy(DiskCacheStrategy.ALL)
        .into(imageView);
  }
  else {
      Glide.with(activity)
        .load(urlStr)
        .diskCacheStrategy(DiskCacheStrategy.ALL)
        .into(imageView);
  }
}

OR is there a way, how to get the defaul behaviour of the defulat StreamModelLoader?
If I understand it correctly, I might be able to just get the info from some static variable and throw IOException if isOnlyOnWiFi is TRUE (that means, do now dlownload images from the Internet, when on Mobile Data).

**Comment by TWiStErRob** [comment]
I assumed you only need it for specific loads (that is configure per load), then your code is acceptable. However notice that Glide.with is a builder so you can return it to have a more general version:
```java
wifiRequest(this, wifiOnly).load(urlStr).diskCacheStrategy(DiskCacheStrategy.ALL).into(imageView);

public static DrawableTypeRequest<String> wifiRequest(Context context, boolean isOnlyOnWiFi) {
	DrawableTypeRequest<String> request;
	if (isOnlyOnWiFi) {
		request = Glide.with(context).using(new NetworkDisablingLoader<String>()).from(String.class);
	} else {
		request = Glide.with(context).fromString();
	}
	return request;
}
```

---

If you want it to be global I suggest something like this:
```java
// in GlideModule:
glide.register(GlideUrl.class, InputStream.class, new WifiOnlyLoader.Factory());

public class WifiOnlyLoader implements ModelLoader<GlideUrl, InputStream> {
	private final ModelLoader<GlideUrl, InputStream> defaultLoader;
	public WifiOnlyLoader(ModelLoader<GlideUrl, InputStream> loader) {
		defaultLoader = loader;
	}
	@Override public DataFetcher<InputStream> getResourceFetcher(GlideUrl model, int width, int height) {
		SharedPreferences prefs = App.getPrefs(); // public static SharedPreferences getPrefs() { return PreferenceManager.getDefaultSharedPreferences(instance); }
		if (prefs.getBoolean("wifi_only", false)) {
			return new NetworkDisablingFetcher(model);
		} else {
			return defaultLoader.getResourceFetcher(model, width, height);
		}
	}
	public static class Factory implements ModelLoaderFactory<GlideUrl, InputStream> {
		@Override public ModelLoader<GlideUrl, InputStream> build(Context context, GenericLoaderFactory factories) {
			//ModelLoader<GlideUrl, InputStream> loader = factories.buildModelLoader(GlideUrl.class, InputStream.class);
			// the above could be used when you have a custom model, this version already replaced the default loader,
			// so it needs to be created explicitly. If you use OkHttp or Volley create that.
			return new WifiOnlyLoader(new HttpUrlGlideUrlLoader(new ModelCache<GlideUrl, GlideUrl>(500)));
		}
		@Override public void teardown() { }
	}
}
```

**Comment by simontom** [comment]
The second one seems to be the solution I need.
If I make "GlideConfiguration implements GlideModule" and register it in AndroidManifest.xml, then copy Your "WifiOnlyLoader implements ModelLoader<GlideUrl, InputStream>" into my project
plus register it inside GlideConfiguration, it should only load from cache if "wifi_only" is TRUE, right?
But how should NetworkDisablingFetcher look like?
Is this the right one?

class NetworkDisablingLoader implements StreamModelLoader<String> {
    @Override
             public DataFetcher<InputStream> getResourceFetcher(final String model, int width, int height) {
        return new DataFetcher<InputStream>() {
            @Override public InputStream loadData(Priority priority) throws Exception {
                throw new IOException("Forces Glide network failure");
            }
            @Override 
             public void cleanup() {
             }
            @Override
             public String getId() {
                 return model;
             }
            @Override
             public void cancel() {
             }
        };
    }
}

Best regard
Simon

**Comment by TWiStErRob** [comment]
It will always read from cache. Sorry, `wifi_only` may be not enough there, you'll have to add logic to figure out if you're on WiFi connection or not and decide based on those two. In it's current state it's more like `disallow_network`.

I gave you the Glide glue, it's up to you when you want to disable network requests (=try only cache) or make network requests (also peeks in cache first). Make sure you have the appropriate `.diskCacheStrategy()` added.

Note that the flow shouldn't even get to this loader if there was a cached resource; this is a helpful info when you're debugging and the breakpoint is just not hit.

Notice that there are two classes `NetworkDisablingLoader` and `NetworkDisablingFetcher`, the second of which is the anon class inside:
```
new DataFetcher<InputStream>() {...}
```
Returning a loader there would be a compile error.

**Comment by simontom** [comment]
Oh, OKay, thank You very much.
I have done something and it seems working as expected. I guess. :-D
Sure, I understand
boolean onlyCache = isImagesOnlyOnWiFi() && !isConnectedViaWiFi();

Best regard
Simon
