### ISSUE TITLE
Special Characters in URL Query Parameters get improperly URL encoded or throw Fatal Exception

### ISSUE THREAD

**Issue by jlmalone** [bumptech/glide#878]
**Glide Version/Integration library (if any)**: 3.6.1
**Device/Android Version**: Nexus 5 Android 6.0
**Issue details/Repro steps**:

Glide will not properly load image urls that contain special characters in the Query Parameters.

```java
String url  = "https://images.example.com/is/image/example/SKU_0001_1?$hp_wn_thumb_app$";
Glide.with(HomeFragment.this).load(url).listener(new ImagePlaceholderListener(
					viewHolder.mPlaceHolder)).centerCrop().into(viewHolder.mImageView);
```

this will in practise load the url:

```
https://images.example.com/is/image/example/SKU_0001_1?%24hp_wn_thumb_app%24
```

Trying to make a Url or GlideUrl object eg

```java
GlideUrl gurl = new GlideUrl("https://images.example.com/is/image/example/SKU_0001_1?$hp_wn_thumb_app$");

Glide.with(HomeFragment.this).load(gurl).listener(new ImagePlaceholderListener(
					viewHolder.mPlaceHolder)).centerCrop().into(viewHolder.mImageView);
```

will throw a fatal exception with stacktrace below.

There seems to be no other methods to call to disable url encoding the input string. Please advise.

**Stack trace**:
This stack trace comes when trying to load a java.net.Url object or com.bumptech.glide.load.model.GlideURL object constucted using special characters in the query parameter
```
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime: java.lang.ClassCastException: com.bumptech.glide.load.model.GlideUrl cannot be cast to java.lang.String
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at com.example.handler.ImagePlaceholderListener.onResourceReady(ImagePlaceholderListener.java:15)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:522)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:98)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-08 15:36:37.061 20317-20317/com.example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by TWiStErRob** [comment]
Notice that the stack trace says `ClassCastException` for `Listener.onResourceReady`. That `ImagePlaceholderListener` is most likely casting or using some unchecked generics somewhere. Whatever is passed to `load(T)` the same must be in `RequestListener<T, ...>` and the method argument as well. If this doesn't help please post the source of `ImagePlaceholderListener`.

**Comment by TWiStErRob** [comment]
Just to be clear: your request already completed successfully, only the delivery failed, so no problems with url-encoding.

**Comment by TWiStErRob** [comment]
See also #867 where we also talked about escaping in a little different context.

**Comment by jlmalone** [comment]
Thank you for the responses @TWiStErRob 
I am now attempting to create URL or GlideUrl objects that preserve the $ special character inside the query component, but nothing seems to be working. All of my constructions are % encoding the $ characters especially when passed into Glide. If you have any more suggestions for making the URL object or overriding encoding within glide, it would be appreciated. It is unfortunate that the server I am hitting uses non-standard compliant urls.




As requested, below is the ImagePlaceholderListener for reference. I can see that the crash I described comes from improper construction of this object when attempting to use URL or GlideUrl objects instead of Strings in the load method.



public class ImagePlaceholderListener<T> implements RequestListener<String, T>
{
	private final View mPlaceHolder;
	private final View mLoading;
	private final View mError;
	private final RequestListener<String, T> mCallback;
	private static final int mAnimationDuration;
	static
	{
		mAnimationDuration = ExampleApplication.getInstance().getResources().getInteger(android.R.integer.config_mediumAnimTime);
	}

	public ImagePlaceholderListener(final View view)
	{
		this(view, false, null);
	}

	public ImagePlaceholderListener(final View view, boolean small)
	{
		this(view, small, null);
	}

	public ImagePlaceholderListener(final View view, final	RequestListener<String, T> callback)
	{
		this(view, false, callback);
	}

	public ImagePlaceholderListener(final View view, final boolean small, final	RequestListener<String, T> callback)
	{
		mPlaceHolder = view;
		mLoading = view.findViewById(R.id.placeholder_image);
		if (small)
		{
			mLoading.getViewTreeObserver().addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener()
			{
				@Override
				public boolean onPreDraw()
				{
					mLoading.getViewTreeObserver().removeOnPreDrawListener(this);
					ViewGroup.LayoutParams layoutParams = mLoading.getLayoutParams();
					layoutParams.width = ExampleApplication
							.getInstance()
							.getResources()
							.getDimensionPixelSize(R.dimen.small_progress_dimension);
					layoutParams.height = layoutParams.width;
					mLoading.setLayoutParams(layoutParams);
					return false;
				}
			});
		}
		mError = view.findViewById(R.id.placeholder_error);
		mCallback = callback;
		mPlaceHolder.setAlpha(1f);
		mPlaceHolder.setVisibility(View.VISIBLE);
		mLoading.setVisibility(View.VISIBLE);
		mLoading.setAlpha(1f);
		mError.setVisibility(View.GONE);
	}

	@Override
	public boolean onException(Exception e, String model, Target<T> target, boolean isFirstResource)
	{
		showError();
		return mCallback != null && mCallback.onException(e, model, target, isFirstResource);
	}

	@Override
	public boolean onResourceReady(T resource, String model, Target<T> target, boolean isFromMemoryCache,
			boolean isFirstResource)
	{
		showImage(isFromMemoryCache);
		return mCallback != null && mCallback.onResourceReady(resource, model, target, isFromMemoryCache, isFirstResource);
	}

	private void showImage(boolean isFromCache)
	{
		mError.setVisibility(View.GONE);
		mLoading.setVisibility(View.GONE);
		if (isFromCache)
		{
			mPlaceHolder.setVisibility(View.GONE);
		}
		else
		{
			mPlaceHolder.setLayerType(View.LAYER_TYPE_HARDWARE, null);
			Animator animator = ObjectAnimator.ofFloat(mPlaceHolder, "alpha", 1f, 0f);
			animator.setDuration(mAnimationDuration);
			animator.addListener(new AnimatorListenerAdapter()
			{
				@Override
				public void onAnimationCancel(Animator animation)
				{
					mPlaceHolder.setLayerType(View.LAYER_TYPE_NONE, null);
					mPlaceHolder.setVisibility(View.GONE);
				}

				@Override
				public void onAnimationEnd(Animator animation)
				{
					mPlaceHolder.setLayerType(View.LAYER_TYPE_NONE, null);
					mPlaceHolder.setVisibility(View.GONE);
				}
			});
			animator.start();
		}
	}

	private void showError()
	{
		mError.setVisibility(View.VISIBLE);
		mError.setAlpha(0f);
		AnimatorSet animatorSet = new AnimatorSet();
		animatorSet.play(ObjectAnimator.ofFloat(mLoading, "alpha", 1f, 0f))
				.with(ObjectAnimator.ofFloat(mError, "alpha", 0f, 1f));
		animatorSet.addListener(new AnimatorListenerAdapter()
		{
			@Override
			public void onAnimationCancel(Animator animation)
			{
				mError.setAlpha(1f);
				mLoading.setVisibility(View.GONE);
			}

			@Override
			public void onAnimationEnd(Animator animation)
			{
				mError.setAlpha(1f);
				mLoading.setVisibility(View.GONE);
			}
		});
		animatorSet.start();
	}
}

**Comment by TWiStErRob** [comment]
**Are you sure that the server responds badly to %-escaped dollars?** I'm asking again, because `onResourceReady` was called, the only thing prevented showing the image was the wrong generics on the listener. I forgot to mention that you should remove the listener altogether and make the request work first without any fancies; and then once everything loads fine start adding  everything back one by one to see if it works together.

In the end you should just change the signature to `ImagePlaceholderListener<M, T>` and replace all `String`s with `M`. Also take the unchecked warnings with Glide seriously, they're there for a reason... generic classes should be instantiated with generic arguments, or use `Object` instead of `String`, because `.listener` declares `? super` that'll remove the unchecked warning as well, code:

```java
// be specific
class ImagePlaceholderListener<M, T> implements RequestListener<M, T> {...}
Glide.with(this).load(gurl).listener(new ImagePlaceholderListener<GlideUrl, GlideDrawable>()).into(imageView);
// or be lazy
class ImagePlaceholderListener<T> implements RequestListener<Object, T> {...}
Glide.with(this).load(gurl).listener(new ImagePlaceholderListener<GlideDrawable>()).into(imageView);
// or if you really want to be raw:
class ImagePlaceholderListener implements RequestListener<Object, Object> {...}
// but the above gives a compile error when using it.
// Introducing and not providing the `Dummy` type arg triggers erasure,
// this should work even if there's an unchecked warning because anything can be cast to Object.
class ImagePlaceholderListener<Dummy> implements RequestListener<Object, Object> {...}
Glide.with(this).load(gurl).listener(new ImagePlaceholderListener()).into(imageView);
```

As for **"overriding encoding within Glide"**: you can simply extend GlideUrl and override the methods that call `getSafeStringUrl` to prevent using the built-in `ALLOWED_URI_CHARS` and just encode however you want to. This will work simply because of polymorphism. `toURL` is called by the default HTTP layer and `toStringUrl` is called by OkHttp and Volley in case you have them registered for Glide.

**Comment by jlmalone** [comment]
ok, so I added the dependency to build.gradle:

dependencies {
...
    compile 'com.github.bumptech.glide:okhttp-integration:1.3.1@aar'


and I also took your advice on the custom GlideUrl:


import com.bumptech.glide.load.model.GlideUrl;
import com.bumptech.glide.load.model.Headers;

import java.net.MalformedURLException;
import java.net.URL;

/**
 * Necessary to help make correct calls to the API which does not apply and URL special Character correction.
 * Created by josephmalone on 16-01-10.
 */
public class ExampleGlideUrl extends GlideUrl
{
	private String urlString;

	public ExampleGlideUrl(URL url)
	{
		super(url);
	}

	public ExampleGlideUrl(String url)
	{

		super(url);
		urlString = url;
	}

	public ExampleGlideUrl(URL url, Headers headers)
	{
		super(url, headers);
	}

	public ExampleGlideUrl(String url, Headers headers)
	{
		super(url, headers);
	}

	/**
	 *
	 * Returns a properly escaped {@link String} url that can be used to make http/https requests.
	 *
	 * @see #toURL()
	 * @see #getCacheKey()
	 */
	@Override
	public String toStringUrl() {

		return urlString.replace("%24","$");
//		return getSafeStringUrl();
	}


}

My issue is now fixed. A thousand thank you's, @TWiStErRob
