### ISSUE TITLE
Proguard fails with missing classes when integration library is used with @aar

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#882]
Using the normal dependencies everything is fine:

``` gradle
compile 'com.github.bumptech.glide:glide:3.6.1'
compile 'com.github.bumptech.glide:okhttp-integration:1.3.1'

$ gradle -q :app:dependencyInsight --dependency okhttp --configuration compile
com.github.bumptech.glide:okhttp-integration:1.3.1
\--- compile

com.squareup.okhttp:okhttp:2.2.0
\--- com.github.bumptech.glide:okhttp-integration:1.3.1
     \--- compile
```

but when the `@aar` classifier is added

``` gradle
compile 'com.github.bumptech.glide:glide:3.6.1'
compile 'com.github.bumptech.glide:okhttp-integration:1.3.1@aar'
// compile 'com.squareup.okhttp:okhttp:2.0.0' // workaround

$ gradle -q :app:dependencyInsight --dependency okhttp --configuration compile
com.github.bumptech.glide:okhttp-integration:1.3.1
\--- compile
```

the automatic transtive inclusion of `okhttp` disappears, and proguard fails:

``` python
Warning: com.bumptech.glide.integration.okhttp.OkHttpStreamFetcher: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning: com.bumptech.glide.integration.okhttp.OkHttpUrlLoader: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning: com.bumptech.glide.integration.okhttp.OkHttpUrlLoader$Factory: can't find referenced class com.squareup.okhttp.OkHttpClient

:app:proguardRelease FAILED // in 1.2.3
:app:transformClassesAndResourcesWithProguardForRelease FAILED // in 1.5.0
org.gradle.api.tasks.TaskExecutionException: Execution failed for task '...'.
...
Caused by: java.lang.RuntimeException: java.io.IOException: Please correct the above warnings first.
...
Caused by: java.io.IOException: Please correct the above warnings first.
...
```

Using both `classpath 'com.android.tools.build:gradle:1.2.3'` and `1.5.0`. This may be an issue with the Android Plugin for Gradle or some POM inconsistency, I couldn't find out yet. The issue seems to have been existed since the beginning of time for integration libraries, there were just no reports. I discovered it while playing with #881, but quickly realized that it was already broken in 3.x as well.

A trivial workaround is to add the missed dependency (commented out above). This may come up for #646 as well, in which case, just run the insight for `glide` and add the missing dependencies.

**Comment by hzsweers** [comment]
Can you not just add -dontwarn to the okhttp integration aar? Seems like something worth reporting as an issue in the plugin though.

**Comment by TWiStErRob** [comment]
That's an option for a workaround, thanks for the idea, but I didn't try if running the app actually works. It's pointless to `dontwarn` if it'll trigger a runtime error, because the classes cannot be found.

Also notice that the `dependencyInsight` doesn't care about debug and release builds. The okhttp dep simply disappears.

**Comment by hzsweers** [comment]
Is the dependency actually removed or is it just on the library classpath but reported as missing to proguard since it's not directly declared in the consuming application's dependencies?

**Comment by TWiStErRob** [comment]
It is removed, I tried to reference a class from okhttp and the compilation failed without the explicit okhttp dependency. Opened http://b.android.com/198936
