### ISSUE TITLE
Glide not firing listener or respecting size multiplier 

### ISSUE THREAD

**Issue by mformetal** [bumptech/glide#883]
I have a simple Vertical RecyclerView, inside of which I am doing:

Glide.with(mContext)
                .load(sketch.getBytes())
                .into(holder.imageView);

Where "Sketch" is my RealmObject class that contains bytes. My holder.imageView is set as match_parent, and Glide correctly works in this case.

However, when I change my orientation to Horizontal, Glide does not fire. In that same snippet of code, if I add a .listener(RequestBuilder....), nothing inside the listener is fired. Why would this be the case? The dimens of my imageView change, of course, but that shouldn't completely remove the functionality of the library.

Forgot to mention: the only way horizontal scrolling works is calling .override() with my screen dimensions. This is, of course, ugly and results in some weird scrolling behavior, so I'd rather not have to do this if given the choice.

**Comment by TWiStErRob** [comment]
Are the views visible? The fact that `override` makes it work suggests that the onPreDraw is not called (see `ViewTarget.SizeDeterminer`). Views must be laid out for Glide to start the load.

What happens if you start the whole thing in horizontal orientation? (This eliminates bugs that may be caused by wrong lifecycle (rotation) handling in your app.)

**Comment by TWiStErRob** [comment]
Also you said after rotation listener doesn't fire. From this I assumed that nothing is displayed either, am I right?

**Comment by mformetal** [comment]
The views are not visible, no. My RecyclerView is though, and since that just lays out items, I would assume that Glide would be able to interpret size from that.

My app runs in portrait mode, so I don't think any "change orientation" bugs could occur.

**Comment by TWiStErRob** [comment]
For Glide to start loading it needs a size (override or from layout). For an view to be laid out it must be added to the view hierarchy and `setVisible(true)` (default). In a recycler view an item is attached to the layout by the time onBind is called, is your Glide code in that method? The baseline is: "don't do unnecessary work", and loading an image into a view that may never become visible to the user counts as this. Note that the constraints don't actually prohibit off-screen views which are properly attached and sized inside the parent view group.

If your application runs in portrait then please elaborate what do you mean when you say this:

> However, when I change my orientation to Horizontal

My request still stands, please try to start the app in a state where now orientation change is necessary to get a horizontal view. (or change above means code change and not a user interaction?)

**Comment by mformetal** [comment]
My apologies on the confusion. By "change orientation to Horizontal," I mean my layout manager for the recycler view. 

Regardless, I've ended up scrapping my original idea and going with something different, so you can mark this issue as closed. Thanks for your help.
