### ISSUE TITLE
Register cacheDecoder and encoder from GlideModule

### ISSUE THREAD

**Issue by yanngx** [bumptech/glide#884]
Hello,

The application I'm working on right now needs the cached images to be encrypted.
I managed to do so by defining BitmapEncoder and StreamBitmapDecoder subclasses and passing them to Glide using the appropriate BitmapTypeRequest's methods.

Everything works brilliantly but I was wondering if it is possible to register my Encoder/Decoder from the GlideModule, that way I can be sure they are used by default everywhere.

**Comment by TWiStErRob** [comment]
It's not officially possible in v3 as far as I know. Maybe with some reflection you could do it, but no guarantees. Take a look at class Glide's code, how those providers are initialised.

As I understand it'll be much easier in v4. It is available as [snapshot](https://github.com/bumptech/glide/wiki/Snapshots) if you want to take the leap right now.

**Comment by yanngx** [comment]
Thanks for the answer ! Indeed it should be very easy to set up in v4. 
We don't have a lot of image loading code in the current state of the app so I think I will wait for the v4 to be released and perform a healthy refactoring ;)
