### ISSUE TITLE
Custom Cache Implementation 

### ISSUE THREAD

**Issue by vipinhelloindia** [bumptech/glide#886]
Try to implement custom cache to that I can access it from anywhere in the app , instead of relying on glide load call . 

    public class GlideConfiguration implements GlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {

        // Prefer higher quality images unless we're on a low RAM device
        if (hasKitKat()) {
            ActivityManager activityManager =
                    (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
            builder.setDecodeFormat(activityManager.isLowRamDevice() ?
                    DecodeFormat.PREFER_RGB_565 : DecodeFormat.PREFER_ARGB_8888);
        } else{
            builder.setDecodeFormat(DecodeFormat.PREFER_RGB_565);
        }

        MemorySizeCalculator calculator = new MemorySizeCalculator(context);
        int defaultMemoryCacheSize = calculator.getMemoryCacheSize();
        int defaultBitmapPoolSize = calculator.getBitmapPoolSize();

        builder.setMemoryCache(new LruResourceCacheInternal(defaultMemoryCacheSize / 2));
        builder.setBitmapPool(new LruBitmapPool(defaultBitmapPoolSize / 2));
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
    }

    public static boolean hasKitKat() {
        return Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT;
    }
}    

    

   
Similar implementation to your <b>LruResourceCache</b>

Have added some log in get and Put in LRUCache ,

    public Y get(T key) {
        Log.i("vipin_get",key.toString());
        return cache.get(key);
    }

    public Y put(T key, Y item) {
        Log.i("vipin_put",key.toString());
        final int itemSize = getSize(item);
        if (itemSize >= maxSize) {
            onItemEvicted(key, item);
            return null;
        }

        final Y result = cache.put(key, item);
        if (item != null) {
            currentSize += getSize(item);
        }
        if (result != null) {
            // TODO: should we call onItemEvicted here?
            currentSize -= getSize(result);
        }
        evict();

        return result;
    }
    

,only Put is called , Is there something I am missing to add like <b>BitmapPool</b> to make it work .
Does that mean we are not picking the Bitmap from cache or some implementation need to be taken carefully .

**Comment by TWiStErRob** [comment]
See `Engine.getEngineResourceFromCache`, that's where `remove` is called. The memory cache only contains resources that were shown in a View, but has been cleared. It is removed when loading (instead of `get`) because it'll be immediately put into the active resources.

**Comment by vipinhelloindia** [comment]
@TWiStErRob Thanks , Can you let me know How can I create a Key from Url and Access the Bitmap if available in any BitmapPool or LRU Cache instead Glide Load Call ..

**Comment by vipinhelloindia** [comment]
Closing considering #54 #58
