### ISSUE TITLE
Set image to wrong imageView for listview item when first time show the ListView

### ISSUE THREAD

**Issue by Zhongjoe** [bumptech/glide#889]
I have a ListView in a fragment, use `Glide.with(applicationContext)` load network image in Adapter.
The problem is that the ListView show same icon for two item. but after scroll or switch fragment, every thing will be ok.

 First Time show the ListView.
![screenshot_2016-01-14-11-33-34](https://cloud.githubusercontent.com/assets/11606443/12315225/840e7cc8-bab3-11e5-95d5-231cc4262b4b.png)

After Switch Fragment or scroll listview
![screenshot_2016-01-14-11-33-43](https://cloud.githubusercontent.com/assets/11606443/12315233/8a0f0c50-bab3-11e5-8052-c6be8fc7c196.png)

Have a custom module:

```java
public class CustomGlideModule implements GlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        ViewTarget.setTagId(R.id.glide_tag_id);
        builder.setDecodeFormat(DecodeFormat.PREFER_RGB_565);
        builder.setDiskCache(new ExternalCacheDiskCacheFactory(context,"disk_cache",
                DiskCache.Factory.DEFAULT_DISK_CACHE_SIZE));
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        glide.register(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory());
    }
 }
```

My Gridle sttings:
```gradle
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'com.github.bumptech.glide:glide:3.6.1'
    compile 'com.github.bumptech.glide:okhttp-integration:1.3.1@aar'
```

**Comment by Zhongjoe** [comment]
My logic is:
If url is empty or null, show a default icon (a text on a pure color background).
If not use glide load the network icon.
 
The key code in Adapter :
<code>
    // I test , if set usCache false, every things is ok.

    if(mIconLoader != null && usCache ) {

        ///drawable is the default icon.

            mIconLoader.loadImage(iconUrl,holder.avatar,drawable);

        }else{

            holder.avatar.setImageDrawable(drawable);

    }
</code>

This is my Image loader. 

<code> 

    /**
     * Construct an ImageLoader with a default placeholder drawable.
     * * If the cache image,mabye use in other screen, need use {@link      Context#getApplicationContext()}
     */

    public ImageLoader(Context context, int placeHolderResId) {
        this.context = context;
        mPlaceHolderResId = placeHolderResId;
        mRequestManager =  Glide.with(this.context);
    }

     public void loadImage(String url, final ImageView imageView,
                          Drawable placeholderOverride, boolean crop) {

             internalLoadImage(url, imageView, placeholderOverride, 0, null);
    }


    private void internalLoadImage(String url, ImageView imageView, Drawable placeHolder,
                                   int placeHolderResId, BitmapTransformation transformation){
        if(TextUtils.isEmpty(url)){
            if(placeHolder != null) {
                imageView.setImageDrawable(placeHolder);
            } else if(placeHolderResId > 0){
                imageView.setImageResource(placeHolderResId);
            } else if(mPlaceHolderResId > 0){
                imageView.setImageResource(mPlaceHolderResId);
            }
            if(DEBUG){
                Log.d(TAG,"internalLoadImage, set default Image.#" + imageView.hashCode());
            }
            return;
        }
        if(DEBUG){
            Log.d(TAG," loadImage with String, url:" + url +", view#"+ imageView.hashCode());
        }
        DrawableTypeRequest request = mRequestManager.load(url);
       DrawableRequestBuilder builder = request.diskCacheStrategy(DiskCacheStrategy.ALL).dontAnimate();
        if(transformation != null){
            builder.transform(transformation);
        }
        placeHolderAndLoadIcon(imageView, placeHolder, placeHolderResId, builder);
    }

    private void placeHolderAndLoadIcon(ImageView imageView, Drawable placeHolder, int placeHolderResId, DrawableRequestBuilder builder) {
        if(placeHolder != null){
            builder.placeholder(placeHolder);
        }else{
            builder.placeholder(placeHolderResId>0?placeHolderResId:mPlaceHolderResId);
        }
        builder.into(imageView);
    }
</code>

**Comment by TWiStErRob** [comment]
Try to add a `Glide.clear(imageView);` inside `isEmpty` in `internalLoadImage`. We had some other issues where Glide gets confused because it assumes ownership over the `ImageView`, and `setImage*` breaks that.

Alternatively you can get rid of that `isEmpty` check and let Glide handle everything for you, see the `fallback()` method on request builder.

Tips:
* you shouldn't need to register okhttp factory if you have `@aar` in Gradle
* replace `imageView.hashCode()` in logging with:
    ```java
    context.getResources().getResourceEntryName(imageView.getId()) + "@" + imageView.hashCode()
    ```

**Comment by Zhongjoe** [comment]
@TWiStErRob   Thanks very much.
Follow your suggestion, just input <code>url ,ImageView, placeHolderResId</code> to <code>Glide</code>,everything is ok.

Check the <code>TextUtils.isEmpty(url)</code> just want more quickly return and load next icon.

<code> Glide.clear(imageView);</code> not working 
Thanks again.
