### ISSUE TITLE
How to set up a kind of image in the load, failure load set another picture

### ISSUE THREAD

**Issue by zhupengGitHub** [bumptech/glide#890]
I want to set different image in a different condition,for example,I want to set image1 to ImageView when the image is loading, set image2 to ImageView when the image load fail, set the requested image to the ImageView when success.

**Comment by TWiStErRob** [comment]
For the failure you can add a `.listener()` and start a new load in `onException`.

For placeholder think again: what would you show while the device struggles to download image1 through a bad network?

If you really want you can use `.thumbnail` though which will start two parallel loads and winner is displayed first, but in the end the main load will display for sure.

An alternative to all of the above is to have image1 and image2 packaged in the app for use as `R.drawable.image1` or loaded as a Drawable (even from network) and saved in some global state (if you use it a lot, and assuming there aren't many such images).

**Comment by TWiStErRob** [comment]
#451 may implement this use case as well.
