### ISSUE TITLE
[Question] is there a way to rotate image using glide?

### ISSUE THREAD

**Issue by raviteja06** [bumptech/glide#896]
I want to rotate the image based on user request. But I don't know how to do that using library. I tried using custom bitmap transformers but no luck. Can anyone help?

**Comment by TWiStErRob** [comment]
Bitmap transformation is the answer, maybe you didn't have different `getId`s and you hit the caches. Please post code so we can see what you tried and go from there if the `getId`s were correct.

**Comment by raviteja06** [comment]
Thanks @TWiStErRob for responding to my question. 
I change the id's to unique but didn't help. 

here is my code

    import android.content.Context;
    import android.graphics.Bitmap;
    import android.graphics.Matrix;

    import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool;
    import com.bumptech.glide.load.resource.bitmap.BitmapTransformation;

    public class MyTransformation extends BitmapTransformation {
    private float rotate = 0f;
    String id;

    public MyTransformation(Context context, float rotate, String id) {
        super(context);
        this.rotate = rotate;
        this.id = id;
    }

    @Override
    protected Bitmap transform(BitmapPool pool, Bitmap toTransform,
                               int outWidth, int outHeight) {
        return rotateBitmap(toTransform, rotate);
    }

    @Override
    public String getId() {
        return "com.example.helpers.MyTransformation."+id;
    }

    public static Bitmap rotateBitmap(Bitmap source, float angle) {
        Matrix matrix = new Matrix();
        matrix.postRotate(angle);
        return Bitmap.createBitmap(source, 0, 0, source.getWidth(), source.getHeight(), matrix, true);
    }
    }

in adapter

    Glide.with(context)
                        .load("file://" + projectMedia.getMediaInfo().getThumbnailPath())
                        .asBitmap()
                        .transform(new MyTransformation(context, projectMedia.getMediaInfo().getThumbnailRotate(), projectMedia.getMediaInfo().getThumbnailPath()))
                        .override(400, 400)
                        .fitCenter()
                        .into(imageView);

**Comment by TWiStErRob** [comment]
I mean unique as in `"RotateTransformation"+rotate`, so that cache is hit properly. Otherwise changing the rotation would not regenerate the image. If you make it totally unique per request you might as well turn off caching, sorry for not being more clear.

The problem is calling `fitCenter` after `transform`: transformations are not additive, check `fitCenter`'s code, try:
```java
.transform(new MyTransformation(...), new FitCenter(...))
```

**Comment by raviteja06** [comment]
No luck.


----------------

Best Regards,

Ravi Gadipudi






On Sat, Jan 16, 2016 at 12:35 AM -0800, "Róbert Papp" <notifications@github.com> wrote:












I mean unique as in "RotateTransformation"+rotate, so that cache is hit properly. Otherwise changing the rotation would not regenerate the image. If you make it totally unique per request you might as well turn off caching, sorry for not being more clear.



The problem is calling fitCenter after transform: transformations are not additive, check fitCenter's code, try:

.transform(new MyTransformation(...), new FitCenter(...))

**Comment by TWiStErRob** [comment]
Just to be sure: did you remove `.fitCenter()`?
If yes, next: try reading the [logs](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) to see if it behaves as you expect.
Also log `getThumbnailRotate` to see if it changes.

Oh, and what is the issue, really? Can you please write an expected/actual case? So far you've only said "it doesn't work", which doesn't mean much in the tech world. I was assuming that when you change rotation it is not reflected in the loaded image. Then you showed the code and I saw the duplicate transformation.

**Comment by TWiStErRob** [comment]
Feel free to reopen if you need more help and provide more info.
