### ISSUE TITLE
AbstractMethodError with OkHttp 3.0.1

### ISSUE THREAD

**Issue by guiwro** [bumptech/glide#900]
Got this runtime error with glide ```4.0.0-SNAPSHOT``` and ```okhttp3-integration 2.0.0-SNAPSHOT```, along OkHttp ```3.0.1```

```java
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.myapp.android.debug, PID: 21585
java.lang.AbstractMethodError: abstract method "void okhttp3.Callback.onResponse(okhttp3.Call, okhttp3.Response)"
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
`

**Comment by floating-cat** [comment]
I guess this issue is not related to Glide.
Do you use Retrofit 2 ? If so, see this https://github.com/square/retrofit/issues/1475

**Comment by guiwro** [comment]
Yes, I also use Retrofit 2.0.0-SNAPSHOT, and the crash occurs only when Glide loads an image.

**Comment by TWiStErRob** [comment]
Can you please execute `gradle dependencies --configuration compile` on your project from command line? It sounds like you're using the right versions based on the text above and what Jake said in the other issue, but worth double checking.

**Comment by guiwro** [comment]
```
+--- com.squareup.okhttp3:okhttp:3.0.1
|    \--- com.squareup.okio:okio:1.6.0
+--- com.squareup.okhttp3:logging-interceptor:3.0.1
|    \--- com.squareup.okhttp3:okhttp:3.0.1 (*)
+--- com.squareup.retrofit2:retrofit:2.0.0-SNAPSHOT
|    \--- com.squareup.okhttp3:okhttp:3.0.1 (*)
+--- com.squareup.retrofit2:converter-moshi:2.0.0-SNAPSHOT
|    +--- com.squareup.retrofit2:retrofit:2.0.0-SNAPSHOT (*)
|    \--- com.squareup.moshi:moshi:1.0.0
|         \--- com.squareup.okio:okio:1.4.0 -> 1.6.0
+--- com.squareup.retrofit2:adapter-rxjava:2.0.0-SNAPSHOT
|    +--- com.squareup.retrofit2:retrofit:2.0.0-SNAPSHOT (*)
|    \--- io.reactivex:rxjava:1.1.0
+--- com.github.bumptech.glide:glide:4.0.0-SNAPSHOT
|    +--- com.github.bumptech.glide:gifdecoder:1.0.0-SNAPSHOT
|    |    \--- com.android.support:support-annotations:22.2.0 -> 23.1.1
|    \--- com.github.bumptech.glide:disklrucache:1.0.0-SNAPSHOT
+--- com.github.bumptech.glide:okhttp3-integration:2.0.0-SNAPSHOT
```

**Comment by floating-cat** [comment]
#897 hasn't update [MOCKWEBSERVER_VERSION](https://github.com/bumptech/glide/blob/a54f60fc48b8e5c012db7565575379b07ff17f50/gradle.properties#L33) version (which depends on OkHttp 3.0.0-rc1).
Can that test dependency effects this issue? Though the dependency tree guiwro showed has no problem.

**Comment by TWiStErRob** [comment]
It shouldn't because that's only for that configuration, though I would have expected a test failure, likely nothing whose signature have changed is used in tests.

**Comment by guiwro** [comment]
Well, I cleaned the project and restarted Android Studio and now, it works well.
Sorry for the inconvenience.

**Comment by b95505017** [comment]
Oops I didn't notice `MOCKWEBSERVER_VERSION` sorry.
