### ISSUE TITLE
The same image URL, the browser can open, according to glide can't display, application uninstall reshipment can show, why?

### ISSUE THREAD

**Issue by Apples0609** [bumptech/glide#901]
The same image URL, the browser can open, according to glide can't display, application uninstall reshipment can show, why???

To do this:
Glide.with(context).load(url).placeholder(R.drawable.ic_gridview_pic_placeholder).error(R.drawable.ic_gridview_pic_placeholder).diskCacheStrategy(DiskCacheStrategy.SOURCE).crossFade().into(imageView);

**Comment by TWiStErRob** [comment]
Please provide more information, you can find a [template here](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues).

**Comment by Apples0609** [comment]
Similar the link：
http://image.xingzhe01.com/logPic/2016-01-18/53ba411446154eac90843d449f3b66c6.jpg-200x200

The same code was originally a mobile phone can be displayed, another can't display, after uninstall reinstall the application.This link will display.Not to uninstall remove - 200 x200 can display.
If the server problem, but it can show the same link on other phones, and uninstall reinstall can show?

I feel very confused，thanks

**Comment by TWiStErRob** [comment]
Hmm, so after reinstall it shows. That sounds like either a bad coincidence or you're having caching issues. Can you please check why the image is not loaded? See [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) for how to log it.

Also what is your Glide version?, do you use any customizations (GlideModule)?, or integration library?

**Comment by Apples0609** [comment]
**Glide 3.6.1**:
**Android 5.1（Can't display properly）**:
**Problem description as above↑↑↑**:

**Glide load line**:
Glide.with(Application.getAppContext()).load(url).placeholder(R.drawable.ic_placeholder).error(R.drawable.ic_placeholder).diskCacheStrategy(DiskCacheStrategy.SOURCE).crossFade().into(imageView);

**Layout XML**:
ImageView view = new ImageView(VoyagerApplication.getForegroundActivity());
view.setScaleType(ImageView.ScaleType.CENTER_CROP);
view.setLayoutParams(new AbsListView.LayoutParams(imageViewSize, imageViewSize));

**Stack trace / LogCat**:
There is no error log(┬＿┬)

**Comment by Apples0609** [comment]
@TWiStErRob
There is no customizations GlideModule，Pictures load using only the glide，Glide ersion Glide 3.6.1
thanks，Is the first time I use the Glide, is also curious only to come over to ask this question, this question after uninstall not found again。

**Comment by TWiStErRob** [comment]
By default logging is disabled in Glide. Copy the `LoggingListener` class from the wiki and add the code in the comment just before the class between: `.crossFade()` and `.into(`. Then check LogCat.

**Comment by Apples0609** [comment]
@TWiStErRob
I try, thank you for your answer

**Comment by Apples0609** [comment]
@TWiStErRob 
Thank you, I found why happen this problem, the following
Because I upload image upload is asynchronous background, when I add the log into the log details, pictures are still in the upload process at the time, so the server didn't get to return the placeholder image picture, cause I thought there was a problem.
Even if the image upload completed under this mechanism, because this bad links have access to the images, so have a cache, also cannot show that display images, so just need to clear the cache can display.Once again thank you for your patience to answer!
谢谢#^_^#

**Comment by TWiStErRob** [comment]
Look into the signature API and Cache invalidation on the wiki. You can save clearing the whole cache and just "clear" that single image that had was bad.
