### ISSUE TITLE
How can i get the size of the image ?

### ISSUE THREAD

**Issue by Fornow** [bumptech/glide#904]
when i use glide to load image, i use `.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)` to get the original image. 

my code is : 
```java
Glide.with(mContext)
    .load(url)
    .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
    .crossFade()
    .into(new SimpleTarget<GlideDrawable>() {
        @Override
        public void onResourceReady(GlideDrawable glideDrawable, GlideAnimation<? super GlideDrawable> glideAnimation) {
            int width = glideDrawable.getIntrinsicWidth();
            int height = glideDrawable.getIntrinsicHeight();
            viewHolder.image1.setImageDrawable(glideDrawable);
        }
    });
```

but the size is incorrect.
then how can i get the correct size of the image?

**Comment by TWiStErRob** [comment]
See #781.

**Comment by Fornow** [comment]
Ok, Thank you very much!

**Comment by dy60420667** [comment]
Glide.with(mContext)
    .load(url)
    .override(screenWidth,screenHeight)
    .crossFade()
    .into(new SimpleTarget<GlideDrawable>() {
        @Override
        public void onResourceReady(GlideDrawable glideDrawable, GlideAnimation<? super GlideDrawable> glideAnimation) {
            int width = glideDrawable.getIntrinsicWidth();
            int height = glideDrawable.getIntrinsicHeight();
            viewHolder.image1.setImageDrawable(glideDrawable);
        }
    });

**Comment by thundertrick** [comment]
For Glide v4:

```
Glide.with(mContainer.getContext().getApplicationContext())
                .asBitmap()
                .load(path)
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap bitmap,
                                                Transition<? super Bitmap> transition) {
                        int w = bitmap.getWidth();
                        int h = bitmap.getHeight()
                        mImageView.setImageBitmap(bitmap);
                    }
                });
```

**Comment by ashadnasim52** [comment]
@thundertrick  where your variable w and h had been used

**Comment by thundertrick** [comment]
> @thundertrick where your variable w and h had been used

`w` and `h` are the size of the original bitmap.

However, this might not be the best solution, because the original bitmap is set into the view, which might cost too much space. See more on my [StackOverFlow answer](https://stackoverflow.com/questions/47827015/how-to-get-original-image-size-by-using-glide-on-android/48554994#48554994), the first comment point out this problem.

The best solution might be create a custom `ModelLoader` or sth like that, which can make full use of the optimization inside Glide.

Hope it helps.

**Comment by TWiStErRob** [comment]
@thundertrick

> The best solution might be create a custom ModelLoader or sth like that, which can make full use of the optimization inside Glide.

Exactly what's in #781. Note that loading the bitmap to get the size is very inefficient. Think about image formats. Loading a 3MB JPEG decoded as 20MB of `Bitmap` just to read the size and then throw away. The first 100-ish bytes contains the size of the full image, so it's a pretty low-resource solution to read that with `inJustDecodeBounds`; and file format differences are handled for you by Android.

@dy60420667 if you add `.override(screenWidth,screenHeight)` then `getIntrinsicWidth` will give you the same numbers.

**Comment by rajumark** [comment]
@thundertrick

**Comment by gordonfreemanix** [comment]
> @thundertrick
> 
> > The best solution might be create a custom ModelLoader or sth like that, which can make full use of the optimization inside Glide.
> 
> Exactly what's in #781. Note that loading the bitmap to get the size is very inefficient. Think about image formats. Loading a 3MB JPEG decoded as 20MB of `Bitmap` just to read the size and then throw away; that's a lot of unnecessary Fourier transformations. The first 100-ish bytes contains the size of the full image (in header / EXIF), so it's a pretty low-resource solution to read that with `inJustDecodeBounds`; and file format differences are handled for you by Android.
> 
> @dy60420667 if you add `.override(screenWidth,screenHeight)` then `getIntrinsicWidth` will give you the same numbers.

Please help me. I could not
