### ISSUE TITLE
RecyclerView+staggeredgridlayout+glide

### ISSUE THREAD

**Issue by 80998062** [bumptech/glide#907]
I know it is a little bit duplicated to some other questions here, but after checking out them, I still can't figure out a way to build a Pinterest-like UI using a 2 columns recyclerView + StaggeredGridLayout with Glide.

So any help will save my day T^T

I know Glide can't work well with a dynamic height (even I make the card's width `MATCH_PARENT` or a **fixed width**: screenWidth-space)

And I had one solution like this:

``` java
    if (shotRatioArray.get(position) == null) {
        Glide.with(mContext).load(imageUrl)
                .dontAnimate()
                .priority(Priority.IMMEDIATE)
                .into(holder.shot)
                .getSize(new SizeReadyCallback() {
                    @Override
                    public void onSizeReady(int width, int height) {
                        float ratio = ImageResizer.getSuitableRatio(width, height, mContext);
                        final int suitableWidth = (AnimUtils.getScreenWidth(mContext) - DensityUtils.dp2px(mContext, 16)) / 2;
                        FrameLayout.LayoutParams lps = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, (int) (suitableWidth * ratio));
                        holder.shot.setLayoutParams(lps);
                        shotRatioArray.put(position, ratio);
                    }
                });

    } else {
        Glide.with(mContext).load(imageUrl)
                .asBitmap()
                .dontAnimate()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .priority(Priority.IMMEDIATE)
                .into(new SimpleTarget<Bitmap>(suitableWidth, (int) (shotRatioArray.get(position) * suitableWidth)) {
                    @Override
                    public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                        // Do something with bitmap here.
                        assert holder.shot != null;
                        holder.shot.setImageBitmap(bitmap);
                    }
                });
    }
```

I try to **keep the image's ratio (W/H) after first loading** so that I can use a fixed height and width when the image is recycled.But in this way,once I set the ImageView's layoutparams,it seems eh...won't change any more (if I don't do that , how can I make the ImageView a proximate size on the  first loading).

Besides,there are many strange animation during the scrolling , just like the ImageView are relayout... 

And another question is I don't konw the sizeCallback take how much time , as long as downloading a full-size image? And in this way , during the recycling from bitmap pool, does Glide have resize a full size image into my fixed size? If so, that will be really inefficient...

Anyway if you have your better solution just tell me,I'll be very grateful for. Now I am all at a mess and don't konw what to do...

**Comment by TWiStErRob** [comment]
With getSize you're measuring `holder.shot` not the bitmap. The only way I'm aware that staggered grids work well is to use `override()`. To hit the caches Glide needs to receive the same w/h over and over again, not the size left by the previously loaded image. You may have better results if you save the size into `shotRatioArray` when the current item is recycled.

I think your only savior here is to know the sizes beforehand and pre-size the `ImageView`s. With SOURCE cache it should be fairly fast to use #781 to measure the bitmap in the file first and then load it.

I would also suggest to ask those people in other issues how they solved it, because I myself didn't try Glide + staggered yet.
