### ISSUE TITLE
Loading and decrypting image

### ISSUE THREAD

**Issue by j-garin** [bumptech/glide#912]
hello.

I have to load images from multiple sources. i want to use glide + okhttp, with okhttp taking care of auth headers and decrypting received data.
so i have a OkHttpClient which i use to get OkHttpUrlLoader. where do i go from here? how can i get glide to use it?
I've found OkHttpGlideModule here https://github.com/bumptech/glide/blob/master/integration/okhttp/src/main/java/com/bumptech/glide/integration/okhttp/OkHttpGlideModule.java but manual or docs on how it can be used. please help

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Configuration
https://github.com/bumptech/glide/wiki/Integration-Libraries#okhttp

**Comment by j-garin** [comment]
thank you for swift reply.
i've completed the steps from Integration-Libraries link and Configuration.
how do i use the modules i've created? how can i choose the module to use?

**Comment by TWiStErRob** [comment]
Configuration wiki says:
> Finally add a meta-data tag to your AndroidManifest.xml file so Glide can find your module

I think this is the step you're looking for.

After that's done, just do the usual `Glide.with...` and your module(s) will be initialised on the first such call.

**Comment by j-garin** [comment]
is there a way to pass parameters to that module? i need different headers for different urls, so i want to configure okhttp for each image load.
also if i reconfigure okhttp while other image is downloading, will that download fail?

**Comment by TWiStErRob** [comment]
You shouldn't reconfigure. Check out `GlideUrl` constructor for localised headers. Use `LazyHeaders.Builder` for dynamic headers.

**Comment by j-garin** [comment]
Thank you very much. That works for me.
One more issue is decrypting image data. The images i load are encrypted with different keys. What is the best way to decrypt data 'on the fly'? Is there a way to intercept byte[] data, decrypt it and then let Glide do the rest?

**Comment by TWiStErRob** [comment]
You can try providing an `.asBitmap().imageDecoder()` which wraps a built-in `StreamBitmapDecoder`. Just wrap the stream with a decoding stream and pass it on.

If the response headers contain the key you can also try overriding behavior in OkhttpUrlLoader.

**Comment by j-garin** [comment]
i'm not sure what exactly you mean when you say that. can you please give
me some reference code?
i'm new with Glide and haven't figured out how it works yet. sorry to keep
asking silly questions.

will something like this work?

Glide.with(context).load(glideUrl).asBitmap().imageDecoder(new
ResourceDecoder<InputStream, Bitmap>() {
    @Override
    public Resource<Bitmap> decode(InputStream source, int width, int
height) throws IOException {
        BufferedInputStream inputStream = new BufferedInputStream(source);
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        byte[] buffer = new byte[4096];
        int count;
        while((count = inputStream.read(buffer)) > -1) {
            outputStream.write(buffer, 0, count);
        }
        byte[] data = outputStream.toByteArray();

        byte[] decryptedData = CryptLib.decode(data);
        Bitmap bitmap = BitmapFactory.decodeByteArray(decryptedData, 0
,decryptedData.length);
        BitmapPool pool = ???
        Resource<Bitmap> resource = new BitmapResource(bitmap, pool);
        inputStream.close();
        outputStream.close();
        return resource;
    }

    @Override
    public String getId() {
        return null;
    }
}).into(imageView);



2016-01-20 16:09 GMT+02:00 Róbert Papp <notifications@github.com>:

**Comment by TWiStErRob** [comment]
Yes, something like this.
```java
BitmapPool pool = Glide.get(context).getBitmapPool();
BitmapResource.obtain(bitmap, pool);
```

The biggest problem is that you're decoding the image yourself losing most of what Glide has to offer. Consider this:
```java
// ... your decryptor until decryptedData
outputStream.close();
// don't close inputStream, because it closes source; that is handled by Glide
source = new ByteArrayInputStream(decryptedData);
return new StreamBitmapDecoder(context).decode(source);
```

Just noticed your PS, isn't there way to wrap an input stream like you did with buffered, but one which decrypts on the fly? That would prevent from having 2x size of the source image in memory.
```java
source = new DecryptingInputStream(key, source);
return new StreamBitmapDecoder(context).decode(source);
```

You said they use different keys, I don't see that here.

**Comment by j-garin** [comment]
thank you. 
i want to use this:
                source = new DecryptingInputStream(aesEncryptionKey, iv, source);
                return new StreamBitmapDecoder(context).decode(source);
but the problem is that decode() requires width and height which i don't have when i call Glide. is there any way to make Glide do the measuring for me?

**Comment by TWiStErRob** [comment]
You get a `width` and `height` in your wrapping `ResourceDecoder`, pass that on.

**Comment by j-garin** [comment]
Thank you so much!

**Comment by j-garin** [comment]
I finally tested the code and decrypting doesn't work. I have tested my decryptor with the test file, all OK.
Could it be that .asBitmap() modifies the inputStream data before i attempt to decrypt it?

**Comment by TWiStErRob** [comment]
Which interface is the decrypting in? What's your cache strategy?

**Comment by j-garin** [comment]
here's the complete code

```
       Glide.with(context)
                .load(glideUrl)
                .asBitmap()
                .imageDecoder(new ResourceDecoder<InputStream, Bitmap>() {
                    @Override
                    public Resource<Bitmap> decode(InputStream source, int width, int height) throws IOException {
                        if (aesEncryptionKey.isEmpty()) {
                            return new StreamBitmapDecoder(context).decode(source, width, height);
                        }

                        BufferedInputStream inputStream = new BufferedInputStream(source);
                        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                        byte[] buffer = new byte[4096];
                        int count;
                        while ((count = inputStream.read(buffer)) > -1) {
                            outputStream.write(buffer, 0, count);
                        }
                        byte[] data = outputStream.toByteArray();

                        try {
                            byte[] decryptedData = new CryptLib(256).decrypt(data, aesEncryptionKey, iv);
                            source = new ByteArrayInputStream(decryptedData);
                        } catch (InvalidKeyException e) {
                            e.printStackTrace();
                        } catch (InvalidAlgorithmParameterException e) {
                            e.printStackTrace();
                        } catch (IllegalBlockSizeException e) {
                            e.printStackTrace();
                        } catch (BadPaddingException e) {
                            e.printStackTrace();
                        } catch (NoSuchAlgorithmException e) {
                            e.printStackTrace();
                        } catch (NoSuchPaddingException e) {
                            e.printStackTrace();
                        }
                        outputStream.close();

                        return new StreamBitmapDecoder(context).decode(source, width, height);
                    }

                    @Override
                    public String getId() {
                        return null;
                    }
                })
                .centerCrop()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(imageView);
```

**Comment by TWiStErRob** [comment]
It likely fails when it reads the cache, because those use different decoders, try setting `sourceDecoder` as well: extract this anonymous inner class to `DecryptingDecoder` and use it like this:
```java
.imageDecoder(new DecryptingDecoder(context, aesEncryptionKey))
.cacheDecoder(new FileToStreamDecoder<Bitmap>(new DecryptingDecoder(context, aesEncryptionKey)))
.diskCacheStrategy(DiskCacheStrategy.SOURCE)
```
You can't use RESULT cache in this case: #707, you can work around that by adding `.encoder(new EncryptingEncoder(context, aesEncryptionKey))` and implementing that class based on `BitmapEncoder`.

Minor tips:
 * Put a log line in each of these classes to be sure they were invoked.
 * Don't return `null` from `getId`, if you must, use `""`; but it's better to return the class name so Glide knows it was involved in the load.
 * move `new StreamBitmapDecoder(context)` to be a field, no need to create a new object every time, because it's stateless

**Comment by j-garin** [comment]
could you please explain the code a little? i can't understand how this thing works and should work. thank you.

**Comment by TWiStErRob** [comment]
Take a look at this first: https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g

**Comment by j-garin** [comment]
Thank you very much. Issue solved.
I love Glide support!

**Comment by BenjiProgramming** [comment]
I have same problem
