### ISSUE TITLE
I can't load image with postfix like http://a.png@750w_1l.src

### ISSUE THREAD

**Issue by tinybright** [bumptech/glide#918]
Glide loades http://a.png when I want it to load http://a.png@750w_1l.src

**Comment by TWiStErRob** [comment]
Can you please write a more real life example? Your second example is not a valid URL. Consider the conflict with: `http://user@host/path`

**Comment by TWiStErRob** [comment]
Also please include any exceptions or logs that are relevant using the tools at https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
