### ISSUE TITLE
donanimate() only if there was a thumbnail

### ISSUE THREAD

**Issue by jush** [bumptech/glide#919]
I have the following code:
```
imageInformationRequest.load(imageInformation)
                        .dontAnimate()
                        .thumbnail(thumbnailPictureRequest.load(imageInformation).override(width / 2, height / 2))
                        .override(width, height)
                        .placeholder(R.color.transparent)
                        .into(pictureOrMap);
```

I added the `dontAnimate()` in order to avoid the cross fading between the thumbnail and the final image but I would like the cross fading to still happen if the final image loads before the thumbnail.

So the behaviour would be, in case thumbnail is shown:
 1. Thumbnail is shown with nice cross fade
 2. Load the final image without any animation.

and in case final image is ready before thumbnail (happens when final image is in memory):
 1. Load final image with cross fade
 2. Thumbnail is not shown at all

**Comment by TWiStErRob** [comment]
Cross-fade implies there are two things to fade between.
What you want is likely achieved with `.animate(android.R.anim.fade_in)` (or `R.anim.abc_fade_in`).
Please try how that works for you and then re-think your quesiton.

**Comment by TWiStErRob** [comment]
Here's a trick I use to simulate loading images on "slow network":
(can be applied to both main and thumb request separately)
```java
.skipMemoryCache(true)
.diskCacheStrategy(SOURCE)
.transform(new DelayTransformation(2000), new CenterCrop(context))

public class DelayTransformation extends BitmapTransformation {
	private final int delay;
	public DelayTransformation(int delay) { super((BitmapPool)null); this.delay = delay; }
	@Override protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int w, int h) {
		try {
			Thread.sleep(delay);
		} catch (InterruptedException e) {
			Log.i("DELAY", "Sleeping for " + delay + "ms was interrupted.", e);
		}
		return toTransform;
	}
	@Override public String getId() { return ""; }
}
```

**Comment by jush** [comment]
Thanks a lot for your quick response.
That was indeed what I was looking for.
