### ISSUE TITLE
Image flickering 

### ISSUE THREAD

**Issue by ghost** [bumptech/glide#92]
I'm using Parse.com as a backend service and Picasso to load images. 

Today I heard about Glide and I wanted to give it a try. It's true that scrolling is smoother, but I'm facing an annoying issue: When updating the listview, images flicker two or three times. I faced the same issue with Universal Image Loader but with Picasso it works great. 

Any ideas how I can fix this. Thanks

**Comment by nawinkhatiwada** [comment]
Hey, guys! anybody found the solution regarding flickering? I am also having the same issue during loading GIF image
