### ISSUE TITLE
 GC_FOR_ALLOC is triggered every 1 second though I still on one page.

### ISSUE THREAD

**Issue by tinybright** [bumptech/glide#923]
>01-25 12:03:01.007 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8191K, 27% free 45491K/62120K, paused 71ms, total 71ms
01-25 12:03:01.796 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8190K, 27% free 45493K/62120K, paused 85ms, total 85ms
01-25 12:03:02.577 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8191K, 27% free 45494K/62120K, paused 97ms, total 97ms
01-25 12:03:03.333 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8191K, 27% free 45494K/62120K, paused 69ms, total 69ms
01-25 12:03:04.099 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8191K, 27% free 45494K/62120K, paused 80ms, total 80ms
01-25 12:03:04.885 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8194K, 27% free 45492K/62120K, paused 61ms, total 61ms
01-25 12:03:05.656 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8191K, 27% free 45492K/62120K, paused 83ms, total 83ms
01-25 12:03:06.412 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8194K, 27% free 45489K/62120K, paused 72ms, total 73ms
01-25 12:03:07.166 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8191K, 27% free 45490K/62120K, paused 74ms, total 74ms
01-25 12:03:07.943 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8188K, 27% free 45493K/62120K, paused 80ms, total 80ms
01-25 12:03:08.692 22923-22923/com.airi.im.ace D/dalvikvm: GC_FOR_ALLOC freed 8191K, 27% free 45494K/62120K, paused 60ms, total 60ms

The  GC_FOR_ALLOC is triggered though I was still on one page.What should I do?Do I need to increase  MemoryCache?

**Comment by TWiStErRob** [comment]
Please give more info: https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues

Other than filling in the template also include what are you doing to the app when this happens.

**Comment by TWiStErRob** [comment]
What was the problem?

**Comment by tinybright** [comment]
I didn't add skipMemoryCache(true). And When I load too many bitmaps, MemoryCache is Full.MemoryCache  recycled  some bitmap and load new bitmap.I think I need to allow large MemoryCache.
