### ISSUE TITLE
what about the proguard rules?

### ISSUE THREAD

**Issue by a1018875550** [bumptech/glide#924]
I want to proguard my project,But i don't the rules about glide...
Coulue please the proguard rules about glide;Thank you very much

**Comment by eliomwang** [comment]
I think you can find what you need here:
https://github.com/bumptech/glide#proguard

**Comment by a1018875550** [comment]
than you very much

**Comment by TWiStErRob** [comment]
Thanks @eliomwang, that's enough to make it work.

There're some more details on the following pages:
 * https://github.com/bumptech/glide/wiki/Configuration#creating-a-glidemodule
 * https://github.com/bumptech/glide/wiki/Integration-Libraries (seach for proguard)
if someone is interested in the background of why.

**Comment by gajicm93** [comment]
@TWiStErRob @sjudd ProGuard rules in the readme file haven't been updated with the ones from: https://github.com/bumptech/glide/blob/master/library/proguard-rules.txt

Specifically, yesterday I had a crash because I was missing
`-keep class com.bumptech.glide.load.data.ParcelFileDescriptorRewinder$InternalRewinder {
  *** rewind();
}`
and eventually found in the file above instead in the readme.

**Comment by TWiStErRob** [comment]
@gajicm93 Hmm, the readme is indeed outdated, but because you don't (shouldn't) need to configure anything:
https://github.com/bumptech/glide/blob/fb672a54e11739454f34430f856a9eeb2ea0244f/library/build.gradle#L42

How are you using Glide in your build.gradle?

**Comment by gajicm93** [comment]
@TWiStErRob I'm using it like this:

```
implementation "com.github.bumptech.glide:glide:$glideVersion"
kapt "com.github.bumptech.glide:compiler:$glideVersion"
implementation "com.github.bumptech.glide:okhttp3-integration:$glideVersion"
```

I'm also using latest version of R8 in full mode.

My build type is like this:

```
release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
```

And app was crashing on 4.4 until I manually updated ProGuard rules in my rules file.
