### ISSUE TITLE
Glide thread consumption across multiple devices.

### ISSUE THREAD

**Issue by chainani** [bumptech/glide#925]
I just integrated facebook stetho into my app for analysis  by passing in a networkInterceptor into the okhttp client that i pass into my glide module. While monitoring network requests I realised that a moto G(1st gen) made 4 network requests at a time, subsequent requests had to wait before being serviced. In case of the Samsung Galaxy Grand 2, Xiaomi mi4 and various other devices 10+ network requests were being serviced parallely. I don't know if this is a glide issue or an okhttp issue or a motorolla issue or if its an issue at all. Some quick googleing has revealed that okhttp assigns the maximum possible number of threads and lets up only after the request finishes. I was wondering if someone could explain how these threads are allocated?

**Comment by TWiStErRob** [comment]
I'm not sure if you're going for lower or higher thread count.

I can only vouch for v3, where Glide has a hard limit on threads in [`GlideBuilder`](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L170):

and all the networking libraries are queried synchronously. Even if you set the thread count [using a `GlideModule`](https://github.com/bumptech/glide/wiki/Configuration) as you say OkHTTP may also have limits, which you can set using the custom client that you likely already use.

All I know is that v4 changed the network integration layer interface to be able to make async requests and uses [a more sophisticated algorithm](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java#L169) for thread count. Unsure how that affects the number of parallel requests made.

**Comment by chainani** [comment]
thanks... I looked at my traces and it makes more sense. Another Slightly off topic question but i'm loading my images using .with(Fragment) when I leave the fragment, the network calls don't get canceled if they were already dispatched. They don't load in the imageview, but I can see them finishing. Is this by design? Is v4 going to fix this?

**Comment by TWiStErRob** [comment]
`DataFetcher.cancel` is called, but as I said okhttp2 <2.7 can't cancel them (that method is just a TODO comment) because it's called from the UI thread, try with `okhttp3-integration:1.4.0` (released yesterday).

**Comment by chainani** [comment]
Thanks! Thats an awesome coincidence!

**Comment by TWiStErRob** [comment]
Did it cancel properly with the new version as you expected?

**Comment by chainani** [comment]
haven't tried it yet... I'll be integrating it tomorrow... I'll keep you posted...

**Comment by chainani** [comment]
hey @TWiStErRob do you know why i cant find okHttpURLLoader in integration.okhttp3?

**Comment by TWiStErRob** [comment]
It's there in the source tree: https://github.com/bumptech/glide/tree/3.0/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3

**Comment by chainani** [comment]
I did see that... I'm importing through gradle... any new proguard-rules i need to add?

**Comment by TWiStErRob** [comment]
Not aware of any new ones. Our okhttp3 lib is just a copy of okhttp2 lib and minor fixes. Clean build? How do you know it's not there? compile? proguard error? runtime?

**Comment by chainani** [comment]
compile error... 
are these correct?

    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'

**Comment by TWiStErRob** [comment]
Yes, and you need `okhttp3:3.0.1` and maybe you need to change the package in proguard for `OkHttpGlideModule` unless you used the `? extends` version.

**Comment by chainani** [comment]
i did use the generic one and i do have that version of okhttp

**Comment by TWiStErRob** [comment]
Then what's the literal error, or did you try a clean build? Are your imports correct for that class?

**Comment by chainani** [comment]
wait no... it went away... Thanks for the help... Clean Build worked...
