### ISSUE TITLE
Android_Client

### ISSUE THREAD

**Issue by l756302098** [bumptech/glide#929]
**Glide Version/Integration library (if any)**:
**Device/Android Version**:
**Issue details/Repro steps/Use case background**:

**Glide load line**:
```java
Glide.with(...).....load(...).....into(...);
```

**Layout XML**:
```xml
<...Layout>
    <ImageView android:scaleType="..." ... />
</..Layout>
```

**Stack trace / LogCat**:
```ruby
paste stack trace here
```

**Comment by TWiStErRob** [comment]
Did you forget to fill the template in? Just put the info after the colons (`:`) and replace the codes inside ```` ``` ````  with your own. You can edit your comments in the top right corner with the pencil.
