### ISSUE TITLE
A problem for Glide used for loading gif.

### ISSUE THREAD

**Issue by zhangshen023** [bumptech/glide#931]
I found a efficient image loader when i want to load gif.I was very happy because i think i can resolve my problem.But ....
Most of gifs can show correctly,but there is a gif not shown on image view. this is my gif.
i'm looking forward to problem getting resolved.
![chick](https://cloud.githubusercontent.com/assets/12484497/12606147/f892aac2-c505-11e5-8b73-12f55bfd34e6.gif)

**Comment by TWiStErRob** [comment]
This looks the same as #836. Please go to that issue and press the Subscribe button on the right.
