### ISSUE TITLE
How to use glide to bind the picture address data in XML

### ISSUE THREAD

**Issue by fg2q1q3q** [bumptech/glide#932]
I used databinding in my project, from Google Docs to understand in the XML configuration pictures address automatic loading pictures can be realized through `@BindingAdapter`. See `ImageLoaderUtils` can be achieved, as shown in the following code, but due to the context of glide each initialization, however there does not exist the parameters，what should I do?

```java
public class Utils {
    @BindingAdapter({"bind:image"})
    public static void imageLoader(ImageView imageView, String url) {
        //How to replace the Glide
        ImageLoaderUtils.getInstance().displayImage(url, imageView);
    }
}
```

**Comment by TWiStErRob** [comment]
```java
Glide.with(imageView.getContext()).load(url).into(imageView)
```

But I would suggest to look into passing an extra argument to that method somehow, either one of these: `RequestManager`, `GenericRequestBuilder<String, ?, ?, ?>`. That way the caller can decide about lifecycle, placeholder, transformations, animations, etc. See this method chain for example: `req = Glide.with.fromString.placeholder` and then inside the method just `req.load.into`.
