### ISSUE TITLE
4.0.0-SNAPSHOT: Unhandled class "java.io.File"

### ISSUE THREAD

**Issue by aurae** [bumptech/glide#933]
In the latest 4.0.0-SNAPSHOT, loading a resource using the built-in `RequestBuilder<File>` raises the following exception:

```java
java.lang.IllegalArgumentException: Unhandled class: class java.io.File, try .as*(Class).transcode(ResourceTranscoder)
	at com.bumptech.glide.request.target.ImageViewTargetFactory.buildTarget(ImageViewTargetFactory.java:20)
	at com.bumptech.glide.GlideContext.buildImageViewTarget(GlideContext.java:51)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:407)
	at my.package.SomeActivity.onCreate(SomeActivity.java:30)
```

Here's a minimal example:

```java
public class SomeActivity extends AppCompatActivity {

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		ImageView iv = (ImageView) findViewById(R.id.iv);
		// Just an example path here
		Glide.with(this).asFile().load(new File("/storage/emulated/0/Download/D04.png")).into(iv);
	}
}
```

**Comment by TWiStErRob** [comment]
What are you trying to achieve here?
Your line reads "load a File as a File into an ImageView".

**Comment by aurae** [comment]
I misunderstood the `asXYZ()` syntax of 4.0.0 to have an impact on the argument being passed into `load()`. Using `asBitmap()`, this obviously works as intended. Sorry!

**Comment by TWiStErRob** [comment]
Glide v4 removes any limitations on the input via generic arguments. The only generic argument is what the target is able to consume. This allows you to create a request that can load anything as long as it's convertible into what the target expects. This means there should be no `from*()` APIs, only `as*()`.
