### ISSUE TITLE
use glide to load local files include directory of assets ect.

### ISSUE THREAD

**Issue by yummyChina** [bumptech/glide#934]
I'm a newer of android developer,when I use api to load picture resources below the directory of assets like:
```java
String asseturl ="assets/demo1.jpg";
Glide.with(context).load(asseturl)....
Glide.with(context).load(new File(asseturl))....
Glide.with(context).load(Uri.fromFile(new File(asseturl))))....
```
not working any code . Please help me.

**Comment by yummyChina** [comment]
I've resolved it by use the absolute path of the image file like:
String asseturl = "file:///android_assert/demo1.jpg"
Glide.with(context).load(asserturl)......
That's mean the Glide just load resource by absolute path,right?

**Comment by TWiStErRob** [comment]
That folder is a virtual folder, it doesn't exist really. Each application sees different contents in that folder what was packaged from their `src/main/assets`.

For any relative path to work you would need to have a base path that is absolute. This is usually hidden as the working directory (pwd/cwd). In Android there isn't really a working directory concept for the apps, so you'll always need absolute paths, but this doesn't mean that you can't use relative paths in your code, just use `Context.get*Dir`, `Environment` and `new File(File, String)` to construct absolute paths from relative ones.
