### ISSUE TITLE
Image is Not Loding in Viewpager Custom Adapter

### ISSUE THREAD

**Issue by Tufan21** [bumptech/glide#935]
i am using Glide Version compile **'com.github.bumptech.glide:glide:3.6.1'** and  this code to display images 

```java
public class ViewPagerAdapter extends PagerAdapter {
   String[] galleryImages;
    Context mContext;
    public ViewPagerAdapter(Context mContext, String[] images) {
        super();
        this.galleryImages = images;
        this.mContext=mContext;
    }
    @SuppressLint("NewApi")
    @Override
    public void finishUpdate(ViewGroup container) {
        super.finishUpdate(container);
    }

    @Override
    public int getCount() {
        return galleryImages.length;
    }
    @Override
    public boolean isViewFromObject(View collection, Object object) {
        return collection == ((View) object);
    }

    @Override
    public Object instantiateItem(ViewGroup  collection, int position) {
        LayoutInflater inflater = (LayoutInflater) collection.getContext()
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        View view = inflater.inflate(R.layout.poduct_child_tems, null);
        ImageView imageView = (ImageView) view.findViewById(R.id.imageViewmain);
        try {
            Glide.with(mContext)
                    .load(galleryImages[position])
                    .error(R.drawable.default_hotel_image)
                    .into(imageView);
        } catch (Exception e1) {
            e1.printStackTrace();
        }
        ((ViewPager) collection).addView(view, 0);
        return view;
    }

    @Override
    public void destroyItem(View collection, int position, Object view) {
        ((ViewPager) collection).removeView((View) view);
    }   
}
```
i checked image URL is proper ..there is no issue with URL..it is loading in browser

actualy main problem i doesn't understand **1st image is loaded for for other my default image appear**

i checked my adapter code there is no issue

**Comment by Tufan21** [comment]
some url of mine are 
http://cdn.travelpartnerweb.com/DesiyaImages/Image/3/nxd/maw/tyk/fbr/0000010909RD.jpg
http://cdn.travelpartnerweb.com/DesiyaImages/Image/3/nxd/maw/tyk/fbr/0000010910RD.jpg
http://cdn.travelpartnerweb.com/DesiyaImages/Image/3/nxd/maw/tyk/fbr/HA.jpg
http://cdn.travelpartnerweb.com/DesiyaImages/Image/3/nxd/maw/tyk/fbr/0000010909RD.jpg
http://cdn.travelpartnerweb.com/DesiyaImages/Image/3/nxd/maw/tyk/fbr/0000010910RD.jpg
http://cdn.travelpartnerweb.com/DesiyaImages/Image/3/nxd/maw/tyk/fbr/0000010908RD.jpg
http://cdn.travelpartnerweb.com/DesiyaImages/Image/1/nxd/maw/tyk/fbr/0000057424RD.jpg
http://cdn.travelpartnerweb.com/DesiyaImages/Image/1/nxd/maw/tyk/fbr/0000057423RD.jpg

**Comment by TWiStErRob** [comment]
Can you share your adapter? These URLs look normal.
What is your `ImageView`'s class? Is it stock?
Also try these techniques to see what's going on: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
What is the return type of `getHotelImages()`? I looks like a list...

**Comment by Tufan21** [comment]
yes it is returning image url as a string ...and imageview is a default imageview no library used

**Comment by TWiStErRob** [comment]
That looks ok, but here are 3 things you might want to consider:

 * Don't insert the item at the first position, just add it and let the ViewPager figure it out: `collection.addView(view);`. It's possible there's something messed up if you always insert at 0 position.

 * Always use parent if available for inflate:

 	```java
 	inflater.inflate(R.layout.poduct_child_tems, collection, false);
 	```
    Read https://possiblemobile.com/2013/05/layout-inflation-as-intended/, twice ;)

 * Use the non-deprecated version:

    ```java
	@Override public void destroyItem(ViewGroup container, int position, Object object) {
	    container.removeView((View)object);
	}
	```

If these don't help, which is likely, did you see anything meaningful with logging?

**Comment by Tufan21** [comment]
that is not issue if i put this on anything like recylerview custom adapter ..image was coming from a mili seconf and again disappear
