### ISSUE TITLE
how to set image in background of image view

### ISSUE THREAD

**Issue by saeed-zh** [bumptech/glide#938]
Excuse me If this question is duplicate, i can not find solution in issues. I want to set Image to background.

![capture](https://cloud.githubusercontent.com/assets/13766432/12643110/5cfce378-c5cf-11e5-9208-a2d26fca001d.PNG)

**Comment by TWiStErRob** [comment]
Yep, I found no proper solution to that, only hacky versions of `SimpleTarget`.

Here is how I would do it:
```java
....fitCenter().into(new GlideDrawableViewBackgroundTarget(view));
```
Notice that it works with any View not just ImageView and that you need to explicity set the transformation (fitCenter/centerCrop).

The following classes are untested, but they compile. Trivial methods collapsed for brevity, IDE auto-format will take care of it anyway that when you copy them.
```java
/** @see ImageViewTarget */
public abstract class ViewBackgroundTarget<Z> extends ViewTarget<View, Z> implements GlideAnimation.ViewAdapter {
     public ViewBackgroundTarget(View view) { super(view); }
     @Override public void onLoadCleared(Drawable placeholder) { setBackground(placeholder); }
     @Override public void onLoadStarted(Drawable placeholder) { setBackground(placeholder); }
     @Override public void onLoadFailed(Exception e, Drawable errorDrawable) { setBackground(errorDrawable); }
     @Override public void onResourceReady(Z resource, GlideAnimation<? super Z> glideAnimation) {
          if (glideAnimation == null || !glideAnimation.animate(resource, this)) {
               setResource(resource);
          }
     }
     @Override public void setDrawable(Drawable drawable) { setBackground(drawable); }
     @Override public Drawable getCurrentDrawable() { return view.getBackground(); }

     @SuppressWarnings("deprecation")
     protected void setBackground(Drawable drawable) {
          if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
               view.setBackground(drawable);
          } else {
               view.setBackgroundDrawable(drawable);
          }
     }

     protected abstract void setResource(Z resource);
}
```
and specializations to be used with `asBitmap`, default and GIF-compatible.
```java
/** @see BitmapImageViewTarget */
public class BitmapViewBackgroundTarget extends ViewBackgroundTarget<Bitmap> {
     public BitmapViewBackgroundTarget(View view) { super(view); }
     @Override protected void setResource(Bitmap resource) {
          setBackground(new BitmapDrawable(view.getResources(), resource));
     }
}

/** @see DrawableImageViewTarget */
public class DrawableViewBackgroundTarget extends ViewBackgroundTarget<Drawable> {
     public DrawableViewBackgroundTarget(View view) { super(view); }
     @Override protected void setResource(Drawable resource) { setBackground(resource); }
}

/** @see GlideDrawableImageViewTarget */
public class GlideDrawableViewBackgroundTarget extends ViewBackgroundTarget<GlideDrawable> {
     private int maxLoopCount;
     private GlideDrawable resource;
     public GlideDrawableViewBackgroundTarget(ImageView view) { this(view, GlideDrawable.LOOP_FOREVER); }
     public GlideDrawableViewBackgroundTarget(ImageView view, int maxLoopCount) {
          super(view);
          this.maxLoopCount = maxLoopCount;
     }

     @Override public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> animation) {
          super.onResourceReady(resource, animation);
          this.resource = resource;
          resource.setLoopCount(maxLoopCount);
          resource.start();
     }

     @Override protected void setResource(GlideDrawable resource) { setBackground(resource); }
     @Override public void onStart() { if (resource != null) { resource.start(); } }
     @Override public void onStop() { if (resource != null) { resource.stop(); } }
}
```

Let's leave this open, it's probably a good idea to have these classes in the library. What do you think @sjudd?

**Comment by TWiStErRob** [comment]
Please note that the following code won't work:
```java
Glide.with(this).load(url1).into(imageView);
Glide.with(this).load(url2).into(new GlideDrawableViewBackgroundTarget(imageView));
```
because the `ViewTarget`s store the request object in the same place, so one view - one load. Unless of course the `get/setRequest` is overridden to behave differently.

**Comment by saeed-zh** [comment]
Thank you for your attention, I add this classes to my project. but I confused, how can use this classes?

does GlideDrawableViewBackgroundTarget class works? (contradiction in your first comment and last one)

**Comment by TWiStErRob** [comment]
It just doesn't work if you load both to the background and to the foreground at the same time. For usage see the first line of code above.

**Comment by saeed-zh** [comment]
oh,  thanks, I just need to load image in background ;)

**Comment by saeed-zh** [comment]
image Quality is low, also it seems that I have memory leak, application consume about 6 MB for one picture.

picture when I manually set background
![capture](https://cloud.githubusercontent.com/assets/13766432/12646278/3b01a4ec-c5e4-11e5-8776-af2155e641d7.PNG)

picture when I use glide
![capture](https://cloud.githubusercontent.com/assets/13766432/12646001/e0c99260-c5e2-11e5-9f42-c76f08d982f2.PNG)

**Comment by saeed-zh** [comment]
application has low responsiveness after use this class

**Comment by TWiStErRob** [comment]
What is your XML for the view that you're loading into (share surrounding layers too)?

**Comment by saeed-zh** [comment]
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    card_view:cardCornerRadius="4dp"
    android:layout_marginLeft="10dp"
    android:layout_marginRight="10dp" >

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?android:attr/selectableItemBackground">

        <ImageView
            android:id="@+id/productImage"
            android:layout_width="match_parent"
            android:layout_height="150dp"
            android:contentDescription="@null"
            android:background="@drawable/a"/> 

        <uicomponents.TextView
            android:id="@+id/productName"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="15dp"
            android:text="نام محصول"
            app:v_styleId="@array/TextView_Large"
            android:shadowRadius="15"
            android:shadowColor="@color/TextView.Large.Default.Shadow"
            android:layout_alignBottom="@+id/productImage"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true" />

        <TableRow
            android:id="@+id/valueSummary"
            android:layout_width="match_parent"
            android:layout_height="40dp"
            android:orientation="horizontal"
            android:gravity="center_vertical"
            android:layout_below="@+id/productImage">

            <uicomponents.ValueTextView
                android:id="@+id/mainValue"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="10000"
                app:v_styleId="@array/TextView_Small"
                android:layout_marginLeft="10dp"
                android:layout_marginStart="10dp"
                android:layout_marginRight="20dp"
                android:layout_marginEnd="20dp"/>

            <uicomponents.ValueTextView
                android:id="@+id/offValue"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="6000"
                app:v_styleId="@array/TextView_Small"
                android:layout_marginRight="20dp"
                android:layout_marginEnd="20dp" />

            <uicomponents.TextView
                android:id="@+id/count"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="5"
                app:v_styleId="@array/TextView_Small"
                android:layout_marginRight="10dp"
                android:layout_marginEnd="10dp" />

            <uicomponents.TextView
                android:id="@+id/countUnit"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="DVD"
                app:v_styleId="@array/TextView_Small" />
        </TableRow>

        <TableLayout
            android:id="@+id/contactOptions"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:layout_below="@+id/valueSummary">

            <View
                android:layout_width="match_parent"
                android:layout_height="1dp"
                android:background="#589"/>


            <TableRow
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal">

                <uicomponents.Button
                    android:id="@+id/call"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="تماس"
                    android:layout_marginTop="2dp"
                    android:layout_marginRight="5dp"
                    android:layout_marginEnd="5dp"
                    app:v_styleId="@array/Button_Rectangle"/>

                <uicomponents.Button
                    android:id="@+id/email"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="ایمیل"
                    android:layout_marginTop="2dp"
                    app:v_styleId="@array/Button_Rectangle"/>
            </TableRow>
        </TableLayout>

    </RelativeLayout>

</android.support.v7.widget.CardView>

**Comment by saeed-zh** [comment]
if it's important, uicomponent.* is a extended classes from an material design library, just for custom font

**Comment by TWiStErRob** [comment]
The texts don't play here. So you're loading the image into `productImage`? Try to log the size of the image loaded into the view and the size of the view using a [`.listener()`](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) they should be close. The color difference is likely because Glide uses 565 Bitmaps by default, see [Configuration](https://github.com/bumptech/glide/wiki/Configuration#bitmap-format).

Hmm, why are you setting the background of the view if the view is an ImageView? You could just use the normal load...? If you really want to use background it would make more sense to move the `selectableItemBackground` to the CardView and set the background on the RelativeLayout so you can get rid of the ImageView.

**Comment by saeed-zh** [comment]
Relativelayout is child of cardView and is Parent of all other element, set background to RelativeLayout causes image height is bigger than what I want.

**Comment by TWiStErRob** [comment]
Ah, I see, but the other part still applies. You have an ImageView which doesn't have an image set, but has a background image. Are you planning to set something there? If not try using that and you won't need any of the above classes.

**Comment by saeed-zh** [comment]
I set background to it just for test image quality, in code I use glide for load main Image.

If I can change my imageView to RelativeLayout, my design remain fix, can I use glide to set fully width image to ralativelayout? if yes How?

**Comment by TWiStErRob** [comment]
I'm not sure I understand your question.... you can load the original sized image via `override(Target.SIZE_ORIGINAL)`. This applies to any load regardless of target.

**Comment by saeed-zh** [comment]
I pass RalativeLayout to "into" method and it is not acceptable. actually I want to achieve something like this, I want to image width be wrapped.

![layout-2016-01-28-182430](https://cloud.githubusercontent.com/assets/13766432/12647827/78af7438-c5ec-11e5-8529-6d8e465441f5.png)

**Comment by saeed-zh** [comment]
which View is better that either usable with glide and satisfy my goal

**Comment by TWiStErRob** [comment]
I think the best solution is to use an ImageView as usual, with a match_parent width. Glide will handle this best, as it was designed to do this.

**Comment by saeed-zh** [comment]
as you can see, ImageView's width is match_parent, but when image is load, it seems like the first picture that I upload in first comment

**Comment by saeed-zh** [comment]
I want to set Image to Background just for it's width. please give me a good solution

**Comment by TWiStErRob** [comment]
That's fitCenter (the default `android:scaleType`), if you want to distort and stretch, use fitXY. If you want to fill, but not distort, use centerCrop. Try them all to see the difference.

**Comment by saeed-zh** [comment]
finally it's works, thank you very much, with previous library classes, I haven't memory leak anymore.

**Comment by TWiStErRob** [comment]
@sjudd what do you think, should these classes go into the library?

**Comment by sjudd** [comment]
Into view backgrounds? That skews the image I think, because its always fitxy?

**Comment by TWiStErRob** [comment]
Hmm, that makes sense, it could be still useful for gradients or borders. I guess is so borderline that it's not worth the effort, also code is readily available above.
If anyone has a good use case feel free to comment here!

**Comment by sjudd** [comment]
Also to expand briefly: You can get a similar effect by using multiple views. The marginal loss in efficiency (if any) is probably substantially outweighed by ease of use/flexibility.

**Comment by strommj** [comment]
Sorry to bump an old thread, but I had a question regarding your comment here:

https://github.com/bumptech/glide/issues/938#issuecomment-176188172

My project has ImageView buttons that require a custom drawable loaded in the background and a separate drawable loaded into the foreground of the button.  In your comment you mention this cannot be done.  I'm wondering about more details on this?  Or should I pursue other libraries to obtain this functionality?

**Comment by chadmirror** [comment]
It would be nice if the official documentation had an example of how to do this.

I had to do some tweaking to update the code sample in this thread. This seems to work for me with Glide 4:

```
/** @see ImageViewTarget
 */
abstract class ViewBackgroundTarget<Z>(view: View) : CustomViewTarget<View?, Z>(view) {
    override fun onLoadFailed(errorDrawable: Drawable?) {
    }

    override fun onResourceCleared(placeholder: Drawable?) {
        view!!.background = placeholder
    }
}

/** @see BitmapImageViewTarget
 */
class BitmapViewBackgroundTarget(view: View) : ViewBackgroundTarget<Bitmap>(view) {
    override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
        view!!.background = BitmapDrawable(view.resources, resource)
    }
}

/** @see DrawableImageViewTarget
 */
class DrawableViewBackgroundTarget(view: View) : ViewBackgroundTarget<Drawable>(view) {
    override fun onResourceReady(resource: Drawable, transition: Transition<in Drawable>?) {
        view!!.background = resource
        if (resource is GifDrawable) {
            resource.setLoopCount(LOOP_FOREVER)
            resource.start()
        }
    }
}
```
use this with
```
Glide.with(myImageView)
        .load(imageUrl)
        .into(DrawableViewBackgroundTarget(myImageView))
```
