### ISSUE TITLE
Gif frames getting dropped into wrong ImageView

### ISSUE THREAD

**Issue by bryanstern** [bumptech/glide#940]
Glide 3.6.1 & 3.7.0
Appears to affect all versions we've tested (Marshmallow, Lollipop, KitKat)

I have a `RecyclerView` which displays gifs in an `ImageView` with a transformation. The onClick event for these `ImageView`s launches a new activity (`FullScreenImageActivity`) with a semi-transparent background and shows the gifs in a larger `ImageView` without any custom transformation (besides the implied `fitCenter` Glide performs). Quite frequently the `ImageView` will display frames from other gifs being loaded in the background activity (the one containing the `RecyclerView`). For example, if my `RecyclerView` has views that are loading `cat.gif` and `dog.gif`, and I launch the `FullScreenImageActivity` to view `cat.gif` while both gifs are still loading, sporadically `dog.gif` frames will be displayed as gif loops. This usually happens if I launch the `FullScreenImageActivity` before the requests complete. The gifs in the `RecyclerView` never have any corruption.

The call in our `RecyclerView.Adapter`'s `onBindViewHolder` Glide call boils down to:
```java
Transformation<Bitmap> transformation = getTransformation();

DrawableRequestBuilder<Media> request = Glide.with(getContext())
    .load(media)
    .bitmapTransform(transformation)
    .diskCacheStrategy(DiskCacheStrategy.SOURCE);

    if (media.stills() != null) {
        DrawableRequestBuilder<Media.Stills> thumbnailRequest = Glide.with(getContext())
            .load(media.stills())
            .bitmapTransform(transformation)
            .diskCacheStrategy(DiskCacheStrategy.ALL);
        request = request.dontAnimate().thumbnail(thumbnailRequest);
    }

    request.into(imageView);
```

The `FullScreenImageActivity` Glide call boils down to this in its `onCreate`
```java
Glide.with(this)
    .load(media)
    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
    .into(new GlideDrawableImageViewTarget(imageView) {
        @Override
        public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> animation) {
            super.onResourceReady(resource, animation);
            progressBar.setVisibility(View.GONE);
        }
    });
```

**Comment by bryanstern** [comment]
A few more thoughts...

`FullScreenImageActivity` has theme where `android:windowIsTranslucent` is true. Disabling that flag resolves the problem. I suspect this fixes it because the original activity will actually hit `onStop` and `onStop` is called on the `GlideDrawableImageViewTarget` which `dog.gif` is being loaded into. Perhaps we could add `LifecycleListener#onResume` `LifecycleListener#onPause` and `start` and `stop` the `GlideDrawable` there instead?

**Comment by TWiStErRob** [comment]
There's no transformation applied in `FullScreenImageActivity` because you're using a custom target. The magic-transformation code is in `into(ImageView)`, you're calling `into(Target)`.

The weird thing is that just because a (transparent) new activity is on top it shouldn't interfere, then this issue should also come up with multiple GIFs in a grid. Are you sure `onStop` is not called? I first thought that it happens because `onStop` is called first (`GlideDrawableImageViewTarget.onStop` is called with `resource==null`) and only after that: `onResourceReady` which starts the resource, so even though the activity is stopped the drawable plays.

What is `getTransformation()` including any custom transformations? Can you repro if that method always returns `UnitTransformation.get()`?

Can you please try to load the "full-screen" image into an ImageView that's in the same activity to reduce complexity? or can you extract the relevant parts into a reproducible project? That would be best. This likely needs thorough debugging.

**Comment by bryanstern** [comment]
`Activity#onStop` is only called when the Activity is no longer visible. Because `FullScreenImageActivity` is translucent, the original Activity is still visible and only paused.

Let me get back to you on the rest of those

**Comment by bryanstern** [comment]
I was ultimately able to resolve this by making use of `Glide.with(this).resumeRequestsRecursive()` and `Glide.with(this).pauseRequestsRecursive()`.

I couldn't reproduce the issue with `UnitTransformation` and I haven't been able to reproduce it in a sample project yet with my same transformation. I'm going to close this until I give you something reproducible.

Thanks for your help!

**Comment by TWiStErRob** [comment]
What's in `getTransformation()`?

**Comment by bryanstern** [comment]
Depending on some other attributes of the data backing the view, `getTransformation()` would either return a transformation that would crop the image using a BitmapShader using a bitmap mask or a transformation that rounded corners. As far as I can tell, I'm using the bitmap pool correctly. I'll try to get something reproducible to you soon.

**Comment by TWiStErRob** [comment]
Hmm, based on not reproing with Unit and that you have custom transformations: my suspicion is that either your custom transformation does something wierd or Glide is applying the custom transformations weirdly for GIF frames. Take your time with the repro. I can look at it over the weekend at the earliest.
