### ISSUE TITLE
how to update image with glide

### ISSUE THREAD

**Issue by romantic011** [bumptech/glide#944]
Excuse me I encountered a problem, but I do not know how to solve it with glide， for example，i have loaded image into imageView with glide， then  i reload the image when the image url is changed ,but the image  is not updated

**Comment by TWiStErRob** [comment]
Glide has to assume certain things, like an URL identifies a resource that doesn't change, to be able to cache efficiently. Read this page https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation
`.signature()` is what you probably need, or the very inefficient `.diskCacheStrategy(NONE)` which **always** retrieves the latest image.

**Comment by romantic011** [comment]
Thank you very much for the fast replies, that's what i want

**Comment by grndvl1** [comment]
Does not work for me when coupled with databinding.
