### ISSUE TITLE
Additional Support Files Not in Release

### ISSUE THREAD

**Issue by stripathi669** [bumptech/glide#945]
I was trying out the samples when I realized that some of files are not put into release jar (for obvious reasons).

For example, if one adds glide via build.gradle, he/she won't be able to import files such as `Registry.java`, `Options.java` while testing one of the sample sample. These, and many other, files are only present in libs folder of repo.

I was wondering what is standarad/intended way to integrate these files in the studio (apart from pulling and importing entire module)

**Comment by TWiStErRob** [comment]
The samples are currently tied in with the build process. However they shouldn't be using any private classes so to should be fairly trivial to extract them and use the published 3.7.0 or 4.0.0-SNAPSHOT jar. I think you're using the `master` samples which are for v4 and adding the v3 lib in build.gradle which gives you the errors. Check out https://github.com/bumptech/glide/wiki/Snapshots to see how to consume the unreleased v4 lib or switch to the 3.0 branch to see the "old" samples.

**Comment by stripathi669** [comment]
Hey, Thanks. My mistake.

It's really wonderful how you guys find out time to answer even smallest and silliest of queries.

**Comment by TWiStErRob** [comment]
The smallest and silliest questions are the best: all the time needed is just to type the answer, no research :) I'm also not working ATM, but hopefully that'll change soon.
