### ISSUE TITLE
Glide  with Zoomable and Image Overlay?

### ISSUE THREAD

**Issue by silenus092** [bumptech/glide#946]
I want to zoom and draw some icon on SVG map, Is glide supports? or I have to implement by myself after I got svg . if so can you suggest me please?

Sincerely yours,

**Comment by TWiStErRob** [comment]
There's an svg sample app in the repo, but you'll have to implement zooming and panning yourself. You're probably better off finding a specialised lib.

**Comment by atonamy** [comment]
@TWiStErRob any recommendations? I tried [sharp](https://github.com/Pixplicity/sharp), but it doesn't render properly svg  files.
