### ISSUE TITLE
glide can not load video thumbnail by uri

### ISSUE THREAD

**Issue by guider** [bumptech/glide#948]
when use  ImageLoader.getInstance().displayImage(uri.toString(),holder.image); was be OK

**Comment by TWiStErRob** [comment]
Please fill in the issue template:
https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues

**Comment by TWiStErRob** [comment]
You cannot load remote videos (#862), nor you can play any videos with Glide (#831), it needs to be a local File to load thumb successfully. Is your Uri a correct `file:///` Uri pointing to a local File?
