### ISSUE TITLE
listview - doubling images

### ISSUE THREAD

**Issue by ddszczygiel** [bumptech/glide#949]
hi,

could anyone of contributors check this thing:

[stackoverflow link to problem](http://stackoverflow.com/questions/35107329/android-listview-with-glide-doubled-bitmaps-after-load)

part of row layout with the profile imageView;

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="72dp"
    android:background="@color/white">

    <ImageView
        android:layout_width="@dimen/icon_diameter"
        android:layout_height="@dimen/icon_diameter"
        android:id="@+id/friendIcon"
        android:layout_centerVertical="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_marginLeft="20dp"
        android:src="@drawable/user_small"
        android:scaleType="centerInside"/>`
 in my opinion i've done everything right but the problem is present on all of my listviews with glide

**Comment by TWiStErRob** [comment]
See http://stackoverflow.com/a/35114351/253468.
