### ISSUE TITLE
how to prevent glide reloading image when activity onResume?

### ISSUE THREAD

**Issue by jwang0512** [bumptech/glide#951]
```java
protected void onCreate(Bundle savedInstanceState) {
...        Glide.with(this).load(url).placeholder(R.mipmap.ic_default).centerCrop().into((ImageView)findViewById(R.id.iv_image)); // url is a http resource, which does not exist,so it shows ic_default.
}

protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if(resultCode==RESULT_OK) {
            bmHead = data.getExtras().getParcelable("data");
            ((ImageView)findViewById(R.id.iv_image)).setImageBitmap(bmHead);  // return from system gallery view.
        }
}
```
after selected image from system gallery view, and return to this activity; the selected image will not displayed in R.id.iv_image.  and we got a log from http server, the url(in onCreate function) is requested again after onActivityResult.

how to prevent this?pls help.

**Comment by vipinhelloindia** [comment]
I guess , you just need to pause the request in onPause and onResume  dont resume it .

**Comment by jwang0512** [comment]
"I guess , you just need to pause the request in onPause and onResume dont resume it ."
tried, but that did not work. Thanks

**Comment by jwang0512** [comment]
fixed by calling Glide.clear(imageView) before setImageBitmap.

**Comment by TWiStErRob** [comment]
What do you mean by doesn't exists? What you experienced sounds like Glide is re-trying an already failed load.

**Comment by LaxmikantMahamuni** [comment]
I have used CircularProgressDrawable as a placeholder on recyclerview items. Once I go to next activity and come again on previous one, glide tries to load again previously failed images (Observe loader again on recyclerview items).
![vid-20180622-wa0045](https://user-images.githubusercontent.com/26277288/41779427-65850eca-764f-11e8-9cb8-50c0d1328ce9.gif)

Please help me out if we can restrict glide to reload image if activity resumed.

**Comment by sjudd** [comment]
@LaxmikantMahamuni Glide will retry load failures, there isn't currently a way to configure this behavior. You may be able to get around it by using Glide.with(applicationContext), but doing so will give up the rest of Glide's lifecycle integration as well.

**Comment by LaxmikantMahamuni** [comment]
@sjudd Thanks, for your valuable reply... I was using _RequestListener_ for **showing error-image with error-text simultaneously**. Now I have created a drawable using canvas as solution for simultaneously showing error-image with error-text. By using this drawable in **.error()** method instead of RequestListener.
