### ISSUE TITLE
Unable to Set Image to ImageView after an Error Occurred

### ISSUE THREAD

**Issue by Jayvd** [bumptech/glide#956]
How to produce,

Set an image using glide to a url that is not valid.

```java
Glide.with(this)
        .load(profilePictureUrl)
        .into(imageView);
```

then somewhere in onClick() method. when we try to set to the imageView. It no longer works.

```java
imageView.setImageResource(R.drawable.resource_id);
imageView.setImageDrawable(otherDrawable);
imageView.setImageBitmap(otherBitmap);
```

Any ideas?

**Comment by TWiStErRob** [comment]
Try to call `Glide.clear(imageView)` before calling any `setImage*`. It'll make Glide stop whatever it's doing and let the control over the view back to you.

I would also suggest looking into `.error()`, `.placeholder()` and `fallback()`.
