### ISSUE TITLE
--- SkImageDecoder::Factory returned null error when loading with Glide

### ISSUE THREAD

**Issue by Orbyt** [bumptech/glide#959]
Im grabbing URLs from a photo based subreddit and loading them with Glide. A few of the images sometimes wont load, and the following gets printed in the console:

`--- SkImageDecoder::Factory returned null`

What I think may be happening is some of the URLs may not be direct image links (with .jpg/.png affixed at the end). Could that cause this error? Whats the workaround for this?

**Comment by TWiStErRob** [comment]
Do those same URLs load other times? One thing it could be is rate limiting on their side sometimes returning HTML or JSON error.

Glide doesn't require any naming convention, it peeks at the magic in the binary header of the stream. Also most redirects are supported, but there's a case which is not: when you pass auth headers it may be passed on to redirects too: #536 it's possible they don't respond with a standard code. There are some debugging tips in that issue as well.

**Comment by Orbyt** [comment]
No, the same URLs dont load other times. Heres some examples of one of the links that wont load: 

https://www.flickr.com/photos/jimmykastner/20162877648/in/photostream/lightbox/
https://500px.com/photo/138485827/orion-by-l%C3%A9on-gelin
http://imgur.com/pWnybTO

Like I mentioned previously, I would assume that its because they arent direct image links, but @TWiStErRob your post made it sound like direct links arent needed. What do you think the issue is here?

**Comment by TWiStErRob** [comment]
These are all HTML documents. A "redirect" doesn't mean that Glide will parse the HTML code for an `<IMG>` tag. A redirect is simply an HTTP response type to locate relocated resources. The end result after resolving all redirects still need to be a binary image. If you open any URLs in a browser you can tell whether Glide can load it by saving it. If it's an HTML page it won't load, if it's an image file it will.

**Comment by Orbyt** [comment]
@TWiStErRob, yes, thats what I was referring to when talking about needing a direct image. 

Anyway, thanks, closed.
