### ISSUE TITLE
Integrating Glide and Volley in eclipse

### ISSUE THREAD

**Issue by IRMobydick** [bumptech/glide#963]
Hi there,
I'm using `Volley` in my app and I want to integrate glide with that, but when I remove `glide-3.7.0.jar` file from lib folder and add `glide-volley-integration-1.4.0.jar` instead, eclipse show error that can't resolved glide related methods.

I've my GideModule:

```java
public class GlideConfiguration implements GlideModule{
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
    }

    @Override
    public void registerComponents(Context context, Glide glide) {

    }
}
```

and in my app manifest after removing Glide library and replacing with integrated library I've change meta data in manifest from:
```xml
<meta-data
    android:name="com.mypackage.android.glide.GlideConfiguration"
    android:value="GlideModule" />
```
to
```xml
<meta-data
    android:name="com.bumptech.glide.integration.volley.VolleyGlideModule"
    android:value="GlideModule" />
```

Where am I wrong? :(
Should I do anything more?

**Comment by TWiStErRob** [comment]
Check the contents of the jar files: Glide IS glide and integration is just some glue to connect Glide and Volley classes.
You can also have more than one module: if the default Volley config is not good enough you can replace it with your own, but you can always have your own setting the format.

**Comment by TWiStErRob** [comment]
What's stopping you from using Android Gradle Plugin and Android Studio? I was also hesitant, but started using them in their infancy (0.12), and after a few weeks I thought I should have started sooner! I think they're both coming to their 2.0 in a few weeks.
