### ISSUE TITLE
Getting illegalStateException

### ISSUE THREAD

**Issue by taimur97** [bumptech/glide#971]
Hi,

I am getting an exception when I try to execute following code

```java
runOnDraw(new Runnable() {
    @Override
    public void run() {
        Glide.with(mContext)
             .load(mResIds.get(0))
             .asBitmap()
             .into(new SimpleTarget<Bitmap>() {
                     @Override public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap>glideAnimation) {
                         //Bitmap b = BitmapFactory.decodeResource(mContext.getResources(), mResIds.get(0));
                         filterSourceTexture2 = OpenGlUtils.loadTexture(resource, OpenGlUtils.NO_TEXTURE, true);
                     }
             });
    }
});
```

The Exception I am getting is "It should be called on main thread"

how to fix it?

**Comment by taimur97** [comment]
you can check the full code file here https://github.com/sangmingming/android-instagram-filter/blob/master/sample/src/jp/co/cyberagent/android/gpuimage/sample/filter/IFImageFilter.java

**Comment by TWiStErRob** [comment]
Call it on the Android main UI thread. That `into(Target)` method only supports calls on the UI thread.
It looks like your OpenGL drawing thread is not the UI thread. Does it still happen if you remove the ` runOnDraw(new Runnable() {` inner class?

Tip: use `int[] filterInputTextureUniform = new int[6];` that way you can use a for loop and don't have to duplicate that much code. OpenGL methods can be called with `array[index]` as well.

**Comment by taimur97** [comment]
Yes it is still showing the error even if I move the code out of runnable I can't call runOnUi method in that class cause it is extending GPUImageFilter

**Comment by taimur97** [comment]
It's really strange cause AFAIK the image filter is set on UI thread and moving it out of runnable should not cause the error

**Comment by TWiStErRob** [comment]
You can check which thread is running which code by putting a few `Thread. currentThread().getName()` log lines in different places.

**Comment by TWiStErRob** [comment]
What's up? Did you figure it out?
