### ISSUE TITLE
Callback upon completion of image loading?

### ISSUE THREAD

**Issue by danieljonker** [bumptech/glide#974]
Upon switching from Picasso to Glide and using Chris Banes' Photoview library, I can't get the same functionality. 

So we have this bug, with photoview in our app, where we used the solution provided with Picasso:
https://github.com/chrisbanes/PhotoView/issues/99

But the .listener doesn't seem to work the same as the calback in picasso. 
Meaning, this code snippet:

```java
public void loadImageInView(String imageUrl, ImageView imageView, ImageType imageType, final PhotoViewAttacher attacher) {
    mGlideBridge
    	.with(imageView.getContext())
	   	.load(getTemplatedUrl(imageUrl, mImageSizes.get(imageType)[0], mImageSizes.get(imageType)[1]))
        .placeholder(getPlaceholderImageDrawable(mImageSizes.get(imageType)[2]))
        .listener(new RequestListener<String, GlideDrawable>() {
            @Override
            public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                return false;
            }

            @Override
            public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                if (attacher != null) {
                    Timber.d("resourceReady");
                    attacher.update();
                }
                return false;
            }
        })
        .into(imageView);
}
```

doesn't work. 
But this (with Picasso) does:

```java
public void loadImageInView(String imageUrl, ImageView imageView, ImageType imageType, final PhotoViewAttacher attacher) {
    picasso
    	.load(getTemplatedUrl(imageUrl, mImageSizes.get(imageType)[0], mImageSizes.get(imageType)[1]))
        .placeholder(getPlaceholderImageDrawable(mImageSizes.get(imageType)[2]))
        .into(imageView, new Callback() {
            @Override
            public void onSuccess() {
                if (attacher != null)
                    attacher.update();
            }

            @Override
            public void onError() {
            }
        });
}
```

I can't seem to find any other way of listening for the image to have finished loading.

**Comment by TWiStErRob** [comment]
As far as I remember Picasso loads the full size image all the time, while Glide tries to load an image Bitmap that is a perfect fit for the view to save memory and processing power. This means that Glide will wait for a layout to happen: no layout -> no size -> Glide cannot start loading -> listener not called.

This is my guess for what's happening here, because your usage of Glide seems correct. One way of working around this is to provide Glide with a size to override the wait for first layout, try:
```java
.override(mImageSizes.get(imageType)[0], mImageSizes.get(imageType)[1])
```

If it doesn't work please take a look at the [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) to go deeper and see what's going on.

> I can't seem to find any other way of listening for the image to have finished loading.

You can also implement a `Target`, see `GlideDrawableImageViewTarget` (what you're currently using) and its super classes.

---

*Usage tips: There's a way to hide the template url resolution by registering custom models (e.g. `class Image { String imageUrl, ImageType type; }`) and building the Url inside a `BaseGlideUrlLoader` subclass. Glide also supports loading the drawable via a resource ID, `mImageSizes.get(imageType)[2]` looks like an int.*

**Comment by danieljonker** [comment]
So I've fixed my issue, it wasn't that the listener callbacks weren't being triggered, it just wasn't working with photoview properly. So basically when setting up the photoview I disabled zoom, then in resource ready, re-enabled it. 

Should I change the title of the issue to be more clear on the issue?

**Comment by TWiStErRob** [comment]
Feel free if you want to.

**Comment by TWiStErRob** [comment]
If you want to zoom an image you need to tell Glide to load a bigger image, otherwise it'll be blurry: `.override(Target.SIZE_ORIGINAL)`.

**Comment by danieljonker** [comment]
Should that be 
```.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)``` ?

I've adjusted the request to:
```
mGlideBridge.with(imageView.getContext()).load(getTemplatedUrl(imageUrl, mImageSizes.get(imageType)[0], mImageSizes.get(imageType)[1]))
                .override(mImageSizes.get(imageType)[0], mImageSizes.get(imageType)[1])
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        attacher.setZoomable(true);
                        return false;
                    }
                })
                .into(imageView);
```

But like you said it's still blurry, am I using the wrong .override method?
Should I being calling .into(Target)?

**Comment by TWiStErRob** [comment]
The image will have the size at most what is defined by `mImageSizes.get(imageType)`, so if that's small, you get a blurry image; try with `SIZE_ORIGINAL`. I don't think you need a custom target for this.

**Comment by danieljonker** [comment]
Ok, cool. Got it sorted. Thanks

**Comment by Pynop** [comment]
@TWiStErRob thanks for giving a clue on the issue. I can confirm: as soon as I started using .override() the issue has disappeared.
