### ISSUE TITLE
Crash in OnTrimMemory()

### ISSUE THREAD

**Issue by mullender** [bumptech/glide#979]
Version: 4.0.0-SNAPSHOT
Stacktrace:
```
0	java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@2399f090[1920x225] ARGB_8888
1	at com.bumptech.glide.util.Util.getBitmapByteSize(Util.java:72)
2	at com.bumptech.glide.load.engine.bitmap_recycle.AttributeStrategy.getSize(AttributeStrategy.java:45)
3	at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimToSize(LruBitmapPool.java:224)
4	at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimMemory(LruBitmapPool.java:207)
5	at com.bumptech.glide.Glide.trimMemory(Glide.java:361)
6	at com.bumptech.glide.Glide.onTrimMemory(Glide.java:508)
7	at com.bumptech.glide.GlideContext.onTrimMemory(GlideContext.java:72)
8	at com.bumptech.glide.RequestManager.onTrimMemory(RequestManager.java:159)
9	at com.***ImageView.onTrimMemory(UrlImageView.java:105)
10	at com.**Application.onTrimMemory(*Application.java:348)
11	at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4212)
```

**Comment by TWiStErRob** [comment]
Hmm, that looks like the bitmap was recycled by a third party, as you can see in `trimToSize` the `removed` is recycled at the end. Do you have any custom (non-Glide builtin) transformations or custom Targets around that may call recycle?

**Comment by TWiStErRob** [comment]
Alternatively: do you use the BitmapPool manually?

**Comment by mullender** [comment]
This is the wrapper I use around the transform code. The doTransform does not call `Bitmap.recycle()`
```java 
@Override
    protected Bitmap transform(BitmapPool pool, Bitmap source, int outWidth, int outHeight) {
        final Bitmap result = doTransform(source);
        if (result != source) {
            pool.put(source);
        }
        return result;
    }
```

**Comment by mullender** [comment]
I just did a code base search and found one instance of `Bitmap.recycle()`
I will remove it and report back

**Comment by TWiStErRob** [comment]
You shouldn't use that wrapper code, see [BitmapTransformation](https://github.com/bumptech/glide/blob/c2fc19316d8680322cabeed31234d19e942866e8/library/src/main/java/com/bumptech/glide/load/resource/bitmap/BitmapTransformation.java#L91):

> The provided Bitmap, toTransform, should not be recycled or returned to the pool.

**Comment by mullender** [comment]
Aha, that makes sense. Closer reading of the docs shows that only intermediate images should be using the pool, not the input or the output image.
To clarify, if a new bitmap is needed in the transform, can it be requested from the pool?

**Comment by TWiStErRob** [comment]
Yes, of course: I think of it as: "if it's not seen by Glide it's my job to get/put or throw away by recycle", which covers the input and output image handling. So if you want to get an intermediate image, render something on it, draw the intermediate on a canvas backed by `toTransform` and then return the intermediate to the pool, you're free to do so. That Bitmap's reference is not seen by Glide, ever. (Obviously not counting BItmapPool as part of Glide, because it has a well-defined interface.)

**Comment by Macarse** [comment]
@TWiStErRob Interesting. We had this because it's a requirement in Picasso. Perhaps having some FAQs on how to port transformations would be useful.

**Comment by mullender** [comment]
@Macarse it is pretty clear, if you read the doc: https://github.com/bumptech/glide/wiki/Transformations#bitmap-re-use

I must have glossed over the big warning not to return the bitmap to the pool.
Sorry for the confusion @TWiStErRob 
And thank you for the quick help!

**Comment by TWiStErRob** [comment]
Yep, that pretty much sums it up, don't remember reading that before :) There are 2 mentions of "don't return" there, and there's one in JavaDocs. Now there's one here, with a stack trace. Google should index this and future users should find one of these.

@mullender No problem, it's better to figure this out, than leave some real bugs hiding in Glide.
