### ISSUE TITLE
BitmapFactory decodeStream about Options.inBitmap.

### ISSUE THREAD

**Issue by Caij** [bumptech/glide#987]
**Glide Version**: 3.7.0

Downsampler.java  
```java
private Bitmap downsampleWithSize(InputStream is, BitmapFactory.Options options,
      BitmapPool pool, int sourceWidth, int sourceHeight, DecodeCallbacks callbacks)
      throws IOException {
    // Prior to KitKat, the inBitmap size must exactly match the size of the bitmap we're decoding.
    if ((options.inSampleSize == 1 || Build.VERSION_CODES.KITKAT <= Build.VERSION.SDK_INT)
        && shouldUsePool(is)) {
        ....
        setInBitmap(options, pool, expectedWidth, expectedHeight, options.inPreferredConfig);
    }
    return decodeStream(is, options, callbacks);
  }  
```

why options.inSampleSize == 1? before Android 4.4 (API level 19),reuse bitmap size equal output bitmap sized bitmaps are supported.  
Android 4.4 and Higher,reuse bitmap size greater than output bitmap sized bitmaps are supported.  bitmapPool.getDirty(width, height, config)  get reuse bitmap size equal output bitmap,if haven't cache bitmap, create new bitmap, why not get greater than output bitmap size in bitmapPool?

```java
  @Override
  public Bitmap getDirty(int width, int height, Bitmap.Config config) {
    Bitmap result = getDirtyOrNull(width, height, config);
    if (result == null) {
      result = Bitmap.createBitmap(width, height, config);
    }
    return result;
  }
```

**Comment by sjudd** [comment]
That's exactly what does happen. On builds greater than API 19, ``Build.VERSION_CODES.KITKAT <= Build.VERSION.SDK_INT`` will return ``true``.

**Comment by Caij** [comment]
On API 14, Build.VERSION_CODES.KITKAT <= Build.VERSION.SDK_INT is false, if  options.inSampleSize == 1 is false, is mean don't use inBitmap.
But, On API 14 ,if reuse bitmap size equal output bitmap sized bitmaps are supported of inBitmap .(reuse bitmap size equal output bitmap size not mean options.inSampleSize == 1, options.inSampleSize == 1 mean source bitmap size equal output bitmap size)
