### ISSUE TITLE
how to know its using the cache images and not downloading everytime

### ISSUE THREAD

**Issue by sant527** [bumptech/glide#989]
In my android app i am using glide. 

case:1 interner is on:
What i found it the page with images which was once opened, when i try to open it again, the images dont look to be loaded from cache, rather getting downloaded. 

case2: internet off:
then it shows the cached images.

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow
Look for "Fetched data", that's when the network is used.
