### ISSUE TITLE
Resizing (override)

### ISSUE THREAD

**Issue by elsennov** [bumptech/glide#991]
Hi, i use this code to resize the Image.
```java
int iconSize = getResources().getDimensionPixelSize(R.dimen.toolbar_icon_size);
BitmapPool bitmapPool = Glide.get(this).getBitmapPool();
CircleTransformation circleTransformation = new CircleTransformation(bitmapPool);

Glide.with(this)
         .load(iconString)
         .bitmapTransform(circleTransformation)
         .into(new SimpleTarget<GlideDrawable>(iconSize, iconSize) {
                @Override
                public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                     actionBar.setLogo(resource);
                }
          });
```
But the size inside onResourceReady is not the same as intended if the image is big. Is it possible to always have the intended size?
Thank you :)

**Comment by TWiStErRob** [comment]
Nothing is resizing your image. Since you're using a custom target Glide cannot determine the appropriate transformation (fitCenter/centerCrop) automagically, and `CircleTransformation` doesn't bother resizing the bitmap to match output size, it should be as easy as:
```java
.bitmapTransform(new FitCenter(bitmapPool), circleTransformation)
```

Note that `.fitCenter().bitmapTransform(circle)` or `.bitmapTransform(circle).fitCenter()` won't work because they call the same method and override each other.

**Comment by elsennov** [comment]
Wow, it works! I used this
```
.bitmapTransform(new CenterCrop(bitmapPool), circleTransformation)
```
I see, so if we want to resize but we use custom target, we need to add fitCenter or centerCrop transformation as well. Thank you so much for the explanation @TWiStErRob . Very helpful and fast response! :+1:

**Comment by TWiStErRob** [comment]
Yep, you need to be explicit. Not necessarily with `.bitmapTransform()`, you can use the convenience methods, but to chain transformations you need to create all of them yourself. The magic that's hiding with normal usage is what you need to replace with custom targets, see: https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/GenericRequestBuilder.java#L681
