### ISSUE TITLE
Bug: Using placeholder it does not replace it when ready

### ISSUE THREAD

**Issue by jonasborggren** [bumptech/glide#993]
**Glide Version**: 3.6.1
**Integration libraries**: 
**Device/Android Version**: 5.1.1
**Issue details / Repro steps / Use case background**:
I'm trying to load image from url when activity is ready, and I want to have a placeholder that is by `ColorDrawable(Color.WHITE);`. The placeholder does not get replaced first time loading the image, but it does get replaced when it's from cache instead of URL.
**Glide load line**:
```java
glide.load(mPlayer.imgUrl)
        .diskCacheStrategy(DiskCacheStrategy.ALL) // If I choose NONE for cache it works
        .placeholder(new ColorDrawable(Color.WHITE)) // if I comment this line it works
        .into(mPicture);
```

**Layout XML**:
```xml
<...Layout>
<de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/player_image"
        android:layout_width="112dp"
        android:layout_height="112dp"
        app:civ_border_color="@color/bright_100"
        app:civ_border_width="4px"
        app:civ_fill_color="@color/bright_100" />
</..Layout>
```

**Stack trace / LogCat**:
```ruby
No log trace available
```

**Comment by TWiStErRob** [comment]
Oh, oh, oh, the good old `CircleImageView`: https://github.com/bumptech/glide#compatibility
Explanation: https://github.com/bumptech/glide/issues/482#issuecomment-107977982

**Comment by jonasborggren** [comment]
Sorry for not reading properly.

**Comment by TWiStErRob** [comment]
No worries, we also have this ;)

> When in doubt, file an issue. We'd rather close a few duplicate issues than let a problem go unnoticed. [CONTRIBUTING.md](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues)
