### ISSUE TITLE
problem in loading specific url under api 16 

### ISSUE THREAD

**Issue by lake-igaw** [bumptech/glide#995]
under api 16 ...
i use google play store app icon by using play store url
but always load fail specific url like start with "http://lh3.googleusercontent.com/~...." 
i don`t know why exactly but when i used difference url, good working  

here is my full url i used 
http://lh3.googleusercontent.com/xrEBCFOz6WqwQTPh_IaYEDAKfv2PFhs4C9EAq34s8wsX7Aj381j2ptr8idKmUi5-Ogs=w300-rw

and i debug in genymotion glaxy s2 & s3 api 16,10

**Comment by sjudd** [comment]
Does it work if you remove the -rw? For example: http://lh3.googleusercontent.com/xrEBCFOz6WqwQTPh_IaYEDAKfv2PFhs4C9EAq34s8wsX7Aj381j2ptr8idKmUi5-Ogs=w300

**Comment by IgaworksLake** [comment]
oh... my.. Thank you so much!

**Comment by TWiStErRob** [comment]
PNG wins over WEBP, weird. Sam, is this documented somewhere?

**Comment by sjudd** [comment]
The affect of -rw? I don't think so.

@IgaworksLake can you fill out the issue template or provide more information about what networking library you're using and what your request looks like? There are a number of known issues decoding webp in the framework on earlier versions of Android, but I had thought we had workarounds for them. Especially if you can reproduce the issue in a sample app using the original url (with "-rw") I'd like to take a look.

I suggested removing "-rw" to confirm that the issue was in fact related to webp.

**Comment by TWiStErRob** [comment]
@sjudd I think the behavior we see is normal, not related to networking.
@IgaworksLake but a confirmation would be nice with info filled in in the [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues).

According to [supported formats](http://developer.android.com/guide/appendix/media-formats.html):
```
WebP support: (Android 4.0+) (Lossless, Transparency, Android 4.2.1+)
```
The webp the url points to (according to ffmpeg):
```
Stream #0:0: Video: webp, argb, 300x300, lossless, 25 tbr, 25 tbn, 25 tbc
```

Genymotion Galaxy S2/S3 devices:
```
S2 2.3.7 API 10
S2 4.1.1 API 16
S3 4.1.1 API 16
S3 4.2.2 API 17
S3 4.3 API 18
```

API 10 and API 16 was mentioned above, here're the relevant versions from [build-numbers](https://source.android.com/source/build-numbers.html):
```
Gingerbread 2.3.3 - 2.3.7 (API level 10)
Ice Cream Sandwich 4.0.1 - 4.0.2 (API level 14, NDK 7)
Jelly Bean 4.1.x (API level 16)
Jelly Bean 4.2.x (API level 17)
```

So putting this all together: 10 doesn't support webp at all, and 16 doesn't support lossless webp. So S2 will never load this file and S3 should work above API 17. Is it possible to work around these limitations?

**Comment by sjudd** [comment]
Oh good point, I'd forgotten about the lossless/transparency limitation!

Then yes, it's fine (at least for now) to just remove the "-rw" when using that url format. on older APi levels.

It is actually possible to work around these limitations if you were to, for example, compile the webp decoder and add an integration library. I've looked in to it, but the current version of the decoder doesn't support downsampling so it's only useful if you have some control over the size of the images you're using.

**Comment by van11** [comment]
Hi,

for some reasons I got into this issue, that if I do not remove `-rw` from url, I get an error: 
`Problem decoding into existing bitmap`

`-rw` forces to download webp image, so without it I am getting `.png` and Glide loads it without any issues. I tested this behaviour on API23.

**Comment by TWiStErRob** [comment]
@van11 Can you share an example? Maybe there's a format (8888 vs 565) detection issue, or the WEBP is animated, or otherwise exotic. What is the device? the Android build may have some vendor customizations as well. If you could provide a small demo app that would be best.
