### ISSUE TITLE
Would you let me know when to invalidate cached bitmap?

### ISSUE THREAD

**Issue by jayjaykim** [bumptech/glide#996]
Suppose, there's a bitmap(https://www.google.co.kr/images/nav_logo242_hr.png) which is already cached in the memory and disk by Glide. One of Google guy changed the bitmap but the url is still unchanged. In that case, when does Glide get the changed bitmap and invalidate the cached bitmap and how? Is the bitmap downloaded as soon as the url of the bitmap is used for rendering and cached again?

**Comment by TWiStErRob** [comment]
It doesn't get automatically updated, Glide doesn't touch the network if something is in cache.

You have a few options:
 * re-request image on every load (horrible performance, waste of resources):

    ```java
    .diskCacheStrategy(NONE).skipMemoryCache(true)
    ```

 * re-request periodically (balanced performance, if period is big enough, say a week)

    ```java
    .signature(new StringSignature(String.valueOf(System.currentTimeMillies() / (7 * 24 * 60 * 60 * 1000))))
    ```

 * re-request when it really changed (best solution), but you'll need to have control over the server. When you receive an URL to display, you can also receive metdata of last change (e.g. last time the user uploaded a profile picture) and use that as the signature

    ```java
    .load(profile.url).signature(new StringSignature(profile.lastChange))
    ```

 * re-request on HTTP non-403 (hacky, Glide was not built for this). You can try to write a cache-decoder that checks the URL and fails if the response is not 403, then detect this failure with a listener and reload the image with a different signature.

 * re-request all the time (like first option), but use a network integration library where the cache is enabled and is maintained by the HTTP headers and 403. This removes Glide's ability to use the two-layer cache, but you'll always have uptodate data, like a browser would.

**Comment by jayjaykim** [comment]
Thank you for you kind answer.
I got the point. The perfect solution to this matter is using okhttp for http communication stack, isn't it? Because it supports e-tag handling in the response header of GET request for image files.

**Comment by TWiStErRob** [comment]
If you want the full power of Glide use the third option regardless of networking lib.

I've never tried the last one if that's what you suggest. With that you might lose much what Glide offers (memory cache, RESULT and SOURCE disk cache) because it always has to try the network layer and that'll decide to give Glide a cache stream or a network stream.

Just using OkHttp won't solve the issue, because it may never be asked to compare etags or check the cache headers. Glide is not using OkHttp's full power by default.

**Comment by jayjaykim** [comment]
I guess okhttp by default supports e-tag handling. One of Square guys says like following.
http://stackoverflow.com/questions/27751634/okhttp-add-etag-and-if-none-match
What he says okhttp sends conditional get request for the response that has e-tag in its header. So I think using Glide on top of okhttp may solve the issue I addressed in this post...

**Comment by TWiStErRob** [comment]
See also #624.
Please let us know how you manage to do it, it will help a lot of people.

**Comment by jayjaykim** [comment]
I just guessed. I need to check how Glide make use of okhttp as ModelLoaderFactory. As soon as I figure out how it handles okhttp I will share in this post because this issue is important :)

**Comment by jayjaykim** [comment]
@TWiStErRob, In order to use the third option we need ETag or Last-modified for each GET request to images, don't we? Does Glide provide any methods which can get those metadata?
BTW, I checked out just simple Glide + okhttp integration does not resolve the issue addressed here :(

**Comment by TWiStErRob** [comment]
Because probably Glide doesn't request the file so OkHttp is not involved. Whether a file is in cache is based solely on memory cache key match or file existence in cache, no network involved (like Browsers do sometimes). If you want ETag handling you have to implement your own networking layer and cache and use `.diskCacheStrategy(NONE)`.

To use the third one you need to be aware of the date of the last change, which you may receive along with the url. For example you get this JSON from your server like this:
```json
"products": [
 { "name": "foo", "url": "http://...", "lastModified": "2016...", "width": "xxx", ... },
 { "name": "bar",  "url": "http://...", "lastModified": "2016...", "width": "xxx", ... }
]
```

**Comment by jayjaykim** [comment]
So in order to guarantee that users always see the latest images, every time each image in image servers is changed its url must be changed and delivered to clients after all. Then clients can load the latest changed images regardless of cached images :) What a simple.

**Comment by TWiStErRob** [comment]
Yes, that's the simplest way. If you look at the definition of URL: http://www.ietf.org/rfc/rfc3986.txt you should see it's a specialized URI, which is an identifier, so it makes sense that different images have different IDs. Since you started out with "here's a fix url that changes", I assumed you ruled that option out.

Note that problem is not Glide specific, any caching solution will have to have a key and means of invalidation. I guess most of the time it's not worth the effort re-validate whether it has changed or not, because the general assumption is that the data will stay the same.

**Comment by jjzhoujun** [comment]
I can get the Heads(Last-Modified) by Retrofit2&Okhttp. The main code is 

`

Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(baseUrl)
                .build();
        RegularPicApi repo = retrofit.create(RegularPicApi.class);
        Call<ResponseBody> call = repo.getPic(path);
        call.enqueue(new retrofit2.Callback<ResponseBody>() {
            @Override
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
                String lastModified = response.headers().get("Last-Modified");
                Glide.with(context).load(url).signature(new StringSignature(lastModified))....
            }
            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {
            }
        }); 

`
`  

public interface RegularPicApi {
        @GET("{url}")
        Call<ResponseBody> getPic(@Path("url") String url);
    }

`
Maybe it will help you.

**Comment by TWiStErRob** [comment]
@dmytrodanylyk never said float ;) use integer division or round/floor/ceil. By dividing (integer) by 7 days, the value will change every 7 days, notice the whole part only in your example.

**Comment by dmytrodanylyk** [comment]
@TWiStErRob I have used float just to illustrate that rounding values ether up/down will not give you correct result.

This approach guarantee that value will expire in at least 7 days. But it may expire after day 1 as well, depending on current time and expiration time.

**Comment by dmytrodanylyk** [comment]
@TWiStErRob here is more specific example so you can reproduce problem:

```kotlin
val current = SimpleDateFormat("dd-MM-yyyy").parse("13-11-2018").time

val expiration = TimeUnit.DAYS.toMillis(7)
val c1 = current
val c2 = current + TimeUnit.DAYS.toMillis(2)
val c3 = current + TimeUnit.DAYS.toMillis(4)

val r1 = c1 / expiration
val r2 = c2 / expiration
val r3 = c3 / expiration

println(r1) // 2549
println(r2) // 2549
println(r3) // 2550
```
As you can see the value has changed in 4 days, not 7.

**Comment by zijinzhiyun** [comment]
> @TWiStErRob here is more specific example so you can reproduce problem:
> 
> ```kotlin
> val current = SimpleDateFormat("dd-MM-yyyy").parse("13-11-2018").time
> 
> val expiration = TimeUnit.DAYS.toMillis(7)
> val c1 = current
> val c2 = current + TimeUnit.DAYS.toMillis(2)
> val c3 = current + TimeUnit.DAYS.toMillis(4)
> 
> val r1 = c1 / expiration
> val r2 = c2 / expiration
> val r3 = c3 / expiration
> 
> println(r1) // 2549
> println(r2) // 2549
> println(r3) // 2550
> ```
> 
> As you can see the value has changed in 4 days, not 7.

@dmytrodanylyk hi,Have you got any good solutions to the problem?

**Comment by dmytrodanylyk** [comment]
@zijinzhiyun I am not 100%, it's been a while, but I think yes, I ended up using this solution.

Something like:

```kotlin
data class ExpirableSignature(
    val expirationMillis: Long,
    val timeMillis: Long = System.currentTimeMillis()
) : ImageSignature {
    override val key: Any = if (expirationMillis == 0L) timeMillis else timeMillis / expirationMillis
}
```

**Comment by zijinzhiyun** [comment]
> Something like:
> 
> ```kotlin
> data class ExpirableSignature(
>     val expirationMillis: Long,
>     val timeMillis: Long = System.currentTimeMillis()
> ) : ImageSignature {
>     override val key: Any = if (expirationMillis == 0L) timeMillis else timeMillis / expirationMillis
> }
> ```

Thank you for you kind answer.

**Comment by theAkito** [comment]
> 
> 
> @zijinzhiyun I am not 100%, it's been a while, but I think yes, I ended up using this solution.
> 
> Something like:
> 
> ```kotlin
> data class ExpirableSignature(
>     val expirationMillis: Long,
>     val timeMillis: Long = System.currentTimeMillis()
> ) : ImageSignature {
>     override val key: Any = if (expirationMillis == 0L) timeMillis else timeMillis / expirationMillis
> }
> ```

I am trying to understand this suggestion, but I didn't quite get, where `ImageSignature` is coming from. Could anyone please elaborate a bit on that? Thank you very much.
