### ISSUE TITLE
i want to delete cached file with  imageUrl

### ISSUE THREAD

**Issue by funset** [bumptech/glide#997]
i want to delete cached file or files  with  imageUrl

how can i to do?
thanks!

**Comment by TWiStErRob** [comment]
Sounds like a duplicate of #624.
Why do you want to delete it?

**Comment by funset** [comment]
when the image file  was changed of an imageUrl ,i want to update diskcache and refresh imageview

**Comment by TWiStErRob** [comment]
Yes, it's the same as the second question in #624 and also read #996.
