### ISSUE TITLE
Placeholder Image is not  circular when Using CropCircleTransformation and placeholder

### ISSUE THREAD

**Issue by chenshuhong** [bumptech/glide#999]
I use [CropCircleTransformation](https://github.com/wasabeef/glide-transformations/blob/master/transformations/src/main/java/jp/wasabeef/glide/transformations/CropCircleTransformation.java) to show circle imageview，but I find that the placeholder image is not circle ，how should I do with this .
`Glide.with(activity).load(path).diskCacheStrategy(DiskCacheStrategy.ALL).bitmapTransform(new GlideCircleTransform(activity)).placeholder(R.drawable.loading).into(imageView)`

**Comment by TWiStErRob** [comment]
The simplest fix: change the loading drawable to a circle.
The transformation is only applied to the loaded resource, see #317 for more info.
